### ISSUE TITLE
Reporting results of statistical tests features

### ISSUE THREAD

**Issue by dimleyk** [jasp-stats/jasp-issues#10]
Is it possible to add a reporting feature which will convert the statistical tables into words and meanings?
For instance, take the example shown here about ANCOVA : http://www.statisticshell.com/docs/ancova.pdf
You can take the reporting sections out of this file, and create a template that will use specific fields in JASP analysis and embed them in the textual report. If for instance, you request to add an effect size, this effect size will also appear in the textual report of the statistical test.
I THINK IT WILL BE GREAT!

**Comment by tomtomme** [comment]
@dimleyk 
I think this one would nowadays be done with AI assistance, thus closing as duplicate of the more detailed https://github.com/jasp-stats/jasp-issues/issues/2010
If you do not agree, feel free to reopen!
