### ISSUE TITLE
moderation analysis

### ISSUE THREAD

**Issue by areeq1** [jasp-stats/jasp-issues#1004]
There is a useful analysis that can be included in the software, moderation analysis. I know that is possible to run under 'regression analysis' (by selecting the two variables to constitute the interaction). However, SEM-based analysis provides more accurate and desirable results. This type of analysis is available in Jamovi
![Screen Shot 2020-10-12 at 2 37 06 pm](https://user-images.githubusercontent.com/68887104/95742307-76a4b480-0c98-11eb-93dc-4d52aa468249.jpg)

**Is your feature request related to a problem? Please describe.**
no

Thank you for the continuous updates of this amazing analytical software. I've already cited it in my research! Keep the good staff, developer team!
Abdullah

**Comment by juliuspf** [comment]
@areeq1, I apologize for the late reply. I believe your request is already possible for some time now in JASP, see here: https://jasp-stats.org/2020/03/12/mediation-and-moderation-analysis-in-jasp/
