### ISSUE TITLE
JASP not recognising data editor?

### ISSUE THREAD

**Issue by nahorp** [jasp-stats/jasp-issues#1005]
Hello,

I have associated Excel as my data editing application under the 'Preferences' section but for some reason JASP cannot recognise it?

![Screen Shot 2020-10-14 at 2 20 39 pm](https://user-images.githubusercontent.com/43395036/95940026-2315a080-0e29-11eb-9225-0de9590f44e5.png)

![Screen Shot 2020-10-14 at 2 20 57 pm](https://user-images.githubusercontent.com/43395036/95940035-2c067200-0e29-11eb-8f8f-48ef35a38629.png)

I am using JASP 0.13 on OS X 10.15.6

Thank you

**Comment by boutinb** [comment]
Strange... this warning should be displayed only when Use default spreadsheet editor is on.
Could you set this checkbox on en off again?

**Comment by nahorp** [comment]
Thanks for your reply @boutinb. I tried checking the box on and off again as well as reopening the program but neither works.

**Comment by boutinb** [comment]
Is your file an spss file?

**Comment by nahorp** [comment]
It is indeed

**Comment by boutinb** [comment]
You cannot open a SPSS file with Excel. You have first to export it as csv.

**Comment by boutinb** [comment]
Did it work? The error message means also that did not have SPSS installed on your machine.

**Comment by nahorp** [comment]
Worked like a charm! :) That is indeed what it was - didn't have SPSS on the machine. Thanks for your prompt help @boutinb, appreciate it.

**Comment by boutinb** [comment]
Good to hear!
