### ISSUE TITLE
Jasp shutting down when loading CSV

### ISSUE THREAD

**Issue by dhanson06** [jasp-stats/jasp-issues#1007]
* JASP version: 0.13.1.0-64bit

* OS name and version: Windows 10 Home
* Analysis: 
* Bug description:
* Expected behaviour:

#### Steps to reproduce:
1. Go to '...' Browse computer files to open
2. Click on '....' Click on CSV file
4. See error Jasp closes

**Comment by boutinb** [comment]
Can you send us your csv file (in zip format), by drag-and-drap the here in GitHub?

**Comment by boutinb** [comment]
Reopen this issue if it still occurs.

**Comment by dhanson06** [comment]
Thanks for following up, I found a page where others had this problem and it was related to the text lines being too long.  I shortened the text and it loaded right up.

I do have another question that maybe you can answer.  If I did an analysis on a dataset is it possible to keep the same settings for a different set of data? I do see that there is a sync feature, but it looks like I would have to update the current data to make that work where instead I want to use an alternate dataset that is formatted exactly the same.

Thanks.

Derek Hanson, PT, DPT
Assistant Professor
Internship Coordinator
Health Promotion & Wellness Program
SUNY-Farmingdale State College
________________________________

**Comment by boutinb** [comment]
Hi @dhanson06 When you use sync data, you don't have to change the file, you can select another file, and the same analyses with the same settings will be run with the new data.

**Comment by dhanson06** [comment]
Thank you so much for the reply.  I will try that.

Derek Hanson, PT, DPT
Assistant Professor
Internship Coordinator
Health Promotion & Wellness Program
SUNY-Farmingdale State College
________________________________

**Comment by dhanson06** [comment]
I have a question that I was hoping you could help with.

I did a k-means cluster analysis and separated a dataset into 4 clusters, and then created a column to display the cluster that each participant is in.  I am trying to find the mean score of the value that represents each cluster (it only displays the centroid value, and the mean that it displays looks like the mean of the centroid maybe), when I try to apply a pass-through filter to the dataset to only display one of the clusters so I can then view the descriptive tab to see the mean it doesn't allow it.  It seems that because I am eliminating many of the data by applying the passthrough, that it subsequently changes the cluster analysis results which then ends up having no more values from the passthrough.

Thanks and I hope you have a great holiday season.

Derek Hanson, PT, DPT
Assistant Professor
Internship Coordinator
Health Promotion & Wellness Program
SUNY-Farmingdale State College
________________________________

**Comment by boutinb** [comment]
@EJWagenmakers Can you have a look?

**Comment by EJWagenmakers** [comment]
Hmm maybe something for @vandenman  or @koenderks ?
