### ISSUE TITLE
JASP file corrupted and does not open anymore, lost work

### ISSUE THREAD

**Issue by Liesbeth-Tip** [jasp-stats/jasp-issues#1008]
I have lost several files because JASP did not save them, even when I had saved and renamed them.

Someone (working in programming) has taken a look at JASP files and said that the files were way too big and there could be some error in the code creating a never-ending loop which causes the files to be so big. 

I used quite large files with 200 participants, calculating descriptives, EFA's, CFA's and SEM in the same file over several variables. The file has many more variables I am not using in my analyses. It worked fine before but not in the last month or so.

The error message is on the JASP forum: https://forum.cogsci.nl/discussion/6508/files-that-i-saved-disappear-or-not-able-to-open#latest

**Comment by boutinb** [comment]
Hi @Liesbeth-Tip Could you describe a bit more precisely what happens: first on which system do you work (Windows/Mac/Linux), and which version? how big are the data files you load? Can you save the file with JASP without adding an analysis, or with which analysis it becomes too big? What happens exactly: you click on the save button, and then it hangs, it crashes, or it does nothing?

**Comment by Liesbeth-Tip** [comment]
Hi Bruno,
Thanks for your message! I have a Windowns 10 laptop, and am using JASP v0.13.0.
Files close as normal, but when I try to open them it gives that error message that something is missing. It doesn;t happen always, some times it keeps corrupting the files that way. I then go back to a previous version and work from that, and in some cases it works fine and manages to save the file as normal, but it could also be that the next time I save it it doesn;t work anymore. It doesn;t hang, or crash, but it does take a long time (couple of minutes at least) to load, or to save a file.
I have a file of N=200 and an doing doing descriotives, CFA's, and SEM analyses, I have 4 measurement models/latent variables with two of thsoe having 20 items, and the others 6 and 10 items maximum.
It can also happen that some time during working on the analyses, the screen on the right goes blank, I then have to save/close it and reopen for the analyses to become visible again. In task manager, the current file I'm working on is using 1050MB of memory/processing. A file can be for example 1200.000 KB but also 2500.000KB.
Hope that helps!
Best wishes,

Liesbeth




________________________________
Van: bruno boutin <notifications@github.com>
Verzonden: vrijdag 23 oktober 2020 10:40
Aan: jasp-stats/jasp-issues <jasp-issues@noreply.github.com>
CC: Liesbeth-Tip <liesbethtip@hotmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [jasp-stats/jasp-issues] JASP file corrupted and does not open anymore, lost work (#1008)


Hi @Liesbeth-Tip<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLiesbeth-Tip&data=04%7C01%7C%7C934859f880034b17b84f08d8772f5627%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637390392471668757%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SN4YDJ%2B59CaS7q1ygqiFjYyiHtZBAHgrFskWBqCq4Ok%3D&reserved=0> Could you describe a bit more precisely what happens: first on which system do you work (Windows/Mac/Linux), and which version? how big are the data files you load? Can you save the file with JASP without adding an analysis, or with which analysis it becomes too big? What happens exactly: you click on the save button, and then it hangs, it crashes, or it does nothing?

**Comment by boutinb** [comment]
Hi @Liesbeth-Tip More than 2 GB is indeed quite big... Did you try to use a 'stronger PC' than your laptop? Would it be also possible to get this data (zipped)?

**Comment by Liesbeth-Tip** [comment]
Hi, my laptop is only a few months old, I tried on my old laptop but the same thing is happening there. I'm afraid I won;t be able to share my data for confidentiality reasons, but I can maybe see if I can run a simulation of the data though I haven't done that before, and then try if I can corrupt that in the same way.
I'll give it a go over the weekend.
Best wishes,
Liesbeth

________________________________
Van: bruno boutin <notifications@github.com>
Verzonden: vrijdag 23 oktober 2020 13:04
Aan: jasp-stats/jasp-issues <jasp-issues@noreply.github.com>
CC: Liesbeth-Tip <liesbethtip@hotmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [jasp-stats/jasp-issues] JASP file corrupted and does not open anymore, lost work (#1008)


Hi @Liesbeth-Tip<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLiesbeth-Tip&data=04%7C01%7C%7Cf5876ae4f0a14673835a08d87743774a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637390478927056416%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xYNJ6GUzwU4ENdIbkWsPJwhfgv03%2BS%2F4UB7ckKsG9ww%3D&reserved=0> More than 2 GB is indeed quite big... Did you try to use a 'stronger PC' than your laptop? Would it be also possible to get this data (zipped)?
