### ISSUE TITLE
Descriptives does not have the drop down menu options

### ISSUE THREAD

**Issue by LiekeTen** [jasp-stats/jasp-issues#1009]
* JASP version: 0.14
* OS name and version: Windows 10 Pro
* Analysis: Descriptives
* Bug description: I want to run a reliability analysis, but my descriptives button does not have an arrow to open the drop down menu to select this options
* Expected behaviour: ?
![InkedScreenshot_problem_LI](https://user-images.githubusercontent.com/73077774/96377695-1b613f00-113c-11eb-96fd-851d58363276.jpg)

**Comment by vandenman** [comment]
Hi @LiekeTen, 

We moved the reliability analyses to its own module. To open it, click on the `+` in the top right corner of the screen:

![image](https://user-images.githubusercontent.com/21319932/96412582-a7ca3b00-11ea-11eb-977e-15ce6de29765.png)

Select `Reliability`. Once the Reliability module is selected this icon appears in the ribbon with these two analyses:

![image](https://user-images.githubusercontent.com/21319932/96412681-c6c8cd00-11ea-11eb-8bfd-dc5f3e38dacd.png)

Let me know if that solves the problem!
