### ISSUE TITLE
Export/Save function for factor scores in EFA and PCA

### ISSUE THREAD

**Issue by annamwolf** [jasp-stats/jasp-issues#101]
Having done an exploratory factor analysis, many reseachers want to continue their analyses (t-test, ANOVA etc.) with the factor scores that can be calculated from the EFA analysis. Afaik, most people use the Thurstone/regression approach, but it would be optimal if you could implement a choice (https://www.personality-project.org/r/html/factor.scores.html).
* Enhancement: Adds the missing feature to purposefully use the results from an EFA and not only see which items create a factor. 
* Purpose: Enables people to continue a statistical analysis with the factor scores as, for example, a dependent variable. 
Thanks a lot!

**Comment by tkasci** [comment]
I would also be happy to see this feature in future releases.

**Comment by EJWagenmakers** [comment]
This should be easier to implement now that we have already included similar functionality for, say, the Machine Learning module.

**Comment by patc3-phd** [comment]
FWIW I too would like it.. I resorted to reproducing the EFA in R (using psych::fa) and requesting factor scores (and comparing the outputs of JASP and R to make sure I was reproducing it correctly)

If I can help to add this feature please let me know how

**Comment by TZaks** [comment]
Is there an update on this? I am also in the position of having used JASP to estimate the factors, but need the scores for further analyses.

**Comment by EJWagenmakers** [comment]
@vankesteren informed me the code does exist:
EFA: https://github.com/jasp-stats/jaspFactor/blob/389a04f7694b535774fd36b6eacad765d62e4a00/R/exploratoryfactoranalysis.R#L578
PCA: https://github.com/jasp-stats/jaspFactor/blob/389a04f7694b535774fd36b6eacad765d62e4a00/R/principalcomponentanalysis.R#L469

Will it be available in the next version, @JorisGoosen @vandenman

**Comment by vandenman** [comment]
The code exists but it's currently not possible to export more than one column to the data set. As a temporary workaround, we could add a button that exports the factor scores as a csv or so.

**Comment by TZaks** [comment]
That would be very helpful, if possible. Do we know the time frame?

Best,
Tara

**Comment by MCube78** [comment]
Hi Everyone, it's been over 5 years since the original request. I hate asking, but I still don't see it in the GUI (am I missing it?). Any workaround yet (like exporting to csv or txt)?

**Comment by JorisGoosen** [comment]
Currently I am rewriting the data-backend, which will allow analyses to easily add columns to the dataset.
Seeing as how the code is already there it should be easy to take those changes by Erik-Jan and make them functional.

**Comment by JorisGoosen** [comment]
Hehe, im working on it right now ;)

**Comment by micahgallen** [comment]
You guys rule. I've converted many people to JASP and I won't stop any time soon! Love the work you all do. Thanks!!!

**Comment by patc3** [comment]
> You guys rule. I've converted many people to JASP and I won't stop any time soon! Love the work you all do. Thanks!!!

hahaha me too I've converted a ton of people (profs and students alike)

**Comment by tomtomme** [comment]
related: https://github.com/jasp-stats/jasp-issues/issues/2265

**Comment by tomtomme** [comment]
@annamwolf 
This is now actively being worked on. However it will likely not make it into 0.19 which will be released in some weeks. 
But 0.20 might ship this important feature.

**Comment by tomtomme** [comment]
@juliuspfadt 
Nice!
Will this be in 0.19 or 0.20 now?

**Comment by koenderks** [comment]
It's in the codebase so it will probably be shipped in 0.19.

**Comment by RichardBentall** [comment]
I have just downloaded 0.19 and the release notes say that it has an option to save factor scores but I can't see it for either EFA or CFA?

**Comment by patc3** [comment]
@RichardBentall for example in exploratory factor analysis (there is the same option in principal components analysis):

![image](https://github.com/user-attachments/assets/88b66535-35d4-466d-ab9b-ea8f86ac40a5)

![image](https://github.com/user-attachments/assets/c048ba18-5aae-4291-8ff5-3be8870115e8)

I don't see it in CFA either, but that's very different than estimating scores in EFA or PCA (if it even makes sense in the context of CFA or SEM more generally)

**Comment by RichardBentall** [comment]
Hi Patrick,

Thanks for this. I don't know why I didn't see this when I was
familiarising myself with JASP last night. Super helpful.

Richard


Richard Bentall PhD FBA,
Professor of Clinical Psychology,
Clinical Psychology Unit,
Department of Psychology,
Cathedral Court,
1 Vicar Lane,
S1 2LT

Tel: 0114 222 6530
Mob: 07470 229121

*Please note that I work for the University of Sheffield on Mondays,
Tuesdays and Friday mornings. I may respond to emails at other times but
this will depend on priorities.*

**Comment by RichardBentall** [comment]
Much appreciated. I don't know why I didn't see this when I was familiarising myself with JASP last night. Super helpful, thanks.

**Comment by TZaks** [comment]
Amazing news! 🥳

**Comment by elias-lang2434** [comment]
Dear all,

I am new to JASP and have encountered a problem related to the discussion above. I have done an EFA based on polychoric correlations and would like to add the factor scores as computed columns. However, when doing this I receive the following message "This analysis terminated unexpectedly. Error in seq_len(ncol(scores)): argument must be coercible to non-negative integer".

The data is ordinal 0-4, and there are no missing values.

I asked a colleague about this who tried replicating the analysis on a different data set and he received the same error message, again with no missing data in the set.

Can anyone help with this issue?

All best,
Elias

<img width="958" height="679" alt="Image" src="https://github.com/user-attachments/assets/cfd48a27-bfb3-47bb-b3c9-1b06c2019994" />
