### ISSUE TITLE
Confidence intervals in custom contrasts

### ISSUE THREAD

**Issue by wmotte** [jasp-stats/jasp-issues#1012]
* Enhancement: Custom contrasts in the (generalized) linear mixed models provide an Estimate, SE, and df output, but 95% (or a differently set) confidence intervals would be very useful as well.
* Purpose: Group differences determined with custom contrasts are often reported in scientific papers with the estimate and the corresponding 95% confidence interval. Currently, this is not provided in the custom contrasts of the frequentist models. I am aware that the emmeans lack this output as well. Perhaps 95% CIs could be determined with bootstrapping or an approximation based on the Estimate, SE, and df.
* Use-case: Clinical reports on group differences require 95% confidence intervals rather than SE only. This feature would help biomedical scholars to determine custom contrast without the need to write lme4 post-hoc scripts.

**Is your feature request related to a problem? Please describe.**
A useful output feature in the (generalized) linear mixed model modules is not yet available.

**Describe the solution you'd like**
Add confidence intervals to the custom contrast results. Based on bootstrapping or custom calculation.

**Describe alternatives you've considered**
The Bayesian (generalized) linear mixed models provide the credibility intervals. But clinicians are still very much favoring frequentist approaches.

Thanks! Wim

**Comment by boutinb** [comment]
@EJWagenmakers What do you think of this request? And who could implement this?

**Comment by EJWagenmakers** [comment]
Seems reasonable. Maybe Henrik and @FBartos could take a look. I am not sure what the best way is to bootstrap when the data is hierarchical -- bootstrap on all levels, starting with the highest one? I believe there were some issues but I cannot recover the relevant literature.

**Comment by FBartos** [comment]
I can't think of a reason why the CI would need to be bootstrapped instead of calculating them based on the estimate and SE (+ df). I will check with Henrik but I think that it shouldn't be a problem to add this.
