### ISSUE TITLE
McNemar Test

### ISSUE THREAD

**Issue by peterubuane** [jasp-stats/jasp-issues#1014]
* Enhancement: Inclusion of McNemar test, Bootstrapping and Data Manipulation capabilities 
* Purpose: Inability to manipulate data is a great limitation unique to Jasp as far as I know.
* Use-case:

**Is your feature request related to a problem? Please describe.** 

**Describe the solution you'd like**
 
I couldn't run McNemar on my dataset. So I had to resort to jamovi

**Comment by boutinb** [comment]
Hi @peterubuane We are thinking of adding some data editing features, but what you can do is to edit your data file with your preferred editor, and JASP should automatically synchronize your changes each time you save them.
For the McNemar test, maybe can @EJWagenmakers says more about it.

**Comment by EJWagenmakers** [comment]
Yes, we need this, and related features as well -- I have indicated this internally to the team already, so it's on the agenda.

**Comment by peterubuane** [comment]
Thank you for your prompt reply. JASP is so unique; although it doesn't yet
have all these features yet, I find its interphase uniquely attractive and
extremely user-friendly. God bless you all for the great work for humanity.

Thank you.


Dr Peter Odion Ubuane, MBChB, FWACPaed
Consultant Paediatrician (Neonatal Unit)
Institute of Maternal & Child Health/Department of Paediatrics
Lagos State University Teaching Hospital
1-5 Oba Akinjobi Way
Ikeja, Lagos, Nigeria
+234-8085645675

**Comment by tomtomme** [comment]
@peterubuane 
Data edit mode is done! Bootstrapping also for many scenarios.
McNemar however is still on the ToDo list, sorry. I will close this, since McNemar etc. is tracked here: https://github.com/jasp-stats/jasp-issues/issues/1445

**Comment by peterubuane** [comment]
I am unable to download and install jasp; the download stops before
completion stating the i 'need authorisation.' How do I resolve this?
Thank you.

*Peter Odion **Ubuane*, *MBChB, Cert.Paed.Bioethics (Kansas), FWACPaed*
*Consultant Neonatologist*
Institute of Maternal & Child Health/Dept of Paediatrics
Lagos State University Teaching Hospital (LASUTH)

*A**ssociate Lecturer** (Paediatric Respiratory Medicine/Critical Care)*
*Lagos State University College of Medicine*
*1-5 Oba Akinjobi Way, GRA,*
*Ikeja, Lagos, Nigeria*
*234-8085645675*



".*..freely you have received, freely give..." (Mat. 10:8, NKJV)*

**Comment by tomtomme** [comment]
@peterubuane 
please open a new issue and at least post a screenshot, your Operating System +version and where you try to download jasp (ms store or jasp-stats.org)

**Comment by peterubuane** [comment]
Dear Peter,

That is strange. Have you tried our pre-installed zip file? (if you
are on Windows).
In general, the best way to get help is to post the issue on our
GitHub page, and you'll be
in direct contact with the programming team (for details see
https://jasp-stats.org/2018/03/29/request-feature-report-bug-jasp/)

Cheers,
E.J.

============================
JASP: A Fresh Way to Do Statistics
Free download at jasp-stats.org
============================

**Comment by tomtomme** [comment]
@peterubuane 
McNemar is now available in the beta version of the frequencies module, available in the module library.

Cochrans test also known as Cochrans Q is tracked here https://github.com/jasp-stats/jasp-issues/issues/1445
