### ISSUE TITLE
Error in sprintf .... invalid format '%i'

### ISSUE THREAD

**Issue by christofnaegele** [jasp-stats/jasp-issues#1017]
* JASP version: 0.14
* OS name and version: macOS 10.15.7 (19H2)
* Analysis: Error message, I cant't get over it
* Bug description:

This analysis terminated unexpectedly.
Error in sprintf(gettext(fmt, domain = domain), ...): invalid format '%i'; use format %s for character objects
Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])
doTryCatch(return(expr), name, parentenv, handler)
withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)
analysis(jaspResults = jaspResults, dataset = dataset, options = options)
.semRSquaredTable(semContainer, options, dataset, ready, position = 4)
semRSquaredTable$addColumnInfo(name = paste0('R2', i), title = gettextf('Group %i', nm[i]), overtitle = gettext('R²'), type = 'number')
private$jaspObject$addColumnInfoHelper(name, title, type, format, combine, overtitle)
gettextf('Group %i', nm[i])
sprintf(gettext(fmt, domain = domain), ...)

* Expected behaviour:
It is a simple SEM model with gender (f/m) as the grouping variable. 
The model runs without the grouping variable, my expectation is that it should also run with gender as the grouping variable. 

I would be happy to send you the lavaan syntax and data via email.

**Comment by Kucharssim** [comment]
Dear @christofnaegele,

thank you for the bug report. It's great that you are able to share the data - can you please send it to s.kucharsky@uva.nl? I would have a closer look at the issue.

Simon

**Comment by TimKDJ** [comment]
@Kucharssim the parameter type in the `gettextf()` is wrong:
https://github.com/jasp-stats/jasp-desktop/blob/b816e1224fc50abc1ad7cefdcaa318389e219cf2/JASP-Engine/JASP/R/semsimple.R#L489-L501
the `%i` should be a `%s`, as `names()` returns a character:
```
> x <- 1
> names(x) <- 2
> x
2 
1 
> names(x)
[1] "2"
```

Would be good to fix this for 0.14.1

**Comment by TimKDJ** [comment]
@christofnaegele: this should be fixed in 0.14.1 which we'll release in the coming weeks.
