### ISSUE TITLE
Can't use the distribution module without loading data

### ISSUE THREAD

**Issue by mservantufc** [jasp-stats/jasp-issues#1018]
* JASP version: 0.13

* OS name and version: Windows 10

For teaching purposes, I would like to be able to use the distribution module without having to load data. Moreover, there seems to be a bug with the "Generate and display data" submodule". If I load a dataset with say, 18 observations, I can draw more than 18 samples from the distribution! Am I doing something wrong?

**Comment by boutinb** [comment]
Hi @mservantufc We have a new version 0.14, and in this one, you can open a Distribution analysis without data.

**Comment by mservantufc** [comment]
Hi @boutinb  Sure but it is not possible to simulate data (via Generate and Display data)without opening a datafile. More importantly, it is not possible to simulate a number of datapoints > to the number of datapoints of variables in the opened datafile.

**Comment by boutinb** [comment]
@FBartos Could you answer this issue?

**Comment by FBartos** [comment]
I think that this might be more relevant for @Kucharssim

**Comment by Kucharssim** [comment]
Hello @mservantufc,

thank you for the feedback! This is not a bug per se, but a limitation of the JASP editor at this time. The current state is only temporary, we plan to allow drawing more data points than rows in the data and/or creating variables from scratch without a data set opened. But it's not implemented yet - hence, Distributions module is limited by the size of the current data set.

@JorisGoosen could you move the following issue a bit up in your priority list, please? https://github.com/jasp-stats/INTERNAL-jasp/issues/170. I am afraid we cannot solve this without it and many users are complaining about this every release...

**Comment by juliuspf** [comment]
@mservantufc, I apologize for the late reply. Could you check your issues with latest version of JASP? I know that at least using the module without data is possible.

**Comment by JorisGoosen** [comment]
Well... Why does the simulated data have to go into the dataset anyway?
It could just go into the state right?

And in any case, this would be easily added  in data-editing. But having analyses change the size (rowcount) of the dataset seems like a bad idea.

**Comment by Kucharssim** [comment]
> Well... Why does the simulated data have to go into the dataset anyway?
It could just go into the state right?

It could, but then we'll get feature requests titled "how can I export the simulated data from distributions into my data set"... Think we discussed this already.

Note that this does not necessarily need to be made such that the analysis changes the row count of the dataset, but it could be done like you commented here: https://github.com/jasp-stats/INTERNAL-jasp/issues/170#issue-425888341 - that is, allow users to specify an "empty" dataset with a set row count and let the analysis populate the columns.

**Comment by JorisGoosen** [comment]
Yeah ok, so this is already possible in the data-editing version.
Ill push that to `development` might as well
