### ISSUE TITLE
Confirmatory Factor Analysis - Model plot cannot be adjusted and labels are unreadable

### ISSUE THREAD

**Issue by Fzouu** [jasp-stats/jasp-issues#1019]
* JASP version: Free 

* OS name and version: Windows 10
* Analysis: Correlation
* Bug description: one of my plots is not clear enough (numbers are in a big font and on top of each other)
* Expected behaviour: readable numbers in plots

**Comment by boutinb** [comment]
Hi @Fzouu Can you give more details about your problem, a screenshot for example? And which version of JASP do you use?

**Comment by Fzouu** [comment]
![Capture (1)](https://user-images.githubusercontent.com/73284302/96998498-d4a48800-1533-11eb-978e-425dbe43c75b.PNG)

**Comment by boutinb** [comment]
Hi @Fzouu You should be able to resize the plot. But maybe @vandenman can give more hints.

**Comment by Fzouu** [comment]
Hi @boutinb,
Even if I resize it, it is still the same.

**Comment by vandenman** [comment]
@Fzouu Can you confirm that this plot was made with Confirmatory Factor Analysis, not correlation?

@boutinb this plot is not made with ggplot so there is no workaround for this at the moment.

**Comment by Fzouu** [comment]
Hi,
it was made by Confirmatory Factor Analysis

**Comment by juliuspf** [comment]
related to https://github.com/jasp-stats/jasp-issues/issues/1145

**Comment by tomtomme** [comment]
@Fzouu 
You can export this plot to pptx via the "save as" button. In Powerpoint then you can move any number or object. Does this help?
