### ISSUE TITLE
JASP crashed

### ISSUE THREAD

**Issue by jamal-ruz** [jasp-stats/jasp-issues#1020]
* JASP version: 0.14
* OS name and version: Windows 10 (10.0)

* Analysis: 
* Bug description:
* Expected behaviour:

#### Steps to reproduce:

-----------------------------------------------------------------------

### Debug information:
**Engine # 0** process *crashed* and it's state is *initializing*.
**Engine # 1** process *crashed* and it's state is *initializing*.
**Engine # 2** process *crashed* and it's state is *initializing*.
**Engine # 3** process *crashed* and it's state is *initializing*.

[Commit used](https://github.com/jasp-stats/jasp-desktop/commit/e93e15cbaf55662b26b323b8ce088b0414ef6e98)

**Comment by boutinb** [comment]
@jamal-ruz Can you give more information about this crash? When does it happen exactly?
