### ISSUE TITLE
Group selector within Descriptive Statistics to prepare for (repeated-measures) modeling

### ISSUE THREAD

**Issue by wmotte** [jasp-stats/jasp-issues#1021]
* Enhancement: Add 'group' entry to the Descriptive Statistics.
* Purpose: To prepare the data for repeated-measures ANOVA/linear mixed models the outcome (y-axis) is ideally plotted against time (x-axis) with the groups separated as individual boxplots sets (in distinct colors). 

**Is your feature request related to a problem? Please describe.**
The inspection of temporal data with two or more groups is currently not possible with Descriptive Statistics. Whereas the data for repeated-measures ANOVA/linear mixed models typically have two variables (e.g. group and time). Currently, there is a single 'split' entry available. Either for the 'group' or 'time' variable.

**Describe the solution you'd like**
Add - next to the 'split' entry also a 'group' entry. 

**Describe alternatives you've considered**
I am currently plotting temporal data with two or more groups in R with ggplot2.

**Additional context**
The plots within the linear mixed model output do show a 'group'/'colour' in the output, however, this is for the model's results (and not for the raw data). Ideally, you want to inspect the data first (i.e. to find out that some time points have too few data points) before fitting a model.

**Comment by boutinb** [comment]
@EJWagenmakers What do you think?

**Comment by EJWagenmakers** [comment]
Maybe this will be covered by the time series plots that we are developing. Wim, can you send an example of the plot you'd like to see?

**Comment by wmotte** [comment]
Attached an example plot (with data and script) of a repeated-measures
dataset. It basically has the same layout as the plot results in the LME
output.

**Comment by vandenman** [comment]
@wmotte Unfortunately, GitHub doesn't show attachments or figures in email replies. Could you use the website to post the example? If you want to add the script and data you'll have them as a zip file (or email it to <d.vandenbergh at jasp-stats.org> and I'll do that for you).

**Comment by wmotte** [comment]
Sorry. Second try.
![JASP_example_plot_repeated-measures](https://user-images.githubusercontent.com/25975935/97342446-83273080-1886-11eb-8cd9-548f0e66789e.png)


[Data__and_script.zip](https://github.com/jasp-stats/jasp-issues/files/5447172/Data__and_script.zip)

**Comment by tomtomme** [comment]
@wmotte 
Have you tried the Visual Modeling Module => Flexplot within JASP. It should do this nicely, if you have time-data in long format. For wide format data we are still missing such a plot. But wide-long conversion is in the works, I think.

**Comment by wmotte** [comment]
This is just what I needed. Long-format is default. Thanks!
