### ISSUE TITLE
ANOVA table missing data in Dutch version of regression analysis

### ISSUE THREAD

**Issue by idegroote** [jasp-stats/jasp-issues#1023]
* JASP version: 
0.13.1
* OS name and version: 
Windows 10
* Analysis: 
Regression
* Bug description: 
The data from the ANOVA (model stats) is missing in the regression output. This only occurs when the language is set to Dutch. When it is set back to English, the output is visible. 
* Expected behaviour:
Run a regression when language is set to Dutch. tick model fit. The anova table appears but is empty. 
Set the language of the program to English and the table populates with the ANOVA values.

**Comment by boutinb** [comment]
Hi @idegroote we have a new version 0.14. And in this version I don't see this problem. Can you try?

**Comment by idegroote** [comment]
Hello Bruno,

I just tried it and it was still the same problem.

Isabelle

[cid:image002.jpg@01D6AC80.344EF730]


Van: bruno boutin <notifications@github.com>
Verzonden: 27 October 2020 16:28
Aan: jasp-stats/jasp-issues <jasp-issues@noreply.github.com>
CC: Isabelle De Groote <Isabelle.DeGroote@UGent.be>; Mention <mention@noreply.github.com>
Onderwerp: Re: [jasp-stats/jasp-issues] ANOVA table missing data in Dutch version of regression analysis (#1023)


Hi @idegroote<https://github.com/idegroote> we have a new version 0.14. And in this version I don't see this problem. Can you try?

**Comment by boutinb** [comment]
Hi @idegroote  Can you use the GitHub website to insert your image? I cannot see it otherwise.

**Comment by idegroote** [comment]
- 
![Prt sc](https://user-images.githubusercontent.com/73485191/97440401-b241ae80-1927-11eb-8d5b-ed0e67716455.png)

**Comment by boutinb** [comment]
This will be solved in the next minor release (0.14.1), over 2 weeks.
