### ISSUE TITLE
Bayesian correlation scaling of scatterplot fails sometimes

### ISSUE THREAD

**Issue by JohnnyDoorn** [jasp-stats/jasp-issues#1024]
* JASP version: 0.14 (https://github.com/jasp-stats/jasp-desktop/commit/3aa14acf2bd119281ee771e30b877e08a3016202)
* OS name and version: Ubuntu 20.04
* Analysis: Bayesian correlation
* Bug description: axis labels are not updated
* Expected behaviour: axis labels should be updated

#### Steps to reproduce:
see attached jasp file (change extension to jasp instead of zip), when I plot VIQ to mri count (which are very large values), the plot labels for both variables are incorrectly 1:20 
I have to say that I cannot reproduce this reliably, it just happens at some point trying different variables (but I think the mri count variable is suspect). 

[plotscale.zip](https://github.com/jasp-stats/jasp-issues/files/5440399/plotscale.zip)

**Comment by AlexanderLyNL** [comment]
Might be related to the too many devices bug

https://github.com/jasp-stats/jasp-issues/issues/1025

There was another issue that was similar to this, but on a different OS, but I can't find it at the moment.

**Comment by JohnnyDoorn** [comment]
For me this is now fixed
