### ISSUE TITLE
Bayesian Correlation - "Too many open devices"

### ISSUE THREAD

**Issue by JohnnyDoorn** [jasp-stats/jasp-issues#1025]
JASP version: 0.14 (jasp-stats/jasp-desktop@3aa14ac)
OS name and version: Ubuntu 20.04
Analysis: Bayesian correlation
Bug description: when trying to make a plot, I get the error of "too many open devices". I think this refers to graphic devices, but I would think these would be closed again. I could not reproduce this in other analyses, but could be mistaken.
Expected behaviour: clear the cache, especially when you choose "remove all" 

Steps to reproduce: create many plots by having different permutations of selected variables

see attached jasp file (change extension to jasp instead of zip)
[tooManyOpenDevices.zip](https://github.com/jasp-stats/jasp-issues/files/5440691/tooManyOpenDevices.zip)

**Comment by vandenman** [comment]
I can't replicate this on Ubuntu 18.04 with the current development (https://github.com/jasp-stats/jasp-desktop/tree/ba369e9eb19bc1ca800840633d6dd9c17f690cc2) or with the flatpak release. Which R version do you use?

**Comment by JohnnyDoorn** [comment]
This is on 3.6.3, should I update to 4?

**Comment by vandenman** [comment]
This was probably fixed in https://github.com/jasp-stats/jaspGraphs/pull/31. If I refresh the file now, everything just works. @JohnnyDoorn Can you confirm this?

**Comment by JohnnyDoorn** [comment]
@vandenman Yes, everything now works for me.

**Comment by JohnnyDoorn** [comment]
Confirmed!
