### ISSUE TITLE
Reliability: error when there are more variables than observations

### ISSUE THREAD

**Issue by djdekker** [jasp-stats/jasp-issues#1026]
* JASP version: 0.14
* OS name and version: macOS 11.0 beta
* Analysis: Reliability (frequentist)
* Bug description: McDonald's ω and Cronbach's α are not calculated when the number of variables equals or exceeds the number of observations
* Expected behaviour: McDonald's ω and Cronbach's α are being calculated

#### Steps to reproduce:
1. Open the attached JASP file.
2. All 28 variables are included in the reliability analysis. There are 27 observations. See error.
3. Note that JASP will calculate reliability after removing any two variables from the analysis.

Note: I calculated Cronbach's α for this data set both in SPSS and in Excel with all variables any without problem.

[reliability_problem.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/5446326/reliability_problem.jasp.zip)

**Comment by juliuspf** [comment]
Thanks for reporting this issue. This is unfortunate behaviour that is caused by coefficients lambda2 and lambda6. These coefficients require the covariance matrix to be invertible, which it is not. Unfortunately all coefficients are computed together, meaning one coefficient will break it for the whole bunch. This will be solved by the planned restructuring (https://github.com/jasp-stats/INTERNAL-jasp/issues/1073).

**Comment by mytnaprofile** [comment]
JASP version: 0.16.3
OS name and version: win 10
Analysis: Exploratory Factor Analysis
Error message: data not valid: there are more variables than observations 

Hi 

I'm new to JASP. I am trying to run exploratory factor analysis, but an error message appears as above. I read the previous thread discussion (#1026 #961), but I think it is more based on the software bug error than statistical error.

I have 300 items to analyse. I try to minimize the total items to run below 12, and it works. but if it is more than this, the message will appear.

Is there any setting I need to look at to ensure that the number of observations/datasets is more than the variables I need to analyse? Or is there any limit on the number of variables I could analyse?

thank you

**Comment by juliuspf** [comment]
Hi @mytnaprofile, thanks for reporting, is it possible you open a new issue for this? https://github.com/jasp-stats/jasp-issues/issues/new?assignees=&labels=&template=bug-report.yml&title=%5BBug%5D%3A+
