### ISSUE TITLE
Switch Dot and Comma in the results for german locals

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#1031]
When I change the language in JASP 0.14 to german the numbers in the results pane are still using a dot instead of a comma to seperate decimal places. See example screenshots from the descriptive module.
<img width="196" alt="Screenshot_20201030_093810" src="https://user-images.githubusercontent.com/4428185/97678519-3a44c700-1a94-11eb-84a3-eefa4bf33d27.png">

**Comment by boutinb** [comment]
Hi @tomtomme You can change the german translation by using WebLate: just make an account and select the JASP project. If you do that this week, it will be probably added in the next minor release (0.14.1) (over ~2 weeks)

**Comment by tomtomme** [comment]
Thats great. I will do that. 
But how about the dot-comma-issue? I guess that it is not possible to change that in weblate, too.

**Comment by boutinb** [comment]
Yes that's true, the dot-comma issue does not depend on the translation. It is now always a dot notation for decimals. We could it make indeed more locale specific (or adding a preference setting). I will discuss it with my colleagues.

**Comment by JorisGoosen** [comment]
Very related to: #39

**Comment by tomtomme** [comment]
not yet in JASP 0.15 beta 20.9.2021 (flatpak linux build)

**Comment by JorisGoosen** [comment]
Aah no, we totally forgot about this, but it is too late for this release.

**Comment by EJWagenmakers** [comment]
Do we even want to do this though? Might just be confusing

**Comment by JorisGoosen** [comment]
It *is* confusing but sadly enough this is how things are. German (and dutch) excel also do this.

**Comment by tomtomme** [comment]
It gets even more confusing if you look at this map closely. Dot and Comma are not the only guys in town. 
<img width="1351" alt="grafik" src="https://user-images.githubusercontent.com/4428185/134175839-f2379258-da50-4928-9176-f8220181379c.png">

**Comment by JorisGoosen** [comment]
Haha, yeah definitely something to get implemented then!

Funny the middle-east decided to go with their own solution ^^

**Comment by amirmasoudabdol** [comment]
> Funny the middle-east decided to go with their own solution ^^

Considering the evolution of the numeral system (from Hindu-Arabic), it's funny that the rest of the world decided to go with their different solutions! 😅😉

Jokes aside, Momayyez is technically a different name for comma, and as long as we support both Point and Comma systems, we should be fine. The difference between Momayyez and Comma is very minimal, so basically, the entire world is actually using two system.

In addition, most analytics in these countries are done using Western softwares, Excel, etc., and they are not that specific either, and people are used to them anyway. No one expect us to support actual Momayyez if you ask me! They'll even be confused if they see it.

**Comment by EJWagenmakers** [comment]
It will be less confusing if we implement the comma-period convention as an option in the general preferences.

**Comment by amirmasoudabdol** [comment]
There are a lot of utilities in [QML](https://doc.qt.io/qt-5/qml-qtqml-locale.html), and [JS](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString) (even R) to do this properly. If we decide to do this, it needs to be consistence, and propagate to analysis controls, etc. As we are offering more languages, we need to start thinking about these more systematically. I expect more of [these kind of issues](https://github.com/jasp-stats/jasp-issues/issues/39) pop up as we release the 0.15.

**Comment by JorisGoosen** [comment]
Well, we should rely on the system for sure.

It is just that someone long ago decided that dots are the way to go internally and we've never bothered to change because the app was in english anyway.

https://doc.qt.io/qt-5/qlocale.html#decimalPoint

**Comment by tomtomme** [comment]
> It will be less confusing if we implement the comma-period convention as an option in the general preferences.

Sounds good to me :) 
Maybe JASP could detect the used locale of the operating system on installation and switch language, dot and comma depending on the settings of the operating system. This is how most software handles it as far as I know. 
@amirmasoudabdol I would not go for Momayyez either for the same reasons you named. We would be the only software around implementing it.

**Comment by tomtomme** [comment]
Still valid for 0.16.3

**Comment by tomtomme** [comment]
Still valid for 0.16.4

**Comment by tomtomme** [comment]
still valid for 0.17 and still a big problem for my students. Quite some time they see a number like 100.000 and think of it as the very very big number, instead of 100.

**Comment by EJWagenmakers** [comment]
I reiterate the suggestion to have the user specify this setting in the general preferences. (a Spanish user requested this as well)
Would this be much work to implement, @JorisGoosen @boutinb @RensDofferhoff ?

**Comment by EJWagenmakers** [comment]
I am not sure whether this is helpful: https://www.tutorialspoint.com/how-to-set-comma-as-decimal-separator-in-r
@vandenman

**Comment by Alexpollet** [comment]
To resolve the problem of decimal, it will be not possible to implement in the configuration part of the program the option of American, European or other type of decimal to avoid confusion and permit that any user can choose what he prefers to use?

**Comment by JorisGoosen** [comment]
I think the best idea is probably to use the default option from whatever language the user has selected.
And add an override for when a user just really wants one of the two.

This is definitely not forgotten and can hopefully be implemented soon.

**Comment by shun2wang** [comment]
I think tying it to language complicates things because there could be many cases here. My suggestion is to focus only on the formatting part? divide into different parts then customize the display style (decimal point, thousandths, etc.) by the user, and provide a small preview in QML, for example this can be changed from JS in JASP result, in javascript [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat)  we can:

`formatter.formatToParts(number);`

```
[
  { type: "integer", value: "3" },
  { type: "group", value: "." },
  { type: "integer", value: "500" },
  { type: "decimal", value: "," },
  { type: "fraction", value: "00" },
  { type: "literal", value: " " },
  { type: "currency", value: "€" },
];
```

**Comment by JorisGoosen** [comment]
It might also be good to rewrite that formatting part in js, because it currently is kind of unreadable and overcomplicated.

However, I agree with @shun2wang that not tying it to language is a good idea

**Comment by tomtomme** [comment]
still valid for 0.18.1

**Comment by tomtomme** [comment]
This and related stuff is tracked here:
https://github.com/jasp-stats/jasp-issues/issues/39

So I am closing this as a duplicate.
