### ISSUE TITLE
This analysis terminated unexpectedly 

### ISSUE THREAD

**Issue by wagner12345** [jasp-stats/jasp-issues#1032]
* JASP version:

* OS name and version: macOS Sierra 10.12.6
* Analysis: 
* Bug description: error in (structure(function (...) : Column I_AGRE not found!
* Expected behaviour:

**Comment by boutinb** [comment]
Hi @wagner12345 Can you give more information: which analysis, which settings, etc?

**Comment by wagner12345** [comment]
Hi! Yes! I was using the descriptive statistics to create plots and tables.
Is that what you meant?

**Comment by boutinb** [comment]
Could you give your JASP file (in a zip format, and using the GitHub Website)?

**Comment by wagner12345** [comment]
Yes how do I do that?

**Comment by boutinb** [comment]
Hi @wagner12345 You drag and drop your file in a issue comment in the GitHub website. Do not use your email.

**Comment by mabe08** [comment]
Hello, I am having the same issue. Not sure what to do. I am leaving a screenshot here. I used this today and then went to add a new data set so I closed it without saving. Once Iopen the new date set, the following comes up.
<img width="1552" alt="Screen Shot 2020-11-03 at 7 43 00 PM" src="https://user-images.githubusercontent.com/73918013/98055991-ca746a80-1e0c-11eb-8aca-2453b2d44983.png">

**Comment by boutinb** [comment]
@mabe08 This is apparently something else: you don't use the same analysis, and you get another error. I don't understand what you did exactly. Do you open JASP with some data file, add the Generalized Mixed Model analysis and get immediately this error? Or is it after setting some analysis options?

**Comment by mabe08** [comment]
I open JASP, open the data set and click on linear modeling I believe is
what it is called. Usually the information would begging to come up, that
is when the error comes up.

**Comment by boutinb** [comment]
Can you send us the JASP file (in a zip format) by using the GitHub website ( drag&drop on a new comment of this issue)?
