### ISSUE TITLE
problem with the opening the csv files

### ISSUE THREAD

**Issue by NikitaKhromov-Borisov** [jasp-stats/jasp-issues#1034]
* JASP version: 0.14

* OS name and version: WIn10 x64
* Analysis: opening the scv file
* Bug description:
![Open](https://user-images.githubusercontent.com/16406847/97808068-90bd2b80-1c75-11eb-9ebd-299211ee2427.jpg)

* Expected behaviour:

**Comment by boutinb** [comment]
Hi @NikitaKhromov-Borisov Just to be sure: you can open this file with an editor like notepad or Excel, but you can't with JASP?

**Comment by tomtomme** [comment]
Is it csv or scv. You wrote both. Did you create it yourself and how? Maybe it is not really a csv. Thus boutinb's suggestion to open it with notepad / a simple text editor. Then post a screenshot of the content.

**Comment by NikitaKhromov-Borisov** [comment]
The problem is observed with any csv files and only with the newest JASP version 0.14.0. So I use the previous version 0.13.1

**Comment by boutinb** [comment]
On Windows you can now install JASP in 2 ways now: for all users (as admin), or for yourself only (you don't need to be admin). How did you install JASP?

**Comment by NikitaKhromov-Borisov** [comment]
just now I reinstalled JASP through the Advanced -> for all users and now
it's OK
Thanks.
BTW, I'm waiting for several years when you will correct the calculation of
the Phi coefficient for contingency tables
E.g.,

*Contingency Tables *

*Sever *

*mStKT *

*1 *

*2 *

*3 *

*4 *

*Total *

0

4

4

3

0

11

1

28

122

14

3

167

2

6

234

46

4

290

3

1

126

131

16

274

4

1

23

63

34

121

Total

40

509

257

57

863

*Nominal *



*Value *

Contingency coefficient

0.545

Phi-coefficient

NaN

Cramer's V

0.375

ᵃ Value could not be calculated - At least one row or column contains all
zeros

You see, there is no row or column containing all zeros.

Moreover, every parameter should be accompanied by CIs.
Especially this is needed for Cohen's effect size (CES) in ANOVA. The
situation is funny: I use jamovi to calculate CES with CIs, but they are
not bootstrapped.

Best regards,
Nikita

пт, 6 нояб. 2020 г. в 18:49, bruno boutin <notifications@github.com>:

**Comment by EJWagenmakers** [comment]
Team, you can look at the phi coefficient? @JohnnyDoorn can you look at the CI for the effect size parameters in ANOVA?

**Comment by boutinb** [comment]
@vandenman Can you have a look to this last question?

**Comment by JorisGoosen** [comment]
I figure this issue is actually solved and there was an issue opened by Nikita at https://github.com/jasp-stats/jasp-issues/issues/811 for the phi-coefficient so I'll close this one.
