### ISSUE TITLE
One-sample t-test. z-test Effect Size CI is incorrect.

### ISSUE THREAD

**Issue by JASPUser** [jasp-stats/jasp-issues#1036]
Win 7. JASP 0.14.0.0 See screenshots. The Cohen's d ES 0.655 is not even inside the given CI (6.122, 6.309). Should be an easy fix. 
![image](https://user-images.githubusercontent.com/27625429/97874964-df4df100-1d6d-11eb-8065-90a7207b7472.png)
![image](https://user-images.githubusercontent.com/27625429/97875144-13c1ad00-1d6e-11eb-806b-9e1606e41610.png)
Can supply data on request.

**Comment by vandenman** [comment]
Hi, thanks for reporting this!

Unfortunately, I can't replicate this on Ubuntu 18.04. Can you perhaps send us the data? Just the one column `tslfest` should be sufficient to replicate the issue. If you prefer, you can also email the data to us.

**Comment by JASPUser** [comment]
Hi Don,
attached.

Has Psych data.

Small filesize  .sav



sincerely,

Peter Williams

Master of Statistical Science

La Trobe University & La Trobe College

Email: peter.williams@latrobe.edu.au

________________________________

**Comment by vandenman** [comment]
Unfortunately, GitHub ignores files sent as attachments. Could you perhaps use GitHub's website to upload the data?

**Comment by JASPUser** [comment]
Trying to upload file as a "csv.txt" attachment.
[survey5ED.csv.txt](https://github.com/jasp-stats/jasp-issues/files/5475655/survey5ED.csv.txt)

**Comment by AlexanderLyNL** [comment]
Solved: https://github.com/jasp-stats/jasp-desktop/pull/4407 for 0.14.1
