### ISSUE TITLE
JASP 0.14.0.0 doesn't show effect sizes in repeated-measures ANOVA's post-hoc comparisons (Cohen's d)

### ISSUE THREAD

**Issue by RenzoLanfranco** [jasp-stats/jasp-issues#1037]
* JASP version: 0.14.0.0

* OS name and version: Windows 10
* Analysis: Repeated-Measures ANOVA
* Bug description: ticking the effect size box doesn't make a difference for post hoc comparisons. It doesn't show Cohen's d scores.
* Expected behaviour: To do what it's supposed to do: show the effect sizes.

#### Steps to reproduce:
Just run a standard repeated-measures ANOVA with post-hoc comparisons. I did Bonferroni-corrected ones.

**Comment by vandenman** [comment]
Hi, thanks for reporting the issue. Unfortunately, I can't replicate the problem with the Bush Tucker example in the Data Library. Could you maybe attach the .jasp file to this issue? You will have to zip the file first otherwise GitHub complains.

**Comment by RenzoLanfranco** [comment]
@vandenman sorry, I just realised it was a bug in the spreadsheet I imported into JASP. It wasn't a JASP bug. 
Thanks for your time!
