### ISSUE TITLE
Inverted alternative hypotheses option for Bayesian One sample Wilcoxon t-test

### ISSUE THREAD

**Issue by ArCourtin** [jasp-stats/jasp-issues#1038]
JASP v 0.14 (was already the case in previous releases, though)
It appears that the one-sided alternative hypotheses options are interverted for the Bayesian one-sample t-test when using a Wilcoxon test (cf. caption)
![bugreport](https://user-images.githubusercontent.com/53186412/97991978-6341c080-1de2-11eb-93b9-d5d77a6ede41.png)

**Comment by JohnnyDoorn** [comment]
Fixed by https://github.com/jasp-stats/jasp-desktop/pull/4390
This will also be in the bug hotfix.
