### ISSUE TITLE
Request considering JASP installation error (missing VCRUNTIME140.dll)

### ISSUE THREAD

**Issue by wstrube** [jasp-stats/jasp-issues#1039]
* JASP version: 0.14

* OS name and version: Windows 64bit

* Analysis: none
* Bug description:

Dear Team of JASP!

As a new member oft he University of Augsburg I tried to install your awesome statistics software JASP today.
I received help by my IT team, as I’m working on a “protected” computer environment (working as a clinical researcher).
When I was trying to install the program and to open it after completion of the installation program, the following error message popped up, which translates to English as follows:  “Code execution cannot be continued due to VCRUNTIME140.dll not being found. Reinstalling the program may solve the problem.” Although I have tried to re-install the program, I wasn’t able to run the software. Do you already have experience with this error message? Is there a solution strategy that I can apply together with my IT department?

Very best wishes
Wolfgang Strube

<!--- A note from the developers:
If possible please attach your data and/or JASP file to the issue, this makes solving the bug a lot easier. If you would prefer to not make your data publicly available then you could also mail it to us.
Note that github requires you to zip the file to upload it here.

[JASP_error_missing_dll.zip](https://github.com/jasp-stats/jasp-issues/files/5481961/JASP_error_missing_dll.zip)

**Comment by boutinb** [comment]
Dear @wstrube Which Windows version do you have: Windows 7, 8, 10 ? 
Could you install manually the VC redistributables: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads ? It should have been done with the installation of JASP, but maybe it did not go well.

**Comment by wstrube** [comment]
Many thanks! Installing an visual C update did the trick – I used this link:
https://aka.ms/vs/16/release/vc_redist.x64.exe

Best regards
Wolfgang

Von: bruno boutin [mailto:notifications@github.com]
Gesendet: Dienstag, 3. November 2020 16:05
An: jasp-stats/jasp-issues <jasp-issues@noreply.github.com>
Cc: Strube Wolfgang <Wolfgang.Strube@bkh-augsburg.de>; Mention <mention@noreply.github.com>
Betreff: Re: [jasp-stats/jasp-issues] Request considering JASP installation error (missing VCRUNTIME140.dll) (#1039)


Dear @wstrube<https://github.com/wstrube> Which Windows version do you have: Windows 7, 8, 10 ?
Could you install manually the VC redistributables: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads ? It should have been done with the installation of JASP, but maybe it did not go well.

**Comment by boutinb** [comment]
Fine to hear! But still strange that the VC redistributables were not installed with JASP...

**Comment by JorisGoosen** [comment]
@wstrube I am wondering, you mention you work within a "protected environment", does that mean you were only allowed to install per-user?

**Comment by wstrube** [comment]
Hi!
Yes that means I was only allowed to install per user and needed my IT service guys to log onto my account and punch in their password
Best regards
Wolfgang

Von: Joris Goosen [mailto:notifications@github.com]
Gesendet: Dienstag, 3. November 2020 17:57
An: jasp-stats/jasp-issues <jasp-issues@noreply.github.com>
Cc: Strube Wolfgang <Wolfgang.Strube@bkh-augsburg.de>; Mention <mention@noreply.github.com>
Betreff: Re: [jasp-stats/jasp-issues] Request considering JASP installation error (missing VCRUNTIME140.dll) (#1039)


@wstrube<https://github.com/wstrube> I am wondering, you mention you work within a "protected environment", does that mean you were only allowed to install per-user?

**Comment by JorisGoosen** [comment]
Aah thank you for the info, enjoy using JASP!
