### ISSUE TITLE
This analysis terminated unexpectedly

### ISSUE THREAD

**Issue by wagner12345** [jasp-stats/jasp-issues#1040]
* JASP version:

* OS name and version:
* Analysis: 
* Bug description:
* Expected behaviour:

#### Steps to reproduce:

This analysis terminated unexpectedly.

Error in (structure(function (...) : Column CLASS_SIZE not found!

Stack trace
analysis(jaspResults = jaspResults, dataset = dataset, options = options, state = oldState)

.readDataSetToEnd(columns.as.numeric = variables)

.fromRCPP('.readDatasetToEndNative', unlist(columns), unlist(columns.as.numeric), unlist(columns.as.ordinal), unlist(columns.as.factor), all.columns ≠ FALSE)

do.call(obj, args)

(function (...) 
{
    .External(InternalFunction_invoke, xp, ...)
})(NULL, c('S_AGE', 'S_GPA', 'CLASS_SIZE'), NULL, NULL, FALSE)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

**Comment by boutinb** [comment]
Hi @wagner12345 You have made another issue https://github.com/jasp-stats/jasp-issues/issues/1032 where I asked you to give me the JASP file...
But I see now that you use MacOS Sierra: this version is not anymore supported by Apple self, and we neither. So you have first to upgrade your OS.

**Comment by tomtomme** [comment]
If you cannot update your OS for some reason, you could download an older JASP version https://jasp-stats.org/previous-versions/
Verstion 0.12 should work
