### ISSUE TITLE
Potential issues with SD calculated through the reliability function 

### ISSUE THREAD

**Issue by ConalMonaghan** [jasp-stats/jasp-issues#1041]
* JASP version: 0.13.1
* OS name and version:
* Analysis: The reliability module - inferential approach
* Bug description: SD produced through this module appears incorrect. For the reliability module, the mean produces the same esimate as the descriptives analysis module, however, standard deviation is roughly half that produced by the descriptives module. The SD produced by the descriptives package appears correct, and matches those produced by other software packages. Therefore, it is likely that the reliability module has the bug. 

* Expected behaviour: SD in the new reliability module should match that produced by the descriptives module. 

Please find screenshot from the descriptives and reliability modules. You will see the means match while the SD do not. 

<img width="178" alt="Screen Shot 2020-11-05 at 1 02 04 pm" src="https://user-images.githubusercontent.com/11736249/98189106-649cf580-1f68-11eb-8e67-46fae634ae85.png">

<img width="863" alt="Screen Shot 2020-11-05 at 1 11 51 pm" src="https://user-images.githubusercontent.com/11736249/98189176-81392d80-1f68-11eb-908c-72439b0da2ff.png">

**Comment by juliuspf** [comment]
Dear Conal, thanks for reporting this issue. 

If I am not mistaken, the standard deviation in descriptives is computed for each variable, and not for a bunch of variables, whereas the standard deviation in the reliability module is computed for a bunch of variables. So it seems unlikely that these align. However, the SD in the reliability module takes the SD of the item means, e.g., with 5 items that's the SD of 5 item means. I am aware that this is done differently by the psych-package in R (by default they take the SD of the observations means, and again differently by SPSS (they take the SD of the observations' sums). We might adapt one of these approaches, if this really proves to be a more widely accepted approach. Any suggestions from your side are definitely welcome.

**Comment by ConalMonaghan** [comment]
Thanks for responding here. So the SD for the reliability module is the distribution of the item means and not individual responses? Great to know, this is a nice additional function and I wonder if a small footnote explaining this difference would be helpful for people who confuse these two forms of variation. Will close.

**Comment by juliuspf** [comment]
Thanks. You are right. We are planning to add two different measures for mean and SD of a scale in the future (and label both accordingly)
