### ISSUE TITLE
I want to help translate the help-texts to german

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#1044]
I already translated via weblate. However the help texts behind the blue (i) buttons seem not to be integrated into weblate. How can I contribute translations to german?

**Comment by boutinb** [comment]
Yes, that's true, the help texts are not yet integrated in WebLate. It will be done soon, and it will be available for 0.15. In 0.14 it is still done with apart md files.

**Comment by tomtomme** [comment]
just great :dancers:
