### ISSUE TITLE
Rename Cronbach' alpha and McDonald's omega to 'coefficient', pay tribute to KR20 in help file

### ISSUE THREAD

**Issue by romanogino** [jasp-stats/jasp-issues#1046]
Dear JASP Team

¿Could you add the Kuder Richardson test to JASP?

Best regards.
r.

**Comment by juliuspf** [comment]
Thank you for this feature request. 
Is there a special reason why you do not want to use Cronbach's alpha? Alpha is a generalisation of KR20, and will be essentially the same under general assumptions.

**Comment by romanogino** [comment]
Sometimes students apply surveys with yes/not answers (binary data) and Cronbach is a little big for these questions. In essence, it is to teach students to apply and analyze simple surveys..
Best regards.

**Comment by brianmsm** [comment]
KR-20 is a particular case of Cronbach's alpha. I don't think an additional option is necessary for something that is essentially the same.

**Comment by romanogino** [comment]
Thanks for the answer. It was just a proposal. Cronbach is also a very good option. 
Best regards.
r

**Comment by juliuspf** [comment]
@EJWagenmakers do you have some thoughts?

**Comment by EJWagenmakers** [comment]
The consensus so far seems to be that the added value is limited. If other people bring the issue up again we can revisit it.

**Comment by juliuspf** [comment]
I will close this for now, @romanogino feel free to reopen it if your concerns have not been addressed sufficiently

**Comment by alandrade1** [comment]
As the calculation may be equivalent, what about just having its name to exibit at the table/result?

**Comment by tomtomme** [comment]
We do this also for Phi and Cramers V. Copy that behaviour maybe?
