### ISSUE TITLE
Reliability analysis in descriptive module not found

### ISSUE THREAD

**Issue by asgomes82** [jasp-stats/jasp-issues#1047]
* JASP version: 0.14

* OS name and version: Windows 10
* Analysis: Reliability analysis
* Bug description: not found
* Expected behaviour: expected to be in descriptive statistics.

I've recently upgraded to v.0.14. Since then, I cannot find the reliability analysis. 

Is it a bug? Did it changed the module where is presented?

Thank you.

**Comment by vandenman** [comment]
The reliability module was moved to a module in JASP 0.14. To get it back,
1. Click on the `+` in the topright of the jasp window. That opens up a menu where you can select `Reliability`.

![image](https://user-images.githubusercontent.com/21319932/98810287-49762e00-241f-11eb-8b31-bd492d601b68.png)

2. Once you've selected `Reliability` a new icon appears on the ribbon and you can do the analysis again.

![image](https://user-images.githubusercontent.com/21319932/98810399-7cb8bd00-241f-11eb-9738-e09c7390a9cd.png)


Hope that helps!

**Comment by asgomes82** [comment]
Perfect! 
Thnak you very much.
