### ISSUE TITLE
This analysis terminated unexpectedly

### ISSUE THREAD

**Issue by janelle112** [jasp-stats/jasp-issues#1049]
* JASP version: 0.11.1

* OS name and version: MacOS Catalina Version 10.15.7
* Analysis: ANOVA
* Bug description: Unable to calculate simple main effects within ANOVA
* Expected behaviour: Calculates simple main effects of my variables (each have more 2 or more levels but it says they don't)

#### Steps to reproduce:
1. Go to Simple Main effects
2. Click on Intensity (A) and move it to Simple Effect Factor
3. Click on Stimulus (B) and move it to Moderator Factor 1

[JASP 3 data.pdf](https://github.com/jasp-stats/jasp-issues/files/5526626/JASP.3.data.pdf)

**Comment by boutinb** [comment]
Hi @janelle112, JASP 0.11.1 is quite old. We have now JASP 0.14. Can you try this version?

**Comment by janelle112** [comment]
Yes, do I need to update the application? I have tried to look for this option with no success. Or is there a link to be able to download that newer version?
________________________________

**Comment by vandenman** [comment]
@janelle112 you can obtain the latest version from https://jasp-stats.org/download/
