### ISSUE TITLE
JASP crashed

### ISSUE THREAD

**Issue by tasha174** [jasp-stats/jasp-issues#1052]
* JASP version: 0.14
* OS name and version: KDE Flatpak runtime

* Analysis: 
* Bug description:
* Expected behaviour:

#### Steps to reproduce:

-----------------------------------------------------------------------

### Debug information:
**Engine # 0** process *crashed* and it's state is *initializing*.
**Engine # 1** process  is *running* and it's state is *idle*.
**Engine # 2** process *crashed* and it's state is *idle*.
**Engine # 3** process  is *running* and it's state is *idle*.

[Commit used](https://github.com/jasp-stats/jasp-desktop/commit/e93e15cbaf55662b26b323b8ce088b0414ef6e98)

**Comment by boutinb** [comment]
HI @tasha174 Can you describe precisely what you did with JASP before it crashes?
