### ISSUE TITLE
macOS Big Sur Compatibility Issue?

### ISSUE THREAD

**Issue by zrocca** [jasp-stats/jasp-issues#1053]
* JASP version:0.14

* OS name and version: macOS 11.0.1
* Analysis: 
* Bug description:  Can't change value data to be ordinal, nominal or scale.  Also, Can't click on the title row for each column to change the name.
* Expected behaviour: Should be able to reclassify the data and change the name of columns.

**Comment by boutinb** [comment]
Hallo @zrocca You can change the data type by clicking on the icon of the column header of the data.
There is no possibility to change the name of the columns directly in JASP, but you can double-click on the data panel, and it will open your data file with your preferred spreadsheet editor. You can then change column names, of data, and this change will be automatically synchronized in JASP.

**Comment by zrocca** [comment]
Hello,

Ive attached a screenshot that shows that I can’t change the data type from
nominal to ordinal. Also when I uploaded the spreadsheet the system
automatically labeled a V7V8 as you can see in the screenshot I was
wondering if there is any way to change that since those data points are
not in the original spreadsheet.

**Comment by boutinb** [comment]
Hi @zrocca I don't the files you upload if you answer directly with your email. Please use GitHub to answer.
You can change a column to ordinal only if it contains integers. Maybe you have some not numeric values in it?

**Comment by pattyswim** [comment]
I am having the same problem. When I try to click on the icon to change the data type to scale, ordinal, or nominal the choices show up and I click on one, but nothing happens. Also the icon looks different. I am attaching a screen shot, I circled the icon in red.
<img width="606" alt="Screen Shot 2020-11-17 at 3 20 46 PM" src="https://user-images.githubusercontent.com/74630372/99462483-a0c94200-28e8-11eb-9c17-2489398a4041.png">

**Comment by boutinb** [comment]
This icon shows that it is Nominal Text type. I can see already that the data contains strings. This means that it cannot be changed in scale or ordinal type.
