### ISSUE TITLE
Unexpected Termination Error in Generalized Linear Modeling

### ISSUE THREAD

**Issue by rcarlton2** [jasp-stats/jasp-issues#1054]
* JASP version: 0.14

* OS name and version: MacOS Mojave and  replicated on High Sierra
* Analysis: Generalized Linear Modeling (Visual Modeling Module)
* Bug description: Output terminates with the following message: 
This analysis terminated unexpectedly.
Error in gzfile(file, 'wb'): cannot open the connection
Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])
doTryCatch(return(expr), name, parentenv, handler)
withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)
analysis(jaspResults = jaspResults, dataset = dataset, options = options)
flexplot:::glinmod_jasp(jaspResults, dataset, options)
.glinmod_model_plot(jaspResults, options, ready, dataset)
.create_flexplot_glinmod(jaspResults, modelplot, options, dataset)
save(terms, generated.formula, options, glinmod_results, dataset, file = '~/Documents/RPackages/data_before.rdata')
gzfile(file, 'wb')
* Expected behaviour: Creation of output

#### Steps to reproduce:
1. Go to 'Visual Modeling'
2. Click on 'Generalized Linear Modeling'
3. Enter IV/DV variables

I saw that someone else posted this same issue as a comment under issue #1032 , but it was unrelated to the actual issue from the OP. I'm not sure if this is an issue with the module or with the OS as I don't have another operating system around to test. I got the same errors using different .csv and .sav file on two different Macs with the same JASP version.

**Comment by rcarlton2** [comment]
Zip file of the JASP data attached. This is just simulated data for practice purposes. 
[Application 7 and 8 Data JASP.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/5548438/Application.7.and.8.Data.JASP.jasp.zip)

**Comment by boutinb** [comment]
Hi @dustinfife, can you have a look to this problem?

**Comment by dustinfife** [comment]
Yes, @boutinb, this is the issue I mentioned to you in email and should have been fixed on my end with my most recent commit on Github. (Long story short, I had a "save" in my file that I used for debugging purposes that I forgot to remove).

**Comment by rcarlton2** [comment]
Thanks both of you, I’ll keep an eye out for the new version.

**Comment by MAALKAN** [comment]
Version 0.14.1 returns an error :
This analysis terminated unexpectedly. 

Error in gzfile(file, 'wb'): cannot open the connection

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

flexplot:::glinmod_jasp(jaspResults, dataset, options)

.glinmod_model_plot(jaspResults, options, ready, dataset)

.create_flexplot_glinmod(jaspResults, modelplot, options, dataset)

save(terms, generated.formula, options, glinmod_results, dataset, file = '~/Documents/RPackages/data_before.rdata')

gzfile(file, 'wb')

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

**Comment by boutinb** [comment]
Hi @rcarlton2 Could you try this version: http://static.jasp-stats.org/Nightlies/MacOS/JASP-nightly-stable-63e5395cc5fdb950150691db0e13d9ca0e8be715.dmg

**Comment by rcarlton2** [comment]
@boutinb @dustinfife  Yes, that takes care of the issue! I can now run the generalized linear model without a problem.

**Comment by boutinb** [comment]
Nice!
