### ISSUE TITLE
JASP crashed

### ISSUE THREAD

**Issue by RMOCHI25** [jasp-stats/jasp-issues#1058]
* JASP version: 0.14
* OS name and version: Windows 10 (10.0)

* Analysis: 
* Bug description:
* Expected behaviour:

#### Steps to reproduce:

-----------------------------------------------------------------------

### Debug information:
**Engine # 0** process  is *running* and it's state is *settings*.
**Engine # 1** process  is *running* and it's state is *settings*.
**Engine # 2** process  is *running* and it's state is *settings*.
**Engine # 3** process  is *running* and it's state is *settings*.

[Commit used](https://github.com/jasp-stats/jasp-desktop/commit/ed2a1b65aab4d34c0e1d9ec8e61cfbabf609a58b)

**Comment by boutinb** [comment]
Hi @RMOCHI25 Could you add a more precise description of what you did to get this error?

**Comment by JorisGoosen** [comment]
Were you changing some settings in JASP perhaps?

**Comment by bradyse** [comment]
After my most recent Windows update, JASP (0.14) quit working. After reinstalling it, every attempt to open the program fails.

**Comment by boutinb** [comment]
I have heard that sometimes there is a problem with the Visual C++ redistributable libraries. These libraries are shipped with JASP, but after a Windows upgrade something goes wrong. Could you install these libraries yourself: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
And then try again to start JASP.

**Comment by JorisGoosen** [comment]
> I have heard that sometimes there is a problem with the Visual C++ redistributable libraries. These libraries are shipped with JASP, but after a Windows upgrade something goes wrong. Could you install these libraries yourself: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
> And then try again to start JASP.

Bruno, if those are missing you get an explicit warning that the runtime is missing and JASP won't even start. Thus it will also not get to this crashreport.

**Comment by JorisGoosen** [comment]
What would be helpful is if @bradyse could start JASP and send us the logfiles.

To do so (s)he would have to open a command prompt, then navigate to the directory where JASP was installed by entering one of the following two commands (or one with the custom folder):
`cd "C:\Program Files\JASP\` or `cd "C:\Program Files (x86)\JASP\`

Then in that folder JASP can be started as:
`JASP --logToFile 1> %USERPROFILE%\Documents\startup.log 2>&1`

After JASP has crashed again you could send us the `startup.log` file now in your "My Documents" folder.
And the logfiles in `C:\Users\bradyse\AppData\Roaming\JASP\JASP\Logs` if your username is `bradyse` on windows, otherwise you would have to replace that.

**Comment by JorisGoosen** [comment]
https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/user-guide/logging-howto.md

**Comment by bradyse** [comment]
I managed to get JASP to actually open after downloading and unzipping the .zip file posted in a previous post [https://github.com/jasp-stats/jasp-issues/issues/1043](url). I had to bypass the "Microsoft Defender SmartScreen" and click "Run anyway." Perhaps it was coincidence, but once I started messing around with the command prompt, JASP finally opened. Here are the logs.  

[JASP 2020-11-26 19_40_57 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/5605602/JASP.2020-11-26.19_40_57.Desktop.log)
[JASP 2020-11-26 19_40_57 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/5605603/JASP.2020-11-26.19_40_57.Engine.0.log)
[JASP 2020-11-26 19_40_57 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/5605604/JASP.2020-11-26.19_40_57.Engine.1.log)
[JASP 2020-11-26 19_40_57 Engine 2.log](https://github.com/jasp-stats/jasp-issues/files/5605605/JASP.2020-11-26.19_40_57.Engine.2.log)
[JASP 2020-11-26 19_40_57 Engine 3.log](https://github.com/jasp-stats/jasp-issues/files/5605606/JASP.2020-11-26.19_40_57.Engine.3.log)
[JASP 2020-11-26 20_05_52 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/5605607/JASP.2020-11-26.20_05_52.Desktop.log)

**Comment by JorisGoosen** [comment]
It seems that maybe a windows update broke it, I saw this in some other issues as well.
And anyhow, your problem has gone so that is good.
