### ISSUE TITLE
Survivorship analyses 

### ISSUE THREAD

**Issue by ducatony** [jasp-stats/jasp-issues#1059]
Hi all,

I was wondering if there has been (I presume there has, but I haven't been able to find it) a discussion on adding survivorship analyses to JASP, specifically Kaplan Meier with the comparisons as well as the Cox Regression analysis.

Kind regard,
Tony

**Comment by boutinb** [comment]
@EJWagenmakers Do you know this?

**Comment by EJWagenmakers** [comment]
We expect to be able to add this before the summer (it is the thesis topic of one of our team members :-))
Cheers,
E.J.
