### ISSUE TITLE
Feature request: Hedge's g (bias corrected) for t-tests and Omega Squared for  ANOVA (Bayesian t-test and ANOVA especially) 

### ISSUE THREAD

**Issue by abnormally-distributed** [jasp-stats/jasp-issues#106]
I am interested in more robust estimates of effect size, such as hedge's g and omega². Are there plans to add this, or is there a way to convert cohen's d estimates in the Bayesian analysis to get credible intervals for hedge's g? 

I don't think the Bayesian ANOVA has an effect size measure at all (like eta²) but omega² would be a good feature I think. 

See this [blog post from the 20% statistician ](http://daniellakens.blogspot.com/2015/06/why-you-should-use-omega-squared.html) on why hedge's g and omega² ought to be used.

**Comment by tomtomme** [comment]
@abnormally-distributed 
both are sufficient in the classical t-test and anova now
is this sufficient to close this issue?
