### ISSUE TITLE
Please add radar chart and heatmap 

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#1060]
JASP already greatly improved plotting especially with flexplot. 
Now whats really missing are some plot types for 3 variables highligted in red. 
The yellow ones are second priority because they are already covered by alternatives that show mostly the same information in a different style.
<img width="1355" alt="grafik" src="https://user-images.githubusercontent.com/4428185/99525496-307af900-299a-11eb-954b-0ce8c7af74de.png">

A special kind of heatmap is already implemented in the correlation module. But not something like [this](https://www.spiegel.de/wissenschaft/natur/wetter-daten-rekord-sommer-wie-warm-war-2019-im-vergleich-zu-2018-a-1280048.html) or [this](https://en.wikipedia.org/wiki/Heat_map#/media/File:Heatmap.png). 
Thanks :)

**Comment by Kucharssim** [comment]
Hello @tomtomme,

thanks for the request. Regarding the heatmaps: I understand what you suggest with the plot in the Spiegel article, I think that should be doable. I am not sure which kind of heatmap you refer to with the wikipedia article. There are many different plots that can be described as a "heatmap". Would you want to be more specific?

**Comment by tomtomme** [comment]
I think it would be nice to be able to add any metric variable and then to choose which one goes to X, to Y and to color. The specific one from wikipedia is not that important to me.

**Comment by Kucharssim** [comment]
Ok, that makes sense now!

**Comment by tomtomme** [comment]
not yet in JASP 0.15 beta 20.9.2021 (flatpak linux build)

**Comment by Kucharssim** [comment]
It was not merged yet - we postponed it for 0.16

**Comment by tomtomme** [comment]
so cool :D

**Comment by tomtomme** [comment]
I guess this was postponed to 0.17 - right? :D

**Comment by boutinb** [comment]
@Kucharssim ?

**Comment by Kucharssim** [comment]
I just got to fixing some corner cases, so let's see; perhaps we can make it for 0.16.1.

**Comment by tomtomme** [comment]
I just tested this in 0.16.1 flatpak beta.
It is awesome!
At the same time the UI could use improvements: 
a) It is not obvious that you can change the color palette, because the color palette drop-down menu sits way above in the visualy separate section "Customizable plots". It is not obvious, that the section "Tile Heatmap" belongs to "Customizable plots"
b) For a literal "heat"-map containing a temperature-variable it would be nice to have a fitting color palette ranging from blue (cold) over white (normal) to red (hot). 
c) An even broader range of color palettes would be optimal. But if the list of color palettes would get longer the names of the palettes would need to be self-descriptive (at least viridis and ggplot do not give information about what to expect). It would be even better if the color-palette drop down menu would contain a preview of the palette next to or except of its name. If except for its name, then the color-blind schemes would need to be grouped into a section thats named "color blind palettes" or similar.

**Comment by Kucharssim** [comment]
Thanks for the feedback! We are aware of the colour palette issues, and it's good that there is a consensus about it - we had exactly this debate earlier (https://github.com/jasp-stats/jaspDescriptives/pull/8#issuecomment-1012089788), but decided to go with this version for now. But we definitely have this on our radar to fix it more systematically (https://github.com/jasp-stats/INTERNAL-jasp/issues/1667 for reference)

**Comment by tomtomme** [comment]
great :)
I have no access to the internal jasp issues however.
Cheers
