### ISSUE TITLE
Error in gzfile(file, 'wb'): cannot open the connection

### ISSUE THREAD

**Issue by summerloving** [jasp-stats/jasp-issues#1061]
* JASP version: 0.14
 MacOS
* OS name and version: macOS Big Sur Version 11.0.1
* Analysis: GLM
* Bug description: error in gzfile (file, 'wb'): cannot open the connection
* Expected behaviour: perform GLM

#### Steps to reproduce:
1. Go to 'GLM'
2. Choose 'DV'
3. Choose 'IV'

**Comment by boutinb** [comment]
Could you send us your JASP file (in a zip format, and by using the GutHub platform)?

**Comment by summerloving** [comment]
> Could you send us your JASP file (in a zip format, and by using the GutHub platform)?

[Screen Shot 2020-11-18 at 8.08.01 PM.zip](https://github.com/jasp-stats/jasp-issues/files/5567628/Screen.Shot.2020-11-18.at.8.08.01.PM.zip)

^^I think this should work now. Thanks!

**Comment by boutinb** [comment]
Hi @summerloving, could you try this version: http://static.jasp-stats.org/Nightlies/MacOS/JASP-nightly-stable-63e5395cc5fdb950150691db0e13d9ca0e8be715.dmg

**Comment by summerloving** [comment]
I tried to download it, but my computer rejected it

**Comment by summerloving** [comment]
I had downloaded the Catalina version previously and I just downloaded the Mojave & High Sierra and I got the same error notification.

**Comment by boutinb** [comment]
HI @summerloving What do you mean exactly by 'my computer rejected it' ? Could you not download it? Could you not start the setup by double-clicking on the dmg file? Or could you not start the installed JASP version?
This version is indeed not certified, but usually by right-clicking on the icon, the you can still start JASP.

**Comment by summerloving** [comment]
[Screen Shot 2020-11-23 at 1.42.44 PM.zip](https://github.com/jasp-stats/jasp-issues/files/5585079/Screen.Shot.2020-11-23.at.1.42.44.PM.zip)

So I am able to download it but after I try to move the JASP app to applications and open JASP I get a message saying it can't be opened and I only have an option to move it to the trash or cancel (this is the "my computer rejected it" part). I have attached a screenshot of that notification. Thanks!

**Comment by boutinb** [comment]
Could you right-click on the JASP icon, and select the Copy menu, and then go to Applications to paste it. You can try also to start it directly by selecting the Open menu.
If all that does not work, we will have to make a certified version.

**Comment by summerloving** [comment]
[Screen Shot 2020-11-24 at 10.45.10 AM.zip](https://github.com/jasp-stats/jasp-issues/files/5590992/Screen.Shot.2020-11-24.at.10.45.10.AM.zip)

I still could not get it to work (see attached screenshot)

**Comment by boutinb** [comment]
Apparently the verification checks are harder on macOS Big Sur. @JorisGoosen Do you have the same problem with a nightly build?

**Comment by JorisGoosen** [comment]
Aah I still have to turn the update on, I will go do that now.
After that I can check if I have the same problem.

But looking at this document by apple: https://support.apple.com/en-us/HT202491
Tells me that @summerloving could also open it by passing through the settings as described under "How to open an app that hasn’t been notarized or is from an unidentified developer"
