### ISSUE TITLE
unexpected termination ANCOVA

### ISSUE THREAD

**Issue by ievagriffin** [jasp-stats/jasp-issues#1063]
* JASP version: 0.9.0.1
 
* OS name and version: chrome os 86.0.4240.183
* Analysis: ANCOVA
* Bug description: error in loadNamespace(name): there is no package called "emmeans"
* Expected behaviour: compute marginal means for the data set

#### Steps to reproduce:
1. run ANCOVA with recall as dependent, group as fixed factor, and imagery as [covariate](
[ezyzip.zip](https://github.com/jasp-stats/jasp-issues/files/5567669/ezyzip.zip)

))
2. click on 'additional options'
3. go to 'marginal means'
4. click on  'group'
5. See error

**Comment by boutinb** [comment]
Hi @ievagriffin Could you use the last JASP version 0.14. If you are using RollApp, this version of JASP will be soon available.

**Comment by tomtomme** [comment]
@ievagriffin 
This is fixed. Tested with jasp 0.18.2 beta. Probably fixed already in earlier versions
So this issue can be closed.
