### ISSUE TITLE
odd df?

### ISSUE THREAD

**Issue by amandazhang0727** [jasp-stats/jasp-issues#1065]
Hi, I was doing a paired sample t-test between two sub-scales.
And I found the df(degree of freedom) was different between the two sub-scales.
There were 59 participants in the survey.The df is 58 and the df for the second scale was 57. 
I was wondering what's wrong with the second sub-scale?

**Comment by EJWagenmakers** [comment]
Probably a missing value somewhere -- to check you can run Descriptives and check the table.
E.J.

**Comment by amandazhang0727** [comment]
> Probably a missing value somewhere -- to check you can run Descriptives and check the table.
> E.J.

how do I deal with the missing value? Do i need to remove it?

**Comment by EJWagenmakers** [comment]
No, but it does mean that your test has a different df

**Comment by amandazhang0727** [comment]
> No, but it does mean that your test has a different df

thank you so much, but still have one concern to go. do I need to report this situation when I'm writing data analysis report?

**Comment by EJWagenmakers** [comment]
Absolutely.

**Comment by juliuspf** [comment]
I am closing this as solved. Feel free to reopen if any questions remain
