### ISSUE TITLE
how to calculate cronbach's alpha and how to find missing value

### ISSUE THREAD

**Issue by amandazhang0727** [jasp-stats/jasp-issues#1066]
Hi, another two questions:
1. How to calculate internal consistency when some of the items are asking the questions in the opposite way?
( E.g. some items asking people to rate "I think people are kind", and some items are like"I believe people are evil") Is there a detailed tutorial for this??

2. Just curious, how do I report the df like this: https://github.com/jasp-stats/jasp-issues/issues/1065
Could you please give me an example or suggestion on how to report this? Never met such situation before. Totally understand if you are not happy to answer this because this is not JASP-related.

**Comment by vandenman** [comment]
1. Under `Reverse-Scaled Items` you can specify which items correlate negatively with the scale. So if, for example, your questionnaire measures peoples' kindness, then it could make sense to drag an item like "I believe people are evil" to the box `Reverse-Scaled Items`.

![image](https://user-images.githubusercontent.com/21319932/99792601-a19be700-2b27-11eb-9292-8e9b028e3e16.png)

 
2. Well when you report a t-test then you usually report some statistics like `t(50) = 5.22, p < .001`. In your case, it looks like you conducted two t-tests. So once you'd report `t(58) = 5.22, p < .001` and for the second you could report `t(57) = 1.001, p = .123` (the numbers are made up btw).

Let me know if you have any further questions!

**Comment by amandazhang0727** [comment]
> 1. Under `Reverse-Scaled Items` you can specify which items correlate negatively with the scale. So if, for example, your questionnaire measures peoples' kindness, then it could make sense to drag an item like "I believe people are evil" to the box `Reverse-Scaled Items`.
> 
> ![image](https://user-images.githubusercontent.com/21319932/99792601-a19be700-2b27-11eb-9292-8e9b028e3e16.png)
> 
> 1. Well when you report a t-test then you usually report some statistics like `t(50) = 5.22, p < .001`. In your case, it looks like you conducted two t-tests. So once you'd report `t(58) = 5.22, p < .001` and for the second you could report `t(57) = 1.001, p = .123` (the numbers are made up btw).
> 
> Let me know if you have any further questions!

OMG thank you so much!! That's really helpful!

**Comment by amandazhang0727** [comment]
> 1. Under `Reverse-Scaled Items` you can specify which items correlate negatively with the scale. So if, for example, your questionnaire measures peoples' kindness, then it could make sense to drag an item like "I believe people are evil" to the box `Reverse-Scaled Items`.
> 
> ![image](https://user-images.githubusercontent.com/21319932/99792601-a19be700-2b27-11eb-9292-8e9b028e3e16.png)
> 
> 1. Well when you report a t-test then you usually report some statistics like `t(50) = 5.22, p < .001`. In your case, it looks like you conducted two t-tests. So once you'd report `t(58) = 5.22, p < .001` and for the second you could report `t(57) = 1.001, p = .123` (the numbers are made up btw).
> 
> Let me know if you have any further questions!

Hi, it worked very well. Thank you.
One more question I'm concerning is, I am trying to calculate the reliability(internal consistency) for a single scale. 
I'm using a single-test reliability analysis, noticed there is a label called bayesian reliability analysis.
When do people use bayesian reliability analysis?

**Comment by EJWagenmakers** [comment]
I think these kinds of questions are more appropriate for the JASP Forum.

**Comment by juliuspf** [comment]
I am closing this, as it is a question for the forum not GitHub.
