### ISSUE TITLE
The engine crashed while trying to run this analysis...

### ISSUE THREAD

**Issue by Lucadam** [jasp-stats/jasp-issues#1068]
JASP version: 0.14
OS name and version: MacOS Big Sur 11.0.1
Analysis: Network Analysis
Bug description: "The engine crashed while trying to run this analysis..."
Expected behaviour: run the network analysis

Steps to reproduce:
1. Go to 'network'
2. Select variables
3. See error

**Comment by vandenman** [comment]
Hi, thanks for reporting this! Unfortunately, I cannot reproduce this issue on Ubuntu 18.04. Could you perhaps share the jasp file that gave you this error, or the log files?

**Comment by Lucadam** [comment]
Hi, thanks! Where can I find the log files?

I have others problems: JASP crashes when I open a file (xls, csv and sav)

**Comment by vandenman** [comment]
If you go to `Preferences` -> `Advanced` -> `Show logs` you should be able to see the logs.

![image](https://user-images.githubusercontent.com/21319932/99959130-c17f1500-2d8a-11eb-9c88-d691ede43656.png).

Note that the log files are created after you do a particular analysis, so please first replicate the error and then share the log files.

**Comment by Lucadam** [comment]
Thank you for the explanation. I actually don't know which is the right file, I think Engine 3 because it was the last one. I also enclose the file with the text that comes out when I open a recent file 


- [problem open file jasp.pdf](https://github.com/jasp-stats/jasp-issues/files/5582942/problem.open.file.jasp.pdf)
- [JASP 2020-11-23 13_26_31 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/5582932/JASP.2020-11-23.13_26_31.Desktop.log)
- [JASP 2020-11-23 13_26_31 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/5582933/JASP.2020-11-23.13_26_31.Engine.0.log)
- [JASP 2020-11-23 13_26_31 Engine 3.log](https://github.com/jasp-stats/jasp-issues/files/5582934/JASP.2020-11-23.13_26_31.Engine.3.log)

Thank you!

**Comment by Lucadam** [comment]
I have an update, I don't know if useful: I can run the network analysis when I select "Cor" in Correlational Method.

**Comment by vandenman** [comment]
@JorisGoosen can you take a look at the messages in the .pdf file above? Would safeGraphics maybe help?

**Comment by JorisGoosen** [comment]
The crashlog does have some graphics related errors in it, so it might be helpful to try safeGraphics mode (in preferences->Interface). But that error seems different from the network analysis one. There might very well be some problems with regards to Big Sur..

As far as network analysis goes, it seems the engine log for engines 1 and 2 are missing. It would be good if @Lucadam could upload those.

**Comment by Lucadam** [comment]
Thank you so much. I redid the analysis. Here the files:

- [JASP 2020-11-23 15_33_12 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/5583663/JASP.2020-11-23.15_33_12.Desktop.log)
- [JASP 2020-11-23 15_33_12 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/5583664/JASP.2020-11-23.15_33_12.Engine.0.log)
- [JASP 2020-11-23 15_33_12 Engine 3.log](https://github.com/jasp-stats/jasp-issues/files/5583666/JASP.2020-11-23.15_33_12.Engine.3.log)
- [JASP 2020-11-23 15_33_12 Engine 2.log](https://github.com/jasp-stats/jasp-issues/files/5583667/JASP.2020-11-23.15_33_12.Engine.2.log)
- [JASP 2020-11-23 15_33_12 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/5583668/JASP.2020-11-23.15_33_12.Engine.1.log)

**Comment by JorisGoosen** [comment]
Thank you for the new logs!

Sadly enough it just shows me that the analysis does indeed crash...
I'll have to test this out myself, I have a mac here so Ill try it out when I get the chance.
And I was planning to upgrade to Big Sur soon, so we can see if that causes it or not.

**Comment by Lucadam** [comment]
I tried the safeGraphics mode and it works. The only problem that remains is that when I open a file from recent files Jasp crashes. Anyway, this is not a problem, I can select manually the file. Thank you so much to solved my main problem!

**Comment by JorisGoosen** [comment]
@Lucadam I just upgraded to Big Sur and can run Network ANalysis fine.

Maybe you could upload the jaspfile with the crashed analysis in it?
To upload it here you need to zip it (or change the extension to zip, also fine).

**Comment by Lucadam** [comment]
I apologize for the delay in replying! Here you can file the jasp file, thanks!
[daminato.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/5688565/daminato.jasp.zip)

**Comment by vandenman** [comment]
Thanks! If I use almost all variables in the data set I get that the engine crashes. I will look into this further and will keep you updated.

**Comment by vandenman** [comment]
So there are multiple things going wrong here. The error message is not very informative, I will improve that. However, your data set consists of `1048349` rows, but rows `167` until `1048349` are completely empty. That's probably not what you want! If I filter out the missing values with `!is.na(ID)` as filter, then the analysis proceeds without error. Would that work for you?

**Comment by Lucadam** [comment]
Thanks! I suspected it because the problems mentioned above remain only for this file (I divided a big file into 4 samples/files). How can I eliminate these additional rows? I'm new to Jasp and R. Eventually, it might be useful if I copy the valid rows into a new CSV and then import them into Jasp?

**Comment by vandenman** [comment]
> How can I eliminate these additional rows?

One way is to open the file in e.g., excel, and delete the rows manually. That way they'll be gone forever (which is probably better in this case). Afterward, you can read the data again in JASP.

If you want to do this within JASP, click on the filter icon:
![image](https://user-images.githubusercontent.com/21319932/102185726-cc245a00-3eb1-11eb-9ffa-2aad844ab08a.png)

Then click on R

![image](https://user-images.githubusercontent.com/21319932/102185776-de9e9380-3eb1-11eb-86e9-a0ad53bcc067.png)

then type `!is.na(ID)` followed by clicking on `Apply pass-through filter`.

**Comment by AlexanderLyNL** [comment]
I think that the problem is solved by removing the missing cases. Please reopen, if something's still unclear.
