### ISSUE TITLE
Error in RM ANOVA - cannot allocate vector of size 1.1 Gb

### ISSUE THREAD

**Issue by rnsoicher** [jasp-stats/jasp-issues#1069]
* JASP version: 0.11
* OS name and version: Windows 10
* Analysis: Repeated Measures ANOVA (one-way)
* Bug description: Receiving the error "Cannot allocate vector of size 1.1 Gb"
* Expected behaviour: F-Table with RM ANOVA results

#### Steps to reproduce:
1. Go to ANOVA
2. Click on Repeated Measures ANOVA
3. Put in four levels of Factor 1, Leave Factor 2 blank
4. Add four variables to the RM cells window.
[JASP Error.zip](https://github.com/jasp-stats/jasp-issues/files/5575268/JASP.Error.zip)
[Data.zip](https://github.com/jasp-stats/jasp-issues/files/5575275/Data.zip)

**Comment by boutinb** [comment]
Could you try the last version of JASP (0.14): https://jasp-stats.org/download/

**Comment by dr-niz** [comment]
I routinely encounter this issue. I've encountered it across many versions of JASP using different datasets. Sometimes it returns the vector size issue. Other times, it simply runs and runs without completing. 

I often use repeated measures designs with lots of levels (e.g., 12-30) and one or two 2-level between subjects factors as well in my models. Sometimes, I can get JASP to complete an analysis if I greatly reduce the within subject factors (e.g., from 12 to 6).

**Comment by boutinb** [comment]
Can you send us a JASP file with this problem. Then we can have a look at the memory used.

**Comment by dr-niz** [comment]
Sure thing. This dataset has a two 12-level within subject measures, and three 2-level between subjects factors. I get the error “cannot allocate vector of size 572.7 Mb” when I try to run this analysis.

**Comment by boutinb** [comment]
@dr-niz  Please use the GitHub Website to send file (in a ZIP format). If you answer via mail, the file is not sent.

**Comment by dr-niz** [comment]
> @dr-niz Please use the GitHub Website to send file (in a ZIP format). If you answer via mail, the file is not sent.

I edited my response to include a .zip of the dataset

**Comment by boutinb** [comment]
I have tried it on my machine (MacBook), and it works without problem. The Engine takes 1.56 GB of real memory and 5.81 GB of Virtual Memory. This is indeed a lot, but not extreme. Most af the machines should support that. I will try tomorrow on a Windows machine.
Here is the result:
[JASP 0_14_1 Final dataset with bad subs removed.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/5673901/JASP.0_14_1.Final.dataset.with.bad.subs.removed.jasp.zip)

**Comment by EJWagenmakers** [comment]
Call me old-fashioned, but this seems huge. Is this an issue with R? (if so, it is what it is)

**Comment by vandenman** [comment]
just to make sure, are you using a 32-bit version of Windows? [R running on a 32-bit system has very strict memory limitations in contrast to R running on 64-bit systems.](http://search.r-project.org/R/library/base/html/Memory-limits.html)

**Comment by dr-niz** [comment]
My computer is about 2 weeks old. Here are the specs:

![image](https://user-images.githubusercontent.com/75586298/101811964-bc3efb80-3ae8-11eb-82de-42335f480640.png)

**Comment by boutinb** [comment]
I have just tried on a Windows 10 machine with 16 GB RAM and 3.39 GHz processor. and it works without problem... and the JASP Engine uses ~1,5 GB (like n Mac)
I see here https://www.rdocumentation.org/packages/utils/versions/3.4.1/topics/memory.size that it's possible to set the memory size used by R. @vandenman : is it possible to increase the memory with a global setting in R?

**Comment by vandenman** [comment]
@boutinb yes it's possible to change the limits. If you try `memory.limit()` in the R beta window you should see the current limit. On Ubuntu I get a warning followed by Inf, but on Windows there should be some value.
![image](https://user-images.githubusercontent.com/21319932/101929089-b0316780-3bd6-11eb-910a-ae922704e5b4.png)

**Comment by boutinb** [comment]
@dr-niz Did you try what Don showed? Om my PC, I get 1.76e+13

**Comment by dr-niz** [comment]
Yes, I get this value: 1.759219e+13

**Comment by boutinb** [comment]
Hmm... this is a tough one... Can other people using Windows try it: @koenderks or @FBartos ?

**Comment by tomtomme** [comment]
@rnsoicher 
@dr-niz 
may this https://github.com/jasp-stats/jasp-issues/issues/617 be related?
May it already be fixed on your side with a newer jasp version?
