### ISSUE TITLE
Bugs in linear regression

### ISSUE THREAD

**Issue by kndiaye85** [jasp-stats/jasp-issues#1070]
* JASP version: JASP 0.11.1

* OS name and version:  Windows 10 Family version 1909
* Analysis: 
* Bug description:
Problem 1) not possible to add all used variables as covariates
Problem 2) when trying to add variables working in total, the engine crashed and JASP closed
* Expected behaviour:
Problem 1) able to consider and add all variables I need
Problem 2) consider all variables to calculate the linear regression

#### Steps to reproduce:
Problem 1)
     1. Go to '...' linear regression with the file attached (JASP3 bug.csv)
     2.  I need the field TOTAL as dependent variable and all others as covariates
     They all use either 01 coding or numbers. 
     3. When I try to add variables as covariates, I have problem when I add some ones : K4 (after K1, K2, K3). If I add it first it is OK 
    but the problem occurs when I want  to add the last Kn. 
    Same problem with : 
        - B2 (linked to variables A2 and B1) 
        - Autres filieres (linked to variables Paces, STAPS, L1 Bio, Article 25)
        - Classe moyenne supérieure (linked to Classe moyenne inférieure, Classe ouvrière, Classe priviligiée)
        - Etes-vous en CFA ou autres contrat

      I don't understand the problem because I can add Liberal, Salariat and Autres Stages without problems (Screenshot3) and for 
     me this is the same variable construction that I used for all

.

      4. See error when adding K1, K2, K3 and K4 for example (screenshot 1)

Problem 2) 

With the same file JASP3 bug, if problem 1) is solved or explained I think JASP crash if I add all variables at once.
See screenshot 2 

Thank you for your investigation

[Bug - linear regression.zip](https://github.com/jasp-stats/jasp-issues/files/5577877/Bug.-.linear.regression.zip)

**Comment by djdekker** [comment]
The error message suggests that you're having a problem with multicollinearity. Did you check for high VIF values ("Regression" > "Linear regression" > "Statistics" > "Collinearity diagnostics"), for example for K2, K3 and K4?

**Comment by kndiaye85** [comment]
Thank you for your answer djdekker
Yes I have seen that probelm of collinearity. I just checked what you said and don't find any abnormality (see in screenshot).
What could explain the error with a high VIF value ? 
Moreover I have also added Liberal, Salariat and Autres Stages and I don't see any explication about why collinearity isn't a problem there. 

![Capture](https://user-images.githubusercontent.com/74825821/99916355-221a3d80-2d0a-11eb-8e88-5832c4472bce.JPG)

**Comment by boutinb** [comment]
Hi @kndiaye85, you use version 0.11, which is quite old. Could use try the newest version (0.14): https://jasp-stats.org/download/ ?

**Comment by kndiaye85** [comment]
Hello @boutinb,  I have just tried and this exactly the same problem.

**Comment by tomtomme** [comment]
@kndiaye85 

I tested the file with 0.18.3. Error message:

The variance-covariance matrix of the supplied data is not positive-definite. Please check if variables have many missings observations or are collinear

I guess there is nothing we can do about this, until JASP learns to deal with lots of missings in regression. This feature is being worked on afaik. So I will close this one.
Feel free to reopen, if you disagree!
