### ISSUE TITLE
Flip variables tool

### ISSUE THREAD

**Issue by App-State-Prof** [jasp-stats/jasp-issues#1071]
There is a feature in reliability testing...to flip/reverse score variables for testing. Can you extend this feature so that flipped variables can be saved as a transformed variable in the data set?

**Comment by vandenman** [comment]
We'll look into this but we'll probably want to set up data editing properly first. So it may take some time before we can look into this.

**Comment by juliuspf** [comment]
@App-State-Prof, I apologize for the delayed reply. How about the feature of "Reverse scaled items"? In that window you can assign variables as reverse scaled and the reliability analysis will treat them as flipped. As for saving a variable as flipped, you could just use the computed column functionality and reverse the variable. For instance, if the variable is Likert-scaled from 0-4, you could apply `4 - variable` in the computed column window. https://jasp-stats.org/2018/12/18/how-to-compute-columns-in-jasp/

**Comment by App-State-Prof** [comment]
Thank you Julius. I have experimented more with the computed column function. This is one activity I used to do in SPSS, then take the new data set into JASP.

**Comment by TarandeepKang** [comment]
I think that is perfectly easy to do recoding of variables using code (in the compute column window) but it would be ideal, I agree, be able to do this without any code implementing a recode feature that looks similar to SPSS. Not sure if you have it now, somewhere,, and I've just missed it. I agree that the necessary coding is very easy, but you know as well as I do that undergrads can get terrified of even the smallest piece of coding! :-)
