### ISSUE TITLE
Import threshold between Categorical or Scale does nothing and manual change of scale does not work.

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#1074]
On jasp 0.14.1-beta and earlier the import threshold does not work. I can change the value in settings => data - but my data is still imported as "scale" instead of being "ordinal". I also cannot change it to ordinal manually. Only to nominal text.

I used this file with grades to reproduce the problem
[grades.txt](https://github.com/jasp-stats/jasp-issues/files/5590470/grades.txt)

This happens on Win10 and Manjaro Linux with all file types (csv sav jasp)

**Comment by boutinb** [comment]
Hi @tomtomme In JASP, an Ordinal column must have only integers, there is now no possibility to have ordinal with decimals. . And if there are only decimals in the column, then JASP read it as a scale column per default. It could be set automatically as nominal text if the unique values of the column is less than the threshold, but it can be quite confusing I think...

**Comment by tomtomme** [comment]
quite confusing yes :)
Any chance that this could be improved in the future?
From a methodical standpoint there is really no reason for ordinal data to have or have not decimals. In fact there is nothing I know in statistics that differentiates between numbers with or without decimals. So why does jasp this?

**Comment by boutinb** [comment]
Unfortunately, this is not just a setting to enable... This would ask quite some work. This is the first time I hear about this request. @EJWagenmakers What do you think?

**Comment by tomtomme** [comment]
thx for the info. I can work around this problem. Would be nice for the future, but can be considered low priority then.
