### ISSUE TITLE
Please integrade Lambda (PRE measure) in Frequencies => contingency tables

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#1075]
Categorial measures of association can be grouped into two types: 
chi-squared, or PRE

Gamma is already implemented for ordinal scales, but lambda is missing in frequencies => contingency tables

Why its important: 
Chi-squared based measures of association like phi or V are considered weak and outdated (Bailey, 1994; Hanneman & Kposowa, 2012). This is mostly because of the vague results these measures supply: associations are “weak”, “moderate”, or “strong” and are not easily interpreted by non-statisticians. In addition, the numerical result doesn’t have much meaning to the layperson. For example, an association of .6 is not twice as strong as .3, so it can be difficult to compare results. On the other hand, the numbers given by a proportional reduction in error method do have that exact meaning: an association of .6 is exactly twice as strong as on with .3. This makes it the preferable method, especially in the social sciences, for reporting results for measures of association. (https://www.statisticshowto.com/proportional-reduction-in-error-pre-test - not the best source, I know)

**Comment by boutinb** [comment]
@Kucharssim Can you have a look to this request?

**Comment by TimKDJ** [comment]
Thanks for pointing out this missing functionality! It will be included in JASP version 0.15 (it won't be 0.14.1 yet)
