### ISSUE TITLE
Old values not discarded after sync with spreadsheet editor

### ISSUE THREAD

**Issue by djdekker** [jasp-stats/jasp-issues#1077]
* JASP version: 0.14
* OS name and version: macOS Big Sur 11.0.1
* Analysis: N/A – data editor
* Bug description: values from spreadsheet are not discarded after sync with spreadsheet editor
* Expected behaviour: after sync, only the up-to-date values should be shown and old values discarded

1. Open test.csv in JASP 0.14 and in a spreadsheet editor. Notice that **group** is a nominal variable.
2. Change the values in the first column from words into numbers.
3. Synchronize the spreadsheet with JASP (or have JASP autosync). JASP should now consider **group** an ordinal or scale variable.
4. After the sync JASP still displays the old values; seemingly, it did not sync.
5. But in fact, JASP did sync the values. The new values become visible when manually changing the variable type.
6. The old values, which have disappeared from the csv file, can still be displayed in JASP when changing **group** back to a nominal variable (perhaps they are cached somewhere?). I think this should not be possible.
7. This bug only occurs when the sync implies a change of data type (e.g., from nominal to ordinal).

[test.csv.zip](https://github.com/jasp-stats/jasp-issues/files/5592088/test.csv.zip)

[JASP_sync_problem.mp4.zip](https://github.com/jasp-stats/jasp-issues/files/5592132/JASP_sync_problem.mp4.zip)

**Comment by boutinb** [comment]
You are right when you suppose that these values are cached! I think I can easily solve it, but I'm not sure if it can be added in 0.14.1. I don't think it's such an important bug. Or is this blocking for you?

**Comment by djdekker** [comment]
Hi Bruno, thanks for your attention. No, it's not blocking at all, so please don't hurry to fix this.
