### ISSUE TITLE
Counts field in Contingency Tables JASP

### ISSUE THREAD

**Issue by PsychEliana** [jasp-stats/jasp-issues#1079]
Hi, could you please explain what the Counts field is used for in the Contingency Tables function? (notice I'm not asking about the Multinominal function but about the contingency tables function)

**Comment by vandenman** [comment]
If you look at the data set `Listerism` (available from `Data Library` -> `5. Frequencies` -> `Listerism`) you get:

![image](https://user-images.githubusercontent.com/21319932/100339686-7bb88b80-2fda-11eb-9cf9-b243b647134e.png)

So it's basically the frequency of how often each combination is observed.

**Comment by vandenman** [comment]
If you open the associated jasp file you also get annotated results for a Bayesian contingency analysis.
