### ISSUE TITLE
Bayesian Correlation Pairwise Plots using datapoints multiplied by 10

### ISSUE THREAD

**Issue by fplatz** [jasp-stats/jasp-issues#1081]
* JASP version: 0.15.1

* OS name and version: maOS Catalina (10.15.7)
* Analysis: Bayesin Korrelation Pairwise Plots (Kendalls Tau-B)
* Bug description: The values of both variables are multiplied by 10. My raw data correctly shows a value range from 1 to 6. However the values used in the plot ranges from 10 to 60.

Is there any solution to get plots using the raw data's range?

All the best
Friedrich

**Comment by vandenman** [comment]
Thanks for reporting the issue!

The current development version shows for me on Ubuntu plots with the range of the raw data. Did you perhaps mean JASP version 0.14.1?
Because I can't replicate the problem, could you perhaps add a .jasp file as a zip file to the issue, so I can see what went wrong?

**Comment by fplatz** [comment]
Thanks for your reply. The issue is also in Version 0.14. I opened JASP on a Mac. Please would you give me your mail address? I will sent you a copy of my JASP-file. 

Best wises,
Friedrich

**Comment by vandenman** [comment]
My email is d.vandenbergh <at> jasp-stats.org
