### ISSUE TITLE
KMO sampling adequacy and Bartlett's test for sphericity for principal component analysis

### ISSUE THREAD

**Issue by teapot82** [jasp-stats/jasp-issues#1083]
* Enhancement: SPSS has KMO sampling adequacy and Bartlett's test for sphericity, and it would be nice to have cumulative % variance by first 3 factors too. (I can do this manually by adding them up, but it would be nice if this was all singing and all dancing)
* Purpose: KMO index indicates the proportion of variance that might be caused by underlying factors, to decide whether or not PCA is appropriate. Bartlett's test is to look at whether the variables are related - another important test to decide appropriateness of PCA. Both of these are important in publishing PCA results so can't use JASP for PCA unfortunately.

**Comment by boutinb** [comment]
@EJWagenmakers can lnwhi do this?

**Comment by EJWagenmakers** [comment]
Possibly. We have several students that are interested in contributing...

**Comment by EJWagenmakers** [comment]
Also, note that these options *are* available in our EFA function. Strange.

**Comment by AlejandroPeru** [comment]
PCA no es análisis factorial.
