### ISSUE TITLE
Coefficient of Variation

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#1084]
Please add the coefficient of variation `v = standard deviation / mean` in JASPs Descriptives section.
There are other relative measures of variation, but this is the most common one and mostly easier to interpret if you want to compare the variation across multiple datasets with different means.
Thx.

**Comment by boutinb** [comment]
This is a really easy thing to add. Maybe someone who starts to work for JASP could do that. @EJWagenmakers: among the student assistent, there is someone that could do that.

**Comment by tomtomme** [comment]
is there a tutorial how / where to start? I would like to dig into this myself. I have the repository cloned here and I can read the code. But I did not write code except php html css and a bit matlab & R years ago. I do not even know which language I am looking at... so is there a chance I could learn this in a few hours?
Maybe it makes even sense to just look at the commits of the student assistent that claims this, to learn? What do you think?

**Comment by boutinb** [comment]
It would be great if you want to try!
The interface is written in QML: https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/development/jasp-qml-guide.md. Here you just have to add a Checkbox.
The analyses are written in R: https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/development/r-analyses-guide.md. You can have a look how Descriptive.R is written. 

It's maybe a lot to learn now. We are planning to make workshops for people willing to make new modules, but I'm afraid not before next summer.

**Comment by EJWagenmakers** [comment]
No, but I think we should we willing to provide personalized instruction in this case.  And we also have at least one student (Jan) who is eager to start. So maybe we can be efficient and someone could do a zoom meeting guiding them through the process? Adding the CV would be a good start...actually, someone from the company we are working with might like that instruction as well, so then we already have 3 people who could contribute. I think we ought to facilitate this.
E.J.

**Comment by tomtomme** [comment]
I like the idea. Atm I could zoom-meet best Friday to Sunday or Tuesday after 13:30 or Thursday before 13:30. Also almost every evening after 20:30 when the kids hopefully sleep :D

**Comment by boutinb** [comment]
Hi @tomtomme Sorry for the late answer. We are going to give a small workshop (2 hours) on how to change or add a new JASP module. This will be for people having already experience in programming and in R in particular.
There are already some documentation in our GitHub you can read before the workshop:

- https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/development/jasp-adding-module.md
- https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/development/jasp-module-workflow.md
- https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/development/jasp-qml-guide.md
- https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/development/r-analyses-guide.md
- https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/development/r-style-guide.md
- https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/development/jasp-human-guide.md

If you have some issues you would like to be treated during the workshop, tell us already.

We thought of Wednesday 10 februari or Thursday 11 februari at 14:00. Could you?

**Comment by tomtomme** [comment]
The Thursday is possible. Thx!

**Comment by boutinb** [comment]
Hi Thomas,

Maybe you can give your real email address, then I can inform you about the workshop directly.


Cheers,
Bruno


________________________________

**Comment by tomtomme** [comment]
Its already on my profile: 
thomas.langkamp@medicalschool-hamburg.de

**Comment by tomtomme** [comment]
I just added it myself - hopefully I did everything correct? this is my first pull request ever and the last time I wrote R is 10 years away...
https://github.com/jasp-stats/jaspDescriptives/pull/20
