### ISSUE TITLE
Bayesian GLMM Terminated Unexpectedly 

### ISSUE THREAD

**Issue by TarandeepKang** [jasp-stats/jasp-issues#1086]
* JASP version:  14.1

* OS name and version: macOS Big Sur
* Analysis: Bayesian GLMM
* Bug description:This analysis terminated unexpectedly.

Error in if (var_name ≠ 'Intercept' && nrow(temp_summary) > 1) {: missing value where TRUE/FALSE needed

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.mmRunAnalysis(jaspResults, dataset, options, 'BGLMM')

.mmSummaryStanova(jaspResults, dataset, options, type)
* Expected behaviour: BGLMM should present results 

#### Steps to reproduce:
Run BGLMM on dataset

I am working as part of a project led by @EJWagenmakers, and we are under specific instructions not to share data.

**Comment by FBartos** [comment]
Hi,

the no data sharing restriction makes the situation a bit more challenging. Could you first try loading and refreshing the results of this file [debug.zip](https://github.com/jasp-stats/jasp-issues/files/5608949/debug.zip) (it needs to be unzipped first).
If this file works, could you recreate the problem with a similar/simulated dataset that you would be able to share?

Also, you said that you are running version 0.14.1. The official release is 0.14.0, so, is that a nightly build?

Best
Frantisek

**Comment by TarandeepKang** [comment]
Your debug dataset worked fine, which led me to believe I had somehow misspecified the model . Indeed, I made a stupid mistake. Everything now works fine! :-)
