### ISSUE TITLE
Can't se all column in Rollapp JASP

### ISSUE THREAD

**Issue by Jessietif** [jasp-stats/jasp-issues#1087]
* JASP version: Rollapp

* OS name and version:
* Analysis: 
* Bug description: I have a data set with several columns and cannot see the right hand ones as the analysis screen is in the way and I can't minimise it anymore. is there a way to scroll right to see and edit all the columns in the screen??
* Expected behaviour:

**Comment by JorisGoosen** [comment]
Can't you just scroll in the data?

**Comment by JorisGoosen** [comment]
If not, please attach a screenshot.

On the other hand, we will be releasing a new JASP this coming week (or the next) and it will also include a Rollapp update.
So that might solve the problem. The current Rollapp version is pretty old btw.
