### ISSUE TITLE
Translation of headers not shown after language switch

### ISSUE THREAD

**Issue by djdekker** [jasp-stats/jasp-issues#1088]
* JASP version: 0.14
* OS name and version: macOS Big Sur 11.0.1
* Analysis: any
* Bug description: In the results pane, the translation of the headers is not shown after switching the interface language
* Expected behaviour: Translated headers should be shown after switching the interface language

1. Open a data set.
2. Open 'Descriptives':
![before](https://user-images.githubusercontent.com/5346286/100537360-325d7b80-3228-11eb-8f1d-3aa7b1d0d967.jpg)
3. Switch the interface language.
4. The header is actually translated, but the translation is not shown:
![after](https://user-images.githubusercontent.com/5346286/100537361-36899900-3228-11eb-87ec-f3c32d89b62d.jpg)
5. You can see that this is a display issue, not a translation issue, when you switch the interface language again.

[test.csv.zip](https://github.com/jasp-stats/jasp-issues/files/5611897/test.csv.zip)

**Comment by JorisGoosen** [comment]
Also happens on Windows.

**Comment by JorisGoosen** [comment]
I will not be fixing this in 0.14.2 but will make sure 0.15 does this properly.
