### ISSUE TITLE
This analysis terminated unexpectedly. Error prompted upon selecting 'Equality of Variances' assumption check.

### ISSUE THREAD

**Issue by Honskreutz** [jasp-stats/jasp-issues#1089]
* JASP version: 0.14

* OS name and version: macOS Catalina 10.15.5
* Analysis: Indépendant samples t-test
* Bug description: 
This analysis terminated unexpectedly.
Error in .ttestIndependentEqVarFill(equalityVariance, dataset, options): object 'result' not found
* Expected behaviour:

#### Steps to reproduce:
1. Select independent samples t-test
2. Select Time' and 'Measurement' variables
3. Select 'Group' grouping variable
4. Select 'Equality of variances' assumption check
5. See error

**Comment by Honskreutz** [comment]
[Unexpected_Termination_Error_MSG.xlsx](https://github.com/jasp-stats/jasp-issues/files/5612671/Unexpected_Termination_Error_MSG.xlsx)

**Comment by djdekker** [comment]
No error here with JASP 0.14 on macOS Big Sur 11.0.1:
<img width="764" alt="error" src="https://user-images.githubusercontent.com/5346286/100551170-5304f000-327f-11eb-8258-0198541256c9.png">

**Comment by boutinb** [comment]
Hi, on MacOS Mojave, it works also without error.
Could you give the whole call stack of the error?

**Comment by boutinb** [comment]
Quite strange indeed. I have tried your reproduction path in all orders, but could not find the error. If it happens again, please give the whole call stack of the error.
