### ISSUE TITLE
DV in regression results

### ISSUE THREAD

**Issue by App-State-Prof** [jasp-stats/jasp-issues#109]
It would be great for students if the linear regression test results would include the dependent variable for each test. They sometimes copy and save results, but forget to mark the DV. Thank you.

**Comment by tomtomme** [comment]
@App-State-Prof 
The DV is included in the Model summary table since some time. 
Is this sufficient to close this issue?

**Comment by App-State-Prof** [comment]
Yes, I have noted the DV in the model summary. Thank you.
