### ISSUE TITLE
Help AFC Bifactor

### ISSUE THREAD

**Issue by AlejandroPeru** [jasp-stats/jasp-issues#1091]
Existirá la manera de realizar AFC bifactor en JASP. Si me podrían compartir una guía estaría agradecido.

**Comment by EJWagenmakers** [comment]
There is this moving gif showing how it is done in our CFA: https://jasp-stats.org/wp-content/uploads/2020/09/CFA.gif 
You can also do this through our lavaan-SEM module (https://www.youtube.com/watch?v=rmpgUrfT_XY).
