### ISSUE TITLE
JASP won't open on Win 10

### ISSUE THREAD

**Issue by Hardknox51** [jasp-stats/jasp-issues#1092]
* JASP version: 0.14.0.0 (tried both 32 and 64 bit versions)

* OS name and version: Windows 10 Home, version 2004, OS Build: 19041.630
* Analysis: JASP will not open
* Bug description: JASP window briefly tries to open, nothing comes up, then immediately closes
* Expected behaviour: To open normally, windows compatibility test reports the program is incompatible

**Comment by boutinb** [comment]
Hi @Hardknox51 Could you send us the JASP log files (https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/user-guide/logging-howto.md) ?

**Comment by Hardknox51** [comment]
Unfortunately, this is all I get in the log files.

'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

**Comment by boutinb** [comment]
Is it what you find in the Desktop or Engine log file (can you send me the files?), or it what you get when you try to start JASP from the command line?

**Comment by Hardknox51** [comment]
From both, because it won't open I followed the command line prompts you
provided to no avail, not sure what to do now. It worked fine when I first
downloaded it weeks ago, now it will not open. Some update must be
preventing it

**Comment by Hardknox51** [comment]
startup log attached

**Comment by JorgeCamachoS** [comment]
Hi, i have the same problem but after the windows 10 thuesday 12 update, JASP is working again.

**Comment by boutinb** [comment]
Hi @Hardknox51, do you have still problem to open JASP ?

**Comment by Lokis123** [comment]
Hi @boutinb! I have a similar issue. JASP won't start on my computer and after enabling logging to my '%USERPROFILE%\AppData\Roaming\JASP\JASP\Logs folder' the only logs that appear are called 'startup.log' and 'JASP <DATE> <TIME> Desktop.log'. The latter contains: 

> JASP 0.14.1 from commit <.......> and branch stable is continuing initialization.
> interprocess exception! No access. 

What specifically is JASP trying to access? I have limited rights on this machine as it is my work system. I imagine that could be part of the issue.

**Comment by boutinb** [comment]
Hi @Hardknox51 I think @Lokis123 found the problem: https://github.com/jasp-stats/jasp-issues/issues/1433. You need to have write permission to the folder %ALLUSERSPROFILE%\boost_interprocess

**Comment by boutinb** [comment]
If this problem persists, reopen it.
