### ISSUE TITLE
Engine crash when rescaling model averaged posteriors

### ISSUE THREAD

**Issue by MichlF** [jasp-stats/jasp-issues#1094]
* JASP version: 0.14

* OS name and version: Windows, most recent
* Analysis: ?
* Bug description: "The engine crashed while trying to run this analysis..." error when trying to rescale plots.
* Expected behaviour: Proper graph rescaling

#### Steps to reproduce:
1. Load "Looks or Personality" data set from data library.
2. Run a Bayesian RMANOVA in the same way the already provided standard RMANOVA is done.
3. Check Plots -> Model averaged posteriors and attempt to rescale one of the plots.

Works over an over again even when I duplicate or redo analysis.

**Comment by vandenman** [comment]
Unfortunately, I can't replicate this problem on Ubuntu. Could you perhaps share the log files in the issue? You can find these in the menu below:

![image](https://user-images.githubusercontent.com/21319932/101748644-1c27a900-3acd-11eb-964f-347c2e4721da.png)

**Comment by MichlF** [comment]
Sure
[JASP 2020-12-10 11_06_14 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/5671863/JASP.2020-12-10.11_06_14.Desktop.log)

**Comment by vandenman** [comment]
Just to double-check, there is only a log of the Desktop and there are no logs of the engines?

For comparison, JASP should create one log file for the Desktop and four log files for the Engines.
![image](https://user-images.githubusercontent.com/21319932/101760729-87787780-3adb-11eb-8077-b09920144a23.png)

**Comment by MichlF** [comment]
Yes sorry. 
[JASP 2020-12-10 11_06_14 Engine 2.log](https://github.com/jasp-stats/jasp-issues/files/5672122/JASP.2020-12-10.11_06_14.Engine.2.log)
[JASP 2020-12-10 11_06_14 Engine 3.log](https://github.com/jasp-stats/jasp-issues/files/5672123/JASP.2020-12-10.11_06_14.Engine.3.log)
[JASP 2020-12-10 11_06_14 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/5672124/JASP.2020-12-10.11_06_14.Engine.0.log)
[JASP 2020-12-10 11_06_14 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/5672125/JASP.2020-12-10.11_06_14.Engine.1.log)

**Comment by juliuspf** [comment]
@MichlF, I apologize for this late reply, but could you confirm this is still an issue with the latest JASP version?

**Comment by tomtomme** [comment]
@MichlF 
I tested with said file and settings in 0.18.3 and all worked fine.
If this is not fixed on your side, feel free to reopen.
