### ISSUE TITLE
JASP crashes on open after MacOSX install

### ISSUE THREAD

**Issue by skyea2** [jasp-stats/jasp-issues#1097]
* JASP version:0.14.0.0 Catalina

* OS name and version: macOS Catalina 10.15.6
* Analysis: I have tried several times to install JASP...both Catalina and preCatalina. I have tried moving an old version to trash, and even restarting my computer after install. Every time I click on the app to open it, it bounces as if it is, then says it is verifying the program, and then never actually executes the open to completion and simply disappears from the dock where it was trying to open
* Bug description: App doesn't open
* Expected behaviour: App should open when clicked

**Comment by JorisGoosen** [comment]
Sorry to hear it!

Could you help us fix your problem by following the steps in: https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/user-guide/logging-howto.md ?

Im guessing that in this case it would be useful if you copy both the logfiles and the output of `./JASP --logToFile` (see the manual I sent).
