### ISSUE TITLE
Add corrections for multiplicity to multiway ANOVA

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-issues#11]
@raviselker: it would be nice to add the possibility to correct p-values from multiway ANOVA for multiplicity. See http://arxiv.org/abs/1412.3416 and https://github.com/singmann/afex/pull/3. Another way to add something that SPSS lacks. I think this option should not be default, but available through a checkbox instead. 
Cheers, E.J.

**Comment by PsyTechMMU** [comment]
Is there any plan for the uncorrected p-value to return as an option?

**Comment by EJWagenmakers** [comment]
Wait, this is an old issue that was never properly addressed, it seems. @JohnnyDoorn, want to discuss this?

**Comment by tomtomme** [comment]
@EJWagenmakers 
So this seems closely related to #86 - and even references the same paper of Cramer.
I think we can close this one and track both issues in #86 so that they can be fixed in one go.
