### ISSUE TITLE
Decision trees, cluster analysis, text analysis?

### ISSUE THREAD

**Issue by App-State-Prof** [jasp-stats/jasp-issues#110]
I realize this is all of my dreams in one place; however for university teaching, adding decision trees, cluster analysis and text analysis to JASP? At present we use Radiant for trees, KH-Coder for text. If JASP would add the three functions above, you would have everything in one place.

**Comment by koenderks** [comment]
With the exception of text analysis, JASP 0.16.1 will offer both requests: cluster analysis and decision trees. Therefore I will close this issue. If text analysis is still on your wish list, please make a new issue for it so that it is on top of the list!
