### ISSUE TITLE
CIs for std(all) in SEM

### ISSUE THREAD

**Issue by MykolasSimasPoskus** [jasp-stats/jasp-issues#1102]
* Enhancement: Add confidence intervals for the std(all) column in SEM
* Purpose: Most publications require CIs
* Use-case: I've been requested by several reviewers to provide CIs for standardized beta weights in SEM. I either explained that the software does not output them or had to use other software for modelling. I would really love to have to use just JASP.

**Comment by MykolasSimasPoskus** [comment]
Just wanted to check in if this is being looked into.

**Comment by boutinb** [comment]
Hi @MykolasSimasPoskus, sorry for the late answer. Maybe can @Kucharssim have a look?

**Comment by juliuspf** [comment]
@LSLindeloo, could you have a look? I think it is kind of simple to obtain output with `lavaan`

**Comment by LSLindeloo** [comment]
@juliuspf sure! I will add them, that should be simple indeed! It’s also possible to show just either standardized or unstandardized coefficients. @Kucharssim , what’s your take on this ?

**Comment by tomtomme** [comment]
@areeq1 & @MykolasSimasPoskus 

This is actively being worked on. See https://github.com/jasp-stats/jaspSem/pull/122
