### ISSUE TITLE
When using "Developer mode" Engine Crash when plotting prior/posterior Bayesian Paired Samples T-Test

### ISSUE THREAD

**Issue by JohnnyDoorn** [jasp-stats/jasp-issues#1103]
* JASP version: 14.1

* OS name and version: Ubuntu 20.04
* Analysis:  Bayesian Paired Samples T-Test
* Bug description: Engine crashes
* Expected behaviour: Engine does not crash
Any data file, run Bayesian paired samples t-test between any 2 continuous/scale variables, and plot prior/posterior. See attached jasp file (change extension)
[debugCrashEngineWhenPlotPriorPosterior.zip](https://github.com/jasp-stats/jasp-issues/files/5711317/debugCrashEngineWhenPlotPriorPosterior.zip)

Commit https://github.com/jasp-stats/jasp-desktop/commit/f2cb223fef6b15089fd6e9da54825d370c1ece57

**Comment by AlexanderLyNL** [comment]
I can replicate this with 0.14.1 on macOS 10.13.6.

**Comment by AlexanderLyNL** [comment]
The error only occurs in Bayesian paired, not in the other Bayesian t-tests.

**Comment by AlexanderLyNL** [comment]
Solved if "Developer mode" is turned off. This bug will disappear automatically when we restructure the code.

**Comment by JohnnyDoorn** [comment]
Confirmed!

**Comment by vandenman** [comment]
this is not an R issue but something weird about enabling developer mode that leads to crashes in R. @JorisGoosen could you explain to me what exactly developer mode does?

**Comment by TimKDJ** [comment]
Relevant:
https://github.com/jasp-stats/INTERNAL-jasp/issues/530
https://github.com/jasp-stats/INTERNAL-jasp/issues/656

**Comment by JorisGoosen** [comment]
Well developer mode only changes 1 thing and that is processing the dependencies that are given to a jaspObject and making sure they are used in QML. 
(which Tim just alluded to with the two links)

And it is caused by people putting stuff in `mustContain` that isnt actually supported.

**Comment by JorisGoosen** [comment]
So probably removing that from the code here would fix the crash. Because I am not in any particular hurry to fix the code for it.

**Comment by JorisGoosen** [comment]
I think it might be this: https://github.com/jasp-stats/jaspTTests/blob/2e53ee5981d5996ee28dda90ab9b888c0ee0fe73/R/commonbayesianttest.R#L794

Because I don't see why there would be three vectors in a list as depencies?

**Comment by JorisGoosen** [comment]
So to fix it would be to check those `optionContainsValue` and change them to single values and probably it won't crash anymore.
And actually these dependencies do not work at all, so it would be good to remove them, or to implement https://github.com/jasp-stats/INTERNAL-jasp/issues/656

**Comment by vandenman** [comment]
Okay, I'll look into the R side. But I don't think a mistake like this should crash the engine.

**Comment by JorisGoosen** [comment]
> Okay, I'll look into the R side. But I don't think a mistake like this should crash the engine.

You are right! But how to fix it wasn't obvious to me before and I really didnt expect people to do this.. But that just shows me I have a lack of imagination.
