### ISSUE TITLE
S.S. Bayesian Correlation: Prior-Posterior Plots are Not Updating

### ISSUE THREAD

**Issue by ASarafoglou** [jasp-stats/jasp-issues#1104]
* JASP version: 0.14 and higher

* OS name and version: macOS Catalina 10.15.7
* Analysis: S.S. Bayesian Correlation
* Bug description: When you change the Alt. Hypothesis in the Bayesian Correlation the prior and posterior plot is not updating.
* Expected behaviour: The plot should be redrawn (or update) if the Alt. Hypothesis is redefined

#### Steps to reproduce:
1. Go to S.S. Bayesian Correlation
2. Insert '47' as sample size and '0.3' as Pearson Correlation. Plot the prior and posterior.
3. Change Alt Hypothesis to 'Correlated positively'
4. The plot did not change
5. You need to change the actual correlation (e.g., 0.3-> 0.31) to force the update. Probably you need to change the dependencies.

Running the Analysis
![Screen Shot 2020-12-18 at 4 10 33 PM](https://user-images.githubusercontent.com/20499997/102629585-a0bc9c00-414b-11eb-9fc7-c2a6c861ed9b.png)

After changing the Alt. Hypothesis: Table updates, but the plot is the same
![Screen Shot 2020-12-18 at 4 10 43 PM](https://user-images.githubusercontent.com/20499997/102629596-a3b78c80-414b-11eb-86bb-a1e7b3de2871.png)

**Comment by akashrajkn** [comment]
I can reproduce this on `v0.14.1` (although parts of the plot seem to change). I will fix it this week

**Comment by amirmasoudabdol** [comment]
@koenderks is this still an issue?

**Comment by koenderks** [comment]
No idea, i cannot build the current version. If this occurs in 0.16.1 then I'm sure this is still an issue

**Comment by akashrajkn** [comment]
Yup, on 0.15, this is still an issue

**Comment by AlexanderLyNL** [comment]
Not an issue in CMake 0.16.2: https://github.com/jasp-stats/jasp-desktop/commit/db130a83190c4d654efc0e3a5d9b7b5805ad8423

**Comment by amirmasoudabdol** [comment]
I can see that it's fixed on the latest nightly as well!
