### ISSUE TITLE
improve tooltips on ribbon icons 

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-issues#1106]
The tooltips for the ribbon icons seem mostly redundant (e.g., "This module offers X" with the icon called "X") -- can we remove them please?
E.J.

**Comment by JorisGoosen** [comment]
Sure, what we could also do is make them more sensible?
The tooltip is basically the "Description" field of a module, so it could easily be made more informative.

But I can also just remove them entirely.

**Comment by tomtomme** [comment]
Would be unfortunate. Maybe I can improve the descriptions? I just need a hint which files to modify. I also do not know if I have access yet. Github-Desktop just shows me the testing-repository. So I guess not.

**Comment by JorisGoosen** [comment]
Well if you want to give it a go, each of the modules has now their own repository. An example is: https://github.com/jasp-stats/jaspDescriptives/ or https://github.com/jasp-stats/jaspAnova/ .

Each of those modules then contains `Description.qml` in `inst` as: https://github.com/jasp-stats/jaspAnova/blob/master/inst/Description.qml

In there you can find the field `description` where a string is surrounded by `qsTr(...)` and that last part is necessary for translation of the description to work.

**Comment by EJWagenmakers** [comment]
You could email me the suggestions, or the link to a Google doc so we can do edits easily.

**Comment by JorisGoosen** [comment]
EJ's suggestion sounds like a lot less work for you Thomas.
If you two work these descriptions out in a googledoc then I could put them in the modules, in a quicker way than opening and merging PRs per module.

**Comment by tomtomme** [comment]
Cool :) I will try to come up with some ideas until the end of the week. Cheers :)

**Comment by tomtomme** [comment]
Here the new tooltips for JASP 
https://docs.google.com/document/d/1cRwkGsj0xDQQ-h5pD6rL1eFg4ipPzCnF7Mied6DnoZM/edit?usp=sharing 

It was a bit more work than anticipated, but a great learning experience.
German-to-english translation mainly via www.DeepL.com/Translator (free version). Would be nice if a native speaker could check this :D
At some point I thought, it would be nice to also give some typical examples for every analysis like I have done in Machine Learning. But I guess some of the tooltips are already a bit on the long side. So if someone can condense them, without sacrificing too much, that would be nice.
There are tooltips marked with * that are not altered yet or where I was unsure.

**Comment by JorisGoosen** [comment]
@EJWagenmakers did you have a chance to look at Thomas' suggestions?

**Comment by AlexanderLyNL** [comment]
I've added some suggestions to the doc.

**Comment by tomtomme** [comment]
Thanks, but what is the idea behind those. Are they additions or replacements?

**Comment by JorisGoosen** [comment]
I'm fairly sure he meant those as replacements to get the sentences a bit shorter. I've asked Alexander to make the changes directly in the doc instead of putting them next to it like before.

**Comment by tomtomme** [comment]
Interesting. I thought the idea was to make the tooltips more verbose for newcomers. I guess it makes sense to stick to one paradigm. If we make some tooltips short and others longer... would look weird, wouldn't it?
________________________________________
Von: Joris Goosen ***@***.***>
Gesendet: Dienstag, 13. April 2021 15:36:58
An: jasp-stats/jasp-issues
Cc: Thomas Langkamp MSH Hamburg; Comment
Betreff: Re: [jasp-stats/jasp-issues] Remove mouse-overs /tooltips on ribbon icons  (#1106)

I'm fairly sure he meant those as replacements to get the sentences a bit shorter. I've asked Alexander to make the changes directly in the doc instead of putting them next to it like before.

**Comment by EJWagenmakers** [comment]
I personally like all tooltips to be as short as possible. I'll take a look tonight though

**Comment by tomtomme** [comment]
ok. then we had a misunderstanding as you said that the original tooltips were too short.... thus I created those longer ones.
________________________________________
Von: EJ ***@***.***>
Gesendet: Dienstag, 13. April 2021 17:39:53
An: jasp-stats/jasp-issues
Cc: Thomas Langkamp MSH Hamburg; Comment
Betreff: Re: [jasp-stats/jasp-issues] Remove mouse-overs /tooltips on ribbon icons  (#1106)

I personally like all tooltips to be as short as possible. I'll take a look tonight though

**Comment by EJWagenmakers** [comment]
Oh, I apologize for the confusion. I can't recall complaining about them being too short...(in the above, you'll see I argued they are mostly redundant) -- or was this someone else? Anyway, I will look now. (I was too optimistic about doing it yesterday evening)

**Comment by EJWagenmakers** [comment]
OK, so I went over the tooltips and proposed some changes. I like the tooltips to start with a verb (e.g., Explore / Evaluate / Quantify...etc). Anyway, I think that (with the exception of audit, but I let that slide) this is consistent and concise.

**Comment by tomtomme** [comment]
Nice :)

The misunderstanding is on my head. I made "being redundant"
to "being to short" in my head.
I think: Take what you like from my work. It was fun anyway. I wrote my
tooltips with my students in mind, and thus they are a bit on the long
side. Long tooltips are unconventional for sure, but I think they can be
worth it if they save a student from the need to look into the way
longer help-texts.

**Comment by EJWagenmakers** [comment]
Well it certainly made us think better about what we want to tooltips to be. If we have very many of them we could have a central option in preferences ("verbose" or "concise") but presently it does not seem worth it, The thing is also that the top vanishes after 2 seconds or so. Actually, I am not sure why it should time out at all -- removing it on mouse movement alone seems sufficient, and having it on the screen longer allows users more time to read it (or discuss it in class). @JorisGoosen what do you think?

**Comment by JorisGoosen** [comment]
Yeah, having it time out doesn't seem sensible indeed. I'll see if I can prolong that.
