### ISSUE TITLE
Error in Producing Bayesian Generalized Linear Mixed Models

### ISSUE THREAD

**Issue by mmcphedr** [jasp-stats/jasp-issues#1107]
* JASP version: 0.14.1
* OS name and version: Windows 10 Home, Version 1909
* Analysis: Bayesian Generalized Linear Mixed Effects Model --> Dependent variable is RT, fixed effects are sq and rel, random effects are sub and it (need to convert to either nominal or ordinal data before analyzing). Family is Inverse Gaussian (link = Identity)
* Bug description: When I include Subject and Item as random effects in the model, the model runs into this error: 

> This analysis terminated unexpectedly. 
> 
> Error in `[.data.frame`(dataset, , .v(x)): undefined columns selected
> 
> Stack trace
> analysis(jaspResults = jaspResults, dataset = dataset, options = options)
> .mmRunAnalysis(jaspResults, dataset, options, 'BGLMM')
> .mmFitModelB(jaspResults, dataset, options, type)
> .mmModelFormula(options, dataset)
> sapply(temp_terms, function(x) typeof(dataset[, .v(x)]) = 'double')
> lapply(X = X, FUN = FUN, ...)
> FUN(X[[i]], ...)
> dataset[, .v(x)]
> `[.data.frame`(dataset, , .v(x))
> stop('undefined columns selected')

* Expected behaviour: JASP should provide me with Bayes Factors for fixed effects and interactions.

#### Steps to reproduce:
1. Go to [this link](https://drive.google.com/file/d/1ARKLGTTL2EMx6PNsNFK1CKLl4bJQr96A/view?usp=sharing) to download the .csv that I am using. Open it in JASP. Change "sub" and "it" to ordinal/nominal variables (they should be scale when loaded)
2. Click on "Mixed Models" --> Bayesian Generalized Linear Mixed Models
3. Change family to "Gamma" or "Inverse Gausian", keep "Link" as "Identity"
4. Input "rt" as dependent variable, "sq" and "rel" as fixed effects variables, and "sub" and "it" as Random effects grouping factors
5. The error quoted above should be produced.

**Comment by FBartos** [comment]
Hi @mmcphedr ,

thanks for reporting the issue and sharing the dataset with instructions - it helped me a lot with this issue. 

There seems to be some interplay between the variable names and our JASP code. We are probably not going to be able to fix this issue immediately, however, I found a workaround that allows you to work with the dataset - adding "var_", or another prefix in front of the variable names. I'm attaching a [.JASP](https://drive.google.com/file/d/1hcN7Xfc4ih2lhTMMJqoFE_HpDKswdf7a/view?usp=sharing) file that executes the specified analysis using this trick (note that the gamma model has problems with convergence, it took more than an hour to fit it and the shape parameter has ESS of 2).

Sorry for the inconvenience,
Frantisek

I'm not completely sure what's causing the problem, but it's not an issue on the development branch (maybe @TimKDJ will know more).

**Comment by TimKDJ** [comment]
On the `development` branch we've turned on automatic column encoding. So `.v()` et al. doesn't actually do anything anymore. If this bug doesn't render the analysis completely useless and only occurs in specific cases (i.e., is not a reason for 0.14.2), then we can just wait for 0.15 and won't need to bugfix.

**Comment by FBartos** [comment]
I checked the analysis and verified that this issue is now fixed. 

The same issues were:
https://github.com/jasp-stats/jasp-issues/issues/1276
https://github.com/jasp-stats/jasp-issues/issues/1521
https://github.com/jasp-stats/jasp-issues/issues/1469
