### ISSUE TITLE
Variable Window broken in flatpak 0.14.1

### ISSUE THREAD

**Issue by TrevorMilliron** [jasp-stats/jasp-issues#1109]
* JASP version: 0.14.1

* OS name and version: Chromebook - Linux Beta (most recent)
* Analysis: 
* Bug description: When I click on a variable header to change labels, the screen expands above the sheet for the variable as usual, but the labels are missing.
* Expected behaviour: I expect to see the nominal categories as listed in the data sheet ready to be named.

#### Steps to reproduce:
1. Go to '...' the datasheet
2. Click on '....' column name (pops up "click here to change labels" prior to click)
3. See error

**Comment by JorisGoosen** [comment]
Aah, yeah that is too bad.
I can reproduce this and it seems the changing to nominal *does work* but the label-editing widget broke after upgrading to a newer version of qt...

**Comment by JorisGoosen** [comment]
The variableswindow has been replaced by a new component and should now work.
There should be a small release soon to make it available.

**Comment by JorisGoosen** [comment]
The new release is building now and should be available for download some time tomorrow.

**Comment by TrevorMilliron** [comment]
Wonderful! Thanks for your work on this!

Trevor

**Comment by JorisGoosen** [comment]
The new window has slightly weird selecting of rows, but I'll be fixing it up for our upcoming release. (Which will take a while longer)
At least it shows the labels and you'll be able to edit them.

And you're welcome!
