### ISSUE TITLE
[0.14.1.0] Crashing when deleting factor in repeated measures ANOVA

### ISSUE THREAD

**Issue by pablrdriguez** [jasp-stats/jasp-issues#1110]
* JASP version: 0.14.1.0

* OS name and version: Windows 10 20H2
* Analysis: Repeated measures ANOVA 
* Bug description: when trying to delete a factor (or a level), the program crashes without warning or error message

**Comment by JorisGoosen** [comment]
Could you upload a jasp-file from the situation *before* it crashes?
That way I know Im doing the same thing as you did before the crash.

**Comment by JorisGoosen** [comment]
If I try this out with the included data file "Alcohol Attitudes" JASP does not crash in 0.14.1 on Windows.
Seeing as @pablrdriguez did not upload a datafile for me that I can use to verify his problem I am now closing this issue.
