### ISSUE TITLE
Request: cfa with ordinal data

### ISSUE THREAD

**Issue by nicovizioli** [jasp-stats/jasp-issues#1113]
Hello. I think that this is an old request, but having the possibility of perform cfa with ordinal data could be from help for a lot of redearchers. For example, most scales or questionnaires requiere working with likert type data.
Cfa with ordinal data may be more helpful than efa with ordinal data too, because thete isnt a factor like software to perform cfa. 
Best regards

**Comment by boutinb** [comment]
It is still possible to change an Ordinal column into a Scale column (click on the Ordinal icon of the column, a pop-up menu should appear and choose the scale type). 
But the restriction to scale data seems to me too strong indeed. @vandenman is there any reason why the factors must be of scale type? If there is no reason, then I can just change the restriction from Allowed to Suggested.

**Comment by juliuspf** [comment]
This is also tracked here: https://github.com/jasp-stats/jasp-issues/issues/1723. But yes. It would be helpful. Let's see how fast I can get to it.
