### ISSUE TITLE
RM ANOVA: Error while loading data, please verify your repeated measures observations

### ISSUE THREAD

**Issue by emilyhanxiao** [jasp-stats/jasp-issues#1114]
* JASP version: 0.14.1

* OS name and version: Windows 10 (October 2020 Update)
* Analysis: repeated measures ANOVA
* Bug description: When loading repeated measures cells, there is still a chance that (according to previous reports) JASP would not recognize the RM label and produce the error message "Error while loading data, please verify your repeated measures observations". 
![图片](https://user-images.githubusercontent.com/76928229/103497031-3f185500-4e0e-11eb-9a0d-84a75d6706e1.png)

* Expected behaviour: Better consistency in recognizing RM labels
* Note: While the bug is mitigated after changing all the RM labels to letters only, without numbers, this bug still presents an inconsistency in the solution of [the previously solved bug](https://github.com/jasp-stats/jasp-issues/issues/358). It only appears unpredictably on some files among many that follow the same format, not all.

#### Steps to reproduce:
1. Open attached file
2. Select "Repeated measures ANOVA"
3. Add "pre" "day1" or any of the date labels to "Repeated measures cells"

[ABR_Tone8k_chan2_wave5_30dBSL_4JASP.zip](https://github.com/jasp-stats/jasp-issues/files/5762809/ABR_Tone8k_chan2_wave5_30dBSL_4JASP.zip)

**Comment by JorisGoosen** [comment]
I think we fixed this in our development version, but it might not have been ported back to stable.
I will have a look.

**Comment by JorisGoosen** [comment]
Well, it has been fixed in 0.15. But the fix is rather hard to port over as it requires quite a few changes to the communication between JASP and it's internal R...
I'm afraid that you will have to wait for that release, hopefully it will be out in a few months.
