### ISSUE TITLE
Analysis Terminated Unexpectedly

### ISSUE THREAD

**Issue by Tlee298** [jasp-stats/jasp-issues#1115]
* JASP version: 0.13.1

* OS name and version: Windows 10
* Analysis: Bayesian Contingency Tables
* Bug description:
* This analysis terminated unexpectedly. 

Error in .contTabBasComputeBF(options, grp.mat[[g]], ready): trying to get slot 'bayesFactor' from an object (class 'try-error') that is not an S4 object 

Stack trace
* Expected behaviour:

**Comment by boutinb** [comment]
Hallo @Tlee298 You wrote that you use 0.13.1. Can you try the last version 0.14.1? If this error still occurs, can you describe exactly the steps in JASP to reproduce this error. It would be even better if send us a JASP file (via GitHub in zip format) where we can reproduce this problem.
