### ISSUE TITLE
Reliable version indicator on website or releases

### ISSUE THREAD

**Issue by adamblake** [jasp-stats/jasp-issues#1116]
* Enhancement: Reliable method of retrieving recent release programmatically
* Purpose: Easier for automatic update and install software to get latest version
* Use-case: User runs `cup jasp` with [chocolatey](https://chocolatey.org/packages/jasp)

**Is your feature request related to a problem? Please describe.**
I maintain the [chocolatey](https://chocolatey.org/packages/jasp) repository for JASP. If you aren't familiar with Chocolatey, it is a Windows package manager. The package is not distributed via Chocolatey, rather Chocolatey finds and performs the downloads and updates for the user. From your perspective, these users are just downloading and installing JASP from a PowerShell or CMD prompt. For it to function properly I need a reliable method of getting the latest release version.

**Describe the solution you'd like**
 
There are two solutions that would work well:
1. [Preferred] Make a new GitHub release for all downloadable versions of JASP that are featured on the JASP website.
2. Add a CSS class or ID to the version numbers on the https://jasp-stats.org/download/ or https://jasp-stats.org/release-notes/ pages. This would let me easily determine where to look for the correct version.

**Describe alternatives you've considered**
 
Originally, I set the package to automatically update to the new version of JASP based on https://jasp-stats.org/download/ and then later by using https://jasp-stats.org/release-notes/. Unfortunately, both of these methods are somewhat unreliable because I just have to make an educated guess about where to look on the page for the most recent version number, then build the download link from that. I switched over to using the GitHub Releases API, but in your current workflow, some releases are only tagged and not given a full GitHub release, e.g. 0.14.0.0 is a release but 0.14.1 is just tagged.

**Additional context**

As a side note, when I created the chocolatey package and added it to the repo there, I contacted your team to make sure that was ok. Hopefully there are still no issues as Chocolatey is such a great tool, but if this has changed let me know and I'm happy to take it down. Thanks!

**Comment by boutinb** [comment]
Hi @adamblake, thanks for your comprehensive request.
We have already an URL that you could use: http://static.jasp-stats.org/JASP-Version.txt
This URL is used by JASP self to check whether a newer version exists.
We could add also a release page in GitHub. I will discuss that with my colleagues.
We should indeed set the appropriate Git tag in our repository.

**Comment by JorisGoosen** [comment]
Well I usually do set a tag for each release already, but wasn't consistently uploading the windows/mac installers there.

That is a great idea. Also for people who have our static domain blocked (apparently some employers do this).

**Comment by JorisGoosen** [comment]
See: https://github.com/jasp-stats/jasp-desktop/releases/tag/v0.14.1.0
Now I just need to remember to do this for every release...

**Comment by adamblake** [comment]
> We have already an URL that you could use: http://static.jasp-stats.org/JASP-Version.txt
> This URL is used by JASP self to check whether a newer version exists.
This is perfect for my use case! Thanks for pointing me to it.
