### ISSUE TITLE
Sequential analysis for Bayesian ANOVA

### ISSUE THREAD

**Issue by franklenin** [jasp-stats/jasp-issues#1118]
Sequential analysis for the Bayesian ANOVA

* Purpose: To implement a sequential analysis for the Bayesian ANOVA

Sequential analysis is a powerful tool of Bayesian analysis. While you already offer a sequential analysis for the Bayesian t-test, there is not an option for the Bayesian ANOVA. It will be extremely useful to have this option in future versions of JASP.

**Comment by boutinb** [comment]
@JohnnyDoorn Could you answer this request?

**Comment by Andre3582** [comment]
Just want to add a comment to say I completely agree and that I would love to see this feature added to JASP!

**Comment by tomtomme** [comment]
@franklenin 
@Andre3582 
This is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/201
Lets track this there
