### ISSUE TITLE
Allow adding empty values to nominals/ordinals

### ISSUE THREAD

**Issue by SchlennoB** [jasp-stats/jasp-issues#1120]
* Enhancement: Allow manually adding values to nominal/oridnal variables, similar to the `levels()` function in R, even if there is no data given for certain levels. 
* Purpose: When analyzing survey data it may happen that certain answer options have not been selected at all. When importing such a dataset JASP will create the values from the data that is available (i.e. given a five level answer scale, only four levels will be shown, if one answer has not been selected by any responent). So its incomplete. 
* Use-case: Manually adding the missing/empty values would allow to include those non-selected values to be included in descriptives analyzes, just counted with zero. 

**Describe the solution you'd like**
I would appreciate to allow adding values, just like I am able to change an existing values' label. R's `levels()` function is doing exactly that, as far as I understand (while being less than a rookie in R). 

**Describe alternatives you've considered**
Could not find any workaround or solution to that. Not even has that question/issue been brought up anywhere. 

**Clumsy illustration of what I mean**
![add_values](https://user-images.githubusercontent.com/62095261/103806568-893f4780-5055-11eb-804e-42afc0002853.png)
 
Thanks in advance, 
Daniel

**Comment by boutinb** [comment]
I think this is quite easy to add. @JorisGoosen, you are just busy with the variables level window, do you think you can easily add this possibility?

**Comment by JorisGoosen** [comment]
Yeah this shouldn't be too hard. The only problem I foresee is that when you synchronize from a datafile it might drop the extra values/labels again. But a workaround for that shouldn't be too hard either.

**Comment by SchlennoB** [comment]
Now that was quick. Thank you!

**Comment by JorisGoosen** [comment]
Well, I have implemented this code in a separate branch (which means it isn't necessarily part of the next release yet.) at 

Because while the added code works [we added `droplevels` to our factor/levels creation code in jasp quite some time ago](https://github.com/jasp-stats/jasp-desktop/commit/567c830a66083aa2f83ebd51c29e99a963287ce3).
And those newly added values well, they are dropped immediately... This was added for filtering I think, to make sure all the variables filtered out don't mess up all the plots.

I think some thought must go in resolving this properly...

**Comment by SchlennoB** [comment]
Take your time! I'm totally happy that you're working on that issue and anyway hadn't expected the feature coming with the next release. 
(But of course can't wait to use the feature. Just because in my reality such "imperfect" datasets with missing values are rather the norm than the exception.)

So still: thank you for working on that!

**Comment by boutinb** [comment]
Implemented in https://github.com/jasp-stats/jasp-desktop/pull/5276
The 0.18.2 version containing this feature should be released over 2 weeks.

**Comment by juyujeng** [comment]
I am currently using JASP version 0.19.3 and have encountered an issue while trying to utilize the "Add Empty Value" feature for nominal or ordinal variables. Despite reviewing the interface, I cannot find any button or option to add a new empty label for a variable.

Does anyone know how to use this feature? Any guidance or instructions would be greatly appreciated. Thank you!

![截圖 2025-01-09 15 32 34](https://github.com/user-attachments/assets/b31a55a9-ddcc-4c52-945a-25f54acb48d0)

**Comment by boutinb** [comment]
Hi @juyujeng, the 'empty values' are called 'missing values' in JASP. You have to click on the Missing values tab button: here you see the default strings considered as missing values. If you click on the 'use custom values', then you can add/removed this list.

**Comment by juyujeng** [comment]
Hi @boutinb , thanks for your quick reply.

Thanks for your quick reply.

I'm having trouble generating a contingency table for two raters (Rater 1 and Rater 2). My data consists of pairs of ratings, where each pair represents the ratings given by Rater 1 and Rater 2 for a specific item.

I've defined 0 and 2 as missing values for Rater 1 (who only give value 1). However, when I attempt to generate the contingency table, it's not being produced correctly. I'm not sure if this is related to how the "add empty value" feature is handling missing data.

Could you please clarify how to properly handle missing values when generating a contingency table in this scenario? 
Thank you

![圖片](https://github.com/user-attachments/assets/839eb83c-fa53-466b-a713-7a818b7d421c)
![圖片](https://github.com/user-attachments/assets/e56e3feb-e2a2-4ecb-a7dc-81b6d3116bab)

**Comment by JorisGoosen** [comment]
Ah there is certainly some confusion here.

An "empty value" as @juyujeng means is a not-entered value in that column. However we do not support that.
The missing values that Bruno mentioned is to have certain values that do exist in the data to be treated *as if they are empty*.
