### ISSUE TITLE
JASP won't open

### ISSUE THREAD

**Issue by bradyse** [jasp-stats/jasp-issues#1121]
* JASP version: 0.14 and 0.14.1
* OS name and version: Windows 10 x64
* Analysis: Opening program
* Bug description: JASP won't open
* Expected behaviour: Open start-up window

This issue began when Windows pushed through a large update in December 2020. Based upon several other threads with the same issue, I attempted the following without success:

- Downloaded the most recent C++ redistributable libraries
- Attempted to open the logtoFile JASP reports (but they do not exist in my AppData\Roaming folder)
- I also had some luck running it from the .zip file, but this solution stopped working unexpectedly
- I have uninstalled and installed JASP multiple times

**Comment by boutinb** [comment]
Hi @bradyse This is really annoying. Just to be sure: you did read this document: https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/user-guide/logging-howto.md ?
Are you admin of your PC? 
Also that you can't see any log file is really strange. What you could try is to create a folder somewhere (D:\temp for example if you have a D drive) with a Command Prompt, to go to the `c:\Program Files\JASP` (where JASP is installed), and then type `JASP > D:\temp\log.txt` . This should create at least this log.txt file.

**Comment by bradyse** [comment]
Thanks for your help. I have admin privileges to my PC, but not full privileges (because this is my employer's laptop). I installed JASP on my C:\ drive. Once I created a temp folder in my network drive (Z:\ drive) using the Command Prompt to create the log file per your instructions, JASP opened and I was able to find the folder where the logs are (which were in my Z:\users\user.name\AppData\Roaming folder). Attached are my log files. JASP appears to be functional now. Thanks for your help!


[JASP 2021-01-06 16_49_50 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/5789417/JASP.2021-01-06.16_49_50.Engine.0.log)
[JASP 2021-01-06 16_49_50 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/5789418/JASP.2021-01-06.16_49_50.Engine.1.log) 
[JASP 2021-01-06 16_49_50 Engine 2.log](https://github.com/jasp-stats/jasp-issues/files/5789419/JASP.2021-01-06.16_49_50.Engine.2.log)
[JASP 2021-01-06 16_49_50 Engine 3.log](https://github.com/jasp-stats/jasp-issues/files/5789420/JASP.2021-01-06.16_49_50.Engine.3.log)
[JASP 2021-01-08 13_07_10 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/5789402/JASP.2021-01-08.13_07_10.Desktop.log)
[JASP 2021-01-08 13_07_10 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/5789403/JASP.2021-01-08.13_07_10.Engine.0.log)
[JASP 2021-01-08 13_07_10 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/5789404/JASP.2021-01-08.13_07_10.Engine.1.log)
[JASP 2021-01-08 13_07_10 Engine 2.log](https://github.com/jasp-stats/jasp-issues/files/5789405/JASP.2021-01-08.13_07_10.Engine.2.log)
[JASP 2021-01-08 13_07_10 Engine 3.log](https://github.com/jasp-stats/jasp-issues/files/5789406/JASP.2021-01-08.13_07_10.Engine.3.log)
[JASP 2021-01-08 13_17_03 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/5789407/JASP.2021-01-08.13_17_03.Desktop.log)
[JASP 2021-01-08 13_17_03 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/5789408/JASP.2021-01-08.13_17_03.Engine.0.log)
[JASP 2021-01-08 13_17_03 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/5789409/JASP.2021-01-08.13_17_03.Engine.1.log)
[JASP 2021-01-08 13_17_03 Engine 2.log](https://github.com/jasp-stats/jasp-issues/files/5789410/JASP.2021-01-08.13_17_03.Engine.2.log)
[JASP 2021-01-08 13_17_03 Engine 3.log](https://github.com/jasp-stats/jasp-issues/files/5789411/JASP.2021-01-08.13_17_03.Engine.3.log)
[JASP 2021-01-08 13_18_07 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/5789412/JASP.2021-01-08.13_18_07.Desktop.log)
[JASP 2021-01-08 13_18_07 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/5789413/JASP.2021-01-08.13_18_07.Engine.0.log)
[JASP 2021-01-08 13_18_07 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/5789414/JASP.2021-01-08.13_18_07.Engine.1.log)
[JASP 2021-01-08 13_18_07 Engine 2.log](https://github.com/jasp-stats/jasp-issues/files/5789415/JASP.2021-01-08.13_18_07.Engine.2.log)
[JASP 2021-01-08 13_18_07 Engine 3.log](https://github.com/jasp-stats/jasp-issues/files/5789416/JASP.2021-01-08.13_18_07.Engine.3.log)

**Comment by boutinb** [comment]
Hi @bradyse, Happy to hear that it works now. But I would like to know exactly what went wrong to avoid the problem you had for other users.
Actually I don't understand exactly what you did. You have created a temp folder in your z drive, and then JASP could start. But do you have still to start JASP with the command prompt? Could you tell me exactly what you did? Did you have to create self the Z:\users\user.name\AppData\Roaming\JASP\JASP folder?
You say that you do not have full privilege on your laptop (but you could install JASP in the C drive). Do you know which rights you don't have?
Hopefully can we find the exact problem that plays on your laptop.

**Comment by bradyse** [comment]
Hi @boutinb, Yes, I created a temp folder in my Z drive by simply going into the File Explorer menu. Then, using the command prompt, I created the log.txt file according to your instructions. I did NOT have to create the  log file in Z:\users\user.name\AppData\Roaming\JASP. Once I used the command prompt to create the log.txt file, JASP immediately opened on my computer. It was like as if it was trying to open from an earlier attempt and then finally executed the process upon created the log.txt file in the temp folder. Once JASP was open, I went in and asked to look at the log files and open the file location. I discovered then that the log files were located on the Z:\users drive and not in my C:\users drive.

I do not have full access to my employer's Z:\ drive. There are some programs that run from that drive that I cannot control (e.g., my email service). However, I have full administrative privileges to install software into either my Z:\users drive or C:\users drive. As instructed by my IT people, I only install things into my C:\ drive to avoid problems with access to my Z:\ drive. This is what I did with JASP--I never installed it to my Z:\ drive. However, it appears that some folders went there anyway. I hope that makes sense, but if not, I can ask my IT people for a more complete explanation. Thanks for your help!

**Comment by boutinb** [comment]
Hi @bradyse This is still quite strange. Could you explain to your IT people what has happened, and maybe can they come up with an explanation why JASP could not start in your environment. Could you ask them also what are exactly the rights you don't have on your PC? Thanks!

**Comment by bradyse** [comment]
Hi @boutinb I spoke to my IT people and you'll have to forgive me for not understanding exactly what's going on, but I have administrator privileges to my local files (on my local drive), but not to my employer's file server. The main problem is that I have two AppData Roaming folders--one on my local drive and one on my network drive. Some of my files sync with my employer's file server. Some programs will "look" for a file path to download files into the AppData and will see my user profile path on the file server instead of the AppData folder on my local drive. I was told that "some programs don't like the file server folders and the file server will cause problems for certain applications." My IT people thought that JASP might look in several places for where to install files and if it doesn't have permission to install the files (like in my profile's file server AppData), then it won't open the program. After creating the temp folder in my local drive, JASP opened because I used my account to create the log.txt file via the Command Prompt. If JASP used the variable %AppDataLocal% instead of %AppData%, then there wouldn't have been an issue. It could also be that our synchronization stuff isn't set up properly, and my employer is going to redo how they do employee user profiles. What is really curious, however, is that my file server's roaming AppData folder had JASP logs in it from earlier. So I'm not sure why JASP didn't "know" that's where my log files were. My IT people are __really_ busy, but if you need more detail, I can ask.

**Comment by boutinb** [comment]
Hi @bradyse Thank you for having taking the time to ask. This is quite useful for us. I think we can make an extra check when JASP starts so that it tries to find a writable folder. Thank you really much!
