### ISSUE TITLE
Dunn's P values: Add p-value explainer footnote

### ISSUE THREAD

**Issue by Oibade** [jasp-stats/jasp-issues#1123]
Dunn's test under the ANOVA section produces unadjusted p-values (they're exactly half) that do not match other softwares (GraphPad PRISM v9.0.0, R v3.6.2). Using JASP 0.14.1

**Comment by EJWagenmakers** [comment]
@JTPetter did you check this one out?

**Comment by JTPetter** [comment]
@EJWagenmakers 

I have looked into verifying Dunn’s test in JASP. It is not available in any of the other common software packages (Minitab, SPSS, etc.), but a comparison with the R package 'dunn.test' confirmed the results in JASP.  See the output below. 

![image](https://user-images.githubusercontent.com/61797391/104439656-a31ae600-5591-11eb-9608-a6440ec0311b.png)
![image](https://user-images.githubusercontent.com/61797391/104439710-b62db600-5591-11eb-83c4-7037530773ee.png)

**Comment by Oibade** [comment]
Sorry for the late reply - it took me a while to reorganize the output with the different softwares and different machines.
The results from SPSS and PRISM match, although the test statistic seems correct JASP seems to consistently underestimate the p-values.

<img width="571" alt="Screen Shot 2021-02-04 at 9 46 59 AM" src="https://user-images.githubusercontent.com/59439593/106909988-c9cec700-66ce-11eb-8a9c-81184976ec16.png">

![P_20210204_094632](https://user-images.githubusercontent.com/59439593/106910319-1ca87e80-66cf-11eb-8ca5-03d90b4f807c.jpg)


<img width="687" alt="Screen Shot 2021-02-04 at 9 46 50 AM" src="https://user-images.githubusercontent.com/59439593/106910003-ce937b00-66ce-11eb-88dd-5f640655d2ab.png">

**Comment by boutinb** [comment]
@JTPetter Could you check this data?

**Comment by aopteryx** [comment]
@JTPetter @boutinb 

Thanks for the support and clarification! I came along the same issue. 

In free software PAST (https://www.nhm.uio.no/english/research/infrastructure/past/) the p-values are also double of JASP, same as in SPSS (double): 
You can do Dunns test in SPSS using Kruskal Wallis first
https://www.ibm.com/support/pages/can-spss-perform-dunns-nonparametric-comparison-post-hoc-testing-after-kruskal-wallis-test

The Z values of all progams are identical. 

For best comparison and tranparency between programs I'd prefer to have a footnote AND the option to allow one-sided and two sided test. Thanks again.

**Comment by EJWagenmakers** [comment]
This makes sense. Note that the two-sided p-value is double that of the one-sided p-value only if the observed effect goes in the expected direction (so don't code this just as p/2).

**Comment by tomtomme** [comment]
There is still no documentation of this in the help file or as a footnote in 0.18.2. This is a problem for all post hoc tests. We should make clear somewhere if they are one or two sided. 

I would vote for two-sided for all, since this emphasizes the exploratory character of post hoc comparisons.  But an option to choose would also be cool and more in line with what the t-Test module does.

**Comment by JTPetter** [comment]
Thanks @tomtomme , I will add a footnote for the next version.

**Comment by JohnnyDoorn** [comment]
@JTPetter Please consult me on ANOVA PR's, since I fixed this earlier in https://github.com/jasp-stats/jaspAnova/commit/4b20cfb1dbfff52eecefd508c1b19e2a963f48b7 and now the footnote is wrong. I removed it for 0.19
