### ISSUE TITLE
Data Library output not appearing

### ISSUE THREAD

**Issue by Saguaroman** [jasp-stats/jasp-issues#1124]
* JASP version: 0.14.1
* OS name and version: Windows 10
* Analysis: All
* Bug description: When I open files in the "data library" the accompanying explanation and analysis used to open as well.  Now, just the data file opens and I don't see a way to get the analysis to appear. 
* Expected behaviour: For the analysis to appear when the "data library" files are opened. 

#### Steps to reproduce:
1. Go to 'main menu - open - data library'
2. Click on any analysis -- I've tried a number and the same thing happens -- no example analysis or explanation of the dataset is visible.  I can run analysis, but that just appears in a new / blank output screen -- the "model" analysis is not anywhere to be seen.

**Comment by boutinb** [comment]
Hallo @Saguaroman, I cannot reproduce this problem on my Windows 10 machine. I can open e.g. the Sleep JASP file from the Descriptives folder. Just to be sure: is this problem only for Data Library JASP files, or can you open other JASP files? And can you add an analysis (the Descriptives analysis e.g) directly from the Ribbon bar (the menu with the big icons)? If yes can you then save it as JASP file, and load it again?
Also, can you turn on the log and send me the log files (https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/user-guide/logging-howto.md)?

**Comment by Saguaroman** [comment]
Thanks @boutinb for looking into this.  To clarify - the data files open fine and I can run analysis in all the normal ways. What is missing are the "pre-run" analyses and explanations of the data library files. When I open something from the data library, the only thing there is the data, without any output window at all. If I run analysis an output window opens with my analysis in it, but  none of the JASP explanation or analysis.  I am attaching a zip file with logs from a session where I opened two different data library files and ran analysis, but didn't see the pre-existing analysis or explanation of the files.  Thanks!  Jake
[JASP 2021-01-15 05_51_37 Desktop.zip](https://github.com/jasp-stats/jasp-issues/files/5820595/JASP.2021-01-15.05_51_37.Desktop.zip)
.

**Comment by djdekker** [comment]
Hello Saguaroman,

Exactly where are you clicking to open the file? Double clicking in the upper area (including the file name, e.g. "Album Sales") will give you the data set without pre-run analyses and explanations.

<img width="1148" alt="dataset" src="https://user-images.githubusercontent.com/5346286/104810182-7403af00-57f3-11eb-9c89-e20039d9717b.png">

You should get the analyses and explanations by double clicking in the lower area:

<img width="1148" alt="jaspfile" src="https://user-images.githubusercontent.com/5346286/104810272-a9a89800-57f3-11eb-8a5d-2eb8d446a883.png">

**Comment by tomtomme** [comment]
I stumbled about this a while ago. I figured it out, but maybe this could be visually more clear / distinguishable. Maybe with labels next to the table-symbols like "full jasp fil" vs. "data only file". Just my first idea. There will be better ones I am sure.

**Comment by Saguaroman** [comment]
Thank you -- that solved the issue!  I feel a bit stupid; I've used this feature for a long time and I don't know why suddenly I started clicking in the wrong place.  Thanks for your help and sorry for raising an issue that wasn't actually a bug!

**Comment by boutinb** [comment]
Thanks @djdekker for having found the problem! 
@Saguaroman: it's fine that you made this issue, because we were not aware that this was not clear enough (when we know something, we have the tendency to think that it's obvious for everyone). I will discuss it with my colleague to see if we can make it clearer, maybe with the idea of @tomtomme.
