### ISSUE TITLE
Trouble Downloading on MacBook Air

### ISSUE THREAD

**Issue by gracee2** [jasp-stats/jasp-issues#1125]
I am needing to download the JASP software for school and none of the versions I download will "open" on my computer. I have a MacBook Air that was brand new in 2017. I tried downloading the older version of JASP as well (as noted on the site) and it did not work. I need this ASAP and any help is appreciated.

**Comment by AlexanderLyNL** [comment]
Hi Gracee2,

Have you tried opening JASP by right-clicking the app and then click open? You might need to do this twice. 

Cheers,
Alexander

**Comment by gracee2** [comment]
Yes, when I right click then click open it says "Verifying JASP" then this screen comes up (see pic) and I click "Open" 
![image](https://user-images.githubusercontent.com/77398456/104470160-6518c480-5587-11eb-956f-42871fe2c868.png)

**Comment by gracee2** [comment]
I figured it out. thank you.

**Comment by AlexanderLyNL** [comment]
@MaxMaier42 could you please the instructions opening JASP on mac more prominent?
