### ISSUE TITLE
Incorrect Labels for Indirect Effects in Mediation with Multiple Predictors and Outcomes

### ISSUE THREAD

**Issue by jufrom** [jasp-stats/jasp-issues#1128]
* JASP version: 0.14.1

* OS name and version: Windows 10
* Bug description: In mediation analysis with multiple predictors and outcomes, the table for indirect effects seems to use incorrect labels (e.g., pred1 -> m -> out1). The labels suggest that the tables for direct, indirect, and total effects use different ordering (_outcomes then predictors_ for direct and total effects and _predictors then outcomes_ for indirect effects). However, if these labels are correct, the total effects do not add up for direct and indirect effects. It looks like the table for indirect effects uses the same ordering of effects as the other tables but incorrect labels. 
* Expected behaviour: Labels for the indirect effects should be ordered in the same way as the total effects.

#### Steps to reproduce:
1. Encountered the bug in a separate datafile with 2 predictors, 1 mediator, 3 outcomes.
2. Reproduced it in a test file with random data: [bugtest.zip](https://github.com/jasp-stats/jasp-issues/files/5821591/bugtest.zip)
3. Check the mediation analysis.
4. The rows 2-4 of the _Indirect Effects_ table seem to state incorrect effects judging from adding up the direct and indirect effects and comparing it to the total effects (e.g., for row 2 in _Indirect Effects_ and looking for the corresponding direct and total effects: `indirect(pred1->m->out2) + direct(pred1->out2) = .011 + -.198 = -.187`, which does not fit the total effect (`pred1->out2 = -.165`). 
5. Adding up effects just based on row (ignoring the labels in the _Indirect Effects_ table) does lead to results that make sense. For example, adding up rows 2: `direct + indirect = -.175 + .011 = -.165`. This is the case for all rows 2-4 suggesting that the just the labels are incorrect and effects are all ordered the same. E.g., row 2 in the _Indirect Effects_ table should be labelled `pred2 -> m -> out1` instead of `pred1 -> m -> out2` in line with the _Direct Effects_ and _Total Effects_ tables.

**Comment by jayjf** [comment]
![Screenshot](https://user-images.githubusercontent.com/77501618/104944252-8b21d880-597c-11eb-83a1-49c5806e5af6.jpg)
Here's a screenshot with how it looks on my end.

**Comment by boutinb** [comment]
@Kucharssim Can you have a look at this issue?

**Comment by Kucharssim** [comment]
Hello @jufrom,

thank you for reporting this bug! You are absolutely right, the order of the variable labels in the output tables were messed up. This will be fixed in the next release of JASP.
