### ISSUE TITLE
Repeated Measures ANOVA empty cell error? 

### ISSUE THREAD

**Issue by jamesmart-io** [jasp-stats/jasp-issues#1129]
I am having trouble with the 0.14.1 update. I’m currently having an issue with an error message while conducting a repeated-measures ANOVA in JASP. I could really use a push in the right direction.
 
I’ve included a screenshot of the error message. It states that some of the cells may be empty, however, I am not missing any data or have any empty cells. I’ve searched Google and GitHub with no luck. Do you have any suggestions?

<img width="613" alt="Screen Shot 2021-01-18 at 3 53 38 PM" src="https://user-images.githubusercontent.com/65377499/104964193-f2a24d00-59a9-11eb-86dc-d558ad051491.png">

**Comment by jamesmart-io** [comment]
I'd be happy to send the developer a private mail with my data and JASP file, but not sure how to do so. Can someone also assist with this?

**Comment by boutinb** [comment]
@JohnnyDoorn If you have time, can you have a look? If not, maybe @vandenman ?

**Comment by JohnnyDoorn** [comment]
Hi @jamesmart-io ,

Thanks for reporting this. Are you comfortable sharing the data set that resulted in that error message? That way I can take a closer look. You can send it by email to j.b.vandoorn <at> uva.nl

Kind regards
Johnny

**Comment by tomtomme** [comment]
@jamesmart-io 
Is this fixed?
Without the data we can't do much.
Feel free to reopen, if the error is still persistent in newer JASP versions and if you can share the data.
