### ISSUE TITLE
Enhancement Request: Post hoc tests in ANOVA to test means from an interaction effect

### ISSUE THREAD

**Issue by wjames35** [jasp-stats/jasp-issues#113]
Enhancement: Post hoc tests in ANOVA to test means from an interaction effect

Purpose. Presently post hoc tests in ANOVA only test mean differences for main effects, but it would be wonderful if they would test mean differences for interaction effects (JMP software does this and it is very useful)

**Comment by JohnnyDoorn** [comment]
This will be in 9.3
