### ISSUE TITLE
JASP crashed

### ISSUE THREAD

**Issue by davidgilden** [jasp-stats/jasp-issues#1131]
* JASP version: 0.14.1
* OS name and version: macOS 10.15

* Analysis: none
* Bug description: damn thing won't open
* Expected behaviour:

#### Steps to reproduce:

-----------------------------------------------------------------------

### Debug information:
**Engine # 0** process *does not exist (anymore)* and it's state is *initializing*.
**Engine # 1** process *does not exist (anymore)* and it's state is *initializing*.
**Engine # 2** process *does not exist (anymore)* and it's state is *initializing*.
**Engine # 3** process *does not exist (anymore)* and it's state is *initializing*.

[Commit used](https://github.com/jasp-stats/jasp-desktop/commit/f2cb223fef6b15089fd6e9da54825d370c1ece57)

**Comment by boutinb** [comment]
Hi @davidgilden Could you try to get some log files by doing what is described in this document: https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/user-guide/logging-howto.md

**Comment by davidgilden** [comment]
Here are the most recent log files from the last failed attempt to start JASP

**Comment by boutinb** [comment]
Hi @davidgilden, you have to us GitHub to send the file.

**Comment by davidgilden** [comment]
[JASP 2021-01-27 10_27_05 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/5889179/JASP.2021-01-27.10_27_05.Desktop.log)
[JASP 2021-01-27 10_27_05 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/5889180/JASP.2021-01-27.10_27_05.Engine.0.log)
[JASP 2021-01-27 10_27_05 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/5889183/JASP.2021-01-27.10_27_05.Engine.1.log)
[JASP 2021-01-27 10_27_05 Engine 2.log](https://github.com/jasp-stats/jasp-issues/files/5889184/JASP.2021-01-27.10_27_05.Engine.2.log)
[JASP 2021-01-27 10_27_05 Engine 3.log](https://github.com/jasp-stats/jasp-issues/files/5889185/JASP.2021-01-27.10_27_05.Engine.3.log)

**Comment by boutinb** [comment]
The JASP engines cannot start an R session.
Which JASP did you download: the Catalina or the Pre-Catalina version?
Could you also try this on a terminal. Type:
`/Applications/JASP.app/Contents/Frameworks/R.framework/Versions/Current/Resources/bin/R`
And check whether this start an R session.

**Comment by davidgilden** [comment]
catalina.  But I did try both eventually.  the version currently not working is called post mohave
i opened terminal and typed that line of code. I got the following message
/Applications/JASP.app/Contents/Frameworks/R.framework/Versions/Current/Resources/bin/R: line 245: /Library/Frameworks/R.framework/Resources/etc/ldpaths: No such file or directory

**Comment by boutinb** [comment]
Hi @davidgilden, there is something going wrong when the JASP engine tries to start R. But I need more information. Did you ever installed R or R studio on your machine? Could you also install this (alpha) version of JASP: https://static.jasp-stats.org/Nightlies/MacOS/JASP-nightly-development-8b7f097b6223945dd01994f09c03a3da73912cad.dmg and send me again the logs?

**Comment by davidgilden** [comment]
I do not think I have installed either R or R studio.  This computer has never really been used. It was given to me by the University of Texas, I migrated everything from another computer.  There is no R or R studio listed in the application folder.
Here are the logs requested:
[JASP 2021-02-03 09_11_53 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/5919405/JASP.2021-02-03.09_11_53.Desktop.log)
[JASP 2021-02-03 09_11_53 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/5919406/JASP.2021-02-03.09_11_53.Engine.0.log)

**Comment by davidgilden** [comment]
Hey boutinb have you given up on this?

**Comment by JorisGoosen** [comment]
Bruno (@boutinb ) asked me to take over because he wasn't sure what to check.

I would ask you to try out the following command:
`JASP_R_HOME=/Applications/JASP.app/Contents/Frameworks/R.framework/Versions/Current/Resources R_HOME=$JASP_R_HOME /Applications/JASP.app/Contents/Frameworks/R.framework/Versions/Current/Resources/bin/R`

**Comment by davidgilden** [comment]
I get this:


PSYC-A41610:~ gilden$ JASP_R_HOME=/Applications/JASP.app/Contents/Frameworks/R.framework/Versions/Current/Resources R_HOME=$JASP_R_HOME /Applications/JASP.app/Contents/Frameworks/R.framework/Versions/Current/Resources/bin/R
Switching R_HOME_DIR to JASP_R_HOME found of :  /Applications/JASP.app/Contents/Frameworks/R.framework/Versions/Current/Resources

R version 3.6.1 (2019-07-05) -- "Action of the Toes"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin15.6.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

Error: package or namespace load failed for ‘utils’:
 .onLoad failed in loadNamespace() for 'utils', details:
  call: switch(os, Linux = if (file.exists("/etc/os-release")) {
  error: EXPR must be a length 1 vector
Error: package or namespace load failed for ‘stats’:
 .onLoad failed in loadNamespace() for 'utils', details:
  call: switch(os, Linux = if (file.exists("/etc/os-release")) {
  error: EXPR must be a length 1 vector
During startup - Warning messages:
1: package ‘utils’ in options("defaultPackages") was not found 
2: package ‘stats’ in options("defaultPackages") was not found 
> 
>

**Comment by JorisGoosen** [comment]
Aah yes, that doesn't look good at all.
I'll have to figure out what could possibly be causing this error because I haven't seen this before...

**Comment by davidgilden** [comment]
This is a brand new computer, given to me by the University. I migrated all of my files and apps to it.  This may be what is causing Jasp to crash.  Would it help if I wiped the hard drive and reinstalled Catalina?

**Comment by JorisGoosen** [comment]
Well, it *might* help, but if your other apps are functional than I suppose there might be something more specific wrong with JASP.

Did you install JASP again from a dmg or did you copy it from your older computer?

**Comment by JorisGoosen** [comment]
This because MacOS does some checks on Apps since Catalina, maybe something didn't work out with that and now it won't let R-in-JASP access some files.

**Comment by JorisGoosen** [comment]
Aah before you wipe your drive, maybe you could show me the output of `uname -a`  because that seems to be giving the anomalous info that R cannot handle.

**Comment by davidgilden** [comment]
To the first question: originally migrated Jasp from Mac running Mohave to Mac running Catalina. So that did not work. Then downloaded post-Mohave Jasp as dmg.  That did not work either and that is what we are dealing with now.

The output requested:
> uname -a
Error: object 'uname' not found

**Comment by JorisGoosen** [comment]
Ah yeah, so at least nothing went wrong with the DMG then because it was installed in the normal way.

The `uname -a` command should be run in the terminal, not in R but just in the (so-called) shell you get when you open it.

**Comment by davidgilden** [comment]
I do not use R, it is not installed on the computer. I did run the uname -a command in the terminal. Maybe I am confused.

**Comment by JorisGoosen** [comment]
Ah ok, well that certainly explains what is going wrong!

It seems that `uname` is somehow missing from your system, and I thought that is a default part of it.
This seems to be the root-issue for JASP not starting, I will have to figure out why it does not work for you.

And I think you aren't confused but the command me and boutinb asked you to run before was starting the R we ship as part of JASP. And I thought maybe you had ran it in there and needed to make sure it wasn't like that. Thank you for bearing with me.

**Comment by JorisGoosen** [comment]
Perhaps you could open up a terminal again and run the command: `env` and separately: `echo $PATH`

**Comment by davidgilden** [comment]
Apparently I do not understand terminal.  I think my terminal session was still running r. I closed it and reopened it and got a different prompt and different results.  Here is what I get in response to the 3 commands you were interested in.

PSYC-A41610:~ gilden$ uname -a
Darwin 

PSYC-A41610 19.6.0 Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64 x86_64

PSYC-A41610:~ gilden$ env
TERM_PROGRAM=Apple_Terminal
SHELL=/bin/bash
TERM=xterm-256color
TMPDIR=/var/folders/5k/193brtlx6jxfvbw7mwszfcbwp854dg/T/
TERM_PROGRAM_VERSION=433
TERM_SESSION_ID=BC3F513D-B5DF-41C9-8665-19349EFDFCB6
USER=gilden
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.JycOLbesvd/Listeners
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
PWD=/Users/gilden
LANG=en_US.UTF-8
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/gilden
LOGNAME=gilden
_=/usr/bin/env

PSYC-A41610:~ gilden$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

**Comment by JorisGoosen** [comment]
Ah yes, thanks for trying it out again. I've redacted your comment a bit because the output of `env` wasn't necessary as it turns out.

It seems that the output of `uname` of your system prints more lines lines than R expects, as an example, on my mac I get:
`Darwin iMac-van-Joris.home 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64`

And it seems that R cannot handle it and crashes...

To fix this reinstalling MacOS again is a solution, but it would be quite some effort. I think renaming your computer might help as well. If you have the rights to do so on the mac. 

If you could follow the steps under "Change your computer’s name " from [this apple manual](https://support.apple.com/lt-lt/guide/mac-help/mchlp2322/mac) and change the computers name from "PSYC-A41610" to something else.

Then once you've done that you can check by running `uname -a` and then hopefully it should be just a single line.
When it is I think JASP should start without a hitch.

**Comment by davidgilden** [comment]
You clearly have identified something but I do not think the computer name is the problem. I have other MacBook Pro computers and I tried uname -a out on one that is running Mohave and where Jasp works.  I get output that does not have the line separations but the computer name has the same length.  Anyway Univ. of Texas is not going to let me change the name. The shared folder is not accessible by me.  Here is the terminal output. Do you think my last recourse is to wipe the memory and reinstall the operating system? I really have to get Jasp working. I teach courses in statistics and we use Jasp to analyze data.  Again thanks and thank Bruno for helping.

PSYC-A06443:~ gilden$ uname -a
Darwin PSYC-A06443 18.7.0 Darwin Kernel Version 18.7.0: Tue Jan 12 22:04:47 PST 2021; root:xnu-4903.278.56~1/RELEASE_X86_64 x86_64

**Comment by davidgilden** [comment]
Update: I described what we were doing with my IT person.  He sent me an article about how to change the computer name using terminal commands.  I did this, shortening the name to 4 characters. That led to the output of uname -a being one line, and that led to Jasp opening. Wow. You were right about the name and the fix. I am good to go. Thank you so much.

**Comment by JorisGoosen** [comment]
Aah great to hear, good luck with the course!
