### ISSUE TITLE
filter not showing items

### ISSUE THREAD

**Issue by jovab** [jasp-stats/jasp-issues#1133]
* JASP version: 0.14.1
 linux
* OS name and version:flatpak on centos 7
* Analysis: 
* Bug description: When I click
![Selectie_108](https://user-images.githubusercontent.com/62739011/105727942-e3804980-5f2b-11eb-8b67-0541224d4790.png)
 on the header of a column, the variables do not appear in the quick filter

**Comment by boutinb** [comment]
I think this is already by @JorisGoosen. A new Flatpak version should come soon.

**Comment by JorisGoosen** [comment]
Yes this is a duplicate of #1109 

I have indeed fixed it, and once https://flathub.org/builds/#/builders/32/builds/37831 completes building and is uploaded to flathub you can use it.
