### ISSUE TITLE
Trouble with CSV format, cant load data to ORDINAL due to characters

### ISSUE THREAD

**Issue by www263** [jasp-stats/jasp-issues#1134]
Hi, I have seen this being posted before, but cant seem to understand how I shall resolve it for me!

Ive edited the names slightly as the variables are somewhat secret, but this stil grants the same issue with not being able to load it in JASP as ORDINAL due to it considering it text, any idea for a fix? Kind regards, W

[data_1.zip](https://github.com/jasp-stats/jasp-issues/files/5867962/data_1.zip)

**Comment by EJWagenmakers** [comment]
Thanks for providing these data. I uploaded this data set in JASP. Only the first column cannot be coaxed into ordinal format -- it includes letters and it is not clear how these would correspond to ordinal levels. If this variable is ordinal (under the hood, so to speak), it is easiest to specify a new column (e.g., "OrdinalLevels") where you decode the ordinal levels with integer numbers.
Cheers,
E.J.
