### ISSUE TITLE
Repeated Anova is not working: error in contrastGrid

### ISSUE THREAD

**Issue by babapinkblubb** [jasp-stats/jasp-issues#1136]
* JASP version:
MAC
* OS name and version:
* Analysis:

analysis(dataset = dataset, options = options, perform = perform, callback = the.callback, state = oldState)

.resultsContrasts(dataset, options, referenceGrid)

emmeans::contrast(referenceGrid[[.v(contrast$variable)]], contrCoef)

contrast.emmGrid(referenceGrid[[.v(contrast$variable)]], contrCoef)

stop('Nonconforming number of contrast coefficients')

* 
* Bug description:
* Expected behaviour:

What does this mean?!?

**Comment by boutinb** [comment]
Could you send a JASP file where this problem occurs? (in zip format, via the GitHub website)

**Comment by tomtomme** [comment]
@babapinkblubb 
The error said "Nonconforming number of contrast coefficients" so you mabe did not enter all coefficients in a custom contrast? Hard to know without the data. 
Feel free to reopen, if the error persists in newer JASP versions and you can share the data.
