### ISSUE TITLE
Issue on JASP 14.1 on Acer Chromebook 14 : all the symbols/logo are missing 

### ISSUE THREAD

**Issue by manondmg** [jasp-stats/jasp-issues#1137]
* JASP version: JASP 0.14.1

* OS name and version: Acer-Chromebook 14
* Analysis: All the symbols/logo are missing 
* Bug description: Hi, I have a problem with JASP. I’m working on a chromebook, so I installed JASP via linux but I don’t have all the symbols on the app, I made a screenshot to show you what I have :
* [https://forum.cogsci.nl/uploads/253/QQVG1UJEO872.png](url)
* you can see that all the symbols/logo are missing (next to descriptives, etc.)
* Expected behaviour:

**Comment by vandenman** [comment]
Did you try using safe graphics mode? See the last screenshot at https://jasp-stats.org/chromebook-installation/

**Comment by manondmg** [comment]
> Avez-vous essayé d'utiliser le mode graphique sécurisé? Voir la dernière capture d'écran sur https://jasp-stats.org/chromebook-installation/

Oh thank you very much, indeed it works!
