### ISSUE TITLE
Can't open .jasp files on Mac Mojave 10.14.6

### ISSUE THREAD

**Issue by pvn0001** [jasp-stats/jasp-issues#1138]
JASP 0.14.1

Mac Mojave 10.14.6

I saved a JASP file to my desktop (.jasp). When attempting to open the file, an error message reads "The document could not be opened. The file isn't in the correct format."

When attempting to right click and select "open with," JASP is not one of the apps able to be selected to open the file. 

Any advice on how to open this file? I am a beginner...

**Comment by boutinb** [comment]
Hello @pvn0001: when you right-click the file and choose 'Open With', you can select 'Other...' . Here you should be able to choose the JASP application (select Enable All Applications). Check also the 'Always Open with' checkbox.
