### ISSUE TITLE
Show Eigen values on Factor Loading table

### ISSUE THREAD

**Issue by App-State-Prof** [jasp-stats/jasp-issues#114]
I teach students who are intro to research. No experience. It would be great to have a check box for "show Eigen values" then have the Eigen value posted above each factor in the table. I am using the scree plot now, they continue to have trouble understanding the Eigen axis to the dots showing the factors.

**Comment by juliuspfadt** [comment]
@App-State-Prof, sorry for the late response. I think this feature is by now in the factor module so I will close this issue. Feel free to reopen if anything remains unsolved.

**Comment by App-State-Prof** [comment]
Julias when using exploratory factor analysis...I still cannot find any report of the specific Eigenvalues. Only scree plot line, which is not definitive. Eigenvalues are in principal component analysis...but not exploratory factor analysis.

**Comment by EJWagenmakers** [comment]
Could we add this to the upcoming version, @juliuspfadt ?

**Comment by juliuspfadt** [comment]
this is what it will look like if it makes it into the next release: 
![Screenshot 2023-04-14 at 09 28 09](https://user-images.githubusercontent.com/38500953/231976111-825f7941-ebd3-4b1d-96fc-ec584c0cadfa.png)
