### ISSUE TITLE
Bayesian Repeated Measures ANOVA does not finish computing Bayes factors

### ISSUE THREAD

**Issue by jlwoodard** [jasp-stats/jasp-issues#1140]
* JASP version: 14.1

* OS name and version: macOS Big Sur version 11.1
* Analysis: Bayesian Repeated Measures ANOVA
* Bug description: I am trying to perform a 2 x 2 mixed-design ANOVA using Bayesian Repeated Measures ANOVA. There are 2 groups, each with around 1500 cases that were measured at baseline and at follow-up (a repeated measures variable of time). If I perform the same analysis using the frequentist Repeated Measure ANOVA, the analysis takes a bit of time, but no more than a few minutes. The Bayesian Repeated Measures ANOVA seems to be stuck on "Computing Bayes Factors". I have let the analysis run for a few hours but it never completes. I can't be sure if it is stuck or if the analysis would just take significantly more time. There are no error messages. The blue progress bar seems to start but never continues despite the program seeming to be running. The variables in the repeated measures cells section are scale level and the between-subjects factor is nominal level.
* Expected behaviour: I would expect the program would terminate with results

Thanks in advance for any possible help!

**Comment by vandenman** [comment]
Thanks for reporting this!

Just to make sure we're on the same page, the `Repeated Measures Cells` and `Between subject factors` in the input view look like this:
![image](https://user-images.githubusercontent.com/21319932/106265443-538e1880-6227-11eb-90ad-dcd80137deaa.png)

and the model specification looks like this?
![image](https://user-images.githubusercontent.com/21319932/106265495-67397f00-6227-11eb-8648-444cbf2a1977.png)

the screenshots are from our debug dataset, but if this matches your input then I'll see how long it takes with 1500 cases.

**Comment by jlwoodard** [comment]
Hi Don,
  Thanks for checking with me. Yes, the screenshot matches my setup. Let me know if you need more information!

All the best,

John

John L. Woodard, Ph.D.
Professor of Psychology
Associate Editor, Journal of the International Neuropsychological Society
Licensed Psychologist
Wayne State University
5057 Woodward Avenue, 7th Floor
Detroit, MI 48202 USA

313-577-5838 (voice)
313-577-7636 (fax)
john.woodard@wayne.edu<mailto:john.woodard@wayne.edu>
On Jan 29, 2021, 05:46 -0500, Don van den Bergh <notifications@github.com>, wrote:
[EXTERNAL]

Thanks for reporting this!

Just to make sure we're on the same page, the Repeated Measures Cells and Between subject factors in the input view look like this:
[image]<https://user-images.githubusercontent.com/21319932/106265443-538e1880-6227-11eb-90ad-dcd80137deaa.png>

and the model specification looks like this?
[image]<https://user-images.githubusercontent.com/21319932/106265495-67397f00-6227-11eb-8648-444cbf2a1977.png>

the screenshots are from our debug dataset, but if this matches your input then I'll see how long it takes with 1500 cases.

**Comment by jlwoodard** [comment]
Just as one additional mention, There are about 1500 participants per group, so around 3000 participants total.

**Comment by tomtomme** [comment]
@jlwoodard 
Can you check if the problem persists in newer JASP versions? This computation will need quite some time. Even with the debug dataset this computation needed around 2-3 minutes with n = 100. And I have a fast machine here.
Even if this would scale almost lineary, this would need at least 2 hours on my fast machine. Let it run over night to be sure.
