### ISSUE TITLE
Descriptive Statistics Disclosure Arrow

### ISSUE THREAD

**Issue by SamanthaS1** [jasp-stats/jasp-issues#1141]
Hi there, I was just wondering how I would be able to find the missing values in the descriptive statistics chart in jasp. So in other words, the problem I've come across is that it's not giving me the options for descriptive statistics in order to analyze values such as median, mode, variance and range. So my question is, how do I add the missing values without the option of adding them? Am I supposed to request this option or some kind of update? The main issue is that it's just not letting me scroll down to where I can check the values that I need for the analysis. If someone could get back to me on this I'd appreciate it,Thanks.

**Comment by EJWagenmakers** [comment]
This may not answer your question, but if you go to the hamburger menu (the three horizontal lines on the top-left) and then go Preferences -> Data -> Missing Value List, you can define your code for missing values. Once these are recognized, the columns will be correctly detected as ordinal or continuous (you can see this from the icon on top of each column), and then you should be able to obtains the medians, ranges, etc.

**Comment by SamanthaS1** [comment]
Actually, that does answer my question somewhat but also how do I define the codes for the missing values, does it have something to do with the drag and drop filter where you are supposed to make a formula with a set of logical values?

**Comment by EJWagenmakers** [comment]
I'm not sure whether filtering out the text entries (that represent the missing values) allows the column to be changed to ordinal or continuous, but the more principled solution is to enter your code for missing values in the missing value field. If I am not answering your question please provide a data set and some screenshots to highlight the issue.  

Cheers,
E.J.

**Comment by SamanthaS1** [comment]
https://docs.google.com/document/d/1v9hgGn8O5pQSl-lk7ZBSfHdKyO-WMjBFT5U79EY5EWk/edit
I included the screen shots in the link to the google document above. Hopefully this gives you some idea of the issue I'm having.

**Comment by EJWagenmakers** [comment]
I requested access...you can also email me the document at ej.wagenmakers at gmail.com

**Comment by EJWagenmakers** [comment]
Hi Samantha
Thanks for the files. In the data spreadsheet view, you can click on the staircase symbol (indicating that the variable is ordinal) and change it to a ruler (indicating that it is a scale variable). You should then be able to obtain means etc. If this isn't it then I'll reopen the issue.
Cheers,
E.J.
