### ISSUE TITLE
One-Sample t-test Test Value is Always 0

### ISSUE THREAD

**Issue by cnormi712** [jasp-stats/jasp-issues#1142]
* JASP version: 0.14.1 (the most recent update)

* OS name and version: Windows 10
* Analysis: One Sample t-test
* Bug description: The test value for a one sample t-test is always set to 0 when calculating the confidence interval around the mean difference and Cohen's d. This is the case even if I set the test value to something else. For example, my class average is 3.19 and the test value is 3.10, but I get a Cohen's d of 7 because the program assumes the value is set to 0 instead of 3.1. However, I should note that the t-statistic value and the p-value are correct. 
* Expected behaviour: For calculating the 95% confidence interval and Cohen's d, the program should use the population mean given in the test value box rather than automatically using 0.

#### Steps to reproduce:
1. Go to one sample t-test. Move the GPA variable over to the VARIABLES box.
2. Click on Student's t-test. Keep the test value at 0. Be sure to check location parameter and 95% confidence interval and effect size and 95% confidence interval boxes. 
3. Scroll over to see the table. Note the values given for the t-statistic, p-value, 95% confidence interval around the mean difference, Cohen's d, and the 95% confidence interval around Cohen's d.
4. Repeat steps 2 and 3 but this time change the test value to 3.1. Note that the t-statistic and p-value change, but the confidence intervals and Cohen's d does not. This is because the confidence intervals and Cohen's d seem to be calculated around a population average (mu) of 0 rather than the test value you give. 
5. See error

<!--- A note from the developers:
If possible please attach your data and/or JASP file to the issue, this makes solving the bug a lot easier. If you would prefer to not make your data publicly available then you could also mail it to us.
Note that github requires you to zip the file to upload it here.

[Practice Data Set.zip](https://github.com/jasp-stats/jasp-issues/files/5895586/Practice.Data.Set.zip)

**Note: This is a fictitious data set used for class purposes only.**

**Comment by AlexanderLyNL** [comment]
Dear cnormi712, 

I believe that this behaviour is correct. The reason for this is provided in a previous comment:

> From version 0.14.1 onwards the test value only affects the test quantities in the one-sample t-test. The estimation quantities (1) effect sizes, and (2) location estimates, and (3) the confidence intervals now do not depend on the test value.
> 
> Previously, we indeed reported all results relatively to the test value. I changed this, because reporting the estimates with respect to the test value is a bit non-standard, see for instance R, and our previous set-up led to some confusion, see #1036, with the confidence intervals. A 95% confidence interval formally represents all test values/null hypotheses that do not lead to a rejection of the null at p < 0.05. This can now be better shown with the one-sample t-test. Furthermore, this change should make the difference between testing and estimation more clear.
> 
> Cheers,
> Alexander

I hope that this suffices. 

Cheers,
Alexander

**Comment by cnormi712** [comment]
To be honest Alexander I'm still a bit confused as to why in an individual study the effect size for Cohen's d uses 0 as the population mean rather than the actual known population mean in its calculation. The output provides information that is very confusing (at least to me and some colleagues). 

For example, the dataset I provided shows only a .09 difference between our sample mean and the population mean on GPA (which results in a very small t-statistic) but then the calculation for Cohen's d reports an effect size of over 7 because the numerator is now 3.19 rather than just .09. The calculation for effect size just seems confusing, why use 0 when the population mean is still known? I've never seen estimates for the one sample t-test reported this way (though admittedly, how often do people use one sample t-tests?). 

I hope you understand I'm not arguing with you, I'm just explaining my confusion. I appreciate you taking the time to respond to my question...and it seems I have some investigating to do!

Thanks again!

**Comment by cnormi712** [comment]
Hello,

Sorry for the double post. I started looking into things. I believe I understand where you are coming from now! Thanks again for your help (and possibly inadvertently pushing me to learn something new/JASP). I'll close now.
