### ISSUE TITLE
Data manipulation features

### ISSUE THREAD

**Issue by PlaytosSandl** [jasp-stats/jasp-issues#1143]
Hello,
I really like JASP -- I am using it on Ubuntu and it is great.  As an experienced data analyst, one feature that is missing is the ability to manipulate the data.  This includes computing variables (such as summing variables to create a new variable) or recoding variables into new variables (such as grouping values of a variable into categories).  This is essential.  SPSS and PSPP allow this to be done easily.

I don't know if this has been raised before, or if it is being planned for, but I feel it would be a significant addition.

T. Seifert, Ph.D.

**Comment by EJWagenmakers** [comment]
Thanks for your kind words and your suggestion. We have implemented this already :-) If you go to https://jasp-stats.org/how-to-use-jasp/ and then scroll down to "functions", you will see "Compute columns" (this is the key one), "Data and Label Editing", and "Filtering". They have blog posts and moving gifs. Computing variables can be done with R code and a drag and drop interface. Please let us know whether you believe particular functionality is still missing. For now I'll close this issue.
Cheers!
E.J.
