### ISSUE TITLE
Distribution plots not showing frequency for lowest value

### ISSUE THREAD

**Issue by jasonckchan** [jasp-stats/jasp-issues#1147]
* JASP version: 0.14.1

* OS name and version: macOS 11.1
* Analysis: Descriptive statistics distribution plots
* Bug description: I have a variable with correlations in it.  Every subject provides their own correlation, ranging from -1 to +1.  When plotting the data with boxplots and jitter element enabled, I can see that there are a whole bunch of subjects with a +1 correlation and another bunch with a -1 correlation.  I wanted to see the exact frequency distribution of these data with a distribution plot.  To my surprise, the data from the distribution plot look wrong.  Instead of having a bi-model distribution with a lot of +1 and -1, I see a negatively skewed distribution, with nobody having a -1 correlation.  The data is in the column "Gamma."  Changing -1 to 0.9 made these subjects appear in the distribution plot. These data are in the Gamma_09 column. This seems like a serious bug.
 
* Expected behaviour: I expected that the distribution plot will correctly show the frequency of subjects with -1 correlation.

#### Steps to reproduce:
1. Go to 'Descriptives'
2. Add 'Gamma' and 'Gamma_09' to 'Variables', check 'Distribution plots' under Basic plots
3. See error

[JASP Bug Gamma.csv.zip](https://github.com/jasp-stats/jasp-issues/files/5905890/JASP.Bug.Gamma.csv.zip)

**Comment by boutinb** [comment]
@koenderks Can you have a look?

**Comment by Kucharssim** [comment]
Hello @jasonckchan,

thank you for reporting this issue, you are right, it was a bug. This will be fixed in the next release.
