### ISSUE TITLE
reliability mode

### ISSUE THREAD

**Issue by vasileiaaristotelidou** [jasp-stats/jasp-issues#1149]
help !! I want to reverse questions in Jasp but there is no reliability mode in the descriptive mode!! My jasp is up to date what is wrong?

**Comment by EJWagenmakers** [comment]
The reliability functionality has been upgraded and is now available as a separate module. Go to the big blue + sign on the top right of the JASP screen to view the modules, and then select the "Reliability" module.

**Comment by vasileiaaristotelidou** [comment]
Thank you very much!!
Is there any tutorial for reversing the questions in questionnaires?

**Comment by EJWagenmakers** [comment]
We don't have a tutorial on this particular aspect I think, but try it out (it is indicated in the GUI) and let us (that is, @juliuspf) know if it doesn't work.
