### ISSUE TITLE
German translation issue in Learn Bayes module

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-issues#1150]
See screenshot. Two issues:
1. In the main output table, the text underneath still speaks of "successes" and "failures" instead of Erfolge etc.
2. Something went wrong in the "Prior-Wahrscheinlichkeitsverteilung" (Maybe the word is too long?)

![image](https://user-images.githubusercontent.com/8603015/106748218-31303c80-6625-11eb-97ef-9e05b7b03396.png)

**Comment by JoKeyser** [comment]
My guess about 1. is that the string hasn't been made available yet on Weblate. The strings seem translatable (they're wrapped in gettext(), see https://github.com/jasp-stats/jaspLearnBayes/blame/master/R/LSbinomialtesting.R#L196), but I could not find them yet in the current state of the [`po` files](https://github.com/jasp-stats/jaspLearnBayes/tree/master/po), nor the [weblate pull requests](https://github.com/jasp-stats/jaspLearnBayes/pulls). That said, I'm not sure if the new repo https://github.com/jasp-stats/jaspLearnBayes/ is already used for building the current versions of JASP...

**Comment by tomtomme** [comment]
Still an issue in 0.18.3
Also captions of most plots still say "conditional"
