### ISSUE TITLE
German translation interferes with prior-posterior graph (important)

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-issues#1151]
1. Set language to German;
2. Go to summary stats, Bayesian independent samples t-test, enter t=1, n1=n2=1000, and select "prior and posterior"
3. The error message in the screenshot appears ("metric information not available for this family/device")
4. Set language to English, and the plot is shown just fine.
5. Revert to German, and the error message reappears.
6. It works fine for Dutch.
7. This suggests that we ought to run our unit tests for the different languages as well, because we want to catch error like these.

![image](https://user-images.githubusercontent.com/8603015/106753037-68a1e780-662b-11eb-85ee-4c83bb2ccd8d.png)

**Comment by JoKeyser** [comment]
I can't reproduce this bug on Ubuntu and JASP version 0.14.2.
It works for me in all 3 languages; hope this helps to narrow down the problem.

![JASP_ZS-Ttest-German-OK](https://user-images.githubusercontent.com/8722846/107121261-c59ed700-6891-11eb-8927-92ea6d6a4e2b.png)

**Comment by boutinb** [comment]
I cannot reproduce it either in the current development. I think it's solved.
