### ISSUE TITLE
JASP crashed

### ISSUE THREAD

**Issue by digitalempire00** [jasp-stats/jasp-issues#1154]
* JASP version: 0.14.1
* OS name and version: Windows 10 (10.0)

* Analysis: 
* Bug description:
* Expected behaviour:

#### Steps to reproduce:

-----------------------------------------------------------------------

### Debug information:
**Engine # 0** process *crashed* and it's state is *initializing*.
**Engine # 1** process *crashed* and it's state is *initializing*.
**Engine # 2** process *crashed* and it's state is *initializing*.
**Engine # 3** process *does not exist (anymore)* and it's state is *idle*.

[Commit used](https://github.com/jasp-stats/jasp-desktop/commit/f2cb223fef6b15089fd6e9da54825d370c1ece57)

**Comment by boutinb** [comment]
Hi @digitalempire00 Could you add more information about how JASP crashed: by startup, by doing an analysis....
Could you add also the log files: https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/user-guide/logging-howto.md

**Comment by felipeviegas** [comment]
I had a crash on startup of this version. It informs that "JASP ran into a problem loading the know issues for this version". It just quits after the message. Interestingly, when I open the "About" window before the warning, it keep it open, as the image shows.
I am using an old Macbook Air (mid/2011) with Mac OS High Sierra.  
![Screen Shot 2021-02-14 at 10 29 58](https://user-images.githubusercontent.com/48022360/107878292-47a18800-6eb0-11eb-9fd2-3ec492247617.png)

**Comment by JorisGoosen** [comment]
@felipeviegas does it keep giving this error?

And if you follow this link in your browser, does that work: http://static.jasp-stats.org/JASP-KnownIssues.json

**Comment by felipeviegas** [comment]
> @felipeviegas does it keep giving this error?
> 
> And if you follow this link in your browser, does that work: http://static.jasp-stats.org/JASP-KnownIssues.json

Hi Joris, sorry for the delayed response. I was out of my old mac!

Tried it now and the problem is gone! I did not update the version. Anything changed remotely?!

Thanks!

**Comment by JorisGoosen** [comment]
There probably was something going wrong with the connection, but good to hear it works now!
