### ISSUE TITLE
Unable to start JASP 0.14.1

### ISSUE THREAD

**Issue by mmower0191** [jasp-stats/jasp-issues#1155]
On opening JASP, I see a 'Welcome to JASP' opening screen, but no spreadsheet panel on the left in which to enter data.

**Comment by EJWagenmakers** [comment]
Dear mmower0191,

At the moment, most analyses need to start with you uploading a data file -- a txt file, a csv file, a ods file, etc. When that file has been loaded you will see the spreadsheet, and we offer some limited capacity to do data "editing": you can create new columns and do filtering. But a comprehensive data editor is something we currently lack. That said, any data editor (Excel, Wordpad, etc.) can easily produce txt/csv/ods files, so I personally feel that the limitation is not serious. Your data editor can also interact with JASP pretty seamlessly (see an outdated post on the topic: https://jasp-stats.org/2018/05/15/data-editing-in-jasp/). That said, some people strongly feel a data editor is a big plus, and we hope to have the data editor finished this year.

So if you want to start an analysis, you are advised to go to the hamburger menu on the top left and navigate to "open" (or click "so open a data file and take JASP for a spin" on the opening screen)

Cheers,
E.J.
