### ISSUE TITLE
Issue with Bayesian Wilcoxon signed-rank output

### ISSUE THREAD

**Issue by marie-aguirre** [jasp-stats/jasp-issues#1156]
Hello, 
First thank you for your amazing work and software !!

I encounter an issue with a non-parametric Bayesian t-test...

JASP version: 14.1
OS name and version: macOS Big Sur version 11.2
Analysis: Bayesian Wilcoxon signed-rank (one-sample)
Bug description: I am trying to a compare a proportion measure to the chance level 0.5. My data do not fulfill the assumption of normality. Thus I am using the Wilcoxon signed-rank test. 
The classic Wilcoxon signed-rank test indicates V = 61 with a p-value of .73 (Note that I found the same results using R)
In order to conclude in favor of the null hypothesis I used a non-parametric Bayesian t-test to compare my proportion measure to 0.5. 
However, the BayesFactor is totally wrong (< .001) ! (with such a p-value in classical test)
The parametric Bayesian t-test (student one) provide a more credible factor than the Wilcoxon one.

Expected behaviour: I assume there is a problem with the Bayesian Wilcoxon signed-rank (one sample) test and expect to correct it ...

You may find my data attached and a screen capture of results.
![Capture d’écran 2021-02-08 à 14 14 45](https://user-images.githubusercontent.com/9552287/107225748-7be0f880-6a19-11eb-8b36-0481215ed8c8.png)
[Datas.zip](https://github.com/jasp-stats/jasp-issues/files/5943921/Datas.zip)

Thanks in advance for any possible help!

**Comment by JohnnyDoorn** [comment]
Hi @marie-aguirre ,

Thank you for reporting this, there was indeed an error in the code, which counted the testValue twice - so if you instead compare your observations to 0.25 (which results in your values being compared to 2*0.25 = 0.5), you should obtain a sensible result.

Kind regards
Johnny

**Comment by marie-aguirre** [comment]
Hi @JohnnyDoorn,

thank you for your quick reply and for you hint ! That way I can analyze my data without waiting for the next release :)

Good luck !
Kind regards

**Comment by JohnnyDoorn** [comment]
Hi @joannarut,

Yes, unfortunately that is still the case, although we are releasing a new version within a couple of months.

Cheers
Johnny

**Comment by joannarut** [comment]
Hi @JohnnyDoorn 
Thank you for letting me know! It's good that there is an easy fix, though! 
Best regards,
Joanna
