### ISSUE TITLE
Issue with Wilcoxon signed rank (one sample) effect size

### ISSUE THREAD

**Issue by marie-aguirre** [jasp-stats/jasp-issues#1158]
Hello,

I encounter again an issue with a the Wilcoxon signed rank (one sample) effect size...

JASP version: 14.1
OS name and version: macOS Big Sur version 11.2
Analysis: Wilcoxon signed-rank (one-sample)
Bug description: I am trying to a compare a proportion measure to the chance level 0.5. My data do not fulfill the assumption of normality. Thus I am using the Wilcoxon signed-rank test.
The classic Wilcoxon signed-rank test indicates V = 61 with a p-value of .73 (Note that I found the same results using R)
The effect size (matched rank biserial correlation) indicate a value of 1.00
However, when I calculated manually I found -.103, this was the same result I found with R (using the package rcompanion and wilcoxonOneSampleRC function).

Am I missing something or is there an error ? 

Expected behaviour: I assume there is a problem with the Wilcoxon signed-rank (one sample) effect size and expect to correct it or maybe have an explanation ...

You may find attached the data file (the same as the previous issue haha!)

[Datas.zip](https://github.com/jasp-stats/jasp-issues/files/5961949/Datas.zip)

Thanks in advance for any possible help!

**Comment by JohnnyDoorn** [comment]
Hi @marie-aguirre,

Thanks for reporting this, it seems that indeed there is a discrepancy between the two results. I did some digging in the code, and found that [this commit ](https://github.com/jasp-stats/jaspTTests/commit/7f6cc1c88cb43182d9a49c3cafd92d4c757c1e52)from @AlexanderLyNL uses the centralised statistic for the effect size, but I am not sure about the reasoning behind this. Alexander, could you maybe shed some light on this?

Kind regards
Johnny

**Comment by AlexanderLyNL** [comment]
Thanks for the report. The centralised version was needed to make the location estimates and the confidence intervals invariant under location shifts. I did indeed not check the downstream use to estimate the biserial correlation. I'll add this to the todo list.

**Comment by marie-aguirre** [comment]
Thank for taking into account my comment! 

If I may add, the Cohen 's d for the one sample Student t-test differs also from what I found when calculated by hand and with R cohens_d function from the rstatix package and some online Cohen 's d calculator.

Here some data to reproduce the values.
I am trying to perform a one sample student t-test on the Arcsin2ET to compare to the chance level, i.e. arcsin(sqrt(0.5)) = 0.785
[Datas.zip](https://github.com/jasp-stats/jasp-issues/files/5965162/Datas.zip)

Other statistical data (t-value, df and p-value) are the equivalent with R, Jasp ou my manual version.
However, the effect size Cohen's d differs.
Jasp value : 2.861
R / online calculator / hand value : -0.23

If possible, I just wanted to clarify this point as well...

Note that from the independent and paired sample t-test (parametric and non parametric) I didn't find any issue with the effect size. It seems to focus on one-sample size tests.

Thank you for being reactive as your are and kind to answers issues and questions!

**Comment by JohnnyDoorn** [comment]
Hi @marie-aguirre,

Hm, with the effectsize package in R, I get the same result as JASP. We compute cohen's d in the one sample t-test by dividing the mean by the standard deviation. Which calculator/formula did you use to obtain your result? 

Kind regards
Johnny

**Comment by marie-aguirre** [comment]
Hi, @JohnnyDoorn 

You are totally right ! I am confused I must have made a mistake. I did this formula as well, I must have done some mistakes when reporting the data.

I am truly sorry for wasting your precious time.
Thank you for your answer and clarification, work spleepless night doesn't suit me ...

Kind regards

**Comment by JohnnyDoorn** [comment]
Hi @marie-aguirre ,

No problem, thanks a lot for getting involved and giving feedback, that's always much appreciated!

Kind regards
Johnny

**Comment by marie-aguirre** [comment]
hi @JohnnyDoorn 

Thanks you are really kind ! 
I really love Jasp and happy if I can help with spotting some (real) issues :)

That's the best statistic software from my point of view, beautiful, easy to use, enable to use Bayesian tests easily and make it understandable. I mainly recommend it to my students.

Honestly I can wait for a R script transcription of Jasp action (many times I use the filter function to make a statistical test, but I need to change it for another statistical test (therefore change the first statistical test reported results)so it dit not create a file with results all reported and stable for OSF share purpose (some data are in the long format...)). From that moment I will fully use it for all my articles !!
The only weakness might also be the absence of figures easily to modify/export for scientific article (in my department at least with APA reglementation).

Thank you again for your time.

**Comment by JohnnyDoorn** [comment]
Why did you change the mean to mean difference for the one-sample tests? Because this is not always relevant for people observing a single set of values. What if we use a "/" to indicate both approaches (testing a difference in means, testing a mean location).

**Comment by AlexanderLyNL** [comment]
Based on the discussion in slack, I reverted it back to the old situation, which reported mean differences for z and t-test.

**Comment by AlexanderLyNL** [comment]
The following code now provides the same results with a slight adjustment on the confidence interval. 

```
myData <- "someRoot/someFolders/Datas.csv"
bob <- read.csv2(myData)

testValue <- 0.5
ciValue <- 0.95

anders <- rcompanion::wilcoxonOneSampleRC(x=bob$ProportionOfMeasure,
                                          mu = testValue, zero.method = "Wilcoxon",
                                          ci = TRUE, conf = ciValue,
                                          type = "perc", R = 10000,
                                          histogram = FALSE,
                                          digits = 3,verbose = FALSE)
anders

iets <- stats::wilcox.test(bob$ProportionOfMeasure, alternative = "two.sided", mu = testValue,
                           conf.int = TRUE, conf.level=ciValue)
iets

df   <- ifelse(is.null(iets[["parameter"]]), "", as.numeric(iets[["parameter"]]))
nd   <- sum(dat != testValue)
maxw <- (nd * (nd + 1)) / 2
d    <- as.numeric((iets[["statistic"]] / maxw) * 2 - 1)

anders$rc
d

wSE  <- sqrt((nd * (nd + 1) * (2 * nd + 1)) / 6) /2
mrSE <- sqrt(wSE^2  * 4 * (1 / maxw^2)) 
zmbiss <- atanh(d)

confIntEffSize <- sort(c(tanh(zmbiss + qnorm((1-ciValue)/2)*mrSE), 
                         tanh(zmbiss + qnorm((1+ciValue)/2)*mrSE)))

c(anders$lower.ci, anders$upper.ci)
confIntEffSize
```

**Comment by AlexanderLyNL** [comment]
Fixed: https://github.com/jasp-stats/jaspTTests/pull/39#event-4401880113
