### ISSUE TITLE
factorial repeated measures ANOVA crash 

### ISSUE THREAD

**Issue by GDG-tech** [jasp-stats/jasp-issues#1160]
* JASP version: 0.13.1

* OS name and version:
* Analysis: 
* Bug description: Cannot compute post hoc analysis

#### Steps to reproduce:

<img width="692" alt="Screenshot 2021-02-15 at 12 13 38" src="https://user-images.githubusercontent.com/79090170/107945255-3f684c00-6f87-11eb-984b-1a140e0d1b26.png">
<img width="692" alt="Screenshot 2021-02-15 at 12 13 47" src="https://user-images.githubusercontent.com/79090170/107945264-42fbd300-6f87-11eb-8cb2-44c673eb3f33.png">

**Comment by JohnnyDoorn** [comment]
Hi @GDG-tech,

Thanks for your report. Could you perhaps include a data set (or preferable a jasp file, which you can upload as zip, or email to j.b.vandoorn <at> uva.nl) that gives the posted error message? Which version of JASP are you using? 

Kind regards,
Johnny

**Comment by GDG-tech** [comment]
Hi Johnny,
Thanks so much for your prompt reply.
I have just realised that there was a problem with the file I was using. I downloaded it again and now everything works.

Best wishes,
GDG-tech<https://github.com/GDG-tech>

**Comment by JohnnyDoorn** [comment]
Hi @GDG-tech 

That's great! Could you tell me what was wrong with your data file? Because it can help us clarify the error messages/checking when loading data/running analyses. 

Kind regards
Johnny

**Comment by GDG-tech** [comment]
Hi Johnny,
Unfortunately, I do not know what was wrong with the file. I just tried to download it again from the website, and the new file did not have any issues. So probably something weird must have happened to my dataset during the first download.

Kind regards,
@GDG-tech<https://github.com/GDG-tech>
[https://avatars.githubusercontent.com/u/79090170?s=400&v=4]<https://github.com/GDG-tech>
GDG-tech - Overview<https://github.com/GDG-tech>
GitHub is where GDG-tech builds software.
github.com

________________________________
