### ISSUE TITLE
Cohen's d overestimated in one-sample t-tests

### ISSUE THREAD

**Issue by andrewfeist96** [jasp-stats/jasp-issues#1162]
* JASP version: 0.14.1

* OS name and version: Windows 10
* Analysis: The computation for Cohen's d is not taking into account the value the data is being tested against.
* Bug description:  Cohen's d is being calculated as M1/sd.
* Expected behaviour: Cohen's d should be calculated as (M1-M2)/sd, where M2 is the assumed mean.  So if I was testing against the null hypothesis of a mean=32, and my sample data had a mean of 38, I'd expect Cohen's d to be 6/sd, not 38/sd.

**Comment by AlexanderLyNL** [comment]
Hi andrewfeist96,

We changed the behaviour of the one-sample t-test recently. It now provides you with estimates that are independent of the test. This was done so 
1. the results align with that of R and other statistical packages;
2. to avoid confusion regarding testing and estimation;
3. to align with the formal definition of confidence intervals. 

See also here

https://github.com/jasp-stats/jasp-issues/issues/1036
https://github.com/jasp-stats/jasp-issues/issues/1112#issuecomment-753624484
https://github.com/jasp-stats/jasp-issues/issues/1142

Hence, I believe that the current behaviour is correct, but do feel free to add to the discussion. 

Cheers,
Alexander
