### ISSUE TITLE
JASP unable to initialize the JIT

### ISSUE THREAD

**Issue by MayliaCypher** [jasp-stats/jasp-issues#1163]
* JASP version:0.14.1

* OS name and version:Windows
* Analysis: 
* Bug description: When I try to open JASP, it shows that there's a fatal error that it can't initialize the JIT.![3F6R17R@LV})D0P(2{0}@ZB](https://user-images.githubusercontent.com/79127076/108017258-6c961800-6fe2-11eb-894f-81d2dd53f550.png)
![L8S V)EIBS @J~T~($EYSVB](https://user-images.githubusercontent.com/79127076/108017285-8172ab80-6fe2-11eb-8813-89777aafb4c0.png)

* Expected behaviour:

**Comment by JorisGoosen** [comment]
Hello @MayliaCypher could you help us out and send us the logfiles of starting JASP?

We've made a manual on how to do that:
https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/user-guide/logging-howto.md

**Comment by MayliaCypher** [comment]
Hi @JorisGoosen 
Here are the logfiles I found

00:00:00.000: new LanguageInfo created: Language: '' qmFolder: '' and qmFilenames: ''
00:00:00.000: new LanguageInfo created: Language: '' qmFolder: '' and qmFilenames: ''
00:00:00.001: new LanguageInfo created: Language: '' qmFolder: '' and qmFilenames: ''
00:00:00.001: new LanguageInfo created: Language: '' qmFolder: '' and qmFilenames: ''
00:00:00.002: new LanguageInfo created: Language: '' qmFolder: '' and qmFilenames: ''
00:00:00.002: new LanguageInfo created: Language: '' qmFolder: '' and qmFilenames: ''
00:00:00.003: new LanguageInfo created: Language: '' qmFolder: '' and qmFilenames: ''
00:00:00.003: new LanguageInfo created: Language: '' qmFolder: '' and qmFilenames: ''
00:00:00.003: new LanguageInfo created: Language: '' qmFolder: '' and qmFilenames: ''
00:00:00.004: new LanguageInfo created: Language: '' qmFolder: '' and qmFilenames: ''
00:00:00.004: new LanguageInfo created: Language: '' qmFolder: '' and qmFilenames: ''
00:00:00.004: new LanguageInfo created: Language: '' qmFolder: '' and qmFilenames: ''
00:00:00.004: new LanguageInfo created: Language: '' qmFolder: '' and qmFilenames: ''
00:00:00.004: new LanguageInfo created: Language: '' qmFolder: '' and qmFilenames: ''
00:00:00.007: JASPControlWrapper::addControlError: A RadioButton inside RadioButtonGroup element (name: ) does not have any name
00:00:00.007: JASPControlWrapper::addControlError: A RadioButton inside RadioButtonGroup element (name: ) does not have any name
00:00:00.007: No checked button found in radio buttons 
00:00:16.930: JASPControlWrapper::addControlError: A RadioButton inside RadioButtonGroup element (name: ) does not have any name
00:00:16.930: JASPControlWrapper::addControlError: A RadioButton inside RadioButtonGroup element (name: ) does not have any name
00:00:16.930: No checked button found in radio buttons 
00:00:23.483: JASPControlWrapper::addControlError: A RadioButton inside RadioButtonGroup element (name: ) does not have any name
00:00:23.483: JASPControlWrapper::addControlError: A RadioButton inside RadioButtonGroup element (name: ) does not have any name
00:00:23.484: No checked button found in radio buttons 
00:00:25.147: JASPControlWrapper::addControlError: A RadioButton inside RadioButtonGroup element (name: ) does not have any name
00:00:25.147: JASPControlWrapper::addControlError: A RadioButton inside RadioButtonGroup element (name: ) does not have any name
00:00:25.148: No checked button found in radio buttons 
00:00:37.644: void Computer::browsePath("C:/Users/ALIENWARE/Documents") called, now sending out signal to show Open file dialog.
00:00:37.644: Now calling MessageForwarder::browseOpenFile("Open", "C:/Users/ALIENWARE/Documents", "Data Sets (*.jasp *.csv *.txt *.tsv *.sav *.ods *.dta *.por *.sas7bdat *.sas7bcat *.xpt)")
00:00:48.235: Chosen path: "E:/公务/Intro-data-for-assignment PSY252/Intro-data-for-assignment/Chap1-Data1.csv"
00:00:48.236: AsyncLoader::loadPackage(asyncloader)


00:00:00.000: Log and possible redirects initialized!
00:00:00.000: jaspEngine started and has slaveNo 3 and it's parent PID is 20752
00:00:00.032: Engine::initialize()

00:00:03.302: QML loaded, url: 'qrc:/components/JASP/Widgets/MainWindow.qml' and obj name: ''
00:00:03.303: QML Initialized!
00:00:03.303: Loading upgrades definitions
00:00:03.825: Description delay timer done, update!
00:00:03.826: RibbonButton for module Descriptives will read from Description again!
00:00:03.827: Description delay timer done, update!
00:00:03.827: RibbonButton for module T-Tests will read from Description again!
00:00:03.827: Description delay timer done, update!
00:00:03.827: RibbonButton for module ANOVA will read from Description again!
00:00:03.827: Description delay timer done, update!
00:00:03.828: RibbonButton for module Regression will read from Description again!
00:00:03.828: Description delay timer done, update!
00:00:03.828: RibbonButton for module MixedModels will read from Description again!
00:00:03.828: Description delay timer done, update!
00:00:03.828: RibbonButton for module Audit will read from Description again!
00:00:03.829: Description delay timer done, update!
00:00:03.829: RibbonButton for module Factor will read from Description again!
00:00:03.830: Description delay timer done, update!
00:00:03.830: RibbonButton for module Frequencies will read from Description again!
00:00:03.831: Description delay timer done, update!
00:00:03.831: RibbonButton for module Discover Distributions will read from Description again!
00:00:03.831: Description delay timer done, update!
00:00:03.831: RibbonButton for module BAIN will read from Description again!
00:00:03.831: Description delay timer done, update!
00:00:03.831: RibbonButton for module Equivalence T-Tests will read from Description again!
00:00:03.832: Description delay timer done, update!
00:00:03.832: RibbonButton for module JAGS will read from Description again!
00:00:03.832: Description delay timer done, update!
00:00:03.832: RibbonButton for module Network will read from Description again!
00:00:03.832: Description delay timer done, update!
00:00:03.832: RibbonButton for module Meta Analysis will read from Description again!
00:00:03.833: Description delay timer done, update!
00:00:03.833: RibbonButton for module Machine Learning will read from Description again!
00:00:03.833: Description delay timer done, update!
00:00:03.833: RibbonButton for module Summary Statistics will read from Description again!
00:00:03.833: Description delay timer done, update!
00:00:03.833: RibbonButton for module SEM will read from Description again!
00:00:03.833: Description delay timer done, update!
00:00:03.834: RibbonButton for module Reliability will read from Description again!
00:00:03.834: Description delay timer done, update!
00:00:03.834: RibbonButton for module Learn Bayes will read from Description again!
00:00:03.834: Description delay timer done, update!
00:00:03.834: RibbonButton for module Visual Modeling will read from Description again!
00:00:03.837: TempFiles::deleteOrphans started
00:00:03.838: looking at file C:/Users/ALIENWARE/AppData/Local/JASP/temp\20752
00:00:03.838: looking at file C:/Users/ALIENWARE/AppData/Local/JASP/temp\4040
00:00:03.980: Engine #0 cleared its send-buffer.
00:00:03.981: Engine #1 cleared its send-buffer.
00:00:03.981: Engine #2 cleared its send-buffer.
00:00:03.981: Engine #3 cleared its send-buffer.
00:00:11.708: JASPControlWrapper::addControlError: A RadioButton inside RadioButtonGroup element (name: ) does not have any name
00:00:11.708: JASPControlWrapper::addControlError: A RadioButton inside RadioButtonGroup element (name: ) does not have any name
00:00:11.708: JASPControlWrapper::addControlError: A RadioButton inside RadioButtonGroup element (name: ) does not have any name
00:00:11.709: No checked button found in radio buttons 
00:01:11.230: JASPControlWrapper::addControlError: A RadioButton inside RadioButtonGroup element (name: ) does not have any name
00:01:11.231: JASPControlWrapper::addControlError: A RadioButton inside RadioButtonGroup element (name: ) does not have any name
00:01:11.231: JASPControlWrapper::addControlError: A RadioButton inside RadioButtonGroup element (name: ) does not have any name
00:01:11.231: No checked button found in radio buttons 
00:01:12.842: void Computer::browsePath("C:/Users/ALIENWARE/Documents") called, now sending out signal to show Open file dialog.
00:01:12.843: Now calling MessageForwarder::browseOpenFile("Open", "C:/Users/ALIENWARE/Documents", "Data Sets (*.jasp *.csv *.txt *.tsv *.sav *.ods *.dta *.por *.sas7bdat *.sas7bcat *.xpt)")
00:01:26.821: Chosen path: "E:/公务/Intro-data-for-assignment PSY252/Intro-data-for-assignment/Chap1-Data1.csv"
00:01:26.822: AsyncLoader::loadPackage(asyncloader)

**Comment by JorisGoosen** [comment]
Hi @MayliaCypher great that you found them, do you think you could add them by attaching them here instead of pasting that?

And also, I see that you we're trying to load an assignment "Chap1-Data1.csv", in which folder on your system did you save it?
From the log you pasted it looks like something chinese "E:/公务/Intro-data-for-assignment PSY252/Intro-data-for-assignment/Chap1-Data1.csv". Is that actually the folder it is in?

Also, what kind of language and country settings have you on your computer?

**Comment by MayliaCypher** [comment]
Good evening,
Yes, the assignment is in the "Intro-data-for-assignment" folder. Do I need to change the names to all English? The language of my computer is Chinese and the country setting is China.
Thank you
Tian Tian
________________________________
发件人: Joris Goosen <notifications@github.com>
发送时间: 2021年2月17日 8:12
收件人: jasp-stats/jasp-issues <jasp-issues@noreply.github.com>
抄送: Tian Tian <ttian02@syr.edu>; Mention <mention@noreply.github.com>
主题: Re: [jasp-stats/jasp-issues] JASP unable to initialize the JIT (#1163)


Hi @MayliaCypher<https://github.com/MayliaCypher> great that you found them, do you think you could add them by attaching them here instead of pasting that?

And also, I see that you we're trying to load an assignment "Chap1-Data1.csv", in which folder on your system did you save it?
From the log you pasted it looks like something chinese "E:/公务/Intro-data-for-assignment PSY252/Intro-data-for-assignment/Chap1-Data1.csv". Is that actually the folder it is in?

Also, what kind of language and country settings have you on your computer?

―

**Comment by JorisGoosen** [comment]
Ah right, well we are working hard to have the next version of JASP work well with chinese and other non-latin alphabets and languages. But in 0.14 this is not all good yet.

You could try placing any files you use with JASP in a folder without chinese characters. That might solve the problem.

**Comment by shun2wang** [comment]
This might be solved by 0.16.4 since we make JASP work with UTF-8 on windows.
So I will close it for now, @MayliaCypher you can try it on latest version and reopen this if you still hava problem.
