### ISSUE TITLE
Linear regression. Problem with covariates

### ISSUE THREAD

**Issue by ecordonP** [jasp-stats/jasp-issues#1164]
* JASP version: 0.14

* OS name and version: Mac OSX Big Sur
* Analysis: Linear Regression
* Bug description: I cannot include categorical variables (dummy) as covariates. Only scale type variables are allowed
* Expected behaviour: In version 0.13, any type of variable could be entered as covariates: scale, ordinal, nominal

**Comment by Kucharssim** [comment]
Hello @ecordonP,

I am sorry for the trouble. In the next version of JASP, it will be possible to include categorical variables as predictors using a dedicated "Factors" field - similarly as is already the case for the logistic regression, see screenshot
![Screenshot 2021-02-16 at 13 43 03](https://user-images.githubusercontent.com/7093546/108064518-1914e000-705d-11eb-817e-37a8f73d8beb.png)

In the meantime, if you already coded your categorical variables as dummy variables (0/1), you can change the variable's type by clicking on the icon next to the variable's name and select "scale". 
![Screenshot 2021-02-16 at 13 46 00](https://user-images.githubusercontent.com/7093546/108064779-70b34b80-705d-11eb-92b3-a4ce0c5dc444.png)
Then you can use it in the "Covariates" field (provided that you are careful interpreting the coefficients and the intercept).

I am closing the issue now. Please reopen if you want to follow up on this issue.
