### ISSUE TITLE
JASP crashes when removing a model in "Learn Bayes" -> "Binomial Estimation" in FlatPak/ArchLinux

### ISSUE THREAD

**Issue by fkroener** [jasp-stats/jasp-issues#1165]
* JASP version: 0.14.3

* OS name and version: ArchLinux using FlatPak
* Bug description: JASP crashes when removing a model in "Learn Bayes" -> "Binomial Estimation"
* Expected behaviour: JASP shouldn't crash

#### Steps to reproduce:
1. Go to 'Learn Bayes'
2. Click on 'Binomial Estimation'
3. Click on "Plus"-Button in Model
4. Click on "Plus"-Button in Model once more.
5. Click on "X" to remove one of the models
6. See JASP window disappear
7. See `malloc_consolidate(): invalid chunk size` or `free(): invalid pointer` in your terminal, where you started JASP via "flatpak run org.jaspstats.JASP"

**Comment by FBartos** [comment]
Hi,
thanks for reporting the issue. We managed to replicate it and the problem seems to happen only on Linux distributions. We are working on fixing it.
Cheers,
Frantisek

**Comment by JorisGoosen** [comment]
Well, I've tested this in the current development version, but locally compiled and it seems to work now.

But I will have to wait for issue https://github.com/jasp-stats/INTERNAL-jasp/issues/1348 to be resolved so that I can try it out in flatpak, because it might behave different.

**Comment by JorisGoosen** [comment]
Ok, it seems that the Qt we are using broke JASP, so a workaround for now is:
`flatpak update --commit 4f232783b07952a4627a186c8020a362d2458c4b2d6046fbd0b43d3f44c551a7 org.kde.Sdk/x86_64/5.15`
After that JASP should work fine.

Once [this issue at kde](https://bugs.kde.org/show_bug.cgi?id=442422) is resolved I can actually debug what is wrong with it, but I am assuming that having a new version of the runtime might already fix it.

**Comment by JorisGoosen** [comment]
@fkroener if you try out the fix above you should be able to use JASP
