### ISSUE TITLE
LearnBayes module: Bayesian testing fails when theta=1

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-issues#1166]
Take the hungry zombie example, so we have 12 confirmatory instances. We specify one model to be theta=1, and the other to be beta(1,1). The problem is that the module would not accept theta=1 as input, no matter how I entered the data. For it to work I ended up having to enter theta = 0.999 as a spike, which is obviously suboptimal.

**Comment by FBartos** [comment]
I'm sorry, I know that we were talking about this and I thought I fixed it.

I have a few conceptual questions. We have two hypotheses:

A: theta = 0
B: theta = .5

We observe 1 failure and 1 success. The log marginal likelihoods are then - Inf for A (a success is impossible under A) and -0.693 for B. What are the BF_AB and BF_BA? Are they 0 and + Inf or are both of them undefined?

How do we deal with plotting the sequential BFs? (I can make the line disappear when it reaches the first success, or we let it go to infinity and shrink the remaining values into one place?

**Comment by EJWagenmakers** [comment]
(a) The BFs are 0 and +Inf. See also the Bayesian binomial in JASP common or (this is easier to check) the Bayesian binomial in the Summary Stats module.
(b) I am not sure how Bayesian binomial in JASP common does this, you could check it out. It probably says plotting is impossible. We could develop a fancy graph with all values shrunk and a fat arrow pointing to infinity, but this is just a sophisticated way of saying that plotting is impossible.

**Comment by FBartos** [comment]
I have one special case that we do not offer anywhere else:
A: theta = 0
B: theta = 0
We observe 1 success. 
the BF_AB is exp(-Inf + Inf). Should the output produce NaN?

**Comment by EJWagenmakers** [comment]
Yes, that should be NaN.
There is also this important scenario:
A: theta = 0
B: theta = 1
We observe 1 success and 1 failure.
This should also produce NaN.
