### ISSUE TITLE
JASP crashed

### ISSUE THREAD

**Issue by rnrpereira** [jasp-stats/jasp-issues#1167]
* JASP version: 0.14.3
* OS name and version: KDE Flatpak runtime

* Analysis: 
* Bug description:
* Expected behaviour:

#### Steps to reproduce:

-----------------------------------------------------------------------

### Debug information:
**Engine # 0** process  is *running* and it's state is *idle*.
**Engine # 1** process  is *running* and it's state is *idle*.
**Engine # 2** process  is *running* and it's state is *idle*.
**Engine # 3** process *crashed* and it's state is *moduleRequest*.

[Commit used](https://github.com/jasp-stats/jasp-desktop/commit/c618f4f749569939c9082daaf2949a4ba7d53437)

**Comment by boutinb** [comment]
HI @rnrpereira Could you describe a bit more what happens: is it when starting JASP, loading data, running an analysis?
Could you also give the log files: https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/user-guide/logging-howto.md ?

**Comment by tomtomme** [comment]
@rnrpereira 
I guess this is fixed. I also use the KDE flatpak version and everything is fine.
If you disagree, feel free to reopen with some more details. Thx.
