### ISSUE TITLE
update websites rollApp version

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#1168]
https://jasp-stats.org/download/ advertises JASP 0.9.0.1 online via Rollapp, but I just checked and its actually at 0.14.3!

**Comment by EJWagenmakers** [comment]
That has just happened. Exciting news, but unfortunately the current version does not work (it keeps crashing). We are in contact with them to sort this out. Once the issue has been fixed we will advertise it more broadly.
