### ISSUE TITLE
Strange looking font errors

### ISSUE THREAD

**Issue by freckledude** [jasp-stats/jasp-issues#1169]
* JASP version: 0.14.1

* OS name and version: Windows 10 Education 20H2
* Analysis: N/A
* Bug description: When in the compute new variable menu, I see that some of the variable names contain characters that did not show up correctly. in their place is a random assortment of colored pixels.
* Expected behaviour: The entire name of the variables should show with no erroneous pixels. 

#### Steps to reproduce: with a dataset...
1. Go to compute new calculated column 

 attached is the data and a screenshot of the bug. The bug appears in a variety of places. For example see where it should show the variables on the very left hand side and how some of the characters of the name of the variables appear correctly, but also a few are simply random dots?!?! kind of cool, but also annoying =] 
[DKE.zip](https://github.com/jasp-stats/jasp-issues/files/6000003/DKE.zip)

**Comment by boutinb** [comment]
Hello @freckledude Could you try it with the Safe Graphics Mode on (Preferences/Interface menu)?

**Comment by freckledude** [comment]
I turned safe graphics mode on and tried it again and the weird text isn't
there anymore! Thanks!
