### ISSUE TITLE
JASP will not display distribution plots

### ISSUE THREAD

**Issue by stephleo** [jasp-stats/jasp-issues#1170]
* JASP version: 12.1

* OS name and version: macOS Catalina 10.15.7
* Analysis: JASP will not display the various distribution plots including Q-Q plot, P-P plot, histogram vs. theoretical pdf, and empirical vs. theoretical pdf.
* Bug description: There was no bug report, but the plots will not display in JASP
* Expected behaviour: Plots displayed on screen.
<img width="1280" alt="Screen Shot 2021-02-18 at 10 03 23 AM" src="https://user-images.githubusercontent.com/77896838/108408863-91ada500-71f3-11eb-8702-48e797630d57.png">
<img width="1280" alt="Screen Shot 2021-02-18 at 10 03 50 AM" src="https://user-images.githubusercontent.com/77896838/108408876-95d9c280-71f3-11eb-9303-ba2f9fc9f07f.png">

**Comment by Kucharssim** [comment]
Dear @stephleo,

Thank you for the report. Perhaps you need to expand the "Estimate parameters" section and select "Maximum likelihood", then all the results should show up.

**Comment by stephleo** [comment]
@Kucharssim 

Thank you.  I selected "Maximum Likelihood" and was able to see the results.  I appreciate your assistance.

**Comment by Kucharssim** [comment]
I am glad it helped!
