### ISSUE TITLE
Bug: Expanding plot crashes JASP

### ISSUE THREAD

**Issue by davisee** [jasp-stats/jasp-issues#1171]
If I plot the model-averaged posteriors in a bayesian ANOVA and want to expand the plot, JASP crashes before it can do so. But it is impossible to visualize the data in the way it outputs in the results. 
![plot_bayesian_anova](https://user-images.githubusercontent.com/17937019/108425619-b4968400-7208-11eb-818e-78d563a58036.png)

**Comment by vandenman** [comment]
So I have a couple of questions:

- What OS and JASP version do you use?
- Does this happen for all data sets? Could you try to reproduce it with the `debug.csv`? You should be able to find that in `Open` -> `Data Library` and then the last entry.
- If you change `Group levels in single plot` to `Individual plot per level`, does the error still occur?
![image](https://user-images.githubusercontent.com/21319932/108476514-67f78b00-7292-11eb-9389-86b8a5a34477.png)


If I create a 3-way interaction that also looks quite cluttered:

![image](https://user-images.githubusercontent.com/21319932/108476272-2070ff00-7292-11eb-87c9-455cc1ac965f.png)

In the bottom right, I can click and drag to resize the figure. This works for me without any issues:

![image](https://user-images.githubusercontent.com/21319932/108476374-3ed6fa80-7292-11eb-9bc0-8d8689f1a0c8.png)

But I understand correctly that at this step JASP crashes?

**Comment by davisee** [comment]
I am using Windows 10 (PC), JASP version 0.14.1. This has only been happening since I downloaded this new version this month. And yes, it is when I go to resize the figure it crashed. It only happens for the interaction graph, none of my other graphs, which is odd but it's consistent.

**Comment by Ghassan-Okour** [comment]
> If I plot the model-averaged posteriors in a bayesian ANOVA and want to expand the plot, JASP crashes before it can do so. But it is impossible to visualize the data in the way it outputs in the results. ![plot_bayesian_anova](https://user-images.githubusercontent.com/17937019/108425619-b4968400-7208-11eb-818e-78d563a58036.png)

Yes, it happens every time I expand any plot to be more readable; even in the last version.

**Comment by boutinb** [comment]
Can you send us the log files: https://github.com/jasp-stats/jasp-desktop/blob/stable/Docs/user-guide/logging-howto.md ?
