### ISSUE TITLE
Independent samples T-Test unable to complete test; error 

### ISSUE THREAD

**Issue by VMP2021** [jasp-stats/jasp-issues#1172]
* JASP version: JASP 0.14.1

* OS name and version: Windows 10 v1909
* Analysis: Independent Samples T-test
* Bug description: analysis couldn't be completed; the following error message appeared

This analysis terminated unexpectedly. 

Error in .ttestIndependentEqVarFill(equalityVariance, dataset, options): object 'result' not found

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.ttestIndependentEqVarTable(jaspResults, dataset, options, ready, type)

.ttestIndependentEqVarFill(equalityVariance, dataset, options)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

* Expected behaviour: should have been able to complete the analysis

#### Steps to reproduce:
5
![image](https://user-images.githubusercontent.com/79347281/108582560-2272a680-7302-11eb-9ef9-09390e40b63c.png)

The problem may be with the size of my file; almost 403K records being compared in this test alone (and multiple other columns of same length in this file).

**Comment by vandenman** [comment]
Thanks for reporting the error! 

I tried to replicate the problem with simulated data of 403K observations but unfortunately, I could not reproduce the error. Would it be possible to share the data that caused this error? I should only need the two columns `V2010_2020NUM_spp_diversity_10...` and `V2010_2020group_10km2grid` to reproduce the error.
