### ISSUE TITLE
Problem One Sample t test & effect size

### ISSUE THREAD

**Issue by pandelis** [jasp-stats/jasp-issues#1173]
Hi, 

* JASP version: 0.14.1
* Analysis: 
* Bug description: I noticed a problem when computing the effect size for One-Sample t test. In the following attached example I get 3.483 which is quite surprising giving the means (43.6 vs 42 and the sd 12.52) 
* Expected behaviour: d should be d = 0.1278 instead of 3,483 I think

Best regards,

[One Sample t-test.Effect Size.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/6023222/One.Sample.t-test.Effect.Size.jasp.zip)

**Comment by AlexanderLyNL** [comment]
Hi pandelis, 

This was changed in 0.14.1 to clarify the difference between estimation and testing, see also

https://github.com/jasp-stats/jasp-issues/issues/1142

However, it appears that this led to some confusion, which is why it'll be reverted in the next version. 

Cheers,
Alexander

**Comment by AlexanderLyNL** [comment]
Fixed: https://github.com/jasp-stats/jaspTTests/pull/39#event-4401880113
