### ISSUE TITLE
JASP crashed

### ISSUE THREAD

**Issue by jaccorenstrom** [jasp-stats/jasp-issues#1174]
* JASP version: 0.14.1
* OS name and version: macOS 10.16

* Analysis: 
* Bug description:
* Expected behaviour:

#### Steps to reproduce:

-----------------------------------------------------------------------

### Debug information:
**Engine # 0** process *does not exist (anymore)* and it's state is *initializing*.
**Engine # 1** process *crashed* and it's state is *initializing*.
**Engine # 2** process *crashed* and it's state is *initializing*.
**Engine # 3** process *crashed* and it's state is *initializing*.

[Commit used](https://github.com/jasp-stats/jasp-desktop/commit/f2cb223fef6b15089fd6e9da54825d370c1ece57)

**Comment by boutinb** [comment]
Hi @jaccorenstrom Could you describe a bit more what happens: is it when starting JASP, loading data, running an analysis?
Could you also give the log files: https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/user-guide/logging-howto.md ?
