### ISSUE TITLE
data transformation not functioning

### ISSUE THREAD

**Issue by narcilili** [jasp-stats/jasp-issues#1177]
* JASP version: 14.1

* OS name and version: windows 10
* Analysis: 
* Bug description: hello, i tried to log transform my data but the 'create column' does not function
* Expected behaviour: i would expect the 'create column' to allow me to write a new column name.

#### Steps to reproduce:
1. Go to 'load the csv file'
2. Click on 'click on the + sign '
3. Scroll down to 'create computed column appears'
![datatransformproblem](https://user-images.githubusercontent.com/61888367/109115898-ab626580-777a-11eb-8b5a-7f0999ba3875.JPG)

**Comment by boutinb** [comment]
Hi @narcilili If you give a name to the Computed Column, then the 'Create Column' button should become available.

**Comment by narcilili** [comment]
hello boutinb,
i got it. thanks a lot. have a nice day.
