### ISSUE TITLE
help on summary stats bayesian one sample t test

### ISSUE THREAD

**Issue by narcilili** [jasp-stats/jasp-issues#1179]
hello jaspers,
I am working on fish length-weight relationship: log W = log a + b log L with a sample size of n = 112. i wonder if i can get some feedback on using summary stats bayesian one sample t test as a substitute for the frequentist t statistic = (b-3)/SE = 3.691, where b is the observed regression coefficient, 3 is the isometric value, SE is the standard error of the regression coefficient. The null is there is no difference between the b and 3. 
This is what I got using the summary stats Bayesian one sample t test where the alternative is 56 times more likely than the null. cheers
![fishlwr](https://user-images.githubusercontent.com/61888367/109278911-0e73fb00-7854-11eb-9f51-bb7f1e8be5aa.JPG)

**Comment by boutinb** [comment]
@EJWagenmakers or @akashrajkn Could you answer this issue?

**Comment by juliuspf** [comment]
This question might be better placed in the forum: https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiq_ISQ5rT7AhUISPEDHYwlBMgQFnoECA8QAQ&url=https%3A%2F%2Fforum.cogsci.nl%2Fcategories%2Fjasp-bayesfactor&usg=AOvVaw2NLQoVETBKcDzBFxBRP5S_

**Comment by AlexanderLyNL** [comment]
Using a Bayesian t-test instead of a frequentist t-test is reasonable.
