### ISSUE TITLE
Enhancement request: GUI for a model editor for Bayes data analysis

### ISSUE THREAD

**Issue by fplatz** [jasp-stats/jasp-issues#118]
* Enhancement: Statistical Modelling
* Purpose: model editor for Bayer analysis
This is my last post for today (I promise you that!): Is it possible to develop a GUI for building statistical routines and models as proposed by Lee and Wagenmakers (2014) or Kruschke (2014) but not by typing endlessly lines of (jag of wing) code but instead by using icons (for distributions) arrows etc. as the authors used to visualize the bayes alternatives to the NHST approaches. The only thing a scientist have to do is to give the distribution parameters or mathematical formulas (at a minimum). Perhaps this might be a step towards a new way of click and Drag & Drop - Bayes data analysis/modelling?

Cheers,
Friedrich

**Comment by tomtomme** [comment]
@fplatz @EJWagenmakers 
Any update on the horizon for bayesian model editors after 7 years? Or should we close this one for now.

**Comment by fplatz** [comment]
I think, that this idea is of high value not only for research but also for educational purposes. But I understand, that this might not be of main interest.Am 20.02.2024 um 11:40 schrieb Thomas Langkamp ***@***.***>:﻿
@fplatz @EJWagenmakers
Any update on the horizon for bayesian model editors after 7 years? Or should we close this one for now.

**Comment by EJWagenmakers** [comment]
Well I will say that there are popular GUIs for Bayesian expert networks. All of this can be done in JAGS/Stan, but the GUIs remain very popular. So I can see the added value there, but it would be a tremendous effort. So I don't think it is a high priority and since we haven't done anything about it in 7 years I will close this isse.

**Comment by fplatz** [comment]
I can understand this point of view. When I suggested this idea, I thought if an „all-in-one-box“-solution as this seemed to me as overall mission for JASP due to the fact, that several solutions did also exist before JASP.  But I see, that this is to resource demanding.Anyway, please keep on moving JASP as you did! It’s a fantastic solution! Am 20.02.2024 um 12:07 schrieb EJ ***@***.***>:﻿
Well I will say that there are popular GUIs for Bayesian expert networks. All of this can be done in JAGS/Stan, but the GUIs remain very popular. So I can see the added value there, but it would be a tremendous effort. So I don't think it is a high priority and since we haven't done anything about it in 7 years I will close this isse.
