### ISSUE TITLE
Simple slopes analysis in regression models estimation

### ISSUE THREAD

**Issue by irenesco** [jasp-stats/jasp-issues#1181]
When using a moderated regression approach it is often necessary to report the conditional effect of the IV at different levels of the moderator (spotlight analysis) or to examine the conditional effect of the IV at for all values of the moderator in order to identify the region of significance for the moderated effect (Johnson-Neyman approach).
* Enhancement: This option (estimated marginal means or simple slope analysis, and Johnson-Neyman analysis) could be added to the regression estimation or to the visual modeling module
* Purpose: examining interaction effect
* Use-case: moderate regression analysis

**Comment by irenesco** [comment]
By the way, thank you for developing JASP - it is a fantastic package and it keeps getting better and better.

**Comment by boutinb** [comment]
@dustinfife Do you think you could add this to your module?

**Comment by dustinfife** [comment]
It already does this naturally. See this blog post:

https://quantpsych.net/simple-slopes-models-in-jasp-r/

At this point, it doesn't allow you to specify the number of levels or the "breakpoints" of those levels. It something I've been meaning to do, but just haven't gotten around to doing it yet. Is that something you need to complete your analysis? Or is the module sufficient as is? If the former, that may be the fire I need to take care of it :)

**Comment by irenesco** [comment]
Hi Dustin!
Thanks for your super quick reply! These two analyses would be incredibly helpful as the Johnson-Neyman approach is one of the default ways to examine interaction patterns in my field, so I would be using it extensively 
(see: https://www.researchgate.net/publication/254957998_Spotlights_Floodlights_and_the_Magic_Number_Zero_Simple_Effects_Tests_in_Moderated_Regression)
Let me know if there is any way I can help with this, and thank you in advance!
Irene

**Comment by irenesco** [comment]
PS I've looked into flexplot, but (I guess by design) does not provide the option to estimate the simple slopes at custom values, or at all values to identify a region of significance.

**Comment by patc3** [comment]
The flexplot module does not provide hypothesis tests for the simple slopes. The graphs are nice, but a significant interaction could underly any combination of significant/non-significant simple slopes. 

My understanding is that (as of today in version 0.17.2.1) it's not possible to get simple slopes and therefore to probe significant interactions, is this accurate?

**Comment by boutinb** [comment]
Hi @patc3, The flexplot module is a module made by @dustinfife , and it is in fact a JASP wrapper of his own flexplot package. I think if you have requests, it is better to do it on his own Github repository: https://github.com/dustinfife/flexplot

**Comment by patc3** [comment]
Ok... I was simply responding to Dustin's comment in this thread

**Comment by dustinfife** [comment]
> The flexplot module does not provide hypothesis tests for the simple slopes. The graphs are nice, but a significant interaction could underly any combination of significant/non-significant simple slopes.

Correct. Flexplot does not do simple slopes analyses as traditionally done.  

> My understanding is that (as of today in version 0.17.2.1) it's not possible to get simple slopes and therefore to probe significant interactions, is this accurate?

Yes to the first statement, no to the second. Flexplot will not do a simple slopes analysis, but it will probe interactions. The way flexplot does things is superior to simple slopes analysis. See this[ blog post about why](https://quantpsych.net/simple-slopes-models-in-jasp-r/). But, in short, simple slopes takes a continuous variable and dichotomizes it when it's not necessary. Flexplot doesn't do this.

**Comment by tomtomme** [comment]
We have the PROCESS module now, so this can be closed I think. Feel free to reopen, if I am mistaken.
