### ISSUE TITLE
Input excel format

### ISSUE THREAD

**Issue by PlaytosSandl** [jasp-stats/jasp-issues#1185]
My suggested request is to input excel format files.  Although JASP will read csv files, reading excel files would make data management and manipulation so much easier.
Thank you.
Tim Seifert, Ph.D.

P.S. I would also encourage you to include adjusted residuals for contingency tables.  They are very useful.  Since JASP already displayed observed and expected values, the addition should be minimal.

**Comment by boutinb** [comment]
For Excel, we also support odt format (Microsoft supports it actively).
For the contingency tables, maybe @vandenman can answer you better.

**Comment by asjones987** [comment]
It wold be helpful if reading XLSX files was supported out of the box.  It sounds like some of the options are cross platform compatible.

https://www.marsja.se/r-excel-tutorial-how-to-read-and-write-xlsx-files-in-r/

http://www.sthda.com/english/wiki/r2excel-read-write-and-format-easily-excel-files-using-r-software

http://www.sthda.com/english/wiki/r-xlsx-package-a-quick-start-guide-to-manipulate-excel-files-in-r

**Comment by tomtomme** [comment]
Some more detail on the ODS (not ODT) support: 
You do NOT have to export to CSV. You can save your XLSX as an ODS in Excel using the "save as" menu and scrolling to the very end of all the available file types. Both file formats (ods and xlsx) are very similar and you would not loose any formulas etc. And you can of course open the ODS in JASP directly.

**Comment by tomtomme** [comment]
@PlaytosSandl 
Feel free to close this issue since its also discussed in
https://github.com/jasp-stats/jasp-issues/issues/611
