### ISSUE TITLE
JASP crashes on syncing changed .csv files

### ISSUE THREAD

**Issue by OehiAlm** [jasp-stats/jasp-issues#1193]
I've been having this issue a lot lately where JASP frequently either crashes on startup with "large" .jasp files or does so, when manually synchronizing with the .csv file that the Data is based on. The .csv file in question was changed outside of JASP (as far as I know, thats the only possible way) and when loading it up, JASP seems to detect the changes fine, as i could see from the log file that was created but then crashes without any further info.

Here are the last couple of lines from the .log file (shortened for better reading and due to privacy stuff)
[JASP log file before crash.log](https://github.com/jasp-stats/jasp-issues/files/6091499/JASP.log.file.before.crash.log)

**Comment by boutinb** [comment]
Hi @OehiAlm Can you read the file with an 'empty' JASP? If not, can you send me the file?

**Comment by OehiAlm** [comment]
yeah, i can read the .csv if theres no project loaded

**Comment by boutinb** [comment]
Could you send me the JASP file and the new data file?

**Comment by OehiAlm** [comment]
I sent them to your Email adress

**Comment by OehiAlm** [comment]
[JASP Data.zip](https://github.com/jasp-stats/jasp-issues/files/6148386/JASP.Data.zip)

**Comment by boutinb** [comment]
Hi @OehiAlm I could indeed reproduce the crash. I have to understand exactly why it crashes, but the first thing I see is that the new data file (with which JASP tries to synchronize) misses 18 variables compared with the old data file, and that many of these missing variables are used in the analyses. So I wonder if this is really the goal to synchronize JASP with such a file?

**Comment by OehiAlm** [comment]
I understand the concern. My intention here was to not have to do delete and then redo the analyses when updating the underlying data file. I could have easily done that since the project isnt that big, it's just a convenience thing of keeping the preferences/adjustments made in the existing analyses and just switching out the old variables for the new ones (or adding the new ones when the old ones have been deleted from the analysis). 
I would love if JASP would tell me that there are some variables in the analyses that are not available in the new / updated data file anymore (without crashing). I think right now (if there are not too many changes) JASP just deletes the missing variables from the analyses, which is okay for small analyses with few variables.

**Comment by boutinb** [comment]
Hi @OehiAlm Yes, for sure JASP should not crash, and your example is really useful for me to make JASP more robust. Until now the changes in the data file are processed silently, but it is indeed a good idea to let know the user that the file has changed, and whether some used variables are missing.

**Comment by OehiAlm** [comment]
Awesome. Looking forward to it :)
