### ISSUE TITLE
I can't load .DAT and .SAV file into jasp

### ISSUE THREAD

**Issue by obaxlove** [jasp-stats/jasp-issues#1196]
Hi,

I am newly introduced to JASP and I can't load both .DAT  and .SAV files downloaded directly from DHS programs site.

**Comment by boutinb** [comment]
Hi @obaxlove, what do you mean by the DHS site: do you use JASP from a web site? That would mean that this site use the Rollapp version (https://www.rollapp.com/launch/jasp). For this version you have either to pay to use local files from your computer, or you have to use the OSF feature (Menu Open/OSF).

**Comment by JorisGoosen** [comment]
@boutinb I think he means he downloaded some files from somewhere and he can't open them in JASP.

@obaxlove which OS do you use?
Can you share the files in question?

**Comment by obaxlove** [comment]
I have been able to use the file.

Best regards,


Obasanjo A. Bolarinwa

________________________________
