### ISSUE TITLE
SEM analysis modification indices

### ISSUE THREAD

**Issue by FD511** [jasp-stats/jasp-issues#1197]
* JASP version:0.14.1
![Schermafbeelding 2021-03-09 om 08 10 39](https://user-images.githubusercontent.com/80311077/110432292-31ea4180-80af-11eb-9338-454de92dd890.jpg)

* OS name and version: 11.2.1 MacOS
* Analysis: SEM analysis modification indices* Bug description:
* Expected [behaviour: see attached file 

#### Steps to reproduce:
1. Go to '...'modification indices

**Comment by Kucharssim** [comment]
Hello @FD511 ,

unfortunately, I cannot reproduce this error. I also do not see any attached file. Note that to attach a file to a GitHub issue, you need to upload it directly to the website, not send it by e-mail.

Thanks.

Best,
Simon
