### ISSUE TITLE
Repeated-measures ANOVA - big design matrix error

### ISSUE THREAD

**Issue by anarfouto** [jasp-stats/jasp-issues#1202]
* JASP version: 0,14.1.0

* OS name and version: Windows
* Analysis: Repeated-measures ANOVA
* Bug description: I have a .csv file with 1000 entries (samples) and 14 columns (repeated measures). When I run a 2-way repeated-measures ANOVA analysis I ran into an error: "Some parameters are not estimable, most likely due to empty cells of the design". I checked the file in excel and there aren't empty cells in the matrix. Then, I tested to run the same analysis with only 100 entries and it ran without any issues. Does JASP has a limitation on the amount of data it can process?
* Expected behaviour: I was expecting to get p-values using the complete design matrix without problems. 

#### Steps to reproduce:
1. Go to 'ANOVA'
2. Click on 'Repeated-Measures ANOVA'
3. Set up '2 within-subjects factors'
4. See an error
![jasp-error](https://user-images.githubusercontent.com/71497582/110696777-66f7b080-81e3-11eb-9aac-c7bd728862a8.png)

Dataset for reproducibility will be sent by email.

**Comment by JohnnyDoorn** [comment]
Hi @anarfouto ,

Thanks for your report. Could you send this data set (or even better, a saved jasp file that includes the your error) by email to j.b.vandoorn at uva.nl? Because I just made a mock data set according to your specifications, but cannot replicate your issue (the computation is very slow though, but this is a byproduct of the R function "lm" unfortunately).

Kind regards,
Johnny

**Comment by anarfouto** [comment]
Hi @JohnnyDoorn,

I already sent the dataset as you requested. Thank you for helping me! :)

Cheers,
Ana

**Comment by JohnnyDoorn** [comment]
Hi @anarfouto,

Where did you send the data set, because I cannot find it (if you sent it to the general JASP email address, could you also send it to the mail address I gave above? 

Cheers
Johnny

**Comment by anarfouto** [comment]
Hi @JohnnyDoorn,

Firstly, I sent it yesterday to the general JASP email address. Then, I forwarded it to you. Is this the correct email: j.b.vandoorn@uva.nl ?

**Comment by JohnnyDoorn** [comment]
Hi @anafouto,

Yes, I got it now!

**Comment by tomtomme** [comment]
@anarfouto 
Was this resolved?
If so, how?
If not, can you test a current JASP version?
