### ISSUE TITLE
Unable to open data in editor under macOS -> add recognition for missing default editor (*.sav original datafile for example)

### ISSUE THREAD

**Issue by kovac254** [jasp-stats/jasp-issues#1203]
* JASP version: 0.14.1

* OS name and version: macOS Big Sur 11.2.2
* Hardware: MacBook with Intel x86 CPU
* Bug description: When I try to open the data in a spreadsheet editor by doubleclicking it I get a message saying "No default spreadsheet editor for file _filename-without-filetype-suffix_.Use Preferences to set the right editor." I have tried setting the OS default editor for *.csv files to TextEdit, Numbers and MS Excel to no avail. I have also tried to manually set the editor in Preferences but I still got the same results. I have restarted both Jasp and the whole computer in between. The very same behavior was reported [here](https://forum.cogsci.nl/discussion/6445/how-to-edit-a-jasp-document-help) so it seems to be a bug affecting multiple macOS users.
* Expected behaviour: The spreadsheet editor opens and allows you to edit the data.

#### Steps to reproduce:
1. Open a *.jasp dataset
2. Doubleclick on the data

**Comment by JorisGoosen** [comment]
Is it possible that the name you choose for your file does not have a file extension?

Because the error you posted here says `filename-without-filetype-suffix`, you seem to be expecting `csv`.
So I would suggest you give it that extension and see if it works then.

It then depends on how you made the file, I would expect JASP to add this extension but it seems to go wrong for you. I can look into that once I know whether manually adding the extension helps you or not.

**Comment by kovac254** [comment]
Sorry for confusion. I'm working with a `*.jasp` file that was created by opening a `*.sav` file and saving it as `*.jasp`. All of these steps were performed on my machine with the same install of JASP.

I have mentioned the `filename-without-filetype-suffix` because the suffix is missing in the error message. It made me wonder whether there is an issue with JASP not providing a suffix for what I assume to be a temporary `*.csv` file generated for editing in the spreadsheet editor.

**Comment by JorisGoosen** [comment]
Well, it depends on the jasp-file and how you made it.

In your case you opened a `*.sav` file with JASP which it remembered. 
So now when you double-click the jasp-file it will try to open the `*.sav` file with your default editor for that.
And apparently you do not have one installed and hence you get this error.

It isn't a very clear message I'll grant you that. And it should really notice this and suggest to generate a file that you *can* open, such as `csv`. But it doesn't do that now...

You can notice quick enough if this is the case by moving or renaming your original datafile. That way JASP can't find it anymore and it will suggest generating a new file, which will be `csv` and should thus use your system-default for that.

**Comment by kovac254** [comment]
I can confirm this helped! Improving the error message/switching it for the dialog that shows up when the file is moved/renamed would be great but at least a workaround will pop-up now when you google the error message. Feel free to close the issue if you consider it closed as well.

**Comment by JorisGoosen** [comment]
You are welcome!

I'll just use this issue to remind me to make that clearer/better.
