### ISSUE TITLE
Interaction effect missing in Kruskal-Wallis test

### ISSUE THREAD

**Issue by mservantufc** [jasp-stats/jasp-issues#1206]
Using JASP version 0.14.1 on windows 10, and running a Kruskal-Wallis test with 2 factors, JASP only returns the p-value for each main effect, but the p-value for the interaction is missing. See .jasp file attached. 
Best,
Mathieu
[full_data_Eysenck_JASP.zip](https://github.com/jasp-stats/jasp-issues/files/6137354/full_data_Eysenck_JASP.zip)

**Comment by tomtomme** [comment]
@mservantufc 
Thx for the request.
Closing since duplicate of https://github.com/jasp-stats/jasp-issues/issues/1531
