### ISSUE TITLE
Cohen's d calculation in One Sample t-test is miscalculated

### ISSUE THREAD

**Issue by npwolff** [jasp-stats/jasp-issues#1207]
* JASP version: 014.1

* OS name and version: Windows 10 Enterprise 1803
* Analysis: One Sample t-test
* Bug description: In the results section, Cohen's d calculation on One Sample t-test is miscalculated
* Expected behaviour:

Cohen's d is calculated by taking the difference from the sample mean and population mean and dividing that value by the standard deviation of the sample.  The current code appears to take the sample mean (not the mean difference) and divide it by the standard deviation.  

In fact, a separate column in the summary table to report the mean difference would be appropriate.  I believe an earlier version of the the software included the mean difference in a column, but did not include the sample mean.  It appears that the effort to fix one issue created another.  Both sample mean and mean difference are appropriate and the cohen's d calculation must reference the mean difference.  

[One sample t-test.zip](https://github.com/jasp-stats/jasp-issues/files/6142512/One.sample.t-test.zip)

Given a population mean (mu) if 178, this data set should give you a sample mean of 177.609, a mean difference of -0.391, and a cohen's d of -0.0796.

**Comment by vandenman** [comment]
Thanks for reporting this!

The effect size in JASP 0.14.1 is indeed not accounting for the test value. This behavior will be reverted in the next release (see https://github.com/jasp-stats/jaspTTests/issues/36).
