### ISSUE TITLE
Error in JASP Data Library

### ISSUE THREAD

**Issue by marcmehu** [jasp-stats/jasp-issues#1208]
Good afternoon,

As I was preparing a stats course using JASP, I realised that some of the data files in the OSF data library have errors (in chapter 5. Frequencies). 

- Emily Rosa.csv
- Hungry Zombies/Hungry Zombies.csv
- Sun Block Lotions.csv
- Zombies.csv

Let me take this opportunity to thank you for your team’s work on this excellent platform.

Best wishes,

Marc

**Comment by EJWagenmakers** [comment]
Hi Marc,

Thanks for the feedback. What OSF directory are you referring to, and what specifically are the errors?

Cheers,
E.J.

**Comment by marcmehu** [comment]
Hello E.J.,

Thanks for your prompt response, the link is: https://osf.io/ncekh/  (The JASP Data Library)
The directory name is <5. Frequencies>. There appears to be a column split at the letters "t" or "u", depending on the file, though it turns out that the issue is only in the preview of the file on the OSF website. The files open fine in JASP.

For example, the file Emily Rosa.csv looks like this
<img width="1021" alt="EmilyRosa" src="https://user-images.githubusercontent.com/80776674/111375671-d4ea1f00-869e-11eb-8f90-476db09d94b2.png">

Sun Block Lotions.csv
<img width="1021" alt="SunBlockLotions" src="https://user-images.githubusercontent.com/80776674/111375979-314d3e80-869f-11eb-9d5c-1882e560f256.png">

Zombies.csv
<img width="1029" alt="HungryZombies" src="https://user-images.githubusercontent.com/80776674/111375888-124eac80-869f-11eb-83d0-f3be78e4bcf0.png">

So it is not really a serious issue, sorry for having you waste your time on this. 

Best,

Marc

**Comment by boutinb** [comment]
@EJWagenmakers or @Kucharssim Do you have write access to this OSF repo? Then could update the files, if not can you give the permission?

**Comment by Kucharssim** [comment]
@EJWagenmakers is administrator, so he can make @boutinb a contributor to the OSF project. 

I just updated Emily Rosa.csv (https://osf.io/z8ufx/), but it still has this problem on OSF (the file is correct though). I think this might be a problem of OSF and not us?

**Comment by EJWagenmakers** [comment]
Exactly, I think it is an OSF issue. @marcmehu: thanks for pointing this out. Note that JASP comes packaged with all these data sets (they are available in the JASP Data Library under "Open"). So there is no need to get the files from the OSF.

**Comment by Kucharssim** [comment]
Well actually, GitHub also complains about this (https://github.com/jasp-stats/jasp-desktop/blob/development/Resources/Data%20Sets/Data%20Library/5.%20Frequencies/Emily%20Rosa.csv):

![Screenshot 2021-03-17 at 11 33 13](https://user-images.githubusercontent.com/7093546/111454210-b32b7f00-8714-11eb-81cc-2c1834a7fdc2.png)

The issue appears for data sets with one column - in that case, OSF and GitHub expect the column still end with a comma, but we leave it without. I can fix this (I still have some updates to do with the Data Library anyways)

**Comment by marcmehu** [comment]
Thanks a lot for looking into this issue! And I will use the data files integrated in the JASP package, it is more straightforward, and so will it be for students (it also teaches me that I need to further explore JASP as there has been more work in it than I know of). From my perspective, the issue is resolved, and I am glad you found the problem and a solution.
Have a nice day!
Marc

**Comment by juliuspf** [comment]
@Kucharssim you want to close this?

**Comment by tomtomme** [comment]
@EJWagenmakers 
This was never fixed. And I really think we should delete the OSF data library. It was not updated since 3 years and does not reflect the quality and quantity of JASPs data library. 
The OSF project should just point to the up to date Online Data library which is already linked on the jasp homepage via https://johnnydoorn.github.io/DataLibraryBookdown/

And almost nobody downloads the files from the OSF, so nobody will miss them, see:
![image](https://github.com/jasp-stats/jasp-issues/assets/4428185/53003fd9-ff02-418f-b627-c9e530fa7680)

**Comment by EJWagenmakers** [comment]
Yes, delete & point to other sources instead seems a good idea

**Comment by tomtomme** [comment]
@Kucharssim 
The link is now set on the OSF project, nice.
But the old files are still there. I would second EJ on better deleting them.
