### ISSUE TITLE
Results of the Shapiro-Wilk test form multivariate normality..  Are they wrong?

### ISSUE THREAD

**Issue by ecordonP** [jasp-stats/jasp-issues#1209]
I have doubts that the results offered by the  Shapiro-Wilk test form multivariate normality test are correct.  I have applied the test to a data set and I obtain Shapiro-Wilk = 0.981 and p = 0.743, which is indicative that the data is distributed according to a multivariate normal.  Using R and the mvShapiro.test package (https://cran.r-project.org/web/packages/mvShapiroTest/mvShapiroTest.pdf), for the same data I obtain MVW = 0.94778 and p = 0.01097, which indicates that we must reject multivariate normality.  Additionally, I used the MVN package (https://cran.r-project.org/web/packages/MVN/MVN.pdf), and Mardia's multivariate normality test also indicated that the data were not distributed according to a multivariate normal.
Therefore, I have doubts about whether the test results returned by JASP are correct.

**Comment by EJWagenmakers** [comment]
Thanks for reporting this. @JTPetter : was this analysis part of your validation project? Team: should we add these analyses?

**Comment by vandenman** [comment]
@ecordonP Thanks for reporting this, this is indeed a bit tricky.

I'm assuming this is about the assumption check within MANOVA, but please correct me if I'm wrong.

In JASP we use the R package [`mvnormtest`](https://cran.r-project.org/web/packages/mvnormtest/index.html). If I apply `mvnormtest` to some sample data and compare the results to `mvShapiro.test`, I get different results:

```r
library(mvShapiroTest)
library(mvnormtest)
library(mvtnorm)
# note that mvShapiroTest sees rows as observations while mvnormtest sees columns as observations.

p <- 10
sigma <- crossprod(matrix(runif(p^2), p, p))
X <- rmvnorm(1e3, sigma = sigma)

# example from ?mshapiro.test
data(EuStockMarkets)
C <- t(EuStockMarkets[15:29,1:4])

mshapiro.test(C)
#> 
#>  Shapiro-Wilk normality test
#> 
#> data:  Z
#> W = 0.81607, p-value = 0.005955
mvShapiro.Test(t(C))
#> 
#>  Generalized Shapiro-Wilk test for Multivariate Normality by
#>  Villasenor-Alva and Gonzalez-Estrada
#> 
#> data:  t(C)
#> MVW = 0.91977, p-value = 0.09392

mshapiro.test(t(X))
#> 
#>  Shapiro-Wilk normality test
#> 
#> data:  Z
#> W = 0.99597, p-value = 0.01045
mvShapiro.Test(X)
#> 
#>  Generalized Shapiro-Wilk test for Multivariate Normality by
#>  Villasenor-Alva and Gonzalez-Estrada
#> 
#> data:  X
#> MVW = 0.99818, p-value = 0.3046
```

The two packages use different methods but we should look into which package performs better (e.g., run a small simulation study). I'm not too bothered that the p-values of the packages differ (they're likely based on different methods) as long as they properly control the error rate.

Maybe @JohnnyDoorn (who programmed this 2 years ago) remembers why he chose this particular package?

**Comment by JTPetter** [comment]
> Thanks for reporting this. @JTPetter : was this analysis part of your validation project? Team: should we add these analyses?

No, the assumption checks for MANOVA (as most assumption checks) still need to be validated.

**Comment by JohnnyDoorn** [comment]
I just took a quick look at this, and I think the main difference between the results that the two methods/functions give, is how they are affected by correlated columns.
If I simulate under the null hypothesis using 
```
  p <- 10
  sigma <- diag(p)
  X <- rmvnorm(1e3, sigma = sigma)
```

Then I obtain the following distributions of p-values:
![RplotShapirp](https://user-images.githubusercontent.com/15704203/201948628-5a340ef8-8543-4054-ad4c-007072cfeb44.png)
which is similar to what I obtain when I simulate using the random sigma of @vandenman 
```
  p <- 10
  sigma <- crossprod(matrix(runif(p^2), p, p))
  X <- rmvnorm(1e3, sigma = sigma)
```
I find it rather puzzling that mshapiro.test does not show a uniform distribution for neither of the 2 scenario's. What else could the null hypothesis be? @vandenman do you have any idea?

Full code:
```
mvP <- mP <- numeric(1e4)
for (i in 1:length(mvP)) {
  p <- 10
  # sigma <- crossprod(matrix(runif(p^2), p, p))
  sigma <- diag(p)
  X <- rmvnorm(1e3, sigma = sigma)
  
  mvP[i] <- mvShapiro.Test((X))$p.value
  mP[i] <-  mshapiro.test(t(X))$p.value # JASP
  print(i)
}
par(mfrow = c(1, 2))
hist(mvP, freq = FALSE, col = rainbow(10), main = "mvShapiro", las = 1)
hist(mP, freq = FALSE, col = rainbow(10), main = "mShapiro/JASP", las = 1) #  JASP
```

**Comment by tomtomme** [comment]
@JTPetter 
Do you have an update, if Shapiro-Wilk was added to the validation project?
I do not like such tests, but they are widely used and should reflect the results of other popular software packages like SPSS, if in doubt.

**Comment by JTPetter** [comment]
@tomtomme No, the validation project has not been extended since JASP 0.13.1. There is, however,  some work on this at the moment. The aim is to create and automatize verification tests similar to the unit tests.

**Comment by tomtomme** [comment]
I would vote for that, yes!

**Comment by JohnnyDoorn** [comment]
@ecordonP Sorry for the huge delay, but the new version of JASP (released this month) will include the improved Shapiro calculation, using the mvShapiroTest package.

**Comment by ecordonP** [comment]
@JohnnyDoorn There is nothing to forgive! We are very grateful for the great work you are doing with this magnificent free software. Best regards.
