### ISSUE TITLE
Variable type changes upon spreadsheet sync

### ISSUE THREAD

**Issue by djdekker** [jasp-stats/jasp-issues#1213]
* JASP version: 0.14.1
* OS name and version: macOS Big Sur 11.2.3
* Analysis: N/A
* Bug description: After syncing with the spreadsheet editor a variable type may change even if the values remain untouched.
* Expected behaviour: The variable type, once determined, stays the same after syncing with the spreadsheet editor.

Steps to reproduce:

[scores.csv.zip](https://github.com/jasp-stats/jasp-issues/files/6158914/scores.csv.zip)

1. Open the dataset both in JASP and in Excel. Note how in JASP, the variable is regarded as an ordinal variable and JASP truncates the decimals (why?).
2. In Excel, copy column A to column B. Do not make any changes to column A.
3. See JASP changing the variable type of both column A and B to scale and showing the decimals.

This also works the other way around: after deleting column B from the Excel sheet and syncing, JASP truncates the values again and regards the variable as ordinal.

Here is a short video clip of what's happening:

https://user-images.githubusercontent.com/5346286/111520638-95800900-8758-11eb-9d77-ec863da1a3f9.mp4

**Comment by boutinb** [comment]
This is quite a funny bug.... JASP tries first to find the column separator in the file. As you have first only 1 column, no separator in the header can be find, and the ',' (comma) is taken as separator by default. As you have numbers with decimals with ',', they are seen as 2 different integers, but the second integer is ignored as there is only one column (if you had a '.' (dot) as decimal, then you would not have got this problem).
When you copy in Excel the column to make a second column. the file is filed with ';': JASP takes that as column separator, and the numbers take back their decimals.
The solution is not to take ',' as default separator as there is only 1 column.
