### ISSUE TITLE
JASP ran into problem loading

### ISSUE THREAD

**Issue by nndgsptn** [jasp-stats/jasp-issues#1214]
* JASP version: 0.14.1
![Jasp error](https://user-images.githubusercontent.com/80874916/111577492-f5bc8c80-87e4-11eb-9712-7f9a1c15806a.png)

* OS name and version: Windows 10
* Analysis: Sorry, I don't know what happens here. It just automatically pops up when opening the app.
* Bug description:
* Expected behaviour:

**Comment by JorisGoosen** [comment]
Nothing bad is going on except that a list of known bugs couldn't be downloaded, don't worry about it.

I am planing to change the message a bit to make this clearer.

**Comment by JorisGoosen** [comment]
Very related to our (private) issue: https://github.com/jasp-stats/INTERNAL-jasp/issues/1286

**Comment by nndgsptn** [comment]
Thank you so much, Sir!

Pada tanggal Rab, 24 Mar 2021 pukul 18.11 Joris Goosen <
***@***.***> menulis:
