### ISSUE TITLE
Version incompatibility?

### ISSUE THREAD

**Issue by astefan1** [jasp-stats/jasp-issues#1216]
* JASP version: currently used version: f2cb223fef6b15089fd6e9da54825d370c1ece57, Nightly version: ??

* OS name and version: macOS Big Sur
* Analysis: not a particular analysis, issue occurs when (trying to) open JASP file
* Bug description: I'm not sure if you can reproduce this one, but I will give it a try: I created a couple of JASP files using a Nightly version that was released around the time when Don and Bruno gave the JASP programming workshop. Unfortunately, I don't know the version number of this version anymore. For a JASP workshop, I downgraded to the current stable version (0.14.1, see link above). However, there seems to be a version incompatibility between these JASP versions. I cannot open .jasp files created with the newer Nightly version using the old JASP version (0.14.1; see screenshot of error message below - the dataset gets loaded into JASP after this, but the analyses are gone), and if I remember correctly, I had some troubles opening old .jasp files with the new version, too (updated analyses were deleted). 

<img width="401" alt="image" src="https://user-images.githubusercontent.com/32095181/111636440-c748ac80-87f8-11eb-8cbb-a8adb2c06a0c.png">

I'm sorry that I cannot provide complete information on the JASP versions, and I'm afraid this might make the issue unsolvable. I attached one of the JASP files that yield an error message, maybe you can read out the version from this somehow? 

* Expected behaviour: JASP files should open with any version

[Bugs.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/6164628/Bugs.jasp.zip)

**Comment by astefan1** [comment]
Alright, I was able to reproduce the problem with the latest Nightly version: af3bdf333aaf4de7d32913193a4b93c7bd5b545e.  If I try to open an old JASP file, I get the following error message:

<img width="401" alt="image" src="https://user-images.githubusercontent.com/32095181/111639445-9027ca80-87fb-11eb-85c9-9f5825374092.png">

**Comment by vandenman** [comment]
jasp files saved with the nightlies are probably not backward compatible. There is some stuff in place for that but not many modules implemented it yet. @JorisGoosen any suggestions?

**Comment by JorisGoosen** [comment]
The nightlies are totally not backwards compatible. For a variety of reasons...

It is possible to fix all of this manually by opening the jasp file as a zip and manually changing stuff in the `analyses.json` or whatever it was called. But I highly doubt it would be worth the effort unless it was some superimportant jasp-file with stuff in it you can't otherwise reproduce.

**Comment by astefan1** [comment]
Okay, thanks for the quick reply! I already manually "converted" the nightly version to the currently used version, so no need to change stuff in the json file. However, it took me like 30-45 minutes, so I think it would be good if other people wouldn't run into these issues, otherwise a lot of time will be lost. I totally see that making the nightlies backwards compatible is not an option, but maybe information could be changed around the use of the nightlies? For example: Would it be possible to add a disclaimer about backwards compatibility to the nightly download page for example? You still tell people whose issues you fixed before a new version comes out to download the nightlies, right? So maybe add a disclaimer there too?

**Comment by astefan1** [comment]
Maybe something like: "We cannot ensure forwards or backwards compatibility of JASP files created with nightly builds. Please use the official version to share your work with others."?

**Comment by JorisGoosen** [comment]
Well, I had hoped that the current message was enough, aka this:

"These installers are generated automatically each night and contain development code; this means that they might not be stable.

**Use at your own risk!**

If you happen to find a bug in a nightly then it can't hurt to issue a bug report at our issue-tracker, but please be sure to mention that you used a nightly and indicate its commit. The commit can be found in the about window under "Sources"."

But if you didn't realize this than others might not either and adding another warning to the page is no trouble at all. I'll add your suggestion there!

**Comment by astefan1** [comment]
Thanks! Yes, I read this. I guess I just assumed it would only affect the program itself (i.e., program might crash, analyses might not work), but I didn't expect that there would be an incompatibility in the saved files. Thanks for adding the additional warning! :-)

**Comment by JorisGoosen** [comment]
Okido, Ive added "Keep in mind that, as these versions are in active development, no attempt is made to ensure backward- or forward-compatibility between jasp-files made with nightlies. So if you want to share your work, or even load it with some other version of JASP, you should not use these nightlies but are better off using some official release of JASP. "

As you can now see on the nightlies page, you might need to refresh.
