### ISSUE TITLE
GLM analysis terminated unexpectedly

### ISSUE THREAD

**Issue by nermd** [jasp-stats/jasp-issues#1217]
* JASP version: 0.14.3

* OS name and version: Fedora Linux using the Flatpak Distribution of JASP !! 
* Analysis: Visual Modeling -> Generalized Linear Modeling
* Bug description: analysis terminated unexpectedly Error in gzfile(file, 'wb'): cannot open the connection
* Expected behaviour: analysis should run

#### Steps to reproduce:
1. Go to 'Visual Modeling -> Generalized Linear Modeling'
2. Add DV
3. Add IV

I can reproduce this problem with any datafile, local, OSP, DataLibrary ... ! 

Full error msg: 
Error in gzfile(file, 'wb'): cannot open the connection

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])
doTryCatch(return(expr), name, parentenv, handler)
withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)
analysis(jaspResults = jaspResults, dataset = dataset, options = options)
flexplot:::glinmod_jasp(jaspResults, dataset, options)
.glinmod_model_plot(jaspResults, options, ready, dataset)
.create_flexplot_glinmod(jaspResults, modelplot, options, dataset)
save(terms, generated.formula, options, glinmod_results, dataset, file = '~/Documents/RPackages/data_before.rdata')
gzfile(file, 'wb')

Notes: 
there are two other issues relating to this problem: #1061 and #1054 
issue #1054 claims this bug is fixed since 0.14.01 
maybe a regression? 

thanks for looking into this!  
David

**Comment by boutinb** [comment]
Hi @nermd, Can you send your JASP file (or your data file)?
