### ISSUE TITLE
Unable to download JASP software

### ISSUE THREAD

**Issue by littlebowwows** [jasp-stats/jasp-issues#1218]
Hello JASP team,

I hope you are well. I am writing to clarify some doubts i have regarding the installation of the software onto my macbook. I have followed all the instructions and steps necessary to get the program up and running, but it seems to not be able to open. The error message states "this was downloaded from a webpage" and when i tried clicking "open", JASP will not run. 

May I know what could be the issue? Please help.

Thanks in advance,
Charmaine Ho

**Comment by AlexanderLyNL** [comment]
Hi Charmaine, 

Could you please try to right-click the program in your Application folder and then select Open? This is a standard mac issue, but it'll open the second time you do this. 

Cheers,
Alexander

**Comment by JorisGoosen** [comment]
And if that does not work, we would be interested to hear which version of MacOS you use.

**Comment by keecorby** [comment]
Hello @JorisGoosen I am having same issue. I have tried to click it in applications and reached out to apple support but cant solve the issue. The version I am using is:
10.12.6
macOS Mojave

**Comment by JorisGoosen** [comment]
You said "click it in applications", I assume you mean left-click?
What happens if you try rightclicking and then choosing "open" from the menu?

If it keeps failing a screenshot of the error would be helpful.
