### ISSUE TITLE
Request: Plots to spot bias (P-P, Q-Q and Zpred vs Zresid)

### ISSUE THREAD

**Issue by isakohrlund** [jasp-stats/jasp-issues#122]
Hi,

I'm trying to teach my students how to spot bias, but JASP currently lacks that functionality, so we're stuck with SPSS.

* Enhancement: P-P, Q-Q and zpred vs zresid plots
* Purpose: Spot bias

**Comment by vankesteren** [comment]
We have this now! not sure when this became available exactly though.
