### ISSUE TITLE
SEM (invariance)

### ISSUE THREAD

**Issue by krutcher7069** [jasp-stats/jasp-issues#1220]
* JASP version: 0.14.1

* OS name and version: Windows 10
* Analysis: Invariance SEM
* Bug description: 
![image](https://user-images.githubusercontent.com/67669189/111932992-248e7780-8af1-11eb-8558-f1cc77293a00.png)

* Expected behaviour: I expected a "normal" SEM output

#### Steps to reproduce:
1. Go to SEM and select Structural Equation Modeling
2. enter the following lavaan syntax:
stressor =~ Language + Culture + Academic + SocialInter
support =~ Socio + Instrument
strat_h =~ Heritage
strat_t =~ Thai
well =~ Creative + Coping + Social + Essential + Physical

well ~ strat_h + strat_t
strat_h ~ support + stressor 
strat_t ~ support + stressor
3. Choose the following options:
![image](https://user-images.githubusercontent.com/67669189/111933281-b302f900-8af1-11eb-8cab-71f09cb47ce2.png)
![image](https://user-images.githubusercontent.com/67669189/111933307-bc8c6100-8af1-11eb-935a-11d3f8e86a90.png)

[invariance SEM.zip](https://github.com/jasp-stats/jasp-issues/files/6179104/invariance.SEM.zip)

**Comment by tomtomme** [comment]
I tested the file in JASP 0.18.3. Everything fine now.
@krutcher7069 
feel free to reopen if not fixed on your side.
