### ISSUE TITLE
error ANOVA Descriptive statistics

### ISSUE THREAD

**Issue by 1995toilet** [jasp-stats/jasp-issues#1222]
* JASP version: 0.14.1

* OS name and version: Windows 10
* Analysis: ANOVA
* Bug description: Analysis terminated unexpectedly
* Expected behaviour: descriptive statistics

#### Steps to reproduce:
1. Go to Repeated measures ANOVA, Rename RM Factor 1 as B, RM Factor 2 as C. rename levels for B as B1, B2 and B3. Rename C levels as C1, C2, and C3. Assign levels accordingly
2. Click on Descriptive statistics

![image](https://user-images.githubusercontent.com/81231444/112134950-3adb2700-8c08-11eb-84d9-bd65b65b2cf5.png)

![image](https://user-images.githubusercontent.com/81231444/112134799-0ebfa600-8c08-11eb-93f6-3b3520d604b8.png)

**Comment by boutinb** [comment]
I can reproduce this problem just by setting one factor to 'C'  or 'E' (A, B, D or F work). In 0.15 this is solved apparently. @JohnnyDoorn do you know why it does not work in 0.14?
One workaround is just to avoid 'C' or 'E' as factor name.
