### ISSUE TITLE
Not able to adjust scaling funnel plot meta-analysis

### ISSUE THREAD

**Issue by W-Wentholt** [jasp-stats/jasp-issues#1223]
* JASP version: 0.14.1

* OS name and version: Windows
* Analysis: classical meta-analysis, random-effects model
* Bug description: scaling of funnel plot is not adjusted to the observed ES, omitting some studies from the funnel plot, affecting the clarity of visual inspection. 
* Expected behaviour: either automatic adjustment of scaling to observed (or filled) ES, or possibility to manually adjust the scaling

#### Steps to reproduce:
1. Go to 'Meta-analysis'
2. Click on 'Classical meta-analysis'
3. Select the variable 'FinalStat_correlation' at 'Effect Size'
4. Select the variable 'FinalStat_SE' at 'Effect Size Standard Error'
5. Select 'Restricted ML' in the drop-down menu under 'Method'
6. Select the variable 'Authors' at 'Study Labels'
7. Go to 'Statistics'
8. Select 'Funnel plot' at 'Model Fit'
9. The displayed funnel plot ranges from -0.15 to 0.15, while the observed ES include four studies with ES > [0.15](url
[JASP bug upload.zip](https://github.com/jasp-stats/jasp-issues/files/6191057/JASP.bug.upload.zip)
)

**Comment by sophieberkhout** [comment]
Sorry for the late response. It indeed looks like the scaling of the funnel plot is off. I will fix it. 

ps. Soon it will be possible to edit plots in JASP :)
