### ISSUE TITLE
Bayesian Linear Regression: Computation of P(incl) for analyses with interaction effects

### ISSUE THREAD

**Issue by astefan1** [jasp-stats/jasp-issues#1224]
* JASP version: 0.14.1

* OS name and version: 
macOS Big Sur
* Analysis:
Bayesian Linear Regression
* Bug description:
As far as I know, the prior probability for inclusion should be computed as "number of models that include the term divided by total number of models". This definition "works" for Bayesian ANOVA (with and without interaction effects) and for Bayesian Linear Regression without interaction effects. However, if you introduce an interaction effect into the regression, JASP gives out values that are slightly different (e.g., P(incl)=0.489 if the predictor appears in 50% of the models). I looked at the code, and I can see where this comes from: BAS doesn't exclude inadmissible models by default (i.e., models with interaction effects but without main effects), so JASP reduces the BAS models to admissible models and calculates the prior probability of inclusion from the sum of prior model probabilities divided by the total prior model probability of all admissible models. Basically: `P(incl) = basModel$priorprobs[whichAdmissible] / sum(basModel$priorprobs[whichAdmissible])`, instead of `P(incl) = length(modelsWithPredictor) / length(admissibleModels)`. 

However, this is numerically not the same as identifying the proportion of models including the effect among the admissible models. To me, this looks like a bug, but maybe it's a feature and I just don't get it?

I attached a JASP file with an example.

[E4_Regression.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/6191412/E4_Regression.jasp.zip)

**Comment by astefan1** [comment]
Aaah, sorry, I just realized, this is actually a result of choosing model priors of beta binomial (1,1) instead of uniform! So it *is* a feature, not a bug ;-) The only thing I'm wondering is whether it would maybe make sense to change the default to uniform to achieve consistency across analyses?

**Comment by EJWagenmakers** [comment]
I thought we already changed the default to uniform?!

**Comment by astefan1** [comment]
Hmmm... As far as I know I'm running the latest version, and there the default is the beta binomial

<img width="295" alt="image" src="https://user-images.githubusercontent.com/32095181/112200476-8fce6b80-8c0f-11eb-8c0a-8cb7e4e82817.png">

**Comment by EJWagenmakers** [comment]
It should be the uniform. The other option is just too confusing, also for teaching.

**Comment by AlexanderLyNL** [comment]
It is indeed more complex, but it's recommended so it has type I error control due to multiplicity. I think that a table showing the prior model probabilities would provide some insights to what this prior does.

**Comment by vandenman** [comment]
> The only thing I'm wondering is whether it would maybe make sense to change the default to uniform to achieve consistency across analyses?

Actually, the Beta-Binomial is probably a better default and we should also implement it for the other analyses. It's on my to-do list.

> It should be the uniform. The other option is just too confusing, also for teaching.

Well, we discussed this before and that's why there is https://github.com/jasp-stats/INTERNAL-jasp/issues/528. With this (and similar issues) the question is a bit, do we want the defaults of JASP to reflect good statistical recommendations, or whatever makes teaching easiest? https://github.com/jasp-stats/INTERNAL-jasp/issues/528 tries to achieve the best of both worlds by making the defaults adjustable.

**Comment by vandenman** [comment]
> I think that a table showing the prior model probabilities would provide some insights to what this prior does.

@AlexanderLyNL I think the tables show this already. If you have an idea on how to make this more insightful, I'm all ears!

![image](https://user-images.githubusercontent.com/21319932/112211168-dc1fa880-8c1b-11eb-8dc0-f0af4622e6d1.png)

**Comment by AlexanderLyNL** [comment]
I thought that this Don van den Bergh guy already published this in one of his papers, but I can't remember which one. We can add an example in the help file with 3 variables, which would be a non-trivial example for the beta-binomial(1,1) prior model probabilities. 

- The first three covariates are either "on" indicated by 1 or "off" indicated by 0
- Num refers to the number of active covariates
- Prior model prob provides the prior model probability to that exact configuration.

                x1  x2 x3 Num Prior model prob
                0   0  0      0      1/4 
                1   0  0       1      1/12
                0   1  0       1      1/12
                0   0  1       1      1/12
                1   1  0       2      1/12
                1   0  1       2      1/12
                0   1  1       2      1/12
                1   1   1       3      1/4
  
- If you sum the prior model probabilities vertically you get P(incl X_{j}) = 1/2 for j=1,2,3
- The number of variables to be included are 0, 1, 2, 3 so 1/4 for each. There is one configuration to include 0 covariates, three configurations to include 1 covariate, three configurations to include 2 covariates, and one configuration to include 3 covariates. 
- Add some brackets on the right hand side to show this. 
- For posterior inclusion probabilities you change the column Prior model prob by the posterior model probabilities.

**Comment by astefan1** [comment]
Hey, thanks for looking into this. I didn't mean to bring up old discussions, so whatever you guys decide is fine for me. I did run into this when preparing teaching materials, so I guess that's additional evidence that uniform is more intuitive for teaching.

**Comment by astefan1** [comment]
@AlexanderLyNL Great explanation, thank you! :-) Do you happen to know the paper that explains why this is better for error control?

**Comment by AlexanderLyNL** [comment]
The reference for this is Scott, JG, Berger, JO (2006). An exploration of aspects of Bayesian multiple testing and perhaps https://psyarxiv.com/s56mk/

**Comment by astefan1** [comment]
Thanks a lot!

**Comment by AlexanderLyNL** [comment]
Also https://psyarxiv.com/pqju6/

**Comment by EJWagenmakers** [comment]
imo people will be forever confused with the beta-binomial default. At some point I will be long dead and you will still be fielding the same question. That will then be my revenge :-)

**Comment by JoKeyser** [comment]
Maybe these alternative perspectives could also be distilled into a (few) sentence(s) in the help text?
