### ISSUE TITLE
CI error bars on rm-ANOVA much too small - can the Morey's correction be optional?

### ISSUE THREAD

**Issue by teapot81** [jasp-stats/jasp-issues#1227]
Here is my descriptive plot for my repeated measures ANOVA in JASP: https://imgur.com/a/Li7B9NA I have selected 95% confidence interval.

The last two categories have a mean within 0.01 of each other and a standard deviation within 0.003. I expect the error bars to be very similar.

Here is the same data with 95% CI error bars in SPSS: https://imgur.com/a/ck2oxyK You will see they are huge in comparison, and almost equal size. When I manually calculate these error bars, using mean +/- 1.96*(s.d. / square root of the n number) my error bars match the size on SPSS. Crucially I think the error bars for the last two conditions should be of similar size.

I noted this from the 'i' button "The variances of the resulting normalized values in each condition, and thus the size of the bars, no longer depend on the participant effects and are therefore a more accurate representation of the experimental manipulation. See Morey (2008) for a thorough discussion of this procedure."

I then had a look at the Morey correction based on this person's problem: https://github.com/jasp-stats/jasp-issues/issues/601 

I'm sure you can tell I'm not a stats expert but I'm worried I'm introducing statistical bias in using these tiny and shrinking error bars, especially since all the papers in my field use SPSS and I have never come across this correction before.

Can Morey's correction to the CI error bars be made optional?

Can someone persuade me that it's not wrong to shrink my error bars like this? 

The last one looks especially tiny and makes it look as though there's some sort of learning effect, or everyone has suddenly got accurate at this task.

I really really like JASP so would prefer to use it over SPSS.

My data:

Condition 1	Condition 2	Condition 3
0.466	0.415	0.422
0.441	0.444	0.418
0.671	0.462	0.509
0.623	0.536	0.543
0.374	0.348	0.364
0.49	0.518	0.471
0.492	0.453	0.458
0.499	(missing value sorry)	0.467
0.388	0.46	0.404
0.639	0.627	0.621
0.545	0.541	0.487

**Comment by tomtomme** [comment]
This feature request to make moreys correction optional / selectable to the user is still valid with jasp 0.18.3

**Comment by tomtomme** [comment]
Also now in development for t-Tests: https://github.com/jasp-stats/jaspTTests/pull/239
:)
