### ISSUE TITLE
Nominal variables not getting added up as independent variables in Linear Regression module

### ISSUE THREAD

**Issue by Mgupta741225** [jasp-stats/jasp-issues#1228]
* JASP version:

* OS name and version:
* Analysis: 
* Bug description:
* Expected behaviour:

**Comment by boutinb** [comment]
Hi @Mgupta741225 This will be possible in the next release. For the time being, if your variable contains only numbers, you can change the type of your nominal variable into a scale variable by clicking on the type icon of the variable.
