### ISSUE TITLE
blurred JASP graph outputs

### ISSUE THREAD

**Issue by renuchahal** [jasp-stats/jasp-issues#1229]
* JASP version: 0.14.1

* OS name and version: MacOS Catalina

* Bug description: everytime i generate any descriptive plots or graphs they are blurred, i tried everything from updating the software, selecting safe graphics mode, closing and reopening and resizing. but nothing seems to work 

<img width="1440" alt="Screenshot 2021-03-30 at 14 39 26" src="https://user-images.githubusercontent.com/81633718/113004457-8727e900-916b-11eb-83ae-19dc8719118a.png">
<img width="1440" alt="Screenshot 2021-03-30 at 14 39 04" src="https://user-images.githubusercontent.com/81633718/113004467-88f1ac80-916b-11eb-912e-05c8575b6a30.png">

**Comment by vandenman** [comment]
If you increase the pixels per inch in the settings:
![image](https://user-images.githubusercontent.com/21319932/113106983-a7a38200-9203-11eb-8e84-a8b157f47adf.png)

does that solve the issue?

**Comment by boutinb** [comment]
I close this issue since there is no answer. If this problem still occur, please reopen this issue.
