### ISSUE TITLE
Can't Open JASP

### ISSUE THREAD

**Issue by ethorman** [jasp-stats/jasp-issues#1230]
* JASP version: 0.14.1

* OS name and version: Windows 64 Bit
* Analysis: 
* Bug description: Each time I try to open JASP up from my computer, it takes me to the setup wizard and gives me the option to repair/change/uninstall. How do I rectify this situation so that I am actually able to open the program.
* Expected behaviour: I would like it to just open, I know how to go from there

**Comment by boutinb** [comment]
Hi @ethorman How do you try to start JASP? Apparently you are starting the msi file (the installer). After installing JASP on your machine, you should have in C:\Program Files a JASP folder, where you can find the JASP.exe. Can you double-click this JASP.exe?

**Comment by boutinb** [comment]
I close this issue since I don't get an answer. If you have still this problem, reopen this issue.

**Comment by wawieansaya** [comment]
I'm having a problem with that too. I cannot open it on my computer and always shows the option "repair/change/uninstall." Did you guys already fix the issue? If then, can you help me with how did you guys repair it? Thank you

**Comment by boutinb** [comment]
Hi @wawieansaya This issue was closed bacause I had no answer to my questions:
How do you try to start JASP? Apparently you are starting the msi file (the installer). After installing JASP on your machine, you should have in C:\Program Files a JASP folder, where you can find the JASP.exe. Can you double-click this JASP.exe?

**Comment by wawieansaya** [comment]
Thank you for contacting me, I appreciate it a lot. I just started
installing it yesterday from this link https://jasp-stats.org/download/.
Then it always shows "change, repair, or remove installation" I tried to
click all of it but I can't still use the JASP. I don't think I have a JASP
folder.
[image: image.png]
[image: image.png]

**Comment by boutinb** [comment]
Hi @wawieansaya I saw you also mentioned your problem in issue #1298 and @JorisGoosen made an answer that seems to solve the problem. Can you try it?
