### ISSUE TITLE
"Copy" table option creates unaligned columns

### ISSUE THREAD

**Issue by felixchenier** [jasp-stats/jasp-issues#1232]
* JASP version: 0.14.1

* OS name and version: macOS Catalina

* Bug description: "Copy" table option creates unaligned columns

"Copy" option from table :
![Screen Shot 2021-03-31 at 13 51 00](https://user-images.githubusercontent.com/34967663/113188515-227e9400-9228-11eb-871a-df521a67dfc3.png)

generates these unaligned columns when pasting in Excel :

![Screen Shot 2021-03-31 at 13 52 11](https://user-images.githubusercontent.com/34967663/113188648-4e017e80-9228-11eb-9f8b-86eddd4083d2.png)

* Expected behaviour:

Data should be aligned that way :

![Screen Shot 2021-03-31 at 13 53 14](https://user-images.githubusercontent.com/34967663/113188770-77baa580-9228-11eb-83d8-3b6aaf3ae3fc.png)

#### Steps to reproduce:
1. Generate an analysis
2. Click on the table's down-arrow and Copy
3. Paste into Excel

**Comment by shun2wang** [comment]
This is because we leave a empty column to add some footnote if available, and here will be a index such "a" or "*". source like:

```
<html>
	<head>
		
		<title>JASP</title>		<style>			p {margin-top:1em; margin-bottom:1em;}		</style>	</head>
	<body style='display: block; padding: 0px; margin: 0px; '>
<div class="jasp-display-item jasp-collection-table jasp-table jasp-view jasp-indent jasp-collection-item jasp-collection-table" style='padding: 0px 7.2px 0px 0px; text-align: start; margin-bottom: 7.2px; margin-top: 1.2px; margin-left: 0px; margin-right: 7.2px; display: block; float: none; position: static; ' >
<div style="display:inline-block; ">
<div class="jasp-table-primitive jasp-display-primitive" >
Within Subjects Effects
--

Animal |   | None |   | 83.125 | ᵃ | 3.000 | ᵃ | 27.708 | ᵃ | 3.794 | ᵃ | 0.026 | ᵃ
  |   | Greenhouse-Geisser |   | 83.125 |   | 1.599 |   | 52.001 |   | 3.794 |   | 0.063 |  
  |   | Huynh-Feldt |   | 83.125 |   | 1.997 |   | 41.619 |   | 3.794 |   | 0.048 |  
Residuals |   | None |   | 153.375 |   | 21.000 |   | 7.304 |   |   |   |   |  
  |   | Greenhouse-Geisser |   | 153.375 |   | 11.190 |   | 13.707 |   |   |   |   |  
  |   | Huynh-Feldt |   | 153.375 |   | 13.981 |   | 10.970 |   |   |   |   |  
 
Note.  Type III Sum of Squares
ᵃ Mauchly's test of sphericity indicates that the assumption of sphericity is violated (p < .05).


</div>
</div></div>	</body>
</html><!--EndFragment-->
```

Should we combine this index with number? I am not really sure.

**Comment by felixchenier** [comment]
@shun2wang 

I now understand this extra column and it makes total sense to me. I would let it that way, so that we ensure that number columns are always pure numbers. In this case, additional columns should be simply added in the heading so that the heading matches with the values?

**Comment by shun2wang** [comment]
Yeah, that's unexpected I will fix it.

**Comment by tomtomme** [comment]
@felixchenier 
This is fixed for me with jasp 0.18.3, when copy pasting to Excel 365 in a browser window at least.
Can you test with your excel version to confirm

**Comment by felixchenier** [comment]
@tomtomme 
No, on Mac it's not fixed. Here are screenshots:
![image](https://github.com/jasp-stats/jasp-issues/assets/34967663/be3ca404-c9e6-4506-a70b-f0e156948578)

![image](https://github.com/jasp-stats/jasp-issues/assets/34967663/9ac3627f-ae82-4b92-bf5c-3aeb00ce2201)

![image](https://github.com/jasp-stats/jasp-issues/assets/34967663/6595f913-f83b-4db7-b43e-d6c135ad186e)

![image](https://github.com/jasp-stats/jasp-issues/assets/34967663/974ffe3e-c4ba-42e1-b23d-a1472d7d8d73)

![image](https://github.com/jasp-stats/jasp-issues/assets/34967663/6cd740fd-c663-4735-9141-331bd2fa9190)

Columns names are still unaligned. It's the same if I copy the whole result pane. It pastes well into Excel, but the columns are still unaligned.

**Comment by tomtomme** [comment]
How strange! It seems that on MacOS it does not copy the html format but only plain text. Because on my linux machine copying into Office in a Browser looks like this:

![image](https://github.com/jasp-stats/jasp-issues/assets/4428185/64a875a4-caef-4441-a339-939da33a99cd)

So can you try "paste special" and see if there is an option that gets you to a result that looks more like mine?

**Comment by felixchenier** [comment]
@tomtomme Weird, I updated Excel and now it works flawlessly. Thanks!

**Comment by tomtomme** [comment]
@felixchenier 
Yeah, Excel is updated all the time! Happy you could solve it!
