### ISSUE TITLE
negative sign missing in simple linear regression

### ISSUE THREAD

**Issue by psychdata** [jasp-stats/jasp-issues#1233]
* JASP version: 0.14.1.0

* OS: Windows 10

* Analysis: (Simple) Linear Regression

* Bug description:  If X and Y are negatively correlated, then the negative sign in (simple) linear regression does not come for Y on X (the bug). I rechecked the same data I am using on RStudio, because this was extremely weird (negative correlation, but positive in a simple linear model) However, on R, the negative sign was rightly there for the linear regression. This could exist for models with more than one predictor as well, but the mistake is most easily detectable in a simple linear model.

**Comment by vandenman** [comment]
Could you provide the data you used to see this behavior? 

I can't replicate this in JASP 0.14.3 on Ubuntu:
``` r
set.seed(123)
n <- 100
sigma <- matrix(c(1, -.5, -.5, 1), 2, 2)

xy <- mvtnorm::rmvnorm(n, rep(0, ncol(sigma)), sigma)
dat <- as.data.frame(xy)
colnames(dat) <- c("x", "y")

print(cor(dat), 20)
#>                         x                       y
#> x  1.00000000000000000000 -0.61811018546781681948
#> y -0.61811018546781681948  1.00000000000000000000
fit <- lm(y ~ x, data = dat)
print(coef(fit), digits = 10)
#>   (Intercept)             x 
#> -0.0159678043 -0.6668367234
```
![image](https://user-images.githubusercontent.com/21319932/113256648-c2d8c500-92c9-11eb-987c-4c788a17e8b2.png)

**Comment by Kucharssim** [comment]
Could this be duplicate of https://github.com/jasp-stats/jasp-issues/issues/489?

**Comment by psychdata** [comment]
@vandenman apologies, I cannot share the dataset with you. I rechecked it now, and it seems to flip sign depending on the presence and absence of the intercept. As I understand, this should not be taking place in at least a simple linear model?

**Comment by vandenman** [comment]
> it seems to flip sign depending on the presence and absence of the intercept.

The absence of an intercept is something that should be highly motivated. Without an intercept, all sorts of paradoxical results can happen. That's also why it's the default in R and JASP to include an intercept.

**Comment by psychdata** [comment]
@vandenman , makes sense, thank you! 

If possible, if you have some academic material on this matter of removing the intercept for analysis and it consequent interpretation, please do share. Thanks!

**Comment by juliuspf** [comment]
@psychdata do you view this issue as solved then?
