### ISSUE TITLE
JASP plugin interface for stochastic volatility models [`stochvol`]

### ISSUE THREAD

**Issue by hdarjus** [jasp-stats/jasp-issues#1234]
* Enhancement: Introduce stochastic volatility models
* Purpose: more models
* Use-case: financial and economic uses

**Describe the solution you'd like**
I would be happy to make the capabilities of [`stochvol`](https://cran.r-project.org/package=stochvol) available to the users of JASP.
I don't find any resources on how to write a plugin, please help me out.

**Additional context**
I am the maintainer of `stochvol`.

Thank you.

**Comment by AlexanderLyNL** [comment]
Hi Darjus,

Thanks for reaching out! Here are some resources:
- https://www.youtube.com/watch?v=cw7v8YxCV8o&feature=youtu.be
- https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/development/jasp-adding-module.md

But we can also set up a zoom call to discuss this further if you prefer that? Would that interest you? One of our specialist is @vandenman who might have more to add. 

Cheers,
Alexander

**Comment by hdarjus** [comment]
Hi Alexander,

Thank you for your quick reply. I will take a look at the resources first and then get back to you if I need help. The description you wrote up looks really promising and exhaustive.

I just heard about JASP in the [newest ISBA Bulletin](https://bayesian.org/wp-content/uploads/2021/03/2103.pdf) and I find it really cool. Thanks for the nice contribution to science from my side.

Cheers,
Darjus

**Comment by EJWagenmakers** [comment]
We are about to turn to time series analysis anyway, so this would be very welcome!

**Comment by EJWagenmakers** [comment]
Also, as Alexander said, do not hesitate to contact us for help (especially when you are trying to get going)
