### ISSUE TITLE
Velicer MAP Test

### ISSUE THREAD

**Issue by lucieunice** [jasp-stats/jasp-issues#1235]
* Enhancement: Add Velicer MAP Test feature
* Purpose: Exploratory Factor Analysis

Hi! Is there any way of doing a Velicer MAP Test for Exploratory Factor Analysis in JASP? It is recommended in addition to parallel analysis and the eigenvalues method, and could be useful as an added feature! 

Thanks :)

**Comment by tomtomme** [comment]
Closing, since duplicate of the more active: https://github.com/jasp-stats/jasp-issues/issues/1951
