### ISSUE TITLE
Bayesian meta-analysis figure legends might be wrong(?)

### ISSUE THREAD

**Issue by ilias-nikolakopoulos** [jasp-stats/jasp-issues#1236]
* JASP version: 0.14.1

* OS name and version: Windows 10
* Analysis: Bayesian meta-analysis
* Bug description: Prior and Posteriors effect size plot mentions the solid line as 
"random H0".  (first image)
* Expected behaviour: According to the instructions, it should be mentioned as "random H1" (image 2).
* 
![image](https://user-images.githubusercontent.com/67070810/113352804-65149f00-9302-11eb-9f8c-2d83e1cacdb4.png)
![image](https://user-images.githubusercontent.com/67070810/113353077-c50b4580-9302-11eb-9a47-21b01c723061.png)

**Comment by sophieberkhout** [comment]
Hi Ilias,

You are right, it should be Random H<sub>1</sub>. I will fix this.

Best,
Sophie

**Comment by ilias-nikolakopoulos** [comment]
Thank you Sophie, and thanks for the wonderful software!!

All the best,
Ilias
