### ISSUE TITLE
there is no package called 'ragg'

### ISSUE THREAD

**Issue by minoskritikos** [jasp-stats/jasp-issues#1239]
For a number of analyses, I get the error message "there is no package called 'ragg'" where a graph should be generated. I'm using a Mac and the latest version of JASP.

Please let me know if you require further info.

Thanks
<img width="1080" alt="Screen Shot 2021-04-06 at 12 29 27" src="https://user-images.githubusercontent.com/82049726/113746066-e8a00880-96d3-11eb-94e9-4bcea52a22d0.png">

**Comment by boutinb** [comment]
Hi @minoskritikos Can you specify which OS (Windows, Mac, Linux) en which version of the OS you use. And which JASP version you use?

**Comment by minoskritikos** [comment]
Yes of course. 

Mac OS Big Sur 14.2.3 - JASP 0.15 build Apr 2 2021 18:01:10

I've noticed this problem with a number of recent builds, both on my MacBook Pro 16 Intel and MacBook Air M1 running 14.2.3

Please let me know if you require further info.

Thanks

**Comment by minoskritikos** [comment]
I should add that if I reinstall the stable release 0.14, I don't have this issue.

**Comment by boutinb** [comment]
Hi @minoskritikos The nightly builds are highly unstable! You should use them only if you are looking for a special fix on an issue that is not yet solved in the official release.
This problem has also been seen by a colleague of mine, and should be solved soon.

**Comment by minoskritikos** [comment]
Understood! I tried a nightly build and loved the raincloud plots, so I stuck with it. Good to know it will be solved soon.

Thanks

**Comment by boutinb** [comment]
If you load an older Nightly build, then it should work.
