### ISSUE TITLE
JASP does not report Posterior Parameter Distribution of Intercept in a fitted linear regression model

### ISSUE THREAD

**Issue by mspezio** [jasp-stats/jasp-issues#1240]
* JASP version: 0.14.1

* OS name and version: Mac 10.15.7
* Analysis: Bayesian Linear Regression
* Bug description: No display of Posterior Parameter Distribution of Intercept for the Fitted Model
* Expected behaviour: Need a display of Posterior Parameter Distribution of Intercept for the Fitted Model

Data file is attached, along with the figures. Also, the correctly estimated Posterior Parameter Distribution for the fitted model is attached.

In order to use JASP to teach Introductory Statistics using Bayesian approaches, JASP needs to return the correct Posterior Parameter Distributions for the fitted models, along with the specified designated credible intervals. Otherwise there will be confusion as to why the Classical and Bayesian values are so different. In this case, the "marginal" posterior distribution of the Intercept, assuming that the predictor variable is not included, is correctly estimated and shown. But there is no display of the posterior distribution of the Intercept when it is obtained from the model that includes the predictor variable.

All posterior parameter distributions need to be accessible and displayed in JASP Bayesian linear regression.

![Screen Shot 2021-04-06 at 5 34 20 PM](https://user-images.githubusercontent.com/26719547/113793992-6547dc80-96fe-11eb-9b1c-e05cbb5aa646.png)
![Screen Shot 2021-04-06 at 5 32 59 PM](https://user-images.githubusercontent.com/26719547/113793995-66790980-96fe-11eb-8b89-35a78b6438a5.png)
[parenthood.csv.zip](https://github.com/jasp-stats/jasp-issues/files/6268166/parenthood.csv.zip)
![Screen Shot 2021-04-06 at 5 36 03 PM](https://user-images.githubusercontent.com/26719547/113794074-97f1d500-96fe-11eb-9c21-07ebc6a08553.png)
![Screen Shot 2021-04-06 at 5 35 55 PM](https://user-images.githubusercontent.com/26719547/113794080-99230200-96fe-11eb-9d5a-dba6d0988ebf.png)

**Comment by boutinb** [comment]
@TimKDJ Can you have a look to this issue?

**Comment by vandenman** [comment]
> Otherwise there will be confusion as to why the Classical and Bayesian values are so different. In this case, the "marginal" posterior distribution of the Intercept, assuming that the predictor variable is not included, is correctly estimated and shown. But there is no display of the posterior distribution of the Intercept when it is obtained from the model that includes the predictor variable.

The reason why the results may differ a lot is that the Bayesian linear regression shows model-averaged posterior distributions.

> In this case, the "marginal" posterior distribution of the Intercept, assuming that the predictor variable is not included, is correctly estimated and shown. But there is no display of the posterior distribution of the Intercept when it is obtained from the model that includes the predictor variable.

So we take the posterior for the intercept of the model that includes the predictor and the posterior for the intercept of the model that excludes the predictor. Next, we average these distributions weighted by the posterior probability of the respective models. 

Plots of posterior distributions for individual models are not possible at the moment. If that is what you would like to see, we can probably add something like this (copied from the Bayesian ANOVAs):

![image](https://user-images.githubusercontent.com/21319932/114386175-2a77f580-9b91-11eb-80a4-d6a6ea044e15.png)

where you can use the terms under `Components` (all non-nuisance variables considered) to do inference for a single model. Would that help?

**Comment by CGMoreh** [comment]
I may have misunderstood the original question, but I've just realised that I have a similar/relatable question if posed not as a plotting issue but as a coefficient-summary one. The coefficients table from a classical and a Bayesian regression seem to differ in that the posterior summary of the intercept coefficient is not included in the results table. In the case of a classical regression output, both the M__ and M_1 intercepts are shown, separately (which is great). But in the posterior summary of a Bayesian regression, only the M_0 Intercept coefficient is shown. This may be confusing for comparative pedagogical purposes (unless I'm completely wrong at interpreting something...). The screenshot below - comparing outputs from two parallel classical/Bayesian models - hopefully highlights what I mean. I have a feeling that the original poster had something similar in mind, maybe?

![image](https://github.com/user-attachments/assets/2c16dff4-ddc5-49f6-b16d-94c9c080d4a7)

**Comment by CGMoreh** [comment]
Thank you for the prompt clarification!
