### ISSUE TITLE
RM ANOVA post-hoc correction behaviour

### ISSUE THREAD

**Issue by felixthcho** [jasp-stats/jasp-issues#1241]
* JASP version: 0.14.1.0

* OS name and version: Windows 10 Home (18363.1440)
* Analysis: ANOVA (Repeated Measure ANOVA)
* Bug description: Post-hoc Scheffe adjusted p-value larger than that of Bonferroni/Holm adjusted when small (e.g. <0.5), but smaller when large (e.g. >0.5)
* Expected behaviour: Post-hoc Scheffe adjusted p-value consistently be the largest.

I am not entirely sure if this is a bug but would very much like to get help.

I was performing a three-way repeated measure ANOVA with 2 within-subject factors and 1 between-subject factors, with a significant 3-way interaction effect. A post-hoc pairwise comparison is thus conducted, but the relationship of p-value by different adjustment seems to be inconsistent. Base on my limited knowledge in statistics, Scheffe adjustment shall be the most conservative, and it would therefore be expected that the p-value shall be highest all along. However, when Bonferroni/Holm adjusted p-value is greater than .5, the Scheffe adjusted p-value appears to be smaller. I wonder if that is an expected behavior?

![image](https://user-images.githubusercontent.com/45197434/113812354-895bfa00-97a0-11eb-91f0-1f56f9d76554.png)

Thanks in advance.

**Comment by tomtomme** [comment]
@felixthcho 
As far as I know how  those corrections work, those values seem to be correct. Have you checked out the actual formulas?
