### ISSUE TITLE
Lavaan in JASP not notifying when SEM solution is inadmissible (nonpositive definite covariance matrix)

### ISSUE THREAD

**Issue by mjkofler** [jasp-stats/jasp-issues#1243]
* JASP version: 0.14.1

* OS name and version: Mac Big Sur 11.1 + Windows version (same issue across platforms)
* Analysis: SEM (lavaan)
* Bug description: When solution is inadmissible (e.g., due to a nonpositive definite covariance matrix), JASP provides output as normal with no indication that the results are bad. Running same code in lavaan in R, and in MPLUS, both give the expected nonpositive definite covariance matrix warning. JASP version does not.
* Expected behaviour: Showing lavaan warning message that the covariance matrix is nonpositive definite. Without this, we would have proceeded with interpretation and published invalid results!

#### Steps to reproduce:
1. Go to '...' SEM menu > SEM
2. Click on '....' SEM
3. Scroll down to '....' Enter your lavaan code and run it
4. See error: In this case, we do not see the necessary error message

**Comment by juliuspf** [comment]
This is very much related to our discussion about displaying warnings from R to the user: https://github.com/jasp-stats/INTERNAL-jasp/issues/2138

**Comment by tomtomme** [comment]
@mjkofler 
I recently saw such a warning, so I guess this was fixed. Could you re-test with jasp 0.18.3?
