### ISSUE TITLE
Error Bayesian GLMM interaction term

### ISSUE THREAD

**Issue by Wouterwolf** [jasp-stats/jasp-issues#1245]
* JASP version: .14.1
* OS name and version: Windows 10
* Analysis: Bayesian GLMM
* Bug description: Error message when trying to compute Bayesian Gamma distribution GLMM (log link) with an interaction term of a continuous fixed factor (cue number) and a categorical fixed factor (age group) with a continuous DV (Latency)
* Expected behaviour: The model computing :)

#### Steps to reproduce:
1. Go to mixed models --> Bayesian GLMM --> Gamma Family --> Link = log
2. Put variable 'Latency' in the dependent variable box, 'CueNum' and 'Age' in the fixed effects variables box, and 'ParticipantID' in the Random effects grouping factors box
3. In the model components section, select CueNum, Age, and CueNum*Age as fixed effects
4. Run the model
5. The following error appears:

Error in if (nrow(temp_summary) = 1) {: argument is of length zero

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.mmRunAnalysis(jaspResults, dataset, options, 'BGLMM')

.mmSummaryStanova(jaspResults, dataset, options, type)

The datafile is too big to send over github, but I'd be happy to send it somewhere :)

**Comment by FBartos** [comment]
Hi @Wouterwolf ,

I'm sorry for not responding earlier. I have recently implemented fixes that should address this type of error. Could you please send me the .jasp file to f.bartos96@gmail.com so I can verify that the issue is indeed fixed?

Best,
Frantisek

**Comment by FBartos** [comment]
I verified that the issue was resolved.

**Comment by Wouterwolf** [comment]
Great, thanks.
Does this mean I have to update JASP?

Best,

Wouter Wolf PhD
Assistant Professor
Department of Developmental Psychology
Utrecht University
Wouter Wolf PhD - Sociale Wetenschappen - Universiteit Utrecht (uu.nl)
<https://www.uu.nl/medewerkers/WWolf>
www.wouterwolf.com

**Comment by FBartos** [comment]
The fixes will be part of the upcoming release or you can test them out in a Nightly (http://static.jasp-stats.org/Nightlies/). 

Thanks again for the help,
Frantisek

**Comment by Wouterwolf** [comment]
Yep, sorry, I saw the other email just now :)

Thanks!

Wouter Wolf PhD
Assistant Professor
Department of Developmental Psychology
Utrecht University
Wouter Wolf PhD - Sociale Wetenschappen - Universiteit Utrecht (uu.nl)
<https://www.uu.nl/medewerkers/WWolf>
www.wouterwolf.com
