### ISSUE TITLE
ANOVA reports variance in dependent variable is equal to 0 after grouping on independent variables

### ISSUE THREAD

**Issue by Photeinos-Santas** [jasp-stats/jasp-issues#1247]
* JASP version: 0.14

* OS name and version: MacOS 11.2.3, MacBook Pro, Retina 15-inch, 2.5 GHz Intel Core i7, 16 GB 1600 MHz DDR3, NVIDIA GeForce GT 750 2 GB, Intel Iris Pro 1536 MB
* Analysis:  A dataset from a 2x8 factorial design (2 metals each at 8 concentrations) with 4 replicates per metal x concentration combination for a total of 64 observations and 3 dependent variables per observation was inserted to JASP as a .csv file for Analysis of Variance, as described below in the 'Steps to reproduce' section. 
* Bug description:  JASP responded with the error displayed in the screenshot attached below.
* Expected behaviour: A full ANOVA table was expected. The same dataset was inserted and analyzed successfully in other statistical analysis software, e.g. Statgraphics, PSPP. Therefore, this is not an error in the data, but rather in the way JASP handles the analysis request.

#### Steps to reproduce:
1. Go to 'ANOVA'
2. Click on '(Classical) ANOVA'
3. Insert 'Me' and 'init_Me_conc' in the "Fixed Factors" field
4. Insert 'pct_Me_removal' or 'uptake_q' or 'arcsin_sqrt_decimal_Me_removal' in the "Dependent Variable" field
5. See error screenshot below

<img width="581" alt="Screen Shot 2021-04-08 at 1 22 52 PM" src="https://user-images.githubusercontent.com/58490816/114149587-bedd2080-9923-11eb-8619-718ef0817cd8.png">

[CSV and JASP file.zip](https://github.com/jasp-stats/jasp-issues/files/6284371/CSV.and.JASP.file.zip)

**Comment by JohnnyDoorn** [comment]
Hi @Photeinos-Santas,

As the error states, apparently there are cells of the interaction effect where the variance is 0 (e.g., all values are the same). Removing the interaction effect from your model (testing only the two main effects) does not give this error. I also see you have a limited sample size per cell, which might contribute to the problem.

Kind regards
Johnny

**Comment by Photeinos-Santas** [comment]
Hi Johnny,
Thanks for your suggestions.
I will check them and let you know.
Best,
Photeinos

**Comment by Photeinos-Santas** [comment]
Hi Johnny,
Your suggestion of removing the interaction term from the model and keeping the main effects only was not an option, because the interactions provide useful information. 
Here is my workaround to the issue:
1. Add to one and subtract from another one of the interaction four identical replicate values the same small amount (e.g. 0.01). Adding and subtracting the same amount cancels out and leaves the average of the four values unchanged before and after the tweaking. The variance of the four values, however, is slightly increased, perhaps at the fourth decimal place, and not zero anymore. 
2. The tweaked dataset was introduced and analyzed in JASP, and the corresponding ANOVA table was constructed with no error messages. 

I have run identical ANOVA models on the same tweaked and untweaked datasets on Jamovi and PSPP, and there was no zero variance error in either dataset or package.

Obviously, the question is why these other packages don't give the same error in the first place, i.e. without tweaking? 
Could it be something in the way JASP is handling the data or doing the calculations, or something else?
I have attached the relevant .zip files with the input and output for each package in case you or someone else might want to follow up on the issue.

Best regards,
Photeinos

[data & output.zip](https://github.com/jasp-stats/jasp-issues/files/6337993/data.output.zip)

**Comment by tomtomme** [comment]
@Photeinos-Santas 
Tested with jasp 0.18.3. This seems fixed.
Feel free to reopen, if not fixed on your side
