### ISSUE TITLE
Troubles installing Jasp on Mac OS Catalina. It will not let me! Please help urgently!

### ISSUE THREAD

**Issue by luciavitarobinia** [jasp-stats/jasp-issues#1248]
* JASP version: Jasp for Catalina

* OS name and version: Catalina
* Analysis: It download the files and says that it cannot open. I do have XQuartz already installed.
* Bug description:
* Expected behaviour:

**Comment by boutinb** [comment]
Hi @luciavitarobinia Just to be sure:  You have downloaded the Catalina & Big Sur JASP version and you have in your download folder a JASP-0.14.1.0-postMojave.dmg file. If you double-click on it, what is the message error exactly? Can you also right-click on the dmg file, and select the 'Open' menu?

**Comment by keecorby** [comment]
I am having same problem it keeps opening a verifying window and after it says open but the program continues to not open. I have the quartz (maybe mispelled) downloaded as well and I did it before the jasp and it still does not work.

**Comment by boutinb** [comment]
@keecorby Did you try to right-click the JASP icon, and select the Open menu?

**Comment by tomtomme** [comment]
@luciavitarobinia 
Can you retest with current JASP 0.18.3?
I believe these issues are fixed.
