### ISSUE TITLE
RM Anova will not let you delete RM factors

### ISSUE THREAD

**Issue by felipeviegas** [jasp-stats/jasp-issues#1249]
JASP is crashing once you try to delete any repeated measures factor that you assign to your RM ANOVA. I am using the latest version (0.14.1) and it was already going on in version 0.14. I updated it to see if it was solved. Every time I make any mistake while preparing the factors of the RM ANOVA, I have to delete the test and start over. If I try to delete the factor, JASP just crashes. I am on Windows 10 64 bit (compilation 19041.867). 

Thanks!

**Comment by JohnnyDoorn** [comment]
Hi @felipeviegas, 

Can you give a detailed step by step description of how you get the error? Because I cannot reproduce this. 

Kind regards,
Johnny

**Comment by felipeviegas** [comment]
Hi Johnny,

I  do normal steps:

   - open my data file on jasp;
   - ask for a repeated measures anova;
   - start to configure repeated measures factor;

Then, if I make any mistake and I have to erase one of the factors,
clicking on the "x" to delete it, jasp will just close on me.
While I tried to record a video of the error, I realized that it will only
happen if I have not yet assigned any variable to the anova. But if any
variable (of my data) is already assigned to the factor I have created,
jasp will not crash. You can see it in this video (crashing just in the
end): https://www.youtube.com/watch?v=ICBKLqDr9yE

I recorded it while listening to music, just a heads-up... and I use a 4k
monitor, so maybe things will be just too small. I can record it again, if
it helps.

Thanks a lot!
________________________
Felipe Viegas Rodrigues <http://feliperodrigues.ib.usp.br>
Univ. do Oeste Paulista <http://www.unoeste.br/site/default.aspx>
+55 18 99683 8488

*“Music is quality, organized in sound and in time.”*

The information contained in this e-mail, including attachments, can only
be forwarded by explicit mention above.


Em seg., 12 de abr. de 2021 às 11:04, JohnnyDoorn ***@***.***>
escreveu:
