### ISSUE TITLE
Saving output in JASP

### ISSUE THREAD

**Issue by joucoski** [jasp-stats/jasp-issues#125]
I can not save the output in any useful format since the HTML format that is generated is very restrictive. In the output window, by clicking Copy in the drop-down list, you can not paste into Notepad. I copied to LibreOffice Calc (free version of a spreadsheet) but did not copy into a usable format. In the matrix each row shows the name of the variable and then with many spaces up to the value of interest. Then the next line has the variable name and other hundreds of spaces up to the correlation value. Is there no other way to save the output? Or could the version to be copied to LibreOffice Calc  be improved so that these unnecessary spaces do not appear? Thank you!

![captura de tela de 2017-12-06 16-46-04](https://user-images.githubusercontent.com/14141667/33679166-19a611a2-daa5-11e7-8233-f50e51ca13e4.png)

**Comment by JorisGoosen** [comment]
The latest version (at least) supports copying tables as LateX.
