### ISSUE TITLE
Error: object 'xxx' not found.

### ISSUE THREAD

**Issue by PUPU777** [jasp-stats/jasp-issues#1251]
When I use jasp to calculate the data, it just appeared the sentence that I wrote in title. Other people who are using the same data do not meet the same problem that I met. Also, when I tried to calculate and then failed because the object not found, the variable just become an empty set when I click descriptive.
![微信图片_20210414001144](https://user-images.githubusercontent.com/82463924/114585340-1e398880-9cb6-11eb-997c-879169df3ae7.png)
![微信图片_20210414001206](https://user-images.githubusercontent.com/82463924/114585372-2691c380-9cb6-11eb-83ec-ca79ef71a607.png)

**Comment by boutinb** [comment]
Hi @PUPU777 Could you describe step by step precisely what you did? Did you load a data file or a JASP file? Then how did you have create your first Computed column. We need all the details (maybe with screenshot) to understand what has happened.

**Comment by PUPU777** [comment]
Hi @boutinb  I loaded a data file and I have also tried JASP file, both of them met the same problem.

After I opened the file, I changed the type of column titled SDO1 from ordinal to scale.
![image](https://user-images.githubusercontent.com/82463924/114682439-ad3fb280-9d41-11eb-8aef-910c287c3b26.png)
then I created a new column called SDO1_r
![image](https://user-images.githubusercontent.com/82463924/114682611-d52f1600-9d41-11eb-82cf-f9fe568eb19e.png)
when I did the simple subtraction for this new column by using the data from SDO, it just showed like this.
![image](https://user-images.githubusercontent.com/82463924/114682977-2f2fdb80-9d42-11eb-8793-925444ed9bce.png)
and when I clicked the descriptive, it showed that SDO1 became an empty set.
![image](https://user-images.githubusercontent.com/82463924/114683201-6a320f00-9d42-11eb-92a7-d0181d5fae4e.png)
however, when I reopened the same file and clicked the descriptive for SDO1 without doing any calculation, the data just showed up normally which I think the data itself is fine.
![image](https://user-images.githubusercontent.com/82463924/114683680-cdbc3c80-9d42-11eb-84e0-185184d99950.png)

**Comment by boutinb** [comment]
That's quite strange...
Which JASP version do you use, and which OS (with its version)?
Can you also try to make a computed column with another random name (eg. AAA), having for value just the value of an existing variables?

**Comment by PUPU777** [comment]
@boutinb

I am using this version now. But I also tried the latest version 0.14.1, and it just didn't work either.

![image](https://user-images.githubusercontent.com/82463924/114686068-052be880-9d45-11eb-9200-c886fe64059e.png)

I use AAA as the new column's name and use the existing value 'patriot' but it is just the same result

![image](https://user-images.githubusercontent.com/82463924/114686809-b468bf80-9d45-11eb-90a9-186927eec39d.png)

**Comment by boutinb** [comment]
And which OS (with its version) do you use?

**Comment by PUPU777** [comment]
@boutinb

I am using windows 10

**Comment by boutinb** [comment]
Really strange...
Could you set the log (https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/user-guide/logging-howto.md). Then restart JASP, and just load a data file and make a simple Computed column, and after that, send me the log files (Desktop and Engines)?

**Comment by PUPU777** [comment]
@boutinb

After I set the log and restart JASP, the calculation just worked successfully and the problem is fixed automatically. This is really strange. Thank you so much!!!

**Comment by boutinb** [comment]
??? 
And if you set the log off and restart JASP?

**Comment by PUPU777** [comment]
@boutinb 

When I set the log off and restart JASP, it doesn’t work again. Then I set back to log on, it works fine

**Comment by boutinb** [comment]
That is really really strange. Never heard such a behaviour... Even if it works, could send me the log files?

**Comment by PUPU777** [comment]
@boutinb

ok. when I tried to calculate with log on, it failed again. these are log files when I couldn't do calculation

[JASP 2021-04-15 16_25_13 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/6316444/JASP.2021-04-15.16_25_13.Desktop.log)
[JASP 2021-04-15 16_25_13 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/6316445/JASP.2021-04-15.16_25_13.Engine.0.log)
[JASP 2021-04-15 16_25_13 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/6316447/JASP.2021-04-15.16_25_13.Engine.1.log)
[JASP 2021-04-15 16_25_13 Engine 2.log](https://github.com/jasp-stats/jasp-issues/files/6316448/JASP.2021-04-15.16_25_13.Engine.2.log)
[JASP 2021-04-15 16_25_13 Engine 3.log](https://github.com/jasp-stats/jasp-issues/files/6316449/JASP.2021-04-15.16_25_13.Engine.3.log)
[JASP 2021-04-15 16_30_32 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/6316450/JASP.2021-04-15.16_30_32.Desktop.log)
[JASP 2021-04-15 16_30_32 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/6316451/JASP.2021-04-15.16_30_32.Engine.1.log)
[JASP 2021-04-15 16_30_32 Engine 2.log](https://github.com/jasp-stats/jasp-issues/files/6316452/JASP.2021-04-15.16_30_32.Engine.2.log)
[JASP 2021-04-15 16_30_32 Engine 3.log](https://github.com/jasp-stats/jasp-issues/files/6316453/JASP.2021-04-15.16_30_32.Engine.3.log)
[JASP 2021-04-15 16_31_19 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/6316454/JASP.2021-04-15.16_31_19.Desktop.log)
[JASP 2021-04-15 16_31_19 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/6316455/JASP.2021-04-15.16_31_19.Engine.0.log)
[JASP 2021-04-15 16_31_19 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/6316457/JASP.2021-04-15.16_31_19.Engine.1.log)
[JASP 2021-04-15 16_31_19 Engine 2.log](https://github.com/jasp-stats/jasp-issues/files/6316458/JASP.2021-04-15.16_31_19.Engine.2.log)
[JASP 2021-04-15 16_31_19 Engine 3.log](https://github.com/jasp-stats/jasp-issues/files/6316459/JASP.2021-04-15.16_31_19.Engine.3.log)


then I set the log off and delete the whole file folder called Logs. then I set log on again. this time it works. those are the files.

[JASP 2021-04-15 16_41_11 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/6316478/JASP.2021-04-15.16_41_11.Desktop.log)
[JASP 2021-04-15 16_41_11 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/6316480/JASP.2021-04-15.16_41_11.Engine.0.log)
[JASP 2021-04-15 16_41_11 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/6316482/JASP.2021-04-15.16_41_11.Engine.1.log)
[JASP 2021-04-15 16_41_11 Engine 2.log](https://github.com/jasp-stats/jasp-issues/files/6316483/JASP.2021-04-15.16_41_11.Engine.2.log)
[JASP 2021-04-15 16_41_11 Engine 3.log](https://github.com/jasp-stats/jasp-issues/files/6316484/JASP.2021-04-15.16_41_11.Engine.3.log)
[JASP 2021-04-15 16_42_12 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/6316485/JASP.2021-04-15.16_42_12.Desktop.log)
[JASP 2021-04-15 16_42_12 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/6316487/JASP.2021-04-15.16_42_12.Engine.0.log)
[JASP 2021-04-15 16_42_12 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/6316488/JASP.2021-04-15.16_42_12.Engine.1.log)
[JASP 2021-04-15 16_42_12 Engine 2.log](https://github.com/jasp-stats/jasp-issues/files/6316489/JASP.2021-04-15.16_42_12.Engine.2.log)
[JASP 2021-04-15 16_42_12 Engine 3.log](https://github.com/jasp-stats/jasp-issues/files/6316492/JASP.2021-04-15.16_42_12.Engine.3.log)

**Comment by boutinb** [comment]
What I see is that you have a locale set to Chinese. I know that JASP has sometimes some problems with that, especially when R is used. Maybe by setting the log on, this overrules some R settings... We will have to understand this problem.
Fortunately you have now a workaround.
If you have some time, I would be quite interested to know if this version http://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-renv-904d1eaa094b4b52e4f4486293bc665e190d6415.msi works better (it is not an official version, just a new version in development).

**Comment by PUPU777** [comment]
@boutinb

I found out when I turn the log on, it can just calculate once. and for the second calculation, it failed. so I tried to download the version you mentioned. this new version works very well. Thank you so much.

**Comment by boutinb** [comment]
Nice!
