### ISSUE TITLE
JASP unexpected internal error

### ISSUE THREAD

**Issue by GGBEE** [jasp-stats/jasp-issues#1252]
![Screenshot 2021-04-14 at 2 13 37 PM](https://user-images.githubusercontent.com/82495460/114662925-17e5f380-9d2c-11eb-832e-1241732c7bae.png)

* JASP version:

* OS name and version:
* Analysis: 
* Bug description:
* Expected behaviour:

**Comment by boutinb** [comment]
Hi @GGBEE Can you tell which JASP version you use, which OS, etc... Could you also add a precise description of what you did: does this error comes up immediately when you start JASP, or when you load some data, or when you you add an analysis?

**Comment by GGBEE** [comment]
Hi,

the error box came up after i have selected two variables into the 'variables' box for the correlation matrix. I hope this information is helpful.

Thanks.
________________________________

**Comment by boutinb** [comment]
Hi @GGBEE Can you give also which JASP version you use, and which OS (windows, Mac, Linux..) with its version you have? 
Just to be sure: you have loaded a data file, added only the Correlation Matrix analysis, and selected two variables into the 'variables' box?
Could you als set up the log (https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/user-guide/logging-howto.md) and send me the log files?
If possible could you also send us the data you use?
