### ISSUE TITLE
Jasp not synchronizing changes made in .csv in Excel

### ISSUE THREAD

**Issue by petrapovalej** [jasp-stats/jasp-issues#1254]
Hi! Me and some of my students have a problem with synchronization. We save excel file as .csv with UTF8 encoding. When we import the .csv file to JASP and make some changes in Excel as editor for .csv files, the changes are not synchronized in JASP. 
What can we do?

We are using Win10, Office 365 (Excel Version 2103) and JASP 0.14.1

**Comment by boutinb** [comment]
Hi @petrapovalej Just to be sure: if you have some changes in Excel, and then press CTRL-Y (shortcut for synchronization) do the change appear in JASP? 
Also what is your 'Synchronize automatically on data file save' setting in Preferences/Data ?

**Comment by petrapovalej** [comment]
Hi! I find out that for some reason the synchronization option has turne
office. I really don't know how because a few days ago everything was
working.
The same happened to some of my students.
So now it's working.
Regards, Petra

**Comment by boutinb** [comment]
Nice to hear it works now!
