### ISSUE TITLE
Unable to Open File 

### ISSUE THREAD

**Issue by LaraKlacar** [jasp-stats/jasp-issues#1256]
JASP version: 0.14.1
MacOS 
High Sierra
Unable to Open File 
No entry (META-INF/manifest.xml) found in archive file

I am trying to upload an Excel sheet into JASP, but this code keeps popping up. I have made sure the file code is .ods
So should be working. Can someone please help me ASAP

If possible please attach your data and/or JASP file to the issue, this makes solving the bug a lot easier. If you would prefer to not make your data publicly available then you could also mail it to us.
Note that github requires you to zip the file to upload it here.

**Comment by boutinb** [comment]
@LaraKlacar Could you send your ods file? Can you also try to save the Excel file in csv fomat and load with in JASP?
