### ISSUE TITLE
Recoding variables in JASP

### ISSUE THREAD

**Issue by romanogino** [jasp-stats/jasp-issues#1258]
Hello

Just a proposal for an enhancement:
Create an option to recoding variables for descriptive analysis. 

**Describe the solution you'd like**
A new variable in a new column. 

I use a lot of descriptive statistics with my students and recoding is very usual in any situation.

Best regards.

r.

**Comment by JorisGoosen** [comment]
We are working towards some improvements in variables/levels/etc for columns and this is certainly one of the things on the list.

Im linking it to our (private) issue for that: https://github.com/jasp-stats/INTERNAL-jasp/issues/751

**Comment by romanogino** [comment]
Thanks for the information. Best regards.
r.

**Comment by JorisGoosen** [comment]
This can stay open, to remind me in the future.

**Comment by jbnezl** [comment]
Any advice regarding how to change the variable type of variables that are in a SPSS file that has been imported into JASP?
The variables are Scales within the nomenclature of SPSS, but when I open the file in JASP, they are coded as nominal.
The file is clean. There are no text entries in the data fields. I am puzzled by the coding.
I can change type on a variable by variable basis, but this is a bit tedious.

Any advice?

Thanks,
John

**Comment by AlexanderLyNL** [comment]
> Any advice regarding how to change the variable type of variables that are in a SPSS file that has been imported into JASP?
> The variables are Scales within the nomenclature of SPSS, but when I open the file in JASP, they are coded as nominal.
> The file is clean. There are no text entries in the data fields. I am puzzled by the coding.
> I can change type on a variable by variable basis, but this is a bit tedious.
> 
> Any advice?
> 
> Thanks,
> John

I think that your scale variables contain fewer than 10 unique integers (1, 2, 3, etc). As such, JASP by default thinks that these variables are nominals. You can change the cut off of 10 to a lower number in the preference menu, see also

https://jasp-stats.org/wp-content/uploads/2021/04/Threshold.gif

**Comment by jbnezl** [comment]
Dear Alexander,

Thanks for the quick reply.

Unfortunately, this did not make a difference.

By the way, many of the entries are means, and so there are more than 10 unique values.
When the entry for a mean is a single digit (e.g., a mean of 3), the value label from the SPSS file is displayed.

For single digit variables (e.g., items within a scale) the variable is coded as nominal and the value label from the SPSS file is displayed.

John

**Comment by JorisGoosen** [comment]
@AlexanderLyNL the SPSS files are read through a different importer, so the threshold for ordinal vs scalar is not used there.

@jbnezl I think it would be most practical if you make a separate issue for this and attach a datafile there, doesn't necessarily need to be the one you tried out now, as long as it acts as "weird" as you say. If you cannot share your datafile then you [can turn on logging and upload the logs as described here.](https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/user-guide/logging-howto.md). Then I can have an in depth look to your problem.

Thank you.

**Comment by jbnezl** [comment]
Hi Joris,

Thanks for the offer.  I will set up a new thread and upload a data file there, probably tomorrow.

John

**Comment by tomtomme** [comment]
Closing as duplicate, since this is now tracked here: https://github.com/jasp-stats/jasp-issues/issues/2325
