### ISSUE TITLE
Add set.seed option?

### ISSUE THREAD

**Issue by quentingronau** [jasp-stats/jasp-issues#126]
One of the participants of our JASP workshop suggested to add a "set.seed" option to Bayesian analyses which use sampling. I think it would be nice to add this option, but I also remember vaguely that we talked about this before and I cannot recall anymore whether there were good arguments for not including this.

**Comment by mac2393** [comment]
I just asked about this again today at SIPS2019. Is there a place in preferences to set.seed()?

**Comment by jenlissemore** [comment]
I came here to ask this same question.

An example of where it would be useful to set a seed: After performing a Bayesian Repeated Measures ANOVA, I want to check the robustness of the results to different prior distributions, by manually specifying several different prior distributions. Each time I do this, however, a different seed is set. Therefore, if I start with r=0.5 for fixed effects, then try r=0.2, when I return to r=0.5, the result will have changed from my initial reported result. It would be ideal to use a constant seed while manually changing the prior options.
