### ISSUE TITLE
When trying to open a JASP file, JASP is not an available location

### ISSUE THREAD

**Issue by aicooper** [jasp-stats/jasp-issues#1260]
* JASP version: 0.8.1

* OS name and version: OS X El Capitan
* Bug description: I have been unable to open any JASP files to perform tasks, I only have a singular data set which was downloaded from the same source I have been downloading the new files

#### Steps to reproduce:
1. Go to 'file-->open'
2. Click on 'downloads'
3. Scroll down to 'desired file'
4. unable to open file

**Comment by boutinb** [comment]
Hi @aicooper Why do you use such an old Mac OS & JASP versions? Apple stopped supporting El Capitan already 3 years ago. Using such a version is quite dangerous (no security update). The last version of JASP supporting El Capitan is 0.9.2. If you really don't want to upgrade your Mac OS, you can still use this version https://static.jasp-stats.org/JASP-0.9.2.0-XCode8.2.dmg. But we don't make any support for such an ole version.
