### ISSUE TITLE
How to install jasp on Debian with gnome?

### ISSUE THREAD

**Issue by GithubUser699** [jasp-stats/jasp-issues#1261]
We will use jasp and I have Debian linux with gnome.

This https://jasp-stats.org/download/ wasn't helpful as the only thing I could use is the flatpak version.

But it depends on kde which I don't have. So... how to install nativly on my gnome environment?

(yes, I tried "apt-get install jasp" and also looked at the software center. I also found this https://github.com/lindemann09/jasp-linux-install but it's 6 years old. I could also find this https://wiki.debian.org/Derivatives/Census/JaSP_packages but it isn't available for latest debian (Debian GNU/Linux 10 (buster), 64-bit, gnome 3.30.2))

I hope you can help me. Thank you!

**Comment by JorisGoosen** [comment]
Hello,

JASP cannot really run "natively" on gnome, as that would require it running with GTK.
Because JASP is based on qt we need that, and the "kde-flatpak" is only used because it contains Qt.

In short, I would use the flatpak if I were you. I personally run the `i3` wm aand also use the JASP flatpak there and it works fine. 

The reason we use flatpak is because just getting accepted in the debian repositories is pretty hard and the dependencies we need are incredibly outdated usually. So it isn't very practical to have it install as a "real debian pkg".

Also, to install flatpak and use JASP you do not need to install kde.
Did you just try following the linux guide?

**Comment by GithubUser699** [comment]
```
user@debian:~$ flatpak install flathub org.jaspstats.JASP
Looking for matches…
Required runtime for org.jaspstats.JASP/x86_64/stable (runtime/org.kde.Platform/x86_64/5.15) found in remote flathub
Do you want to install it? [Y/n]: y

org.jaspstats.JASP permissions:
    ipc       network              wayland              x11
    dri       file access [1]      dbus access [2]

    [1] home, xdg-config/kdeglobals:ro
    [2] com.canonical.AppMenu.Registrar


        ID                                                          Arch   Zweig  Remote  Download
 1.     org.kde.Platform                                            x86_64 5.15   flathub < 370,8 MB
 2.     org.freedesktop.Platform.GL.default                         x86_64 20.08  flathub  < 96,0 MB
 3.     org.freedesktop.Platform.VAAPI.Intel                        x86_64 20.08  flathub  < 11,5 MB
 4.     org.freedesktop.Platform.openh264                           x86_64 2.0    flathub   < 1,5 MB
 5.     org.kde.PlatformTheme.QGnomePlatform.Sources                x86_64 5.15   flathub < 500,2 kB
 6.     org.kde.PlatformTheme.QGnomePlatform                        x86_64 5.15   flathub   < 4,9 MB
 7.     org.kde.PlatformTheme.QtSNI.Sources                         x86_64 5.15   flathub  < 39,8 kB
 8.     org.kde.PlatformTheme.QtSNI                                 x86_64 5.15   flathub   < 1,3 MB
 9.     org.kde.WaylandDecoration.QGnomePlatform-decoration         x86_64 5.15   flathub   < 4,8 MB
10.     org.kde.WaylandDecoration.QGnomePlatform_decoration.Sources x86_64 5.15   flathub < 473,1 kB
11.     org.kde.Platform.Locale                                     x86_64 5.15   flathub < 341,7 MB (partial)
12.     org.jaspstats.JASP                                          x86_64 stable flathub < 562,0 MB

Proceed with these changes to the Default system installation? [Y/n]:
```

Won't that install kde (and maybe remove /break gnome)? I never used flatpack or anything which wasn't compatible with debian and gnome.

**Comment by JorisGoosen** [comment]
No it won't break gnome or actually install kde for that matter.

flatpak keeps separate dependencies from the system it runs on. This means that it can install the different parts on all kinds of linux systems. It won't otherwise interfere with your OS at all.

**Comment by JorisGoosen** [comment]
And it is fully compatible, really, no need to worry ;)

**Comment by GithubUser699** [comment]
Okay, I trust you.

Everything still workes until now (after downloading) and jasp seems to works good as well.

Thank you for your fast help and for taking away my worries!

**Comment by JorisGoosen** [comment]
You are welcome and I hope JASP will be a pleasure to use!
