### ISSUE TITLE
Mac Version 10.10.6

### ISSUE THREAD

**Issue by paucaryomi** [jasp-stats/jasp-issues#1264]
* JASP version: Which one should i use?

* OS name and version: Mac 10.10.6
* Analysis: 
* Bug description: Hello
I need assistance on what JASP link I can download for a Mac 10.10.6 version. I have attempted to download a few links from your page but my Mac continually pops up a message stating it's not compatible with my computer. 

May you send any suggestions/ links that you may think could work?
* Expected behaviour:

**Comment by AlexanderLyNL** [comment]
Hi Paucaryuomi,

You're using Mac OSX Yosemite. This version of mac OS hasn't been supported by Apple for almost four years (August 2017). This means that you're at risk of security breaches. For us this means that we are unable to make the newest JASP versions available for these older OS. I think that the following version might work:

https://static.jasp-stats.org/JASP-0.9.2.0-XCode8.2.dmg

Note that this is version 0.9.2 and it does not include many features that we added to JASP over the last 3 years. If 0.9.2 doesn't work, you might try one of our 0.8 versions in our repository:

https://jasp-stats.org/previous-versions/

Hope this helps.

Cheers,
Alexander

**Comment by JorisGoosen** [comment]
Also it doesn't include numerous bugfixes either, I would strongly recommend updating your MacOS or replacing either your laptop or use something like linux. But we can't help you out with getting a newer version of JASP running on such an outdated system.

Sorry about that.
