### ISSUE TITLE
Saving figures: Don't fail without file name extension.

### ISSUE THREAD

**Issue by JoKeyser** [jasp-stats/jasp-issues#1265]
* JASP version: 0.14.3

* OS name and version: Ubuntu 20.04
* Analysis: Descriptives, etc.
* Bug description: If the file name to save to does *not* include an extension, JASP fails with "Error message: Format incorrectly specified". This is irritating and redundant, since the saving dialog already specifies the file format, so the extension is actually specified from the UI.
* Expected behaviour: JASP should always use the setting specified in the save dialog. If the user manually specifies an extension in addition, check if it is consistent with the UI dialog - if yes: take it. If inconsistent, ask user to resolve the conflict (lazy people like me would just delete the manually typed extension).

#### Steps to reproduce:
1. Go to any plot.
2. Click on 'Save image as'
3. See screenshot:

![jasp-save-please](https://user-images.githubusercontent.com/8722846/115878731-2aa5aa00-a449-11eb-87f0-f8dbe177d7cb.png)

**Comment by JoKeyser** [comment]
Another, related request:

It would be nice if JASP either:
- remembered the choice of file extension, or
- users can set their preference in the figure options (where you set the PPI etc)

Currently, JASP defaults to PNG every time I save an image.

**Comment by JoKeyser** [comment]
@tomtomme thanks for checking, yes it works for me too, so the main issue is resolved.
An option to set your preference or JASP remembering would be nice.

And one minor observation: If you supply the file extension manually, JASP does the right thing, i.e. to use the corresponding format, but it doesn't switch to the corresponding format in the file dialog. Maybe adding that would be nice, too.

**Comment by tomtomme** [comment]
I second also this second request. The described behaviour is standard in most other programs I use.

**Comment by tomtomme** [comment]
@JoKeyser 
I tested your second request. When I type .svg manually the UI switches to .svg automatically and the created file is .svg - so all fine here on manjaro kde.

**Comment by JoKeyser** [comment]
@tomtomme ah nice to hear that it works, it may well be my exotic desktop environment that is to blame (I'm using `i3wm`).
So rather than edit, I would close this one, and if anyone else bumps into this, they should open a fresh issue.
(In general with editing, I think the history of what's going on will be way too confusing.)
