### ISSUE TITLE
Error loading scatterplot

### ISSUE THREAD

**Issue by hjosborn16** [jasp-stats/jasp-issues#1266]
* JASP version: 0.14.1.0

* OS name and version: MacOS 10.14
* Analysis: Correlation plot under descriptives option
* Bug description: See attached screenshot for full error
* Expected behaviour: It should be loading a scatterplot between continuous variables. I'm submitting this error on behalf of a student in my statistics course.

#### Steps to reproduce:

![thumbnail_image_6487327](https://user-images.githubusercontent.com/82959461/115925156-b40bab00-a44e-11eb-9d1c-ba4fa07119dc.jpg)

**Comment by boutinb** [comment]
Hi @hjosborn16 The picture you send is from a really old JASP version, surely not from 0.14.1. Could you ask your student to use an up-to-date JASP version?
