### ISSUE TITLE
Update List of Youtube Tutorials

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#1268]
You have a nice 2020 overview of JASP videos in this blog post: 
https://jasp-stats.org/2020/02/11/how-to-use-jasp-jasp-on-youtube/

An Update would be great. During the last year many Youtubers added Tutorials. I also currently do one video a week to complement my virtual university seminars:
https://www.youtube.com/channel/UCjH2MCEThnoyDXTS31vCwZQ/videos

Only a few like me upload in german language:
https://www.youtube.com/results?search_query=jasp+tutorial+deutsch&sp=CAISBAgFEAE%253D

Maybe the new blog-post could cover especially languages other than english.
Would be gread to see those ressources added.
Thanks, Thomas

**Comment by EJWagenmakers** [comment]
Thanks, we're on it
