### ISSUE TITLE
SEM Analysis terminated unexpectedly 

### ISSUE THREAD

**Issue by IRoss10** [jasp-stats/jasp-issues#1269]
* JASP version: 0.14.1

* OS name and version: MacOS Big Sur 11.2.1
* Analysis: SEM
* Bug description: The below image appeared when I tried to enter my SEM model

I edited my syntax to be 
narc =~ Pers.Narc01r.T11 + Pers.Narc02r.T11
and recieved the following message 

![image](https://user-images.githubusercontent.com/82854588/116167237-2a582800-a743-11eb-9946-9581b089bb35.png)

**Comment by boutinb** [comment]
Hi @IRoss10 Could you send your data, or your JASP file?
