### ISSUE TITLE
Bayesian linear regression robustness check in summary stats but not in common?

### ISSUE THREAD

**Issue by quentingronau** [jasp-stats/jasp-issues#127]
Is there a reason why we have the robustness check plot in the summary stats module but not in common (at least I could not find it easily)?

**Comment by vankesteren** [comment]
@vandenman do you know something about this? I don't think I am the right person for this issue

**Comment by vandenman** [comment]
I'm closing this because I think it's outdated but please reopen if I'm wrong. The robustness check plot is now available through JASPgraphs.
