### ISSUE TITLE
Feature request: Bayesian Logistic Regression

### ISSUE THREAD

**Issue by AugustOlsson** [jasp-stats/jasp-issues#1271]
Hi, a great addition would be the possibility to conduct Bayesian (binary) logistic regression as an alternative to the "standard" frequentist logistic regression. I do all the analyses I can using bayesian stats, and it is a bit messy to *have* to include a frequentist analyses together with otherwise bayesian analyses when I need to perform a logistic regression. 

Best,
August

**Comment by EJWagenmakers** [comment]
Yes, this has been on our to-do list for a while; thanks for the reminder, I agree this is an important analysis.

**Comment by tomtomme** [comment]
@AugustOlsson 
This is done! Please check out and feel free to reopen, if there is still something missing for you!
