### ISSUE TITLE
JASP won't run any analysis

### ISSUE THREAD

**Issue by Posh061090** [jasp-stats/jasp-issues#1273]
* JASP version:14.1

* OS name and version:
* Analysis: 
* Bug description: Cant run any analysis. As soon as I have uploaded the data and select analysis the app freezes and doesnt respond to any action.
* Expected behaviour: Run the analysis

[All soil data.xlsx](https://github.com/jasp-stats/jasp-issues/files/6400934/All.soil.data.xlsx)

**Comment by boutinb** [comment]
Hi @Posh061090 Which OS (Windows, Mac, Linux) do you use, and which version?

**Comment by Posh061090** [comment]
> Hi @Posh061090 Which OS (Windows, Mac, Linux) do you use, and which version?

I just tried to run my stats again and now I am faced with a new problem. Please the attached screengrab showing the error code.

![JASP error](https://user-images.githubusercontent.com/83425612/116686599-50d0ca00-a9b4-11eb-8fd8-56d98f53ac3f.jpg)

**Comment by vandenman** [comment]
Hi @Posh061090 could you post the log files? This [guide](https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/user-guide/logging-howto.md) explains how to turn on logging.

If you can first *delete* all logfiles, then recreate the crash, and then post all logfiles here (both of the form `JASP 2020-11-24 10_48_37 Desktop.log`, and of the form `JASP 2020-11-24 10_48_37 Engine 0.log`, note that there may be multiple files).

**Comment by Posh061090** [comment]
[JASP 2021-04-30 13_30_40 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/6405001/JASP.2021-04-30.13_30_40.Desktop.log)
[JASP 2021-04-30 13_30_40 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/6405002/JASP.2021-04-30.13_30_40.Engine.0.log)

**Comment by JorisGoosen** [comment]
Hey Portia,

Im not 100% sure this is what is causing your problem, but it can't hurt to try it.

If you go to "Main Menu -> Preferences -> Advanced Preferences"  then you see "Handling LC_CTYPE"
Can you choose `Keep LC_CTYPE at systemdefault.` there and then restart JASP?
Maybe that helps.

**Comment by Posh061090** [comment]
> Hey Portia,
> 
> Im not 100% sure this is what is causing your problem, but it can't hurt to try it.
> 
> If you go to "Main Menu -> Preferences -> Advanced Preferences" then you see "Handling LC_CTYPE"
> Can you choose `Keep LC_CTYPE at systemdefault.` there and then restart JASP?
> Maybe that helps.

I just tried your suggestion now, but the problem still persists. Thank you though :-)

**Comment by Posh061090** [comment]
> Ah ok, too bad.
> 
> I think we can try two other things, to be sure to know what goes wrong. I hope you want to bear with me :)
> 
> * Try making a new user in Windows where the username doesn't contain any spaces or "weird" characters. (I see your username is "Portia pohlo" maybe the space is messing up something...). And then try running JASP as that user.
> * Try setting Windows in a different locale, like USA or something, instead of South Africa. Just to see if that helps.

No problem, I appreciate the help :-). The app was working before without any issues. It only started giving me trouble yesterday when I upgraded to the latest version. Now even if I go back to the old version it gives the same trouble. If my location and username wasn't a problem before why would it be now? Sorry for the questions I am just trying to narrow things down.

**Comment by Posh061090** [comment]
> Ah ok, too bad.
> 
> I think we can try two other things, to be sure to know what goes wrong. I hope you want to bear with me :)
> 
> * Try making a new user in Windows where the username doesn't contain any spaces or "weird" characters. (I see your username is "Portia pohlo" maybe the space is messing up something...). And then try running JASP as that user.
> * Try setting Windows in a different locale, like USA or something, instead of South Africa. Just to see if that helps.

I cannot change the username and location as this is a work laptop, not a personal one. I don't have administrative control on the pc

**Comment by boutinb** [comment]
Hi @Posh061090 Nice that it works! But do you have any idea why it works now?

**Comment by Posh061090** [comment]
> Hi @Posh061090 Nice that it works! But do you have any idea why it works now?

I have no idea why it worked. I was just testing it when it started working and it ran the analysis so I don't know the cause and I didn't do anything differently than before.
