### ISSUE TITLE
JASP crashed. It happens when I try and run two JASPs programs at the same time. It freezes and crashes.

### ISSUE THREAD

**Issue by moonlitpath66** [jasp-stats/jasp-issues#1277]
* JASP version: 0.14.3
* OS name and version: KDE Flatpak runtime

* Analysis: 
* Bug description:
* Expected behaviour:

#### Steps to reproduce:

-----------------------------------------------------------------------

### Debug information:
**Engine # 0** process *crashed* and it's state is *initializing*.
**Engine # 1** process *does not exist (anymore)* and it's state is *stopped*.
**Engine # 2** process *does not exist (anymore)* and it's state is *stopped*.
**Engine # 3** process *does not exist (anymore)* and it's state is *stopped*.

[Commit used](https://github.com/jasp-stats/jasp-desktop/commit/c618f4f749569939c9082daaf2949a4ba7d53437)

**Comment by juliuspf** [comment]
@moonlitpath66 is this issue still valid with the latest version?
