### ISSUE TITLE
JASP gets confused when I open a second dataset

### ISSUE THREAD

**Issue by nathgeig** [jasp-stats/jasp-issues#1278]
Using JASP version 0.14.1, I ran into an issue I haven't had before.  When I try to run analyses using datasets (e.g., a t-test with the Harpo dataset, or a correlation analysis with the Parenthood dataset), JASP isn't able to find the data.  For example, with the correlation analysis it says "Error in `[.data.frame`(dataset, vcomb[[i]]): undefined columns selected."   

I tried restarting JASP and that didn't help.  

So I restarted the computer and analyses worked with the first dataset I pulled up (Harpo).  But then didn't work on a second dataset (Parenthood) or when I closed Harpo and reopened.  

So it seems like the only way I can get JASP to run is by restarting the computer before every time I open a new dataset.

**Comment by nathgeig** [comment]
I should add to this that the filter section seems to say "No more data!" at the times when the analyses don't work.  Even though I haven't put any filters on.

**Comment by boutinb** [comment]
@nathgeig Quite strange, I cannot reproduce this. On which OS and version do you work? Can you also send us the log files: https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/user-guide/logging-howto.md

**Comment by Rudy-Labs** [comment]
I get the following "You need a new application to open this link to ms-gamingoverlay"
Say right clip "Open with", select the jasp extension and remain the same.
