### ISSUE TITLE
Add random effects and nesting designs to frequentist ANOVA

### ISSUE THREAD

**Issue by FarMar** [jasp-stats/jasp-issues#128]
Add an option for random effects to the frequentist ANOVA, and allow nesting of factors
* Enhancement: Improves functionality to allow a wider range of experimental designs to be analysed
* Purpose: To enable users to analyse designs which are nested and contain random factors e.g. location, block, etc.

**Comment by tomtomme** [comment]
@FarMar 
We have now a (Generalized) Linear Mixed Model module (https://jasp-stats.org/2020/07/02/introducing-jasp-0-13)
Since an ANOVA with random factors is a special case of this model, it could suffice for your needs. 

Is that so?

**Comment by JohnnyDoorn** [comment]
I think so, so closing this now (please reopen if I'm mistaken).
