### ISSUE TITLE
Hi, NEW MAC CANT GET SPSS

### ISSUE THREAD

**Issue by domryan24** [jasp-stats/jasp-issues#1282]
Hi, 

I need to use JASP to edit and analyse my data file but I can only download my data into SPSS or CSV format - however whenever I try and open the CSV format the app automatically crashes everything, so I opted the SPSS format which worked - however I need to edit my data set and can't because it won't allow me to (as SPSS is not downloaded on my MAC and can't be due to the new M1 chip).

Does anyone have a way they could help me?

How can I get around this problem?

(When I try and edit)
<img width="553" alt="Screenshot 2021-05-04 at 1 47 09 pm" src="https://user-images.githubusercontent.com/83649980/117005499-3ada4680-acdf-11eb-93e9-327e208c6c6c.png">

THANKS SO MUCH, ITS FOR MY FINAL DISSERTATION AND REALLY APPRECIATE ANY HELP :)

**Comment by boutinb** [comment]
Hi @domryan24 Which version of JASP do you use? And which OS (and version) do you have?

**Comment by domryan24** [comment]
Hi @boutinb, I've now been able to export the data set into a CSV film from JASP and then opened that CSV file and is now working - however (in my data set of 105) I'm doing correlation analyses and want scatterplots to show and use in my report - however not all my datapoint come onto the scatterplots when I try and do a correlation - is this the correct format (just looks strange with so little data points) or is there something I'm doing wrong you could help me with?

<img width="1440" alt="Screenshot 2021-05-04 at 2 45 20 pm" src="https://user-images.githubusercontent.com/83649980/117012967-5b0e0380-ace7-11eb-895f-45b8658f469b.png">

**Comment by domryan24** [comment]
Thank too @boutinb !!
