### ISSUE TITLE
Repeated Measure ANOVA (non-parametric) doesn't work! screenshot

### ISSUE THREAD

**Issue by areeq1** [jasp-stats/jasp-issues#1283]
Dear JASP support team,

I tried to run the repeated measure ANOVA (the non-parametric version). The analysis works OK, but only when I insert the group factor the software won't run.

Please see the screenshot
![Screen Shot 2021-05-04 at 5 01 31 pm](https://user-images.githubusercontent.com/68887104/117016023-f361b380-acfa-11eb-841f-285da90815c1.jpg)

Thank you for your support,
Abdullah

**Comment by JohnnyDoorn** [comment]
Hi @areeq1,

Adding a grouping factor will lead to the test being the Durbin test (see https://en.wikipedia.org/wiki/Durbin_test). 

> The Durbin test is a nonparametric test for balanced incomplete designs that reduces to the Friedman test in the case of a complete block design. 
> A balanced incomplete block design has the following properties:
>   -  Every block contains k experimental units.
>  - Every treatment appears in r blocks.
>  -  Every treatment appears with every other treatment an equal number of times.

It seems that your grouping factor (gender) is not balanced, so the test is not possible for this data.

Kind regards,
Johnny

**Comment by areeq1** [comment]
Thank you for the prompt and useful response, Johnny!
Much appreciated
