### ISSUE TITLE
Error chronbachs alpha reliability test

### ISSUE THREAD

**Issue by aimeewardle** [jasp-stats/jasp-issues#1287]
See image attached. Trying to upload to reliability and it took 30 minutes before it said this...
![20210506_140901](https://user-images.githubusercontent.com/83768434/117304066-41022b80-ae75-11eb-84f4-5b1b2f822705.jpg)

**Comment by boutinb** [comment]
Hi @aimeewardle Which JASP version do you use? Which OS and version do you use? How big is your data? Could you share it? And what did you do exactly before getting this error (which  options did you use)?

**Comment by aimeewardle** [comment]
Jasper type is 14.0
Doing reliability test on questionnaire that has 146 questions so selected
each question and put them into variable section to do a chronbachs alpha.

**Comment by aimeewardle** [comment]
It's as if the amount of data is too much for it to handle but I have my dissertation due and need it done

**Comment by boutinb** [comment]
Hi @aimeewardle, on which OS do you work (Mac, Windows, Linux), with which version?
You say you use JASP 0.14, but we have released a newer version 0.14.1, could you try it?
And my question about how big is your dataset, is to know how big in Mega Bytes is your datafile. Would it be possible to send us this datafile?

**Comment by AxiaMuller** [comment]
I'm a Windows user, and the error is the same. I also have the latest version, downloaded it two days ago.

**Comment by AxiaMuller** [comment]
Also, I had missing values, so I replaced them with -999, added it to data preferences and then it crashed

**Comment by boutinb** [comment]
Hi @AxiaMuller Couls you send me your datafile (in a zip format)? And tell me exaclty each step you do before the crash?

**Comment by juliuspf** [comment]
@aimeewardle, sorry for the late reply. I will close this issue as it is fixed in the newest JASP version. Feel free to reopen it if necessary.
