### ISSUE TITLE
JASP file opening and loading but crashing before I see my analyses

### ISSUE THREAD

**Issue by JHBdeGroot** [jasp-stats/jasp-issues#1289]
* JASP version: 0.14.1

* OS name and version: Mac OS Catalina 10.15.7
* Analysis: Problem opening JASP file
* Bug description: Opens and loads JASP file but it closes/crashes before showing analyses
* Expected behaviour: Correctly open JASP file and see analyses

#### Steps to reproduce:

I wanted to attach the file producing this problem but it's too big (40 MB vs. 10 MB limit). Let me know if there's another way I can send it so it may be more easy to solve this problem!

**Comment by boutinb** [comment]
Hi @JHBdeGroot Does this happen if you try a smaller file? 40MB should not be too big for JASP (I've just trued a file og 60 MB without problem). Can you zip your file and try to send it?

**Comment by JHBdeGroot** [comment]
Hi @boutinb  I'm getting the following error if I try to upload the zip file - Can I paste a Wetransfer/surffile link to the document?: 
"Yowza, that’s a big file. Try again with a file smaller than 10MB."

**Comment by boutinb** [comment]
A Wetransfer link is OK.

**Comment by JHBdeGroot** [comment]
https://we.tl/t-Yipsu3tn8e

**Comment by boutinb** [comment]
Could you send the data file instead? I cannot load this JASP file...

**Comment by JHBdeGroot** [comment]
Yes, that's the problem I'm having with the JASP file, and I'm wondering why it occurs. Datafile can be accessed here.
https://we.tl/t-DNTvPD26Eg

**Comment by boutinb** [comment]
Hmm, I have no problem with the data file (it is quite small, so it is surely not a memory problem), I can load it and make analyses, save JASP, load the new JASP file without problem.
Here is my JASP file: https://we.tl/t-01dHNL98C6

**Comment by JHBdeGroot** [comment]
To be clear: I'm trying to open my analyses in JASP based on the SPSS-dataset. So I had done a ton of analyses in JASP already, but now I can't open the JASP file I send you anymore, and I'm wondering what's wrong.

**Comment by JHBdeGroot** [comment]
I will try it out later - I'll let you know if I run into any other troubles, thank you for your help!

**Comment by boutinb** [comment]
OK fine, the new version should be released over some weeks.
