### ISSUE TITLE
Pressing tab should select the new level instead of the next factor

### ISSUE THREAD

**Issue by MichlF** [jasp-stats/jasp-issues#1292]
* Enhancement request: 
* Issue:
Occurs for example when creating a repeated measures ANOVA with one factor of more than 3 levels: When labelling individual levels of the first factor, one can advance from one level to the next by pressing the TAB key. This works fine for the first three levels but when going from the third to the fourth level, the selection jumps to the second RM factor instead of jumping to the newly created fourth level. This is rather unintuitive and requires manual selection of the newly created fourth level. This behavior is even more problematic when creating an ANOVA with a lot of levels per factor because it requires a manual mouse selection for every single newly created level.

EDIT: The behavior becomes even more unpredictive after typing in the label for the second factor with the selection jumping to the last level of the previous factor. Once you enter the label of that level, the next tab jumps you to the first level of the second factor. So in short, highly uninuitive!

* Enhancement suggestion:
The enhancement therefore should be that it should always jump to the new level instead of the second factor. Factor selection should be done per manual mouse click or another hotkey / key combination.
This will also not require the user to delete the newly created level when the necessary amount of levels is reached, simply because that level won't be created in the data entry window (e.g. the "Repeated Measures Cells") when no input is given. That is, the user can simply not type anything and manually select the next factor if desired.

**Comment by tomtomme** [comment]
Still valid with 0.18.3. Using Tab acts strangely. Sometimes going down, sometimes up.

**Comment by RensDofferhoff** [comment]
Yes the whole tab/arrow key order of the RM components are a bit broken again. I will try to find some time

**Comment by tomtomme** [comment]
@MichlF 
I think this fixed now with 0.19 beta
Please reopen if you think, that this does not solve the issue!!

To test yourself you could get the latest beta from here: https://static.jasp-stats.org/Nightlies/
