### ISSUE TITLE
JASP keeps on crashing when I try to open a datafile

### ISSUE THREAD

**Issue by Bra-coder** [jasp-stats/jasp-issues#1293]
* JASP version: 14.01

* OS name and version: Windows
* Analysis: 
* Bug description: Opening JASP is quite easy and works, but when I try to open a datafile JASP stops working when the loading bar is almost complete. I used JASP already with the same datafile, and this worked before. After a while it became harder to open the file, I had to try 4/5 times before it would open. Today I tried it for 20 times now, still keeps on crashing. I already reinstalled some system drivers. Also I tried the 'safe graphics' option. I read that people had the same problem with previous versions... Is it just faith that I am the unlucky one now? Please help if possible!
* Expected behaviour:

**Comment by boutinb** [comment]
Hi @Bra-coder Does it happen only for one datafile, or can you open other datafiles (like the ones in the Data Library)? If this is due to a particular datafile, how big is this file? Would it be possible to send this datafile (in a zip format)?

**Comment by tomtomme** [comment]
@Bra-coder 
could you re-test with current jasp 0.18.3?
