### ISSUE TITLE
import long format file for Repeated ANOVA

### ISSUE THREAD

**Issue by fabien-tell** [jasp-stats/jasp-issues#1296]
Thanks for your great work. However, as an R user I was surprised, if I did well understand (I may be stupid) that we need a different format for repeated ANOVA. Instead of having factors (Categorical factors) and error factors (individual ID) in columns as well as the dependent variable, I had to redo all my csv files. For the other analysis the format is rather classic but not for this one. I know that some packages require the wide format but would it be possible to choose it? 
  
* Enhancement: Long format File import 
* Purpose: Easy switch from R format input  to Jasp
* Use-case:

**Comment by boutinb** [comment]
Hi @fabien-tell This feature is in our pipeline. This won't be in the next release, but maybe the next one. For the time being, this pre-treatment has to be done indeed before loading the data file into JASP.

**Comment by fabien-tell** [comment]
Thanks a lot.
