### ISSUE TITLE
JASP not searchable in startmenu after installing

### ISSUE THREAD

**Issue by a501** [jasp-stats/jasp-issues#1298]
* JASP version:
* 0.14.1   64bit

* OS name and version: Window 10
* Analysis: 
* Opening Jasp after having closed it
* Bug description:
* When I install Jasp, I can open it directly by clicking the 'lunch JASP'. But when I close the program and I want to reopen it later, it is not opening. When I type in the windows search box 'JASP', it shows me the JASP 0.13.0 version, but I cannot open it (because the 13 version is not installed, but my computer is not realizing it).
* So when I want to open JASP again, I have to first uninstall JASP and than reinstall it again and opening it via the 'lunch JASP' button.
* Expected behaviour:
That I can open and close the software as often as I want.
When I enter 'JASP' in the windows search field, that the right/installed version shows up

**Comment by wawieansaya** [comment]
Same, I'm having a problem too
Each time I try to open JASP up from my computer, it takes me to the setup wizard and gives me the option to repair/change/uninstall. How do I rectify this situation so that I am actually able to open the program.
I don't know what to do I need this for my stats. How did you fix yours? Thank you

**Comment by JorisGoosen** [comment]
Is it possible the registration in the start menu is a little bit off?
I've noticed this on occasion, when Ive just installed JASP (at least) I cannot find it by typing "JASP" into the search/start bar.

But opening the start menu and scrolling through all the apps you have installed and you should be able to find JASP under, well, "JASP".

Could you let me know if that at least starts JASP?

I can have a look for the next release to make sure it get's registered properly.

**Comment by a501** [comment]
Hello,

Yes indeed, in this way I can open it!!!
Thank you verymuch for your help!!

________________________________
Von: Joris Goosen ***@***.***>
Gesendet: Montag, 17. Mai 2021 12:44
An: jasp-stats/jasp-issues ***@***.***>
Cc: a501 ***@***.***>; Author ***@***.***>
Betreff: Re: [jasp-stats/jasp-issues] Can't open JASP, always need to uninstall than install again (#1298)


Is it possible the registration in the start menu is a little bit off?
I've noticed this on occasion, when Ive just installed JASP (at least) I cannot find it by typing "JASP" into the search/start bar.

But opening the start menu and scrolling through all the apps you have installed and you should be able to find JASP under, well, "JASP".

Could you let me know if that at least starts JASP?

I can have a look for the next release to make sure it get's registered properly.

**Comment by tomtomme** [comment]
@a501 @wawieansaya 
Could you test if the issue persists with jasp 0.18.3?
I guess depending on how fast your machines are, the windows search needs some minutes to gather informations on just installed programs. But as long as the start menu icon exists right after install this should not be a real problem, correct?
