### ISSUE TITLE
Copying results into Word includes previously deleted analyses

### ISSUE THREAD

**Issue by asjones987** [jasp-stats/jasp-issues#1301]
* JASP version: JASP 0.14.1
* OS name and version: Windows 10

I imported a small CSV file then added descriptive statistics and a few other modules. Some modules i removed others i clicked on then removed before even adding data fields.

The results window looked correct with the modules and options I selected. This included not showing modules on the left windows or results on the right window for items I had removed.

I then went to the very top title with the default name Results and selected the drop down arrow. I selected copy and pasted the results into Microsoft Word. I was excited for the output as i could adjust and tweak the layout from there.
HOWEVER then I realized the results pasted into MS Word also included the modules I had removed. They were not in the results screen but included in the copy.

I tested this a few times and it seemed to happen every time.

I can submit the JASP file if needed, but i may need to do some cleanup first.

Hopefully this is an easy issue.

**Comment by boutinb** [comment]
Hi @asjones987 I cannot reproduce this problem, but maybe I don't do exactly what you describe. Could you indeed send your JASP file (first zip it to send it via GitHub)?

**Comment by asjones987** [comment]
I have attached my JASP File. I will also try uploading a video of my issue.

[Copy to Clipboard JASP.zip](https://github.com/jasp-stats/jasp-issues/files/6516344/Copy.to.Clipboard.JASP.zip)

**Comment by boutinb** [comment]
Hi @asjones987 Thanks, I can reproduce it. I put this bug in the backlog. For the time being as workaround, you can save the JASP file, close JASP, and load again the JASP file, then you don't have this problem anymore.

**Comment by asjones987** [comment]
Hi @boutinb, thanks for the follow-up. I did realize when making the video of the workaround.  Hopefully it is an easy fix that you all can get to sooner rather than later. I do understand priorities.  Good luck and thanks for supporting JASP.
