### ISSUE TITLE
Filter selection problem 

### ISSUE THREAD

**Issue by Type-token** [jasp-stats/jasp-issues#1302]
* JASP version:

* OS name and version:
* Analysis: T-Test
* Bug description: Filter selection Fail
* Expected behaviour:

#### Steps to reproduce:
1. Go to 'Open'
2. Click on 'Data Library\T-Tests'
3. Scroll down to 'Kitchen Rolls', Then click field name "Sex" and show the filter panel.  Then change the check logo in front of "M" to "X" so as to exclude male data. However, it won't work. Male data won't be displayed in grey or excluded. 

![Filter Selection Failed](https://user-images.githubusercontent.com/64425323/118905825-158c4000-b94f-11eb-843d-c4c55d1e7cb1.PNG)

**Comment by boutinb** [comment]
Hi @Type-token I cannot reproduce this problem. Which version of JASP do you use, and which OS (Windows, Linux, Mac) and version do you use?

**Comment by Type-token** [comment]
windows 10 (64 bit), version 20H2; Jasp version 0.14.1.0  (64bit)

**Comment by boutinb** [comment]
Strange... @JorisGoosen or @vandenman can you reproduce this on your PC?

**Comment by vandenman** [comment]
I cannot reproduce it with JASP 0.14.3 on Ubuntu 20.04

**Comment by Type-token** [comment]
very strange. Vice versa. If only choose "M", the same bug happens.
![Filter Selection Failed 2](https://user-images.githubusercontent.com/64425323/118946694-3cfffe80-b989-11eb-9b76-777bae64e317.PNG)

**Comment by boutinb** [comment]
Could you give us your log files also: https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/user-guide/logging-howto.md

**Comment by Type-token** [comment]
Hi, I try to find the log files here C:\Users\Joffice\AppData\Roaming\JASP\JASP\Logs  
However, it is empty in the folder.

**Comment by Type-token** [comment]
[JASP 2021-05-20 17_34_34 Engine 3.log](https://github.com/jasp-stats/jasp-issues/files/6514701/JASP.2021-05-20.17_34_34.Engine.3.log)
Here is the log file. Thanks!

**Comment by Type-token** [comment]
[JASP 2021-05-20 17_41_40 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/6514784/JASP.2021-05-20.17_41_40.Desktop.log)
[JASP 2021-05-20 17_41_40 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/6514785/JASP.2021-05-20.17_41_40.Engine.0.log)
[JASP 2021-05-20 17_41_40 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/6514787/JASP.2021-05-20.17_41_40.Engine.1.log)
[JASP 2021-05-20 17_41_40 Engine 2.log](https://github.com/jasp-stats/jasp-issues/files/6514789/JASP.2021-05-20.17_41_40.Engine.2.log)
[JASP 2021-05-20 17_41_40 Engine 3.log](https://github.com/jasp-stats/jasp-issues/files/6514790/JASP.2021-05-20.17_41_40.Engine.3.log)

Hi, here are all the log files when this bug shows up again. Many thanks!

**Comment by boutinb** [comment]
From the log, I can see that it seems the engines do not get at all the dataset. Can you load a dataset form your PC, add a simple analysis (Descriptives for example), and check whether it works?

**Comment by JorisGoosen** [comment]
Well, I've just tried it here on Windows x64 0.14.1 but I cannot reproduce this at all.

I will have a look at the logs though, maybe it'll tell me something.

**Comment by JorisGoosen** [comment]
Suppose this version, a nightly, works then keep in mind the warnings we have at our [nightly page](https://static.jasp-stats.org/Nightlies/):

> These installers are generated automatically each night and contain development code; this means that they might not be stable.

> Use at your own risk!

> Keep in mind that, as these versions are in active development, no attempt is made to ensure backward- or forward-compatibility between jasp-files made with nightlies. So if you want to share your work, or even load it with some other version of JASP, you should not use these nightlies but are better off using some official release of JASP.

> If you happen to find a bug in a nightly then it can't hurt to issue a bug report at our issue-tracker, but please be sure to mention that you used a nightly and indicate its commit. The commit can be found in the about window under "Sources".

**Comment by Type-token** [comment]
Thanks. The nightly seems to work fine in my windows 10 pro 64bit laptop but not my home desktop (win 10, 64 bit , version 21H1).  Moreover, in R panel, some letters are missing. 
<img width="1911" alt="Capture Jasp Filter problem" src="https://user-images.githubusercontent.com/64425323/119049825-9c92f400-b9f3-11eb-9e13-a351428a97fc.PNG">

**Comment by Type-token** [comment]
I tried the nighty in my office pc （Win 10, enterprise, 64 bit, version 20H2). Neither did it work. Whenever, I used filter, the R panel will pop up automatically. Moreover, when choosing "F" or "M" in the above examples, cases won't be excluded but all cases will be included. Then I turned Jasp off and tried it again. It turns out sometimes it works sometimes not. Very strange

**Comment by boutinb** [comment]
The missing letters might be another problem. For this one could you go in JASP to Preferences/Interface and change the Interface font to Arial or Helvetica?
The first problem is quite an annoying one because we cannot reproduce it. What I can see is that the engine cannot read the data, and that is done by a so-called shared-memory. Are you admin of your PC? Maybe we will have to do special version to have more logs.

**Comment by JorisGoosen** [comment]
I think what @boutinb is saying is probably right, how is your userfolder structure @Type-token ?

Because for now we are making use of boost's shared memory and it needs to store files in `%APPDATA%/Local/JASP/JASP/` (Or something like that, Im on linux now so can't check) and it might be possible that this goes wrong if that is perhaps a network drive, or well, something else perhaps.

> Then I turned Jasp off and tried it again. It turns out sometimes it works sometimes not. If the R panel doesn't pop up automatically, usually the filter tends to work. Very strange

This on the other hand is kind of weird indeed. Maybe you could add the logs from one of the attempts that worked?

**Comment by Type-token** [comment]
> The missing letters might be another problem. For this one could you go in JASP to Preferences/Interface and change the Interface font to Arial or Helvetica?
> The first problem is quite an annoying one because we cannot reproduce it. What I can see is that the engine cannot read the data, and that is done by a so-called shared-memory. Are you admin of your PC? Maybe we will have to do special version to have more logs.

For the missing letters, even if the interface font is set to Arial in Jasp Version 0.14.1, it won't be fixed. However, for the nightly version, no such problems of missing letters.

**Comment by Type-token** [comment]
> The missing letters might be another problem. For this one could you go in JASP to Preferences/Interface and change the Interface font to Arial or Helvetica?
> The first problem is quite an annoying one because we cannot reproduce it. What I can see is that the engine cannot read the data, and that is done by a so-called shared-memory. Are you admin of your PC? Maybe we will have to do special version to have more logs.

Yes, I am admin of my PC.

**Comment by Type-token** [comment]
> I think what @boutinb is saying is probably right, how is your userfolder structure @Type-token ?
> 
> Because for now we are making use of boost's shared memory and it needs to store files in `%APPDATA%/Local/JASP/JASP/` (Or something like that, Im on linux now so can't check) and it might be possible that this goes wrong if that is perhaps a network drive, or well, something else perhaps. Maybe not enough diskspace? Or on the edge of it... Hmm.
> 
> > Then I turned Jasp off and tried it again. It turns out sometimes it works sometimes not. If the R panel doesn't pop up automatically, usually the filter tends to work. Very strange
> 
> This on the other hand is kind of weird indeed. Maybe you could add the logs from one of the attempts that worked?

I install Jasp 14.1 onto my C drive. When testing nightly version, it is put in C drive, which has 32G empty space.

**Comment by Type-token** [comment]
> change the Interface font to Arial or Helvetica?

This won't work. Finally, when setting it to "Safe Graphics Mode" in the interface, the missing letter problem can be solved.

**Comment by boutinb** [comment]
Hi @Type-token Fine the missing letter problem is fixed. One problem less. For the other problem, I will make a version with more logs, so that we can hope to have more information.

**Comment by boutinb** [comment]
Hi @Type-token Could you try this version http://static.jasp-stats.org/Nightlies/WindowsZip/JASP-nightly-development-1aae37ad72a110ad9152ffe666ce30cce509e88c.zip and send me the logs again?

**Comment by Type-token** [comment]
hi, thanks. for the nightly version, may I know where to find the log files?

**Comment by boutinb** [comment]
They should appear at the same place, something like C:\Users\Joffice\AppData\Roaming\JASP\JASP\Logs, or you can click in Preferences/Advanced the Show logs button.

**Comment by Type-token** [comment]
> They should appear at the same place, something like C:\Users\Joffice\AppData\Roaming\JASP\JASP\Logs, or you can click in Preferences/Advanced the Show logs button.

Hi, Thanks. I've tested.  Seems this version works more swiftly. 

At the beginning, the filter worked when I selected "F" or "M" for the column of "Sex".   However, when I cancel the filter by de-select "F" or "M", JASP will be stuck and crashed.

Moreover, when click open the R panel, the filter function can't go back and failed. Cf the following capture
![Capture 1](https://user-images.githubusercontent.com/64425323/119811446-ad72c680-bf19-11eb-8f1c-f3737bc8aa6b.PNG)

Moreover, even if I clicked the eye icon to hide those filtered-out items, it failed. (cf. the following capture)
![Capture 2](https://user-images.githubusercontent.com/64425323/119811539-ced3b280-bf19-11eb-9f38-dee0559f6b22.PNG)

All the log files are listed as follows:
[JASP 2021-05-27 18_08_43 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/6553268/JASP.2021-05-27.18_08_43.Desktop.log)
[JASP 2021-05-27 18_08_43 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/6553269/JASP.2021-05-27.18_08_43.Engine.0.log)
[JASP 2021-05-27 18_08_43 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/6553270/JASP.2021-05-27.18_08_43.Engine.1.log)
[JASP 2021-05-27 18_21_01 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/6553271/JASP.2021-05-27.18_21_01.Desktop.log)
[JASP 2021-05-27 18_21_01 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/6553272/JASP.2021-05-27.18_21_01.Engine.0.log)
[JASP 2021-05-27 18_21_01 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/6553273/JASP.2021-05-27.18_21_01.Engine.1.log)
[JASP 2021-05-27 18_24_21 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/6553274/JASP.2021-05-27.18_24_21.Desktop.log)
[JASP 2021-05-27 18_24_21 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/6553275/JASP.2021-05-27.18_24_21.Engine.0.log)
[JASP 2021-05-27 18_24_35 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/6553276/JASP.2021-05-27.18_24_35.Desktop.log)
[JASP 2021-05-27 18_24_35 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/6553277/JASP.2021-05-27.18_24_35.Engine.0.log)
[JASP 2021-05-27 18_24_35 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/6553278/JASP.2021-05-27.18_24_35.Engine.1.log)

**Comment by boutinb** [comment]
The thing is that the version I sent you is a development version (so not fully tested), and that you have just found a bug in this version! The Eye button does not work as wanted anymore. This will be fixed.
But can you filter and un-filter the data just by clicking the Filter column of the labels table? I see in the log that you could start an analysis, so it seems that the original problem you had does not to occur anymore. That is quite strange, but still a good nieuws!

**Comment by Type-token** [comment]
> The thing is that the version I sent you is a development version (so not fully tested), and that you have just found a bug in this version! The Eye button does not work as wanted anymore. This will be fixed.
> But can you filter and un-filter the data just by clicking the Filter column of the labels table? I see in the log that you could start an analysis, so it seems that the original problem you had does not to occur anymore. That is quite strange, but still a good nieuws!

To my strange, the filter doesn't work again.
[JASP 2021-05-27 19_07_57 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/6553494/JASP.2021-05-27.19_07_57.Desktop.log)
[JASP 2021-05-27 19_07_57 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/6553495/JASP.2021-05-27.19_07_57.Engine.0.log)

**Comment by boutinb** [comment]
OK, that's interesting. There is definitely a problem with the shared memory library we use (the boost library) with your PC. 
If I have a look at the boost doc, I see:
`In those platforms, shared memory is emulated with mapped files created in a "boost_interprocess" folder created in a temporary files directory. In Windows platforms, if "Common AppData" key is present in the registry, "boost_interprocess" folder is created in that directory (in XP usually "C:\Documents and Settings\All Users\Application Data" and in Vista "C:\ProgramData"). For Windows platforms without that registry key and Unix systems, shared memory is created in the system temporary files directory ("/tmp" or similar).`
I can see on my PC for example that the files are located in c:\ProgramData\boost_interprocess. This ProgramData folder is an hidden folder, but you can see it with the Windows Explorer by clicking in the View menu 'Hidden Items'. Can you see this folder?
Also, in Windows Explorer, if you right-click on your C drive and select the Properties menu, can you see how much free space you have on this drive?

**Comment by Type-token** [comment]
> OK, that's interesting. There is definitely a problem with the shared memory library we use (the boost library) with your PC.
> If I have a look at the boost doc, I see:
> `In those platforms, shared memory is emulated with mapped files created in a "boost_interprocess" folder created in a temporary files directory. In Windows platforms, if "Common AppData" key is present in the registry, "boost_interprocess" folder is created in that directory (in XP usually "C:\Documents and Settings\All Users\Application Data" and in Vista "C:\ProgramData"). For Windows platforms without that registry key and Unix systems, shared memory is created in the system temporary files directory ("/tmp" or similar).`
> I can see on my PC for example that the files are located in c:\ProgramData\boost_interprocess. This ProgramData folder is an hidden folder, but you can see it with the Windows Explorer by clicking in the View menu 'Hidden Items'. Can you see this folder?
> Also, in Windows Explorer, if you right-click on your C drive and select the Properties menu, can you see how much free space you have on this drive?

![Capture 2](https://user-images.githubusercontent.com/64425323/120632642-c50ef980-c49b-11eb-9364-8a35b5368709.PNG)
![Capture](https://user-images.githubusercontent.com/64425323/120632649-c6402680-c49b-11eb-8c28-da9d96f080d7.PNG)

**Comment by boutinb** [comment]
Hi @Type-token Sorry for the late answer. I have to say that I am quite puzzled with your bug. The log says clearly that the boost library cannot find the shared memory which is used between the JASP and its engines. I can see that it can create the files it needs on your PC...
We are planning to change this shared memory by using a local database, but it will take some time...
Maybe @JorisGoosen has a suggestion?

**Comment by JorisGoosen** [comment]
Hello @Type-token and @boutinb 

I've been looking at logs and following this issue from the side. It does look strange.

So for this I've added way more logging to the processes in JASP that manage the shared memory. 
That might help in figuring out where something goes wrong, hopefully.

A new nightly will be building soon and once done I will post it here so that @Type-token can hopefully give it another spin and we can try to get to the bottom of this.

**Comment by JorisGoosen** [comment]
@Type-token do you think you have the chance to test out a new nightly?

See here: https://static.jasp-stats.org/Nightlies/ and I'd recommend just using the `zip64` one as you don't need to install anything, it takes a little while to start up btw so give it some time.

**Comment by Type-token** [comment]
hi, thanks for the update! I try the jasp zip x64 released on June 23. The filter has not yet worked. Cf. the following capture
<img width="1911" alt="Capture Jasp Filter problem" src="https://user-images.githubusercontent.com/64425323/123216854-8ef1f200-d4fc-11eb-8466-5506d739d73a.PNG">

**Comment by JorisGoosen** [comment]
Thank you for testing, could you also upload the logs?

**Comment by Type-token** [comment]
> Thank you for testing, could you also upload the logs?

Here come
[JASP 2021-06-24 14_39_02 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/6707709/JASP.2021-06-24.14_39_02.Desktop.log)
[JASP 2021-06-24 14_39_02 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/6707711/JASP.2021-06-24.14_39_02.Engine.0.log)
[JASP 2021-06-24 14_39_02 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/6707712/JASP.2021-06-24.14_39_02.Engine.1.log)
[JASP 2021-06-24 14_39_02 Engine 2.log](https://github.com/jasp-stats/jasp-issues/files/6707713/JASP.2021-06-24.14_39_02.Engine.2.log)
[JASP 2021-06-24 14_39_02 Engine 3.log](https://github.com/jasp-stats/jasp-issues/files/6707714/JASP.2021-06-24.14_39_02.Engine.3.log)
[JASP 2021-06-24 14_49_57 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/6707715/JASP.2021-06-24.14_49_57.Desktop.log)
[JASP 2021-06-24 14_49_57 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/6707716/JASP.2021-06-24.14_49_57.Engine.0.log)
[JASP 2021-06-24 14_50_03 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/6707717/JASP.2021-06-24.14_50_03.Desktop.log)
[JASP 2021-06-24 14_50_03 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/6707718/JASP.2021-06-24.14_50_03.Engine.0.log)

**Comment by JorisGoosen** [comment]
So...

I can see in the 14_49_57 log that initially it *does find* the shared memory a la:
```
00:00:13.390: SharedMemory::unloadDataSet JASP-DATA-49716
00:00:13.622: Engine received resuming message
00:00:13.622: Engine resuming, absorbing settings and rescanning columnNames for en/decoding
00:00:13.623: SharedMemory::retrieveDataSet(49716)
00:00:13.627: Opened shared mem with name JASP-DATA-49716
00:00:13.627: SharedMemory::retrieveDataSet(49716)
```

It can find it again a few times later, but then the xth time it loses the file (I guess it got deleted somehow?)
```
00:00:21.537: Engine received pauseRequested message
00:00:21.538: Engine paused
00:00:21.538: SharedMemory::unloadDataSet JASP-DATA-49716
00:00:21.540: Engine received resuming message
00:00:21.540: Engine resuming, absorbing settings and rescanning columnNames for en/decoding
00:00:21.541: SharedMemory::retrieveDataSet(49716)
00:00:21.545: Error when retrieving the data set: The system cannot find the file specified.
00:00:21.545: No data set found in shared memory with name: JASP-DATA-49716
```

But we aren't cleaning it up, and this seems to go right in most systems... The problem is that boost doesn't seem to have any function that return the path to the file in question, so I can't track it in JASP itself.

I would really like to fix this thing, for now I can imagine that unloading and reloading the dataset less often might be a boon in your case.

However, the real solution would be to [move away from shared memory fully as discussed in this private issue.](https://github.com/jasp-stats/INTERNAL-jasp/issues/1194), but that will definitely not be done in 0.15.

I will have a look at how hard it is to make it a bit more selective about un- and re-loading.

**Comment by JorisGoosen** [comment]
Alright, so this next version should be a bit more conservative with its shared memory unloading and thus as well with the reloading.
Hopefully that will make it also a bit better behaved on your system.

Same as before, could you try out the following and let us know how it goes?
https://static.jasp-stats.org/Nightlies/WindowsZip/JASP-nightly-lessSharedMemUnReLoading-e6f13e19f4cca5a7f83731d85baa553682860075.zip

**Comment by JorisGoosen** [comment]
@Type-token ?

**Comment by Type-token** [comment]
> Alright, so this next version should be a bit more conservative with its shared memory unloading and thus as well with the reloading.
> Hopefully that will make it also a bit better behaved on your system.
> 
> Same as before, could you try out the following and let us know how it goes?
> https://static.jasp-stats.org/Nightlies/WindowsZip/JASP-nightly-lessSharedMemUnReLoading-e6f13e19f4cca5a7f83731d85baa553682860075.zip

Hi, Thanks. This version works better. seems the filter works now except that sometimes it will cause a crash. Then I have to end the process and reopen it again. cf

![Jasp crash](https://user-images.githubusercontent.com/64425323/123952930-41ccbf00-d9d9-11eb-80c8-39317e68e7f9.PNG)
[JASP 2021-06-30 19_16_36 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/6740461/JASP.2021-06-30.19_16_36.Desktop.log)
[JASP 2021-06-30 19_16_36 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/6740462/JASP.2021-06-30.19_16_36.Engine.0.log)
[JASP 2021-06-30 19_16_36 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/6740463/JASP.2021-06-30.19_16_36.Engine.1.log)
[JASP 2021-06-30 17_44_45 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/6740464/JASP.2021-06-30.17_44_45.Engine.0.log)
[JASP 2021-06-30 17_44_45 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/6740465/JASP.2021-06-30.17_44_45.Engine.1.log)

**Comment by JorisGoosen** [comment]
Well good that it works a bit better, sadly enough I see in the 17_44_45 Engine 1 log that it still fails to find the shared memory suddenly (which is probably why JASP stops responding):
```
00:00:01.640: SharedMemory::retrieveDataSet(21404)
00:00:01.641: Error when retrieving the data set: The system cannot find the file specified.
00:00:01.641: No data set found in shared memory with name: JASP-DATA-21404
```

I'm quite mystified why those files keep disappearing... I would really like to solve it and help you out with our next version but I am running out of ideas. Is there some kind of filesystem cleaner running on your PC?

Because Im reasonably sure the library we use that creates those shared-memory-files has no reason to delete it in the meantime so what is deleting those files?

On the other hand, we are also planning on changing that backend to some other system because this is far from the only complication and that *would* solve this problem. It is only that that will take few more months.

**Comment by Type-token** [comment]
What are  filesystem cleaners? I use 360 antivirus.

**Comment by JorisGoosen** [comment]
Well, I wouldn't know for sure. But I find it mysterious that the backing file that boost-shared-memory uses keeps disappearing on your system.. 

Basically the file is there for a while and then at some point JASP tries to reload from it and it fails because: `Error when retrieving the data set: The system cannot find the file specified.`  so it has somehow gone missing.
This would be a file in `c:\ProgramData\boost_interprocess` probably, in a folder named with a number (Im guessing that is process id or PID.

I've never seen this either on any of my systems or in any bugreport before. 

So it could be something like Norton (it seems to have such functionality: https://support.norton.com/sp/en/us/home/current/solutions/v7786151 ) but I know windows also has something like this (Disk Cleanup tool I think).
But I'm just guessing here to be honest, because I don't know what else could be going on.

**Comment by JorisGoosen** [comment]
Figuring out if it is Norton would of course be easy, simply disable Norton entirely for a bit, run JASP and see if it doesn't crash then.

And I'm fairly sure windows wouldn't be automatically cleaning up stuff (and enabling it looks a bit complicated anyway: https://docs.microsoft.com/en-us/troubleshoot/windows-server/backup-and-storage/automating-disk-cleanup-tool) so most likely that isn't running. 

Your computer is not being managed by some IT-departement? Because then there might be other variables at play as well.
