### ISSUE TITLE
Please consider adding Hayashi's Quantification Methods I-IV

### ISSUE THREAD

**Issue by mossackanme** [jasp-stats/jasp-issues#1304]
* Enhancement: Add Hayashi's Quantification Methods (HQM) I-IV
* Purpose: Research and education
* Use-case: HQM I-IV have been long known in Japanese-/Chinese-speaking academic societies. They are unique in approach but mathematically equivalent to other known methods in the West.

**Describe the solution you'd like**
Mathematically-speaking, HQM I is equivalent to _Regression Analysis_. HQM II is equivalent to _Discriminant Analysis_. HQM III is mathematically equivalent to _Correspondence Analysis_. HQM IV is equivalent to _Multidimensional Scaling_ of categorical data. For each HQM, provide a similar layout to the equivalent pair but using the HQM counterpart for analysis instead.

**Describe alternatives you've considered**
Regression Analysis, Discriminant Analysis, Correspondence Analysis, and Multidimensional Scaling have been widely used, but covering the HQM I-IV would attract more users among Japanese-/Chinese-speaking scholars who are more familiar to employ HQM I-IV.

**Additional context**
https://econpapers.repec.org/article/hitecorev/v_3a27_3ay_3a1976_3ai_3a3_3ap_3a282-284.htm
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1637943/
https://pubmed.ncbi.nlm.nih.gov/7241832/
https://www.mdpi.com/2071-1050/9/6/1057/htm
https://sites.google.com/site/masahironohome/resource/resource/exemplary-analysis-by-hayashi-s-quantification-method-iii
https://link.springer.com/chapter/10.1007/978-4-431-65950-1_48

**Comment by boutinb** [comment]
@EJWagenmakers What do you think?

**Comment by tomtomme** [comment]
@mossackanme 
If those methods are already available in JASP, but only their names are different in Japanese / Chinese - shouldn't this be tackled via translation?
