### ISSUE TITLE
Filtering Issues with Lesser than or equal to on Mac IOS version

### ISSUE THREAD

**Issue by Shalotted** [jasp-stats/jasp-issues#1305]
* JASP version: 0.14.1

* OS name and version: MacOS
* Analysis: 
* Bug description: Filtering system does not filter out any data
* Expected behaviour: 

#### Steps to reproduce:
1. Go to the filter box
2. Enter the equation you want to filter with < or lesser than or equal to
3. press on filter
4. See that your data that is over this value is still in your data set, and is not being picked up by the filtering system

![Screen Shot 2021-05-21 at 10 33 50 AM](https://user-images.githubusercontent.com/84581842/119155194-e7773080-ba20-11eb-9f7b-d95ee2b946c6.png)

**Comment by boutinb** [comment]
Hi @Shalotted Quite strange, I cannot reproduce this problem. Could you send me your JASP file?
