### ISSUE TITLE
Boxplots of r (categories) x c (categories) factors

### ISSUE THREAD

**Issue by proffsg2020** [jasp-stats/jasp-issues#1306]
Assumptions of a two-way ANOVA relate to how the data fits the two-way ANOVA model and these are the following: 

1. there should be no significant outliers in any cell of the design; 
2. the distribution of the dependent variable should be approximately normally distributed in every cell of the design; and 
3. the variance of the dependent variance should be equal in every cell of the design (known as the assumption of homogeneity of variances).

So if I have a 2 x 2 factorial design, for example, gender (male, female) and treatment groups (Treatment 1, Treatment 2) on a DV, then Assumption 1 should display 2 x 2 = 4 boxplots, i.e., boxplots for Male, Treatment 1; Female, Treatment 1; Male, Treatment 2; and Female, Treatment 2.

This is also true for normality assumption that we have to check it for 4 cells of the design.

But JASP has no capability to do this yet.

The only thing JASP can do is a split of variable groups on DV which resulted to a set of boxplots of a factor. For example, Male and Female boxplots of a DV but not boxplots boxplots for Male, Treatment 1; Female, Treatment 1; Male, Treatment 2; and Female, Treatment 2; as mentioned above.

**Comment by tomtomme** [comment]
@proffsg2020 
If I understand your request correctly this is solved since jasp 0.15, which added raincloud plots.
cheers :D

Feel free to reopen, if I misunderstood
