### ISSUE TITLE
Heteroscedasticity testing

### ISSUE THREAD

**Issue by MurtazaMahidolUniversity** [jasp-stats/jasp-issues#1309]
Jasp is fantastic but one feature missing is check for Heteroscedasticity. I use Gretl for that, but if there is an option to check for Heteroscedasticity in JASP, I can do all the regression testing in JASP.

**Comment by vandenman** [comment]
Just so I fully understand the feature request, you want to be able to test whether the residuals of linear regression are heteroscedastic or not?

**Comment by MurtazaMahidolUniversity** [comment]
Hi,

Thanks for the quick reply.

I don't have a very in-depth theoretical knowledge of statistics. So my
quantitative analysis is tool-functionality dependant.

When I use Gretl, I always check the Robust standard error before running
regression analysis to avoid any possible heteroscedasticity errors.
[image: image.png]

With JASP, there is no option to do so.

Is it possible to have this feature in JASP?

Best regards
Murtaza



>

**Comment by MurtazaMahidolUniversity** [comment]
Hi,

Below is the screenshot of the process plugin for SPSS. (
http://www.processmacro.org/download.html )
The HC1 option is used to avoid any possible heteroscedasticity errors when
making regression models.

[image: image.png]

JASP is so good on many fronts, except this one missing functionality. I
hope you guys can add this to JASP to make it the only needed tool for
academic researchers.

Best regards
Murtaza

>
