### ISSUE TITLE
One Sample T Test

### ISSUE THREAD

**Issue by pbrunori92** [jasp-stats/jasp-issues#1311]
* JASP version: 0.14.1

* OS name and version: MacOS MacBook Air 2019
* Analysis: One Sample T Test 
* Bug description: Known bug: computed effect sizes ignore the test value. 
* Expected behaviour: 
[5.One-Sample t-test example - Weight Gain.csv.zip](https://github.com/jasp-stats/jasp-issues/files/6549477/5.One-Sample.t-test.example.-.Weight.Gain.csv.zip)

#### Steps to reproduce: 
1. import data set into JASP (see attached data set)
2. Click on T Tests 
3. click on One sample T Test 
4. known bug highlighted in yellow will appear 

2.

**Comment by vandenman** [comment]
Hi, 

A known bug implies that somebody reported this issue, and subsequently, we updated our list of known bugs to warn people that this part of the analysis does not work. It's already on our radar and will be fixed in the next release.
