### ISSUE TITLE
Plots fonts doesn't rendered.

### ISSUE THREAD

**Issue by rosid-uhm** [jasp-stats/jasp-issues#1312]
* JASP version: 0.14.3

* OS name and version: Ubuntu 20.04 LTS
* Analysis: Descriptives
* Bug description: Plot fonts doesn't rendered properly
* Expected behaviour:

I already using the 

`flatpak run --command=fc-cache org.jaspstats.JASP -f -v`

unfortunately it doesn't fix the problem.
I tried to reinstall JASP but it seems doesn't fix the issues.

![Screenshot from 2021-05-27 10-49-13](https://user-images.githubusercontent.com/84888311/119763215-50efb700-bed9-11eb-9587-a8309031dc67.png)

Thanks!

**Comment by boutinb** [comment]
Hi @rosid-uhm Could you try to change in Preferences/Interface the 'Result & Help' fonts to Lucinda Grande or another standard fonts (like Arial)?

**Comment by rosid-uhm** [comment]
Hi @boutinb , i changed the fonts to Arial, Lucinda, and Times New Roman but it still there.

Any idea? 
Do i need to uninstall other applications (R/ RStudio) since i read in other issues it caused by ggplot packages?

**Comment by rosid-uhm** [comment]
Hmmm, it seems my device in the faulty here, the graphics card driver aren't properly installed in linux since my device support already ended years ago. Thanks for your help @boutinb !
