### ISSUE TITLE
Copy plot to word generates the warning: "additional permissions are required to access the following files"

### ISSUE THREAD

**Issue by boutinb** [jasp-stats/jasp-issues#1313]
* JASP version: 0.14
* OS name and version: MacOS Mojave
* Bug description:
Generate a plot in JASP, copy it with the menu, and paste it into a Word document. Then you get the warning: "additional permissions are required to access the following files"
* Expected behaviour:
This warning should not appear.

**Comment by tomtomme** [comment]
@boutinb 
Closing since we do not support Mojave anymore.
