### ISSUE TITLE
Cannot install JASP software

### ISSUE THREAD

**Issue by Sherlyally** [jasp-stats/jasp-issues#1314]
Why can't JASP software be downloaded?

Can you give me a link, so I can download JASP?

Please. I need JASP. I use JASP software to do my thesis.

I've also used JASP online via rollApp, but can't analyze many variables.

ASAP...

**Comment by vandenman** [comment]
download links are here: https://jasp-stats.org/download/

**Comment by vandenman** [comment]
Here is a [direct link](https://static.jasp-stats.org/JASP-0.14.1-64bit.msi) to download JASP 0.14.1 for Windows. If you use a computer where you do not have admin rights, you can try the [zip version](https://static.jasp-stats.org/JASP-0.14.1-64bit.zip). In case both of these fail, it would be great if you could tell us what exactly fails (e.g., error messages, screenshots etc.)

**Comment by Sherlyally** [comment]
I have tried it, both the link you provide and the zip version. but still it can't be downloaded.
![Screenshot (3)](https://user-images.githubusercontent.com/84972991/120047064-cffe0000-c03d-11eb-80f9-73376cf86d63.png)

**Comment by vandenman** [comment]
This looks more like an internet-related problem than that the download links do not work. If I connect with a VPN to a server in Indonesia (which GitHub lists as @Sherlyally's location) then the download works just fine.

@JorisGoosen did you experience this before/ is there any workaround for this situation?

@Sherlyally does this problem occur regardless of where you are connected to the internet? So for example, do you get the same message "This site can't be reached", regardless of whether you're using your internet at home or say, your internet at work or university?

**Comment by Sherlyally** [comment]
However, on January 16, 2021, I was able to download JASP (JASP 0.8.5.1).

Only under JASP 0.8.5 that I can download.

**Comment by JorisGoosen** [comment]
Sometimes `static.jasp-stats.org` can't be reached, but that is ok as i've also uploaded the installers here: https://github.com/jasp-stats/jasp-desktop/releases/tag/v0.14.1.0

So try https://github.com/jasp-stats/jasp-desktop/releases/download/v0.14.1.0/JASP-0.14.1-64bit.msi

I would **highly recommend using a newer version then 0.8.5.1** @Sherlyally !

**Comment by Sherlyally** [comment]
@JorisGoosen I am very very grateful to you. I can download the link.

**Comment by Sherlyally** [comment]
@vandenman @JorisGoosen thank you for helping me and thank you for solving my problem, now I can work on my thesis.
![Screenshot (4)](https://user-images.githubusercontent.com/84972991/120165240-912a9e80-c225-11eb-90e7-105a83228e77.png)

**Comment by vandenman** [comment]
@Sherlyally That message is nothing to worry about. At start, JASP downloads a list of known issues. Whenever you run an analysis for which we know that some subset might contain an error we show a message, for example:

![image](https://user-images.githubusercontent.com/21319932/120168239-f1f2b080-c1fe-11eb-83bd-2111ab684e3c.png)

The reason why the regular download link didn't work for you might also be why JASP was unable to download the list of known issues.

I'm happy to hear that Joris was able to resolve the problem. I'm closing this issue now, but if something comes up in the future don't hesitate to open a new issue!
