### ISSUE TITLE
Can JASP analyze more than two variables?

### ISSUE THREAD

**Issue by Sherlyally** [jasp-stats/jasp-issues#1317]
After I installed JASP, I tried to do my thesis. But the results are like this (I analyzed four variables and the variables I analyzed were favorable and unfavorable).
I saw on youtube the woman analyzed three variables and it worked (she uses JASP 0.13).
Is JASP only able to analyze a few variables and should always be favorable?

![Screenshot (5)](https://user-images.githubusercontent.com/84972991/120169880-976f4980-c22a-11eb-9295-334154df301a.png)
![Screenshot (6)](https://user-images.githubusercontent.com/84972991/120170091-cdacc900-c22a-11eb-8d79-fc0dcf68d868.png)

**Comment by JoKeyser** [comment]
Disclaimer: I'm not part of the JASP team.
Of course JASP can analyze more than two variables.

Have you followed the advice given in the error message? "The variance-covariance matrix of the supplied data is not positive-definite. Please check if the variables have many missing observations or are collinear"

**Comment by Sherlyally** [comment]
In my thesis, the statements in the measuring instrument that I use are not all positive.
Can JASP not be able to analyze measuring instruments in which there are positive and negative statements ?

**Comment by JoKeyser** [comment]
> Can JASP not be able to analyze measuring instruments in which there are positive and negative statements ?

@Sherlyally , I believe your question is beside the point. JASP's error message is not about the raw data entries, but about the resulting [covariance matrix](https://en.wikipedia.org/wiki/Covariance_matrix) between your variables. It then suggests that you should please check if the variables have many missing observations or are collinear.

**Comment by juliuspf** [comment]
@Sherlyally, I apologize for getting back to you so late, probably too late. It might be that the items of your test are coded in opposite directions if you have positive and negative statements. In any case, the error message points to a problem with the data not with JASP. In newer versions of JASP, you will be able to at least estimate coefficient alpha for that data set. I will close this for now, feel free to reopen if your issue has not been addressed sufficiently.
