### ISSUE TITLE
JASP crashed

### ISSUE THREAD

**Issue by socialistscholar** [jasp-stats/jasp-issues#1318]
* JASP version: 0.14.1
* OS name and version: macOS 10.16

* Analysis: Analysis file wouldn't load.
* Bug description:
* Expected behaviour:

#### Steps to reproduce:

-----------------------------------------------------------------------

### Debug information:
**Engine # 0** process *crashed* and it's state is *initializing*.
**Engine # 1** process *does not exist (anymore)* and it's state is *initializing*.
**Engine # 2** process *does not exist (anymore)* and it's state is *initializing*.
**Engine # 3** process *does not exist (anymore)* and it's state is *initializing*.

[Commit used](https://github.com/jasp-stats/jasp-desktop/commit/f2cb223fef6b15089fd6e9da54825d370c1ece57)

**Comment by boutinb** [comment]
Hi @socialistscholar Do you load a big datafile? Would it be possible to share this datafile? And also could you send us the log files: https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/user-guide/logging-howto.md ?
