### ISSUE TITLE
The engine crashed while trying to run this analysis. 

### ISSUE THREAD

**Issue by Elendil77** [jasp-stats/jasp-issues#1320]
![image](https://user-images.githubusercontent.com/85206136/120412069-2192dd00-c313-11eb-90dd-483e293d07fc.png)* JASP version: 0.41.1

* OS name and version: MacOS Catalina
* Bug description: Jasp will not provide descriptive stats for a certain data set. 
* Expected behaviour: Descriptive stats being provided. 

#### Steps to reproduce:
1. Go to '...' Jasp, with this data set. (I for some reason cannot find a way to attach or link to this.) 
2. Click on '....' Descriptive stats
3. See error

![image](https://user-images.githubusercontent.com/85206136/120412069-2192dd00-c313-11eb-90dd-483e293d07fc.png)

**Comment by boutinb** [comment]
Hi @Elendil77 Does this happen only for some dataset? You can send us a dataset or a JASP file if you first zip it, and then drag & drop in GitHub.

**Comment by Elendil77** [comment]
Hey,
Yeah, it was specifically this dataset. I gave Jasp a spin using a different data set and it worked ok. Unfortunately the one that won’t work is the dataset for my midterm for my research methods class.

**Comment by boutinb** [comment]
Hi @Elendil77 How big is your dataset? Can you share it with us?

**Comment by journalofarthroplasty** [comment]
metoo

**Comment by Elendil77** [comment]
absolutely- I am sorry I just saw this.
 Research Methods Midterm(excel).csv
<https://drive.google.com/file/d/1dGjFJoFTT5HNHRWGHn91OOzcwh3pxE1B/view?usp=drive_web>

**Comment by vandenman** [comment]
Hi @Elendil77 it looks like I don't have access to that link. I've requested access with my gmail account and you should have received an email about that now. Also, would it be alright if I reupload the file here as a zip so that my colleagues can also access it? Note that you can always upload any file on GitHub as long as it's a zip file.

**Comment by Elendil77** [comment]
I'm sorry it didn't give you access. I've given it now. Absolutely you can
reupload it as a zip. I don't know how to do that or I would have done it
myself.

**Comment by vandenman** [comment]
No worries!

@boutinb here is the zip file: [Research Methods Midterm(excel).zip](https://github.com/jasp-stats/jasp-issues/files/6695148/Research.Methods.Midterm.excel.zip)

**Comment by boutinb** [comment]
OK, I can reproduce the error now...

**Comment by boutinb** [comment]
[Research Methods Midterm(excel) copy.csv.zip](https://github.com/jasp-stats/jasp-issues/files/6702355/Research.Methods.Midterm.excel.copy.csv.zip)
@Elendil77 Your file had 100000 lines of empty cells. I have removed them (cf zip file), and it works now.
