### ISSUE TITLE
Saving R code within a .jasp file

### ISSUE THREAD

**Issue by kylebarrentine** [jasp-stats/jasp-issues#1322]
* Enhancement: Saving R objects within a .jasp file. Would reduce the amount of redundant custom coding needed inside of R each time a user opens a .jasp file. Additionally, JASP could automatically print summaries of any saved objects within R upon opening a .jasp file. 
* Purpose: Currently, when testing models within base R on the JASP interface, your R code is not saved alongside the other JASP inputs,  as the R objects do not save within the .jasp file. Allowing users to save R objects within JASP would increase the efficacy of the R interface within JASP and reduce the amount of redundant code needed.
* Use-case: When writing custom R code within JASP, for instance when testing for interactions within regressions, saving these objects within JASP would save time, and the immediate summaries printed upon opening the file would give the user a complete understanding of what R objects are saved within the JASP, no matter how long the file has lain dormant.

**Comment by boutinb** [comment]
@kylebarrentine This is a project we are working on, hopefully there will be a version this year with such possibility. But maybe can @TimKDJ tell more about it.

**Comment by juliuspf** [comment]
@kylebarrentine, thanks for the request. As @boutinb already pointed out, there is a JASP version coming up that allows to display and copy all R code associated with an analysis, so it can be replicated inside R. I hope that solves your issue.

**Comment by Kucharssim** [comment]
Re-reading this request, I am not sure whether the upcoming R syntax mode really solves the current issue; it appears to me that @kylebarrentine asks us to save the objects that were created in the "R in JASP" window. This is unrelated to the R syntax though, isn't it?

**Comment by juliuspf** [comment]
Ah. Now I get it. That is indeed unrelated. But is that something we will implement?

**Comment by Kucharssim** [comment]
Perhaps @JorisGoosen can give an opinion?

**Comment by JorisGoosen** [comment]
I understand what @kylebarrentine wants, but couldnt he just store files through `save()` or `saveRDS()` and reload it?

The R-syntax window is really quite separate from the jasp-files, so im not really sure how that would be sensibly stored.
Not to mention the incredible potential for abuse as you could then store basically anything in a JASP file and get the user to run it...

So Im closing this
