### ISSUE TITLE
Phi is always positive

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#1325]
If one goes with this formula 
![grafik](https://user-images.githubusercontent.com/4428185/121182811-bcd00900-c863-11eb-8735-b5fa132eea72.png)

representing this table
![grafik](https://user-images.githubusercontent.com/4428185/121182904-cfe2d900-c863-11eb-99e8-3a7e796a328c.png)

then Phi can be negative. 
I always get only positive values of Phi with JASP. Most likeley because the formula JASP uses to calculate Phi is based on Chi2.
Would be nice, if we could switch to the above formula to get negative Phi where possible. Interpretation is way easier then.

**Comment by EJWagenmakers** [comment]
Yes, definitely, it should be allowed to be negative.

**Comment by tomtomme** [comment]
still broken in JASP 0.15 beta 20.9.2021 (flatpak linux build)

**Comment by EJWagenmakers** [comment]
This is hot-fix worthy imo
