### ISSUE TITLE
Calculate Phi for 2xX tables too

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#1326]
Currently Phi is only calculated for 2x2 tables in JASP. 
However it is possible to calculate it for 2xX tables too. 
It gives the same result as Cramers V, sure, so it seems superfluous. But its always hard to tell the students, whats possible and sensible, and then using some software to tell them, that the software thinks different for no apparent reason.

If Phi is superflous for 2xX tables it should also be scratched for 2x2 tables. That would be consistent / logical at least. But I would prefer the first solution.

**Comment by tomtomme** [comment]
still broken in JASP 0.15 beta 20.9.2021 (flatpak linux build)

**Comment by tomtomme** [comment]
still valid for JASP 0.16

**Comment by tomtomme** [comment]
still valid for JASP 0.16.3 - just a note, to keep this alive

**Comment by Kucharssim** [comment]
Thanks for following this up, it slipped my attention. I added it to the next release, so I will look into it by then!

**Comment by tomtomme** [comment]
Nice. Maybe its also possible to include the sign for Phi. For 2x2 tables Phi can be negative. At least when dummy-coded.

**Comment by tomtomme** [comment]
Just as a reminder: negative Phi is implemented, but Phi for 2xX tables not yet.

**Comment by Kucharssim** [comment]
We will need to push this one more release further, sorry about that!

**Comment by tomtomme** [comment]
still valid for JASP 0.16.4 - just a note, to keep this alive

**Comment by tomtomme** [comment]
still valid for JASP 0.17

**Comment by tomtomme** [comment]
Still valid for 0.18.1.

**Comment by tomtomme** [comment]
Closing as duplicate of https://github.com/jasp-stats/jasp-issues/issues/1364
All missing correlation stuff now gathered there.
