### ISSUE TITLE
Flexplot Error with 3 categorial variables, one paneled

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#1327]
repreoducible bug in visual modeling => flexplot (jasp 0.14.1 win10 and 0.14.3 flatpak linux)

If all 3 variables are nominal or ordinal in flexplot and one of the 3 is paneled I get this:
<img width="802" alt="Screenshot 2021-06-08 143930" src="https://user-images.githubusercontent.com/4428185/121186632-98762b80-c867-11eb-8a83-d962fda3d251.png">

If the same dependend variable is switched to scale everything works:
<img width="967" alt="Screenshot 2021-06-08 143827" src="https://user-images.githubusercontent.com/4428185/121186713-aa57ce80-c867-11eb-85ca-13c2633833da.png">

Stack trace
```analysis(jaspResults = jaspResults, dataset = dataset, options = options)

flexplot:::flexplot_jasp2(jaspResults, dataset, options)

.flexPlotRes(jaspResults, formula, dataset, options, ready)

flexplot(formula, data = dataset, method = linetype, se = options$confidence, alpha = options$alpha, ghost.line = ghost, suppress_smooth = suppress_smooth, spread = whiskers[[options$intervals]], jitter = jitter)

with(varprep, flexplot_errors(variables = variables, data = data, method = method, axis = axis))

with.default(varprep, flexplot_errors(variables = variables, data = data, method = method, axis = axis))

eval(substitute(expr), data, enclos = parent.frame())

eval(substitute(expr), data, enclos = parent.frame())

flexplot_errors(variables = variables, data = data, method = method, axis = axis)

stop(paste0('Ru oh! Somebody done made a mistake! Looks like you either spelled something wrong, or included a variable not in your dataset! Have you considered spellcheck? (Oh, btw, it was the variable(s) ', paste0(not.there, collapse = ','), ' that caused a problem'))```

**Comment by boutinb** [comment]
@dustinfife Could you have a look at this issue?

**Comment by dustinfife** [comment]
Sorry for the delayed response. There is an error in how flexplot is handling things, but the user shouldn't be able to plot three categorical variables. I'll work on the error message. In the meantiem, Bruno, is there an easy way to specify in the qml that you can't have more than two categorical variables when the outcome is categorical?

**Comment by boutinb** [comment]
> Sorry for the delayed response. There is an error in how flexplot is handling things, but the user shouldn't be able to plot three categorical variables. I'll work on the error message. In the meantiem, Bruno, is there an easy way to specify in the qml that you can't have more than two categorical variables when the outcome is categorical?

I thought it was possible, but by testing it, I see that it cannot... The allowedColumns property is not as dynamic as it should be. I'll see if there is a simple way to fix this.

**Comment by tomtomme** [comment]
still broken in JASP 0.15 beta 20.9.2021 (flatpak linux build)

**Comment by tomtomme** [comment]
And as you can see here, it used to work just fine. I can still open the jasp file containing this in the new beta. I do not get why you two say it should not work to begin with.

<img width="1357" alt="grafik" src="https://user-images.githubusercontent.com/4428185/134141728-8350220e-53b1-4a8a-bd43-b92cf29f87e0.png">

**Comment by tomtomme** [comment]
Still valid for JASP 0.16

**Comment by tomtomme** [comment]
Still valid for JASP 0.16.3 - just a note, to keep this alive

**Comment by dustinfife** [comment]
[This commit](https://github.com/dustinfife/flexplot/commit/fa48ba67dc02590d89abb3a0ead2bbcfadec91a5) fixes this problem.

**Comment by tomtomme** [comment]
This is solved now on linux with the new build of flexplot which just arrived in the bioarch repo. As this should be released with stable on win and macos early next year I will close this already.
Thank you again @dustinfife for your hard work on flexplot. It helps a ton with teaching stats.
