### ISSUE TITLE
Add the possibility of a qualitative variable in linear regression

### ISSUE THREAD

**Issue by victiane** [jasp-stats/jasp-issues#1328]
* Enhancement: it would be great to be able to put in qualitative variables in linear regression (for now from what I could do one can only put quantitative variables)
* Purpose: do social sciences regression
-

**Comment by Kucharssim** [comment]
Dear @victiane,

thank you for the request. If I understand it correctly, you would like to use categorical variables as predictors in linear regression. This is already implemented and will be part of the next release of JASP. 

Please reopen this issue in case I misunderstood your request, or if you want to follow up with something more specific regarding this request. Thank you.
