### ISSUE TITLE
Resquest for JASP ANCOVA code

### ISSUE THREAD

**Issue by Chuziliang** [jasp-stats/jasp-issues#1331]
* JASP version: 0.14.1

* OS name and version: Window 10
* Analysis: 3 factors ANCOVA
* Bug description: Hi, I am doing a 3 factors ANCOVA analysis using JASP( 3 factors, and 1 covariance), I find the simple main effect result of JASP was not identicial to SPSS. So, can you provide me the code or the formula, how JASP doing ANCOVA. Thank you!

**Comment by EJWagenmakers** [comment]
@JTPetter: Did you discuss this case in your validation report?

**Comment by Chuziliang** [comment]
> @JTPetter: Did you discuss this case in your validation report?

Thank you for your reply! 
No, I didn't.
I just used JASP to analyze my data, and found the conflict result of simple main effect by coincidence(interestingly, the statistic results of main effect and interaction are the same). So I am interested in how JASP calculate the sum of square when doing multi factor ANCOVA, maybe we can find something in the code or the formula.

**Comment by EJWagenmakers** [comment]
Hi Chuziliang. My comment was meant for Jonas Petter, who did an extensive comparison between SPSS, R, Minitab, and JASP. See https://jasp-stats.org/2021/02/03/the-jasp-verification-project/

**Comment by JTPetter** [comment]
@Chuziliang Hello! Would you mind sharing your data set and/or JASP-file, so I could try and replicate the issue?
