### ISSUE TITLE
Wrong association of JASP file to JASP app

### ISSUE THREAD

**Issue by hynekcigler** [jasp-stats/jasp-issues#1332]
* JASP version: 0.14.1

* OS name and version: Windows 10
* Czech local (but the same happens with Spanish as @romanogino reported here: #1315).
* This is follow-up of previous discussion started here #1315 .

JASP won't open the JASP file if double clicked. If selected "Open with", an association seems to be strange (see the screenshot). If I select JASP application using "Open with", nothing happens (JASP does not start and a strange association remains to be the same). 
![image](https://user-images.githubusercontent.com/20371612/121496387-b4e6a500-c9da-11eb-96fc-8ad86b42afdc.png)

If I open the JASP, I can easily use Open command to open any JASP file (no bug here, JASP works fine).

**Comment by JorisGoosen** [comment]
Is it possible to upload the file here?

If not, I am interested in the name and location of the file mostly.

**Comment by romanogino** [comment]
Hi
I have been testing my JASP files with English letters and works correctly. I removed spaces, accents and others details from the Spanish language, set everything to English language and it can open the files. My new hypothesis is that it could be the language applied to name the files.
Best regards.
r.

**Comment by hynekcigler** [comment]
@romanogino you are probably right, great! :-) 
Anyway, here are two files, both are located in c:\Users\Hynek\Dropbox\MU\_kos\jasp-issue\:

1. Original file with the issue: [vaha-original.jasp](https://www.dropbox.com/s/me23w2uhpow3qq1/vaha-original.jasp?dl=0).
2. New file without the issue: [vaha-en.jasp](https://www.dropbox.com/s/6ha2dzqrpzguhhw/vaha-en.jasp?dl=0). 

Basically, both files are the same, but I changed Czech labels of the first variable ("muž" and "žena") to English without local characters ("man" and "women"). This was the only change (variables still have the same names).

**Comment by JorisGoosen** [comment]
Good detective work both ^^

@romanogino so you say JASP does not work when you have spanish characters in the name of the file?

@hynekcigler I'll have to have a look at your files later, but it sounds like for you the changes are within the file?

**Comment by romanogino** [comment]
Hi
The problem was found in the file name., not inside the file.
![2021-06-10_162403](https://user-images.githubusercontent.com/1270242/121599317-7bc52980-ca08-11eb-8ab4-19c54696f493.jpg)

**Comment by hynekcigler** [comment]
@JorisGoosen My problem was inside the file, the value labels of the first variable "pohlavi" (sex). I hate these local languages issues, it happens all the time :-/

**Comment by JorisGoosen** [comment]
@hynekcigler yeah sadly enough they do. Windosw also makes it extra hard sadly enough. All these things are very easy on Linux & Mac.

But, it *can* of course work on windows, I just need to find out what went wrong here. In fact I just created a new testversion of JASP, quite unstable as we are still testing lot's of things and even changing stuff.

But this one should handle certain imports better, maybe you or @romanogino could give it a spin?
I would caution against using it much though, see the disclaimer at https://static.jasp-stats.org/Nightlies/

Anyway, the testversion is here as [an installer](https://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-csvEncoding-be03ff5b5f0b0854b88543c285824143dc54bf72.msi) or [a zip](https://static.jasp-stats.org/Nightlies/WindowsZip/JASP-nightly-csvEncoding-be03ff5b5f0b0854b88543c285824143dc54bf72.zip).

The zip takes a little while to get going the first time you start it.

**Comment by romanogino** [comment]
I had the problem of not being able to open the JASP files when I used strange letters or symbols in the variables, but it did not affect the association with the program. You could open the file and then the error would appear. On the other hand, when I used strange letters or symbols in the file name, the association for JASP does not work there.
I'm going to download the night version and try it out. I will comment on any bugs, with the intention of improving the quality of the software.
Best regards.
r.

**Comment by JorisGoosen** [comment]
I've been testing it here, changing my computer's locale all through europe and parts of asia. And none of the problems you (and others) describe seem to pop up now.

I will close this issue now, but I would still be grateful if (preferably) both of you could still test the special version for me. That way I can be sure that the next version of JASP will work for you.

If it is still broken feel free to reopen this issue!

**Comment by hynekcigler** [comment]
@JorisGoosen  Hi, unfortunately, it did not work on my PC. The behavior is the same with dev version as with the stable version. Anyway, I found a new and highly related bug, which I have not discovered before. I cannot open any file with local characters (e.g. vaha-original.jasp above) using JASP Open menu, if any other JASP file is already open. However, I can still open any file without local characters (i.e., vaha-en.jasp above). 

Yah, Windows has several difficulties. On the other hand, many other are easier with them compared to iOS/Linux :)

**Comment by romanogino** [comment]
Hello
Unfortunately, JASP 0.15 does not open files with accents (e.g. perception.jasp) but without the accent (e.g. perception.jasp) there is no problem. For now, it is best to use English words.  
On the other hand, this new version brings a lot of improvements.
Best regards.

**Comment by JorisGoosen** [comment]
>  Hi, unfortunately, it did not work on my PC. The behavior is the same with dev version as with the stable version. Anyway, I found a new and highly related bug, which I have not discovered before. I cannot open any file with local characters (e.g. vaha-original.jasp above) using JASP Open menu, if any other JASP file is already open. However, I can still open any file without local characters (i.e., vaha-en.jasp above).

Aah too bad, but that is an interesting find, I'll check it out.

> Unfortunately, JASP 0.15 does not open files with accents (e.g. perception.jasp) but without the accent (e.g. perception.jasp) there is no problem. For now, it is best to use English words.

Well, there is also the possibility to set windows into utf-8 mode and it could solve all these problems. But it is only supported on Win10 and hasn't been extensively tested.

Although I think it would be easier for everyone if I can just manage to get JASP and windows to cooperate with regards to different locales...
