### ISSUE TITLE
linear regression error

### ISSUE THREAD

**Issue by narcilili** [jasp-stats/jasp-issues#1333]
* JASP version: 0.14.1

* OS name and version: windows 10
* Analysis: simple linear regression of natural log transformed number of eggs on year
* Bug description: error message appears as shown in the snippet below
![egssjasp](https://user-images.githubusercontent.com/61888367/121605433-f7fa5400-ca7e-11eb-972e-15ea599b0a0f.JPG)

* Expected behaviour: the slope should be 0.223144

#### Steps to reproduce:
1. Go to ' regression'
2. Click on 'classical linear regression'
3. Scroll down to 'drag year variable into covariate box then drag lneggs variable into dependent variable box

'

**Comment by vandenman** [comment]
The problem is that the variables `Ineggs` and `year` have a correlation of 1. Judging from their names and the data in the screenshot, it sounds like `Ineggs` is a linear function of `eggs`. You probably want to use only one of these two variables.

**Comment by narcilili** [comment]
hello vandenman,
thank you for your interest. yes, i spotted that right away. but, i was hoping that jasp would be able to estimate the intercept and slope even if the correlation coefficient is equal to 1. i tried using excel and there was no problem.
cheers

**Comment by vandenman** [comment]
@narcilili the problem with that is twofold:

1. If excel gives you a slope without any warnings then that is dubious as best and incorrect at worst. There is no single "slope" to be estimated. In fact, there are an infinite amount of possible pairs of values for the two slopes that are all statistically indistinguishable. 

2. If you would do this in R (see below), then one of the two correlated predictors is simply ignored (the estimate is NA). Hence the easiest solution is to omit one of your two correlated predictors, and then you would get meaningful output. Rather than providing possibly misleading or incorrect output in JASP, we show an error message that there is something wrong with the data that you should resolve before the analyses can produce meaningful output. In your example, you can omit either `Ineggs` or `eggs` from the data and the error message should disappear.

``` r
df <- data.frame(
  y  = rnorm(10),
  x1 = 1:10,
  x2 = 1:10 # identical to x1
)
fit <- lm(y ~ x1 + x2, data = df)
summary(fit)
#> 
#> Call:
#> lm(formula = y ~ x1 + x2, data = df)
#> 
#> Residuals:
#>     Min      1Q  Median      3Q     Max 
#> -1.1163 -0.5388 -0.0126  0.2966  1.2297 
#> 
#> Coefficients: (1 not defined because of singularities)
#>             Estimate Std. Error t value Pr(>|t|)
#> (Intercept) -0.93631    0.54429  -1.720    0.124
#> x1           0.07798    0.08772   0.889    0.400
#> x2                NA         NA      NA       NA
#> 
#> Residual standard error: 0.7968 on 8 degrees of freedom
#> Multiple R-squared:  0.0899, Adjusted R-squared:  -0.02386 
#> F-statistic: 0.7902 on 1 and 8 DF,  p-value: 0.4
```

<sup>Created on 2021-06-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by narcilili** [comment]
hello vandenman,
 i am sorry if i did not make it clear that i have only one predictor variable--year--and one response or dependent variable--lneggs. the example you gave is quite different because it has two predictor variables. thank you for your continuing interest.
cheers

**Comment by vandenman** [comment]
@narcilili no worries, I guess I misunderstood. 

To avoid any further misunderstandings, could you show me the analysis options you used? E.g., a screenshot like this or a list of options you selected:

![image](https://user-images.githubusercontent.com/21319932/121855174-57f93080-ccf3-11eb-8032-068dac404b70.png)

In particular, the stuff under `Model` is quite relevant.

**Comment by narcilili** [comment]
![jaspregressionerror](https://user-images.githubusercontent.com/61888367/121868294-649d7900-cd33-11eb-820e-630056986ed9.JPG)
hello vandenman,
here is a snippet of showing where i placed the predictor and response variables. thanks you,
cheers

**Comment by vandenman** [comment]
@narcilili that makes sense, I've fixed this in the linked pull request. The output in the next version of JASP should look like this:

![image](https://user-images.githubusercontent.com/21319932/121901389-a4aa2f00-cd26-11eb-8023-8753ed617c73.png)

**Comment by narcilili** [comment]
hello vandenman,
i tried using R and this is what i got
Call:
lm(formula = lneggs ~ year, data = lneggs)

Coefficients:
(Intercept)         year  
     4.8520       0.2231  

> fit<-lm(formula = lneggs ~ year, data = lneggs)
> summary(fit)

Residuals:
       Min         1Q     Median         3Q        Max 
-4.444e-10 -2.444e-10 -4.444e-11  2.556e-10  4.555e-10 

Coefficients:
             Estimate Std. Error   t value Pr(>|t|)    
(Intercept) 4.852e+00  2.490e-10 1.949e+10   <2e-16 ***
year        2.231e-01  4.425e-11 5.043e+09   <2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 3.427e-10 on 7 degrees of freedom
Multiple R-squared:      1,	Adjusted R-squared:      1 
F-statistic: 2.543e+19 on 1 and 7 DF,  p-value: < 2.2e-16

which is quite different from your latest comment. thank you for your continuing interest.
cheers

**Comment by narcilili** [comment]
hello vandenman,
i tried using R and this is what i got
> fit<-lm(formula = lneggs ~ year, data = lneggs)
> summary(fit)
Residuals:
       Min         1Q     Median         3Q        Max 
-4.444e-10 -2.444e-10 -4.444e-11  2.556e-10  4.555e-10 

Coefficients:
             Estimate            Std. Error   t value           Pr(>|t|)    
(Intercept) 4.852e+00  2.490e-10 1.949e+10   <2e-16 ***
year        2.231e-01       4.425e-11 5.043e+09   <2e-16 ***
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
Residual standard error: 3.427e-10 on 7 degrees of freedom
Multiple R-squared:      1,	Adjusted R-squared:      1 
F-statistic: 2.543e+19 on 1 and 7 DF,  p-value: < 2.2e-16

which is quite different from your latest comment. thank you for your continuing interest.
cheers

**Comment by vandenman** [comment]
Hi @narcilili

In the screenshot you posted, you regressed `year` on `Ineggs`. In the R code, however, you flipped this and regressed `Ineggs` on `year`. Note that the results are identical in terms of p-values:
``` r
df <- data.frame(
  year   = 1:9,
  Ineggs = c(5.07517, 5.29832, 5.521476, 5.7446, 5.96775, 6.19089, 6.41404, 6.63718, 6.86032)
)

summary(lm(year ~ Ineggs, data = df))
#> 
#> Call:
#> lm(formula = year ~ Ineggs, data = df)
#> 
#> Residuals:
#>        Min         1Q     Median         3Q        Max 
#> -5.846e-05 -2.440e-06 -1.544e-06  1.280e-05  2.848e-05 
#> 
#> Coefficients:
#>               Estimate Std. Error t value Pr(>|t|)    
#> (Intercept) -2.174e+01  9.846e-05 -220847   <2e-16 ***
#> Ineggs       4.481e+00  1.642e-05  272893   <2e-16 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> Residual standard error: 2.838e-05 on 7 degrees of freedom
#> Multiple R-squared:      1,  Adjusted R-squared:      1 
#> F-statistic: 7.447e+10 on 1 and 7 DF,  p-value: < 2.2e-16
summary(lm(Ineggs ~ year, data = df))
#> 
#> Call:
#> lm(formula = Ineggs ~ year, data = df)
#> 
#> Residuals:
#>        Min         1Q     Median         3Q        Max 
#> -6.356e-06 -2.856e-06  3.444e-07  5.444e-07  1.304e-05 
#> 
#> Coefficients:
#>              Estimate Std. Error t value Pr(>|t|)    
#> (Intercept) 4.852e+00  4.601e-06 1054463   <2e-16 ***
#> year        2.231e-01  8.177e-07  272893   <2e-16 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> Residual standard error: 6.334e-06 on 7 degrees of freedom
#> Multiple R-squared:      1,  Adjusted R-squared:      1 
#> F-statistic: 7.447e+10 on 1 and 7 DF,  p-value: < 2.2e-16
```

<sup>Created on 2021-06-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

In the screenshot I posted before, I regressed `year` on `Ineggs`, and you can see that the values in the estimates table (Unstandardized, standard error, and t-value) match those in `summary(lm(year ~ Ineggs, data = df))`. Whether you want `year ~ Ineggs` or `Ineggs ~ year` depends on your actual question and hypotheses of interest.

**Comment by narcilili** [comment]
hello vandenman,
you have been so helpful, thank you. but, just for the record i clearly wrote in my first comment : "Analysis: simple linear regression of natural log transformed number of eggs on year."  i hope you have a pleasant day. 
cheers
