### ISSUE TITLE
How to Connect Data Points on Boxplot with Lines?

### ISSUE THREAD

**Issue by alegra07** [jasp-stats/jasp-issues#1335]
* Enhancement: Connect Data Points on Boxplot with Lines
* Purpose: Highlight differences between paired replicates/conditions

Example from R:
![image](https://user-images.githubusercontent.com/85741791/121678728-d36e9e00-cab7-11eb-88d9-2b20ce79b238.png)

**Comment by vandenman** [comment]
Hi @alegra07 the next version of JASP will include raincloud plots like these:

![image](https://user-images.githubusercontent.com/21319932/122921942-6682c000-d363-11eb-9cf3-18c0bd3e87c9.png)

is that what you had in mind?

**Comment by juliuspf** [comment]
@alegra07, I trust that this issue has been solved? If not feel free to reopen this!
