### ISSUE TITLE
JASP quit unexpectedly after trying to open .sav

### ISSUE THREAD

**Issue by AnguloB** [jasp-stats/jasp-issues#1337]
* JASP version: 0.14.1.0 

* OS name and version: macOS 11.4 (20F71)
* Bug description: When I try to open a .sav file (e.g, https://www.europeansocialsurvey.org/data/ ) JASP quit unexpectedly (see attached file for further detail).
* Expected behaviour: To open the file. 

[report.zip](https://github.com/jasp-stats/jasp-issues/files/6646197/report.zip)

**Comment by boutinb** [comment]
Hi @AnguloB Which one did you try to load? I have tried on a Mac the EES 9 2018 SPSS file without problem.

**Comment by AnguloB** [comment]
I have tried with ESS9 - 2018  and with ESS6 - 2012. 


With 2018 I have tried about 15~20 times and I have open it once. Then try to open again and failed. 




> Hi @AnguloB Which one did you try to load? I have tried on a Mac the EES 9 2018 SPSS file without problem.

**Comment by JorisGoosen** [comment]
@AnguloB could you follow the guide at https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/user-guide/logging-howto.md and post the logs here?

That way we can see where your JASP seems to crash.

**Comment by AnguloB** [comment]
> @AnguloB could you follow the guide at https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/user-guide/logging-howto.md and post the logs here?
> 
> That way we can see where your JASP seems to crash.
The files :) 
[logs.zip](https://github.com/jasp-stats/jasp-issues/files/6653579/logs.zip)

**Comment by JorisGoosen** [comment]
Well you found the logs and all that, thank you!
But there is a slight problem: you didn't load your `sav`-file after turning logging on right?
Because I don't see anything related to loading a `sav` in any of the logs.

Maybe you could try again? Thank you :)

**Comment by AnguloB** [comment]
I have loaded it twice now (I think also before). I hope the logs are ok now. Thank you.

[Logs 2.zip](https://github.com/jasp-stats/jasp-issues/files/6655289/Logs.2.zip)

**Comment by JorisGoosen** [comment]
Thank you!

This does include it and well, yeah it does indeed crash. I can see where but to be able to fix it I will need your data-file.
Is it possible to share the entire file with me?

Otherwise I could also try it with a part of the file: I think I will need the column `livecnta` but it might be another one.
So preferably the whole file and otherwise just that column.

**Comment by AnguloB** [comment]
Yes, of course, this data is available for everybody. 
[ESS9e03_1.sav.zip](https://github.com/jasp-stats/jasp-issues/files/6655675/ESS9e03_1.sav.zip)

**Comment by JorisGoosen** [comment]
Aah I misread the first comment, but thank you for making it easier for me ^^

**Comment by JorisGoosen** [comment]
Aah, so this also works fine on my mac... Which means I will have to make a version of JASP with some more logging to be able to pinpoint the exact problem.

**Comment by boutinb** [comment]
Loading the sav file on 0.14.1 crashes for me. On 0.15 it goes really slow.... I have a look.

**Comment by JorisGoosen** [comment]
Also look at that PR, it fixes that problem. It was logging too much

**Comment by JorisGoosen** [comment]
(I think anyway)

**Comment by JorisGoosen** [comment]
@AnguloB could you try out https://static.jasp-stats.org/Nightlies/MacOS/JASP-nightly-development-3013d805aba58e62313731d810da70cba239683d.dmg 

It might work and otherwise will have way more informative logs for us.

**Comment by AnguloB** [comment]
I have installed and the problem persists (I have attached logs). 
[Logs.zip](https://github.com/jasp-stats/jasp-issues/files/6694449/Logs.zip)

**Comment by JorisGoosen** [comment]
Well, the logfile size went down at least, and I can now see sort of where it breaks for you. I'll make another version.

**Comment by JorisGoosen** [comment]
@AnguloB do you think you could give the following a spin: https://static.jasp-stats.org/Nightlies/MacOS/JASP-nightly-ariadneSpecial-f20eded03476589e73cf68f8438cf6487ea63433.dmg

Thanks for bearing with us in this bughunt!

**Comment by AnguloB** [comment]
@JorisGoosen Here my logs again.. 

[Logs.zip](https://github.com/jasp-stats/jasp-issues/files/6714220/Logs.zip)

**Comment by JorisGoosen** [comment]
Are you perhaps running an M1 macbook?

**Comment by AnguloB** [comment]
No, 2015 macbook (And also tried with 2016 Macbook but not with the nightly versions).

**Comment by JorisGoosen** [comment]
Ok good, just wanted to make sure!

**Comment by JorisGoosen** [comment]
Alright, this next version has a slightly bit more logging and hopefully also a fix, so maybe this time it will actually work.

https://static.jasp-stats.org/Nightlies/MacOS/JASP-nightly-ariadneSpecial-2f53b46afed521c5209f747f868a054997d71a82.dmg

No hurry though! I might have time to look at the logs later today (if it works I would still like to see them) but on monday is more likely.

**Comment by AnguloB** [comment]
Unfortunately, it has crashed again. Here the logs!
[Logs.zip](https://github.com/jasp-stats/jasp-issues/files/6724222/Logs.zip)

**Comment by JorisGoosen** [comment]
Ok, I do think we are getting closer, even if it doesn't feel like it, hopefully you can try out: https://static.jasp-stats.org/Nightlies/MacOS/JASP-nightly-ariadneSpecial-4193936839e2bdb48becf6ab7bbf0010677e9ab6.dmg

**Comment by AnguloB** [comment]
Not yet [Logs 2.zip](https://github.com/jasp-stats/jasp-issues/files/6731110/Logs.2.zip)

**Comment by JorisGoosen** [comment]
@AnguloB can you maybe try something else entirely, if you go to `File menu -> Preferences -> Interface` and then enable `Safe graphics mode`, does that help?

And as an aside, how much free space do you have on your harddrive?

**Comment by AnguloB** [comment]
It has also crashed :(

Right now I have 24.62 GB

**Comment by JorisGoosen** [comment]
Can you send me the crashreport?

Because it seems that JASP now stops in a different place than before... So I'm thinking that maybe it is only tangentially related to loading the .sav...

**Comment by AnguloB** [comment]
:) 
[Logs.zip](https://github.com/jasp-stats/jasp-issues/files/6734638/Logs.zip)

**Comment by JorisGoosen** [comment]
Aah I meant the thingy MacOS shows you when the app crashes ^^

**Comment by AnguloB** [comment]
[textt.zip](https://github.com/jasp-stats/jasp-issues/files/6734742/textt.zip)

**Comment by JorisGoosen** [comment]
Aah, well "luckily" the error is indeed in reading the sav file...

For my own administration:
```
Thread 4 Crashed:: QThread
0      libsystem_platform.dylib            	0x00007fff203ff552 _platform_strlen + 18
1      org.jasp-stats.jasp                      	0x0000000101f26c7c ReadStatImportColumn::readstatValueToString(readstat_value_s const&) + 108
2      org.jasp-stats.jasp                      	0x0000000101f27f47 ReadStatImportDataSet::setLabelsToColumns() + 423
3      org.jasp-stats.jasp                      	0x0000000101f2a13d ReadStatImporter::loadFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, boost::function<void (int)>) + 1357
```

**Comment by JorisGoosen** [comment]
Hello @AnguloB 

I've been thinking and tinkering and I think I might have a version of JASP that can load the file: https://static.jasp-stats.org/Nightlies/MacOS/JASP-nightly-ariadneSpecial-8bedf81ff79c507b7a687bd43719f1e3f74ae379.dmg

I personally have a weird crash right now if I scroll right in the data **and** have JASP fullscreen, with the sav file from here. So don't put it fullscreen when trying it out.

Although it would be informative for me to know whether it crashes for you when doing that.

But of course, I mostly hope that the file can now be loaded without issue!

**Comment by AnguloB** [comment]
Wow! I can open it now and do some descriptive statistics. In my computer works great in full screen. Thank you. Do you plan to incorporate the fix in future JASP versions?

I don’t know if it is related but recently I have also experienced a similar crash with a csv (I can’t attach the file because is sensitive information): in this case this version-fix doesn’t solve that problem.

**Comment by JorisGoosen** [comment]
Awesome!

Yeah the fix will be in the upcoming version of course, which we hope to have out by beginning september at the latest.

About the csv, it won't be related to the specific issue here because the problem was in the particular code for reading spss(/sas/stata) files. With csv it might be related to having "strange" characters (not really strange, just from an american perspective) although I would be surprised if that leads to a crash. I'd suggest opening an issue, although it will be hard to debug it if I don't have access to the file in question.

And I would suggest using the latest working version you to save the file as a JASP-file and then loading it in 0.14.1. That way you can be surer that you will be able to load it properly in the upcoming release.
