### ISSUE TITLE
Reproducing JASP network in R 

### ISSUE THREAD

**Issue by MyrtheV** [jasp-stats/jasp-issues#1338]
* JASP version: 0.14.1

* OS name and version: MacOS Catalina 
* Analysis: Network analysis 
* Bug description: I am trying to reproduce a JASP network in R, but I am unable to replicate the network. Instead I get the error message that the "Correlation matrix is not positive definite". One suggestion made [here](https://github.com/SachaEpskamp/bootnet/issues/40) is that instead of using the "cor_auto" one should use spearman correlation. This indeed solves the error in R, however, the results are different from the network in JASP. The results are the same as the results following from the spearman correlation in JASP. My question is, how is it possible that the network is working in JASP but returns an error in R? Shouldn't the error also appear in JASP? 
* Expected behaviour: Error message in JASP. 

#### Steps to reproduce:
I attached the JASP file and data. 
In R, I used the following code to estimate the network (with this code I could reproduce three other networks estimated the same way in JASP): 
`estimateNetwork(data3, default = "EBICglasso", threshold = FALSE, corMethod = "cor_auto", missing = "pairwise", sampleSize = "pairwise_maximum")`

Let me know if you need more information. Thanks! 

[data3.csv](https://github.com/jasp-stats/jasp-issues/files/6647731/data3.csv)
[noPD-2.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/6647739/noPD-2.jasp.zip)

**Comment by vandenman** [comment]
If I refresh the file on development I get the same error message:

![image](https://user-images.githubusercontent.com/21319932/121882540-f5af2880-cd10-11eb-9b3d-d5672a0530e7.png)

The latest release uses an older version of bootnet (version 1.2.4, the current CRAN version is 1.4.3.), so if you want to replicate the results you may need to downgrade bootnet.

**Comment by MyrtheV** [comment]
Ah okay, good to know! Thanks, this solves my issue.
