### ISSUE TITLE
Total number of edges 

### ISSUE THREAD

**Issue by MyrtheV** [jasp-stats/jasp-issues#1339]
* JASP version: 0.14.1 

* OS name and version: MacOS Catalina 
* Analysis: Network analysis 
* Bug description: I was wondering if 112 is supposed to represent to the total number of edges in the table. I don't think this is correct. With 16 nodes this should be 120 (16 * 15 / 2). This (120) is also what R returns. 
<img width="503" alt="Schermafbeelding 2021-06-14 om 13 49 59" src="https://user-images.githubusercontent.com/39378038/121888142-eaabc680-cd17-11eb-8fb9-a35472564be1.png">

**Comment by vandenman** [comment]
yeah there are some parenthesis missing, `nVar * (nVar-1L) %/% 2` should be `(nVar * (nVar-1L)) %/% 2`
