### ISSUE TITLE
Translations: Binary files are trailing behind `.po` files...

### ISSUE THREAD

**Issue by JoKeyser** [jasp-stats/jasp-issues#1340]
Hi @boutinb and @vandenman ,

I noticed that the binary translation files are trailing behind their `.po` files.
For example, in the Descriptives module, there are recent changes in the [`.po` files](https://github.com/jasp-stats/jaspDescriptives/tree/master/po) from Weblate, but the resulting [`.qm` files](https://github.com/jasp-stats/jaspDescriptives/tree/master/inst/qml/translations) are not yet updated.
It would be great if these files could be (automatically) synched up more regularly.

**Comment by vandenman** [comment]
@boutinb , I guess we can do this automatically with GitHub actions?

**Comment by boutinb** [comment]
It's updated each Saturday night automatically. So the nightly after the Saturday should get the translations. If you want it one earlier, you can ask me. We can also decide to trigger the actions more often.

**Comment by JoKeyser** [comment]
@boutinb , I guess 1x per week would be fine, but it seems to me that it wasn't updated in the last month, e.g. see https://github.com/jasp-stats/jaspDescriptives/commits/master/inst/qml/translations

**Comment by JoKeyser** [comment]
@boutinb  , I believe I found at least one problem with the [current version of generateLanguageFiles.sh#L55](https://github.com/jasp-stats/jasp-actions/blob/821ca06de3abc9041eadf15b5010a1611d123e29/translations/generateLanguageFiles.sh#L55), where no QMFILE variable is defined for most modules (other than jasp-desktop).
I attempted a fix in https://github.com/jasp-stats/jasp-actions/pull/8

**Comment by JoKeyser** [comment]
@boutinb , thanks for merging, I'm glad my hunch about the `.qm` files was correct.

One more question/doubt remains in my head: Are the `.mo` files also taken care of? I'm not sure if they are (supposed to be) handled with the same script? (I don't have time this week to really check this.)

**Comment by boutinb** [comment]
It's a good point... I'll have a look

**Comment by boutinb** [comment]
Yes there were still some problems. I have just solved them.
