### ISSUE TITLE
Problem loading known issues error

### ISSUE THREAD

**Issue by rosid-uhm** [jasp-stats/jasp-issues#1342]
* JASP version: 0.14.1

* OS name and version: Windows 10
* Analysis: idle
* Bug description: Error window
* Expected behaviour: 

I started facing this around 2 days ago and it keep coming everytime i run JASP.
Even when it's idle, it's show up.

![Screenshot 2021-06-15 185159](https://user-images.githubusercontent.com/84888311/122049094-39d32380-ce0c-11eb-8e43-13890d9b07e9.png)

also provided some logs,
[Logs.zip](https://github.com/jasp-stats/jasp-issues/files/6655420/Logs.zip)

Thanks!

**Comment by vandenman** [comment]
Nothing to worry about, it means that jasp could not access the server with the list of known issues. This will be clearer in the upcoming version.
