### ISSUE TITLE
Bayesian rmANOVA terminates unexpectedly

### ISSUE THREAD

**Issue by SteffiPeykarjou** [jasp-stats/jasp-issues#1346]
Hi guys,

I am trying to run a Bayesian Repeated Measures ANOVA, a regular analysis that I am using a lot. For some reason, I keep getting an error running the analysis with the attached dataset (never had that before). I tried Jasp versions 0.13.1 and 0.14 on Windows 10 PCs.

I am trying to use two between-subjects factors (cond, median-split (Anzahl Trials Fam), and structure the input using two within-subjects factors (roi + ele: o - Iz, O1, O2, Oz, po: P3, P4, PO9, PO10). The analysis runs very long, > 1 hr, and then terminates suddenly with the error message you find below.

I'd appreciate any help a lot!
Thank you,
Steffi

![grafik](https://user-images.githubusercontent.com/50366502/123782639-d51ccc00-d8d5-11eb-96c1-9f03222d640b.png)
[](url)

**Comment by SteffiPeykarjou** [comment]
[Hip_FPVS+Hip_Fam_mediansplit_NumTrialsFam.txt](https://github.com/jasp-stats/jasp-issues/files/6732695/Hip_FPVS%2BHip_Fam_mediansplit_NumTrialsFam.txt)

**Comment by vandenman** [comment]
Hi @SteffiPeykarjou, thanks for the report!

Could you maybe describe the structure of the `Repeated Measures Factors` a bit more? In particular I'm unsure what I should enter here to replicate the problem:
![image](https://user-images.githubusercontent.com/21319932/124487281-d0ad5300-ddae-11eb-9acf-b9e012f3e1d4.png)

You can also upload the .jasp file here directly, if you zip it first.

One thing you should consider is that JASP by default adds all interactions between `Between Subject Factors` and `Repeated Measures Factors`. If you open the tab `Model` you'll see this:
![image](https://user-images.githubusercontent.com/21319932/124487464-0baf8680-ddaf-11eb-86e3-0307ec95e8a1.png)

Here, the highlighted lines contain interaction effects. By default all interactions are considered, which includes the 4-way interaction between `ele`, `roi`, `cond`, and `median_split`.


This is probably the reason why it takes so long to compute. What I would do is:
0. Enter the `Between Subject Factors` but *not* the `Repeated Measures Cells`.
1. Select all `Model Terms` (<kbd>Ctrl</kbd> + <kbd>A</kbd>).
2. Click on the leftward arrow:
![image](https://user-images.githubusercontent.com/21319932/124487927-8b3d5580-ddaf-11eb-8c1e-ea98eb1be662.png)
3. Now there are no models specified.
4. Manually enter the models you want to consider.
    1. You can enter main effects by selecting individual components and dragging these from `Components` to `Model Terms`.
    2. You can enter interaction and main effects by selecting multiple components (hold <kbd>Ctrl</kbd> and left-click on multiple components) and then drag these from `Components` to `Model Terms`.
5. If you have no idea what models to consider, I'd recommend entering all main effects, and the interaction effect between `cond` and `median_split`. 

This way, there are fewer models considered and the analysis should finish faster.

Let me know if this helped!

**Comment by SteffiPeykarjou** [comment]
Hi @vandenman,
thanks a lot for your help, I really appreciate it!
I tried with the reduced model as you suggested, which gives me a new error. I think I made an error with my columns, but can't figure out what it was. I am attaching the original analysis and the adapted one, that's probably the easiest way. Thanks for any further suggestions!
Best
Steffi
[Hip_FPVS+Hip_Fam_mediansplit_NumTrialsFam_newerror.zip](https://github.com/jasp-stats/jasp-issues/files/6766008/Hip_FPVS%2BHip_Fam_mediansplit_NumTrialsFam_newerror.zip)
[Hip_FPVS+Hip_Fam_mediansplit_NumTrialsFam.zip](https://github.com/jasp-stats/jasp-issues/files/6766009/Hip_FPVS%2BHip_Fam_mediansplit_NumTrialsFam.zip)

**Comment by tomtomme** [comment]
@SteffiPeykarjou 
Both files run the analysis just fine with jasp 0.18.3
For the file named "newerror" however, I first had to remove the empty rows and columns. This is afaik a known issue with RM (B)ANOVA. It can't handle missing data very well yet. 
Advanced Missing value handling is on the horizon for JASP 0.19 however. So lets cross fingers for that to materialize :D

If this is not solved on your side, feel free to reopen.
