### ISSUE TITLE
.TXT file closes JASP instead of JASP opening .TXT file

### ISSUE THREAD

**Issue by WimRoest** [jasp-stats/jasp-issues#1347]
* JASP version: 0.14.1.0
 Windows 10
* OS name and version:
* Analysis: 
* Bug description: Downloaded JASP last week and opened one datafile with no problem. It opened and I could analyze data. On opening the second data file today (A downloaded Google form datafile in CSV format). First saved file as _.txt (Tab delimited)_ and tried to open file but without success. JASP does not open the file and closes automatically. 
* Expected behaviour: Expect JASP to open file as it is in suggested format.
*

**Comment by boutinb** [comment]
Hi @WimRoest Could you tell us which OS (Wndows, Mac, Linux) and which OS version you use? Cold you also give this file?

**Comment by WimRoest** [comment]
Windows 10 Pro, version 2004, OS build 19041.1052

File attached.
[Technology Readiness and Acceptance Survey.txt](https://github.com/jasp-stats/jasp-issues/files/6733860/Technology.Readiness.and.Acceptance.Survey.txt)

**Comment by WimRoest** [comment]
@boutinb 
I think I have the solution to this issue. This is what I did and it opened perfectly: (1) I first opened a version of the data file directly from the Google form as a Google "Sheets". This gave me all the columns and contents for each cell in the correct place. (2) Then I downloaded into Excel format from Sheets as an Excel spreadsheet; (3) Then I saved to folder in .TXT (Tab Delimited) format. (4) It then opened perfectly in JASP. It seems one cannot save a .CSV format spreadsheet as .TXT unless the data is first sorted into columns etc. Could it be?

**Comment by boutinb** [comment]
Hi @WimRoest, I had a look to your txt file, and it is indeed quite a weird file. It starts like this:
`"Timestamp,""Username"",""I have read the above information and am willing to participate"",`
And JASP has to guess here what are the delimiters to read the names of the columns...
JASP should not crash, but its algorithm won't be intuitive enough to understand this file (it can see that the delimiters are probably the commas, but a column name may also contain a comma, so in this case the double quotes should encapsulate the column names: but here the double quotes are weirdly set).
But anyway, you have found a way to generate a proper CSV file, so I think we can close this issue.
