### ISSUE TITLE
Color bar in correlation matrix heatmap

### ISSUE THREAD

**Issue by daamartins** [jasp-stats/jasp-issues#1349]
Dear all

Thank you so much for all the work you have put in setting this great tool. I am wondering whether it is possible to get the color bars for the heatmaps of correlation matrices? I cannot really find them. Is there an equivalent in ggplot that i could use?

Thanks

**Comment by vandenman** [comment]
Hi @daamartins, the R code for the color bar is `ggplot2::scale_fill_gradient2(limits = c(-1, 1), na.value = "white")` ([source](https://github.com/jasp-stats/jaspRegression/blob/9d0d59cf80170d4e861315cc683ba287f3c4bc19/R/correlation.R#L1122)). For more details on this scale, see https://ggplot2.tidyverse.org/reference/scale_gradient.html

**Comment by juliuspf** [comment]
I will close this. @daamartins if you have any more questions please do not hesitate to ask.
