### ISSUE TITLE
UTF-8 coding of character strings in plots

### ISSUE THREAD

**Issue by lklende** [jasp-stats/jasp-issues#135]
## Template for bug reports

* JASP version: 0.8.5.1
* OS: Windows 10
* Analysis: Descriptives Boxplot
* Steps to reproduce: Change label of one or more variabel with names including interantional character i.e. ø or æ. The charactes are OK in tables, not in plots. An example is illustrated in attached file. Characters of labels in a table is ok, not in the plots.

## Template for enhancement requests
 
* Enhancement: Handle UTF-coding in plots
* Purpose: Make it possible to use international charactes in plots.
[ResultsInternationalCharacters.docx](https://github.com/jasp-stats/jasp-desktop/files/1659804/ResultsInternationalCharacters.docx)

**Comment by JorisGoosen** [comment]
@lklende I was just looking at some cyrillic in plots and it seemed that now we have that correct for most plots. So I'm assuming that scandinavian characters also work. The only plot where there still seems to be a problem is in a large matrix-plot for correlations and I have opened another issue for that.

So I'll be closing this issue now, and thanks again for kind words.
