### ISSUE TITLE
InferentialPlotsCorrelation

### ISSUE THREAD

**Issue by Diesfeldt** [jasp-stats/jasp-issues#1351]
Problem: changing the alternative hypothesis from ‘correlated’ to ‘correlated positively’ does change the table output and does change the label BF+0 in the inferential plots, but it does not change the value of BF and the pizza-plot.
[InferentialPlotsCorrelation.docx](https://github.com/jasp-stats/jaspSummaryStatistics/files/5530425/InferentialPlotsCorrelation.docx)

**Comment by tomtomme** [comment]
This is fixed.
