### ISSUE TITLE
Is it possible to deactivate scientific notation in the output viewer?

### ISSUE THREAD

**Issue by SchwingMC** [jasp-stats/jasp-issues#1352]
* Enhancement:Deactivate scientific notation
* Purpose: Some graphs and outputs are looking more streamlined.
* Use-case:

**Is your feature request related to a problem? Please describe.**
 
Some graphs are in scientic notation while this is not necassary.
![image](https://user-images.githubusercontent.com/85257001/124820511-de5d0700-df6d-11eb-9eb2-e9e60047a6de.png)

**Describe the solution you'd like**
 

**Describe alternatives you've considered**
 

**Additional context**

**Comment by boutinb** [comment]
I don't think it's possible, @vandenman ? But in the next release (end of Augustus probably), there will be a plot editing feature: you can then specify the ticks with their value/label on each axe.

**Comment by vandenman** [comment]
@SchwingMC This is not possible, as scientific notation avoids that different axis labels overlap. You sort of already see this happening with -40000 and -20000, so we set a cutoff at 1e5 to switch to scientific notation. Of course, this isn't always appropriate, as in your example. With the plot editing feature in the next release you should be able to do something like this:
![image](https://user-images.githubusercontent.com/21319932/124881055-36782580-dfcf-11eb-92b3-d7605cb2345a.png)
so you can control the text shown at individual labels.

**Comment by juliuspf** [comment]
I think this can be closed, since the plot editing functionality solves this issue, and the need for the scientific notation will not change.
