### ISSUE TITLE
JASP crashed

### ISSUE THREAD

**Issue by suhrudp** [jasp-stats/jasp-issues#1355]
* JASP version: 0.14.1
* OS name and version: Windows 10 (10.0)
* Analysis: 
* Bug description:
* Expected behaviour:

#### Steps to reproduce:

-----------------------------------------------------------------------

### Debug information:
**Engine # 0** process *does not exist (anymore)* and it's state is *stopped*.
**Engine # 1** process *crashed* and it's state is *initializing*.
**Engine # 2** process *crashed* and it's state is *initializing*.
**Engine # 3** process *crashed* and it's state is *initializing*.

[Commit used](https://github.com/jasp-stats/jasp-desktop/commit/f2cb223fef6b15089fd6e9da54825d370c1ece57)

**Comment by vandenman** [comment]
Hi @suhrudp, could you provide a bit more information on what you were doing when JASP crashed?
