### ISSUE TITLE
Display ratios in forest plot

### ISSUE THREAD

**Issue by TriRob** [jasp-stats/jasp-issues#1356]
* Enhancement: Meta-Analysis for binary outcomes
* Purpose: Pooling estimates from studies with binary outcomes (e.g. risk ratios, odds ratios). 
* Use-case: Many outcomes in the field of health and medicine are binary (heart attack, stroke, remission, death, clinically meaningful treatment response etc.) and require relevant meta-analytic options. 

**Additional context**
Hi, I work in the health and medical field, where meta-analyses of binary outcomes are common. It would be a great feature to have this possibility in a future JAPS update. 

I believe JAPS could stand out by incorporating different random effects models for estimating between-study variance, as the Hartung-Knapp/Sidak-Jonkman method is often not available in commonly used software such as RevMan, but can be preferable to the often used DerSimonian and Laird method. This would also allow for sensitivity analysis within one program. 

Some references: 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4950030/
https://www.acpjournals.org/doi/abs/10.7326/M13-2886
https://onlinelibrary.wiley.com/doi/10.1002/sim.7411

Many thanks and keep up the great work! 
PS: I will add that I am not a statistician.

**Comment by boutinb** [comment]
@sophieberkhout Can you answer this request?

**Comment by sophieberkhout** [comment]
JASP already provides various random-effects models. A random-effects model can be fitted with one of the various estimators for the amount of heterogeneity (you can find these in the 'Method' dropdown menu):

- Maximum Likelihood
- Restricted ML
- DerSimonian-Laird
- Hedges
- Hunter-Schmidt
- Sidik-Jonkman
- Empirical Bayes
- Paule-Mandel

I believe it is even possible to conduct the HKSJ method by setting the method to 'Sidik-Jonkman' and then in the 'Statistics' tab under 'Regression Coefficients' choose 'knha' in the 'Test' dropdown menu of the confidence interval estimates (see image below).

![Screenshot 2021-07-14 120705](https://user-images.githubusercontent.com/49243293/125604753-4301fe29-59ad-4fb6-a3bc-2eb4e8d62cce.png)

From the documentation of the `metafor` package (which this analysis uses):
> When test="knha", the Knapp and Hartung (2003) method is used, which applies an adjustment to the standard errors of the estimated coefficients (to account for the uncertainty in the estimate of the amount of (residual) heterogeneity) and uses t- and F-distributions.

Hope this helps!

**Comment by TriRob** [comment]
Many thanks, Sophie! That's very helpful! I was confused by the forest plot. I think it would be useful to have available more interpretable effect measures such as odds rations or risk ratios as the output in the forest plot. This seems to be restricted to log odds ratios (https://jasp-stats.org/2017/11/15/meta-analysis-jasp/). Maybe there could be an option where this is back transformed in the forest plot in the future. Again, many thanks for the quick response! :)

**Comment by sophieberkhout** [comment]
I see. As you are probably aware, when using ratios as effect sizes, you need to take the log (for normality) to be able to conduct the meta-analysis. However, I agree that it would be nice if the forest plot could show the ratios without the log. I will see if I can add this functionality.

**Comment by TriRob** [comment]
Thanks a lot!

**Comment by Fernandez-Felix** [comment]
Many thanks, Sophie! I appreciate your contribution to the development of the Meta-analysis module in JASP.
I know that the appropriate scale to summarize ORs or RRs is the "log scale", but interpreting them is easier using the original scale (OR or RR). I am trying to build the forest plot using ORs. However, it seems that it is not possible to exponentiate "Effect Size" in JASP. I usually work with Stata, and it allows building the polled effect using "log scale" and then visualizing the results (tables or forest plots) in ORs scale. 

Is it possible to do this in JASP? If it is not available, do you think it could be included in the next update?

**Comment by tomtomme** [comment]
@Fernandez-Felix 
You should have the ES as a variable in the data. You can then compute a new column to comput exp(ES) and use that. Does that help?
See https://jasp-stats.org/2018/12/18/how-to-compute-columns-in-jasp/#:~:text=How%20to%20Compute%20Columns%20in%20JASP%201%20Setting,your%20Computed%20Column%20and%20Exporting%20the%20Data%20

Also regarding the original issue. Is there still a feature missing from your list? May make sense to open a new issue for those then.

**Comment by tomtomme** [comment]
@TriRob 
As your request was answerde I will close this now

@Fernandez-Felix 
Your issue is still discussed here: https://github.com/jasp-stats/jasp-issues/issues/2371
