### ISSUE TITLE
could'nt install JASP

### ISSUE THREAD

**Issue by rkela** [jasp-stats/jasp-issues#1357]
* JASP version: JASP 0.14.1

* OS name and version: Chromebook 32-bit
* Analysis:  I was typing the codes in the terminal, and it was all good until I typed "flatpak --user remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo" and it said, "command not found". I did it like you showed in the pictures, so I don't know what I did wrong
 Is the problem with my Chromebook, or is there something I am missing?

**Comment by vandenman** [comment]
Hi @rkela, what do you get when you run `flatpak --version` in a terminal? If that also returns `command not found` you should probably double-check if installing flatpak went correctly.
