### ISSUE TITLE
Unexpected behavior opening .csv with text columns

### ISSUE THREAD

**Issue by AnguloB** [jasp-stats/jasp-issues#1359]
* JASP version:  0.14.1

* OS name and version:  MacOs. BigSur MacBook Pro
* Bug description: When I try to open .csv with long strings and lots of rows JASP crashes. When I try to open the same file but with less rows and with the problematic row, it doesn’t crash but there are missing rows (and there is no warning). With R (and excel) I can open it with any problem. 

#### Steps to reproduce:
1.	Open file

#### Example
I have created a dataset with lorem ipsum. The problematic row is id = 12. If you try to open it, it crashes. If you remove rows and keep for example row 1 to 20, it opens but only read 1 to 12. 

[fake.csv.zip](https://github.com/jasp-stats/jasp-issues/files/6815475/fake.csv.zip)

**Comment by boutinb** [comment]
Hi @AnguloB I see the problem. Apparently when a row has more than 4096 characters, JASP crashes. I will fix this problem.
