### ISSUE TITLE
Feature request: Option to use label instead of variable name for outputs

### ISSUE THREAD

**Issue by drleehw** [jasp-stats/jasp-issues#136]
SPSS doesn't permit spaces in variable names, thus, if one analyses an SPSS dataset with JASP, one ends up with outputs that have ugly variable names like T1_Neuroticism_q1. Please can we have the ability to read the more user-friendly variable label from SPSS? 

Ideally, there would be an option to read row 2 of a .ods sheet in the same way. Row 1: variable name; Row 2: user-friendly label. 

Thanks

**Comment by AlexanderLyNL** [comment]
Tooltip added.
