### ISSUE TITLE
Multiple imputation

### ISSUE THREAD

**Issue by TarandeepKang** [jasp-stats/jasp-issues#1362]
* Enhancement: Adding a multiple imputation routine
* Purpose: better handling of missing data
* Use-case: missing data are common in quantitative studies using questionnaires, which are widely used in psychology, epidemiology, and some other areas of medicine, especially in cases where trimming/winsorisation is not sufficient to deal with greater numbers of missing data points. See for example this article from the British Medical Journal: https://www.bmj.com/content/338/bmj.b2393 and this one in JAMA https://jamanetwork.com/journals/jama/article-abstract/2468879.

**Is your feature request related to a problem? Please describe.**
 
At the moment, ability to handle missing data is rather limited in the software. I note that similar feature request had been made previously #904 but the issue has been closed.
**Describe the solution you'd like**
 
The ability to run multiple imputation of missing data in JASP. 
Particularly useful are packages might be mice:

 van Buuren S, Groothuis-Oudshoorn K (2011). “mice: Multivariate Imputation by Chained Equations in R.” Journal of Statistical Software, 45(3), 1-67. https://www.jstatsoft.org/v45/i03/.  

or  mi:

 https://www.jstatsoft.org/article/view/v045i02 
**Describe alternatives you've considered**
 
Multiple imputation procedures are available in SPSS, but obviously this is not reducible, implementation in R is also possible, although this can be rather difficult for people with little exposure to programming.

**Additional context**

**Comment by EJWagenmakers** [comment]
We are in fact already in the process of implementing MICE. It takes a little longer than expected, because in the mean time we also added data editing.
Cheers,
E.J.

**Comment by TarandeepKang** [comment]
That must be the fastest response in history! In any case, now I will be able to help our UGs and my R-phobic PhD supervisor transition away from SPSS, because JASP will be able to fulfil all of their needs. Thank you again for all the hard work, folks!

**Comment by EJWagenmakers** [comment]
We wanted to wait until we have data editing. We can revisit this issue immediately after we have our syntax release. Actually, maybe before that time some project members can look into this.

**Comment by tomtomme** [comment]
MICE etc is now tracked here: https://github.com/jasp-stats/jasp-issues/issues/2437
closing since duplicate
