### ISSUE TITLE
Timestamp's string invalid SPSS datafile

### ISSUE THREAD

**Issue by Ankeetal** [jasp-stats/jasp-issues#1363]
* JASP version: 0.14.1

* OS name and version: Windows
* Bug description: Tried to open an SPSS (sav) datafile and received the following error message: the timestamp's string is invalid. JASP could therefore not open the file (but SPSS could). I have been able to open other SPSS datafiles (same version) without this error. 
* Expected behaviour:

#### Steps to reproduce:
NA

<!--- A note from the developers:
If possible please attach your data and/or JASP file to the issue, this makes solving the bug a lot easier. If you would prefer to not make your data publicly available then you could also mail it to us.

**Comment by juliuspf** [comment]
@Ankeetal could you upload the SPSS file here?

**Comment by JorisGoosen** [comment]
@Ankeetal could you post a screenshot here of the error?
And uploading the spss file would indeed be quite helpful.

Also (for my own administration) #606 should be taken into account when looking at this issue.
