### ISSUE TITLE
Option to align dots when error bars are displayed in descriptive plots

### ISSUE THREAD

**Issue by AnthonyWonga** [jasp-stats/jasp-issues#1369]
* Enhancement: An option to align dots with error bars in descriptive plots
* Purpose: For making figures similar to those in mainstream journals
* Use-case: Making figures for publication

**Is your feature request related to a problem? Please describe.**
When JASP produces descriptive plots, the dots do not align on a straight vertical line when error bars are included (see below with data from the library)
![image](https://user-images.githubusercontent.com/88035348/127146395-1fb47059-ff9b-4886-8ade-73e38ab3d5ba.png), I understand that this is a feature, but an option to align them would be nice

**Describe the solution you'd like**
An option to align the summary dots on a straight vertical line

Thanks a lot for the amazing JASP.

**Comment by tomtomme** [comment]
@AnthonyWonga 
For the time being I hope I can help with a workaround. You can export plots to .pptx format now and then edit them in powerpoint. 

And at the same time I am questioning those alligned figures in "mainstream journals". Why would you want to make the plot less readable? Is there really a journal that demands this?

@vandenman 
What do you think? Is this essentially a "wont fix" or are you still considering such an option?
