### ISSUE TITLE
Linear regression - Casewise Diagnostics - Amount of outliers does not decrease after filtering case numbers out

### ISSUE THREAD

**Issue by teamagilelaura** [jasp-stats/jasp-issues#1371]
* JASP version: 0.14.1
* OS name and version: MacOS BigSur 11.4
* Analysis: Linear Regression (Classical)
* Bug description: In the _casewise diagnostics_ I have cases that are reported as outliers, e.g. case number 48. As soon as I filter out case number 48 and run the analysis again, it shows a new case number as an outlier, e.g. 47. Hereby, overall the amount of case numbers stays the same, the only difference is that new case numbers are marked. 
For another analysis the amount of outliers stays the same and the case numbers change without pattern like here (from 48 to 47 and 131 to 130), e.g. case number 129 ist removed and case number 120 pops up after the removal of case number 129.
* Expected behaviour: As soon as I remove/filter out the listed case number of my data set, the case number disappears from the Casewise diagnostics list and the amount of outliers is reduced.

#### Steps to reproduce:
1. Go to 'Regression'
2. Click on 'Classical - Linear Regression and run bootstrapped analysis'
3. Scroll down to 'Casewise Diagnostics'
4. See numbers
5. Filter out the reported 'case number'
6. See 'Casewise Diagnostics' amount of outliers stays the same only new numbers appear.

**Before**
![image](https://user-images.githubusercontent.com/52463345/127291440-78d08da3-350f-493c-a88f-37e7fddecb3a.png)

**Data removed**
![Screenshot 2021-07-28 at 10 36 24](https://user-images.githubusercontent.com/52463345/127291866-88c7e366-4089-45d3-bde5-c6cfe6b8d0d5.png)

**Afterwards**
![Screenshot 2021-07-28 at 10 38 52](https://user-images.githubusercontent.com/52463345/127292060-204f0e60-7344-419c-9d1d-807026cff3e9.png)

**Comment by vandenman** [comment]
@teamagilelaura by default, cases with a standardized residual above 3 are interpreted as outliers. However, when you filter out outliers, you effectively change the entire standardization process (which is based on all data). I would not recommend filtering out all outliers by default, only to further inspect these cases for any particular oddities (which may be grounds to exclude them). In addition, if you look at the plot `Residuals vs. predicted` you should be able to tell which points are outliers. However, it could very well be that you see something like this:

![image](https://user-images.githubusercontent.com/21319932/127298973-cf81b0b6-b40b-4656-813e-a983215037ce.png)
 once you exclude the point above the red line, it's very likely that the top point right underneath the red line becomes the next outlier.

**Comment by teamagilelaura** [comment]
Thank you very much @vandenman !
