### ISSUE TITLE
Mean vs Median (Bayesian LMM)

### ISSUE THREAD

**Issue by jubera** [jasp-stats/jasp-issues#1372]
Hi, 

I am performing Bayesian LMM analysis with JASP. I would like to perform a graph to see the raw means vs the estimated means. 

However, JASP output gives the Median and the lower and upper 95% HPD (see screenshot attached). Would it be possible to get the means in addition to the medians? or maybe my question does not make sense at all (?)

Thanks in advance for your help!

Esperanza

![Screenshot 2021-07-28 at 16 11 02](https://user-images.githubusercontent.com/4691978/127337656-2bb7b377-05b2-4a80-bbc5-3df31f1b067f.png)

**Comment by FBartos** [comment]
Hi Esperanza,

I'm sorry but it's not currently possible to obtain the desired output. We are using the `emmeans` package and it seems to only provide medians and 95% HPD. 

Best,
Frantisek

**Comment by AlexanderLyNL** [comment]
To clarify, the table shows a summary of the posterior of the marginal means. For instance, the posterior median 1.039 can be used as a point estimate for the marginal mean for Row 1 and Session 1. After data observation, the table shows that there is a 95% probability that the marginal mean of Row 1 and Session 1 is between 0.845 and 1.229.

**Comment by juliuspf** [comment]
Doe that solve your issue @jubera?
