### ISSUE TITLE
3-way RM ANOVA

### ISSUE THREAD

**Issue by GregBorghi** [jasp-stats/jasp-issues#1375]
* JASP version: 0.14.1

* OS name and version: Windows 10
* Analysis: Bayesian RM ANOVA
* Bug description: When attempts to run a 3-way (2x2x2) RM factor ANOVA that comprehend a single between-subject factor with 2 levels and 2 covariates, the software enters in a permanent state of loading and the charging bar does not move (I tried to leave it for like 2 hours but the charging bar was still at 0)
* Expected behaviour: to have a fully functioning 3-way RM ANOVA functioning

#### Steps to reproduce:
1. Go to 'Bayesian Repeated Measure ANOVA'
2. Click on 'RM factors (enter all the 3)'
3. Add Between subject factor (2 levels)
4. Add 2 covariates

Attached file from the analysis:
[JASPanovaDEBUG.zip](https://github.com/jasp-stats/jasp-issues/files/6933348/JASPanovaDEBUG.zip)

**Comment by vandenman** [comment]
So there are an incredibly large number of models present. If I were you, I'd delete all interactions effects, unless you actually have hypotheses about them. You can do so by going to `Models` and removing all the terms that contain an interaction effect. You can select a range of models by holding shift or ctrl, similar to how you can select multiple files in windows explorer.

Once I remove all the interactions effects, the analyses runs fine for me.
