### ISSUE TITLE
Crash on cluster analysis when adding predicted clusters (linux)

### ISSUE THREAD

**Issue by Ziggyblake** [jasp-stats/jasp-issues#1378]
* JASP version: 0.14.3
* OS name and version: Linux mint 20.1
* Analysis: Everytime I try to run a cluster analysis it works properly, but when I want to add the cluster to the data ("Add predicted clusters to data") JASP totaly crashes and closes. I have tried to uninstall and reinstall, through the software manager and through the flatpak, the error is still here. A few month ago it used to work (maybe before an update ?). It does the same on different data files and different clusters algorithms
* Expected behaviour: Not expected to crash

#### Steps to reproduce:
launch a data file, go to Machine Learning, pick any Cluster analysis. Run your cluster analysis (it works). Then check "Add predicted clusters in the data". And voila. It crashes systematically on my machine.
Thanks for the good work

**Comment by vandenman** [comment]
I can replicate this on flatpak 0.14.3, the current flatpak beta branch, but not on a locally build development version.

**Comment by vandenman** [comment]
@JorisGoosen it looks like this happens more generally on flatpak (e.g., Network analysis is also affected). Perhaps the computed column stuff goes wrong somewhere?

**Comment by JorisGoosen** [comment]
Yeah indeed, even adding a computed column and filling it with values crashes...

I am having quite some trouble getting the debugsymbols loaded in flatpak though...

**Comment by Ziggyblake** [comment]
PS: most machine learning algorithms do the same when you want to add the data, its not only the "clustering" ones.
Any tricks on how to get past the bug while waiting for your brilliant brains to find a solution? 
Thanks

**Comment by vandenman** [comment]
@Ziggyblake JASP 0.14 does not have the issue, so you could try using that version (see [downgrading flatpak](https://docs.flatpak.org/en/latest/tips-and-tricks.html#downgrading)). The alternative is to not save anything to the dataset, but I guess that's not a very nice option.

**Comment by Ziggyblake** [comment]
@vandenman thank you, but version 14.0.0 fails to launch. I can install it via flatpak, but I can't run it. 

14.0.1 and 14.0.2 and 14.0.3 all work fine, but they all have the cluster bug. 
I'll try with 13.1 later. Thank you.

**Comment by JorisGoosen** [comment]
Ok, it seems that the Qt we are using broke JASP, so a workaround for now is:
`flatpak update --commit 4f232783b07952a4627a186c8020a362d2458c4b2d6046fbd0b43d3f44c551a7 org.kde.Sdk/x86_64/5.15`
After that JASP should work fine.

Once [this issue at kde](https://bugs.kde.org/show_bug.cgi?id=442422) is resolved I can actually debug what is wrong with it, but I am assuming that having a new version of the runtime might already fix it.

**Comment by Ziggyblake** [comment]
error: org.kde.Sdk.Debug/x86_64/5.15 not installed

When trying to install it "flatpak install --user org.kde.Sdk.Debug/x86_64/5.15" :
Looking for matches ... 
error: No remote refs found similar to ‘org.kde.Sdk.Debug/x86_64/5.15'

I'm quite a linux/flatpak noob to be honnest I might be doing something wrong. Thanks for your help anyway.

**Comment by JorisGoosen** [comment]
Hey sorry, I did something wrong!

But I couldn't find all the issues where I did so...

You should actually try:
`flatpak update --commit=212d267860a3001081816007b074dd57993335aec23485c082d40034c6a5b857 org.kde.Platform/x86_64/5.15`

**Comment by JorisGoosen** [comment]
@Ziggyblake ?

**Comment by Ziggyblake** [comment]
Thanks ! It works perfectly. 
Thank you so much.
Have a great day.

**Comment by JorisGoosen** [comment]
Aah great!

Adding the `--user` flag might also help, but then it all needs to be installed as user.

**Comment by AlexanderLyNL** [comment]
This seems to be fixed. So I'm closing this, please reopen if not. Thanks for the report.
