### ISSUE TITLE
Printing results

### ISSUE THREAD

**Issue by eqcanela** [jasp-stats/jasp-issues#138]
Despite its simplicity, I still need more comforts in printing (or saving the results of JASP analysis in Mac. I am not given enough possibilities and the plot images are saved differently from the text results (in HTML). Jasp version is 0.8.5. OS is High Sierra and I use safari Browser.

Thank you. 
## Template for bug reports

* JASP version:
* OS name and version:
* Analysis:
* Steps to reproduce: 

## Template for enhancement requests
 
* Enhancement:
* Purpose:

**Comment by JorisGoosen** [comment]
Seeing as how this issue does not actually give us a suggestion on how to make printing easier and I have the feeling that exporting the results to HTML, opening them in a webbrowser and printing should probably work fine; I'll close this issue.
