### ISSUE TITLE
JASP crashed

### ISSUE THREAD

**Issue by kornbrot** [jasp-stats/jasp-issues#1380]
* JASP version: 0.13.1
* OS name and version: macOS 10.16
* Analysis: 
* Bug description:
* Expected behaviour:

#### Steps to reproduce:

-----------------------------------------------------------------------

### Debug information:
**Engine # 0** process *crashed* and it's state is *initializing*.
**Engine # 1** process *crashed* and it's state is *idle*.
**Engine # 2** process *does not exist (anymore)* and it's state is *initializing*.
**Engine # 3** process *does not exist (anymore)* and it's state is *initializing*.

[Commit used](https://github.com/jasp-stats/jasp-desktop/commit/d2d5d378a3ccb371eb6ea357352966b510c516a6)

**Comment by boutinb** [comment]
Hi @kornbrot Could you try the last version of JASP (0.14.1). Also if the problem still occurs, could you describe exactly what you do? How do you start JASP: clicking JASP icon, by loading a file? Do you get any error message?
