### ISSUE TITLE
Descriptive sum for Likert or any scale

### ISSUE THREAD

**Issue by romanogino** [jasp-stats/jasp-issues#1383]
Hello

Just to improve JASP, I suggest adding the summation option in the descriptive statistics. That column or result is missing in the reports.

JASP is an excelent softaware!!

Best regards.
r.
![JASP](https://user-images.githubusercontent.com/1270242/129498736-40093850-b3e9-4869-a45f-1a057346f5d2.jpg)
![SPSS](https://user-images.githubusercontent.com/1270242/129498737-8e520350-8b3e-4f6c-aeec-07a23e617937.jpg)

**Comment by vandenman** [comment]
Hi @romanogino, I think you can find the `sum` under `Central Tendency`:

![image](https://user-images.githubusercontent.com/21319932/129525287-b035775b-da71-4853-9ab6-49ebf364af2e.png)

In the upcoming release, however, the location of `sum` has been moved to the group `Distributions`.

**Comment by romanogino** [comment]
Dear @vandenman 
Thanks for the information, it is useful.
Best regards.
r.
