### ISSUE TITLE
Display order descriptive statistics

### ISSUE THREAD

**Issue by romanogino** [jasp-stats/jasp-issues#1384]
Hello everybody

Just other suggestion: ascending or descending display order, alphabetical or list of variables, for descriptive statistics.
To continue improving JASP.
Best regards.

![jasp 02](https://user-images.githubusercontent.com/1270242/129499421-8ce7fed8-0373-4620-aaed-db854e913523.jpg)
![SPSS 02](https://user-images.githubusercontent.com/1270242/129499422-35db6ccf-f917-4c12-8ccf-2e08fd41a2b3.jpg)

r.

**Comment by vandenman** [comment]
Hi @romanogino, the order in tables is typically not fixed but instead follows the order in which you enter the variables:

![image](https://user-images.githubusercontent.com/21319932/129524824-78210426-a17e-4112-a524-8873d879a567.png)

If you wish the enter variables alphabetically, you can first sort the variables in the input list:
![image](https://user-images.githubusercontent.com/21319932/129524876-1c87ff23-9b1a-4928-990f-e93a93fd2b50.png)

which yields:
![image](https://user-images.githubusercontent.com/21319932/129524903-d8b577c8-b0cf-4d46-8ad2-2d4e0e1549cf.png)

After that, you can select multiple variables at once (with either shift to select a range of variables or ctrl to select individual variables) and as long as you work from top to bottom the table will be sorted alphabetically:

![image](https://user-images.githubusercontent.com/21319932/129524956-f1f6c5df-ffd9-47f2-8b14-ef4e8f9060dd.png)

Hope that helps!

**Comment by romanogino** [comment]
Dear @vandenman 
I am very accustomed for looking all the options in the windows. 
Thanks for the information, it is useful.
Best regards.
r.
