### ISSUE TITLE
Urgent (have assignment due in an hour)

### ISSUE THREAD

**Issue by knlyyl** [jasp-stats/jasp-issues#1386]
* JASP version: most recent

* OS name and version: macOS Catalina version 10.15.7
* Analysis: 
* Bug description: 
This analysis terminated unexpectedly. Error in parse(text = x, keep.source = FALSE): :2:0: unexpected end of input
1: resids ~
   ^
Stack trace
* Expected behaviour:

**Comment by vandenman** [comment]
Hi @knlyll, sorry to hear about your assignment. Could you maybe post the jasp file with the bug in this issue? If so, you have to zip the file before uploading, otherwise, GitHub won't let you upload it.
