### ISSUE TITLE
Additional regression types: Ridge, Lasso and Elastic Net

### ISSUE THREAD

**Issue by TarandeepKang** [jasp-stats/jasp-issues#1388]
* Enhancement: Implement additional regression procedures including Ridge, Lasso & Elastic Net
* Purpose: These methods provide solutions to multicolinearity issues
* Use-case: for datasets in which variables are correlated with one another, and linear regression is inappropriate. Often useful for analysis of survey datasets, as in social psychology psychiatry and epidemiology

These and other regression methods not currently available in JASP are available in the glmnet R package.

**Describe alternatives you've considered**
 
Currently these analyses are only possible in SPSS or R

**Comment by Kucharssim** [comment]
Dear @TarandeepKang,

Thank you for the suggestion. Is there anything that is missing if you open Machine Learning Module -> Regularized Linear Regression? This analysis offers Lasso, Ridge, and Elastic Net as well. But we will be of course interested if there is anything in particular that keeps you away from using JASP for this purpose.

Best,
Simon

**Comment by TarandeepKang** [comment]
Thank you for this prompt response! I’m afraid it was all my fault, for looking only under the regression module, and not investigating the machine learning one. Thank you again for all your hard work!


Sent from Yahoo Mail for iPhone


On Thursday, August 19, 2021, 14:46, Simon Kucharsky ***@***.***> wrote:




Dear @TarandeepKang,

Thank you for the suggestion. Is there anything that is missing if you open Machine Learning Module -> Regularized Linear Regression? This analysis offers Lasso, Ridge, and Elastic Net as well. But we will be of course interested if there is anything in particular that keeps you away from using JASP for this purpose.

Best,
Simon

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Kucharssim** [comment]
No worries! Glad that I could help!
