### ISSUE TITLE
Find out why test set indicator shows error with missing data

### ISSUE THREAD

**Issue by koenderks** [jasp-stats/jasp-issues#1389]
This is a new issue relating to https://github.com/jasp-stats/jasp-issues/issues/1387. It seems like using these data:
[BoostingRegressionBugWhenAssigningTestSetIndicator.-.NEW.csv](https://github.com/jasp-stats/jasp-issues/files/7021050/BoostingRegressionBugWhenAssigningTestSetIndicator.-.NEW.csv)

this error occus:
![](https://user-images.githubusercontent.com/65332772/130212402-0aebeba4-862e-451a-b5a9-03127708f263.png)

This can be solved by removing some variables (like Dur.R) from the data set because these contain missing values. However, we need to figure out why this crashes.

**Comment by vandenman** [comment]
So the reason why is the following:

in https://github.com/jasp-stats/jaspMachineLearning/blob/7a5ac1164eec15db340163f865f4a9b43ad5b707/R/commonMachineLearningRegression.R#L44-L52 we read the dataset and then do:
```r
dataset             <- na.omit(dataset)
```
before then, the test set indicator contains both 0 and 1. After dropping the missings, only 0 remains. If you remove `Dur.R`, which happens to contain some missing values that cause some 1s to be dropped, then it works again.
