### ISSUE TITLE
JASP crashes on opening

### ISSUE THREAD

**Issue by Stats1010** [jasp-stats/jasp-issues#1391]
* JASP version: 0.14.1.0
* OS name and version: Windows
* Analysis: 
* Bug description: When trying to open a JASP file that I've been doing analysis in, it does not open anymore. It crashes every time I try to  open it. Its been working fine but now all of a sudden the file won't open. 
* Expected behaviour: The file should open as normal.

**Comment by boutinb** [comment]
Could you send us the JASP file? For this zip it, and drag & drop it in a comment of this issue in GitHub.

**Comment by Stats1010** [comment]
hi team, here it is :) greatly appreciate your help, especially any tips so this doesn't happen again - mid-thesis at the moment so very stressful having JASP not cooperate! :)

[Cleaned data for analysis JASP.zip](https://github.com/jasp-stats/jasp-issues/files/7045009/Cleaned.data.for.analysis.JASP.zip)

**Comment by tomtomme** [comment]
@Stats1010 
Have you retested with less analysis or with newer jasp versions? Would be cool to know, if this is solved.
