### ISSUE TITLE
Analysis terminated unexpectedly 

### ISSUE THREAD

**Issue by Ascrypto** [jasp-stats/jasp-issues#1394]
* JASP version: 0.14.1
* OS name and version: MacOS Big Sur
* Analysis: Independent samples T-Test (Assumption Checks) 
* Bug description: 
This analysis terminated unexpectedly.
Error in .ttestIndependentEqVarFill(equalityVariance, dataset, options): object 'result' not found
Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])
doTryCatch(return(expr), name, parentenv, handler)
withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)
analysis(jaspResults = jaspResults, dataset = dataset, options = options)
.ttestIndependentEqVarTable(jaspResults, dataset, options, ready, type)
.ttestIndependentEqVarFill(equalityVariance, dataset, options)

*******************
It was working just fine before I updated the OS. 
Thank you.

**Comment by boutinb** [comment]
If you have updated your Mac OS, maybe you need to download the right JASP dmg file in the Download page: https://jasp-stats.org/download/. Could you remove JASP and download the Catalina & Big Sur version?

**Comment by Ascrypto** [comment]
Resolved. Thank you.
