### ISSUE TITLE
Notification "Engine crashed"

### ISSUE THREAD

**Issue by PerPalmgren** [jasp-stats/jasp-issues#1396]
* JASP version: 0.15
* OS name and version: Windows
* Analysis: 
* Bug description: I was trying out the beta version during a flight (no internet). When I tried to make a graph bigger (by pulling the corner) the program crashed time after time. See print screen below:
* 
![JASP distribution plot](https://user-images.githubusercontent.com/79397662/130927727-57e66729-a591-46ce-94a2-2155b07a4971.png)

* Expected behaviour:

**Comment by PerPalmgren** [comment]
﻿Hi,
I hope you are fine.
Two questions:
- Could you please send me the latest ”nightly” so I can test the upcoming 0.15
- Do you have an official release date?
Kind regards
Per Palmgren

Per J. Palmgren | DC, FRCC, MMedEd, PhD |
Associate Professor |
Department of Learning, Informatics, Management and Ethics |
Karolinska Institutet | Tomtebodavägen 18A | 171 77 Stockholm |
Tel. + 46 8 524 85 294<tel:+%2046%208%20524%2085%C2%A0294>
***@***.******@***.***> | ki.se<http://ki.se/>
________________________________

Karolinska Institutet – a medical university

27 aug. 2021 kl. 15:20 skrev bruno boutin ***@***.***>:

﻿

The current version 0.14.1 should work also fine: this is the official up-to-date version you can use also for your course. What you are using is 'development' version. It should be released begin of September. Do you need some new features that will be released only in 0.15?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjasp-stats%2Fjasp-issues%2Fissues%2F1396%23issuecomment-907198138&data=04%7C01%7Cper.palmgren%40ki.se%7C01bb4b9a1c424d2ce5d008d9695d73c0%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637656672366010688%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rcUnkAb8xYvHcFLlNV7njX1dI14tw%2FgbNTdGsxfIJxo%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS5YGHTASG6GMC2N2AVNIILT66GKBANCNFSM5C2ZZWZA&data=04%7C01%7Cper.palmgren%40ki.se%7C01bb4b9a1c424d2ce5d008d9695d73c0%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637656672366020685%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nOAiOP5q6BYKLTRkAp%2F84%2FUOrZ%2BCGMEIoNB8u%2BGufmY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cper.palmgren%40ki.se%7C01bb4b9a1c424d2ce5d008d9695d73c0%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637656672366030679%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=a34uK6FTlb824xApeHM3grDfaYlo8ZObpP5vbzF8JXw%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cper.palmgren%40ki.se%7C01bb4b9a1c424d2ce5d008d9695d73c0%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637656672366030679%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cck09t%2FrK56oH14FMSpo6nLi%2BTh%2Br4KhcrtfjzY7XR8%3D&reserved=0>.



När du skickar e-post till Karolinska Institutet (KI) innebär detta att KI kommer att behandla dina personuppgifter. Här finns information om hur KI behandlar personuppgifter<https://ki.se/medarbetare/integritetsskyddspolicy>.


Sending email to Karolinska Institutet (KI) will result in KI processing your personal data. You can read more about KI’s processing of personal data here<https://ki.se/en/staff/data-protection-policy>.

**Comment by amirmasoudabdol** [comment]
You can download the latest Nightly [here](http://static.jasp-stats.org/Nightlies/), and the release date is just around the corner! 🙂

**Comment by PerPalmgren** [comment]
Hi,
Is it possible fo you to sen me a link to a download because I don’t know how to handle a whole Zip-file.
Kind regards
Per

Per J. Palmgren | DC, FRCC, MMedEd, PhD |
Associate Professor |
Department of Learning, Informatics, Management and Ethics |
Karolinska Institutet | Tomtebodavägen 18A | 171 77 Stockholm |
Tel. + 46 8 524 85 294<tel:+%2046%208%20524%2085%C2%A0294>
***@***.******@***.***> | ki.se<https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fki.se%2F&data=04%7C01%7Cper.palmgren%40ki.se%7C9f6969aac91f4526542308d875898009%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637388580700328145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=f6OY6fEm6z0scmnO%2FDhlWRgL%2BujfjA072A2uHaASfNY%3D&reserved=0>
________________________________

Karolinska Institutet – a medical university

**Comment by amirmasoudabdol** [comment]
If you are using Windows, I believe you can just download the MSI file, and that is just a normal Window installer package. [This one](http://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-development-61a659d99e452e6302669e9781d53c45bda702a1.msi) should do it, it's for 64bit systems.

**Comment by PerPalmgren** [comment]
Yes, I am using Windows. What is the MSI file?
Do you mean the JASP .exe. file?
Per

***@***.***

Per J. Palmgren | DC, FRCC, MMedEd, PhD |
Associate Professor |
Department of Learning, Informatics, Management and Ethics |
Karolinska Institutet | Tomtebodavägen 18A | 171 77 Stockholm |
Tel. + 46 8 524 85 294<tel:+%2046%208%20524%2085%C2%A0294>
***@***.******@***.***> | ki.se<https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fki.se%2F&data=04%7C01%7Cper.palmgren%40ki.se%7C9f6969aac91f4526542308d875898009%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637388580700328145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=f6OY6fEm6z0scmnO%2FDhlWRgL%2BujfjA072A2uHaASfNY%3D&reserved=0>
________________________________

Karolinska Institutet - a medical university

**Comment by amirmasoudabdol** [comment]
This link, http://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-development-61a659d99e452e6302669e9781d53c45bda702a1.msi

Clicking on it will download the latest Nightly, and you can then double click on it and it let you install the new version.

**Comment by juliuspf** [comment]
I believe this should be fixed by now, if not feel free to reopen the issue.
