### ISSUE TITLE
JASP closes when removing a level of the factors of a Repeated Measures ANOVA

### ISSUE THREAD

**Issue by JaumeLloria** [jasp-stats/jasp-issues#1397]
* JASP version: 0.14.00
 Windows 10
* Bug description: JASP shuts down suddenly when I remove a level of the factors of a RM ANOVA. Clicking in the "x" for removing the level shuts down the software. It happens to me when I have done a copy of the previous analysis (to do not have to select all the options that my analysis include again and just change the variables in which the analysis is going to be performed). 
* Expected behaviour: to keep running normally and allow to keep doing the analysis without loosing the non-saved data

#### Steps to reproduce:
0. Generate a database that allows for a repeated measures ANOVA with two factors (in my case: time and modality)
1. Go to '...' ANOVA > Repeated Measures ANOVA > Start the first analysis selecting the desired variables > in my case an ANOVA with 6 levels for the TIME factor (i.e. Pre, Post, Post1, Post2, Post8, Post24 and Post48) and with two levels in the second factor: MODALITY (30-4 and 15-2). 
2. Generate a copy of this analysis and start selecting the desired variables for the new analysis. In this second case, the factor TIME, only has 4 levels (i.e. Pre, Post10, Post24, Post48). 
4. See error when trying to delete the two levels that has been copied from the first analysis to only perform an analysis with 4 levels in this first factor. 

<!--- A note from the developers:
I prefer to do not share the data here for confidentiality issues, but I will be happy to share it with a JASP developer if necessary. 

I've repeated this analysis many times, and the bug has occured all the times. So it is not a punctual error.

**Comment by JaumeLloria** [comment]
Great! Thanks a lot for your answer. I'll just wait until you release the new version of JASP. 

Thanks again for you work

**Comment by juliuspf** [comment]
If this issue is indeed solved, would you mind closing this issue @JaumeLloria ?
