### ISSUE TITLE
Bayes factor robustness check error in German version

### ISSUE THREAD

**Issue by CRobinho** [jasp-stats/jasp-issues#1398]
Dear support team,

during the 2021 JASP workshop, I encountered an error. In JASP 0.15 ("Workshop 2021 version") under Bayesian independent samples t-test, the bayes factor robustness check works in English language but not in German (maybe a problem with the Umlaut).

This happened for the stereograms dataset and it also happened for the invisibility cloak dataset in the library. A screenshot is attached. 

Thanks for looking into this!

Christoph

![error robustness check](https://user-images.githubusercontent.com/82031543/131121710-71903f25-2942-4e8a-be20-5951250152f3.png)

**Comment by CRobinho** [comment]
Hi, unfortunately, the error persists 

[JASP 2021-08-28 15_26_18 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/7070769/JASP.2021-08-28.15_26_18.Desktop.log)
[JASP 2021-08-28 15_26_18 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/7070770/JASP.2021-08-28.15_26_18.Engine.0.log)

**Comment by juliuspf** [comment]
Dear @CRobinho, could you try if this issue is solved with the latest JASP version?
