### ISSUE TITLE
Add visible package reference to output

### ISSUE THREAD

**Issue by vankesteren** [jasp-stats/jasp-issues#140]
JASP uses `R` packages for specific analyses. It would be nice if we would visibly display which package is responsible for which output (@SachaEpskamp) -- see pca (psych), sem (lavaan), network (bootnet).

**Comment by tomtomme** [comment]
This would indeed be useful and is not yet covered by our R syntax mode afaik.

**Comment by tomtomme** [comment]
closing as duplicate of https://github.com/jasp-stats/jasp-issues/issues/875
alle citation issues now there
