### ISSUE TITLE
cannot install software

### ISSUE THREAD

**Issue by catalinah12** [jasp-stats/jasp-issues#1400]
* JASP version: 0.14.1-64 bit

* OS name and version: Windows 10
* Analysis: Home network works just fine, yet software won't download due to "network issue"
* Bug description: couldn't download- network issue
* Expected behaviour: Will download about 1/4 of the way, then fail to download rest of the software even when network is working completely fine

**Comment by boutinb** [comment]
Strange, I have just tried to download the file, and it works in 2 minutes (300 MB). I have put this file in wetransfer: https://we.tl/t-dAUUmmMvSI
Maybe the network connection with wetransfer is better.

**Comment by catalinah12** [comment]
> Strange, I have just tried to download the file, and it works in 2 minutes (300 MB). I have put this file in wetransfer: https://we.tl/t-dAUUmmMvSI
> Maybe the network connection with wetransfer is better.

Hi, thanks for the help. The connection with wetransfer definitely worked. I managed to download the software and it's installing at the moment. Thanks again!
