### ISSUE TITLE
Changing datatype of the column

### ISSUE THREAD

**Issue by MalavikaSunil** [jasp-stats/jasp-issues#1401]
* Purpose: change the datatype from nominal to ordinal
* Use-case: I have to change it to this scale in order to produce mean, median and mode.

I want to change the data type of my variable from nominal to ordinal. I have tried hovering the mouse and changing but it does not change. I am not understanding what is going on.

Please provide a solution to change from nominal to ordinal so that I can produce the results for the descriptives.

![image](https://user-images.githubusercontent.com/89886678/131599664-58b24d32-e19b-4d73-8d94-a607095892d1.png)

**Comment by vandenman** [comment]
First of all, it is rather meaningless to compute the mean of entirely categorical input, such as `{""ImportId"":""QID3_2""}` and `Describe yourself as ...`. 

I take it that you want to convert the text values `Agree` and `Neutral` (and perhaps `Disagree`?) to numeric?

It should indeed be easier to do this. Here's a workaround for now. In the example below, I'll use our debug data set and change the nominal text variable `debString` to ordinal but it should also work for your data.

1. Create a new column by clicking on the black + in the top right corner of the data view: 
![image](https://user-images.githubusercontent.com/21319932/131629036-9001e5c0-1caf-4ab1-b9e4-84080555acb6.png)

2. Select ordinal, R-code, and give the column a name. Then click `Create column`:
![image](https://user-images.githubusercontent.com/21319932/131629175-af4084d0-b0f4-445a-b874-b33c0d556099.png)

3. Type `factor(A_1)` to turn the variable in your screenshot into an ordinal variable. Click on `Compute column` to run the code.
![image](https://user-images.githubusercontent.com/21319932/131629300-f5fdec24-6676-4c9a-8ca3-3f4f73c0e914.png)

Now you can use the new column in your analyses. You can still rename and reorder the levels by clicking on the name of the variable:
![image](https://user-images.githubusercontent.com/21319932/131629526-202cb2f5-2326-4e2b-9711-0788dd53d1dd.png)

Here you can also see that the label `a` is assigned the value 1 and `b` is assigned the value 2.

Let me know if that solves the issue!
