### ISSUE TITLE
Program won't open

### ISSUE THREAD

**Issue by armsgeor** [jasp-stats/jasp-issues#1405]
* JASP version: I have tried Catalina and Mojave version and the 9.2 version. 

* OS name and version: High Sierra 10.3
* Analysis: I can download Catalina and Mojave version but they won't open, the app verifies then when I click open the app from the dock disappears and nothing opens. 
* Bug description: 
* Expected behaviour:

**Comment by boutinb** [comment]
Hi @armsgeor We have a version that should work for High Sierra, and it the one with the button 'Mojave & High Sierra'. After starting the dmg file, you should copy it into the Application folder. There it should not disappear.
FYI: High Sierra is not supported by Apple anymore, so we won't probably support High Sierra for our next release. It is anyway highly recommended not to stay on a not supported OS version: you don't get patches anymore for security breach.

**Comment by armsgeor** [comment]
Hi,So I copied it into the application folder. It still won't open. The application bounces in the dock while its verifying then when the window pops up asking if I want to open I click open there is a pause and the JASP application disappears from the dock and nothing ever opens.

**Comment by boutinb** [comment]
> Hi,So I copied it into the application folder. It still won't open. The application bounces in the dock while its verifying then when the window pops up asking if I want to open I click open there is a pause and the JASP application disappears from the dock and nothing ever opens. 

But is JASP still in the Application folder? If yes, can you click on it?

**Comment by juliuspf** [comment]
I will close this since the latest JASP version does not support your OS anymore.
