### ISSUE TITLE
I am attempting to download JASP on my Macbook Air Version 10.14.6,  but when I click the application the popup below comes up. I attempted to use the web browser, but that will also not work and freezes when I attempt to open a document on my laptop. Please advise.

### ISSUE THREAD

**Issue by alexa619** [jasp-stats/jasp-issues#1406]
* JASP version: 

* OS name and version: MAC 10.14.6
* Analysis: I am attempting to download JASP on my Macbook Air Version 10.14.6,  but when I click the application the popup below comes up. I attempted to use the web browser, but that will also not work and freezes when I attempt to open a document on my laptop. 
<img width="519" alt="Screen Shot 2021-09-06 at 11 08 58 AM" src="https://user-images.githubusercontent.com/90205020/132236982-eecd8514-9d29-4e78-b22f-a6f3383b90fc.png">

* Bug description:  File will not upload.
* Expected behaviour:

**Comment by boutinb** [comment]
Hi @alexa619 I don't understand exactly what you do. JASP is not a web application, it does not work on a webbrowser. You have to download the 'Mojave & High Sierra' version, start the downloaded dmg file, copy the JASP app to the Applications folder, and then click on the JASP icon in the Application folder? You get maybe a warning because it is an app downloaded from the internet.

**Comment by amirmasoudabdol** [comment]
Hi @alexa619, would you please send a screenshot of the same dialog again but this time press the "Show Details" and then take the screenshot. I'm interested to see what kind of information is provided by Apple. If there are a lot of text in there, please copy and paste it here that we can read. I'm not sure, but maybe there is some more information there that could help us understand the problem.

**Comment by alexa619** [comment]
[cid:f0a4868d-8cc8-400c-ba32-58c899da66cd]
________________________________

**Comment by boutinb** [comment]
Hi @alexa619 We cannot see the image on GitHub. If you want to show a picture, please use the GitHub website and drag & drop the picture in a comment of this issue.
