### ISSUE TITLE
Problems with mac High Sierra 10.13.16

### ISSUE THREAD

**Issue by JeffS1984** [jasp-stats/jasp-issues#1408]
* JASP version: 0.14 and 0.9.2

* OS name and version: High Sierra 10.13.16
* Analysis: I have a student who tries to open JASP, and it immediately quits unexpectedly.  I see on this message board that this issue was raised in July 2020 (#885). Should I have the student try a different version of JASP, like 0.11 or something? Thank you!
* Bug description: 
* Expected behaviour:

**Comment by boutinb** [comment]
Hi @JeffS1984 High Sierra is not supported anymore by Apple anymore, so we will end the support of this version also with our next release. It is also highly recommended not to stay on a OS version which is not supported: any security breach won't be fixed anymore.
But JASP 0.14.1 used to work on High Sierra (at least if the right dmg file was downloaded from our website, called JASP-0.14.1.0-preCatalina.dmg). Was the JASP app copied to the Application folder?

**Comment by JeffS1984** [comment]
Thank you boutinb! The student has tried everything 0.9-0.14. He seems pretty good with a computer so I don't think he is doing anything weird. I may just give him alternative assignments not using JASP.

**Comment by juliuspf** [comment]
Since we do not support the OS anymore, I will close this issue. Feel free to reopen if your issue has not been addressed properly.
