### ISSUE TITLE
Compile error on Linux: Missing #include for constants?

### ISSUE THREAD

**Issue by JoKeyser** [jasp-stats/jasp-issues#1410]
When I try to compile current `development` (commit `fe9e83473ec512806d821dc495d48c373bbe5ccf`) on Linux, I get errors about undeclared identifiers `DBL_MAX`, `DBL_EPSILON`, and `FLT_EPSILON`.

This is easy to fix by `#include <float.h>`, or maybe another include... I'm not sure though where to put it best, or if it should be included only for Linux, so I don't propose a PR.

**Comment by vandenman** [comment]
@JoKeyser what version of GCC do you have? Recently, @JMBKoch had the same issue while compiling. I believe that adding `#include <cfloat.h>` fixed the issue for him though.

**Comment by JMBKoch** [comment]
@JoKeyser @vandenman I can confirm that this was the fix in my case.

**Comment by JoKeyser** [comment]
@vandenman , I'm trying GCC version 11.1.0 on Arch Linux.

To be more precise, inserting `#include <float.h>` into file [`utils.h`](https://github.com/jasp-stats/jasp-desktop/blob/development/Common/utils.h) resolves the error.
If I replace that with `#include <cfloat.h>`, I get an error to "'cfloat.h' file not found".
When I try `#include <cfloat>` (note missing `.h`), it also compiles fine.

Not sure if there are any tradeoffs to make here.

**Comment by vandenman** [comment]
I think `<cfloat>` is the c++ version of `<float>`, which is a c header. But either one should be fine.

**Comment by vandenman** [comment]
but this seems to be a GCC 11 issue (JMBKoch has the same version, also on Arch) because older versions (e.g., GCC 9.3) do not need this header to be included.

**Comment by amirmasoudabdol** [comment]
I think we can probably eliminate this issue by using the [numeric_limits](https://en.cppreference.com/w/cpp/types/numeric_limits) interface, and move away from macros. The `<limits>` header can be universally used as long as the compiler meets the selected standard. I think most floating limits are available from C++11 onward.

**Comment by JoKeyser** [comment]
@amirmasoudabdol , the parts that I understand sound promising :D. I'm happy to test a branch with that idea...

**Comment by amirmasoudabdol** [comment]
That'd be great! I just pushed a branch to address this. I hope it works! 🙏🏼

**Comment by vandenman** [comment]
@amirmasoudabdol this can be closed now right?
