### ISSUE TITLE
JASP crashes when creating a computed column

### ISSUE THREAD

**Issue by BubblesTheBomb** [jasp-stats/jasp-issues#1411]
* JASP version: 0.14.3
* OS name and version: Manjaro Linux; Build ID: rolling GNOME Version: 3.38.3
* Analysis: 
* Bug description: [birthWeight(1).zip](https://github.com/jasp-stats/jasp-issues/files/7129220/birthWeight.1.zip)
* Expected behaviour:

#### Steps to reproduce:
1. Go to add column
2. Create a computed Column
3. Multiply Mother's body mass by 0.46
4. Press Compute Column
5. See error (CPU spikes and then the application crashes)

**Comment by JoKeyser** [comment]
I can reproduce this on Ubuntu 20.04.3 and JASP 0.14.3.
(To use the data, I had to rename the extension `.zip` to `.jasp`.)
More importantly, it's independent of that data set - if I just load the sleep data from the data library and compute a column, it crashes the same way.
The last message from JASP is:
```
So the entire column had a change? yes
```

**Comment by lentilha** [comment]
I have the same problem using Ubuntu 20.04.3
JASP also crashed after I computed the new column externally and uploaded the new dataset and tried to plot the data computed in the new column

**Comment by JorisGoosen** [comment]
Ok, it seems that the Qt we are using broke JASP, so a workaround for now is:
`flatpak update --commit 4f232783b07952a4627a186c8020a362d2458c4b2d6046fbd0b43d3f44c551a7 org.kde.Sdk/x86_64/5.15`
After that JASP should work fine.

Once [this issue at kde](https://bugs.kde.org/show_bug.cgi?id=442422) is resolved I can actually debug what is wrong with it, but I am assuming that having a new version of the runtime might already fix it.

**Comment by JoKeyser** [comment]
@JorisGoosen , the workaround works for me, both on stable and beta, albeit with another commit, as you corrected already in #1360, i.e. after 
`flatpak update --commit=212d267860a3001081816007b074dd57993335aec23485c082d40034c6a5b857 org.kde.Platform/x86_64/5.15`.

**Comment by periklesfc** [comment]
Hi,

I encountered the same problem as described above but using Ubuntu 21.10

Do yo u have any advice about how to fix it?

thanks a lot in advance

**Comment by JoKeyser** [comment]
@periklesfc , did you try the workaround in the [comment above yours](https://github.com/jasp-stats/jasp-issues/issues/1411#issuecomment-919349063)?
For me that workaround still works in JASP version 0.16 on Ubuntu 20.04.3 LTS.

**Comment by periklesfc** [comment]
Yes, I did the following:

- Uninstall JASP
- Run: flatpak update --commit=212d267860a3001081816007b074dd57993335aec23485c082d40034c6a5b857 org.kde.Platform/x86_64/5.15
- Reinstall JASP
- Try to compute a column

But the programme crashed anyway. It caught my attention that, despite of uninstall and reinstall JASP, when I opened it again automatically charged the same database at the same screen it was when I uninstalled it. Dont know if this info has any utility, but just in case.

**Comment by JoKeyser** [comment]
@periklesfc , can you try again, just running the `flatpak update` command?
(That is, **after** JASP is installed; there is no need to uninstall JASP either.)

I believe by uninstalling first and re-installing afterwards, you effectively changed nothing.

**Comment by periklesfc** [comment]
Bingo!

Now it works (does not crash when computing a column).

Thank you very much :)

**Comment by JorisGoosen** [comment]
> I notice that when I install JASP, some action regarding org.kde.Platform is performed as well, I hope it doesn't automatically undo what was done in step 1. 

Yeah it does... 

> I also note the message
> >    Note that '/var/lib/flatpak/exports/share' is not in the search path set by the XDG_DATA_HOME and XDG_DATA_DIRS environment variables, so applications may not be able to find it until you set them.
> which may be related to the issue, but it's unclear what to make of it (see below for the full output).

No it isn't, it's because you use Ubuntu and it lacks that setting by default. See https://unix.stackexchange.com/questions/471327/whats-the-right-way-to-add-directories-to-xdg-data-dirs for some information on how to set it.
It will be useful also when you install other flatpaks, this way they will show up in menus etc.

As for the crashing, after youve installed/updated JASP you have to run the fix in https://github.com/jasp-stats/jasp-issues/issues/1424
