### ISSUE TITLE
This analysis terminated unexpectedly.  Error in lavaan::lavTestLRT(semContainer[['semResultsList']]$object$semResults): lavaan ERROR: model did not converge  Stack trace

### ISSUE THREAD

**Issue by pass202** [jasp-stats/jasp-issues#1412]
Hey Guys! I need your help! This is my written syntax, but JASP ends the analysis!
Can you help me or does someone see the problem?

* Measurmentmodel
HH =~ HH1 + HH2 + HH3 + HH4 + HH5 + HH6 + HH7+ HH8+ HH9+ HH10
AG =~ AG1 + AG2 + AG3 + AG4 + AG5 + AG6 + AG7+ AG8+ AG9+ AG10
EM =~ EM1 + EM2 + EM3 + EM4 + EM5 + EM6+ EM7+ EM8+ EM9+ EM10
IM =~ IM1 + IM2 + IM3
RD =~ RD1 + RD2 + RD3
RU =~ RU1 + RU2 + RU3
AB =~ AB1 + AB2 + AB3 + AB4 + AB5 + AB6
BE =~ BE1 + BE2 + BE3 + BE4 + BE5
IN =~ IN1 + IN2 + IN3 + IN4 + IN5 + IN6
WS =~ WS1 + WS2 + WS3 + WS4 + WS5 + WS6
* Structural model
IM ~ HH + AG + EM
RD ~ HH + AG + EM
RU ~ HH + AG + EM
AB ~ IM + RD + RU + HH + AG + EM
BE ~ IM + RD + RU + HH + AG + EM
IN ~ IM + RD + RU + HH + AG + EM
WS ~ HH + AG + EM+ IM + RD + RU + AB + BE + IN

**Comment by vandenman** [comment]
Hi @pass202 could you perhaps share the dataset or jasp file that led to the error?
