### ISSUE TITLE
Error with custom contrasts

### ISSUE THREAD

**Issue by hcsmith1123** [jasp-stats/jasp-issues#1414]
* JASP version: 0.14.1

* OS name and version: MacOS
* Analysis: Repeated Measures ANOVA 
* Bug description: 
*
<img width="863" alt="Screen Shot 2021-09-09 at 7 35 06 AM" src="https://user-images.githubusercontent.com/90391871/132679233-1acb7349-8791-4637-af5f-4ea5d85d8c96.png">

* Expected behaviour:

**Comment by boutinb** [comment]
HI @hcsmith1123 Could you describe precisely what you do (which options you click) before getting this error? Wuould it possible to get also the data you use, or even the JASP file? For this you have to zip it, and drag & drop it in a new comment of this issue in GitHub.
