### ISSUE TITLE
p-values into the weights matrix of the network analysis

### ISSUE THREAD

**Issue by SirOttomano** [jasp-stats/jasp-issues#1416]
* Enhancement: Hi, I would ask you if it is possible to add the p-values into the weights matrix of the network analysis. When this matrix is computed by using the option "cor_auto" (because I have a database made by continuous, binary and ordinal variables), I cannot know the exact correlation method applied; thus,  I cannot compute the p-value with JASP neither by using another software.
* Purpose: identify and analyse the relationships among the factors influencing the real estate market.

**Comment by tomtomme** [comment]
@SirOttomano 
Thx for the request. Can you clarify a point?
You want "to add the p-values into the weights matrix of the network analysis"
And at the same time you "cannot compute the p-value[s]" because of unknow correlation methods used.
So how can we help exactly?
