### ISSUE TITLE
Undefined columns selected

### ISSUE THREAD

**Issue by zijunke** [jasp-stats/jasp-issues#1418]
* JASP version: 0.14.1.0

* OS name and version: Windows 11 (Surface)
* Analysis: Binomial Estimation using Learn Bayes
* Bug description:  The analysis terminated when we dragged the levels of a binary variable to the Sucesses or Failures boxes.
Error message returned "Error in '[.data.frame'(.readDataSetToEnd(columns = options[['selectedVariable']]), : undefined columns selected
Stack trace"

* Expected behaviour:

**Comment by boutinb** [comment]
Hi @zijunke Could you give your JASP file?
