### ISSUE TITLE
Variable types (icons) change in marginal means (ANOVA)

### ISSUE THREAD

**Issue by JohnnyDoorn** [jasp-stats/jasp-issues#142]
* JASP version: development 
* OS name and version: Ubuntu 16.04
* Analysis: ANOVA
* Steps to reproduce: any ANOVA dataset - add some factors and DV, then go to marginal means analysis.

See attached screenshot - for some reason JASP lists different variable types (icons) under the marginal means analysis.
![changedvartypes](https://user-images.githubusercontent.com/15704203/37163447-1a4a3228-22f8-11e8-94c8-3ea62be000bb.png)
[varTypeChange.zip](https://github.com/jasp-stats/jasp-desktop/files/1793960/varTypeChange.zip)

**Comment by JorisGoosen** [comment]
Already fixed
