### ISSUE TITLE
Incomplete translation does not work

### ISSUE THREAD

**Issue by icekylin** [jasp-stats/jasp-issues#1420]
After this commit [#4623](https://github.com/jasp-stats/jasp-desktop/pull/4623) the Chinese and Spanish Select languages  can not work.
I tried to the daily build（zip package）, and the language of the JASP interface cannot be selected from Chinese and Spanish.
Maybe even if the translation file is incomplete, we can make it available, which will be beneficial to both localized translators and users

**Comment by AlexanderLyNL** [comment]
Thanks for the report. For me the same issue, neither, Chinese nor Spanish are working for me, but Japanese and English is working. Settings:

**OS**
macOS 11.5

**Commit**
https://github.com/jasp-stats/jasp-desktop/commit/184c617e27177e72f7467c622b1e98b90fe7188f

**Comment by icekylin** [comment]
Whether the latest news about this bug？
