### ISSUE TITLE
Add Weblate link to README

### ISSUE THREAD

**Issue by ovari** [jasp-stats/jasp-issues#1425]
Should the correct link be added to the [README.md](https://github.com/jasp-stats/jasp-issues) file?

Do all the files at https://hosted.weblate.org/projects/jasp/ need to be translated or just https://hosted.weblate.org/projects/jasp/jaspdesktop/?

What do you think?

Thank you

**Comment by ovari** [comment]
Sorry for the noise. It is already there at https://hosted.weblate.org/projects/jasp/

**Comment by ovari** [comment]
Should the correct link be added to the README file?

Do all the files at https://hosted.weblate.org/projects/jasp/ need to be translated or just https://hosted.weblate.org/projects/jasp/jaspdesktop/?

Thank you

**Comment by AlexanderLyNL** [comment]
You raise a fair point. The translation guides can be found in our main repository and not in our issue repository, see the bottom of https://github.com/jasp-stats/jasp-desktop/ and https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/development/jasp-guideline-translators.md in particular. The latter guide, written by Johannes Keyser, can also be found here https://jasp-stats.org/translation-guidelines/. The last link is referred to in JASP itself, when selecting a language, so we thought that it would be relatively easy to find.

**Comment by ovari** [comment]
Thank you for your links.
