### ISSUE TITLE
The "developer cannot be verified" Issue on macOS

### ISSUE THREAD

**Issue by reichsatcwu** [jasp-stats/jasp-issues#1426]
* JASP version: .15.0.1 whatever is on your site this evening. 

* OS name and version: Big Sur 11.4

MacOS refuses to open the file once it's in the applications folder because "developer cannot be verified" that there is no malware. There is no way to bypass this. 

<img width="256" alt="Screen Shot 2021-09-22 at 9 33 19 PM" src="https://user-images.githubusercontent.com/91240016/134456203-82a3b1ce-3c1e-4915-8093-312a30c71102.png">

**Comment by amirmasoudabdol** [comment]
We are aware of this issue and working on a fix for it. For now, you can follow this instruction:

> To install JASP, please do the following:
> 1. Right click JASP-0.15.0.0.dmg and select “Open”
> 2. Move JASP to your Application folder
> 3. Go to your Application folder
> 4. Right click JASP and select “Open”
> 5. A notification appears noting that the developer cannot be verified, select “Open”
> 6. Right click JASP and select “Open” again

**Comment by reichsatcwu** [comment]
Thank you for the help. I didn't have the option to override yesterday and do now. Everything is up and running! 

In case anyone else searches this issue: I updated to the newest Big Sur v. 11.6 last night.

**Comment by mmarikar** [comment]
I'm on MacOS Catalina 10.15.7
I overcame the [The "developer cannot be verified" Issue on macOS](https://github.com/jasp-stats/jasp-issues/issues/1426#) by doing he following:
1. System Preferences
2. Security and Privacy
3. Enable the app when the message appears

**Comment by tomtomme** [comment]
A student of mine just told  me the following solution works for macOS monterey:
https://support.apple.com/de-de/guide/mac-help/mchleab3a043/mac

**Comment by boutinb** [comment]
We are also about to release a version that should solve this problem. You can try a beta version here: http://static.jasp-stats.org/Nightlies/macOS-x86_64/JASP-nightly-stable-ff3de5165ae037a16afd7d04bfb5a01823be68e1.dmg

**Comment by amirmasoudabdol** [comment]
Closed by https://github.com/jasp-stats/INTERNAL-jasp/issues/1629!
