### ISSUE TITLE
Failed update on Pop!_OS

### ISSUE THREAD

**Issue by Veelgehoord** [jasp-stats/jasp-issues#1427]
* JASP version: 0.15.0
 Linux (Pop!_OS)
* Analysis: Update halts
* Bug description: flatpak update gives an error
* Error: app/org.jaspstats.JASP/x86_64/stable is not available

**Comment by oguzkarayemis** [comment]
This worked for me.
First remove the current installation: `flatpak remove org.jaspstats.JASP`
Second reinstall with this command: `flatpak install flathub org.jaspstats.JASP`

**Comment by jbingram** [comment]
Error: While pulling app/org.jaspstats.JASP/x86_64/stable from remote flathub: Server returned status 404: Not Found

**Comment by tomtomme** [comment]
I can confirm this. JASP installs only from flathub-beta, not from flathub-stable

**Comment by vandenman** [comment]
@Veelgehoord could you try `flatpak repair`?

See also https://github.com/jasp-stats/jasp-issues/issues/1424#issuecomment-930030925

**Comment by tomtomme** [comment]
repair did something... needed to deinstal both after and installed stable only. That fixed it.

**Comment by jbingram** [comment]
Weird. The procedure "remove JASP stable -> repair ->  install" was not working this morning and yesterday on 3 computers.
Just retried now and everything works on all computers.
NB: I had no beta version installed

**Comment by juliuspf** [comment]
@Veelgehoord, could you try with the latest release?

**Comment by tomtomme** [comment]
this was no issue for me during the last at least 2 releases. I think this can be closed

**Comment by juliuspf** [comment]
I appreciate your involvement @tomtomme, but replying to the bots stale-announcement for issues that can be closed will only lead to the bot removing the stale label, and the issue will eventually not be closed :) Please only reply to the bot's stale-message if the issue should not be closed.
