### ISSUE TITLE
[Feature Request]: Translation to code (Python, R) from analyses

### ISSUE THREAD

**Issue by kc2nc90** [jasp-stats/jasp-issues#1428]
* Enhancement: Translation to code (Python, R) from analyses
* Purpose: Support developing coding skills along side data analysis skills

**Describe the solution you'd like**
Perform data analysis and see behind the curtain for how the coding that runs the analysis looks. Thanks for your work!

**Comment by kc2nc90** [comment]
Edge Centrality in Network Analysis-- cannot resize to read list. Thanks for any guidance!

Would love eigenvector centrality option for network analysis.  Thanks for your excellent work!

**Comment by juliuspf** [comment]
An upcoming release will have the option to get the underlying R code. I doubt that we will also translate to Python though, @Kucharssim?

**Comment by Kucharssim** [comment]
We do not plan to translate our analysis code to Python atm.

We do indeed plan to release a syntax mode for R, which will provide a convenient R interface to JASP analyses. However, this feature does not provide step-by-step instructions how to carry out an analysis in R, instead it will enable you to carry out the whole analysis with "one line of code". If one wants to "look behind the curtain" to know in detail how it's done one step at a time, it's possible to do so now: our code is open source and everyone can read it :)

**Comment by tomtomme** [comment]
R-Syntax output is done since JASP 0.17
This can be closed
