### ISSUE TITLE
Descriptives: Percentiles cannot be negative. Please add lower bound to the UI

### ISSUE THREAD

**Issue by AlexanderLyNL** [jasp-stats/jasp-issues#1429]
**Operating system:**
macOS 11.5 Big Sur

**Commit ID:**
https://github.com/jasp-stats/jasp-desktop/commit/f6ba93bde91dcf36e936e64603a8c541545d0987

**JASP file / screenshot:**
<img width="2352" alt="Screenshot 2021-09-16 at 00 10 48" src="https://user-images.githubusercontent.com/10271675/133516690-c6eb76a7-6b5a-4b9a-9a7d-1f581e442f87.png">

https://www.dropbox.com/s/rell9f5kpljbv2a/plotEdit2.jasp?dl=0

**Bug description**
- Percentile -2

**Steps to reproduce**

**Expected behaviour**

**Comment by tomtomme** [comment]
Can still enter negative percentiles with jasp 0.18.3
Error message is slightly more informative however.

`"Error in Percentiles, all values should >=0 and <=100"`

@shun2wang 
So I guess this could be closed?
