### ISSUE TITLE
GUI problem under high DPI

### ISSUE THREAD

**Issue by usamakh** [jasp-stats/jasp-issues#143]
* JASP version: Version 0.8.6
* OS name and version: Win10 x64

My screen is high-dpi 12in ....& when I upgraded JASP this weekend from previous release all the buttons & the GUI became too much zoomed. This wasn't the problem with previous release
[http://prntscr.com/irrrde](http://prntscr.com/irrrde)

From context menu I have tried disabling scaling under highDPI setting

**Comment by JorisGoosen** [comment]
We are converting all of the GUI to something called QML which gives us a lot of control on the rendering of the user interface.

Part of this will be a user-changeable setting that will scale the entire interface uniformly.

**Comment by JorisGoosen** [comment]
The next release 0.10.0 will fix this.
