### ISSUE TITLE
Number of observations is <2 in Mean Speed on subject

### ISSUE THREAD

**Issue by shelbyf8** [jasp-stats/jasp-issues#1432]
* JASP version: Jasp 0.15.0.0
 windows
* OS name and version: windows 10 home
* Analysis: anova 
* Bug description: 
* Expected behaviour: it won’t let me complete my anova test. 
![Uploading image.jpg…]()

**Comment by shelbyf8** [comment]
![Uploading image.jpg…]()
 
This is my data.

**Comment by vandenman** [comment]
@shelbyf8 did you mean to upload your data? Also, what analysis did you run, and with what options? 

As an aside from that, it's not possible to conduct a Repeated Measures ANOVA with fewer than 2 observations after grouping on subject.

**Comment by shelbyf8** [comment]
I’m running a classical anova, not a repeated measures anova. I’m honestly not even sure if this is right, it’s for one of my classes but I’ve never done anything like this. I appreciate your response.

**Comment by vandenman** [comment]
@shelbyf8 could you share the jasp file? In order to upload it, you have to zip it first. Note that your previous attempt didn't succeed (you may have to wait until the upload completes before clicking comment).
