### ISSUE TITLE
JASP won't start

### ISSUE THREAD

**Issue by Lokis123** [jasp-stats/jasp-issues#1433]
* JASP version: 0.14.1
* OS name and version: Windows 10 Enterprise, 21H1
* Analysis:
* Bug description: JASP won't start after install. After enabling logging to %USERPROFILE% the log 'JASP <date> <time> Desktop.log' appears. It contains only "interprocess exception! No access". I have limited rights/access to this machine, but what is JASP trying to access?.
* Expected behaviour: App to open as normal.
[JASP 2021-09-27 14_33_48 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/7236289/JASP.2021-09-27.14_33_48.Desktop.log)

**Comment by JorisGoosen** [comment]
It sounds like the boost shared memory fails to create the required files, might be related to what @boutinb talks about in https://github.com/jasp-stats/jasp-issues/issues/1302#issuecomment-849666054

**Comment by JorisGoosen** [comment]
He mentions that the docs of boost say: ```
In those platforms, shared memory is emulated with mapped files created in a "boost_interprocess" folder created in a temporary files directory. In Windows platforms, if "Common AppData" key is present in the registry, "boost_interprocess" folder is created in that directory (in XP usually "C:\Documents and Settings\All Users\Application Data" and in Vista "C:\ProgramData"). For Windows platforms without that registry key and Unix systems, shared memory is created in the system temporary files directory ("/tmp" or similar).
```

So it probably fails to create that particular file, maybe you dont have write permissions there?

**Comment by Lokis123** [comment]
It seems you are right! I have been given write permissions to the folder %ALLUSERSPROFILE%\boost_interprocess, and the app started properly! I encountered another error after this (regarding the lack of a driver for OpenGL or something), but that was temporarily solved through starting JASP with 'JASP --safeGraphics'. 
Thank you so much for following up on this as fast as you did!

**Comment by boutinb** [comment]
What a good news! It is also good for us to know this.
