### ISSUE TITLE
several suggestions

### ISSUE THREAD

**Issue by NikitaKhromov-Borisov** [jasp-stats/jasp-issues#1437]
Please remove, finally, once and for all the spaces between e and the exponent like 9e-6, but not 9e{space]-6!.

It is illogical to present confidence intervals for marginal means in ANOVA, but not when comparing two samples.

Present confidence intervals for Cohen's d in ANOVA, not only for t-test.  

The greatest misconception is to calculate phi in contingency tables only for 2x2 tables.

For all contingency coefficients, the confidence intervals should be calculated.

Your bootstrap is working extremely abnormally slow.

Compare with the PAST software (https://www.nhm.uio.no/english/research/infrastructure/past/) where I can easily run 1 million bootstraps.

Attached are my proposals for the templates for the presentation of the results. 
[Templates.docx](https://github.com/jasp-stats/jasp-issues/files/7247010/Templates.docx)
Nikita Khromov-Borisov

**Comment by tomtomme** [comment]
some of those issues are already raised in separate issues. If you want someone to look into yours, you need to file one issue at a time and check before which ones are already raised.

**Comment by NikitaKhromov-Borisov** [comment]
Sorry me, but
If you are really interested in improving the program, then please organize
the communication so that it would be convenient for the user.
Best regards,
Dr. Nikita Khromov-Borisov

ср, 29 сент. 2021 г. в 18:23, Thomas Langkamp ***@***.***>:

**Comment by EJWagenmakers** [comment]
Hi Nikita,

Thanks for your suggestions; we realize these are freely given, and we do appreciate them. We are already working to address several (@amirmasoudabdol, you were looking at improved formatting for scientific notation I believe; @FBartos, can you add the comment on phi to the project "more love for contingency tables"? ). I'll have to look into some of the others. If you want to help us still more, I do agree with Thomas that it is easier to create separate posts for each issue -- this makes it easier to assign them to a team member with the most expertise, it facilitates communication, it allows us to mark the completed suggestions as done, and it makes it more appealing for other users to up-vote your specific suggestions. But, as I said, we gratefully acknowledge your suggestions and we'll look at them more closely. @AlexanderLyNL @JohnnyDoorn maybe you can take a look as well.

Cheers,
E.J.

**Comment by tomtomme** [comment]
> Sorry me, but If you are really interested in improving the program, then please organize the communication so that it would be convenient for the user. Best regards, Dr. Nikita Khromov-Borisov 

I apologize for my original comment, it sounded rude in hintsight. 
You are certainly right, that it could be easier for us users to raise issues. To organize issue-communication in another way JASP would need to switch the platform - a huge undertaking. I just wanted to point out, how you could improve your way to help - and yes, it is great that you want to help in the first place!

**Comment by tomtomme** [comment]
@NikitaKhromov-Borisov 
Could you check if the remaining bootstrap issue is still valid? If so, it might only be solvable on the R side.

**Comment by NikitaKhromov-Borisov** [comment]
Your bootstrap is working extremely abnormally slow.

Best regards,

Dr. Nikita Khromov-Borisov
Independent Researcher
Saint Petersburg, Russia

Commission on Pseudoscience
Russian Academy of Sciences (RAS)
RUSSIA


чт, 11 апр. 2024 г. в 17:53, Johnny van Doorn ***@***.***>:

**Comment by tomtomme** [comment]
@NikitaKhromov-Borisov 
Thx for the update. 
I cannot run PAST, since Win/Mac only, and cannot inspect the code, since not open source - but its free! Nice. So current / working link if someone from the team (@shun2wang @JohnnyDoorn) can check it out:
https://www.nhm.uio.no/english/research/infrastructure/past/

The PAST manual (https://www.nhm.uio.no/english/research/resources/past/downloads/past4manual.pdf) suggests that one can choose  between "simple (basic)" bootstrap and "BCa (adjusted percentile method)". So we have to be careful to compare apples to apples here. Which method did you try and which method did JASP use? Afaik JASP uses BCa as default in most modules, but in some you can also switch. 
Maybe BCa is computationally more intense?

@NikitaKhromov-Borisov:
Can you please send the data set with which you benchmarked the bootstrap and which analysis and settings you used and how long JASP and PAST needed? That would be very helpful!

**Comment by shun2wang** [comment]
There is so little information available to know what happend. that it is recommended to create separate issues to track rather than tracking different requirements under the closed issue:-)

**Comment by tomtomme** [comment]
1 second does not sound possible, does it? Unless past does not really bootstrap 99999 times

**Comment by tomtomme** [comment]
So besides that - does anyone from the team have an idea why our bootstrap is so slow - because I also think it could be faster even if the expectation of being as fast as PAST may not be reasonable. 
And if we know, why it is slow, can we fix it or does this need to be fixed in the used R-packages?

**Comment by JohnnyDoorn** [comment]
Perhaps @vandenman knows more about the technical details and how there can be such a difference.

**Comment by NikitaKhromov-Borisov** [comment]
Why not ask Oyvind Hammer, the author of PAST?
His email
***@***.***

Best regards,
Nikita


пн, 15 апр. 2024 г. в 16:36, Johnny van Doorn ***@***.***>:

**Comment by NikitaKhromov-Borisov** [comment]
Maybe the attached material would be useful

Best regards,
Nikita


пн, 15 апр. 2024 г. в 17:31, Nikita Khromov-Borisov <
***@***.***>:

**Comment by NikitaKhromov-Borisov** [comment]
Best regards,
Nikita


---------- Forwarded message ---------
От: Olivier Scaillet ***@***.***>
Date: ср, 1 мая 2024 г. в 09:27
Subject: Re: [EXTERNAL]
To: Nikita Khromov-Borisov ***@***.***>


Hi Here they are.



[image: 1603985063783]

*Olivier Scaillet*
Professor

Senior chair SFI

Pgm chair EEA-ESEM 2024

GFRI Director

*GFRI and Swiss Finance Institute*

Office UniPignon 421 | +41 22 379 88 16
40 bd du Pont d'Arve | CH - 1211 Geneva 4

Skype: olivier_scaillet
Please visit my Home Page, our MOOC and SPOC!
https://scaillet.ch

https://www.coursera.org/specializations/investment-management

https://www.unige.ch/formcont/cours/spoc-marches-financiers





*From: *Nikita Khromov-Borisov ***@***.***>
*Date: *Tuesday, 30 April 2024 at 19:47
*To: *Olivier Scaillet ***@***.***>
*Subject: *[EXTERNAL]


Dear Author(s),


please, send me your paper(s):



Davide La Vecchia, Alban Moor, Olivier Scaillet,
A higher-order correct fast moving-average bootstrap for dependent data,
Journal of Econometrics,
Volume 235, Issue 1,
2023,
Pages 65-81,
ISSN 0304-4076,
https://doi.org/10.1016/j.jeconom.2022.01.008.

Best regards,

Dr. Nikita Khromov-Borisov

Independent Researcher

Saint Petersburg, Russia



Commission on Pseudoscience
Russian Academy of Sciences (RAS)
RUSSIA



*Ce message est envoyé depuis une adresse extérieure à l’UNIGE, soyez
vigilant-es (**expéditeur, pièces jointes).*
*This message is sent from an address outside UNIGE, be careful (sender,
content).*
------------------------------

**Comment by tomtomme** [comment]
Thx nikita. But we email attachements are automatically stripped. We cannot see them.

**Comment by tomtomme** [comment]
@NikitaKhromov-Borisov 
Again - we did not get your attachements, because you did send them via mail. Please drag and drop them here, if you still consider this an issue.
Regarding PAST and asking Oyvind Hammer: Again, PAST is not open source. If Oyvind Hammer would grant us access to his bootstrap code, some R maintainer would need to port this. So this is probably not directly fixable by us I guess. We depend on many R packages and can only maintain a fraction of those ourselves.

Nevertheless I wrote Oyvind Hammer now this eMail:

> Dear Oyvind Hammer,
> 
> I am working with the JASP team on an issue to speed up our bootstrap if possible, see discussion:
> https://github.com/jasp-stats/jasp-issues/issues/1437
> 
> A user praised PAST for its fast bootstrap and I wonder, if you could shed any light on this and/or share code. Maybe it is portable to JASP which is build on R.
> 
> Thx!
> Thomas
> --
> 
> https://www.zotero.org/thomas_langkamp
> https://www.youtube.com/@StatisticsSupreme

**Comment by tomtomme** [comment]
@NikitaKhromov-Borisov 
This is Øyvind very helpful answer! He allowed me to share it here:

> Hello Thomas!
> 
> As far as I understand, this is about bootstrapping in ANOVA. There is nothing especially clever about how I coded it in PAST. The only things are that 1) The bootstrapping does not run the whole ANOVA routine for each replicate (with calculation of parametric significance etc.), only the bare minimum necessary to obtain an F value; and 2) I'm using a compiler that us known to produce fast executables (Delphi - yes I'm old!).
> 
> I guess that if JASP is built on R, then there is not very much you can do about this, as you are just calling an R function?
> 
> My code is a complete mess, especially the ANOVA module, so I'm not sure if that would be very helpful, but if you like then I can have a close look and give you more details about the implementation (but again, it's nothing particularly clever).
> 
> Of course, bootstrapping is well suited for distributing on multiple cores. PAST uses such multithreading in several modules, but not yet in ANOVA because it is fast enough already, and as many machines only have 4 cores this is not a miracle cure anyway.
> 
> Finally, I should say that some modules in PAST run much more slowly than the implementations in R, because of my poor algorithms, so PAST is not a particularly fast program in general.
> 
> Let me know if there is more that I can do to help!
> 
> Prof. Øyvind Hammer
> Natural History Museum, University of Oslo

Thx Øyvind for the fast and detailed response!

May I share your answer in the github discussion I linked in my previous mail?

If you are not comfortable with public discussions like this I would like to forward your answer to johnny doorm, a core developer within the jasp team. I just manage some communication and report bugs, but am not competent enough to apply your tipps and hints.
And,you are right. We would need to implement those improvements (if feasible) upstream within the R packages we call in JASP.

Cheers, Thomas

> 
> Yes of course you can share my email, EXCEPT that looking at it now, the ANOVA in PAST does in fact not include any bootstrapping (only a permutation test). So your JASP user must have referred to bootstrapping in PAST being quite fast in general (many modules include bootstrapping). My comments in my previous email still apply however.
> 
> Øyvind

So I guess this settles this discussion mostly. The only angle I see from Øyvind's mail is multithreading. I will make a dedicatet feature request for that and link it here. But this will probably not be implemented soon and might also be only tackable from within the R-Packages we use. The issue will become more pressing when/if we switch our database backend from sqlite to something that can handle more than 1000 columns.

Cheers Thomas
