### ISSUE TITLE
Informed prior setting in JASP

### ISSUE THREAD

**Issue by Diesfeldt** [jasp-stats/jasp-issues#144]
I am working in JASP 0.9.1.0, module Bayesian Independent Samples T-Test. Is there an option to change a default Cauchy distribution prior? I suppose it was available in earlier JASP versions (see Quintana & Williams, in BMC Psychiatry 2018, 18: 178). But in JASP 0.9.1.0 I cannot find the option.

**Comment by EJWagenmakers** [comment]
If you scroll down on the input panel there is a tab that says "prior" -- open it and you'll be able to change the distribution almost at will...
Cheers,
E.J.

**Comment by Diesfeldt** [comment]
Beste Eric-Jan,

Hartelijk dank voor je hulp. Ik stuur een print screen mee. Ik zie geen mogelijkheid tot scrollen en vind geen tab voor prior.
Ik gebruik de meest recente versie van JASP: 0.9.1.0

Met vriendelijke groet,

Han Diesfeldt




Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

________________________________
Van: EJWagenmakers <notifications@github.com>
Verzonden: Tuesday, November 13, 2018 10:43:22 PM
Aan: jasp-stats/jasp-issues
CC: Diesfeldt; Author
Onderwerp: Re: [jasp-stats/jasp-issues] Informed prior setting in JASP (#144)


If you scroll down on the input panel there is a tab that says "prior" -- open it and you'll be able to change the distribution almost at will...
Cheers,
E.J.

**Comment by EJWagenmakers** [comment]
When I looked at your initial issue I could replicate it -- but only because I mistakenly selected the frequentist test! Are you sure you selected the *Bayesian* version? :-) 
I can't see the screenshot, by the way...
E.J.

**Comment by Diesfeldt** [comment]
Thanks again! Yes I opened the module Bayesian Independent Samples T-Test. I try to send the screenshot by separate mail. The input panel shows the following options: hypothesis, Bayes Factor, Tests, Additional statistics, Plots (four options to select), Missing values. That is what I see.

Cheers,

Han


Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

________________________________
Van: EJWagenmakers <notifications@github.com>
Verzonden: Friday, November 16, 2018 5:46:58 PM
Aan: jasp-stats/jasp-issues
CC: Diesfeldt; Author
Onderwerp: Re: [jasp-stats/jasp-issues] Informed prior setting in JASP (#144)


When I looked at your initial issue I could replicate it -- but only because I mistakenly selected the frequentist test! Are you sure you selected the Bayesian version? :-)
I can't see the screenshot, by the way...
E.J.
