### ISSUE TITLE
JASP crashed

### ISSUE THREAD

**Issue by brandenjohnson1** [jasp-stats/jasp-issues#1441]
* JASP version: 0.14.1
* OS name and version: Windows 10 (10.0)
* Analysis: 
* Bug description:
* Expected behaviour:

#### Steps to reproduce:

-----------------------------------------------------------------------

### Debug information:
**Engine # 0** process  is *running* and it's state is *idle*.
**Engine # 1** process *crashed* and it's state is *initializing*.
**Engine # 2** process  is *running* and it's state is *idle*.
**Engine # 3** process  is *running* and it's state is *idle*.

[Commit used](https://github.com/jasp-stats/jasp-desktop/commit/f2cb223fef6b15089fd6e9da54825d370c1ece57)

**Comment by boutinb** [comment]
Hi @brandenjohnson1 We have a new version 0.15 (https://jasp-stats.org/download/). Could you try it?
