### ISSUE TITLE
Unfortunately the plot cannot be resized. Error message: no plot was found

### ISSUE THREAD

**Issue by R180** [jasp-stats/jasp-issues#1443]
JASP 0.15 Windows 10 ANOVA

If I open JASP and then open from the JASP data library the _tooth-growth-data-set-and-pre-performed-analysis_, and then attempt to re-size the plot, I get the following error message.

**_Unfortunately the plot cannot be resized. Error message: no plot was found If the problem persists, please report the message above at: https://jasp-stas.org/bug-reports_** 

See the following screen shot.
![image](https://user-images.githubusercontent.com/16230091/135733308-ca9d6db2-f215-4972-b164-9dcb88ab73ea.png)

I have attached the JASP file.
[Tooth Growth, saved.zip](https://github.com/jasp-stats/jasp-issues/files/7272455/Tooth.Growth.saved.zip)

The problem does not occur if I import the data from a CSV file and run the ANOVA from scratch.

**Comment by boutinb** [comment]
Hi @R180 Thank you for reporting this error.
Apparently this JASP file was not correctly refreshed for the 0.15 release. I see this error in other JASP files of the Data Library. A simple workaround is to refresh the analysis (CTRL-R for example, or Refresh All in Dropdown menu of the title), this recreates the plot objects, and you can resize it without error.
We will pay attention to refresh correctly all the JASP files of the Data Library in 0.16 (over some weeks).
