### ISSUE TITLE
Resizing plots: Provide a way for the user to know and reproduce the exact amount of resizing.

### ISSUE THREAD

**Issue by R180** [jasp-stats/jasp-issues#1444]
Currently, the user can drag the lower corner of a plot's output field to resize and change the dimensions of a plot. (This is sometimes necessary, for example, when the plot would otherwise be too narrow to accommodate the horizontal-axis labels.)

However, there's currently no way for the user to do this consistently since the plot's output field deforms in a gradual continuous manner, with no feedback as to exactly how much the horizontal and/or vertical dimensions are changing.

This problem could be remedied in a number of ways.

One way would be to provide the user with numerical, on-screen information (a pair of pixel values) indicating what the exact dimensions are. Practically, this would need to be accompanied by a feature in which there were a key (like the shift key) that allows the resizing to happen in discrete steps as the user drags the lower right corner of the output field.

**Comment by juliuspf** [comment]
@R180, thanks for the request, and I apologize for the delayed response.

**Comment by vandenman** [comment]
@juliuspf this is something we want to build into plot editing.

**Comment by tomtomme** [comment]
superseeded by this duplicate https://github.com/jasp-stats/jasp-issues/issues/3078
which adds some more detail. lets discuss there.
