### ISSUE TITLE
Analysis terminated unexpectedly on 15.0

### ISSUE THREAD

**Issue by brandenjohnson1** [jasp-stats/jasp-issues#1446]
* JASP version: 15.0.0.0
* OS name and version: Windows 10 64-bit
* Analysis: Confirmatory Factor Analysis

I had just downloaded the latest version. I had specified the observed variables, and was in the process of requesting various data (e.g., model plots) when I got the error message. 

[NOAARAS_Merged_BJworking_Trust.zip](https://github.com/jasp-stats/jasp-issues/files/7281991/NOAARAS_Merged_BJworking_Trust.zip)

[NOAARAS_Merged_BJworking_Trust.csv](https://github.com/jasp-stats/jasp-issues/files/7281985/NOAARAS_Merged_BJworking_Trust.csv)

Error report:

```
This analysis terminated unexpectedly.

Error in bars[[node]] <- pnorm(GroupThresh$est[GroupThresh$lhs = GroupVars$name[node]]): attempt to select more than one element in integerOneIndex

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

ConfirmatoryFactorAnalysis(...)

.cfaPlotPath(jaspResults, options, cfaResult)

jaspBase:::.suppressGrDevice(pathplot <- semPlot::semPaths(object = .cfaLavToPlotObj(cfaResult[['lav']], options), DoNotPlot = TRUE, ask = FALSE, layout = 'tree', intercepts = options$plotmeans, whatLabels = if (!options$plotpars) 'name' else if (options$plotstd) 'std' else 'par', mar = ifelse(rep(is.null(options$secondOrder), 4), c(12, 3, 12, 3), c(6, 3, 6, 3)), edge.color = 'black', color = list(lat = '#EAEAEA', man = '#EAEAEA', int = '#FFFFFF'), border.width = 1.5, edge.label.cex = 0.9, lty = 2,
    title = FALSE))

eval(plotFunc, parent.frame())

eval(plotFunc, parent.frame())

semPlot::semPaths(object = .cfaLavToPlotObj(cfaResult[['lav']], options), DoNotPlot = TRUE, ask = FALSE, layout = 'tree', intercepts = options$plotmeans, whatLabels = if (!options$plotpars) 'name' else if (options$plotstd) 'std' else 'par', mar = ifelse(rep(is.null(options$secondOrder), 4), c(12, 3, 12, 3), c(6, 3, 6, 3)), edge.color = 'black', color = list(lat = '#EAEAEA', man = '#EAEAEA', int = '#FFFFFF'), border.width = 1.5, edge.label.cex = 0.9, lty = 2, title = FALSE)
```

**Comment by juliuspf** [comment]
@brandenjohnson1 thanks for the issue! Unfortunately, I cannot unzip your zip file on my computer. Could you describe which variables you used in what factor structure? Or, alternatively, upload a workable zipped jasp file?

**Comment by juliuspf** [comment]
Unfortunately I cannot recreate the issue with the information provided. I have tried a few different factor models with the NOAARAS_Merged_BJworking_Trust.csv file but nothing has led to the error described here. Without further information about the factor model leading to this issue I will close this, but feel free to reopen it again once you have some more information.
