### ISSUE TITLE
JASP crashes on network graphics settings

### ISSUE THREAD

**Issue by harcel** [jasp-stats/jasp-issues#1448]
* JASP version: 0.15

* OS name and version: Linux, Pop!_OS 21.04

* Analysis: When I try to add the x-ccordinates of the network plot to the data set, all is fine, then including the y-coordinate as well makes JASP crash (repeatedly).
* Bug description: [bug.zip](https://github.com/jasp-stats/jasp-issues/files/7302189/bug.zip)
* Expected behaviour: I expected both x and y to be added to the data file, instead, my whole session crashes.

#### Steps to reproduce:
1. Go to Graphical options
2. Click on save the layout to the data set, and add one for x
3. Scroll down to the name for y, add it too.
4. It crashes, for me

**Comment by boutinb** [comment]
Hi @harcel It does not crash for me... But I am on MacOS. Maybe can @akashrajkn try it?

**Comment by tomtomme** [comment]
@JoKeyser & @harcel 
I tested this on manjaro kde and all worked fine with jasp 0.18.3 - could you re-test? Since popOS is ubuntu based, this might be isolated to debian based distros. Either way, we probably can close this, since we cannot track distro-specifics, right?

**Comment by akashrajkn** [comment]
@tomtomme with jasp `v0.18.3` (flathub) and Pop!_OS `22.04 LTS`, it works fine.

**Comment by tomtomme** [comment]
thx @akashrajkn 
closing then!
