### ISSUE TITLE
Cannot open / load saved analysis .jasp file

### ISSUE THREAD

**Issue by wschelle** [jasp-stats/jasp-issues#1449]
* JASP version: currently V0.15.0 (but also experienced it with V0.14.1)

* Windows 10 (laptop, core i7, 8 GB RAM) & 7 (desktop, core i5, 16 GB RAM):
* Analysis: Linear Mixed Models
* Bug description: I ran a couple of linear mixed model analyses. Saved the results. But now I cannot open the saved jasp-files. When I try to open them, I do see a progress bar (loading data, loading jasp file), but when the progress bar reaches completeness, JASP quits.
* Expected behaviour: To see my saved analyses.

#### Steps to reproduce:
1. Go to the folder where you saved my jasp file
2. Click on the jasp-file
3. Scroll down to nowhere

<!--- A note from the developers:
If possible please attach your data and/or JASP file to the issue, this makes solving the bug a lot easier. If you would prefer to not make your data publicly available then you could also mail it to us.
Note that github requires you to zip the file to upload it here.

If you didn't feel all fields from this template are necessary for your issue please take the time to remove them from the issue. 
---
[JASPCO2.zip](https://github.com/jasp-stats/jasp-issues/files/7303975/JASPCO2.zip)
>

**Comment by boutinb** [comment]
I cannot reproduce this problem.
Could you send your JASP file (rename it with the zip extension, and you can drag & drop it on a new comment of this issue in GitHub)?
