### ISSUE TITLE
Add variables from long lists returns the list to the top

### ISSUE THREAD

**Issue by mike-ology** [jasp-stats/jasp-issues#145]
* Enhancement: Retain position in variable list when adding variables to an analysis

* Purpose: There has been a few occasions now when I have been working with datasets with many similarly named variables that I have conducted the incorrect analysis unknowingly because everytime a variable is added to an analysis (e.g. to fill Repeated Measures Cells) long variable lists automatically jump back to the top.

When adding a variable to an analysis, can the variable list not move from its current position? This will reduce the amount of scrolling through the list (as related variables are often next to one another), and also reduce the number of errors when adding variables because the list position is not where I was expected it to be left.

Thank you!

**Comment by AlexanderLyNL** [comment]
This is basically fixed with the option to reorder variables alphabetically or by type.

**Comment by TimKDJ** [comment]
You still jump in variables list though; just assign a variable that required a little bit of scrolling to get to (you won't always be able to get the variable you want without scrolling). Your position in the list should not change..

**Comment by tomtomme** [comment]
Still relevant with 0.18.2 beta

**Comment by tomtomme** [comment]
With current jasp 0.19 beta (and earlier) the behaviour is, that the variable list jumps on top of the variable, that was just above the added one. This way you cannot see the next variable in the list anymore. It is very confusing. Thus I relabeled this as a Bug.

**Comment by tomtomme** [comment]
This one is only reproducible if you have scrolled down a bit within a long list. Here two screenshots that show the bug:

before:
![grafik](https://github.com/jasp-stats/jasp-issues/assets/4428185/1427711c-f5be-4d1d-98a2-76773485719c)

after:
![grafik](https://github.com/jasp-stats/jasp-issues/assets/4428185/6d2c8499-4304-4fda-a38a-aadfcf0db564)

instead we want:
![grafik](https://github.com/jasp-stats/jasp-issues/assets/4428185/c2a5b87b-2e74-4143-b0a4-320a79816ce6)

**Comment by tomtomme** [comment]
Still there with 0.19.2 beta flatpak

**Comment by tomtomme** [comment]
This is fixed within the latest beta :D
