### ISSUE TITLE
Feature request: Multinomial Logistic Regression

### ISSUE THREAD

**Issue by rafiulbiswas** [jasp-stats/jasp-issues#1451]
In SPSS there are can be performed both binary logistic regression and multinomial logistic regression. Here, in JASP i can perform only binary logistic regression. There is no option to perform multinomial logistic regression. 
![image](https://user-images.githubusercontent.com/8818508/136686885-68ee333d-d2eb-4a60-93ec-6148eed67ce9.png)
To work with categorical data with more than two categories I need multinomial logistic regression model. Would you please add this feature.

**Comment by boutinb** [comment]
@EJWagenmakers What do you think of this request?

**Comment by bazyliszek** [comment]
was there any update on that?

**Comment by EJWagenmakers** [comment]
It is a good suggestion, and we actually want to add the possibility of imposing an order (as for Likert scales).

**Comment by jes1984** [comment]
Thanks, a multinomial option would be great!!

**Comment by tomtomme** [comment]
Multinomial logistic regression is done via the GLM module under Regression
