### ISSUE TITLE
Feature request: Variable descriptions

### ISSUE THREAD

**Issue by kevinvschie** [jasp-stats/jasp-issues#1452]
* Enhancement: it is customary to have short variable names in JASP (or any data processor really). However, these short names (though well-intended) may not always clearly communicate what is measured. Even very clear descriptors (e.g., "age") may cause confusion (e.g., measured in months [for infants/children] or in years). If there was a place where one could add more information pertaining to a given variable, that would be great.
* Purpose: to give users (specifically co-authors, reviewers, etc) more information on what is measured
* Use-case:

**Is your feature request related to a problem? Please describe.**
 it would be useful to have more information for variables besides their variable name. 

**Describe the solution you'd like**
 It would be ideal if it was possible to add more information to the variables. I am not exactly sure how this could be implemented in the software. Perhaps the first row in an .xls or .csv file is the variable name (e.g., memory_recall) and the second row could provide additional information (e.g., proportion of word recalled on the final memory test) . Ideally, this would result in the possibility to hover over the variable name in data view and then the additional information would appear in a text box. Or when analyzing the data one would not only see the variable names, but could also tick a box to see the full descriptions of the variables.  

**Describe alternatives you've considered**
 n/a

**Additional context**

**Comment by JoKeyser** [comment]
I agree that this kind of "annotation" to the raw data would be helpful.
I'd like to point out possible workarounds until a clean technical solution is found.

- For units of measurement, one could add the SI units in parenthesis into the variable name, e.g. Height (cm).
- For textual description, one can use JASP's annotation feature in the Results, as is done for the data sets in JASP's data library.
  Among JASP users, you can share this information in the corresponding `.jasp` file.
- For more extensive description of a data set, one could do something like the JASP Data library, see https://jasp-stats.org/2020/06/09/finished-the-jasp-data-library-1st-ed/.

**Comment by juliuspf** [comment]
I doubt we will have a technical solution for this, but maybe we are wrong... @JorisGoosen ?

**Comment by JorisGoosen** [comment]
Yeah this would definitely be nice but we don't support it atm.
Ill add it to the todo list for data-editing though. As we need to change many things there in any case

**Comment by tomtomme** [comment]
this is done and can be closed

**Comment by JorisGoosen** [comment]
Ah yes this was added to both columns/variables and the workspace as a whole since 0.18.1 and 0.18.2
