### ISSUE TITLE
Error: JASP crashes after computing Bayesian Repeated-Measures ANOVA

### ISSUE THREAD

**Issue by MartinaFanghella** [jasp-stats/jasp-issues#1454]
* JASP version: JASP 0.14.1.0
* OS name and version: Windows 10 Pro
* Analysis: Bayesian repeated-measures ANOVA
* Bug description: [JASP_Error.zip](https://github.com/jasp-stats/jasp-issues/files/7330659/JASP_Error.zip)
* Expected behaviour: I am trying to run a Bayesian Repeated-Measures ANOVA, but at the end of computation JASP crashes. 

#### Steps to reproduce:
1. Go to 'Bayesian Repeated Measures ANOVA'
2. Click on 'Model Terms' and add the following factors (including interactions): Task, Hemisphere, Site, Emotion
3. Scroll down to 'Specific model terms' and add the same factors including interactions
Wait until the end of computation (it might take long).
Note that, when excluding the factor "Site" from Model (and Specific Model) Terms, JASP correctly computes Bayesian RM ANOVA
4. See error: (below)

```
Error in array(0, dim = c(steps, nparam, 2), dimnames = list(NULL, names(weightedMeans), : length of 'dimnames' [2] not equal to array extent

Stack trace
tryCatchOne(expr, names,

 parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.BANOVArunAnalysis(jaspResults, dataset, options, 'RM-ANOVA')

.BANOVAestimatePosteriors(jaspResults, dataset, options, model)

.BANOVAsamplePosteriors(jaspResults, dataset, options, model, posteriors)

array(0, dim = c(steps, nparam, 2), dimnames = list(NULL, names(weightedMeans), c('x', 'y')))
```

**Comment by juliuspf** [comment]
@MartinaFanghella could you confirm the issue still persists with the newest JASP version?
