### ISSUE TITLE
[Bug]: Cannot plot the posterior - possibly too concentrated near 0.

### ISSUE THREAD

**Issue by linjansen** [jasp-stats/jasp-issues#1455]
### JASP Version

0.14

### JASP Module

jaspTTests

### What OS are you seeing the problem on?

macOS Big Sur 11.6

### Bug Description

 I keep encountering a problem in the Bayesian Independent Samples T-test that I did not have a couple of years ago (when I used an earlier version of JASP). Namely, when I ask for the prior and posterior plot in order to get the estimated posterior effect size and its 95% CI, I get the error: "Cannot plot the posterior - possibly too concentrated near 0". However, the posterior is not close to zero at all. In fact, I only get this error when the posterior is quite far from zero. 

When I compare the output of the current analyses to the output from a couple of years ago, the descriptives and Bayes factors are exactly the same, except that the error % for the Bayes factors was given in the old analysis but is 'NaN' in the new analysis with the following note: "t-value is large. A Savage-Dickey approximation was used to compute the Bayes factor but no error estimate can be given". In the old analysis, this could be given however.

The estimated posterior effect size and its 95% CI are only given in this 'prior and posterior' plot, so if I get this error instead of the plot, I cannot get this information. Is there a way to request this information without showing the plot? Or is there a way to get the plot to work? What I find strange is that it worked on the same data in an earlier version of JASP.

I will e-mail you one or more JASP files that show this issue (it happens in multiple files).

### Expected Behaviour

It should plot the prior and posterior distribution. See the attached print screen for an example showing the requested plot (that I got when I ran the analyses a few years ago) and the error (that I get when I run the analyses now).
![Schermafbeelding 2021-09-21 om 13 52 45](https://user-images.githubusercontent.com/22299026/136979422-be35b40a-bdb6-4763-9556-b5d5d5d41ed0.png)

### Steps to Reproduce

1. Run a Bayesian Independent Samples T-Test
2. Check the boxes for 'prior and posterior' and 'additional info' under 'Plots'.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
I tested in 0.18.3 and this is still valid.

**Comment by tomtomme** [comment]
Closing now, as we have duplicate here right now: https://github.com/jasp-stats/jasp-issues/issues/2603
