### ISSUE TITLE
[Bug]: Crash either when moving around to see data, or random crash when trying to open menu tab

### ISSUE THREAD

**Issue by verboten999** [jasp-stats/jasp-issues#1456]
### JASP Version

0.15

### What OS are you seeing the problem on?

windows 10

### Bug Description

Crash either when moving around to see data, or random crash when trying to open menu tab

### Expected Behaviour

Dragging the data view shouldn't make it crash and return me to desktop

### Steps to Reproduce

Open data file, either moving the data view or changing data type (ordinal to scale or vise versa)

### Log (if any)

```bash
Source
JASP.exe

Summary
Stopped working

Date
‎12-‎Oct-‎21 22:17

Status
Report sent

Description
Faulting Application Path:	C:\Program Files (x86)\JASP\JASP.exe

Problem signature
Problem Event Name:	APPCRASH
Application Name:	JASP.exe
Application Version:	0.0.0.0
Application Timestamp:	615d8c33
Fault Module Name:	Qt5Quick.dll
Fault Module Version:	5.15.2.0
Fault Module Timestamp:	5fa50aeb
Exception Code:	c0000005
Exception Offset:	000000000006a33d
OS Version:	10.0.19043.2.0.0.256.48
Locale ID:	14345
Additional Information 1:	9ed6
Additional Information 2:	9ed6c075aaac27838916f57557b51e9e
Additional Information 3:	93ea
Additional Information 4:	93ea632b09fda6db00733b150882f81e

Extra information about the problem
Bucket ID:	4ef525daafc03c63559fe46c446c0a50 (1558215149749013072)
```

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by verboten999** [comment]
Nope, still no go. Still crashes both on my PC and my laptop. Both on AMD processor and Nvidia GPU, if it helps somewhat. Coming back to 0.14.1 for now. Thanks for the suggestion, though.

**Comment by juliuspf** [comment]
Does this issue persist with the latest JASP version? @verboten999
