### ISSUE TITLE
JASP crashed

### ISSUE THREAD

**Issue by Becca268** [jasp-stats/jasp-issues#1460]
* JASP version: 0.15
* OS name and version: Windows 10 Version 2009
* Analysis: 
* Bug description:
* Expected behaviour:

#### Steps to reproduce:

-----------------------------------------------------------------------

### Debug information:
**Engine # 0** process *crashed* and it's state is *initializing*.

[Commit used](https://github.com/jasp-stats/jasp-desktop/commit/a22bb90bde03b38637da8c11766ac9be205da9bb)

**Comment by Pkidd1** [comment]
Hi,
I'm having a similar problem to that above. Using Windows 10, Version 21H1. JASP closes as soon as any actions are performed e.g. just opening a data set causes a crash.
I've tried uninstalling and re-installing the package. Any other advice?

Thanks
Paul
