### ISSUE TITLE
Release full jasp-desktop bundle

### ISSUE THREAD

**Issue by izahn** [jasp-stats/jasp-issues#1462]
Since version `0.15.0` it seems that jasp desktop cannot be built from the official github release. Downloading https://github.com/jasp-stats/jasp-desktop/archive/refs/tags/v0.15.0.tar.gz, extracting it, and running `qmake` / `make` fails with 

```
In file included from ../../Common/column.cpp:18:
../../Common/column.h:31:10: fatal error: columntype.h: No such file or directory
```
because the released tarball does not contain all the submodules needed to build jasp-desktop. 

The build instructions at https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/development/jasp-building-guide.md recommend checking out the git repository and pulling in all the submodules. This works, but makes it difficult to checksum the various sources to ensure that we are building from specific reproducible source code releases.

It would make packaging easier if a complete release tarball including all submodules needed to build jasp-desktop was included with official github releases. This will allow packagers to build this software from a single check-summed source code release.

There may be other ways to address this problem as well, and I have no opinion about the best way to address it. The important thing from my perspective is that we have checksum-able source code releases for all the various components of jasp desktop, along with instructions for building it using those verifiable sources .

**Comment by amirmasoudabdol** [comment]
Hi @izahn, thanks for reaching out. I believe that tarball is generated by GitHub, and I agree, it should either be self-contained, or not be there. I don't even think it contains the `.git` folder, so it's not even possible to update the submodules when you download it. 

As for the better solution for this, we are considering an alternative that might simplify the build procedure. I will keep you updated as soon as we have something. But, for now, if you want to build JASP, please use the git repo. Checkout to the https://github.com/jasp-stats/jasp-desktop/releases/tag/v0.15.0 tag, and start from there.
