### ISSUE TITLE
Use system language as default JASP interface language

### ISSUE THREAD

**Issue by djdekker** [jasp-stats/jasp-issues#1466]
* Enhancement: use the system language as the default interface language for JASP
* Purpose: make JASP easier to use
* Use-case: general use

**Describe the solution you'd like**
I'd like to suggest that JASP checks the language of the operating system upon the first boot and sets the JASP interface language accordingly (if the system language is available in JASP). If the system language is not available in JASP, then JASP could default to English.

**Comment by tomtomme** [comment]
related
https://github.com/jasp-stats/jasp-issues/issues/39
