### ISSUE TITLE
[Bug]: Languages mixed up in One Sample T-Test note

### ISSUE THREAD

**Issue by djdekker** [jasp-stats/jasp-issues#1467]
### JASP Version

0.15

### JASP Module

jaspTTests

### What analysis are you seeing the problem on?

One Sample T-Test

### What OS are you seeing the problem on?

macOS 11.6 Big Sur

### Bug Description

In the note under the one sample t-test output, the English text and the translation (Dutch, German) are mixed up.

<img width="404" alt="Schermafbeelding 2021-10-19 om 21 44 50" src="https://user-images.githubusercontent.com/5346286/137980024-afa012bf-d29e-41a9-a6ca-e9dd10b7901a.png">

<img width="410" alt="Schermafbeelding 2021-10-19 om 21 45 14" src="https://user-images.githubusercontent.com/5346286/137980052-53fa6d1d-4efd-4b34-b4c6-418788e76654.png">

### Expected Behaviour

The text should be in the interface language.

### Steps to Reproduce

1. Open the debug data set.
2. Request a One Sample T-Test, for example with variable contNormal.
2. Change the interface language from English to Dutch or German.
3. See error.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by amirmasoudabdol** [comment]
Thanks for reporting this. We will look into this!

**Comment by boutinb** [comment]
This is solved for next release (next week hopefully)
