### ISSUE TITLE
[Feature Request]: Total percentage in confusion matrix when running a logistic regression

### ISSUE THREAD

**Issue by PerPalmgren** [jasp-stats/jasp-issues#1471]
* Enhancement:
* Purpose:
* Use-case:

**Is your feature request related to a problem? Please describe.**
No overall percentage in the classification table/confusion matrix. when running logistic regression.

**Describe the solution you'd like**
It would great with classification table  with the total percentage of cases overall that were correctly classified ("Overall Percentage" ). This is possible in SPSS and also in JAMOVI (through  an accuracy value).

**Comment by PerPalmgren** [comment]
I this request feasible?

**Comment by boutinb** [comment]
@fqixiang Could you answer whether this is feasible?

**Comment by fqixiang** [comment]
@boutinb Yes it is. It's very strange that the accuracy doesn't seem displayed anywhere, even though I remember seeing it before. In any case, I'll add it.

**Comment by PerPalmgren** [comment]
@boutinb and @fqixiang 
I think the new confusion matrix (when using the proportions button) is very cluttered. What is the added value for within rows and columns?
I really prefer how it has been in previous JASP versions. What is missing overall percentage like in SPSS (see picture) or only accuracy in Jamovi.
![table-classification](https://user-images.githubusercontent.com/79397662/142777506-b72b256c-6ca3-4360-8527-350382f17f2c.png)
Kind regards
Per

**Comment by fqixiang** [comment]
@Kucharssim I agree with @PerPalmgren that the new confusion matrix with proportions is very cluttered - perhaps I should change it to SPSS style?

**Comment by EJWagenmakers** [comment]
Yes, I agree.

**Comment by PerPalmgren** [comment]
Do you know when this will be rectified? My students are now running their logistic regression analysis in SPSS or JAMOVI, because they can´t interpret the present confusion matrix (when set on proportions) in JASP. That is sad because I  love JASP.

**Comment by boutinb** [comment]
I think this is an easy fix. @fqixiang when do you think you can solve it?

**Comment by fqixiang** [comment]
@boutinb  I already assigned it to the 0.16.1 release, so ultimately depends on when the new release is ready. :)

**Comment by PerPalmgren** [comment]
Thank you @fqixiang and @boutinb. This is highly appreciated as my students right now uses another free software to get told of this total percentage.
