### ISSUE TITLE
[Bug]: Untranslatable string "Click here to add text"

### ISSUE THREAD

**Issue by JoKeyser** [jasp-stats/jasp-issues#1474]
### JASP Version

0.15

### What analysis are you seeing the problem on?

Any analysis, the bug is in jaspDesktop

### What OS are you seeing the problem on?

Ubuntu

### Bug Description

When adding a Note to analysis results, there is a hard-coded English string that cannot yet be translated.

In current development branch, the string is at https://github.com/jasp-stats/jasp-desktop/blob/development/Desktop/html/js/jaspwidgets.js#L375:

```
this.ghostTextDefault = 'Click here to add text';
```

### Expected Behaviour

The string should be translatable.

### Steps to Reproduce

1. Switch to any language other than English.
2. In any analysis result, click on *Add Note*.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by icekylin** [comment]
> Start New Translation

But when I added “JASP/jaspGraphs” as a new translation for Simplified Chinese according to the above steps, I was prompted that I did not have permission. Does this mean what the administrator needs to do？

**Comment by icekylin** [comment]
@JoKeyser But when I added “JASP/jaspGraphs” as a new translation for Simplified Chinese according to the above steps, I was prompted that I did not have permission. Does this mean what the administrator needs to do？

**Comment by JoKeyser** [comment]
@icekylin , hm, I'm not sure to be honest, but I think it should work. I guess there may be something wrong with Weblate itself, or its configuration with JASP.
I've opened another issue #1482 to track this problem separately there.

**Comment by boutinb** [comment]
@icekylin We have a problem with our WebLate license, but I hope it will be solved soon.
@JoKeyser the javascript strings are now not translated. There are not so many fortunately, but we need to solve this indeed.

**Comment by JorisGoosen** [comment]
> @JoKeyser the javascript strings are now not translated. There are not so many fortunately, but we need to solve this indeed.

We could just set them on the `WebChannel` in `MainPage.qml` as properties and in QML so that they are easily available as `jasp.blablaText` in JS. Should be quite easy honestly.
