### ISSUE TITLE
Enhancement Request: Bayesian Graph

### ISSUE THREAD

**Issue by mrstruijk** [jasp-stats/jasp-issues#148]
## Template for enhancement requests
Hi! The network graph output of the sig. testing is fantastic.  Would this be possible for Bayesian correlations as well? 
* Enhancement:  Selecting Bayesian (Pearson) correlations in the Network Plot section.   
* Purpose:  Compare Bayesian and significance testing correlations graphically.  Complete my thesis with less headache.

**Comment by tomtomme** [comment]
@mrstruijk 
Afaik we now have a bayesian network module with same plotting options as the classic network module. Please reopen, if this is not sufficient or if I misunderstood.
