### ISSUE TITLE
[Feature Request]: Plots in Descriptives

### ISSUE THREAD

**Issue by PerPalmgren** [jasp-stats/jasp-issues#1480]
### Purpose

Improved interpretations of plots

### Is your feature request related to a problem?

I think it would be a very nice feature to be able to turn of "N" and "Missing" when running an exploration of data (I often ask my students to look at the shape of data first.) The uncompleted table disturbs.  Further, it would be great to be able to ONLY display the density when adding this to a distribution plot.

### Describe the solution you would like

These functions are possible in JAMOVI.

**Comment by PerPalmgren** [comment]
Just wanted to check in on the developmental status for this?

**Comment by boutinb** [comment]
@vandenman Did you add this feature?

**Comment by vandenman** [comment]
@boutinb there is a PR open (for the next release).

Following EJ's suggestion I went for a radio button:

![image](https://user-images.githubusercontent.com/21319932/141946084-58cc4aa7-e435-4ec6-a87a-bc8d4412e00b.png)

The radio button allows you to specify whether you want a histogram, density, or both. This applies to both the distribution plot and the subplots on the diagonal of the correlation plot.

@PerPalmgren would this meet your needs?

> Would it be possible to have three checkboxes on the same level?

Usually, if one checkbox can only be checked after another one is checked, we indent it a little bit.

**Comment by PerPalmgren** [comment]
Not so familiar with names like PR?😜 Is it possible to send me a link?
Kind regards
Per

Per J. Palmgren | DC, FRCC, MMedEd, PhD |
Associate Professor |
Department of Learning, Informatics, Management and Ethics |
Karolinska Institutet | Tomtebodavägen 18A | 171 77 Stockholm |
Tel. + 46 8 524 85 294<tel:+%2046%208%20524%2085%C2%A0294>
***@***.******@***.***> | ki.se<https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fki.se%2F&data=04%7C01%7Cper.palmgren%40ki.se%7C9f6969aac91f4526542308d875898009%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637388580700328145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=f6OY6fEm6z0scmnO%2FDhlWRgL%2BujfjA072A2uHaASfNY%3D&reserved=0>
________________________________

Karolinska Institutet – a medical university

**Comment by PerPalmgren** [comment]
Got it! Nice 😜
When are you planning for next release?

**Comment by vandenman** [comment]
@boutinb there is a PR open (for the next release).

Following EJ's suggestion I went for a radio button:

![image](https://user-images.githubusercontent.com/21319932/141946084-58cc4aa7-e435-4ec6-a87a-bc8d4412e00b.png)

The radio button allows you to specify whether you want a histogram, density, or both. This applies to both the distribution plot and the subplots on the diagonal of the correlation plot.

@PerPalmgren would this meet your needs?

> Would it be possible to have three checkboxes on the same level?

Usually, if one checkbox can only be checked after another one is checked, we indent it a little bit.

**Comment by PerPalmgren** [comment]
Do you know when this feature will be implemented?

**Comment by vandenman** [comment]
This will be implemented in the next version (so not 0.16). There is no specific release date for the next version, but hopefully, it'll be in January.
