### ISSUE TITLE
Weblate: JASP exceeds the limits of the Libre plan

### ISSUE THREAD

**Issue by JoKeyser** [jasp-stats/jasp-issues#1482]
### Description and context

When trying to add Simplified Chinese to the jaspGraphs component (https://hosted.weblate.org/languages/zh_Hans/jasp/), I get logged out and get this message:

> Your request was rejected because you have performed too many operations recently. You have been signed out, please sign in and try again later.

When I try to get information about any project alert (the red exclamation marks `!` in Weblate), I get this message:

> Your billing plan has exceeded its limits. You can still use the service, but are recommended to upgrade the billing plan.

Maybe there is some misunderstanding or buggy configuration on Weblate's end?
This may be relevant documentation: https://docs.weblate.org/en/latest/admin/projects.html#adding-translation-projects-and-components

This problem was first discovered in issue #1474 by @icekylin, see comment https://github.com/jasp-stats/jasp-issues/issues/1474#issuecomment-955203734.
I'm opening this issue to track it separately.

**Comment by icekylin** [comment]
Thank you for your report. In fact, I also encountered it. I have already reported this problem in [weblate issue #6376](https://github.com/WeblateOrg/weblate/issues/6736)  , so that we can determine the cause of the problem together.

**Comment by boutinb** [comment]
We have indeed some problem with our WebLate license. But this one is I think only a temporary: if you try to add this component the day after, it should work.

**Comment by icekylin** [comment]
> We have indeed some problem with our WebLate license. But this one is I think only a temporary: if you try to add this component the day after, it should work.

I just tried it and it still doesn't work. When I try to add ‘jaspGraphs’, there is no response for a long time. I will be forced to log out and prompt "rate limit"  if I try it again.

**Comment by JoKeyser** [comment]
Citing https://github.com/WeblateOrg/weblate/issues/6736#issuecomment-956177835:
> "JASP project has exceeded the limits for the Libre plan (it matches the Advanced plan), that's why you cannot add new component. Please write to care@weblate.org to discuss possible solutions."

Hopefully there is a way to resolve the situation?

**Comment by EJWagenmakers** [comment]
We have upgraded our plan with Weblate, so this should not be a restriction any longer. (not sure whether they have lifted the restriction already. @boutinb ?

**Comment by boutinb** [comment]
We have now 'Advanced for non-profit (20000 strings)' still in trial period (but should be definitive soon).
We have now 10,191 string (20,000  allowed)  and 21 languages (30 allowed). So the warning should not appear anymore (and I don't see it).

**Comment by JoKeyser** [comment]
Thank you, this is great news. I just tried to add the original culprit again (adding Simplified Chinese to jaspGraphs), and Weblate gives me " The translation will be updated in the background.". That sounds more promising than, but the component hasn't appeared yet.
Maybe it takes some time, I have not much experience with adding components in Weblate.

**Comment by boutinb** [comment]
Hmm.. I have tried also to add Chinese to jaspGraphs, and I get also the same 'promising' message. If I don't see the translation today, I will ask WebLate support.

**Comment by icekylin** [comment]
@boutinb This problem is still unresolved, Please ask WebLate for support.
thank you.

**Comment by boutinb** [comment]
I have asked WebLate. What strange is that you can add other components, biut only this jaspGraph seems not to work.
Hopefully I have soon more information.

**Comment by boutinb** [comment]
It is now solved.
