### ISSUE TITLE
[Feature Request]: Bar Graph in Descriptives with error bars

### ISSUE THREAD

**Issue by mickeywilson5** [jasp-stats/jasp-issues#1483]
### Description

Bar Graph in Descriptives with SEM 

### Purpose

Giving the user the option of either a scatter graph or bar graph (as in excel bar graph) for a quick interpertation of the data

### Is your feature request related to a problem?

Everytime I add ordinal or nomial catagory to the Descriptives "split" option I always get a scatter plot. There is no option for a bar graph only box plots and descriptives, which give a graph of each sample without SEM.

### Describe the solution you would like

Under Descriptives, Plots there is an option for boxplots and Basic plots. There is no option under basic plots for a standard bar graph comparing all samples side by side with error bars. Once a nomimal or ordinal catagory is selected in the 'split' the graph automaticly switchs to a scatter graph.

**Comment by juliuspf** [comment]
Hi @mickeywilson5, thanks for the request and sorry for the late reply. I suppose with SEM you mean standard error? I dont know how feasible this is, given that "distribution plots" give you bar graphs. and box plots give you boxes with error bars. So what you would like are bar graphs with error bars, correct?
