### ISSUE TITLE
[Bug]: Descriptive statistic there can't click in with reliability statistic

### ISSUE THREAD

**Issue by Lizyy14** [jasp-stats/jasp-issues#1485]
### JASP Version

0.15

### JASP Module

jaspDescriptives

### What analysis are you seeing the problem on?

 Descriptive statistic there can't click in with reliability statistic

### What OS are you seeing the problem on?

window 10

### Bug Description

[Bug]: Descriptive statistic there can't click in with reliability statistic

### Expected Behaviour

![image](https://user-images.githubusercontent.com/93464625/139571936-f07a4e86-e33d-4e47-a637-be55348905b4.png)
![Picture1](https://user-images.githubusercontent.com/93464625/139572013-2eb98d6d-f15b-44a3-ac1f-e91855c44922.png)

### Steps to Reproduce

1. 
2. 
3. 
...
![Picture1](https://user-images.githubusercontent.com/93464625/139572045-95f10d57-0528-4427-bf14-1e544a4055b3.png)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
The reliability is an extra module you can load here:
<img width="701" alt="Screenshot 2021-10-31 at 17 14 38" src="https://user-images.githubusercontent.com/503332/139592680-15090839-2434-4781-a078-f74687f91124.png">
