### ISSUE TITLE
[Feature Request]: Add a‘ Refresh button’ to all analysis pages

### ISSUE THREAD

**Issue by icekylin** [jasp-stats/jasp-issues#1487]
### Description

Although the analysis can be performed automatically in most cases, in some cases the analysis action will not be performed automatically. For example, when performing model fitting exploration, and when some plot actions are performed, there are situations where the analysis cannot be run automatically. 

### Describe the solution you would like

I recommend adding a button with a refresh function to manually rerun all analyses. This will greatly reduce the occurrence of type errors due to delays and unexpected terminations.

### Describe alternatives that you have considered

Sometimes I need to go back and forth in the box to reselect or check the relevant options in order to activate this analysis to run automatically.
I imagine that when the refresh button is pressed, the analysis module corresponding to JASP re-runs the analysis process, including all statistics and plot operations and so on, depending on the currently selected dependencies and reload it.Maybe the position of the button can be side by side with other buttons.
![Snipaste_2021-10-31_20-14-23](https://user-images.githubusercontent.com/10348402/139582837-ade80c53-b2d1-4c27-a9ba-1dcd39b77447.png)

**Comment by boutinb** [comment]
You can already refresh all analyses by typing the shortkey CTRL-R (or CMD-R with Mac)

**Comment by JorisGoosen** [comment]
Or selecting it from the topmenu in the results (downturned triangle next to "Results")

**Comment by icekylin** [comment]
Very grateful for your help

**Comment by JoKeyser** [comment]
For the record: This idea is also tracked in issue #1257 .
