### ISSUE TITLE
[Bug]: Issue with unpermitted RM levels names in RM Anova

### ISSUE THREAD

**Issue by TaliRaveh** [jasp-stats/jasp-issues#1489]
### JASP Version

0.15

### JASP Module

jaspAnova

### What analysis are you seeing the problem on?

Repeated measures ANOVA

### What OS are you seeing the problem on?

Windows 10

### Bug Description

Attempting to run a mixed ANOVA with two repeated measured factors and one between-subject factor. At first I get empty tables in the results section and then an error message:

![Screenshot 2021-11-01 090054](https://user-images.githubusercontent.com/93510355/139633904-856d26d3-a8e5-4d57-97c5-b2cb67a4e8f3.png)

Oddly, the analysis worked fine when I had one more repeated measure, or when I did a Bayesian repeated-measures ANOVA.
link to the jasp file:
[https://drive.google.com/file/d/1BlplfekxWaN5_x5G-YWtp8hgHGU2boKf/view?usp=sharing](url)

### Expected Behaviour

getting the results of the analysis

### Steps to Reproduce

1. re-made the csv file
2. re-ran the analysis with a new JASP file
2. 
3. 
...

### Log (if any)

```bash
This analysis terminated unexpectedly.

Error in if ((misc$estType = 'pairs') && (paste(c('', by), collapse = ',') ≠ : missing value where TRUE/FALSE needed

Stack trace
doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

AnovaRepeatedMeasures(...)

.rmAnovaContrastTable(rmAnovaContainer, longData, options, ready)

cbind(contrastResult, confint(contrastResult, level = options$confidenceIntervalIntervalContrast)[, 5:6])

confint(contrastResult, level = options$confidenceIntervalIntervalContrast)

confint.emmGrid(contrastResult, level = options$confidenceIntervalIntervalContrast)

summary(object, infer = c(TRUE, FALSE), level = level, ...)

summary.emmGrid(object, infer = c(TRUE, FALSE), level = level, ...)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports
```

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JohnnyDoorn** [comment]
Hi @TaliRaveh,

Thanks for your bug report, I will work on fixing this for the next release. In the meantime, it seems that the error can be avoided by changing your RM level names. The level name of "n" seems to be the evildoer here, so if you rename this to something else (e.g., "nn"), your RM ANOVA will run.

Kind regards
Johnny

**Comment by TaliRaveh** [comment]
Thank you so much!

**Comment by amirmasoudabdol** [comment]
Thanks for taking care of this @JohnnyDoorn. Are you planning to have this for 0.16.1? If so, I think you should add it to the project.

**Comment by SophieCormack** [comment]
I also encountered this same bug when one of my RM level names was "**none**" - based on this conversation I changed the name and it then worked.  Please could you make sure that this level name is permitted in the next version too?

**Comment by tomtomme** [comment]
@TaliRaveh & @SophieCormack 
The linked file on gdrive above is not accessible anymore, so I cannot test this with a current jasp version. 

But I tested with a file from the data library. Changing var and level names to "n" and "n 2" and "none", was fine. Also I could not give two vars or levels the same name - a number was appended automagically. Thus I consider this fixed.

If you disagree, feel free to reopen.
