### ISSUE TITLE
[Bug]: JASP Freezing for 5 to 60 Seconds and Buttons Get Slow After Tabbing to Another Window and Back

### ISSUE THREAD

**Issue by Xeonen** [jasp-stats/jasp-issues#1490]
### JASP Version

0.15

### What analysis are you seeing the problem on?

General JASP Interface

### What OS are you seeing the problem on?

Windows 10

### Bug Description

If I move to another window and move back to JASP, it takes a few seconds for JASP to respond. Moreover, in any analysis, clicking options will cause JASP to freeze. This issue was not present in JASP v14.

### Expected Behaviour

JASP should have responded to commands instead of freezing for 15 seconds and when I clicked on "Skewness" tick in a descriptive analysis, it should not have waited for 5 seconds before tick being visually ticked.

### Steps to Reproduce

1.  Run JASP
2.  Do virtually any analysis.
3. Save JASP file
3. TAB to another window, tab back
4. Try to do any analysis or interact
..
[JASP 2021-11-03 00_26_35 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/7464097/JASP.2021-11-03.00_26_35.Engine.0.log)
[JASP 2021-11-03 00_26_35 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/7464098/JASP.2021-11-03.00_26_35.Desktop.log)
.
[jasp file.zip](https://github.com/jasp-stats/jasp-issues/files/7464103/jasp.file.zip)

EDIT:
I have added a video of the issue. My system resources is also shown in the video.
https://youtu.be/OF_GXNOJ1lY

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by amirmasoudabdol** [comment]
I cannot reproduce this issue. A few questions

1. Does this only happen when you tab between apps? So, if you just run the analysis, save your file, and continue working on JASP, everything works smoothly?
2. Do you know if your computer were particularly busy at that time?
3. Do you use a particularly large dataset?

**Comment by Xeonen** [comment]
> I cannot reproduce this issue. A few questions
> 
> 1. Does this only happen when you tab between apps? So, if you just run the analysis, save your file, and continue working on JASP, everything works smoothly?
> 2. Do you know if your computer were particularly busy at that time?
> 3. Do you use a particularly large dataset?

Hello, I have uploaded a video showing the bug. It is a clear screen recording. I will also explain here in text.
https://youtu.be/OF_GXNOJ1lY

1. If I do not switch between apps I still get a large delay. When I switch, the delay gets much worse.
2. No, and I have been able to reproduce the issue with a very low CPU and RAM usage with a few apps running (notepad, system info etc)
3. No, I reproduced the problem in a dataset with 3 attributes and 126 cases.

**Comment by JorisGoosen** [comment]
Thank you for uploading the video and making such a clear bugreport!

Very weird behaviour... We'll get to the bottom of this, I'm just not sure yet how.

**Comment by icekylin** [comment]
I also seem encountered the same issue. I used the installation loaded from the ZIP file. After running the analysis of JASP, when I jumped from another application window to the JASP interface, there would usually be suspended animation and crash.here is log file for the issue, and data file is a JASP example file.
[JASP 2021-11-04 21_39_53 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/7475297/JASP.2021-11-04.21_39_53.Desktop.log)
[JASP 2021-11-04 21_39_53 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/7475298/JASP.2021-11-04.21_39_53.Engine.0.log)
[JASP 2021-11-04 21_39_53 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/7475299/JASP.2021-11-04.21_39_53.Engine.1.log)

**Comment by JorisGoosen** [comment]
Well you could help out by trying this testversion of JASP: https://static.jasp-stats.org/JASP-SlowdownProfiler-Test.zip

It will print a whole lot more information on what is happening inside JASP and, in the end at exit, how long certain operations took. If you could run JASP and use it for a bit while it is displaying the slowdowns and then upload the logs here then that would be quite helpful.

**Comment by Xeonen** [comment]
> Well you could help out by trying this testversion of JASP: https://static.jasp-stats.org/JASP-SlowdownProfiler-Test.zip
> 
> It will print a whole lot more information on what is happening inside JASP and, in the end at exit, how long certain operations took. If you could run JASP and use it for a bit while it is displaying the slowdowns and then upload the logs here then that would be quite helpful.

Hello, sorry for the late reply. I've recorded another video with the profiler, added the logs, video, and my dxdiag report.

Video
https://youtu.be/Ry79ld4VrTc

Logs
[JASP 2021-11-07 19_50_27 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/7492715/JASP.2021-11-07.19_50_27.Engine.0.log)
[JASP 2021-11-07 19_50_27 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/7492716/JASP.2021-11-07.19_50_27.Desktop.log)

DxDiag
[DxDiag.txt](https://github.com/jasp-stats/jasp-issues/files/7492718/DxDiag.txt)

**Comment by JorisGoosen** [comment]
Ok, so I will be trying to get a build of JASP which uses a newer version of QWebEngine (aka the resultsview).

In the meantime we could test if it is caused by `ANGLE` (which renders opengl through directx) and might be part of the slowdown.

If you open up a command-prompt, navigate to wherever `JASP.exe` is and then set `QT_OPENGL=desktop` it will use the proper drivers.
```
D:\>cd JASP\JASP-nightly-development-a6d5fc56cf9d8d909535139264aa674d4628fa6d
D:\JASP\JASP-nightly-development-a6d5fc56cf9d8d909535139264aa674d4628fa6d>set QT_OPENGL=desktop
D:\JASP\JASP-nightly-development-a6d5fc56cf9d8d909535139264aa674d4628fa6d>JASP.exe
```

When I have the other build ready I will post it here.

**Comment by Xeonen** [comment]
> Ok, so I will be trying to get a build of JASP which uses a newer version of QWebEngine (aka the resultsview).
> 
> In the meantime we could test if it is caused by `ANGLE` (which renders opengl through directx) and might be part of the slowdown.
> 
> If you open up a command-prompt, navigate to wherever `JASP.exe` is and then set `QT_OPENGL=desktop` it will use the proper drivers.
> 
> ```
> D:\>cd JASP\JASP-nightly-development-a6d5fc56cf9d8d909535139264aa674d4628fa6d
> D:\JASP\JASP-nightly-development-a6d5fc56cf9d8d909535139264aa674d4628fa6d>set QT_OPENGL=desktop
> D:\JASP\JASP-nightly-development-a6d5fc56cf9d8d909535139264aa674d4628fa6d>JASP.exe
> ```
> 
> When I have the other build ready I will post it here.
> 
> Edit: No need for a video or all that, just a confirmation that it fixes the slowdown or not is fine.

I tried with the stable 1.16, nightly 1.16 installed, nightly 1.16 zip. None of them worked so far.

Is there anything on my machine that I can install/reinstall/uninstall to troubleshoot?

**Comment by JorisGoosen** [comment]
Ah thanks @Xeonen !
Too bad it didn't help.

Right now I'm working on getting JASP running with Qt 6.2, but this is a bit of work and will probably take me at least another day. Once I have a version you can use to test I will let you know.

**Comment by Xeonen** [comment]
> Ah thanks @Xeonen ! Too bad it didn't help.
> 
> Right now I'm working on getting JASP running with Qt 6.2, but this is a bit of work and will probably take me at least another day. Once I have a version you can use to test I will let you know.

It is okay, I will test any version if needed. For now I'm using v14 and getting by.

**Comment by JorisGoosen** [comment]
Alright, I've managed to get a prototype version of JASP using Qt6, you can get it here: https://static.jasp-stats.org/JASP-Qt6-testing.zip

And I really hope this solves the slowdown. There might be other things wrong with it though, I had to change quite some unrelated things as well to get this running.

**Comment by Xeonen** [comment]
> Alright, I've managed to get a prototype version of JASP using Qt6, you can get it here: https://static.jasp-stats.org/JASP-Qt6-testing.zip
> 
> And I really hope this solves the slowdown. There might be other things wrong with it though, I had to change quite some unrelated things as well to get this running.

@JorisGoosen works like a charm! There is no more stutter or freezing. ANOVA module appears to be dead though.

**Comment by JorisGoosen** [comment]
Awesome!

Well, I'm going to guess more analyses are dead, but that will be the next step ;)

If this really fixes the annoying bug then we will have a bugfix release coming up in the near future where they *do* work ^^

**Comment by Xeonen** [comment]
> Awesome!
> 
> Well, I'm going to guess more analyses are dead, but that will be the next step ;)
> 
> If this really fixes the annoying bug then we will have a bugfix release coming up in the near future where they _do_ work ^^

@JorisGoosen 
Thanks a lot for all the work poured into the JASP. I hope one way I will be able to return the favor by doing commits.

**Comment by Arwa-AA** [comment]
Hi Joris Goosen,

Allow me to add to the discussion my observation on the issue as well:
1. Using the same data file I used in the previous version (JASP 14), it was working fine in JASP 14, but some having some issues in JASP 15 and 16.  I think JASP 16 performs better than JASP 15 though! 
2. Currently, to use JASP 16, I close all web browsers and some other open files/tools so JASP will not crash. 
3. with performing #2, still JASP 16 is slow especially when I try to change a variable type (e.g. from scale to ordinal) or when I try to filter out some values. It takes few seconds to provide me the options to do so.

I am also using windows 10.

Hope this input helps!

**Comment by JorisGoosen** [comment]
@Arwa-AA have you also tried with https://static.jasp-stats.org/JASP-Qt6-Testing-2.zip ?
