### ISSUE TITLE
[Feature Request]:  CI in descriptives table

### ISSUE THREAD

**Issue by ajestudillo** [jasp-stats/jasp-issues#1492]
### Description

When you do a test statistic, such as a t-test, there is an option to include CI in the graph. I think it would be a good to have the same option for the descriptives table.

### Purpose

the CI for the means can be seen numerically.

### Is your feature request related to a problem?

There is not a numerical indicator of CI for means 

### Describe the solution you would like

the possibility of including the CI in the descriptives table, similarly as it happens for the plots

**Comment by tomtomme** [comment]
@ajestudillo 
There is the SE in the descriptives table. Double it and you get the 95% CI. Is this sufficient?
You can also get any CI for means and SDs within the descriptives module now, I think since JASP 0.17 or so.

Can you test this new functionality and give feedback if this is sufficient?
