### ISSUE TITLE
[Feature Request]: Standardized factor loadings with CFA

### ISSUE THREAD

**Issue by uta-connolly** [jasp-stats/jasp-issues#1493]
### Description

Looking for standardized factor loadings with CFA

### Purpose

To compare factor loadings on a standardized scale when using confirmatory factor analysis

### Additional context

I do not see an output to request standardized factor loadings when doing Confirmatory Factor Analysis.

**Comment by juliuspf** [comment]
Hi, thanks for the FR, I think this should already be possible, shouldn't it. If you unfold the "Advanced" tab. See my screenshot. You can choose what standardization should be in the output table. Is that sufficient for you?
![Screenshot 2021-11-09 at 09 48 09](https://user-images.githubusercontent.com/38500953/140892313-562d779d-8fb0-4e21-8eff-b08b8179ebd9.png)

**Comment by juliuspf** [comment]
@JMBKoch Could you confirm this, then we can close this issue.

**Comment by JMBKoch** [comment]
@juliuspf @uta-connolly  Yes indeed, you can specify the desired standardization method under the Advanced tab, so I'm closing this issue.

**Comment by uta-connolly** [comment]
Hello and Apologies, I’m out of the office till next week. From your description I’m happy for it to be closed out. Otherwise, I will be able to follow up next week.
Really appreciate how quickly you were able to respond and add this to your CFA features.
Best regards,
John Connolly

On Nov 13, 2021, at 1:30 PM, JMBKoch ***@***.***> wrote:

﻿

[External]

@juliuspf<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjuliuspf&data=04%7C01%7Cconnolly%40uta.edu%7C4aa4791637014f6485f208d9a6a9ba11%7C5cdc5b43d7be4caa8173729e3b0a62d9%7C1%7C0%7C637724070180991415%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=u2hP547WOPZboYSWfnmYsSRLRBARln3%2Fun7QjvKxK%2B0%3D&reserved=0> @uta-connolly<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Futa-connolly&data=04%7C01%7Cconnolly%40uta.edu%7C4aa4791637014f6485f208d9a6a9ba11%7C5cdc5b43d7be4caa8173729e3b0a62d9%7C1%7C0%7C637724070180991415%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=R9drjdnUQ%2BJcQxNCQnCAA7QmT1v0aXvPbg%2FYYNhFypg%3D&reserved=0> Yes indeed, you can specify the desired standardization method under the Advanced tab, so I'm closing this issue.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjasp-stats%2Fjasp-issues%2Fissues%2F1493%23issuecomment-968068952&data=04%7C01%7Cconnolly%40uta.edu%7C4aa4791637014f6485f208d9a6a9ba11%7C5cdc5b43d7be4caa8173729e3b0a62d9%7C1%7C0%7C637724070181001377%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bvrGlGalDvUrFwbUJLJhGFaEjvBtSbj4vooMjj2mIA8%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG4KUHTZXFG5YTIGEZ5L3Z3ULZR6NANCNFSM5HJWMCGA&data=04%7C01%7Cconnolly%40uta.edu%7C4aa4791637014f6485f208d9a6a9ba11%7C5cdc5b43d7be4caa8173729e3b0a62d9%7C1%7C0%7C637724070181001377%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dT0N%2BDDH%2FuHp%2BFdmZN2Oj2Xq0uAGlODbuseNeRXi94Y%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cconnolly%40uta.edu%7C4aa4791637014f6485f208d9a6a9ba11%7C5cdc5b43d7be4caa8173729e3b0a62d9%7C1%7C0%7C637724070181011330%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BoEbRu%2FZzgIIdT96doAWlg7RwuGgM6rJVIYPkdE21v8%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cconnolly%40uta.edu%7C4aa4791637014f6485f208d9a6a9ba11%7C5cdc5b43d7be4caa8173729e3b0a62d9%7C1%7C0%7C637724070181011330%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yN%2FnOU4JD1j%2FWFBBlcdXObGtTyu%2BNUvkgfdqLpUBKyQ%3D&reserved=0>.
