### ISSUE TITLE
[Bug]: JASP 0.16 crash  with help info content Copy

### ISSUE THREAD

**Issue by icekylin** [jasp-stats/jasp-issues#1494]
### JASP Version

JASP 0.16

### Commit ID

2a93b3077ed005781f4c2195e95ee24896dd60bb

### JASP Module

jaspFrequencies

### What analysis are you seeing the problem on?

Bayesian A/B Test

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I opened the JASP (from ZIP file document) frequency analysis module. I clicked the info button and copy the content of the document, it crashed when I copy some content.
I suspect that this problem has something to do with the slower running speed reported earlier. Usually it becomes slow and freezes after running JASP for about 3 minutes. This crash is more likely to occur. Will this be more associated with the built-in browser, some browser menus will stay on the screen.
![Snipaste_2021-11-07_11-17-24](https://user-images.githubusercontent.com/10348402/140631238-2da04bd8-4309-4a98-b3ed-b86e3610924b.png)

### Expected Behaviour

Can copy some content and not crash.

### Steps to Reproduce

1. Open a example data file
2. Click the JASP Frequencies
3. Add a Bayesian A/B Test
4. Click the info button for help
5. Select some content and right click to copy that(Maybe need to try a few more times)
6. Crash happened
...

### Log (if any)
[Logs.zip](https://github.com/jasp-stats/jasp-issues/files/7490576/Logs.zip)

### Final Checklist

- [x] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by icekylin** [comment]
I tried #1431 JASP-Qt6-Testing-2.zip it works well!
Thank you!

**Comment by JorisGoosen** [comment]
Great!

If you keep using this version: it is a development version so their might still be bugs in there we haven't found yet.

**Comment by icekylin** [comment]
@JorisGoosen Yes, I know that it is a alpha version,thanks.
 If you have a new beta release anytime please let me know,I'd also be happy to test it .
