### ISSUE TITLE
[Feature Request]: Explanation of "Covariates" vs. "Factors" in Linear Regression analysis

### ISSUE THREAD

**Issue by isakohrlund** [jasp-stats/jasp-issues#1495]
### Description

There are two boxes for independent variables in the linear regression analysis: covariates AND factors. Only covariates are explained in the "Show info" box, leaving users such as student wondering what the difference is and which to use when.

### Purpose

Improve understanding and reduce mistakes

### Use-case

Teaching

### Is your feature request related to a problem?

Lack of description in the JASP help box for the analysis.

### Describe the solution you would like

Add a description of the difference between excoriates and factors, and which to use when.

**Comment by vandenman** [comment]
Good point. I'll change it in the helpfile, but for your information, `covariates` refers to continuous predictors (e.g., age). `factors` refers to categorical predictors (e.g., gender).

**Comment by isakohrlund** [comment]
Great. Thank you. The confusion is because:
1. Ordinal variables are allowed in both boxes, so where to put such a variable when given the choice?
2. There are two separate boxes, so JASP wants the user to differentiate between "covariates" and "factors" for some reason, which is not explained.

**Comment by vandenman** [comment]
> Ordinal variables are allowed in both boxes

Ordinal variables are tricky. They are not entirely continuous nor categorical and there is no golden rule on what to do with them. If you assume that the levels of an ordinal variable are equidistant, you can enter it as a covariate and will obtain a single coefficient. If you do not want to make this assumption, you can enter it as a factor and obtain a coefficient for each level (except the reference level). For different datasets, it may make sense to perceive one ordinal variable as continuous and another ordinal variable as categorical.
