### ISSUE TITLE
Program freezes when exporting results to html

### ISSUE THREAD

**Issue by Doc13kd** [jasp-stats/jasp-issues#1496]
### JASP Version

0.15

### JASP Module

jaspAnova

### What analysis are you seeing the problem on?

repeated measures anova

### What OS are you seeing the problem on?

windows

### Bug Description

I am creating an instructional video for my students. I have run a repeated measures ANOVA and want to export the results to html to show them how they can then copy that into Word. When I export, the program freezes on "Exporting Result Set"
It does create an html.tmp file in my directory, but never finishes the file.

### Expected Behaviour

The program should have created an html file of the results

![Jasp freezing on export screen shot](https://user-images.githubusercontent.com/93929717/140764662-594db426-4328-45cd-b532-fe5a6df19b8b.png)

### Steps to Reproduce

1. run repeated measures anova
2. select export results - html
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Strange...
Could you try also this: load the Data Library/ANOVA/Alcohol attitudes JASP file, and export the HTML file. Try also to export the Result PDF file.
Also it would be fine to have your log files: https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/user-guide/logging-howto.md

**Comment by JorisGoosen** [comment]
@Doc13kd  could you test with: https://static.jasp-stats.org/JASP-Qt6-testing.zip

This could solve the problem, Im curious if it does.

There might be other things wrong with it though, I had to change quite some unrelated things as well to get it running (with Qt6).

**Comment by Doc13kd** [comment]
Hi Joris –

Thank you for getting back to me. I actually found a work around where I don’t need to export it to HTML and right now don’t have the time to go back and play around withit.

Kathy

Dr. Kathleen T. Doherty
Senior Professor of Psychology
Harrisburg Area Community College
One HACC Drive, W 211
Harrisburg, PA 17110

717-780-2496
***@***.******@***.***>

************************************************************
“I long to accomplish a great and noble task, but it is my chief duty
to accomplish small tasks as if they were great and noble.” (Helen Keller)
************************************************************

**Comment by JorisGoosen** [comment]
Alright, well, then I'm closing this issue.

ood you found a way around it.
