### ISSUE TITLE
[Bug]: JASP won't reopen existing JASP files.

### ISSUE THREAD

**Issue by QBWoof** [jasp-stats/jasp-issues#1497]
### JASP Version

0.14

### JASP Module

jaspSem

### What analysis are you seeing the problem on?

Path analysis (SEM)

### What OS are you seeing the problem on?

MacOS 10.14 and Windows 10

### Bug Description

I am able to open JASP and run my analyses from a new file. However, if that file closes, I am unable to reopen it again. JASP will open, it appears to "load the file," the window disappears, and then JASP never re-opens. I have tried this on multiple computers (mac and PC) and have the same issue. I assume there's a trick that I am unaware of. Any help would be appreciated!

Sincere thanks. 

### Expected Behaviour

I would assume that the file would open and I would be able to view former analyses. 

### Steps to Reproduce

1. Try to re-open existing JASP file from my computer.
2. Wait for JASP to open, load file, and then never re-open again.
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JorisGoosen** [comment]
@QBWoof could you attach a zipfile here containing one or more of these broken jasp-files?

And have you tried 0.15 already?
