### ISSUE TITLE
[Bug]: JASP program won't stay open

### ISSUE THREAD

**Issue by Arcanelady** [jasp-stats/jasp-issues#1498]
### JASP Version

0.15

### What OS are you seeing the problem on?

Windows 10

### Bug Description

JASP won't stay open on my computer.

### Expected Behaviour

JASP should stay open when downloaded.

### Steps to Reproduce

1. 
2. 
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment]
Hi @Arcanelady, could you try the latest JASP version and see if the issue persists?
