### ISSUE TITLE
[Feature Request]: Option to choose between Exclude pairwise/Exclude list wise 

### ISSUE THREAD

**Issue by Psychowannabe** [jasp-stats/jasp-issues#1499]
### Description

Option to choose between Exclude pairwise/Exclude list wise - Classical Linear Regression

### Purpose

It would be amazing to allow us the option to choose between exclude cases pairwise or exclude cases listwise when using the classical linear regression analysis. I know this option is already available in other features of JASP but I guess it's missing for the frequentist linear regression. It seems that as of the moment, it defaults to exclude listwise when running classical linear regressions.

**Comment by boutinb** [comment]
@vandenman Could you answer this request?

**Comment by vandenman** [comment]
unfortunately, there is no clean way to implement pairwise deletion (e.g., without bootstrapping), so I don't think we will implement this soon. However, it is on our agenda to use the R package mice for imputing missing values, which should provide an alternative.

**Comment by tomtomme** [comment]
MICE is tracked here: https://github.com/jasp-stats/jasp-issues/issues/1362
closing since duplicate
