### ISSUE TITLE
[Bug]: Analysis Terminated Unexpectedly

### ISSUE THREAD

**Issue by StudentKate** [jasp-stats/jasp-issues#1500]
### JASP Version

0.14

### JASP Module

jaspReliability

### What analysis are you seeing the problem on?

Single- Test Reliability

### What OS are you seeing the problem on?

ADAPT

### Bug Description

![JASP Reliability](https://user-images.githubusercontent.com/84303770/141609701-bcfe2b37-872b-4262-9a00-967a33651508.PNG)

I am using JASP through the University of Adelaide virtual desktop they call ADAPT as I have had problems openning JASP on my desk top. I have am using Chrome at the moment- I will try another browser and see if that helps. 

### Expected Behaviour

I was trying to run a reliability analysis for an assignment. 

### Steps to Reproduce

1. drag the items across that i am checking
2. under single-test reliability
-unclick confidence interval and Mc Donald's w.
3. the analysis is terminated
...

### Log (if any)

```bash
Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.frequentistReliabilityMainResults(jaspResults, dataset, options)
```

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment]
Hi @StudentKate, could you try jasp version 0.15 and see if the issue persists?

**Comment by juliuspf** [comment]
I will close this for now, @StudentKate feel free to reopen it if your concerns have not been addressed sufficiently.
