### ISSUE TITLE
[Bug]: ANCOVA, ANOVA, Visual Modeling Module completely broken in 0.16 beta flatpak

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#1502]
### JASP Version

0.15 (Development)

### JASP Module

jaspVisualModeling

### What analysis are you seeing the problem on?

all in visual modeling

### What OS are you seeing the problem on?

manjaro linux

### Bug Description

This is since the 0.16 beta (flatpak) 

Opening any analysis of the visual modeling module gives this error:

```
This analysis terminated unexpectedly.

Error in flexplot(...): object 'flexplot_jasp2' not found

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

...
```
I do not even need to enter any variable.

### Expected Behaviour

the module should work

### Steps to Reproduce

open any analysis of visual modeling module

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
I cannot reproduce this problem on Mac, nor on Windows.

**Comment by vandenman** [comment]
@boutinb it's flatpak specific. The GitHub tarball of flexplot is 180 MB, so to reduce the size I filter everything according to .Rbuildignore. But the .Rbuildignore actually filters the R files that implemented JASP-specific things...

**Comment by tomtomme** [comment]
yep. Flatpak.
I just verified this error on a second machine.
If the easy solution is for JASP to become big, then just do it. I guess flatpak users can handle a download of some Gigabytes.

**Comment by vandenman** [comment]
> If the easy solution is for JASP to become big

JASP is already (way) too big in my opinion, but luckily it's very easy to fix this bug without making JASP even bigger.

**Comment by tomtomme** [comment]
yes it got big. Thats a problem for devs I guess?

For me as a user its more important, that it is stable. 
Students seeing JASP crash in some way is bad. This issue got caught in beta, so that is fine. But the last flatpak/Qt-issue was not. JASP crashed in front of the class, while I was trying to re-lable and quick-filter. A student immidiately asked if we should switch to SPSS :D  - if he only knew. He never used SPSS, just heard of older students using it....

**Comment by vandenman** [comment]
Yeah, the Qt situation is terrible with flatpak (see e.g., https://github.com/flathub/io.qt.qtwebengine.BaseApp, which we are forced to use to ship JASP with flatpak). Hopefully, this gets better with Qt 6, but otherwise, we may need to look into shipping JASP differently on Linux.

**Comment by tomtomme** [comment]
Clicking ANOVA or ANCOVA crashes JASP without error message on 0.16 beta. All other main buttons seem fine. I guess this is a related flatpak issue. If I remember correctly we had this before with ANOVA. Or should I open a new bug report?

**Comment by vandenman** [comment]
@tomtomme does the issue persist after you follow the steps in https://github.com/jasp-stats/jasp-issues/issues/1424?

**Comment by tomtomme** [comment]
I tried, but cannot aply the fix on this machine. At home I applied the fix successfully some weeks ago. No clue what changed. Both machines use manjaro. flatpak repair does not help either.

```
flatpak --user update --commit=212d267860a3001081816007b074dd57993335aec23485c082d40034c6a5b857 org.kde.Platform/x86_64/5.15
Looking for updates…
Fehler: org.kde.Platform/x86_64/5.15 not installed

flatpak update --user --commit 4f232783b07952a4627a186c8020a362d2458c4b2d6046fbd0b43d3f44c551a7 org.kde.Sdk/x86_64/5.15
Looking for updates…
Fehler: org.kde.Sdk/x86_64/5.15 not installed

flatpak install org.kde.Sdk/x86_64/5.15
Looking for matches…
Skipping: org.kde.Sdk/x86_64/5.15 is already installed
```

**Comment by tomtomme** [comment]
the crash however apears only with 0.16 beta. With 0.15 AN(C)OVA and flexplot are fine. And the fix above was for 0.15 I think.

**Comment by vandenman** [comment]
In the latest beta version, available through `flatpak install https://dl.flathub.org/build-repo/65097/org.jaspstats.JASP.flatpakref`, visual modeling should no longer crash.

**Comment by tomtomme** [comment]
ANOVA / ANCOVA is also fixed with this
