### ISSUE TITLE
[Bug]: Inclusion of + or - in group labels is permitted, but leads to malformed labelling of output (classical ANOVA->post-hoc test )

### ISSUE THREAD

**Issue by MikeAitkenDeakin** [jasp-stats/jasp-issues#1503]
### JASP Version

0.15

### JASP Module

jaspAnova

### What analysis are you seeing the problem on?

Post hoc

### What OS are you seeing the problem on?

Windows 10

### Bug Description

ANOVA module allows factor level names that includes symbol sequence " - " .
Use of this symbol sequence in group/level name breaks the output of pairwise post-hoc test.

See in attached example
[EXAMPLE.zip](https://github.com/jasp-stats/jasp-issues/files/7546054/EXAMPLE.zip)

Conjecture: the label for second group replaced by a substring of first group following the " - " subsequence). Presumably arises due to mis-parsing of a string representation of the contrast. 

Note similar sequences such as "a + z"; "a- z"; "a -z" do not produce issue

### Expected Behaviour

Preferred 
Output table contains correct group names when group label name contains **" - "**

### Steps to Reproduce

1. Open Data Library data set "Anova/Pain Threshold"
2. In ANOVA analysis panel add Post Hoc test (move Hair Colour to RH panel)
3. Output is correctly formatted
<img width="1464" alt="screenshot" src="https://user-images.githubusercontent.com/20127596/141990462-9aa800fa-d83d-479a-a4a6-dfc332c1d0c4.png">
4. In data pane, edit labels for the 3 values of **Hair Colour** variable to contain " - " sequence (e.g. **Dark - Blond**)
5. output of post-hoc test is now incorrectly formatted
<img width="1464" alt="screenshot" src="https://user-images.githubusercontent.com/20127596/141990243-f935158e-3a8e-46be-b4c8-ca81b7d386ce.png">

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@MikeAitkenDeakin 
can confirm
still present on 0.18.3 flatpak

**Comment by tomtomme** [comment]
@MikeAitkenDeakin 
closing, as now tracked here: https://github.com/jasp-stats/jasp-issues/issues/2564
