### ISSUE TITLE
[Bug]: Dataset can be opened, but associated syntax (modules / results) cannot be opened

### ISSUE THREAD

**Issue by AnSoGrub** [jasp-stats/jasp-issues#1504]
### JASP Version

0.14

### What OS are you seeing the problem on?

Windows 10

### Bug Description

Unfortunately, a data set can still be opened, but the associated calculations/modules can no longer be opened. 
The error message is attached as an image (figure1). The specified path cannot be found on the PC (figure 2). Unfortunately, I can't upload the dataset itself here, because it's privacy-sensitive data.

A new installation of JASP (both the originally used version, nor version 15 or 16) are purposeful.

figure 1
![grafik](https://user-images.githubusercontent.com/94522749/142163639-b5c2d6df-3602-4308-991a-7fa25077619f.png)

figure 2
![grafik](https://user-images.githubusercontent.com/94522749/142163726-8c299c41-b59b-492a-bcdb-f95419e2b39c.png)

### Expected Behaviour

The modules/calculations should be output - not just the data set.

### Steps to Reproduce

No reproduction possible - it concerns only 2 data files

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JorisGoosen** [comment]
@AnSoGrub can you test whether 0.15 works better? (Or 0.16 which we will likely release in two hours).

**Comment by AnSoGrub** [comment]
With 0.15 the file does not open at all (so also the record that still opens with 0.14.1 does not open with 0.15). Only the "start screen" of JASP appears briefly and then disappears again - JASP is also not present in the Task Manager of Windows.

**Comment by JorisGoosen** [comment]
The error message you printscreened in your issue, with which version of JASP is that made?
The same goes for the picture of the JASP folder.

Also which language is your computer set in?

**Comment by AnSoGrub** [comment]
The error message and the folder is from version 0.14.1. The data is created with this version.
With a newer version (0.15 or 0.16) the file does not open at all.

Yes, it is german.

**Comment by JorisGoosen** [comment]
Well, the main problem is that the modules won't load in 0.14.1 though right?

If you start 0.16 from an unpacked zip https://static.jasp-stats.org/JASP-0.16.0-64bit.zip and you double-click `jasp.exe` do you see the message warning you it needs to recreate some module-folders?

And after you see the welcome screen can you check whether it has created a `Modules` in there?
