### ISSUE TITLE
[Feature Request]: Standard errors for effect sizes across JASP

### ISSUE THREAD

**Issue by Trebicky** [jasp-stats/jasp-issues#1506]
### Description

Effect size standard errors

### Purpose

When running a meta-analysis in JASP, we need to enter effect size and effect size standard error. But JASP does not report results (e.i. for t-tests or correlations) including SE of the given resulting effect. Purpose would be no need to calculate SEs externaly or by hand.

### Use-case

I want to meta-analyse my own results and do all inside JASP - the individual analyses that would feed the meta-analysis and the meta-analysis.

### Is your feature request related to a problem?

Meta-analysis module wants SE but analyses in JASP do not report SE.

### Describe the solution you would like

Include a check box of whether I want to display CI and/or SE for my effects.

### Describe alternatives that you have considered

Or let me enter effect size and sample size instead of SE in the meta-analysis module.

### Additional context

The vast majority of studies one usually needs to put into a meta-analysis does not come with SE for their effect (seldom we find CI), but sample size usually can be extracted. That leads people to look for unnecessary external solutions or calculate things by hand.

Consider including more inclusive options what data to input into meta-analysis module and provide results from JASP with data that are needed across modules in JASP - like SE for effects for Meta-analysis.

I am an avid user and advocate of JASP. But these small issues and inconsistencies represent considerable hurdles for people to embrace current best practices that JASP clearly has in mind. This particular small step may be the enabling point for many to include meta-analysis into their active analytic toolkit.

Another option might be the development of some new modules for conversions between effect sizes and calculation of these particularities like SE for effects. Maybe inspired by https://www.psychometrica.de/effect_size.html ?

Thank you for a great job!

**Comment by EJWagenmakers** [comment]
Dear Trebicky,

Thanks for this feedback. To me surprise, JASP indeed does not return standard errors for effect sizes. JASP does return confidence intervals, but that's not the same. So I think the easiest solution is just to add the SEs everywhere, and automatically, as the numbers cannot be interpreted without the SE anyway. This is really imporant to we will prioritize this.
Also thanks for that useful link on effect sizes. We are working on something similar but this useful resource had escaped us.

Cheers,
E.J.

**Comment by Trebicky** [comment]
I am delighted to hear this, and I am happy it would be an easy fix for you. I am looking for ver 0.15.x including this :-)

It is rather a painful struggle to find out that the analysis only gives some numbers, but you need other numbers to proceed on.

I found it most irritating when discovering G*Power that sometimes needed effect sizes no analysis provided by default or at all, and I had to take several intermediate steps with fingers crossed to reach some results.

Having an internal tool for the conversion of effects that JASP gives and needs will be great.

I know the stronger focus for JASP development is on Bayesian approaches, but do you plan on some freq Power analysis tools (sensitivity, at least) for tests provided within JASP?

**Comment by EJWagenmakers** [comment]
We have that under development as well.
EJ

**Comment by Trebicky** [comment]
Sweet sweet future!
