### ISSUE TITLE
[Bug]: zscore and if/else not working

### ISSUE THREAD

**Issue by rsbalkin** [jasp-stats/jasp-issues#1507]
### JASP Version

0.15 / 0.16

### What analysis are you seeing the problem on?

Regression

### What OS are you seeing the problem on?

Big Sur 11.6

### Bug Description

will not form zscores; will not transform if/else/then
error syntax below

### Expected Behaviour

columns would fill

### Steps to Reproduce

1. add a variable (+)
2. select Zscores(y)
3. insert scale variable

see above error syntax. No column filled

A similar issue occurs with the if/else(y)
1. add a variable
2. create statement using scaled variable (e.g., ifElse (scaledvar >= 40,1,0)

see error syntax; no column fill
![Screen Shot 2021-11-18 at 7 31 54 PM](https://user-images.githubusercontent.com/55462112/142540972-1aa8e250-a45b-4d8b-a4ac-f7b8f8fb8823.png)
![Screen Shot 2021-11-18 at 7 32 30 PM](https://user-images.githubusercontent.com/55462112/142540981-b9851fee-fa20-4802-a9e2-5bf9b71b726e.png)
[HSB messed up.csv](https://github.com/jasp-stats/jasp-issues/files/7567165/HSB.messed.up.csv)
ed

### Log (if any)

```bash
Error: no applicable method for 'zScores' applied to an object of class "c('double', 'numeric')"
tryCatch(suppressWarnings({
    returnVal <- eval(parse(text = .rCode))
}), error = function(e) {
    .setRError(paste0(toString(e$message), "\n", paste0(sys.calls(), collapse = "\n")))
})
tryCatchList(expr, classes, parentenv, handlers)
tryCatchOne(expr, names, parentenv, handlers[[1]])
value[[3]](cond)


Error: no applicable method for 'ifElse' applied to an object of class "c('double', 'numeric')"
tryCatch(suppressWarnings({
    returnVal <- eval(parse(text = .rCode))
}), error = function(e) {
    .setRError(paste0(toString(e$message), "\n", paste0(sys.calls(), collapse = "\n")))
})
tryCatchList(expr, classes, parentenv, handlers)
tryCatchOne(expr, names, parentenv, handlers[[1]])
value[[3]](cond)
```

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by vandenman** [comment]
Thanks for the bug report! JASP 0.16 was released a few days ago. Could you see if the issue persists with version 0.16? (I was not able to replicate the error in 0.16 on my end, let's hope it also works for you).

**Comment by rsbalkin** [comment]
It is .16 as well. Same errors I recorded

**Comment by rsbalkin** [comment]
Columns are not filling on the Mac system (Big Sur 11.6).  This is a problem in 0.16 as well.  Not sure what the problem is.
Rick Balkin
***@***.***

**Comment by djdekker** [comment]
I can confirm the zScores issue on macOS Monterey 12.0.1 and JASP 0.16.

**Comment by rsbalkin** [comment]
Yes.  Also happens with if/else

Richard S. Balkin, Ph.D., LPC, NCC
Fellow, American Counseling Association
Professor and Interim Chair
Department of Leadership and Counselor Education
School of Education
University of Mississippi
Editor, International Journal for the Advancment of Counselling
Fellow, American Counseling Association
email: ***@***.***

**Comment by rsbalkin** [comment]
I just re-installed JASP, but the same errors occur. Has this been resolved?

Thank you,

Rick
Rick Balkin
***@***.***

**Comment by vandenman** [comment]
Hi @rsbalkin this is now solved in the development version of JASP, not in the released version. So the next version of JASP should no longer have this issue. If you want to try it out before then, you could try a nightly version (see https://static.jasp-stats.org/Nightlies) at the moment of writing the nightlies have not yet been built, so you may need to wait another day or so.

**Comment by rsbalkin** [comment]
Thank you!
