### ISSUE TITLE
[Feature Request]: Specifying number of digits after the decimal point - minor improvement

### ISSUE THREAD

**Issue by dsoergel** [jasp-stats/jasp-issues#1508]
### Description

Do not apply that specification to numbers like chi-square, t, F, correlation coefficient, or the level of significance p, and similar cases

### Purpose

Having these types of numbers curtailed to integers does not make sense, while for data values, mean, mode and such it might.

### Describe the solution you would like

See description

**Comment by vandenman** [comment]
Could you be more specific in what your feature request adds in addition to the current options? For example, it is already possible to change the number of decimals (for non-integer numbers) and also show exact p-values instead of `p<0.05`:

![image](https://user-images.githubusercontent.com/21319932/142585277-f6e1d3b9-ab3c-4e4b-a3a4-1b84b50af0a6.png)

**Comment by dsoergel** [comment]
Sorry, I had overlooked the exact p values 
option. But that still does not address the other 
types of numbers I mentioned, such as any type of 
correlation or association measures. So it would 
make sense for the program to have a list of 
these types of measures and not apply the number 
of decimals specified by the user to those. I may 
want data values, means, and modes displayed as 
integers (counts, test scores usually given as 
integers) and still have correlation coefficient displayed as 0.67.

I am very new to JASP. In my work, I use 
statistical analysis very rarely. I just this 
semester used a little exercise in JASP to give 
students in an introductory research methods 
course a taste of statistical software.

DS

At 11/19/2021 02:51 AM, you wrote:

**Comment by juliuspf** [comment]
I dont think this is feasible as it would require adding options for many many parameters. But maybe @AlexanderLyNL or @EJWagenmakers are of a different opinion.

**Comment by AlexanderLyNL** [comment]
We have this as far as I know. As mentioned by Don, the number of decimals can be set for non-integer numbers using the the Results preference. 

<img width="1360" alt="Screenshot 2022-10-04 at 12 27 04" src="https://user-images.githubusercontent.com/10271675/193797001-448f7a00-62c2-4c08-b00c-c6cd2b1e2036.png">

I'll close this issue for the moment. If it's unclear, then please reopen.

**Comment by EJWagenmakers** [comment]
I agree. However, when JASP knows a number is an integer, it should obviously not give any decimals. When JASP does do this, it is an oversight that we should fix.
