### ISSUE TITLE
[Bug]: CFA Crashes

### ISSUE THREAD

**Issue by ludwigkreuzpointner** [jasp-stats/jasp-issues#1509]
### JASP Version

Others

### JASP Module

jaspSem

### What analysis are you seeing the problem on?

Confirmatory Factor Analysis

### What OS are you seeing the problem on?

Windows 10

### Bug Description

The analysis is working, but when I click on Model plot, this error message apply as long as the variables are ordinal. When changing them to scale is works.

CFA Crashes when Model plot is activated: Error in 

`bars[[node]] <- pnorm(GroupThresh$est[GroupThresh$lhs = GroupVars$name[node]]): attempt to select more than one element in integerOneIndex`

### Expected Behaviour

The Model plot should be shown?!

### Steps to Reproduce

1. In Version 0.16 it seems to become possible to insert ordinal variables in CFA. But then the model plot don't work.

### Log (if any)

```bash
This analysis terminated unexpectedly.

Error in bars[[node]] <- pnorm(GroupThresh$est[GroupThresh$lhs = GroupVars$name[node]]): attempt to select more than one element in integerOneIndex

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

ConfirmatoryFactorAnalysis(...)

.cfaPlotPath(jaspResults, options, cfaResult)

jaspBase:::.suppressGrDevice(pathplot <- semPlot::semPaths(object = .cfaLavToPlotObj(cfaResult[['lav']], options), DoNotPlot = TRUE, ask = FALSE, layout = 'tree', intercepts = options$plotmeans, whatLabels = if (!options$plotpars) 'name' else if (options$plotstd) 'std' else 'par', mar = ifelse(rep(is.null(options$secondOrder), 4), c(12, 3, 12, 3), c(6, 3, 6, 3)), edge.color = 'black', color = list(lat = '#EAEAEA', man = '#EAEAEA', int = '#FFFFFF'), border.width = 1.5, edge.label.cex = 0.9, lty = 2,
    title = FALSE))

eval(plotFunc, parent.frame())

eval(plotFunc, parent.frame())

semPlot::semPaths(object = .cfaLavToPlotObj(cfaResult[['lav']], options), DoNotPlot = TRUE, ask = FALSE, layout = 'tree', intercepts = options$plotmeans, whatLabels = if (!options$plotpars) 'name' else if (options$plotstd) 'std' else 'par', mar = ifelse(rep(is.null(options$secondOrder), 4), c(12, 3, 12, 3), c(6, 3, 6, 3)), edge.color = 'black', color = list(lat = '#EAEAEA', man = '#EAEAEA', int = '#FFFFFF'), border.width = 1.5, edge.label.cex = 0.9, lty = 2, title = FALSE)
```

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment]
@ludwigkreuzpointner thank you for the issue! Could you provide some more info about the data and the factor model that lead to this crash? Ideally, a jasp file or a data file with a description of the factor model would be good. Otherwise we cannot diagnose the problem.

**Comment by ludwigkreuzpointner** [comment]
@juliuspf It seems that it does no matter how the model is define. When the variable are ordinal and model plot is chosen, the error message arise. I add an example:

[example.zip](https://github.com/jasp-stats/jasp-issues/files/7903917/example.zip)

**Comment by juliuspf** [comment]
Thanks for the data! Could you try this again with the latest nightly? https://static.jasp-stats.org/Nightlies/ 
I tried your data with the newest version and I do not get the error anymore.

**Comment by juliuspf** [comment]
and apologies for the late reply :)

**Comment by ludwigkreuzpointner** [comment]
Yeah, the latest version works for me either. Thanks.
