### ISSUE TITLE
Saving residuals and factor scores

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-issues#151]
From the forum:

"Can I save factor score, regression residuals, ... in JASP ? I did not see the function, but maybe it is well hidden ?"

Would be useful. Perhaps we can address it once we have "compute columns" working. @JorisGoosen @vankesteren 

E.J.

**Comment by freckledude** [comment]
I also support this feature!

**Comment by juliuspfadt** [comment]
duplicate of https://github.com/jasp-stats/jasp-issues/issues/101

**Comment by tomtomme** [comment]
can be closed, since its a duplicate
