### ISSUE TITLE
[Bug]: JASP 0.16 Crash

### ISSUE THREAD

**Issue by verboten999** [jasp-stats/jasp-issues#1510]
### JASP Version

Others

### What OS are you seeing the problem on?

windows 10

### Bug Description

[JASP 2021-11-22 22_15_03 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/7582269/JASP.2021-11-22.22_15_03.Engine.0.log)
[JASP 2021-11-22 22_15_55 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/7582270/JASP.2021-11-22.22_15_55.Desktop.log)
[JASP 2021-11-22 22_15_55 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/7582271/JASP.2021-11-22.22_15_55.Engine.0.log)
[JASP 2021-11-22 22_16_28 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/7582272/JASP.2021-11-22.22_16_28.Desktop.log)
[JASP 2021-11-22 22_16_28 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/7582273/JASP.2021-11-22.22_16_28.Engine.0.log)
[JASP 2021-11-22 22_09_36 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/7582274/JASP.2021-11-22.22_09_36.Desktop.log)
[JASP 2021-11-22 22_09_36 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/7582275/JASP.2021-11-22.22_09_36.Engine.0.log)
[JASP 2021-11-22 22_10_31 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/7582276/JASP.2021-11-22.22_10_31.Desktop.log)
[JASP 2021-11-22 22_10_31 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/7582279/JASP.2021-11-22.22_10_31.Engine.0.log)
[JASP 2021-11-22 22_11_11 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/7582280/JASP.2021-11-22.22_11_11.Desktop.log)
[JASP 2021-11-22 22_11_11 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/7582281/JASP.2021-11-22.22_11_11.Engine.0.log)
[JASP 2021-11-22 22_15_03 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/7582282/JASP.2021-11-22.22_15_03.Desktop.log)

### Expected Behaviour

Just moving the data by dragging with mouse to inspect data should not crash the software.

### Steps to Reproduce

1. open JASP
2. Drag the data or change scale
3. Crash
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by verboten999** [comment]
Also the last JASP software that did not show this behavior was 0.14.1
If it helps somewhat, it happens both on 
my desktop PC: 
Ryzen 7 3700X
NVidia GTX1080
32GB RAM dual channel

my notebook:
Ryzen 9 5900HX
RTX 3060
32 GB RAM dual channel

**Comment by verboten999** [comment]
Source
JASP.exe

Summary
Stopped working

Date
‎22-‎Nov-‎21 22:10

Status
Report sent

Description
Faulting Application Path:	C:\Program Files (x86)\JASP\JASP.exe

Problem signature
Problem Event Name:	APPCRASH
Application Name:	JASP.exe
Application Version:	0.0.0.0
Application Timestamp:	61925f43
Fault Module Name:	Qt5Quick.dll
Fault Module Version:	5.15.2.0
Fault Module Timestamp:	5fa50aeb
Exception Code:	c0000005
Exception Offset:	000000000006a33d
OS Version:	10.0.19043.2.0.0.256.48
Locale ID:	14345
Additional Information 1:	6ce1
Additional Information 2:	6ce1b96de68e72ab5e94de9874d54b67
Additional Information 3:	c146
Additional Information 4:	c146315565e7ed44d2581af3e487baeb

Extra information about the problem
Bucket ID:	718673e0b21742826e650cdd8bc68c33 (2190170939457965107)

**Comment by juliuspf** [comment]
Hi @verboten999, sorry for the late response. Does the issue persist with the latest JASP version?

**Comment by verboten999** [comment]
Hi,

Unfortunately the problem persists with following error message still:

Error in `[.data.frame`(trainingAndValidationSet, , match(names(trainingAndValidationSet), : undefined columns selected

Stack trace
doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

mlClassificationBoosting(...)

.mlClassificationTableSummary(dataset, options, jaspResults, ready, position = 1, type = 'boosting')

.mlClassificationComputeResults(dataset, options, jaspResults, ready, type = type)

.boostingClassification(dataset, options, jaspResults)

trainingAndValidationSet[, match(names(trainingAndValidationSet), all.vars(formula))]

`[.data.frame`(trainingAndValidationSet, , match(names(trainingAndValidationSet), all.vars(formula)))

stop('undefined columns selected')


Regards

**Comment by boutinb** [comment]
The reproduction path is quite unclear. The last error shows that you are using a machine learning analysis.
Can you describe step by step precisely what you do, and give some screenshots?

**Comment by JorisGoosen** [comment]
In fact the problem described in the last comment sounds completely different than the original actual issue (which was a crash and this is a failing analysis)...

**Comment by verboten999** [comment]
Hi,

It seems I'm confusing this issue with the other one I posted earlier. I apologize for that. The crashing issue has been resolved with the new JASP version. Thank you.


Regards
