### ISSUE TITLE
[Bug]: Difference between EFA results between JASP 0.15 and 0.16

### ISSUE THREAD

**Issue by christofnaegele** [jasp-stats/jasp-issues#1513]
### JASP Version

0.16

### JASP Module

jaspFactor

### What analysis are you seeing the problem on?

Exploratory Factor Analysis

### What OS are you seeing the problem on?

MacOs & Win 1§0

### Bug Description

Is this a bug?

I am puzzled as the results I get from an exploratory factor analysis are different when I run the analysis on JASP 0.15 or 0.16. I ran into this issue today, as I was working with my students. I am on JASP 0.16, my students are on 0.15. 

The first picture shoes the results I get running the exploratory factor analysis with JASP 0.15: 
![grafik](https://user-images.githubusercontent.com/45144351/143290928-87ffd575-0021-40cd-a86c-f54a54e8542c.png)

The second with JASP 0.16: 
![grafik](https://user-images.githubusercontent.com/45144351/143290983-ae0081d3-e4f9-41d7-bbd9-3cd404a3b623.png)

The descriptives are the same: 
![grafik](https://user-images.githubusercontent.com/45144351/143290429-683f689d-3a15-4957-8ad4-e8c5519a99ad.png)

If I manually force a three factor structure, I get the same results for JASP 0.15 and 0.16: 
![grafik](https://user-images.githubusercontent.com/45144351/143291093-54731da3-8798-41fc-89ff-6e261c12db01.png)

Why do I get a different factor structure for the parallel analysis, rotation oblique, promax? 
The data set is the same, the paramters are set alike, the missing values are defined in the same way. 

Christof 

### Expected Behaviour

The same results in JASP 0.15 and 0.16.

### Steps to Reproduce

Open data
Run Exloratory Factor Analysis, the same variables 
Tun it on JASP 0.15 and 0.16 = different results. 

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by christofnaegele** [comment]
Sorry, I/it messed up the pictures. 

This is the result of the analysis run on 0.15, a two factor structure, instead the four factor structure reported by JASP 0.16: 
![grafik](https://user-images.githubusercontent.com/45144351/143292224-217475e0-a9e0-4f1d-afed-dd1e38f32d04.png)

Please ignore the first picture, as the results must be differten with a varimax rotation.

**Comment by EJWagenmakers** [comment]
@JMBKoch could you take a look?

**Comment by juliuspf** [comment]
Hi @christofnaegele, thank you for the bug report and catching this disparity. I think this is indeed desired behaviour. There was a "bug" in 0.15 regarding the number of factors retained from parallel analysis (see this PR https://github.com/jasp-stats/jaspFactor/pull/57). In short, the number of factors/components indicated by the parallel analysis can be based on a PCA or an EFA. in 0.15, the number of factors/components coming out of the parallel analysis was always based on a PCA, even when you were working in the EFA tab. In 0.16 this error was fixed, now the parallel analysis inside the PCA tab is always based on a PCA, and inside the EFA tab the parallel analysis always retains the factors from a parallel EFA. For 0.16.1 we will add a button where you can actually choose what your parallel analysis should be based on. Does this answer your question?

We should have mention this in the release notes, and I apologize for the lack of communication.

**Comment by christofnaegele** [comment]
Hi Julius Pfad
Thanks for your quick answer.
Yes, all OK. Great.
Christof
