### ISSUE TITLE
[Bug]:  probability positive plot

### ISSUE THREAD

**Issue by narcilili** [jasp-stats/jasp-issues#1514]
### JASP Version

0.16

### JASP Module

jaspLearnBayes

### What analysis are you seeing the problem on?

binary classification

### What OS are you seeing the problem on?

windows 10

### Bug Description

"Not-tested” correspond to the prior probability of an individual being infected with the disease before being tested which is the prevalence equal to  0.10 . However, the not-tested prior probability of an individual being not infected with the disease before being tested is also 0.10  as shown in the bar plot below

![image](https://user-images.githubusercontent.com/61888367/143659957-fd22ec29-c899-4639-8a76-7440cbfe0ef3.png)

### Expected Behaviour

the not-tested prior probability of an individual being not infected with the disease before being tested is should be equal to 0.90, right? 

### Steps to Reproduce

1. open jasp
2. click learnbayes
3. click binary classification
4. click plots
5. click probability positive
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by EJWagenmakers** [comment]
I'm not sure I understand. You write "the not-tested prior probability of an individual being *not* infected with the disease before being tested is also 0.10 as shown in the bar plot below." But the y-axis has the probability of being positive (= infected).

**Comment by narcilili** [comment]
hello ej,

thanks for replying. you are correct. i think i mistook the not tested negative (turquoise) as
the complement (rareness) to prevalence. the bar plot is correct: the prevalence should be 
the same for both negative and positive conditions before being tested. 
using the default data in JASP, the negative is 0.1 before testing and 0.027 after a negative result.
this is because false negatives (0.02)/false negatives (0.02) + true negatives (0.72) = 0.027. 
this means that the probability of a positive condition given a negative test = 0.027. 
i hope i am right this time. sorry for the false alarm.

cheers
narcilili

**Comment by boutinb** [comment]
@narcilili Can we close this issue?
