### ISSUE TITLE
Testing multicollinearity in logistic regressions

### ISSUE THREAD

**Issue by PerPalmgren** [jasp-stats/jasp-issues#1515]
### Description

It would be very good to test multicollinearity as part of the assumption verifications when running  logistic regressions.

### Describe the solution you would like

This is possible in SPSS and JAMOVI. I have inserted the table generated in JAMOVI. A similar output would really be beneficial in JASP.

### Additional context

![Picture1](https://user-images.githubusercontent.com/79397662/143683778-6c357802-a738-4022-abd9-e0a7deba08ff.png)

**Comment by Kucharssim** [comment]
Can you take a look, @fqixiang?

**Comment by fqixiang** [comment]
I will try to implement this as part of the 0.16.1 release.

**Comment by PerPalmgren** [comment]
@fqixiang happy if this will be implemented in 0.16.1 😜🤩
