### ISSUE TITLE
[Feature Request]: Add Polish language to translations

### ISSUE THREAD

**Issue by WojtekHerisz** [jasp-stats/jasp-issues#1516]
### Description

I would like to contribute with Polish language translation but it is not currently available.

### Describe the solution you would like

Add Polish language to translations

**Comment by EJWagenmakers** [comment]
Dear Wojtek,

We have an efficient system set up on WebLate, so basically you can just start (and possibly involve colleagues as well). See the information on https://jasp-stats.org/translation-guidelines/
I am closing this issue to keep thing tidy. Please email us if anything is unclear.

Cheers,
E.J.

**Comment by boutinb** [comment]
I see that you managed to add the polish language for the jasp-Descriptives-QML component. Did you have another problem?
