### ISSUE TITLE
Fix/prevent/explain the failing homogeneity tests in RM-ANOVA

### ISSUE THREAD

**Issue by JoKeyser** [jasp-stats/jasp-issues#1518]
### JASP Version

0.16

### JASP Module

jaspAnova

### What analysis are you seeing the problem on?

Classical Repeated Measures ANOVA

### What OS are you seeing the problem on?

Ubuntu

### Bug Description

If you check "Homogeneity tests" in repeated measures ANOVA without adding a between subject factor, you get an error message ([defined here](https://github.com/jasp-stats/jaspAnova/blob/7a0ae370ef9e90a09bcf27421fbb5764ad6eb19a/R/anovarepeatedmeasures.R#L724)):

> "Cannot perform homogeneity tests because there are no between subjects factors specified."

![rmanova-error](https://user-images.githubusercontent.com/8722846/143909464-10e1ca23-7a49-497f-bece-3b635a72a4fe.png)

JASP's behaviour leaves me guessing:

- Does the test make sense, but JASP cannot perform it (yet)?
- If the test is non-sensical, then why did it let me check the option?

### Expected Behaviour

- If the test is sensible to perform without between subject factor(s), JASP should state that it is not implemented (yet).
- If the test is non-sensical without between subject factor(s), the user should be informed about that dependency beforehand, e.g. by greying out the option.
  Optimally, there could also be a link to a brief explanation in the help file.

(I should note that I tried to figure out if homogeneity tests are sensible without a between subjects factor, but could not find a clear answer; any hint is very welcome.)

### Steps to Reproduce

1. Open any dataset, e.g. Alcohol Attitudes from 3. ANOVA in Data Library.
2. Select ANOVA -> Classical -> Repeated Measures ANOVA.
3. Check Assumption Checks -> Homogeneity tests (and leave "Between Subject Factors" empty).

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JohnnyDoorn** [comment]
Hi @JoKeyser ,

Thank you for your informative report. The test that is implemented (Levene's test) is used for assesing between subjects variation. One of its assumptions is independent observations between groups, and since the within-subjects observations are dependent, it would not be suitable to use it for assessing equal variances in two repeated measures. I think greying out the option is not very informative, since it does not convey the reason for greying it out. The error message is maybe a little aggressive, but we made it such that it only concerns the assumption table (the rest of the ANOVA results will still be displayed without the error blocking it). 
For assessing the variance in a repeated measures design, Mauchly's test can be used (sphericity, but here you need more than 2 levels).
Adding to the helpfile is very good idea though and I will make an issue for this. 

Kind regards
Johnny

**Comment by JoKeyser** [comment]
@JohnnyDoorn thank you for your quick and detailed answer.
Your reasoning seems sound to me, and thanks for pointing out that Mauchly's test is sufficient if you have >2 levels.

One case/questions remains unclear to me: What if one has repeated factors with just 2 levels; does RM-ANOVA not assume equal variances in that case? The text books I consulted so far are vague about this... if you could, I think many people would appreciate a clarification about this in the help file (well, at least I would :)).

**Comment by JohnnyDoorn** [comment]
When you are dealing with paired samples (also like in the paired t-test) you look at the standard deviations of the differences, so for two groups, you only have 1 standard deviation. Only for more than 2 groups do you have more than 1 standard deviation, and then you use the sphericity test.

**Comment by JoKeyser** [comment]
Thank you; that obviates the test for 1 rm-factor with 2 levels.
Does this reasoning extend to multiple rm-factors, each with 2 levels?
(Sorry in case that's also obvious, it isn't to me, currently.)

**Comment by JohnnyDoorn** [comment]
I think in multiway RM ANOVA, you still only look at each factor separately - I am not sure why though (perhaps this is not an assumption of the model?)

**Comment by JoKeyser** [comment]
I think it would helpful to figure this out with certainty, and if true, include this in the help file. (My confusion is triggered by a 2x2 RM-ANOVA without between factors.)

**Comment by amirmasoudabdol** [comment]
@JohnnyDoorn, if the new PR addresses this, please close the issue.

**Comment by Mattiwinks** [comment]
> Hi @JoKeyser ,
> 
> Thank you for your informative report. The test that is implemented (Levene's test) is used for assesing between subjects variation. One of its assumptions is independent observations between groups, and since the within-subjects observations are dependent, it would not be suitable to use it for assessing equal variances in two repeated measures. I think greying out the option is not very informative, since it does not convey the reason for greying it out. The error message is maybe a little aggressive, but we made it such that it only concerns the assumption table (the rest of the ANOVA results will still be displayed without the error blocking it). For assessing the variance in a repeated measures design, Mauchly's test can be used (sphericity, but here you need more than 2 levels). Adding to the helpfile is very good idea though and I will make an issue for this.
> 
> Kind regards Johnny

Hi I', going through an issue where I can't use the sphericity test because I'm using two levels. What do I do to check for the variance in my ANOVA test?

**Comment by JohnnyDoorn** [comment]
Hi @Mattiwinks ,

For those ANOVA's, you do not have this assumption (e.g., see https://en.wikipedia.org/wiki/Repeated_measures_design).

Kind regards,
Johnny
