### ISSUE TITLE
[Bug]: Not every section is being initialised/computed after opening a file

### ISSUE THREAD

**Issue by rnsoicher** [jasp-stats/jasp-issues#1519]
### JASP Version

0.16

### JASP Module

jaspDescriptives

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I am opening someone else's JASP file. Students are asked to run a series of 7 different descriptive statistics. While the first three appear in the results pane fine, the last four show the title of the section and then "Waiting for initialization of module: Descriptives". I have tried waiting and also restarting the program. It continues to happen. The only way I can get the descriptive statistics where this message is appearing is by moving variables in and out of the variables/split boxes. I've included a screenshot of what I'm seeing. The table you see only came up after I moved some variables around. I have also included a .zip folder containing the .jasp file causing the problem. 
![Initialization error](https://user-images.githubusercontent.com/74789299/143944456-74d61de0-aab5-4e62-b8aa-9139873ddcaa.png)
[Lab2_StudentJ.zip](https://github.com/jasp-stats/jasp-issues/files/7621215/Lab2_StudentJ.zip)
 

### Expected Behaviour

I should see the results of all the different descriptive statistic analyses.

### Steps to Reproduce

I attempted to reproduce this bug with a different student's JASP file, but the problem did not occur. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JorisGoosen** [comment]
Could you try refreshing all?

Either by pressing "Ctrl+R" or selecting the menu in the results (clicking the triangle next to "Results"):
![image](https://user-images.githubusercontent.com/29062713/144018886-0e237abe-2e70-4607-910d-089962f1d698.png)

It looks like it failed loading for the student and then it was baked into the jasp-file perhaps.
