### ISSUE TITLE
Enhancement: Add Shapiro-Wilks test to Descriptives

### ISSUE THREAD

**Issue by lithos** [jasp-stats/jasp-issues#152]
## Normality Tests in Descriptives
 
* Enhancement: Add normality test option to Descriptives
* Purpose:  Display the Shapiro Wilks test for a given continuous variable.

As a preliminary inspection, I encourage our students to run some descriptives and plots (distributions. boxplots, + QQ plots) and to have a look at a normality test to get a feel for it. Including the option in the Descriptive Stats (even though more an inferential measure) would make life easy and not require them to pretend to be doing a one way t-test.

thanks

**Comment by JohnnyDoorn** [comment]
This is now in JASP 0.9.3.
