### ISSUE TITLE
[Bug]: JASP Crashes

### ISSUE THREAD

**Issue by herberthoijtink** [jasp-stats/jasp-issues#1520]
### JASP Version

0.16

### Commit ID

Herbert Hoijtink

### JASP Module

jaspBain

### What analysis are you seeing the problem on?

opening a data set (not the .jasp-file, but the data set) from the bain library. 

### What OS are you seeing the problem on?

Windows 10 enterprise

### Bug Description

Step1: my pc is off and I turn it on. I open JASP, use - open -  data library - bain - click on the data set (that is, not the .jasp file) for the one sample t-test, and JASP crashes. If I first click on the .jasp file, close jasp, and then click on the data set, jasp does not crash.

### Expected Behaviour

JASP should not crash :-))

### Steps to Reproduce

1.  shut down pc
2. restart pc
3.  open JASP
4.  open a bain data set from the JASP library (note: the data set, not the .JASP file)
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @herberthoijtink Could you set logging on (https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/user-guide/logging-howto.md): once you have set the logging on, open the BAIN Sample T-Test Data file, if it crashes again, then send us the log files in GitHub (drag & drop the log files in a new comment of this issue)

**Comment by JorisGoosen** [comment]
If Herbert could do what Bruno describes that would be good because if I try this out on windows I do not get a crash at all.

**Comment by JorisGoosen** [comment]
And, is this on a UU IT-controlled PC?

**Comment by herberthoijtink** [comment]
Dear Joris and Bruno,

Yes this is on a UU IT-controlled PC. The most open version of it.

I will do the log thingy later today and let you know.

All the best,

Herbert

**Comment by herberthoijtink** [comment]
Dear Bruno,

I can’t reproduce the error anymore. Sorry! I will keep the logtofile on in case it happens again. For now you can close the issue. I will try to do that myself right now, if Github allows me.

All the best,

Herbert

**Comment by JorisGoosen** [comment]
Ah good to hear it doesn't happen anymore.

I suspect it might have something to do with the userfolder, I remember from working at the servicedesk of UU that the user-documents come from a network drive. Perhaps JASP was trying to write something to that folder while loading and it went wrong because the system was still connecting or who knows what.

Keeping the logs on is a good idea!
