### ISSUE TITLE
[Bug]: Error in running Generalized Linear Mixed Models

### ISSUE THREAD

**Issue by BubiUnitn** [jasp-stats/jasp-issues#1521]
### JASP Version

0.15

### JASP Module

jaspMixedModels

### What analysis are you seeing the problem on?

Generalized Linear Mixed Models 

### What OS are you seeing the problem on?

mac OS Monterey 12.0.1

### Bug Description

Dear experts,
I was trying to carry out a Logistic regression using GLMM, using as a dependent variable a binary variable, as fixed effects variables I put age and level of education (1-7). All were categorical variables. As I was forced to choice a random effect/grouping effect although It was not of my interest, I put the gender variable, splitting my sample in 2 parts. 

Honestly I don't know if the input is completely correct, but a bug error appeared:
withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)
`withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

MixedModelsGLMM(...)

.mmRunAnalysis(jaspResults, dataset, options, 'GLMM')

.mmFitModel(jaspResults, dataset, options, type)

.mmModelFormula(options, dataset)

table(dataset[, c(tempRe$value, me)])

dataset[, c(tempRe$value, me)]

`[.data.frame`(dataset, , c(tempRe$value, me))

stop('undefined columns selected')`

So I decided to copy and paste it here. 

I hope someone has any suggestion to solve this issue or to perform the analysis in a better way. 
Thank you anyway for your time, 

Kind regards, 
Giulia

### Expected Behaviour

I suppose that the analysis should be computed, showing estimators of the intercepts for each factors included in the model, also showing the interaction among them. 

### Steps to Reproduce

1
2. 
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.
<img width="1057" alt="Schermata 2021-12-01 alle 16 08 29" src="https://user-images.githubusercontent.com/95363606/144260945-e2e4f51d-62fb-46a8-98a4-c83cbab7ec62.png">

**Comment by boutinb** [comment]
@FBartos Can you have a look?

**Comment by FBartos** [comment]
I believe that this was the same issue as in: https://github.com/jasp-stats/jasp-issues/issues/1107 which got fixed with the newer versions (it's working in 16.3),
