### ISSUE TITLE
[Bug]: Configural Invariance Testing Code in Multigroup CFA is not correct

### ISSUE THREAD

**Issue by ChristianKandler** [jasp-stats/jasp-issues#1524]
### JASP Version

0.16

### JASP Module

jaspFactor

### What analysis are you seeing the problem on?

Multigroup CFA

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I identified an error with the "configural" invariance testing. 

### Expected Behaviour

The "metric" and other levels of MI testing are correct. But their seems to be an error in the code for "configural" MI testing. More dfs indicate too many restrictions in the modeling.

### Steps to Reproduce

1. CFA modeling
2. Testing different invariance levels
3. obvious error accurred, because configural MI cannot be based on fewer dfs compared to metric MI level
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @ChristianKandler Could you send us a jasp file (in a zip format, and drag & drop in a comment of this GitHub issue) showing the problem?

**Comment by ChristianKandler** [comment]
[SPeADy1.zip](https://github.com/jasp-stats/jasp-issues/files/7649760/SPeADy1.zip)

See final CFA and multigroup CFA:
Configural : df = 6 --> Must be wrong!!!
Metric : df = 4 --> is correct
Scalar : df = 6 --> is correct
...

Does this help? You can compare with a previous JASP release which correctly worked here. Ther problem only occured with the last release.

Many thanks,
Christian

**Comment by boutinb** [comment]
[SPeADy2.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/7649950/SPeADy2.jasp.zip)
I see that in 0.15 Configural df still gives 6, only in 0.14.1 it gives 2.
@Kucharssim Can you have a look?
