### ISSUE TITLE
[Feature Request]: slow bootstrap

### ISSUE THREAD

**Issue by NikitaKhromov-Borisov** [jasp-stats/jasp-issues#1527]
### Description

BT is very slow

### Describe alternatives that you have considered

For instance fast algorithms from  PAST https://www.nhm.uio.no/english/research/infrastructure/past/

**Comment by amirmasoudabdol** [comment]
Thanks @NikitaKhromov-Borisov! You have brought this up before, and it is already in our radar! 🙂
