### ISSUE TITLE
[Feature Request]: Cyrillic

### ISSUE THREAD

**Issue by NikitaKhromov-Borisov** [jasp-stats/jasp-issues#1528]
### Description

Cyrillic is not recognized

### Describe the solution you would like

recognizing Cyrillic ASAP

**Comment by amirmasoudabdol** [comment]
Hi @NikitaKhromov-Borisov, as I explained [here](https://github.com/jasp-stats/jasp-issues/issues/1525#issuecomment-985602897), we should support Cyrillic and this problem might be caused on your end. You don't need to open a new Feature Request, instead, if you help me understand your side of the problem a bit better, maybe we will be able to help.

I close this feature request, feel free to reply to your original bug filling, here, https://github.com/jasp-stats/jasp-issues/issues/1525#issuecomment-985602897.
