### ISSUE TITLE
JASP Crashing Every Single Time

### ISSUE THREAD

**Issue by chrisaberson** [jasp-stats/jasp-issues#153]
* JASP version: 0.8.6
* OS name and version: Windows 10 Enterprise
* Analysis: All
* Steps to reproduce: Open JASP. Open datafile. Run Analysis. Boom. Unexpected internal error. 

Any file, any analysis. 0.8.5 works fine though.

**Comment by FransMeerhoff** [comment]
Hi @chrisaberson 

Please reopen this issue if this problem still occurs on the latest version.

Kind regards 
Frans Meerhoff
