### ISSUE TITLE
[Feature Request]: Support native locale encoding in SPSS files

### ISSUE THREAD

**Issue by shun2wang** [jasp-stats/jasp-issues#1532]
### Description
Thanks to the development team, I see that JASP's ‘Datamode’ is under development, I tested it once and it’s amazing!
In some cases, data form and plots look abnormal due to data file in Non-Western alphabet，I think that data editor mode provides an opportunity to solve this problem, So convert the character encoding of the data file in data editor to improve the character garbled problem caused by the differences in the local language environment.

### Describe the solution you would like

Provide a button-type drop-down list in data editor mode, provide various encodings for selection, the user can see in the form and plot whether the characters are displayed normally, and then convert it to UTF-8 to save it as a JASP file

### Describe alternatives that you have considered

I have to convert the encoding format in other software such as SPSS/Excel and open it in JASP.

### Additional context

I will provide several data files and screenshots with different encodings in the attachment for your review.
[JASP_Datacode.zip](https://github.com/jasp-stats/jasp-issues/files/7655979/JASP_Datacode.zip)

**Comment by JorisGoosen** [comment]
Hey @icekylin 

Maybe it isn't necessary to do this, what kind of datafiles are you trying to load?
I have been working on making sure that JASP handles different alphabets on windows and there are a few settings that you could try and tweak.

But perhaps it would be good to start of with exactly what you are trying to load and goes wrong.

- Your system is windows and the alphabet/locale is chinese? (Guessing from your name)
- What is your setting of "Handling LC_CTYPE" in "Windows workarounds" in Advanced preferences?
- What is your setting of "Assume CSV is in native if no BOM" in "Windows workarounds" in data preferences?

Thank you for the examples!

**Comment by icekylin** [comment]
Hi @JorisGoosen 

The following are my preference settings in JASP：

- OS:Windows 10  locale is chinese
- "Handling LC_CTYPE" setting is "let JASP guess..."
- "Windows workarounds" setting is Not Selected

I have tried to switch the above options, but it didn’t help.
For example, in the file I attached, you can see the normal display (Figure 1) in SPSS and my SPSS settings (Figure 2), as well as abnormal unopenable (Figure 3), another sample data file (. sav file）
[datacode2.zip](https://github.com/jasp-stats/jasp-issues/files/7660516/datacode2.zip)

**Comment by JorisGoosen** [comment]
Ah yes, the workaround for "no BOM in windows" is only used for csv-files. So if you save it as "csv" in excel, not as UTF-8 or msdos then this workaround makes sure it is read properly.

I was not actually aware that SPSS used locale-dependent encoding in their files... That would require a fix indeed.

**Comment by icekylin** [comment]
Thank you for your work!
In fact, the solution to the garbled problem in SPSS is to switch the locale encoding and then save it as UTF-8, but I don’t know the working principle.

So you think this is a bug fix rather than a new feature requirement?

**Comment by icekylin** [comment]
> Thank you for your work! In fact, the solution to the garbled problem in SPSS is to switch the locale encoding and then save it as UTF-8, but I don’t know the working principle.
> 
> So you think this is a bug fix rather than a new feature requirement?

**Comment by icekylin** [comment]
> So if you save it as "csv" in excel, not as UTF-8 or msdos then this workaround makes sure it is read properly.
The .csv file in the sample file given to you for the first time is actually edited in the notepad software, it can freely switch the locale encoding, it is easy to do this.

**Comment by JorisGoosen** [comment]
> Thank you for your work!

> In fact, the solution to the garbled problem in SPSS is to switch the locale encoding and then save it as UTF-8, but I don’t know the working principle.

That is a solution, but it requires people to be aware of that setting, and that is often not the case.
 
> So you think this is a bug fix rather than a new feature requirement?

Well, it is a bit of both. It would be a new feature to support that but it is also most definitely a bug when you do not see the data in JASP that you entered in SPSS.

The CSV setting should work reasonably for exports from excel. Now one should be added for SPSS perhaps.

What would really help me is if I could have 1 copy of your SPSS file saved as UTF-8 and 1 copy saved in your current locale (China PRC). That would help me implement this.

**Comment by JorisGoosen** [comment]
> > So if you save it as "csv" in excel, not as UTF-8 or msdos then this workaround makes sure it is read properly.
> 
> The .csv file in the sample file given to you for the first time is actually edited in the notepad software, it can freely switch the locale encoding, it is easy to do this.

Yes once you are aware of these settings it isn't that hard to work with. But most users will not be aware that locales or encodin exist and so wouldn't know what to do. This is why the csv-workaround is there. Because a csv made in linux will never have a BOM but always be UTF-8. On windows however it depends on the local system, the users preferences and which options they've selected in whatever program they use.

So we have tried to guess reasonably what would be the case.

One problem with your chinese SPSS file could be that once the file is copied to another computer (set for instance in dutch locale) that it wouldn't be possible to open it properly anymore. Because perhaps it doesn't store which locale was used. (CSV definitely doesn't do this, which is why the workaround was disabled before)

**Comment by icekylin** [comment]
Ok, I will give you a copy of the UTF file saved by SPSS whith the SPSS setting commands. Now this file can be opened perfectly in JASP, I don’t know if this can help.
Thanks!
[datacode-UTF.zip](https://github.com/jasp-stats/jasp-issues/files/7660693/datacode-UTF.zip)

**Comment by JorisGoosen** [comment]
So the one in `datacode-UTF.zip` is the same as the one in `datacode2.zip` but the first is saved in UTF-8 and the second as  chinese-locale?

**Comment by icekylin** [comment]
> So the one in `datacode-UTF.zip` is the same as the one in `datacode2.zip` but the first is saved in UTF-8 and the second as chinese-locale?

Sorry I didn’t provide you with a clear document, here to clarify the following

- 102643862_165_165.sav— saved as chinese-locale
- 102643862_165_165.sav— saved as UFT-8

**Comment by icekylin** [comment]
@JorisGoosen Hi, Joris.I've noticed whether the question about encoding can be significantly improved as new versions of R. that R 4.2 for Windows will support UTF-8 as native encoding, which will be a major improvement in encoding support, allowing Windows R users to work with international text and data.more from [here](https://developer.r-project.org/Blog/public/2021/12/07/upcoming-changes-in-r-4.2-on-windows/)

**Comment by JorisGoosen** [comment]
> @JorisGoosen Hi, Joris.I've noticed whether the question about encoding can be significantly improved as new versions of R. that R 4.2 for Windows will support UTF-8 as native encoding, which will be a major improvement in encoding support, allowing Windows R users to work with international text and data.more from [here](https://developer.r-project.org/Blog/public/2021/12/07/upcoming-changes-in-r-4.2-on-windows/)

Pfoeh, I've been waiting for ages for R to support that!

But we do not use R for reading spss... Once I start work on 0.17 I'll have a look and see if SPSS sotres the actual locale somewhere in the file. Because that would make things easier. If it doesn't then I guess I could make it an option during the opening of a file or something.

**Comment by icekylin** [comment]
NEWS: R version 4.2.0 (Vigorous Calisthenics) [prerelease versions](http://cran.r-project.org/src/base-prerelease) will appear starting Tuesday 2022-03-22. Final release is scheduled for Friday 2022-04-22.NEWS: R version 4.2.0 (Vigorous Calisthenics) prerelease versions will appear starting Tuesday 2022-03-22. Final release is scheduled for Friday 2022-04-22.

**Comment by amirmasoudabdol** [comment]
We are aware of this, and hopefully we can have it tested and deployed for JASP 0.17.0! :-)
