### ISSUE TITLE
[Bug]: can't open the program

### ISSUE THREAD

**Issue by SvetDmFin** [jasp-stats/jasp-issues#1533]
### JASP Version

0.16

### What OS are you seeing the problem on?

Windows

### Bug Description

Unfortunately, I can't install JASP properly. I have tried versions 16, 15, and 14 for Windows, but in the end of the installation process, when I click "Finish" and "Launch JASP", nothing more occurs. I do not see the welcome page or any other signals of the opening. I also tried to press the JASP icon in the Windows menu, but nothing occurred as well. As far as I understood, the installation itself has been done properly (I used Windows C Disk, Program Files) , the problem is with the opening of the programm.

### Expected Behaviour

After the installation JASP should be opened.

### Steps to Reproduce

1. Download JASP for Windows (version 16,15,14)
2. Use msi Downloader
3. Installation is done in Disk C, program files for all users of the computer
4. Button Finish and Launch occured
5. Welcome Page hasn't been opened
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @SvetDmFin Could you try to start JASP from the command prompt. For this,

- Start a command prompt by typing 'command prompt' in the Start menu.
- Type `"c:\Program Files (x86)\JASP\JASP.exe" > log.txt` to start JASP.
- Check whether JASP starts or not.
- Type 'notepad log.txt' to see the log file.
- Send me this log file in a comment of this GitHub issue.

**Comment by SvetDmFin** [comment]
Hi, boutinb!

I have done the command as You have written, but JASP still doesn't work and the notepad log.txt stays that 'notepad' doesnt occur as internal or external command that can be done by the programm or file.

What should I try next?

Thank You!

**Comment by boutinb** [comment]
Do you have a log.txt file? It should be found in the folder displayed when you started the command prompt, something like 'C:\Users\<your username>'. You should see it in the File Explorer. Then send it by dragging & dropping it in a comment of this GitHub issue.

**Comment by juliuspf** [comment]
@SvetDmFin, could you try the latest version of JASP and see if the issue persists?
