### ISSUE TITLE
[Bug]: Newly downloaded JASP 0.16 programme crashes again and again on Macbook Pro. Will not open.

### ISSUE THREAD

**Issue by helpmplease** [jasp-stats/jasp-issues#1534]
### JASP Version

0.16

### What OS are you seeing the problem on?

Catalina 10.15.7

### Bug Description

[New Issue · jasp-stats_jasp-issues.pdf](https://github.com/jasp-stats/jasp-issues/files/7657971/New.Issue.jasp-stats_jasp-issues.pdf
![Screenshot 2021-12-06 at 13 43 35](https://user-images.githubusercontent.com/95602459/144788434-c10a6a29-6c46-4dc7-808e-aa5372239487.png)
)

### Expected Behaviour

The programme should have opened

### Steps to Reproduce

1. Downloaded JASP 0.16
2. followed the instructions on how to open it (cancel verification, etc.)
3. The programme crashed
4. This happened again and again even after removing the app and reloading it
5. The prior versions worked fine
2. 
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by helpmplease** [comment]
I hope you can help. I downloaded this newer version and replaced the prior version. Now I cannot continue what I had been in the middle of working on.

**Comment by boutinb** [comment]
Hi @helpmplease 
Could you start JASP by doing the following:
. Start a Terminal
. Type: /Applications/JASP.app/Contents/MacOS/JASP --safeGraphics
If this still crashes, can you give me the output from the Terminal?

**Comment by helpmplease** [comment]
Thanks Bruno, it worked. You are a genius!

Best wishes,

Scott

**Comment by boutinb** [comment]
Thanks! This problem occurs apparently with some graphic drivers. It's quite annoying... Fortunately this option exists. This option is now set in your profile, so that if you start now JASP directly by clicking its icon, it should also works.
