### ISSUE TITLE
Problem Downloading Jasp

### ISSUE THREAD

**Issue by amal1412** [jasp-stats/jasp-issues#1535]
### Description

problem downloadin Jasp

### Additional context

I’m trying to download the JASP, I can’t to do it!
My computer processor is: 
SNAPDRAGON 8CX, by ARM, 64 bit. 

How I can get it on my computer??? Is there another suitable version for this computer processor???

**Comment by boutinb** [comment]
Hi @amal1412 Are you on Windows? Then you should be able to download the Windows version https://jasp-stats.org/download/

**Comment by amal1412** [comment]
Hi,
Thank you for your answer.
I’m in windows 10, I tried to download the software JASP, and I got: This
installation package is not supported on this type of processor. Contact
the product supplier!
I must to download it!

Thank you 🙏🏻



בתאריך יום ב׳, 6 בדצמ׳ 2021 ב-17:22 מאת bruno boutin <
***@***.***>:

**Comment by boutinb** [comment]
Hi @amal1412 This is quite strange... I have found this page https://www.drivereasy.com/knowledge/fix-this-installation-package-is-not-supported-by-this-processor-type/, maybe it can help.
What you can still do anyway is to download the pre-installed version https://jasp-stats.org/thank-you-for-downloading-jasp-win64-zip/ : it is a zip file you have to unzipped. Afterwards, just start the JASP.exe executable. For the convenience you can make a shortcut on your desktop.

**Comment by carrileroy** [comment]
I am having similar difficulties updating to the new version of JASP. I had version 15 running fine, but when I downloaded the new updated file, it won't run. I tried uninstalling all versions and re-downloading both 16 and the older version of 15.

I get this error message: 
![Capture](https://user-images.githubusercontent.com/37891183/148158319-364145cd-2dae-4805-8f15-118369b52fec.JPG)

I am working on a PC with Windows 10, 64-bit.

**Comment by boutinb** [comment]
Hi @carrileroy Could you open a Command Prompt, and start JASP in this way:
`"C:\Program Files (x86)\JASP\JASP.exe" > log.txt`
This should start JASP and write some logs in log.txt
Can you then send me this log.txt file by dragging & dropping it in a new comment of this issue in GitHub?

**Comment by carrileroy** [comment]
Here is the log.txt file: 

Making new argument list for Application startup: C:\Program Files (x86)\JASP\JASP.exe
Starting JASP 0.16 from commit ef60937d81e5388ed2f27f6047cc1363e9af4611 and branch development
Application initialized
Application init entered
MainWindow constructor started
TempFiles::createSessionDir(): 'C:/Users/leroyc/AppData/Local/JASP/temp/3820' about to be (removed and re)created.
Going to construct the necessary models for JASP to function.
Desktop:	Checking qm file: C:/Program Files (x86)/JASP/Resources/Translations/jaspDesktop-de.qm
Desktop:	Language (42) not registered in LanguageModel, adding it now
Desktop:	Checking qm file: C:/Program Files (x86)/JASP/Resources/Translations/jaspDesktop-eo.qm
Desktop:	Language 32 (eo) is not allowedDesktop:	Checking qm file: C:/Program Files (x86)/JASP/Resources/Translations/jaspDesktop-es.qm
Desktop:	Language (111) not registered in LanguageModel, adding it now
Desktop:	Checking qm file: C:/Program Files (x86)/JASP/Resources/Translations/jaspDesktop-gl.qm
Desktop:	Language (40) not registered in LanguageModel, adding it now
Desktop:	Checking qm file: C:/Program Files (x86)/JASP/Resources/Translations/jaspDesktop-id.qm
Desktop:	Language (52) not registered in LanguageModel, adding it now
Desktop:	Checking qm file: C:/Program Files (x86)/JASP/Resources/Translations/jaspDesktop-ja.qm
Desktop:	Language (59) not registered in LanguageModel, adding it now
Desktop:	Checking qm file: C:/Program Files (x86)/JASP/Resources/Translations/jaspDesktop-nl.qm
Desktop:	Language (30) not registered in LanguageModel, adding it now
Desktop:	Checking qm file: C:/Program Files (x86)/JASP/Resources/Translations/jaspDesktop-pt.qm
Desktop:	Language (91) not registered in LanguageModel, adding it now
Desktop:	Checking qm file: C:/Program Files (x86)/JASP/Resources/Translations/jaspDesktop-tr.qm
Desktop:	Language 125 (tr) is not allowedDesktop:	Checking qm file: C:/Program Files (x86)/JASP/Resources/Translations/jaspDesktop-zh_Hans.qm
Desktop:	Language (25) not registered in LanguageModel, adding it now
QtWebEngine initialized
Entering eventloop

[log.txt](https://github.com/jasp-stats/jasp-issues/files/7834219/log.txt)

**Comment by boutinb** [comment]
Hmm, that does not help much...
Could you start JASP with the safeGraphics option? For this type in a command prompt:
`"C:\Program Files (x86)\JASP\JASP.exe" --safeGraphics`

**Comment by carrileroy** [comment]
That works! So, what does that mean? Should I use the command prompt and "safeGraphics" mode to open it from now on? Will that affect any functionality? Thank you so much for working through this with me!

**Comment by boutinb** [comment]
What fine! The platform we use to render our software (Qt) has sometimes some problems with (old) graphic card. The setting safeGraphic takes care of this situation. When you start JASP from the command prompt with this setting, it sets this setting in its preferences, and the next time you start JASP, it should use automatically this setting. You should be able now to start JASP directly (by clicking its icon, or from the start menu), and you should see in the Menu Preferences/Interface the checkbox 'Safe graphic mode' checked.
