### ISSUE TITLE
[Feature Request]: "locking" filters

### ISSUE THREAD

**Issue by kevinvschie** [jasp-stats/jasp-issues#1536]
### Description

Sometimes you want to analyse part of your data (e.g., as a follow-up). To do that you can apply filters and for example select one of two groups to further analyse variable A. However, for variable B you want to include both groups again, so you need to remove the filter. The issue is that this resets the applied filter for variable A. Is there a way to lock the filters for given analyses?

### Purpose

Keep the output file (i.e., the stats) clean.

### Is your feature request related to a problem?

see above

### Describe the solution you would like

It would be great if filters could somehow be locked or linked to specific analyses.

**Comment by JoKeyser** [comment]
@kevinvschie , others have the same request, and it's already tracked in issue #385.
