### ISSUE TITLE
[Bug]: F test for R² change in linear regression using wrong df for categorical variables

### ISSUE THREAD

**Issue by drpetersen** [jasp-stats/jasp-issues#1537]
### JASP Version

0.16

### JASP Module

jaspRegression

### What analysis are you seeing the problem on?

Classical Linear Regression

### What OS are you seeing the problem on?

Linux (Debian bullseye)

### Bug Description

When a categorical variable with k > 2 levels is added as a Factor to a classical linear regression model, the F test checking for significance of the effect of that categorical variable should use df1 = k-1 degrees of freedom (in the numerator). This correctly happens in the ANOVA table of the linear regression output, but the „F Change“ test for R² Change (which is required when the categorical variable is not the only predictor) uses df1 = 1 instead, as shown in the screenshot below:

![Screenshot_20211208_172402](https://user-images.githubusercontent.com/9879249/145244924-8074dd6d-f583-4956-b152-b7cc2ca0b1b9.png)

I have put together a small sample data set which shows the problem. In comparison, manual dummy coding of the categorical variable always yields the correct number of df1. I suspect that this might be a problem with the code for the R² Change F test. (Or else, a fundamental misunderstanding on my part.)

Thank you for looking into this, and also for your great software!

### Expected Behaviour

df1 should be k-1 for a categorical variable with k levels in the R² Change F test.

### Steps to Reproduce

1. Open the attached JASP file
2. Compare R² Change for the linear regression with automatic and that with manual dummy coding of categorical variable `categ`.

[example.zip](https://github.com/jasp-stats/jasp-issues/files/7677458/example.zip)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
@Kucharssim Can you have a look at this issue?

**Comment by Kucharssim** [comment]
Dear @drpetersen,

thank you very much for reporting this issue and for making a clear and reproducible example. Indeed this was a bug in the summary table which computed the df incorrectly when categorical predictors were used. I just created a fix to this issue so I expect it to be resolved in the next JASP release.

Once we merge my fixes to the analysis, we will close this issue. Please feel free to reopen it in case the problem occurs in the future again.
