### ISSUE TITLE
Enhancement: Provide odds ratios for contingency tables (as well as log odds)

### ISSUE THREAD

**Issue by charlesmalpas** [jasp-stats/jasp-issues#154]
## Template for enhancement requests
 
* Enhancement: Provide odds ratios for contingency tables (as well as log odds)
* Purpose: The contingency table module provides log odds ratios, but not odds ratios. It would be very useful to have both options (with 95% confidence intervals), especially for teaching purposes.

**Comment by charlesmalpas** [comment]
Hi Team,

I know this is probably low priority, but I am trying to switch to JASP for my teaching. This would really helpful with teaching biostats to medical students, who have a preference for odds on the original scale.

Many thanks!

Charles

**Comment by tomtomme** [comment]
@charlesmalpas 
odds ratios are in.
Feel free to close this issue.
