### ISSUE TITLE
[Feature Request]: Different effects and their error estimates for Meta-analysis

### ISSUE THREAD

**Issue by Trebicky** [jasp-stats/jasp-issues#1540]
### Description

Letting users choose which effects are entered and avoid SEs

### Purpose

Increased usability and understanding of meta-analysis and variables to input.

### Use-case

One might want top run meta-analysis on correlation coeficientes from available literature with SEs not available (from mean differecnes when only samples sizes, means and SD.)

### Is your feature request related to a problem?

Commonly the available literature (and common statistical tools) does not report SEs for effects and some time not even the effects of interest. Making the meta-analysis moduilke more flexible in what data to imput would increase its usability and remove hurdles.

### Describe the solution you would like

Add an option to choose whether to run meta-analysis on correlations, mean differences, etc.  Let user input commonly available data into labeled fields (e.g. Effect size in Pearson's r; Sample size; Mean for group A, sample size for group A, SD for group A...))

### Describe alternatives that you have considered

Fill in the JASP help page - even the hyperlink does not go anywehre. Provide a way to calculate SEs from commonly available data like effect size and sample size)

### Additional context

The current meta-analysis tool is nice and all, but it is a bit generic to suit all possible purposes with only one dialogue and relies on SEs to be entered. But we usually don't have them, and we need to calculate them externally. If the dialogue were more inclusive for other possibilities of available data (like N, SDs), it would be much easier to use. Maybe get inspired by how jamovi does that?

Could JASP possibly have more options in the drop-down menu of the meta-analysis module like Classical meta-analysis of the strength of associations and Classical meta-analysis of mean differences?

By the way, having an option to choose additional info about individual studies (like sample size, sex, population, dose entered as another columns in dataset) and having it plotted in the forest plot as another column next to the Study label would be sweet and highly informative for the forest plot readers.

**Comment by boutinb** [comment]
@sophieberkhout What do you think of this request?

**Comment by sophieberkhout** [comment]
Hi @Trebicky,

I am happy to let you know that this is already in development! We are working on more support for various outcomes and effect sizes and we are also implementing functionality to calculate outcomes or effect sizes within JASP from data or data summaries.

As for the forest plot, I agree that it would be nice to be able to add more information to the forest plot but this can be a little more difficult to implement. I suggest making a separate issue for this feature request.

Best,
Sophie

**Comment by Trebicky** [comment]
Hi,
That is delightful news, and I am looking forward to a news release. When can we expect one?
I am glad to hear JASP will be more internally connected when it comes to further data processing, from analysis to analysis.
I see bigger struggles in entering data from already published literature, but I am sure the JASP team will provide a quality solution.

OK, I'll open a new Issue for forest plot enhancements.


And what about some power/sensitivity estimates in the Meta-analysis module, like suggested in https://osf.io/5c7uz/.

Meta-analyses are nice and all, but still many seem underpowered, which is an important part of the meta-analysis results. Usually, we gather all 'available' evidence on a given effect. Results show a small meta-analytic effect, but the important message is that the effect is small and that the number of studies so far is too small even to detect it reasonably.

**Comment by tomtomme** [comment]
@sophieberkhout 
any updates on this one?

**Comment by tomtomme** [comment]
@Trebicky 
I just saw https://github.com/jasp-stats/jasp-issues/issues/1361
This is essentially the same issue. We could close this one and track them together. 
Do you agree?
