### ISSUE TITLE
[Feature Request]: Meta-analysis forest plots contain more study descriptors

### ISSUE THREAD

**Issue by Trebicky** [jasp-stats/jasp-issues#1542]
### Description

Let user select what additional columns  to show next to the study label in the forest plot

### Purpose

Let readers gain more info about individual studies in the meta-analysis results

### Use-case

I want to show which studies were publsihed and which were not. Or show what dose was used or waht sex were the raters

### Is your feature request related to a problem?

One problem in meta-analyses is how to interpret heterogeneity. One option is methodological or sample related variables (categorical) that can be reviewed while reading the plot

### Describe the solution you would like

Let user choose additional columuns to show next the study lable (and not to write all in study lable column)

**Comment by FBartos** [comment]
I will do a larger revamp of the meta-analysis module this year and keep this in mind
