### ISSUE TITLE
[Bug]: DataMode-Label displayed in the cell should not be discarded

### ISSUE THREAD

**Issue by icekylin** [jasp-stats/jasp-issues#1544]
### JASP Version

0.16 (Nightly)

### Commit ID

9be136546e4d7c781cc189aa4fd6468b8993143b

### What OS are you seeing the problem on?

Windows 10

### Bug Description

Thanks to the development team, I was pleasantly to see that the data editor mode in Nightly Build and I tested it  for a while (maybe I can continue testing next).

Issue description:In a data set with labels (for example, 1=yes, 0=no), when I double-click a cell try to change the number code (not the label character), I find that the edit is actually the label character. When I delete a character in the cell, that all the label will be discarded.

I will attach a sample file for you to test this operation.
[datawithlable.zip](https://github.com/jasp-stats/jasp-issues/files/7698113/datawithlable.zip)

### Expected Behaviour

After double-clicking the cell, what should be edited is the variable level and its code.
The variable label should only be editable when you click on the variable name at the top.
Or a design similar to SPSS, you can provide a drop-down list for users to choose when editing such variables (as shown in the figure)
![snapshot_2021-12-12_12-45-21](https://user-images.githubusercontent.com/10348402/145700667-7b9f946d-b606-46bb-b0a4-d16bbbb05883.png)

### Steps to Reproduce

1. Double-click the cell with the variable label
2. Remove some label characters
3. enter（In addition, I think that after entering the carriage return in the cell, the cursor should be automoved to the next line according to the usual data editor habits instead of disappearing.)
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by amirmasoudabdol** [comment]
Hi @icekylin, thanks for opening the issue. I will take a note of it.

P.S. We are still fine-tuning the data mode and it will not be out for some times. The nightly that you have downloaded was a special version and other nightlies will not include the data mode until we are close to releasing it for everyone.

**Comment by icekylin** [comment]
Ok，Thanks @amirmasoudabdol 
Maybe I can close it or you can reopen it when you need tracking it continue.
