### ISSUE TITLE
[Feature Request]: Cohen d for contrasts in linear mixed models

### ISSUE THREAD

**Issue by csamuel11** [jasp-stats/jasp-issues#1545]
### Description

I am working with classical linear mixed models. When I specify contrasts in the "Estimated marginal means" section, the resulting table gives the following values: Estimate, SE, df, z, p. However, I would also like to have Cohen's d and Hedges g (unbiased alternative to Cohen's d).

### Purpose

Cohen's d and Hedges g would help me determine the effect size of the contrast that I specify.

### Use-case

As mentioned above, I would use this feature when calculating contrasts between estimated marginal means in classical linear mixed models.

### Is your feature request related to a problem?

No, this feature request is not related to a problem.

### Describe the solution you would like

Not applicable.

### Describe alternatives that you have considered

I think R squared is a potential alternative, although I would prefer Cohen's d and Hedges g.

### Additional context

I think that within the lme4 package, the JASP team could use the `lme.dscore()` function to calculate the Cohen's d value. Here is a link to the [relevant R documentation](https://www.rdocumentation.org/packages/EMAtools/versions/0.1.3/topics/lme.dscore).

**Comment by csamuel11** [comment]
I came across a [post](https://afex.singmann.science/forums/topic/compute-effect-sizes-for-mixed-objects) on the afex (analysis of factorial experiments) R package website. It discusses how computing standardized effect sizes, like Cohen's d, is hard for linear mixed models. The post is about 3.5 years old, so maybe someone has figured it out by now. However, I understand if JASP can no longer add this feature.

**Comment by boutinb** [comment]
@FBartos Could you answer this question?

**Comment by rennoamanda** [comment]
anyone? how to get Cohen d for contrasts in linear mixed models?

**Comment by EJWagenmakers** [comment]
I think it would make sense to add effect size here!
For instance see https://easystats.github.io/effectsize/articles/from_test_statistics.html

**Comment by rennoamanda** [comment]
Thank you so much EJWagenmakers!!!this was very helpfull!

**Comment by boutinb** [comment]
I think we can close this issue? If not re-open it.
