### ISSUE TITLE
[Bug]: JASP slow on 0.16 - 2 minutes to process every action

### ISSUE THREAD

**Issue by CortezPA** [jasp-stats/jasp-issues#1546]
### JASP Version

0.16

### JASP Module

jaspDescriptives, jaspAnova, jaspFactor, jaspFrequencies, jaspRegression, jaspTTests, jaspMixedModels, jaspAudit, jaspBain, jaspNetwork, jaspSem, jaspMachineLearning, jaspSummaryStatistics, jaspMetaAnalysis, jaspDistributions, jaspEquivalenceTTests, jaspJags, jaspReliability, jaspVisualModeling

### What OS are you seeing the problem on?

Windows 11 Pro Version 21H2, Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz   3.70 GHz, 32,0 GB

### Bug Description

Version 0.16 makes JASP impossible to use (very slow)

### Expected Behaviour

JASP does not work properly. It takes ages to open files. Every time I click for any analysis menu it is very slow. It takes like 2 minutes to pop up a menu, no matter which one. It worked properly on the old version.

### Steps to Reproduce

1. Install version 0.16
2. Try to open any file or choose any analysis
3. JASP will be slow and you won't be able to do anything, except if you wait 2 minutes every time you click on analysis, scrolls, output, etc
4. I already uninstalled and installed and it stills slow
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by amirmasoudabdol** [comment]
Thanks for reporting this! We have seen variation of this issue and it is really baffling to us. A few questions: 

- You mentioned that it was not like this on older versions of JASP, by that, do you mean 0.14 or 0.15? 
- If you have recently upgraded to Windows 11, have you experienced this on Windows 10 as well? and on which JASP version?

**Comment by CortezPA** [comment]
**You mentioned that it was not like this on older versions of JASP, by that, do you mean 0.14 or 0.15?**
It works fine till 0.14.1. Right now I am using 0.14.1. 0.15 become slower and 0.16 is impossible to use.

**If you have recently upgraded to Windows 11, have you experienced this on Windows 10 as well? and on which JASP version?**
I did not experience it on Windows 10, but I used 0.14.1 on Windows 10.

**Comment by boutinb** [comment]
@JorisGoosen You made a (beta) version with Qt6.2 that seemed to solve this problem, do you have it somewhere?

**Comment by CortezPA** [comment]
**> @JorisGoosen You made a (beta) version with Qt6.2 that seemed to solve this problem, do you have it somewhere?**

I could install and test it. If you want to check any technical log on my machine or remote control to test it, just let me know. Thanks in advance.

**Comment by JorisGoosen** [comment]
https://static.jasp-stats.org/JASP-Qt6-Testing-2.zip

**Comment by CortezPA** [comment]
**> https://static.jasp-stats.org/JASP-Qt6-Testing-2.zip**

It works smooth. Thanks.

**Comment by boutinb** [comment]
This problem occurs apparently only with particular computers, and is solved with the newest version of the framework with use (Qt 6.2). Hopefully our next release (probably in februari) will use this Qt version.
