### ISSUE TITLE
[Bug]: Can't create model plot for Confirmatory Factor Analysis

### ISSUE THREAD

**Issue by ofthetower** [jasp-stats/jasp-issues#1548]
### JASP Version

0.16

### JASP Module

jaspFactor

### What analysis are you seeing the problem on?

Confirmatory Factor Analysis

### What OS are you seeing the problem on?

macOS Big Sur 11.6

### Bug Description

Not sure if this is a bug or I'm just doing something wrong, but I'm doing CFA on a construct and when I tried asking for the model plot, this is the error message that shows up:

Error in bars[[node]] <- pnorm(GroupThresh$est[GroupThresh$lhs = GroupVars$name[node]]): attempt to select more than one element in integerOneIndex

This is the dataset I'm working on: [Coursework 2.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/7712687/Coursework.2.jasp.zip)

And this this is what the error looks like: <img width="1351" alt="Screen Shot 2021-12-14 at 11 17 56 PM" src="https://user-images.githubusercontent.com/96130949/146026380-1ed72b22-9801-41fd-9d51-70b01ef79b69.png">

### Expected Behaviour

The model plot for the data should show up

### Steps to Reproduce

1. select "model plot" under Plots for CFA
2. 
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by Kucharssim** [comment]
Dear @ofthetower,

thank you for reporting this issue. There is a bug with plotting the model when ordinal variables are included.

I just created a fix for this problem, so I expect this bug to be gone in the next release. Once we merge this fix to the analysis repository, we will close this issue. Please feel free to reopen it in case you encounter it again in the future.
