### ISSUE TITLE
Enhancement: Generalized Linear Mixed Models

### ISSUE THREAD

**Issue by kornbrot** [jasp-stats/jasp-issues#155]
* Enhancement: Generalized Linear Mixed Models, GLMM
* Purpose: Enable repeated measures for proportions (binomial), counts (Poisson). Include Bayes Information Criteria, BIC. Same facilities as SPSS Mixed.
Know its a tough ask, BUT
we have submitted Mss that show

1.  ANOVA and GLMM give different answers for both inferential and descriptive stats
2. BIC reliable discriminates among link functiions

**Comment by tomtomme** [comment]
@kornbrot
Is the current implentation of our GLMM module sufficient?
If so, feel free to close this issue.

**Comment by tomtomme** [comment]
related: https://github.com/jasp-stats/jasp-issues/issues/845

**Comment by tomtomme** [comment]
@kornbrot 
I have reviewed the current GLMM implementation in JASP and all your suggestions are included.
Please reopen, if you disagree!
