### ISSUE TITLE
[Bug]: Can't open JASP 0.16 on PopOS! or Ubuntu 

### ISSUE THREAD

**Issue by KalcMatej99** [jasp-stats/jasp-issues#1551]
### JASP Version

0.16

### What OS are you seeing the problem on?

PopOS! 20 20.04 LTS

### Bug Description

The app doesn't open if i click on the icon or if i try to lauch it from the terminal.
![1](https://user-images.githubusercontent.com/47791945/146240103-e98a0a29-83b4-4305-aaa4-c1339004542e.png)

### Expected Behaviour

The application should open and work

### Steps to Reproduce

1. Insert in the terminal "flatpak run -v org.jaspstats.JASP"
2. Press enter

### Log (if any)

```bash
matejkalc@pop-os:~$ flatpak run -v org.jaspstats.JASP
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/matejkalc/.local/share/flatpak
F: Opening user flatpak installation at path /home/matejkalc/.local/share/flatpak
F: Opening user flatpak installation at path /home/matejkalc/.local/share/flatpak
F: Cleaning up unused container id 3879495216
F: Allocated instance id 2955481475
F: Add defaults in dir /org/jaspstats/JASP/
F: Add locks in dir /org/jaspstats/JASP/
F: Allowing dri access
F: Allowing homedir access
F: Allowing wayland access
F: Allowing x11 access
F: Running 'bwrap --args 39 xdg-dbus-proxy --args=41'
F: Running 'bwrap --args 39 org.jaspstats.JASP'
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
```

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
@JorisGoosen is on holidays, but maybe @vandenman or @amirmasoudabdol know about this problem?

**Comment by JorisGoosen** [comment]
Hey @KalcMatej99 Im back from vacation

It seems that whatever locale your computer is set at isn't supported by flatpak or some other component we rely on.

I think @JohnnyDoorn might've had the same once with some mix between dutch and english locale.

@KalcMatej99 could you run `locale` in a terminal and post the output here?

**Comment by KalcMatej99** [comment]
Hi, hereis the output:
matejkalc@pop-os:~$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=it_IT.UTF-8
LC_TIME=it_IT.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=it_IT.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=it_IT.UTF-8
LC_NAME=it_IT.UTF-8
LC_ADDRESS=it_IT.UTF-8
LC_TELEPHONE=it_IT.UTF-8
LC_MEASUREMENT=it_IT.UTF-8
LC_IDENTIFICATION=it_IT.UTF-8
LC_ALL=

**Comment by JorisGoosen** [comment]
@KalcMatej99 Ah I forgot about this issue for a bit, sorry.

But I see that some of your `LC_*` are `"en_US.UTF-8"` while the other are without quotes `it_IT.UTF-8`

Maybe this is what is going wrong? 
Could you show me the  contents of `/etc/default/locale` ?

**Comment by JorisGoosen** [comment]
@TheBlueQuasar happy to have been of help ^^

Hopefully @KalcMatej99 as well, but seeing as how it works for one user it might be good for the other too so I'll close this issue now. If it doesnt help @KalcMatej99 is of course free to reopen and we'll dig deeper.
