### ISSUE TITLE
[Feature Request]: Maybe an addition for https://jasp-stats.org/features/

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#1552]
### Description

SPSS vs JASP feature comparison

### Purpose

To help my colleagues decide if / when to switch

### Use-case

"Depressions" from SPSS

### Is your feature request related to a problem?

There is not yet a feature comparison like this on the web

### Describe the solution you would like

See link to table below

### Describe alternatives that you have considered

Ignoring the competition

### Additional context

Please review and add missings here: 
https://docs.google.com/spreadsheets/d/13EFGc___U7MwTcV4JJjQ542_Joor4o2HNkCsTHLXd7w/edit#gid=0
I did the research mostly via the IBM SPSS Documentation.

**Comment by icekylin** [comment]
Good idea，I add 'Mutiple Response' Function here:
<html>
<body>


Function | JASP | SPSS
-- | -- | --
Multiple Response | × | √


</body>
</html>

**Comment by boutinb** [comment]
@tomtomme Thank you really much for this overview! Maybe can @AlexanderLyNL and @EJWagenmakers have a look to complete it?

**Comment by EJWagenmakers** [comment]
This is a great list! Including @JohnnyDoorn here as well.

**Comment by JohnnyDoorn** [comment]
@tomtomme That looks great already! We had a blogpost at some point that set out a comparison, although a table on our website that lists each feature would be awesome.
In the meantime you could send your colleagues the [blogpost](https://jasp-stats.org/2017/11/01/jasp-vs-spss/) (it's from 2017, so we have many more features since then!)

**Comment by tomtomme** [comment]
@JohnnyDoorn - there is a table on your website already: https://jasp-stats.org/features/
See the title of this issue. You just have to update it! :dancers: 
The blogpost is really old at this point. Many points are not valid anymore. Maybe I write an updated blogpost, when 0.17 is out the door. But the table should go online before, if everybody here thinks its great :D

**Comment by tomtomme** [comment]
Anything i can do at thus point?

**Comment by tomtomme** [comment]
I am fine if you just do not want to add the SPSS comparison. It might backfire somehow. Just close this issue then.

Independent of this:
The features-page was updated with the "quality-control module" but the new "Generalized Linear Model" from the Regression module is missing. Also "Linear Mixed Model" is missing while "Generalized Linear Mixed Model" is there.

**Comment by boutinb** [comment]
> The features-page was updated with the "quality-control module" but the new "Generalized Linear Model" from the Regression module is missing. Also "Linear Mixed Model" is missing while "Generalized Linear Mixed Model" is there.

@DanaJohanna Could you have a look?

**Comment by tomtomme** [comment]
Since still nobody said or indicated "we do not want this on our page", I will try again :D
And not without some effort.
I updated my SPSSvsJASP feature comparison to the new style on https://jasp-stats.org/features

See
https://docs.google.com/spreadsheets/d/13EFGc___U7MwTcV4JJjQ542_Joor4o2HNkCsTHLXd7w/edit#gid=0

I also emptied cells, where I think that a Bayesion or Classical version may not even possible be possible - like Bayesian Descriptives. Because a minus sign might misleadingly suggest that JASP is missing out on something here.

**Comment by EJWagenmakers** [comment]
I like it. We could make this available on our materials page. I do think the document ought to focus squarely on SPSS, so the remarks concerning our former employees who started jamovi should go, imo.

**Comment by tomtomme** [comment]
I deleted the jamovi-parts just now. I do not need those anymore. 
So feel free to link the document on materials.

My original idea was to only extend https://jasp-stats.org/features with 2 SPSS columns, but if you think the rest of the doc is worth linking, all the better.

If you decide to link the whole doc, I would also translate the remaining parts.

**Comment by boutinb** [comment]
Hi @tomtomme Thank you really much for your work. We would like to add a link to your spreadsheet (with your credits) from our Features web page, but would it possible to have a document with only the comparisons of the analyses supported between JASP & SPSS?

**Comment by tomtomme** [comment]
Absolutely. Will make one sometime this week.

Cheers

**Comment by tomtomme** [comment]
The link to the new document containing only the table:
https://docs.google.com/spreadsheets/d/1lQ7Pt8vFfSrHxQ9Kh3rjY6Ttx2Yx5b1sVKEGLYU9v4Y/edit?usp=sharing

**Comment by boutinb** [comment]
@DanaJohanna Can you add this to the Web site?

**Comment by boutinb** [comment]
Thanks @tomtomme !

**Comment by DanaJohanna** [comment]
Thank you for doing this @tomtomme!
My only request is to add a sentence into the document with: This table is made and maintained by Thomas Langekamp.
The [Features page](https://jasp-stats.org/features/) has been updated already. Let me know if anything should change.

Also, we could make this a page/ blogpost within JASP and link to that rather than the google sheet. It is then important that it is maintained properly. @tomtomme, would you be okay with notifying me everytime you change something? @EJWagenmakers, what do you think?

**Comment by tomtomme** [comment]
@DanaJohanna: The Sentence is added.
However I do not see any SPSS-additions or a link to my spreadsheet on https://jasp-stats.org/features - if you meant that?

I can update my spreadsheet everytime a new JASP version is released and notify you here. From my point of view, you are free to do whatever you want with the info in the spreadsheet. It could also be maintained by someone else

**Comment by juliuspf** [comment]
![Screenshot 2022-11-25 at 14 19 44](https://user-images.githubusercontent.com/38500953/203994374-135bf5cc-10d7-40cf-963d-ddcbe983b205.png)
Also, the name is Langkamp, right?

**Comment by DanaJohanna** [comment]
@juliuspf thank you! I changed the name.

**Comment by Ghassan-Okour** [comment]
@juliuspf Excuse me; what is the meaning of [dataModeSkf14nov] in [JASP Nightlies]???

**Comment by EJWagenmakers** [comment]
I like the way the file is currently referenced on the site.

**Comment by EJWagenmakers** [comment]
@Ghassan-Okour : this is a nightly we produced for SKF, a company we are working with.

**Comment by Ghassan-Okour** [comment]
> @Ghassan-Okour : this is a nightly we produced for SKF, a company we are working with.

THANKFUL...

**Comment by tomtomme** [comment]
I updated the comparison for JASP 0.17. Mainly I added Acceptance Sampling and some details to Meta-Analysis

**Comment by tomtomme** [comment]
@DanaJohanna 
I updated my feature overview to 0.17.2 which now includes power analysis. This is missing on https://jasp-stats.org/features/

**Comment by boutinb** [comment]
@CGuazzoneJASP  Can you update the page?

**Comment by CGuazzoneJASP** [comment]
Page has been updated a couple weeks ago.

**Comment by tomtomme** [comment]
@CGuazzoneJASP 
I updated my chart again to reflect 0.18.2 beta.
 https://jasp-stats.org/features/ needs those updates too.

**Comment by EJWagenmakers** [comment]
Right now I am in charge of the website update. I'll do this soon. So  you are referring to the inclusion of Process models and survival models, right?

**Comment by tomtomme** [comment]
correct :)
________________________________________
Von: EJ ***@***.***>
Gesendet: Dienstag, 2. Januar 2024 14:17:57
An: jasp-stats/jasp-issues
Cc: Thomas Langkamp MSH Hamburg; State change
Betreff: Re: [jasp-stats/jasp-issues] [Feature Request]: SPSS vs JASP addition for https://jasp-stats.org/features/ (Issue #1552)

Right now I am in charge of the website update. I'll do this soon. So you are referring to the inclusion of Process models and survival models, right?

**Comment by tomtomme** [comment]
I updated my features page for 0.19.
Also added some rows for data editing features and a row for multivariate models (MANCOVA, CCA, MMR).

Also an external contributor might add 2 more columns to compare to STATA (wip)

**Comment by tomtomme** [comment]
updated for 0.19.2
