### ISSUE TITLE
[Bug]: Bootnet crashed in JaspNetwork

### ISSUE THREAD

**Issue by JBatHome** [jasp-stats/jasp-issues#1553]
### JASP Version

0.16

### JASP Module

jaspNetwork

### What analysis are you seeing the problem on?

"Thresholds" in Analysis Option with Partial Correlation Estimator

### What OS are you seeing the problem on?

Windows 10

### Bug Description

When you click on Method in "Thresholds", you have this message : "bootnet crashed with the following error message: argume
<img width="960" alt="Image of Bug" src="https://user-images.githubusercontent.com/96084370/146421509-f3c9916b-19b3-4d83-a5cd-d198092081fc.png">
nts is of length zero" 

### Expected Behaviour

Give information about significance of partial correlations and suppress edge in network (?).

### Steps to Reproduce

1. Click on Partial Correlation in Estimator
2. Click on Analysis Option - Partial Correlation
3. Click on Method below Threshold
4. The bug appears
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @vandenman I can reproduce this crash by using the debug data file: just set any 3 dependent variables, Estimator to Partial Correlation and Threshold to Method.

**Comment by JBatHome** [comment]
Hi @vandenman , do you have time to fix this crash? I'm looking forward to using this possibility offered by JASP. Thank you!

**Comment by vandenman** [comment]
@JBatHome it's on my radar! Unfortunately, I have a lot on my plate right now so it may take a little longer.
