### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Gonmar22** [jasp-stats/jasp-issues#1554]
### JASP Version

0.16

### JASP Module

jaspDescriptives, jaspFactor, jaspFrequencies

### What analysis are you seeing the problem on?

Not able to perform any analysis.

### What OS are you seeing the problem on?

Windows 10

### Bug Description

Not able to perform any analysis. A message appears when i add an item. "The engine crashed while trying to run this analysis".

### Expected Behaviour

The Results should have appeared on the right.

![Capture](https://user-images.githubusercontent.com/96257811/146422509-b2d90304-e5a5-4333-8a9f-dcb6eaa9b4ac.JPG)

### Steps to Reproduce

1. 
2. 
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @Gonmar22 I cannot reproduce this problem. Does this problem occur with other data file? Could you send us you csv file that causes this error?

**Comment by Gonmar22** [comment]
Yes it occurs with other data files. Of course, i'll attach to this comment. Thank you
[Dados_PASSAGEM_SPSS.csv](https://github.com/jasp-stats/jasp-issues/files/7746645/Dados_PASSAGEM_SPSS.csv)
.

**Comment by boutinb** [comment]
Hi @Gonmar22 I see that your file has not a UTF-8 encoding. Could you save them with this option: with Excel for example you can choose with the 'Save as' menu the "CSV UTF-8 (comma delimited) (*. csv)" option.
Can you then load the UTF-8 csv file into JASP, and starts again the CFA analysis?

**Comment by Gonmar22** [comment]
Thank you very much. Now it works!

**Comment by boutinb** [comment]
Nice!
