### ISSUE TITLE
[Bug]: Error during Installation via flatpak

### ISSUE THREAD

**Issue by hussain-beig** [jasp-stats/jasp-issues#1556]
### JASP Version

0.16

### What OS are you seeing the problem on?

Linux (Xubuntu 20.04 LTS)

### Bug Description

Hi,
I was trying to install JASP 0.16 via flatpak as described [here](https://jasp-stats.org/linux-installation-guide/) but when I enter the second command while downloading org.jaspstats.JASP I get the following error:
Error: While pulling app/org.jaspstats.JASP/x86_64/stable from remote flathub: Invalid compression type '60'

I'm not sure if this has something to do with this but I also get this note when I use flatpak:
Note that the directories 
'/var/lib/flatpak/exports/share'
'/home/hussain/.local/share/flatpak/exports/share'
are not in the search path set by the XDG_DATA_DIRS environment
variable, so applications installed by Flatpak may not appear on
your desktop until the session is restarted.

Please help me fix this.

![Screenshot_2021-12-20_16-17-55](https://user-images.githubusercontent.com/85665276/146755692-c1807933-24cf-4ac5-a7c7-1acccb903c15.png)

### Expected Behaviour

org.jaspstats.JASP should have got downloaded properly and installed JASP.

### Steps to Reproduce

1. flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
2. flatpak install flathub org.jaspstats.JASP
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
There exist other issues with flatpak installation. Some solutions have been already proposed. Can you have a look for example to these 2 issues:
https://github.com/jasp-stats/jasp-issues/issues/1424
https://github.com/jasp-stats/jasp-issues/issues/1511

**Comment by boutinb** [comment]
And also did you have a look to this page: https://jasp-stats.org/linux-installation-guide/

**Comment by hussain-beig** [comment]
I ran `flatpak install flathub org.jaspstats.JASP` again (without doing anything) and it installed just fine. Not sure what caused the issue in the first place.
