### ISSUE TITLE
[Feature Request]: Point-Biserial Correlation Coefficient

### ISSUE THREAD

**Issue by Arwa-AA** [jasp-stats/jasp-issues#1559]
### Description

Would like to request an additional feature "point-biserial correlation coefficient" which measures correlation between a continuous-level variable and a binary variable.

**Comment by boutinb** [comment]
@EJWagenmakers What do you think of this request?

**Comment by EJWagenmakers** [comment]
Yes this would be good to have! Maybe one of our new recruits could try and implement this...

**Comment by JBatHome** [comment]
"The point-biserial correlation is mathematically equivalent to the Pearson (product moment) correlation"

https://en.wikipedia.org/wiki/Point-biserial_correlation_coefficient

No need to do anything more.

Enjoy !

**Comment by juliuspf** [comment]
I think this can be closed then. @Arwa-AA, if your issue has not been sufficiently addressed feel free to reopen it.

**Comment by jsphh7124** [comment]
In JASP version 0.18.3, it is no longer possible to include categorical variables in correlation analysis. Hence, Point-Biserial Correlation cannot be handled. Please reconsider adding this feature option.

**Comment by boutinb** [comment]
@jsphh7124 What do you mean? I can add nominal and ordinal variables without problem:
![Screenshot 2024-03-22 at 10 28 32](https://github.com/jasp-stats/jasp-issues/assets/503332/9f19fd4b-d5cb-439a-9524-0d04bf85b93e)

**Comment by tomtomme** [comment]
Maybe this is about binary data in nominal text format. In that case that data would need to be recoded into a numerical format.

**Comment by PerPalmgren** [comment]
I still think to add a button for Point-Biserial correlation under Pearson’s, Spearman’s and Kendall’s tau plus allowing for a dichotomous categorical variable to be inserted (with out having to recode) would be beneficial for JASP users, both  from a functional as well as a pedagogical perspective.
Per (the JASP lover)

**Comment by JBatHome** [comment]
OK, but how do you decide for the sign if it's not recoding ? Some users could do a false interpretation with a random choice by Jasp...

**Comment by tomtomme** [comment]
@PerPalmgren 
You think Point-Biserial correl is beneficial. How?
I agree that not having to recode categorial variables would be beneficial though - would be cool to have that one as its own feature request. JASP 0.19.2 still cannot do that.
