### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by NikitaKhromov-Borisov** [jasp-stats/jasp-issues#1560]
### JASP Version

0.16

### JASP Module

jaspBain

### What analysis are you seeing the problem on?

Welch's T test

### What OS are you seeing the problem on?

Windows 11

### Bug Description

In BAIN the resulting table with  Descriptive statistics all N=2
[Uploading BAIN.zip…]()

### Expected Behaviour

All N should be different and real

### Steps to Reproduce

1. 
2. 
3. 
...
In my sample all N are different
![image](https://user-images.githubusercontent.com/16406847/147508750-5cceb4be-102b-47dc-913e-4c5925099049.png)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by icekylin** [comment]
Hi,
>Uploading BAIN.zip…

Do you want to upload a data file here? you may need to try to upload the file and make sure the link again.because your additional file link is directed to this issue but not a zip file. Thanks.
