### ISSUE TITLE
[Bug]: empty heatmap in correlation

### ISSUE THREAD

**Issue by GUYON29** [jasp-stats/jasp-issues#1563]
### JASP Version

0.16

### JASP Module

jaspRegression

### What analysis are you seeing the problem on?

Correlation and Heatmap

### What OS are you seeing the problem on?

Windows 10

### Bug Description

For some modules, like heatmap in correlation, when you introduce the variables nothing happens. You have to remove a variable and put it back.I have a short video to show this (where can I send this video ?)

### Expected Behaviour

https://user-images.githubusercontent.com/95767832/147922433-3fcb4890-e14e-4f67-ae84-ea8166b0736b.mp4

### Steps to Reproduce

Fix this bug

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @GUYON29 I find your English completely understandable (I'm french also!). For your problem, I cannot reproduce it. I have tried it on Mac & Windows 10. Can someone else try it? @vandenman, @JohnnyDoorn ?

**Comment by juliuspf** [comment]
@GUYON29, could you check if this issue still persists in the newest version, 0.16.3?
