### ISSUE TITLE
[Feature Request]: multivariate multiple regression and hierarchical linear regression (entering predictors in blocks)

### ISSUE THREAD

**Issue by TarandeepKang** [jasp-stats/jasp-issues#1565]
### Description

Multivariate multiple regression and hierarchical linear regression as enhancements to existing linear regression procedures

### Purpose

Basic features of regression widely available in other statistical packages

### Use-case

Commonly used in various aspects of research data analysis, and also in undergraduate teaching

### Describe alternatives that you have considered

Currently possible in R as well as SPSS

### Additional context

I am aware this request is a repeat of #176  & #252 but wondering if any progress has been made? The ability to add predictors in blocks so that the order can be prespecified on theoretical grounds, is widely used in health psychology, and social psychology, and probably other fields, also. It is also not uncommon to have datasets with multiple dependent and predictor variables, and to want to analyse the relationships between them. Forgive the repost, and also if I have missed these features in the program!

**Comment by EJWagenmakers** [comment]
Hello Tarandeep,

Currently you can add predictors in blocks, just by adding the nuisance predictors "to the null model" in the model tab. So let's say you already have predictors X and Y, and you want to test the added effect of Z. Then you add X and Y "to the null model", and look at the results for Z. If you have an additional predictors K and M, and you want to retain the results for Z, just copy the first analysis, add Z "to the null model" (so that X, Y, and Z are now all part of the null model) and then examine the effect of K and M.

Cheers,
E.J.

**Comment by TarandeepKang** [comment]
Hello EJ,

Thank you for this very helpful response, that certainly fits my needs for a two-block design. Apologies for having missed it! I do however think it would be a further enhancement to allow a user-defined number of blocks, which would suit other researchers with more complex designs. As is available in that other commercial software that I will not name! Also, do you have any plans to allow multiple dependent variables in the regression module? That would be an excellent addition!

Thanks again for the great work, and for pointing out this great feature that I had missed! I leave it up to you to decide whether you want to close this issue?
Warmest regards,

Tarandeep

**Comment by boutinb** [comment]
I think we can close this issue

**Comment by TarandeepKang** [comment]
I agree that this is an effective workaround, yet I think there is still something outstanding. Firstly, the suggestion that EJ makes above allows us only to enter predictors into steps, SPSS allows the user to define the number of blocks. Secondly, I don't think the issue of the regression module allowing multiple dependent and predictor variables. As far as I can see, the software currently only allows one dependent variable at a time. Again, this is not the case when using the GLM procedure in SPSS or R.

**Comment by EJWagenmakers** [comment]
I think these are two separate requests. The first is to allow multivariate dependent variables. We should do this at some point but I am not sure about the urgency (we have some other fish to fry). The second is about defining the number of blocks. This is also an interesting addition that saves the user some time.  Again, we should put this on this list but I'd like to finish some other projects first.
