### ISSUE TITLE
[Bug]: This analysis terminated unexpectedly. Error in pf((=F, df, dullAnovaDf,lower.tail=FALSE):Non-numeric argument to mathematical function

### ISSUE THREAD

**Issue by monikahannna** [jasp-stats/jasp-issues#1566]
### JASP Version

0.14

### JASP Module

jaspAnova

### What analysis are you seeing the problem on?

repeated measures ANOVA simple main effets

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I have one repeated measures factor with 3 levels and one between subject factor with 3 levels. When I do my simple main effets analyses with the repeated measures factor in "imple effect factor" and the between subject factor i "moderator factor" it works but if when I do the reverse it doesn't work anymore.
I have already tried with both versions of jasp 0.14 and 0.16
![bug](https://user-images.githubusercontent.com/97235405/148394906-f4f3434c-4eff-40e6-ba59-98f14cbf5468.JPG)

### Expected Behaviour

I would like to obtain the results of my analyzes in both directions

### Steps to Reproduce

1. 
2. 
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @monikahannna I see you use the 0.14 JASP  version, could you try he newest version 0.16? If the problem still occurs, could you then send us a JASP file that shows this problem?

**Comment by monikahannna** [comment]
Hi,
Yes I have the same problem when I use the next version, 0.16. So I send
you my JASP file.
Thanks you for help.
Monika Karasinska
Neuropsychologue
06 09 54 01 70



Le ven. 7 janv. 2022 à 11:49, bruno boutin ***@***.***> a
écrit :

**Comment by boutinb** [comment]
Hi @monikahannna, if you want to send us a JASP file, please rename it as a zip file and drag & drop it in a new comment of this issue in GitHub. Via Email, the attachment is not sent.

**Comment by monikahannna** [comment]
[ANOVA indice d efficience etude.zip](https://github.com/jasp-stats/jasp-issues/files/7829070/ANOVA.indice.d.efficience.etude.zip)

**Comment by monikahannna** [comment]
it's done!
Thanks
Monika Karasinska
Neuropsychologue
06 09 54 01 70


Le ven. 7 janv. 2022 à 13:54, bruno boutin ***@***.***> a
écrit :

**Comment by boutinb** [comment]
This is will be solved in 0.16.1 (over 3 weeks hopefully).

**Comment by monikahannna** [comment]
ok, thanks you!
Monikz

Le jeu. 13 janv. 2022 à 15:52, bruno boutin ***@***.***> a
écrit :
