### ISSUE TITLE
[Bug]: Unable to open any downloaded file on chromebook with linux.

### ISSUE THREAD

**Issue by chromebookjasp** [jasp-stats/jasp-issues#1569]
### JASP Version

0.16

### What OS are you seeing the problem on?

Chrome OS version 96.0.4664.111

### Bug Description

Whenever I try to open any csv file it doesn't appear to be downloaded on my computer at all. I download a google sheet as a csv file and then open jasp and try to open it. I open the menu > open > computer > browse and it seems as though nothing has ever been downloaded on my computer besides the software it runs on. It does not open my files page when it does this either, just some page I've never seen before that supposedly shows downloads on my chromebook. I need help with this asap as I need to use jasp for a college course and no videos or forums seem to cover this issue. 
![Screenshot 2022-01-10 3 55 40 PM](https://user-images.githubusercontent.com/97485066/148857717-4d40ee5d-dfa1-4c54-aecc-a7654ab23dc3.png)
![Screenshot 2022-01-10 3 54 41 PM](https://user-images.githubusercontent.com/97485066/148857720-cef5935a-0c2f-428e-bd88-bcdee69a307d.png)

### Expected Behaviour

I should've been able to find and open the downloaded files so as to run statistics on them.

### Steps to Reproduce

1. download a google sheet as a csv file
2. open jasp
3. open menu
4. click open 
5. click computer
6. click browse or documents or downloads
7. no files appear
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JoKeyser** [comment]
In your second screenshot, you have not navigated to your Download folder, as far as I understand... so it is expected that the file is not shown there yet, if I understand correctly.

Have you tried to browse to the Download folder? As a first step, click on "Home" in the left pane.

**Comment by sspears1** [comment]
I just helped a user at my university with a very similar issue. Based off the information you provided, I think it may be the same issue.

This is happening because Linux on Chrome runs in a sandboxed environment, meaning that it and any applications running through it do not have access to the files on your Chromebook.  You can use this guide from the ChromeOS docs to learn how to make folders accessible to Linux and how to access them: https://chromeos.dev/en/linux/setup#sharing-files-to-linux

**Comment by chromebookjasp** [comment]
@sspears1 you were correct and I confirmed it earlier today. I appreciate the help!! Thank you!

**Comment by boutinb** [comment]
Thanks @sspears1 !
