### ISSUE TITLE
Enhancement request: Reporting likelihoods in Bayesian tests

### ISSUE THREAD

**Issue by fplatz** [jasp-stats/jasp-issues#157]
* Enhancement: Reporting models' likelihoods in Bayesian tests in output tables
* Purpose: For the purpose of calculating posterior model odds (with own prior probabilities) as well as for teaching statistics for instance, it would be great to have the likelihoods of every model in the output table. It might be the case that some won't need this information, a possible solution might be the implementation of an option in the tests' menu like "tick here for a report of models' likelihoods". 
Thanks a lot! 

Best,
Friedrich

**Comment by tomtomme** [comment]
@fplatz 
This request seems still relevant today. Correct?

@juliuspfadt 
If still relevant, we should assign someone.

**Comment by fplatz** [comment]
Happy new year to @ll! Yes, I think, it is still relevant. Thanks for the implementation! Am 01.01.2024 um 19:04 schrieb Thomas Langkamp ***@***.***>:﻿
@fplatz
This request seems still relevant today. Correct?
@juliuspfadt
If still relevant, we should assign someone.

**Comment by FBartos** [comment]
A relevant note is that some of the Bayesian tests don't need to compute the marginal likelihood (which might be computationally expensive to obtain), but sometimes use alternatives corresponding to Savage-Dickey density ratio etc (I think that t-test uses a one-dimensional integration over the t-statistic to obtain the BF directly--after simplifying the formula with ratio of marginal likelihoods).

btw, the Robust T-Tests module provides log(marginal likelihoods) for different t-tests models:
![image](https://github.com/jasp-stats/jasp-issues/assets/38475991/a751f7e0-6147-41be-8e4e-9bd9e6400d5b)

**Comment by JohnnyDoorn** [comment]
Thanks @FBartos!
@fplatz does that solve your issue? I do think that the current setup is the way to go: we have the "vanilla" t-tests as the core analyses, and for users that want to dive deeper, there is the robust t-test module. That way we avoid cluttering the regular t-test interface (I think 99% of users are not interested in the marginal likelihood itself).

Kind regards,
Johnny

**Comment by fplatz** [comment]
Hi all! 
That sounds very promising and seems to be a suitable solution. My 
initial post was some month ago. Meanwhile the development of new 
modules increased the possibilities and thus, my post is "out dated" 
:-) 

Thank you for your solutions!
