### ISSUE TITLE
[Bug]: Some interface guidance seem unreasonable in jaspAnova

### ISSUE THREAD

**Issue by icekylin** [jasp-stats/jasp-issues#1578]
### JASP Version

0.16

### JASP Module

jaspAnova

### What analysis are you seeing the problem on?

ANOVA

### What OS are you seeing the problem on?

Windows 10

### Bug Description

The guide says "below", but the info button is "above" it. see the pic
![Snipaste_2022-01-19_15-02-06](https://user-images.githubusercontent.com/10348402/150081907-0ee2ce9f-02df-4806-bf5d-872ae3f90dbb.png)

### Expected Behaviour

So，change it as “above” is better.

### Steps to Reproduce

1. ANOVA
2. Order restrictions

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [ ] I have included a JASP file that causes the crash/bug, if any.
- [x] I have accurately described the bug, and steps to reproduce it.

**Comment by amirmasoudabdol** [comment]
Thanks for pointing this out! We will patch it in the next release!

**Comment by icekylin** [comment]
@amirmasoudabdol Likewise, I think "Bias corrected and accelerated."at [here](https://github.com/jasp-stats/jaspAnova/blob/1305b7ac88c252b5abcd6d22492e2c9962b03127/R/ancova.R#L1838) and help file are typo without a "and", maybe it should be "Bias corrected and accelerated."or "bias-corrected and accelerated (BCa)",so you can see [here](https://www.frontiersin.org/articles/10.3389/fpsyg.2019.02215/full)

I guess there is no need to reopen an issue, right?

**Comment by amirmasoudabdol** [comment]
It seems that you are right, but I think one of the maintainers of the jaspAnova should look it up. Maybe @JohnnyDoorn could confirm it?

**Comment by icekylin** [comment]
yes,if it can be confirmed,I think this impact is trivial, so we can change it in the next release.
I can open a new issue if necessary, or you can track it in an internal issue.

**Comment by JohnnyDoorn** [comment]
@Kucharssim you had added this at some point - do you have any words of wisdom here? I am unsure as I am unfamiliar with the whole bca thing..
