### ISSUE TITLE
JASP will not run 

### ISSUE THREAD

**Issue by tastickfan** [jasp-stats/jasp-issues#1579]
### JASP Version

0.16

### What OS are you seeing the problem on?

Arch 

### Bug Description

Hi I'm a total linux newbie and I cannot run JASP for the life of me. I keep getting an error with setting a locale. 

### Expected Behaviour

JASP should run. 

### Steps to Reproduce

1. I try to run JASP 
...

### Log (if any)

```bash
[🔴] × flatpak run org.jaspstats.JASP
terminate called after throwing an instance of 'std::runtime_error'
what():  locale::facet::_S_create_c_locale name not valid


locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_DE.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=
```

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Can this issue help you: https://github.com/jasp-stats/jasp-issues/issues/1424 ?

**Comment by boutinb** [comment]
Did you have a look at this installation guide: https://jasp-stats.org/linux-installation-guide/

**Comment by JorisGoosen** [comment]
This issue occurs when not all `LC_*` values are set to the same value... Like `LC_TIME=en_DE.UTF-8` if changed to `LC_TIME=en_US.UTF-8` it should work fine.
