### ISSUE TITLE
Network analysis breakdown

### ISSUE THREAD

**Issue by JASPUSER09990** [jasp-stats/jasp-issues#158]
## Template for bug reports

* JASP version: Version 0.8.6
* OS name and version: Windows 7 Enterprise SP1
* Analysis: Network analysis
* Steps to reproduce: Network analysis --> Select 25 variables as Dependent variables --> Click "Network plot" --> Add a binary variable to "split by". Then, a box coming out saying "JASPEngine.exe has stopped working". The whole programme stopped. 
This mistake message also occures when I want to save the plot as pdf file. 
This mistake message also occures when I change the estimator.
I guess this breakdown is due to too many DVs.

**Comment by AlexanderLyNL** [comment]
Will be fixed in the next version 0.9.3.
