### ISSUE TITLE
[Bug]: JASP installed but application does not open

### ISSUE THREAD

**Issue by manondmg** [jasp-stats/jasp-issues#1580]
### JASP Version

0.16

### What OS are you seeing the problem on?

Chromebook

### Bug Description

Hello, I installed JASP on my chromebook 2020. I installed JASP on linux by following all your instructions on the site. the application installed well on my computer, the icon is showing well in my folders next to the linux terminal. However, when I click on the application to open it, it loads in a vacuum. It never opens. I turned off / on the computer. I have installed/uninstalled JASP 5 times. Nothing changes, the application keeps loading in a vacuum. I also reset the computer to factory settings. This has not changed anything. 
Thank you for your help 
Sincerely

### Expected Behaviour

The application should open but it loads and never opens. 

### Steps to Reproduce

1. The application should open but it loads and never opens. 
2. 
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by manondmg** [comment]
please @JorisGoosen Do you know what to do? Do you have a solution?

**Comment by JorisGoosen** [comment]
have you tried the solutions in: https://github.com/jasp-stats/jasp-issues/issues/1600

if not, I would love to see the output you get after trying to start jasp in a terminal
