### ISSUE TITLE
[Bug]: Scrolling speed seems inconsistent in the interface

### ISSUE THREAD

**Issue by shun2wang** [jasp-stats/jasp-issues#1584]
### JASP Version

0.16 (Nightly)

### Commit ID

50f5040b071c06eb39c9bf08e4f8ff9cc88ac131

### What OS are you seeing the problem on?

Windows 10 21H2

### Bug Description

Scrolling speed behaves inconsistently in data library, analysis and data view, speed in analytics and data view does not seem to respond to setting parameters in preferences,they are too fast. watch this video：

https://user-images.githubusercontent.com/10348402/150792197-11fb7140-a1fc-4aa7-9696-810dd743bedb.mp4

### Expected Behaviour

The scroll speed setting parameter should be a global response, and the scrolling speed should be consistent in any interface.

### Steps to Reproduce

1. set scroll to 100 pix/s
2. scroll on data library,data view,analysis with touchpad or mouse
3. data library is slow but other fast.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [ ] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by icekylin** [comment]
@amirmasoudabdol Could you please take a look at this issue，thank you!

**Comment by amirmasoudabdol** [comment]
I can, but at the moment I'm involved with another projects that has a higher priority. After that, I can look into this and see how it fits into our release schedule! :-)

**Comment by shun2wang** [comment]
This cannot be reproduce on JASP 0.16.3, so i am going to close it
