### ISSUE TITLE
[Bug]: Error message when opening pre-installed version of JASP 0.16 on flashdrive

### ISSUE THREAD

**Issue by avamosi** [jasp-stats/jasp-issues#1585]
### JASP Version

0.16

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I downloaded a pre-installed version of 0.16 on a flash drive.  When I start the program, it freezes with the error message written out below.  A specific set of icons appears to be missing.  I downloaded the pre-installed version onto multiple flash drives and had the same error and computer freeze with each—any recommendations.

An error occured trying to initialize a module from dir E:/JASP-0.16.0-64bit/Modules/jaspEquivalenceTTests, the error was: icons is missing from E:/JASP-0.16-64ibt/Modules/jaspEquivalencTTests/jaspEquivalenceTTests/icons. 

### Expected Behaviour

The program should initiate directly from the flash drive. 
![image](https://user-images.githubusercontent.com/98360081/150873876-3a79cd47-c3d1-4e9c-8847-bff30136ee64.png)

### Steps to Reproduce

1. See the image and error message above
2. 
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment]
Hi @avamosi, thanks for the report. Does this issue persist with the latest version of JASP?

**Comment by JorisGoosen** [comment]
Im sorry but if your flashdrive is formatted with FAT you probably cant install JASP on it.

You need to reformat it to ntfs or something.
