### ISSUE TITLE
[Bug]: Undefined translation string in developer module installer

### ISSUE THREAD

**Issue by icekylin** [jasp-stats/jasp-issues#1589]
### JASP Version

0.16 (Development)

### What OS are you seeing the problem on?

Windows 10

### Bug Description

There may be undefined string（“Install”） in the developer module installer interface.
the code text may at [here](https://github.com/jasp-stats/jasp-desktop/blob/1c936af44d57b6ddfa3fad7c44869f1787b3cc82/Desktop/components/JASP/Widgets/ModuleInstaller.qml#L187) in ModuleInstaller.qml
![undefined translation string](https://user-images.githubusercontent.com/10348402/151165613-9caa0934-f941-4a38-95a0-c123085ad600.png)

### Expected Behaviour

to be definded

### Steps to Reproduce

1. see the screenshot
2. 
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Thanks to @JoKeyser, the extra string should come up to WebLate this weekend, and can be then translated.
