### ISSUE TITLE
[Bug]: JASP CRASHES (Multi-Study Files)

### ISSUE THREAD

**Issue by WD4576** [jasp-stats/jasp-issues#1590]
### JASP Version

0.16

### What analysis are you seeing the problem on?

Capability Study

### What OS are you seeing the problem on?

Windows 10

### Bug Description

When performing a Capability Study, I had 4 datasets to evaluate.  To save steps, after the first study I hit the + tab and duplicated the study.  I then changed the title and a few parameters and ran the additional studies.  This worked fine.
This issue was when trying to retrieve the study from the file storage location.  JASP would begin to open normally then crash.  All attempts to troubleshoot the issue failed.  
This morning I tried another method.  I completed one study per JASP file.  This worked and each file could be saved and re-opened.  This does not allow the time saving steps of duplicating a study but will work untill the issue is resolved.

### Expected Behaviour

The system should have allowed multi data streams to be analyzed in one file.

### Steps to Reproduce

1. Create a multi data set file 
2. Perform four capability studies on the data
3. Save the file to my documents
4. Try to open the file.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @WD4576, I'm not sure to understand completely the steps you do: when you duplicate an analysis (by clicking the '+' button), you still use the same dataset, so I don't see how you use another dataset in your description.

Maybe, for your information, the best way to use the same analyses for several datasets (when they have the same column names) is the following: 
. Make your analyses with the first dataset, and save the JASP file.
. In the hamburger menu, click 'Sync Data', and choose another dataset: all the analyses should be rerun with the new data (as long as the column names are the same). Then save the JASP file with another name.

**Comment by WD4576** [comment]
Bruno,
  I was working with four columns of data.  When you hit the + you duplicate the study.  But you can then edit the study. It allows you to choose a different data set to be evaluated and other parameters if necessary.  The studies I was working on only needed the data set and one decimal point change in the upper tolerance.   Everything else was going to be identical, so I felt duplicating the study and changing one or two factors was the fastest way to do this.  This created four studies in one file.  That large of a file seems to be what caused my inability to email the file even when zipped.  It also would crash when I tried to open the saved file.  With each test completed in a separate file the issue has not repeated. 
If my explanation is not clear, I would be willing to set up a "Teams" call to discuss it with you.
Shane

**Comment by boutinb** [comment]
How big is your data file and your JASP file?

**Comment by WD4576** [comment]
The one giving issues was 10.6MB


[cid:b8cc77b5-940c-4c58-a65f-3a99303f9240]

Shane S. Kreuzer

Special Process Laboratory Technician

ASQ Certified Black Belt

Tel: +1 (803) 506-6586

E-mail: ***@***.******@***.***>

SKF Sumter, USA

925 Corporate Circle, Sumter, South Carolina – 29154

www.skf.com<http://www.skf.com/>, Facebook<https://www.facebook.com/SKFGroup>, LinkedIn<https://www.linkedin.com/company/skf>, Twitter,<https://twitter.com/skfgroup> Instagram,<https://instagram.com/skfgroup/> YouTube SKF Sumter, USA

This communication constitutes an electronic communication within the meaning of the Electronic Communication Privacy Act 18 U.S.C. 2510 et. Seq., and any unauthorized interception of this communication is strictly prohibited by law.  If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify the sender immediately by reply e-mail and delete the message and any attachments.



________________________________

**Comment by boutinb** [comment]
Strange, this is not really big. And you should be able to upload it in this GitHub issue (you need first to zip it, and you need to that directly with the GitHub website, not via email): the max size is 25 MB. Can you try again by zipping it?
