### ISSUE TITLE
[Bug]: When trying to deploy .msi using Intune error/message appears

### ISSUE THREAD

**Issue by SvDellen** [jasp-stats/jasp-issues#1595]
### JASP Version

0.16

### What OS are you seeing the problem on?

Windows 10/11, Intune

### Bug Description

When trying to deploy Jasp .msi using Intune the following message appears and setup/confige can't continue. Would be nice if this could be fixed.

![jasp_error](https://user-images.githubusercontent.com/86820374/151755386-5e0d3dfd-38a6-42ec-b3d2-e2b91e407d13.png)

Thanks in advance and best regards

Sijtze

### Expected Behaviour

When adding .msi to Intune error should nog show up. For update purposes this is the way to go for .msi installs using Intune.

### Steps to Reproduce

1. add new app in Intune, choose for line-of-business type, app type
2. select app package file, select jasp .msi file
3. add file, error appears
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by amirmasoudabdol** [comment]
Although I have not worked with Intune, I guess that this is probably due to a misconfiguration in our installer! We are in the process of improving and modernising the installer, and that should hopefully make this more robust as well.

@JorisGoosen, I'm not so sure, but this [missing `Id`](https://github.com/jasp-stats/jasp-desktop/blob/72cead0afe63a628d353704b5a3d0bf278855c0a/Tools/wix/jasp.wxs#L19) might be the issue, unless it's being replaced by something and I am not familiar with.

**Comment by SvDellen** [comment]
I've managed to work around it using: https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool. But in the light of managing updates it would be nicer to deploy the .msi instantly. Then it's possible to only upload the new .msi, change the version number and the update would install automatically.

**Comment by JorisGoosen** [comment]
> Although I have not worked with Intune, I guess that this is probably due to a misconfiguration in our installer! We are in the process of improving and modernising the installer, and that should hopefully make this more robust as well.

But sadly it won't be ready for the next release yet.

> @JorisGoosen, I'm not so sure, but this [missing `Id`](https://github.com/jasp-stats/jasp-desktop/blob/72cead0afe63a628d353704b5a3d0bf278855c0a/Tools/wix/jasp.wxs#L19) might be the issue, unless it's being replaced by something and I am not familiar with.

https://wixtoolset.org/documentation/manual/v3/xsd/wix/product.html indicates that it is an "autogen guid" and so should generate one every time, at least, otherwise it wouldn't install at all I guess?

**Comment by tomtomme** [comment]
@SvDellen 
The new msix installer is now live with jasp 0.18.3
So I hope this is fixed now.
Can you test?
