### ISSUE TITLE
[Feature Request]: Saving the residuals of a Bayesian regression to data file

### ISSUE THREAD

**Issue by Golden-Retriever-1** [jasp-stats/jasp-issues#1596]

**Comment by vandenman** [comment]
This is a reasonable request. However, In the Bayesian framework, the residuals are not fixed values but rather distributions. As a consequence, any further analysis of the residuals *should* account for this uncertainty. I guess we could make add two columns to the dataset, the posterior mean of the residuals and the posterior standard deviation of the residuals (which may be used as a proxy for a standard error).

@EJWagenmakers any further suggestions?

**Comment by EJWagenmakers** [comment]
I am on board with your suggestion!

**Comment by Golden-Retriever-1** [comment]
Thank you for your replies.

The question arose from how to present the requirement whether the variance of the residuals is not constant across predictions to an audience who is less familiar with Bayesian statistics. Furthermore, how to compare this check across several Bayesian linear regressions.
The current simple plot adds nothing as value to reports, publications, etc. It is a very broad and inaccurate (in that sense that its characteristics cannot be adapted well and precisely like grid, like adding elements etc.) format to describe the residuals to anyone when having conducted a Bayesian linear regression. I cannot even replot it with adapted scale range, standardize the values, plot several graphs into one plot, combine them in several plots next to each other etc. 

Hence, it would be nice to get several options to describe the residual(s) distributions. What about standardized residual(s) distributions to be able to compare? Is the R code available anywhere to be able to access the individual values and exactly have a look at each step of programming?
Here is a similar request related to residual analysis (in another statistical procedure): https://github.com/jasp-stats/jasp-issues/issues/151

**Comment by Golden-Retriever-1** [comment]
> This is a reasonable request. However, In the Bayesian framework, the residuals are not fixed values but rather distributions. As a consequence, any further analysis of the residuals _should_ account for this uncertainty. I guess we could make add two columns to the dataset, the posterior mean of the residuals and the posterior standard deviation of the residuals (which may be used as a proxy for a standard error).
> 
> @EJWagenmakers any further suggestions?

I would argue that posterior means and standard deviation are insufficient to describe the residuals to any audience. Are there any other ways to obtain complete information about the residual(s) distributions which can be explained easier to a broader audience?! Descriptive statistics about distributions usually include more than only mean and standard deviation.

**Comment by vandenman** [comment]
> I would argue that posterior means and standard deviation are insufficient to describe the residuals to any audience.

Well, there is, at least at the moment, no good way to export more complete information on the distribution of the residuals. I guess it is possible to also export the quantiles of the distribution of the residuals. But to export that we'd need to create a new column for each quantile level (e.g., `quantile_01`, `quantile_02`, ..., `quantile_98`, `quantile_99`) which may become very cumbersome to work with.

**Comment by vandenman** [comment]
> Hence, it would be nice to get several options to describe the residual(s) distributions. What about standardized residual(s) distributions to be able to compare? Is the R code available anywhere to be able to access the individual values and exactly have a look at each step of programming?

The R code is available here: https://github.com/jasp-stats/jaspRegression/blob/002e5d4241df938de664333230b1a94acf4b63b3/R/regressionlinearbayesian.R#L1048-L1060

We use the R package [BAS](https://cran.r-project.org/package=BAS). Note that this package uses many analytical solutions and avoids sampling unless there is no other choice.



> The current simple plot adds nothing as value to reports, publications, etc. It is a very broad and inaccurate (in that sense that its characteristics cannot be adapted well and precisely like grid, like adding elements etc.) format to describe the residuals to anyone when having conducted a Bayesian linear regression. I cannot even replot it with adapted scale range, standardize the values, plot several graphs into one plot, combine them in several plots next to each other etc.

While we strive to make JASP as feature-rich as possible, if you must have full flexibility over the figures I would recommend using R directly (or post-process figures from JASP with some other software, e.g., Adobe Illustrator).

**Comment by Golden-Retriever-1** [comment]
There is currently no good way to describe the residuals at all for reporting them anywhere. The current plot gives only a very broad estimate for the data analyst but is not of further use to write about, present, display, report etc. Thus, the feature request on how to best describe the residuals distribution is well reasoned, since at least I hope that the assumptions for Bayesian linear regression are of interest for those who conduct the analysis. 
Adobe Illustrator for graphs is no good idea (= inaccurate!), the grid is missing, the axes are not related or fixed anywhere in the graphics. There is simply nowhere "must" (that is a bit of an odd speech, I suppose).

This is an issue for a feature that simply arises from practice of statistical data analysis. Checking assumptions of a Bayesian linear regression where residuals are definitely considered! This is for sure of interest for several users who conduct a Bayesian linear regression and check the assumptions! How to best display and describe residuals!
