### ISSUE TITLE
[Feature Request]: Add coefficient of variation to more analysis

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#1599]
### Description

Add the coefficient of variation to ANOVAs, t-Tests, Regressions etc. tables of "descriptives"

### Purpose

It is hard to compare unstandardized values like SD between variables or even across groups of the same variable if the means differ considerably. The coeffiecient of variation is a well known solution to this problem and should be broadly added to every "Descriptives table"

### Use-case

To compare dispersion accross variables and groups.

### Is your feature request related to a problem?

The coefficient of variation is underutilized because it is until now only reported in JASPs main "Descriptives" module

### Describe the solution you would like

Add the coefficient of variation in all "Descriptive" tables right next to the already shown n, mean, sd, se

**Comment by tomtomme** [comment]
I love it!
Good work guys! Thank you for the quick implementation!

**Comment by tomtomme** [comment]
I just tested the new awesome flatpak-beta! Coefficient of Variation is in t-Tests :D 
But not yet in descriptive tables of ANOVAs or Regression.
Thx so far!

**Comment by Kucharssim** [comment]
Yes, currently it's only in T-tests. We have a PR for ANOVAs too, but we did not manage to merge it for the 0.16.3 release. It will be hopefully in 0.16.4.
