### ISSUE TITLE
Principal Component Analysis (PCA) is blocked and non-functional due to variable type assignment

### ISSUE THREAD

**Issue by DrKjellArne** [jasp-stats/jasp-issues#1602]
### Description

A data set having few unique values, although Continuous variables

### Purpose

Sometimes, a small data set is used having Continuous variables

### Is your feature request related to a problem?

When selecting the variables for PCA, no error explanation why the variables can not be used for PCA

### Describe the solution you would like

A message when selecting a ordinal type variable, that only Continuous type variables can be selected for this type of analysis.

### Additional context

![JASP_PCA](https://user-images.githubusercontent.com/98814065/152232403-9405a15a-6115-49c0-9f78-ff848a0721d5.png)

**Comment by vandenman** [comment]
I agree there should be a helpful message that explains what is going on. Perhaps @boutinb can take a look at that?

Note that you can change the variable type like so: 
![image](https://user-images.githubusercontent.com/21319932/152296813-4a4bf62c-c16d-468b-a7ae-fcddc1e83793.png)
and after you change the variable type to scale it should be possible to use the variables in PCA.

**Comment by DrKjellArne** [comment]
Thank you your prompt response. Yes, I found the option to change the variable type. At first, not intuitive for a newbe, but elegant once discovered.
