### ISSUE TITLE
[Bug]: incorrect SHA256 for portable Windows version

### ISSUE THREAD

**Issue by DIV-on-github** [jasp-stats/jasp-issues#1604]
### JASP Version

0.16

### What OS are you seeing the problem on?

Windows 10.

### Bug Description

Website https://jasp-stats.org/thank-you-for-downloading-jasp-win64-zip/
has
Your download should start automatically within the next 5 seconds. In case it doesn’t, click [here](https://static.jasp-stats.org/JASP-0.16.0-64bit.zip).
SHA256 checksum: a2540778696669049f670b6632e99461817e02902599c92aa4da3d0552173be3.

It seems to be OUT OF DATE, and applying to version 0.15

Name: JASP_0-15-0_preinstalled.zip
Size: 546893923 bytes (521 MiB)
CRC32: F6882B6F
CRC64: 58F34B7C218C4E31
SHA256: A2540778696669049F670B6632E99461817E02902599C92AA4DA3D0552173BE3
SHA1: 12FBCFC342642AF613720157B947C02C610C02A7
BLAKE2sp: B1EF794983E876EFD4F09174D59B8229317E916E352B2E6B72969D4EAD083A62

according to 7-Zip.

—DIV

### Expected Behaviour

File has
Name: JASP_0-16-0-0-64bit_preinstalled.zip
Size: 564819524 bytes (538 MiB)
CRC32: 96F1D624
CRC64: D5C90FA0E54CA122
SHA256: 5794F514C287BF06910E2CAEB9601ED260CC757BB3A7EAA596B68C9350E3B0C4
SHA1: A212B8973D51EEFE6C31D91B38E2840B66DAA59B
BLAKE2sp: 0546D564EF10804CDD713FC75E00BCBE005D7306D75C955544F5063448C1C104

according to 7-Zip.

### Steps to Reproduce

Download file and check CRC.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by DIV-on-github** [comment]
BTW, I downloaded the current file twice to confirm.
—DIV

**Comment by juliuspf** [comment]
any ideas @JorisGoosen

**Comment by JorisGoosen** [comment]
Well, Ill double check the sha256sum but its just something that @DanaJohanna could fix on the website  I suppose.
If were gonna be sharing sha256sums we should make sure they are correct.

**Comment by JorisGoosen** [comment]
The correct sha256sum is indeed `5794f514c287bf06910e2caeb9601ed260cc757bb3a7eaa596b68c9350e3b0c4`

**Comment by shun2wang** [comment]
@JorisGoosen Maybe should add this information to the checklist https://github.com/jasp-stats/INTERNAL-jasp/issues/1910

**Comment by JorisGoosen** [comment]
![afbeelding](https://user-images.githubusercontent.com/29062713/187656056-9610ba4c-2237-4157-8c1b-16e6c6065e05.png)

**Comment by DanaJohanna** [comment]
The check sum has now been updated, thank you for noticing!

**Comment by JorisGoosen** [comment]
> The check sum has now been updated, thank you for noticing!

The checksum I put in the issue was for 0.16 btw, not for 0.16.3.... 
I guess this was a bit confusing, sorry... I thought it was about the overview of older jasp versions, but I realize now we don't put checksums there.

The checksum for the actual *current* zip download is `6997b1e25c95c73b8c67e224eca378b20a1d86420e735e209ea569a3e658836e`

**Comment by DanaJohanna** [comment]
I now updated the checksum on https://jasp-stats.org/thank-you-for-downloading-jasp-win64-zip with 6997b1e25c95c73b8c67e224eca378b20a1d86420e735e209ea569a3e658836e

**Comment by JorisGoosen** [comment]
merci!
