### ISSUE TITLE
[Feature Request]: show cursor initially in Create Computed Column dialogue box

### ISSUE THREAD

**Issue by DIV-on-github** [jasp-stats/jasp-issues#1606]
### Description

Show cursor initially in Name entry field of Create Computed Column dialogue box

### Purpose

Let user know where focus is.

### Use-case

Let user know where focus is.

### Is your feature request related to a problem?

I didn't know where focus was.

### Describe the solution you would like

Show cursor initially in Name entry field of Create Computed Column dialogue box

### Describe alternatives that you have considered

Change shading or outline of element with focus.

**Comment by DanaJohanna** [comment]
Create Computed Column dialogue box already has the cursor in it

**Comment by DanaJohanna** [comment]
The 'show cursor initially in Create Computed Column dialogue box' is solved, the additional 'different-but-related note' is not

**Comment by juliuspf** [comment]
I know it is a bit more trouble but it would be good to make a new issue about this then.
