### ISSUE TITLE
[Feature Request]: Descriptive statistics (Mean (or median) and Standard deviation) for correlations

### ISSUE THREAD

**Issue by Crom60** [jasp-stats/jasp-issues#1609]
### Description

It would be really useful if when running a correlation (Pearson, Spearman, Bayesian etc.) that there was an option for basic descriptive statistics. If you have missing data that influences your variables inconsistently there is no way without extensive filtering to get means and standard deviations for participants included in the correlations. It might be easiest to limit this option to the pairwise display of correlations as this will get messy for a Matrix. 

### Purpose

Provide easy to access descriptive statistics for correlations.

### Use-case

Anytime you have correlation results you would like to write up in APA format.

### Is your feature request related to a problem?

No

### Describe the solution you would like

Have an option to get descriptive statistics for correlations. 

### Describe alternatives that you have considered

One option would be to create an option within the descriptive statistics that allowed you to remove missing data pairwise for two variables.

**Comment by juliuspf** [comment]
Hi @Crom60, thanks for the request. Is this feasible, @Kucharssim?

**Comment by tomtomme** [comment]
@Crom60 
You can already get descriptives in the closely related Linear Regression module. 
Feel free to reopen, if this is not sufficient.
