### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by wagnerfontes2** [jasp-stats/jasp-issues#161]
* JASP version: 0.8.6.0
* OS name and version: Windows 8.1 Pro 64 bit
* Analysis: none - the software does not start
* Steps to reproduce: 
- I downloaded the installer, run it and at the end it does not start JASP (the checkbox was marked). 
- Tried to run Jasp.exe in the Program Files, then got the message "JASP.exe application error. The application could not be initialized correctly (0xc000007b)" 
![image](https://user-images.githubusercontent.com/31344134/39889524-8542555e-546e-11e8-9101-4e618da9ba13.png)
- Tried to run as administrator, to uninstall and reinstall, to download and run the preinstalled version, to disable the antivirus (AVG), all showing the same error message.

**Comment by JorisGoosen** [comment]
I am going to assume the new version works, if not, feel free to reopen this issue.
