### ISSUE TITLE
MSA 

### ISSUE THREAD

**Issue by WD4576** [jasp-stats/jasp-issues#1611]
### JASP Version

0.16

### JASP Module

jaspQualityControl

### What analysis are you seeing the problem on?

Measurement System Analysis

### What OS are you seeing the problem on?

Windows 10

### Bug Description

![image](https://user-images.githubusercontent.com/97352284/153430644-265685ef-3006-4949-b6b8-d7a581b22bef.png)

### Expected Behaviour

Jasp should run the analysis.

### Steps to Reproduce

1. Select operators
2. Select sample number
3. Select measurements
4. FAULT
...

### Log (if any)

```bash
Could not copy and paste Jasp to this format.  "task not supported"
```

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomishay** [comment]
Can you please provide the jasp file associated with this issue?

**Comment by WD4576** [comment]
Today I am having problems with a capability study as well.  Had to revert Minitab.  It, like the MSA worked but was rejected by JASP.  Any help or coaching would be appreciated.


[cid:d6cbc829-df90-46c9-bce8-8e307738c325]

Shane S. Kreuzer

Special Process Laboratory Technician

ASQ Certified Black Belt

Tel: +1 (803) 506-6586

E-mail: ***@***.******@***.***>

SKF Sumter, USA

925 Corporate Circle, Sumter, South Carolina – 29154

www.skf.com<http://www.skf.com/>, Facebook<https://www.facebook.com/SKFGroup>, LinkedIn<https://www.linkedin.com/company/skf>, Twitter,<https://twitter.com/skfgroup> Instagram,<https://instagram.com/skfgroup/> YouTube SKF Sumter, USA

This communication constitutes an electronic communication within the meaning of the Electronic Communication Privacy Act 18 U.S.C. 2510 et. Seq., and any unauthorized interception of this communication is strictly prohibited by law.  If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify the sender immediately by reply e-mail and delete the message and any attachments.



________________________________

**Comment by WD4576** [comment]
[cid:15115812-d4d4-429f-a8a3-ab0d677c765f]
And this is another issue we have, our email system does not like to send the files.  Its hit and miss.

[cid:f76370b8-e66c-408d-9c32-a5283b08dd7b]

Shane S. Kreuzer

Special Process Laboratory Technician

ASQ Certified Black Belt

Tel: +1 (803) 506-6586

E-mail: ***@***.******@***.***>

SKF Sumter, USA

925 Corporate Circle, Sumter, South Carolina – 29154

www.skf.com<http://www.skf.com/>, Facebook<https://www.facebook.com/SKFGroup>, LinkedIn<https://www.linkedin.com/company/skf>, Twitter,<https://twitter.com/skfgroup> Instagram,<https://instagram.com/skfgroup/> YouTube SKF Sumter, USA

This communication constitutes an electronic communication within the meaning of the Electronic Communication Privacy Act 18 U.S.C. 2510 et. Seq., and any unauthorized interception of this communication is strictly prohibited by law.  If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify the sender immediately by reply e-mail and delete the message and any attachments.



________________________________

**Comment by WD4576** [comment]
Sending data file .csv


[cid:14c27cbe-abbf-4a17-bf73-358c390cdc9a]

Shane S. Kreuzer

Special Process Laboratory Technician

ASQ Certified Black Belt

Tel: +1 (803) 506-6586

E-mail: ***@***.******@***.***>

SKF Sumter, USA

925 Corporate Circle, Sumter, South Carolina – 29154

www.skf.com<http://www.skf.com/>, Facebook<https://www.facebook.com/SKFGroup>, LinkedIn<https://www.linkedin.com/company/skf>, Twitter,<https://twitter.com/skfgroup> Instagram,<https://instagram.com/skfgroup/> YouTube SKF Sumter, USA

This communication constitutes an electronic communication within the meaning of the Electronic Communication Privacy Act 18 U.S.C. 2510 et. Seq., and any unauthorized interception of this communication is strictly prohibited by law.  If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify the sender immediately by reply e-mail and delete the message and any attachments.



________________________________

**Comment by WD4576** [comment]
Sending jasp zip file separately.


[cid:4ff89a3f-5a62-44a1-9088-2586619cd02f]

Shane S. Kreuzer

Special Process Laboratory Technician

ASQ Certified Black Belt

Tel: +1 (803) 506-6586

E-mail: ***@***.******@***.***>

SKF Sumter, USA

925 Corporate Circle, Sumter, South Carolina – 29154

www.skf.com<http://www.skf.com/>, Facebook<https://www.facebook.com/SKFGroup>, LinkedIn<https://www.linkedin.com/company/skf>, Twitter,<https://twitter.com/skfgroup> Instagram,<https://instagram.com/skfgroup/> YouTube SKF Sumter, USA

This communication constitutes an electronic communication within the meaning of the Electronic Communication Privacy Act 18 U.S.C. 2510 et. Seq., and any unauthorized interception of this communication is strictly prohibited by law.  If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify the sender immediately by reply e-mail and delete the message and any attachments.



________________________________

**Comment by icekylin** [comment]
hi @WD4576 You can't attach the file to the email because GitHub will throw it away, you can click [here](https://github.com/jasp-stats/jasp-issues/issues/1611) and upload the file in the GitHub comment in your browser (please zip the file)

**Comment by WD4576** [comment]
[MSA Fault.zip](https://github.com/jasp-stats/jasp-issues/files/8049214/MSA.Fault.zip)
I zipped and did the drag and drop.  Hope this worked.

**Comment by WD4576** [comment]
Done.  Good luck.


[cid:fec9251b-6443-40c2-a046-c7e24bb3d9d3]

Shane S. Kreuzer

Special Process Laboratory Technician

ASQ Certified Black Belt

Tel: +1 (803) 506-6586

E-mail: ***@***.******@***.***>

SKF Sumter, USA

925 Corporate Circle, Sumter, South Carolina – 29154

www.skf.com<http://www.skf.com/>, Facebook<https://www.facebook.com/SKFGroup>, LinkedIn<https://www.linkedin.com/company/skf>, Twitter,<https://twitter.com/skfgroup> Instagram,<https://instagram.com/skfgroup/> YouTube SKF Sumter, USA

This communication constitutes an electronic communication within the meaning of the Electronic Communication Privacy Act 18 U.S.C. 2510 et. Seq., and any unauthorized interception of this communication is strictly prohibited by law.  If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify the sender immediately by reply e-mail and delete the message and any attachments.



________________________________

**Comment by juliuspf** [comment]
Sorry for the long wait. I downloaded your .jasp file, opened it with the latest jasp version (0.16.3), and refreshed the analysis. No error occurred. Could you confirm this on your machine?

**Comment by WD4576** [comment]
Confirmed -  Issue resolved.
Thank you,
Shane


[cid:ca61d8de-6948-48ff-82d9-cfd21b52e6a5]

Shane S. Kreuzer

Special Process Laboratory Technician

ASQ Certified Black Belt

Tel: +1 (803) 506-6586

E-mail: ***@***.******@***.***>

SKF Sumter, USA

925 Corporate Circle, Sumter, South Carolina – 29154

www.skf.com<http://www.skf.com/>, Facebook<https://www.facebook.com/SKFGroup>, LinkedIn<https://www.linkedin.com/company/skf>, Twitter,<https://twitter.com/skfgroup> Instagram,<https://instagram.com/skfgroup/> YouTube SKF Sumter, USA

This communication constitutes an electronic communication within the meaning of the Electronic Communication Privacy Act 18 U.S.C. 2510 et. Seq., and any unauthorized interception of this communication is strictly prohibited by law.  If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify the sender immediately by reply e-mail and delete the message and any attachments.



________________________________
