### ISSUE TITLE
[Bug]: Individual Unicode characters do not display properly in Plot

### ISSUE THREAD

**Issue by icekylin** [jasp-stats/jasp-issues#1615]
### JASP Version

0.16 (Nightly)

### Commit ID

3882b2dc5c519f0093bea7d427f3bd50ee060de2

### What OS are you seeing the problem on?

Windows 10 21H2

### Bug Description

Unicode Single-character of data labels do not display correctly on the x-axis of plots, such as in interval plots and Raincloud plots.
![unicode-character-single](https://user-images.githubusercontent.com/10348402/153743998-4e048ec2-575e-4567-9c44-d159f5c62a54.png)
[Unicode-lable-data.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/8055149/Unicode-lable-data.jasp.zip)

### Expected Behaviour

Unicode Single-character display correctly.

### Steps to Reproduce

1. see the example data set.(remove .zip suffix)
2. Add or delete the number of Chinese characters in the label.

you can paste in the editor with follow character example:
```
是
否
对
错
选中
未选中
已选中
```

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by icekylin** [comment]
@JorisGoosen @vandenman Could you please assess if this has an impact on pre-release versions, I'm guessing the impact is Low

**Comment by JorisGoosen** [comment]
@icekylin and @vandenman, this is kind of strange, because it looks like the font used in the plot is missing the glyph for that character. Which is weird because the font in the plot ought to be the same as the one in the table... Where we *do* see the glyph..

Impact is def low, but would still be good to fix this, but probably not in 0.16.1

**Comment by icekylin** [comment]
@JorisGoosen thanks.I use the Microsoft Yahei Chinese font as the default font for JASP on my computer, and this problem occurs with any glyph.
As you said, does this mean that we need to bundle an open source font in JASP, such as [Noto font](https://en.wikipedia.org/wiki/Noto_fonts).

**Comment by vandenman** [comment]
@JorisGoosen can you check the version of textshaping on the buildbot? I can replicate this exact issue, but once I updated textshaping to 0.3.6 the problem disappeared. Perhaps we've been bitten by https://github.com/r-lib/textshaping/issues/25. Either way, it's probably a good idea to ensure we're always using the latest version of ragg, textshaping, and systemfonts.

> As you said, does this mean that we need to bundle an open source font in JASP, such as [Noto font](https://en.wikipedia.org/wiki/Noto_fonts).

As far as I know, JASP already bundles Freesans for exactly this reason.

**Comment by JorisGoosen** [comment]
See: https://github.com/jasp-stats/INTERNAL-jasp/issues/263

If I go to university later this week I can check what buildbot uses, but @boutinb is there now right? Maybe he can check?

**Comment by JorisGoosen** [comment]
Oh wait, I can check the nightly of course

**Comment by JorisGoosen** [comment]
And @vandenman the version in the latest windows zip is indeed `0.3.5` so probably fixed just by running a new nightly right?

**Comment by amirmasoudabdol** [comment]
@JorisGoosen, yes, we can just install the latest version while we are preparing the `R.framework`! 👍🏼

**Comment by boutinb** [comment]
The Nightly on Windows is nearly ready. But the textshapping version comes from the required files, so I'm quite skeptical that this will help.

**Comment by JorisGoosen** [comment]
> The Nightly on Windows is nearly ready. But the textshapping version comes from the required files, so I'm quite skeptical that this will help.

I'll update jasp-required-files
