### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by gsunil97** [jasp-stats/jasp-issues#1616]
### JASP Version

0.16

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I open up a data set (csv) and am unable to perform any analysis since then. The JASP app closes. I was able to run analysis on this same data set last week, so I am a bit confused. Please assist, thanks!

### Expected Behaviour

I should have been able to conduct an analysis

### Steps to Reproduce

1. Open JASP application
2. Open up file
3. Click on descriptives
4. JASP automatically closes
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by icekylin** [comment]
Hi @gsunil97 Can you upload your data file  and log file (the location  which you can find in the preferences settings for log).
You may to compress both the log and data files into .zip file and upload them here.This will help developers analyze this problem.thanks.

**Comment by gsunil97** [comment]
Attached are the data and log files - thanks!


________________________________

**Comment by icekylin** [comment]
thanks,@gsunil97 but you can't attach the file to the email because GitHub will throw it away, you can click https://github.com/jasp-stats/jasp-issues/issues/1616 and upload the file in the GitHub comment in your browser (please zip the file)

**Comment by shun2wang** [comment]
Closed because necessary feedback required and inactive for a long time.
@gsunil97 Feel free to open it if the you think the problem is still happened.
