### ISSUE TITLE
[Bug]: Unexpected termination in jaspSem

### ISSUE THREAD

**Issue by MatowickiM** [jasp-stats/jasp-issues#1617]
### JASP Version

0.16

### JASP Module

jaspSem

### What analysis are you seeing the problem on?

Structural Equation Modelling

### What OS are you seeing the problem on?

Windows 11

### Bug Description

Hi,

during execution of my SEM model I recieved error with unexpected remination:
![image](https://user-images.githubusercontent.com/99728112/154048182-34bc7444-d359-4200-98f6-30a3471c896d.png)

Attatched I present my model file and source data.

Thanks in advance for any help,
Micha
[211214_MaaS_together_workingdata.zip](https://github.com/jasp-stats/jasp-issues/files/8068459/211214_MaaS_together_workingdata.zip)
l

### Expected Behaviour

I would expect to get the results of my model.

### Steps to Reproduce

1. 
2. 
3. 
...

### Log (if any)

```bash
doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

SEM(...)

.semPathPlot(modelContainer, dataset, options, ready)

.semCreatePathPlot(modelContainer[['results']][['object']][[1]], NULL, pcont, options, ready)

.suppressGrDevice(semPlot::semPaths(object = po, layout = 'tree2', intercepts = FALSE, reorder = FALSE, whatLabels = ifelse(options[['pathPlotPar']], 'par', 'name'), edge.color = 'black', color = list(lat = '#EAEAEA', man = '#EAEAEA', int = '#FFFFFF'), title = FALSE, legend = options[['pathPlotLegend']], legend.mode = 'names', legend.cex = 0.6, label.cex = 1.3, edge.label.cex = 0.9, nodeNames = decodeColNames(po@Vars$name), nCharNodes = 3, rotation = 2, ask = FALSE))

eval(plotFunc, parent.frame())

eval(plotFunc, parent.frame())

semPlot::semPaths(object = po, layout = 'tree2', intercepts = FALSE, reorder = FALSE, whatLabels = ifelse(options[['pathPlotPar']], 'par', 'name'), edge.color = 'black', color = list(lat = '#EAEAEA', man = '#EAEAEA', int = '#FFFFFF'), title = FALSE, legend = options[['pathPlotLegend']], legend.mode = 'names', legend.cex = 0.6, label.cex = 1.3, edge.label.cex = 0.9, nodeNames = decodeColNames(po@Vars$name), nCharNodes = 3, rotation = 2, ask = FALSE)
```

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by Kucharssim** [comment]
The discussion about this issue is here: https://github.com/jasp-stats/jasp-issues/issues/1629
