### ISSUE TITLE
[Bug]: Unicode characters do not display properly in anova Marginal Means table

### ISSUE THREAD

**Issue by shun2wang** [jasp-stats/jasp-issues#1618]
### JASP Version

0.16 (Nightly)

### Commit ID

3882b2dc5c519f0093bea7d427f3bd50ee060de2

### JASP Module

jaspAnova

### What analysis are you seeing the problem on?

Anova- Marginal Means 

### What OS are you seeing the problem on?

Windows 10 21H2

### Bug Description

Unicode character of data labels do not display correctly on Marginal Means table. it is different from https://github.com/jasp-stats/jasp-issues/issues/1615 ，seems some encoding error in this table view.

![2022-02-15 193251](https://user-images.githubusercontent.com/10348402/154054474-5ab2ba54-7086-4aad-ab7c-ff9fee53d234.png)

[Unicode-lable-data.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/8068642/Unicode-lable-data.jasp.zip)

### Expected Behaviour

Unicode Single-character display correctly.

### Steps to Reproduce

1. see the example data set.(remove .zip suffix)
2. Add Marginal Means table with Chinese characters label.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by vandenman** [comment]
Hmm I cannot replicate this:

![image](https://user-images.githubusercontent.com/21319932/155477486-78d408d5-7525-46f5-9cf0-5b554a5c2293.png)

Does it still happen on 0.16.1? Also, could it be that you accidentally uploaded the jasp file from another issue? This file contains a descriptives and independent samples t-test but no ANOVA.

@koenderks can you replicate this on Windows? Refreshing the file below should suffice.

[Unicode-lable-data_ANOVA.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/8130475/Unicode-lable-data_ANOVA.jasp.zip)

(rename and drop .zip)

**Comment by icekylin** [comment]
@vandenman I'm sure I can reproduce it on my windows. I just downloaded and flashed the file you provided and the problem persists.
I'm guessing this might have to be reproduced on windows in a Chinese locale.

**Comment by vandenman** [comment]
@icekylin thanks for checking! Let's hope @koenderks can verify that it's just windows being windows and not necessarily dependent on the locale (which would make it a bit more tedious to find out what is going on).

**Comment by koenderks** [comment]
I can reproduce this, but with different symbols:
![image](https://user-images.githubusercontent.com/25059399/155500845-eaf19f70-53c5-4e05-89a4-66dc95072eb9.png)
