### ISSUE TITLE
[Bug]: JASP won't open/run

### ISSUE THREAD

**Issue by denversaunders** [jasp-stats/jasp-issues#1620]
### JASP Version

0.14

### JASP Module

jaspDescriptives

### What OS are you seeing the problem on?

Linux on chromebook

### Bug Description

when i click the icon to run jasp it just keeps spinning

### Expected Behaviour

jasp opens

### Steps to Reproduce

1. click icon
2. 
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by denversaunders** [comment]
Updated. Tried to run off of Linux command, still not working

[==========] Ready
denversaunders@penguin:~$ ^[[200~flatpak run org.jaspstats.JASP~
-bash: $'\E[200~flatpak': command not found
denversaunders@penguin:~$ flatpak run org.jaspstats.JASP
bwrap: Can't mount proc on /newroot/proc: Operation not permitted
error: ldconfig failed, exit status 256
denversaunders@penguin:~$ flatpak install flathub org.jaspstats.JASP
Looking for matches…
Skipping: org.jaspstats.JASP/x86_64/stable is already installed
denversaunders@penguin:~$

**Comment by JorisGoosen** [comment]
I think this is the same problem as here: https://github.com/jasp-stats/jasp-issues/issues/1600

There are some workarounds there.

**Comment by denversaunders** [comment]
awesome! it worked! thank you so much
