### ISSUE TITLE
[Bug]: Error in ANOVA

### ISSUE THREAD

**Issue by irenesco** [jasp-stats/jasp-issues#1626]
### JASP Version

0.16

### JASP Module

jaspAnova

### What analysis are you seeing the problem on?

ANOVA

### What OS are you seeing the problem on?

Mac OS 10.15

### Bug Description

```
This analysis terminated unexpectedly.

Error in if ((misc$estType = 'pairs') && (paste(c('', by), collapse = ',') ≠ : missing value where TRUE/FALSE needed

Stack trace
withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

Anova(...)

Ancova(jaspResults, dataset = NULL, options)

.anovaContrastsTable(anovaContainer, dataset, options, ready)

cbind(contrastResult, confint(contrastResult, level = options$confidenceIntervalIntervalContrast)[, 5:6])

confint(contrastResult, level = options$confidenceIntervalIntervalContrast)

confint.emmGrid(contrastResult, level = options$confidenceIntervalIntervalContrast)

summary(object, infer = c(TRUE, FALSE), level = level, ...)

summary.emmGrid(object, infer = c(TRUE, FALSE), level = level, ...)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports
```

### Expected Behaviour

I have used this exact same dataset last year and conducted the same analysis, a one-way ANOVA (it is an in class exercise) but the output of the analysis did not appear this time.

### Steps to Reproduce

1. 
2. 
3. 
...

### Log (if any)

```bash
This analysis terminated unexpectedly.

Error in if ((misc$estType = 'pairs') && (paste(c('', by), collapse = ',') ≠ : missing value where TRUE/FALSE needed

Stack trace
withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

Anova(...)

Ancova(jaspResults, dataset = NULL, options)

.anovaContrastsTable(anovaContainer, dataset, options, ready)

cbind(contrastResult, confint(contrastResult, level = options$confidenceIntervalIntervalContrast)[, 5:6])

confint(contrastResult, level = options$confidenceIntervalIntervalContrast)

confint.emmGrid(contrastResult, level = options$confidenceIntervalIntervalContrast)

summary(object, infer = c(TRUE, FALSE), level = level, ...)

summary.emmGrid(object, infer = c(TRUE, FALSE), level = level, ...)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports
```

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JohnnyDoorn** [comment]
Hi @irenesco ,

Do you maybe have the data set that causes this issue? That way I can look where the error lies. If you rather send it by email, you can send it to j <dot> b <dot> vandoorn <at> uva <dot> nl.

Kind regards
Johnny

**Comment by irenesco** [comment]
Hi Johnny,

Thanks for your quick reply!
Attached is the dataset; none of the one-way ANOVAs with promotion as Fixed
Factor and n_donuts or spent_on_donuts or other variable calculated as part
of the exercise (e.g., profits etc.) worked.
Thanks,
Irene

**Comment by JohnnyDoorn** [comment]
Hi @irenesco ,

Sorry for the delay, I am just checking it now, but I don't see the file, so maybe it's best to just email it directly to me.

Kind regards
Johnny
