### ISSUE TITLE
[Bug]: JASP crashes when a filter is applied in a categorical variable in a spreadsheet.

### ISSUE THREAD

**Issue by koisa** [jasp-stats/jasp-issues#1636]
### JASP Version

0.16

### What analysis are you seeing the problem on?

After opening any file with qualitative-type variable, then crashes occur when try to apply filter on spreadsheet's categorical variable.

### What OS are you seeing the problem on?

Ubuntu 18.04 and Linux Mint 19.2 Tina, but NOT in Mac OSX 10.14.6. Not tested in Windows machines.

### Bug Description

JASP crashes systematically when trying to apply a filter to a categorical variable. After opening a data file, for instance, **Open** > **Data Library** > "**2. T-Tests**" and selecting "**Eye Movements**" file, JASP comes up with a spreadsheet with three columns: "ParticipantNumber", "Condition", and "CriticalRecall". By clicking the word "Condition" at the top of Condition variable column, a table will appear on top of the spreadsheet  listing the "Condition" variable categories, which are Fixation and Horizontal. Crashing will occur systematically right here if I  try (1) to apply filter in any categories, Fixation or Horizontal on the leftmost column, or (2) to push the "Reverse the order of all labels" option on the right-hand side of the filter window.

The problem also occur with version 0.16.1.  I did not test on JASP to 0.15 on Ubuntu 18.04, as I could not find a way to downgrade JASP using **flatpak** or other way around.  

_PS: This might be another issue, but I am experiencing incompatibility between JASP on Ubuntu 18.04  and some versions of NVIDIA driver. The nvidia-driver-510 (the latest one) allows me to use JASP, but JASP does not even launch with the nvidia-driver-460 when and as I need to use CUDA 11.2  GPU processing resources in Python._ 

### Expected Behaviour

Not to crash and apply the filter or reverse the order of categories.

### Steps to Reproduce

**Steps are already described in Bug Description, but reproduced here again**

1. Open data file, for instance, **Open** > **Data Library** > "**2. T-Tests**" and selecting "**Eye Movements**" file;
2. Click the word "Condition" at the top of Condition variable column;
3. Either (1) apply filter in either categories, Fixation or Horizontal on the leftmost column, or (2) click the "Reverse the order of all labels" option on the right-hand side of the window ==> **CRASH**.

...

### Log (if any)

```bash
Clarify me how to do so.
```

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JorisGoosen** [comment]
Is this perhaps the same bug as #1424 ?

If so the fix will come out soon but a workaround is available in the issue.

**Comment by koisa** [comment]
HI,

Not sure, but I can wait.

I have seen  #1424 <https://github.com/jasp-stats/jasp-issues/issues/1424> and
tried to apply the workaround, first checked for installed packages

$ flatpak list | grep org.kde
org.kde.Platform/x86_64/5.15 system,runtime
org.kde.Platform/x86_64/5.15-21.08 system,runtime
org.kde.Sdk/x86_64/5.15 system,runtime                 <=== It is here

then tried to issue the suggested correction, but I got an error message.

$ flatpak update --user --commit
4f232783b07952a4627a186c8020a362d2458c4b2d6046fbd0b43d3f44c551a7
org.kde.Sdk/x86_64/5.15
Looking for updates...
error: org.kde.Sdk/x86_64/5.15 not installed           <=== but got this
message?!

I did not know how to proceed.

Thank you for your attention.

**Comment by koisa** [comment]
Hi,

Going thru  #1424 <https://github.com/jasp-stats/jasp-issues/issues/1424> I
have been trying different combinations of workaround and for me

$ sudo flatpak update --commit
4f232783b07952a4627a186c8020a362d2458c4b2d6046fbd0b43d3f44c551a7
org.kde.Sdk/x86_64/5.15

solved the crashing problem!

Thank you again for your attention and the great work being carried out by
the JASP developers. I would like to let you know that I am a faculty of
Faculdade de Medicina at the Universidade de São Paulo, and we are using
JASP for teaching medical statistics to the second-year medical students
together with G*Power (
https://www.psychologie.hhu.de/arbeitsgruppen/allgemeine-psychologie-und-arbeitspsychologie/gpower
).

Koichi Sameshima (koisa)

**Comment by JorisGoosen** [comment]
> Hi, Going thru #1424 <#1424> I have been trying different combinations of workaround and for me $ sudo flatpak update --commit 4f232783b07952a4627a186c8020a362d2458c4b2d6046fbd0b43d3f44c551a7 org.kde.Sdk/x86_64/5.15 solved the crashing problem! 

Nice!

> Thank you again for your attention and the great work being carried out by the JASP developers. 

Our pleasure and we hope to keep going :)

> I would like to let you know that I am a faculty of Faculdade de Medicina at the Universidade de São Paulo, and we are using JASP for teaching medical statistics to the second-year medical students together with [G*Power]( https://www.psychologie.hhu.de/arbeitsgruppen/allgemeine-psychologie-und-arbeitspsychologie/gpower). 

I think I see your university on the map already: https://jasp-stats.org/teaching-with-jasp/ but still great to hear it is useful to others!
