### ISSUE TITLE
Copy-paste not working for Google docs

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-issues#164]
From the twitterverse (but also reported here earlier, I think):
Tables can be copied in Word/LibreOffice, but not in other programs, most notably Google docs.
It would be nice to see this fixed.

Cheers,
E.J.

**Comment by ScarabeeGris** [comment]
Hello, this JASP clipboard still doesn't work on Google docs. Any news of this issue ? Thanks

**Comment by TediJaho** [comment]
Hiii,  this issue still keeps happening on Google docs, any way to fix it?

**Comment by RensDofferhoff** [comment]
Ill take a look. It works on Firefox en chrome on Linux and Firefox on windows

**Comment by RensDofferhoff** [comment]
Fixed in https://github.com/jasp-stats/jasp-desktop/pull/5110.

A nightly will build later today.
