### ISSUE TITLE
[Feature Request]: second degree of freedom for Levene's test (independent sample t-test)

### ISSUE THREAD

**Issue by mservantufc** [jasp-stats/jasp-issues#1641]
### Description

Add second degree of freedom for Levene's test (independent sample t-test)

### Purpose

Levene's test is an ANOVA on transformed scores, but the second degree of freedom of this ANOVA is missing when computing Levene's test from the independent sample t-test menu

**Comment by EJWagenmakers** [comment]
Not sure I understand -- we are in the t-test scenario, so we know there are two groups. The t-test is also an ANOVA, but we don't give two degrees of freedom there either. I agree that Levene's test needs a second degree of freedom reported in case there are more than two groups. Am I missing something?

**Comment by EJWagenmakers** [comment]
OK, I checked and it is crrently suboptimal. In the t-test, the degree of freedom that is reported in the table is the one that does not seem relevant. We could change the report to that for the ANOVA, but I wonder whether for the t-test the Levene isn't better reported as a t-test (so t and one df, instead of an F). @JohnnyDoorn?
Below is a screenshot showing the t-test Levene (top) and the other for the ANOVA version (bottom):
![image](https://user-images.githubusercontent.com/8603015/156137093-553d803e-556f-491d-81b9-3906e6b2dc55.png)

**Comment by mservantufc** [comment]
Right, but in this case you need to be consistent and report a t statistic for Levene's test in the context of an independent samples t-test, not a F. JASP currently reports a F that should follow a FS distribution with two degrees of freedom.  
In addition, the degree of freedom of the t statistic corresponds to the second degree of freedom from the ANOVA, not the first degree of freedom (1) as currently reported.

**Comment by EJWagenmakers** [comment]
As an aside, @JohnnyDoorn, is there any reason for the fact that the df for the ANOVA Levene are reported as 1.00000 and 47.0000 instead of just 1 and 47? Let's fix this too now that we are at it.

**Comment by JohnnyDoorn** [comment]
The t-test Levene's test is now updated to use t and the more informative df. The ANOVA df's for Levene test can be a decimal number (not sure when exactly, maybe with a covariate, I just remember that it could not be an integer always). I can look into building in a flexible specification for this.

**Comment by AlexanderLyNL** [comment]
I think there's some misunderstanding, perhaps on my behalf. As far as I can see, the Levene's test in this context is about whether the variances are the same or not. In that case, the test statistic should be F(1, N-2), where N is total number of samples of the two samples combined, see https://en.wikipedia.org/wiki/Levene%27s_test.

**Comment by Kucharssim** [comment]
So in other words (if I follow @AlexanderLyNL's point correctly), instead of converting the Levene's test to a t-statistic (proposed here https://github.com/jasp-stats/jaspTTests/pull/121), the fix should just keep the F-test and add a column with the second degrees of freedom.

**Comment by FBartos** [comment]
I'm now reviewing the PR and I'm confused. There seems to be a t-statistic with two degrees of freedom now? 

![image](https://user-images.githubusercontent.com/38475991/172568634-d763d066-c3aa-45e1-a64c-c064093659e0.png)
