### ISSUE TITLE
[Feature Request]: Contrast-specific error term for planned contrats in the context of RM-ANOVA

### ISSUE THREAD

**Issue by mservantufc** [jasp-stats/jasp-issues#1642]
### Description

Contrast-specific error term for planned contrats in the context of  RM-ANOVA

### Purpose

Add an option to pool or not error term when computing within-subjects contrasts 

### Is your feature request related to a problem?

In the RM-ANOVA/Post Hoc Tests menu, the option to pool error term or not is available, but it is not for the RM-ANOVA/Contrasts menu

### Describe the solution you would like

Add a "Pool error term" option in the RM ANOVA/Contrasts menu

### Additional context

Currently, JASP computes linear contrasts for RM-ANOVA using a pooled error term, but this approach is not recommended (e.g., Maxwell, Delaney, & Kelly, 2018). The mean-square error from the full design may be a poor estimate of the error term when just two levels of the independent variable are compared, because any degree of violation of the sphericity assumption will make the error term too small or two large for some comparisons (Boik, 1981). I am confused because the option to pool or not the error term is available for post-hoc tests in the RM-menu, but not for contrasts. What is the rationale behind this choice ? 
Best,
Mathieu

**Comment by tomtomme** [comment]
@mservantufc 
I can confirm that JASP does not implement this yet. But I am sure it is still on the radar of the dev team. I can give no timeframe however. Sorry.
