### ISSUE TITLE
[Bug]: Very slow performance

### ISSUE THREAD

**Issue by amsa1234** [jasp-stats/jasp-issues#1643]
### JASP Version

0.16.1

### What analysis are you seeing the problem on?

General performance

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I've noticed with both JASP 16.0 and 16.1 that performance is extremely slow across all or most modules and features. Even enabling something like "Descriptives" in a t-test is taking quite a while. Trying to select a repeated measures ANOVA briefly results in a "Not responding" grey-out. In general, the effect appears long after the click (and in the case of the repeated measures ANOVA, doesn't seem to work at all). 

### Expected Behaviour

Smooth operation of JASP: the effect should immediately follow the click. 

### Steps to Reproduce

None - I wonder if others are facing this problem? I'm working with a fairly small data set (just 400 participants or so, and not many columns either). I apologise that I haven't included any images, logs, or files. 

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JorisGoosen** [comment]
Is your problem perhaps similar to https://github.com/jasp-stats/jasp-issues/issues/1490 @amsa1234  ?

If so a fix is coming out soon but it requires a bit of testing. 
You could help me out if you download: https://static.jasp-stats.org/Nightlies/WindowsZip/JASP-nightly-development-918b55131640ba14c576f258c5bbc64ef69d1c31.zip 
Then unpack it and click `jasp.exe`, it needs to fix some stuff at startup (it will tell you).

Does that one run faster?

**Comment by amsa1234** [comment]
Thank you very much. I tried this one, and yes, it does run faster.
However, see the following:

1) Before loading, it gives this error message:"It seems the bundled module
jaspVisualModeling wasn't correctly installed, and thus cannot be loaded.
If you installed this version of JASP via an official installer let the
JASP team know". However, if I click the "x" on this message, JASP still
opens, and when it does, it runs faster and smoothly.

2) More importantly, JASP spontaneously shuts down with no error message
during use. Specifically, this has happened when I try to add information
on the second factor in the repeated measures ANOVA.

Many thanks!

Amar

**Comment by JorisGoosen** [comment]
> Thank you very much. I tried this one, and yes, it does run faster. However, see the following: 1) Before loading, it gives this error message:"It seems the bundled module jaspVisualModeling wasn't correctly installed, and thus cannot be loaded. If you installed this version of JASP via an official installer let the JASP team know". 

Yeah did you maybe double click JASP.exe twice before it opened? If so, no worries, the next time you start JASP visual modelling will probably be there.

> However, if I click the "x" on this message, JASP still opens, and when it does, it runs faster and smoothly.

Awesome

> 2) More importantly, JASP spontaneously shuts down with no error message during use. 
> Specifically, this has happened when I try to add information on the second factor in the repeated measures ANOVA. 

Yes, this is the version currently in development and my colleague just fixed it. There might be more of these bugs, but hopefully not.

>Many thanks! Amar

You are very welcome!

**Comment by amsa1234** [comment]
Thanks Joris! So, just to confirm, what should I do for the ANOVAs to run
smoothly?

Amar

**Comment by JorisGoosen** [comment]
Well, unless you want to learn how to compile software from source code I think you have two options:
- Use the released version of JASP that is slow
- Wait until I build a new nightly

Now the new nightly will only be built on thursday probably, and otherwise the new version of JASP is coming out in just a few weeks.

**Comment by amsa1234** [comment]
Thanks! (and as always, thanks for the amazing work you do on JASP!).

**Comment by JorisGoosen** [comment]
https://static.jasp-stats.org/Nightlies/ if you want to be able to use ANOVA you can get one of the newest `stable` nightlies.
