### ISSUE TITLE
[Bug]: Cohen's D not appearing in ANOVA post hoc

### ISSUE THREAD

**Issue by kristen-j-black** [jasp-stats/jasp-issues#1645]
### JASP Version

0.14

### JASP Module

jaspAnova

### What analysis are you seeing the problem on?

One-way ANOVA

### What OS are you seeing the problem on?

Windows & Mac

### Bug Description

I supervise a lab where students use JASP. Many students were having an issue where the Cohen's D column was blank for the post-hoc tests for one-way ANOVA. 

### Expected Behaviour

Cohen's D values should appear in the column

### Steps to Reproduce

I have not had the problem myself, but several students in the lab have, on both mac and PC computers

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by kristen-j-black** [comment]
Thanks for the response! I did check with a few students and it seems like this issue showed up with version .16 as well. It was several different computers where the column for Cohen’s d would appear in the output, but the actual values were not provided.

**Comment by JohnnyDoorn** [comment]
Hi @kristen-j-black ,

Do you maybe have a data set where this is the case, that you could email me? That way I can have a closer look
You can send it to j.b.vandoorn <at> uva.nl

Kind regards
Johnny
