### ISSUE TITLE
[Bug]: GLMM contrasts problem

### ISSUE THREAD

**Issue by jvicensb** [jasp-stats/jasp-issues#1648]
### JASP Version

0.16.1

### JASP Module

jaspMixedModels

### What analysis are you seeing the problem on?

GLMM

### What OS are you seeing the problem on?

MacOS Catalina

### Bug Description

When trying to specify the contrasts in the GLMM, it appears the bug:

Error in contrast.emmGrid(emm, contrs, adjust = if (type == "GLMM") selectedAdjustment) : Nonconforming number of contrast coefficients

### Expected Behaviour

When running a LMM, for continuous data, the contrasts can be set by -1, 1. I am trying to do the same and it pops the bug. Maybe I am not doing it right though...

### Steps to Reproduce

1. Mixed models
2. GLMM
3. Dependent variable "ordinal variable"; 2 nominal independent variables as fixed effects; 1 nominal independent variable as random effect (ID)
4. Estimated marginal means 5.Specify contrasts...
<img width="1216" alt="Screenshot 2022-03-07 at 17 10 07" src="https://user-images.githubusercontent.com/80293085/157072606-f7cecebd-542d-463d-8c5d-2065db260167.png">

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by jvicensb** [comment]
Dear FBartos,

is it possible to solve the issue I recently raised? Or it is very complex?

Best regards and thank you for your work in advance,

Jordi

**Comment by FBartos** [comment]
Dear Jordi,

Thanks for reporting the error and sorry for the late response (I missed the original notification).

I'm having trouble reproducing the issue with my debugging data set, could you please save the JASP analysis that leads to the error as a .JASP file and send it to my email (f.bartos96@gmail.com)? There might be some non-standard formatting that is causing the issue and I'm having trouble reproducing locally.

Best,
Frantisek

**Comment by jvicensb** [comment]
Dear Frantisek,

first of all, thank you for your help and your terrific work helping the community. It is admirable the way you put it out.

Second, please find attached the file. I hope you can detect what mistake I made. If you need anything else just let me know. 

And again, thank you for your help.

Best regards,


Jordi

**Comment by jvicensb** [comment]
Forgot to attach the file,


Jordi

**Comment by juliuspf** [comment]
@jvicensb could you try to attach the file again?

**Comment by FBartos** [comment]
I actually got the file by email at the end. We know about the issue - caused by the contrasts widget and filtering factor levels in data editor, and Bruno should have a fix for the next release.

**Comment by jvicensb** [comment]
Hi Julius and Frantisek,

exactly, Frantisek gave me the “quick fix” for the bug, and told me about next release may cover this problem.

Thank you for your great support, you are awesome.

Best regards,

Jordi
