### ISSUE TITLE
[Bug]: Chi-square goodness-of-fit test: when specifying H0, proportions are expected, but user needs to provide counts 

### ISSUE THREAD

**Issue by mservantufc** [jasp-stats/jasp-issues#1651]
### JASP Version

0.16.1

### JASP Module

jaspFrequencies

### What analysis are you seeing the problem on?

Multinomial test

### What OS are you seeing the problem on?

Windows 10

### Bug Description

Menu multinomial test -->expected proportions (chi-2 test). It looks like JASP expects counts for H0, not probabilities (which is confusing because it's clearly written "expected proportions". Either modify to "expected counts" or expect probabilities when specifying H0.

### Expected Behaviour

H0 should accept probabilities, not counts (or you guys have to change "expected proportions" into "expected counts")

### Steps to Reproduce

1-load text file below
[marital_status_datafile.txt](https://github.com/jasp-stats/jasp-issues/files/8216061/marital_status_datafile.txt)
2-menu Multinomial test, reproduce screen capture below
![Capture](https://user-images.githubusercontent.com/45162680/157477686-04dd0eca-3228-4e72-ba9f-3fd4894a8d9a.PNG)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by EJWagenmakers** [comment]
If I'm not mistaken, whatever is entered is renormalized to add to 1. This is often more convenient. If the user want to specify proportions directly this is possible. Please reopen if this is not the case. The helpfile should mention this of course (on my cell, so can't check)

**Comment by mservantufc** [comment]
That's the issue EJ. You can't specify proportions (well you can but the chi-square test is incorrect. I reopen the issue.

**Comment by EJWagenmakers** [comment]
Oh that is strange but should be a straightforward fix, because anything in there should just be renormalized. I'll assign Don and Simon to see how they feel about this.

**Comment by Kucharssim** [comment]
Continuing this discussion in https://github.com/jasp-stats/jasp-issues/issues/1652
