### ISSUE TITLE
[Bug]: Chi-square goodness-of-fit test: when specifying H0, proportions are expected, but user needs to provide counts

### ISSUE THREAD

**Issue by mservantufc** [jasp-stats/jasp-issues#1652]
### JASP Version

0.16.1

### JASP Module

jaspFrequencies

### What analysis are you seeing the problem on?

chi-square test of independence

### What OS are you seeing the problem on?

Windows 10

### Bug Description

see issue #1651. EJ closed it, because he thought user could specify both proportions or counts for H0. However, specifying proportions returns an incorrect chi-square (and user cannot enter proportions with more than one decimal). Again, this is confusing because the menu clearly states "Expected proportions", but JASP expects counts. 

### Expected Behaviour

H0 should accept probabilities, not counts (or you guys have to change "expected proportions" into "expected counts")

### Steps to Reproduce

1-load text file below
[Dancing cats.txt](https://github.com/jasp-stats/jasp-issues/files/8222178/Dancing.cats.txt)
-menu Multinomial test, reproduce the two screen captures below
correct test:
![image](https://user-images.githubusercontent.com/45162680/157635796-b09afc45-16f9-4ed4-8aae-91c25b2f3f50.png)
incorrect test:
![Capture](https://user-images.githubusercontent.com/45162680/157637411-b22fdb21-d739-40ff-aae6-1f86a27dbe1c.PNG)
st:

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by Kucharssim** [comment]
Dear @mservantufc,

thank you for submitting the issue.

Just as a side-note, it is possible to re-open a closed issue instead of opening a new one. So I now re-closed the old issue that EJ reopened so that it's clear we continue this discussion here.

As for your screenshot of the "incorrect test": I fail to see why it is incorrect. You defined your expected proportion of 'widowed' category as 0.0, but you found 2 cases of 'widowed' in the data. So the result seems correct in this case. I have been playing around further with the analysis, but I cannot get it to return incorrect results.

I see the point that limiting the input to be defined within one decimal is too restrictive if one wants to specify the hypothesis as proportions. I will look into loosening up this restriction.

I also see a problem that if you select `Descriptives` and `Counts`, then the column `Expected Counts` may not be correct, as the output is always shown as integers, even though the expected counts may not be integers. That should be fixed as well.

**Comment by Kucharssim** [comment]
Yes, I will make sure you can specify it as you have shown here :)

As a workaround in the current version, you can just multiply the proportions by some constant (e.g., 100) to obtain numbers that you can input while preserving their proportionality. For example, 10.1, 56.1, 31.3, 2.5 should give you the correct results.

**Comment by AlexanderLyNL** [comment]
@Kucharssim Could you also check this on Qt 6.2?

**Comment by hcp4715** [comment]
Dear @AlexanderLyNL,

I have a side question: how to conduct Bayesian multinomial test (goodness-of-fit test) in R? I clicked the "?" icon of the analysis and it says the related R packages are "ggplot" and "stats". It's confusing to me because I didnot find a function for Bayesian multinomial test  in that "stats" package . 

Best,
Chuan-Peng

**Comment by AlexanderLyNL** [comment]
Hi Chuan-Peng, 

You're right. The help file is incomplete, it should also mention the BayesFactor package and Gunel and Dickey (1974). I'll make sure these references are added. 

Cheers,
Alexander

**Comment by hcp4715** [comment]
hi, @AlexanderLyNL,

Thanks for your reply. I am still a bit confused about the calculation of BF for the multinomial test. 

The reference you provided, https://psyarxiv.com/bux7p/, is using sampling method, but in the script, this method is not used. Instead, the analytical method is used.

```
  # expected counts under the null hypothesis (Binomial median)
  expected <- setNames(sum(counts)*thetas, names(counts))

  # compute Bayes factor
  lbeta.xa <- sum(lgamma(alphas + counts)) - lgamma(sum(alphas + counts))
  lbeta.a  <- sum(lgamma(alphas)) - lgamma(sum(alphas))

  # in this case, counts*log(thetas) should be zero, omit to avoid numerical issue with log(0)
  if (any(rowSums(cbind(thetas, counts)) == 0)) {
    LogBF10 <- (lbeta.xa-lbeta.a)
  } else {
    LogBF10 <- (lbeta.xa-lbeta.a) + (0 - sum(counts * log(thetas)))
  }
```

Also, I am quite confused about this algorithm (maybe I am wrong). I checked many online resources to understand this part, but many of them showed that the conjugate prior for multinomial is Dirichlet Distribution, instead of multivariant Beta function, which is used here ` sum(lgamma(alphas)) - lgamma(sum(alphas))`

**Comment by AlexanderLyNL** [comment]
Hi Chuan-Peng, 

The reference provides two parts. The first part is concerend with the comparison as in JASP, whereas the second part is concerned with order restrictions. The first part is solved analytically as in JASP. 

Regarding the computations, the Dirichlet distribution has a Dirichlet function as normalising constant. This is the same as a multivariable beta function, see https://en.wikipedia.org/wiki/Dirichlet_distribution#Probability_density_function

A multinomial test can be used to compare observed to expected frequencies, whereas a contingency table compares the row and column allocations. Hence, the difference in results. 

Cheers,
Alexander

**Comment by hcp4715** [comment]
Hi, @AlexanderLyNL,

Thanks a lot for pointing that part out, very helpful.

A follow-up question about the multinomial test and contingency table. If my research question is whether a sample is a representative sample of a population in terms of age (after I divide the whole population into several age bins), and I have the proportion data of each age bin from the population and the proportion data from the sample, which one is more appropriate?

I really appreciate any help you can provide.

Best
Chuan-Peng

**Comment by AlexanderLyNL** [comment]
Hi Chuan-Peng, 

A multinomial analysis with a specific null hypothesis (the population proportions) will do. 

Cheers,
Alexander

**Comment by hcp4715** [comment]
Thanks a lot, @AlexanderLyNL, your replies make my day!

**Comment by hcp4715** [comment]
Hi, @AlexanderLyNL,

I have another follow-up question about the Bayesian multinomial test: if there is any index that is equivalent to the effect size? For example in the Bayesian t-test, we can estimate Cohen's *d*. With effect size, we can also do simulations to estimate the sample size, etc.  

In the Bayesian multinomial test, we are testing whether the observed counts deviate from an expected one, but how to quantify the deviation? Is it also related to the N we have? For example, in my case, the counts are converted to percentage data, which means the sum of the data is always 100. In this case, how much deviation from the expected distribution is big enough for me to conclude that the observation is indeed not drawn from the expected multinomial distribution? 

Again, any suggestions are highly appreciated!

Best
Chuan-Peng

**Comment by AlexanderLyNL** [comment]
Hi Chuan-Peng, 

My first search didn’t lead to an obvious effect size measure for multinomial models. If I were to create one, then I would define the effect size as the distance between two vectors associated to the population and the observed frequencies. 

For K number of population frequencies p_{1}, p_{2}, .., p_{K-1}, p_{K} this would be a K-1 dimensional vector g such that 

	g_{i} = \log( p_{I} / p_{K})

Thus, g is the vector 

	g = (\log(p_{1} / p_{K}), \log(p_{2} / p_{K}), …, \log(p_{K-1} / p_{K}))

Similarly, for observed frequencies \hat{p}_{1}, \hat{p}_{2}, …, \hat{p}_{K-1}, \hat{p}_{K} I would create an analogous K-1 dimension vector \hat{g} such that 

	\hat{g}_{i} = \log( \hat{p}_{i} / \hat{p}_{K})

Thus, \hat{g} is the vector 

	\log(\hat{p}_{1}/ \hat{p}_{K}), log(\hat{p}_{2}/ \hat{p}_{K}), …, log(\hat{p}_{K-1}/ \hat{p}_{K})

The observed effect size would then be the distance between g and \hat{g}, which is defined as

	\sqrt{\sum_{i=1}^{K-1} (\hat{g}_{i} - g_{i})^{2}}

An alternative would be to use vectors m of the form 

	m_{i} = \sqrt{p_{i}}

instead. Whether this truly makes sense needs researching though. 

Cheers,
Alexander

**Comment by hcp4715** [comment]
Hi, @AlexanderLyNL 

Thanks for your quick response. I also searched a bit, and one [discussion on StackExchange](https://stats.stackexchange.com/questions/4044/measuring-the-distance-between-two-multivariate-distributions) suggested [Bhattacharyya distance](http://en.wikipedia.org/wiki/Bhattacharyya_distance). 

The difficulty with these distance metrics is how to use them for sensitivity analysis. That is, how to systematically change these distances and check how it will affect the resulting BF. Do you have any suggestions?

Best
Chuan-Peng

**Comment by AlexanderLyNL** [comment]
A first step involves some simulations, examples, and then some mathematics I reckon. I'm not so convinced by the Bhattacharyya distance, but perhaps I'm missing something. Nonetheless, I wouldn't discard it in an initial study. KL might be better and I'm still more convinced about the g vectors I recommended. The m that I suggested boils down to Hellinger distance.

**Comment by hcp4715** [comment]
Hi, @AlexanderLyNL 

Thanks for your response, I am still trying to understand what you suggested above.

When I was looking into the R code behind the Bayesian multinomial test, I suspect that one line of code might be only applicable to the default prior of Dirichlet, i.e., `$\alpha_1 = \alpha_2 = ... = \alpha_K = 1`. 

The line of code I am referring to is:
https://github.com/jasp-stats/jaspFrequencies/blob/d48babf63b14526abaf2c208c8ae769801b6d4db/R/multinomialtestbayesian.R#L402

The code itself is:

`LogBF10 <- (lbeta.xa-lbeta.a) + (0 - sum(counts * log(thetas)))`

The equation is (if I do it correctly): 

```
$log(BF_{e0}) = log(Beta(x + \alpha))- log(Beta( \alpha)) + (\sum_{k=1}^k log(\theta_k *(\alpha_{k}-1)) - \sum_{k=1}^k log(\theta_k * (x_k + \alpha_{k}-1)))$
```

If the `(0 - sum(counts * log(thetas)))` part is the code for `$(\sum_{k=1}^k log(\theta_k *(\alpha_{k}-1)) - \sum_{k=1}^k log(\theta_k * (x_k + \alpha_{k}-1)))$`, then it applies only to the special case when `$\alpha_k$` equals to 1. 

Of course, I may miss something in the code. If this is the case, please let me know what I missed.

Best
Chuan-Peng
