### ISSUE TITLE
[Bug]: Data View-After removing the label the cell show blank 

### ISSUE THREAD

**Issue by shun2wang** [jasp-stats/jasp-issues#1655]
### JASP Version

0.16.1 (Nightly)

### Commit ID

a7d4928c2decd3e28bff64c333db7ec3b78eee52

### What OS are you seeing the problem on?

Windows 10 21H2

### Bug Description

After editing the value label, if we remove the label, the cell appears blank, which will confuse the user that the data has been cleared. Please see the examples and animations I have provided 
![JASP_xDkJRmqli0](https://user-images.githubusercontent.com/10348402/158051752-bc7a19df-17c9-443a-8a8c-24684335e6f6.gif)

[plot error.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/8239184/plot.error.jasp.zip)

### Expected Behaviour

should show the value instead of blank.

### Steps to Reproduce

1. add labels on values
2. remove the values

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by icekylin** [comment]
@JorisGoosen Perhaps this problem should be paid attention to during the development of datamode, do you think so?

**Comment by JorisGoosen** [comment]
Well, im not sure if this really is a problem actually?
Maybe there are good reasons to have an empty label?

And of course, you would have to specifically enter an empty label and then not do anything about it to get into this situation.

What would the alternative be?
- Getting a warning whenever you leave it empty: which would be kind of annoying I guess
- Not being allowed to leave it empty, switch back to previous label or something, but what if you want it empty?

Currently we allow labels to be the same and this merges them, so having a bunch of empty labels would just mean, merge them all and give them label `""`. Which could be valid?

![image](https://user-images.githubusercontent.com/29062713/161722176-31555739-47b2-47e5-b382-927625bb981b.png)

**Comment by icekylin** [comment]
Ok thanks for your reply. I still think that a blank display would be considered "missing glitch" or "unreasonable" by the user,someone also raised this doubt to me

>Getting a warning whenever you leave it empty: which would be kind of annoying I guess

- Yes, I agree that frequent warnings should not be

>Not being allowed to leave it empty, switch back to previous label or something, but what if you want it empty?

- For labels deleted by the user themselves, it should be replaced with the displayed data value(Even mixed display value and label, I can understand that **the value is the label at this time**.). 
- empty label is not a good idea for a plot at least.

![image](https://user-images.githubusercontent.com/10348402/161735307-9e288606-bb72-41d2-b06a-2e1a87a4ccc3.png)

- I investigated the performance on SPSS and here is an example,They replaced the value with the displayed label that was not defined or deleted by the user:
![image](https://user-images.githubusercontent.com/10348402/161733849-237fa306-69d8-47e4-91d8-af5e520c718a.png)

**Comment by JorisGoosen** [comment]
> For labels deleted by the user themselves, it should be replaced with the displayed data value(Even mixed display value and label, I can understand that the value is the label at this time.).

Yes, this does seem like the best solution.

We just had a meeting and we talked about the fact that having duplicate labels could be a problem (or at least is unwanted) as well. And that could be triggered by using the value (if another label has the same label), but in that case at least there *is* a label.

I think this could be fixed relatively easy so maybe I can indeed take it with in data editing version.
