### ISSUE TITLE
[Feature Request]: Frequentist Generalized Linear Models

### ISSUE THREAD

**Issue by fqixiang** [jasp-stats/jasp-issues#1656]
### Description

A module for frequentist genearlized linear models is needed.

### Purpose

To extend the current regression and logistic regression options to other distributions and links.

### Use-case

Many.

### Describe the solution you would like

A sub-module added to the current Regression module.

**Comment by tomtomme** [comment]
Maybe a stupid question: Is this not what the visual modeling module provides?

**Comment by fqixiang** [comment]
@tomtomme Good question! You're right that the visual modelling module does provide parameter estimates for some generalized linear models, but the focus of that module is on visually inspecting patterns in the data (check out https://jasp-stats.org/2020/04/21/the-visual-modeling-module/). Furthermore, in terms of actual GLM analyses, the visual modelling module is very limited: it doesn't give you the choice of link functions, model comparison, model goodness-of-fit stats, p-values, residual analyses, outlier detection, just to name a few. This is why we need a proper GLM module on its own. The same logic applies to the mixed model and linear model options available in the visual modelling module.

**Comment by Kucharssim** [comment]
@juliuspf Qixiang is working on it himself
