### ISSUE TITLE
[Bug]: Unable to run JASP on Chromebook

### ISSUE THREAD

**Issue by gridppbonvert** [jasp-stats/jasp-issues#1657]
### JASP Version

0.16.1

### What OS are you seeing the problem on?

Chromebook Version 99.0.4844.57 (Official Build)(32-bit)

### Bug Description

Installed JASP as described using Linux Development and installation completed. When using command sudo flatpak run org.jaspstats.JASP, this error message appears: "error: app/org.jaspstats.JASP/aarch64/master not installed".
Kindly assist. Thanks.

### Expected Behaviour

Not running

### Steps to Reproduce

Same as above

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JorisGoosen** [comment]
if you use `sudo flatpak` it runs the flatpaks installed to `system` and if `flatpak` those installed to `user`.

So try running `flatpak run org.jaspstats.JASP` if it is actually installed to `user`.
If that doesnt help try `flatpak --list` and post the output here.
