### ISSUE TITLE
[Feature Request]: Adding Krippendorff's alpha

### ISSUE THREAD

**Issue by evanmiltenburg** [jasp-stats/jasp-issues#1665]
### Description

It would be nice to have not just Cohen's and Fleiss' kappa, but also Krippendorff's alpha. The latter is much more versatile than the former two.

### Purpose

Krippendorff's alpha is used to compute inter-rater reliability (AKA inter-annotator agreement or inter-coder reliability). The advantage of this approach is that it supports categorical, ordinal, interval and ratio type data and also handles missing data.

### Use-case

Alpha is one of the core metrics used in quantitative content analysis and other annotation tasks.

### Describe the solution you would like

I would like to see Krippendorff's alpha as an option in the reliability menu.

### Describe alternatives that you have considered

There is a package in R or a macro in SPSS, but it would be nice to have this in JASP.

### Additional context

This was already mentioned in #310 but that request was closed after Kappa was added.

**Comment by EJWagenmakers** [comment]
Definitely! Did we not already have this, @juliuspf ?

**Comment by juliuspf** [comment]
The request has come up before, if I recall correctly. I cannot find the corresponding issue though. Anyways, yes it would be a nice addition and should be possible to implement without too much trouble.

**Comment by evanmiltenburg** [comment]
Thanks for the positive response!

> The request has come up before, if I recall correctly. I cannot find the corresponding issue though.

#310 is the only issue I could find (it misspelled Krippendorff's name, which is why it is harder to find).

Thinking about this some more, it would be great to also include some measures from the table on [this Wikipedia page](https://en.wikipedia.org/wiki/Precision_and_recall). E.g. precision (AKA positive predictive value), recall (AKA sensitivity), and the F1-score. These are used quite often (in the medical literature, but also in machine learning) and relatively easy to implement; the only issue is that one should specify which column contain the ground truth/reference data.

**Comment by EJWagenmakers** [comment]
About the PPV, sensitivity etc., note that we offer this functionality in the Learn Bayes module -> Binary classification. See also https://jasp-stats.org/2021/09/28/binary-classification/
