### ISSUE TITLE
[Feature Request]: Add REML

### ISSUE THREAD

**Issue by pvanbaarlen** [jasp-stats/jasp-issues#1669]
### Description

REML analysis via JASP

### Purpose

carry out REML

**Comment by Kucharssim** [comment]
Hello @pvanbaarlen,

In case this is about mixed models, I believe REML is already used under some settings of the analyses. Perhaps @FBartos could provide more details.

If this is not about mixed models, could you be more specific please?

**Comment by pvanbaarlen** [comment]
Dear Simon,

Thank you very much for responding to my question!

Indeed, REML facilities analysis of linear mixed models and estimates variance components; REML is residual maximum likelihood, sometimes also called restricted maximum likelihood.

It would be great to know if REML is somewhere hidden in your extensive JASP options,

With regards,
Petre

**Comment by FBartos** [comment]
Hi Petre,

REML is the default method for estimating LMM when "Model terms" are tested with either the Satterwaite or Kenward-Roger method. You can set and see the additional information about the model in the highlighted options on the screenshot.

![image](https://user-images.githubusercontent.com/38475991/162380666-3abdfa8d-3a62-495a-a3f7-2d64e8b67850.png)

Cheers,
Frantisek

**Comment by pvanbaarlen** [comment]
Dear Frantisek,
Thank you very much! that's extremely useful to know, I'm very happy with that. Best wishes, Peter
