### ISSUE TITLE
[Feature Request]: Computed variable based on filtered (subset of) data

### ISSUE THREAD

**Issue by dmirkov** [jasp-stats/jasp-issues#1672]
### Description

Calculation of new variable only on filtered data

### Purpose

Sometimes we need to calculate a new variable (e.g., Z-values) for a subset of data. However, the "Calculator" takes into account all data from the whole data set. 

### Use-case

Standardizing data

### Is your feature request related to a problem?

I have a set of data and want to calculate Z value only for the subset (which i get after applying a filter)

### Describe the solution you would like

It would be nice that when calculating a subset of data, Z-values are based on mean and SD from the filtered data.

### Describe alternatives that you have considered

At the moment, filtered data can not be exported. This would be an indirect solution to the problem. After exporting the filtered data and therafter imorting it again as a new file with exported subset of data would allow to calculate the Z value properly

**Comment by juliuspf** [comment]
HI @dmirkov. Thank you for the request. You are raising an interesting point. I wonder how feasible it is to implement @vandenman ?

**Comment by dmirkov** [comment]
Hi 😊 Thanks!

Get Outlook za Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tomtomme** [comment]
@dmirkov 
this is in developement, see https://github.com/jasp-stats/jasp-issues/issues/2553

so closing as duplicate.
