### ISSUE TITLE
[Bug]: Issue with Equality of Variances within the Independent Ttest

### ISSUE THREAD

**Issue by lipniskiss** [jasp-stats/jasp-issues#1676]
### JASP Version

0.16

### JASP Module

jaspTTests

### What analysis are you seeing the problem on?

Equality of Variances within the Independent Ttest

### What OS are you seeing the problem on?

Windows 11

### Bug Description

Error in .ttestindependentEqVarFill(equalityVariance, dataset, options): object 'result' not found - this error occurred when I selected "equality of variances" when trying to set up my t-test.
[Food Intake_Ttest Bug.zip](https://github.com/jasp-stats/jasp-issues/files/8403217/Food.Intake_Ttest.Bug.zip)
<img width="960" alt="image" src="https://user-images.githubusercontent.com/102876330/161397393-e7e25da5-d149-4a71-b3fa-c5937803cefc.png">

### Expected Behaviour

I should be able to select 'equality of variances' to run my Ttest?

### Steps to Reproduce

1. Select: Independent Samples T-test
2. Select: Student
3. Select: Group 1 'does not equal' Group 2
4. Select: Normality
5. Select: Equality of Variances
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by lipniskiss** [comment]
Never mind! I spoke with my advisor and discovered the problem - my data set was not set up correctly to run the test. There was no variances in my data, so it could do the equality of variances...

**Comment by boutinb** [comment]
We can close this issue I think
