### ISSUE TITLE
An(c)ova introduces side effects for Regression

### ISSUE THREAD

**Issue by KelvinBalcombe** [jasp-stats/jasp-issues#1677]
### JASP Version

0.16

### JASP Module

jaspAnova, jaspRegression

### What analysis are you seeing the problem on?

Linear Regression

### What OS are you seeing the problem on?

Windows 10

### Bug Description

1) Run a classical linear regression including a categorical variable within Factors
2) Click on classical ANOVA (you do not actually have to specify a model)
3) Specify the same classical linear regression as in 1)  - The effect coding for the Factor has changed along with the labeling

### Expected Behaviour

Running an ANOVA should not change the effects coding in a linear regression unless you explicitly want it to.

### Steps to Reproduce

1.  Load any file with a continuous response variable and a categorical factor variable (e.g. Heart Rate.csv data library 3 ANOVA)
2.  Run a classical linear regression specifying the categorical variable within the factor box (e.g. heart rate on Gender as a Factor)
3. Click on Classical ANOVA
4. Start another linear regression and Re-Run the same classical linear regression as in 1-2
5. Observe the change to the effects coding of Gender along with its label

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by AlexanderLyNL** [comment]
linear regression default dummy coding, in jasp we use a different coding for contrasts. Globally the options variable gets changed.
