### ISSUE TITLE
[Bug]: Mardia coefficient not showing in SEM output

### ISSUE THREAD

**Issue by ctalerico2018** [jasp-stats/jasp-issues#1680]
### Description

Blank Mardia Cause annotation

### Purpose

Understand why the coefficient is not reporting

### Use-case

I have an output without a Mardia coefficient and I don't know what is causing it, if its a bug or something wrong with my data-set

### Is your feature request related to a problem?

yes, I am not currently getting an output and I have no errors reported.

### Describe the solution you would like

A means to interpet why the software is not reporting the test.

### Describe alternatives that you have considered

utilizing other software, but I much prefer JASP because it is otherwise much more user friendly.

**Comment by juliuspf** [comment]
Hi @ctalerico2018. Thank you for making the request. Can you tell me a bit more about this feature? What analysis is it related to?

**Comment by ctalerico2018** [comment]
Mardia coefficient wasn't producing an output on my structural equation model and I couldn't figure out why.  The model ran and I had an output for the other tests, but this one.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by juliuspf** [comment]
@ctalerico2018 could you provide a jasp file for this bug? Or the data and describe the model you tried to fit?
