### ISSUE TITLE
[Bug]: Installing JASP

### ISSUE THREAD

**Issue by lfvillalobos** [jasp-stats/jasp-issues#1681]
### JASP Version

0.16.1

### What analysis are you seeing the problem on?

Installing JASP

### What OS are you seeing the problem on?

MacOS BigSur

### Bug Description

Hi guys. I'm trying to install JASP on my computer. Once installed, I cannot open it. It says, "JASP" cannot be opened because the developer cannot be verified". I'm attaching a screenshot. 
<img width="1440" alt="Screen Shot 2022-04-09 at 2 42 21 PM" src="https://user-images.githubusercontent.com/103332944/162588260-14a1d85e-67c4-4ae0-ae06-360b64cddd3d.png">

Could you please help me? Thank you!

### Expected Behaviour

<img width="1440" alt="Screen Shot 2022-04-09 at 2 42 21 PM" src="https://user-images.githubusercontent.com/103332944/162588320-cef881e5-cc06-4eec-b333-62251a9475e1.png">

### Steps to Reproduce

1. Install JASP
2. Try to open it
3. I couldn’t 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by icekylin** [comment]
Yes this is a known issue to us. It should be fixed in the upcoming next release.
You can refer to here https://github.com/jasp-stats/jasp-issues/issues/1426 to temporarily solve this problem

**Comment by boutinb** [comment]
We have a beta version that should solve this problem: http://static.jasp-stats.org/Nightlies/macOS-x86_64/JASP-nightly-stable-2509cc21037a54e6f20c5dc5d54b81403ae7690f.dmg 
Could you try it?

**Comment by lfvillalobos** [comment]
Thank you.

From: bruno boutin ***@***.***>
Date: Tuesday, April 12, 2022 at 10:17 AM
To: jasp-stats/jasp-issues ***@***.***>
Cc: lfvillalobos ***@***.***>, Author ***@***.***>
Subject: Re: [jasp-stats/jasp-issues] [Bug]: Installing JASP (Issue #1681)

We have a beta version that should solve this problem: http://static.jasp-stats.org/Nightlies/macOS-x86_64/JASP-nightly-stable-2509cc21037a54e6f20c5dc5d54b81403ae7690f.dmg
Could you try it?
