### ISSUE TITLE
[Feature Request]: Bar Charts as Plot Option

### ISSUE THREAD

**Issue by paulamarentette** [jasp-stats/jasp-issues#1683]
### Description

bar charts as plot option

### Purpose

to illustrate means-based tests

### Use-case

t-tests, ANOVA, 

### Describe the solution you would like

bar charts with options for SD, SE, CI as error bars, capacity to edit y axis to include 0

### Additional context

I like the new raincloud charts, but would like to show students the same results across several formats. Bar charts (Where I can set the y-axis to 0) are particularly useful in helping students understand results in large datasets that are significant but trivial. Also it is useful to compare box plot vs. bar chart in exploring median vs. mean.
The current line graph emphasizes the difference (and won't let me change the y axis to 0 even with new editing capacity).
Also the line graph suggests continuity, and is therefore misleading.

**Comment by EJWagenmakers** [comment]
I agree! Maybe an option that one of our new recruits can work on. @Kucharssim do you have any ideas who to assign this to? These are popular tests so lots of people might appreciate the suggested functionality. Maybe something for @LSLindeloo or @arandolan or @foger3 ?
