### ISSUE TITLE
[Bug]: Error during the initialization of a Module

### ISSUE THREAD

**Issue by AriaAvi** [jasp-stats/jasp-issues#1684]
### JASP Version

0.16.1

### JASP Module

jaspMachineLearning

### What analysis are you seeing the problem on?

machine learning, regression, reliability, and network 

### What OS are you seeing the problem on?

Windows 10

### Bug Description

[Bug]: Error message: An error occurred trying to initialize a module from dir C:/... The error was: icon is missing from C:\   

Note: the machine learning, regression, reliability, and network are all missing and I get 4 error messages every time I launch JASP. Despite the errors I can still open JASP. However, the abovementioned 4 modules are missing. 
Please see the PPT file. 
[Jasp Error.pptx](https://github.com/jasp-stats/jasp-issues/files/8469138/Jasp.Error.pptx)

### Expected Behaviour

I expect to see and be able to run the machine learning, regression, reliability, and network modules. 

### Steps to Reproduce

1. 
2. 
3. 
...
Nil

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by AriaAvi** [comment]
@boutinb Hi, No I did not load any module with a Developer module. In brief, I installed the latest JASP the 'conventional' way, and clicked to open it, but I received the errors.
Note: I reinstalled JASP, but the problem persisted.

**Comment by boutinb** [comment]
The error indicates that JASP cannot find the module you try to use. Apparently there was a problem during the installation.
Could you try to install again JASP. Maybe you could try the beta version of our new version (released probably next week): http://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-stable-3b846c5eea7abafede12e339bf47d2b6c6934917.msi

**Comment by AriaAvi** [comment]
Thank you. The beta version works fine.

**Comment by boutinb** [comment]
It's now an official version! So I can close this issue.
