### ISSUE TITLE
[Feature Request]: VPAT

### ISSUE THREAD

**Issue by mshephe1** [jasp-stats/jasp-issues#1685]
### Description

Many American universities will not allow softwares to be used unless there is a VPAT (voluntary product assessibility template). 

### Is your feature request related to a problem?

No VPAT (which demonstrates ADA complicance)

### Describe the solution you would like

Create a VPAT

### Additional context

Many American Universities will not allow the use of software unless they demonstrate ADA compliance (universities don't want to get sued).  I won't be able to use this software with my students unless this can be demonstrated.

**Comment by EJWagenmakers** [comment]
We realize that particular aspects of JASP need to be improved as far as accessibility is concerned, and this will become relevant once we've finished the two major projects we are working on now. The VPAT/ADA guidelines may come in handy, but I must see that they've managed to bury the essentials under a heap of jargon. @boutinb maybe handy to keep this in mind when we turn to accessibility...

**Comment by EJWagenmakers** [comment]
BTW, I tried to find information online on what software needs to do to be ADA compliant, but I mostly get information on websites. Would you happen to know the essential components? Screenreader-compatible, and operable by keyboard? Is there anything else?

**Comment by mshephe1** [comment]
> BTW, I tried to find information online on what software needs to do to be ADA compliant, but I mostly get information on websites. Would you happen to know the essential components? Screenreader-compatible, and operable by keyboard? Is there anything else?

https://montevallo.app.box.com/v/VPAT-Template  This from my university.  It seems to be based on generic standards.

**Comment by EJWagenmakers** [comment]
Thanks, this is very helpful. @boutinb can you make a note of this?

**Comment by boutinb** [comment]
I have created an Accessibility project. @akashrajkn: you were working already on improving the shortcuts. If you make an issue or a PR, use this project.

**Comment by TarandeepKang** [comment]
Dear team, I thought I would respond to this thread, because I both regularly use the software, and, have a physical disability and related accessibility needs. I will be happy to discuss this with you further, if you like? I know for example that under Apple systems company recommends labelling all options so that they can be easily interacted with using voice recognition technologies, such as those provided in the operating system. Now, however I only work with Windows, but I will be happy to help with testing anything you implement to make the software more accessible. Shortcut keys are a good start! They will help for people with reduced mobility, and we will submit a ticket out of individuals with visual impairments, and other restrictions. As I said, happy to chat further about this, if it would help!

**Comment by EJWagenmakers** [comment]
Great, we'll definitely take you up on this offer!

**Comment by akashrajkn** [comment]
Nice! I will use this project and put some updates there. 

@TarandeepKang thanks for the offer, I will make a start on the development with shortcuts soon, and would be happy to get your feedback in the future :)

**Comment by R180** [comment]
FYI. Here's an example: https://www.jamovi.org/VPAT.pdf

**Comment by EJWagenmakers** [comment]
@JTPetter this is the relevant thread with information about the VPAT document. Maybe you can create one for JASP and we can update it as we add more accessibility options.

**Comment by R180** [comment]
One thing to keep in mind that a VPAT can be produced even if JASP has not yet gotten very far with regard to accessibility. This will allow me to at least _request_ that my institution make JASP available on it's machines.

**Comment by JTPetter** [comment]
We have created a VPAT for JASP. It will be available on the website very soon, but for now you can find it here: 
[VPAT_JASP.pdf](https://github.com/jasp-stats/jasp-issues/files/11415568/VPAT_JASP.pdf)
