### ISSUE TITLE
[Bug]: jaspML file is not saved in Machine learning module (Random Forest Regression)

### ISSUE THREAD

**Issue by akypar** [jasp-stats/jasp-issues#1686]
### JASP Version

0.16.1

### JASP Module

jaspMachineLearning

### What analysis are you seeing the problem on?

Regression / Random forest 

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I am trying to save a trained model (jaspML) to use it in prediction. Even though i check the "Save trained model" box the jaspML file is not created.

### Expected Behaviour

The jaspML file should be created.

### Steps to Reproduce

1. open a data file (csv)
2. machine learning / regression / random forest
3. set target and predictors
4. press the "browse" button to set the location where the jaspML file should be saved
5. check the box next to "Save trained model"
6. no file is created
...
[ML_test.zip](https://github.com/jasp-stats/jasp-issues/files/8484414/ML_test.zip)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by AlexanderLyNL** [comment]
Hi Akypar, 

Thanks for the report. I can reproduce this on 
- macOS 11.6.5 M1
- For me the problem occurs with Random Forest Regression, but the model gets saved for Boosting Regression
- JASP 0.16.1

@koenderks could you have please have a look.

**Comment by koenderks** [comment]
I can reproduce this, but its a dependency thing since if you refresh the analysis you can save the model

**Comment by akypar** [comment]
Refreshing the analysis does not work for me...

**Comment by koenderks** [comment]
Did you try it via this "Refresh button" on top? 
![image](https://user-images.githubusercontent.com/25059399/163341356-d2668e92-1c5b-4940-8024-91601e3479cc.png)

As you can see, this way the model should be saved (on my pc here at least).

**Comment by akypar** [comment]
When I press this button I get the following:


This analysis terminated unexpectedly.

Error in str2lang(x): :1:27: unexpected input
1: DOESNOTMATTER ~ 26/10/2017_
                               ^

Stack trace
doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = 
dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

mlRegressionRandomForest(...)

.mlRegressionTableSummary(dataset, options, jaspResults, ready, position 
= 1, type = 'randomForest')

.decodeJaspMLobject(model)

.decodeJaspMLobject.randomForest(model)

formula(paste('DOESNOTMATTER', '~', 
paste0(decodeColNames(names(model$forest$xlevels)), collapse = ' + ')))

formula.character(paste('DOESNOTMATTER', '~', 
paste0(decodeColNames(names(model$forest$xlevels)), collapse = ' + ')))

str2lang(x)

**Comment by koenderks** [comment]
@akypar could you save your analysis as a .jasp file (via top left menu -> save), then make a .zip from this .jasp file and upload it here in this issue. That would make this bug a little bit more reproducible. Thanks in advance

**Comment by akypar** [comment]
Here is the zip file.
[ML_test.zip](https://github.com/jasp-stats/jasp-issues/files/8488376/ML_test.zip)

**Comment by koenderks** [comment]
Ok thanks! I can reproduce your error. It seems to be something with the column names of the data containing a `_`. Here is the same data file, but with different column names ([ML_test2.csv](https://github.com/jasp-stats/jasp-issues/files/8488467/ML_test2.csv)). Using this file I can save the model in JASP 0.16.1. Could you try using this file @akypar?

![image](https://user-images.githubusercontent.com/25059399/163371904-c8b74d0d-541e-4372-9559-862a3a873e0b.png)

**Comment by akypar** [comment]
Indeed, it was a column name problem...

Thanks a lot Koen!!!!!

**Comment by koenderks** [comment]
No worries. If you run into anything else let me know!

**Comment by akypar** [comment]
Hi AlexanderLyNL,

Thanks for the confirmation.

I tried Boosting Regression without any success (jaspML not saved).
