### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by c0okieCut** [jasp-stats/jasp-issues#1689]
### JASP Version

0.16.1

### JASP Module

jaspDescriptives

### What analysis are you seeing the problem on?

PieCharts, Distribution Plots

### What OS are you seeing the problem on?

Windows10

### Bug Description

https://1drv.ms/v/s!AqTPjJEuff5bhSmM5qAQ2LoVa6aI

### Expected Behaviour

I used to be able to produce charts and tables.

### Steps to Reproduce

1. Reset windows10
2. Re-install Jasp
3. graphical problems
...

### Log (if any)

https://1drv.ms/u/s!AqTPjJEuff5bhS_AnZtw8K5cbmsa?e=88YZ7W

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by c0okieCut** [comment]
Thanks, this a waste of time. Graphics card drivers issue.

**Comment by boutinb** [comment]
What was the problem?

**Comment by c0okieCut** [comment]
Graphical components of the program did not load. I think the video link I
uploaded still stands. Let me know if you haven't seen it and still want to
see.

20 Nis 2022 Çar 12:36 tarihinde bruno boutin ***@***.***>
şunu yazdı:
