### ISSUE TITLE
MANOVA

### ISSUE THREAD

**Issue by gamons** [jasp-stats/jasp-issues#169]
## Template for bug reports

* JASP version:
* OS name and version:
* Analysis:
* Steps to reproduce: 

## Template for enhancement requests
 
* Enhancement: MANOVA as a standard feature in JASP.
* Purpose: At a Master level at my university, we use MANOVA. I use JASP for two purposes teaching and training. Both use MANOVA. Thus, I am requesting that MANOVA be added as a standard feature in JASP. Thank you in advance!

**Comment by TimKDJ** [comment]
MANOVA was implemented in 0.10
