### ISSUE TITLE
JAGS throws error in `stringr::str_count(model, chars)`: object 'model' not found

### ISSUE THREAD

**Issue by HamidLD** [jasp-stats/jasp-issues#1691]
### JASP Version

0.16.2

### JASP Module

jaspJags

### What analysis are you seeing the problem on?

Model fitting

### What OS are you seeing the problem on?

Win10 64bit

### Bug Description

I have a behavioral data set [BartC.csv](https://github.com/jasp-stats/jasp-issues/files/8523015/BartC.csv) , to which I want fit a cognitive model using JAGS (shown in the attached image 
![error](https://user-images.githubusercontent.com/104083111/164276821-747f3a29-56b6-4a29-b576-0be7980667e5.PNG), but I get the following error:  

This analysis terminated unexpectedly.

Error in stringr::str_count(model, chars): object 'model' not found

Stack trace
doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

JAGS(...)

.JAGSrunMCMC(jaspResults, dataset, options)

jaspResults[['mainContainer']]$setError(.JAGSmodelError(e, options))

private$jaspObje

ct$setError(x)

.JAGSmodelError(e, options)

stringr::str_count(model, chars)

stri_count_fixed(string, pattern, opts_fixed = opts(pattern))

### Expected Behaviour

It should produce the posterior means of parameters beta and rho for each participant, like the following: 
![posterior](https://user-images.githubusercontent.com/104083111/164277477-f04ac6a7-cbe4-428a-9684-1c606afdb0a7.PNG)

### Steps to Reproduce

1. Use the following model in the JAGS module (I've attached the data earlier)
data{
 for (k in 1:maxPumps){
   cut[k] = k - 0.5
 }
}
model{
  for (i in 1:nParticipants){
    rho[i] ~ dnorm(7, 1/5^2)T(0,)
    beta[i] ~ dnorm(3, 1/2^2)T(0, )
    yPredTmp[i] ~ dnorm(rho[i], 1/beta[i]^2)T(0, )
    yPred[i] = round(yPredTmp[i])
  }
  for (t in 1:totalTrials){
    yPrime[t] ~ dnorm(rho[participant[t]], 1/beta[participant[t]]^2)T(0, )
    y[t] ~ dinterval(round(yPrime[t]), cut[1:burst[t]])
  }
}

2. Select the rho and beta parameters as the output
 
3. And here the error is produced. 

Jasp file:
[BartC.zip](https://github.com/jasp-stats/jasp-issues/files/8523403/BartC.zip)
 

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by amirmasoudabdol** [comment]
@FBartos, any idea what's going on here?

**Comment by FBartos** [comment]
hmm, no idea. Maybe an issue for @vandenman to look at?

**Comment by vandenman** [comment]
Looks like the same issue as https://github.com/jasp-stats/INTERNAL-jasp/issues/1816

**Comment by HamidLD** [comment]
> Looks like the same issue as https://github.com/jasp-stats/INTERNAL-jasp/issues/1816

That link doesn't work for me. ("404" error). 
To give you more information, here's the experiment that has done what I want to do: https://osf.io/3n98r/ 
I can also do it in R, but thought to give it a try with Jasp first because it's easier ha!

**Comment by vandenman** [comment]
@HamidLD there is an error because you need to specify initial values for some model components. But unfortunately, an error occurs when trying to show the error message...

With settings like these:
![image](https://user-images.githubusercontent.com/21319932/164498958-cd7c8946-e768-4c8e-b8cb-d2889d93fbdf.png)

I get the following error in jasp-stats/jaspJags#69:
![image](https://user-images.githubusercontent.com/21319932/164499049-8db9394d-bf6c-467c-90c4-d21c038454a4.png)


can you tell me what the correct values for these should be?

**Comment by HamidLD** [comment]
> @HamidLD there is an error because you need to specify initial values for some model components. But unfortunately, an error occurs when trying to show the error message...
> 
> With settings like these: ![image](https://user-images.githubusercontent.com/21319932/164498958-cd7c8946-e768-4c8e-b8cb-d2889d93fbdf.png)
> 
> I get the following error in [jasp-stats/jaspJags#69](https://github.com/jasp-stats/jaspJags/pull/69): ![image](https://user-images.githubusercontent.com/21319932/164499049-8db9394d-bf6c-467c-90c4-d21c038454a4.png)
> 
> can you tell me what the correct values for these should be?

I see. Those values should be:
maxpumps: 116 (there is a +1 in the code, so maybe it should be 117)
totalTrials: 4830
participants: 161 (each have had 30 trials)
This demo file might also be useful: 
[BARTDemo.zip](https://github.com/jasp-stats/jasp-issues/files/8532576/BARTDemo.zip)

**Comment by HamidLD** [comment]
@vandenman Thanks! It worked! I had almost given up on this ha. 
The only thing that confuses me is the number of participants. I have 161 participants, yet this gives you 180 for rho and beta, and it gives the error when you try any number other than 180.

**Comment by HamidLD** [comment]
I think I found out what's going on. For some reason, the model has calculated imaginary participants, producing very similarly weird numbers and CIs for them (the rho for all of them is 7 with CIs between 0 and 17), so I deleted these and total n is 161 now. 
Anyway, thanks again, I couldn't have figured this out without you.

**Comment by vandenman** [comment]
> For some reason, the model has calculated imaginary participants, producing very similarly weird numbers and CIs for them (the rho for all of them is 7 with CIs between 0 and 17)

Ah yeah in that case all information is sampled from the prior distributions, so the sampled values probably do not make any sense.

**Comment by HamidLD** [comment]
> > For some reason, the model has calculated imaginary participants, producing very similarly weird numbers and CIs for them (the rho for all of them is 7 with CIs between 0 and 17)
> 
> Ah yeah in that case all information is sampled from the prior distributions, so the sampled values probably do not make any sense.

Oh yeah that makes sense, thanks!
