### ISSUE TITLE
[Feature Request]: fix the number of JASP engines by an administrator

### ISSUE THREAD

**Issue by mathijsdeen** [jasp-stats/jasp-issues#1693]
### Description

Is it possible to make the number of JASP engines that are available to be fixed by an administrator

### Purpose

When RAM is limited (e.g. on an application server), you might want to limit RAM usage for the end user.

### Is your feature request related to a problem?

At our mental health organization we're thinking about implementing JASP, but the IT department is hesitating because of potentially excessive RAM usage.

### Describe the solution you would like

The option to fix the number of JASP engines available to the end user, possibly overriding or ignoring the user setting in Preferences -> Advanced -> Engine Options

### Additional context

I discussed this already with @JorisGoosen via e-mail, briefly.

**Comment by mathijsdeen** [comment]
Thank you for implementing this. According to jasp-stats/jasp-desktop#4838, this can be used by providing a modified JASP config file to the users, containing some `maxEngineCountAdmin` field. Could you explain how this should be implemented? Where should this JASP config file be placed, or which config file should be modified?

**Comment by JorisGoosen** [comment]
Hello Matthijs,

This depends on your operating system. On windows and linux this should be fairly simple.

Assuming you will be using windows you can set a value in the registry, in either one of these:
- `HKEY_CURRENT_USER\Software\JASP\JASP`
- `HKEY_LOCAL_MACHINE\Software\JASP\JASP`

The value you will want to set/add there (after installing JASP perhaps? I did not test deployment):
`maxEnginesAdmin` which should be a `REG_DWORD` and set to whatever value you deem good.

I would also suggest disable animations `disableAnimations` as `REG_SZ` set to `true`. (Should save on streaming all those desktops)

So this hasn't been tested by me but all the settings should work fine so Im very curious to hear whether this works out or not.

You could test it with this (unsigned) [stable nightly installer](https://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-stable-7bda69f819b904dc494e3beffe3e98c1430342aa.msi )

**Comment by mathijsdeen** [comment]
Many thanks! We're using Windows indeed, so this should be straightforward. I'm assuming this will be available in the next stable release? I'll ask our IT department to update by then, and refer to this issue for the instructions above. I'll keep you posted :).

**Comment by JorisGoosen** [comment]
> Many thanks! We're using Windows indeed, so this should be straightforward. I'm assuming this will be available in the next stable release? 

You are most welcome :)
Indeed it will be, it should be out soon!

> I'll ask our IT department to update by then (I don't think I can convince them to install a nightly release..), and refer to this issue for the instructions above. I'll keep you posted :).

Makes sense, and I can help out if something doesn't work as intended.

**Comment by JorisGoosen** [comment]
@mathijsdeen if you do look at this (0.16.4 should be out next week) please let us know how it goes at https://github.com/jasp-stats/INTERNAL-jasp/issues/2121 so that we can make some documentation out of the steps that were required.
