### ISSUE TITLE
[Bug]: Select custom editor no longer works in JASP 0.16.2

### ISSUE THREAD

**Issue by TomTomato55** [jasp-stats/jasp-issues#1696]
### JASP Version

0.16.2

### What OS are you seeing the problem on?

MacOS Monterey 12.3.1

### Bug Description

With JASP 0.16.2 there is an error when Data Preferences are set to "Select custom editor." When I select an editor application (i.e., Excel, Numbers, SPSS - it doesn't matter which one), JASP produces the following error when I click a cell in the JASP data spreadsheet:

"Unable to start the editor : Microsoft Excel.app. Please check your editor settings in the preference menu."

<img width="421" alt="Screen Shot 2022-04-28 at 5 38 07 PM" src="https://user-images.githubusercontent.com/104600724/165868870-946c2a23-9172-49ea-a91d-c99fec60f3a7.png">

If I change Data Preferences to "Use default spreadsheet editor," then clicking a cell in the JASP data spreadsheet correctly opens Excel (i.e. my default editor).  However, this means I can't edit the data in anything but the default editor.

### Expected Behaviour

I reinstalled JASP 0.16.1 alongside the current version.  When I use JASP 0.16.1, "Select custom editor" works perfectly. When I click a cell in the data spreadsheet, whatever I have set as the custom editor opens  The problem only happens with JASP 0.16.2

### Steps to Reproduce

1. I tried four different JASP datasets.  The error happened with all four .jasp files in 0.16.2
2. The error did not happen on these four JASP datasets when using 0.16.1
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment]
Hi @TomTomato55, thanks for reporting this. Maybe Joris can help, once he is back from holiday.
