### ISSUE TITLE
[Feature Request]: JASP Road Map

### ISSUE THREAD

**Issue by HiramTheHero** [jasp-stats/jasp-issues#1697]
### Description

A Road Map that shows the upcoming development goals for JASP

### Purpose

Give information about upcoming development goals for JASP

### Additional context

I apologize if you already have one. I haven't been able to find it on the JASP website nor on Github. It would be nice to see what cool features are coming up for JASP. (And maybe give some feedback from the community about the development goals, etc.) Thank you for this great software!

**Comment by juliuspf** [comment]
Hi @HiramTheHero, thank you for the request. I think EJ can say more about this.

**Comment by AlexanderLyNL** [comment]
I'd like to keep this internal, as there is already quite some pressure on people working on this. That said, we're always open for suggestions.

**Comment by juliuspf** [comment]
Sorry @HiramTheHero, I will close this then. Let's hope that soon, there will be no need for a road map anymore ;)
