### ISSUE TITLE
[Bug]: compute column with missing values fails if missings are not replaced by zeros

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#1699]
### JASP Version

0.16.2

### What analysis are you seeing the problem on?

-

### What OS are you seeing the problem on?

Windows 10 and MacOS

### Bug Description

I have a dataset with missing values. I try to compute the mean of some variables. Some of them have missing values like -77 that are correclty registered within JASPs preferences and thus the cells appear empty. 

The following does not work - the computed cells stay empty without an error message:
`((((((((((((MPfeminin + MPsanft) + MPsensibel) + WPfeminin) + WPsanft) + WPsensibel) + MMfeminin) + MMsanft) + MMsensibel) + WMfeminin) + WMsanft) + WMsensibel) / 3)`

The following does work:
(replaceNA(MPfeminin,0) + replaceNA(MPsanft,0) + replaceNA(MPsensibel,0) + replaceNA(WPfeminin,0) + replaceNA(WPsanft,0) + replaceNA(WPsensibel,0) + replaceNA(MMfeminin,0) + replaceNA(MMsanft,0) + replaceNA(MMsensibel,0) + replaceNA(WMfeminin,0) + replaceNA(WMsanft,0) + replaceNA(WMsensibel,0))/3

Is this expected behabiour - and when yes - why?

### Expected Behaviour

I would like to compute sums without replacing every NA with a 0.

### Steps to Reproduce

1. open the .jasp-dataset below
2. look into the 2 computed columns at the end
3. one stays empty, the other one works
...

### Log (if any)

[missings.zip](https://github.com/jasp-stats/jasp-issues/files/8610466/missings.zip)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment]
@tomtomme good question! I think this is desired behaviour since in the underlying R `NA + 1 = NA`, unless the NAs are replaced with anything (as you did). I wonder if it makes sense to include a button that replaces the GAs with a user specified value in these NA scenarios. Joris might know if this is feasible. Of course, you could always resort back to an R column and do something like `rowSums(cbind(MPfeminin, WMsensibel), na.rm = TRUE) / 3` (I left out a few of those variables to save me some writing time).

**Comment by tomtomme** [comment]
I guess me and my students think more in line of `Something +1 = Something +1`, even if this Something is NA. It did not occur to us, that the number getting overboard would be something useful. But from what I read this is indeed R proper. And that the given reasons for this seem strange to us, is probably our problem. 
What JASP could maybe do, is to inform the user about that R is indeed trying to calculate something and that the output is NA or that this operation cannot be calculated properly. Or some kind of progress bar, or "operation successful" message or a hint about Rs rules about NAs. Because we thought that JASP was just broken in this regard. And that is probably true for anyone not trained in R.

**Comment by juliuspf** [comment]
@JorisGoosen, do you have any idea if this is feasible to implement? Something in the computed column window as to how to treat NAs? or could this be covered by data editing?

**Comment by vandenman** [comment]
In general, `NA + 1` equals `NA`. If somebody specifies that `-99` should be treated as a missing value, then JASP should:

1. Not show `-99` in the data view but rather a missing value (i.e., `NA`).
2. Treat missing values as missing values, so `NA + 1` equals `NA`.
3. Show a warning message + a link to a helpfile about missing values whenever a computed column contains missing values.

So far, I think point 3 is missing, which shouldn't be too difficult to add.

**Comment by juliuspf** [comment]
Would you take this on then?

**Comment by vandenman** [comment]
Let's first see if Joris has any input.

**Comment by tomtomme** [comment]
@vandenman Point 1 is also missing. JASP showing NA would be an improvement. At the moment the cells look empty, which could mean 2 things: empty cell or cell with missing value. Thanks for taking this on!

**Comment by vandenman** [comment]
> JASP showing NA or anything that would distinguish NA from just empty cells would be an improvement.

I think there is a misunderstanding here. There is no difference between NA and an empty cell?
As in, every empty cell is internally represented as a missing value. As soon as you add `-99` to the list of missing values, all values in the data set with `-99` are not represented as `-99` but as `NA`.

**Comment by juliuspf** [comment]
A change in the representation of all NAs would be an option. Instead of empty cells it could be a dot `.` (as in SPSS), or maybe it could even be user defined? @AlexanderLyNL, @EJWagenmakers any thoughts?

**Comment by juliuspf** [comment]
in any case a bit more guidance in the helpfile would definitely be good.

**Comment by tomtomme** [comment]
exactly what I think Julius :D
For me, when I collect data, I can choose to collect NA, -99 or just nothing - or maybe a fluke of my data collection tool produces unforseen empty cells instead of a -99.

I think it would make sense to show NA or -99 even if I add it to the list of missing values. Because when I can still see the missing value -99, I only then can distinguish between a really empty cell and a cell with a -99. One could say that -99 is a different code for a missing value than an empty cell.
________________________________________
Von: Julius Pfadt ***@***.***>
Gesendet: Freitag, 13. Mai 2022 15:53:40
An: jasp-stats/jasp-issues
Cc: Thomas Langkamp MSH Hamburg; Mention
Betreff: Re: [jasp-stats/jasp-issues] [Bug]: compute column with missing values fails if missings are not replaced by zeros (Issue #1699)

A change in the representation of all NAs would be an option. Instead of empty cells it could be a dot . (as in SPSS), or maybe it could even be user defined? @AlexanderLyNL<https://github.com/AlexanderLyNL>, @EJWagenmakers<https://github.com/EJWagenmakers> any thoughts?

**Comment by juliuspf** [comment]
I think we are getting closer to being on the same page, but we are not quite there :)
What Don was saying is that for the machine there cannot be empty cells that are not NA. If you want your empty cells to represent something else than NA, you need to fill them with something else. If they are empty, JASP will treat them as NA. In any case it could help to just show another label for NA instead of an empty cell. 
Now, even if you would want two different labels, say *empty* for any empty cell and *missing* for an NA or -99 cell, inside JASP both cells would be treated as NAs, and in your computed columns they would also show up as NA.

**Comment by JorisGoosen** [comment]
> In general, `NA + 1` equals `NA`. If somebody specifies that `-99` should be treated as a missing value, then JASP should:
> 
>     1. Not show `-99` in the data view but rather a missing value (i.e., `NA`).

This would be a general thing then right, under Preferences->Data? 
And I think it is a good idea, we could definitely go for a default "." or "NA" or whatever. 
Although I assume there was a reason we went for blank cells in the first place?

>     2. Treat missing values as missing values, so `NA + 1` equals `NA`.

This goes automatically right?
Because I assume R's `NA` gets converted into a `nan` for doubles in scalars? 
Not reallly sure what happens with ordinals etc.

In any case, it would be easy to have that be JASPs behaviour.

> 
>     3. Show a warning message + a link to a helpfile about missing values whenever a computed column contains missing values.

This can't hurt, although the warning message would be a bit hidden in some situations (I assume this would be shown in the computed-columns-subwindow), where a source for the computed column later gets missing values introduced?


However setting the display of NA/missing-value to `.` should already make it pretty obvious when a computed column contains them. So why go through the trouble of adding the warning?
The helpfile could simply be part of the datapreferences helpfile right?

**Comment by juliuspf** [comment]
I would be a curious as the next guy to know why we went with blank cells... 
The last point you are making is correct, if the computed cell is showing a dot or something, people would already know that something related to NAs has happened to their computation.

**Comment by tomtomme** [comment]
Julius wrote: 2Now, even if you would want two different labels, say empty for any empty cell and missing for an NA or -99 cell, inside JASP both cells would be treated as NAs, and in your computed columns they would also show up as NA."

Thats fine and quite what I would expect. I just care about the labeling. And you clearly explained a very nice solution :D
Thanks!
________________________________________
Von: Julius Pfadt ***@***.***>
Gesendet: Freitag, 13. Mai 2022 17:24:06
An: jasp-stats/jasp-issues
Cc: Thomas Langkamp MSH Hamburg; Mention
Betreff: Re: [jasp-stats/jasp-issues] [Bug]: compute column with missing values fails if missings are not replaced by zeros (Issue #1699)

I think we are getting closer to being on the same page, but we are not quite there :)
What Don was saying is that for the machine there cannot be empty cells that are not NA. If you want your empty cells to represent something else than NA, you need to fill them with something else. If they are empty, JASP will treat them as NA. In any case it could help to just show another label for NA instead of an empty cell.
Now, even if you would want two different labels, say empty for any empty cell and missing for an NA or -99 cell, inside JASP both cells would be treated as NAs, and in your computed columns they would also show up as NA.

**Comment by tomtomme** [comment]
Julius wrote: "if the computed cell is showing a dot or something, people would already know that something related to NAs has happened to their computation."

Exactly. They would at least know, that JASP tried to compute something, and that the perceived "error" might be on the side of the user. With an empty cell showing up in the computed column, and without a message, there is this awkward feeling that JASP just did not do anything.

I also agree with everything Joris wrote.
Cheers :)

________________________________________
Von: Julius Pfadt ***@***.***>
Gesendet: Freitag, 13. Mai 2022 18:17:46
An: jasp-stats/jasp-issues
Cc: Thomas Langkamp MSH Hamburg; Mention
Betreff: Re: [jasp-stats/jasp-issues] [Bug]: compute column with missing values fails if missings are not replaced by zeros (Issue #1699)

I would be as curious as the next guy to know why we went with blank cells...
The last point you are making is correct, if the computed cell is showing a dot or something, people would already know that something related to NAs has happened to their computation.

**Comment by tomtomme** [comment]
This is closed, because julius tracks rhis issue now as a feature request to improve na visibility.
That should be enough to prevent confusion with NAs

**Comment by juliuspf** [comment]
thanks :)
