### ISSUE TITLE
Binomial sequential plot crashes JASP after data editing

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-issues#170]
JASP crashes when the following steps are taken:
1. Open the zombie example (from the data library for instance)
2. Go to Frequencies -> Bayesian Binomial test; set test value to 1; drag outcome variable into the input field; and tick "sequential analysis"
3. Now edit the data using LibreOffice: add any number of hungry zombies and press "save". JASP will try to run the analysis but crashes. 

Reopening JASP and analyzing the saved csv file does not give the error and works fine. So the file itself seems in good order.

Cheers,
E.J.

**Comment by JorisGoosen** [comment]
I can no longer reproduce this, closing the issue.
