### ISSUE TITLE
[Bug]: Error during ANOVA

### ISSUE THREAD

**Issue by sachinthorat5989** [jasp-stats/jasp-issues#1700]
### JASP Version

0.16.1

### JASP Module

jaspAnova

### What OS are you seeing the problem on?

Linux Mint 20.1 Cinnamon

### Bug Description

![Screenshot from 2022-05-03 19-48-15](https://user-images.githubusercontent.com/35394177/166473115-3dc3b8d5-74b5-4a00-a7f1-5af735d86cd6.png)

Any work around?
![Screenshot from 2022-05-03 19-48-15](https://user-images.githubusercontent.com/35394177/166476116-317d4544-7a8c-4263-bbbf-3b31ffa2d6d9.png)
[](url)

### Expected Behaviour

it should show analysis for 3 level 3 factor - Factorial design with main effects and effect interactions

### Steps to Reproduce

1. Just add 3 fixed factors and it will show up
2. 
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JohnnyDoorn** [comment]
Hi @sachinthorat5989 ,

Yes, if you could send me the jasp or data file, I can take a closer look. You can also email it to j <dot> b <dot> vandoorn <at> uva <dot> nl

Cheers,
Johnny

**Comment by tomtomme** [comment]
@sachinthorat5989 
Did you send the file to Johnny?
It probably is just what the error says. One or your groups does have 0 or 1 measurement and thus the ANOVA cannot run. How big is your sample for each group?
