### ISSUE TITLE
[Bug]: Can't export EPS figures: Doesn't find Lucida Grande Font

### ISSUE THREAD

**Issue by RenzoLanfranco** [jasp-stats/jasp-issues#1701]
### JASP Version

0.16.2 (Development)

### JASP Module

jaspTTests

### What OS are you seeing the problem on?

macOS Monterey

### Bug Description

When I run a Bayesian one-sample t-test and try to export in EPS a Prior and Posterior plot, it shows the error message attached. This doesn't happen when I try to export in EPS the Sequential analysis plot.

I do have the Lucida Grande font installed.

<img width="444" alt="jasperror" src="https://user-images.githubusercontent.com/40778736/166664145-f8eaef00-3fc0-4b6e-9033-98488a1cb735.png">

### Expected Behaviour

It should be able to

### Steps to Reproduce

1. Plot a Bayesian one-sample t-test
2. Tick "Plots" and "Prior and Posterior"
3. On the plot, select "Save image as" and choose EPS.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by vandenman** [comment]
@juliuspf I cannot replicate this on Ubuntu, can you replicate this on macOS?

**Comment by juliuspf** [comment]
I am having different trouble with the above described procedure. Saving the plot as .eps opens a quartz window which shows the plot, then the spinning wheel appears, and after a few seconds the quartz window closes but there is no saved file

**Comment by boutinb** [comment]
I cannot reproduce it either on my Mac.
@RenzoLanfranco Can you change the results fonts in Preferences/Interface menu in JASP? Set it to Arial for example.

**Comment by tomtomme** [comment]
This might be loosely related to these other MacOS font-problems:
https://github.com/jasp-stats/jasp-issues/issues/2054

@RenzoLanfranco 
Did you have time to test with another font or an updated JASP version or can you share your jasp-file?

**Comment by boutinb** [comment]
This is solved since 0.18.2: The EPS format needs the XQuartz libraries on Mac. If XQuartz was installed, then no problem was found. Since 0.18.2, the needed XQuartz libraries are shipped with JASP.
