### ISSUE TITLE
[Feature Request]: add GPU acceleration for machine learning

### ISSUE THREAD

**Issue by jackliull** [jasp-stats/jasp-issues#1702]
### Description

machine learning modular is only run on CPU now , it is slow and unstable, please add GPU acceleration.

### Purpose

to improve the speed and stability  of machine learning modular.

### Use-case

when use machine learning modular 

### Is your feature request related to a problem?

no

### Describe the solution you would like

Add a enable CUDA acceleration choice.

### Describe alternatives that you have considered

no

**Comment by juliuspf** [comment]
Hi @jackliull, thanks for the request. Is that feasible @vandenman?

**Comment by vandenman** [comment]
Hi @jackliull,

GPU acceleration is not a priority right now. Furthermore, given that e.g., a CUDA implementation would only be available to those that have graphics cards that support that it is unlikely that we will implement this anytime soon.

**Comment by TarandeepKang** [comment]
Hi @vandenman I wonder whether you and the team would consider reopening this issue (I know it won't and shouldn't be urgent) given the recent announcement that Nvidia will be producing new chips for a variety of manufacturers in desktop and laptop format, which would seemingly make CUDA capability much more widespread at least over the coming years? https://www.nvidia.com/en-gb/products/rtx-spark/   For example using the cuda.ml package to leverage 
GPUs for ML. https://cran.r-project.org/web/packages/cuda.ml/ I also consider this issue relevant to this other issue discussing a Windows on ARM version of JASP #4191.

Best,

Tarandeep
