### ISSUE TITLE
[Bug]: Cannot add minus sign to custom contrasts RM ANOVA

### ISSUE THREAD

**Issue by gretamik** [jasp-stats/jasp-issues#1704]
### JASP Version

0.16.2

### JASP Module

jaspAnova

### What analysis are you seeing the problem on?

RM ANOVA

### What OS are you seeing the problem on?

macOS Monterey 12.3.1

### Bug Description

Cannot use - sign for custom contrasts, thus, making contrasts impossible to run.
Copy paste function does not seem to work either. 

![Screenshot 2022-05-06 at 11 49 38](https://user-images.githubusercontent.com/83002159/167108891-317f94bb-9345-4ab0-a2c5-59af3e76f561.png)
 

### Expected Behaviour

I should be able to add a -1 in the custom contrasts table (as it was the case in the previous versions)

### Steps to Reproduce

Just try typing a minus sign in the custom contrasts table. The contrast textboxes do not seem to recognize anything that isn't numbers thus preventing the user to correctly specify contrasts 

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment]
HI @gretamik, thanks for reporting this. Lets ask @JohnnyDoorn what could be up here.

**Comment by gretamik** [comment]
My solution was re-installing version 16.1 and was able to run my contrasts properly. So it's really something about the latest update that is bugging.

**Comment by JohnnyDoorn** [comment]
Yes that's very unfortunate, i think something changed in the contrast
widget. @boutinb hopefully knows more about this issue.
