### ISSUE TITLE
JAGS throws errors in ' stringr::str_count(model, chars): object 'model' not found'

### ISSUE THREAD

**Issue by SSeven1128** [jasp-stats/jasp-issues#1706]
### JASP Version

0.16.2

### JASP Module

jaspJags

### What analysis are you seeing the problem on?

Bayesian Hierarchical Modeling

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I tried to analyze the dataset by Bayesian Hierarchical Modeling. However, after I put in the model string, the error as the picture occured.
![pic](https://user-images.githubusercontent.com/65548550/168062044-869a8d2f-23c5-44b3-ba7a-347a141d8b74.jpg)
I have sent the JASP file named 'FG_modeling.jasp' to issues@jasp-stats.org for privacy.
Thanks.

### Expected Behaviour

It should output the posterior distributions of all the parameters.

### Steps to Reproduce

![pic](https://user-images.githubusercontent.com/65548550/168058162-dd75173b-e969-45bf-bf53-f842ffe4528e.jpg)

The model string as shown below:
```r
model{

# uninformative priors
mu_bet ~ dnorm (0,0.00001)
mu_lam ~ dnorm (0,0.00001)
mu_gam ~ dnorm (0,0.00001)
mu_tau ~ dnorm (0,0.00001)
mu_the ~ dnorm (0,0.00001)
mu_k ~ dnorm (0,0.00001)
mu_b ~ dnorm (0,0.00001)
mu_o ~ dnorm (0,0.00001)
mu_bk ~ dnorm (0,0.00001)
mu_bb ~ dnorm (0,0.00001)
mu_bo ~ dnorm (0,0.00001)

sd_d ~ dnorm (0,0.00001)
sd_r ~ dnorm (0,0.00001)
sd_s ~ dnorm (0,0.00001)
sd_bet ~ dnorm (0,0.00001)
sd_lam ~ dnorm (0,0.00001)
sd_gam ~ dnorm (0,0.00001)
sd_tau ~ dnorm (0,0.00001)
k_the ~ dnorm (0,0.00001)
sd_k ~ dnorm (0,0.00001)
sd_b ~ dnorm (0,0.00001)
sd_o ~ dnorm (0,0.00001)
sd_bk ~ dnorm (0,0.00001)
sd_bb ~ dnorm (0,0.00001)
sd_bo ~ dnorm (0,0.00001)

for (p in 1:nSub){

bet[p] ~ dnorm (mu_bet,sd_bet)
lam[p] ~ dnorm (mu_lam,sd_lam)
gam[p] ~ dnorm (mu_gam,sd_gam)
tau[p] ~ dnorm (mu_tau,sd_tau)
the[p] ~ dbeta (mu_the*k_the, (1-mu_the)*k_the) 
k0[p] ~ dnorm (mu_k,sd_k)
b0[p] ~ dnorm (mu_b,sd_b)
o0[p] ~ dnorm (mu_o,sd_o)
bet_k[p] ~ dnorm (mu_bk,sd_bk)
bet_b[p] ~ dnorm (mu_bb,sd_bb)
bet_o[p] ~ dnorm (mu_bo,sd_bo)

}
for (p in 1:nSub){

	for (i in 1:nTrial){

Choice[p,i] ~ dmultinom ({pd[p],pr[p],ps[p]})

pd[p] <- 1/2(erf((u[i]+b[i]+k[i])/o[i]*sqrt(2))-erf((u[i]+b[i]-k[i])/o[i]*sqrt(2)))
pr[p] <- (1-pd[p])*(1/(1+exp(-tau[p]*u[i])))
ps[p] <- (1-pd[p])*(1-pr[p])

u[i]<G^0.9*(eta_g^gam[p]/(eta_g^gam[p]+eta_l^gam[p])^(1/gam[p]))-lam[p]*L^0.9*(eta_l^gam[p]/(eta_g^gam[p]+eta_l^gam[p])^(1/gam[p])) 
k[i] <- k0[p]+bet_k[p]*Condition[i]
b[i] <- b0[p]+bet_b[p]*Condition[i]
o[i] <- o0[p]+bet_o[p]*Condition[i]

G <- gain[i]
L <- Loss[i]
eta_g <- green[i]+grey[i]*the[p]
eta_l <- 1-eta_g[i]
}
}
}
```

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment]
Hi @SSeven1128, thanks for the issues and providing all the info. Any idea what could be going wrong @Jiashun97?

**Comment by SSeven1128** [comment]
> duplicate of #1691. This has been fixed on development, so the upcoming release (0.16.3) should no longer show this behavior. An error occurs, but an error occurs when trying to show the error... The error is possibly due to a mistake in the model specification, or due to jags not finding any starting values where the log-posterior is finite.

Thanks for your reply! As answered in the issue #1691 , the error is partly due to JAGS not finding any initial values of the parameters. However, in most instances, the initial values of the parameters are set to NULL, like "inits = NULL" in R. It seems that the initial values of the parameters are not essential. What's more, we tried to set the initial values of the parameters to NULL, such as "mu_bet<-NULL", instead of set nothing, it showed another error as "The expression did not return a number". So, is initial values vitally needed? Or what should we do if there is no initial values of the parameters?

**Comment by tomtomme** [comment]
@SSeven1128 
Could you test with a new JASP version? If it works now, feel free to close this issue.
