### ISSUE TITLE
[Bug]: Huynh-Feldt values incorrect in repeated measures ANOVA

### ISSUE THREAD

**Issue by jgoldman13** [jasp-stats/jasp-issues#1709]
### JASP Version

0.16

### JASP Module

jaspAnova

### What analysis are you seeing the problem on?

Repeated Measures ANOVA

### What OS are you seeing the problem on?

Windows 10

### Bug Description

The Sphericity correction for the Huynh-Feldt is off in the RM ANOVA. I am pasting a picture of the same analysis ran in JAMOVI where the correction is accurate and when it is run in JASP. I was running this data file from the open source text Learning Stats with JASP -page 323, using the Broca.csv file. A student actually caught the descrepancy when the image in the textbook didn't match the results they were getting in their own JASP analysis. You can access the data here: [https://github.com/tomfaulkenberry/JASPbook/tree/master/data](https://github.com/tomfaulkenberry/JASPbook/tree/master/data)
![JASP_broca](https://user-images.githubusercontent.com/105524411/168398397-59c0640b-55cd-4bb6-aace-5aa015f2dcb6.PNG)
![JAMOVI_broca](https://user-images.githubusercontent.com/105524411/168398399-dc411a61-1ac6-4759-ad24-4e50227fd106.PNG)
)

### Expected Behaviour

The results were ran correctly otherwise, it's just the Huynh-Feldt correction that's off. 

### Steps to Reproduce

1. ANOVA
2. RM ANOVA
3. Move items into the RM cells
4. Click assumption checks
5. Sphericity tests
6. Check none, GG, and HF
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JohnnyDoorn** [comment]
Hi @jgoldman13 ,

Thank you for taking the time to report this - I see now that the maximum correction factor for the df is 1 (R can give values greater than 1, which went unnoticed before). This will be fixed in the next release.

Kind regards,
Johnny
