### ISSUE TITLE
JASP 0.9.0.1 for Mac crashes during all analyses

### ISSUE THREAD

**Issue by gjpoarch** [jasp-stats/jasp-issues#171]
## Template for bug reports

* JASP version: 0.9.0.1
* OS name and version: macOS High Sierra 10.13.6
* Analysis: e.g., repeated measures ANOVA
* Steps to reproduce: 
<img width="581" alt="screenshot 2018-08-28 13 12 14" src="https://user-images.githubusercontent.com/41833791/44719732-72bb7580-aac4-11e8-9531-041386093366.png">

## Template for enhancement requests
 
* Enhancement:
* Purpose:

**Comment by JorisGoosen** [comment]
Without the csv file we cannot take a look at this.
