### ISSUE TITLE
[Bug]: error with date format in prophet

### ISSUE THREAD

**Issue by willkm3** [jasp-stats/jasp-issues#1714]
### JASP Version

0.16.2

### What analysis are you seeing the problem on?

Prophet

### What OS are you seeing the problem on?

Windows 10

### Bug Description

When I attempt to run the Prophet module I get the following error. I cannot get it to accept any of my data files.

This analysis terminated unexpectedly.
Error: CCTZ: Unrecognized output timezone: 'GMT'

### Expected Behaviour

My input .csv file is in the following format. Date is YYYY-MM-DD

Date,Close
2013-04-01,536
2013-05-01,578
2013-06-01,657

### Steps to Reproduce

1. load date and close into Prophet. Same error every time.
2. 
3. 
...

### Log (if any)

This analysis terminated unexpectedly.

Error: CCTZ: Unrecognized output timezone: 'GMT'

Stack trace
Prophet(...)

.prophetComputeResults(jaspResults, dataset, options, ready)

.prophetModelResultsHelper(dataset, options)

prophet::fit.prophet(m = mod, df = fitDat)

sort(set_date(unique(df$ds)))

set_date(unique(df$ds))

as.POSIXct(lubridate::force_tz(ds, 'GMT'), tz = 'GMT')

lubridate::force_tz(ds, 'GMT')

cpp_force_tz(time, tz = tzone, roll)

C_force_tz(dt = dt, tz = tz, roll = roll)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment]
Hi @willkm3, thanks for reporting this. Is it possible for you to attach a .jasp file for this bug, or your data as a .csv file? Did you try any other analyses with this particular data set?

**Comment by willkm3** [comment]
Hi Julius - I did not save a .jasp. I have attached the data file.
Thanks,
William

 

    On Monday, May 23, 2022, 08:54:24 AM CDT, Julius Pfadt ***@***.***> wrote:  
 
 


Hi @willkm3, thanks for reporting this. Is it possible for you to attach a .jasp file for this bug, or your data as a .csv file? Did you try any other analyses with this particular data set?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>
  
Date,Close
2013-03-01,93.1
2013-04-01,139.88
2013-05-01,127.9
2013-06-01,89.24
2013-07-01,98.46
2013-08-01,130.01
2013-09-01,126.05
2013-10-01,202.19
2013-11-01,1116
2013-12-01,739.28
2014-01-01,805.22
2014-02-01,549.99
2014-03-01,456.99
2014-04-01,449.02
2014-05-01,626.21
2014-06-01,640.79
2014-07-01,580
2014-08-01,477.81
2014-09-01,387
2014-10-01,336.82
2014-11-01,379.89
2014-12-01,322.3
2015-01-01,215.8
2015-02-01,255.7
2015-03-01,244.51
2015-04-01,236.11
2015-05-01,228.7
2015-06-01,262.89
2015-07-01,284.45
2015-08-01,231.35
2015-09-01,236.49
2015-10-01,316
2015-11-01,376.88
2015-12-01,429.02
2016-01-01,365.52
2016-02-01,438.99
2016-03-01,416.02
2016-04-01,446.6
2016-05-01,530.69
2016-06-01,674.74
2016-07-01,622.83
2016-08-01,576.15
2016-09-01,611.1
2016-10-01,701.02
2016-11-01,739
2016-12-01,966.58
2017-01-01,966.19
2017-02-01,1189.1
2017-03-01,1081.5
2017-04-01,1435
2017-05-01,2191.83
2017-06-01,2420.6
2017-07-01,2854.3
2017-08-01,4718.3
2017-09-01,4367.1
2017-10-01,6455.1
2017-11-01,9907
2017-12-01,13769
2018-01-01,10267
2018-02-01,10315
2018-03-01,6925.4
2018-04-01,9240.6
2018-05-01,7485.8
2018-06-01,6391.5
2018-07-01,7731.3
2018-08-01,7014.6
2018-09-01,6622.4
2018-10-01,6368.39
2018-11-01,4039.5
2018-12-01,3830.5
2019-01-01,3503.8
2019-02-01,3894
2019-03-01,4167.5
2019-04-01,5599.52
2019-05-01,8532.67
2019-06-01,10809
2019-07-01,10088
2019-08-01,9623.9
2019-09-01,8331.14
2019-10-01,9185.6
2019-11-01,7599.88
2019-12-01,7208.3
2020-01-01,9367.4
2020-02-01,8561.5
2020-03-01,6427.68
2020-04-01,8631.82
2020-05-01,9451.1
2020-06-01,9150.7
2020-07-01,11350
2020-08-01,11671
2020-09-01,10795
2020-10-01,13788
2020-11-01,19696.27
2020-12-01,28938.52
2021-01-01,33138
2021-02-01,45300
2021-03-01,58796
2021-04-01,57630
2021-05-01,37280

**Comment by huangkai31** [comment]
I have the same problem with 0.16.3

1. Open the data :  Data Library -> 15. Prophet -> JASP Webpage Visits
2. Click Phophet icon on the top bar
3. move visits into Dependent Variable, move date into Time
4. On the results of prophet, it shows error message:

This analysis terminated unexpectedly.
Error: CCTZ: Unrecognized output timezone: 'GMT'

![image](https://user-images.githubusercontent.com/1758277/179432151-198538b3-175d-4376-b64c-bcb9d5fea4cf.png)

**Comment by JorisGoosen** [comment]
@willkm3 I have a suggestion for something you could try that might help us fix this.

Can you set an environment variable in windows called `TZDIR` and set to a specific path in JASP.
So if you installed JASP to `C:\Program Files\JASP` you would set it to:
`C:\Program Files\JASP\R\share\zoneinfo`

To add an environment variable you can do this: https://docs.oracle.com/en/database/oracle/machine-learning/oml4r/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0

After that (re)start JASP and see if it now does work?

**Comment by wilmo79** [comment]
> @willkm3 I have a suggestion for something you could try that might help us fix this.
> 
> Can you set an environment variable in windows called `TZDIR` and set to a specific path in JASP. So if you installed JASP to `C:\Program Files\JASP` you would set it to: `C:\Program Files\JASP\R\share\zoneinfo`
> 
> To add an environment variable you can do this: https://docs.oracle.com/en/database/oracle/machine-learning/oml4r/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0
> 
> After that (re)start JASP and see if it now does work?

Hello, @JorisGoosen, I was getting the same issue as @willkm3 using version 0.16.3, using the included Prophet model in the Data Library. I can confirm that the proposed fix worked for me! (FYI the default install path is in x86 programs, i.e.  C:\Program Files (x86)\JASP\R\share\zoneinfo) 

Cheers

**Comment by JorisGoosen** [comment]
Ok awesome @wilmo79 then Ill make sure to include that environment variable before we load R and then it will work for everyone from 0.16.4 onwards

**Comment by JorisGoosen** [comment]
@willkm3 @wilmo79 there is a testversion of jasp here: https://static.jasp-stats.org/Nightlies/WindowsZip/JASP-nightly-stable-a0c8e9c7b43ffd1020190ebe0a625668320a29aa.zip

It should have the fix for this bug in there, if you could test and verify it would be much appreciated.

**Comment by wilmo79** [comment]
> @willkm3 @wilmo79 there is a testversion of jasp here: https://static.jasp-stats.org/Nightlies/WindowsZip/JASP-nightly-stable-a0c8e9c7b43ffd1020190ebe0a625668320a29aa.zip
> 
> It should have the fix for this bug in there, if you could test and verify it would be much appreciated.

Hi @JorisGoosen, looks good!
- Removed the variable I'd previously set manually; re-opened JASP & verified the issue was back on version 16.3 (it was)
- Downloaded and ran the nightly version above, opened the supplied Prophet model and swapped 'visits' and 'actions' to make it run, which it did without failing.
Cheers,
Will

cc @willkm3

**Comment by willkm3** [comment]
Just for clarity... You successfully loaded my data file and ran the Prophet module?

willkm3

**Comment by JorisGoosen** [comment]
@willkm3 I could not test this as this problem does not occur on my system, @wilmo79 tested whatever problem they had and it seems solved.

I did ask on 9 september if you could test it then, but the fix is already in 0.16.4

I suggest you try it with your data and let us know whether it *has* solved the problem or not.

**Comment by willkm3** [comment]
Thanks for the reminder. I have been working on other projects. I will try it and let you know. 

Willkm3
