### ISSUE TITLE
[Bug]: Bayesian RM anova crashes with many factors

### ISSUE THREAD

**Issue by mdechas65** [jasp-stats/jasp-issues#1715]
### JASP Version

0.16.2

### JASP Module

jaspAnova

### What analysis are you seeing the problem on?

Bayesian Repeated measures ANOVA

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I have been trying to run a Bayesian repeated measures ANOVA with 5 factors (4 within - all with 2 levels, and 1 between with 2 levels). I have tried to run this analysis around 20 times on more and more powerful machines but the analysis never finishes (although it starts to run for a few hours) - either I see only a blank JASP screen, or JASP shuts down completely. Please note that I can run the same analysis with no problems when there are fewer factors (i.e., 3 within and 1 between, all with 2 levels). Just wondering why I cannot run this analysis with 5 factors?

### Expected Behaviour

I should be able to see a results table

### Steps to Reproduce

1. Bayesian repeated measures ANOVA
2. Four within-S factor (2 levels each); 1 between-S factor (2 levels)
3. Options - BF10; Table - effects across matched models; Order - compare to null model
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment]
HI @mdechas65, thanks for reporting this. One of the maintainers might have an idea why this happens. Could you provide a .jasp file for this bug, or at least a data file?

**Comment by mdechas65** [comment]
Hi there - also just to let you know the specifications I used. This was a repeated measures ANOVA with 4 within-S factors (hemi, region, task, item) and 1 between-S factor (group). I am using Bayes Factor BF10, order - compare to null model, and Tables - effects across matched models - thanks again, Marianne

**Comment by tomtomme** [comment]
@mdechas65 
Since you resolved the problem I am closing this one!
Feel free to reopen, if I am mistaken!
