### ISSUE TITLE
[Feature Request]: load jasp modules from R `installed.packages()`

### ISSUE THREAD

**Issue by sukanka** [jasp-stats/jasp-issues#1716]
### Description

Currently, I'm building jasp-desktop on archlinux from source. I build the executable and the modules separately, but the executable complains that it can't find the modules.
![image](https://user-images.githubusercontent.com/31362108/169972958-a6797267-1d9c-4f05-b87e-9c526f1d8e24.png)

Even if I install `jaspDescriptives` as an R package or even copy the installed R package to `Modules/`, it still complains.
```R
r$> 'jaspDescriptives' %in% installed.packages()
[1] TRUE
```

### Purpose
I want to know where should I link the installed R package `jaspDescriptives` to so that jasp-desktop can find and load it.

```bash
➜  jasp-desktop ls -al /usr/lib/jasp-desktop
total 288
drwxr-xr-x   4 root root   4096 May 24 00:22 .
drwxr-xr-x 233 root root 278528 May 24 14:32 ..
drwxr-xr-x   2 root root   4096 May 24 00:22 Modules
lrwxrwxrwx   1 root root     23 May 24 00:19 Resources -> /usr/share/jasp-desktop
drwxr-xr-x   2 root root   4096 May 24 00:22 bin
```
### Use-case

Not applicable

### Is your feature request related to a problem?

No

### Describe the solution you would like

I hope jasp-desktop can also find the modules installed as R packages.

### Describe alternatives that you have considered

Link the installed R package `jaspDescriptives` to `/usr/lib/jasp-desktop/Modules/jaspDescriptives` but it does not work.

### Additional context
jasp-desktop version: 0.16.2
R: 4.2.0
The build script I use: (full script can be found at https://github.com/sukanka/jaspOnArch/blob/main/jasp-desktop/PKGBUILD)
https://github.com/sukanka/jaspOnArch/blob/f0584bfbbc9592b661fdc8b1d644c6b7dbb937b9/jasp-desktop/PKGBUILD#L59-L65
explanation: 
`$pkgname` is just `jasp-desktop`, and `$pkgdir` is like a `chroot`, files in `$pkgdir/usr` will be installed to `/usr`.
`$srcdir` is the directory that contains the source of this package. The source of the packages is under `$srcdir/jasp-desktop`

**Comment by juliuspf** [comment]
Hi @sukanka, thanks for the report. I hope Don can help.

**Comment by vandenman** [comment]
@sukanka what is the structure of `/usr/lib/jasp-desktop/Modules/jaspDescriptives`? In my jasp build the folder structure looks like this:

```
build
|- Modules
   |- jaspDescriptives (contains all R package dependencies of this module)
      |- abind (symlink)
      |- ... other R packages
      |- jaspDescriptives (symlink, the module installed as an R package)
```
It could also be that installing jaspDescriptives failed somehow.

**Comment by sukanka** [comment]
Thanks for your reply! Actually I just linked 
```bash
ln -s /usr/lib/R/library/jaspDescriptives /usr/lib/jasp-desktop/Modules/jaspDescriptives
```
so `/usr/lib/jasp-desktop/Modules/jaspDescriptives` is just `/usr/lib/R/library/jaspDescriptives`
```bash
➜  ~ tree /usr/lib/R/library/jaspDescriptives -L 1
/usr/lib/R/library/jaspDescriptives
├── DESCRIPTION
├── Description.qml
├── help
├── html
├── icons
├── Meta
├── NAMESPACE
├── po
├── qml
└── R
```

But when I link all R library to that place, (so I linked jaspDescriptives and all its dependencies)
```bash
ln -s /usr/lib/R/library/  /usr/lib/jasp-desktop/Modules/jaspDescriptives
```
JASP doesn't complain  `jaspDescriptives` not being found, though it does complain about other modules such as `jaspCircular`,
but when  I also link 
```bash
ln -s /usr/lib/R/library/  /usr/lib/jasp-desktop/Modules/jaspCircular
```
That complaint disappears. 

So I guess, for each `jaspModule`, I have to link the R library to it, like
```bash
ln -s /usr/lib/R/library/  /usr/lib/jasp-desktop/Modules/jaspModule
```
That's ok, but I'm not very satisfied with it. I want that I only need to link once, and jasp can find the modules automatically.

**Comment by vandenman** [comment]
> That's ok, but I'm not very satisfied with it. I want that I only need to link once, and jasp can find the modules automatically.

Hmmm... well, that is problematic. The reason every module has its own folder with dependencies (as symlinks to reuse dependencies), is to support that different modules use different R package versions. Right now, the modules don't actually use different versions of dependencies but in the (far) future it should become possible to update (and downgrade) modules independently which means that different modules might be using different packages. Another way to think of this is that all modules are installed in a virtual environment.

> So I guess, for each jaspModule, I have to link the R library to it

Alternatively, have `renv` manage all R package dependencies. Usually, the renv cache lives in `~/.cache/R/renv` but you can overwrite the default location and use a system-wide location instead (in fact, JASP also uses its own cache folder). That might be more work to set up than symlinking the same folder multiple times though.

That's the only solution I can come up with for now.
