### ISSUE TITLE
[Bug]: This Installation Package could not be opened.

### ISSUE THREAD

**Issue by ty2y** [jasp-stats/jasp-issues#1717]
### JASP Version

Others

### JASP Module

jaspDescriptives

### What analysis are you seeing the problem on?

Windows

### What OS are you seeing the problem on?

Windows 10

### Bug Description

When downloading JASP from your website and attempting to run the MSI it provides me with the following error:
![image](https://user-images.githubusercontent.com/106143975/169978448-7a7a31d4-5645-4d1d-8e7d-a155cd3b362a.png)

Please could you advise

### Expected Behaviour

Install JASP

### Steps to Reproduce

1. Run the MSI multiple times and as admin
2. 
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment]
Hi @ty2y, thanks for reporting this. Which version of JASP are you trying to install?

**Comment by juliuspf** [comment]
so the 0.16.2 version I suppose?

**Comment by ty2y** [comment]
Yes I believe so

**Comment by ty2y** [comment]
Hi I am following https://jasp-stats.org/download/ and downloading the windows 64 bit version

**Comment by JorisGoosen** [comment]
@ty2y and it works? Or not?

We've just released 0.16.4 so you could try that and report back here whether it works or not.

If it doesnt work you could try downloading https://static.jasp-stats.org/JASP-0.16.4-64bit.zip and unpacking it to `C:\JASP-0.16.4-64bit\", then in a command prompt:
```
cd C:\JASP-0.16.4-64bit\
jasp --safeGraphics --junctions
```

After it's done the `Modules` folder in the unpacked `JASP-0.16.4-64bit` should look like:
![image](https://user-images.githubusercontent.com/29062713/193560069-0002a70d-448d-49a8-b274-1ff0f49a2176.png)
