### ISSUE TITLE
Enhancement Request - Polynomial Regression

### ISSUE THREAD

**Issue by chrisbeardy** [jasp-stats/jasp-issues#172]
* Enhancement: 
Add in Polynomial Regression feature with multiple independent variables and provide the formula if required

* Purpose:
Gives a wider range of options for doing a regression analysis and enhances the fit available for when regression is used for calibration. For example, I use linear and polynomial regression and have recently started using JASP for doing calibration of test rigs. A linear regression with multiple independent variables can be used to predict a true value of the dependent variable based on data collected from tests conducted with known inputs. The formula with the coefficients can then be used to "correct" the error seen in further tests with unknown inputs. 

Using a polynomial regression often provides better results than a linear regression so it would be good to see the feature added  in JASP. 

Please google "how to do a multiple polynomial regression in R" for examples.

**Comment by aewong00** [comment]
I also second this feature request.  I would also like for JASP to have in its multiple regression/generalized linear model modules support for polynomial regression.  Quadratic, cubic, etc. independent variable terms.  Thank you.  I would like to use JASP for teaching my graduate statistics course and I'd like to demonstrate this feature to my class.  I very much like also the flexplot incorporation into JASP - it's very helpful for visualizing interactions.

**Comment by tomtomme** [comment]
I second this too, and have requested this also in the context of the flexplot module here: 
https://github.com/jasp-stats/jasp-issues/issues/2138

**Comment by tomtomme** [comment]
Example from the duplicate #2486
![image](https://github.com/jasp-stats/jasp-issues/assets/4428185/d870aeed-1aab-460b-97b0-805adf7a1dbd)

**Comment by dustinfife** [comment]
Flexplot already does this. You can do quadratic and cubic, both in flexplot and in linear modeling

**Comment by tomtomme** [comment]
@dustinfife 
not completely. The formula is not displayed in the plot nor are the coefficients given by the "Regression Slopes and intercept" table. Those slopes and intercepts always display the fit of the linear model, even if visual fit is switched to poisson or cubic.

Also I just saw a bug in "Linear Modelling" where I switch the visual fit, but it always stays linear.

**Comment by dustinfife** [comment]
You're probably not doing it right. You have to click on the menu "Model Terms," check the box that says "Add as a polynomial" to specify which predictor needs to be squared (or cubed), then change the fitted line type to quadratic (or cubic). Once you do that, the line will bend and the tables will report the coefficient for the squared term.

**Comment by tomtomme** [comment]
Ah - sorry for the noise. This can be closed then!

**Comment by Franck6S** [comment]
Done. Thanks
![image](https://github.com/jasp-stats/jasp-issues/assets/152309774/224a4ce8-28ca-45f3-98c0-046603e60f5f)

**Comment by chrisbeardy** [comment]
does this allow for multiple independent variables and therefore multiple coefficients? e.g. A = Intercept + C*X + C*Y + C*Z + C*X^2 + C*Y^2 + C*Z^2 + C*X*Y + C*X*Z + C*Y*Z where C is a coefficient. That's what I was after.

**Comment by tomtomme** [comment]
@chrisbeardy 
Yes!

**Comment by Lia-UC** [comment]
Sorry, where can I find the features for the  linear modeling @Franck6S ?
