### ISSUE TITLE
[Bug]: Flexplot error: plot could not be edited. ! ‘x’ contains missing values

### ISSUE THREAD

**Issue by gcutt** [jasp-stats/jasp-issues#1721]
### JASP Version

0.16.2

### What analysis are you seeing the problem on?

Flexplot

### What OS are you seeing the problem on?

Windows 10

### Bug Description

Using JASP flexplot, I try to set the y-axis limits manually, and it keeps returning the error: “Unfortunately the plot could not be edited. Error message: ! ‘x’ contains missing values. If the problem persists, please report the message above at jasp-stats.org/bug-reports.” There are missing values in the plotted variable.  

### Expected Behaviour

Flexplot should allow user to specify y-axis limits even when there are missing data in the plotted variable.  

### Steps to Reproduce

1. 
2. 
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment]
Hi @gcutt, thanks for reporting this. Maybe Don knows what's up here.

**Comment by tomtomme** [comment]
@gcutt 
I tested flexplot with missing data and had no problems in jasp 0.18.3.
I tested different scales and number of missing data.
Since we had recently a big flexplot update, that may be related. 
So I am closing this one.

If this is not fixed on your side, feel free to reopen!
