### ISSUE TITLE
[Feature Request]: Categorical Variable (Covariate) within Bayesian Linear Regression

### ISSUE THREAD

**Issue by Harrie-Rose** [jasp-stats/jasp-issues#1726]
### Description

Currently, the most up-to-date version of JASP does not allow for a categorical variable to be entered as a covariate within the model. Having looked at the forums, the feature is still in development - and the solution often provided is to run an ANCOVA instead. However, the in the bayesain ANCOVA you are unable to enter continuous variable as fixed or random factors. Would you have an update on when the feature to the bayesian regression model would be completed and/or an alternative solution.

**Comment by vandenman** [comment]
> However, the in the bayesain ANCOVA you are unable to enter continuous variable as fixed or random factors.

The continuous variables should be entered as covariates and the categorical variables should be entered as fixed factors:

![image](https://user-images.githubusercontent.com/21319932/171616298-1a5609cc-eca8-4f24-b2d6-4a84b5c4d93a.png)
