### ISSUE TITLE
[Bug]: locale::facet::_S_create_c_locale name not valid

### ISSUE THREAD

**Issue by estatistics** [jasp-stats/jasp-issues#1727]
### JASP Version

0.16.2

### What analysis are you seeing the problem on?

didnt run

### What OS are you seeing the problem on?

kubuntu latest

### Bug Description

flatpak run org.jaspstats.JASP 
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid

I solved this by runnning

`export LC_ALL=C; flatpak run org.jaspstats.JASP `

and throwed some warning on the terminal

```

Making new argument list for Application startup: org.jaspstats.JASP
Starting JASP 0.16.1 from commit 028b4c149470e3e87db539892edc6428b94db758 and branch HEAD
QIBusPlatformInputContext: invalid portal bus.
QApplication: invalid style override 'GTK+' passed, ignoring it.
	Available styles: Breeze, Windows, Fusion
Application initialized
Application init entered
MainWindow constructor started
TempFiles::createSessionDir(): '/home/elias/.JASP/temp/2' about to be (removed and re)created.
Going to construct the necessary models for JASP to function.
Desktop:	Checking qm file: /app/bin/Resources/Translations/jaspDesktop-ja.qm
Desktop:	Language (59) not registered in LanguageModel, adding it now
Desktop:	Checking qm file: /app/bin/Resources/Translations/jaspDesktop-zh_Hans.qm
Desktop:	Language (25) not registered in LanguageModel, adding it now
Desktop:	Checking qm file: /app/bin/Resources/Translations/jaspDesktop-nl.qm
Desktop:	Language (30) not registered in LanguageModel, adding it now
Desktop:	Checking qm file: /app/bin/Resources/Translations/jaspDesktop-fr.qm
Desktop:	Language (37) not registered in LanguageModel, adding it now
Desktop:	Checking qm file: /app/bin/Resources/Translations/jaspDesktop-de.qm
Desktop:	Language (42) not registered in LanguageModel, adding it now
Desktop:	Checking qm file: /app/bin/Resources/Translations/jaspDesktop-es.qm
Desktop:	Language (111) not registered in LanguageModel, adding it now
Desktop:	Checking qm file: /app/bin/Resources/Translations/jaspDesktop-id.qm
Desktop:	Language (52) not registered in LanguageModel, adding it now
Desktop:	Checking qm file: /app/bin/Resources/Translations/jaspDesktop-pt.qm
Desktop:	Language (91) not registered in LanguageModel, adding it now
Desktop:	Checking qm file: /app/bin/Resources/Translations/jaspDesktop-gl.qm
Desktop:	Language (40) not registered in LanguageModel, adding it now
Desktop:	Checking qm file: /app/bin/Resources/Translations/jaspDesktop-tr.qm
Desktop:	Language 125 (tr) is not allowedDesktop:	Checking qm file: /app/bin/Resources/Translations/jaspDesktop-eo.qm
QtWebEngine::initialize() called with QCoreApplication object already created and should be call before. This is depreciated and may fail in the future.
Desktop:	Language 32 (eo) is not allowedQtWebEngine initialized
Entering eventloop
Loading required namespace: ragg
qrc:/components/JASP/Widgets/VariablesWindow.qml:34:2: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
```

### Expected Behaviour

to be run without problem

### Steps to Reproduce

1. run jasp
2. locale problem
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JorisGoosen** [comment]
@estatistics could you show me the output of `locale`?

**Comment by JorisGoosen** [comment]
Also try setting `export LANG=en` (although I would first like to see that output because this really shouldn't be happening).

**Comment by estatistics** [comment]
I commented many lines in order to speed locale generation. 
I dont know if this played a role afterwards. 
Now is running and i must do a statistical analysis.
I cannot take the risk to close it right now. But at late at night, I can try anything you say....

(jasp v.0.16.1. - How do you see version when no running? flatpak run jasp --version dont work.)

`Locale`

LANG=el_GR.UTF-8
LANGUAGE=en_US:el
LC_CTYPE="el_GR.UTF-8"
LC_NUMERIC=en_AU.UTF-8
LC_TIME=en_AU.UTF-8
LC_COLLATE="el_GR.UTF-8"
LC_MONETARY=en_AU.UTF-8
LC_MESSAGES="el_GR.UTF-8"
LC_PAPER=en_AU.UTF-8
LC_NAME=en_AU.UTF-8
LC_ADDRESS=en_AU.UTF-8
LC_TELEPHONE=en_AU.UTF-8
LC_MEASUREMENT=en_AU.UTF-8
LC_IDENTIFICATION=en_AU.UTF-8
LC_ALL=

**Comment by estatistics** [comment]
Another bug/request: jasp has no option to set different separators for csv data...

**Comment by JorisGoosen** [comment]
> Another bug/request: jasp has no option to set different separators for csv data...

Well, the code tries to detect `\t` `,` `;` `:` from the header I think. However, feel free to make a new issue for it if you think there is something wrong with that.

For now I will only focus on the issue at hand here.

To see the installed version I think you can do `flatpak list` and see the version there.

What you could already try (and it won't interfere with your running analysis) is:
- open a new terminal
- run `export LANG=en`
- run `export LC_ALL=C`
- `flatpak run org.jaspstats.JASP` and see whether it now *does* work.

**Comment by estatistics** [comment]
Update: `flatpak run org.jaspstats.JASP ` is running ok after maybe setting the locale? Dont know
"Starting JASP 0.16.1 from commit 028b4c149470e3e87db539892edc6428b94db758 and branch HEAD"

**Comment by JorisGoosen** [comment]
> Update: `flatpak run org.jaspstats.JASP ` is running ok after maybe setting the locale? 

Yeah I think so, at least, your other JASP will just keep running as it was as long as you don't close it ;)

> Dont know "Starting JASP 0.16.1 from commit 028b4c149470e3e87db539892edc6428b94db758 and branch HEAD"

But I guess this means you already tried?

**Comment by estatistics** [comment]
I did some steps before like: 
`export LC_ALL=C`
and
`LANGUAGE=`
as well commenting out lines on locale.gen of other languages except of those i wanted. 

So all of these can have affect the running behaviour of JASP. 
if you search it is a common bug. Some coders says to change c code in order not to based on locale (dont know what this means).

so you can close this bug. I set another bug about naming levels of vars.
