### ISSUE TITLE
[Bug]: Try to set name for the variables names. It exits. 

### ISSUE THREAD

**Issue by estatistics** [jasp-stats/jasp-issues#1728]
### JASP Version

0.16.1

### What analysis are you seeing the problem on?

naming variable levels

### What OS are you seeing the problem on?

kubuntu latest on bullseye 11

### Bug Description

 Try to set name for the variables names. It exits. 

### Expected Behaviour

to name var levels succesffully without exiting. 

### Steps to Reproduce

1. import c with gender 1/2 levels
2. try to name 1 to female and 2 to male
3. jasp quits
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Thanks for reporting. This crash bug on linux is also known (see https://github.com/jasp-stats/jasp-issues/issues/1360 and https://github.com/jasp-stats/jasp-issues/issues/1678) and should be fixed with upcoming 0.16.3. Also fixed with current flatpak beta.

**Comment by juliuspf** [comment]
hi @estatistics, did you check with the more recent version of JASP?
