### ISSUE TITLE
[Bug]: To set specific levels to do statistical analysis IS BUG - why u like to make my life hard?

### ISSUE THREAD

**Issue by estatistics** [jasp-stats/jasp-issues#1729]
### JASP Version

0.16.1

### What analysis are you seeing the problem on?

setting specific type of var for specific analysis

### What OS are you seeing the problem on?

kubuntu on bullseye 11

### Bug Description

I want to do a factor analysis. 
My vars are set to ordinal. 
I dont know a quick way to change 100+ vars to ratio scale. 
The same bug goes for jamovi and I HATE IT. 

Why u people try to make peoples life hard? 
Some people (including myself) dont want to be invollved about the measurement of vars. 
I know what i am doing before hand.
eg. PSPP do not have such requirement. 
I can run correlations with nominal vars or even factor analysis. 

### Expected Behaviour

to run any stat analysis irrelevant of var type of measurement set by jasp

### Steps to Reproduce

1. ordinal vars cannot participate to factor analysis (WRONG)
2. 
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Could you play with this setting please and see, if this solves your problem?
![grafik](https://user-images.githubusercontent.com/4428185/171802595-c5cb8f2c-3916-46d8-bc04-dba6040ba1b7.png)

I think setting this to the right number, should prevent your variables being detected as categorial and should set them to scale on loading / opening the data.

(The reason for the behaviour is probably that JASP and Jamovi are also made for students - to prevent them from doing some mistakes.)

**Comment by estatistics** [comment]
yes, that did it. I set it to "0".

**Comment by estatistics** [comment]
yes, that did it. I set it to "0".

**Comment by tomtomme** [comment]
Very nice! :)
