### ISSUE TITLE
Expanding the output window

### ISSUE THREAD

**Issue by DrMarkGS** [jasp-stats/jasp-issues#173]
Currently in JASP the divider between the spreadsheet and output views can easily moved and almost minimized.  It would be useful to be able to do this with the statistics options window as well to allow the full output to be easily seen, especially when the results tables are wide.  Its not too much of a nuisance when using a large PC monitor but more so on a smallish laptop.

* Enhancement:
* Output visability

**Comment by JorisGoosen** [comment]
I am assuming this is fixed now
