### ISSUE TITLE
[Bug]: By pressing compute new column JASP exits (and it is somewhat hard to take the mean)

### ISSUE THREAD

**Issue by estatistics** [jasp-stats/jasp-issues#1732]
### JASP Version

0.16.1

### What analysis are you seeing the problem on?

to compute a new variable (mean)

### What OS are you seeing the problem on?

kubuntu on bullseye 11

### Bug Description

By pressing compute new column JASP exits (and it is somewhat hard to take the mean).
I created a new column, then i "press" "+" and "variables", and then "means" and then compute and then jasp exits

ps. you must press an additional "+" in order to put parenthesis in order to be able to transfer the whole equation inside the "mean" formula, otherwise the last variable outside parenthesis is out.

### Expected Behaviour

to compute the mean of the new variable

### Steps to Reproduce

1. created a new column
2. "press" "+" and "variables", and then "means"
3. then compute and then jasp exits
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Thanks for reoorting. This crash bug on linux is known and should be fixed with upcoming 0.16.3

**Comment by tomtomme** [comment]
You can already try the flatpak beta here, which fixed it for me on manjaro: 
```
sudo flatpak remote-add flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
sudo flatpak install flathub-beta org.jaspstats.JASP
flatpak run --branch=beta org.jaspstats.JASP
```

**Comment by estatistics** [comment]
```
sudo flatpak remote-add flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
error: Can't load uri https://flathub.org/beta-repo/flathub-beta.flatpakrepo: TLS support is not available

```

**Comment by estatistics** [comment]
"For example, if the OpenSSL library installed on your Linux system does not support TLSv1.3, then the above command’s output will not display TLS v1.3 and your web servers running on this system will not be able to support TLS v1.3."

**Comment by estatistics** [comment]
openssl ciphers -v | awk '{print $2}' | sort | uniq
SSLv3
TLSv1
TLSv1.2
TLSv1.3

**Comment by estatistics** [comment]
"bug" here: https://github.com/flatpak/flatpak/issues/1207

**Comment by tomtomme** [comment]
Interesting - I never saw one of those error messages on manjaro however. My machine also:
```
openssl ciphers -v | awk '{print $2}' | sort | uniq
SSLv3
TLSv1
TLSv1.2
TLSv1.3
```

**Comment by estatistics** [comment]
Updating / reinstalling glib network, glib utls, ca certificates not solved the problem.

`curl -o flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo`
`sudo flatpak remote-add --if-not-exists flathub --from flathub.flatpakrepo`

and WITHOUT SUDO (otherwise TLS error is thrown)

` flatpak install flathub-beta org.jaspstats.JASP`
and voila.... it is downloading / installing.....

**Comment by tomtomme** [comment]
good to know. Manjaro required the sudo for some things to work out for me. Distro specifics ...

**Comment by estatistics** [comment]
(Beta version) Computed only the first row..... the rest of values?   
F1 + F2 must result 2, not 6.31.... it is like that computed the total mean of both columns (????)
I dont know how to add values inside mean without "+"..... what is the proper way? 
[](https://i.postimg.cc/4NCYsMVG/119.jpg)

**Comment by tomtomme** [comment]
You need to go with the R Interface in JASP here. This is the R Code you may need: 
`apply(data.frame(var1, var2, var3), 1, mean, na.rm=TRUE)`
JASP can manipulate and compute column-wise but noc yet row-wise. This will be implemented hopefully this year, when the editor-mode of JASP is done. Until then, this R Code snipet should do the trick.

**Comment by JorisGoosen** [comment]
@estatistics did you also follow the steps at: https://flatpak.org/setup/Ubuntu

Because ubuntu is usually quite a bit out of date with regards to `flatpak` and this might very well be the cause of some of the problems.

However, it is a little bit unclear what this issue is about right now.
The original crashing problem is solved by 0.16.3 and I guess this is now about having row-wise operations in computed-columns etc?

**Comment by tomtomme** [comment]
I confirm, the crashing is a non issue anymore. 
We may relable this to feature-request until things like apply(data.frame(var1, var2, var3), 1, mean, na.rm=TRUE) are possible with the point & click interface.

**Comment by richlv** [comment]
I guess computing mean across columns would be #516.

**Comment by tomtomme** [comment]
as an update on this issue:
next jasp version will present the row functions also in the drag and drop GUI, see
https://github.com/jasp-stats/jasp-desktop/pull/5826#pullrequestreview-2735732572
