### ISSUE TITLE
Mann-Whitney 

### ISSUE THREAD

**Issue by PerPalmgren** [jasp-stats/jasp-issues#1735]
### Description

The abbreviated Mann-Whitney statistics

### Is your feature request related to a problem?

No

### Describe the solution you would like

I think it is confusing (and especially my students) with the abbreviated statistic depicted in JASP when running a Mann-Whitney test (see picture). I think it would make more sense (especially pedagogically) to use the abbreviation "U" for a Mann-Whitney test statistic and the abbreviation "W" for the Wilcoxon- signed rank test statistic. Thes a rather commonly used in statistics. I know there are some different thoughts on how these tests should be named but I think clarity is more important.

### Additional context

![Namnlös](https://user-images.githubusercontent.com/79397662/171859896-19b1fd48-769a-4b39-95b3-189613cfe6ef.png)

**Comment by PerPalmgren** [comment]
@juliuspfadt Was this changed in the latast 017.1 version?

**Comment by juliuspfadt** [comment]
Not to my knowledge, but I have also not heard from the maintainers if they wanted to commit to doing this. I have no thoughts on the subject, so it makes sense to wait for @vandenman to reply.

**Comment by PerPalmgren** [comment]
@vandenman 
 I think it would make more sense (especially pedagogically) to use the abbreviation "U" for a Mann-Whitney test statistic and the abbreviation "W" for the Wilcoxon- signed rank test statistic.

**Comment by EJWagenmakers** [comment]
I believe this is a recurring discussion. @JohnnyDoorn had an opinion on the matter I believe....

**Comment by JohnnyDoorn** [comment]
Hi @PerPalmgren ,

The reason why we use W to denote the test statistic is to stay consistent with the R output of the wilcox.test function, where the test statistic is W: the sum of the ranks, with the minimum subtracted. However, I don't have a strong opinion on how the statistic is denoted, and using U might be more consistent with the test name and Wikipedia. And if you think it will help students be less confused, I'm all for it!

Cheers
Johnny

**Comment by PerPalmgren** [comment]
Hi guys @JohnnyDoorn @vandenman @EJWagenmakers 
The literature is not unanimous about the definition and naming of the Mann-Whitney tests. Like you say the Mann-Whitney U test goes under a myriad of names (in Wikipedia including Wilcoxon rank-sum test making it more confusing, as it is language wise very similar to Wilcoxon´s signed rank, used for dependent samples). To facilitate for JASP users and other stakeholders I think it would be wise to use the U as an abbreviation for the statistic produced by the Mann-Whitney test, and the W as an abbreviation for the statistic produced by the Wilcoxon´s signed rank test.
All the best and have a great week.
Per😜

**Comment by tomtomme** [comment]
@JohnnyDoorn 
Is this a wontfix?

**Comment by PerPalmgren** [comment]
And W for Wilcoxon 🤪
