### ISSUE TITLE
[Bug]: "HDInterval failed" when installing developer module of LearnBayes

### ISSUE THREAD

**Issue by Jiashun97** [jasp-stats/jasp-issues#1739]
### JASP Version

Others

### Commit ID

d10ccb499154c8a0887a2b7c8a5f8ba30b650ff0

### JASP Module

jaspLearnBayes

### What analysis are you seeing the problem on?

Installation

### What OS are you seeing the problem on?

macOS Monterey 12.2.1

### Bug Description

I encountered a bug when I was installing the developer module of "LearnBayes"
![Screen Shot 2022-05-31 at 5 49 31 PM](https://user-images.githubusercontent.com/65221219/172360847-f42fd427-4965-4d83-8991-a4bb3dcbb8c3.png)
.

### Expected Behaviour

It should be successfully installed.

### Steps to Reproduce

1. Navigate to the developer folder (https://github.com/Jiashun97/jaspLearnBayes/tree/fixes-buffons-needle4)
2. Install the developer module
3. 
...

### Log (if any)

[JASP 2022-06-06 17_12_27 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/8852452/JASP.2022-06-06.17_12_27.Engine.0.log)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JorisGoosen** [comment]
The problem seems related to running permissions:
```
Installing HDInterval [0.2.2] ...
	FAILED
Error installing package 'HDInterval':
======================================

sh: /Applications/JASP.app/Contents/Frameworks/R.framework/Versions/4.1-arm64/Resources/bin/R: Permission denied
[1] "Installed HDInterval to '/Users/jiashunwang/Library/Application Support/JASP/JASP/Modules/DevelopmentModule/.renv/1/HDInterval', now running post install fixes."
```

**Comment by JorisGoosen** [comment]
Have you tried the latest `development` nightly?

As in, the bug you see above I solved through: https://github.com/jasp-stats/jasp-desktop/commit/029cc2e37ab5bdb302463a27a7806400c4173260

However, that just leads to another problem that looks like:
https://github.com/jasp-stats/jasp-desktop/commit/029cc2e37ab5bdb302463a27a7806400c4173260

At least it does for @Jiashun97 ... 

It works on my system (at least when I just tried it now) and it might be good to check on intel as well, so if you could try that might be helpful.

**Comment by juliuspf** [comment]
The development version is older than the release version, isn't it? I tried the latest development nightly, but the installation still fails, if you require some logs, let me know

**Comment by juliuspf** [comment]
> However, that just leads to another problem that looks like: [jasp-stats/jasp-desktop@029cc2e](https://github.com/jasp-stats/jasp-desktop/commit/029cc2e37ab5bdb302463a27a7806400c4173260)

what do you mean by this?

**Comment by Kucharssim** [comment]
@JorisGoosen installation of development modules still fail on development (at least on Intel), I shared logs in Slack: https://pml-uva.slack.com/archives/CV655R7QS/p1655108848078389?thread_ts=1654700619.241799&cid=CV655R7QS

**Comment by tomtomme** [comment]
@Jiashun97 
could you re-test with jasp 0.18.3?
