### ISSUE TITLE
[Feature Request]: Merging data

### ISSUE THREAD

**Issue by ClaraIsabell** [jasp-stats/jasp-issues#1744]
### Description

Merging data files

### Purpose

Analyses with data from different/repeated measurements

### Is your feature request related to a problem?

No.

### Describe the solution you would like

Data merging like in SPSS for example (merging files by key variable)

**Comment by juliuspf** [comment]
hi @ClaraIsabell, thanks for the request. @JorisGoosen is this something that is feasible?

**Comment by JorisGoosen** [comment]
Would this be related to https://github.com/jasp-stats/jasp-issues/issues/33 ?

Because I hope to finally get this working with the new data-editing support that will be coming in an upcoming release.

**Comment by tomtomme** [comment]
@JorisGoosen 
This tutorial shows, how it is done in SPSS: https://ezspss.com/merging-files-in-spss/
