### ISSUE TITLE
[Feature Request]: Polychoric Correlation Matrix

### ISSUE THREAD

**Issue by khh200** [jasp-stats/jasp-issues#1746]
### Description

It would be lovely to be able to call for Polychoric Correlation matrices to aid in the reproducability of categorical SEM.

### Purpose

To include polychoric correlation matrices in publications to aid with reproducability.

### Use-case

To include polychoric correlation matrices in publications to aid with reproducability.

### Describe the solution you would like

I would like for a polychoric correlation section to be added in either the correlation or SEM function. The psych package's polychoric produces such matrices.

### Describe alternatives that you have considered

The polycor package is another option a swell.

**Comment by juliuspf** [comment]
Hi @khh200, thanks for the request. This should probably go into the correlation analysis then.

**Comment by tomtomme** [comment]
@khh200 
This is implemented, see https://github.com/jasp-stats/jasp-issues/issues/893
If this does not suffice for you feel free to reopen!
