### ISSUE TITLE
[Bug]: 0.16.2 & 0.16.3 Font not displaying correctly on Windows 10

### ISSUE THREAD

**Issue by secircle** [jasp-stats/jasp-issues#1747]
### JASP Version

0.16.2

### JASP Module

jaspRegression

### What analysis are you seeing the problem on?

Linear Regression, but I think this is not limited to the regression

### What OS are you seeing the problem on?

Windows 10; 10.0.19044 Build 19044

### Bug Description

Hi,
 
I would like to report a bug with the font display on 0.16.2. I upgraded from 16.1 to 16.2, and immediately noticed that numbers are not displaying correctly. Please see the attached ppt file (I used screen capture). So I uninstalled 16.2 immediately, and reinstalled 16.1. And it fixed the problem. I also attached the screen capture of 16.1. As you can see from the clock (right bottom), it happened in 14 minutes, from the same laptop. 

[JASP 0.16.2 bug report.pptx](https://github.com/jasp-stats/jasp-issues/files/8913301/JASP.0.16.2.bug.report.pptx)

Below is my system info. 

OS Name	Microsoft Windows 10 Home
Version	10.0.19044 Build 19044
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	*****
System Manufacturer	Dell Inc.
System Model	XPS 13 9310 2-in-1
System Type	x64-based PC
System SKU	*****
Processor	11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz, 2803 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	Dell Inc. 2.9.0, 3/17/2022
SMBIOS Version	3.2
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	Dell Inc.
BaseBoard Product	*****
BaseBoard Version	*****
Platform Role	Mobile
Secure Boot State	On

Thank you.

### Expected Behaviour

The numbers should not be mushed. I should be able to read them with clarity.

### Steps to Reproduce

1. Run any data analysis on Windows 10
2. 
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JorisGoosen** [comment]
Also try resetting your zoom-level (with `Ctrl + 0`)

**Comment by JorisGoosen** [comment]
@secircle could you perhaps attach the screenshot as a `png` file?

**Comment by JorisGoosen** [comment]
You can do so with paint for instance

**Comment by secircle** [comment]
Sure absolutely. I created two screenshots, one with Arial and the other with SegueUI
![JASP0 16 3_Arial](https://user-images.githubusercontent.com/57462288/175415670-bc55c8ec-4b2e-4876-b841-d38d1e91c9e4.png)
![JASP0 16 3_SegueUI](https://user-images.githubusercontent.com/57462288/175415679-1034543c-3a1d-4fcc-8905-6f9f0c65491f.png)

**Comment by boutinb** [comment]
Do you have a High DPI monitor (retina display) ?

**Comment by shun2wang** [comment]
This may be an issue with Chromium font rendering for a long time, on some high DPI devices and devices with hardware rendering enabled, there may be cases where text looks fuzzy or blurry (because JASP result page is build on Qt6-Qt WebEngine and the latter is based on Chromium project).

so @secircle  you can try to fix it according to the following [information](https://support.google.com/chrome/answer/95290?hl=en) and feedback here. thanks

**Comment by secircle** [comment]
Thank you both. Both are XPS13 laptops (full HD resolution). They are not retina displays. The cleartype adjustment did not fix the issue. 

IMPORTANT CLUE!!!: I did not have this issue with 0.16.1. When I uninstalled 0.16.2 and rolled it back to 0.16.1, the problem disappeared. So there should be something that happened between 0.16.1 and 0.16.2.

**Comment by secircle** [comment]
Hi I just rolled back from 0.16.3 to 0.16.1 because I need to use screen capture of the JASP for my work. 
Again, rolling back to 0.16.1 solved the issue. I attached the screenshots, taken before the roll back and after the new installation. I hope the dev team can look into this for PC users.

[JASP 0.16.3 Before rollback]
![JASP 0 16 3_Screenshot 2022-07-14 124519](https://user-images.githubusercontent.com/57462288/179039476-e372a6e3-02ad-4555-a09d-0910958cbc25.png)
![JASP 0 16 3 Screenshot 2022-07-14 124413](https://user-images.githubusercontent.com/57462288/179039479-81d19055-cd4b-4512-a0a1-b651a0340c0b.png)

[JASP 0.16.1 after rollback]
![JASP 0 16 1 Screenshot 2022-07-14 125738](https://user-images.githubusercontent.com/57462288/179039466-28c5f15e-649c-4262-ac52-86090d6ae18b.png)
![JASP 0 16 1 Screenshot 2022-07-14 125759](https://user-images.githubusercontent.com/57462288/179039473-4bfb0c4b-80a6-4639-9e37-f7afef12a28f.png)

**Comment by JorisGoosen** [comment]
If what @shun2wang mentions about hardware rendering in chromium is the culprit it should be easy to mitigate by turning on "Safe Graphics" in Advanced Preferences.
This will also turn on software rendering in the webengine and thus hardware rendering *off*.

For us to fix this problem (if it is in chromium) is not really feasible though... 

The reason it started happening from 0.16.2 is because we upgraded Qt to 6.2 then because it fixes many problems we had. And apparently this bug is in there but we cannot revert to the older version of qt.

**Comment by secircle** [comment]
Three weeks ago I followed @shun2wang suggestion and turned on the Safe Graphics. However, if I remember correctly, it did not fix the problem. Moreover, it made other programs look bad. Unless I use a JASP on a dedicated PC, I don't think this can be a viable option even if it can solve the problem. Too bad that this issue cannot be addressed for now. I understand the tradeoffs during the development process. I guess I should use 0.16.1 for now. Did you get any feedback from other PC users? Are there any other PC users experiencing a similar issue?

**Comment by secircle** [comment]
Thanks @JorisGoosen 

Safe graphics mode did not improve the rendering. I tested this with my other Dell XPS13 laptop (Windows 10; 1080p resolution) with JASP 0.16.3 version just now. Below I tested with Safe Graphics mode on or off on JASP & smoothing edges option on Windows 10 as suggested by @shun2wang.

*Safe Graphics Off
![JASP 0 16 3 Safe Graphics Off Screenshot 2022-07-14 165316](https://user-images.githubusercontent.com/57462288/179085225-4dea5004-73d8-4089-84c2-ab47d2741362.png)
![JASP 0 16 3 Safe Graphics Off Screenshot 2022-07-14 165240](https://user-images.githubusercontent.com/57462288/179085227-5d4084a7-e223-4b98-b79d-f06fc7185493.png)

*Safe Graphics On
![JASP 0 16 3 Safe Graphics On Screenshot 2022-07-14 165033](https://user-images.githubusercontent.com/57462288/179085228-9cf5ba60-4618-4424-8951-af3235e57ce7.png)
![JASP 0 16 3 Safe Graphics On Screenshot 2022-07-14 164940](https://user-images.githubusercontent.com/57462288/179085219-51e12bf6-95fd-4a12-b9d8-67188acfeda5.png)

*Smooth Edges on Windows 10 On or Off
![JASP 0 16 3 Smooth Edges On Screenshot 2022-07-14 165743](https://user-images.githubusercontent.com/57462288/179085220-48c4259c-4c61-470b-a3e3-22f765ead2d5.png)
![JASP 0 16 3 Smooth Edges Off Screenshot 2022-07-14 165637](https://user-images.githubusercontent.com/57462288/179085222-b11c3157-2501-4fbe-a9e8-eb07835f13a7.png)
![JASP 0 16 3 Smooth Edges Off Screenshot 2022-07-14 165520](https://user-images.githubusercontent.com/57462288/179085223-6289efe2-d067-42de-b885-9b9b477f20c4.png)

**Comment by boutinb** [comment]
Hi @secircle , Could you export the result as html and pdf files, and check whether you have the same problem when visualising these files with your browser?

**Comment by boutinb** [comment]
I have now a Windows 11 machine where I can reproduce your problem. I still don't understand why the rendering is so bad, but I noticed that when I set JASP to have the whole screen, then is the rendering much better (with still sometimes some blue letters). Do you have the same behaviour?

**Comment by secircle** [comment]
@boutinb Glad to hear that you were able to replicate the same issue on Windows 11. It is interesting to hear that both Windows 10 & 11 experience the same issue across different hardware.

In terms of full screen, all of my screenshots were taken in full-screen mode. So, I can confirm that the problem still exists with the full-screen mode.

**Comment by boutinb** [comment]
So after quite some research, I can reproduce this problem with a small application directly with Qt (the platform we use to build JASP). I could not find a workaround, but I have submitted a bug issue by Qt. Hopefully they can help us soon.

**Comment by secircle** [comment]
Thank you @boutinb Glad to hear that you submitted the bug issue to Qt. I hope they can look into this issue soon.

**Comment by boutinb** [comment]
A workaround has been found (at least working on our Windows machine) and a new (beta) version has been made: https://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-stable-8a016cb625c4ec0b3c9b5d9942696e3accdba9b0.msi
@secircle could you try this version?

**Comment by JorisGoosen** [comment]
@boutinb why reopen it?

Also the workaround is fairly good but only works like 90% of the time (as in, of the horizontal position of the results).
But it should be easy to get the output to look good and thus we have something untill Qt fixes the real problem.

**Comment by secircle** [comment]
Thank you @boutinb for the update. I uninstalled the previous 0.16.3 and installed the one you suggested. It seems the new version fixed the problem! Thank you so much for the hard work. See the screenshots below. 

However, I also found that the JASP doesn't function correctly when I readjust the figure size. I don't know why this is happening so I would like to share the screenshots with the error codes.

![Screenshot 2022-08-16 142556](https://user-images.githubusercontent.com/57462288/184952976-fac36b11-f579-4954-9779-8c431c59d810.png)
![Screenshot 2022-08-16 142622](https://user-images.githubusercontent.com/57462288/184953000-5be390a5-772e-42f8-80b5-ab1f2365c0d9.png)
![Screenshot 2022-08-16 142642](https://user-images.githubusercontent.com/57462288/184953014-4fd4ba6d-0140-44a7-aea7-5d50907e0bdc.png)

Below, I started from a fresh CSV file, and tried to run the same ANOVA analysis.
![Screenshot 2022-08-16 142746](https://user-images.githubusercontent.com/57462288/184953027-ca2522ab-f809-4807-ac96-2a0edf3e4176.png)

**Comment by JorisGoosen** [comment]
@secircle ah yes I just fixed that bug.

In general, that is a good reason to work with official releases but I can imagine the bug is rather ugly to look at...
Newer versions will appear at [our nightlies page](https://static.jasp-stats.org/Nightlies/) under "Windows ZIP/MSI"

So you can try a later one and then the analyses should actually run ^^
However there is no guarantee that jaspfiles made with these versions can be loaded properly with official releases (although it will probably be alright) and there might be some other new stuff in there that wasn't tested enough yet.

**Comment by secircle** [comment]
Thank you, @JorisGoosen I appreciate it!
