### ISSUE TITLE
[Feature Request]: Exporting Results From Analyses in R-Friendly Structure

### ISSUE THREAD

**Issue by NegativePotato** [jasp-stats/jasp-issues#1750]
### Description

Exporting Results in R-Friendly Structure

### Purpose

Export the results from the analyses in a structure that can be then loaded in R to be then used in markdown text or directly integrated in plots. Then the values can be automatically updated with new data incoming, or corrections being applied to the dataset.

### Use-case

Example : After a Repeated Bayesian ANOVA, export the results of the post-hoc comparisons if relevant, load that structure in your R or MD script, and thus update the values where they are presented.

### Is your feature request related to a problem?

No

### Describe the solution you would like

An export button with the results being neatly compiled 

### Describe alternatives that you have considered

I have written a script that parses the HTML result export from JASP to get this info and it works well! But I'm sure you would be able to come up with a much better solution ^^ Also I'd be happy to share what I'm written so far if it may help..

**Comment by boutinb** [comment]
We are busy to make our analyses directly available in R, with a R syntax generated from JASP. Should arrive over some months

**Comment by tomtomme** [comment]
@NegativePotato 
Since R-Syntax mode is done, I think we can close this. If I am mistaken, feel free to reopen!
