### ISSUE TITLE
[Feature Request]: Add info about uninstall to linux installation guide

### ISSUE THREAD

**Issue by 3TInfoTinker** [jasp-stats/jasp-issues#1752]
### Description

As a newbie in all aspects, I was unable to get JASP active on my Ubuntu desktop and wanted to uninstall it. For this, I've searched the web for a pretty while but nothing to enable me for the removal nor in the repository of jasp-stats.

### Purpose

Needed guidance to uninstall the JASP

### Use-case

After updating it went invisible. 

### Is your feature request related to a problem?

Couldn't get the jasp in action after the update.

### Describe the solution you would like

needed to know the steps for removal of jasp

### Describe alternatives that you have considered

Then; I just used the basic instinct to remove it using the terminal with the following:

👉   ~$ flatpak remove org.jaspstats.JASP   ↵

It removed:

-    ID                                                 Branch      Op
 1. [-] org.jaspstats.JASP                    stable        r
 2. [-] org.jaspstats.JASP.Locale         stable        r

Uninstall complete.

Next, I used:

👉   ~$ flatpak remove --all --delete-data  ↵

 ID                                                                                                                     Branch              Op
 1. [-] org.freedesktop.Platform.GL.default                                                          20.08               r
 2. [-] org.freedesktop.Platform.GL.default                                                          21.08               r
 3. [-] org.freedesktop.Platform.VAAPI.Intel                                                         20.08               r
 4. [-] org.freedesktop.Platform.VAAPI.Intel                                                        21.08               r
 5. [-] org.freedesktop.Platform.openh264                                                             2.0                 r
 6. [-] org.gtk.Gtk3theme.Yaru                                                                                3.22               r
 7. [-] org.kde.Platform                                                                                           5.15               r
 8. [-] org.kde.Platform.Locale                                                                                5.15                r
 9. [-] org.kde.Platform                                                                                            6.2                 r
10. [-] org.kde.Platform.Locale                                                                                6.2                 r
11. [-] org.kde.PlatformTheme.QGnomePlatform.Sources                                     5.15                r
12. [-] org.kde.PlatformTheme.QGnomePlatform.Sources                                    6.2                 r
13. [-] org.kde.PlatformTheme.QGnomePlatform                                                   5.15                r
14. [-] org.kde.PlatformTheme.QGnomePlatform                                                  6.2                 r
15. [-] org.kde.PlatformTheme.QtSNI.Sources                                                      5.15                r
16. [-] org.kde.PlatformTheme.QtSNI                                                                    5.15                r
17. [-] org.kde.WaylandDecoration.QGnomePlatform-decoration                         5.15                r
18. [-] org.kde.WaylandDecoration.QGnomePlatform-decoration                          6.2                 r
19. [-] org.kde.WaylandDecoration.QGnomePlatform_decoration.Sources           5.15                r
20. [-] org.kde.WaylandDecoration.QGnomePlatform_decoration.Sources           6.2                 r

Uninstall complete.

**Delete data for org.freedesktop.Platform.GL.default? [y/n]: y
Delete data for org.freedesktop.Platform.GL.default? [y/n]: y
Delete data for org.freedesktop.Platform.VAAPI.Intel? [y/n]: y
Delete data for org.freedesktop.Platform.VAAPI.Intel? [y/n]: y
Delete data for org.freedesktop.Platform.openh264? [y/n]: y
Delete data for org.gtk.Gtk3theme.Yaru? [y/n]: y
Delete data for org.kde.Platform.Locale? [y/n]: y
Delete data for org.kde.Platform.Locale? [y/n]: y
Delete data for org.kde.Platform? [y/n]: y
Delete data for org.kde.Platform? [y/n]: y
Delete data for org.kde.PlatformTheme.QGnomePlatform.Sources? [y/n]: y
Delete data for org.kde.PlatformTheme.QGnomePlatform.Sources? [y/n]: y
Delete data for org.kde.PlatformTheme.QGnomePlatform? [y/n]: y
Delete data for org.kde.PlatformTheme.QGnomePlatform? [y/n]: y
Delete data for org.kde.PlatformTheme.QtSNI.Sources? [y/n]: y
Delete data for org.kde.PlatformTheme.QtSNI? [y/n]: y
Delete data for org.kde.WaylandDecoration.QGnomePlatform-decoration? [y/n]: y
Delete data for org.kde.WaylandDecoration.QGnomePlatform-decoration? [y/n]: y
Delete data for org.kde.WaylandDecoration.QGnomePlatform_decoration.Sources? [y/n]: y
Delete data for org.kde.WaylandDecoration.QGnomePlatform_decoration.Sources? [y/n]: y
Delete data for org.jaspstats.JASP? [y/n]: y
------------------------------**
👆  I got it removed. And it's because of my system i.e. my system doesn't support it.

**Comment by JorisGoosen** [comment]
So what you are trying to achieve by this issue is us adding the remove command to [our linux guide](https://jasp-stats.org/linux-installation-guide/)?

As in, I guess it might be useful if it was so hard to discover?

Also, when you are installing jasp via flatpak on ubuntu it is very much recommended to follow: https://flatpak.org/setup/Ubuntu (although that might not have helped in your case because I have no inkling what the problem might have been)

**Comment by JorisGoosen** [comment]
Ive just updated the guide so I hope this will save somebody some trouble in the future ^^
