### ISSUE TITLE
[Feature Request]: Standard errors, p-values and confidence intervals for path coefficients in SEM-mediation

### ISSUE THREAD

**Issue by wave-form** [jasp-stats/jasp-issues#1753]
### Description

The SEM-mediation program generates text output with direct and indirect effects, in addition to a graphic path model with path coefficients. Would it be possible to get a table of the various path coefficients with either 95% confidence intervals or p values?  

### Purpose

To be able to conduce null hypothesis significance testing of the IV-M and M-DV assocaitions in a mediation model.

### Is your feature request related to a problem?

Problem: Inability to determine if IV-M and M-DV associations are statistically significant in mediation models that involve multiple mediators and covariates. 

### Describe the solution you would like

An additional table of output that contains individual path coefficients and their 95% CIs and/or associated p values. It would also be nice if the path figure that is generated in the output could be resized to make it easier to read the path coefficients in mediation models that have multiple mediators.

### Describe alternatives that you have considered

The obvious is going into lavaan and running the model, but that more or less defeats the purpose of JASP.

**Comment by Kucharssim** [comment]
Dear @wave-form,

thank you for the request, this feature will be available in the next release!
