### ISSUE TITLE
[Feature Request]: Splitting descriptive plots by more factors

### ISSUE THREAD

**Issue by bjtrbjtr** [jasp-stats/jasp-issues#1754]
### Description

Allow plots from factorial ANOVAs to be split up by >2 factors. 

### Purpose

Allow viewing/presentation of results without collapsing conditions. Make JASP's plotting abilities parallel to analysis abilities for factorial designs. 3- and 4-way factorial designs are commonly run and JASP analyzes them easily, but cannot plot them in a way that allows full examination of results when there are 3-way or higher interactions.

### Use-case

It is pretty common to run 3-way or even 4-way factorial designs. Right now, JASP allows plotting where results are split along one factor into separate lines, and along a second factor into separate plots. To the best of my knowledge, there is no way to split the results again by a third or fourth factor. Any analysis of a factorial design with >2 factors could benefit from this feature.

### Is your feature request related to a problem?

Nope - just a request for a cherry on top of the ice cream!

### Describe the solution you would like

Specifically, the Descriptive Plots feature allows assignment of one factor to separate lines, and a second factor to separate plots. Ideally, assigning multiple factors to both separate plots and separate lines would be implemented (and, for separate lines, factors would be indicated such that one factor controlled line color, a second factor controlled solid/dashed/dotted/etc lines, a third factor controlled marker shape, and a fourth factor controlled open vs closed markers).

### Describe alternatives that you have considered

Separate plots may be simpler to implement, and would be a great solution even if separate lines were not feasible. Right now, I typically plot results in other software (like Excel) to circumvent this issue, but it would be really nice to have it all in JASP.

**Comment by juliuspf** [comment]
is this feasible @JohnnyDoorn?

**Comment by tomtomme** [comment]
@bjtrbjtr 
Note that this is already possible with flexplot from jasps visual modeling module. 
However, it sure would be nice, to extend those capabilities to other modules, so this stays on the ToDo list.

Also this is very much related to this request: https://github.com/jasp-stats/jasp-issues/issues/1757

**Comment by tomtomme** [comment]
Closing, since issue transferred to #1757, which is essentially the same, just for rainclouds.
