### ISSUE TITLE
[Feature Request]: More complex raincloud plots

### ISSUE THREAD

**Issue by kevinvschie** [jasp-stats/jasp-issues#1757]
### Description

You can only create very basic raincloud plots. For instance, for a within-between interaction (each factor having two levels; let's say time [pre to post] and treatment [A or B]) JASP creates two separate raincloud plots (separated by the indicated factor). However, ideally you'd want to have this all in one graph (instead of two). Related to this is that raincloud plots can only be created for designs with two factors. It is simply impossible to visualize a threeway interaction, because you always have to leave one factor out.

### Purpose

better visualize the data

### Describe the solution you would like

The ability to visualize data using raincloud plots for (a) designs more than two factors and (b) the ability to integrate raincloud plots in one graphs instead of having multiple separate ones.

**Comment by iandol** [comment]
Obviously it seems @jorvlan is perfect for this feature given https://github.com/jorvlan/raincloudplots :-) — it would indeed be truly wonderful to be able to have a GUI module interface to his flexible library to do 1x1 2x2 2x3 with the various great layout options he has provided as checkboxes… ❤️ 

This could be separated as a new module from the basic options already available in the standard modules to allow a more complete GUI without interrupting the ttest / anova etc options?

**Comment by vincentott** [comment]
The raincloudplots module Im working on can handle two factorial designs with varying levels.
Thus, pre/post experimental/control is possible to visualize in one plot.
Similarly, it should also handle a 4x3 design etc.
I don´t think I will have the time to build something for designs with more than 2 factors.

On the other hand, the module will hopefully be released in the near future.

**Comment by tomtomme** [comment]
@kevinvschie 
The new raincloud module is now in 0.19 beta!
To test it yourself you could get the latest beta from here: https://static.jasp-stats.org/Nightlies/
Please reopen if you think, that this does not solve the issue!!
