### ISSUE TITLE
Request: Block Function for Hierarchical Linear Regression

### ISSUE THREAD

**Issue by abswan** [jasp-stats/jasp-issues#176]
## Template for enhancement requests
 

* Enhancement: In SPSS, there is an ability to define fully each step in a block format in a Stepwise or Hierarchical Linear Regression. For example, if I only want one variable in the equation in the first model, then I add in one more in the next block, then in the third block I add in a third predictor variable. From what I can tell in JASP 0.9.0.1, you can specify at least one variable as the "null model", but then every other covariate is lumped into a second model (i.e., you can't have more than 2 models from what I can tell). Using the Stepwise enter method, rather than Enter, I was not able to go beyond two models (so my third predictor variable seems to be missing in the output).

* Purpose: Make the regression process fuller and more similar to SPSS, giving researchers better control of their analyses to test hypotheses and theories. This would also make seeing R-squared changes easier for each model block

**Comment by infiniteline** [comment]
Agreed. Having the capability to add additional models is needed.

**Comment by atefertiller** [comment]
This functionality is needed.

**Comment by chantelanuit** [comment]
The implementation of blocks in JASP is not optimal presently. However, there is a possibility to use more than 2 blocks if the LR analysis is repeated. For instance, imagine you have a model with intraversion, extraversion, and openness and you would like to predict a criterion. In step 1, you include intraversion and extraversion in the covariates. You specify also that intraversion is in the null model (in the Model tab). That way, you have model 1 with intraversion only and model 2 with intraversion and extraversion. Then, you redo a regression analysis, but you include both intraversion and extraversion in the null model and openness in the H1 model. That way you have a three blocks model. This is not straightforward, but it works.

**Comment by TarandeepKang** [comment]
Dear team, I agree with the other commenters here that allowing entry of predictors in blocks, to conduct hierarchical regression is important, and much needed new feature. Do you have any updates?

**Comment by Arwa-AA** [comment]
Hi All,

Sorry to re-open this old post. would like to ask if there is a workaround to do a hierarchical regression with more than 2 blocks in JASP?

Thank you

**Comment by tomtomme** [comment]
@abswan & others
This is on the ToDo list, but no timeline, sorry.

**Comment by JohnnyDoorn** [comment]
I am currently implementing this feature - it will be in the next JASP release (scheduled for May). Sorry for the long waiting time!

**Comment by TarandeepKang** [comment]
Thank you very much for this @JohnnyDoorn! The wait has been worth it! I realise it's somewhat of an old-fashioned method, and these days more modern approaches like regularisation are preferred. That being said, I wonder if the team has any plans to allow the same kind of block flexibility in other regression models. I think even the evil IBM contraption at least allows this for binary logistic regression, too.
