### ISSUE TITLE
[Feature Request]: addition to the descriptive boxplot

### ISSUE THREAD

**Issue by PerPalmgren** [jasp-stats/jasp-issues#1764]
### Description

The addition of a mean-line to boxplotsin the descriptive module.

### Purpose

When inspecting the shape/distribution of the data it is rather common to look at the data numerically (by comparing mean vs median and look at skeweness and kurtosis), statistically (SW-test) and visually (looking an histograms and boxplots), I think it would be very beneficial for JASP users to be able in the descriptive module and customizable plots to select (by clicking) adding a "mean-line" . This could really facilitate the analysis. and also pedagogical for statistical learners.

### Is your feature request related to a problem?

No but an enhancement!

### Describe the solution you would like

This is possible to add in R: https://r-coder.com/boxplot-r/

**Comment by PerPalmgren** [comment]
Hi,
Is this something likely to come as a new feature in the near future?
All the best 
Per😎

**Comment by EJWagenmakers** [comment]
Not sure...I think that when it comes to the Descriptives, I see many areas of improvement that are more fundamental...but we'll keep it in mind

**Comment by PerPalmgren** [comment]
@EJWagenmakers @tomtomme 
Hi,
I think this added feature to Box plots in the JASP Descriptive module would be a great improvement both statically, scientifically and pedagogically.
Wish you a great summer.
Per "the JASP lover"

**Comment by EJWagenmakers** [comment]
This should be possible in the new "Raincloud plot" submodule in the revamped Descriptives module. Please reopen if you had something else in mind.

**Comment by PerPalmgren** [comment]
@EJWagenmakers 
That is great. But it is very cumbersome when you run an EDA to have to open a new analysis. Would it not be possible in JASP to also include just a simple button for the arithmetic mean under "Customizable plots" - "Box plots" - "Label outliers" in Descriptives? Similar how it is done in Jamovi or automatically produced in DATAtab!
All the best.
Per " the JASP lover"
