### ISSUE TITLE
[Bug]: INSTALLATION PROBLEM

### ISSUE THREAD

**Issue by daneshpouya** [jasp-stats/jasp-issues#1767]
### JASP Version

0.16.3

### What OS are you seeing the problem on?

WINDOWS 7; 64BIT

### Bug Description

was using the version 0.16.1, however I uninstalled it to use the newer version 0.16.3. The installation process failed to be complete and it rolled back.
![JASP INSTALLATION PROBLEM](https://user-images.githubusercontent.com/108266999/176437606-ae5fc865-4c4e-41bf-81cd-56c5883dbbba.PNG)

### Expected Behaviour

BRING INSTALLED

### Steps to Reproduce

1. 
2. 
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
From JASPs download page: "Please note that JASP 0.16.3 is not available for Windows 7."
Sorry to say that, but ou will have to stay with an older version https://jasp-stats.org/previous-versions

or upgrade your OS.
