### ISSUE TITLE
[Bug]: Can't run JASP in Arch-based Linux Distro

### ISSUE THREAD

**Issue by ferroson** [jasp-stats/jasp-issues#1769]
### JASP Version

0.16.3

### What analysis are you seeing the problem on?

 I don't know exactly

### What OS are you seeing the problem on?

Archcraft Linux (rolling release)

### Bug Description

I can't run JASP installed from Flathub

![image](https://user-images.githubusercontent.com/108534456/177127135-9347a4e0-1800-4525-a9eb-f8870a20d193.png)

I run JASP in terminal with $ flatpak run org.jaspstats.JASP command, then the error appears: [3:14:0704/161551.826279:FATAL:flatpak_sandbox.cc(291)] Your Flatpak installation is setuid, which is not supported
/app/bin/org.jaspstats.JASP: line 5: 3 Trace/breakpoint trap (core dumped) JASP $1

### Expected Behaviour

Applications available on Flathub should work on all Linux distros because Flatpak is not distro-independent like deb or rpm, this is the first time I have encountered installation problems on Flatpak

### Steps to Reproduce

1. If assuming that JASP can be used on a Debian or Ubuntu based distro, then I can't switch distros
2. JASP might be able to run on an Arch-based Linux distro via a virtual machine such as QEMU or VirtualBox, by first installing a Debian or Ubuntu-based distro, but that would overload the device and not run like a native application.
3. 
...

### Log (if any)

(none)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by vandenman** [comment]
What is your flatpak version?

**Comment by ferroson** [comment]
The flatpak version is 1:1.12.7-1

![image](https://user-images.githubusercontent.com/108534456/177153237-3038392e-83a3-4e21-8ee3-067b1c6e71b0.png)

**Comment by ferroson** [comment]
I can work around the issue for a while. How to reproduce:

Edit /var/lib/flatpak/exports/share/applications with your favorite text editor. If you are confused, just use nano because it is usually preinstalled on every Linux distribution. We need root permissions to do this, so type the command in terminal:

$ sudo nano /var/lib/flatpak/exports/share/applications

On the Exec line, add the --no-sandbox parameter, it should look like this:

Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=org.jaspstats.JASP --file-forwarding org.jaspstats.JASP --no-sandbox @@ %f @@

JASP can be run through the start menu normally afterwards

![Screenshot_2022-07-05-07-12-24_1366x768](https://user-images.githubusercontent.com/108534456/177229094-0f2014eb-2bfb-47d2-bf0d-bc28cc99c731.png)

![Screenshot_2022-07-05-07-12-42_1366x768](https://user-images.githubusercontent.com/108534456/177229208-df7cf1da-2a17-476e-be2d-73d1bc6c7167.png)


![Screenshot_2022-07-05-07-12-53_1366x768](https://user-images.githubusercontent.com/108534456/177229191-31109f5b-8a7e-453b-ac3e-873ddec7ddb5.png)

Why does JASP need --no-sandbox? I never encountered this problem when using Debian 11 (32bit, it seems with older versions). I was trying to figure out the problem, then found this on Flatpak Github: https://github.com/flatpak/flatpak/issues/3044

Even so, I don't know exactly what happened

**Comment by vandenman** [comment]
Well, the linked issue looks like it explains why `--no-sandbox` is sometimes necessary. Jasp uses the Qt WebEngine which is built on Chromium. @JorisGoosen we should probably take a look at https://github.com/flathub/io.qt.qtwebengine.BaseApp/wiki#sandboxing-support-qt6-only.

**Comment by ferroson** [comment]
Does that mean JASP won't use the sandbox later? On the one hand, the use of --no-sandbox will make it easier for users to run the application. If we have followed the instructions correctly, hopefully it can be used without any extra steps, but it seems that some users tend to want the application in a sandbox

**Comment by vandenman** [comment]
Jasp does nothing with `--no-sandbox`, as indicated by the first line in the terminal of your screenshot:
![image](https://user-images.githubusercontent.com/21319932/177716876-303af5a4-9172-44b3-a05e-a785c0f5bfed.png)

However, chromium probably does something with it. Either way, it would indeed be better if Jasp can be run without `--no-sandbox`. This is already the case on e.g., Ubuntu 20.04 and most other distros I encountered though. Did you btw try `flatpak run org.jaspstats.JASP --enable-setuid-sandbox`? I'm not sure if this overwrites the previous Init parameter `disable-setuid-sandbox`, but it's worth a try.

**Comment by sukanka** [comment]
Note that you are using Archcraft Linux (rolling release), which is based on archlinux, you may try to install `jasp-desktop` from [BioArchLinux](https://github.com/BioArchLinux/Packages) after Tue Jul 19 18:00:00 UTC 2022 (as a relevant issue is been processed)

**Comment by ferroson** [comment]
Thank you very much for the advice

**Comment by tomtomme** [comment]
@ferroson 
Was this solved for you in the meantime? Maybe by a newer flatpak or jasp release or the biorch repo?

**Comment by ferroson** [comment]
> @ferroson Was this solved for you in the meantime? Maybe by a newer flatpak or jasp release or the biorch repo? I am on manjaro (arch base too) and never had thes problems
Yes, I can install, then run the app without modifying anything again
