### ISSUE TITLE
Jasp won't run

### ISSUE THREAD

**Issue by OscarLecuona** [jasp-stats/jasp-issues#177]
I've been trying to run jasp in windows 10 and it just won't run. This problem started with the 0.9.0.1 version but I downloaded previous ones (0.9 and 0.8.6) and I get the same result. Also tried to run it as admin and reinstalled multiple times. Checking the control panel the process of jasp starts, but then freezes.

Pc specs: Acer aspire 5750g i5 2.5 ghz, windows 10, 8gb RAM, nvidia geforce gt 630m.

Any help on why this is happening? Thanks a lot!

**Comment by JorisGoosen** [comment]
@OscarLecuona have you perhaps tried the new 0.10.0.0 version?
Maybe that one works, if not, feel free to reopen this issue.
