### ISSUE TITLE
Bug: error message when trying to perform LGCM in JASP 

### ISSUE THREAD

**Issue by jstamos84** [jasp-stats/jasp-issues#1774]
I was trying to perform LGCM in Jasp. When I tried to add factors I got the following error message.

This analysis terminated unexpectedly.

Error in data.frame(..., check.names = FALSE): arguments imply differing number of rows: 60, 53

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

LatentGrowthCurve(...)

.lgcmEnrichData(dataset, options)

cbind(dataset, mm)

cbind(deparse.level, ...)

data.frame(..., check.names = FALSE)

stop(gettextf('arguments imply differing number of rows: %s', paste(unique(nrows), collapse = ', ')), domain = NA)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

**Comment by juliuspf** [comment]
Hi @jstamos84, thanks for reporting this. If possible, could you upload a .jasp file (zipped) that leads to the error? Or alternatively, the data set?

**Comment by tomtomme** [comment]
@jstamos84 
I guess it was just what the error message says: "arguments imply differing number of rows: 60, 53"
So the module has problems, wenn one of your vars has 60 rows and the other 53, probably the rest is empty / missing values. I experienced such problems also back then and they might be fixed for LGCM.

However, on trying to replicate the error, I found the Latent Growth Curve module completely broken!
No matter what data I throw at it, this error message appears:

This analysis terminated unexpectedly.

Error in .lgcmEnrichData(dataset, options): object 'currentNa' not found

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.lgcmEnrichData(dataset, options)

options(na.action = currentNa)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports
