### ISSUE TITLE
[Bug]: Polygon edge not found

### ISSUE THREAD

**Issue by iandol** [jasp-stats/jasp-issues#1778]
### JASP Version

0.16.3

### Commit ID

6a43098c15a5875a1f6cbab94f4dd038e1c55568

### JASP Module

jaspTtest

### What analysis are you seeing the problem on?

Anova or TTests

### What OS are you seeing the problem on?

macOS 12.4

### Bug Description

When I first tried JASP I could generate raincloud plots, but now with new analyses I get the same error whenever I try to activate them, and even for old files that did work now show that error "polygon edge not found":

<img width="528" alt="Screenshot 2022-07-20 at 00 27 49" src="https://user-images.githubusercontent.com/153905/179865304-b553e10e-e069-44e9-8684-69ca3a8b237e.png">

### Expected Behaviour

Should be getting raincloud plots, or at least getting a less cryptic message.

### Steps to Reproduce

1. Load sample data "Directed Reading Activity"
2. Turn on the "Raincloud plots" option
3. See the error
...

### Log (if any)

Log when trying to enable Raincloud plot for a sample:

[LogArchive.zip](https://github.com/jasp-stats/jasp-issues/files/9145312/LogArchive.zip)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment]
Hi @iandol, thanks for reporting this. I can't seem to recreate the issue on my Mac (with 12.4). I get proper raincloud plots. Are you using a Mac with an Intel chip or apple silicon?

**Comment by iandol** [comment]
By the way, where are the preferences saved. I did try uninstalling and reinstalling and deleting some prefs files but obviously missed some...

**Comment by tomtomme** [comment]
@iandol 
thanks for your report. We track this MacOS font issue here: https://github.com/jasp-stats/jasp-issues/issues/2054
So I am closing this one. cheers :)
