### ISSUE TITLE
[Feature Request]: exponential & log model fit for Flexplot

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#1779]
### Description

Add the option to model exponential & logarithmic functions in Flexplots options

### Purpose

We have quadratic and cubic already, so log and exp seem as the next natural step

### Use-case

non-linear models

### Is your feature request related to a problem?

I can not visually model exponential growth in JASP right now

### Describe the solution you would like

Add exponential & logarithmic functions in Flexplots options

### Describe alternatives that you have considered

using Excel

### Additional context

This feature request goes out to the amazing @dustinfife

**Comment by tomtomme** [comment]
Just a note that this is stull valid for 0.16.4

**Comment by tomtomme** [comment]
still valid for 0.17

**Comment by tomtomme** [comment]
@juliuspfadt - can someone be assigned? thx

**Comment by dustinfife** [comment]
Thanks for the suggestion. It's not going to be as easy. With quadratic/cubic, you can modify linear models like this:

`lm(y~a + I(a^2), data=d)`

With exponential and log functions, you'd have to use the `nlm` function (if I remember right) which adds a LOT of complications. I'll think about this though.

**Comment by tomtomme** [comment]
I do not know about "nlm" or any R-package for that matter or why it would be needed. My R-knowledge is really bad and rusty.
But if I needed to transform my e.g. exponential data, I just used log10 or log_natural to transform my y-data:

Then to compute predictions or to interpret my b' or a' (the ' to inform me, that both come from transformed data), I just would do:

y^ = 10 ^ (b'x +a')

and 
10^b 

and 
10^a

if I used log10. 


Sure, log10 might not be the ideal base. Log2 or whatever might fit better. But it usually made not much of a difference for me and was fine for my teaching purposes. However if I wantet to do a scatterplot with such exponential data and an exponential trend line, I had to resort to Excel, to show it to my students. 
And I really do not know what the difficulty is, to implement, say log10 or ln into JASP or flexplot for that matter. Is the complicated thing to find the best log base to fit the data?

**Comment by dustinfife** [comment]
I think you're mixing up transformations with fitting functions. Let's back up a bit and talk about what a linear model is actually doing. The simplest form of a linear model is:

$y = b_0 + b_1x$

In this case, $b_0$ and $b_1$ are parameters to be estimated. R then uses some simple math to figure out the best values of b0/b1 given the data. Now, if we specify a quadratic, the model changes slightly:

$y = b_0 + b_1x + b_2x^2$

All we've done is added another "variable" that just so happens to literally be the square of the first variable. But you're still using basic regression machinery to estimate the parameters (in this case b0, b1, and b2). You've essentially "hacked" regression to do something it wasn't really designed to do. That is what flexplot (and lm) are doing. If you specify a quadratic, in the background R is creating another variable that is equal to the square of the variable, adding that as a predictor in the model, then estimating its slope. 

Now, let's consider an exponential function:

$y = ab^x$

Here, the parameters to estimate are a and b. Standard regression won't work anymore! The math isn't the same. The math for estimating b0/b1/b2 is not the same as the math for estimating a/b. And there's no way to "hack" an exponential function so it follows the regression form (y=b0+b1x+b2x2....). 

What you're talking about is transformations. Transformations are not the same as fitting a quadratic model. With transformations, you _modify the data_ then use standard regression as if those variables were not transformed, then you study slopes/intercepts. You're not actually estimating a/b in this case. You're estimating b0/b1/b2 for transformed variables. 

Make sense?

Unfortunately, this is often the bane of my existence with fitting complex models. Very often the line I need to fit the data should be curved in such a way that standard linear models can't handle them (such as with an exponential). In these cases, I have to resort to custom models (either using a Bayesian approach or using custom functions in nlm). 

If you're really looking for a transformation, I'd just use JASP to create a new column for a transformed variable, then fit that.

**Comment by tomtomme** [comment]
Thanks Dustin for the detailed explanation. I just learned that there is a subtle difference in fitting and transforming. Well, now that I know about it, it is not even that subtle.

However, I also have to realize, that my original request was not clearly formulated. What I am searching for is really just a graphical way to show my students exponential etc. lines within scatterplots via Flexplot - no numerical modeling / fitting etc. needed. 
ATM I have to use Excel or Calc for this, see:

![image](https://github.com/jasp-stats/jasp-issues/assets/4428185/cda246aa-d5eb-4212-864b-4385857578cf)


(P.S. I guess that this request is a duplicate of mine:
https://github.com/jasp-stats/jasp-issues/issues/2486 )

**Comment by tomtomme** [comment]
Closing, since now tracked in the more complete issue here: https://github.com/jasp-stats/jasp-issues/issues/2138
