### ISSUE TITLE
Application-wide font size setting

### ISSUE THREAD

**Issue by accessibility-bug-reports** [jasp-stats/jasp-issues#178]
* JASP version: 0.9.0.1
* OS name and version: Manjaro Linux, KDE 5
* Enhancement: Add a setting to allow for the font size to be changed within the application that would change all fonts in all areas of the application to match or have the application inherit the system font size. 
* Purpose: Accessibility. When I use a screen magnifier the text can't be big enough to be legible without being too blurry. And screen magnifiers are a pain compared to just making the text bigger.

**Comment by JorisGoosen** [comment]
Current version has scaling for the entire application, either from preferences or ctrl+- (zoom out), ctrl++ or ctrl+= (zoom in), ctrl+0 (reset zoom)
