### ISSUE TITLE
[Bug]: Raincloud plots for paired t-test are incorrectly plotted

### ISSUE THREAD

**Issue by basvanhooren** [jasp-stats/jasp-issues#1784]
### JASP Version

0.16.2

### JASP Module

jaspTTests

### What OS are you seeing the problem on?

Windows 10

### Bug Description

When plotting the raincloud plots for paired t-tests, the second condition (ending with R2) always appears first in the plot, while I would like the first condition (ending with R1) to appear first, or at least to have the freedom to change which condition appears first. 

Changing the order in which the data is presented in the file that is uploaded (which I did in the attached file) did not solve the problem. 

[Data for JASP AVG data test.csv](https://github.com/jasp-stats/jasp-issues/files/9191460/Data.for.JASP.AVG.data.test.csv)

![image](https://user-images.githubusercontent.com/64524532/181056023-dd63070c-b7fa-49d1-8689-f0758ddf98dd.png)

### Expected Behaviour

See previous comment

### Steps to Reproduce

1. Load dataset
2. Perform paired t-test
3. Plot raincloud plot

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@basvanhooren 
sadly this is still an issue with jasp 0.18.3
Afaik, there is ongoing work however to be able to sort columns in data edit mode. This should solve it. Since the current behaviour seems to be, that the RCP always shows the column more to the right first.

Another way to solve this would be, to respect the order in which the user did put in the vars in the analysis window.

**Comment by EJWagenmakers** [comment]
We have a student doing some major extensions of raincloud plots at the moment. I will also attend him to this issue.

**Comment by vincentott** [comment]
I just tested it and think it should work in the upcoming standalone raincloud plots module.

However, the data will have to be in long-format, so I first applied tidyverse::pivot_longer() in R.
As far as I know, a general wide-long transformation in JASP is still under development.

**Comment by tomtomme** [comment]
@vincentott 
great to hear. 
A fix within the t-Test module is still needed, but that is lower prio for sure.

**Comment by tomtomme** [comment]
@basvanhooren 
This is now fixed via edit data mode. There you can now resort the variables so that earlier time steps are more on the left and that is the order the tTest module respects.

**Comment by basvanhooren** [comment]
Thanks Thomas!

Kind Regards/Groeten,

Bas

Bas Van Hooren, PhDc | T: +31 6 51643957 | E: ***@***.*** | Twitter: @BasVanHooren| Website: http://www.basvanhooren.com<http://www.basvanhooren.com/> | LinkedIn: https://www.linkedin.com/in/basvanhooren/
________________________________
Van: Thomas Langkamp ***@***.***>
Verzonden: dinsdag 23 april 2024 12:00
Aan: jasp-stats/jasp-issues ***@***.***>
CC: Bas Van Hooren ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [jasp-stats/jasp-issues] [Bug]: Raincloud plots for paired t-test are incorrectly plotted (Issue #1784)


@basvanhooren<https://github.com/basvanhooren>
This is now fixed via edit data mode. There you can now resort the variables so that earlier time steps are more on the left and that is the order the tTest module respects.

**Comment by TeuMasaki** [comment]
I have encountered the same problem, and I don't know how this fixed this specific problem (two separate columns in a raincloud plot within paired t-test miss-ordered).
Is is possible to get a more detailed instruction to switch their order in the plot?

**Comment by vincentott** [comment]
> Is is possible to get a more detailed instruction to switch their order in the plot?

Yes, we have a new, comprehensive raincloud plots module and there is also a youtube tutorial:
https://www.youtube.com/watch?v=AAdXUAl_w6E

At 00:37:40 I explain how to change the order of clouds.
This works for the secondary factor (as shown in the video), as well as for the primary factor (a feature that is covered earlier in the video).
