### ISSUE TITLE
[Bug]: Error in relyFit[['freq']][['omega.fit']]<-omega[[indices']]: replacement has length zero

### ISSUE THREAD

**Issue by sarahatwatts** [jasp-stats/jasp-issues#1785]
### JASP Version

Others

### JASP Module

jaspReliability

### What analysis are you seeing the problem on?

Cronbachs alpha

### What OS are you seeing the problem on?

Macbook pro - running jasp online

### Bug Description

A bug happened. The error message asked for it to be reported: Error in relyFit[['freq']][['omega.fit']]<-omega[[indices']]: replacement has length zero

### Expected Behaviour

I should have been able to run a reliability analysis which resulted in the following:
![Uploading Screen Shot 2022-07-29 at 9.47.21 am.png…]()

### Steps to Reproduce

1. Ran exploratory factor analysis
2. tried runninng reliability analysis and it eorrored out on me 
3. 
<img width="822" alt="Screen Shot 2022-07-29 at 9 18 17 am" src="https://user-images.githubusercontent.com/110209865/181665674-54d50ed0-7cb8-4e53-af56-e2debc102058.png">

...
![Uploading Screen Shot 2022-07-29 at 9.44.36 am.png…]()
![Uploading Screen Shot 2022-07-29 at 9.45.07 am.png…]()

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by vandenman** [comment]
Thanks for reporting the issue! Could you answer a few questions to help us solve this bug?

1. Which version of Jasp are you using?


2. With
> Macbook pro - running jasp online

Do you mean you're using Jasp through [rollapp](https://www.rollapp.com/app/jasp)?

3. Would it be possible to share the data set or Jasp file that lead to this error? Note that if you wish to attach a file to the issue then 1) it is public, and 2) you need to use GitHub's website (you cannot upload files to GitHub by replying to an email).

**Comment by sarahatwatts** [comment]
Hi there

Yes, I'm using JASP through Rollapp, online. 

The dataset is .JASP so won't allow me to upload. Am I able to email it to you somehow?

**Comment by vandenman** [comment]
you can email it to me at d.vandenbergh<at>jasp-stats.org. Note however that rollapp is running  Jasp 0.14.3, while we are currently at Jasp 0.16.3 so it could be that the bug has already been fixed.

**Comment by sarahatwatts** [comment]
Thanks Don

Sorry your email address is not registering as being in the proper form.
Should it be ***@***.***
<http://d.vandenberghjasp-stats.org/>?

I'm also on the unpaid version of Rollapp - could that have any
implications?

Kind regards

Sarah

**Comment by vandenman** [comment]
ah yes, you're right it is `d.vandenbergh<at>jasp-stats.org` where you should replace \<at\> with @ (so bots scraping email addresses on GitHub have a harder time).

**Comment by juliuspf** [comment]
I am quite sure this is an old bug that has been fixed since 0.14.3. I can't really offer a solution, since updating JASP on rollApp was somewhat tricky (if I remember correctly). The only obvious solution is to use JASP offline locally. Sorry about that.

**Comment by juliuspf** [comment]
I will close this issue for now, cause we cannot offer a solution for rollapp.
