### ISSUE TITLE
[Feature Request]: Button for switching labels on and off

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#1786]
### Description

Button for switching labels on and off

### Purpose

Sometimes I like to see the numbers behind the labels directly in the data (without opening the variable pane where I can edit the labels)

### Use-case

informing myself about the data and the labels easily

### Is your feature request related to a problem?

At hte moment I have to delete the labels to see the number in data or I have to switch to metric scale - which is not obvious or intuitive

### Describe the solution you would like

a button to switch between label and number view like in spss

**Comment by tomtomme** [comment]
any chance to include this in 0.19?

**Comment by JorisGoosen** [comment]
Hmm, this could be in an upcoming version.
Didnt have  look at it yet though

**Comment by JorisGoosen** [comment]
Done in https://github.com/jasp-stats/jasp-desktop/pull/5367
