### ISSUE TITLE
[Bug]: JASP is not showing labels in plots.

### ISSUE THREAD

**Issue by utkb** [jasp-stats/jasp-issues#1787]
### JASP Version

0.16.3

### JASP Module

jaspRegression

### What analysis are you seeing the problem on?

Correlation

### What OS are you seeing the problem on?

Ubuntu 22.04 (Flatpak Version)

### Bug Description

There is no labels on Plots. What i am doing wrong?

![image](https://user-images.githubusercontent.com/13717035/181752364-3d6b7fc6-baf9-4878-9a3e-d6f8e5920507.png)

### Expected Behaviour

The labels should appear.

### Steps to Reproduce

1. Make any analysis and select plots.
2. 
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by utkb** [comment]
I can solve the problem, changing font options to Liberation Sans or Serif solve the problem.

**Comment by shun2wang** [comment]
@utkb thank you for your report, We are still interested in knowing the period that happened here, can you tell us:
1. What was the font setting when this problem happened?
2. Could you give a simple example dataset (.jasp or .csv) to upload here?

**Comment by utkb** [comment]
Thank you for your effort.

I think previous fonts are Microsoft Fonts, one of them Helvetica. I can not upload dataset because of sensitive patient information and JASP behave same with all databases. After I changed fonts to Liberation Sans, there is no Helvetica font, I can't select problematic fonts again so i think there is a missing font problem here.

I can remove JASP completely with associated data and reinstall for reproduce.

**Comment by utkb** [comment]
![image](https://user-images.githubusercontent.com/13717035/182013402-3b3d9a2f-6e1b-4f69-8e5d-d45c2a88dc6f.png)

**Comment by utkb** [comment]
I reinstalled JASP with reset, i can confirm the missing font is Helvetica.

**Comment by shun2wang** [comment]
hi @utkb thank you!
what language does your dataset labels is？for example here
![chrome_eoWr7WroXr](https://user-images.githubusercontent.com/10348402/182014507-8157aeb3-3b45-4c16-9820-1c39cf4b8179.png)

**Comment by utkb** [comment]
Turkish but without special characters such as ç, ğ, ö, ş, ü.

**Comment by JorisGoosen** [comment]
Ill doublecheck the default fonts on linux before the next release, not sure why helvetica is selected in flatpak anyway. I think we used to only set that for macos.

**Comment by JorisGoosen** [comment]
@RensDofferhoff can you check this when the new beta build is done?

**Comment by tomtomme** [comment]
@utkb 
Can you re-test with jasp 0.18.3?

**Comment by tomtomme** [comment]
Since flatpak default font is not helvetica anymore (just tested) I will close this one for now.

@utkb 
If not fixed on your side, pls reopen!

**Comment by utkb** [comment]
Sorry for late response, solved, thank you very much.
