### ISSUE TITLE
[Bug]: Cannot create control chart for column with empty cells

### ISSUE THREAD

**Issue by NadjaSchuh** [jasp-stats/jasp-issues#1788]
### JASP Version

0.16.2

### JASP Module

jaspProcessControl

### What analysis are you seeing the problem on?

Control Charts

### What OS are you seeing the problem on?

Windows 10

### Bug Description

![image001](https://user-images.githubusercontent.com/110393355/182142102-663de142-828e-48a1-a9c1-fa2568faab83.png)
Cannot create control chart when column has empty cells

### Expected Behaviour

Ignor the empty cells

### Steps to Reproduce

1. 
2. 
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JTPetter** [comment]
This should be handled in one of the upcoming versions (probably the one after 0.17). For now, I would suggest removing the empty cells.
