### ISSUE TITLE
Request: duplicate analysis

### ISSUE THREAD

**Issue by tvantimmeren** [jasp-stats/jasp-issues#179]
I often use a certain set-up for an analysis (e.g. a repeated measures ANOVA, including a covariate, some descriptives plots) that I would like to repeat while only changing a few variables. It would be great if it would be possible to 'duplicate' or copy/paste the whole analysis. 

* Enhancement: More efficient
* Purpose: Faster analysis

**Comment by SamZebrado** [comment]
Looking forward to this change:) Keeping click same set of buttons is "driving me crazy"... Well

**Comment by EJWagenmakers** [comment]
Yes, this is something we discussed, right, @boutinb?

**Comment by DocVXL** [comment]
I would like to see this too. It's currently in Jamovi, so the code is already out there.
