### ISSUE TITLE
[Feature Request]: Control charts adjustable control limits and targets

### ISSUE THREAD

**Issue by NadjaSchuh** [jasp-stats/jasp-issues#1790]
### Description

to be able to adjust control limits and mean

### Purpose

adjust control limits and mean to what is useful for  specific data and proces

### Use-case

Standard control chart is based on calculated mean and 2stdev. Not all processes need to be controled like that

### Describe the solution you would like

Adjustable control limites based on stdev. adjustable mean and control limits base on history data (=fixed values)

**Comment by juliuspf** [comment]
Hi @NadjaSchuh, thanks again for the request. This is again related to the quality control module?

**Comment by NadjaSchuh** [comment]
By the way, someone programmed these options as part of the machine learning module on my request. I think this option should also be in the quality control module
