### ISSUE TITLE
[Bug]: Control Chart subgroups

### ISSUE THREAD

**Issue by NadjaSchuh** [jasp-stats/jasp-issues#1791]
### JASP Version

0.16.2

### What analysis are you seeing the problem on?

control charts

### What OS are you seeing the problem on?

Windows 10

### Bug Description

When adding a column as subgroup in control charts, JASP still requires to put a fixed group size. I guess it does not use the column to define subgroups as the option implies.
![image](https://user-images.githubusercontent.com/110393355/182163961-ca141843-9f1e-4a93-9843-e33e2aac50a3.png)

### Expected Behaviour

Use the column to define subgroups sizes (does not need to be constant).

### Steps to Reproduce

1. 
2. 
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment]
Hi @NadjaSchuh, thanks again for the report. This is again related to the quality control module?

**Comment by NadjaSchuh** [comment]
Hi,

Yes, all remarks are for quality control module.

Met vriendelijke groet,

Nadja Schuh
Engineer

T +31 (0) 497 339 619
K  2.03 | Alpha gebouw | LouwersHanique<https://www.louwershanique.com/nl>

***@***.***<https://www.louwershanique.com/nl>

Van: Julius Pfadt ***@***.***>
Verzonden: dinsdag 2 augustus 2022 15:57
Aan: jasp-stats/jasp-issues ***@***.***>
CC: Nadja Schuh ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [jasp-stats/jasp-issues] [Bug]: Control Chart subgroups (Issue #1791)

U ontvangt niet vaak e-mail van ***@***.******@***.***>. Meer informatie over waarom dit belangrijk is<https://aka.ms/LearnAboutSenderIdentification>

Hi @NadjaSchuh<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNadjaSchuh&data=05%7C01%7Cnadja.schuh%40louwershanique.com%7C24d0d3a7a6604349fcb908da748ef08b%7Caf830d7edaf1445ebac88998fe478490%7C0%7C0%7C637950454507012123%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RSRD0vZvYTzV0ybBQhYcOXmIGx%2B6kI4ECYQNBPX08Ys%3D&reserved=0>, thanks again for the report. This is again related to the quality control module?

-

**Comment by NadjaSchuh** [comment]
still doesnt work. I get now already an error before even trieing to add a subgroup collumn :C

This analysis terminated unexpectedly.

Error in `[.data.frame`(dataset, k): undefined columns selected

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

variablesChartsSubgroups(...)

.PClongTowide(dataset, k, measurements)

table(dataset[k])

dataset[k]

`[.data.frame`(dataset, k)

stop('undefined columns selected')

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

**Comment by boutinb** [comment]
I don't think this issue should be closed.
