### ISSUE TITLE
[Feature Request]: Syntax output

### ISSUE THREAD

**Issue by planktonwrangler** [jasp-stats/jasp-issues#1794]
### Description

Output program code, syntax for journal article submission

### Purpose

Required for scientific journal article submission

### Use-case

Trying to submit a journal article with results that were analyzed using JASP

### Is your feature request related to a problem?

No

### Describe the solution you would like

In SPSS, it is easy to access and save the syntax/scripts so that they can be provided to publishers during the journal article submission process.

### Describe alternatives that you have considered

If I cannot get these for the analyses I did in JASP, then I think I will have to re-do these analyses in SPSS.

### Additional context

All peer-reviewed journals now require program code and/or syntax and scripts for data analysis and statistical reporting reproducibility. It would be helpful to make these available or provide instructions on how to obtain them.

**Comment by juliuspf** [comment]
Hi @planktonwrangler, thanks for the request. The JASP Team is already working on this, and it is definitely a high priority.

**Comment by EJWagenmakers** [comment]
Yes, the highest priority. Note, however, that the JASP analyses are completely reproducible -- the .jasp file contains the data, executed analyses with selected options, and annoted results. This may need to be explained to editors unfamiliar with a reproducible GUI.

**Comment by tomtomme** [comment]
This is done since JASP 0.17 and can be closed
