### ISSUE TITLE
[Bug]: Bayesian Mixed ANOVA running slow

### ISSUE THREAD

**Issue by kevinvschie** [jasp-stats/jasp-issues#1795]
### JASP Version

0.16.3

### JASP Module

jaspAnova

### What analysis are you seeing the problem on?

Bayesian Repeated Measures ANOVA

### What OS are you seeing the problem on?

Windows 10 Enterprise

### Bug Description

I'm running a Bayesian Repeated Measures ANOVA (two repeated measures factors, both with two levels) and three between subjects factors. Sample size is 80. It's been running for 30 minutes now and there's very little progress (only a very tiny bit of blue in the progress bar). It's hard to check any computed error terms (and see what the actual progression is), because when I try move there JASP nearly freezes and whites out. Is it having a hard time because I'm letting it do crazy analyses or is something wrong here? It's hard to even estimate how long this will take. How long should something like this normally take?

Relevant system specs: 
Processor Xeon(R) W-2223 CPU @ 3.60GHz
Ram: 16GB

### Expected Behaviour

see above

### Steps to Reproduce

1. 
2. 
3. 
...
load data, run analyses.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by vandenman** [comment]
What do you see under model?

![image](https://user-images.githubusercontent.com/21319932/183044780-fa1e4bda-0ac7-481d-9934-1a8208b77aa9.png)


By default, JASP considers all possible interactions, which may not be what you want.

**Comment by kevinvschie** [comment]
Under components I see the two within-subjects factors and the three between factors. Under model terms it lists all possible main effects and interactions. For these analyses I'm mainly interested in the Analysis of Effects (across matched models). I think that necessitates having all those model terms listed? Or maybe I'm mistaken?

**Comment by vandenman** [comment]
If you are interested in the analysis of effects for all possible interactions, then you should leave all those terms in there. In that case, the analysis will simply take a long time to compute.

**Comment by kevinvschie** [comment]
if certain model terms were to be added to the null model would that then mean less computational load?

**Comment by vandenman** [comment]
yes, that would mean these are added in all models and that would decrease the model space (and hence make the computational load smaller). You can also remove the terms you are not interested in (for example, all three-way, four-way, and five-way interactions).

**Comment by kevinvschie** [comment]
Somehow if I select the highest interaction (five way) it includes *everything* in the null model automatically. With that I mean all model terms listed. How can I add only certain interactions?

**Comment by kevinvschie** [comment]
Whilst trouble sheeting here I kept the Bayesian Repeated Measures ANOVA (two repeated measures factors, both with two levels) and three between subjects factors running, but 5% in (based on the progress bar) JASP just quit. No error message, it just shut down. Is this an indication that what I want isn't computationally possible?
