### ISSUE TITLE
[Feature Request]: Histogram scales when splitting by categories

### ISSUE THREAD

**Issue by bcdudek** [jasp-stats/jasp-issues#1798]
### Description

Descriptive plots with histograms split by groups don't use same scale.

### Purpose

Compare distributions across categories/groups

### Use-case

Teaching

### Describe the solution you would like

When using split by groups, provide option to use the same scale on each group's plot.

### Describe alternatives that you have considered

Jamovi

### Additional context

In teaching intro statistics, it is very common to use exemplar data sets where distribution shape of a DV is compared across groups.  Can't really do this well unless the histograms have the same scale properties - begin and end at same value.

I like teaching with JASP, but this is a basic issue that is very frustrating.

**Comment by EJWagenmakers** [comment]
I agree!

**Comment by bcdudek** [comment]
Wondering how to get this request assigned.  I thought that EJ's weighing in would have motivated it.

**Comment by tomtomme** [comment]
@bcdudek 
This one is actually assigned here https://github.com/jasp-stats/jasp-issues/issues/451
Since this is a duplicate I am closing this one. Lets hope it gets done for 0.19 :D
