### ISSUE TITLE
[Feature Request]: Bayesian multidimensional reliability

### ISSUE THREAD

**Issue by Richmull** [jasp-stats/jasp-issues#1799]
### Description

Reliability module

### Describe the solution you would like

Implementation of Bayesrel multidimensional modeling in the reliability module please

### Additional context

Are there any plans to expand the unidimensional reliability analyses to the MD case in JASP, please?

**Comment by juliuspf** [comment]
Yes! But I cannot give you a date for this yet. The R-package is almost done though :)

**Comment by Richmull** [comment]
Thanks Julius. Look forward to it when it’s ready.

**Comment by tomtomme** [comment]
@Richmull 
Closing, since duplicate of https://github.com/jasp-stats/jasp-issues/issues/1336 where julius confirmed that this will come for Bayes and Frequentist together.
