### ISSUE TITLE
[Bug]: Quality control of JASP in ubuntu

### ISSUE THREAD

**Issue by JuanRafaelB** [jasp-stats/jasp-issues#1801]
### JASP Version

0.16.3

### JASP Module

jaspProcessControl

### What analysis are you seeing the problem on?

all the quality control analysis

### What OS are you seeing the problem on?

Ubuntu

### Bug Description

![imagen](https://user-images.githubusercontent.com/12464834/184552774-d473b752-bb3f-4cf2-87ae-1f7083b142d8.png)

### Expected Behaviour

Codified matrix did not showed

### Steps to Reproduce

1. 
2. 
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by shun2wang** [comment]
thank you for your report, it's seem a duplication of https://github.com/jasp-stats/jasp-issues/issues/1766 and we've tracked it here.
