### ISSUE TITLE
[Bug]:   cant run jasp in   UBUNTU 18.04.5 LTS

### ISSUE THREAD

**Issue by cuetox1** [jasp-stats/jasp-issues#1803]
### JASP Version

0.16.3

### What OS are you seeing the problem on?

UBUNTU 18.04.5 LTS

### Bug Description

No run

### Expected Behaviour

open software

### Steps to Reproduce

Install 
Run   "flatpak run org.jaspstats.JASP"

Show the next message:

_[3:16:0819/174530.985158:ERROR:object_proxy.cc(621)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/Flatpak: org.freedesktop.DBus.Error.InvalidArgs: No existe la propiedad «supports»
/app/bin/org.jaspstats.JASP: línea 5:     3 `trap' para punto de parada/seguimiento               (`core' generado) JASP $1_

![imagen](https://user-images.githubusercontent.com/32189302/185717683-6f6da3f8-c304-4c08-aa35-13ab5ccde66e.png)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment]
Hi @cuetox1, thanks for the report. Let's see if one of the developers can help.

**Comment by tomtomme** [comment]
@cuetox1 
Could you retest with current jasp 0.18.3 and an updated UBUNTU? flatpak support on that old ubuntu might be not that great.
Also maybe test, if jasp srarts, when you disconnect from the internet before. MIght have to do with a proxy.
