### ISSUE TITLE
[Feature Request]: Contour enhanced funnle plot

### ISSUE THREAD

**Issue by Trebicky** [jasp-stats/jasp-issues#1804]
### Description

Adding option to enhance contour in meta-analysis funnel plot

### Purpose

Allow for better inspection of p-values distribution in funnel plot  

### Use-case

If we want to see wheter effect cluster around certain p values

### Is your feature request related to a problem?

To visualise small study effects or visualy inspect funnel plot for asymmetries or clustering. 

### Describe the solution you would like

check box to choose default or contour enhanced funnel plot

### Describe alternatives that you have considered

Have it as an option in plot editing window

**Comment by tomtomme** [comment]
@Trebicky 
Thx for the request and sorry for the late response. This may take some time.
