### ISSUE TITLE
[Bug]: windows installer package part of the setup did not finished

### ISSUE THREAD

**Issue by tdkelly** [jasp-stats/jasp-issues#1807]
### JASP Version

0.16.3

### What OS are you seeing the problem on?

Windows 10

### Bug Description

Error: There is a problem with this windows installer package, A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.

Changes are rolled back

### Expected Behaviour

Expected the prgram to completely install successfully

### Steps to Reproduce

1. Run the installer and follow the on screen prompts
2. 
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by shun2wang** [comment]
Hi, @tdkelly 
it  seems that the package downloaded maybe broken, you can download it on https://jasp-stats.org/download/ and try again.

**Comment by tdkelly** [comment]
Hello, thank you for the suggestion but that did not make a difference. We are trying to install on several machines, most of them go fine without issue it is only on a few of them that this is happening on. Downloading a fresh copy had no effect the same problem came up. 

![2022-08-29_10-15-14](https://user-images.githubusercontent.com/22504918/187257346-5484a7d4-4570-4047-bbd8-9dd0e3511d97.jpg)

**Comment by shun2wang** [comment]
Aha, sorry about that.
@tdkelly Could you help us with more details?
1. Open a Windows command line and use `msiexec /i <path to your full JASP installation package> /l*v msilog.txt` to get the installation log. E.g:
`msiexec /i C:\Users\Programs\JASP-0.16.3-64bit.msi /l*v msilog.txt`
Then upload this `msilog.txt` here.
2. Did you try to install with administrator account?

**Comment by tdkelly** [comment]
Hello, 
Yes I installed the application under an administrator account. Unfortunately I cannot upload the log it says it is too large a file. Do you have another method of getting the verbose log to you?

Thanks

**Comment by shun2wang** [comment]
you can upload it to a cloud storage(like OneDrive,Google drive) and share a link for us.

with thanks

**Comment by tdkelly** [comment]
Here you go I had to zip it up to get it to transfer

https://drive.google.com/file/d/1v7axuv5JeD8LMyTGBBx236M4whZIne1-/view?usp=sharing

**Comment by shun2wang** [comment]
OK, thanks. Let our engineers see if there are any other comments. 

Until then you use a JASP pre-installed version by unziped the https://static.jasp-stats.org/JASP-0.16.3-64bit.zip

**Comment by boutinb** [comment]
Hi @tdkelly , are the PC's the same (same WIndows version e.g.) or does exist some differences between them? It would be of interesting to know if the PC's where JASP cannot be installed have some special configurations.

**Comment by JorisGoosen** [comment]
@shun2wan thanks for asking for the log, it confirmed my suspicion.

The action that fails in the msi is the "recreation of junctions" (which is quite necessary).
However, if @tdkelly can download that aforementioned zip, unpacks it and runs "jasp.exe" it should do the same things.

And then we can see whether it works if ran outside the msi. 

As @boutinb questions, what is different between the windows pcs?
Are some of them another version?
Or are they perhaps managed by some it-department?
Or running remotely?

I don't know, but there must be something different that causes this issue.

**Comment by tdkelly** [comment]
Hello, 
All the computers (working and non working) are the same model with the same hardware. Running the exact same image. I did try the zip and that will not launch. It starts then goes into suspended and closes almost immediately. Any further suggestions is appreciated. In the meantime I will look more into the failures and see if there is something else that could causing this. 

Thank You

**Comment by JorisGoosen** [comment]
Could you perhaps open a "command prompt" and then navigate to the folder where you unpacked `JASP.exe`  and the accompanying files.

If there is a folder in there called `Modules` make sure to delete it first. (if it is there I would like to know though)

Then run `JASPEngine.exe --recreateJunctions`

Maybe this will give us some more feedback

**Comment by tdkelly** [comment]
Yes I had a Modules folder, I deleted that and ran the command and got the following error message
![2022-08-30_10-20-21](https://user-images.githubusercontent.com/22504918/187502640-9c267161-eb4f-4ae4-9b34-a93af0183c2f.jpg)

**Comment by shun2wang** [comment]
Is this also same with https://github.com/jasp-stats/jasp-issues/issues/1841 ?

**Comment by lgunali** [comment]
https://github.com/jasp-stats/jasp-issues/issues/1807#issuecomment-1230605267

https://github.com/jasp-stats/jasp-issues/issues/1807#issuecomment-1231951257

@JorisGoosen I have the same issues on JASP 0.17.1

I have just updated the video driver... could you help me?

![screen](https://user-images.githubusercontent.com/71451331/225576871-60b9ce98-32ab-4c2c-b6a1-01d99e6c8eb9.png)

**Comment by JorisGoosen** [comment]
@igunali could you just open a new issue for your problem. Because it might or might not be the same but there is no need to bother tdkelly with it ;)
Please describe your issue in your own words there, then we'll see whether it is the same or not

**Comment by lgunali** [comment]
> @igunali could you just open a new issue for your problem. Because it might or might not be the same but there is no need to bother tdkelly with it ;) Please describe your issue in your own words there, then we'll see whether it is the same or not

@JorisGoosen I've done that https://github.com/jasp-stats/jasp-issues/issues/2061#issue-1629743467 as you suggest.
Thank you very much
