### ISSUE TITLE
[Bug]: "You can’t open the application “JASP” because this application is not supported on this Mac."

### ISSUE THREAD

**Issue by kreacherofthenight** [jasp-stats/jasp-issues#1808]
### JASP Version

0.16

### What OS are you seeing the problem on?

macOS 12.5.1

### Bug Description

Followed installation guide verbatim, double clicked to open JASP after moving to Applications folder, and instead of the step " A window appears noting that the developer cannot be verified, select “Cancel” "  happening, the attached screenshot is what appeared. Deleting the files and reinstalling did not work, mac is up-to-date, been restarted even, zilch.

![Screen Shot 2022-08-28 at 11 29 24 AM](https://user-images.githubusercontent.com/112338301/187084586-9725d2e0-85d0-496b-9ab7-fe363c21a35b.png)
.

### Expected Behaviour

Step 5: A window appears noting that the developer cannot be verified, select “Cancel”
from:
https://jasp-stats.org/installation-guide/

### Steps to Reproduce

1. navigate to application folder
2. double-click JASP
3. select Open

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment]
Hi @kreacherofthenight, thanks for the report. Is there any particular reason you did not use the newest version of JASP, aka 0.16.3?

**Comment by mspezio** [comment]
Just reproduced this with 0.16.3 on a Mac running OS 12.5. JASP does not seem to be recognized by Monterey?

**Comment by juliuspf** [comment]
are you on Mac intel or silicon? Did you download the corresponding JASP version, aka the intel or the silicon one? Cause I am on macOS Monterey as well (intel), and it all works fine...

**Comment by mspezio** [comment]
Three of my students updated to 12.5.1. Redownloaded from JASP github site and tried from the standard download site. Students downloaded the correct version for 11+. Nothing is working. Message is always that the application is not supported on this Mac. Is there any solution to this problem? This is affecting whether I will be able to stay with JASP this term to teach my course. Thank you

**Comment by kreacherofthenight** [comment]
I just checked and it is 16.3 that I have downloaded, I guess I forgot to add the tenth. I had mistakenly downloaded the silicon, thinking the 10.5 vs 11+ was about which mac version you were on. I deleted it, then made sure to download the intel version, and it is now working fine. Thank you

**Comment by EJWagenmakers** [comment]
Great, happy to hear this!

**Comment by juliuspf** [comment]
I suspect the same is happening with the students? Might they also have assumed that they needed to download the 11+ version although it is for apple silicon and they are actually on intel (see screenshot), @mspezio ?
<img width="650" alt="Screenshot 2022-09-04 at 15 47 27" src="https://user-images.githubusercontent.com/38500953/188316835-2e49e1c2-03d8-4746-9371-3910acee879d.png">

**Comment by JorisGoosen** [comment]
I can just remove those versionnumbers. Not sure how they help (because 11.0+ is simply the first version of macos supporting apple silicon so its not like anyone could possibly have the older version on there anyway).

**Comment by mspezio** [comment]
Hi Jay,

Try to download and install JASP in the 10.5+ version. It's possible that JASP developers erroneously listed the other version as needed for Mac OS 11.0+.

Please let me know how this goes.

Best, Prof. Spezio
________________________________

**Comment by mspezio** [comment]
Thanks, this is possible. I will ask the students to try the 10.5+ version. I endorse Joris' idea of removing the Mac OS version numbers from the download links, and simply giving Intel or Silicon machine options. I'll report back once we try the Intel version under Mac OS 12.5.1. Fingers crossed.

**Comment by JorisGoosen** [comment]
Ive removed the versions in any case. Should be more clear for everyone now!
