### ISSUE TITLE
[Bug]: Error in Gauge r&R analysis

### ISSUE THREAD

**Issue by NadjaSchuh** [jasp-stats/jasp-issues#1809]
### JASP Version

0.16.2

### What analysis are you seeing the problem on?

Quality Control module:  Gauge r&R (non-replicable measurements)

### What OS are you seeing the problem on?

Windows 10

### Bug Description

doesn't create report

![image](https://user-images.githubusercontent.com/110393355/187166935-b1eceba6-f0d9-4dba-b77c-df173723095c.png)

### Expected Behaviour

show report

### Steps to Reproduce

After checkmark "show report" this error is shown

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment]
Hi @NadjaSchuh, thanks for reporting this. Is it possible that you upload a .jasp file or the data file that lead to the issue?

**Comment by NadjaSchuh** [comment]
I will ask the owner if this is allowed


Van: Julius Pfadt ***@***.***>
Verzonden: maandag 29 augustus 2022 12:19
Aan: jasp-stats/jasp-issues ***@***.***>
CC: Nadja Schuh ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [jasp-stats/jasp-issues] [Bug]: This analysis terminated unexpectedly. Error in if ((x%%1) ≠ 0) {: missing value where TRUE/FALSE needed Stack trace (Issue #1809)

U ontvangt niet vaak e-mail van ***@***.******@***.***>. Meer informatie over waarom dit belangrijk is<https://aka.ms/LearnAboutSenderIdentification>

Hi @NadjaSchuh<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNadjaSchuh&data=05%7C01%7Cnadja.schuh%40louwershanique.com%7C06379e8a5fb44dc4ca0308da89a7e3f5%7Caf830d7edaf1445ebac88998fe478490%7C0%7C0%7C637973651426769595%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3%2B1hU24KidnTGQJV1p3LP9Cxy2%2BIfhUafF%2BEFWHuGfA%3D&reserved=0>, thanks for reporting this. Is it possible that you upload a .jasp file or the data file that lead to the issue?

-

**Comment by NadjaSchuh** [comment]
[MSA Diameter QT5p20.csv](https://github.com/jasp-stats/jasp-issues/files/9493726/MSA.Diameter.QT5p20.csv)

**Comment by juliuspf** [comment]
I reopened this since I can replicate the issue. The error shows up once the "show report" checkbox is ticked
