### ISSUE TITLE
[Bug]: unable to convert string to requested encoding

### ISSUE THREAD

**Issue by JASPlearner** [jasp-stats/jasp-issues#1811]
### JASP Version

0.16.3

### What OS are you seeing the problem on?

window 10

### Bug Description

![image](https://user-images.githubusercontent.com/111798846/187397076-ffc1e263-5186-49be-9093-c03863498302.png)

I could not open my file in JASP.

### Expected Behaviour

open the file.

### Steps to Reproduce

1. open JASP
2. open-computer-browse-(choose my own file)

...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment]
hi @JASPlearner, thanks for the report. I will ask someone to look at this.

**Comment by JorisGoosen** [comment]
@JASPlearner do you have access to SPSS?

Because this is related (im guessing) to #1532 and as @shun2wang mentions there it should be possible to save your `sav` in "utf-8" encoding: https://github.com/jasp-stats/jasp-issues/issues/1532#issuecomment-986725227

If you do that it should work fine.

**Comment by JASPlearner** [comment]
I think my file is utf-8 already. 
I save my file as cvs. and it was opened in JASP. but the Chinese characters were all lost.

**Comment by JASPlearner** [comment]
Thanks for your prompt reply!! :) @JorisGoosen @juliuspf

**Comment by shun2wang** [comment]
Hi @JASPlearner If you are a Chinese user and have exported a sav file from some online service, then usually this sav file is stored in Chinese local encoding(not utf-8 in fact). If you can read Chinese, please refer to https://www.wjx.cn/jq/5130953.aspx
If you want to use the sav file in JASP, you can open the file completely in SPSS, reset SPSS to Unicode and save as a copy of this file.then try to open it with JASP.

if didn't help, you can send a sample file here or just send to me shuonwang(@)gmail.com

**Comment by JorisGoosen** [comment]
@JASPlearner You're welcome!

I hope the workarounds @shun2wang gave are enough for now, because this should definitely be implemented but I don't think it'll make it into the next release yet...

**Comment by shun2wang** [comment]
fixed in next coming release 0.17.3.
