### ISSUE TITLE
[Feature Request]: Update the help files of bayes t-test, anova with effect size delta

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#1812]
### Description

in classical t-tests, anovas etc. we are used to think in means instead of medians. Also cohens d is missing

### Purpose

don't confuse the user by only showing median in the upper right of the plot

### Use-case

more info

### Describe the solution you would like

show the mean and cohens d somewhere in the plot or the tables

### Additional context

![grafik](https://user-images.githubusercontent.com/4428185/187440454-91fb9860-1345-467e-84e0-563dcbe19ad1.png)

**Comment by tomtomme** [comment]
As I read this blog by Lakens http://daniellakens.blogspot.com/2016/01/power-analysis-for-default-bayesian-t.html 
and the comments below the blog... I think this feature-request may not be feasable?
Because Bayesian statistics emphasize distributions of effect sizes over point estimates.
Nontheless it would be nice to explain somewhere what "effect size delta" is and what it is not. There is no documenation yet in jasps help file.
In classic statistics delta is usually Cohens d for the population effect size. But here it just seems to be the median difference of prior and posterior. So something very different. Not based on the mean, not standardized and not for the population. I hope I got this right?

**Comment by EJWagenmakers** [comment]
1. I think you are (much) better off reading blogs by Bayesian statisticians :-)
2. Effect size delta is the population version of Cohen's delta, so mu / sigma -- to clarify this in the help file is a good feature request. @juliuspf can you assign this?
3.  "In classic statistics delta is usually Cohens d for the population effect size. But here it just seems to be the median difference of prior and posterior. So something very different. Not based on the mean, not standardized and not for the population. I hope I got this right?"

Not this time :-) The prior and posterior reflect one's belief about the standardized population effect size delta. We report the posterior median because it is generally preferred over reporting the posterior mean.

**Comment by tomtomme** [comment]
mmh. Interesting. From all the graphs I have seen (like the one above) Median and delta seem to have the identical value (1.515 above). That does not seem to be correct, does it?

**Comment by EJWagenmakers** [comment]
I am not sure what you mean when you say "median and delta have the identical value". Delta does not have a single value -- it has a distribution, the median of which is indicated in the plot. When the prior is symmetric and centered on delta = 0, as is usually the case, then the posterior median will equal the difference between the prior and posterior median.

**Comment by tomtomme** [comment]
Then the mode of the delta distribution seems to equal the median diff of prior to posterior. This suggests to me that median diff and mean diff are the same, as expected in symetric distributions. Is the standard deviation of the posterior 1?
Then it is logical that mode of delta and the median diff of prior to posterior are equal. If correct, this info could also make it into the helpfile for bayes beginners like me.

**Comment by EJWagenmakers** [comment]
"Then the mode of the delta distribution seems to equal the median diff of prior to posterior."
 
It is not immediately evident how you'd compute the difference between the two distributions; I would just say that the prior median is at delta = 0, and the posterior median is at delta = whatever-the-median-is. For symmetric and unimodal distributions, the mean is the same as the mode. 

" Is the standard deviation of the posterior 1?"

No -- the peakedness of the posterior indicates the precision of our knowledge. As n grows large, the posterior will be more and more peaked.

**Comment by tomtomme** [comment]
Thanks for bearing with me. I think I got it now.  I try to summarize:

You confirmed that the "bayesian" effect size delta above is an estimation of "the population version of Cohen's delta" - as I thought. It is NOT the point estimate Cohens d, which I tried to read into it at the same time.
I learned that the delta here has no single value, but is in fact a distribution.
I also learned: delta =  µ / sigma here, as in classical stats, but the unknown sigma is kind of visualized / estimated by the peakedness of the distribution. Nice.

Also:
![Unbenannt](https://user-images.githubusercontent.com/4428185/205236648-dccc4021-cee3-42d6-b1ed-4f71ca0f16a4.png)

Because the example is symmetric all of the following _population_ point estimates are equal and also already _standardized_:

delta at the mode of the posterior - delta at the mode of the prior 
= mode of posterior - mode of prior
= median of posterior - median of prior
= mean of posterior - mean of prior
= 1.515 - 0

They are standardized by the estimated sigma.
For someone trained in thinking of delta as a point estimate of sample data it is hard to think of delta as an estimated population distribution. So if this "population distribution estimate" part could be made more clear in the help file this would be great for yet non-bayesian thinkers. I guess :)

**Comment by EJWagenmakers** [comment]
Agreed, except one thing:
"I also learned: delta = µ / sigma here, as in classical stats, but the unknown sigma is kind of visualized / estimated by the peakedness of the distribution."

The peakedness of the distribution refers to the uncertainty about delta, not sigma. For instance, when n grows large we may learn with great certainty that mu is about 2 and sigma is about 4; this would mean that the posterior distribution on delta is peaked around 1/2.

**Comment by tomtomme** [comment]
Still missing in 0.17 help file for bayes t-Tests and ANOVAs, section plots, paragraph "prior and posterior":

- The effect size delta is an estimate of the effect size distribution in the population. It is not a point estimate.

**Comment by tomtomme** [comment]
Closing, since tracked via #2529
and probably not even needed for people with proper understanding of bayesian methods :D
