### ISSUE TITLE
[Bug]: K-means clustering hidden in machine learning

### ISSUE THREAD

**Issue by czenci** [jasp-stats/jasp-issues#1813]
### JASP Version

0.16.3

### JASP Module

jaspMachineLearning

### What analysis are you seeing the problem on?

K-means Clustering

### What OS are you seeing the problem on?

mac OS Monterey Version 12.5

### Bug Description

Dear team, I can't find the K-means Clustering feature. Comparing the screenshots of this tutorial https://jasp-stats.org/2019/09/24/introducing-jasp-0-11-the-machine-learning-module/, I only see Neighborhood-based Clustering:

<img width="164" alt="image" src="https://user-images.githubusercontent.com/99724605/187505401-bc5c99f7-90df-4d3a-8506-b34d3026ed2d.png">

Could you please help?

PS, I love JASP, thank you!

### Expected Behaviour

Machine learning > Clustering > K-means Clustering

### Steps to Reproduce

1. 
2. 
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment]
HI @czenci, thanks for the report. I suspect that something has gone wrong with the naming of these analyses since the introduction of the module.

**Comment by koenderks** [comment]
K-means clustering is part of the neighborhood-based clustering analyses with the centers option (Under training parameters) set to "Means" (the default). The other neighbourhood-based clustering analyses to be found here are k-medoids (centers = medoids) or k-medians (centers = medians).
