### ISSUE TITLE
[Bug]: Model posterior probability does not change when the model prior probability changes

### ISSUE THREAD

**Issue by Jiashun97** [jasp-stats/jasp-issues#1816]
### JASP Version

0.16.3

### JASP Module

jaspAnova

### What analysis are you seeing the problem on?

repeated measure anova

### What OS are you seeing the problem on?

windows 10

### Bug Description

When change the model prior, the model posterior probability P(M|data) does not change.

### Expected Behaviour

The model posterior probability P(M|data) should be updated together with the model prior probability P(M).

### Steps to Reproduce

1. Open stroop example data set in repeated measure anova with random slopes.
2. Left panel under model prior, change the prior from "beta binomial a = 1, b = 1" to "beta binomial a = 2, b = 3", then to Castillo u = 1
3. 
...
![WechatIMG23](https://user-images.githubusercontent.com/65221219/187918180-f9c8a2ed-b5e6-4e4f-90e7-23cb85af7ec9.png)

![WechatIMG25](https://user-images.githubusercontent.com/65221219/187918187-ba38897e-3d73-4b56-ba02-c6d62a32a8ab.png)

![WechatIMG26](https://user-images.githubusercontent.com/65221219/187919903-57040728-32ef-43b7-80f1-0b7e7ac30b4d.png)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment]
is this related to https://github.com/jasp-stats/INTERNAL-jasp/issues/2086 ?

**Comment by Jiashun97** [comment]
> is this related to [jasp-stats/INTERNAL-jasp#2086](https://github.com/jasp-stats/INTERNAL-jasp/issues/2086) ?

yes!

**Comment by vandenman** [comment]
Both issues indicate a bug with the state, but they're not exactly the same bug, so I wouldn't close either issue.
