### ISSUE TITLE
[Feature Request]: Repeated Measures MANOVA

### ISSUE THREAD

**Issue by zaeemhadi** [jasp-stats/jasp-issues#1819]
### Description

Currently MANOVA in JASP is only suitable for multiple measures assessed at one time point.

### Purpose

To analyze multiple measures assessed at multiple time points.

### Use-case

A variable X with units (i) and a variable Y with units (j) is measured multiple points in time. To look at the interaction of both variables over time, a repeated measures MANOVA would be required.

### Is your feature request related to a problem?

No

### Describe the solution you would like

Option to include repeated measures in MANOVA.

### Describe alternatives that you have considered

JASP probably doesn't have an alternative for this.

**Comment by tomtomme** [comment]
This is a duplicate.
RM MANOVA is already tracked here: https://github.com/jasp-stats/jasp-issues/issues/1660

Can be closed.
