### ISSUE TITLE
[Bug]: installation package couldn't be opened

### ISSUE THREAD

**Issue by spacedina** [jasp-stats/jasp-issues#1821]
### JASP Version

0.16.3

### What OS are you seeing the problem on?

windows

### Bug Description

![Screenshot (299)](https://user-images.githubusercontent.com/113032367/189025476-0b19574b-3832-4782-bdf3-b80b03d1d0af.png)
Downloaded the new version and cant seem to open it trying to uninstall it and this happen
![Screenshot (300)](https://user-images.githubusercontent.com/113032367/189025754-8ef95618-f7bb-4fbf-80c6-b439c1851a8e.png)
I did try to install the 14 version and it say that updated version has already been installed. So I can't seem to open any version

### Expected Behaviour

Expected the program to open

### Steps to Reproduce

1. Run the installer and follow the on screen prompts
2. 
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by spacedina** [comment]
in the meantime im using the pre-installed version as stated  [here](https://github.com/jasp-stats/jasp-issues/issues/1807#issuecomment-1231129748) I hope this is okay and can run the same function

**Comment by juliuspf** [comment]
Hi @spacedina, thanks for the report. May I ask, which windows version are you using?

**Comment by spacedina** [comment]
> Hi @spacedina, thanks for the report. May I ask, which windows version are you using?

Im using windows ver 11

**Comment by juliuspf** [comment]
@spacedina could this be the same as here? https://github.com/jasp-stats/jasp-issues/issues/1822

**Comment by JorisGoosen** [comment]
@spacedina what kind of cpu does your pc have?

**Comment by JorisGoosen** [comment]
@juliuspf sure sounds like it is the same as #1822 or https://github.com/jasp-stats/jasp-issues/issues/1841

**Comment by JorisGoosen** [comment]
@spacedina  
Can you open a command prompt in windows and try the following:
```
mkdir test
cd test
mkdir folder
mklink /j junction folder
dir /a
```
Please copy all the output here
