### ISSUE TITLE
[Bug]: 0.16.3 won't install on Surface Pro X - ARM CPU

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#1822]
### JASP Version

0.16.3

### What OS are you seeing the problem on?

Windows 10 and 11 Home ARM64

### Bug Description

This is a bug report of one of my students.
JASP does not install on her Surface Pro X with custom microsoft / quallcom ARM64 CPU called "Microsoft® SQ1™ processor", see https://www.microsoft.com/en-us/surface/business/surface-pro-x/processor

### Expected Behaviour

should install

### Steps to Reproduce

1. download
2. install
3. error message, see below
same on win 10 and 11

### Log (if any)

![Screenshot 2](https://user-images.githubusercontent.com/4428185/189069166-455e75d3-fce0-4b38-9494-c93fa9a331e7.jpg)
![Screenshot 3](https://user-images.githubusercontent.com/4428185/189069242-748d1cdf-29aa-4d93-a89c-2db6642f88ba.jpg)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JorisGoosen** [comment]
Ai, it might be a while before we will get around to supporting windows arm... We also don't really have any way to test it.

**Comment by JorisGoosen** [comment]
Well this error also seems to occur on intel windows, so it might be unrelated to ARM after all.
However, I can still not reproduce it

**Comment by JorisGoosen** [comment]
@tomtomme  
Can you ask your students to open a command prompt in windows and try the following:
```
mkdir test
cd test
mkdir folder
mklink /j junction folder
dir /a
```
Please copy all the output here

**Comment by tomtomme** [comment]
![screen2.jpg](https://user-images.githubusercontent.com/4428185/193472158-64f5ff22-ed02-43af-b031-05fa56225c09.jpg)

**Comment by JorisGoosen** [comment]
Thank you @tomtomme !

Well at least the problem doesn't seem to be making the junctions, so that's something.
In https://github.com/jasp-stats/jasp-issues/issues/1807#issuecomment-1262419496 the solution seemed to be updating the graphics driver.

Could you try downloading https://static.jasp-stats.org/JASP-0.16.4-64bit.zip and unpacking it somewhere, then in a command prompt:
```
cd <to/the/folder-where-you-unpacked>
jasp --safeGraphics -platform minimal --junctions
```

**Comment by JorisGoosen** [comment]
@tomtomme I guess you didnt have a chance to test this on your student's pc?

However, I do think I should implement the safe graphics fix for the installer-phase, just to make sure users can get to starting JASP at all.

**Comment by tomtomme** [comment]
@JorisGoosen - yeah, she did not answer. Happily awaiting the fix. Feel free to close this issue anytime
