### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by vellinhs** [jasp-stats/jasp-issues#1823]
### JASP Version

0.14

### JASP Module

jaspReliability

### What analysis are you seeing the problem on?

Reliability

### What OS are you seeing the problem on?

Windows 11

### Bug Description

I can't run reliability test for some of my datas, but the rest of datas went well.

### Expected Behaviour

It should've shown the result of reliability

### Steps to Reproduce

1. 
![image](https://user-images.githubusercontent.com/113122820/189158314-1b516988-0a32-4861-bea7-2ab90df10297.png)
[](url)
2. 
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment]
Hi @vellinhs, thanks for the report. Could you download the latest JASP version and try again?

**Comment by juliuspf** [comment]
I will close this for now, since this issue occurred with an old JASP version and should be fixed in the newer releases
