### ISSUE TITLE
[Bug]: jaspNetwork- groups number out of range

### ISSUE THREAD

**Issue by andremonezi** [jasp-stats/jasp-issues#1824]
### JASP Version

0.16.3

### JASP Module

jaspNetwork

### What analysis are you seeing the problem on?

Network

### What OS are you seeing the problem on?

Windows 

### Bug Description

This analysis terminated unexpectedly.

Error in groups[[i]]: subscript out of bounds

Stack trace
withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

NetworkAnalysis(...)

.networkAnalysisPlotContainer(mainContainer, network, options)

.networkAnalysisNetworkPlot(plotContainer, network, options)

jaspBase::.suppressGrDevice({
    for (v in names(allNetworks)) {
        networkToPlot <- allNetworks[[v]]
        if (options[['estimator']] = 'mgm') {
            edgeColor <- networkToPlot[['results']][['edgecolor']]
            if (is.null(edgeColor))
                edgeColor <- networkToPlot[['results']][['pairwise']][['edgecolor']]
        }
        legend <- allLegends[[v]]
        networkPlotContainer[[v]]$plotObject <- .networkAnalysisOneNetworkPlot(network = networkToPlot, options = options, minE = minE, maxE = maxE, layout = layout, groups = groups, labels = labels, legend = legend, shape = shape, nodeColor = nodeColor, edgeColor = edgeColor, nodeNames = nodeNames)
    }
})

eval(plotFunc, parent.frame())

eval(plotFunc, parent.frame())

.networkAnalysisOneNetworkPlot(network = networkToPlot, options = options, minE = minE, maxE = maxE, layout = layout, groups = groups, labels = labels, legend = legend, shape = shape, nodeColor = nodeColor, edgeColor = edgeColor, nodeNames = nodeNames)

qgraph::qgraph(input = wMat, layout = layout, groups = groups, repulsion = options[['repulsion']], cut = options[['cut']], edge.width = options[['edgeSize']], node.width = options[['nodeSize']], maximum = maxE, minimum = minE, details = options[['showDetails']], labels = labels, palette = if (options[['manualColors']]) NULL else options[['nodePalette']], theme = options[['edgeColors']], legend = legend, shape = shape, color = nodeColor, edge.color = edgeColor, nodeNames = nodeNames, label.scale = options[['scaleLabels']],
    label.cex = options[['labelSize']], GLratio = 1/options[['legendToPlotRatio']], edge.labels = options[['edgeLabels']], edge.label.cex = options[['edgeLabelCex']], edge.label.position = options[['edgeLabelPosition']])

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

### Expected Behaviour

Every time I try to change the colors of the scale factors, Jasp crashes and issues the message as shown in the attached image. 

### Steps to Reproduce

1. I enter all the items in the analyses and the network runs normally.
2. 
![Crashes](https://user-images.githubusercontent.com/64216719/189174450-1c6d7091-140c-4861-af84-30a636979a13.png)
I change the color of the groups (factors) and the system crashes.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by vandenman** [comment]
Hi @andremonezi thanks for reporting this issue!

Would it be possible to upload a JASP file with this error? Note that in order to attach it on GitHub, you must zip it first.
