### ISSUE TITLE
[Bug]: JASP not running on Chromebook

### ISSUE THREAD

**Issue by juliann5432** [jasp-stats/jasp-issues#1826]
### What OS are you seeing the problem on?

Chromebook

### Bug Description

I have tried downloading JASP 5 times, and it shows up with the exact phrase every single time. I have not gotten the display to show at all. ( The welcome page)
I follow the instructions for the application from the website exactly but it still will not work. 
The phrase, (Warning: Not exporting file org.jaspstats.JASP.appdata.xml of unsupported type.)
I have a hw assignment due so this not being able to work is causing me issues :(

### Expected Behaviour

The welcome page is expected to pop up.

### Steps to Reproduce

I have no experience with JASP so I cannot explain the steps exactly. I just followed the instructions from the JASP website.

**Comment by JorisGoosen** [comment]
@juliann5432 

Perhaps you could tell me what step you are at in https://jasp-stats.org/chromebook-installation/ ?

And show me a screenshot of what is going on so I can verify you have in fact followed the instructions correctly.

Right now I really can't help you, you havent specified what command you are running, where you are running it, whether any of the steps before had any problems etc.

Once I know more we can see about getting JASP running on time to finish your assignment

**Comment by JorisGoosen** [comment]
Also I can reproduce this

**Comment by juliann5432** [comment]
I finish all the steps, even updating flatpak. I already got out of the terminal so I cannot show you the screenshot, however, it looked exactly like the screenshots on the website. 
I have gotten the application downloaded and it shows up on my computer, however, when I try to click on it to open it, nothing happens.

**Comment by juliann5432** [comment]
When I used (sudo umount /proc/{cpuinfo,diskstats,meminfo,stat,uptime}) its loading but it wont open still. It has had a loading sign for days before.

**Comment by JorisGoosen** [comment]
@juliann5432 You should open a terminal and run `flatpak run org.jaspstats.JASP`.
Then, when it doesnt work you copy all the text of the terminal to a textfile and then you should attach that here.

Because just telling me "it won't open" is not enough information and I would like to help you after all ;)
