### ISSUE TITLE
[Bug]: Some Strings are not translatable via weblate

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#1829]
### JASP Version

0.16.3

### JASP Module

jaspFrequencies, jaspRegression

### What analysis are you seeing the problem on?

Contingency tables and Regression

### What OS are you seeing the problem on?

all

### Bug Description

see pictures

### Expected Behaviour

all strings should be translatable

### Steps to Reproduce

1. 
2. 
3. 
...

### Log (if any)

"Count" is not translatable here:
![grafik](https://user-images.githubusercontent.com/4428185/190120548-8195a2d0-d85c-48f4-a26b-372bf5eee4de.png)

same for the highlighted here:
![Screenshot_20220914_114502](https://user-images.githubusercontent.com/4428185/190121547-8a81cd9e-4b30-47c5-a8a9-a41466d76173.png)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Very strange - with JASP 0.17 those strings are still not translated - but the translations are set in weblate:
![grafik](https://user-images.githubusercontent.com/4428185/216380051-c6f8bde7-6792-498a-a273-fbb68947d05c.png)

**Comment by boutinb** [comment]
In the Logistische Regression, I see:
<img width="531" alt="Screenshot 2023-02-03 at 14 30 02" src="https://user-images.githubusercontent.com/503332/216615506-deb7ba1d-67f8-4ac4-890f-3410924cfa3f.png">
So `(Intercept)` is translated

**Comment by tomtomme** [comment]
Yes. Also fine in Generalized linear. But: 
![grafik](https://user-images.githubusercontent.com/4428185/217444185-3616e9da-524f-40ce-ad77-797ede868fa9.png)

**Comment by tomtomme** [comment]
> Very strange - with JASP 0.17 those strings are still not translated - but the translations are set in weblate: ![grafik](https://user-images.githubusercontent.com/4428185/216380051-c6f8bde7-6792-498a-a273-fbb68947d05c.png)

specifically this one still seems valid in 0.18.1 - seems to be translated in weblate, but does not show up, when I open jasp and switch to german
