### ISSUE TITLE
Jasp taskbar is missing 

### ISSUE THREAD

**Issue by saritfriedman** [jasp-stats/jasp-issues#183]
I’m trying to run some exploratory factor analyses using Jasp – however, it's missing the necessary task bar above that usually shows “file” and the plus sign etc. I have attached a screenshot. Is someone able to help me with this? 
Thank you!
![screenshot of jasp](https://user-images.githubusercontent.com/43715127/46253149-d4745400-c463-11e8-8190-8b173793b99f.PNG)

**Comment by JorisGoosen** [comment]
Hopefully the latest release of 0.10.0.0 fixed this problem completely by removing the task bar at all times ;)
