### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by belizondo1990** [jasp-stats/jasp-issues#1830]
### Description

cant open JASP on my laptop

### Purpose

for experimental psychology course 

### Is your feature request related to a problem?

when i download it onto my laptop i am able to access it, but once i shut my latop down, then turn it on, the next time i cant access JASP on my laptop

### Describe the solution you would like

would like to access JASP on my laptop without any issues 

### Describe alternatives that you have considered

deleted JASP off my laptop then re-downloaded and experience same issue

**Comment by shun2wang** [comment]
hi, this seems a bug report but not a 'Feature Request'.

can you open a bug report here? (click 'New issue' and choose first one 'bug report')
