### ISSUE TITLE
[Bug]: Error in model "Model 1" - Estimation failed

### ISSUE THREAD

**Issue by QBWoof** [jasp-stats/jasp-issues#1831]
### JASP Version

0.16.3

### JASP Module

jaspSem

### What analysis are you seeing the problem on?

Structural Equation Modeling - path analysis 

### What OS are you seeing the problem on?

MacOS Montery 12.5.1

### Bug Description

I tried to run my SEM path analysis and get the following message 

Error in model "Model 1" - Estimation failed Message:Breakup

Breakup is a categorical variable, so I wondered if this was giving me the issue (although I've run this analysis on previous versions of JASP with a different computer without a problem), but changing variable type doesn't help. 

![Screen Shot 2022-09-17 at 9 46 45 PM](https://user-images.githubusercontent.com/94058587/190880919-93d81efd-822b-4463-8b10-8af8053f305a.png)

### Expected Behaviour

The model would have run :) 

### Steps to Reproduce

1. I tried re-opening the dataset, shifting variables around in dataset, re-opening JASP etc
2. 
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment]
Hi @QBWoofm thanks for the report. Is it possible you share the data file or zipped .jasp file with us here?

**Comment by QBWoof** [comment]
Hi,

Let me delete all of the irrelevant data. Can I share it via email?

Thanks!

**Comment by juliuspf** [comment]
yes you can, try julius.pfadt<at>gmail.com

**Comment by LSLindeloo** [comment]
@juliuspf , could you forward the relevant files to me?

**Comment by juliuspf** [comment]
I could, if I got them :)

**Comment by LSLindeloo** [comment]
Haha okay thanks! We’ll wait then :)

Op wo 21 sep. 2022 om 09:03 schreef Julius Pfadt ***@***.***>
