### ISSUE TITLE
[Bug]: Tabs & Menu missing in main window (Flatpak under EndlessOS)

### ISSUE THREAD

**Issue by btreut** [jasp-stats/jasp-issues#1833]
### JASP Version

0.16.3

### What OS are you seeing the problem on?

EndlessOS 4.0.9

### Bug Description

I am a newbie to JASP, but looking at the Getting Started Video on Youtube, I have the impression that my main window is missing the tabs on the left side and the sandwich menu bars on the left, see enclosed screenshots.
![image](https://user-images.githubusercontent.com/8996291/191762337-912a24ea-5e45-499e-9523-1a1b27414610.png)
![image](https://user-images.githubusercontent.com/8996291/191762495-5a18b705-3bdc-45a6-bacf-c26bfd037944.png)

### Expected Behaviour

I expect to see the Tabs Files & Common and the sandwich menu.

### Steps to Reproduce

it happens every time, when I start Jasp on my laptop (acer Travelmate Spin B) running [EndlessOS
](https://endlessos.com/)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by shun2wang** [comment]
Hi @btreut ,
your screenshots looks OK, If you follow the installation [instructions](https://jasp-stats.org/linux-installation-guide/) on our website, I don't see anything unusual.

for my JASP on windows:
![image](https://user-images.githubusercontent.com/10348402/191777206-79e0b10e-0906-42ca-8c12-e4b3fd692de9.png)

can you open a data file and run some analysis?

**Comment by btreut** [comment]
@shun2wang I guess that if you hit the Alt key under Windows, you get the menu entries Files, Common and the menu on the right edge, especially the topic Help below. I do not see these entires and do not get them using Alt. 
![image](https://user-images.githubusercontent.com/8996291/191793624-aac7d859-7b8a-49ad-b817-37164dec7e59.png)

**Comment by Kucharssim** [comment]
Dear @btreut,

no need to worry, the screenshot with the hamburger menu on the right comes from an earlier version of JASP. Nothing is missing, only the GUI changed a little bit so the things are in other places:

- On the right side of the main panel you have the `+` symbol with which you can attach additional JASP modules. That corresponds to the "Modules" option in your screenshot.
- "About" and "Preferences" are now under the hamburger menu on the left.
- "Help" file is accessible from an individual analysis by clicking on the blue ℹ️ button in its header:


![Screenshot 2022-09-22 at 18 06 33](https://user-images.githubusercontent.com/7093546/191797246-3e6f99f4-d4e5-4ea4-b908-372de2133dd1.png)

**Comment by btreut** [comment]
Ok. Thanks for the clarification.
