### ISSUE TITLE
[Bug]: Fedora 36 Not Openin App

### ISSUE THREAD

**Issue by euyar42** [jasp-stats/jasp-issues#1836]
### JASP Version

0.16.3

### What analysis are you seeing the problem on?

When opening app, its crashed.

### What OS are you seeing the problem on?

Linux Fedora 36 KDE

### Bug Description

When opening app, its crashed.
This is the console result.
![Screenshot_20220924_100138](https://user-images.githubusercontent.com/70096810/192084788-33de66ce-72bc-45a5-8d02-4b42c02361fc.png)

This is the my system:
Operating System: Fedora Linux 36
KDE Plasma Version: 5.25.5
KDE Frameworks Version: 5.98.0
Qt Version: 5.15.5
Kernel Version: 5.19.9-200.fc36.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 6 × AMD Ryzen 5 4500U with Radeon Graphics
Memory: 5.7 GiB of RAM
Graphics Processor: AMD RENOIR
Manufacturer: LENOVO
Product Name: 20VG
System Version: ThinkBook 15 G2 ARE

### Expected Behaviour

The app open.

### Steps to Reproduce

1. I install via flathub.
2. open via double click.
3. open via terminal.
...

### Log (if any)

![Screenshot_20220924_100138](https://user-images.githubusercontent.com/70096810/192084827-b26c1206-97e5-4045-96d4-c92d7abc9436.png)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by shun2wang** [comment]
thanks for your report, could you please copy and paste all log in the terminal here? thanks

**Comment by euyar42** [comment]
Thank you, unfortunately that's the all log.

**Comment by JorisGoosen** [comment]
@euyar42 could you show us the output of the command `locale` ?

**Comment by euyar42** [comment]
![Screenshot_20220924_142004](https://user-images.githubusercontent.com/70096810/192095075-20845830-545f-4828-9e01-8f6687c1916f.png)

**Comment by euyar42** [comment]
These are the problem report app infos:
![Screenshot_20220924_220231](https://user-images.githubusercontent.com/70096810/192114491-fe3f4d34-6c2f-402b-a24e-609fbedbaed7.png)
![Screenshot_20220924_220231](https://user-images.githubusercontent.com/70096810/192114508-97088321-89f7-442a-951e-fef9057e9d42.png)
![Screenshot_20220924_220521](https://user-images.githubusercontent.com/70096810/192114549-a09cb2ee-f22c-4b53-8cba-ca8330061822.png)
![Screenshot_20220924_220548](https://user-images.githubusercontent.com/70096810/192114558-8d5293a9-e747-46f8-82f4-2b12a91225cf.png)

**Comment by JorisGoosen** [comment]
@euyar42 could you give this a try:
- open a terminal
- run: `export LC_MONETARY="en_US.UTF-8"`
- run: `export LC_MEASUREMENT="en_US.UTF-8"`
- in the same terminal start JASP

I hope it then does work, I think we've had some bugs like this before. But those usually had weirder locales set.

**Comment by euyar42** [comment]
This is worked but, i think ı have to do it everytime. If ı wanna solve the issue permanantly i think change my MEASUREMENT etc. settings:
![Screenshot_20220926_154122](https://user-images.githubusercontent.com/70096810/192278809-b17d9097-c1d9-426d-b5d4-3f92b94f8a69.png)
Thank you for your help! I hope this issue solved permanantly by JASP because in my country some regional setting different than others.

**Comment by JorisGoosen** [comment]
Hey @euyar42 

I dont think we'll be working on this issue anytime soon. It seems to only occur on linux-systems where some "strange" combination of `LC_*` values is made. Not entirely sure what is "strange" though, Ive also seen it with setting only one to a dutch locale while the rest was set to `en_us` (like you have roughly).

I hope it isnt too much of an inconvenience to set those values to something different permanently?

An other option would be to create a custom `.desktop` file for JASP (or a script) where you set those `LC_` values to the above right before starting JASP.

**Comment by euyar42** [comment]
Thank you, than ı will not close the issue, maybe solve in future.

**Comment by JorisGoosen** [comment]
@euyar42 well, Ive already closed it.
