### ISSUE TITLE
[Feature Request]: T-sized adjusted fit indices in SEM module

### ISSUE THREAD

**Issue by mjkofler** [jasp-stats/jasp-issues#1837]
### Description

Requesting addition of T-sized adjusted fit indices in SEM module for equivalence testing

### Purpose

T-sized adjusted fit indices appear to offer advantages over traditional fit indices and may be a helpful addition

### Use-case

Equivalence testing of models in SEM

### Is your feature request related to a problem?

A Reviewer is asking us to add these indices

### Describe the solution you would like

Adding T-sized adjusted RMSEA and CFI values

### Describe alternatives that you have considered

Learning R

### Additional context

It appears that R code is available and that these indices can be calculated from the chi-square values of the specified model and the independence model: 

Yuan, K.-H., Chan, W., Marcoulides, G. A., & Bentler, P. M. (2016). Assessing structural equation models by equivalence testing with adjusted fit indexes. Structural Equation Modeling: A Multidisciplinary Journal, 23(3), 319-330. [https://doi.org/10.1080/10705511.2015.1065414]

Marcoulides, K. M., & Yuan, K.-H. (2017). New ways to evaluate goodness of fit: A note on using equivalence testing to assess structural equation models. Structural Equation Modeling: A Multidisciplinary Journal, 24(1), 148-153. [https://doi.org/10.1080/10705511.2016.1225260]

**Comment by juliuspf** [comment]
hi @mjkofler, thanks for the request. Seems straightforward enough, @Kucharssim?

**Comment by mjkofler** [comment]
I think so? Complicating factor based on the Yuan paper is that these new RMSEA and CFI indices can’t be evaluated by the traditional ‘rules of thumb’ for what indicates excellent, close, adequate etc. fit, and that the ‘rule of thumb’ cutoffs for each vary based on model df and N. 

So it would seem that we’d need to run 3 R scripts from that paper:
1. Compute T-sized RMSEA and T-sized CFI using https://www3.nd.edu/%7Ekyuan/EquivalenceTesting/T-size_RMSEA_CFI.R <https://www3.nd.edu/~kyuan/EquivalenceTesting/T-size_RMSEA_CFI.R>
2. Compute T-sized RMSEA comparison values for excellent, close, fair, mediocre, and poor fit using https://www3.nd.edu/~kyuan/EquivalenceTesting/RMSEA_e.R <https://www3.nd.edu/~kyuan/EquivalenceTesting/RMSEA_e.R>
3. Compute T-sized RMSEA comparison values for excellent, close, fair, mediocre, and poor fit using https://www3.nd.edu/~kyuan/EquivalenceTesting/CFI_e.R <https://www3.nd.edu/~kyuan/EquivalenceTesting/CFI_e.R>

I could envision a Table giving the T-sized values in 1 column, then a 2nd column showing the values suggestive of each of the nominal descriptors. 

Inputs for script 1 are the chi-square, df, N, number of parameters for the model, and the chi square of the independence model. All of those values are in the JASP output except, as far as I can tell, the independence model chi-square. 

Inputs for 2 and 3 are model df and N.

Thanks!

**Comment by LSLindeloo** [comment]
@mjkofler, thanks for the detailed description! I will add this to the module asap.

> Op 27 sep. 2022 om 19:26 heeft mjkofler ***@***.***> het volgende geschreven:
> 
> ﻿
> I think so? Complicating factor based on the Yuan paper is that these new RMSEA and CFI indices can’t be evaluated by the traditional ‘rules of thumb’ for what indicates excellent, close, adequate etc. fit, and that the ‘rule of thumb’ cutoffs for each vary based on model df and N. 
> 
> So it would seem that we’d need to run 3 R scripts from that paper:
> 1. Compute T-sized RMSEA and T-sized CFI using https://www3.nd.edu/%7Ekyuan/EquivalenceTesting/T-size_RMSEA_CFI.R <https://www3.nd.edu/~kyuan/EquivalenceTesting/T-size_RMSEA_CFI.R>
> 2. Compute T-sized RMSEA comparison values for excellent, close, fair, mediocre, and poor fit using https://www3.nd.edu/~kyuan/EquivalenceTesting/RMSEA_e.R <https://www3.nd.edu/~kyuan/EquivalenceTesting/RMSEA_e.R>
> 3. Compute T-sized RMSEA comparison values for excellent, close, fair, mediocre, and poor fit using https://www3.nd.edu/~kyuan/EquivalenceTesting/CFI_e.R <https://www3.nd.edu/~kyuan/EquivalenceTesting/CFI_e.R>
> 
> I could envision a Table giving the T-sized values in 1 column, then a 2nd column showing the values suggestive of each of the nominal descriptors. 
> 
> Inputs for script 1 are the chi-square, df, N, number of parameters for the model, and the chi square of the independence model. All of those values are in the JASP output except, as far as I can tell, the independence model chi-square. 
> 
> Inputs for 2 and 3 are model df and N.
> 
> Thanks!
>

**Comment by mjkofler** [comment]
Awesome - thank you! Could you add an option to show the chi-square for the independence model also? (Or maybe I’m just missing where to get that info in the current build?).
