### ISSUE TITLE
[Bug]: error while setting test set indicator for Boosting classification

### ISSUE THREAD

**Issue by verboten999** [jasp-stats/jasp-issues#1838]
### JASP Version

0.16.3

### JASP Module

jaspMachineLearning

### What analysis are you seeing the problem on?

Boosting Classification

### What OS are you seeing the problem on?

Windows 10

### Bug Description

Error in `[.data.frame`(trainingAndValidationSet, , match(names(trainingAndValidationSet), : undefined columns selected

### Expected Behaviour

Successfully set which data set as test data on data set

### Steps to Reproduce

1. Select Machine Learning
2. Select Boosting Classification
3. Insert Features
4. Insert Target
5. Set seed to 1
6. Test set indicator to a variable (1 for test data)

### Log (if any)

Error in `[.data.frame`(trainingAndValidationSet, , match(names(trainingAndValidationSet), : undefined columns selected

Stack trace
doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

mlClassificationBoosting(...)

.mlClassificationTableSummary(dataset, options, jaspResults, ready, position = 1, type = 'boosting')

.mlClassificationComputeResults(dataset, options, jaspResults, ready, type = type)

.boostingClassification(dataset, options, jaspResults)

trainingAndValidationSet[, match(names(trainingAndValidationSet), all.vars(formula))]

`[.data.frame`(trainingAndValidationSet, , match(names(trainingAndValidationSet), all.vars(formula)))

stop('undefined columns selected')

![JASP error](https://user-images.githubusercontent.com/92387953/192525948-ea20807e-4e3a-4b90-a850-75b112c3ee57.png)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [ ] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by verboten999** [comment]
Hi,

Thanks for reaching out. I will send the file as soon as I'm able.


Regards

**Comment by verboten999** [comment]
Hi,

Attached is the requested file.


Regards

**Comment by juliuspf** [comment]
I am sorry, there is not attachment. You cannot attach the file to an email because GitHub does not allow those. You have to upload the file to this issue https://github.com/jasp-stats/jasp-issues/issues/1838.

**Comment by verboten999** [comment]
Hi,

I apologize for that. I uploaded the zip file here as per requested.

Regards

[Boosting-Try.zip](https://github.com/jasp-stats/jasp-issues/files/9665118/Boosting-Try.zip)

**Comment by tomtomme** [comment]
@verboten999 & @vandenman 
Sadly this bug persists. When refreshing the file I get

`An error occurred in the analysis: undefined columns selected`


When I change the data split prefs from "test set indicator" to "split by %" this changes to:

```
This analysis terminated unexpectedly.

Error in tapply(observed, predicted, sum): arguments must have same length

Stack trace
feature_importance.explainer(x = explainer, loss_function = loss_function, type = type, N = N, ...)

feature_importance.default(model, data, y, predict_function = predict_function, loss_function = loss_function, label = label, type = type, N = N, n_sample = n_sample, B = B, variables = variables, variable_groups = variable_groups, ...)

replicate(B, loss_after_permutation())

sapply(integer(n), eval.parent(substitute(function(...) expr)), simplify = simplify)

lapply(X = X, FUN = FUN, ...)

FUN(X[[i]], ...)

loss_after_permutation()

loss_function(observed, predict_function(x, sampled_data))

tapply(observed, predicted, sum)

stop('arguments must have same length')

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports
```

**Comment by tomtomme** [comment]
with 0.19 from 23.5.24 the error message is:

> An error occurred in the analysis: undefined columns selected

readding vars or even starting the analysis from scratch does not help.

**Comment by koenderks** [comment]
Linked PR will fix this.

<img width="1510" alt="image" src="https://github.com/jasp-stats/jasp-issues/assets/25059399/cb0ed441-06d1-4c12-8be5-5f95444b2e8f">
