### ISSUE TITLE
[Bug]: The resulting chart cannot be displayed.

### ISSUE THREAD

**Issue by wwwon09** [jasp-stats/jasp-issues#1839]
### JASP Version

0.16.3

### JASP Module

jaspDescriptives, jaspAnova, jaspFactor, jaspFrequencies

### What analysis are you seeing the problem on?

Descriptives

### What OS are you seeing the problem on?

Window 10

### Bug Description

A bug happened!I am working on the data analysis,I want to make a histogram of frequency distribution.But the drawing area is always blank.When I copy to word, the file is blank. I will send the screenshot to your email.What is the reason and what should I do?

### Expected Behaviour

The statistical chart should have been displayed instead of being blank.

### Steps to Reproduce

1. open
2. computer
3. desktop
4. descriptives
5. basic plots
6. distribution plots and correlation plots

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by shun2wang** [comment]
maybe a duplication of https://github.com/jasp-stats/jasp-issues/issues/1703
Are there any non-ASCII characters in your PC user name? if so that will be solved in next release version in a few days.

**Comment by wwwon09** [comment]
> Do I need to download jasp again after changing my username?

**Comment by wwwon09** [comment]
Do I need to download jasp again after changing my username?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jasp-stats/jasp-issues"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月28日(星期三) 下午3:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jasp-stats/jasp-issues] [Bug]: The resulting chart cannot be displayed. (Issue #1839)





 
maybe a duplication of #1703
 Are there any non-ASCII characters in your PC user name? if so that will be solved in next release version in a few days.

**Comment by shun2wang** [comment]
You can just download this pre-release http://static.jasp-stats.org/Nightlies/WindowsZip/JASP-nightly-stable-d661fe4ae66457f3c203188e0500a3ff18aba29a.zip and unziped to try it. Please note that this is not an official release, you can try to see if it solves your problem and wait for our official release (it will only take a few days)

**Comment by wwwon09** [comment]
Can you tell me how to download it? There are many files after decompression.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jasp-stats/jasp-issues"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月28日(星期三) 下午3:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jasp-stats/jasp-issues] [Bug]: The resulting chart cannot be displayed. (Issue #1839)





 
You can just download this pre-release http://static.jasp-stats.org/Nightlies/WindowsZip/JASP-nightly-stable-d661fe4ae66457f3c203188e0500a3ff18aba29a.zip and unziped to try it. Please note that this is not an official release, you can try to see if it solves your problem and wait for our official release (it will only take a few days)

**Comment by shun2wang** [comment]
Double click JASP.exe to start it

**Comment by wwwon09** [comment]
Thank you very much.My problem has been solved.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jasp-stats/jasp-issues"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月28日(星期三) 下午4:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jasp-stats/jasp-issues] [Bug]: The resulting chart cannot be displayed. (Issue #1839)





 
Double click JASP.exe to start it
