### ISSUE TITLE
Computation of IC95% in descriptive statistics

### ISSUE THREAD

**Issue by vicenteinefo** [jasp-stats/jasp-issues#184]
* Enhancement: In dispersion statistics section of descriptive statistics analysis, standard error (SE mean) is available but IC95% is not shown
* Purpose:  It would be an excellent teaching resource for undergraduate students.

**Comment by AlexanderLyNL** [comment]
Discussed here: https://github.com/jasp-stats/jasp-desktop/issues/2672

But it is possible to get the 2.5 and 97.5 % percentiles from a (sampling) distribution, via the "Statistics" tab.
