### ISSUE TITLE
[Bug]: error in Neighborhood-Based Clustering, t-SNE

### ISSUE THREAD

**Issue by lwilleminpetignat** [jasp-stats/jasp-issues#1840]
### JASP Version

0.16.3

### JASP Module

jaspMachineLearning

### What analysis are you seeing the problem on?

Neighborhood-Based Clustering

### What OS are you seeing the problem on?

Window 10

### Bug Description

Cette analyse s'est terminée de manière inattendue.

Error in data.frame(x = tsne$Y[, 1], y = tsne$Y[, 2], cluster = predictions): les arguments impliquent des nombres de lignes différents : 28, 2618

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

mlClusteringKMeans(...)

.mlClusteringPlotTsne(dataset, options, jaspResults, ready, position = 8, type = 'kmeans')

data.frame(x = tsne$Y[, 1], y = tsne$Y[, 2], cluster = predictions)

stop(gettextf('arguments imply differing number of rows: %s', paste(unique(nrows), collapse = ', ')), domain = NA)

Pour recevoir de l'aide concernant ce problème, veuillez signaler le message ci-dessus à l'adresse suivante : https://jasp-stats.org/bug-reports

### Expected Behaviour

I can't have the "t-SNE cluster plot" and I don't understand why... Probably something basic but I'm new on Jasp.

### Steps to Reproduce

1. Take my variable
2. Clic on "Machine learninng - Neighborhood - based"
3. Clic "t-SNE cluster plot"
4. Bug occurs
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [x] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by lwilleminpetignat** [comment]
I saw that the problem is due to the t-SNE removing duplicates rows (saw this in a previous post) but I don't understand how to fix that.

**Comment by juliuspf** [comment]
Hi @lwilleminpetignatm thanks for reporting this. Could you share a zipped .jasp file with the issue, or a data file that causes the error?

**Comment by lwilleminpetignat** [comment]
[JASP.zip](https://github.com/jasp-stats/jasp-issues/files/9664069/JASP.zip)
