### ISSUE TITLE
[Bug]: Windows Installer error when installing JASP 0.16.2.0 or JASP 0.16.3.0 - cant install JASP

### ISSUE THREAD

**Issue by kallochs** [jasp-stats/jasp-issues#1841]
### JASP Version

0.16.2

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I am having troubles with your program, and different versions have been tried.  When installing JASP, I receive the following error:
![image](https://user-images.githubusercontent.com/114593506/192812361-1b51175b-c55d-4292-bf82-6af4ad194cd5.png)
JASP 0.16.2.0 SETUP:
There is a problem with this Windows Installer package.  A program run as part of the setup did not finish as expected.  Contact your support personnel or package vendor.

I am support personnel and I have tried two versions and several PC's and receive the same error each time.
![JASP ERROR](https://user-images.githubusercontent.com/114593506/192813264-81bfe764-31ed-4fb4-8e41-427d78063fe9.png)

### Expected Behaviour

Hoping to install package for use by a Doctor.

### Steps to Reproduce

1. see above write up of what I have done
2. 
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JorisGoosen** [comment]
@kallochs are you running the installer as an administrator? 

Also, could you try downloading and unpacking https://static.jasp-stats.org/JASP-0.16.3-64bit.zip ?
Then once you have it unpacked you could open a command prompt and run `JASP.exe`

It should create folders called something like `jaspDescriptives` etc inside `Modules`. If not there might be some permissions issues on your computers.

JASP (or the installer) needs to have permission to create junctions in its install folder and that is where your install seems to fail.

**Comment by JorisGoosen** [comment]
Aah hey, @kallochs what kind of computer are you trying to install on?

As in, what kind of CPU does it have, because we've had this issue: #1822 
We do not yet support windows ARM im afraid.

**Comment by kallochs** [comment]
One is a Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz   3.41 GHz
Another is Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz   1.90 GHz

Both are 64bit processors

Thank you,
Sonja Kalloch, ---<--<--({@
InformationTechnology Specialist
VA Maine Area (Station 402)
"I think a hero is an ordinary individual who finds strength to persevere and endure in spite of overwhelming obstacles. " - Christopher Reeve

From: Joris Goosen ***@***.***>
Sent: Wednesday, September 28, 2022 11:46 AM
To: jasp-stats/jasp-issues ***@***.***>
Cc: Kalloch, Sonja J. ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [jasp-stats/jasp-issues] [Bug]: Windows Installer error when installing JASP 0.16.2.0 or JASP 0.16.3.0 - cant install JASP (Issue #1841)


Aah hey, @kallochs<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkallochs&data=05%7C01%7C%7C9bcc4623be7f4554bb4108daa1689a15%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637999767875531972%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zDULq894giWvqHOqWDZEdCkFh83DmE8U8Yln8dY8Egk%3D&reserved=0> what kind of computer are you trying to install on?

As in, what kind of CPU does it have, because we've had this issue: #1822<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjasp-stats%2Fjasp-issues%2Fissues%2F1822&data=05%7C01%7C%7C9bcc4623be7f4554bb4108daa1689a15%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637999767875531972%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hb5R7FEsGIdq9TckLSg6LYT8WUFAz6Wqy9wvJqH%2FWCs%3D&reserved=0>
We do not yet support windows ARM im afraid.

-

**Comment by JorisGoosen** [comment]
Did you see these questions as well @kallochs ?

> @kallochs are you running the installer as an administrator?
> 
> Also, could you try downloading and unpacking [static.jasp-stats.org/JASP-0.16.3-64bit.zip](https://static.jasp-stats.org/JASP-0.16.3-64bit.zip) ? Then once you have it unpacked you could open a command prompt and run `JASP.exe`
> 
> It should create folders called something like `jaspDescriptives` etc inside `Modules`. If not there might be some permissions issues on your computers.
> 
> JASP (or the installer) needs to have permission to create junctions in its install folder and that is where your install seems to fail.

**Comment by JorisGoosen** [comment]
@kallochs 
Can you open a command prompt in windows and try the following:
```
mkdir test
cd test
mkdir folder
mklink /j junction folder
dir /a
```
Please copy all the output here

**Comment by kallochs** [comment]
c:\>mkdir test
c:\>cd test
c:\test>mklink /j junction folder
Junction created for junction <<===>> folder
c:\test>dir /a
 Volume in drive C is OSDisk
 Volume Serial Number is 9E40-4543
 Directory of c:\test
09/29/2022  11:40 AM    <DIR>          .
09/29/2022  11:40 AM    <DIR>          ..
09/29/2022  11:40 AM    <JUNCTION>     junction [c:\test\folder]
               0 File(s)              0 bytes
               3 Dir(s)  189,027,241,984 bytes free
c:\test>

**Comment by JorisGoosen** [comment]
Thank you @kallochs !

Well at least the problem doesn't seem to be making the junctions, so that's something.
In https://github.com/jasp-stats/jasp-issues/issues/1807#issuecomment-1262419496 the solution seemed to be updating the graphics driver.

Another way could be by minimizing the graphics requirements of JASP during junction creation and subsequent runs.
Could you try downloading https://static.jasp-stats.org/JASP-0.16.4-64bit.zip and unpacking it somewhere, then in a command prompt:
```
cd <to/the/folder-where-you-unpacked>
jasp --safeGraphics --junctions
```

After it's done the `Modules` folder in the unpacked `JASP-0.16.4-64bit` should look like:
![image](https://user-images.githubusercontent.com/29062713/193560069-0002a70d-448d-49a8-b274-1ff0f49a2176.png)

**Comment by kallochs** [comment]
Good morning,

I am still not able to get this product installed - I get this notice, and after leaving it all night (from 1PM yesterday to this morning)  and again today using the updated version you sent me with the link below.  How long should this take to install?

***@***.***


In addition, the CMD path you asked me to try is not complete, or perhaps I am not understanding your intent with jasp --safeGraphics -junctions What is it I am to being at the command prompt, I have never seen a command line like this before.


Thank you,
Sonja Kalloch, ---<--<--({@
InformationTechnology Specialist
VA Maine Area (Station 402)
"I think a hero is an ordinary individual who finds strength to persevere and endure in spite of overwhelming obstacles. " - Christopher Reeve

From: Joris Goosen ***@***.***>
Sent: Monday, October 3, 2022 6:53 AM
To: jasp-stats/jasp-issues ***@***.***>
Cc: Kalloch, Sonja J. ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [jasp-stats/jasp-issues] [Bug]: Windows Installer error when installing JASP 0.16.2.0 or JASP 0.16.3.0 - cant install JASP (Issue #1841)


Thank you @kallochs<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkallochs&data=05%7C01%7C%7Cf461a0a84b8646ac87cc08daa52d71a9%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638003912947230488%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2j%2FGl7WZf4L0mJ4lLuEoXZVrKtV1%2FYmn9vOvmwADrYc%3D&reserved=0> !

Well at least the problem doesn't seem to be making the junctions, so that's something.
In #1807 (comment)<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjasp-stats%2Fjasp-issues%2Fissues%2F1807%23issuecomment-1262419496&data=05%7C01%7C%7Cf461a0a84b8646ac87cc08daa52d71a9%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638003912947230488%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=CIne%2FpyxnsY0jo3p1W4yzM%2FdMbyQwFxZIoNpHGOUmsU%3D&reserved=0> the solution seemed to be updating the graphics driver.

Another way could be by minimizing the graphics requirements of JASP during junction creation and subsequent runs.
Could you try downloadingDIR and unpacking it somewhere, then in a command prompt:

cd <to/the/folder-where-you-unpacked>

jasp --safeGraphics --junctions

After it's done the Modules folder in the unpacked JASP-0.16.4-64bit should look like:
[image]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F29062713%2F193560069-0002a70d-448d-49a8-b274-1ff0f49a2176.png&data=05%7C01%7C%7Cf461a0a84b8646ac87cc08daa52d71a9%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638003912947230488%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=S6PG9aLV9l6xyPX%2BA5VM%2BwXRlnrofvUHaCxGPxQ7eU0%3D&reserved=0>

-

**Comment by kallochs** [comment]
I finally had success with the newest version you sent the link for.  This item can be listed as resolved, please.

Thank you,
Sonja Kalloch, ---<--<--({@
InformationTechnology Specialist
VA Maine Area (Station 402)
"I think a hero is an ordinary individual who finds strength to persevere and endure in spite of overwhelming obstacles. " - Christopher Reeve

From: Kalloch, Sonja J.
Sent: Thursday, October 6, 2022 8:46 AM
To: jasp-stats/jasp-issues ***@***.***>
Subject: RE: [EXTERNAL] Re: [jasp-stats/jasp-issues] [Bug]: Windows Installer error when installing JASP 0.16.2.0 or JASP 0.16.3.0 - cant install JASP (Issue #1841)

Good morning,

I am still not able to get this product installed - I get this notice, and after leaving it all night (from 1PM yesterday to this morning)  and again today using the updated version you sent me with the link below.  How long should this take to install?

***@***.***


In addition, the CMD path you asked me to try is not complete, or perhaps I am not understanding your intent with jasp --safeGraphics -junctions What is it I am to being at the command prompt, I have never seen a command line like this before.


Thank you,
Sonja Kalloch, ---<--<--({@
InformationTechnology Specialist
VA Maine Area (Station 402)
"I think a hero is an ordinary individual who finds strength to persevere and endure in spite of overwhelming obstacles. " - Christopher Reeve

From: Joris Goosen ***@***.******@***.***>>
Sent: Monday, October 3, 2022 6:53 AM
To: jasp-stats/jasp-issues ***@***.******@***.***>>
Cc: Kalloch, Sonja J. ***@***.******@***.***>>; Mention ***@***.******@***.***>>
Subject: [EXTERNAL] Re: [jasp-stats/jasp-issues] [Bug]: Windows Installer error when installing JASP 0.16.2.0 or JASP 0.16.3.0 - cant install JASP (Issue #1841)


Thank you @kallochs<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkallochs&data=05%7C01%7C%7Cf461a0a84b8646ac87cc08daa52d71a9%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638003912947230488%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2j%2FGl7WZf4L0mJ4lLuEoXZVrKtV1%2FYmn9vOvmwADrYc%3D&reserved=0> !

Well at least the problem doesn't seem to be making the junctions, so that's something.
In #1807 (comment)<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjasp-stats%2Fjasp-issues%2Fissues%2F1807%23issuecomment-1262419496&data=05%7C01%7C%7Cf461a0a84b8646ac87cc08daa52d71a9%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638003912947230488%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=CIne%2FpyxnsY0jo3p1W4yzM%2FdMbyQwFxZIoNpHGOUmsU%3D&reserved=0> the solution seemed to be updating the graphics driver.

Another way could be by minimizing the graphics requirements of JASP during junction creation and subsequent runs.
Could you try downloadingDIR and unpacking it somewhere, then in a command prompt:

cd <to/the/folder-where-you-unpacked>

jasp --safeGraphics --junctions

After it's done the Modules folder in the unpacked JASP-0.16.4-64bit should look like:
[image]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F29062713%2F193560069-0002a70d-448d-49a8-b274-1ff0f49a2176.png&data=05%7C01%7C%7Cf461a0a84b8646ac87cc08daa52d71a9%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638003912947230488%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=S6PG9aLV9l6xyPX%2BA5VM%2BwXRlnrofvUHaCxGPxQ7eU0%3D&reserved=0>

-

**Comment by JorisGoosen** [comment]
@kallochs I am wondering though, did you finally figure out what I meant with the cmd path?

And did you manage to run JASP.exe from the command prompt or just doubleclicking in the unzipped folder?

This is important to know because then I could or could not add the "safeGraphics" flag to the standard run of JASP during the installer. That way in the future it will also work from the installer.

**Comment by kallochs** [comment]
No, I did not figure out what you meant for the command prompt.

The software was installed by me, an administrator - but is not available for the end user.  It does come up an offer him a Remote App with JASP - he said he will try this.

Thank you,
Sonja Kalloch, ---<--<--({@
InformationTechnology Specialist
VA Maine Area (Station 402)
"I think a hero is an ordinary individual who finds strength to persevere and endure in spite of overwhelming obstacles. " - Christopher Reeve

From: Joris Goosen ***@***.***>
Sent: Thursday, October 6, 2022 11:56 AM
To: jasp-stats/jasp-issues ***@***.***>
Cc: Kalloch, Sonja J. ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [jasp-stats/jasp-issues] [Bug]: Windows Installer error when installing JASP 0.16.2.0 or JASP 0.16.3.0 - cant install JASP (Issue #1841)


@kallochs<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkallochs&data=05%7C01%7C%7Cb0afd5ec5f8449b2920008daa7b33b00%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638006685481604638%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=uU3m848nXCaqs6FL2K3Yyi0SOLxoosknajFYt7zq3lQ%3D&reserved=0> I am wondering though, did you finally figure out what I meant with the cmd path?

And did you manage to run JASP.exe from the command prompt or just doubleclicking in the unzipped folder?

This is important to know because then I could or could not add the "safeGraphics" flag to the standard run of JASP during the installer. That way in the future it will also work from the installer.

-

**Comment by bassam-abulnoor** [comment]
Hello,
I have the same problem. I have windows 7 I know the support ended from 0.13 version but I had no problem till 0.16 but any version after that I try to install I'm faced with the same error. I tried this
```
cd <to/the/folder-where-you-unpacked>
jasp --safeGraphics --junctions 
```
for the zip version extract but it gave me "access denied" although I'm the administrator. Is there a workaround for this issue or it's related to my OS.
Thanks a lot in advance.

**Comment by JorisGoosen** [comment]
@bassam-abulnoor can you open a new issue instead of opening this up again?
Also, you can try running that command prompt *as administrator* through the right-click menu.
