### ISSUE TITLE
[Bug]: Importing CSV with non-ascii created in local codepage in Excel has problems

### ISSUE THREAD

**Issue by JorisGoosen** [jasp-stats/jasp-issues#1842]
### JASP Version

0.16.4 on Windows

### Bug Description

JASP 0.16.4 contains R 4.2.1 and this allows for using UTF-8 everywhere, this has fixed quite a few problems in JASP.
But there are still some issues with the workaround implemented in https://github.com/jasp-stats/jasp-desktop/commit/a0d1f6a9661e5c8180a9b9913673f0df785be566 (supporting reading CSV encoded in local codepage)
This is related also to https://github.com/jasp-stats/jasp-issues/issues/1811

These both (if working at all) would show garbled text, so instead of chinese (if the local codepage is that) you might get random unicode characters.

### Expected Behaviour
Expected behaviour would be to gracefully handle reading those files.

### Workaround
Luckily there is an easy workaround, exporting as a utf-8 csv. This also makes it possible to share your csv with other around the world and still allowing them to load it properly.

(As reading a csv in local codepage of chinese on a machine with local codepage dutch (for instance) would also fail.
This because Excel wouldnt know in which codepage the file was exported...

**Comment by JorisGoosen** [comment]
There seems to be no way to discover what codepage is selected by the user due to JASP running in UTF-8.
At least not through the windows api.

A possibility could be to open a separate program to query the codepage and return that to jasp somehow. But that would be a bit complicated and would probably entail writing to a textfile.

Another option would be to add a dropdown to let the user select a local codepage to use when reading the csv.
However, that would also be a rather complicated solution.

What I am leaning towards is just dropping support for the old local codepages entirely and just revert back to only supporting utf8 csvs, like on linux and mac.
Then we just need to let people know that if they get weird characters after loading a csv from excel they should open it in excel and just save it as utf-8.
Because that is rather easy and is also the only application that makes this weird choice.

**Comment by shun2wang** [comment]
>What I am leaning towards is just dropping support for the old local codepages entirely and just revert back to only supporting utf8 csvs, like on linux and mac.

I agree!

>Another option would be to add a dropdown to let the user select a local codepage to use when reading the csv.

We should note that this may not only be for csv, but the. sav file of SPSS and STATA also have the problem of [local encoding](https://github.com/jasp-stats/jasp-issues/issues/1532). Therefore, it may be a good way to have a preview for user to decide which encoding that "looks normal". See https://github.com/jasp-stats/INTERNAL-jasp/issues/2119

**Comment by shun2wang** [comment]
Great! yeah I think so that we don't need to deploy it in this release, but the next version.🍻

**Comment by JorisGoosen** [comment]
Ive still got an hour and a half :p

**Comment by JorisGoosen** [comment]
So with the not quite polished code I get:
![afbeelding](https://user-images.githubusercontent.com/29062713/212079996-63a7218d-1353-4dd9-bca5-42c68d964ad9.png)

and selected codepage:
![afbeelding](https://user-images.githubusercontent.com/29062713/212080105-885e7cf8-a8b7-4308-845c-b140ed175652.png)

**Comment by shun2wang** [comment]
Here I think shold choose the encoding code but not codepage. because codepage is system locale(windows 936) but file encoding is GB18030.

**Comment by JorisGoosen** [comment]
Well, a codepage is an encoding right? But Ill check in the list I get whether anything that looks like it is in there
quite a few possibilities

**Comment by JorisGoosen** [comment]
![afbeelding](https://user-images.githubusercontent.com/29062713/212082002-674d0baa-7ac4-4143-9ef4-62a7b15aa3a1.png)
 
![afbeelding](https://user-images.githubusercontent.com/29062713/212082107-5ccee013-add5-464a-ba9f-aa8971874486.png)

Looks good no?

**Comment by JorisGoosen** [comment]
Ow but this isnt:
![afbeelding](https://user-images.githubusercontent.com/29062713/212082948-3513e606-b7ed-4eb5-b5a5-0f57537fb29c.png)

**Comment by shun2wang** [comment]
The text in the above two pictures is correctly decoded without garbled code.

I  confuse for codepage what I see. If Iopen a csv file with a text editor (such as notepad++), Ican see its encoding code in the lower right corner.

like this:
![图片](https://user-images.githubusercontent.com/10348402/212082474-189302da-b308-4d3c-96dc-5afb7f7a48ff.png)

**Comment by JorisGoosen** [comment]
I guess that issue is still in there...

**Comment by shun2wang** [comment]
What system codepage do your PC on? if it depends on system codepage?

**Comment by JorisGoosen** [comment]
But maybe there is some code in our csv reader that gets confused by CJK, im looking through a hex-editor as we speak ;)

This does mean there really is no way Im gonna finish this for this release.

**Comment by shun2wang** [comment]
Don't worry, I don't think it's urgent. I checked again and it works on the local code page at least for now.
as I said in https://github.com/jasp-stats/INTERNAL-jasp/issues/1750#issuecomment-1262325439

**Comment by JorisGoosen** [comment]
Im not worried, its more of a challenge than anything else :P

**Comment by JorisGoosen** [comment]
Although I dont really have an spss file saved in another locale I think. Im gonna look for that issue

**Comment by shun2wang** [comment]
haha, great, I will always support you to do this, because coding itself is a headache.🍻

**Comment by JorisGoosen** [comment]
Thank you!

Sadly enough my code cant work with stata/spss because it causes the same error as prompted you to open https://github.com/WizardMac/ReadStat/issues/263 ...

But at least it looks like something that could be fixed in ReadStat, so maybe I can work on that after my time off.

**Comment by shun2wang** [comment]
Yes, I realized that we using ReadStat, then I think the that was a upstream issue, but the upstream repair is usually very cautiously (meaning slow).

**Comment by JorisGoosen** [comment]
well I guess it would go slower if we give them code
