### ISSUE TITLE
[Bug]:  JASP can not plot with unicode user name on windows

### ISSUE THREAD

**Issue by Alishka-1706** [jasp-stats/jasp-issues#1843]
### Description

версия JASP 0.16.3.0. Windows 10

### Is your feature request related to a problem?

I can't make a conspiracy. a window for the graph will appear, but there is no graph itself.

### Describe alternatives that you have considered

I tried to set a safe graphics mode and a dark theme
![lcgdR6-_S8s](https://user-images.githubusercontent.com/114731347/193234664-156d7c5b-628f-40b1-aef3-eca0648dde8f.jpg)

**Comment by shun2wang** [comment]
@Alishka-1706 Thanks for the report, this is indeed a known issue. It has been fixed in the next version, you can download the latest version on the official website soon or [here](https://github.com/jasp-stats/jasp-desktop/releases/tag/v0.16.4)

**Comment by boutinb** [comment]
This version will be public next week.

**Comment by shun2wang** [comment]
@Alishka-1706 you can download the release now at https://jasp-stats.org/download/

**Comment by Alishka-1706** [comment]
Thanks for the answer! 

>Вторник, 4 октября 2022, 06:05 +03:00 от Shun Wang < ***@***.*** >:
>
***@***.*** you can download the release now at  https://jasp-stats.org/download/
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you were mentioned. Message ID:  <jasp-stats/jasp-issues/issues/1843/1266334572 @ github . com>

--
