### ISSUE TITLE
Compute and re-code into new variables in JASP?

### ISSUE THREAD

**Issue by PerPalmgren** [jasp-stats/jasp-issues#1844]
### Description

Hi.  I dont get an answer in the JASP forum so I try here. Could somebody help me🙏.  How do I go about to:  a) create a new nominal (binary) variable from a scale variable. So, I have an age variable (denoted as year of age) and I want to dichotomize this to a nominal variable with two levels, thus, under or equal to the mean age =1 and over the mean age = 2.  b) collapse an ordinal scale (Likert) with five steps to an ordinal scale with three steps. Thus, I want 1 & 2 =1, 3=2 and 4 & 5 =3.  Grateful for some help :-)

**Comment by vandenman** [comment]
Hi @PerPalmgren, sorry to hear that you didn't get a response on the forum. Let me try to answer your questions:

### Recoding a scale variable into a binary nominal variable

Essentially, you'd create a new column with computed columns and then enter something like this:

![image](https://user-images.githubusercontent.com/21319932/193261775-019c38fb-aec8-4982-bf5c-c0a22aa5e817.png)

Here `Years of age` is simulated with `round(abs(rnorm(100, 21, 3)))`.

### Collapse an ordinal scale (Likert) with five steps to an ordinal scale with three steps.

You can achieve this by nesting the ifElse statements, like so:

![image](https://user-images.githubusercontent.com/21319932/193262217-3aaca6ac-6f36-49e3-a291-395c9b7152e2.png)

Here, `facFive` is the variable in the debug dataset.

You can also type these using R code, which I find easier as soon as you need to nest multiple `ifElse` statements. To use R code, make sure you click on the R after creating a new column:

![image](https://user-images.githubusercontent.com/21319932/193262511-8c8f4b6c-e34b-4f70-b001-47f9f7507a76.png)

Afterward, you can type something like this:

```r
ifElse(facFive <= 2, 1, 
ifElse(facFive <= 3, 2, 3)
)
```
to generate the new ordinal variable.

You can check that the results are as intended using contingency tables:

![image](https://user-images.githubusercontent.com/21319932/193262889-59726cc6-d4a6-403d-ae9a-51253862d961.png)


Let me know if that answers your questions!

**Comment by PerPalmgren** [comment]
Thank you this was very helpful :-)

**Comment by juliuspf** [comment]
@PerPalmgren Does that mean it can be closed? Your comment actually triggered the action to remove the stale label, which means the issue will be exempted from closing in 42 days :)

**Comment by PerPalmgren** [comment]
Yes!😛 it can be closed and sorry for triggering.

Per J. Palmgren | DC, FRCC, MMedEd, PhD |
Associate Professor |
Department of Learning, Informatics, Management and Ethics |
Karolinska Institutet | Tomtebodavägen 18A | 171 77 Stockholm |
Tel. + 46 8 524 85 294<tel:+%2046%208%20524%2085%C2%A0294>
***@***.******@***.***> | ki.se<https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fki.se%2F&data=04%7C01%7Cper.palmgren%40ki.se%7C9f6969aac91f4526542308d875898009%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637388580700328145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=f6OY6fEm6z0scmnO%2FDhlWRgL%2BujfjA072A2uHaASfNY%3D&reserved=0>
________________________________

Karolinska Institutet – a medical university
