### ISSUE TITLE
[Bug]: variance-covariance matrix input in JASP SEM

### ISSUE THREAD

**Issue by Majous** [jasp-stats/jasp-issues#1845]
### JASP Version

0.16.3

### JASP Module

jaspSem

### What analysis are you seeing the problem on?

SEM with variance-covariance matrix input

### What OS are you seeing the problem on?

Windows 10 Home

### Bug Description

After opening the variance-covariance matrix, when I want to use it as a input in SEM, theres a bug reporting that the input is not a proper variance-covariance matrix. Same in JASP v. 14 and the latest version. I checked the matrix in R and it is positive-definite.

### Expected Behaviour

I would like that sem to work instead of reporting the bug.

### Steps to Reproduce

1. Opening the .csv file 
2. opening SEM
3. choosing var-cov matrix as input
4. writing equations, ctrl+enter

### Log (if any)

[JASP 2022-10-03 16_45_28 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/9698496/JASP.2022-10-03.16_45_28.Desktop.log)
[JASP 2022-10-03 16_45_28 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/9698497/JASP.2022-10-03.16_45_28.Engine.0.log)
[polychor for jasp v. 7.csv](https://github.com/jasp-stats/jasp-issues/files/9698498/polychor.for.jasp.v.7.csv)
![bug_jasp](https://user-images.githubusercontent.com/63358644/193607444-64f5e8d7-ade2-4d89-aba3-3b04cc24e73c.png)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment]
Hi @Majous, thanks for reporting this! @Kucharssim I can reproduce this. It seems something is going wrong in `.semReadData` when a covariance matrix is the input. When I look at what the resulting "dataset" from this function looks like then it is not a square matrix. The function just reads the data according to the columns specified, although for a covariance matrix it should also use the columns as rows. For the matrix from this issue the resulting dataset that is put out from `.semReadData` has 38 rows and 2 columns. We might need an extra readData function

**Comment by Majous** [comment]
Thank you for the fast answer. I will wait for a solution

**Comment by Kucharssim** [comment]
@Majous thanks for submitting this report!

@juliuspf you are right; the analysis only reads the columns that are used in the models, but does not subset any rows, so that breaks the covariance matrix. It should be an easy fix

**Comment by Majous** [comment]
Good afternoon,

I would like to ask how long do you expect would it take to be resolved? In weeks, months? I would like to try. No pressure. Thank you for looking into that.

**Comment by boutinb** [comment]
This is planned for the next version which should be release in Januari.
