### ISSUE TITLE
[Bug]: Can't open files in Data Library

### ISSUE THREAD

**Issue by AnswersStat** [jasp-stats/jasp-issues#1846]
### JASP Version

0.16.3

### JASP Module

jaspDescriptives, jaspAnova

### What analysis are you seeing the problem on?

Descriptive data.csv

### What OS are you seeing the problem on?

Windows 10 Pro

### Bug Description

I'm trying to follow the JASP student guide but I'm constatly being asked to open files that don't exist in my data library. Is there a data base I need to sync to? I've attached an image of a single example, but I am finding the same with all files. Also, is there a way to find data library files by name or just by navigating through the menu? Thanks!
![JASP_Prob1](https://user-images.githubusercontent.com/114946426/193643936-f506fae3-8538-4101-95e6-61d398cdd91c.PNG)
![JASP 1](https://user-images.githubusercontent.com/114946426/193643989-05e3873a-e04c-47f3-812a-b10e334872d6.PNG)
![JASP2](https://user-images.githubusercontent.com/114946426/193644009-527c4892-34bb-4db6-b3be-1f36a82eb8eb.PNG)
![JASP3](https://user-images.githubusercontent.com/114946426/193644012-2a322b06-0b77-430a-941c-f1983394ca91.PNG)
![JASP4](https://user-images.githubusercontent.com/114946426/193644013-085c6eae-fcb8-43a5-8d98-95ccb3a89708.PNG)

### Expected Behaviour

DAta Library should include referenced files

### Steps to Reproduce

1. Redownloaded JASP today: https://jasp-stats.org/download/
2. Not sure how to reproduce the error
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment]
Hi @AnswersStat, thanks for the report. It might be the student guide is outdated and some files have been renamed. Could you post a link to the guide? All example data files should be in the "Data Library". It is unlikely that none of the files from the guide are available though. Any ideas, @AlexanderLyNL?

**Comment by EJWagenmakers** [comment]
Yes, the student guide is written by Mark Goss-Sampson and has its own data sets

**Comment by AlexanderLyNL** [comment]
I think that this issue is solved. Please reopen if not.
