### ISSUE TITLE
[Feature Request]: Naming of residuals in contingency tables in 016.4

### ISSUE THREAD

**Issue by PerPalmgren** [jasp-stats/jasp-issues#1847]
### Description

Naming of residuals

### Is your feature request related to a problem?

Why has the naming for the residuals (by the way a wonderful feature in this version) been unstandardized, Pearson and Standardized residuals? This is very confusing!!!! As the SPSS nomenclature is residuals, standardized residuals and adjusted residuals. So, in JASP Pearson´s residuals is the same as standardized residuals in SPSS? and in JASP standardized residuals is the same as adjusted residuals in SPSS? This is not optimal. See prinstscreen from SPSS and JASP below.

### Describe the solution you would like

Use more similar naming/nomenclature as SPSS or Unstandardized, Standardized and Adjusted standardized 

### Additional context
![Namnlös](https://user-images.githubusercontent.com/79397662/193903018-ef76f024-9b87-45e0-a02a-467ea07aad79.png)

[Residulas.zip](https://github.com/jasp-stats/jasp-issues/files/9709804/Residulas.zip)

**Comment by Kucharssim** [comment]
Dear @PerPalmgren,

I agree that the difference between JASP and SPSS is confusing for SPSS users, but we do have a reason to do this.

Consider that [Agresti (2019)](https://www.wiley.com/en-us/An+Introduction+to+Categorical+Data+Analysis%2C+3rd+Edition-p-9781119405283) calls the residuals that we call *standardized* the same as we do in JASP:

![Screenshot 2022-10-04 at 21 13 15](https://user-images.githubusercontent.com/7093546/193906546-104a319c-a497-48b3-837f-09de37156083.png)

And also provides a reason why Pearson residual is called that way (i.e., it is applicable to GLMs under the same name and directly leads into the Pearson Chi-square statistic):

![Screenshot 2022-10-04 at 21 12 08](https://user-images.githubusercontent.com/7093546/193906814-26110712-f049-4666-b2cc-61a69cc7fdca.png)

Our use of the terms is also consistent with the base function in R for doing a [chi-square test](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/chisq.test).

I understand that it is frustrating to see the confusion with the terminology in SPSS. However we are not trying to imitate whatever SPSS is doing, but rather try to make our own judgement. In cases like these (where I would argue SPSS itself deviates from other sources of literature and software packages), we will sometimes happen to deviate from it.

**Comment by PerPalmgren** [comment]
Hi Simon,

Thank you for your swift and thourugh reply. I understand this choice but maybe for clarity for JASP users it could rather be called Pearson residual and Standardized Pearson residual.

All the best

Per

Per J. Palmgren | DC, FRCC, MMedEd, PhD |
Associate Professor | Director of doctoral studies
Department of Learning, Informatics, Management and Ethics |
Karolinska Institutet | Tomtebodavägen 18A | 171 77 Stockholm |
Tel. + 46 8 524 85 294<tel:+%2046%208%20524%2085%C2%A0294>
***@***.******@***.***> | ki.se<https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fki.se%2F&data=04%7C01%7Cper.palmgren%40ki.se%7C9f6969aac91f4526542308d875898009%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637388580700328145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=f6OY6fEm6z0scmnO%2FDhlWRgL%2BujfjA072A2uHaASfNY%3D&reserved=0>
________________________________

Karolinska Institutet – a medical university

4 okt. 2022 kl. 21:34 skrev Simon Kucharsky ***@***.***>:

﻿

Dear @PerPalmgren<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPerPalmgren&data=05%7C01%7Cper.palmgren%40ki.se%7Cb97ae0025e3d4714426508daa63f74bb%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C638005088727631237%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XFDun8VnhL%2Fa6D9wp9aMzMyje%2F%2FMUQdqmFj5DEH%2Fdpc%3D&reserved=0>,

I agree that the difference between JASP and SPSS is confusing for SPSS users, but we do have a reason to do this.

Consider that Agresti (2019)<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.wiley.com%2Fen-us%2FAn%2BIntroduction%2Bto%2BCategorical%2BData%2BAnalysis%252C%2B3rd%2BEdition-p-9781119405283&data=05%7C01%7Cper.palmgren%40ki.se%7Cb97ae0025e3d4714426508daa63f74bb%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C638005088727631237%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qz4c50Sn2tH43JiJwz7H4faCylwVJ9rn3nF46OedrJ4%3D&reserved=0> calls the residuals that we call standardized the same as we do in JASP:

[Screenshot 2022-10-04 at 21 13 15]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F7093546%2F193906546-104a319c-a497-48b3-837f-09de37156083.png&data=05%7C01%7Cper.palmgren%40ki.se%7Cb97ae0025e3d4714426508daa63f74bb%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C638005088727631237%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2BaAhN4lXsovPfOCawN3X%2B27VW4e%2FIQdqJ0M879X7dL0%3D&reserved=0>

And also provides a reason why Pearson residual is called that way (i.e., it is applicable to GLMs under the same name and directly leads into the Pearson Chi-square statistic):

[Screenshot 2022-10-04 at 21 12 08]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F7093546%2F193906814-26110712-f049-4666-b2cc-61a69cc7fdca.png&data=05%7C01%7Cper.palmgren%40ki.se%7Cb97ae0025e3d4714426508daa63f74bb%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C638005088727631237%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=10DjQcoMH6UNpM0pwNYNmK2PxwT9UpQzQl%2BlenHR%2F78%3D&reserved=0>

Our use of the terms is also consistent with the base function in R for doing a chi-square test<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.rdocumentation.org%2Fpackages%2Fstats%2Fversions%2F3.6.2%2Ftopics%2Fchisq.test&data=05%7C01%7Cper.palmgren%40ki.se%7Cb97ae0025e3d4714426508daa63f74bb%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C638005088727631237%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YyxGoVYs1PeW0rLdpa4%2B2%2FPmqYR7yOF8o5TMJOgZbyg%3D&reserved=0>.

I understand that it is frustrating to see the confusion with the terminology in SPSS. However we are not trying to imitate whatever SPSS is doing, but rather try to make our own judgement. In cases like these (where I would argue SPSS itself deviates from other sources of literature and software packages), we will sometimes happen to deviate from it.

—
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjasp-stats%2Fjasp-issues%2Fissues%2F1847%23issuecomment-1267487834&data=05%7C01%7Cper.palmgren%40ki.se%7Cb97ae0025e3d4714426508daa63f74bb%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C638005088727631237%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=58zZw2JH6OORX4HOBHwspQ4eU8eE%2F%2FTMhryLFNXrYMo%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS5YGHU545CGYNTK24VHVCLWBSBEJANCNFSM6AAAAAAQ43JA4Y&data=05%7C01%7Cper.palmgren%40ki.se%7Cb97ae0025e3d4714426508daa63f74bb%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C638005088727631237%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PU%2FtHRQC78qmwQ85Dh2mNWHdXGjGY9JkEDZ3PpA84M4%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>



När du skickar e-post till Karolinska Institutet (KI) innebär detta att KI kommer att behandla dina personuppgifter. Här finns information om hur KI behandlar personuppgifter<https://ki.se/medarbetare/integritetsskyddspolicy>.


Sending email to Karolinska Institutet (KI) will result in KI processing your personal data. You can read more about KI’s processing of personal data here<https://ki.se/en/staff/data-protection-policy>.

**Comment by PerPalmgren** [comment]
Let me propose to call it (see reference below)
- Residuals
- Person residuals 
- Adjusted Pearson residuals
https://cscu.cornell.edu/wp-content/uploads/95_conttableresid.pdf

**Comment by PerPalmgren** [comment]
Any thoughts on my last suggestion?

**Comment by PerPalmgren** [comment]
@Kucharssim any thoughts on my suggestion for naming?

**Comment by PerPalmgren** [comment]
@Kucharssim @juliuspfadt 
I still think my suggestion with regards to the naming of residuals and the referens provided would make things more clear for JASP users. @Kucharssim the reference I provide also refer to the calculations by Agresti.
Kind regards
Per

**Comment by PerPalmgren** [comment]
Any response?

**Comment by Kucharssim** [comment]
Hi @PerPalmgren,

sorry, your earlier response slipped my attention. 

I will try to summarise. Please correct me if I am wrong.

Currently we have these types of residuals in JASP:

1. Unstandardized residuals: calculated as `observed - expected`
2. Pearson residuals: calculated as `(observed - expected) / sqrt(expected)`
3. Standardized residuals: calculated as `(observed - expected) / sqrt(V)`, where V is the residual error variance.

This is consistent with terminology used in R and other analyses like Poisson GLM as discussed in the Agresti reference.

SPSS uses the following names:

1. Residuals
2. Standardized residuals
3. Adjusted residuals

You propose to change the naming in the following way:

1. Residuals
2. Pearson residuals
3. Adjusted Pearson residuals

I admit I am still uncertain about this proposal as I would prefer to keep consistency with other JASP analyses and with references like Agresti rather than keeping consistency with SPSS. I also see a value in calling the third type of residuals as "standardized" as they follow the standard normal distribution under the null hypothesis.

Further, I see that the reference you provided uses three different names for the third type of residuals: "adjusted Pearson residuals", "adjusted standardized residuals", and "standardized residuals" - the latter is also used by JASP.

I do understand that the clash between what JASP calls "standardized" and what SPSS calls "standardized" is unfortunate, but I still think this could be clarified for SPSS users in the help file. Alternatively, it would be also possible to do something like

1. Unstandardized residuals
2. Pearson residuals
3. Standardized (adjusted Pearson) residuals

That's perhaps the best of the two worlds?

As this is mostly a matter of preference and conventions, perhaps @EJWagenmakers would want to give his opinion?

**Comment by PerPalmgren** [comment]
Hi Simon,
I do understand the dilemma and I think your last proposal is a very good compromise and “the best of two worlds”.
Great😜👍
Per

Per J. Palmgren | DC, FRCC, MMedEd, PhD |
University Lecturer |
Department for Learning, Informatics, Management and Ethics |
Karolinska Institutet | Tomtebodavägen 18A | 171 77 Stockholm |
Tel. + 46 8 524 85 294
________________________________

Karolinska Institutet – a medical university

**Comment by JaspBoy** [comment]
Can anyone help me distinguish something then - when would one use adjusted pearson residuals instead of pearson residuals?
