### ISSUE TITLE
[Bug]: rollApp Status is wrong

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#1848]
### JASP Version

Others

### What OS are you seeing the problem on?

rollApp

### Bug Description

![grafik](https://user-images.githubusercontent.com/4428185/194101062-3f18f1a6-4b98-45dd-ae9b-8eaf4e6a4c82.png)

As already mentioned in https://github.com/jasp-stats/jasp-issues/issues/1760 the "October 2021 update" is wrong.
JASP 0.14.3 on rollApp is still free and works. We are also not working on an alternative solution.
Nothing has changed. Please remove this misleading "October 2021 Update"

And if the "limitations" are of concern, then say it. 
The free starter tier is limiting, if you have Big Data or need to share your .jasp file, see:

> App capabilities will be limited
>     you will not be able to save your work
>     audio playback will not be available
>     minimal computing resources will be allocated

Note: You still can screenshot plots and copy paste text-annotations via rollapps clipboard-manager.

### Expected Behaviour

Advertise rollapp properly.
It is a good thing to have it for all the Tablet / ARM-users out there.

### Steps to Reproduce

1. 
2. 
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@DanaJohanna : Are you still active here on github and maintaining the web-page?

**Comment by DanaJohanna** [comment]
I just changed the contents of the website by deleting the 'October 2021 update'. I will close this issue now and issues regarding development of the app can be discussed in #1760. If there are any specifics regarding the rollapp (as it is) that should be mentioned on the website, please let me know.

**Comment by tomtomme** [comment]
small update on the rollApp situation.
They still ship outdated 0.14.3. 

However for the first time today I got this: 
![grafik](https://user-images.githubusercontent.com/4428185/233014526-b4337c2a-dbde-4894-a81e-b20f15009df9.png)

This means, that if server load is high, you cannot access JASP via rollApp for free. You would need to try later. I guess this is where the original confusion came from, where people thought that this message meant, that rollApp is now always for paying customers only. But this is clearly not the case, as this message does not pop up often and you can use JASP via rollApp just fine for free most of the time.
