### ISSUE TITLE
Normality assumptions checks in descriptive statistics

### ISSUE THREAD

**Issue by vicenteinefo** [jasp-stats/jasp-issues#185]
* Enhancement: To have the one sample normality assumption check and the equality of variance assumption check in descriptive statistics analysis independently of whatever test applied.
* Purpose: As a good teaching resource independently of the test applied.

**Comment by juliuspfadt** [comment]
I think this can be closed, given that normality checks are implemented, and the team (as it seems) has decided against including the variance equality in the descriptive module, since that can be found in other modules (e.g., t-test).
