### ISSUE TITLE
[Bug]: Using exponent notation cannot be enabled in result

### ISSUE THREAD

**Issue by shun2wang** [jasp-stats/jasp-issues#1852]
### JASP Version

0.16.4

### What analysis are you seeing the problem on?

All

### What OS are you seeing the problem on?

Windows 10 21H2

### Bug Description

numbers in result always displayed using the E-notation,even if `Use exponent notation` is checked.

![image](https://user-images.githubusercontent.com/10348402/194755061-0c2a3a71-33ef-4337-af3f-19f29dbdf4f5.png)

### Expected Behaviour

Using exponent notation when the option is checked.

### Steps to Reproduce

1. checked the use exponent notation option
2. open 'debug' data set
3. see pic

### Log (if any)

[JASP 2022-10-09 19_41_51 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/9741529/JASP.2022-10-09.19_41_51.Engine.1.log)
[JASP 2022-10-09 19_41_51 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/9741530/JASP.2022-10-09.19_41_51.Engine.0.log)
[JASP 2022-10-09 19_41_51 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/9741531/JASP.2022-10-09.19_41_51.Desktop.log)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by EJWagenmakers** [comment]
This is strange, because this was a known bug for 16.3, and 16.4 supposedly fixed it -- I checked earlier, and on 16.4 it does work as it should *on my computer*...

**Comment by shun2wang** [comment]
yeah EJ, I don't remember exactly have seen this problem too,I I'll give more info when joris and bruno come back

**Comment by shun2wang** [comment]
I can not reproduce it now on same PC...very strangely.
