### ISSUE TITLE
[Feature Request]: Implement GUI input for SEM instead of lavaan syntax, improve mediation analysis

### ISSUE THREAD

**Issue by Ghassan-Okour** [jasp-stats/jasp-issues#1854]
### Description

Merging types of SEM in one menu driven dialogue box  

### Purpose

to be more flexible for the needs of the researcher

### Use-case

building more powerful models

### Is your feature request related to a problem?

No; I loved JASP in the previous week; tried its menus and it is a powerful environment

**Comment by juliuspf** [comment]
Hi @Ghassan-Okour, thank you for the request and taking the time to become familiar with GitHub issues. Could you be a bit more specific with what you mean? What is is about the SEM module that you think could be improved?

**Comment by Ghassan-Okour** [comment]
Hi @juliuspf, 
why in [structural equation modeling] the user should write the [lavaan] code to run this analysis, while in [mimic model] and [mediation analysis] the researcher can select the variables without writing any code?
How can the researcher manipulate them MI in [Confirmatory factory analysis] without writing any code?
I think if the current dialogue box of [structural equation modeling] become like the dialogue boxes of [mimic model] and [mediation analysis] then running the [structural equation modeling] will be so easy for the researcher who have not the ability to write the necessary code for his model.
Best Regards....

**Comment by Ghassan-Okour** [comment]
Hi @juliuspf,
the current [Mediation Analysis] adopting recursive mediators; what if the researcher wants to make non-recursive mediators or manipulating the MI among the residuals of the mediators?
Best regards...

**Comment by juliuspf** [comment]
So these are some valid points, that I will try to summarize. The lavaan syntax is used because it is very powerful and flexible and some operations available through the lavaan syntax for SEM are hard to replace by click-and-response operations. I agree, that for non-R people this is not very intuitive. If you look at the Factor module, you can fit a CFA with dragging variables around. Also, what do you mean by "MI"? I will rename the issue so there is less ambiguity.

**Comment by Ghassan-Okour** [comment]
> So these are some valid points, that I will try to summarize. The lavaan syntax is used because it is very powerful and flexible and some operations available through the lavaan syntax for SEM are hard to replace by click-and-response operations. I agree, that for non-R people this is not very intuitive. If you look at the Factor module, you can fit a CFA with dragging variables around. Also, what do you mean by "MI"? I will rename the issue so there is less ambiguity.

**Comment by Ghassan-Okour** [comment]
![Screenshot 2022-10-11 132607](https://user-images.githubusercontent.com/115344297/195066517-4f5e08eb-98d3-4f44-9469-9f6bc1fe1b15.jpg)
