### ISSUE TITLE
Suggesting to include [careless r package] as a module in next JASP version; as a data screening module that using several methods to detect careless responses of insufficient effort responding

### ISSUE THREAD

**Issue by Ghassan-Okour** [jasp-stats/jasp-issues#1855]
Suggesting to include [careless r package] as a module in next JASP version; as a data screening module that using several methods to detect careless responses of insufficient effort responding

_Originally posted by @Ghassan-Okour in https://github.com/jasp-stats/jasp-issues/issues/1759#issuecomment-1272269154_

**Comment by juliuspf** [comment]
I am closing this as it is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/1853
