### ISSUE TITLE
[Feature Request]: The standardized estimates are the same of the unstandardized estimates using CFA factor Analysis

### ISSUE THREAD

**Issue by Ghassan-Okour** [jasp-stats/jasp-issues#1856]
### Description

The standardized estimates are the same of the unstandardized estimates using CFA factor Analysis

### Purpose

to correct this bug for one of both

### Is your feature request related to a problem?

Yes

### Describe the solution you would like

correcting the unstandardized estimates or the standardized estimates

**Comment by juliuspf** [comment]
Thanks for taking the time. This is not a bug, but normal behaviour. When the "Factor scaling" in the "Model options" is set to "Factor variances", which is the default, the latents are automatically standardized, meaning the unstandardized estimates and the latent standardized estimates will be equal.

**Comment by Ghassan-Okour** [comment]
> Thanks for taking the time. This is not a bug, but normal behaviour. When the "Factor scaling" in the "Model options" is set to "Factor variances", which is the default, the latents are automatically standardized, meaning the unstandardized estimates and the latent standardized estimates will be equal.

Thankful gracefully....
