### ISSUE TITLE
[Feature Request]: Add a CITATION.cff file to your repo

### ISSUE THREAD

**Issue by tpronk** [jasp-stats/jasp-issues#1857]
### Description

CITATION.cff files are plain text files with human- and machine-readable citation information for software (and datasets). Code developers can include them in their repositories to let others know how to correctly cite their software. https://citation-file-format.github.io/

### Purpose

You'll get a "cite this repo" link in the right panel of the GitHub website. For instance, see this repo: https://github.com/tpronk/splithalfr

### Use-case

People wanting to cite the repo

### Is your feature request related to a problem?

No problem

### Describe the solution you would like

Add a CITATION.cff file

**Comment by juliuspf** [comment]
@tpronk thank you for the request. Just to be clear, this should be for people wanting to cite JASP?

**Comment by tpronk** [comment]
Hey @juliuspf and @vandenman! Yes it is. And for now it's mainly interesting to techy types like me :), but it's getting more popular, as attested to by the fact that GitHub can parse these files to create one of those citation links.
