### ISSUE TITLE
[Feature Request]: SE for correlations

### ISSUE THREAD

**Issue by Trebicky** [jasp-stats/jasp-issues#1858]
### Description

Effect size standard errors for correlations

### Purpose

Though CIs are great, frequently we need to report SE (e.g., for meta-analyses) for correlation coeficients. It is great JASP implement SE as an option in the new release, but it is missing in correlations.

### Use-case

Reporting SE for correlation, imputing effects in to meta analysis

### Is your feature request related to a problem?

JAPS's native meta-analysis module is asking for SE

### Describe the solution you would like

A check box to choose CI or SE or both.

### Describe alternatives that you have considered

Add option into meta-analysis module to choose what measure of error  (or even simpler - sample size, which is usually reported)

### Additional context

This is especially needed when JAPS's native meta-analysis module is asking for SE and JASP itself does not provide it...

**Comment by Kucharssim** [comment]
Dear @Trebicky,

thank you for the request! In fact, we just implemented this feature for correlations as well, it will be available in the next release.
