### ISSUE TITLE
Correlation normality assumptions checks available

### ISSUE THREAD

**Issue by vicenteinefo** [jasp-stats/jasp-issues#186]
* Enhancement: It would be useful to have the correlation normality assumptions checks available when this statistical index being calculated.
* Purpose: In order to do the whole analysis from the same menu and could select the appropriatte correlation index (parametric or non-parametric) for the analysis of the data

**Comment by Kucharssim** [comment]
This has been added https://github.com/jasp-stats/jasp-desktop/pull/3622

(Also a related issue https://github.com/jasp-stats/jasp-issues/issues/488)
