### ISSUE TITLE
[Bug]: Error: package ‘ROCR’ was installed before R 4.0.0: please re-install it

### ISSUE THREAD

**Issue by tpronk** [jasp-stats/jasp-issues#1860]
### JASP Version

0.16.4

### JASP Module

jaspMachineLearning

### What analysis are you seeing the problem on?

Classification via K-nearest neighbor

### What OS are you seeing the problem on?

Windows 10

### Bug Description

During the "Machine Learning with JASP" workshop at Data Science Day, I opened the petal dataset to run a K-nearest neighbor classification on. As I entered variables into the GUI, I saw a red box with an error message saying: Error: package ‘ROCR’ was installed before R 4.0.0: please re-install it.

Note that none of the other workshop participants had this problem. It might be that I had this problem because I've got a lot of stuff installed on my PC, like Conda etc.

I managed to solve this error (and get the K-nearest neighbor to work) by opening JASP as administrator, then start the R (Beta) module, and run the R statement below.
`install.packages("ROCR", repos = "https://cloud.r-project.org")`

### Expected Behaviour

The K-nearest neighbor should show tables etc.

### Steps to Reproduce

Fixed it on my end. See description for how (perhaps) to reproduce this issue. Sorry for not offering more information; I prioritized getting JASP to work again for the workshop.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by koenderks** [comment]
This bug seems to be gone in the current release! @tpronk Please reopen if you still encounter this issue.
