### ISSUE TITLE
[Bug]: Axis values are not correct in scatter plot with densities

### ISSUE THREAD

**Issue by rebekkasl** [jasp-stats/jasp-issues#1861]
### JASP Version

0.16.4

### JASP Module

jaspRegression

### What analysis are you seeing the problem on?

Scatter plot with densities

### What OS are you seeing the problem on?

Windows 10

### Bug Description

The scatter plots with densities created using Descriptives>Customizable plots and Regression>Correlation (Display pairwise, Scatter plots) do not match. Specifically, for the scatter plot created in Regression>Correlation, the axis values in the distribution plot do not match the axis values in the scatterplot (for one of the variables). When I click "Display pairwise", only the axis values for the distribution plots appear, so I assumed that they match those of the scatter plot, or at least have the same min and max values if the number of ticks deviated. However, for AQ, you can see in the distribution plot that there are no values below 1.5 (also checked the data here, min=1.53). Without the tick values in the scatter plot, you cannot tell that the y-axis in the scatter plot has a minimum of 1.5, which does not correspond to the minimum y-axis value in the distribution plot (which is 1.0). I have marked the area in red in the image below.
![for jasp](https://user-images.githubusercontent.com/86594877/195557305-a10bfa64-e5d0-4ddc-8ffa-4a1982949f8a.png)

### Expected Behaviour

The scatter plot with densities creates in Regression>Correlation should match the scatter plot with densities created in Descriptives>Customizable plots. That is, the values of the axis pairs (the two y-axes and the two x-axes) should correspond. 

### Steps to Reproduce

1. Open "data for JASP.csv"
2. Regression>Correlation
3. Add the two variables
4. Click on "Display pairwise"
5. Click on "Scatter plots", and then "Densities for variables"
6. Compare to the same plot created using Descriptives>Customizable plots>Scatter plots
...
[data for JASP.csv](https://github.com/jasp-stats/jasp-issues/files/9775129/data.for.JASP.csv)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by Kucharssim** [comment]
Dear @rebekkasl,

thank you for the report, I will take a look

**Comment by tomtomme** [comment]
The error may be with the histogram. I saw something similar once, where the axis numbers at the beginning did not quite fit to the very small dataset. However this was some time ago and I never reported it

**Comment by tomtomme** [comment]
I re-tested with jasp 0.18.3. The error persists. The left plot should definitely have histograms that line up with the scatterplot. The histograms are to high and to much to the right.
The scatterplot and its histograms on the very right does it correctly.

**Comment by tomtomme** [comment]
This is now discussed here: https://github.com/jasp-stats/jasp-issues/issues/1627
And in developement here: https://github.com/jasp-stats/jaspGraphs/pull/72

Closing as duplicate
