### ISSUE TITLE
JASP crashed when Start

### ISSUE THREAD

**Issue by shun2wang** [jasp-stats/jasp-issues#1868]
* JASP version: 0.16.4
* OS name and version: Windows 10 Version 2009

* Analysis: 
* Bug description: JASP engine crashed when start.
* Expected behaviour:

#### Steps to reproduce:
1. Start JASP

[JASP 2022-10-21 20_31_51 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/9839005/JASP.2022-10-21.20_31_51.Engine.0.log)
[JASP 2022-10-21 20_31_51 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/9839006/JASP.2022-10-21.20_31_51.Desktop.log)

-----------------------------------------------------------------------

### Debug information:
**Engine # 0** process *crashed* and it's state is *initializing*.

[Commit used](https://github.com/jasp-stats/jasp-desktop/commit/35bc382125b0a2a484375f146b679219552fbfec)

**Comment by JorisGoosen** [comment]
Does it keep crashing or was this only once?

**Comment by shun2wang** [comment]
Unfortunately (or should say fortunately😜 ? )this only happened only once. I have tried to reproduce without success, but I suspect it may be related to https://github.com/jasp-stats/jasp-issues/issues/1880, because I saw this popup.

**Comment by tomtomme** [comment]
@shun2wang 
since this is a duplicate, we can close it, right?
