### ISSUE TITLE
[Feature Request]: Partial correlation networks/Gaussian graphical model

### ISSUE THREAD

**Issue by TarandeepKang** [jasp-stats/jasp-issues#1872]
### Description

Partial correlation networks/Gaussian graphical model

### Purpose

Examining relationships between variables and a predictor, when all others are controlled for

### Use-case

Situations in which there are a large number of pairs requiring other variables to be controlled for

### Is your feature request related to a problem?

Existing correlation options are not suitable when there are multiple pairs each requiring all other variables to controlled for

### Describe the solution you would like

The ability to build a partial correlation network in JASP

### Describe alternatives that you have considered

Simple partial correlation analysis but this is inappropriate for analyses involving multiple pairs=

### Additional context

I myself am new to this method, but the following papers may be useful:=
Giraud, C., Huet, S., & Verzelen, N. (2012). Graph Selection with GGMselect. Statistical Applications in Genetics and Molecular Biology, 11(3). https://doi.org/10.1515/1544-6115.1625

Epskamp, S., & Fried, E. I. (2018). A tutorial on regularized partial correlation networks. Psychological Methods, 23(4), 617–634. https://doi.org/10.1037/met0000167

**Comment by juliuspf** [comment]
@TarandeepKang, thanks for the request. Any idea how feasible this is @vandenman?

**Comment by vandenman** [comment]
While we used to support partial correlation networks, we removed these because the R package [parcor was removed from cran](https://cran.r-project.org/web/packages/parcor/index.html). However, the default estimator `EBICglasso` estimates a Lasso regularized partial correlation network. Do you necessarily need unregularized partial correlation networks?

**Comment by TarandeepKang** [comment]
Sorry, I had been looking the correlation/regression module and not the network module. In the best possible way, the software has more features than I can keep up with! It does however look like partial correlation is still supported as an estimator within the network module? As of 0.16.4.

**Comment by vandenman** [comment]
@TarandeepKang Ah yes, you're right I'm confusing two options. `adalasso` (a method for adaptive lasso) was removed a while ago, not the partial correlation networks.

**Comment by TarandeepKang** [comment]
Thank you for your help, Don and Julius. Since this was a nonissue, I'll close it now.
