### ISSUE TITLE
[Feature Request]: SNR instead of "Statistic"

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#1873]
### Description

The column called "Statistic" is meaningless because everything in JASP is a statistic

### Purpose

be more descriptive / comprehensible

### Use-case

teaching

### Is your feature request related to a problem?

teaching

### Describe the solution you would like

Please change this to something more understandable like Signal-to-Noise-Ratio (SNR).

### Describe alternatives that you have considered

-

### Additional context
<img width="325" alt="grafik" src="https://user-images.githubusercontent.com/4428185/198599381-0f528527-e2f1-48db-adb2-fbc670874dec.png">

Above we see the column "Statistic". Please change this to something more understandable like Signal-to-Noise-Ratio (SNR).
This is also true for other t-Tests or ANOVAS

**Comment by juliuspf** [comment]
@tomtomme, thanks for the request. Let's have Don look at it.

**Comment by vandenman** [comment]
"Statistic" is short for "Test statistic" (see https://en.wikipedia.org/wiki/Test_statistic). This column combines a t-value and a Z-value. The union of these we call a statistic. Sometimes these are referred to as t-statistic and z-statistic rather than t-value or z-value (see https://en.wikipedia.org/wiki/T-statistic).

Note that this is also mentioned in the helpfile:
![image](https://user-images.githubusercontent.com/21319932/199212194-eb3c21ae-2e3d-4fa7-b5b1-5da340fb238d.png)

Would you prefer "Test statistic" instead of "Statistic"?

**Comment by tomtomme** [comment]
Yes, absolutely.
Because a mean is also called a "statistic". Or is this a difference between german and english? We germans at least would call a mean a statistic.
Help-File: Good to know its there. But I would prefer to see this in the GUI, to avoid confusion while teaching, where we usually do not look into help files - maybe I should change that...

**Comment by AlexanderLyNL** [comment]
The signal-to-noise ratio has a particular meaning in probability, theoretical statistic and signal processing, which is why in my opinion wouldn't work here.

**Comment by tomtomme** [comment]
Interestin. 
"Theoretical statistic" you say. What is a t F z Chi² value to you? For me it is a "theoretical statistic" applied onto a sample and they are directly connected to another theoretical statistic called p-value, that only exists (or has a meaning) in theory, if you repeat the experiment many many times in the same way.

Another consideration:
The term is more widely used on google scholar outside of the field of "signal processing" than within the field of "signal processing"

- statistics "signal-to-noise-ratio" -"signal processing" 1,1 billion hits
- "signal-to-noise-ratio" "signal processing" 1 hit (sic!)
-  "signal to noise ratio" statistics 1.6 billion hits

So you might see, "it would not work here" is not a very good argument to me, if you can not more precisely explain why. Because my point still stands: I read the term often and it is widely used as a union for t z F Chi² etc.
That might not be the case within the field of psychology however. My background is climatology / geography. So this might explain why we - at the end - may agree to disagree.

**Comment by juliuspf** [comment]
@tomtomme your enthusiasm is definitely not going unnoticed ;) I think your last point is spot on. I went through the whole psychology bachelor and master cycle, and taught the practical statistics course. And we have always just called this the statistic or test statistics of the t-test. This might be my forgetfulness, but we never learned the term SNR as the interpretation. That is not to say, this is one of the interpretations, but given that this program mainly addresses psychologists, I would also vote for leaving it as is. I would keep this issue open for others to see who might be more supportive of your interpretation :)

**Comment by tomtomme** [comment]
Fine with me :D
Sometimes I forget that I am an outsider with unconventional views more common in environmental sciences. Feel free to close this, too.

**Comment by juliuspf** [comment]
Having diverging views of non-psychologists is a good thing. And these discussions keep us at our toes and reevaluate our past choices. And it all comes from a good place: trying to make the program more appealing to users :)
