### ISSUE TITLE
[Feature Request]: See names when create graphs

### ISSUE THREAD

**Issue by celzbz** [jasp-stats/jasp-issues#1877]
### Description

Can't see names at the bottom of graphs

### Purpose

Need to see names at the bottom of graphs

### Use-case

can't see name

### Is your feature request related to a problem?

Yes, I can't see the names when I create graph and need to answer questions that are based on the graph.  

### Describe the solution you would like

When you scroll over the graph/bars you would be able to see the names come up/put the names vertically?

### Describe alternatives that you have considered

putting the names vertically

### Additional context

I can't see the names on graphs I create.

**Comment by juliuspf** [comment]
Hi @celzbz, could you tell us a bit more about what you require? What analysis is this related to? Maybe you could bring more clarity with uploading a screenshot?
