### ISSUE TITLE
[Bug]: JASP does not start in Mint 22

### ISSUE THREAD

**Issue by wato-uy** [jasp-stats/jasp-issues#1879]
### JASP Version

0.16.4

### What OS are you seeing the problem on?

Linux Mint 22

### Bug Description

Hi!
I've been using JASP for a while without any problems but today I went to use it and it didn't start. I rebooted the laptop, nothing. I uninstalled and installed the latest version following the instructions on the website and it didn't start either. I did the latter twice, updating flatpak, fixing flatpak errors, everything. I reinstalled JASP and it still won't start. No error message or anything, simply not with the application menu button or from the console, nothing.
Please help!

### Expected Behaviour

Start the software

### Steps to Reproduce

1. 
2. 
3. 
...
There is no bug, JASP just does not start

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment]
HI @wato-uy thanks for reporting this, maybe @vandenman has an idea?

**Comment by wato-uy** [comment]
Hi,
I kept looking and was able to get JASP to start. Reading the error message
when trying to start it from the terminal, I saw that it had something to
do with the keyboard layout (something that had never happened to me before
because I always used the same layout: Latin American Spanish). The truth
is that when I switched to the default layout (Spanish) JASP started...
quack... Don't ask me what this means. I'll have to change the keyboard
layout every time I need to use JASP :-/ but well, it works.
I paste below the error.
Thanks a lot for the reply anyway.

> flatpak run org.jaspstats.JASP
Desktop: QML cache directory:
/home/wato/.var/app/org.jaspstats.JASP/cache/JASP/JASP/qmlcache_62ac36111c6918e61763dbb4613c748ad82de8cb
Making new argument list for Application startup: JASP
Starting JASP 0.16.4 from commit 62ac36111c6918e61763dbb4613c748ad82de8cb
and branch HEAD
QtWebEngineQuick initialized
Gtk-Message: 15:37:07.220: Failed to load module "xapp-gtk3-module"
Qt: Session management error: None of the authentication protocols
specified are supported
Application initialized
qt.webenginecontext:

GLImplementation: desktop
Surface Type: OpenGL
Surface Profile: CompatibilityProfile
Surface Version: 4.6
Using Default SG Backend: yes
Using Software Dynamic GL: no
Using Angle: no

Init Parameters:
  *  application-name JASP
  *  browser-subprocess-path /app/bin/QtWebEngineProcess
  *  create-default-gl-context
  *  disable-features
DnsOverHttpsUpgrade,ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture

  *  disable-setuid-sandbox
  *  disable-speech-api
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess
  *  enable-threaded-compositing
  *  in-process-gpu
  *  use-gl desktop

xkbcommon: ERROR: Couldn't process include statement for 'latam(mac_intl)'
xkbcommon: ERROR: Abandoning symbols file "(unnamed)"
xkbcommon: ERROR: Failed to compile xkb_symbols
xkbcommon: ERROR: Failed to compile keymap
[3:19:1031/153707.500471:FATAL:xkb_keyboard_layout_engine.cc(640)] Keymap
file failed to load: latam-mac_intl
/app/bin/org.jaspstats.JASP: línea 5:     3 `trap' para punto de
parada/seguimiento               (`core' generado) JASP $1

Regards!
...................
W Bell

**Comment by vandenman** [comment]
No real idea what could cause this.

@JorisGoosen perhaps flatpak is missing some dependencies?

**Comment by leadzeppelin13** [comment]
I have the same issue but on Manjaro-KDE. I installed the JASP flatpak which did run before a few months ago. Yesterday I tried starting JASP after a long time and it doesn't run. Here is what I have on the terminal:

flatpak run org.jaspstats.JASP
Desktop:        QML cache directory: /home/pritam/.var/app/org.jaspstats.JASP/cache/JASP/JASP/qmlcache_62ac36111c6918e61763dbb4613c748ad82de8cb
Making new argument list for Application startup: JASP
Starting JASP 0.16.4 from commit 62ac36111c6918e61763dbb4613c748ad82de8cb and branch HEAD
QtWebEngineQuick initialized
Application initialized
qt.webenginecontext: 

GLImplementation: desktop
Surface Type: OpenGL
Surface Profile: CompatibilityProfile
Surface Version: 4.6
Using Default SG Backend: yes
Using Software Dynamic GL: no
Using Angle: no

Init Parameters:
  *  application-name JASP 
  *  browser-subprocess-path /app/bin/QtWebEngineProcess 
  *  create-default-gl-context  
  *  disable-features DnsOverHttpsUpgrade,ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
  *  disable-setuid-sandbox  
  *  disable-speech-api  
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess 
  *  enable-threaded-compositing  
  *  in-process-gpu  
  *  use-gl desktop 

xkbcommon: ERROR: Couldn't process include statement for 'us(phonetic)'
xkbcommon: ERROR: Abandoning symbols file "(unnamed)"
xkbcommon: ERROR: Failed to compile xkb_symbols
xkbcommon: ERROR: Failed to compile keymap
[3:33:1101/150305.257252:FATAL:xkb_keyboard_layout_engine.cc(640)] Keymap file failed to load: us-phonetic
/app/bin/org.jaspstats.JASP: line 5:     3 Trace/breakpoint trap   (core dumped) JASP $1

**Comment by JorisGoosen** [comment]
@wato-uy do you use X11 or wayland?

Or if you don't know what those mean, what is your desktop environment?

**Comment by wato-uy** [comment]
Hi Joris.

I use Linux Mint 22 with Cinnamon desktop.

**Comment by JorisGoosen** [comment]
Ah yes thanks @wato-uy and @leadzeppelin13 it seems that the keyboard mapping you both chose somehow cause a problem for flatpak...

`latam(mac_intl)` and `us(phonetic)`

So it seems that xcb configuration is a bit flaky (as is suggested by the comments in the link by @leadzeppelin13 above) and you might give a try to changing the configuration as described there. Perhaps it can be solved by changing the config as described there?

**Comment by wato-uy** [comment]
Thanks Joris.
As I mentioned above, I had already found a way to get JASP to start, and that was by changing the keyboard layout (in my case, from Latin American Spanish to Spanish). By doing that JASP does start. Who knows what's going on, but it works.

**Comment by JorisGoosen** [comment]
Yeah very good that you found it because this is one of those annoying problems where strange settings+flatpak clash.
There are also sometimes problems if one of the locale environment vars is set strangely (`LC_*`) where we can't really do anything about it on our end...

Because JASP can't force a different keymap for everyone to avoid this problem...

**Comment by tomtomme** [comment]
@JorisGoosen 
I guess we can close this one then, since this is a flatpak issue, right? Or do you still want to try and fix it?
fwiw I have never experienced it with german locale. 

Also 
@AnonymousBystander 
@wato-uy 
does the problem persist with jasp 0.18.3?
always switching locale is not a real solution, is it?
