### ISSUE TITLE
[Bug]: Can't save trained model in random forest classification

### ISSUE THREAD

**Issue by ajrobi12** [jasp-stats/jasp-issues#1881]
### JASP Version

0.16.3

### JASP Module

jaspMachineLearning

### What analysis are you seeing the problem on?

Random Forest Classifications

### What OS are you seeing the problem on?

Windows 10

### Bug Description

![image (25)](https://user-images.githubusercontent.com/116920778/199067419-86aa8c8c-61e2-4de0-a739-7502d0feb4df.png)

I'm trying to save my trained model from a random forest classification analysis so that I can apply it to a new dataset. When I click "Save trained model", though, I receive this error. I'm not sure what exactly the issue is with the three columns noted in the error message, but would love to resolve so I can complete my model. 

File is too large to attach, so I will email it to [issues@jasp-stats.org].

### Expected Behaviour

Was expecting the trained model to be saved to my desktop so that I could pull it for a prediction analysis.

### Steps to Reproduce

1. Open a random forest classification
2. Use these targets and features ![image (26)](https://user-images.githubusercontent.com/116920778/199068297-13498768-fb3c-4d1a-b709-de3c17fee3bf.png)
3. Try to save trained model
![image (27)](https://user-images.githubusercontent.com/116920778/199068481-353b0c33-b5b5-4746-ba4a-76f772f14263.png)
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment]
Hi @ajrobi12, thanks for reporting this. I will ask one of the maintainers to have a look. Just to clarify, the issue persists with version 0.16.4?

**Comment by ajrobi12** [comment]
Hi @juliuspf - that's correct, the issue does still persist with 0.16.4. thanks for looking into it!

**Comment by AndoStat** [comment]
Just report that JASP 16.4 has the same issue on My Win 10 22H2 Enterprise x64 so Forecast function gone "fishing".

**Comment by tomtomme** [comment]
@ajrobi12 
@AndoStat 
I tested this with jasp 0.18.3 and it worked fine.
Feel free to reopen if not fixed on your side.
