### ISSUE TITLE
[Feature Request]: Bayesian Credible Intervals given a specific prior

### ISSUE THREAD

**Issue by Masharipov** [jasp-stats/jasp-issues#1882]
### Description

For the Descriptives the JASP use a uniform prior. It would be great to get a table of credible intervals given a specific prior in the future JASP release.

### Purpose

1) To see how the posterior probability distribution changes depending on the prior.
2) To perform Bayesian parameter inference. In the JASP, Bayesian inference is perfomed using Bayes Factors. 
An alternative way of Bayesian inference can be to consider the posterior probability distribution (aka Bayesian paramerer inference).
2.1) For example, one can check whether the credible interval (e.g. specified as 95% Highest density interval) falls within or outside the region of practical equivalence (ROPE). This procedure refers to the "HDI+ROPE" decision rule described in Kruschke (2018).
2.2) Or one can calculate the posterior probability of finding the effect (a) inside the ROPE, (b) to the left of the ROPE and (c) to the right of the ROPE. This procedure refers to the "ROPE-only" decision rule described in Kruschke (2018, see supplementary).

### Use-case

All Bayesian t-tests

### Is your feature request related to a problem?

For the Descriptives the JASP use only uniform prior.

### Describe the solution you would like

Add table of credible intervals given a specific prior.

### Additional context

Kruschke, J. K. (2018). Rejecting or Accepting Parameter Values in Bayesian Estimation. Advances in Methods and Practices in Psychological Science, 1(2), 270–280. https://doi.org/10.1177/2515245918771304

P.S. Sorry for creating multiple features requests (it was reccomended to create a single request per issue in JASP forum).

**Comment by tomtomme** [comment]
@Masharipov 
I have added details of your request to the duplicate #785

Please reopen if you disagree.
