### ISSUE TITLE
[Bug]: Error in UseMethod('.applyEnDeCoder', x): no applicable method for '.applyEnDeCoder' applied to an object of class 'character'  Stack trace

### ISSUE THREAD

**Issue by NinaBotanical** [jasp-stats/jasp-issues#1886]
### JASP Version

0.16.4

### JASP Module

jaspTTests

### What OS are you seeing the problem on?

windows 10

### Bug Description

![JASP](https://user-images.githubusercontent.com/117329869/199640692-ce4b77f8-62c0-4e80-819f-332d4cdf5828.jpg)

[avengers.csv](https://github.com/jasp-stats/jasp-issues/files/9925443/avengers.csv)

Any value I attempt to place in the dependent variable field, generates this error

### Expected Behaviour

This is my first time using it, but my understanding is that it should have generated a scatter plot

### Steps to Reproduce

1. click on numerical variable
2. click arrow to send to dependent variable box
3. error
4. 
5. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by Kucharssim** [comment]
Dear @NinaBotanical ,

thank you for the report. It is indeed a bug, and was already reported here: https://github.com/jasp-stats/jasp-issues/issues/1849. Please follow that issue to check new developments.
