### ISSUE TITLE
[Bug]: Visual Modeling-Linear modeling failed

### ISSUE THREAD

**Issue by bartle34** [jasp-stats/jasp-issues#1889]
### JASP Version

0.16.4

### JASP Module

Visual Modeling

### What OS are you seeing the problem on?

Windows 10

### Bug Description

When trying to perform visual modeling.
![14C91466-AC54-4579-A677-1E537B3A5B71](https://user-images.githubusercontent.com/117683794/200407028-72ce73a1-8398-4b3f-b63a-fc977627698b.jpeg)

### Expected Behaviour

Visual modeling a first time in performing my t test.

### Steps to Reproduce

1. In put the data set
2. Go to visual modeling linear modeling

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by shun2wang** [comment]
@bartle34 thank you for the report. It was already reported here: https://github.com/jasp-stats/jasp-issues/issues/1849 and fixed in Next release. following pined issue to learn more about progress.
