### ISSUE TITLE
JASP crashes when attempting to open .sav file made with R

### ISSUE THREAD

**Issue by hsorlie** [jasp-stats/jasp-issues#189]
I have a large dataset (tibble) that I work on in R. I subset a smaller version of this (still a tibble) and write a .sav file using the write_sav() function in the Haven package. This .sav opens just fine in SPSS, but if I try to open it with JASP it instantly crashes. This happens both if I right-click the file and choose open with JASP, and if browse to and open it from within JASP. Attaching a sample .sav file that triggers this behaviour, at least on my JASP.
[sample.sav.zip](https://github.com/jasp-stats/jasp-desktop/files/2443765/sample.sav.zip)

* JASP version: 0.9.0.1
* OS name and version: macOS 10.14

**Comment by FransMeerhoff** [comment]
Hi @hsorlie 

This problem can not be reproduced in latest JASP version 0.9.2.
Please reopen if the problem still exists

Kind regards
Frans Meerhoff
