### ISSUE TITLE
[Bug]: Distributions -> Logistic -> red rectangle around tab 

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-issues#1890]
### JASP Version

0.16.4

### JASP Module

Distributions

### What analysis are you seeing the problem on?

Logistic

### What OS are you seeing the problem on?

Windows 11

### Bug Description

![image](https://user-images.githubusercontent.com/8603015/200442095-8bdb7d60-ec55-43e7-a124-aab0d51be3c7.png)

### Expected Behaviour

No red rectangle should appear

### Steps to Reproduce

open logistic under distributions

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by shun2wang** [comment]
I think it may related to https://github.com/jasp-stats/INTERNAL-jasp/issues/2135 and fixed in https://github.com/jasp-stats/jaspDistributions/pull/79

**Comment by boutinb** [comment]
Yes this is already solved. You can test it in the last nightly
