### ISSUE TITLE
[Bug]: This analysis terminated unexpectedly.

### ISSUE THREAD

**Issue by lg123cat** [jasp-stats/jasp-issues#1892]
### JASP Version

0.16.4

### JASP Module

Visual Modeling

### What analysis are you seeing the problem on?

Linear Modeling 

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

![Image 11-7-22 at 9 58 PM](https://user-images.githubusercontent.com/117701320/200464550-2573901b-b72a-4cd2-b438-329a405a7183.jpg)

### Expected Behaviour

I should have seen a linear model 

### Steps to Reproduce

Im not really sure 

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by shun2wang** [comment]
@lg123cat thank you for the report. It was already reported here: https://github.com/jasp-stats/jasp-issues/issues/1849 and fixed in Next release.
