### ISSUE TITLE
[Bug]: This analysis terminated unexpectedly.

### ISSUE THREAD

**Issue by BX305** [jasp-stats/jasp-issues#1893]
### JASP Version

0.16.4

### JASP Module

Quality Control

### What analysis are you seeing the problem on?

Design analysis

### What OS are you seeing the problem on?

Windows 10

### Bug Description

This analysis terminated unexpectedly.
<html>
<body>
<div id="id-0" class="jasp-analysis" style="color: silver; font-family: Arial, sans-serif, freesans, &quot;Segoe UI&quot;; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; opacity: 1; height: 396px;"><div class="jasp-display-item jasp-collection jasp-view" style="margin-top: 0.1em; margin-bottom: 0.6em; padding-left: 0.6em; margin-right: 0.6em; padding-right: 0.6em; background-color: rgba(224, 224, 224, 0); border: 1px solid rgba(105, 105, 105, 0); border-radius: 6px;"><div class="jasp-toolbar h3-toolbar" style="display: block;"><h3 class="in-toolbar toolbar-clickable" style="font-size: 15px; margin-top: 0.5em; margin-bottom: 0.5em; cursor: pointer; min-width: 1em; display: inline-block; vertical-align: middle;"><br class="Apple-interchange-newline">Design</h3><div class="toolbar-button toolbar-clickable jasp-menu jasp-hide" style="display: inline-block; visibility: hidden; width: 16px; height: 16px; margin-left: 4px; cursor: pointer; background: url(&quot;images/lightTheme/menu-indicator.svg&quot;) center center / 70% no-repeat; vertical-align: middle; font-size: 15px; margin-top: 0.5em; margin-bottom: 0.5em;"></div></div><div class="object-body"><div class="jasp-display-item jasp-collection-table jasp-table jasp-view jasp-indent jasp-collection-item jasp-collection-table jasp-collapsible jasp-display-item-flat" style="margin-top: 0.1em; margin-bottom: 0.6em; padding-left: 0px; margin-right: 0.6em; padding-right: 0.6em; background-color: rgba(224, 224, 224, 0); border: 1px solid rgba(105, 105, 105, 0); border-radius: 6px;"><div class="object-body"><div class="jasp-table-primitive jasp-display-primitive" style="padding-left: 0.6em;">

Selected Design
--

Factorial |   | 3 |   | 4 |   | III |   | 0 |   | 1 |   | 1 |   | 0 |   |  
 

</div></div></div></div></div></div><div class="fatalError analysis-error-message error-message-box ui-state-error" style="border: 3px double rgb(205, 10, 10); background: url(&quot;images/ui-bg_glass_95_fef1ec_1x400.png&quot;) 50% 50% repeat-x rgb(254, 241, 236); color: rgb(205, 10, 10); min-width: 300px; max-width: 1000px; position: absolute; top: 60px; left: 50px; margin-right: 50px; z-index: 100; padding: 1em; border-radius: 0.4em; white-space: normal; font-family: Arial, sans-serif, freesans, &quot;Segoe UI&quot;; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="ui-icon ui-icon-alert" style="display: block; text-indent: -99999px; overflow: hidden; background-repeat: no-repeat; width: 16px; height: 16px; background-position: 0px -144px; background-image: url(&quot;images/ui-icons_cd0a0a_256x240.png&quot;); float: left; margin-right: 0.3em;"></span>This analysis terminated unexpectedly.<br><br>Error in loadNamespace(x): there is no package called 'car'<br><br><div class="stack-trace-selector"><span style="cursor: pointer; display: inline-block; vertical-align: middle;">Stack trace</span><div class="stack-trace-arrow" style="width: 16px; height: 16px; margin-left: 2px; background: url(&quot;images/lightTheme/expand.png&quot;) center center / 70% no-repeat; cursor: pointer; display: inline-block; vertical-align: middle;"></div></div><div class="stack-trace" style="display: block;">doTryCatch(return(expr), name, parentenv, handler)<br><br>withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)<br><br>analysis(jaspResults = jaspResults, dataset = dataset, options = options)<br><br>doeFactorial(...)<br><br>.factorialRegressionANOVAcreateTable(options, ready, fit, saturated, model)<br><br>.factorialRegressionANOVAfillTable(factorialRegressionANOVA, factorialRegressionSummaryFit, options, fit, saturated, model)<br><br>loadNamespace(x)<br><br>withRestarts(stop(cond), retry_loadNamespace = function() NULL)<br><br>withOneRestart(expr, restarts[[1]])<br><br>doWithOneRestart(return(expr), restart)</div><br>To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports</div>
</body>
</html>

### Expected Behaviour

Run the analysis

### Steps to Reproduce

1.Two level factorial [design](url)
2.
3.
...
![image](https://user-images.githubusercontent.com/117710655/200488889-4c114de6-bbb9-4d4e-8596-3f379d8cc48e.png)

![image](https://user-images.githubusercontent.com/117710655/200488987-f10b10d3-d5e7-4916-9908-31e67992172d.png)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JTPetter** [comment]
This is fixed in the latest JASP version, the analysis functionality is now under Quality Control -> DOE -> Analyze Design.
