### ISSUE TITLE
[Bug]: "The engine crashed while trying to run this analysis" Windows 10

### ISSUE THREAD

**Issue by dbeman-student** [jasp-stats/jasp-issues#1898]
### JASP Version

0.16.4

### JASP Module

ANOVA, Descriptives, Factor, Frequencies, Mixed Models, Regression, T-Tests

### What analysis are you seeing the problem on?

All of them

### What OS are you seeing the problem on?

Windows 10

### Bug Description

Getting error message "The engine crashed while trying to run this analysis.." no matter what module I attempt to run. I can't load any other modules either.  I am getting the error message, "Loading packages for Module XXXX failed". 

### Expected Behaviour

This is my first time using this tool, so I expect that the module would provide statistics and charts from the chosen module. As I have never seen this operate correctly yet, I don't have screenshots nor am I certain of what is considered "normal operation" for this tool.

### Steps to Reproduce

1. After opening the application, I open a recent .csv file (comma-delimited) with tables and statistics.
2. If I choose any of the above preset modules, I am met with this error.
3. Using the + Sign at the top to use a different module gives me the "Module XXXXX failed" message.
...

### Log (if any)

[JASP 2022-11-06 14_39_53 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/9975182/JASP.2022-11-06.14_39_53.Desktop.log)
[JASP 2022-11-06 14_39_53 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/9975183/JASP.2022-11-06.14_39_53.Engine.0.log)
[JASP 2022-11-09 16_02_41 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/9975184/JASP.2022-11-09.16_02_41.Desktop.log)
[JASP 2022-11-09 16_02_41 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/9975185/JASP.2022-11-09.16_02_41.Engine.0.log)
[JASP 2022-11-09 16_04_45 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/9975186/JASP.2022-11-09.16_04_45.Desktop.log)
[JASP 2022-11-09 16_04_45 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/9975187/JASP.2022-11-09.16_04_45.Engine.0.log)
[JASP 2022-11-06 14_12_37 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/9975188/JASP.2022-11-06.14_12_37.Desktop.log)
[JASP 2022-11-06 14_12_37 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/9975189/JASP.2022-11-06.14_12_37.Engine.0.log)
[JASP 2022-11-06 14_15_43 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/9975190/JASP.2022-11-06.14_15_43.Desktop.log)
[JASP 2022-11-06 14_15_43 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/9975192/JASP.2022-11-06.14_15_43.Engine.0.log)
[JASP 2022-11-06 14_18_05 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/9975193/JASP.2022-11-06.14_18_05.Desktop.log)
[JASP 2022-11-06 14_18_05 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/9975194/JASP.2022-11-06.14_18_05.Engine.0.log)
[JASP 2022-11-06 14_19_18 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/9975195/JASP.2022-11-06.14_19_18.Desktop.log)
[JASP 2022-11-06 14_19_18 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/9975196/JASP.2022-11-06.14_19_18.Engine.0.log)
![2022-11-09 16_13_19-Data Example Normality](https://user-images.githubusercontent.com/74502865/200944528-a29edfb6-5d2b-4aa2-b4f2-c33f9012b353.png)
[Data Example Normality Test.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/9975242/Data.Example.Normality.Test.jasp.zip)
![2022-11-09 16_12_41-Loading packages for Module jaspBain failed](https://user-images.githubusercontent.com/74502865/200945359-07ea0edb-d680-42fd-ae8f-3172be4e8fd1.png)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@dbeman-student 
Could you re-test with jasp 0.18.3? Thx
