### ISSUE TITLE
[Bug]: Editing Plot (changing axes ranges) not possible

### ISSUE THREAD

**Issue by ASarafoglou** [jasp-stats/jasp-issues#1900]
### JASP Version

0.16.4

### JASP Module

JAGS

### What analysis are you seeing the problem on?

JAGS analysis

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

This is specific to one of my jasp files. I want to adjust the plots of the posterior distributions from 4 parameters in the .jasp model and JASP either crashes or gives me an error message (1st picture) or says that the axes ranges are nan (2nd/3rd picture). I can edit the axes in other .jasp files and JAGS models.

<img width="918" alt="Screenshot 2022-11-10 at 14 12 33" src="https://user-images.githubusercontent.com/20499997/201101624-9f81c396-4620-4c0e-8e96-298879957f24.png">
<img width="1625" alt="Screenshot 2022-11-10 at 14 12 43" src="https://user-images.githubusercontent.com/20499997/201101647-031f65b9-9cb4-48e8-b611-449a38ccc95c.png">
<img width="1631" alt="Screenshot 2022-11-10 at 14 12 50" src="https://user-images.githubusercontent.com/20499997/201101665-7da66b9e-252c-4907-ac3f-574bab8162fc.png">

### Expected Behaviour

I don't see why I wouldn't be able to change the axes ranges. The parameters seem fine to me.

### Steps to Reproduce

Best way to test this is probably to try to change the axes in my .jasp file: 
[DiffusionModel_shapePerception.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/9980989/DiffusionModel_shapePerception.jasp.zip)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@ASarafoglou 
I tested your file with jasp 0.18.3 - however not on macOS but on flatpak linux. Here it works fine. Can you test on your machine and confirm?

**Comment by ASarafoglou** [comment]
I just downloaded the latest version of JASP and tried to change the axes ranges using the .jasp file. It seems to work now, thank you!

**Comment by tomtomme** [comment]
Great! Closing then.
