### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by BJW89** [jasp-stats/jasp-issues#1908]
### JASP Version

0.16.4

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

JASP fails to launch

### What OS are you seeing the problem on?

Windows 11

### Bug Description

JASP opens the window, says 'loading data' (from previously saved analyses) then force quits itself and fails to launch. Have tried opening hundreds of times successively, and won't launch even when all other background processes and apps are closed. 

### Expected Behaviour

JASP should have opened.

### Steps to Reproduce

1. Every time I try to open JASP.
2.
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @BJW89 How do you open JASP: do you open it by double-clicking a JASP file, or just starting the application without any file? If it crashes already when just opening the JASP application, could just start it from the command line:

- Start a command prompt by typing 'command prompt' in the Start menu.
- Type "c:\Program Files (x86)\JASP\JASP.exe" > log.txt to start JASP. (if JASP is installed in c:\Program Files (x86), if installed somewhere else, change the path to JASP.exe)
- Check whether JASP starts or not.
- Type 'notepad log.txt' to see the log file.
- Send me this log file in a comment of this GitHub issue.
