### ISSUE TITLE
[Bug]: Can't put a graph/plot in a PPTX file, says it's not supported

### ISSUE THREAD

**Issue by burritobandito77** [jasp-stats/jasp-issues#1910]
### JASP Version

0.16.4

### JASP Module

Unrelated

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

I went to save a plot in PPTX style and it wouldn't let me. It said, "Unfortunately the plot could not be saved. Error message: pptx device only supports on epage. If the problem persists, please report the message above at: https://jasp-stats.org/bug-reports

### Expected Behaviour

I should have been able to save the plot as a .PPTX file

### Steps to Reproduce

1.In JASP, click the hamburger menu (top left) > Open > Data Library > Ttests > Kitchen Rolls
2.Click "Descriptives" (in the top bar) and then under "Tables", click the triangle/caret and then check "frequency tables" check mark 
<img width="1239" alt="Screen Shot 2022-11-21 at 12 10 39 AM" src="https://user-images.githubusercontent.com/118720395/203000011-518d4fe7-2e43-4348-9f58-695fdf46e590.png">

3.The plot that appears in the results pane says Inferential Plots, mean NEO, Prior and Posterior. If you click the triangle/caret beside "Prior and Posterior", then Save Image as > then a dialog box appears and in the dropdown it says, "Powerpoint (*.pptx)" and then the error appears (see screenshot) 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
@vandenman Other plots can be saved in pptx format (like the Sequential analysis or the Descriptives plots), but this one cannot because it says 'pptx device only supports one page' . The plot is not so big, so why should it need 2 pages? Is there a way to circumvent this error?

**Comment by vandenman** [comment]
I'll check, I've seen this error before when we erroneously tried to open a new page twice.
