### ISSUE TITLE
[Feature Request]: Added assumption test for logistic regression.

### ISSUE THREAD

**Issue by PerPalmgren** [jasp-stats/jasp-issues#1911]
### Description

One important assumption to be tested in logistic regression (when reading the literature) is that there needs to be a linear relationship between the continuous independent variables and the logit transformation of the dependent variable. 

### Purpose

Improved assumption testing

### Is your feature request related to a problem?

For the time being this can not be tested in JASP. One method that can be used to check the assumption of "linearity in the logit" is the Box-Tidwell procedure (Box & Tidwell, 1962). This procedure can be carried out in various statistical packages, including SPSS Statistics. The method is one of several methods recommended to assess whether a continuous independent variable is linearly related to the logit of the dependent variable (e.g., Hosmer & Lemeshow, 1989; Menard, 2002, 2010).

### Is your feature request related to a JASP module?

Logistic regression

### Describe the solution you would like

Apparently Box-Tidwell procedure can be found in the R CAR package: https://stackoverflow.com/questions/66618959/how-to-run-a-box-tidwell-test-in-r-to-test-for-a-linear-relationship-between-the

### Describe alternatives that you have considered

This is also described in Laerd statistics:  https://statistics.laerd.com/spss-tutorials/binomial-logistic-regression-using-spss-statistics.php

### Additional context

I hope that Box-Tidwell procedure could be incorporated in JASP with one click. Would be very elegant:-)

**Comment by EJWagenmakers** [comment]
This would be good. Maybe something for @fqixiang ?

**Comment by Arwa-AA** [comment]
Hi all,
I would like to inquire about this feature if it has been implemented, please?

**Comment by PerPalmgren** [comment]
@fqixiang Is this something you can have a look at?🙏🏻
All the best
Per😎

**Comment by PerPalmgren** [comment]
@fqixiang are you on it?

**Comment by PerPalmgren** [comment]
@fqixiang great if this assumption test could be added to the logistic module🙏🏻.
Per

**Comment by PerPalmgren** [comment]
@fqixiang You think you will have time to do this during this term?

**Comment by PerPalmgren** [comment]
Would be super if this assumption test was added to JASP. For the time being me and my students do this in SPSS. Not the most easy thing to do in SPSS😵‍💫.
Kind regards 
Per

**Comment by tomtomme** [comment]
@PerPalmgren @SA-YEM @fqixiang 
Request added to the list of missing assumption checks here: https://github.com/jasp-stats/jasp-issues/issues/490
Thus closing as duplicate now.
Thx for your requests! They will be dealt with sooner or later.

**Comment by PerPalmgren** [comment]
@tomtomme @fqixiang 
I hope that this additional assumption test for logistic regression will not be forgotten.
All the best
Per
