### ISSUE TITLE
[Bug]: Allow for choosing jasp Module in r-commander

### ISSUE THREAD

**Issue by Tony-Myers** [jasp-stats/jasp-issues#1912]
### JASP Version

0.16.4

### JASP Module

Other Module

### What OS are you seeing the problem on?

Windows 10, macOS Intel

### Bug Description

Using R beta in 0.16.4 does not allow access to R packages that are used in JASP where previous versions (including 0.16.3) do. Commands such as library(BayesFactor) and other calls to packages do not work. This happens on both Mac (intel) and Windows versions.
<img width="1012" alt="JASP issue with R beta" src="https://user-images.githubusercontent.com/40142137/203183733-4026d954-ba40-4d66-872e-d3e6c2a4ce0b.png">

### Expected Behaviour

The packages selected should load and be used for additional analysis using R code as they have with previous versions.

### Steps to Reproduce

1. Open R (beta)
2. Type the following code: library(BayesFactor)
3. Error: there is no package called ‘BayesFactor’
...

### Log (if any)

JASP 2022-11-22 00_11_11 Desktop.log

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JorisGoosen** [comment]
Ah, this is a side-effect of having separate r-libaries per module.
To use that particular package you'd have to specify the libpath there. This works now already but it would be a bit of a pain. For macos:
```

> .libPaths()
[1] "/Applications/JASP-0.16.4.app/Contents/Frameworks/R.framework/Versions/4.2-arm64/Resources/library"
> .libPaths("/Applications/JASP-0.16.4.app/Contents/Modules/jaspAnova")
> library(BayesFactor)
```

And on windows something like `.libPaths(paste0(R.home(), "../../Modules/jaspAnova"))` probably works.

I think a reasonable fix for future versions would be to have a dropdown in the R-commander where one can choose which module should be loaded (if any).
