### ISSUE TITLE
[Bug]: Cochrane terminates erroneously

### ISSUE THREAD

**Issue by RensDofferhoff** [jasp-stats/jasp-issues#1916]
### JASP Version

Others

### Commit ID

a3bd752093effa19f1c7e4ec5e7db23b44f7cd57

### JASP Module

Cochrane

### What analysis are you seeing the problem on?

Classical Continuous Outcomes

### What OS are you seeing the problem on?

macOS Silicon, Manjaro

### Bug Description

The following error is shown.
`Error in !options$coefficientEstimate: invalid argument type`
![image](https://user-images.githubusercontent.com/20978635/203826947-e6bc5f78-4b52-48e4-a61d-787929dfdbda.png)

### Expected Behaviour

-

### Steps to Reproduce

1. Open Cochrane Continuous Outcomes
2. Select any subject
3. Select any review/meta-analysis

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by FBartos** [comment]
yep, the Cochrane module does not work on the development/stable branch now because it imports analysis files from Meta-Analysis module and the qml was not updated yet. I linked the issue to the PR which will fix it.

**Comment by FBartos** [comment]
fixed in previous releases
