### ISSUE TITLE
[Bug]: This analysis terminated unexpectedly.  Error in `$<-.data.frame`(`*tmp*`, 'model', value = structure(list(coefficients = c(`(Intercept)` = 24.5288289473684), : replacement has 11 rows, data has 1  Stack trace

### ISSUE THREAD

**Issue by leahrowan** [jasp-stats/jasp-issues#1917]
### JASP Version

0.16.4

### JASP Module

Regression

### What analysis are you seeing the problem on?

Correlation, linear model

### What OS are you seeing the problem on?

Windows 11

### Bug Description

When adding my dependent variable I get this message, no matter how many different ones I try:
This analysis terminated unexpectedly.

Error in `$<-.data.frame`(`*tmp*`, 'model', value = structure(list(coefficients = c(`(Intercept)` = 24.5288289473684), : replacement has 11 rows, data has 1

Stack trace

### Expected Behaviour

it should have produced a graph

### Steps to Reproduce

1.
2.
3.
...
adding dependent or independent variables

### Log (if any)

[correlation_83030.csv](https://github.com/jasp-stats/jasp-issues/files/10096872/correlation_83030.csv)

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by Kucharssim** [comment]
Dear @leahrowan,

thank you for submitting the report.

Would you mind attaching a zipped .jasp file to this issue on the GitHub website? Alternatively, provide a step by step description of how to reproduce the issue?

I tried to reproduce the bug with the data set you attached (tried to do various settings in the linear regression analysis), but I have not managed to get the error message you reported.
