### ISSUE TITLE
[Bug]: The application is JUST NOT starting up

### ISSUE THREAD

**Issue by ramdasmenon1965** [jasp-stats/jasp-issues#1919]
### JASP Version

0.16.4

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

Unable to launch application

### What OS are you seeing the problem on?

Windows 11

### Bug Description

I installed JSP 0.16.4 yesterday, and also registered it under my email ID ramdas@ekaagra.com. It didn't work, so I uninstalled it.

I installed it again today 29 Nov 22, and tried running it but it failed again.

### Expected Behaviour

the application should have started when I clicked the icon

### Steps to Reproduce

1.
2.
3.
...
Nothing in particular

### Log (if any)

None

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by JorisGoosen** [comment]
@ramdasmenon1965 can you try starting JASP from a commandline?

Open a Command prompt and run `JASP --logToFile --safeGraphics` and then check whether you have [any logfiles](https://github.com/jasp-stats/jasp-desktop/blob/stable/Docs/user-guide/logging-howto.md) and if so please upload those here.

**Comment by ramdasmenon1965** [comment]
Dear Joris

I ran the Command Line prompt, but didn't get anything, have attached a
screenshot.

Also, I made a mistake in informing that I am using Windows 11; I am
actually using Windows 10.



Best regards
*Ramdas Menon, +91-98404-58652*

*www.ekaagra.com <http://www.ekaagra.com>*

Ramdas's Ekaagra calendar
<https://calendar.google.com/calendar/u/1?cid=cmFtZGFzQGVrYWFncmEuY29t>

**Comment by JorisGoosen** [comment]
Hey Ramdas,

To upload anything to github you need to actually go to this issue page, it will drop all attachments on emails. So I cant see you screenshot.
Also, did you see: https://github.com/jasp-stats/jasp-desktop/blob/stable/Docs/user-guide/logging-howto.md#logs-location ?

**Comment by tomtomme** [comment]
@ramdasmenon1965 
It is strang, that you said something about registering jasp. We do not ask anywhere afaik about registering. Where did you download jasp?
In any case. Make sure to get jasp from jasp-stats.org and try the new version 0.18.3. It should work!
Please let us know if you could make it work!

**Comment by tomtomme** [comment]
We cannot see your attachement, if you send them via email. Pls upload them directly here on github
