### ISSUE TITLE
[Bug]: Troubles opening large .jasp files on Mac

### ISSUE THREAD

**Issue by ASarafoglou** [jasp-stats/jasp-issues#1920]
### JASP Version

0.16.4

### JASP Module

JAGS

### What analysis are you seeing the problem on?

JAGS analysis

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

For one .jasp file I consistently have troubles opening it by just double clicking on the file.
I believe this is because the .jasp file is too big (186 MB)
<img width="551" alt="Screenshot 2022-11-29 at 15 28 12" src="https://user-images.githubusercontent.com/20499997/204557465-d67849ea-0c83-4691-8d5d-88b55fc86c04.png">

I have other .jasp files from the same module that open just fine, but that are all less than 10MB. 

I will attached a .jasp file "that works" (SignalDetectionTheory_RecognitionMemory) and the .jasp file I have troubles with (ThurstoneScaling_RankingUSStates), maybe you are able to reproduce the bug.

[SignalDetectionTheory_RecognitionMemory.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/10113974/SignalDetectionTheory_RecognitionMemory.jasp.zip)

I cannot upload the ThurstoneScaling .jasp file, but this is the OSF page where I stored it:
https://osf.io/38rjz

### Expected Behaviour

The .jasp file should open when I click on it, even if it is a large file.

### Steps to Reproduce

1. Double-click on the file (doesn't work)
2. Open JASP first, then under Open --> Computer select the .jasp file
3. This should open the analysis

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JorisGoosen** [comment]
Can you give me access to the osf file (I have an account with my uva email)? Now I get:
<img width="932" alt="image" src="https://user-images.githubusercontent.com/29062713/205170968-284b56aa-5368-4cff-9fd9-a9a214b0e535.png">

**Comment by ASarafoglou** [comment]
Sorry! I made the project public, it should work now.

**Comment by JorisGoosen** [comment]
Aah yeah, I can reproduce it and also, why is there a statefile in there of 200mb? :o

<img width="695" alt="afbeelding" src="https://user-images.githubusercontent.com/29062713/205283265-c37891bc-e719-4c77-8155-60c7e6891a3e.png">

**Comment by ASarafoglou** [comment]
I don't know..? Oo
I just ran the analysis, I don't know how that happened

**Comment by JorisGoosen** [comment]
Not your fault ;)

**Comment by Kucharssim** [comment]
JAGS probably saves the MCMC samples into a state, @vandenman?

**Comment by JorisGoosen** [comment]
Yeah he's at the JASP office, that is basically what happens. That is to be expected.
Ill just make sure JASP doesnt crash trying to load it during startup.

**Comment by JorisGoosen** [comment]
So the PR should fix the problem but I did notice it did not automactically register the new JASP app as the default application for opening JASP files... So be sure to open it through "Open with"
