### ISSUE TITLE
[Bug]: Empty documentation for SEM > Latent Growth

### ISSUE THREAD

**Issue by patc3** [jasp-stats/jasp-issues#1921]
### JASP Version

0.16.4

### JASP Module

SEM

### What analysis are you seeing the problem on?

Latent Growth

### What OS are you seeing the problem on?

Windows 10

### Bug Description

The documentation for SEM > Latent Growth is empty. I don't know what I need to put in variables/regressions/factor/timings...

![image](https://user-images.githubusercontent.com/41131893/204634094-8420b3ff-18d4-4d1d-ac6f-b7ff34075b9e.png)

### Expected Behaviour

Documentation available (not empty)

### Steps to Reproduce

1. Open a dataset
2. Activate the SEM module
3. Go at the top in SEM, click on Latent Growth
4. Click on the blue i button to get documentation

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
We have multiple modules with empty docs. I opened a meta-bug to gather all. Please add to the list there, if I missed one: 
https://github.com/jasp-stats/jasp-issues/issues/2529
