### ISSUE TITLE
[Bug]: unexpected error: missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by SKBaurai** [jasp-stats/jasp-issues#1923]
### JASP Version

0.16.4

### JASP Module

SEM

### What analysis are you seeing the problem on?

Bootstrap

### What OS are you seeing the problem on?

Windows 10

### Bug Description

![image](https://user-images.githubusercontent.com/119281063/204763617-c4d20d8c-b3d8-4aa3-b9ea-c632c472486c.png)
<html>
<body>
<div id="id-3" class="jasp-analysis" style="color: silver; font-family: Arial, sans-serif, freesans, &quot;Segoe UI&quot;; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; opacity: 1; height: 424px;"><div class="jasp-display-item jasp-collection jasp-view hidden-collection" style="margin-top: 0px; margin-bottom: 0px; padding-left: 0px; margin-right: 0px; padding-right: 0px; background-color: rgba(224, 224, 224, 0); border: 0px none; border-radius: 0px;"><div class="object-body"><div class="jasp-display-item jasp-collection-table jasp-table jasp-view jasp-indent jasp-collection-item jasp-collection-table jasp-collapsible jasp-display-item-flat" style="margin-top: 0.1em; margin-bottom: 0.6em; padding-left: 0px; margin-right: 0.6em; padding-right: 0.6em; background-color: rgba(224, 224, 224, 0); border: 1px solid rgba(105, 105, 105, 0); border-radius: 6px;"><div class="object-body"><div class="jasp-table-primitive jasp-display-primitive" style="padding-left: 0.6em;">

Model fit
--

. |   | . |   | . |   | . |   | . |   | . |   | . |   | . |   | . |   | . |   |  
 

</div></div></div></div></div></div><div class="fatalError analysis-error-message error-message-box ui-state-error" style="border: 3px double rgb(205, 10, 10); background: url(&quot;images/ui-bg_glass_95_fef1ec_1x400.png&quot;) 50% 50% repeat-x rgb(254, 241, 236); color: rgb(205, 10, 10); min-width: 300px; max-width: 1000px; position: absolute; top: 60px; left: 50px; margin-right: 50px; z-index: 100; padding: 1em; border-radius: 0.4em; white-space: normal; font-family: Arial, sans-serif, freesans, &quot;Segoe UI&quot;; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="ui-icon ui-icon-alert" style="display: block; text-indent: -99999px; overflow: hidden; background-repeat: no-repeat; width: 16px; height: 16px; background-position: 0px -144px; background-image: url(&quot;images/ui-icons_cd0a0a_256x240.png&quot;); float: left; margin-right: 0.3em;"></span>This analysis terminated unexpectedly.<br><br>Error in if (!all(rk &gt; 1 &amp; rk &lt; R)) warning('extreme order statistics used as endpoints'): missing value where TRUE/FALSE needed<br><br><div class="stack-trace-selector"><span style="cursor: pointer; display: inline-block; vertical-align: middle;">Stack trace</span><div class="stack-trace-arrow" style="width: 16px; height: 16px; margin-left: 2px; background: url(&quot;images/lightTheme/expand.png&quot;) center center / 70% no-repeat; cursor: pointer; display: inline-block; vertical-align: middle;"></div></div><div class="stack-trace" style="display: block;">tryCatchOne(expr, names, parentenv, handlers[[1]])<br><br>doTryCatch(return(expr), name, parentenv, handler)<br><br>withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)<br><br>analysis(jaspResults = jaspResults, dataset = dataset, options = options)<br><br>SEM(...)<br><br>.semParameters(modelContainer, dataset, options, ready)<br><br>.semParameterTables(modelContainer[['results']][['object']][[1]], NULL, params, options, ready)<br><br>lavaan::parameterestimates(fit, standardized = TRUE, level = options[['ciWidth']], boot.ci.type = options[['bootCItype']])<br><br>norm.inter(t, adj.alpha)</div></div>
</body>
</html>

### Expected Behaviour

The results of the model fit with Bootstrap 5000 

### Steps to Reproduce

1. Lavaan measurement and structure syntax
2. Bootstrap 5000
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by LSLindeloo** [comment]
Hi @SKBaurai, 

Could you provide me the dataset that was used and the exact model you specified? Then I will be able to find out what the problem is.
You could send these to lorenzolindeloo@gmail.com or include them in this conversation. 

Thanks in advance!

Lorenzo
