### ISSUE TITLE
[Feature Request]: Heading in data

### ISSUE THREAD

**Issue by PerPalmgren** [jasp-stats/jasp-issues#1928]
### Description

It would be great when in the data window that when you press to re-label that the JASP user had the possibility to rename name of the variable! 

### Purpose

More user friendly when handling variables

### Is your feature request related to a problem?

No

### Is your feature request related to a JASP module?

Unrelated

### Describe the solution you would like

This very good function is possible in JAMOVI.

**Comment by boutinb** [comment]
This add this to the Data Editing project.

**Comment by PerPalmgren** [comment]
Will this be incorporated in 0.17 version?

**Comment by boutinb** [comment]
No, this will be probably in 0.18, when we will introduce data editing inside JASP. Just as reminder: with synchronization, you can already change data and column name in Excel or any spreadsheet editor, and the change will be automatically read by JASP.

**Comment by tomtomme** [comment]
This is done!
