### ISSUE TITLE
[Bug]: Can not load data measure types (nominal, ordinal) for Factor analysis

### ISSUE THREAD

**Issue by maks7** [jasp-stats/jasp-issues#1929]
### JASP Version

0.16.4

### JASP Module

Factor

### What analysis are you seeing the problem on?

Principal component analysis

### What OS are you seeing the problem on?

Other

### Bug Description

I am using Windows 8.1 OS.
JASP can load only scalar data measure type for Factor analysis. Is it by design behavior to load only scalar data for analysis? I think that most probably it is a bug so all kind of data should be able to load for analysis.

### Expected Behaviour

I expected when I like to prepare sub-set of data (to use 10 items from 50 items list) for Factor (Principal component analysis) to be able to add them like: when I click on A10 item with measure type (nominal, ordinal), the button "add arrow" to be enabled so I can add the item to the Variables list.

Screenshot for set of items:
![JASP_Factor_Bug_1](https://user-images.githubusercontent.com/11076429/205450423-395245f3-d3eb-4961-b616-9e644db5ce32.JPG)

### Steps to Reproduce

1. On a Windows machine (OS version Windows 8.1), install JASP v.0.16.4
2. Once installed, load statistical data file.
3. Once data file loaded and data visible on screen, run Factor (main menu) ->then Principal Component Analysis.
4. Once Principal Component Analysis on the screen, click on item measure type (nominal, ordinal) and click arrow button to add to Variables list section.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment]
thanks for creating the issue, this will be fixes with the next release :)
