### ISSUE TITLE
Predictors should be encoded in base64. Header with slash confuses JASP. Error message "object 'XSg' not found" 

### ISSUE THREAD

**Issue by yuttin1i2o** [jasp-stats/jasp-issues#193]
## Template for bug reports

When I set J/N data as Factors, then error message "object 'XSg' not found" appears.

Here is the file:
[181012_JASP.xlsx](https://github.com/jasp-stats/jasp-desktop/files/2473260/181012_JASP.xlsx)

* JASP version: 0.9.1.0
* OS name and version: Windows 10 Home
* Analysis: Meta Analysis
* Steps to reproduce: 
![image](https://user-images.githubusercontent.com/44092454/46872409-f52ea780-ce6e-11e8-9f5f-dbfa2f1be065.png)

## Template for enhancement requests
 
* Enhancement: I wish I could earn how to solve this error message.
* Purpose: I cannot go through my analysis.

**Comment by akashrajkn** [comment]
Duplicate issue #248. Fixed in PR jasp-desktop#2932
