### ISSUE TITLE
[Bug] Weblate is blocked: "Pay the bills to unlock this project."

### ISSUE THREAD

**Issue by JoKeyser** [jasp-stats/jasp-issues#1930]
### Bug Description

Weblate is blocked for all components - it is currently impossible to fix/save any translation via Weblate.
Weblate reports "Pay the bills to unlock this project."

![jasp-bills](https://user-images.githubusercontent.com/8722846/205490451-4942a9eb-fd8d-459a-a54c-e21dca35eefd.png)

This may be related to the special plan that JASP enjoys, see https://github.com/jasp-stats/jasp-issues/issues/1482, hopefully this is just a misconfiguration.

### Expected Behaviour

Weblate users should be able to fix/save translations.

### Steps to Reproduce

1. Visit any JASP module on Weblate at <https://hosted.weblate.org/projects/jasp/>.
2. Try to fix/save any translation.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Yes I know. Apparently the bill was not yet paid. I have asked the financial department of the UvA to pay it asap.

**Comment by JoKeyser** [comment]
The message disappeared, and I can save strings again; so I'm closing this.

**Comment by boutinb** [comment]
Yes it took a while. Sorry for the inconvenience.
