### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by martin-vasilev** [jasp-stats/jasp-issues#1931]
### JASP Version

0.16.2

### JASP Module

Frequencies

### What analysis are you seeing the problem on?

Contingency Tables

### What OS are you seeing the problem on?

Windows 10

### Bug Description

![Untitled](https://user-images.githubusercontent.com/8078973/205664787-211e3f27-2259-45d9-a33d-87c6643767b1.png)
[bridge.csv](https://github.com/jasp-stats/jasp-issues/files/10155090/bridge.csv)
[bridge.zip](https://github.com/jasp-stats/jasp-issues/files/10155133/bridge.zip)

Phi-coefficient from the Chi-square test shows a negative value, when the measure can have only positive values (between 0 and 1). Previous versions of JASP (I believe 0.14) didn't use to have this problem, as we have been using this dataset for teaching for a few years. 

### Expected Behaviour

It should return a positive Phi coefficient value.

### Steps to Reproduce

1.Open Bridge.csv
2. Frequency -> Contingency Tables
3. Drag both variables and tick effect size measures
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by EJWagenmakers** [comment]
I thought this was actually something that was fixed in response to a bug report?! When I quickly Google this I find that Phi is allowed to take on negative values. I will try to find the issue...

**Comment by martin-vasilev** [comment]
Oh, I see. I wasn't aware of this, as I have only seen the formula where it is calculated from the
