### ISSUE TITLE
[Bug]: Error in `[.data.frame`(dataset, k): undefined columns selected

### ISSUE THREAD

**Issue by Scott-Leek** [jasp-stats/jasp-issues#1932]
### JASP Version

0.16.4

### JASP Module

Quality Control

### What analysis are you seeing the problem on?

Variables charts for subgroups

### What OS are you seeing the problem on?

Windows 10

### Bug Description

![image](https://user-images.githubusercontent.com/119875860/205674862-c0ff814b-6085-4eb7-ae2f-80eb946fd415.png)

[10 primer thickness.csv](https://github.com/jasp-stats/jasp-issues/files/10155457/10.primer.thickness.csv)

this analysis terminated unexpectedly.

Error in `[.data.frame`(dataset, k): undefined columns selected

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

variablesChartsSubgroups(...)

.PClongTowide(dataset, k, measurements)

table(dataset[k])

dataset[k]

`[.data.frame`(dataset, k)

stop('undefined columns selected')

### Expected Behaviour

I get an X-bar and R chart

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JTPetter** [comment]
This is fixed in the latest version.
