### ISSUE TITLE
[Feature Request]: Simple Slopes for Linear Regression

### ISSUE THREAD

**Issue by renenob** [jasp-stats/jasp-issues#1933]
### Description

In the linear regression module, please add option to check for simple slopes analysis to check  the effect of IV on DV across different levels of the moderator

### Purpose

This is needed to robustly report moderation effect.  It's kind of pointless to report the there is moderation when I cannot even describe the nature of the moderation.

### Use-case

In all regression analyses testing for moderation or interaction

### Is your feature request related to a JASP module?

Regression

### Describe alternatives that you have considered

I go to JAMOVI to check the simple slopes. but I like JASP better so I was hoping I don't have switch software as I am analyzin

**Comment by tomtomme** [comment]
@renenob 
since jasp 0.18.2 added the process module, you can now do simple slopes analyisis in JASP!
Hence I am closing this one.
Feel free to reopen, if I misunderstood your request!
