### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Pey2000** [jasp-stats/jasp-issues#1934]
### JASP Version

0.15

### JASP Module

Unrelated

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

A bug

### Expected Behaviour

When I attempt to open jasp, it says a bug happened and does not let me open it. 

### Steps to Reproduce

1.Open Jasp

### Final Checklist

- [x] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
@Pey2000  You say that you use JASP 0.15. Why do you use an old version. Can you try the last version (0.16.4). Also:which Mac OS version do you have?
