### ISSUE TITLE
[Bug]: Repeated Measures- Contrast table must have a positive length of dim

### ISSUE THREAD

**Issue by mpeters2** [jasp-stats/jasp-issues#1936]
### JASP Version

0.16.4

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

Repeated Measures

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

Any analysis other than a one-way anova causes the following error message:

![image](https://user-images.githubusercontent.com/26334076/206802211-ab6b7fdd-17c2-4cb2-8d19-a3806790bbe2.png)

### Expected Behaviour

I expected it to perform an 3x3 ANOVA.  I can successfully perform one-way ANOVAs using the same data columns, but as soon as I add another factor, it gives me an error.  I've tried both 2x2 and 3x3 repeated-measures ANOVAs.

### Steps to Reproduce

1.Start a Repeated-measures ANOVA
2.Define the first factor
3.Define the second factor
4.Assign data to the cells...crash!
...

### Log (if any)

[JASP 2022-12-09 11_03_15 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/10198430/JASP.2022-12-09.11_03_15.Engine.0.log)
[JASP 2022-12-09 11_03_15 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/10198432/JASP.2022-12-09.11_03_15.Desktop.log)

[DataAndJASPfiles.zip](https://github.com/jasp-stats/jasp-issues/files/10198436/DataAndJASPfiles.zip)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JohnnyDoorn** [comment]
Hi @shun2wang ,

Could you try renaming the factorlevels? I think the "none" is causing some issues, so renaming it to something else (e.g., "nothing") should fix it. We are working on a solution, but this would help in the meantime. Apolgies for the tardy reply.

Kind regards,
Johnny

**Comment by shun2wang** [comment]
Hi @JohnnyDoorn ah, I just changed the empty title but I am not owner of this issue😃

**Comment by JohnnyDoorn** [comment]
Ahh sorry!! I meant @mpeters2

**Comment by tomtomme** [comment]
@mpeters2 
I tested using your file and jasp 0.18.3
I even left the "none".  All worked fine.
Feel free to reopen, if not fixed on your side.
