### ISSUE TITLE
[Bug]: contrasts can be applied only to factors with 2 or more levels

### ISSUE THREAD

**Issue by KatastroFee811** [jasp-stats/jasp-issues#1937]
### JASP Version

0.16.4

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

MANOVA

### What OS are you seeing the problem on?

Windows 10

### Bug Description

![Fehlermeldung](https://user-images.githubusercontent.com/120279122/206873854-86a1a5ae-00d9-4c7f-bb52-7ee03ae7fd2a.jpg)
```r
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]): Kontraste können nur auf Faktoren mit 2 oder mehr Stufen angewendet werden  Stack trace Manova(...)  .manovaComputeResults(jaspResults, dataset, options, ready)  stats::aov(terms(formula(modelFormula), keep.order = TRUE), datasetFac)  eval(lmcall, parent.frame())  eval(lmcall, parent.frame())  stats::lm(formula = terms(formula(modelFormula), keep.order = TRUE), data = datasetFac, singular.ok = TRUE)  model.matrix(mt, mf, contrasts)  model.matrix.default(mt, mf, contrasts)  `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]])  stop('contrasts can be applied only to factors with 2 or more levels')
```

Diese Fehlermeldung erscheint sobald ich die MANOVA erstellen möchte. In einer vorherigen MANOVA mit einem ähnlichen Datensatz der genauso formatiert war und die gleichen Faktoren erhielt, gab es keinerlei Probleme

Ich habe beispielhaft einen Auszug aus dem Datensatz mit angehängt

![Datensatz](https://user-images.githubusercontent.com/120279122/206873907-fa1559af-56fb-4421-8bee-02d6316a03a9.jpg)

Ich benötige die MANOVA für meine Bachelorarbeit

### Expected Behaviour

Das Berechnen der MANOVA

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@KatastroFee811 
Feel free to reopen, if you can share your jasp file.
