### ISSUE TITLE
[Bug]: Error when running standard t-test

### ISSUE THREAD

**Issue by mspezz** [jasp-stats/jasp-issues#1940]
### JASP Version

0.16.4

### JASP Module

Equivalence T-Tests

### What analysis are you seeing the problem on?

Independent Samples T-Test

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

Error in (new('C++Function', .Data = function (...) : Trying to decode columnName but 'CorticalGrayMatterRightSideVolume' is not an encoded columnName!

### Expected Behaviour

Expected an output screen with tables and plots. 

### Steps to Reproduce

1. Add DV
2. Add IV
3.
[...](url)
[CH-NAT V CH-PAT Analysis.xlsx](https://github.com/jasp-stats/jasp-issues/files/10222863/CH-NAT.V.CH-PAT.Analysis.xlsx)

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@mspezz 
Equivalence t-Test was fixed recently, sorry that it took so long!
Feel free to reopen, if not fixed on your side!
