### ISSUE TITLE
[Bug]: error message but the analysis is run in SEM modul

### ISSUE THREAD

**Issue by areeq1** [jasp-stats/jasp-issues#1941]
### JASP Version

Others

### JASP Module

SEM

### What analysis are you seeing the problem on?

SEM modul

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

Please see the picture attached
![Uploading 203411441-cb394292-0bff-4779-b361-f4daf4ee21d1.jpeg…]()

### Expected Behaviour

none

### Steps to Reproduce

any SEM analysis I guess

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by LSLindeloo** [comment]
@areeq1 Thanks! However, I cannot open the provided image; could you drag the image into a comment? I believe I can see the image then! Also, could you send me additional information and the dataset that was used to reproduce the error?

Thanks in advance!

Lorenzo

**Comment by areeq1** [comment]
Ok, let's try it again here. I have attached it. Can you please confirm receipt? The error messages appear in any application of SEM. Note, please that I'm using a night version 17:56 02-11-2022
Cheers
![Screen Shot 2022-11-22 at 11 08 23 pm](https://user-images.githubusercontent.com/68887104/208967250-06864e32-d51f-4edd-a14b-a1c689955083.jpg)

**Comment by shun2wang** [comment]
Hi@areeq1 can you try it  on 0.16.4 [release version](https://jasp-stats.org/download/)? a nightly build just for our development verification and often have some problems, so we **do not** recommend long-term use.

**Comment by areeq1** [comment]
True. When the latest version is used the message disappears. Thanks

**Comment by Ghassan-Okour** [comment]
> True. When the latest version is used the message disappears. Thanks

@areeq1 ESEM working in JAMOVI as well
