### ISSUE TITLE
[Bug]: Logistic Regression, Degree of Freedom

### ISSUE THREAD

**Issue by bmatyasb** [jasp-stats/jasp-issues#1944]
### JASP Version

0.16.4

### JASP Module

Regression

### What analysis are you seeing the problem on?

Logistic Regression

### What OS are you seeing the problem on?

Windows 11

### Bug Description

Logistic regression gave me a strange degree of freedom (number of observations - number of predictors used).
![image](https://user-images.githubusercontent.com/91070973/208058334-c974e3c9-4585-48f1-8f33-b8102917c6e9.png)

### Expected Behaviour

As far as I know, and according to other programs (jamovi, SPSS), in a binomial logistic regression the degree of freedom = number of groups - 1. Since it is binomial, df = 1. 
(screenshot from jamovi).
![image](https://user-images.githubusercontent.com/91070973/208058456-2a8d47bd-9143-4da0-b6a4-1deb5928dd74.png)

In JASP, however, df = number of observations - number of predictors in the model (this can be seen in the Model Summary).
Hence the p-values etc associated with my predictors are not the same as those obtained with other programs. 
Why is this? Why is the degree of freedom calculation different?

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by Kucharssim** [comment]
Dear @bmatyasb,

The df in the JASP output you are looking at is the df for the whole model. The df you are looking at in jamovi is per predictor. It seems jamovi does not report the df for the whole model.

The df you are seeking in JASP is in the "Coefficients" table, not "Model Summary".

I hope this helps! Please reopen the issue if something is still unclear or if you insist there is an error.
