### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by Reardon7** [jasp-stats/jasp-issues#1945]
### Description

Density plot with subgroups

### Purpose

To better report the distribution of data

### Use-case

Any time a density plot may include groups

### Is your feature request related to a problem?

I solved it in R, but think many would like it it JASP

### Describe the solution you would like

Workshopped at https://stackoverflow.com/questions/74826246/how-to-overlay-total-density-and-group-density-using-ggdensity

### Describe alternatives that you have considered

Completed in JASP

### Additional context

 I wanted to generate a single density plot diagram that shows both the total density and group density plots. 

The R function I created to do this is the following:

`Densityplot<-function(var1,var2,df1) { 
  contvar = deparse(substitute(var1)) 
  dvar = deparse(substitute(var2)) 
  ggdensity(df1, x = contvar, add = "mean", rug = TRUE, color = dvar, fill = dvar)+geom_density(aes(y = after_stat(density * 2))) + scale_y_continuous(sec.axis = sec_axis(~.x/2, name = 'Total density'))}
`

Using the built in R iris data, it is called as:
`Densityplot(Sepal.Length,Species,iris)`

It would be helpful if JASP included an option for density plots to (a) be divided into groups, and (b) to display the total density in addition to the group density.   Bonus points for also allowing users to define the colors used in the density plot!

This was [workshopped here](https://stackoverflow.com/questions/74826246/how-to-overlay-total-density-and-group-density-using-ggdensity).

**Comment by EJWagenmakers** [comment]
This is under development right now.

**Comment by tomtomme** [comment]
@Reardon7 
I just realized we have this already in descriptives, see: 
[densities.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/14210911/densities.jasp.zip)

So for densitie plots alone, this is done. And improved rainclouds (also for descriptives) are planned.
