### ISSUE TITLE
[Bug]: custom contrasts in MIXED ANOVA: changes in df calculation (and error pooling) between JASP Versions 0.14.1 and 0.16.3

### ISSUE THREAD

**Issue by farstat** [jasp-stats/jasp-issues#1946]
### JASP Version

0.16.3

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

Repeated Measures ANOVA

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

As I am currently running a replication study, I wanted to replicate some MIXED-ANOVA-results from last year (JASP version 0.14.1). However, as I did so using my actual version of JASP (0.16.3), the same input led to strongly changed degrees of freedom in the tests for custom contrasts. Here are the results:

1. Analysis from JASP version 0.14.1
[results0.14.1.pdf](https://github.com/jasp-stats/jasp-issues/files/10259793/results0.14.1.pdf)

2. Analysis from JASP version 0.16.3
[results0.16.3.pdf](https://github.com/jasp-stats/jasp-issues/files/10259795/results0.16.3.pdf)

### Expected Behaviour

I thought both analyses should reproduce the same results. Did you change the calculation behind it? And if so: It is documented somewhere, so that I can refer to it? What is the difference between the two approaches?

### Steps to Reproduce

I am not sure, if you can reproduce the issue, you should run the same analyses with JASP 0.16.3 and JASP 0.14.1. 

I have added a reduced data-set for you (please note that I excluded all participants with missing on the ic-variable).
[data_JASP.csv](https://github.com/jasp-stats/jasp-issues/files/10259830/data_JASP.csv)

The contrast specifications you can see via the outputs above, I did repeated Measurements ANOVA with cond as between factor and gd_social_t1 to t3 as repeated measures of goal desirability.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JohnnyDoorn** [comment]
Marking this as closed, since it has been answered on the JASP forum: https://forum.cogsci.nl/discussion/8346/custom-contrasts-in-jasp-rm-anova-different-df-calculation-and-error-pooling-in-0-14-1-and-0-16-3#latest
