### ISSUE TITLE
[Bug]: JASP crashes on startup when opening very large .jasp-files

### ISSUE THREAD

**Issue by maximusmontis** [jasp-stats/jasp-issues#1947]
### JASP Version

0.16.4

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

Any larger number of analyses

### What OS are you seeing the problem on?

Windows 11

### Bug Description

When opening very large JASP files with lots of analyses/plots (~30 MB or larger) directly from Windows Explorer, JASP crashes on startup.
A possible workaround is to start JASP without opening a file, and then open the file through JASP.
The crash ist not related to any particular file or analysis, it happens with any large file.

### Expected Behaviour

The file should be opened without crashing.

### Steps to Reproduce

1. Find/Create large JASP file (>30 MB)
2. Open file through Windows Explorer (double click)
3. JASP crashes

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
I think @JorisGoosen did solve this problem. Could you try it on this beta version of 0.17: https://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-stable-b602fde033a17d0f01eac1f6e5ebc8ecf907a3c2.msi
