### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ajkhansa** [jasp-stats/jasp-issues#1949]
### JASP Version

0.16.3

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 11

### Bug Description

JASP starts up but then it does not open after. The first loading screen appears and then I am unable to see anything after that. I cannot open the software or any JASP file. I tried it with 0.16.4 as well as with 0.16.3 and the same problem persists.

### Expected Behaviour

The software should have opened normally.

### Steps to Reproduce

1.Open JASP
2.After the loading screen nothing appears, so am unable to do anything further.
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by ajkhansa** [comment]
Hi, it is not the data file that causes the issues. JASP shows the starting window and nothing appears after. It is the same if I use any previously created JASP file. This started happening all of a sudden.

**Comment by shun2wang** [comment]
Hi @ajkhansa thanks for your report. Could you refer to [here](https://github.com/jasp-stats/jasp-desktop/blob/stable/Docs/user-guide/logging-howto.md#windows) and upload a .log file?
