### ISSUE TITLE
[Bug]: repeated two way ANOVA 

### ISSUE THREAD

**Issue by melanie0120** [jasp-stats/jasp-issues#1950]
### JASP Version

0.16.4

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

Repeated measures

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

I am doing a two-way repeated ANOVA but there are a few bugs.

<img width="1457" alt="截圖 2022-12-23 上午10 39 12" src="https://user-images.githubusercontent.com/121272289/209260558-19251fb9-e42f-4236-960c-14de09b286dc.png">
<img width="1455" alt="截圖 2022-12-23 上午10 39 25" src="https://user-images.githubusercontent.com/121272289/209260566-acf345bb-6bce-4a2d-b958-b023bf154744.png">

What does it mean? Please help me! I am going to cry 😭

### Expected Behaviour

It should have show me the result

### Steps to Reproduce

Here is the data.

[SPSOA_data.csv](https://github.com/jasp-stats/jasp-issues/files/10291694/SPSOA_data.csv)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JohnnyDoorn** [comment]
Hi @melanie0120,

I think something is going wrong because of the names of your factor levels. Could you try renaming them (for instance words instead of numerics), to see if that solves the problem?  We are working on a solution currently, but this could work in the meantime. 

Kind regards
Johnny

**Comment by tomtomme** [comment]
@melanie0120 
I re-tested with your file and your settings from the screenshot in jasp 0.18.3 and everything went fine.
Feel free to reopen if not fixed on your side.
