### ISSUE TITLE
[Feature Request]: Operations on subsets of data files

### ISSUE THREAD

**Issue by deldotcurliszero** [jasp-stats/jasp-issues#1953]
### Description

Develop tools & methods for performing operations (e.g. descriptive statistics) on subsets of data files. Similarly, allow manipulation of data tables to create additional tables that highlight different aspects of the data and allowing performing of analyses on them

### Purpose

Allow exploration of data efficiently from different perspectives from within JASP

### Use-case

Data set has disease incidence rate by gender, ethinicity and age. I would like to create derived data sets, for example by binning by age ranges, and then explore and analyze them by ethicity, by gender etc.

### Is your feature request related to a problem?

data exploration with descriptive statistics from different perspectives

### Additional context

Currently the only way to manipulate data different ways for analysis is to do it outside of JASP and upload one data file at a time. This is very tedious and time consuming when exploring data.

**Comment by tomtomme** [comment]
@deldotcurliszero 
I think everything you describe is possible in JASP. Have you tried data edit mode and all the filtering options and options to calculate new columns? Also Flexplot from the visual modeling module is great for exploration.

If your problems are not yet solvable, then feel free to reopen with some more details. Thx!
