### ISSUE TITLE
[Bug]: app closes on hp pavillion laptop

### ISSUE THREAD

**Issue by razija313** [jasp-stats/jasp-issues#1955]
### JASP Version

Others

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 10, Windows 11

### Bug Description

I downloaded jasp onto my hp pavilion laptop and it closes right when I try to open it to use it. I ran a repair popup and it still closed after a second. 

### Expected Behaviour

The app opened and I browsed jasp. 

### Steps to Reproduce

1. Download app 
2. Open it
3. Then it would close 
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @razija313, could you try the pre-installed version: https://jasp-stats.org/thank-you-for-downloading-jasp-win64-zip ?

**Comment by razija313** [comment]
I did and a bunch of files downloaded but not the jasp app. 

Sent from Yahoo Mail on Android 
 
  On Thu, Jan 5, 2023 at 9:52 AM, bruno ***@***.***> wrote:   


Hi @razija313, could you try the pre-installed version: https://jasp-stats.org/thank-you-for-downloading-jasp-win64-zip ?

**Comment by razija313** [comment]
What can I do instead since the app is still not downloading? 

Sent from Yahoo Mail on Android 
 
  On Thu, Jan 5, 2023 at 9:52 AM, bruno ***@***.***> wrote:   


Hi @razija313, could you try the pre-installed version: https://jasp-stats.org/thank-you-for-downloading-jasp-win64-zip ?

**Comment by shun2wang** [comment]
Hi @razija313 If you downloaded JASP zip file like `JASP-0.16.4-64bit.zip`, just unzip it and run JASP.exe in the folder.
If you have any problems, you can take a screenshot and upload it [here](https://github.com/jasp-stats/jasp-issues/issues/1955) (but cannot upload by email).🍻

**Comment by razija313** [comment]
![20230105_212414](https://user-images.githubusercontent.com/122033438/210925729-989d34e0-ce4f-4d79-891e-029a6fb8312c.jpg)
When I ran the link this popped up

**Comment by shun2wang** [comment]
@razija313 did you tried the pre-installed latest version: https://jasp-stats.org/thank-you-for-downloading-jasp-win64-zip ?
and check your PC hardware specifications refer to:https://pureinfotech.com/find-computer-specs-windows-11/

**Comment by razija313** [comment]
Is there any other way I can use jasp if my computer does not directly download it for any reason. I am willing to buy roll-on app if this gives me access to jasp on my phone and laptop. Can you please suggest me another route I can take because my statistics class begins today and I have assignments required for me to do in jasp to submit immediately. Thank you for your help

Sent from Yahoo Mail on Android 
 
  On Thu, Jan 5, 2023 at 10:57 PM, Shun ***@***.***> wrote:   


@razija313 did you tried the pre-installed latest version: https://jasp-stats.org/thank-you-for-downloading-jasp-win64-zip ?
and check your PC hardware specifications refer to:https://pureinfotech.com/find-computer-specs-windows-11/

**Comment by boutinb** [comment]
It is quite unclear what is going wrong on your PC...
From the screenshot you sent, I see that you had 0.16.2 installed, but. the last JASP version is 0.16.4. Did you install JASP before?
There exists a (paid) online version as specified in the download page (https://jasp-stats.org/download/), but you will get only an older version (0.14.3).
And also I don't understand why you can't download the zip file https://jasp-stats.org/thank-you-for-downloading-jasp-win64-zip...

**Comment by razija313** [comment]
I do see I downloaded both the 0.16.2 and 0.16.4 now. I am deleting the 0.16.2 now Does buying jasp allow me to use it in my browser rather than downloading it? 

Sent from Yahoo Mail on Android 
 
  On Fri, Jan 6, 2023 at 8:42 AM, bruno ***@***.***> wrote:   


It is quite unclear what is going wrong on your PC...
From the screenshot you sent, I see that you had 0.16.2 installed, but. the last JASP version is 0.16.4. Did you install JASP before?
There exists a (paid) online version as specified in the download page (https://jasp-stats.org/download/), but you will get only an older version (0.14.3).
And also I don't understand why you can't download the zip file https://jasp-stats.org/thank-you-for-downloading-jasp-win64-zip...

**Comment by razija313** [comment]
If I buy roll on and run jasp through roll on, does this give me access to jasp with out having to download it to my computer? 

Sent from Yahoo Mail on Android 
 
  On Fri, Jan 6, 2023 at 8:42 AM, bruno ***@***.***> wrote:   


It is quite unclear what is going wrong on your PC...
From the screenshot you sent, I see that you had 0.16.2 installed, but. the last JASP version is 0.16.4. Did you install JASP before?
There exists a (paid) online version as specified in the download page (https://jasp-stats.org/download/), but you will get only an older version (0.14.3).
And also I don't understand why you can't download the zip file https://jasp-stats.org/thank-you-for-downloading-jasp-win64-zip...

**Comment by boutinb** [comment]
The RollApp online version is not done by us, but by another compagnie. You get JASP online (so you don't have to download it), but as I said , it is a quite old version, which maybe does not fit for your course.

**Comment by tomtomme** [comment]
@razija313 
Is this resolved? If yes, feel free to close this issue.

Related: https://github.com/jasp-stats/jasp-issues/issues/1760
