### ISSUE TITLE
[Bug]: incompatible system

### ISSUE THREAD

**Issue by razija313** [jasp-stats/jasp-issues#1956]
### JASP Version

0.9.2

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I downloaded jasp on my hp pavilion and when I try to open it it won't stay open. I troubleshooted the issue and it said that my software was incompatible 

### Expected Behaviour

I downloaded jasp and it opened

### Steps to Reproduce

1.download jasp
2.open it up
3. Go to jasp in files
4. Click on jasp with right button
5. Trouble shoot 
6. Detect issue

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@razija313 
Can you re-test with jasp 0.18.3?
