### ISSUE TITLE
[Feature Request]: Allow the user to specify discrete/a range of missing values per variable rather than the existing single global option

### ISSUE THREAD

**Issue by TarandeepKang** [jasp-stats/jasp-issues#1957]
### Description

Define the missing values for each variable separately

### Purpose

Analysis of data with different missing values for each variable

### Use-case

Analysis of survey data, where each question may have single/multiple values to be recorded as missing, and these may differ between questions

### Is your feature request related to a problem?

Datasets with multiple missing values that differ across variables cannot currently be analysed using the software.

### Describe the solution you would like

The option to declare missing values separately for each variable

### Describe alternatives that you have considered

Use SPSS (unfortunately) or R

### Additional context

Missing values interface in SPSS is excellent, and would provide a good template. This is probably the single biggest issue holding back wider adoption of JASP by survey researchers.

**Comment by TarandeepKang** [comment]
Hi team, I can only imagine how busy you are, but equally I thought I would just follow-up on the status of this issue.

**Comment by TarandeepKang** [comment]
Again, sorry to bother, but this does seem to be a very important feature which could go well with any plans you have for data editing?

**Comment by boutinb** [comment]
We will add this feature. First we will release a version with Data Editing this month, where more room is given for the variable properties (long name, description), then we will add this feature.

**Comment by TarandeepKang** [comment]
That's wonderful! Both are going to be very useful, and very widely appreciated!

**Comment by boutinb** [comment]
Implemented by https://github.com/jasp-stats/jasp-desktop/pull/5276
