### ISSUE TITLE
[Bug]: I am unable to conduct multigroup CFA

### ISSUE THREAD

**Issue by hongfeiy63** [jasp-stats/jasp-issues#1958]
### JASP Version

0.16.4

### JASP Module

Factor

### What OS are you seeing the problem on?

Windows 10

### Bug Description

When I do multigroup CFA, it shows some categories of variables are empty (see ttached)

[A.docx](https://github.com/jasp-stats/jasp-issues/files/10371262/A.docx)
[Uploading A1.jasp…]()
[Uploading Data File A.1sav.sav…]()

### Expected Behaviour

Because I failed to do multigroup CFA, I want to do it successfuly. 
[A.docx](https://github.com/jasp-stats/jasp-issues/files/10371286/A.docx)

### Steps to Reproduce

1.click fator analysis
2.click multigroup CFA
3.select C1A2as group variable
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by Kucharssim** [comment]
Dear @hongfeiy63,

thank you for your report. I see you tried to upload some files, but I cannot open them (I think perhaps you submitted the issue before the files were fully uploaded).

Could you please come back to this issue and upload the files again? Thank you very much.

**Comment by hongfeiy63** [comment]
[A.zip](https://github.com/jasp-stats/jasp-issues/files/10372389/A.zip)

**Comment by hongfeiy63** [comment]
Many thanks! I did now. Sorry for this inconvenience.
















At 2023-01-09 15:48:25, "Simon Kucharsky" ***@***.***> wrote:

Dear @hongfeiy63,

thank you for your report. I see you tried to upload some files, but I cannot open them (I think perhaps you submitted the issue before the files were fully uploaded).

Could you please come back to this issue and upload the files again? Thank you very much.

**Comment by juliuspf** [comment]
this is the error I see
![Screenshot 2023-01-09 at 11 50 44](https://user-images.githubusercontent.com/38500953/211291401-a204e9d3-5eff-4198-95ea-1eb8494140fb.png)
this does not strike me as a bug. It is a problem with your data after grouping. If you use the descriptives module, split the used variables by your grouping variable and show the frequency tables you will see that some categories have zero cases after grouping. Lavaan (which JASP uses) does not like that. You may have to recode some of your data. See this answer https://groups.google.com/g/lavaan/c/ZEbJqF03DPg. Unfortunately, collapsing categories is far from ideal.

**Comment by hongfeiy63** [comment]
Many thanks for your email.
But I found this empty is not true. Pls see the below results of frequency. Actually, Group 1 has 331 participants and Group 2 has 166 participants.The JASP shows that the frequencies are 0+4+17+56+56=133. Why?















At 2023-01-09 19:03:11, "Julius Pfadt" ***@***.***> wrote:

this is the error I see

this does not strike me as a bug. It is a problem with your data after grouping. If you use the descriptives module, split the used variables by your grouping variable and show the frequency tables you will see that some categories have zero cases after grouping. Lavaan (which JASP uses) does not like that. You may have to recode some of your data. See this answer https://groups.google.com/g/lavaan/c/ZEbJqF03DPg. Unfortunately, collapsing categories is far from ideal.

**Comment by hongfeiy63** [comment]
Many thanks for your email.
But I found that this empty is not true. Pls see the below results of frequency. Actually, Group 1 has 331 participants and Group 2 has 166 participants.The JASP shows that the frequencies are 0+4+17+56+56=133. Why?


[image1.zip](https://github.com/jasp-stats/jasp-issues/files/10373016/image1.zip)

**Comment by hongfeiy63** [comment]
Dear Simon,
Many thanks. But I do not understand your frequency. Would you pls kindly tell me the way you got the frequency? For I got my frequency by "Analysis" in  SPSS.
BTW, I am unable to open  https://groups.google.com/g/lavaan/c/ZEbJqF03DPg. What browser works?
Best,
Hongfei Yang
















At 2023-01-09 20:40:21, "Simon Kucharsky" ***@***.***> wrote:

Dear @hongfeiy63,

this is not about the total observations per group, but about the response patterns in the indicator variables split by group.

For example, the "Not at all" category in PCM02 variable was observed 0 times in Group 1:

From descriptives:

Double checked with contingency tables:

**Comment by Kucharssim** [comment]
Dear @hongfeiy63,

please download and unzip [descriptives.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/10373670/descriptives.jasp.zip) for the computed frequencies.

> BTW, I am unable to open  [groups.google.com/g/lavaan/c/ZEbJqF03DPg](https://groups.google.com/g/lavaan/c/ZEbJqF03DPg). What browser works?

I don't have trouble with opening this link on my browsers (chrome, safari)

**Comment by hongfeiy63** [comment]
Dear Julius，
Many thanks！I am not able to open https://groups.google.com/g/lavaan/c/ZEbJqF03DPg。
Would you pls kindly open it and make some screenshots (pictures) and email me?
Many thanks!
Best!
Hongfei Yang













At 2023-01-09 19:03:11, "Julius Pfadt" ***@***.***> wrote:

this is the error I see

this does not strike me as a bug. It is a problem with your data after grouping. If you use the descriptives module, split the used variables by your grouping variable and show the frequency tables you will see that some categories have zero cases after grouping. Lavaan (which JASP uses) does not like that. You may have to recode some of your data. See this answer https://groups.google.com/g/lavaan/c/ZEbJqF03DPg. Unfortunately, collapsing categories is far from ideal.

**Comment by juliuspf** [comment]
You should thank Simon :) Here are two screenshots of the website you can't open.

![Screenshot 2023-01-10 at 08 36 56](https://user-images.githubusercontent.com/38500953/211490251-b4bffab8-a993-4b57-b1f3-7331d5e35277.png)

![Screenshot 2023-01-10 at 08 36 59](https://user-images.githubusercontent.com/38500953/211490246-704fcf5f-ec71-4a1f-81c9-a3a2f3f0b772.png)

**Comment by hongfeiy63** [comment]
Dear Simmon and Julius,
Many thanks for your help. I followed the guidline in the picture you emailed me and write the following sentence. In my multigroup CFA, variable PCM02 has 5 categories (1-2-3-4-5). Category 1 is empty in Group 1.  Would you pls tell me if the sentence is correct and how to put it in JASP. Many thanks !



myData$PCM02.collapsed <- ifelse (myData$ PCM02 == 1, yes = 2, no = myData$PCM02)
















At 2023-01-10 15:38:36, "Julius Pfadt" ***@***.***> wrote:

You should thank Simon :) Here are two screenshots of the website you can't open.

**Comment by juliuspf** [comment]
To be honest, the computeColumn functionality is a but buggy for me at the moment. 
So the data you have is actually coded 1-5 for the categories "not at all" to "fully". What should work is to compute a new column with R code. For each variable that is affected by the error you need to create a new column. For instance for PCM02, the following code should have worked. 
```r
ifelse(PMC02 == 1, 2, PCM02)
```
However, using the zipped .jasp file you sent, where data is ordinal and labelled, the computing does not produce the required result. Any ideas @Kucharssim? 
What has worked for me is saving the data as a .csv file 
[A1.csv](https://github.com/jasp-stats/jasp-issues/files/10434368/A1.csv)
and then reading in the csv file, change the column types of the used variables to ordinal but not labelling the variables., change the type of the grouping variable to nominal
![Screenshot 2023-01-17 at 12 19 46](https://user-images.githubusercontent.com/38500953/212886123-cc886d40-58c2-425b-ba19-e4d99dd4a66d.png)

Following that procedure for each variable and working within the non-labelled data set, the collapsing has worked for me. Then you can use the CFA again and fit your model.

**Comment by hongfeiy63** [comment]
Many many thanks! I opened A1.CSV. But I do not know how to get in the "Computed Column"
WOuld you pls tell where to click?
Sorry for my ignorance!
Best,
Hongfei Yang












At 2023-01-17 19:20:47, "Julius Pfadt" ***@***.***> wrote:

To be honest, the computeColumn functionality is a but buggy for me at the moment.
So the data you have is actually coded 1-5 for the categories "not at all" to "fully". What should work is to compute a new column with R code. For each variable that is affected by the error you need to create a new column. For instance for PCM02, the following code should have worked.

ifelse(PMC02==1, 2, PCM02)

However, using the zipped .jasp file you sent, where data is ordinal and labelled, the computing does not produce the required result. Any ideas @Kucharssim?
What has worked for me is saving the data as a .csv file
A1.csv
and then reading in the csv file, change the column types of the used variables to ordinal but not labelling the variables., change the type of the grouping variable to nominal


Following that procedure for each variable and working within the non-labelled data set, the collapsing has worked for me. Then you can use the CFA again and fit your model.

**Comment by juliuspf** [comment]
see here: https://jasp-stats.org/2018/12/18/how-to-compute-columns-in-jasp/

**Comment by hongfeiy63** [comment]
Many thanks. I did. But the result is as follows. How to deal with it ?
















在 2023-02-01 19:37:18，"Julius Pfadt" ***@***.***> 写道：

see here: https://jasp-stats.org/2018/12/18/how-to-compute-columns-in-jasp/

**Comment by juliuspf** [comment]
something went wrong with the attachment, you need to properly attach something on this website.

**Comment by hongfeiy63** [comment]
What do you mean by attackment? How to attach what is needed?
Many thank.
















At 2023-02-01 20:16:04, "Julius Pfadt" ***@***.***> wrote:

something went wrong with the attachment, you need to properly attach something on this website.

**Comment by juliuspf** [comment]
> Many thanks. I did. But the result is as follows. How to deal with it ? 

I cannot see what the result is, which means I do not know what is going wrong. So you either need to tell me in descriptive terms or you upload a screenshot, which only works if you upload it to this website.

**Comment by boutinb** [comment]
Hi @hongfeiy63, I think the problem is that you answer directly from your email: you should use directly GitHub to attach images.

**Comment by juliuspf** [comment]
I am sorry, if you want to attach something, you cannot answer via e-mail, but you have to reply in the reply-window on the website. Since that seems to be impossible for you, I suggest to send the attachment to me via email, which is Julius.pfadt(at)gmail.com

**Comment by juliuspf** [comment]
![Picture 1](https://user-images.githubusercontent.com/38500953/216270633-1d85d37b-2364-4dff-8c51-0b708725432a.png)

So this is the picture. It is my bad, since the code I uploaded contains a spelling mistake. It should be 
```r
ifelse(PCM02 == 1, 2, PCM02)
```

**Comment by hongfeiy63** [comment]
Many thanks.
But nothing happs when I click "Compute column". Pls see the attached. 
What shall I do next?
Thanks for your patience!
Best,
Hongfei
















At 2023-02-02 16:26:19, "Julius Pfadt" ***@***.***> wrote:

So this is the picture. It is my bad, since the code I uploaded contains a spelling mistake. It should be

ifelse(PCM02==1, 2, PCM02)

**Comment by juliuspf** [comment]
Again, there will be no attachment shown if you communicate via email to the GitHub website. If you have attachments, use my email address. If you do not manage, I cannot help you, and I also cannot continue to repeat myself.

**Comment by juliuspfadt** [comment]
I think this is mostly solved, through email.
