### ISSUE TITLE
[Feature Request]: unable to install 

### ISSUE THREAD

**Issue by kwillliams09** [jasp-stats/jasp-issues#1959]
### Description

I've tried 5 times now to install JASP on my laptop and it will not work.

### Purpose

College Course Requirement

### Is your feature request related to a problem?

If the software is installing correctly, I have no idea how to operate it; but I do not think it's installing correctly. 

### Is your feature request related to a JASP module?

Unrelated

### Describe the solution you would like

I need guidance on how to install and operate this software as I feel like I will fail my course due to not even remotely understanding this. 

### Describe alternatives that you have considered

I have deleted all attempts after failure, I've restarted my computer also. 

### Additional context

![Screenshot 2023-01-10 8 08 13 PM](https://user-images.githubusercontent.com/122418257/211702739-dc7b9180-15c9-4c80-a727-bebbaed1ce31.png)

This is what it shows me after it's "done" installing. I have not seen the screen shown in the step-by-step guide. I also do not know if I'm doing something wrong, or just do not understand the software. I have never coded a computer before. I am extremely terrified that I won't be able to get this to work and fail my course, and it is a graduation requirement. Any help is greatly appreciated. Thank you.

**Comment by shun2wang** [comment]
Hi @kwillliams09 Could you open [here](https://github.com/jasp-stats/jasp-issues/issues/new?assignees=&labels=Bug&template=bug-report.yml&title=%5BBug%5D%3A+) and make a Bug report ? because this seems not a Feature and some necessary information needs you provide there.  

I will close it, please open another bug issue, thanks.
