### ISSUE TITLE
[Bug]: JASP WON'T OPEN ON MY MAC

### ISSUE THREAD

**Issue by lindsaylaurenne** [jasp-stats/jasp-issues#1962]
### JASP Version

0.16.4

### JASP Module

Unrelated

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

Hi the program won't open on my mac. It says this software isn't supported. I have an old version from 2018 installed that works fine. And I wanted to update it. Can I not have two versions at once?

Please help as I would like to use the newest one! 

I have a Mac version 11.6.8 with a 3.1 GHz Quad-Core Intel Core i7

### Expected Behaviour

Program should open

### Steps to Reproduce

1.
2.
3.
...
Help

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by lindsaylaurenne** [comment]
[]
<img width="335" alt="Screen Shot 2023-01-11 at 12 33 40 PM" src="https://user-images.githubusercontent.com/122453007/211807369-4b3f5bcb-def6-4af7-a891-971611a10fc5.png">
(url)

**Comment by shun2wang** [comment]
Hi @lindsaylaurenne I guessing your Mac use intel chip but not M1/M2 Silicon right? so you should choose the 'Intel' on the [download page](https://jasp-stats.org/download/) to download the install package.

![image](https://user-images.githubusercontent.com/10348402/211955438-9c17b7fc-3d90-4e5f-8589-fddabef9e08d.png)

Also you may check OS version(>10.13) if it is >10.13 , more install guide please refer [here](https://jasp-stats.org/installation-guide/).
