### ISSUE TITLE
[Bug]: Issue installation JASP, black screen.

### ISSUE THREAD

**Issue by MariaSua** [jasp-stats/jasp-issues#1963]
### JASP Version

0.16.4

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 10

### Bug Description

![image](https://user-images.githubusercontent.com/122473116/211888624-b99f9009-4022-447c-a3c4-a5fcdf9e3d4c.png)

### Expected Behaviour

To work.

### Steps to Reproduce

1. Installed
2. Open the app.
3. Doesn't work.
4.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @MariaSua 
Could just start JASP from the command line? For this:

- Start a command prompt by typing `command prompt` in the Start menu.
- Type `"c:\Program Files (x86)\JASP\JASP.exe" > log1.txt` to start JASP. (if JASP is installed in c:\Program Files (x86), if installed somewhere else, change the path to JASP.exe)
- Check whether JASP starts or not.
- If you have the same problem, type `"c:\Program Files (x86)\JASP\JASP.exe --safeGraphics" > log1.txt`
- Type 'notepad log1.txt' or notepad log2.txt to see the log file.
- Send me these log files in a comment of this GitHub issue.

**Comment by MariaSua** [comment]
Hi I did it. The first step open the application with the same issue but the second one doesn't work. Attached are the log files. Thank you.
[log1.txt](https://github.com/jasp-stats/jasp-issues/files/10401638/log1.txt)
[log 2.txt](https://github.com/jasp-stats/jasp-issues/files/10401639/log.2.txt)

**Comment by boutinb** [comment]
Hi @MariaSua I have made a mistake. Could you type:
`"c:\Program Files (x86)\JASP\JASP.exe" --safeGraphics` instead?
Can you tell me what you see?

**Comment by MariaSua** [comment]
Hi, I did it and it works. 
![image](https://user-images.githubusercontent.com/122473116/212374289-5b31c1f4-8c53-4fdc-8447-4e7167296975.png)
Is there a way to open the app without this step on command prompt?

**Comment by boutinb** [comment]
The safeGraphics setting should be set automatically now the next time you start JASP. Can you start JASP now by double-clicking its icon?

**Comment by MariaSua** [comment]
Hi, yeah. The app is working now. Thanks.
