### ISSUE TITLE
Error installing Jasp on W10 and W11[Bug]: 

### ISSUE THREAD

**Issue by Matdu13** [jasp-stats/jasp-issues#1964]
### JASP Version

0.16.4

### JASP Module

Other Module

### What analysis are you seeing the problem on?

on installation

### What OS are you seeing the problem on?

Windows 11

### Bug Description

I try to install Jasp on W10 and W11 with the installer JASP-0.16.4-64bit, i have  this message :
![image](https://user-images.githubusercontent.com/15792945/211947572-b30b255b-3b52-4edc-8b6f-74bc2fd83e9a.png)

i try also to install jasp by unpacking JASP-0.16.4-64bit.zip and start Jasp.exe in admin, in this case i have this message :  MF.dll missing ... and after closing MfReadWrite.dll is missing

i have already read old post on problem installation where i see the zip solution.
What could i do ?
[Jasp instal problem.docx](https://github.com/jasp-stats/jasp-issues/files/10397115/Jasp.instal.problem.docx)

### Expected Behaviour

i run the installer and, near the end of installation i have this error 

### Steps to Reproduce

1.click on JASP-0.16.4-64bit

2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JorisGoosen** [comment]
@Matdu13 can you test https://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-stable-ab1199a0dcca7fbfa773b87fd970e202d2d5b61c.msi ?

**Comment by Matdu13** [comment]
Thanks a lot, this file permit a normal installation on w11 without been admin, but avast antivirus says it's dangerous,
Problem solved, a new time thank's a lot

**Comment by boutinb** [comment]
Just a warning: the version you have now is a beta version. Over few days, we should release the 0.17 official version.
The beta version is not "signed", that means that Microsoft does not recognize it as safe, that's why you get this warning. The official version will be 'signed', and you should not get this warning anymore.
