### ISSUE TITLE
[Bug]: SEM - Latent Growth Curve only allow 10/11 variables into variables box

### ISSUE THREAD

**Issue by Emily0502** [jasp-stats/jasp-issues#1967]
### JASP Version

0.16.3

### JASP Module

SEM

### What analysis are you seeing the problem on?

Latent Growth Curve will only allow me to input 10/11 variables in to variables box. When I try to add one more, i get the following message: This analysis terminated unexpectedly.  Error in if (lgcmResult@test[[1]]$df < 0) {: missing value where TRUE/FALSE needed  Stack trace  To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

### What OS are you seeing the problem on?

Windows 10

### Bug Description

Latent Growth Curve will only allow me to input 10/11 variables in to variables box. When I try to add one more, i get the following message: 
This analysis terminated unexpectedly.  Error in if (lgcmResult@test[[1]]$df < 0) {: missing value where TRUE/FALSE needed  Stack trace  To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

### Expected Behaviour

Latent Growth Curve will only allow me to input 10/11 variables in to variables box. When I try to add one more, i get the following message: This analysis terminated unexpectedly.  Error in if (lgcmResult@test[[1]]$df < 0) {: missing value where TRUE/FALSE needed  Stack trace  To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

### Steps to Reproduce

1. Descriptives (scale data)
2. Latent growth 
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by LSLindeloo** [comment]
Hi @Emily0502, 

thanks for reporting this bug. I would like to look into the issue. Could you provide me with the dataset that you used and the variables you included? You can include the dataset here or (if you don't want the dataset to be publicly available) send it to lorenzolindeloo@gmail.com. I will only use the dataset to fix the bug and it will be deleted afterwards.
Thanks in advance!

Lorenzo

**Comment by tomtomme** [comment]
@Emily0502 
I tested this with jasp 0.18.3 and could much more than 11 variables.
Feel free to reopen if you can share your data and find that this is still not fixed on your side.
Thx
