### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Coacheltaylor** [jasp-stats/jasp-issues#1968]
### JASP Version

0.16.4

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 11

### Bug Description

I downloaded Jasp and the ds5_spss_file a file that Capella requires in one of our classes. I can find them when I search my computer Download folder however whenever i use Jasp to find the file they don't show up in any of the folders i place them in. I can find it from my laptop folders but not while using Jasp. I can use the Search box while in JASP but whenever I click the file in the Search box it shows there is no items that match my search. Below I attached the file Capella sent that I can't find but I also attached two screeshots. One showing The Capstone Project references file from my computer wiith items in the folder and the other pic shows me looking in that same folder from JASP and there not being any items in the file. Any suggestions as to why this is happening? Thank you

[ds5_spss_files (3).zip](https://github.com/jasp-stats/jasp-issues/files/10403143/ds5_spss_files.3.zip)

![image1](https://user-images.githubusercontent.com/122470065/212109365-07423480-79f8-4bf4-bd85-a3007d292c02.jpeg)

![image0 (1)](https://user-images.githubusercontent.com/122470065/212109574-a31941f8-cf75-483f-8526-2237e3f98666.jpeg)

### Expected Behaviour

When I open JASP and Browse for downloaded files they should show up in the folder I placed them in. 

### Steps to Reproduce

1. Download a file
2. Open JASP & Browse
3. Search for file and it's not there
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @Coacheltaylor , in your sceenshot, there is a zip file, but you should first unzip this file.
If I do that, I can see the sav files:
<img width="773" alt="Screenshot 2023-01-13 at 10 33 31" src="https://user-images.githubusercontent.com/503332/212286676-e01037f6-1bac-48cd-8319-e042a83b8c2f.png">

**Comment by tomtomme** [comment]
@Coacheltaylor 
I hope you managed to unzip the file and open the individual jasp files. If not, feel free to reopen.
