### ISSUE TITLE
[Bug]: Not able to save trained models

### ISSUE THREAD

**Issue by Darius-bit** [jasp-stats/jasp-issues#1972]
### JASP Version

0.16.4

### JASP Module

Machine Learning

### What analysis are you seeing the problem on?

Classification

### What OS are you seeing the problem on?

Windows 11

### Bug Description

This analysis terminated unexpectedly.

Error in str2lang(x): :1:35: unexpected symbol
1: Inhibitors ~ fsTer + CDS_position start
                                      ^

Stack trace
doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

mlClassificationDecisionTree(...)

.mlClassificationTabl
[data.zip](https://github.com/jasp-stats/jasp-issues/files/10466062/data.zip)
eSummary(dataset, options, jaspResults, ready, position = 1, type = 'rpart')

.decodeJaspMLobject(model)

.decodeJaspMLobject.rpart(model)

formula(paste(decodeColNames(as.character(model$terms)[2]), '~', paste0(decodeColNames(strsplit(as.character(model$terms)[3], split = ' + ', fixed = TRUE)[[1]]), collapse =
[data.zip](https://github.com/jasp-stats/jasp-issues/files/10466035/data.zip)
 ' + ')))

formula.character(paste(decodeColNames(as.character(model$terms)[2]), '~', paste0(decodeColNames(strsplit(as.character(model$terms)[3], split = ' + ', fixed = TRUE)[[1]]), collapse = ' + ')))

str2lang(x)

### Expected Behaviour

I used Jasp to develop machine algorithms to predict some classes (Classification problems). However when I am trying to save the trained models, I am not able to save the,

Jasp should save the trained models in the specified folder

### Steps to Reproduce

1. Loaded my data
2. Trained different models using Classification algorithms
3. Save/export the trained models

### Log (if any)

This analysis terminated unexpectedly.

Error in str2lang(x): :1:35: unexpected symbol
1: Inhibitors ~ fsTer + CDS_position start
                                      ^

Stack trace
doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

mlClassificationDecisionTree(...)

.mlClassificationTableSummary(dataset, options, jaspResults, ready, position = 1, type = 'rpart')

.decodeJaspMLobject(model)

.decodeJaspMLobject.rpart(model)

formula(paste(decodeColNames(as.character(model$terms)[2]), '~', paste0(decodeColNames(strsplit(as.character(model$terms)[3], split = ' + ', fixed = TRUE)[[1]]), collapse = ' + ')))

formula.character(paste(decodeColNames(as.character(model$terms)[2]), '~', paste0(decodeColNames(strsplit(as.character(model$terms)[3], split = ' + ', fixed = TRUE)[[1]]), collapse = ' + ')))

str2lang(x)

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by koenderks** [comment]
This is a known issue and related to https://github.com/jasp-stats/jaspMachineLearning/issues/158. 

The solution (for now) is to remove the _ sign and any spaces in your variable name(s).

Let me know if that works!

**Comment by Darius-bit** [comment]
Hi,
it is working now.
However, for some other reason, I got another error.
Please find in attachment the JASP file as well as the starting data

Error in str2lang(x): :1:41: unexpected symbol
1: Inhibitors ~ cDNAstart + stop + cadd + 4nucl
                                            ^

Stack trace
doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset =
dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

mlClassificationDecisionTree(...)

.mlClassificationTableSummary(dataset, options, jaspResults, ready,
position = 1, type = 'rpart')

.decodeJaspMLobject(model)

.decodeJaspMLobject.rpart(model)

formula(paste(decodeColNames(as.character(model$terms)[2]), '~',
paste0(decodeColNames(strsplit(as.character(model$terms)[3], split = ' + ',
fixed = TRUE)[[1]]), collapse = ' + ')))

formula.character(paste(decodeColNames(as.character(model$terms)[2]), '~',
paste0(decodeColNames(strsplit(as.character(model$terms)[3], split = ' + ',
fixed = TRUE)[[1]]), collapse = ' + ')))

str2lang(x)






Il giorno ven 20 gen 2023 alle ore 14:31 Koen Derks <
***@***.***> ha scritto:

**Comment by koenderks** [comment]
I would have to look into this further to give a definitive answer. 

One thing you could do is try and remove the 4 in your variable name, this might be the same issue as before but maybe JASP also does not handle number in variable names correctly. Could you try to change the names to something without _, spaces and numbers and let me know if that changes anything?

**Comment by tomtomme** [comment]
Tested with the provided jasp file in jasp 0.18.3. Worked all fine, even with spaces and _ signs.
@Darius-bit 
Feel free to reopen, if not fixed on your side.
