### ISSUE TITLE
[Feature Request]: SEM Sensitivity Analysis

### ISSUE THREAD

**Issue by kyle-hickerson** [jasp-stats/jasp-issues#1973]
### Description

Sensitivity analysis for SEM using the semsen package can be used to detect the effects of ommitted variable bias in lavaan objects.

### Purpose

To detect omitted variable bias in SEM models.

### Use-case

Researchers examining their model robustness to potential omitted confounding variables. 

### Is your feature request related to a problem?

No.

### Is your feature request related to a JASP module?

SEM

### Describe the solution you would like

Implmentation of the semsen package in jasp

### Describe alternatives that you have considered

I don't believe alternative packages exist for sensitivity analysis of lavaan objects.

**Comment by tomtomme** [comment]
@apoiraud
This is a reasonable request and there is already a patch in the pipeline for this.

@juliuspfadt 
Can you rebase the patch from LSLindeloo or is this more work than it seems?
