### ISSUE TITLE
[Bug]: JASP is 64Bit; but is installing under [[Program Files (x86)]] instead of [[Program Files]]

### ISSUE THREAD

**Issue by Ghassan-Okour** [jasp-stats/jasp-issues#1974]
### JASP Version

0.16.4

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

Unrelated

### What OS are you seeing the problem on?

Windows 11

### Bug Description

![image](https://user-images.githubusercontent.com/115344297/213862050-999450af-37ae-4071-988b-b48f2646b4d0.png)

### Expected Behaviour

C:\Program Files\JASP
NOT: C:\Program Files (x86)\JASP

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by Ghassan-Okour** [comment]
Thanks for your help...

**Comment by boutinb** [comment]
Hmm, it does not work as I thought...

**Comment by Ghassan-Okour** [comment]
> Hmm, it does not work as I thought...

Good morning,
I just wonder when the team of JASP will solve this issue!!!
Best Regards for whole of you...

**Comment by boutinb** [comment]
I'm afraid not... Several promising attempts did not succeed.

**Comment by Ghassan-Okour** [comment]
@boutinb 
Are there any new news about this issue?
Best Regards...

**Comment by boutinb** [comment]
We will switch to msix file, and we have seen that it solves this problem. So probable this will be solved for the next release.
