### ISSUE TITLE
[Feature Request]: Please Install all R tidyverse packages

### ISSUE THREAD

**Issue by phish108** [jasp-stats/jasp-issues#1975]
### Description

The tidyverse comes with several very useful packages for data wrangling, which are missing

### Purpose

Better data wrangling support

### Use-case

Sometimes it is needed to prepare or reorganise the data in ways that are not available in the UI

### Is your feature request related to a problem?

Sometimes the data needs to be reorganised or prepared, before the analysis can be run. It would be nice, to enter some data wrangling code in R directly, before running the analysis. Currently, many important features are missing, such as forcats :( 

### Is your feature request related to a JASP module?

Unrelated

### Describe the solution you would like

It would be sufficient, if the tidyverse package is fully installed. 

### Describe alternatives that you have considered

I could not find smart alternatives for factor organisation in the UI.

**Comment by JorisGoosen** [comment]
Related to https://github.com/jasp-stats/jasp-issues/issues/33 and https://github.com/orgs/jasp-stats/projects/20

**Comment by tomtomme** [comment]
@phish108 
Here is our list of included R-Packages. Can you say more precisely which are missing?

**Comment by phish108** [comment]
This is pretty long ago but in the issue it states:

- the `tidyverse` is/was only partially installed at the time of testing.

- I checked only the `forcats` package at the time, which was missing despite of being part of the core `tidyverse` for many years. I suppose that some of the other packages were also not included.

For basic data wrangling the latest `tidyverse` packages would be a super convenient escape route for satisfying some specialized data requirements.

**Comment by tomtomme** [comment]
@phish108 
sry, I just now added the link to our R package list. 
I also googled this list: https://www.rdocumentation.org/packages/tidyverse/versions/2.0.0 
and checked that all those are in the R package list of JASP
Since all packages are included now I am closing this one.
Feel free to reopen if you still miss something.
