### ISSUE TITLE
[Feature Request]: Add Network Meta Analysis to Meta-Analysis Module

### ISSUE THREAD

**Issue by renespijker** [jasp-stats/jasp-issues#1978]
### Description

network meta analysis

### Purpose

to perform network meta analysis for systematic reviews

### Use-case

when comparing multiple treatments for a certain disease you would like to compare the effectiveness but not always have the opportunity to have direct comparisons

### Is your feature request related to a JASP module?

Cochrane, Meta Analysis

### Describe the solution you would like

have the function added to the meta analysis component is jasp 

### Describe alternatives that you have considered

you can find description of the feature here: https://methods.cochrane.org/cmi/network-meta-analysis with solutions for R etc.

**Comment by FBartos** [comment]
Hi, this is a great suggestion for improving the meta-analysis module. We would be happy to implement it, although it is unfortunately at the top of our priorities right now.

**Comment by tomtomme** [comment]
@renespijker 
This one (https://github.com/jasp-stats/jasp-issues/issues/2067) seems closely related, but it does not seem to be a real duplicate. Can you confirm?

**Comment by tomtomme** [comment]
@renespijker 
This one https://github.com/jasp-stats/jasp-issues/issues/1646 is a duplicate that predates your issue. Lets discusse there.
Please reopen, if you disagree!

**Comment by renespijker** [comment]
> @renespijker This one (#2067) seems closely related, but it does not seem to be a real duplicate. Can you confirm?

This one is not a duplicate

**Comment by renespijker** [comment]
> @renespijker This one #1646 is a duplicate that predates your issue. Lets discusse there. Please reopen, if you disagree!

agree
