### ISSUE TITLE
[Bug]: gression or factor cannot be added in Latent Growth

### ISSUE THREAD

**Issue by areeq1** [jasp-stats/jasp-issues#1979]
### JASP Version

0.16.4

### Commit ID

e5371ca8eb112816cd6b4ea47d9330617df21f67

### JASP Module

SEM

### What analysis are you seeing the problem on?

Latent Growth Curve

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

Hi, the Latent Growth Curve analysis works OK, but when a regression or factor is added then it crashes.
![Screen Shot 2023-01-25 at 4 30 03 pm](https://user-images.githubusercontent.com/68887104/214576833-e31865b0-a8b3-4ae4-a250-550bc8cd0c70.jpg)

### Expected Behaviour

An error message will pop up

### Steps to Reproduce

1. adding regression or factor to the analysis
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [x] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by LSLindeloo** [comment]
Hi @areeq1, 

Have you tried to switch "missing value handling" to "exclude cases listwise"? It seems there is a bug in the lavaan package when missing = "fiml" and regressions or factors are added, even if there are no missing values in the dataset. I will try to figure out a workaround for this as soon as I can! :)
Hope this also works for your specific case, It would be great if you would let me know! 

Best,

LSLindeloo

**Comment by areeq1** [comment]
Hi @LSLindeloo I tried. In a previous version, this would work but now it is not working anymore. Can you please fix that? It is important in any LGC model to use covariates. Please help us

**Comment by tomtomme** [comment]
@areeq1 
This seems to be a duplicate or at least closely related to https://github.com/jasp-stats/jasp-issues/issues/2510
Lets discuss there, if you can still replicate or get different error messages with current jasp, please post them in 2510
Feel free to reopen, if this is a different issue!
Whatever it is, we sure need more help in testing LGCM!

related issues
#2212
#2076
#2032
#2002
#1774
