### ISSUE TITLE
[Feature Request]: PLS-SEM to have VIF, HTMT, AVE, other measures...

### ISSUE THREAD

**Issue by areeq1** [jasp-stats/jasp-issues#1982]
### Description

The package seems to work but, thanks! I suggest adding VIF and possibly HTMT to assess the collinearity and discriminant validity. Much appreciated

### Purpose

collinearity and discriminant validity

### Is your feature request related to a problem?

No

### Is your feature request related to a JASP module?

Other

### Describe the solution you would like

add an option to get these measures

**Comment by juliuspfadt** [comment]
also requested here: https://forum.cogsci.nl/discussion/8935/assessing-measurement-model-when-using-pls-sem

**Comment by juliuspfadt** [comment]
see also https://github.com/jasp-stats/jasp-issues/issues/2089

**Comment by tomtomme** [comment]
closing as duplicate of https://github.com/jasp-stats/jasp-issues/issues/2089
