### ISSUE TITLE
[Bug]: No error bars displayed when running a 2-way ANOVA

### ISSUE THREAD

**Issue by PerPalmgren** [jasp-stats/jasp-issues#1983]
### JASP Version

0.17.0

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

Descriptive plots

### What OS are you seeing the problem on?

Windows 10

### Bug Description

In JASP 0.17 when running a 2-way ANOVA using "Descriptive Plots", and ticking "Display error bars" (choosing Confidence intervals) these are not shown (see image below). However, when instead choosing Standard error these are displayed and after I can re-select Confidence intervals and they are now displayed. However, after the dynamic updating freezes and when de-selecting "Display error bars" these still remains and are not removed. This is a problematic bug!
![Namnlös](https://user-images.githubusercontent.com/79397662/215110170-bce9af17-7636-4140-8f67-c4baa2a375bc.png)

### Expected Behaviour

The tick boxes should and the dynamic updating should work.

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
This is unfortunate, but an easy workaround is just to click another option: specify temporary another confidence interval, or change it to Standard error.
A fix is already done, and will be in the next version.
