### ISSUE TITLE
[Bug]: Logistic Regression Footnote message

### ISSUE THREAD

**Issue by KelvinBalcombe** [jasp-stats/jasp-issues#1984]
### JASP Version

0.17.0

### JASP Module

Regression

### What analysis are you seeing the problem on?

logistic regression

### What OS are you seeing the problem on?

Windows 10

### Bug Description

error message

### Expected Behaviour

Using Firth Logistic Regression should not then create a footnote message when using logistic regression

### Steps to Reproduce

1. Call up the titanic data from the data library under regression
2. Run a logistic regression of Survived on Age (this should work) 
3. Choose a Firth Logistic Regression from the Generalised Linear Model, and run the same model above (this should work)
4. Now repeat a new version of step 2. Above the coefficients table there is a warning saying JASPTable$addFootnote ... that obscures the output

### Log (if any)

None

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
A compressed (zipped) .jasp file of your issue would be more than welcome!

**Comment by tomtomme** [comment]
@boutinb & @KelvinBalcombe 
Kelvin provided a jasp file by pointing to the titanic data from our library. With this I can reproduce this indeed very weird error that depends on the order of analysis you do. I attached the jasp file containing the analysis and the error message that were precisely given by Kelvin. Sorry for not following up earlier on this!
[Titanic.zip](https://github.com/jasp-stats/jasp-issues/files/14157844/Titanic.zip)

**Comment by tomtomme** [comment]
@fqixiang 
Are you still working on jasp issues? 
If not I would try to reassign them.

**Comment by fqixiang** [comment]
Hi Thomas, I'm not atm. I would have some time in May/June, but that's
probably too late.

Qixiang

**Comment by tomtomme** [comment]
@fqixiang 
Would you prefer to stay assigned to those issues then? Or do you want to see which ones you want to tackle, when you have time?

**Comment by fqixiang** [comment]
@Thomas,
let me have a look and unassign myself from those I don't think I will have
time for.

**Comment by tomtomme** [comment]
tested and still valid for latest 0.19 beta

**Comment by JorisGoosen** [comment]
Somehow something gets stuck somewhere between 2 analyses running on the same engine but I have no idea where...

You can see by opening the engine-window (Ctrl/Cmd+Alt+Shift+E) en then killing it by pressing right/middle-mouse button.
Rerunning the analysis then works.... Until you run the generalized one once more...

Definitely something strange going on and I would like to know what is going wrong here. But at least @JohnnyDoorn has a fix.

**Comment by tomtomme** [comment]
I tried verifiing that this one is fixed but it seems module logistic regression is now completely broken:
![grafik](https://github.com/jasp-stats/jasp-issues/assets/4428185/f5cd6fa2-672b-4284-9561-bd1e2ae4f2fc)

**Comment by JohnnyDoorn** [comment]
Yes, this is now fixed, thanks for checking
