### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by deborahira** [jasp-stats/jasp-issues#1985]
### JASP Version

Others

### JASP Module

Bsts

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

a bug happend 

### Expected Behaviour

this is not working

### Steps to Reproduce

1.no
2.no
3.no
...

### Log (if any)

this is not working 

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by deborahira** [comment]
is not working.

**Comment by deborahira** [comment]
t

**Comment by vandenman** [comment]
@deborahira what is not working *exactly*? It is impossible for me to see what is happening on your screen. Without further information, it is very difficult to figure out what goes wrong. Could you be more descriptive about the bug you experience?

**Comment by deborahira** [comment]
When I open up the app it says jasp has experienced unexpected internal
error

**Comment by boutinb** [comment]
Hi @deborahira This is too little information for us. Could you give us the log files: https://github.com/jasp-stats/jasp-desktop/blob/stable/Docs/user-guide/logging-howto.md ?
