### ISSUE TITLE
jasp needs closing internet connect to start  

### ISSUE THREAD

**Issue by drhosini** [jasp-stats/jasp-issues#1986]
### JASP Version

0.17.0

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 10

### Bug Description

jasp needs closing internet connect to start  

### Expected Behaviour

jasp needs closing internet connect to start  

### Steps to Reproduce

1.
2.
3.
...
even the zipped file had the same problem

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by drhosini** [comment]
the program just opens and closes immediately except when cutting the internet

**Comment by boutinb** [comment]
Hi @drhosini Did you close this issue by mistake? If yes, reopen it, and then could you start JASP from the command line, by typing: "c:\Program Files (x86)\JASP\JASP.exe". Do you get some information from the command line?

**Comment by drhosini** [comment]
Yes closed by mistake.  The same issue remains when Jasp started from command line? It opens and closes immediately

**Comment by shun2wang** [comment]
Well I have this problem too. 

when I find in logs or try to build on my PC, I can see this error:

```
Uncaught std::exception! Was: Module version not understood: <html>
<head>
<meta http-equiv='refresh' content='1; url=http://static.jasp-stats.org/JASP-Version.txt?cmd=redirect&arubalp=12345'>
</head>
</html>
```
maybe from [here](https://github.com/jasp-stats/jasp-desktop/blob/8ff70d7f7a140c9996c4070e84fa2043b9e7b652/Desktop/gui/jaspversionchecker.h#L50-L52) and when I access "http://static.jasp-stats.org/JASP-Version.txt" it tell` 0.16.4` but not `0.17.0`?

may also worth noting to https://github.com/jasp-stats/jasp-issues/issues/1880

**Comment by JorisGoosen** [comment]
@drhosini are you behind a proxy?

**Comment by JorisGoosen** [comment]
@boutinb wanted to wait until we maybe bring out  hotfix for updating JASP-Version.txt
