### ISSUE TITLE
[Bug]: Repeated measures ANOVA does not run

### ISSUE THREAD

**Issue by jasonckchan** [jasp-stats/jasp-issues#1987]
### JASP Version

0.17.0

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

repeated measures ANOVA

### What OS are you seeing the problem on?

macOS Intel, macOS Silicon

### Bug Description

After selecting the variables involved in a RM ANOVA, the tables pop up but no results are shown.  This happens on both the Intel and Apple Silicon version of the application.  No such issues on 16.4.  I only noticed it on 17.  The issue is replicable and can be demonstrated on different Macs even after an uninstall and reinstall.

### Expected Behaviour

Data should appear on the tables.

### Steps to Reproduce

1. ANOVA
2. Repeated Measures ANOVA
3. Select variables for analysis

Note bottom of screenshot shows a non-RM ANOVA, which runs properly.
...
<img width="1326" alt="Screen Shot 2023-01-30 at 8 44 44 AMGMT-6" src="https://user-images.githubusercontent.com/78377371/215508828-5b52a973-7151-44bc-82c5-8485734da03a.png">

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JohnnyDoorn** [comment]
Hi @jasonckchan ,

Could you attach a jasp file (you can save your file as a ".jasp" and then change the extension to ".zip" to be able to upload it to github. Then I can try to reproduce your issue, because so far I have no issues with the RM ANOVA.

Kind regards
Johnny

**Comment by jasonckchan** [comment]
Here you go, Johnny.  Thanks for looking into it!

Jason

**Comment by JohnnyDoorn** [comment]
Hi @jasonckchan ,

Something seemed to have gone wrong with the attachment - you can also send it to johnnydoorn <at> gmail <dot> com

Cheers
Johnny

**Comment by boutinb** [comment]
@JohnnyDoorn You can reproduce this issue with any dataset: if you have only 1 factor, even if the Repeated Measures cell are filled with variables, no table is displayed. In 0.16.4, a table was displayed.

**Comment by JohnnyDoorn** [comment]
Ah OK. @arandolan how did you not pick this up when testing the RM ANOVA? 
I am not sure what is causing this, as I didn't change anything for the last release. It could be a PR from @Kucharssim, or adding the wrappers @boutinb ?

**Comment by boutinb** [comment]
I have seen that the first factor is not set in the Model Terms per default:
![Screenshot 2023-01-30 at 16 44 20](https://user-images.githubusercontent.com/503332/215523891-0865cbcd-0eeb-4c90-9b45-0cfe93cb15f7.png)
@jasonckchan Could you add the Init_Acc factor to the Model Terms (if it is not yet set)?

**Comment by EJWagenmakers** [comment]
Also, how come this was not caught with our unit tests?

**Comment by vandenman** [comment]
@EJWagenmakers we do not have unit tests for QML, only for R (although there is an issue for this I think).

**Comment by arandolan** [comment]
@JohnnyDoorn sorry I'm not sure how I missed this - I will look into it but my initial guess is that it might be related to differences between nightlies that were pushed over the course of the testing phase; and/or the fact that I run Windows and not macOS.

**Comment by JohnnyDoorn** [comment]
Hi @arandolan, yes no worries, I misunderstood and it seemed that this was caused by a last-minute change by Bruno.

**Comment by boutinb** [comment]
@arandolan There were 2 issues here. One of them was that the default factor was not directly set as model term. This issue is new and caused by a last-minute change by me. So you could not find it during your testing. The second issue is an old one: changing the factor name removes it from the model term. Maybe tricky to see if already the first factor was already not set in the model terms.
This kind of issues should have automatic tests anyway.

**Comment by jasonckchan** [comment]
> I have seen that the first factor is not set in the Model Terms per default:
> ![Screenshot 2023-01-30 at 16 44 20](https://user-images.githubusercontent.com/503332/215523891-0865cbcd-0eeb-4c90-9b45-0cfe93cb15f7.png)
> @jasonckchan Could you add the Init_Acc factor to the Model Terms (if it is not yet set)?

It does work if I manually add the RM component to the model term.  Thank you.  I assume that this would be fixed in the next version?  I just think that this would confuse a lot of students.  :)

**Comment by EJWagenmakers** [comment]
We are considering a hot fix to resolve this issue
