### ISSUE TITLE
[Bug]: Regression Casewise Diagnostics table shows wrong case ID when having missing data in dependent variable

### ISSUE THREAD

**Issue by ProStatFFM** [jasp-stats/jasp-issues#1989]
### JASP Version

0.17.0

### JASP Module

Regression

### What analysis are you seeing the problem on?

Linear Regression

### What OS are you seeing the problem on?

Windows 11

### Bug Description

Hi,
I figured out that when calculating a linear regression and my depended variable has missing values, the case ID shown in the casewise diagnostics is wrong. I created an ID variable to show you more in the next section.

### Expected Behaviour

![jasp_0 17_bug](https://user-images.githubusercontent.com/98039393/215984914-630ee828-5d6b-4f85-9481-b2c686485497.png)
JASP is telling me that case ID (internal calculation of JASP) no. 14 is problematic in regression due to residuals. Case 14 has no value in my dependend variable "PR M TOTAL", so looking at the casewise diagnostics table, JASP should have told me no. 16 as the case which is problematic. This makes the table for casewise diagnostics completely useless since you can't filter correctly.

### Steps to Reproduce

1. Open the example dataset "Album sales". Look at the regression table "casewise diagnostics" with standardized residuals. Have a look at the case IDs. They are correct because the dependent variable has no missing.
2. Delete sales values in line 3 to 5. Again, have a look at the casewise diagnostics table. The case IDs have changed (after case 1 and 2) and now do not provide the correct line number in the dataset.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by EJWagenmakers** [comment]
This would be important to fix, team
