### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by alyssaperr** [jasp-stats/jasp-issues#1994]
### JASP Version

Others

### JASP Module

Descriptives

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

i don't know what happened i am just trying to do my work

### Expected Behaviour

need this fixed

### Steps to Reproduce

1.
2.
3.
...

please fix

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @alyssaperr We really need more information to be able to help you. You haven't answered the questions in the bug issue: which JASP version, a precise description step by step of what you do, a screenshot of the error...
