### ISSUE TITLE
update FAQ to reflect sytax mode

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#1998]
### JASP Version

0.17.0

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Other

### Bug Description

![Screenshot_20230208-075351](https://user-images.githubusercontent.com/4428185/217456456-3e6af793-f2d3-410d-9784-1cc4e0fb5d5b.png)

### Expected Behaviour

...

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by EJWagenmakers** [comment]
Yes, great point! We'll draft something.

**Comment by boutinb** [comment]
Updated! Thanks for paying attention
