### ISSUE TITLE
[Bug]: Latent Growth would not work with regression

### ISSUE THREAD

**Issue by areeq1** [jasp-stats/jasp-issues#2002]
### JASP Version

0.17.0

### Commit ID

1f51a10930b9c41bc73d48bd4a7afd62b3e5e36b

### JASP Module

Other Module

### What analysis are you seeing the problem on?

Latent Growth

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

When a regression is added to the Latent Growth analysis an error message pops up. Please fix that.
![Screenshot 2023-02-08 at 7 52 48 pm](https://user-images.githubusercontent.com/68887104/217598381-50e4f0ae-970e-42f9-8c2a-d1c0427f2b05.jpg)

### Expected Behaviour

Error message

### Steps to Reproduce

When a regression is added to the Latent Growth analysis an error message pops up. Please fix that.
![Screenshot 2023-02-08 at 7 52 48 pm](https://user-images.githubusercontent.com/68887104/217598381-50e4f0ae-970e-42f9-8c2a-d1c0427f2b05.jpg)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by Kucharssim** [comment]
Dear @areeq1,

thank you for reporting this issue. I think I can reproduce it, but I would like to make sure that it is indeed what you encounter. Is it possible for you to share your JASP file here on the GitHub issue (please make sure to zip it and upload it directly on the GitHub website, not send it by email as attachment)?

If that's not possible, could you please check for me if the error message disappears if you

1. Expand the "Advanced" section
2. Select "Exclude cases listwise"
3. Select "ML" estimator

Thank you.

**Comment by areeq1** [comment]
After selecting "Exclude cases listwise" it works. However, FIML is really needed in LGCM as missing values are expected. 
Also, it might be helpful to note that this worked in version 0.16.

**Comment by Kucharssim** [comment]
Thank you.

Yes, I indeed intend to fix it, I was just checking if I can reproduce the exact problem you reported, or if there are multiple issues that lead to the same error message :)

**Comment by areeq1** [comment]
Looking forward to the next nightly version (Mac silicon) then :)

**Comment by areeq1** [comment]
Anything done for this issue? It is still present.

**Comment by tomtomme** [comment]
@areeq1 
I think we have still problems with LGCM and could use your help in testing.
See also this issue: https://github.com/jasp-stats/jasp-issues/issues/2076

Can you test with current jasp 0.18.3 if you have problems when entering a var in regression or factor?
