### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by cindyptrns** [jasp-stats/jasp-issues#2004]
### JASP Version

0.17.0

### JASP Module

ANOVA, Descriptives, Regression, T-Tests

### What analysis are you seeing the problem on?

correlation, regression

### What OS are you seeing the problem on?

Windows 11

### Bug Description

![image](https://user-images.githubusercontent.com/124864243/217736999-8f4376b5-5323-4daf-b49f-828e84ccac05.png)

i can't continue this jasp

### Expected Behaviour

usually I can use this jasp application normally, but after being updated to version 0.17.0 it becomes unusable

### Steps to Reproduce

1.
2.
3.
...
i can't and don't understand how, please help

### Log (if any)

i need ur help to fix this please

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @cindyptrns Can you tell what you do exactly step by step? Do you open a JASP without file or do you double-click directly on a JASP file? Does the error happen only when you open a Linear Regression? If this happen with a JASP file, can you post this JASP file in this issue (rename it first as zip file)? Also could you send us the log files: https://github.com/jasp-stats/jasp-desktop/blob/stable/Docs/user-guide/logging-howto.md

**Comment by tomtomme** [comment]
@cindyptrns 
Feel free to reopen, if still not fixed on your side with jasp 0.18.3
