### ISSUE TITLE
[Feature Request]: Different filters for each analysis

### ISSUE THREAD

**Issue by ajestudillo** [jasp-stats/jasp-issues#2005]
### Description

filtering variables without overriding analysis

### Purpose

being able to filter specific variables without overriding previous analysis. This would allow to 

### Is your feature request related to a JASP module?

Unrelated

### Describe the solution you would like

being able to incorporate separate filters for each analysis

**Comment by juliuspfadt** [comment]
this is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/385. You may follow the updates there.
