### ISSUE TITLE
[Feature Request]: Allow standard deviation in bar plot with t-test

### ISSUE THREAD

**Issue by TBLeftHand** [jasp-stats/jasp-issues#2009]
### Description

After a t-test it is possible to show the bar plot with standard error, however it is not possible to display the standard deviation

### Purpose

standard deviation is a standard parameter and should be able to be shown in a graph

### Is your feature request related to a JASP module?

T-Tests

### Describe the solution you would like

Show standard deviation in bar plot

**Comment by tomtomme** [comment]
@TBLeftHand 
This is possible in jasps visual modeling module => flexplot
In the options you can choose SD.
Is this sufficient? I do not see why this is specifically needed within the t-Test.
Thx for your feedback. Cheers.
