### ISSUE TITLE
[Bug]: Unexpected internal error

### ISSUE THREAD

**Issue by SabrinaFeggins** [jasp-stats/jasp-issues#2013]
### JASP Version

0.17.0

### JASP Module

Reliability

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

This is the message that keeps coming up.  It happens each time I try to complete a task.
<img width="423" alt="Screen Shot 2023-02-12 at 5 02 18 PM" src="https://user-images.githubusercontent.com/125217064/218340068-bababc15-e120-4f2f-96e1-3808a4c964b6.png">

### Expected Behaviour

I should have been able to run a reliability test 

### Steps to Reproduce

1. I don't know
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment]
Hi @SabrinaFeggins, thanks for creating the issue. Is it possible for you to upload a zipped .jasp file that causes the error? Or alternatively upload the data set here?

**Comment by boutinb** [comment]
Hi @SabrinaFeggins. I cannot reproduce this problem. need to know what you exactly do: do you open JASP with a data file or with a JASP file, which analysis do you try to start, does the engine crash immediately when you start the analysis? I would need also the JASP logs:  https://github.com/jasp-stats/jasp-desktop/blob/stable/Docs/user-guide/logging-howto.md
