### ISSUE TITLE
[Bug]: Cannot open .jasp with space / blank in filename via click in filebrowser

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#2015]
### JASP Version

Still valid for 0.19 beta

### What OS are you seeing the problem on?

Flatpak Linux, possibly MacOS

### Bug Description

If a JASP-supported filetype (like .jasp, .sav, .csv, .ods) does contain a blank than it does not open JASP on clicking the file. This is only with the flatpak-version it was no problem with the bio-arch version. But I think I have seen this on MacBooks of my students too.

On click on the file, the JASP icon in the task bar very briefly lights up as if JASP attempts to start. But after a split of a seconds thats over and nothing happens. No window ever appeared.

Opening JASP and browsing to the file totally works all the time, even with blanks in the file name.

### Expected Behaviour

JASP should open and show the contents of the file when clicking on a file in a file explorer, even when the filename contains blanks.

### Steps to Reproduce

1. click on any filetype linked with JASP when the filename contains blanks
2. wait
3. nothing happens

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Can this be solved for next version? 
It is a quite annoying bug :D

**Comment by tomtomme** [comment]
Still valid for 0.18.1

**Comment by tomtomme** [comment]
Still present in 0.18.2 flatpak-beta from 30.11.23

**Comment by RensDofferhoff** [comment]
I will build a new nightly for you but this is resolved when on local flatpak build

**Comment by tomtomme** [comment]
confirmed! newest beta works with blanks in file names :D
