### ISSUE TITLE
[Feature Request]: descriptive tables similar to descriptive plots

### ISSUE THREAD

**Issue by ajestudillo** [jasp-stats/jasp-issues#2017]
### Description

Including a descriptive table with the numerical information with similar options as descrptive plots

### Purpose

Having both numerical and visual information of CIs, SEMs, across used and unused factors

### Is your feature request related to a JASP module?

ANOVA

**Comment by tomtomme** [comment]
@ajestudillo 
Can you detail this?
As far as I understand you are talking about adding CIs to the descriptives table of ANOVAs. We already have SE in that table and mean+-doubleSE gives you the 95% KI. Is this sufficient? 
Regarding the descriptive plot, besides the KI it presents the means, which are already included in the table.
You also write about SEMs - is that a typo and you meant SEs? Those are included already as stated above.
