### ISSUE TITLE
multinomial and ordinal logistic regression

### ISSUE THREAD

**Issue by coledavis** [jasp-stats/jasp-issues#202]
## Template for enhancement requests
 
* Enhancement: Multinomial logistic regression and ordinal regression
* Purpose: I think multinomial logistic regression would be an immensely useful addition, as logistic regression outputs are often non-binary. In terms of importance, multinomial would come before ordinal. 

I am able to provide some R coding for these which I think would be helpful in providing a blueprint for the back-end (I know, front end is where the really hard work is). Let me know if you'd like it.

**Comment by tultimatte** [comment]
I would like to second ordinal logistic regression!
Thank you so much :)

**Comment by djstepz1** [comment]
Multinomial (1st) and ordinal (2nd) would be a fantastic addition, something I already use in SPSS, but of course in JASP it would be perfect! I would add that the addition of multinomial in particular has real potential to increase the softwares use in social science, consumer and marketing research.

**Comment by KelvinBalcombe** [comment]
I see this request was made quite a while ago. I am trying to persuade some colleagues to transfer from SPSS to JASP for their undergraduate teaching. The inclusion of the ordered logit and multinomial logit would be key in that decision (even though the can be done in the R-box at the end quite easily I think).  So,I would just like to add support the comments above
