### ISSUE TITLE
[Bug]: Error messages SEM 

### ISSUE THREAD

**Issue by Boert98** [jasp-stats/jasp-issues#2020]
### JASP Version

0.17.0

### JASP Module

SEM

### What analysis are you seeing the problem on?

SEM

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

Displayed error message:
<img width="953" alt="Bildschirmfoto 2023-02-16 um 08 54 19" src="https://user-images.githubusercontent.com/125014619/219302801-3861cc8c-07d0-4339-8f24-eecd3ede1ad6.png">
SEM: 
<img width="609" alt="Bildschirmfoto 2023-02-16 um 08 54 32" src="https://user-images.githubusercontent.com/125014619/219302904-f09ff6dc-287c-4b30-89c5-ec8ef45dc7f3.png">
Model that I want to display:
<img width="775" alt="Bildschirmfoto 2023-02-16 um 08 55 35" src="https://user-images.githubusercontent.com/125014619/219302952-cac027ac-0d25-4451-8af3-7f47b2e118b5.png">
Control variables (AGE, GEN_kod, OS) are indicated as "Scale" 
JASP:
[Jasp alles neu.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/10753456/Jasp.alles.neu.jasp.zip)

### Expected Behaviour

It should work, please

### Steps to Reproduce

1. Code SEM
2. Apply model
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment]
funny enough, this runs fine in R
```r
data <- read.csv("/Users/julius/Downloads/Jasp alles neu.csv")

mod <- "
SR =~ SR_9 + SR_10 + SR_11 + SR_12 + SR_13
CC =~ CC_1 + CC_5 + CC_6 
ITC =~ ITC_1 + ITC_2 + ITC_3
NB =~ NB_1 + NB_2 + NB_3 + NB_4 + NB_5
SEF =~ SEF_1 + SEF_2 + SEF_3
ATT =~ ATT_1 + ATT_2 + ATT_3 + ATT_4
JS =~ JS_1 + JS_2 + JS_3revers + JS_4 + JS_5revers
TI =~ TI_1revers + TI_2revers + TI_3revers
CB =~ CB_1 + CB_2 + CB_3 + CB_4 + CB_5 + CB_7 + CB_8 + CB_9 + CB_10 + CB_11 + CB_12 + CB_13
#hypothesis
ITC ~ SR + CC + ATT + NB + SEF + AGE + GEN_kod + OS
JS ~ alpha*ITC + AGE + GEN_kod + OS
TI ~ beta*JS + direct*ITC + AGE + GEN_kod + OS
CB ~ gamma*JS + direct*ITC + AGE + GEN_kod + OS
"

library(lavaan)

fit <- sem(data = data, model = mod, fixed.x = T, auto.fix.single = T, 
           auto.var = T, auto.cov.lv.x = T, auto.cov.y = T, auto.th = T,
           auto.delta = T, auto.efa = T, auto.fix.first = T, int.lv.free = T)
fitmeasures(fit)
```

and removing some options also makes it run fine in JASP: 
![Screenshot 2023-02-16 at 10 07 41](https://user-images.githubusercontent.com/38500953/219319177-23ca62c6-605a-4be9-ae2a-85770552d443.png)

**Comment by juliuspfadt** [comment]
Also, @LSLindeloo, we should merge the notes underneath the fit table. https://github.com/jasp-stats/INTERNAL-jasp/issues/2246

**Comment by Boert98** [comment]
Thank you for the quick response, it worked! 
However, I have ran into another issue. In order to check how to improve my model, I was trying to look at the hypothesis separately. Unfortunately, I can not get results for this input: 
<img width="622" alt="Bildschirmfoto 2023-02-16 um 10 36 35" src="https://user-images.githubusercontent.com/125014619/219326677-6b7c8573-d1c9-4b76-9d0d-c2a3318b618d.png">
I get the following error message:
<img width="960" alt="Bildschirmfoto 2023-02-16 um 10 37 13" src="https://user-images.githubusercontent.com/125014619/219326822-b6f8075c-e912-418d-9ab0-54e61bb5baed.png">
It works without the additional fit measures though. But I do need those. 
Can you assist?

**Comment by juliuspfadt** [comment]
It would help, if you attached a zipped .jasp file, or at least show the options that you used. Anyways, with these options I get a result
![Screenshot 2023-02-16 at 11 06 25](https://user-images.githubusercontent.com/38500953/219334445-5e75ef31-c65c-4218-b897-afc4b8c648cf.png)
