### ISSUE TITLE
[Bug]: R error on Nonparametrics in 'Repeated Measures ANOVA'

### ISSUE THREAD

**Issue by eddie-uu** [jasp-stats/jasp-issues#2021]
### JASP Version

0.17.0

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

Friedman Test

### What OS are you seeing the problem on?

Windows 11

### Bug Description

Using the Nonparametrics feature in 'Repeated Measures ANOVA', I am attempting to perform the Friedman test. For this, I am using the data as shown below, with 3 RM factors such that you can fill all of them with for example value(5, 10, 15), block(1, 2, 3), and sign(negative, positive).

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
</head>

<body link="#0563C1" vlink="#954F72">

T -15 B1 | T -10 B1 | T -5 B1 | T 5 B1 | T 10 B1 | T 15 B1 | T -15 B2 | T -10 B2 | T -5 B2 | T 5 B2 | T 10 B2 | T 15 B2 | T -15 B3 | T -10 B3 | T -5 B3 | T 5 B3 | T 10 B3 | T 15 B3
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
794 | 688.25 | 872.625 | 825.25 | 799.875 | 670 | 581.375 | 598.625 | 707.9375 | 676.625 | 649.1875 | 593.5 | 541.375 | 572.9375 | 607.0625 | 655.6875 | 629.375 | 599.75
664 | 661 | 759.3125 | 891.4375 | 760.4375 | 658.125 | 635.625 | 646.625 | 869.125 | 703.25 | 647.9375 | 582.6875 | 588.8125 | 667.375 | 758.375 | 782.375 | 653.1875 | 651.0625

</body>

</html>

When using these values, I am receiving the 'Please specify appropriate terms for the Friedman/Durbin' error.
![image](https://user-images.githubusercontent.com/70958908/219339778-93f3f6f9-deca-487c-8624-3af552a61727.png)

### Expected Behaviour

What I am expecting is that the calculation is processed properly, and shows me the results.

### Steps to Reproduce

1. Use the 'Repeated Measures ANOVA'
2. Use a data file with values such as given in the bug description, with 3 RM factors
3. Fill RM cells with all the data columns
4. Perform the nonparametrics with all factors as RM factors

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JohnnyDoorn** [comment]
Hi @eddie-uu ,

The grouping factor is a between-subjects factor (other than the ID variable) - see also the helpfile. For this data, I do not think the Friedman test is appropriate, since the Friedman test only goes for one-way ANOVA. Also, only having 2 observations per cell seems a bit problematic (but the main analysis still runs, so I guess that is fine?).

Kind regards,
Johnny
