### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by brittanddogs** [jasp-stats/jasp-issues#2023]
### JASP Version

0.17.1

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

on every thing 

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

JASP has experienced an unexpected internal error:
The engine crashed...

JASP cannot continue and will close.

We would be grateful if you could report this error to the JASP team.

it happens at differente times when doing different things, but usually occurs whitin 1 min of me opening the app

### Expected Behaviour

i would like to have to quit jasp 

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by brittanddogs** [comment]
it happens right when i open jasp

**Comment by shun2wang** [comment]
Hi @brittanddogs can you refer here to upload logs? https://github.com/jasp-stats/jasp-desktop/blob/stable/Docs/user-guide/logging-howto.md#mac

with thanks

**Comment by boutinb** [comment]
Did you upload the right dmg version? The Intel one for MacOS should be called JASP-0.17.1.0-macOS-x86_64.dmg.
