### ISSUE TITLE
[Bug]: Incorrect eta-square in unequal-cells ANOVA, Type III

### ISSUE THREAD

**Issue by bfmalle** [jasp-stats/jasp-issues#2024]
### JASP Version

0.17.1

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

ANOVA with unequal cells

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

The error arises in the  η^2 calculations for unbalanced designs under Type III decomposition (Type I is correct, and partial η^2s are also correct).  I believe the error occurs because the total SSQ is not computed the right way under Type III —  it seems to be computed as SS_effects + SS_residual and therefore omits SSQ shared among the effects. It's correct that the shared SSQ are removed from the effects themselves under Type III.  But total SSQ must include shared SSQ (and must be the same in Type I and Type III). Details in the attached file.  Also attached is a zipped JASP file.
[JASP Eta squared problem in ANOVA.pdf](https://github.com/jasp-stats/jasp-issues/files/10775194/JASP.Eta.squared.problem.in.ANOVA.pdf)
[JASP error in eta-square.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/10775200/JASP.error.in.eta-square.jasp.zip)

### Expected Behaviour

The η^2 values under Type III need to be corrected to be based on the full SS_total in the denominator.

### Steps to Reproduce

1. See attached JASP file
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JohnnyDoorn** [comment]
Hi @bfmalle ,

Thank you for your detailed post. Do you have any additional references for the calculation of SS_T? Because I just checked the calculations through additional R-packages, and these also give the same results as JASP. For instance with the effectsize package:
```
# Load data and ensure correct format
dat <- read.csv("~/Downloads/etaDat.csv")
dat$diet <- as.factor(dat$diet)
dat$exercise <- as.factor(dat$exercise)

# Set appropriate contrasts for type 3 SS
contrasts(dat$diet) <- contr.sum
contrasts(dat$exercise) <- contr.sum

# Fit models
myModType1 <- lm(BMI ~ exercise * diet, data = dat)
myModType3 <- car::Anova(myModType1, type=3, singular.ok=FALSE)

# Compute effect size
library(effectsize)
eta_squared(myModType1, partial = FALSE) # type 1
eta_squared(myModType3, partial = FALSE) # type 3
```
![image](https://user-images.githubusercontent.com/15704203/220109986-138f3803-8034-4c2c-88f6-000d146a23f8.png)

**Comment by JohnnyDoorn** [comment]
Ah I realize the rounding of the result here is not so helpful.. Here is a more detailed output:
```
eta_squared(myModType1, partial = FALSE)$Eta2[3] # type 1
eta_squared(myModType3, partial = FALSE)$Eta2[3] # type 3
```
![image](https://user-images.githubusercontent.com/15704203/220111323-10734d76-dc87-435c-bde8-ad20c313a1fe.png)

**Comment by bfmalle** [comment]
Thanks for your quick response, Johnny.  Perhaps there is a newly developed habit from the R community, but the logic I follow (and that SPSS has followed) is this: Total SSQs always stay the same.  It's just that in Type III, only the unique components (corrected for everything else in the model) are displayed, and all the shared components (that get "credited" to early-entering effects in Type I) are not displayed.  But they are still there and should be retained in the Total SSQ and the calculation of the (nonpartial) eta-squares.  

Attached is the SPSS output from Type I and III runs, showing the consistent Total SSQ.   You will also notice that SPSS displays the Model SSQ, from which we can compute that  (corresponding to the model
[SPSS correct Total SSQ and Eta squared.pdf](https://github.com/jasp-stats/jasp-issues/files/10787106/SPSS.correct.Total.SSQ.and.Eta.squared.pdf)

Also attached, a painstaking reconstruction (with almost precise graph) of all the unique and shared SSQs.  The file also shows that JASP (and apparently R) computes the (nonpartial) eta-squares with the incorrect denominator (Residual + unique-only SSQs), leaving out the shared SSQs.  The file also shows that the sum of all the eta-squares (of both unique and shared components) is, as it should be, the Model R-square (displayed in SPSS).
[All unique and shared SSQs computed and graphed.pdf](https://github.com/jasp-stats/jasp-issues/files/10787144/All.unique.and.shared.SSQs.computed.and.graphed.pdf)

P.S. My titles were flipped in the originally uploaded JASP file.  Attached is the revised on: It's the Type III run that has incorrect eta-squares and the Type I run has the correct ones.  
[JASP error in eta-square rev.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/10787112/JASP.error.in.eta-square.rev.jasp.zip)

**Comment by JohnnyDoorn** [comment]
Hi @bfmalle,

Thanks again for your response - this is very helpful stuff. I've discussed with a colleague, and it seems that indeed the calculation we use is incorrect for imbalanced designs. I will work on an update to the analysis, so it should be fixed by the next JASP release. 

Kind regards,
Johnny

**Comment by bfmalle** [comment]
Fantastic, Johnny, thank you.  

I understand that fixing the bug has priority, but I also want to point to Feature Request #2025, which you probably saw.  It's about the need for crossed contrasts in multi-factor multi-level ANOVA.  I think this is another issue that R  packages just don't address very well but SPSS has long solved elegantly.  I would be happy to work with you on any revisions!

**Comment by bfmalle** [comment]
One more question on the bug — it seems that R (or it least the eta_squared function) makes the same error?  With whom should we get in touch to fix that?

**Comment by bfmalle** [comment]
Fantastic, thank you!  omega's formula contains SSQ_total as well, so it is likely to be affected:

ω2 = (SS_effect – (df_effect)(MS_error)) / (MS_error + SS_total)

**Comment by Rodrigoneuroscience** [comment]
> ### JASP Version
> 0.17.1
> 
> ### Commit ID
> _No response_
> 
> ### JASP Module
> ANOVA
> 
> ### What analysis are you seeing the problem on?
> ANOVA with unequal cells
> 
> ### What OS are you seeing the problem on?
> macOS Intel
> 
> ### Bug Description
> The error arises in the η^2 calculations for unbalanced designs under Type III decomposition (Type I is correct, and partial η^2s are also correct). I believe the error occurs because the total SSQ is not computed the right way under Type III — it seems to be computed as SS_effects + SS_residual and therefore omits SSQ shared among the effects. It's correct that the shared SSQ are removed from the effects themselves under Type III. But total SSQ must include shared SSQ (and must be the same in Type I and Type III). Details in the attached file. Also attached is a zipped JASP file. [JASP Eta squared problem in ANOVA.pdf](https://github.com/jasp-stats/jasp-issues/files/10775194/JASP.Eta.squared.problem.in.ANOVA.pdf) [JASP error in eta-square.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/10775200/JASP.error.in.eta-square.jasp.zip)
> 
> ### Expected Behaviour
> The η^2 values under Type III need to be corrected to be based on the full SS_total in the denominator.
> 
> ### Steps to Reproduce
> 1. See attached JASP file
> 
> ...
> 
> ### Log (if any)
> _No response_
> 
> ### Final Checklist
> * [x]  I have included a screenshot showcasing the issue, if possible.
> * [x]  I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
> * [x]  I have accurately described the bug, and steps to reproduce it.

Same problem. I ran ANOVA. JASP is using sums of squares Type 3 (by default) and the results were significant in one factor. Previously, I ran an ANOVA type 3 using the package "car" in Rstudio and the results were non significant. Therefore, JASP is not using type 3.
