### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by HKA07** [jasp-stats/jasp-issues#2027]
### JASP Version

0.17.0

### JASP Module

Unrelated

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

I tried opening a dataset with JASP. But got this instead: 

JASP has experienced an unexpected internal error:
The engine crashed...

JASP cannot continue and will close.

### Expected Behaviour

Open files with JASP

### Steps to Reproduce

1. Open JASP
2. Open File
3. Bug
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Did you upload the right dmg version? The Intel one for MacOS should be called JASP-0.17.1.0-macOS-x86_64.dmg.

**Comment by HKA07** [comment]
> Did you upload the right dmg version? The Intel one for MacOS should be called JASP-0.17.1.0-macOS-x86_64.dmg.

Yes I did

**Comment by boutinb** [comment]
Could you then give the log files: https://github.com/jasp-stats/jasp-desktop/blob/stable/Docs/user-guide/logging-howto.md
