### ISSUE TITLE
[Bug]:Says Jasp has experienced an unexpected internal error ; The engine crash, JAsp can not continue. 

### ISSUE THREAD

**Issue by Sdowley744** [jasp-stats/jasp-issues#2028]
### JASP Version

0.17.1

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

installation

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

![tempImageQGr2Wr](https://user-images.githubusercontent.com/125894072/220687016-e5dcbf33-1994-4130-9062-62b6006171ce.gif)

### Expected Behaviour

I could not open application/software.

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @Sdowley744 I can see from your screenshot, that you have installed JASP for Mac Intel, but you say that you have Mac Silicon: you should install the JASP Silicon version (just to be sure, the dmg file you download is called JASP-0.17.1.0-macOS-arm64.dmg).
I can see also that you have installed 0.17.0, there is now a 0.17.1 version.
