### ISSUE TITLE
[Bug]: The size of the last flight of Jasp Nigtlies (today) have a half of the size of yesterday flight of it

### ISSUE THREAD

**Issue by Ghassan-Okour** [jasp-stats/jasp-issues#2030]
### JASP Version

Others

### Commit ID

a1317f43c4d47bcf11db07c5f201192fea5d0a5f

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

Unrelated

### What OS are you seeing the problem on?

Windows 11

### Bug Description

![image](https://user-images.githubusercontent.com/115344297/220983735-03b8f4ce-7ef9-4d09-ad22-3527073d1287.png)

### Expected Behaviour

The size of the last flight of Jasp Nightlies (today) have a half of the size of yesterday flight of it
The size for the flight of today is 364 MB
But the size for the flight of yesterday is 715 MB
Is it correct????
Best Regards...

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
I don't what happened. I have built another one, and this one seems normal
