### ISSUE TITLE
Exploratory Factor Analysis

### ISSUE THREAD

**Issue by danieleasioli** [jasp-stats/jasp-issues#2034]
### Description

Using Exploratory Factor Analysis I have noticed that there is no the option of getting also the correlation matrix among the variables at the beginning of the analysis which I believe is useful. Could it be possible to add such feature?

### Purpose

Improve Exploratory Factor Analysis for students

### Is your feature request related to a JASP module?

Factor

### Describe the solution you would like

Using Exploratory Factor Analysis I have noticed that there is no the option of getting also the correlation matrix among the variables at the beginning of the analysis which I believe is useful. Could it be possible to add such feature?

### Describe alternatives that you have considered

NA

**Comment by juliuspfadt** [comment]
@danieleasioli, thanks for creating the issue. I believe what you are looking for is done within the Regression-module where you can find a correlation-analysis. This is to keep the analyses mostly concise.
