### ISSUE TITLE
[Bug]: Help-Window partly empty

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#2035]
### JASP Version

0.17.1

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Manjaro

### Bug Description

![grafik](https://user-images.githubusercontent.com/4428185/222126678-8518be01-aa50-4f83-9c5f-d290b1342460.png)

after switiching to english

![grafik](https://user-images.githubusercontent.com/4428185/222126877-f454f69f-b75b-48f7-9b22-b283b59ee5ab.png)

### Expected Behaviour

I would like to see the full help-texts as in earlier jasp versions. This happens not only with the descriptive help. 

### Steps to Reproduce

open a help text with the blue info button

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
As a workaround I deleted /home/thomasl/.var/app/org.jaspstats.JASP/ 
Now help-texts are back.
But I still consider this a bug. 
Maybe the cache is not updated correctly?
And I just saw this on a completely different machine of a colleaugue. She did a **fresh** install on **windows 10** and had the same problem in any language. And on windows I do not know where this "app" folder is.

**Comment by boutinb** [comment]
Hui @tomtomme, you are using the 'Generate markdown files for help' (in the Preferences/Advanced). This option should not have been released, as the help files are not yet ready for this. If you check it out, then the whole help file should appear again.

**Comment by tomtomme** [comment]
Is it possible that this option is enabled by default on new installs on win10?

**Comment by boutinb** [comment]
No the setting is set to false per default... but this setting should not be available anyway in the release (hopefully it will be on soon, the generated help file will be then translatable!)
