### ISSUE TITLE
[Bug]: Confidence intervals for Wilcoxon signed-rank test are reported even when requested confidence level is not achievable

### ISSUE THREAD

**Issue by lollopus** [jasp-stats/jasp-issues#2037]
### JASP Version

0.17.1

### JASP Module

T-Tests

### What analysis are you seeing the problem on?

One Sample T-Test

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

Confidence intervals for the Wilcoxon signed-rank test are reported even when the requested confidence level is not achievable. This issue is particularly severe when analysing very small samples, such that the granularity of computable confidence levels is coarse.
For instance, when the sample size = 6 the top three available confidence levels are: 0.969, 0.938, 0.906. However, Jasp will report a CI for the Hodges-Lehmann estimate even when the user requests a confidence level of 99%, which is technically unachievable.
The issue is a bug in Jasp since the underlying R function `wilcox.test` correctly handles these cases by posting a warning message.

### Expected Behaviour

This is how R handles unachievable confidence level requests:
`x  <- c(1, 2, 3, 4, 5, 6)`
`wilcox.test(x, conf.int = TRUE, conf.level = 0.99)`

> Wilcoxon signed rank exact test
>
>data:  x
>V = 21, p-value = 0.03125
>alternative hypothesis: true location is not equal to 0
>96.9 percent confidence interval:
> 1 6
>sample estimates:
>(pseudo)median 
>           3.5 
>
>**Warning message:**
>**In wilcox.test.default(x, conf.int = TRUE, conf.level = 0.99) :**
>  **requested conf.level not achievable**

As demonstrated below Jasp does not handle these situations correctly as it  reports an erroneous CI of [1, 6] for the requested confidence level of 99%. The expected behaviour should be to parse these R warning messages, not report a CI and explain to the user that the requested confidence level is unachievable.

### Steps to Reproduce

1. save a .csv file containing the real values 1, 2, 3, 4, 5, 6 in a single column
2. open the file in JASP
3. add a One Sample T-Test analysis
4. add the column variable containing the values
5. select the _Wilcoxon_ checkbox
6. select both the _Location estimate_ and _Confidence interval_ checkboxes
7. insert the value _99_ in the confidence level field

This is a screenshot of the erroneous results:
<img width="1281" alt="Screen Shot 2023-03-02 at 11 37 06" src="https://user-images.githubusercontent.com/11914162/222404814-cb2c801b-de76-443f-9cf7-652a18e49bc7.png">

As you can see Jasp erroneously reports the CI for the best available confidence level 96.9% when the user asked for 99%. The unaware user will thus proceed with using an invalid confidence level.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
checked with jasp 0.18.3 and still an issue

**Comment by JohnnyDoorn** [comment]
Hi @lollopus ,

Sorry for my slow reply. We do not use the wilcox.test function for the confidence intervals, but the MBESS package. This package offers more flexibility for smaller sample sizes. We are currently working on reworking the presentation of the R-packages being used. Please reopen this issue if you have further questions.

Kind regards,
Johnny

**Comment by lollopus** [comment]
Hi @JohnnyDoorn I am afraid that your **closing the issue is premature**, since irrespective of the underlying package being used for t-tests, the CIs reported by Jasp for small samples are **incorrect**. Should I reopen this issue (which I do not know how to do) or post a new one? Thanks

**Comment by lollopus** [comment]
Incidentally, I see that MBESS is based on R, so I wonder whether wilcox.test() is used after all... In any case as I commented in my previous post the output of Jasp is incorrect. If I were in charge of debugging I would as a first step check what the full output of MBESS is under the conditions of the example I gave in my initial post.

**Comment by JohnnyDoorn** [comment]
Thanks for the detailed explanation - I will incorporate the wilcox.test function output in the CI's for the Wilcoxon CI's (I assume this issue also holds for the rank sum test, since that's also too discrete for low sample sizes).

Kind regards
Johnny

**Comment by lollopus** [comment]
Yeah, wilcox.test seems indeed to be used in Jasp (JaspTTests/R/ttestonesample.R). Serving the full output of that function would be acceptable, however a better solution might be to parse the full R output for the string "requested conf.level not achievable" and if present do the following: 1. not report a CI; 2. tell the user that the requested confidence level is unachievable. Thanks again

**Comment by JohnnyDoorn** [comment]
Yes, I'm thinking to just report whichever level the wilcox.test function defaults to, and to then add a footnote explaining that the desired level is not possible and that we provide the closest possible confidence level.
