### ISSUE TITLE
[Bug]: This analysis terminated unexpectedly (additional fit measures)

### ISSUE THREAD

**Issue by natashlya13** [jasp-stats/jasp-issues#2038]
### JASP Version

0.17.1

### JASP Module

SEM

### What analysis are you seeing the problem on?

Structural Equation Modeling

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

This analysis terminated unexpectedly.

Error in solve.default(X[[i]], ...): Lapack routine dgesv: system is exactly singular: U[3,3] = 0

Stack trace
lapply(modelContainer[['results']][['object']], .fitMeasures)

FUN(X[[i]], ...)

lavaan::fitMeasures(fit, fit.measures = 'all')

lavaan::fitMeasures(fit, fit.measures = 'all')

lav_fit_measures(object = object, fit.measures = fit.measures, baseline.model = baseline.model, fm.args = fm.args, output = output)

lav_fit_cfi_lavobject(lavobject = object, fit.measures = fit.measures, baseline.model = baseline.model, standard.test = standard.test, scaled.test = scaled.test)

lav_fit_fiml_corrected(lavobject, version = version)

lapply(Wm, solve)

FUN(X[[i]], ...)

solve.default(X[[i]], ...)

[Log dan outlier_PCOS lean 120 sampel dan leptin.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/10878269/Log.dan.outlier_PCOS.lean.120.sampel.dan.leptin.jasp.zip)

### Expected Behaviour

This happened when i checklisted the additional fit measures.

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by aewong00** [comment]
I had the same error too running this model, the error occurs when I click "additional fit measures"

graduateschool_gpa ~ gre_score + highschool_gpa + college_gpa
gre_score ~ highschool_gpa + college_gpa

My error message is 
This analysis terminated unexpectedly.

Error in solve.default(X[[i]], ...): Lapack routine dgesv: system is exactly singular: U[3,3] = 0

Stack trace
lapply(modelContainer[['results']][['object']], .fitMeasures)

FUN(X[[i]], ...)

lavaan::fitMeasures(fit, fit.measures = 'all')

lavaan::fitMeasures(fit, fit.measures = 'all')

lav_fit_measures(object = object, fit.measures = fit.measures, baseline.model = baseline.model, fm.args = fm.args, output = output)

lav_fit_cfi_lavobject(lavobject = object, fit.measures = fit.measures, baseline.model = baseline.model, standard.test = standard.test, scaled.test = scaled.test)

lav_fit_fiml_corrected(lavobject, version = version)

lapply(Wm, solve)

FUN(X[[i]], ...)

solve.default(X[[i]], ...)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

**Comment by juliuspfadt** [comment]
@natashlya13, @aewong00, thanks for the report. I dont get this error anymore in the newest (beta) JASP version, I suspect because we now use the latest `lavaan` version. So with the next release that is just around the corner this issue should be fixed.
