### ISSUE TITLE
crashing on version 17.1

### ISSUE THREAD

**Issue by App-State-Prof** [jasp-stats/jasp-issues#2039]
### JASP Version

0.17.1

### JASP Module

Regression

### What analysis are you seeing the problem on?

logistic regression

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I have been having crashed on version 17.1. It has happened in network analysis, today logistic regression.
![logistic crash](https://user-images.githubusercontent.com/33431829/222922145-017becbf-b470-412a-881a-58c6b76d7dbc.JPG)

### Expected Behaviour

Sometimes I will alter a test and it crashes, other times I am observing the test results and it crashes.

### Steps to Reproduce

1.Now sure when or how.
2. Intermittent in the new version.
3.
...

### Log (if any)

I am sorry I don't know how to do this.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by vladimirsim** [comment]
Hello, I have a problem with crashing, too. I have just installed JASP on a Window 10 PC. I load the 'Telco customer churn' dataset from the '10. Machine learning' data library and then, when I open the  _Descriptives_ or the _Machine learning_ menu, JASP crashes within 5-10 seconds without displaying any error messages. The program simply closes and that's it. I have tried downloading the 'Telco customer churn' file and opening it from a local drive. Same result.

**Comment by boutinb** [comment]
@vladimirsim & @App-State-Prof, could you send us the log files: https://github.com/jasp-stats/jasp-desktop/blob/stable/Docs/user-guide/logging-howto.md ?

**Comment by vladimirsim** [comment]
Another example of JASP crashing, this time the ANOVA module.
[JASP 2023-04-13 15_50_24 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/11222480/JASP.2023-04-13.15_50_24.Engine.0.log)
[JASP 2023-04-13 15_50_24 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/11222481/JASP.2023-04-13.15_50_24.Engine.1.log)
[JASP 2023-04-13 15_50_24 Engine 2.log](https://github.com/jasp-stats/jasp-issues/files/11222482/JASP.2023-04-13.15_50_24.Engine.2.log)
[JASP 2023-04-13 15_50_24 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/11222483/JASP.2023-04-13.15_50_24.Desktop.log)

**Comment by boutinb** [comment]
Hi @vladimirsim, this is quite difficult to understand what's going wrong on your PC. I see that JASP is installed on your E drive. Is there anything special with this drive? Why is it not just the C drive? 
What you could also do it to start JASP from the command line:  Start a command prompt (cmd) and type `E:/Program Files/JASP/JASP`. Can you give me then the output you see on the command prompt when JASP crashes?

**Comment by vladimirsim** [comment]
Hello Bruno!

 

I have started JASP from cmd. It starts normally but nothing else happens in cmd. When JASP crashes, it does not have any implication on the command prompt. Nothing is written on cmd, only the starting line. Here are the log files – attached.

I have installed on E because C is my Windows drive, D is my CD drive and E is my data drive. I have installed other applications on E and they run properly.

 

Could it be the local settings in Windows? For example a decimal comma instead of a decimal point, etc.? For example, I just saw that currently my decimal point for numbers is the point, but for currency is the comma.



 

 



 

Best,

Vladimir

**Comment by vladimirsim** [comment]
I think that I have found a solution. I don't know what the problem was, but I went to _Preferences>Interface>Miscellaneous options_ and there I activated the '_Safe graphics mode_'. Now JASP works fine and I managed to do my analyses. Thank you very much for your time and efforts! Good luck!
