### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by JP-TATA** [jasp-stats/jasp-issues#2049]
### JASP Version

0.17.1

### JASP Module

Factor

### What analysis are you seeing the problem on?

second order confirmatory analysis

### What OS are you seeing the problem on?

Windows 11

### Bug Description

This analysis terminated unexpectedly.

Error in Wm.all %*% Delta.all %*% E.inv: requires numeric/complex matrix/vector arguments

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.cfaTableMain(jaspResults, options, cfaResult)

lavaan::fitMeasures(cfaResult[['lav']])

lavaan::fitMeasures(cfaResult[['lav']])

lav_fit_measures(object = object, fit.measures = fit.measures, baseline.model = baseline.model, fm.args = fm.args, output = output)

lav_fit_cfi_lavobject(lavobject = object, fit.measures = fit.measures, baseline.model = baseline.model, standard.test = standard.test, scaled.test = scaled.test)

lav_fit_fiml_corrected(lavobject, version = version)

### Expected Behaviour

Second order factor creation
![image_2023-03-10_084746903](https://user-images.githubusercontent.com/127468770/224225928-82310e83-6b7d-4214-8fd7-9fffb109db09.png)
[Data.zip](https://github.com/jasp-stats/jasp-issues/files/10938633/Data.zip)

### Steps to Reproduce

1. Factor 1 and Factor 2 are working ok
2. when launching second factor it computes for a long time and then crashes
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment]
I checked this error within R and I could only reproduce it if I set back my `lavaan` version to 0.6.13, which is the one currently in use in JASP 0.17.1. For the next release JASP, or for that sake the next nightly version, should contain the latest `lavaan` version as it is published on CRAN, and thus the error should be fixed. @boutinb, could you build a Mac intel version soon, so I can confirm?
