### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by Smarquez12** [jasp-stats/jasp-issues#2051]
### Description

i cant find my documents saved onto my laptop when i try to open a file on jasp 0.17.10

### Purpose

submit an assinment

### Use-case

i cant find my documents saved onto my laptop when i try to open a file on jasp 0.17.10

### Is your feature request related to a problem?

yes

### Is your feature request related to a JASP module?

Descriptives

### Describe the solution you would like

How can I open my saved documents on jasp?

### Describe alternatives that you have considered

None

### Additional context

I am needing support finding my saved excel document to export on Jasp for my assignment for school/ Please tell me how I can fix this issue.

**Comment by boutinb** [comment]
Hi @Smarquez12, your request is quite unclear. If you don't know where are your excel documents, please ask a colleague/student to help you. Reopen this issue, if you can describe precisely your problem step by step, and if it is related to a problem inside JASP.
