### ISSUE TITLE
[Feature Request]: Baysian ANOVA post hoc comparison on the interaction level

### ISSUE THREAD

**Issue by YunyunMu** [jasp-stats/jasp-issues#2057]
### Description
Hi, I am currently using the newest version of Jasp to analyze the data. I used the Bayesian repeated measures ANOVA and found an interaction effect (e.g, Group * Trial type).  However, unlike the frequentist ANOVA, I couldn't see the option of post hoc comparisons on the interaction level (Group * Trial type).  Is there a solution for this? Thanks a lot!

### Is your feature request related to a JASP module?

ANOVA

**Comment by tomtomme** [comment]
@YunyunMu 
I am closing this, since this is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/588
Lets discuss this feature request there.
