### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by Mattiwinks** [jasp-stats/jasp-issues#2059]
### Description

Jasp 0.17.1 Cannot perform tests because there are only two levels of the RM factor. What can I do to fix this?

### Is your feature request related to a JASP module?

ANOVA

**Comment by JohnnyDoorn** [comment]
Hi @Mattiwinks. 

This seems to concern the Mauchly test, which is not applicable for RM ANOVA with only two levels - see also my response to your other thread. Please reopen if you have additional questions.
