### ISSUE TITLE
[Bug]: Installer error when installing JASP 0.17.1 on Windows 8

### ISSUE THREAD

**Issue by lgunali** [jasp-stats/jasp-issues#2061]
### JASP Version

0.17.1

### JASP Module

Other Module

### What OS are you seeing the problem on?

Windows 8

### Bug Description

There is a problem with this windows installer package, A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.

same as https://github.com/jasp-stats/jasp-issues/issues/1841#issue-1389517673

### Expected Behaviour

Install to use JASP 0.17.1 in Windows 8

### Steps to Reproduce

1. download windows version at https://jasp-stats.org/download/
2. run JASP-0.17.1-64bit.msi on Windows 8 
![screen](https://user-images.githubusercontent.com/71451331/225985224-66218266-4233-4d7f-9194-8fdb43b56f7c.png)
3. error: There is a problem with this windows installer package, A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.
4. updated video driver but installer doesn't work
5. do that https://github.com/jasp-stats/jasp-issues/issues/1807#issuecomment-1231002975 and uploaded zip file on log
6. download portable windows version at https://jasp-stats.org/download/
7. unpack  JASP-0.17.1-64bit.zip
8.  7Zip report some file errors but unpack files
9.  explorer unpack files in 30 minutes  (idk about errors)
10.  run JASP
11.   error see screenshot      ![screen 1](https://user-images.githubusercontent.com/71451331/225984540-bcb9953b-9e3f-4117-aca2-38676d9a307d.png)
12. junction test sucefully
13. do that https://github.com/jasp-stats/jasp-issues/issues/1807#issuecomment-1231885449 but error https://github.com/jasp-stats/jasp-issues/issues/1807#issuecomment-1231951257
14.  run jasp --safeGraphics -junctions on cmd but same error at point 10
...

### Log (if any)

[msilog.txt.zip](https://github.com/jasp-stats/jasp-issues/files/11004448/msilog.txt.zip)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by lgunali** [comment]
hello folks,
With portable version I run the vcredist installer...
When I run jasp engine it tells me I'm messing R.dll

I tried  downloading this: https://www.dependencywalker.com/depends22_x64zip
I Opened it and opened "JASP.exe" with it. Then I exported the results to "Dependency Walker Image (DWI)" and I uploaded here
[JASP.dwi.zip](https://github.com/jasp-stats/jasp-issues/files/11008262/JASP.dwi.zip)

**Comment by boutinb** [comment]
Windows 8 is not supported anymore by Microsoft: https://support.microsoft.com/en-au/office/what-windows-end-of-support-means-for-office-and-microsoft-365-34e28be4-1e4f-4928-b210-3f45d8215595
So please upgrade first to Windows 10 or change to Linux

**Comment by JorisGoosen** [comment]
Qt 6.2 was present in all versions `>=0.16.2`  so below that.

It really is a good idea to upgrade your OS though, you won't be getting any security updates from Microsoft... Who knows what virus might make use of the security holes left open?

In any case you can try 0.16.1 and older when you keep using Win8.

**Comment by lgunali** [comment]
> 

Thank you very much for your suggestions.

0.16.1 really works very good.
