### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by sammyjktho** [jasp-stats/jasp-issues#2062]
### Description

I tried downloading JASP on my laptop MacBook, and it shows that it couldn’t access to the application that I just downloaded, but it shows that on my folder that the application JASP is there but when I click on the folder application, it wouldn’t show up

### Purpose

JASP application folder was denied

**Comment by EJWagenmakers** [comment]
This was solved by installing an older JASP version (because the macOS version was old and not supported by Apple any more). Elsewhere I created an issue to make users aware of this more explicitly.
