### ISSUE TITLE
[Bug]: Error message, ''length (error) = 1 is not true'', displays when trying to run a network analysis

### ISSUE THREAD

**Issue by amot2** [jasp-stats/jasp-issues#2063]
### JASP Version

0.17.1

### JASP Module

Network

### What analysis are you seeing the problem on?

Classic Network Analysis 

### What OS are you seeing the problem on?

Windows 11

### Bug Description

The network plot does not show, an error message comes up saying ''length (error) = 1 is not true''. 

### Expected Behaviour

It should have produced a network plot of the relevant dependent variables. 

### Steps to Reproduce

1. Upload dataset file
2. Select 'classic network analysis' under 'network'
3. Put relevant variables in 'dependent variables' box

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@amot2 
This seems fixed in jasp 0.18.3
Feel free to reopen, if not fixed on your side.

**Comment by tomtomme** [comment]
Note to myself:
This error also appears with non-parametric bootstrapping in the network-module.
