### ISSUE TITLE
[Bug]: Jasp crashed

### ISSUE THREAD

**Issue by czenci** [jasp-stats/jasp-issues#2064]
### JASP Version

0.17.1

### JASP Module

Descriptives

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

Yesterday, I ran a test on Jasp and left it open. When I opened my computer today, Jasp had crashed and I was asked to report it. Nonetheless, I still love Jasp!

### Expected Behaviour

It should not have crashed

### Steps to Reproduce

1. Check descriptives
2. Put the computer in hibernation 
3. Launch Jasp
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by RensDofferhoff** [comment]
This PR is likely to fix this issue https://github.com/jasp-stats/jasp-desktop/pull/5001

**Comment by tomtomme** [comment]
@czenci 
So this seems fixed at least in jasp 0.18.3
Feel free to reopen, if not fixed on your side.
