### ISSUE TITLE
[Feature Request]: factor variable in (scatter) plots

### ISSUE THREAD

**Issue by PetBuj** [jasp-stats/jasp-issues#2068]
### Description

Add button (text field) to use some nominal/ordinal variable to distinguish points in scatter plot. Moreover, several independet lines (linear or other) will be applied

### Purpose

It is very commont to distinguish several groups of objects in one scatter plot (in other statistical SW)

### Use-case

I need to illustrate dependency between age and earnings (income) of men and women.

### Is your feature request related to a problem?

Yes, I have problem to preapre these plots

### Is your feature request related to a JASP module?

Descriptives

### Describe the solution you would like

Add botton/text field in descr.plots module

**Comment by tomtomme** [comment]
This is possible in descriptives. Use the Scatterplot in "customizable plots" and put gender in as the "split" variable. 
This is also possible in the addon module visual modelling => flexplot. Just add the 3 variables.

**Comment by tomtomme** [comment]
Examples:
![grafik](https://user-images.githubusercontent.com/4428185/227203340-6c27216c-e324-4851-b28b-a44250f61e80.png)
I hope, this is what you need :)

**Comment by tomtomme** [comment]
@PetBuj 
So I guess this can be closed then. Feel free to open a new issue if something else is missing for you :)
