### ISSUE TITLE
[Bug]: Repeated Measures ANOVA

### ISSUE THREAD

**Issue by francescgo** [jasp-stats/jasp-issues#2069]
### JASP Version

0.17.1

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

Repeated Measures ANOVA

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

It can not calculate simple main effects

### Expected Behaviour

It should show
![image](https://user-images.githubusercontent.com/591449/227540197-714d90e5-389f-4d0e-ad37-ce08373c319c.png)

### Steps to Reproduce

1. Download 2-way Mixed ANOVA.csv from [demo repository](http://bit.ly/2wlbMvf).
2. In «Simple Main Effects», add Grip to «Simple effect factor» and %1RM to «Moderator factor 1».

### Log (if any)

This analysis terminated unexpectedly.

Error in options$homogeneityCorrectionBrown || options$homogeneityCorrectionWelch: invalid 'x' type in 'x || y'

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.rmAnovaSimpleEffects(rmAnovaContainer, dataset, longData, options, ready)

.anovaResult(rmAnovaContainer[['simpleEffectsContainer']], options = simpleOptions)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@francescgo 
This seems to work fine in jasp 0.18.3
I even used % signs in the factor level names etc.
Feel free to reopen if not fixed on your side.
