### ISSUE TITLE
dès que je lance l'application ça me met un message d'erreur et je ne peux pas utiliser l'application[Bug]: 

### ISSUE THREAD

**Issue by memoire2023** [jasp-stats/jasp-issues#2070]
### JASP Version

0.17.1

### JASP Module

Other Module

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

dès que je lance l'application ça me met un message d'erreur et je ne peux pas utiliser l'application.

### Expected Behaviour

Je devrai pouvoir lancer l'application pour l'utiliser

### Steps to Reproduce

1. Lancement de l'application
2. Message d'erreur
3. Le logiciel se ferme 
...

### Log (if any)

<img width="1243" alt="Capture d’écran 2023-03-25 à 09 09 12" src="https://user-images.githubusercontent.com/128891049/227705809-5702de0b-3629-45b6-9f30-36b81295b3f0.png">

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Bonjour @memoire2023,
First of all, it would be better if your write your issue in english, I'm french, but most of the people here does not understand french.
Could you give me the version of you Mac OS: you can see it in the 'About this mac' (À propos de...). Are you also sure that you have downloaded the Mac Intel version of JASP (and not the Solicon one): could you give the name of the downloaded dmg file?

**Comment by tomtomme** [comment]
@memoire2023 
Feel free to reopen if you can provide more details and if this is not yet fixed in jasp 0.18.3. Thx!
