### ISSUE TITLE
[Bug]: Header row is ghosted

### ISSUE THREAD

**Issue by edenrothschild** [jasp-stats/jasp-issues#2071]
### JASP Version

0.17.1

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

I am trying to open t-test using my own data but the entire header row is ghosted. JASP only works when I am using existing datasets.

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

<img width="1236" alt="Screenshot 2023-03-26 at 8 41 52 am" src="https://user-images.githubusercontent.com/128939454/227745926-cfe5ab91-d907-4895-b397-081ae1159046.png">

### Expected Behaviour

I should have been able to access any of the tests in the header

### Steps to Reproduce

1. I simply removed and downloaded the software again and it didn't work on either selection.
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @edenrothschild, you say that JASP works when you use existing dataset, what do you mean by that: do you mean that you load dataset from the JASP Data Library? And what do you do exactly when you load your own dataset? I see from your picture, that no dataset was loaded, so did you get an error when loading your dataset?
