### ISSUE TITLE
[Feature Request]: DIF

### ISSUE THREAD

**Issue by kwokng** [jasp-stats/jasp-issues#2072]
### Description

Can these packages be converted to be used in JASP to run DIF analyses?  lordif (Choi, Gibbons & Crane, 2011)  difR (Magis, Beland & Raiche, 2013)  TAM (Kiefer, Robitzsch & Wu, 2013)

### Purpose

Create DIF analysis.

### Additional context

Can these packages be converted to be used in JASP to run DIF analyses?

lordif (Choi, Gibbons & Crane, 2011)

difR (Magis, Beland & Raiche, 2013)

TAM (Kiefer, Robitzsch & Wu, 2013)

**Comment by Ghassan-Okour** [comment]
> ### Description
> Can these packages be converted to be used in JASP to run DIF analyses? lordif (Choi, Gibbons & Crane, 2011) difR (Magis, Beland & Raiche, 2013) TAM (Kiefer, Robitzsch & Wu, 2013)
> 
> ### Purpose
> Create DIF analysis.
> 
> ### Use-case
> _No response_
> 
> ### Is your feature request related to a problem?
> _No response_
> 
> ### Is your feature request related to a JASP module?
> _No response_
> 
> ### Describe the solution you would like
> _No response_
> 
> ### Describe alternatives that you have considered
> _No response_
> 
> ### Additional context
> Can these packages be converted to be used in JASP to run DIF analyses?
> 
> lordif (Choi, Gibbons & Crane, 2011)
> 
> difR (Magis, Beland & Raiche, 2013)
> 
> TAM (Kiefer, Robitzsch & Wu, 2013)

I wish as you wish...

**Comment by EJWagenmakers** [comment]
More generally it would certainly be desirable to have an IRT module.

**Comment by tomtomme** [comment]
Closing then, since duplicate of https://github.com/jasp-stats/jasp-issues/issues/160

**Comment by tomtomme** [comment]
@Ghassan-Okour 
this is now available as a community module in jasps module store :)
