### ISSUE TITLE
Error in bainSummary[['Parameter']]: subscript out of bounds  

### ISSUE THREAD

**Issue by sofievdongen** [jasp-stats/jasp-issues#2073]
### JASP Version

0.17.1

### JASP Module

ANOVA, Bain

### What analysis are you seeing the problem on?

Bain ANOVA descriptives + plots 

### What OS are you seeing the problem on?

Windows 11

### Bug Description

When I try to run a Bain ANOVA on my dataset, I can see the descriptives, hypothesis and plots for a few seconds but after that I get an error saying: this analysis terminated unexpectedly. This is the trace that comes with it: 
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

As far as I've tried, I am still able to run other analysis, like a normal ANOVA. 
I haven't used JASP often, so I'm quite lost. If anyone knows how to fix this, please inform me. 

Thank you in advance.

### Expected Behaviour

Instead of the bug, i should be able to see the descriptives and plots without an error. 

### Steps to Reproduce

1.Click on Bain
2. Select ANOVA option in Bain
3. Choose the right dependent variable and fixed factor
4. Select descriptives at 'tables' and the two options under 'plots' 
5. After a few seconds the error occurs in the right part of the screen, where the statistics are seen
...

### Log (if any)

![The error](https://user-images.githubusercontent.com/129060684/227925193-d50b2d79-4f5a-4f8b-b157-05b440b949cb.png)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by koenderks** [comment]
Hi @sofievdongen,

To reproduce this bug it would be nice to have the data file that is used. Is it possible to attach your data set as a .csv file? You can just drag the file into the box where you write the comment.

Thanks

**Comment by sofievdongen** [comment]
[Rekenvaardigheid(2).csv](https://github.com/jasp-stats/jasp-issues/files/11077986/Rekenvaardigheid.2.csv)

**Comment by koenderks** [comment]
Hmm I cannot reproduce this bug with your data set and JASP version 0.17.1 (see screenshot below).
![image](https://user-images.githubusercontent.com/25059399/227927706-561e0109-3b08-4b6c-afb5-e1a96c85b4ff.png)

Which JASP version are you currently using?

Could you attach the JASP file with the crashed analysis here as well? You can do this by going to the upper-left menu --> save as --> Right click on the saved .jasp file --> Zip as and then upload the .zip file here!

**Comment by sofievdongen** [comment]
I can't seem to save it as a .zip file, the only option is .jasp. I'm currently using 0.17.1 JASP version.

**Comment by koenderks** [comment]
Once you have saved the analysis as a .jasp file, then you can right click on this .jasp file to rename it and change the .jasp extension to .zip!

**Comment by sofievdongen** [comment]
[Rekenvaardigheid(3).zip](https://github.com/jasp-stats/jasp-issues/files/11078052/Rekenvaardigheid.3.zip)

**Comment by koenderks** [comment]
Hmm I also do not get an error with this file. What if you try refreshing the analysis using the refresh all option at the top of the file? If I do that on your file it works for me.

![image](https://user-images.githubusercontent.com/25059399/227929790-5066d5b7-47fd-4b0e-a642-03096455e390.png)

Alternatively, you can download this file and change .zip to .jasp. Then you should get my results. 
[Rekenvaardigheid(3).zip](https://github.com/jasp-stats/jasp-issues/files/11078078/Rekenvaardigheid.3.zip)

Let me know if that works.

**Comment by sofievdongen** [comment]
I can't seem to find the 'result' menu in the first place. Where do I find it?

**Comment by koenderks** [comment]
It should be all the way om top of the results panel on the right part of the screen. If you hover over “Results” then a black arrow should appear. If you click this then the menu should appear

**Comment by sofievdongen** [comment]
It seems to work if I refresh it! I have no clue why it's working all of a sudden but I will not question it. Thank you for your help and your patience!

**Comment by koenderks** [comment]
No worries, glad it works now!
