### ISSUE TITLE
[Bug]: Spearman's rho gives NaN

### ISSUE THREAD

**Issue by paulamarentette** [jasp-stats/jasp-issues#2075]
### JASP Version

0.17.1

### JASP Module

Regression

### What analysis are you seeing the problem on?

Spearman rho

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

![Screenshot 2023-03-29 at 19 53 00](https://user-images.githubusercontent.com/48217084/228707715-b2f61527-b8aa-4f7d-aec4-cdd47ecd7554.jpg)

Using the Data Library Big 5 Dataset for correlation.
I teach intro stats and this problem has occurred on diverse platforms by many students. 

Once you have calculated a correlation matrix, if you then add in Spearman it gives NaN (as seen above).
The fix so far: remove the variables, select Spearman, add the variables back.

[W9 JASP settings_Big Five Personality Traits.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/11107026/W9.JASP.settings_Big.Five.Personality.Traits.jasp.zip)

### Expected Behaviour

It should calculate Spearman rho.

### Steps to Reproduce

1. open Big 5 Personality file from JASP data library
2. calculate correlation matrix with all 5 variables
3. select Spearman rho
4. get error
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by Ghassan-Okour** [comment]
It working on Windows 11 Pro as it should be:
![image](https://user-images.githubusercontent.com/115344297/228712846-894bd7bc-69a8-4784-97c4-c2a5cfb9d7c0.png)

**Comment by paulamarentette** [comment]
I sent a screenshot. This occurred with many students.
I have replicated it many times on my own laptop.
Trying to be helpful and report a bug.
Best,
Paula

**Comment by juliuspfadt** [comment]
@paulamarentette, thanks for reporting this bug. I can definitely replicate it on my machine. So it might be related to the OS (I am also on macOS intel).

**Comment by Kucharssim** [comment]
Dear @paulamarentette,

thank you for posting this issue. Please note that other users already reported it: https://github.com/jasp-stats/jasp-issues/issues/2022. You can read the discussion in the linked issue for workarounds on the current JASP version.

The issue was already fixed on our development version - so the next JASP release will not have this issue again. I am closing this GitHub issue for now as the bug is fixed for the next release and the other issue presents a solution on the current JASP version.

Thank you!

**Comment by paulamarentette** [comment]
Thanks,
I did look, and didn't find anything under Spearman's rho.
I appreciate the update.
Paula
