### ISSUE TITLE
[Bug]: LGCM "analysis terminated unexpectedly" when adding a factor to the model

### ISSUE THREAD

**Issue by GeryKarantzas** [jasp-stats/jasp-issues#2076]
### JASP Version

0.17.1

### JASP Module

SEM

### What analysis are you seeing the problem on?

Latent Growth Curve Modelling

### What OS are you seeing the problem on?

Windows 11

### Bug Description

I ran a latent growth curve model in JASP 0.17.1 the model includes 10 time points. The model runs fine prior to entering a factor variable (binary categorical variable - coded 1,2). When the factor is added to the model. The following message emerges... (Note the model ran fine with the factor variable included in the previous version of JASP I was using (which was 0.16.4).

This analysis terminated unexpectedly.

Error in solve.default(X[[i]], ...): Lapack routine dgesv: system is exactly singular: U[11,11] = 0

Stack trace
analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.lgcmFitTable(modelContainer, dataset, options, ready)

lavaan::fitMeasures(lgcmResult)

lavaan::fitMeasures(lgcmResult)

lav_fit_measures(object = object, fit.measures = fit.measures, baseline.model = baseline.model, fm.args = fm.args, output = output)

lav_fit_cfi_lavobject(lavobject = object, fit.measures = fit.measures, baseline.model = baseline.model, standard.test = standard.test, scaled.test = scaled.test)

lav_fit_fiml_corrected(lavobject, version = version)

lapply(Wm, solve)

FUN(X[[i]], ...)

solve.default(X[[i]], ...)

Note: I have attached the JASP file in which the error [occurs.](url)

[SoAR COVID Data_Wide Form_Abuse variables recoded_I3 Variables Only GK interactions_Class variable - JASP error.zip](https://github.com/jasp-stats/jasp-issues/files/11111269/SoAR.COVID.Data_Wide.Form_Abuse.variables.recoded_I3.Variables.Only.GK.interactions_Class.variable.-.JASP.error.zip)

### Expected Behaviour

The model should have at least run and provide a warning if the model was inadmissable.

### Steps to Reproduce

1. Enter continuous assessments into the variables dialogue box (psych_ab_sum_t1 to psych_ab_sum_t10)
2. Estimate the linear, quadratic and cubic models (covary latent curve)
3. Add IcubeClass nominal variable to factor dialogue box
...

### Log (if any)

[JASP 2023-03-30 22_15_26 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/11111410/JASP.2023-03-30.22_15_26.Desktop.log)
[JASP 2023-03-30 22_15_26 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/11111411/JASP.2023-03-30.22_15_26.Engine.1.log)
[JASP 2023-03-30 22_15_26 Engine 2.log](https://github.com/jasp-stats/jasp-issues/files/11111412/JASP.2023-03-30.22_15_26.Engine.2.log)
[JASP 2023-03-30 23_21_24 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/11111415/JASP.2023-03-30.23_21_24.Desktop.log)
[JASP 2023-03-30 23_21_24 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/11111416/JASP.2023-03-30.23_21_24.Engine.0.log)

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
I also get errors when entering a var in regression:


```
This analysis terminated unexpectedly.

Error in .lgcmEnrichData(dataset, options): object 'currentNa' not found

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.lgcmEnrichData(dataset, options)

options(na.action = currentNa)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

```
