### ISSUE TITLE
[Bug]: What is the small mark on all boxplots?

### ISSUE THREAD

**Issue by PerPalmgren** [jasp-stats/jasp-issues#2078]
### JASP Version

0.17.1

### JASP Module

Descriptives

### What OS are you seeing the problem on?

Windows 10

### Bug Description

What is that small tick mark that appears when running Box plots (see below)?
Kind regards
Per
[Namnlös.zip](https://github.com/jasp-stats/jasp-issues/files/11119852/Namnlos.zip)

### Expected Behaviour

Clean boxplot

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by PerPalmgren** [comment]
![Namnlös](https://user-images.githubusercontent.com/79397662/229068457-57292ded-0e21-4f0b-8267-fee931f18483.png)

**Comment by tomtomme** [comment]
@PerPalmgren 
This is just a normal tick mark of the x-axis. It makes more sense, when you see it with several boxplots next to each other. It could also be hidden, but it never bothered me. Is it a problem?
