### ISSUE TITLE
[Bug]: Crashing

### ISSUE THREAD

**Issue by seakanyasorn** [jasp-stats/jasp-issues#2079]
### JASP Version

Others

### JASP Module

Unrelated, ANOVA, T-Tests

### What OS are you seeing the problem on?

Windows 11

### Bug Description

when I open the JASP. After some time after i open the file, even I didn't do anything more, the program crashed and turned off.

### Expected Behaviour

the program should open smoothly

### Steps to Reproduce

1. open program
2. select file
3. after a while the program will crash
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by seakanyasorn** [comment]
![image](https://user-images.githubusercontent.com/120014497/229074791-f146f8b1-48db-4f55-b7f3-43e045acec9e.png)

**Comment by boutinb** [comment]
Hi @seakanyasorn, could also send the log files: https://github.com/jasp-stats/jasp-desktop/blob/stable/Docs/user-guide/logging-howto.md?
In the screenshot you send, you made a computer column. Do you have this problem also if you just open a Descriptives analysis for example? Does it happen always after a certain amount of time?

**Comment by seakanyasorn** [comment]
this is the test when I open a file with Descriptive and ANOVA.[image:
image.png].

And also these are the log file, I don't know which file could be chosen so
I send them all.

Thank you for the reply.

**Comment by boutinb** [comment]
Hi @seakanyasorn , if you want to add a file, add it in the GitHub issue (via email, it does not work). Can you also add the log files?

**Comment by seakanyasorn** [comment]
[JASP 2023-04-03 10_10_56 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/11144441/JASP.2023-04-03.10_10_56.Desktop.log)
[JASP 2023-04-03 10_10_56 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/11144442/JASP.2023-04-03.10_10_56.Engine.0.log)
[JASP 2023-04-03 10_10_56 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/11144443/JASP.2023-04-03.10_10_56.Engine.1.log)
[JASP 2023-04-03 10_10_56 Engine 2.log](https://github.com/jasp-stats/jasp-issues/files/11144444/JASP.2023-04-03.10_10_56.Engine.2.log)
[JASP 2023-04-03 10_10_56 Engine 3.log](https://github.com/jasp-stats/jasp-issues/files/11144445/JASP.2023-04-03.10_10_56.Engine.3.log)

Sorry for delay

**Comment by seakanyasorn** [comment]
After adding Safe graphics mod, still get the same error. These are the new log file that I try
[JASP 2023-04-19 13_54_27 Engine 2.log](https://github.com/jasp-stats/jasp-issues/files/11269627/JASP.2023-04-19.13_54_27.Engine.2.log)
[JASP 2023-04-19 13_54_27 Engine 3.log](https://github.com/jasp-stats/jasp-issues/files/11269629/JASP.2023-04-19.13_54_27.Engine.3.log)
[JASP 2023-04-19 13_54_27 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/11269630/JASP.2023-04-19.13_54_27.Engine.0.log)
[JASP 2023-04-19 13_54_27 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/11269631/JASP.2023-04-19.13_54_27.Engine.1.log)
[JASP 2023-04-19 13_54_27 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/11269632/JASP.2023-04-19.13_54_27.Desktop.log)

**Comment by boutinb** [comment]
I don't see what is going wrong here. Maybe you can try the last beta version of 0.17.2: https://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-stable-b2f8bdd54faf32e586f764743a9faa411ebe388d.msi ?

**Comment by tomtomme** [comment]
@seakanyasorn 
could you re-test with jasp 0.18.3?
