### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by mspezz** [jasp-stats/jasp-issues#2081]
### JASP Version

0.16.4

### JASP Module

Regression

### What analysis are you seeing the problem on?

Linear Regression - Stepwise

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

"This analysis terminated unexpectedly."

Error in model.frame.default

![Screenshot 2023-03-31 at 8 56 02 AM](https://user-images.githubusercontent.com/74941834/229170659-98180258-8086-4431-b7da-28504f2c5014.png)

### Expected Behaviour

Stepwise regression should run

### Steps to Reproduce

1. Enter dependent
2. Enter covariates
3. Select method: "Stepwise"
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
This is fixed. Tested with jasp 0.18.3 flatpak.
Please reopen if not fixed on your side!
