### ISSUE TITLE
Error in 3X3 RM ANOVA recurs

### ISSUE THREAD

**Issue by JorisGoosen** [jasp-stats/jasp-issues#2085]
@mpeters2:

I'm still getting this error

**Expected Behaviour**

Perform a 3x3 repeated-measures ANOVA.

**Steps to Reproduce**

Dataset imported from a csv file
Creating the experimental design by generating two 3-level factors. Unlike the previous poster, I get this with a pure repeated-measures ANOVA.

<img width="1508" alt="Screen Shot 2023-04-07 at 2 28 00 PM" src="https://user-images.githubusercontent.com/26334076/230659307-5e7ba152-12d7-4354-a3c3-dd7c29249eeb.png">

_Originally posted by @mpeters2 in https://github.com/jasp-stats/jasp-issues/issues/1712#issuecomment-1500530695_

**Comment by tomtomme** [comment]
tested with 0.18.3 and the data from the linked internal issue. I can confirm its fixed
