### ISSUE TITLE
[Bug]: no negative correlation

### ISSUE THREAD

**Issue by areeq1** [jasp-stats/jasp-issues#2086]
### JASP Version

0.17.1

### Commit ID

e5371ca8eb112816cd6b4ea47d9330617df21f67

### JASP Module

SEM

### What analysis are you seeing the problem on?

Partial Least Squared SEM 

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

When a correlation table is requested, negative correlations do not appear. Instead, the module would show <.001. Please see the screenshot. 
![Screenshot 2023-04-08 at 8 58 10 pm](https://user-images.githubusercontent.com/68887104/230736398-f42d3b2b-31a6-455b-8948-91a26c0b0298.jpg)

### Expected Behaviour

The module would show <.001 instead of a negative correlation 

### Steps to Reproduce

1. Request construct correlations under PLS-SEM

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@areeq1 
Can you re-test with jasp 0.18.3? If not fixed I need your data file. Rename it to .zip and then drag and drop here. Thx!

**Comment by 111rar** [comment]
Unfortunately. Still the same issue.

**Comment by tomtomme** [comment]
@111rar 
Can you send a data file showing this? Rename it to .zip and then drag and drop here. Thx!

**Comment by tomtomme** [comment]
@areeq1 @111rar 
Are you sure this is present in 0.18.3?
I cannot even get this table. The module has only the option to display Observed Covariances:

![image](https://github.com/jasp-stats/jasp-issues/assets/4428185/9ecac2bd-b0d3-4c55-967b-f18acb7cc45d)

My guess is, you opened your old analysis, where the correlation table is stil present. Then you would need to refresh the analysis, by setting and unsetting something.

So thx for your reports, bu I am closing this one until you can  drag and drop me a .jasp file that reproduces this. That would be so cool!
