### ISSUE TITLE
Closes due to "unexpected internal error" sometimes, and does not run analyses

### ISSUE THREAD

**Issue by pwsalw** [jasp-stats/jasp-issues#209]
## Template for bug reports
* JASP version: 9.0.0 and 9.0.1 (I tried both)
* OS name and version: Windows 7 Enterprise
* Steps to reproduce: 
Attempt to open a file in JASP:
![capture](https://user-images.githubusercontent.com/41090299/42542502-c23414ba-846c-11e8-92a7-4734123efb9e.PNG)

Or if that works, attempt to run analyses, but it won't show the analyses:
![capture2](https://user-images.githubusercontent.com/41090299/42542518-ce716a5c-846c-11e8-9df3-400abd19b747.PNG)

[AllData 7-7-18.zip](https://github.com/jasp-stats/jasp-desktop/files/2182419/AllData.7-7-18.zip)
The file seems to not save the data.

**Comment by FransMeerhoff** [comment]
If still has this problem still exists on the latest release version JASP 0.9.2 please reopen
