### ISSUE TITLE
[Bug]: After running a Bayesian independent sample t-test, a change in the settings (e.g., BF01 to BF10) leads to JASP recalculating the test.

### ISSUE THREAD

**Issue by hrgodmann** [jasp-stats/jasp-issues#2091]
### JASP Version

0.17.1

### JASP Module

T-Tests

### What analysis are you seeing the problem on?

Bayesian independent sample t-test

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

When I run an independent sample t-test and change settings that probably should not lead to a recalculation (like ticking BF01 instead of BF10), Jasp recalculates the whole test. This leads to a change in the raincloud plots when ticking back and forth between BF01 and BF10. Also I am not able to set a seed as the setting is grayed.

### Expected Behaviour

I think the t-test should not recalculate.

### Steps to Reproduce

1. Load in any data and perform an independent sample t-test (tried it with different)

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@hrgodmann 
changing that setting, needs to recalculate the BF. Why would you think that no recalculation is needed? Are you talking specifically about the plots? Then yes, those could stay, but only recalculating parts of the analysis would probably be a big design change in how jasps analysis modules work.

Regarding the seed - thats coupled to the non-parametric version of the test.
I hope that helps

**Comment by hrgodmann** [comment]
@tomtomme 
Hi thanks for answering to my issue! However, changing that setting should not lead to recalculation. But the issue does not persist in the newest version and can thus be closed.
