### ISSUE TITLE
[Feature Request]: MixedModelsLMM with only ~1 in fixed part

### ISSUE THREAD

**Issue by hugoquene** [jasp-stats/jasp-issues#2092]
### Description

allow LMM with intercept-only fixed part

### Purpose

1. To compare null model without and fuller model with predictor in their fixed part, while allowing random intercepts. 2. To assess ICC of empty model, as per Snijders & Bosker (1999, 1E). 

### Use-case

See e.g. Twisk (2010) Chapter 3?; Snijders & Bosker 1999 on ICC

### Is your feature request related to a problem?

Able to compare model with and without predictor, while taking random intercepts into account. 

### Is your feature request related to a JASP module?

Mixed Models

### Describe the solution you would like

In MixedModelsLMM, allow formula = y~1+(1|clusters), and report the LMM.

### Describe alternatives that you have considered

add a column of constants (1), and use that as predictor

### Additional context

Ideally I would also like to compare
y ~ 1 + (1|clusters), 
y ~ 1 + (1+x|clusters), 
and y ~ 1 + x + (1+x|clusters).
Currently only the latter LMM is possible. But comparing these three models is often relevant. 

See also Faraway (2006) p.171 (ISBN 978-1-58488-424-8)

**Comment by R180** [comment]
I *think* my request is the same. JASP does not allow an intercept-only logistic linear mixed effects model. The use case is to ascertain whether a proportion is significantly different from 0.5, while accounting for a random effect. See the attached JASP file. 
[will not run intercept-only logistic generalized linear mixed effects model.zip](https://github.com/jasp-stats/jasp-issues/files/12911426/will.not.run.intercept-only.logistic.generalized.linear.mixed.effects.model.zip)
