### ISSUE TITLE
[Bug]: Warning text is inconsistent with menu options

### ISSUE THREAD

**Issue by hugoquene** [jasp-stats/jasp-issues#2093]
### JASP Version

0.17.1

### JASP Module

Mixed Models

### What analysis are you seeing the problem on?

LinearMixedModels

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

LMM Model fitted with ML. 
Model Summary produces correct table, with helpful note (italics added):
 
_Note.  The model was fitted using restricted maximum likelihood. Please note that models with different fixed effects cannot be compared when REML is used. To use ML, switch 'Test model terms' to 'Likelihood ratio tests'._

The `Test model terms` field is in fact named `Test method` (under Options). 

### Expected Behaviour

Table note of model summary should refer to `Test method`, or `Test method` should be named `Test model terms`, in order to achieve consistency between the Table note and the menu. 

<img width="1140" alt="Screenshot 2023-04-12 at 22 27 24" src="https://user-images.githubusercontent.com/24574995/231578094-299f27af-f14b-42ce-8f9c-2bd4921f6af3.png">

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by FBartos** [comment]
thanks for reporting the issue! will be fixed

**Comment by hugoquene** [comment]
Thanks for the speedy resonse and fix! Best, Hugo
