### ISSUE TITLE
[Bug]: In the Summary Stats Bayesian independent t-test module, both groups are assigned number 1

### ISSUE THREAD

**Issue by hrgodmann** [jasp-stats/jasp-issues#2095]
### JASP Version

0.17.1

### JASP Module

Summary Statistics

### What analysis are you seeing the problem on?

Bayesian independent samples t-test 

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

In the Summary Stats Bayesian independent t-test module, both groups are named number 1 in the sample size specification (see Screenshot)
<img width="656" alt="Bildschirmfoto 2023-04-13 um 20 25 59" src="https://user-images.githubusercontent.com/109094700/231850185-ed708197-40db-4d22-83a2-93d59a770011.png">

### Expected Behaviour

It should be 1 and 2.

### Steps to Reproduce

1. Open the module

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by EJWagenmakers** [comment]
Did we miss this all these years? @vandenman can you fix this perhaps?

**Comment by akashrajkn** [comment]
@EJWagenmakers I think this happens only in the recent version. On `v0.16.1`, it says Group size 1 and Group size 2.
