### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by mollshea** [jasp-stats/jasp-issues#2096]
### JASP Version

0.17.1

### JASP Module

Summary Statistics

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

keeps shutting down when I try to get the histogram
<img width="1240" alt="Screen Shot 2023-04-14 at 6 52 46 PM" src="https://user-images.githubusercontent.com/130803697/232167948-6a6799cd-fd60-4d50-96cb-8ad5fa0469bb.png">

### Expected Behaviour

I just want the thing not to crash

### Steps to Reproduce

1.
2.
3.
...
  

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @mollshea I cannot reproduce it. Maybe it has to do with your dataset? Do you have the same problem with other dataset (from the Data Library/Descriptives Sleep dataset for example). If it still happens, could you send us the log files (https://github.com/jasp-stats/jasp-desktop/blob/stable/Docs/user-guide/logging-howto.md)?
