### ISSUE TITLE
[Bug]: changed labels but can't change values

### ISSUE THREAD

**Issue by z5136547** [jasp-stats/jasp-issues#2098]
### JASP Version

0.17.1

### JASP Module

Unrelated

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

My variable values include words, but I have changed the variable labels to be just numbers. When I export to CSV, it shows the value with words instead of the label with numbers. I also cannot change the variables from nominal to scale, even though I have changed all the labels to be numbers. It told me "Failed to convert column to continuous: values contain text."

Is there anyway I can export to CSV with numbers? And change the variable type to scale? 

Thanks so much.
<img width="357" alt="Screenshot 2023-04-15 at 6 44 57 PM" src="https://user-images.githubusercontent.com/130826459/232201821-57bbed9e-b28a-46c4-9443-cd01b3991a0c.png">
<img width="613" alt="Screenshot 2023-04-15 at 6 53 15 PM" src="https://user-images.githubusercontent.com/130826459/232202496-bed60589-9a19-431a-9857-143e481a687c.png">

### Expected Behaviour

numbers instead of words in the CSV file
<img width="430" alt="Screenshot 2023-04-15 at 6 46 58 PM" src="https://user-images.githubusercontent.com/130826459/232201911-81ba4896-678e-44e6-a26d-5f8bfff96b83.png">

### Steps to Reproduce

1. changed label names to numbers 
2. attempted to change from nominal to scale but can't
3. exported to csv but it shows the values instead of numbers

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Your data is messed up. Strip all words and equal signs from that variable in excel, leaving only the numbers. Then set the words as labels in jasp.
