### ISSUE TITLE
Enhanced Keyboard Shortcuts

### ISSUE THREAD

**Issue by humanfactors** [jasp-stats/jasp-issues#21]
JASP really needs to have more keyboard shortcuts. Suggestions include:
- Keyboard shortcut for each analysis
- Shortcut to add a variable to test column (this is vital, moving mouse to click each variable is time consuming when variables are not ordered the same as your factors).
- Shortcut to switch between different viewers

**Comment by tomtomme** [comment]
Can be closed, I guess. We have this kind of implemented via preferences => interface => ALT-navigation mode. Not the classical Strg+Something Shortcuts, but while a bit more complex, they are also more complete.

**Comment by boutinb** [comment]
Thanks for cleaning up !

**Comment by tomtomme** [comment]
Yeah, I hope this helps a bit to keep track of all the nice feature requests :D
