### ISSUE TITLE
[Bug]: Bayesian Paired-Samples t-test (Wilcoxon) - Won't run with ordinal data, but will with scale data.

### ISSUE THREAD

**Issue by JayD05** [jasp-stats/jasp-issues#2102]
### JASP Version

0.16.4

### JASP Module

T-Tests

### What analysis are you seeing the problem on?

Bayesian Paired-Samples t-test / Wilcoxon

### What OS are you seeing the problem on?

Windows 10

### Bug Description

In attempting to run a Bayesian t-test / Wilcoxon I noticed that the analysis would not run if data were ordinal, but would run if the same variables were relabelled as scale data. Further, Frequentist t-test/Wilcoxon will run with ordinal, but Bayesian equivalents will not (even though the same variables are used). See example below:

When data are coded as ordinal:

![ordinal data](https://user-images.githubusercontent.com/120119018/232768342-c53dc8c3-e90d-406e-ba09-a7db5f4b432e.PNG)

Frequentist Wilcoxon runs fine:

![ordinal test](https://user-images.githubusercontent.com/120119018/232768697-10a0a066-7ec7-45c7-aee2-80070052b790.PNG)

However, Bayesian returns the following error ("Number of observations < 2 in [Var1 & Var2]"), which doesn't make any sense as there are > 2 observations (as shown by the Frequentist analysis running fine):

![ordinal bayes test](https://user-images.githubusercontent.com/120119018/232769042-ac508867-cf0c-409e-9491-de5becc69fcc.PNG)

Note. The same issue exists for both paired-samples t-test and Wilcoxon.

Changing the same variables from ordinal to scale:

![scale data](https://user-images.githubusercontent.com/120119018/232769477-b796497a-124b-444a-a6ae-e92087ba0cad.PNG)

Rerunning the Bayesian analysis shows that it now works fine:

![scale test](https://user-images.githubusercontent.com/120119018/232770104-9b0e8d9e-8d96-49b6-baf7-caf7287b4bbb.PNG)

Data:

[jasp data.zip](https://github.com/jasp-stats/jasp-issues/files/11261435/jasp.data.zip)

### Expected Behaviour

The t-test / Wilcoxon should run regardless of whether data are ordinal or scale.

### Steps to Reproduce

1. Run analysis with ordinal variables
2. Change data type on variables from ordinal to scale
3. Rerun same analysis with scale variables
4. JASP will run when data are scale but not ordinal
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@JayD05 @vandenman 
tested with jasp 0.18.3 and your data. I had to switch to scale and then ordinal again - then everything worked. But on that switch the labels were lost. I re-entered labels and the bug was there again.

So this bug is isolated to ordinal data with labels
here the file that shows this directly
[ddaf.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/14201208/ddaf.jasp.zip)

**Comment by JohnnyDoorn** [comment]
Somehow the Bayesian t-test (any) looks at the labels instead of the values.. when I use facFive from the debug data set it's fine, but when i adjust the labels to a-e instead of 1-5, it breaks. Descriptives, freq t-test and other analyses still work fine though.
