### ISSUE TITLE
[Feature Request]: Regression

### ISSUE THREAD

**Issue by Chuckysmaster** [jasp-stats/jasp-issues#2105]
### Description

Evaluation of a moderated multiple regression

### Purpose

statistics

### Use-case

Evaluation 2xPrädiktors; 1xModerator; 1xKriterum

### Is your feature request related to a JASP module?

Regression

### Describe the solution you would like

Proposed solution to evaluate my data with a moderated multiple regression

### Additional context

For my master's thesis, I would like to perform a moderated multiple linear regression analysis. This includes P1, P2, a moderator and a criterion. Could you please tell me how I can do the analysis using JASP?

**Comment by tomtomme** [comment]
@Ghassan-Okour @Chuckysmaster 
see https://jasp-stats.org/2020/03/12/mediation-and-moderation-analysis-in-jasp/
on how to do a moderation analysis with multiple regression. You can additionaly use flexplot (visual modeling module) to look into the interaction more closely.
Hope this helps!
Also the new process module enables even more complex moderation/mediation analysis!
