### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by zbagla** [jasp-stats/jasp-issues#2109]
### JASP Version

0.17.1

### JASP Module

Regression

### What analysis are you seeing the problem on?

Linear Regression

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

How do I solve this? tried the backward method for regression, it worked for other regressions, just not this exact one.

![Screenshot 2023-04-26 at 16 10 17](https://user-images.githubusercontent.com/119601727/234585206-c638e7f4-fff1-47a7-8a1a-00fdeb609ab8.png)

### Expected Behaviour

Just get all the regression tables

### Steps to Reproduce

1. Run a backward linear regression

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
I tested backward regression in jasp 0.18.3. All fine.
Maybe this was specific to your data. Pleas reopen, if you can share your jasp file. Rename it to .zip first, then drag and drop here. thx.
