### ISSUE TITLE
Overlap in plot text Bayesian linear regression

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-issues#211]
@vandenman 

The BAS "plot of coefficients" has overlapping text for the interval endpoints when the 95% credible interval is near zero. Maybe check how we solved this for the Bayesian t-test?

![image](https://user-images.githubusercontent.com/8603015/42756825-109446bc-88fe-11e8-8d60-a7619864e084.png)

**Comment by AlexanderLyNL** [comment]
Fixed by https://github.com/jasp-stats/jasp-desktop/pull/2921
