### ISSUE TITLE
[Feature Request]: Raincloud plots also in the Descriptives Section

### ISSUE THREAD

**Issue by hrgodmann** [jasp-stats/jasp-issues#2112]
### Description

It would be nice to have Raincloud plots (like in the ANOVA section during the analysis) also in the Descriptives section.

### Is your feature request related to a problem?

No

### Is your feature request related to a JASP module?

Descriptives

**Comment by tomtomme** [comment]
@hrgodmann 
now tracked here https://github.com/jasp-stats/jasp-issues/issues/1698
Lets discuss there.
