### ISSUE TITLE
[Bug]:  Pearson's Correlation table not working properly

### ISSUE THREAD

**Issue by Sininejuust** [jasp-stats/jasp-issues#2113]
### JASP Version

0.17.1

### JASP Module

Regression

### What analysis are you seeing the problem on?

Correlation

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I'm trying to check out all correlations between my variables (there are 64 of them), but when doing a Pearson's correlation, the table doesn't show me the info correctly.... or show the info at all. I'm including photos of the table it does produce. As you can see, it's definitely not looking right and also stops randomly. I tried to do this once a week ago and then it worked properly, but I forgot to write down some things so wanted to do it again today but.. :( Tried restarting jasp several times, but nothing works. 
![image](https://user-images.githubusercontent.com/106011618/235155856-921d25d7-1cac-40f9-a65b-3cf67e38e296.png)
![image](https://user-images.githubusercontent.com/106011618/235155939-e394c278-4af4-4f7e-8dad-bec0612c5d54.png)
![image](https://user-images.githubusercontent.com/106011618/235155992-3dfea75b-d3db-48a1-b68c-110dbe5d75ac.png)

### Expected Behaviour

I was expecting a table looking more like this one: 
![image](https://user-images.githubusercontent.com/106011618/235156626-0935a1fe-97b8-4d3f-8d42-5b1474e46b9b.png)
(Image taken from the internet)

### Steps to Reproduce

1. Click on regression
2. Choose classical correlation
3. Input all your variables
4. Get the result I got
![image](https://user-images.githubusercontent.com/106011618/235156922-bffe7cf8-d14a-431b-8af4-25454a6a1689.png)

### Log (if any)

Tried to attach log files but I can't figure out how to correctly do them so they're all blank, didn't include them. 

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [x] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by Sininejuust** [comment]
Here's what I've tried so far:
Uninstalled and installed jasp again
Tried on a different computer
Tried on the same computer but with a previous version (0.16.4)

None of these helped, still getting the same messed up table. Please help, I'm kind of running behind on my thesis....

**Comment by Sininejuust** [comment]
Turns out that spearman's rho table is doing the same thing

**Comment by Kucharssim** [comment]
Hi @Sininejuust,

sorry that this is happening to you. Unfortunately I am unable reproduce the issue. 

Could you share your data with us? You can either zip the jasp file and attach it here in the GitHub issue webpage. Alternatively you can send me the jasp file to s.kucharsky@jasp-stats.org. 

Thank you!

**Comment by Kucharssim** [comment]
Dear @Sininejuust,

thanks for sending the file!

It seems the column names break the main table for some reason. I will investigate why and fix it.

In the meantime, you have two options as a workaround:

1. Select the option "display pairwise" - in this case the table is not broken so it should give you the results.
2. Rename the columns to get rid of the `[` and `]` characters. For example instead of names like `BDSMG1[BDSM1]` using `BDSMG1_BDSM1` should give you the correct table.

**Comment by tomtomme** [comment]
@Kucharssim 
Can confirm, that this is still a problem with 0,18.3

**Comment by tomtomme** [comment]
and this one is related / similar, but anova module: https://github.com/jasp-stats/jasp-issues/issues/1503

**Comment by tomtomme** [comment]
@Sininejuust 
closing, as now tracked here: https://github.com/jasp-stats/jasp-issues/issues/2564
