### ISSUE TITLE
[Bug]: Incorrect mean differences calculated for post hod test

### ISSUE THREAD

**Issue by samamarco** [jasp-stats/jasp-issues#2114]
### JASP Version

0.17.1

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

post hoc tests

### What OS are you seeing the problem on?

Windows 10

### Bug Description

When computing post hoc tests for a rather large anova, the mean-differences were not correct. When I manually checked the mean differences, I received a different number. I confirmed the two mean values in the descriptives plot, and that the variables were correctly assigned to the proper cells, and still noticed the mean differences were calculated incorrectly.

A link to the screenshot showing the error, as well as the jasp files and csv file can be found here

https://drive.google.com/drive/folders/1wP6hH5Uecoa9xHzkMU0lutveqzB5E_1U?usp=share_link 

### Expected Behaviour

The actual mean difference should be 0.701

### Steps to Reproduce

1. I restarted the analysis from scratch on a different JASP sheet and using a manually-created excel spreadsheet 
2.the error still happend
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by samamarco** [comment]
> I looked further into it and realized that JASP calculates the weighed mean for unequal ns differently than how I assumed, even though the overall two levels of dst vs fcl have the same n, the other between subject factor has a slightly different n for each. When I learned that, I managed to replicate it manually

**Comment by JohnnyDoorn** [comment]
Great, in that case I'll close this for now - please reopen if you have additional questions!
