### ISSUE TITLE
[Bug]: The name of the network analysis centrality indicator is incorrect

### ISSUE THREAD

**Issue by zhangzheng19971121** [jasp-stats/jasp-issues#2115]
### JASP Version

0.16.2

### JASP Module

Network

### What analysis are you seeing the problem on?

NA

### What OS are you seeing the problem on?

Windows 10

### Bug Description

The drawing process confuses two centrality indexes, degree and strength

### Expected Behaviour

The drawing process confuses two centrality indexes, degree and strength

### Steps to Reproduce

The drawing process confuses two centrality indexes, degree and strength

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@zhangzheng19971121 
Thx for the report. I cannot see a problem anymore with jasp 0.18.3. Plot and Table seem coherent.
Pls reopen if not fixed on your side.
