### ISSUE TITLE
[Bug]: Error in options$homogeneityCorrectionBrown || options$homogeneityCorrectionWelch: invalid 'x' type in 'x || y'

### ISSUE THREAD

**Issue by EthanF12** [jasp-stats/jasp-issues#2118]
### JASP Version

Others

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

Mixed ANOVA

### What OS are you seeing the problem on?

Windows 11

### Bug Description

Error came up whilst using simple main effects, seems to be happen when trying to use between subjects (Independent Measure IV) as simple effect factor, and within subjects (Repeated Measure IV) as moderator factor. It won't complete analysis.

### Expected Behaviour

Should have just given me the simple main effects for my between subjects variable interacting with within subjects variable

### Steps to Reproduce

1.
[Data_Q1 (1).csv](https://github.com/jasp-stats/jasp-issues/files/11378303/Data_Q1.1.csv)
Start Mixed ANOVA, so Verb as independent IV and Time as repeated measure IV, looking at interaction effect in simple main effects.
Try to use simple main effects for Verb (word context) as simple effects factor, then Time (Time period) as moderator factor.
2.
3.
...

### Log (if any)

tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.rmAnovaSimpleEffects(rmAnovaContainer, dataset, longData, options, ready)

.anovaResult(rmAnovaContainer[['simpleEffectsContainer']], options = simpleOptions)

Stack trace shown after error

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JohnnyDoorn** [comment]
Thanks for reporting this, we were aware of this issue, and it will be fixed in the May release.
