### ISSUE TITLE
[Feature Request]: generic chart option

### ISSUE THREAD

**Issue by rjgoif** [jasp-stats/jasp-issues#2120]
### Description

To allow for generic chart creation from simple elements, like a GUI version of ggplot2 of the SPSS graph builder

### Purpose

To allow users to generate charts in the same style as those automatically produced by the statistical modules in JASP. 

### Use-case

Plotting the odds ratios with error bars from a logistic regression, or make a descriptive plot of current data with summary statistics from another published analysis. 

### Is your feature request related to a problem?

no

### Is your feature request related to a JASP module?

Descriptives

### Describe the solution you would like

A simple drag and drop graph option where fields like data geometry (bars, dots, lines, etc) and other elements (error bars/areas/lines, shape coding, size coding, paneling, etc) can be tied to colums of a dataset. 

### Describe alternatives that you have considered

A tricky solution is generate a fake dataset that has the desired parameters (e.g. a mean and standard deviation that equal the central value and error bars of your real data), however this is a pretty janky workaround. 

### Additional context

JASP could not only be a great alternative to SPSS (but free!) and R (without needing to code!), but also Graphpad Prism which is more flexible in the kinds of charts you can create. I would love to see features that combine the best parts of Graphpad Prism and SPSS visualization flexibility.

**Comment by tomtomme** [comment]
@rjgoif & @dustinfife 
Are you aware of jasps visual modeling module => flexplot? This is not exactly what you describe, but I wonder if it would be easier to integrate this functionality within flexplot in comparison to starting from scratch.

**Comment by dustinfife** [comment]
Flexplot already does most of this. At one time I talk to @EJWagenmakers about embedding flexplot graphs in all analyses, but I don't remember what ended up happening with that.

**Comment by tomtomme** [comment]
Yeah. 
My vote would be, to put flexplot as a submodule under descriptives with the name "magic plots".  
And the other plot options we already have, they would fit in a second submodule with the name "manual plots" :D
That would be so next level!

@EJWagenmakers 
What do you think?

**Comment by vincentott** [comment]
Should I still first finish the raincloud plots as a standalone module?
And then the re-organization of the Descriptives module happens afterwards?

I am also curious: Would there still be a plotting module planned for the long-term? Or would the Descriptives module get its own plotting subsection with flexplots, rainclouds, histograms etc.?

**Comment by EJWagenmakers** [comment]
"Should I still first finish the raincloud plots as a standalone module?
And then the re-organization of the Descriptives module happens afterwards?" -> yes
"Or would the Descriptives module get its own plotting subsection with flexplots, rainclouds, histograms etc.?" -> I think that would make most sense
EJ

**Comment by tomtomme** [comment]
@rjgoif @dustinfife 
Flexplot and Timeseries are now submodules of descriptives with 0.19 beta. Rainclouds will be next shortly. So I am closing this one for now. Please reopen if you disagree!

**Comment by tomtomme** [comment]
@rjgoif 
Progress on a generic plot builder can be followed here: https://github.com/jasp-stats/jaspDescriptives/pull/345 and https://github.com/jasp-stats/jasp-issues/issues/3083
