### ISSUE TITLE
[Bug]: No display of plots and charts

### ISSUE THREAD

**Issue by BorislavaD** [jasp-stats/jasp-issues#2121]
### JASP Version

0.16.4

### JASP Module

ANOVA, Frequencies, Mixed Models, Regression, T-Tests

### What analysis are you seeing the problem on?

Linear regression, Independent and Dependent T-test, One way/Two way ANOVA, ANCOVA. Factorial ANOVA

### What OS are you seeing the problem on?

Windows 11

### Bug Description

The visal modeling option doesn't work almost at all. I cannot present my analysis visually and create more coomplex and visually descriptive charts.
<img width="763" alt="image" src="https://user-images.githubusercontent.com/132648946/236398243-29aecf7f-933c-4844-a697-95574d455fdb.png">

### Expected Behaviour

Plots and charts should appear to present the computed data

### Steps to Reproduce

1. Run a linear regreassion or some other analysis
2.Go to either Marginal effects plots or to the option of Visual Modeling
3.Include the variables I am interested in and the program crashes
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@BorislavaD 
flexplot got some updates in the past. Please re-test with jasp 0.18.3 and reopen, if still a problem and you can share your jasp file as described by Simon above. Thx!
