### ISSUE TITLE
[Feature Request]: Percentage in charts and other graphics

### ISSUE THREAD

**Issue by romanogino** [jasp-stats/jasp-issues#2124]
### Description

 The graphs are simple and good, but without percentages they do not convey complete information

### Purpose

 Improve communication of results

### Is your feature request related to a JASP module?

Descriptives

### Describe the solution you would like

 A button that allows you to add or remove the percentages, with one, two and three decimal places, in any graph. Perhaps absolute numbers too.

### Describe alternatives that you have considered

 I add them manually with other image editing software.

### Additional context

With the percentages of each portion, the interpretation would be easier.
![image](https://user-images.githubusercontent.com/1270242/236632985-0ec29e8b-95ce-40c8-8bfe-a0c596375429.png)

**Comment by tomtomme** [comment]
Now tracked in #2123
