### ISSUE TITLE
[Feature Request]: Integration of GPT-like AI for Enhanced Explanation of Interface and Results

### ISSUE THREAD

**Issue by dimleyk** [jasp-stats/jasp-issues#2128]
### Description

I propose the integration of an AI language model, such as GPT or similar, into JASP for the purpose of enhancing explanation of the software interface and the results generated by various outputs.

### Purpose

The goal is to improve the overall user experience by offering clearer, more detailed explanations of the software's features and the results of statistical analyses. This feature would make statistical analysis more accessible to users with varying degrees of familiarity with statistical methods and terminology.

### Use-case

When a user hovers over a checkbox or a selection for a statistical test or software feature, a tooltip appears explaining what it is in simple and plain language. After a user completes an analysis, they can input the test output values, name of the analysis, reporting style (e.g., APA), and desired tone into the AI via an API. The AI then generates a report or explanation based on these inputs.

### Is your feature request related to a problem?

Yes, this feature request aims to address the difficulty some users may have in understanding the functionalities of JASP and interpreting the results of their analyses.

### Is your feature request related to a JASP module?

Other

### Describe the solution you would like

I would like to see an AI language model integrated into JASP. Offline, it would provide tooltips explaining each statistical test and software feature. Online, it would utilize an API to provide detailed explanations of analysis results based on user-provided input. Advanced settings such as report length would be configurable.

### Describe alternatives that you have considered

One alternative would be to expand the existing help documentation or to add more detailed tooltips manually. However, this would not offer the same level of customization and adaptability that an AI model would.

### Additional context

Incorporating this feature would not only improve the JASP user experience but also attract new users who might be initially intimidated by the complexity of statistical analysis. Furthermore, it would align with the growing trend of AI-assisted software interfaces, solidifying JASP's position as an innovative leader in the field of statistical analysis software.

**Comment by EJWagenmakers** [comment]
We have this (and similar ideas) under consideration!

**Comment by tomtomme** [comment]
closing, since this is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/2010

**Comment by tomtomme** [comment]
@dimleyk 
this is available now
