### ISSUE TITLE
Bug Report: JASP 0.9.01 Mauchly's test of sphericity claiming RM factor has only 2 levels

### ISSUE THREAD

**Issue by Salt54J** [jasp-stats/jasp-issues#213]
* JASP version: 0.9.01
* OS name and version: Windows 10 Pro, Version 10.0.17134
* Analysis: Repeated Measures ANOVA with a between-subjects factor. Mauchly's test of sphericity.
* Steps to reproduce: Repeated measures ANOVA with several levels to an RM factor. Add a between subjects factor. Check box for sphericity tests.

Sometimes Mauchly's test of sphericity is saying my RM Factor has only 2 levels when it actually has many levels. This only seems to happen sometimes. With most datasets it is fine. I have attached a raw data file, JASP file and output file for an instance where the RM factor has 15 levels and yet JASP is saying that Mauchly's won't run because there are only 2 levels in the RM factor.

[JASPbugreport-Mauchly.zip](https://github.com/jasp-stats/jasp-desktop/files/2248064/JASPbugreport-Mauchly.zip)

**Comment by AlexanderLyNL** [comment]
@JohnnyDoorn is this fixed by the way?

**Comment by vicenteinefo** [comment]
I have the same issue...

JASP version: 0.9.1
OS name and version: Mac OS El Capitan 10.11.6

**Comment by JohnnyDoorn** [comment]
This will be fixed in the new release (0.9.2).
