### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by tnwlsl81** [jasp-stats/jasp-issues#2130]
### JASP Version

0.17.1

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

correlations

### What OS are you seeing the problem on?

Windows 11

### Bug Description

Hello,
It may not be a bug, but I am having an issue with changing the column from nominal to scale. 
It kept saying I have text but I do not have any text in my file.
I have been using JSAP for a while and it is the first time this happens.  
I attached the JASP zip file here. 
[asr0.zip](https://github.com/jasp-stats/jasp-issues/files/11450218/asr0.zip)
Thank you for your help!

### Expected Behaviour

I hope that I can change the column to scale.

### Steps to Reproduce

1. When I open the file and try to change the type of column, it did not let me. 
2.
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @tnwlsl81 I see that the last row of your data has again the name of your variables:
![Screenshot 2023-05-11 at 12 06 58](https://github.com/jasp-stats/jasp-issues/assets/503332/0e5ba3d6-9cef-4b26-82e5-3f8e6554fd62)

So you need first to clean your data.
