### ISSUE TITLE
[Feature Request]: Open Excel (.xls/.xlsx) data files

### ISSUE THREAD

**Issue by mjkofler** [jasp-stats/jasp-issues#2134]
### Description

Currently, only able to open .CSV files

### Purpose

Avoid having to export data files from .XLSX to .CSV, which removes all formulas, formatting, etc.

### Use-case

Opening .xlsx files directly, like JAMOVI does, saves time and reduces errors

### Is your feature request related to a problem?

Often, we do a lot of data processing in Excel (computing variables etc.). That file then has to be exported to CSV to be opened in JASP. Then, any time we need to make a change, we have to update the Excel file, re-export, then update the JASP file.

### Describe the solution you would like

ability to directly open .xlsx Excel files

### Describe alternatives that you have considered

None

**Comment by tomtomme** [comment]
Dear mjkofler, you do NOT have to export to CSV. You can save your XLSX as an ODS in Excel using the "save as" menu and scrolling to the very end of all the available file types. Both file formats (ods and xlsx) are very similar and you would not loose any formulas etc. And you can of course open the ODS in JASP directly.

**Comment by tomtomme** [comment]
@mjkofler 
Feel free to close this issue since its also discussed in
https://github.com/jasp-stats/jasp-issues/issues/611

**Comment by shun2wang** [comment]
Importing Excel .xls/.xlsx file is a valid request and I have a plan to implement it.
