### ISSUE TITLE
[Bug]: Modules not showing in alphabetical order in modules list?

### ISSUE THREAD

**Issue by patc3** [jasp-stats/jasp-issues#2135]
### JASP Version

Others

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 10

### Bug Description

![image](https://github.com/jasp-stats/jasp-issues/assets/41131893/791b402d-f458-4bd0-b3e0-fbc2636cadfe)

### Expected Behaviour

Expected: Power, Prophet, Quality Control

### Steps to Reproduce

1. open jasp
2. click module list

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by patc3** [comment]
it's in version 0.17.2, but this version is not available in the dropdown list to select from

**Comment by shun2wang** [comment]
fixed by https://github.com/jasp-stats/jasp-desktop/commit/6bf63c30fe65229dba37c9aa87f1defb77fb7276 and btw 0.172 is released now.

**Comment by patc3** [comment]
I'm using 0.17.2 of course, the power module didn't exist before then. So I don't think the fix made it to the deployed version.

**Comment by shun2wang** [comment]
Hi @patc3 thanks for your report. yes we did fixed this yesterday but this build not uploaded as official released version.

@boutinb @CGuazzoneJASP can you have a look for this?
