### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by dknf** [jasp-stats/jasp-issues#2136]
### Description

Silent installation

### Purpose

Deploy JASP with MDT

### Use-case

University

### Is your feature request related to a problem?

Last version of "JASP" is not deployable in silent installation

### Describe the solution you would like

I would like to have the latest version of JASP compatible in silent installation if possible please

### Describe alternatives that you have considered

https://github.com/donovaly/JASPInstProj/releases/tag/0.1 (There is a version on Github deployable in silent installation but the version is too old)

### Additional context

Thank you for your help

**Comment by tomtomme** [comment]
@JorisGoosen 
Is this possible now with msix and installation from the windows store?

@dknf 
Would it help in your university setting to install from windows store and could jasp silently auto-update from there?

**Comment by RensDofferhoff** [comment]
With our new Windows store entry University ICT departments should have a lot more tools to work with JASP.
If truly you need the appx offline for MDT you can get it like so https://woshub.com/how-to-download-appx-installation-file-for-any-windows-store-app/.
We may provide this one in the future on the site but I will need to discuss this with the team
