### ISSUE TITLE
[Bug]: Unreadable font color in variable selection menus

### ISSUE THREAD

**Issue by yetipowers** [jasp-stats/jasp-issues#2137]
### JASP Version

0.17.1

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

The problem does not have to do with the analyses, it concerns the variable selections.

### What OS are you seeing the problem on?

Arch

### Bug Description

Since the new update (quite a few weeks) I have several issues, the most crucial issue is that the font color is ironically the opposite it should be – in dark theme it has dark font color, in light theme white color, when selecting variables.
I tried to change the text options but no effect – there is also not the option to change the font color.
I am also unable to change the user interface language and many other options anymore, but that's a different, not so crucial issue.

Here you can see the font colors:
![issue - light theme](https://github.com/jasp-stats/jasp-issues/assets/43173999/aff89318-2729-47ae-8bc2-1abd557dc7ba)
![issue - dark scheme ](https://github.com/jasp-stats/jasp-issues/assets/43173999/137bc01b-7ab5-4ab2-8ba7-f3866cc68328)

I did not change anything as far as I know in the settings from the user interface, apart from switching to German.

Now I am even unable to change from German to English, or choose a different font which is currently activated. In the dropdown list I can select a font, but after clicking the preferred font, it still stays the same. The same issue occurs with language selection. I tried QT Text, but the font color issue stayed the same.

![User Interface Options](https://github.com/jasp-stats/jasp-issues/assets/43173999/ecca9b76-cac6-4194-99f9-a7f586cdb647)

### Expected Behaviour

Font color should be readable: light theme = black font color, dark theme: white font color.

### Steps to Reproduce

1. When selecting an analysis, search for the variable.
2. Need to click on the variable, which gets readable because of background highlighting in grey.
3.
...

I am not certain how to reproduce this issue .. It seems that not many users have the same problem since update I haven't found a request like this? I have no idea what could be wrong, it one day just appeared like so. I can still run most analyses, it is just a bit cumbersome to select the correct variables.

Are there not any hidden configuration options to change the font colors?

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
I am also on flatpak (manjaro) . Maybe I can help. Can you give me the output of the command
`flatpak list | grep JASP`
And have you tried
`'flatpak repair'`
or uninstalling all JASP version & then re-installing JASP?

At some point in the past I had flatpak problems, because I ran stable and beta and that mixed up some settings or cache-files. So if nothing of the above helps you could also try to delete these folders / config files e.g.:

/home/thomasl/.JASP/
/home/thomasl/.var/app/org.jaspstats.JASP/

**Comment by tomtomme** [comment]
also - are you maybe using some kind of darkmode via your desktop environment? I am on KDE light mode. What do you use?

**Comment by RensDofferhoff** [comment]
As @tomtomme suggested its probably best to throw out some old configuration and cached files along with a reinstall to check if that resolves it.

So remove:
/home/<username>/.JASP/
/home/<username>/.var/app/org.jaspstats.JASP/
/home/<username>/.config/JASP

flatpak uninstall org.jaspstats.JASP
flatpak install flathub org.jaspstats.JASP

We just have a new version out as well!

**Comment by yetipowers** [comment]
Thank you a lot for the  support! The update fixed the issue, I didn't have to delete my config files. If the same problem should occur in the future, I would then first try to delete my config files. Btw I am using a window manager (dwm), no KDE. Thank you so much I can finally see all my variables again!! Have a nice day! Kind regards :)
