### ISSUE TITLE
Enhancement: Heat map function for correlation matrix 

### ISSUE THREAD

**Issue by Freeopenstat** [jasp-stats/jasp-issues#214]
Request:
I think a heat map function for correlation matrix for Pearson, Spearman and Kendall would be very good. I think it would be ideal to have this kind of function because it is frequently used across many disciplines.

**Comment by Kucharssim** [comment]
I think this has been implemented in version 0.12. @Freeopenstat feel free to reopen this issue if the current functionality is not what you wanted.
