### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by evanmiltenburg** [jasp-stats/jasp-issues#2140]
### JASP Version

0.17.1

### JASP Module

Reliability

### What analysis are you seeing the problem on?

Krippendorff's alpha

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

There's a discrepancy between Krippendorff's alpha scores returned by JASP and Jamovi (using the seolmatrix module). Full description here: https://github.com/hyunsooseol/seolmatrix/issues/5#issuecomment-1549261300

### Expected Behaviour

The scores should be the same for the two implementations, but they are not. (Fleiss kappa is the same, so it does not seem to be a data issue). Compare:

JASP:
<img width="1360" alt="Screenshot 2023-05-16 at 12 02 08" src="https://github.com/jasp-stats/jasp-issues/assets/1513355/7d66af37-0df4-41a5-b577-34665eb1db2f">

Jamovi:
<img width="1392" alt="Screenshot 2023-05-16 at 12 02 50" src="https://github.com/jasp-stats/jasp-issues/assets/1513355/f4208d66-2680-4f99-b903-296583dbaf7f">

### Steps to Reproduce

1. Open the file (attached).
2. JASP: Run Reliability/rater agreement/Krippendorff's alpha (ordinal)
3. Jamovi: Use the Seolmatrix module to compute Krippendorff's alpha through the menu.

[voorbeeld_hoge_agreement.ods](https://github.com/jasp-stats/jasp-issues/files/11486498/voorbeeld_hoge_agreement.ods)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by evanmiltenburg** [comment]
It is not clear to me why the scores differ and where the bug is. Given the Kappa scores I am inclined to believe JASP is correct, but I'm not 100% sure.

**Comment by juliuspfadt** [comment]
Thanks for creating the issue @evanmiltenburg. What we do for Krippendorffs alpha before the calculating is to transpose the data matrix before the estimation. So the coefficient in JASP assumes that the rows of a data matrix should contain the coders and the columns the units of analysis (see [wikipedia](https://en.wikipedia.org/wiki/Krippendorff%27s_alpha)). I am not really sure if that is in concordance with how you wish to structure your data, but this all seems like desired behavior. Maybe we should put a clear note in the help file though.

**Comment by juliuspfadt** [comment]
given the high correlations among the coders/raters in your dataset I think the JASP results are correct.

**Comment by evanmiltenburg** [comment]
Thanks, that makes sense! Interesting that alpha uses rows and requires the transposed matrix, while all other approaches use columns.On 16 May 2023, at 13:57, Julius Pfadt ***@***.***> wrote:﻿
given the high correlations among the coders/raters in your dataset I think the JASP results are correct.

**Comment by juliuspfadt** [comment]
Yes, this has been a headache since the implementation :)

**Comment by evanmiltenburg** [comment]
It's an interesting issue though, because in some fields the transposed format may have become the standard. (Due to Krippendorff's original implementation.) In that case it makes sense to make the transpose option visible in the interface, e.g. through a dropdown menu with "Raters are columns" (default) versus "Raters are rows" (optional).

But my original question has been answered, so feel free to close this issue. Thanks again!
