### ISSUE TITLE
[Bug]: Error editting plot 

### ISSUE THREAD

**Issue by dilasuay** [jasp-stats/jasp-issues#2144]
### JASP Version

0.17.2

### JASP Module

Visual Modeling

### What analysis are you seeing the problem on?

Flexplot

### What OS are you seeing the problem on?

Windows 10

### Bug Description

Hello, I am not able to edit Flexplots y-axis manually. When I tried to change the values, the following error message appeared. 
![Ekran görüntüsü 2023-05-16 210855](https://github.com/jasp-stats/jasp-issues/assets/50375381/d3b7da55-653e-4be0-a3e9-60fba8980dc8)
How can I solve this problem? 

### Expected Behaviour

The graph y-axis should be edited as I desire.

### Steps to Reproduce

1. load data 
2. click visual modelling >flexplot
3. put dependent variable (scalar)
4. 2 independent variable (both nominal)
5. plot appears very well but its too narrow to see the interaction effect 
6. so I click FlexPlot> edit image > y-axis >advanced>set manually 
7. Error massage!
8.
9.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by dilasuay** [comment]
I also realized that when I play with the different intervals (quartiles, standard error, or standard deviation), it is possible to edit normally for a while. Then the error message pops up eventually.

**Comment by shun2wang** [comment]
Hi @dilasuay thank you for report. could you add a JASP file (by zip it and upload in comment) which including this error? seems I can not reproduce this with my dataset.
