### ISSUE TITLE
[Bug]: This analysis terminated unexpectedly

### ISSUE THREAD

**Issue by Stellina01** [jasp-stats/jasp-issues#2145]
### JASP Version

0.17.2

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

Repeated Measures ANOVA

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

<img width="1334" alt="Capture d’écran 2023-05-17 à 14 11 12" src="https://github.com/jasp-stats/jasp-issues/assets/133875591/cdeaa9f9-633f-4531-b4bb-41225daf8ff2">
An error message appears when I try to use the repeated measures ANOVA.

### Expected Behaviour

Two tables should appear with "within subjects effects" and "between subjects effects".

### Steps to Reproduce

1. In Repeated Measures ANOVA, create a RM factor.
2. Put data in the repeated measures cells.
3. Put data in "between subjects factors".
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JohnnyDoorn** [comment]
@Stellina01 thanks for reporting this! there seems to be an issue in the latest mac-release with some packages - we are working on a hotfix currently! 
@boutinb @JorisGoosen @RensDofferhoff this is one of the packages missing in the mac release (just talked to Rens about it).

**Comment by JorisGoosen** [comment]
I can reproduce and might even be the culprit...

**Comment by Didic99** [comment]
"> @Stellina01 thanks for reporting this! there seems to be an issue in the latest mac-release with some packages - we are working on a hotfix currently!
> @boutinb @JorisGoosen @RensDofferhoff this is one of the packages missing in the mac release (just talked to Rens about it)."

Any idea how long it will take to fix this? I am dealing with a similar issue.

**Comment by JorisGoosen** [comment]
It is already fixed, the latest nightly should work.

**Comment by JorisGoosen** [comment]
https://static.jasp-stats.org/JASP-0.17.2.1-macOS-arm64.dmg
