### ISSUE TITLE
[Bug]: Reliability: no package called Rdpack

### ISSUE THREAD

**Issue by Didic99** [jasp-stats/jasp-issues#2146]
### JASP Version

0.17.2

### JASP Module

Reliability

### What analysis are you seeing the problem on?

Cronbach's a

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

A bug appeared when conducting a Cronbach's alpha test. 
<img width="1405" alt="Schermafbeelding 2023-05-17 om 19 16 43" src="https://github.com/jasp-stats/jasp-issues/assets/133903637/694822dd-3aeb-4d9c-9bb0-51b283c69256">

### Expected Behaviour

A table with the results should have appeared. 

### Steps to Reproduce

1. Reliability
2. Undimensional Reliability
3. Drag variables to the right
4. Click Cronbach's a
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment]
@Didic99 thanks for creating the issue. Is it possible that you provide a zipped .jasp file or the data file to reproduce the error?

**Comment by JorisGoosen** [comment]
Thanks but the bug is probably already fixed we are waiting for the windows binaries to be signed for a proper release...

https://static.jasp-stats.org/JASP-0.17.2.1-macOS-arm64.dmg

**Comment by juliuspfadt** [comment]
@Didic99, @sting86425, can you confirm the issue is solved with the latest JASP version?

**Comment by sting86425** [comment]
Yes👍 the bug has been fixed, thanks a lot
