### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by sara-conti** [jasp-stats/jasp-issues#2149]
### JASP Version

0.17.2

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

Repeated Measures ANOVA

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

The engine crashed while trying to run this analysis... 
And before there was an error about "mvtnorm" package: 
This analysis terminated unexpectedly.

Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]): there is no package called ‘mvtnorm’

Stack trace

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

### Expected Behaviour

I wanted the analysis tables

### Steps to Reproduce

1.
2.
3.
...
Nope

### Log (if any)

jaspAnova::AnovaRepeatedMeasures(
          version = "0.17.2",
          contrasts = list(list(contrast = "none", variable = "PROVA"), list(contrast = "none", variable = "CONDIZIONE"), list(contrast = "none", variable = list("PROVA", "CONDIZIONE"))),
          repeatedMeasuresCells = list("PROVA1+SAG", "PROVA1+DX_USO", "PROVA1+SX_USO", "PROVA2+SAG", "PROVA2+DX_USO", "PROVA2+SX_USO"),
          repeatedMeasuresFactors = list(list(levels = list("1", "2"), name = "PROVA"), list(levels = list("Sag", "Dx", "Sx"), name = "CONDIZIONE")),
          withinModelTerms = list("PROVA", "CONDIZIONE", list("PROVA", "CONDIZIONE")))

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by sara-conti** [comment]
<img width="1303" alt="image" src="https://github.com/jasp-stats/jasp-issues/assets/103056959/f332237d-b145-455a-9b97-7ab3dd1d3d53">

**Comment by JohnnyDoorn** [comment]
This will be fixed in the hotfix (there were some missing packages on the mac version)
