### ISSUE TITLE
Post-hoc bonferroni comparisons for interactions in ANOVA

### ISSUE THREAD

**Issue by jandrews94** [jasp-stats/jasp-issues#215]
Would it be possible to include post-hoc tests for interactions and not just main effects in ANOVA's?

**Comment by boutinb** [comment]
@JohnnyDoorn Do you think it can be added for 0.9.3?

**Comment by JohnnyDoorn** [comment]
Yes, this is in my recent PR (still need to fix one small thing and then it should pass the unit test).

**Comment by AugustOlsson** [comment]
Hey @JohnnyDoorn any plans to include post-hoc testing for interactions in Between-measures BANOVA as well in addition to the newly included post-hoc testing for mixed/repeated BANOVA?

Best,
August
