### ISSUE TITLE
[Bug]: No package called ‘mvtnorm’

### ISSUE THREAD

**Issue by binhpham79** [jasp-stats/jasp-issues#2152]
### JASP Version

0.17.2

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

Contrasts and Post Hoc Tests

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

The Anova is crashed when selecting Contracts -> Factors, then select any option but `None'.

This also happen when doing Post Hoc Tests with Type = Dunnet or Standard.
![image](https://github.com/jasp-stats/jasp-issues/assets/22779243/9d99bcb3-6c36-4f94-a064-0ed3862a4e44)

### Expected Behaviour

This should not happen unless the Anova package does not support it.

### Steps to Reproduce

1. Anova
2. Select Dependent and Fixed Factors 
3. Select Contrasts
4. Select any option `simple' or 'difference'

### Log (if any)

[JASP 2023-05-21 22_14_52 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/11524905/JASP.2023-05-21.22_14_52.Desktop.log)
[JASP 2023-05-21 22_14_52 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/11524906/JASP.2023-05-21.22_14_52.Engine.0.log)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by binhpham79** [comment]
Data file (.jasp) that replicates the issue.

[Hotel_price.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/11524914/Hotel_price.jasp.zip)

**Comment by boutinb** [comment]
This problem is known and already solved. There will be hopefully tomorrow a release for this, but for the time being you can use this version: https://static.jasp-stats.org/JASP-0.17.2.1-macOS-arm64.dmg
