### ISSUE TITLE
[Bug]: Bayesian RM ANOVA does not show CI in Descriptives table 

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-issues#2153]
### JASP Version

0.17.2

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

ANOVA

### What OS are you seeing the problem on?

Windows 11

### Bug Description

The Descriptives table (Bayesian RM aNOVA) does not give the CI, even when that option is ticked. See 
also https://forum.cogsci.nl/discussion/8580/bayesian-rm-anova-no-cis-for-descriptive-statistics#latest

![image](https://github.com/jasp-stats/jasp-issues/assets/8603015/c7a9e984-53c6-4d20-aa0f-e9210863f8dd)

### Expected Behaviour

Show the CI in the table

### Steps to Reproduce

Run a B RM ANOVA

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by ColineAlice** [comment]
Hello,
I got the exact same issue (so does my student): Credible Interval are not displaying within Bayesian RM Anova (as well as the related post-hocs but that's another issue)
![image](https://github.com/jasp-stats/jasp-issues/assets/137557704/995f6c64-b7ef-4ef5-9d4a-aa8132d99113)

I'm also running it on a Windows 11 with on64 bits and Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz 2.30 GHz.

Sorry for cross-posting, the issue has also be opened here : https://github.com/jasp-stats/jasp-issues/issues/2190
