### ISSUE TITLE
[Bug]: Wrong Variable Option in Forward Stepwise

### ISSUE THREAD

**Issue by WrldTraveler** [jasp-stats/jasp-issues#2156]
### JASP Version

0.17.1

### JASP Module

Regression

### What OS are you seeing the problem on?

Windows 11

### Bug Description

I am trying to run a forward stepwise linear regression, but for my DV it requires it to be ordinal or nominal. This is a violation of assumptions for linear regressions. The DV has to be interval or ratio. 
![Screenshot 2023-05-22 at 4 16 41 PM](https://github.com/jasp-stats/jasp-issues/assets/134339316/0f660d6a-73a9-4d04-a117-818aa55b2368)

### Expected Behaviour

The DV should be continuous (interval or ratio)

### Steps to Reproduce

1.  I try and drag the DV to the spot it should go, and it won't go because it is an interval
2.
3.
...

### Log (if any)

<img width="1203" alt="Screenshot 2023-05-22 at 3 18 59 PM" src="https://github.com/jasp-stats/jasp-issues/assets/134339316/0a95d20c-0e3a-4395-ba2e-4376a1569b3a">

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by EJWagenmakers** [comment]
You have selected *logistic* regression, not *linear* regression. :-)
