### ISSUE TITLE
[Bug]: RMSEA in exploratory factor analysis

### ISSUE THREAD

**Issue by Lucy965** [jasp-stats/jasp-issues#2157]
### JASP Version

0.16.4

### JASP Module

Factor

### What analysis are you seeing the problem on?

Exploratory factor analysis

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I have worked with exploratory factor analysis, with the number of factors based on PC and based on eigenvalues, WLS estimator, oblimin rotation, and tetrachoric correlations. Everything is fine until I look at the additional fit indices, where my RMSEA is calculated as 0.587. I have recalculated it in R (PCA), and there I get a value of approximately 0.09. It seems that it doesn't work because, during the WLS estimation, it does not provide the likelihood, which is necessary for calculating the BIC information criterion.

### Expected Behaviour

It should calculate the correct value of RMSEA for the combination of oblimin rotation, tetrachoric matrix input, and WLS estimator.

### Steps to Reproduce

1. dichotomous data matrix (dummy variables 0,1)
2. exploratory factor analysis
3.WLS estimator, oblimin rotation, tetrachoric correlations
4. RMSEA is not correct
...

### Log (if any)

I am not allowed to share data.

### Final Checklist

- [x] I have included a screenshot showcasing the issue, if possible.
- [x] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by Lucy965** [comment]
I have tried it with different data (dummy variables), and the RMSEA is still not calculated correctly.

![346157966_921559012348998_5457014284337558660_n](https://github.com/jasp-stats/jasp-issues/assets/117731653/20d30c83-e784-4da7-94c3-2d000910f403)
![346167418_773879501147356_4490593984965681437_n](https://github.com/jasp-stats/jasp-issues/assets/117731653/ddaedd38-da0a-413d-89ac-cc59121f75eb)

**Comment by juliuspfadt** [comment]
Also, is there any reason you are using the 0.16.4 version?

**Comment by Lucy965** [comment]
I have sent you the data via email because I am not allowed to share it publicly. Version 0.16.4 suits me well. I am aware that a newer version is currently available, but I have been working with the submitted data in this version. I would appreciate a response and your findings :-)

**Comment by juliuspfadt** [comment]
@Lucy965 thanks for the info. Can I ask how you performed the analysis in R? I have tried: 

```r
dt <- read.csv("/Users/julius/Downloads/efa_bug.csv")

dt_test <- dt[, 3:22]

library(psych)

out <- fa(dt_test, nfactors = 3, rotate = "oblimin", cor = "mixed", fm = "wls")
out$RMSEA

```
yielding the same results as JASP, which is of course not surprising since JASP uses the psych package.

**Comment by Lucy965** [comment]
I have tried:
    ml_cor = tetrachoric(ml[,-c(1,2)]) 
# Paralel analysis
    ml_pa = fa.parallel(x = ml_cor$rho, n.obs = nrow(ml), fa = "pc", n.iter = 1000, quant = .95, plot = TRUE)   
# EFA, PCA
    ml.pc = principal(r = ml_cor$rho, n.obs = nrow(ml), nfactors = ml_pa$ncomp, rotate = 'oblimin', scores = TRUE, oblique.scores = FALSE)

**Comment by juliuspfadt** [comment]
How do you obtain a RMSEA when doing a PCA with the `psych` package though? You are aware that PCA and EFA are distinct analyses?

However, I do think it is weird that the SRMR is quite different than the RMSEA. So something seems to be going wrong, but the bug would then be within the psych package and not within JASP.

**Comment by Lucy965** [comment]
Yes, that´s it... The question is why...

**Comment by juliuspfadt** [comment]
Well, I think the psych people probably know best. I am afraid I cannot help you any further
