### ISSUE TITLE
[Bug]:  there is no package called dplyr

### ISSUE THREAD

**Issue by AnguloB** [jasp-stats/jasp-issues#2163]
### JASP Version

0.17.1

### JASP Module

Other Module

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

When using R console, the package dplyr is not loading and as a result we have an error. 

It was working on previous JASP versions and it is documented in R package list (https://jasp-stats.org/r-package-list/). It also happens in my students computers.. 

![Screenshot 2023-05-24 at 8 23 10 AM](https://github.com/jasp-stats/jasp-issues/assets/8128625/ca900e84-e832-497f-b105-6f1e5592ff56)

### Expected Behaviour

Load the package and do the analysis. 

### Steps to Reproduce

1. dplyr::lag(sample(1:50))

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JorisGoosen** [comment]
Hey @AnguloB 

aah well, you could try loading the anova module in the r commander?
Descriptives doesnt need it and that is what youve got loaded.

Each module has its own r library and they cannot see those of others (unless one module depends on another of course)

**Comment by tomtomme** [comment]
@JorisGoosen 
I chose anova in r commander and then get this with jasp 0.18.3: 
```
> library(dplyr)
Error: could not find function "library"
```

**Comment by JorisGoosen** [comment]
This is what I meant in https://github.com/jasp-stats/jasp-issues/issues/2163#issuecomment-1770358070 in any case ;)
