### ISSUE TITLE
[Bug]: contrasts can be applied only to factors with 2 or more levels

### ISSUE THREAD

**Issue by analyst2023** [jasp-stats/jasp-issues#2164]
### JASP Version

0.17.1

### JASP Module

Regression

### What analysis are you seeing the problem on?

Linear Regression

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

I keep receiving an error that terminates my analysis. I am trying to use a binary dummy variable with possible values 0 or 1 as a factor in my linear regression. The error I receive is "Error in 'contrasts <-' (*tmp*' , value = contr.funs[1 + isOF[nn]): contrasts can be applied only to factors with 2 or more levels" 

I have checked the variable type, updated JASP, recreated the variable, and I receive the same error that does not show up when I use any other binary categorical dummy variables, such as sex. 
<img width="777" alt="Screen Shot 2023-05-25 at 2 23 28 PM" src="https://github.com/jasp-stats/jasp-issues/assets/134652243/5b2b2633-fbd7-49f2-a107-56d28ad9923c">

### Expected Behaviour

It should use the variable as a factor producing a result with a reference group. 

### Steps to Reproduce

1. Yes, any time I add this variable as a factor or remake the variable with the same values. 

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@analyst2023 
Could you re-test with jasp 0.18.3 and if the error persists, share your jasp file, by renaming to .zip and drag and dropping here?
