### ISSUE TITLE
[Feature Request]: Bayesian repeated ANOVA, BFexcl

### ISSUE THREAD

**Issue by maomiaopeng** [jasp-stats/jasp-issues#2165]
### Description

Hi! I have a question that I am not sure whether I understand it correctly. - For repeated Bayesian ANOVA, can I obtain BFexcl by 1/BFincl? Considering that BFincl = p(models with that factor | data) ÷ p(models without that factor | data), if we assume 1/BFincl = 3, does that mean that the models without that factor are three times more likely than those that include it? I really appreciate your answer :)

### Purpose

to test whether there is evidence of absence

**Comment by EJWagenmakers** [comment]
Yes you can. And this should be straightforward to check in JASP. Also, note that for these kinds of questions were have a separate forum (https://forum.cogsci.nl/categories/jasp-bayesfactor)

**Comment by maomiaopeng** [comment]
Thank you very much!
