### ISSUE TITLE
[Bug]: Nagelkerke R² in logistic regression is incorrect

### ISSUE THREAD

**Issue by ChenCC99** [jasp-stats/jasp-issues#2166]
### JASP Version

0.17.2

### JASP Module

Regression

### What analysis are you seeing the problem on?

Logistic Regression

### What OS are you seeing the problem on?

Windows 11

### Bug Description

Nagelkerke R-squared is incorrect. it is the same as Cox & Snell R-squared.

### Expected Behaviour

Nagelkerke R-squared should be larger than Cox & Snell R-squared.

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by EJWagenmakers** [comment]
Thanks, I've forwarded the information!

**Comment by tomtomme** [comment]
@ChenCC99 
This is fixed. Tested with japs 0.18.3. Please reopen if not fixed on your side.
