### ISSUE TITLE
[Bug]: PLS factor loading (reflective index) in JASP

### ISSUE THREAD

**Issue by ChenCC99** [jasp-stats/jasp-issues#2167]
### JASP Version

0.17.2

### JASP Module

SEM

### What analysis are you seeing the problem on?

Partial Least Squares SEM

### What OS are you seeing the problem on?

Windows 11

### Bug Description

The data analyzed by JASP (compositeCorrelationDisattenuated = FALSE) and R cSEM package (.disattenuate = FALSE) are inconsistent in factor loading (reflective index). 

### Expected Behaviour

The outputs of "compositeCorrelationDisattenuated = FALSE" and "compositeCorrelationDisattenuated = TRUE" should be differnet.

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@ChenCC99 
Can you re-test with jasp 0.18.3? If not fixed I need your data file please. Rename it to .zip and then drag and drop here.
