### ISSUE TITLE
[Bug]: Reliability Analysis terminated

### ISSUE THREAD

**Issue by vellinhs** [jasp-stats/jasp-issues#2168]
### JASP Version

0.14

### JASP Module

Reliability

### What analysis are you seeing the problem on?

Reliability

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I wanted to do reliability test for my questionnaire item, but when i run the test. The result doesn't show and this text pops up:

![image](https://github.com/jasp-stats/jasp-issues/assets/113122820/9e094a09-6955-4fa2-874f-90ea1d5a302a)

Is it the JASP bug or is there something wrong with my data? Please help to assist me. Thank you so much

### Expected Behaviour

My reliability test result should be come out fine

### Steps to Reproduce

1.This analysis terminated unexpectedly. 

Error in `*tmp*`[['freq']]: subscript out of bounds

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.frequentistReliabilityMainResults(jaspResults, dataset, options)
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [x] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [x] I have accurately described the bug, and steps to reproduce it.

**Comment by vellinhs** [comment]
I already send the data file to issues@jasp-stats.org Please help me thank you

**Comment by EJWagenmakers** [comment]
0.14 is quite old. I recommend installing the latest version -- this may be a problem we've already solved. Please re-open this issue if the problem persists.
