### ISSUE TITLE
[Bug]: impossibility to save a trained model in the Machine Learning module

### ISSUE THREAD

**Issue by Tophe-0** [jasp-stats/jasp-issues#2170]
### JASP Version

0.17.2

### JASP Module

Machine Learning

### What analysis are you seeing the problem on?

KNN, LDA, SVM etc

### What OS are you seeing the problem on?

Windows 11

### Bug Description

Hi,
I attached the .csv file I have problem with
[PrestwOverSampling.csv](https://github.com/jasp-stats/jasp-issues/files/11610979/PrestwOverSampling.csv)

When I run, with the attached .csv file, a K-Nearest Neighbors or a Linear discriminant analysis or Support Vector Machine or any of the classification algorithms in the Machine learning module, everything works fine and I get a model and all the informations with it. Now, If I try to save any of these trained models in the .jaspML format (in the Export Results section) to further run a prediction with other .csv files I got this error message:

This analysis terminated unexpectedly.

Error in str2lang(x): :1:15: unexpected numeric constant
1: Activity ~ PC 1
                  ^

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.mlClassificationTableSummary(dataset, options, jaspResults, ready, position = 1, type = 'knn')

.decodeJaspMLobject(model)

.decodeJaspMLobject.kknn(model)

formula(paste(decodeColNames(as.character(model$terms)[2]), '~', paste0(decodeColNames(strsplit(as.character(model$terms)[3], split = ' + ', fixed = TRUE)[[1]]), collapse = ' + ')))

formula.character(paste(decodeColNames(as.character(model$terms)[2]), '~', paste0(decodeColNames(strsplit(as.character(model$terms)[3], split = ' + ', fixed = TRUE)[[1]]), collapse = ' + ')))

str2lang(x)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

Please couyld someone tell me what is wrong with my .csv file ?
I already did some similar experiments which ran correctly
Thanks very much for your help
Regards
Christophe
if you can't load my .csv file, please send me an e-mail to cdigiorg@unice.fr so I send it to you

### Expected Behaviour

I should be able to save any of the trained models in the .jaspML format and then use them to predict .csv file containing unknown items

### Steps to Reproduce

1. I load the csv file
2. I click Machine Learning and then K-Nearest Neighbors
3. I put the Column Activity as target
4. I put PC1 to PC 260 as features
5. In Tables, I click on Confusion matrix, Class proportions, Evaluation metrics
6. In Plots I click on Data split, Classification accuracy, ROC curves
7. In Export Results, I click Add predictions to data = KNN pred
8. I click Browse to specify the path I want to use for the .jaspML
9. and then when I click Save trained model, I get the message error
10. everything else, i.e. Data Split Preferences & Training Parameters were let to default
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by koenderks** [comment]
There is a known issue where it is impossible to save a trained model if any of the variables contain spaces, so it is probably best to try and remove these from your column names and try again.

Let me know if that solves your issue!

**Comment by Tophe-0** [comment]
Hi 

Well it was as simple as that. Everything is fine now
Thank you very much for your rapid reply.
Christophe

**Comment by koenderks** [comment]
For our info, this issue is related to https://github.com/jasp-stats/jaspMachineLearning/issues/158
