### ISSUE TITLE
[Bug]: GLMM marginal means contrasts disrespect filters

### ISSUE THREAD

**Issue by bknakker** [jasp-stats/jasp-issues#2171]
### JASP Version

0.17.2.1

### JASP Module

Mixed Models

### What OS are you seeing the problem on?

Windows 11

### Bug Description

I added a fixed factor to a binomial (aggregated) GLMM. I filtered out one level from the factor. The analysis was rerun with k-1 levels instead of k, but the level that I filtered out was still present in the Estimated marginal means / [x] specify contrasts table, and an error message appeared stating "Nonconforming number of contrast coefficients". I could not reproduce the bug with example datasets using gaussian GLMM, so it probably affects aggregated logistic specifically.
![image](https://github.com/jasp-stats/jasp-issues/assets/6921414/d30c4fef-682e-457f-83f5-32385229824b)

### Expected Behaviour

Levels not present in the data should be omitted from the contrast table as well.

### Steps to Reproduce

1. Create an aggregated binomial test dataset and add a within-subject factor with e.g. 4 categorical levels.
2. Filter out one of the categorical levels (I did it with the first one)
3. Fit an aggregated binomial GLMM with the within-subj factor as a fixed factor. Confirm that the number of contrasts is now 2 for the fixed factor, so the model fit respects the skipped level.
4. Select the w-s factor for Estimated marginal means analysis
5. Tick the 'specify contrasts' tickmark and observe that the filtered-out level is still there.
6. Attempt to specify a contrast (with e.g. zero for the omitted level, but it doesn't matter I guess) and observe the error message in the output pane.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by bknakker** [comment]
Please note that I didn't want to postpone (possibly to never) reporting this because of tinkering with a test dataset, and I cannot supply the actual data that I worked with, unfortunately. Please inform me if the bug doesn't reproduce based on the steps I describe and I'll find time to investigate what might be the missing detail. Thanks for understanding.

**Comment by FBartos** [comment]
Fixed by previous qml filter updates.
