### ISSUE TITLE
[Bug]: installation help

### ISSUE THREAD

**Issue by cas5185** [jasp-stats/jasp-issues#2172]
### JASP Version

0.17.2.1

### JASP Module

Unrelated

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

When I download JASP to my MacBook Air (Big Sur, Version 11.2.3) and try to drag and drop the installer into the App Store, I get a pop-up that says the app is not available in my country or region. I'm in the US. Thanks for any help!

### Expected Behaviour

n/a

### Steps to Reproduce

1.n/a
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JorisGoosen** [comment]
You should try dropping it in Applications ;)

**Comment by cas5185** [comment]
Oh my GOD how embarrassing. Thank you and sorry for the silliness!

**Comment by JorisGoosen** [comment]
Hope you love JASP as much as we love making it ;)
