### ISSUE TITLE
[Feature Request]: linear weighing in Cohen kappa 

### ISSUE THREAD

**Issue by sinchi3488** [jasp-stats/jasp-issues#2175]
### Description

The available weighted Cohen kappa in the reliability module uses quadratic weighing. Is there a chance to add linear weighing option?

### Purpose

Perform weighted kappa for ordinal variables using linear weighing 

### Is your feature request related to a JASP module?

Reliability

### Describe the solution you would like

Adding an option to weighted kappa for linear or quadratic weighing

**Comment by juliuspfadt** [comment]
hi @sinchi3488, thanks for creating the request. It would actually be fairly easy if the psych package we use for the calculation would offer this. Unfortunately, it does not. Trying to put in our own weighting matrix runs into an error as well, probably some bug in the psych package. I have now messages the maintainer of the psych package to include the option for linear weighting, given it is a fairly simple change on their end. Lets hope they do it and I dont have to hard code it.
