### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by Hassanekassem** [jasp-stats/jasp-issues#2177]
### Description

Stacked or grouped box plot

### Purpose

compare a variable between two groups across different time points

### Is your feature request related to a problem?

no

### Is your feature request related to a JASP module?

Descriptives, Visual Modeling

### Describe the solution you would like

I would like a feature that allow grouping the data two ways

**Comment by tomtomme** [comment]
This is a duplicate of 
https://github.com/jasp-stats/jasp-issues/issues/1734
and
https://github.com/jasp-stats/jasp-issues/issues/1415
