### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by NikitaKhromov-Borisov** [jasp-stats/jasp-issues#2179]
### JASP Version

0.17.2

### JASP Module

Frequencies

### What analysis are you seeing the problem on?

contingency tables

### What OS are you seeing the problem on?

Windows 11

### Bug Description

I attempt to carry out the analysis of the last contingency table from the file with data on 4 CTs: Pneumonia.csv
Unfortunately, for this last tabel JASP get a report on missing values. 
However, when I analyse the same 4th  table from the separate file Missing.csv, it's OK
What's the reason?
[JASP problem.docx](https://github.com/jasp-stats/jasp-issues/files/11666251/JASP.problem.docx)
[Missing.csv](https://github.com/jasp-stats/jasp-issues/files/11666266/Missing.csv)
[Pneumonia.csv](https://github.com/jasp-stats/jasp-issues/files/11666267/Pneumonia.csv)

### Expected Behaviour

all should be OK

### Steps to Reproduce

1. down load the file
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@NikitaKhromov-Borisov 
Tested with jasp 0.18.3. Seems fixed. Please reopen if not fixed on your side
