### ISSUE TITLE
[Bug]: Added modules don´t remain!

### ISSUE THREAD

**Issue by PerPalmgren** [jasp-stats/jasp-issues#2180]
### JASP Version

0.17.2.1

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

Adding modules!

### What OS are you seeing the problem on?

Windows 10

### Bug Description

When I try to add modules like "Power" and "Reliabilty" in JASP 0.17.2.1, the modules don´t stay when I close the program. When I re-open JASP they are not displayed in the top panel! Is this new that the module must be added iteratively  every time? It is rather cumbersome. 
All the best
Per 

### Expected Behaviour

Module should remain when closing the program.

### Steps to Reproduce

1.Add modulePower" or Reliabilty
2. Close JASP
3. Re-open JASP
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by RensDofferhoff** [comment]
Thanks for reporting!
This is should definitely not happen.
We can reproduce this bug one machine

Greetings,
Rens

**Comment by RensDofferhoff** [comment]
To fix this issue please turn on the 'Remember enabled modules' setting under advanced preferences.
This should be on by default but this seems to fail on certain machines.

Did you do a fresh install or update from a previous version? Did anything peculiar happen during install?

Greetings,
Rens

**Comment by PerPalmgren** [comment]
All ok now but the default setting should be looked at.

**Comment by tomtomme** [comment]
Seems fixed.
