### ISSUE TITLE
[Bug]: CFA error with grouping variable

### ISSUE THREAD

**Issue by marcellakna** [jasp-stats/jasp-issues#2182]
### JASP Version

0.17.2

### JASP Module

Factor

### What analysis are you seeing the problem on?

multigroup confirmatory factor analysis

### What OS are you seeing the problem on?

Windows 10

### Bug Description

JASP does'nt accept my grouping variable "diplomandin" for the multigroup cfa.  If i create a new variable, it doesn't work either, no matter in what way i scale it (nominal, ordinal etc.). However I gave the data to a friend, who did the exact same analysis and for her the mg cfa worked without problems. So it has to be an issue with my JASP (?). I also deinstalled and reinstalled JASP, but still get the same results. 

This analysis terminated unexpectedly.

Error in `$<-.data.frame`(`*tmp*`, 'group', value = c('Dogus', 'Dogus', : replacement has 432 rows, data has 72

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.cfaTableParEst(jaspResults, options, cfaResult)

.cfaParEstToTablesHelper(pe, options, cfaResult, ests, footnote)

`$<-`(`*tmp*`, 'group', value = c('Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka',
'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil',
'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil',
'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova',
'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink',
'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic',
'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc',
'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko',
'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer',
'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner',
'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner'))

`$<-.data.frame`(`*tmp*`, 'group', value = c('Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Dogus', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka',
'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Kadluczka', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil',
'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil',
'Aninilkumparambil', 'Aninilkumparambil', 'Aninilkumparambil', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Ramos', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova',
'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Svedova', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink',
'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Fink', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Eger', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic',
'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Mikulic', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc',
'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Demean-Dumulesc', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko',
'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Golovko', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer',
'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Schoierer', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner',
'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner', 'Aigner'))

stop(sprintf(ngettext(N, 'replacement has %d row, data has %d', 'replacement has %d rows, data has %d'), N, nrows), domain = NA)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports
![Screenshot (148)](https://github.com/jasp-stats/jasp-issues/assets/135831484/2aeac12c-8667-4f02-be6b-29877b0c015d)

### Expected Behaviour

the calculation of the CFA according with the grouping variable.

### Steps to Reproduce

1. everytime i do a mg cfa.
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment]
@marcellakna, thanks for creating the issue. is it at all possible that you share the data or zipped .jasp file?

**Comment by marcellakna** [comment]
Hello, has there been any development? I tried the same analysis with the Jasp 0.17.2 (before I used the newest format, so 0.17.2.1) but still got the same error.

**Comment by juliuspfadt** [comment]
I have not received the data, so I cannot say. Quick question, did you use the email `issus@jasp-stats.org` or `issues@jasp-stars.org` ?

**Comment by ibrahmoztrk** [comment]
Hi all, is this issue solved? I am experiencing something similar. Thx.

**Comment by juliuspfadt** [comment]
Given that there is no data file that was shared I cannot even say that there was an issue to begin with. If you experience the same issue, you could upload the zipped .jasp file here so we can look into it.

**Comment by ibrahmoztrk** [comment]
Unfortunately, I cannot share the data (or a sample), but it looks like this:

tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.cfaTableParEst(jaspResults, options, cfaResult)

.cfaParEstToTablesHelper(pe, options, cfaResult, ests, footnote)

$<-`(`*tmp*`, 'group', value = c "I HAVE HIDDEN THE VARIABLE NAMES HERE"...

stop(sprintf(ngettext(N, 'replacement has %d row, data has %d', 'replacement has %d rows, data has %d'), N, nrows), domain = NA)

**Comment by ibrahmoztrk** [comment]
I am able to run CFA with the whole data but this problem occurs when I define the multigroup CFA grouping variable

**Comment by juliuspfadt** [comment]
hmm, without the data this is somewhat of a guessing game. I suspect that the name of the grouping variable might be causing the problem. What is the language of your system and the name of that variable? Can you try renaming it?

**Comment by ibrahmoztrk** [comment]
Both are in English. I have tried several other variables as well and all of them failed. The only one "successfully working" was with two levels. I wonder if that is the case? Can grouping variable have more than two categories?

**Comment by juliuspfadt** [comment]
That should not be an issue. Unfortunately, I cannot help you further without a data set that causes this.

**Comment by ibrahmoztrk** [comment]
Hi, thanks. It seems to be the problem. When I filter data to have 2 groups, everything works fine, but when I increase the group number to 3, it crashes.

**Comment by juliuspfadt** [comment]
You were right, I found the bug. I am attaching a simulated data set, so anyone reading this can test it: 
[testCFA.csv](https://github.com/jasp-stats/jasp-issues/files/12377692/testCFA.csv)
model would be `model = "f =~ x1 + x2 + x3"`. Next version of JASP should have the fix

**Comment by ibrahmoztrk** [comment]
Perfect! Thanks so much!

**Comment by Yang1566** [comment]
> Hi, thanks. It seems to be the problem. When I filter data to have 2 groups, everything works fine, but when I increase the group number to 3, it crashes.

I just experienced the exactly same problem here, and when changed the grouping variables into two (saying male and female), everything is back to normal.

@juliuspfadt Thank you so much if this bug can be fixed in next version. I am more than pleased to see it there.

**Comment by luk-hbs** [comment]
> You were right, I found the bug. I am attaching a simulated data set, so anyone reading this can test it: [testCFA.csv](https://github.com/jasp-stats/jasp-issues/files/12377692/testCFA.csv) model would be `model = "f =~ x1 + x2 + x3"`. Next version of JASP should have the fix

Dear @juliuspfadt may I politely ask if we can expect this bug to be fixed soon? Using version 0.18.3. released earlier this year, I am still experiencing the same bug.

**Comment by juliuspfadt** [comment]
Oh. that is not good. Trying with the release version I dont see bug. Can you share your zipped .jasp file? Cause maybe this is a different error.

**Comment by luk-hbs** [comment]
I attach a file that has a reduced number of variables and units. 
Just for clarity, the error is manifested when a second order solution is chosen and any variable that has more than two variants is chosen as the grouping variable for the invariance test (see varianbles PMAT, DUVTYPDULM, AGE_3, EDU_3).

Here are the paremeters of the analysis without selected multigroup CFA (please leave aside that there are only two first order factors in the model, there is a reason for that):

![image](https://github.com/jasp-stats/jasp-issues/assets/163986504/ef44ee02-4d80-4eab-9c8f-0e9af05e8f54)
![image](https://github.com/jasp-stats/jasp-issues/assets/163986504/55815688-cd39-47ce-8199-c4fb11377b27)


Here the error message:
![image](https://github.com/jasp-stats/jasp-issues/assets/163986504/c4d5c57d-1e08-40cb-9e60-1c10bab5c988)

Here is the JASP data file
[SECOND_ORDER_CFA_invariance_BUG.zip](https://github.com/jasp-stats/jasp-issues/files/14649284/SECOND_ORDER_CFA_invariance_BUG.zip)

**Maybe important information at the end. I tried to use the online version of JASP (0.14.3) for the same analysis and it seems that this error does not occur here.** 

Thank you for your willingness to address the problem @juliuspfadt
