### ISSUE TITLE
[Bug]: Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]): there is no package called ‘Rdpack’

### ISSUE THREAD

**Issue by rpw19** [jasp-stats/jasp-issues#2184]
### JASP Version

0.17.2

### JASP Module

Reliability

### What analysis are you seeing the problem on?

Error in loadNamespace

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

I can't do the reliability through analysis terminated unexpectedly.

Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]): there is no package called ‘Rdpack’
#
Stack trace

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports[](url)

### Expected Behaviour

I can do the reliability without any probs pls help

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment]
Hi @rpw19, thanks for creating the issue. I think this should be solved in the latest release 0.17.2.1. Could you try that and see if the issue persists?

**Comment by juliuspfadt** [comment]
please download this version: https://jasp-stats.org/thank-you-for-downloading-jasp-macos-apple-silicon/ and check :)

**Comment by rpw19** [comment]
Hi julius,
Thank you for your help :)I've downloaded the new version, it works on the Reliability (unidimensional reliability) :)
However it wont work on the CFA, there's a different issue from the last issue i've mentioned (the model is not admissible...)
is there anything that i can do to analyzed the CFA?Thank you so much and have a nice day. :)


    Pada Kamis, 8 Juni 2023 16.25.36 WIB, Julius Pfadt ***@***.***> menulis:  
 
 


please download this version: https://jasp-stats.org/thank-you-for-downloading-jasp-macos-apple-silicon/ and check :)

**Comment by juliuspfadt** [comment]
regarding the CFA, could you open a new issue and describe your problem there, please?
