### ISSUE TITLE
[Bug]: The engine crashed while trying to run this analysis

### ISSUE THREAD

**Issue by happyfeliz1** [jasp-stats/jasp-issues#2185]
### JASP Version

0.17.2

### JASP Module

ANOVA, Descriptives, T-Tests

### What OS are you seeing the problem on?

Windows 10

### Bug Description

The engine crashed while trying to run this analysis... I want to edit my graphs (Adding axis description) and when doing so the before mentioned bug occures. Afterwards neither the analysis, nor the editing of the graph works. How can this be fixed?
![image](https://github.com/jasp-stats/jasp-issues/assets/135974790/448d07a8-8b15-481a-bf8d-fe2c0d2c5548)

### Expected Behaviour

A descrption of the y axis of a graph should be added
[Thriving_Scores_best_data_27_11_ohne_mean_imputation.zip](https://github.com/jasp-stats/jasp-issues/files/11687453/Thriving_Scores_best_data_27_11_ohne_mean_imputation.zip)

### Steps to Reproduce

1. Open Results
2. Click on the arrow to edit Image
3. Edit the graph
4. y-axis
5. fill in: "thriving" in title
6. press Ok
7. Bug occurs
![image](https://github.com/jasp-stats/jasp-issues/assets/135974790/67343b6b-4aee-4761-b223-fe01eba91865)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by happyfeliz1** [comment]
Just got an e-mail.. What means this? Do I have to edit anything?

Label and Assign / Bug-label-and-assign
Failed in 6 seconds

**Comment by RensDofferhoff** [comment]
Thanks of your report.
I cannot reproduce this bug on windows 11 with our newest [version 0.17.2.1](https://jasp-stats.org/download/)
Could you try our newest version to see if this resolves the issue?

I can successfully make the edits:
[Thriving_Scores_best_data_27_11_ohne_mean_imputation.zip](https://github.com/jasp-stats/jasp-issues/files/11703176/Thriving_Scores_best_data_27_11_ohne_mean_imputation.zip)

**Comment by tomtomme** [comment]
Confirm. This is also fixed for me.
@happyfeliz1 
Please reopen if not fixed for you on jasp 0.18.3!
