### ISSUE TITLE
[Bug]: Wilcoxon signed-rank test gives wrong result

### ISSUE THREAD

**Issue by dummycaterpillar** [jasp-stats/jasp-issues#2187]
### JASP Version

0.17.2.1

### JASP Module

T-Tests

### What analysis are you seeing the problem on?

Paired Samples T-Test

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I wanted to use the Wilcoxon signed rank test. I also used Python for the test. However, Python and JASP produced different results for the statistic and z-score. My by hand calculation gave me a statistic equal to Python one. I think JASP performed a wrong calculation or statistical test.
![image](https://github.com/jasp-stats/jasp-issues/assets/136254885/b2640e5c-afc3-4fbc-8e53-ebf83e8d3139)
[wilcoxon test.zip](https://github.com/jasp-stats/jasp-issues/files/11715179/wilcoxon.test.zip)

### Expected Behaviour

The test should produce statistic and z-score values like Python.

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by dummycaterpillar** [comment]
Thanks @JohnnyDoorn 
So it is something about R vs Python rather than JASP. 
Thank you for the clarification.

**Comment by JohnnyDoorn** [comment]
Glad to see it's sorted @dummycaterpillar  - just for my own curiosity, how does scipy handle the ties? Because it seems weird that you cannot reproduce the R results with some different setting.

**Comment by dummycaterpillar** [comment]
For my by hand calculation, I followed my textbook. Since scipy gives me the same statistic, I assume they do the same thing. In my textbook, ties are given mean ranks, and zeroes are split equally between positives and negatives. @JohnnyDoorn
