### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by hadavis625** [jasp-stats/jasp-issues#2189]
### JASP Version

0.17.2.1

### JASP Module

SEM

### What analysis are you seeing the problem on?

CFA

### What OS are you seeing the problem on?

Windows 10

### Bug Description

This analysis terminated unexpectedly.

Error in diag(scales) %*% truevar: non-conformable arguments

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.cfaTableReliability(jaspResults, options, cfaResult)

semTools::compRelSEM(cfaResult[['lav']], return.total = TRUE)

omegaCat(truevar = commonCov, denom = totalCov, threshold = threshold[[b]][myIndNames], scales = latScales[[b]][myIndNames])

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

### Expected Behaviour

It should have run the CFA

### Steps to Reproduce

1. Open CFA
2. create 4 factors
3. populate factors
4. Get error
...
![image](https://github.com/jasp-stats/jasp-issues/assets/136475435/6ea00f9c-50b3-4dec-954b-ba87aea4243c)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@hadavis625 
Can you re-test with jasp 0.18.3? If not fixed I need your data file. Rename it to .zip and then drag and drop here. I tried to replicate this with other data, but I could not.

**Comment by tomtomme** [comment]
This one might be the same as https://github.com/jasp-stats/jasp-issues/issues/2564
The problem there was that special characters like / were used in the var names.
