### ISSUE TITLE
Feature Request (HLM, PCR, Ridge etc...)

### ISSUE THREAD

**Issue by Farscape1** [jasp-stats/jasp-issues#219]
Hi,

I am wondering if JASP is planning to add multinomial regression, multi-level modelling, and things like principal component regression and lasso.

I know it is a lot of feature request but the use of multiomial, multilevel, and PCR is becoming frequent in our field (medical).

Thanks,

**Comment by tomtomme** [comment]
@Farscape1 
- Multinomial logistic regression is done - if that is what you meant. For frequencies we have a multinomial test. 
- mixed modeling is done
- Ridge & Lasso are available under Machine learning with Regularized Linear Regression

This leaves
- PCR, which is tracked here: https://github.com/jasp-stats/jasp-issues/issues/2084

So I am closing this one as a duplicate of PCR. Please reopen, if I am mistaken open a new issue if one of the implementations is lacking for your usecase. Thx!
