### ISSUE TITLE
[Bug]: Credible interval in "Descriptives" (bayesian RM ANOVA) doesn't show

### ISSUE THREAD

**Issue by Fetilu** [jasp-stats/jasp-issues#2190]
### JASP Version

0.17.2.1

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

Descriptives with 95% Credible Interval clicked on

### What OS are you seeing the problem on?

Windows 11

### Bug Description

Hello everyone,

I'm currently trying to retrieve credible intervals of specific sub-levels' means from my bayesian repeated mesures ANOVA. Even though it's requested, the credible interval isn't displayed. Instead, JASP shows me the Standard Error and the Coefficient of variation. While those are interesting statistics, they are not what I asked JASP to give me :/ 

Wish I could put a screenshot but this is another issue with my computer and Windows 11...

### Expected Behaviour

The credible interval of each sub-level means should have been displayed

### Steps to Reproduce

I'm not sure I can reproduce the bug as colleagues with the same version don't have such issue. The issue also appears whatever the input I give to JASP.

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by ColineAlice** [comment]
Hello,
I got the exact same issue (so does my student) when Credible Interval are not displaying within Bayesian RM Anova (as well as the related post-hocs but that's another issue)
![image](https://github.com/jasp-stats/jasp-issues/assets/137557704/62e63c99-0d67-4231-b9e0-474850c14eba).

I'm also running it on a Windows 11 with on64 bits and Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz   2.30 GHz.
