### ISSUE TITLE
[Bug]: The wilcoxon signed rank test does not report the same values as wilcox.test in R

### ISSUE THREAD

**Issue by saracoppi** [jasp-stats/jasp-issues#2191]
### JASP Version

Others

### JASP Module

T-Tests

### What analysis are you seeing the problem on?

Wilcoxon sign rank test

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

The wilcoxon signed rank test does not report the same values as wilcox.test in R
I thought the results should be the same. I have verified that paired t.test values of the two programs correspond, which means that the datasets are not a problem, but the issue happens with the wilcoxon signed rank test. Would you mind sharing the R function/ formula you have used to implement this test in JASP?

Thanks

### Expected Behaviour

the results should be the same. Would you mind sharing the formula you have used to implement the Wilcoxon signed rank test in JASP? I thought it was based on R functions

### Steps to Reproduce

1.
2.
3.
...
yes

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by saracoppi** [comment]
Hi this is Sara,

I have a problem reproducing the Wilcoxon signed rank test results obtained
by JASP. In fact, when I use R the results I get are completely
different from the ones I get in JASP. Do you know why?

I attach here my data file and the relative screenshots from JASP and R.

In case, do you mind sharing the right R formula on which JASP is based on?
Thanks a lot,

Best,
Sara
[image: Screenshot 2023-06-14 at 20.25.35.png][image: Screenshot 2023-06-14
at 20.28.25.png]

**Comment by saracoppi** [comment]
Please, do NOT share the data,

Thanks,
Sara

**Comment by saracoppi** [comment]
Additionally, in this webpage (https://rdrr.io/r/stats/wilcox.test.html) it
says:
"By default (if exact is not specified), an exact p-value is computed if
the samples contain less than 50 finite values and there are no ties.
Otherwise, a normal approximation is used."
Therefore I assume that if there is any problem with the ties, and add
exact = FALSE, it should use a normal approximation and therefore there
should not be any issue, or difference with JASP.,

Let me know,

Thanks,


Best,
Sara

**Comment by saracoppi** [comment]
additionally if use wilcoxsign_test(a$parch_A_parch_VT_Illusion~
a$poly_A_poly_VT_Illusion, zero.method ="Wilcoxon"), which should handle
ties, I get the same results as wilcox.sign(a$parch_A_parch_VT_Illusion~
a$poly_A_poly_VT_Illusion), and both are different from JASP,

Sorry for the many emails,
And thanks for your understanding,

Best,
Sara

**Comment by JohnnyDoorn** [comment]
Hi @saracoppi ,

I ran your data set through JASP and R, and obtain the same result for the paired Wilcoxon test: W = 112, p = 0.097:
```

> dat <- read.csv("~/Downloads/wilcoxDat.csv")
> wilcox.test(dat$parch_A_parch_VT_Illusion, 
+             dat$poly_A_poly_VT_Illusion, 
+             paired = TRUE)

	Wilcoxon signed rank test with continuity correction

data:  dat$parch_A_parch_VT_Illusion and dat$poly_A_poly_VT_Illusion
V = 112, p-value = 0.09713
alternative hypothesis: true location shift is not equal to 0
```
![image](https://github.com/jasp-stats/jasp-issues/assets/15704203/6fb40a26-1e54-445e-9aa5-8fbae99a7bc5)


So I am not sure what went wrong on your end - perhaps you forgot the `paired = TRUE` in R?

Kind regards
Johnny

**Comment by tomtomme** [comment]
@saracoppi 
I hope this could be cleared up?
Feel free to reopen, if you have any updates!

**Comment by saracoppi** [comment]
Hej Thomas!

thank you!

for some reason, I still get different results and I do not know why.

Best,
Sara

**Comment by tomtomme** [comment]
@saracoppi 
and you have used the same code as johnny above with paired = true and the newest jasp?
