### ISSUE TITLE
[Feature Request]: Add Winget support

### ISSUE THREAD

**Issue by atos93** [jasp-stats/jasp-issues#2193]
### Description

Add Winget support

### Purpose

to be able to install JASP in more efficent way

### Use-case

install JASP from Windows

### Is your feature request related to a JASP module?

Unrelated

### Describe the solution you would like

Incorporate a template into the https://github.com/microsoft/winget-pkgs repository, ensuring that it receives automatic updates whenever a new release becomes available.

**Comment by RensDofferhoff** [comment]
I will bring this up in our next meeting!

**Comment by tomtomme** [comment]
@atos93 
jasp is now available from the windows store with automatic update capabilities. Is this sufficient?

@RensDofferhoff 
Can winget bring anything more to the table than msix and win store? Maybe when win store is locked at company level?

**Comment by RensDofferhoff** [comment]
@tomtomme 
`winget install "JASP" `

Will install JASP.
It will pull from the store repo on behalf of the acting user.
Winget and the Store are now quite closely knit:

> The winget tool will not be available until you have logged into Windows as a user for the first time, triggering Microsoft Store to register Windows Package Manager as part of an asynchronous process.

https://learn.microsoft.com/en-us/windows/package-manager/winget/


But if @atos93 or anyone else thinks of a valid reason why we should also put JASP in the winget repo as well we can consider it.

**Comment by RensDofferhoff** [comment]
winget install JASP.JASP now also works
