### ISSUE TITLE
[Bug]: "JASP has experienced an unexpected internal error. The Engine Crashed.."

### ISSUE THREAD

**Issue by raffifger2725** [jasp-stats/jasp-issues#2197]
### JASP Version

0.17.2.1

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

Data Analysisis

### What OS are you seeing the problem on?

Windows 11

### Bug Description

When i want to factor the file after using a realibilty the JASP always stopped. The text is my Engine is Crashed. What i must do? i have do reinstall many time. I cant find any trick again about this problems

### Expected Behaviour

crashed application

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @raffifger2725 As long as we have no reproduction path (a precise description step by step of what you are doing), or any JASP file where we can see this error, we can't help you.
