### ISSUE TITLE
[Bug]: PostgreSQL database: driver not found

### ISSUE THREAD

**Issue by LaRiffle** [jasp-stats/jasp-issues#2199]
### JASP Version

0.17.2.1

### JASP Module

Other

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

I'm trying to open a PostgresSQL connection but receive a "Driver not found" error

### Expected Behaviour

Connection should work

### Steps to Reproduce

1. "Open"
2. "Database"
3. Select "Postgres" and any configuration, and click on "Connect to database"

<img width="970" alt="CleanShot 2023-06-26 at 08 54 25@2x" src="https://github.com/jasp-stats/jasp-issues/assets/12446521/3ab1f79e-0650-4a97-882a-08e2174c1fd8">

<img width="610" alt="CleanShot 2023-06-26 at 08 53 54@2x" src="https://github.com/jasp-stats/jasp-issues/assets/12446521/dc02e646-12b7-4fa9-8239-1f2361bfe805">

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by JorisGoosen** [comment]
@LaRiffle did you actually install any drivers for postgressql on your system?

I can run postgressql fine on my macos so Im assuming you are missing some driver from your system.
But you do not describe how or where your database runs and what you installed on your system.

If you can add that information here we might be able to help you figure out what your missing

**Comment by LaRiffle** [comment]
Should I install something specific for JASP? Or linking to the Qt SQL engine?

**Comment by JorisGoosen** [comment]
https://doc.qt.io/qt-6/sql-driver.html

Is how qt describes how to use the databases, our jasp interface basically forwards everything to that.

I just tried installing some official postgres drivers via the "App Stack Builder" but I cant get them to run.

But what postgres did you install?
@RensDofferhoff discovered that connecting to the `homebrew` version isnt possible without changing something in the binary of JASP. But I think that connecting to the official versions of postgres should work.

The problem is only that how to connect is not exactly well documented for all platforms*dbs
When I get to the office Ill check what I did there, but I suspect I used the ODBC driver, so you could give that a go

**Comment by natmaka** [comment]
Using JASP 0.17.2.1 (installed by Flatpak --user ...) on a Debian bookworm (amd64) with all potentially pertinent Debian packages installed  (systemwide): libqt6sql6-psql , libpostgresql-jdbc-java , odbc-postgresql and libqt6sql6-odbc I encounter the same issue (same error message).

**Comment by JorisGoosen** [comment]
@natmaka Flatpak does not use local or system installed libraries at all.
But maybe we can help you out though, but it would require a new issue though as this one is about macos Intel where the issue is quite different

**Comment by tomtomme** [comment]
@LaRiffle 
Could you figure this one out? Does it work with jasp 0.18.3? If so, how?

**Comment by natmaka** [comment]
@LaRiffle No, I could not figure this one out, it does not work (here) with JASP 0.18.3.

All related Flatpak dependencies are up-to-date.  I also tried after installing psqlodbc

Same error message "Error: Driver not loaded Driver not loaded" (sic).

I'm pretty sure that my connection string is adequate (it works on the command line, using psql).

Were you able to find a way?

**Comment by tomtomme** [comment]
@natmaka 
I know your issue is not sorted out. Please post updates for that in your own issue. This is the issue of LaRiffle and I asked LaRiffle and not you! Thx!

**Comment by natmaka** [comment]
@tomtomme Sorry, it seems to me that those issues are coupled as (AFAIK) both have the same cause (PG driver not or inadequately integrated), and therefore that any information related to one of them may be useful the other(?)  Won't bother you again. Thx.

**Comment by tomtomme** [comment]
They are abit different because of the OS. And please do bother us, but in your issue :)
Thx for contributing!

**Comment by tomtomme** [comment]
@LaRiffle 
Please reopen, if you can share answers to the points Joris made above.

**Comment by tomtomme** [comment]
similar issue now discussed here: https://github.com/jasp-stats/jasp-issues/issues/2946
