### ISSUE TITLE
Bayesian Log-Linear Regression not working?

### ISSUE THREAD

**Issue by gorkang** [jasp-stats/jasp-issues#22]
Dear all,

I created a fake set of data to compare the results of a Log-Linear Regression and a Bayesian Log-Linear Regression (see attached .jasp file).

![image](https://cloud.githubusercontent.com/assets/6491790/16047095/1ad66952-3225-11e6-9514-9bcfd54db321.png)

The Log-Linear Regression gives the expected results (IV1 and IV2 p<0.001 and IV1_IV2 p<0.01), but, the Bayesian Log-Linear Regression gives a BF10 of 1. Interestingly, it seems the Bayesian Log-Linear Regression *_always*\* gives a BF10 of 1, independently of the data you feed it.

Cheers!

[Log-linear.jasp.zip](https://github.com/jasp-stats/jasp-desktop/files/314186/Log-linear.jasp.zip)

**Comment by tomtomme** [comment]
Seems fixed at least since 0.18.2 beta. As a default, this analysis now displays the best "2" models. 

Can be closed?
