### ISSUE TITLE
[Bug]: Bug Report in PROPHET Module

### ISSUE THREAD

**Issue by mkozkok** [jasp-stats/jasp-issues#2201]
### JASP Version

0.17.2.1

### JASP Module

Prophet

### What analysis are you seeing the problem on?

saving predictions

### What OS are you seeing the problem on?

Windows 10

### Bug Description

When I want to save predictions, I receive this message:

_This analysis terminated unexpectedly.
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE, : arguments imply differing number of rows: 3, 2
Stack trace
To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports_

### Expected Behaviour

I want to save the predictions but the BUG is preventing me from saving them.

### Steps to Reproduce

1.
2.
3.
...
![exportissue](https://github.com/jasp-stats/jasp-issues/assets/138057925/0027bed2-8379-486c-9482-cd02d6ce157e)
[poppr.zip](https://github.com/jasp-stats/jasp-issues/files/11899317/poppr.zip)

### Final Checklist

- [x] I have included a screenshot showcasing the issue, if possible.
- [x] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [x] I have accurately described the bug, and steps to reproduce it.

**Comment by mkozkok** [comment]
Can someone help me with that?

**Comment by Kucharssim** [comment]
Dear @mkozkok,

I am sorry that the bug prevents you from exporting your predictions. @petersen-f just fixed the bug in the development version of the module - this will not help you solve the problem at this moment but will bring the fix in a future JASP version.
