### ISSUE TITLE
[Bug]: Repeated Measures ANOVA does not run

### ISSUE THREAD

**Issue by knamesnik** [jasp-stats/jasp-issues#2202]
### JASP Version

Others

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

Repeated Measures ANOVA (Freq and Bayes)

### What OS are you seeing the problem on?

Windows 10

### Bug Description

When running a repeated measures ANOVA, no output is generated using the classical method and an error is given using the Bayesian method (BF is undefined - all effects are specified as nuisance) even though previously results were given and there really is an effect. Students in our course experienced the same problem on different OS. Not sure about the JASP versions. 

<img width="653" alt="image" src="https://github.com/jasp-stats/jasp-issues/assets/38688445/dc9f84c3-2faa-42b8-9887-4c0601ba7229">
[data file displaying bug.zip](https://github.com/jasp-stats/jasp-issues/files/11903029/data.file.displaying.bug.zip)

### Expected Behaviour

Output generated

### Steps to Reproduce

1.run RM ANOVA
2.run Bayesian RM ANOVA
3.(optional) add factor to analysis
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JohnnyDoorn** [comment]
Hi @knamesnik 

Are you using the latest version of JASP? because we had a brief period where the ANOVA did not run.

cheers
Johnny

**Comment by tomtomme** [comment]
@JohnnyDoorn 
You can download the file here:
https://github.com/jasp-stats/jasp-issues/files/11903029/data.file.displaying.bug.zip

When I delete the first two variables (nominal text), then the anovas run. Otherwise they do not! Very strange!

**Comment by JohnnyDoorn** [comment]
I see that you need to add the terms to the model still - when you do that, the analyses run. (I was also a bit puzzled at first!). I don't know where the initial error message about undefined BF comes from, I think that's an artifact from a previous jasp version.
