### ISSUE TITLE
[Feature Request]: Make Weblate work again

### ISSUE THREAD

**Issue by JoKeyser** [jasp-stats/jasp-issues#2203]
### Description

Currently, nearly all modules on Weblate are locked for translation.
This was the case over the last few days... not sure if there's just a hickup or an actual problem?

> The translation is temporarily closed for contributions due to maintenance, please come back later. 

### Is your feature request related to a problem?

Currently it's not possible for normal users to add/change translations via Weblate.

### Is your feature request related to a JASP module?

Nearly all modules.

### Describe the solution you would like

Unlock to enable translations via Weblate.

**Comment by boutinb** [comment]
Thanks for the reminder! There are now unlocked.
