### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by Jays72** [jasp-stats/jasp-issues#2204]
### Description

Timeseries visualisations and forecasting

### Purpose

Visualize timeseries data and undertake forecasting of future values based on historical trends

### Use-case

Used for scientific data, water quality and environmental data analysis

### Is your feature request related to a problem?

The ability to visualise and forecast future performance based on historical data 

### Is your feature request related to a JASP module?

Visual Modeling

### Describe the solution you would like

Plot a series of line graphs of parameters against data and forecast future values based on historical performance

### Describe alternatives that you have considered

R packages - forecast, TSA and timeSeries

**Comment by EJWagenmakers** [comment]
We are currently testing a time series module, which will feature in the next release, out very soon. So I am closing this issue in anticipation of the upcoming version.

**Comment by tomtomme** [comment]
As far as I can see, there is still no possibility to visualize multiple lines / time series within one plot for comparison purposes. Like e.g. a climate model ensemble plot: 
![grafik](https://github.com/jasp-stats/jasp-issues/assets/4428185/4e8b2fb3-0a7e-4600-9ccb-4dd1507fdbe5)

I tested the modules
- BSTS
- time series (beta)
- predictive analytics

On that matter: Why are those within different modules and not within one big time series module?

**Comment by EJWagenmakers** [comment]
We're going to consolidate these modules in the (near) future
