### ISSUE TITLE
[Bug]: Factor analysis based on Polychoric/tetrachoric correlations

### ISSUE THREAD

**Issue by Mary-Toothfairy** [jasp-stats/jasp-issues#2206]
### JASP Version

0.17.2.1

### JASP Module

Factor

### What analysis are you seeing the problem on?

PCA and EFA

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

I can run Factor on my data as long as I base my analysis on Correlation or Covariance matrix. When I want to switch to Polychoric, the analysis is terminated. I get this message:

This analysis terminated unexpectedly.

Error in if (isTryError(efaResult) && options[['basedOn']] = 'mixed' && : missing value where TRUE/FALSE needed

Stack trace

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

### Expected Behaviour

I should have just gotten a factor matrix. 

### Steps to Reproduce

1. Click on Factor
2. Click Polychoric matrix
3. Analysis is terminated. 
...

### Log (if any)

This analysis terminated unexpectedly.

Error in if (isTryError(efaResult) && options[['basedOn']] = 'mixed' && : missing value where TRUE/FALSE needed

Stack trace

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports
<img width="1067" alt="Screenshot 2023-07-01 at 17 05 07" src="https://github.com/jasp-stats/jasp-issues/assets/137114411/fc439043-3b75-49be-a839-ecc12484526b">
[JASP_bug_file.csv](https://github.com/jasp-stats/jasp-issues/files/11927236/JASP_bug_file.csv)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
I recently ran into this error too and just want to confirm it (JASP 0.17.2.1 flatpak)

**Comment by juliuspfadt** [comment]
hi @Mary-Toothfairy, thanks for creating the issue. Could you provide me either with the zipped .jasp file or with a screenshot showing which variables you used in the analysis?

**Comment by Mary-Toothfairy** [comment]
Hello,
I attached a screen shot to this message. This is the regular Factor
analysis, yet I have ordinal data so I would prefer to use the Polychoric
correlations table.
Thank you,
Mary Toothfairy

**Comment by juliuspfadt** [comment]
Hmm, it seems you replied through email, and then attachments get lost. You would need ti manually upload it to the website here.

**Comment by Mary-Toothfairy** [comment]
<img width="1292" alt="Screenshot 2023-07-03 at 10 32 24" src="https://github.com/jasp-stats/jasp-issues/assets/137114411/9f0636fb-64e2-47a2-b31f-19b2462b7a4e">
