### ISSUE TITLE
[Bug]: Filtered out Stats applied to averages

### ISSUE THREAD

**Issue by WillSTT** [jasp-stats/jasp-issues#2208]
### JASP Version

0.17.2.1

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I may be confused because I just started using JASP. After filtering out non qualifiers for my table and removing them from view, I can see that the mean of a given table is 4. but when applying the "mean()" feature  to a new column, the mean includes the hidden data into the average, skewing the data to 4.5.

### Expected Behaviour

The mean() feature should be the same as the mean value represented in the descriptive section, getting rid of the filtered out data.

### Steps to Reproduce

1.Take a data set and filter out some stats
2.See the average represented in the description
3.Then create a new column and use the mean() function in a basic equation. 
...
If you do that equation on your calculator you will see the new equation included the old mean using the filtered out stats.

### Final Checklist

- [x] I have included a screenshot showcasing the issue, if possible.
- [x] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by WillSTT** [comment]
>  

![ERROR](https://github.com/jasp-stats/jasp-issues/assets/138356136/af79e868-fade-435b-8c2d-5c1ed7564fbc)

**Comment by boutinb** [comment]
That is not good... We will have a look.

**Comment by WillSTT** [comment]
Hey, let me know if this is hotfixed or something, I would love to get back
to using JASP but this seems to be an obvious roadblock!

Thank you for your help

**Comment by boutinb** [comment]
As workaround, you can use a spreadsheet editor to generate different datasets according to each filter you want to use, and then synchronise your JASP file with each of these datasets (In the hamburger menu, Sync Data menu).
