### ISSUE TITLE
File menu unresponsive

### ISSUE THREAD

**Issue by UppsalaCognitionLab** [jasp-stats/jasp-issues#221]
## Template for bug reports

* JASP version: 0.9.0.1
* OS name and version: Microsoft Windows [Version 10.0.17134.228]
* Analysis: When i open JASP and go to the "File" menu, nothing happens when i click on "Computer"
* Steps to reproduce: Open JASP, to to "file" menu, click on "computer"

## Template for enhancement requests
 
* Enhancement:
* Purpose:

**Comment by kaaylim** [comment]
I have the same issue on Linux. "Browse" button does not  work, and I can see "Documents" and "Desktop" folders but cannot open them.


* JASP version: 0.9.0.1  (Flatpak)
* OS name and version: Solus - Linux budgie 4.19.1-98.current
* Resolution:
>screen #0:
  dimensions:    1280x1024 pixels (338x270 millimeters)
  resolution:    96x96 dots per inch
* Graphics:
>VGA compatible controller: Intel Corporation Xeon E3-1200 v2/3rd Gen Core processor Graphics Controller

**Comment by JorisGoosen** [comment]
This should no longer be a problem as we have completely replaced the file menu in 0.10.0.0
