### ISSUE TITLE
[Feature Request]: Forest plot

### ISSUE THREAD

**Issue by khasmolders** [jasp-stats/jasp-issues#2210]
### Description

Fixed vertical line at the no effect point leads to misinterpretation.

### Purpose

Interpretation of subgroup effects would be helped if this line was de-emphasised or omitted and replaced by a vertical line at the overall treatment effect level, making it easier to see if a subgroup confidence interval differed significantly from the overall effect.

### Use-case

Visually comparing effect sizes (blood pressure control) of groups of patients with the same characteristics (patient profile) with that of the total group of patients..

### Is your feature request related to a problem?

The vertical line is fixed on the no effect point and therefore focuses unwanted attention on whether or not the confidence interval for an individual subgroup touches the no effect point.

### Is your feature request related to a JASP module?

Meta Analysis

### Describe the solution you would like

Adjustable vertical line in the forest plot.

### Describe alternatives that you have considered

Making the forest plot in excel (but failed so far)

### Additional context

In below example (screenshot) the bold line is the preferred line and the dashed line is the current fixed line.
![image](https://github.com/jasp-stats/jasp-issues/assets/138560710/f41e23e6-75c6-43cd-a589-bd3418b947a2)

**Comment by FBartos** [comment]
Hi, that looks like a very nice suggestion! I will see what I can do.

Btw, do you know by any chance whether the figure was generated in R / what was the package?

**Comment by khasmolders** [comment]
> Hi, that looks like a very nice suggestion! I will see what I can do.
> 
> Btw, do you know by any chance whether the figure was generated in R / what was the package?

Hi, thanks for your quick respons!
Unfortunately i'm a newbie in the field of JASP (and R), so i don't know how or with what software the forest plot was generated...

**Comment by FBartos** [comment]
No worries, we will figure out :)
