### ISSUE TITLE
[Bug]: The Latent growth module does not accept factors (covaraite)

### ISSUE THREAD

**Issue by areeq1** [jasp-stats/jasp-issues#2212]
### JASP Version

0.17.2.1

### Commit ID

e5371ca8eb112816cd6b4ea47d9330617df21f67

### JASP Module

Other

### What analysis are you seeing the problem on?

Latent Growth

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

I have reported that several times in the last few months but nothing updated in the new versions.  The Latent growth module doesn't work when a factor is added.
Please fix this!

![Screenshot 2023-07-05 at 12 48 37 am](https://github.com/jasp-stats/jasp-issues/assets/68887104/ccba5c55-e066-451f-99e4-8534558ec8fe)

### Expected Behaviour

An error message 

### Steps to Reproduce

1. Running the module with covaraite
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by drdrpeterson** [comment]
I'm having this issue too. JASP 0.18.1 on Apple Silicon

**Comment by tomtomme** [comment]
@areeq1 
This seems to be a duplicate or at least closely related to https://github.com/jasp-stats/jasp-issues/issues/2510
Lets discuss there, if you can still replicate or get different error messages with current jasp, please post them in 2510
Feel free to reopen, if this is a different issue!
Whatever it is, we sure need more help in testing LGCM!

related issues
#2212
#2076
#2032
#2002
#1774
