### ISSUE TITLE
[Bug]: Model is not admissible

### ISSUE THREAD

**Issue by cunj123** [jasp-stats/jasp-issues#2214]
### JASP Version

0.17.1

### JASP Module

Factor

### What analysis are you seeing the problem on?

Multifactor CRA

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I am trying to make a multifactor CFA, but JASP keeps telling me that the model is not admissible 
![jaspcfa](https://github.com/jasp-stats/jasp-issues/assets/86965206/4ac415fc-44de-4c07-b40b-fa3389318f58)
This keeps happening only when I try adding one of the variables (P2). I am not sure if something is wrong with my model, or it's an issue with the app
[Konfirmatorna faktorska analiza.zip](https://github.com/jasp-stats/jasp-issues/files/11961340/Konfirmatorna.faktorska.analiza.zip)

### Expected Behaviour

The analysis should be displayed.

### Steps to Reproduce

1. Add the model
2. Try to do CFA and try adding P2 into one of the factors

### Log (if any)

[JASP 2023-07-05 21_35_56 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/11961333/JASP.2023-07-05.21_35_56.Desktop.log)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment]
@cunj123 thanks for creating the issue. Unfortunately, I do not think this is a bug with the program but an issue with your model, which is the issue that the message prints: the underlying R package `lavaan` threw an error, which says some variances are negative. This points to some misspecification of your model, and you already identified the variable that might be left out. However, you might try to change the estimator to something other than ML, and run the analysis again. You can always argue for that given that you have ordinal data.
