### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jrace1** [jasp-stats/jasp-issues#2215]
### JASP Version

0.17.2.1

### JASP Module

Quality Control

### What analysis are you seeing the problem on?

Type 2 and 3 gauge r&R (manual/automatic equipment)

### What OS are you seeing the problem on?

Linux

### Bug Description

Good morning,
When trying to open a ".csv" file the following error occurs:

![image](https://github.com/jasp-stats/jasp-issues/assets/29781149/7e76edfd-18e0-439c-b813-45465274f0ff)

![image](https://github.com/jasp-stats/jasp-issues/assets/29781149/9fd4fc65-524d-42ae-a7e5-8ea8b2737abd)

The detail is that I am using the same data available in the JASP Data Library: Open/Data Library/18. QUALITY CONTROL/GAUGE R&R (Wide Format), the Unique Difference is that I am opening from a ".CSV" file.

Open through the library works normally, but opening by file ".csv" appears this error.

Follows data used in the ".csv" file:

﻿Parts,Operators,V1,V2,V3
1,Operator A,-0.5,-0.5,-0.5
1,Operator B,-0.5,-0.5,-0.5
1,Operator C,-1,-0.5,-0.5
2,Operator A,-7,-6.5,-6
2,Operator B,-6.5,-7,-6.5
2,Operator C,-6,-6,-6
3,Operator A,-2,-2,-1.5
3,Operator B,-1,-1,-2
3,Operator C,-2,-2,-1
4,Operator A,-8,-8,-7.5
4,Operator B,-7,-7.5,-7.5
4,Operator C,-7,-7,-7
5,Operator A,-4,-4,-3.5
5,Operator B,-3.5,-3.5,-4
5,Operator C,-3,-4,-4
6,Operator A,-2,-1,-2
6,Operator B,-1,-2,-2
6,Operator C,-1,-1,-1
7,Operator A,-11,-11,-11
7,Operator B,-11,-11,-11
7,Operator C,-11,-10,-11
8,Operator A,-6,-6,-6
8,Operator B,-6,-6,-6
8,Operator C,-6,-5,-5
9,Operator A,-2,-2,-1
9,Operator B,-2,-2,-2
9,Operator C,-2,-1,-2
10,Operator A,-6,-6,-6
10,Operator B,-6,-6,-6
10,Operator C,-6,-6,-6

### Expected Behaviour

The expected behavior would be the same as the example available in the data library: Open/Data Library/18. QUALITY CONTROL/GAUGE R&R (Wide Format)

### Steps to Reproduce

1.Click on "Open"
2.Click on "Computer"
3.Click the "search" button
4.Select the ".csv" file
5.In the top menu select "Quality Control"
6.Select the option "Type 2 and 3 Gauge R&R (Manual/Automatic Equipment)"
7.In "Data Format", select the "Across Rows" option
8.Select Checkbox "Tolerance With"
9.Select all plot checkbox
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by vandenman** [comment]
@JTPetter do you have time to take a look at this?

**Comment by JTPetter** [comment]
Hi @jrace1 ,

did you enter all measurements into the correct field? I cannot reproduce your error, at least not in a way that is not intended. If I enter only one of the measurement columns I get the error message:
![image](https://github.com/jasp-stats/jasp-issues/assets/61797391/767d1808-4553-4096-bde1-d1f0578acedf)
But this is desired behavior, as with one column there is only one measurement per operator per part, which does not allow to make the desired calculations.

If I enter all variables correctly it works for me:
![image](https://github.com/jasp-stats/jasp-issues/assets/61797391/3d6322d3-8ebb-4427-a9e3-ce393bab9016)

Let me know if that resolves it for you, if not please attach a screenshot of the whole interface so I can see all your settings.
