### ISSUE TITLE
[Bug]: JASP 0.17.2.1 for windows saves only data file while saving to a cloud folder

### ISSUE THREAD

**Issue by TaliRaveh** [jasp-stats/jasp-issues#2217]
### JASP Version

0.17.2.1

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 10

### Bug Description

When saving data file with analysis to a OneDrive folder (on my desktop), the file is saved only with the original data file, but not the analysis or changes to the data file (after syncing with the csv file). No error message is displayed. 

### Expected Behaviour

The file should open with the data (after changes) and the analysis.

### Steps to Reproduce

1. Use any csv file
2. open the csv file in JASP
3. Save the Jasp file in OneDrive folder
4. Close JASP
5. Open the file again
6.
7.
...

### Log (if any)

NA

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
I'm not sure to understand exactly what you do: you open csv file with JASP, add some analyses, save the JASP file. If you open the JASP file (and not the csv file), the analyses have disappeared and you see only the data? Can you send me then the JASP file (for this you have first to zip it, and then you can drag & drop on a comment of this issue with GitHub)?
