### ISSUE TITLE
[Bug]: Pre-installed version not on website

### ISSUE THREAD

**Issue by scopak** [jasp-stats/jasp-issues#2218]
### JASP Version

0.17.1

### Commit ID

JASP 0.17.2.1 64bit pre-installed version does not appear available for download.

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

JASP 0.17.2.1 64bit pre-installed version does not appear available for download.

### What OS are you seeing the problem on?

Windows 11

### Bug Description

Hello,

Is JASP 0.17.2.1 64bit pre-installed version available for download? I see JASP-0.17.1-64bit on the download page, but not the latest release.

### Expected Behaviour

JASP 0.17.2.1 64bit pre-installed version availability 

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Oh I see, it was still linked with the older version. Sorry, I have just set the link to the 0.17.2.1. version.
