### ISSUE TITLE
[Feature Request]: Move Inference or rename Descriptives Module

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#2219]
### Description

Consider renaming the module e.g. to "Basics" or splitting out the Inference section into a submodule maybe including the Shapiro-Wilk-Test.

### Is your feature request related to a problem?

The module Descriptive contains a growing section of Inference. This might confuse students.

### Is your feature request related to a JASP module?

Descriptives

### Describe alternatives that you have considered

leave as is

**Comment by Kucharssim** [comment]
@EJWagenmakers, what do you think?

**Comment by EJWagenmakers** [comment]
I don't think students are confused at this point, and changing things might result in more confusion. But we should be careful not to include too much inference in the Descriptives (which is a recurring discussion).
