### ISSUE TITLE
JASP keeps crashing

### ISSUE THREAD

**Issue by kevinvschie** [jasp-stats/jasp-issues#222]
## Template for bug reports

Ever since I downloaded the new JASP version, it keeps crashing. I am unable to load in .csv files. 

![screen shot 2018-10-17 at 09 01 36](https://user-images.githubusercontent.com/26565846/47068165-db34f200-d1eb-11e8-95af-288f9c45897f.png)

* JASP version: 0.9.1.0.
* OS name and version: 10.13.6 (mac OS High Sierra)
* Analysis: bayesian independent t-test

**Comment by pdf1337** [comment]
I'm getting the same crashes while trying to perform network analysis.

**Comment by hyunsooseol** [comment]
I'm also getting the same crashes with the newest version of JASP(0.9.2.0)

**Comment by WiednerF** [comment]
I am also getting the Crashes with the newest version on Windows

**Comment by AlexanderLyNL** [comment]
@boutinb We could solve this for 0.9.2, but I think we would be more efficient if we focus on our new build now. Is our nightly good enough for testing?

**Comment by JorisGoosen** [comment]
@kevinvschie @pdf1337 @hyunsooseol @WiednerF am I correct in assuming that the latest release of 0.10.0.0 fixes your problems?

If not, feel free to reopen this issue.
