### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ASMITHAHIRALAL** [jasp-stats/jasp-issues#2221]
### JASP Version

0.17.2.1

### JASP Module

Unrelated, Other

### What analysis are you seeing the problem on?

computing

### What OS are you seeing the problem on?

Windows 11

### Bug Description

IT SAYS ENGINE CRASHED

### Expected Behaviour

It should allow me to perform the operations

### Steps to Reproduce

1.
2.l,
3.
...

### Log (if any)

no

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Dear @ASMITHAHIRALAL, to be able to understand what is going on your PC, you have to describe exactly all the steps you do before you get the message error: does it crash just by double-clicking the JASP icon, or after loading a data file, or a JASP file, or by adding an analysis?
