### ISSUE TITLE
Conditional Process Analysis

### ISSUE THREAD

**Issue by itailL** [jasp-stats/jasp-issues#2222]
### Description

Conditional process analyses as an enhancement to linear and logit regressions.

### Purpose

An advanced method to test for more complex mechanisms with regressions. For example, moderation, mediation, moderated mediation, etc.

### Use-case

This method is becoming increasingly popular in behavioral sciences, as it allows testing for psychological mechanisms or complex relationships. 

### Is your feature request related to a JASP module?

Regression

### Describe the solution you would like

There are currently three existing tools for process analysis: an SPSS and SAS add-ins and an R package (https://www.processmacro.org/index.html). A GUI similar to that available in SPSS would be straightforward to use.

**Comment by Kucharssim** [comment]
Dear @itailL,

mediation and moderation are already available in JASP, please see https://jasp-stats.org/2020/03/12/mediation-and-moderation-analysis-in-jasp/.

This does not rely on PROCESS though so if you want to follow the exact methodology as taught by A. F. Hayes, that's currently not possible. We do have a long-term project for implementing PROCESS models in JASP, perhaps @JohnnyDoorn or @maltelueken have something more concrete to share at this moment?

**Comment by EJWagenmakers** [comment]
This is under active development, and a teaser blogpost will be out soon. So I am happy to close this issue!

**Comment by itailL** [comment]
Thanks! I really appreciate the amazing work you and your team are doing.
