### ISSUE TITLE
[Feature Request]: Option to fix intercepts to zero in mean structure

### ISSUE THREAD

**Issue by HeikoBreitsohl** [jasp-stats/jasp-issues#2223]
### JASP Version

0.17.2.1

### JASP Module

Factor

### What analysis are you seeing the problem on?

CFA with mean structure

### What OS are you seeing the problem on?

Windows 10

### Bug Description

When fitting a CFA with "Model Options -> Include mean structure" activated, JASP includes a table with the indicator intercepts, but not the factor means.

On a related note, it is unclear whether JASP fixes the factor means or some indicator intercepts to zero for identification. It seems to be the former, regardless of how the covariance structure is identified.

### Expected Behaviour

Ideally, there would be a table with factor means, after the intercepts table.

When, under "Model identification", selecting...
- Factor variances, the mean structure should be identified by fixing factor means to zero.
- Marker variable, the mean structure should be identified by fixing indicator intercepts to zero.
- Effects coding [Thanks for adding this feature!], the mean structure should be identified by constraining indicator intercepts to average to zero.

### Steps to Reproduce

1. Specify a two factor CFA, using the Political Democracy dataset
2. Select "Model Options -> Include mean structure" and "Model identification: Marker variable"
3. No Table with factor means available.

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment]
@HeikoBreitsohlm thanks for creating this issue. You are right, by default the latent intercepts are fixed to 0. And so far there is no option to change it. I think it makes sense to add this as an option underneath the `include mean structure` options such as:
<img width="1382" alt="Screenshot 2023-07-14 at 09 24 32" src="https://github.com/jasp-stats/jasp-issues/assets/38500953/2326d374-4168-42fc-8069-d99f0884ce26">

**Comment by HeikoBreitsohl** [comment]
@juliuspfadt Thanks for the swift response! This looks great!
Would it be possible to add a third option that corresponds to effects coding?
That could be called something like "Constrain manifest intercepts to average to zero".

**Comment by juliuspfadt** [comment]
Hi @HeikoBreitsohl, sorry for the late response. Regular work has kept me busy. Do you mean the intercepts of the manifest variables per latent variable should average to zero? That is easy to implement.
