### ISSUE TITLE
[Bug]: Equality Constraints in Multigroup SEM have at least 2 bugs

### ISSUE THREAD

**Issue by HeikoBreitsohl** [jasp-stats/jasp-issues#2225]
### JASP Version

0.17.2.1

### JASP Module

SEM

### What analysis are you seeing the problem on?

Multigroup SEM with Equality Constraints

### What OS are you seeing the problem on?

Windows 10

### Bug Description

When adding equality constraints, some constraint options add unwanted constraints, while others don't do anything:
- "Loadings" adds constraints on loadings AND factor covariances
- "Means" adds constraints, but does not add labels to the output table
- "Factor variances" does not change anything
- "Factor covariances" does not change anything
The others seem to work. [I did not check "Thresholds".]

[By the way, this all works fine in the CFA module.]

### Expected Behaviour

Each constraint option should add only one type of constraint (and the corresponding labels).

### Steps to Reproduce

1. Open the Holzinger-Swineford data (Data Library -> Mental Ability)
2. Specify factors, e.g.
Factor1=~x1+x2+x3
Factor2=~x4+x5+x6
Factor3=~x7+x8+x9

3. Select grouping variable "School"
4. Add equality constraints
See screenshots for some examples.
![SEM_Constraining_FactorVariances_does_nothing](https://github.com/jasp-stats/jasp-issues/assets/30316517/29a773d5-f6af-4f6a-9ff4-1ffbadf179db)
![SEM_FactorCovariances_constrained_erroneously](https://github.com/jasp-stats/jasp-issues/assets/30316517/47ad5bee-8c61-483b-a6f2-4eafa0b44871)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@HeikoBreitsohl 
Thx for reporting. Is this still an issue with jasp 0.18.3?

**Comment by HeikoBreitsohl** [comment]
@tomtomme 
Yes, the issues are still there: 

Loadings: the same issue remains (JASP adds constraints on loadings AND factor covariances).
Intercepts: Works fine (as before).
Residuals: Works fine (as before).
Residual covariances: Works fine.
Means: same issue (adds constraints, but does not add labels to the output table).
Regressions: Works fine.
Latent variances: same issue (does not change anything).
Latent covariances: same issue (does not change anything).

**Comment by tomtomme** [comment]
@juliuspfadt 
This one seems to be a serious bug. It is also mentioned here that equality constraints worked with jasp 0.16.4 just fine: https://github.com/jasp-stats/jasp-issues/issues/2046

**Comment by juliuspfadt** [comment]
I will check it

**Comment by juliuspfadt** [comment]
Okay. so there was a spelling error in the R code so the factor variances constraint was not taken into account properly. Some of the errors are not actually errors though. 
- "Loadings" adds constraints on loadings AND factor covariances:
that is fixed by correcting the typo
- "Means" adds constraints, but does not add labels to the output table
Sine latent intercepts are fixed to zero, clicking "means" will actually do nothing, that is correct. We might add a note to the table
- "Factor variances" does not change anything: 
In your code the factor variances are fixed to unity for the factor scaling, so these are not subject to constraints anymore. We might add a note here.
- "Factor covariances" does not change anything: fixed by correcting the typo.

**Comment by HeikoBreitsohl** [comment]
Thanks for the clarification, and sorry for my confusion. 

To be sure, I went through (almost) all options for invariance testing, for each method of factor scaling.
I used this model:
Factor1=~ x1+x2+x3
Factor2=~ x4+x5+x6
Factor3=~ x7+x8+x9
x1~~x4
Factor3~Factor1+Factor2

### Factor scaling: Factor loadings

1. Adding constraints on factor loadings: **Adds unwanted constraints on factor covariances**
2. Adding constraints on intercepts: Works fine (adds constraints to intercepts, free factor means in the second group)
3. Adding constraints on residuals: Works fine
4. Adding constraints on residual covariances: Works fine
5. Adding constraints on means: Does add constraints (or, more precisely, fixes; see also my summary below), but **does not label them**
6. [I did not test thresholds.]
7. Adding constraints on regressions: Works fine
8. Adding constraints on factor variances: **Does not do anything (remain freely estimated)**
9. Adding constraints on factor covariances: **Adds constraints on the variances!**
10. 

### Factor scaling: Factor variance

1. Adding constraints on factor loadings: **Adds unwanted constraints on factor covariances (but does correctly free factor variances in the second group)**
2. Adding constraints on intercepts: Works fine (adds constraints to intercepts, free factor means in the second group)
3. Adding constraints on residuals: Works fine
4. Adding constraints on residual covariances: Works fine
5. Adding constraints on means: Does add constraints (or, more precisely, fixes), but **does not label them**
6. [I did not test thresholds.]
7. Adding constraints on regressions: Works fine
8. Adding constraints on factor variances: **Does not do anything (remain freely estimated)**
9. Adding constraints on factor covariances: **Adds constraints on the variances!**

### Factor scaling: Effects coding
1. Adding constraints on factor loadings: **Adds unwanted constraints on factor covariances**
2. Adding constraints on intercepts: Works fine
3. Adding constraints on residuals: Works fine
4. Adding constraints on residual covariances: Works fine
5. Adding constraints on means: **Does not do anything** (Before adding these constraints, factor means were correctly freely estimated in both groups.)
6. [I did not test thresholds.]
7. Adding constraints on regressions: Works fine
8. Adding constraints on factor variances: **Does not do anything (remain freely estimated)**
9. Adding constraints on factor covariances: **Adds constraints on the variances!**

### Summary and some observations:
- Some (partially known) bugs involve the commands for constraints on factor loadings, factor variances, and factor covariances.
- There is also an issue with constraining factor means, particularly with effects coding.
- I find it inconvenient that you have to actively "Include mean structure" after adding constraints that affect the mean structure (e.g., on the manifest intercepts). I think it would be an improvement if the mean structure option would be activated automatically when adding constraints on manifest intercepts and/or factor means.
- Not providing the labeling when constraining factor means seems like an inconsistent procedure. I do like that the labels are numbered, so users can check the total number of constraints. But this only works if all invariance constraints are labeled!
- It might be confusing to users that, by default, there is a checkmark indicating that factor means are fixed to zero. Perhaps this option could be "inverted" and renamed ("Free latent intercepts")? That way, none of the boxes would be checked by default, which seems more intuitive.

**Comment by juliuspfadt** [comment]
@HeikoBreitsohl Thanks a lot for the detailed list. I will get on some more fixes soon.
