### ISSUE TITLE
[Feature Request]: Add DuckDB Driver

### ISSUE THREAD

**Issue by HiramTheHero** [jasp-stats/jasp-issues#2227]
### Description

Add DuckDB Driver

### Purpose

Gain access to DuckDB databases

### Use-case

Querying data from DuckDB databases

### Is your feature request related to a problem?

No.

### Describe the solution you would like

The ability to connect to a DuckDB database.

### Describe alternatives that you have considered

Export data from a DuckDB database, then use JASP on the exported data.

### Additional context

[DuckDB](https://duckdb.org/) is, basically, the SQLite of analytics. It is a powerhouse of a tool for data analysis. It would be excellent to be able to connect to it with JASP.

**Comment by RensDofferhoff** [comment]
Interesting suggestion!

**Comment by JorisGoosen** [comment]
I think you could possibly use ODBC already: https://duckdb.org/docs/api/odbc/overview.html
(Our support for databases is restricted to what qt sql supports: https://doc.qt.io/qt-6/qtsql-index.html )

**Comment by tomtomme** [comment]
@HiramTheHero 
Could you test with ODBC as Joris suggested?

**Comment by HiramTheHero** [comment]
I tried following the instructions on DuckDB's website and the blue help icon in JASP when in the database tab, but I couldn't get it to connect. I have no ODBC experience, so I assume it is error on my end. Someone with more ODBC experience will have to try and make it work.

**Comment by tomtomme** [comment]
@HiramTheHero 
Ok. Closing then. If you can resolve this in the future, we would be happy about feedback here!
