### ISSUE TITLE
[Bug]: Not possible to plot model averaged posteriors on Apple Silicon (M1)

### ISSUE THREAD

**Issue by RenzoLanfranco** [jasp-stats/jasp-issues#2233]
### JASP Version

0.17.2.1

### JASP Module

Unrelated, ANOVA, Regression, T-Tests

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

At the office, I have a PC lab with the latest version of JASP and the Windows version of JASP installed. Everything runs smoothly. In my laptop (Apple Silicon, M1 Macbook Pro), I have the Apple Silicon version of JASP installed. Most features run as expected. However, whenever I run a Bayesian ANOVA, ANCOVA or RM ANOVA, and tick the box "Model averaged posteriors", JASP is unable to plot anything and remains running ad infinitum. This is not the case with my Windows JASP. After trying to run these analyses between the two systems, and having installed different versions, I've come to the conclusion that this is very likely due to a bug in the Apple Silicon version.

### Expected Behaviour

For the Apple Silicon version of JASP to be able to plot model averaged posteriors for the Bayesian versions of statistical analyses.

### Steps to Reproduce

1. Load any dataset in your Apple Silicon JASP
2. Run a Bayesian RM ANOVA
3. Try to plot the model averaged posteriors.

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by RensDofferhoff** [comment]
I cannot reproduce this. 
Could you provide a JASP file?

**Comment by RenzoLanfranco** [comment]
> I cannot reproduce this. Could you provide a JASP file?

Thanks for the quick reply! I just realised that it only happens when you first tick the box "Estimates" beforehand.
