### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ecadrian** [jasp-stats/jasp-issues#2236]
### JASP Version

0.17.2.1

### JASP Module

Learn Bayes

### What analysis are you seeing the problem on?

Binary Classification

### What OS are you seeing the problem on?

Windows 10, Ubuntu

### Bug Description

The explanatory text shows the Bayes Theorem formula with perhaps a typo.
![BayesTheorem](https://github.com/jasp-stats/jasp-issues/assets/88053603/b7f7edcf-1ae4-4dfa-a052-1ff7ebe1d618)

### Expected Behaviour

If I´m understanding the formula right, the condition must be negative

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@ecadrian 
The formula seems fixed in jasp 0.18.3.
Can you confirm?

**Comment by ecadrian** [comment]
Yes.
Thanks
________________________________
De: Thomas Langkamp ***@***.***>
Enviado: xoves, 8 de febreiro de 2024 22:04
Para: jasp-stats/jasp-issues ***@***.***>
CC: Juan C. Estévez ***@***.***>; Mention ***@***.***>
Asunto: Re: [jasp-stats/jasp-issues] [Bug]: (Issue #2236)


@ecadrian<https://github.com/ecadrian>
The formula seems fixed in jasp 0.18.3.
Can you confirm?
