### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by carolina-byte** [jasp-stats/jasp-issues#2237]
### JASP Version

Others

### JASP Module

Network

### What analysis are you seeing the problem on?

Network Analysis

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

il software si blocca quando inserisci le variabili

### Expected Behaviour

non dovrebbe bloccarsi

### Steps to Reproduce

1.
2.
3.
...
1. inserisco le variabili
2. il software va in blocco e mi dice che c'è un errore

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by vandenman** [comment]
Grazie per averci segnalato questo problema su GitHub. Potresti spiegare meglio cosa va storto? Ad esempio, potrebbe pubblicare (una schermata) del messaggio di errore che appare? Grazie in anticipo!

Nota: questa traduzione è stata generata automaticamente, di solito comunichiamo in inglese.

Messaggio non tradotto: _Thank you for telling us about this issue on GitHub. Could you explain a bit more about what goes wrong? For example, could you post (a screenshot of) the error message that appears? Thanks in advance!_

**Comment by tomtomme** [comment]
@carolina-byte 
Please reopen, if you can add more details!
