### ISSUE TITLE
[Bug]: Results for Bayesian Paired T-Tests seem inaccurate?

### ISSUE THREAD

**Issue by jack-ptrs** [jasp-stats/jasp-issues#2241]
### JASP Version

0.17.2.1

### Commit ID

17.3

### JASP Module

Equivalence T-Tests

### What analysis are you seeing the problem on?

Bayesian Paired T-Test (both Student and Wilcoxon) 

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

The Wilcoxon signed rank tests suggest WS differences regarding the "ExpRel_Distr" variables, whereas suggests much smaller differences for comparable variables with comparable means and SDs. Is this a bug or is this a correct result? I've had previous issues with BFs being unreliable in JASP (albeit for much more complex models). See screenshot distress and vividness t-tests and descriptives. Used default cauchy priors. 

<img width="693" alt="Screenshot 2023-07-27 at 13 05 39" src="https://github.com/jasp-stats/jasp-issues/assets/140711509/51c7f4c3-5556-4418-a704-773c80b95ed5">

### Expected Behaviour

I would have expected less drastic differences, especially given the smaller sample size on the variable with more evidence for WS differences. 

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@jack-ptrs 
Thx for the report. Does the problem persist with jasp 0.18.3?

@Jillderon 
What do you think about this? Is it a bug?

**Comment by tomtomme** [comment]
@jack-ptrs 
In similar issue reports I read, that it may be wise to run such an analysis several times and for wilcoxon to increase number of samples. 
Then the model might converge differently. 

(Sidenote: In other Bayesian analysis you can set a seed to make results reproducible. But thats not available in tTests. You could switch to anova for that, but that then misses the non-parametric option. And setting the seed also does not make your problem of the unexpected result go away.)
