### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Sparkety** [jasp-stats/jasp-issues#2243]
### JASP Version

0.14

### JASP Module

Regression

### What analysis are you seeing the problem on?

Classical Linear Regression

### What OS are you seeing the problem on?

Other

### Bug Description

When I click to select a variable to add to the "covariate" field, the arrow goes dark grey and is unresponsive. I can add variables to "dependent variable", but not "covariates". 

![Screenshot 2023-07-27 at 13 02 23](https://github.com/jasp-stats/jasp-issues/assets/140831400/8a30164c-96df-4532-a175-a8d1ca0bf620)

### Expected Behaviour

I should be able to select a variable, then click the arrow to move it across to "covariates". 

### Steps to Reproduce

1. I saved my data file as .csv.
2. I opened the data file in JASP.
3. I selected "Regression - Classical - Linear Regression"
4. I selected one of the variables on the left hand side, which I wanted to move into the "covariates" field.
5. The arrow I ought to be able to use to move it went dark grey and unresponsive.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Can you test this with the current jasp 0.17.3?
