### ISSUE TITLE
[Bug]: Error when installing developer module from module template on Windows 11

### ISSUE THREAD

**Issue by rcalinjageman** [jasp-stats/jasp-issues#2249]
### JASP Version

0.17.2.1

### Commit ID

2ec76a9fe6592cb08a73b18d4f70d1b39a260380

### JASP Module

Other

### What analysis are you seeing the problem on?

Installing developer module

### What OS are you seeing the problem on?

Windows 11

### Bug Description

I'm trying to follow the directions for getting started with developing a module.
I forked the module template and then cloned it to my local machine.  In JASP, I enabled developer mode and then pointed to the directory of the module template.  When I then try to "Install Developer Module" I get an error (see below).  This occurred on two different development machines, though both Windows 11.  It occurred with no modifications to the module template.

I am not clear how to diagnose the error about R CMD config CC returning multiple lines.  But I can confirm that sh is accessible via the command line on both these machines.

This is probably some mistake on my end, but a pointer would be much appreciated.

Thanks.

Bob

```
Evaluating R-code:
options(renv.config.install.verbose=FALSE)
Output:

00:00:00.000: Received: '{
	"moduleCode" : "options(\"renv.config.install.verbose\" = FALSE);jaspBase::installJaspModule(modulePkg='C:/Users/rcalinjageman/Documents/GitHub/jaspesci', libPathsToUse=c('C:/Users/rcalinjageman/Downloads/JASP/R/library', 'C:/Users/RCALIN~1/AppData/Roaming/JASP/JASP/Modules/DEVELO~1'), moduleLibrary='C:/Users/RCALIN~1/AppData/Roaming/JASP/JASP/Modules/DevelopmentModule', repos='https://cloud.r-project.org', onlyModPkg=FALSE, force=TRUE, cacheAble=FALSE, frameworkLibrary='C:/Users/rcalinjageman/Downloads/JASP/R/library');",
	"moduleName" : "jaspModule",
	"moduleRequest" : "installNeeded",
	"typeRequest" : "moduleInstallRequest"
}
' so now clearing my send buffer
00:00:00.000: Engine received moduleInstallRequest message
00:00:00.000: About to run module request for module 'jaspModule' and code to run:
'options("renv.config.install.verbose" = FALSE);jaspBase::installJaspModule(modulePkg='C:/Users/rcalinjageman/Documents/GitHub/jaspesci', libPathsToUse=c('C:/Users/rcalinjageman/Downloads/JASP/R/library', 'C:/Users/RCALIN~1/AppData/Roaming/JASP/JASP/Modules/DEVELO~1'), moduleLibrary='C:/Users/RCALIN~1/AppData/Roaming/JASP/JASP/Modules/DevelopmentModule', repos='https://cloud.r-project.org', onlyModPkg=FALSE, force=TRUE, cacheAble=FALSE, frameworkLibrary='C:/Users/rcalinjageman/Downloads/JASP/R/library');'
jaspRCPP_evalRCode runs: 
"options("renv.config.install.verbose" = FALSE);jaspBase::installJaspModule(modulePkg='C:/Users/rcalinjageman/Documents/GitHub/jaspesci', libPathsToUse=c('C:/Users/rcalinjageman/Downloads/JASP/R/library', 'C:/Users/RCALIN~1/AppData/Roaming/JASP/JASP/Modules/DEVELO~1'), moduleLibrary='C:/Users/RCALIN~1/AppData/Roaming/JASP/JASP/Modules/DevelopmentModule', repos='https://cloud.r-project.org', onlyModPkg=FALSE, force=TRUE, cacheAble=FALSE, frameworkLibrary='C:/Users/rcalinjageman/Downloads/JASP/R/library');"
Evaluating R-code:
returnVal = 'null';	tryCatch(    suppressWarnings({	returnVal <- eval(parse(text=.rCode))     }),	    error	= function(e) { .setRError(  paste0(toString(e), '
', paste0(sys.calls(), collapse='
'))) } 	); returnVal	
Output:

00:00:00.414: Was a failure, now crafting answer.
00:00:00.414: Error was:
Error: Error in jaspBase::installJaspModule(modulePkg = "C:/Users/rcalinjageman/Documents/GitHub/jaspesci", : R CMD config CC returns more than 1 line, this will break renv and thus your install.
Most likely you are on mac and you should run `xcode-select --install` in a terminal.
If that doesn't help or you aren't on a mac: feel free to open an issue at https://github.com/jasp-stats/jasp-issues/issues/new/choose

The output was:
'sh' is not recognized as an internal or external command,
operable program or batch file.

tryCatch(suppressWarnings({
    returnVal <- eval(parse(text = .rCode))
}), error = function(e) {
    .setRError(paste0(toString(e), "\n", paste0(sys.calls(), collapse = "\n")))
})
tryCatchList(expr, classes, parentenv, handlers)
tryCatchOne(expr, names, parentenv, handlers[[1]])
value[[3]](cond)
00:00:00.414: Sending it.
```

### Expected Behaviour

The module should have installed.

### Steps to Reproduce

1.  Use the module template and try to install it.
2.
3.
...
See above

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JorisGoosen** [comment]
Aah, did you install rtools?

Also, if that doesnt help, can you open the R command window in JASP and run:
`Sys.getenv("PATH")` then paste the output here?

**Comment by rcalinjageman** [comment]
I *did* have Rtools installed, but it was Rtools 4.0.  

I've updated, and I no, no longer get *that* error -- instead I now get an error related to installing the Matrix package, similar to what is reported here: https://github.com/jasp-stats/jasp-issues/issues/2258 but where it looks like Matrix can't be moved into the library under the JASP directory:

# Installing packages --------------------------------------------------------

- Installing Matrix ...                         OK [copied from cache in 0.37s]

00:03:27.690: Was a failure, now crafting answer.
00:03:27.690: Error was:
Error: Error: could not copy / move file 'C:/Users/rcali/AppData/Local/JASP/temp/15340/tmp0/\renv-staging-2c60fa24e2/Matrix' to 'C:/Program Files (x86)/JASP/R/library/Matrix'
move: cannot rename file 'C:/Users/rcali/AppData/Local/JASP/temp/15340/tmp0/\renv-staging-2c60fa24e2/Matrix' to 'C:/Program Files (x86)/JASP/R/library/Matrix', reason 'Access is denied'
copy: error copying directory [error code 16]
robocopy /E /Z /R:5 /W:10 "C:/Users/rcali/AppData/Local/JASP/temp/15340/tmp0/\renv-staging-2c60fa24e2/Matrix" "C:/Program Files (x86)/JASP/R/library/.renv-copy-2c605c5695"
================================================================================


-------------------------------------------------------------------------------
   ROBOCOPY     ::     Robust File Copy for Windows                              
-------------------------------------------------------------------------------

  Started : Thursday, August 17, 2023 8:40:03 PM
   Source : C:\Users\rcali\AppData\Local\JASP\temp\15340\tmp0\renv-staging-2c60fa24e2\Matrix\
     Dest : C:\Program Files (x86)\JASP\R\library\.renv-copy-2c605c5695\

    Files : *.*
	    
  Options : *.* /S /E /DCOPY:DA /COPY:DAT /Z /R:5 /W:10 

------------------------------------------------------------------------------

2023/08/17 20:40:03 ERROR 5 (0x00000005) Creating Destination Directory C:\Program Files (x86)\JASP\R\library\.renv-copy-2c605c5695\
Access is denied.


tryCatch(suppressWarnings({
    returnVal <- eval(parse(text = .rCode))
}), error = function(e) {
    .setRError(paste0(toString(e), "\n", paste0(sys.calls(), collapse = "\n")))
})
tryCatchList(expr, classes, parentenv, handlers)
tryCatchOne(expr, names, parentenv, handlers[[1]])
value[[3]](cond)
00:03:27.690: Sending it.


but then if I run as administrator, it works!

**Comment by shun2wang** [comment]
like a permissions issue: `copy to 'C:/Program Files (x86)/JASP/R/library/Matrix', reason 'Access is denied'` so administrator run is works.

@JorisGoosen If I remember correctly we will not install dependencies to local JASP installation path but a user temp path?

**Comment by JorisGoosen** [comment]
Yeah it shouldnt be copying to `C:\Program files\` at all... But I sadly hve no more time top look at this before monday

**Comment by ThymonGosselink** [comment]
I have had the same issue with the matrix file ever since I tried to download a newer versions of JASP and nightly versions.

**Comment by RensDofferhoff** [comment]
I think I know the cause and to fix it we need to update to R4.3.1.
I am doing some experimentation.

**Comment by RensDofferhoff** [comment]
@ThymonGosselink are you also on Windows?
I got it working and will make a windows nightly at least

**Comment by RensDofferhoff** [comment]
mind that you might need rtools43 (on PATH)

**Comment by ThymonGosselink** [comment]
@RensDofferhoff yes on windows! thanks for the message! i will try rtools43, I have both but I few months ago 43 was not supported yet.

**Comment by RensDofferhoff** [comment]
@ThymonGosselink You will need the Nightlie Im making as well.
It will take a bit to complete and upload but it should work then

**Comment by ThymonGosselink** [comment]
@RensDofferhoff Rtool43 is ready ill wait for the nightly thanks!

**Comment by RensDofferhoff** [comment]
I uploaded the nightly https://static.jasp-stats.org/Nightlies/.

To get it to work you probably need to remove the contents of the C:\Users\<username>\AppData\Roaming\JASP\JASP  folder. As it is probably filled with contents form the previous release which use different everything.

![65914940](https://github.com/jasp-stats/jasp-issues/assets/20978635/9e1c9377-8499-4bd8-bd91-4a6479093a22)

**Comment by ThymonGosselink** [comment]
@RensDofferhoff I didn't remove the contents first and had the same error as when I removed the contents from the folder even reinstalling JASP.
![image](https://github.com/jasp-stats/jasp-issues/assets/128499116/ea9d5fdc-2934-4110-8185-988ef1c60e3e)

**Comment by RensDofferhoff** [comment]
@ThymonGosselink well actually there is an issue.
It works if you just keep clicking okay (probably).
But the error you showed is another but I just fixed.
I will update the nightly somewhere tonight!

**Comment by RensDofferhoff** [comment]
The new nightly fixes the icon error.
It might still give you an error about jaspBase the first time you try.
But the second time you try it should all work smoothly.

**Comment by ThymonGosselink** [comment]
@RensDofferhoff Thanks it runs without error!

**Comment by JorisGoosen** [comment]
> To get it to work you probably need to remove the contents of the C:\Users\username\AppData\Roaming\JASP\JASP folder.

Its why this button exists in Advanced Preferences: 
<img width="291" alt="afbeelding" src="https://github.com/jasp-stats/jasp-issues/assets/29062713/0a2c3b70-5525-4658-9db3-586f203ad87f">

**Comment by tomtomme** [comment]
@ThymonGosselink & @rcalinjageman 
From the discussion it sounds like this was solved. Please reopen, if I am mistaken!

**Comment by rcalinjageman** [comment]
I had to drop working on a JASP module for a while, but went to return to it today.  I've again run into a problem trying to install the developer module.

I'm working on Windows 11 with Rtools 4.3 installed.  

First, I cleared the previous install of Jasp 1.8, including all JASP directories in my user/appdata directories (local and roaming).  

Then I downloaded the latest JASP 0.19 nightly (JASP-nightly-development-bb60d059228a628af8530942a36d3c08d421a687) and unzipped it.

I forked the module template in github and then went to advanced settings to point JASP to the module directory.

When I try to install the developer module I get:

onLoad failed in loadNamespace() for 'renv', details:
  call: if (renv_path_within(cache, getwd())) {
  error: the condition has length > 1

In the rconsole, if I try to initiate renv (renv::diagnostics) I get the same error.

In the rconsole, getwd() yields:
[1] "C:/Users/rcali/AppData/Local/JASP/temp/2628" 

which is a valid directory created by JASP and populated with an internal.sqlite file, tmp1 and tmp0 directories, and an empty status file.

That's as far as I could get.  I haven't tried a different machine for the moment.  Any help would be appreciated -- I've finally got the space to dig into module development, and would love to get started.  Thanks.

**Comment by tomtomme** [comment]
Thx for the report.
Sounds like this bug I also experience:
https://github.com/jasp-stats/jasp-issues/issues/2588#issuecomment-1984496275

Should be fixed with next nightly, hopefully?

**Comment by JorisGoosen** [comment]
@rcalinjageman yes there were some problems with a recent update to renv, were now using a workaround version and it  should be in the latest nightlies (those since today at the very least).

You might want to run the "clear installed modules and cache" button in advanced preferences.

**Comment by tomtomme** [comment]
@rcalinjageman 
Any updates on how the esco module is evolving? Any help you need or problems you encountered?
