### ISSUE TITLE
Pie Chart

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#225]
## Template for bug reports

* JASP version: 0.9.1
* OS name and version: 4.14.78-1-MANJARO Linux
* Analysis: There is no (obvious?) way to create pie charts in descriptive analysis
* Steps to reproduce: Click descriptive analysis, plots section, no pie chart available

## Template for enhancement requests
 
* Enhancement: implement pie charts please.
* Purpose: I just started teaching a new bunch of first semesters' and was like "yeah students - this variable would be best displayed as a pie chart" and was baffled that it just was not there. "umm... ok, then lets go back to spss. There weĺl find it. It was just plain embarrassing, as I am not new to jasp and should have known it. But I just "expected" it to be there, if you know what I mean. I know histograms and bar charts are cool too, but a pie chart is just way too common in the media to ignore it. Its something new students know from their life before university. Something to hold on to before they go deep down the statistics rabbit hole.

**Comment by tomtomme** [comment]
Looks good, but is not yet in version 0.9.2

**Comment by tomtomme** [comment]
Still looking good, yet still not in 0.10

**Comment by TimKDJ** [comment]
@koenderks @vandenman can you guys add the piechart to JASPgraphs? Then we'll incorporate it in descriptives after

**Comment by tomtomme** [comment]
Thanks for the merge. However, I can't find a piechart option in jasp 0.10.2

**Comment by TimKDJ** [comment]
Yeah for now we just added the plotting functionality internally; we still need to implement it in descriptives. We're in the middle of a restructure of our analysis code which takes up a lot of our time, but hopefully we get around to it soon!

**Comment by tomtomme** [comment]
ok thanks for the heads up!

**Comment by TimKDJ** [comment]
The piechart will be in descriptives when we release the next version of JASP
