### ISSUE TITLE
[Bug]: Cannot plot GLM mixed model

### ISSUE THREAD

**Issue by kimbostroem** [jasp-stats/jasp-issues#2250]
### JASP Version

Others

### JASP Module

Mixed Models

### What analysis are you seeing the problem on?

Generalized Linear Mixed Model

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

In JASP 0.17.3 There is no possibility anymore to plot the data of a Generalized Linear Mixed Model. There are simply no model variables to select. This is in contrast to previous versions.

![Bildschirmfoto 2023-08-07 um 20 24 15](https://github.com/jasp-stats/jasp-issues/assets/92366643/f4daff78-be87-4018-a034-1c8b1fb32ce3)

### Expected Behaviour

Model variables should appear to be selected as plot variables

### Steps to Reproduce

1. Open a CSV data file
2. Choose Mixed Models/Generalized Linear Mixed Models
3. Choose Variables to analyze
4. Analysis works, but under Plot no variables can be selected to be plotted (see attached screenshot)
...
I would like to upload a JASP fle, but it seems that file type is not supported for upload by the system?

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by chris-olivers** [comment]
I have the exact same provlem with Mixed Model - Classical - Linear Mixed Models. 
Model can be defined and analysis runs, but no optiosn to plot: all fields empty.
JASP version 0.17.3 (July 23)
OS: Windows 11

**Comment by FBartos** [comment]
Thanks for the bug repoort. This indeed is an issue in the 0.17.3 release. I just checked that 0.18 (coming out soon) fixes this issue. Please, reopen the issue if the error persists after the update.
Cheers,
Frantisek

**Comment by chris-olivers** [comment]
Nice, thanks.

**Comment by ViSoph** [comment]
I have the problem with the 0.18 version too. Anyone could help?
