### ISSUE TITLE
[Bug]: JASP 0.17.3 cannot render Bayesian sequential analysis with robustness check

### ISSUE THREAD

**Issue by RenzoLanfranco** [jasp-stats/jasp-issues#2252]
### JASP Version

Others

### JASP Module

T-Tests, Other

### What OS are you seeing the problem on?

Windows 10, Windows 11

### Bug Description

In version 0.17.3, at least for Bayesian t-tests, there is a bug when one tries to plot a sequential analysis **with robustness check**. JASP crashes and shows the error message: 

I tried plotting this in version 0.17.0, and it works well, so this bug is probably new.

### Expected Behaviour

JASP should have no problem plotting Bayesian t-tests' sequential analysis with a robustness check.

### Steps to Reproduce

1. You open the JASP dataset
2. You run a Bayesian t-test (in this case, one-sample)
3. You select the boxes to plot the sequential analysis and tick robustness check
4. Image 1 shows the result with JASP 0.17.3, with the error message.

![jasp_bug02](https://github.com/jasp-stats/jasp-issues/assets/40778736/c7eef335-9d8f-4c17-9af0-118891d35ffb)

5. Image 2 shows the result with JASP 0.17.0 (no error).
![jasp_bug01](https://github.com/jasp-stats/jasp-issues/assets/40778736/b849baf4-ded8-4553-b165-ea5d3df086ae)

...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
@vandenman , @Kucharssim can you have a look?

**Comment by EJWagenmakers** [comment]
This is important to fix. I can reproduce the error. It is strange we did not catch this with our tests?!
