### ISSUE TITLE
[Bug]: problem with loading csv file

### ISSUE THREAD

**Issue by JustineBatino** [jasp-stats/jasp-issues#2253]
### JASP Version

Others

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

Opening a .csv file

### What OS are you seeing the problem on?

Windows 11

### Bug Description

opening a .csv file, then jasp loads, then shutting down. Another is opening the file in the JASP program itself, then it stays in the "loading dataset" been more than 20 mins, still 

https://github.com/jasp-stats/jasp-issues/assets/99676716/f00a8f6c-ec5d-4dcc-88d4-c92e2c35bfec

https://github.com/jasp-stats/jasp-issues/assets/99676716/619e8ccb-5215-4f0b-a8d5-a23215117a24

### Expected Behaviour

the file data should be loaded

the file should not stuck

### Steps to Reproduce

1.  Open JASP 17.3
2. browse a .csv file
3. open the file

1. right the .csv file
2. click the open with
3. select jasp.exe

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by shun2wang** [comment]
Hi @JustineBatino thanks for the report. can you upload the .csv file (zip it) with the issue in this comment?

**Comment by RensDofferhoff** [comment]
I cannot reproduce this on windows 11 for both the zip and installed version on our suite of CSVs.
Could you provide the csv to us?
