### ISSUE TITLE
[Bug]: Cannot connect to PostgreSql database

### ISSUE THREAD

**Issue by Stuckalf** [jasp-stats/jasp-issues#2254]
### JASP Version

0.17.2.1

### JASP Module

Unrelated, Other

### What analysis are you seeing the problem on?

Connect to database

### What OS are you seeing the problem on?

Windows 10

### Bug Description

It is impossible to connect to our working postgres database on localhost.
I always get the same error:
Error: driver not loaded driver not loaded
Please see steps to reproduce below.

PostgreSql v15.3.4
JASP v0.17.3
Driver installed in JASP: qsqlpsql.dll v6.4.2.0

### Expected Behaviour

Connection to database is successful

### Steps to Reproduce

1.Click on the "Open" dialog
2. Choose menu entry "Database"
3. Chose PostgreQql driver and enter the appropriate conntion settings, database name and credentials (I have the database running on localhost)
4. Click on the button "Connect to database"
5. Error occurs in the Preview data window: "Error: Driver not loaded Driver not loaded"
...
![jasp error connect to postgres](https://github.com/jasp-stats/jasp-issues/assets/103405739/ac6c1d64-ff81-4bfd-a6ed-2e6cdfa021f8)

### Log (if any)

[JASP 2023-08-11 08_38_20 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/12319139/JASP.2023-08-11.08_38_20.Desktop.log)
[JASP 2023-08-11 08_38_20 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/12319140/JASP.2023-08-11.08_38_20.Engine.0.log)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by RensDofferhoff** [comment]
Good Afternoon,

The Qt database drivers are wrappers around real database drivers that need to be installed on the system (they are a dependency) . 
Try installing the postgress drivers and make sure they can be discovered by Qt (they are on PATH).
https://www.postgresql.org/download/windows/


Greetings,
Rens

**Comment by Stuckalf** [comment]
Hello Rens,

I had already installed the drivers, but I didn't know that I had to add an entry in the PATH variable. That fixed it.
Seems to work right now - I just connected to the database and can access the tables.

Thanks for the quick support!

Greetings
Alf

**Comment by RensDofferhoff** [comment]
Great to hear!
I will discuss with my colleagues how to make this easier in the future.
Shipping all the various drivers for all our supported platform is a big hassle.
Better logs would be a start but we are open to suggestion beyond that.

**Comment by shun2wang** [comment]
@RensDofferhoff May should add this note into the database docs? https://github.com/jasp-stats/jasp-desktop/blob/stable/Resources/Help/filemenu/Database.md

**Comment by RensDofferhoff** [comment]
> @RensDofferhoff May should add this note into the database docs? https://github.com/jasp-stats/jasp-desktop/blob/stable/Resources/Help/filemenu/Database.md

Great idea I'll add a note on the development branch!
