### ISSUE TITLE
[Bug]: JASP PLS-SEM results different from other software

### ISSUE THREAD

**Issue by francischuah** [jasp-stats/jasp-issues#2256]
### JASP Version

Others

### JASP Module

SEM

### What analysis are you seeing the problem on?

Partial Least Squares SEM

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I try to use the PLS-SEM function as implemented in JASP and compare its output with result from ADANCO (A software develop by Henseler which is equivalent to cSEM as implemented in JASP).

The data and the output were available on the book of Henseler (2021). Nonetheless, with the same sets of data and same specification of the analysis, the output generated by JASP were way different from ADANCO and cSEM.

Attached is the example of output.
Reliability (JASP)
 
![image](https://github.com/jasp-stats/jasp-issues/assets/86041835/300551df-70d5-4d49-b886-e7b50fe190b3)

Reliability (Book)
![image](https://github.com/jasp-stats/jasp-issues/assets/86041835/52cfaca3-ff7c-4ae4-82b7-dd7b52826763)

 

Weights (JASP)
![image](https://github.com/jasp-stats/jasp-issues/assets/86041835/7d5258b0-c6e1-4856-9078-3d126eae1add)

Weight (Book)
 
![image](https://github.com/jasp-stats/jasp-issues/assets/86041835/92998335-fa2a-4f8e-b632-c9ea1e79aa20)

Hereby I attached the zip file for the dataset in excel and jasp format
 
[Project Files.zip](https://github.com/jasp-stats/jasp-issues/files/12320983/Project.Files.zip)

### Expected Behaviour

Supposedly PLS-SEM in JASP should gives the similar result like ADANCO and cSEM

### Steps to Reproduce

1. Load the same dataset into three different application (JASP, ADANCO, cSEM)
2. The same syntax were copied and paste into cSEM and JASP
3. Ensure the setting of estimation is similar
4. Run the analysis and the output will be produced

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment]
@francischuah, thanks for creating the issue. Unfortunately, from your .jasp file I cannot find a model specification. Could you paste the syntax here somwhere?

**Comment by francischuah** [comment]
> @francischuah, thanks for creating the issue. Unfortunately, in your .jasp file I cannot find a model specification. Could you paste the syntax here somwhere?

Hi,
Please find the syntax as below

OrgPres =~ cei1 + cei2 + cei3 + cei4 + cei5 + cei6 + cei7 + cei8
OrgIden =~ ma1 + ma2 + ma3 + ma4 + ma5 + ma6
AffLove =~ orgcmt1 + orgcmt2 + orgcmt3 + orgcmt7
AffJoy =~ orgcmt5 + orgcmt8
Gender <~ gender
OrgIden ~ OrgPres
AffLove ~ OrgPres + OrgIden + Gender
AffJoy ~ OrgPres + OrgIden + Gender


A side note:
Even indicator correlation gives different output. ADANCO and cSEM demonstrate some negative correlation not in JASP.

**Comment by juliuspfadt** [comment]
@francischuah, I found the issue. So what JASP is doing is reading the data as ordinal variables, since they actually are specified as ordinal. The ordinal data is the passed to cSEM and voila. If you order your data set (`as.ordered` for every column) and run the analysis again in R, you will obtain the same results as in JASP. I am attaching the ordinal data set so you might try it out. Given that this is desired behavior, I am closing this now 
[ordData.rds.zip](https://github.com/jasp-stats/jasp-issues/files/12332229/ordData.rds.zip)
