### ISSUE TITLE
[Bug]: Install developer module has begun failing with install of Matrix

### ISSUE THREAD

**Issue by rcalinjageman** [jasp-stats/jasp-issues#2258]
### JASP Version

0.17.2.1

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

Custom developer module

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

Starting today, installing a developer module I had been working on fails.  It's strange because I had the developer module working just fine on OS X, but now it is failing with the same error on 3 different virtual machines with OS X I had setup.  It seems to fail when installing Matrix.  I've looked through older logs, and there have been no previous problems installing Matrix -- it's always just installed.  It looks like maybe it's trying to compile it instead of pulling the binary?  Not sure.  

### Expected Behaviour

The developer module should have installed

### Steps to Reproduce

1. Pull rcalinjageman/jaspesci2. 
2. Point JASP to that directory as the developer module3. . Try to install the developer module .

### Log (if any)

[JASP 2023-08-14 16_57_36 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/12340327/JASP.2023-08-14.16_57_36.Desktop.log)
[JASP 2023-08-14 16_57_36 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/12340328/JASP.2023-08-14.16_57_36.Engine.0.log)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JorisGoosen** [comment]
@rcalinjageman it is indeed copiling something there and failing to find fortran.
But perhaps you are just missing that?

Do you have https://mac.r-project.org/tools/gfortran-12.2-universal.pkg installed?

**Comment by rcalinjageman** [comment]
I tried installing gfortran and restarting JASP, but same error.  

It's really strange because a) this was working on the same machine earlier, though it looks like it was installing Matrix 1.6, not Matrix 1.6-1, and b) this is affecting every osx virtual machine I had setup - both an older 10.15 virtual machine and a newer 11 virtual machine and even a clean new instance of each, c) I have tried removing references to packages that depend on Matrix from the DESCRIPTION and NAMESPACE files for my module but JASP keeps trying to install Matrix anyways, and d) If I look in the library for the R framework included in JASP, it looks like it already *has* Matrix.

Hope it's not something silly on my end, but I'm really struggling to get started with module development in JASP.  I can't get any Windows machines to even begin compilations.  Once I setup some OSX virtual machines I was immediately able to install and get a first analysis running, with output, etc... but this Matrix issue has me pulling my hair out.

**Comment by JorisGoosen** [comment]
Yeah I heard from my colleaugues @RensDofferhoff and @vandenman that the same problem occured for them so it seems this is related to R somehow, but we havent had the chance to look into it.

we'll have to fix this anyway cause it sounds like it is going to bite us.
But as of yet we don't know what's causing it yet.

@vandenman you dont happen to know of a nice workaround for this yet?

**Comment by rcalinjageman** [comment]
Thanks; I'll stay tuned.  Good to know it's not something silly I overlooked.

by chance: do you know if I'm the only one encountering errors building a developer module in Windows as well? (https://github.com/jasp-stats/jasp-issues/issues/2249).  On every machine/flavor I've tried I get "R CMD config CC returns more than 1 line, this will break renv and thus your install." and I haven't been able to figure out a way to go forward.

**Comment by vandenman** [comment]
So the R CMD config CC error is one that we added ourselves because otherwise `renv` crashes much later with an error. If you open a terminal, what do you get when you run `R CMD config CC`? Or alternatively, in R what do you get when you run
```r
Rexe <- file.path(R.home("bin"), "R.exe")
system2(Rexe, c("CMD", "config", "CC"))
```

@JorisGoosen, we added this in https://github.com/jasp-stats/jaspBase/pull/95 because of these lines in `renv` ([source](https://github.com/rstudio/renv/blob/70318f1562f96029f51ebbb8e99e7fa93a22280c/R/scope.R#L170)) but that is only ever run on macOS. Shouldn't we only run this check on macos then?

**Comment by JorisGoosen** [comment]
> Shouldn't we only run this check on macos then?

It turns out this can also catch silly errors on windows (like a missing rtools or conflicting ming installs), although the error message might be amended to say something non-macos I guess

**Comment by JorisGoosen** [comment]
Does this one work: https://static.jasp-stats.org/Nightlies/macOS-x86_64/JASP-nightly-development-b5783619b4989ae43f4f44c795c54abc4b0b9dfc.dmg ?

**Comment by tomtomme** [comment]
@rcalinjageman 
Please reopen, if you found time to test a new jasp version and have more feedback for us. Thx!
