### ISSUE TITLE
Integrate Compute Column and Filter construction with dataview

### ISSUE THREAD

**Issue by JorisGoosen** [jasp-stats/jasp-issues#226]
A user mentioned he found it more intuitive to drag the columns from the dataview into the constructor as opposed to the list on the left. 

This is actually not a bad idea, although it could be more challenging than I now think, this issue is mostly here as a reminder and to-do.

**Comment by tomtomme** [comment]
I do not think, this would be very useful, when you have lots of variables. It is very cumbersome to scroll through a long list of variables in the data view horizontaly. The current vertical scroll works much better. 
It would be beneficial however, if we could sort the variable list by type and by name, like we can do in the analysis panels.

**Comment by JorisGoosen** [comment]
I agree this is not the best idea and sorting them is a better idea.
But probably I would want to rewrite the "filter/column constructor) interface in any case...
