### ISSUE TITLE
[Bug]: Disattenuate composite correlations in JASP PLS SEM

### ISSUE THREAD

**Issue by francischuah** [jasp-stats/jasp-issues#2260]
### JASP Version

Others

### JASP Module

SEM

### What analysis are you seeing the problem on?

PLS SEM

### What OS are you seeing the problem on?

Windows 10

### Bug Description

This is a bug that has been explained in (#2167). I attached screenshot below for reference.

In PLS SEM, the disattenuate composite correlations implies that the estimation is done using Mode A consistent where the loadings is corrected for attenuation

Output from ADANCO, Mode A consistent -  Disattenuate composite correlations "TRUE"
![image](https://github.com/jasp-stats/jasp-issues/assets/86041835/849d62c8-6787-4184-9aa5-f69a51228658)

Output from JASP, Mode A - Disattenuate composite correlations "TRUE"
![image](https://github.com/jasp-stats/jasp-issues/assets/86041835/7a80a5ec-1130-4462-95bb-267929b697aa)

Both demonstrate consistency in terms of output.

However, when "Disattenuate composite correlations" is unchecked, the output between ADANCO and JASP PLS SEM differs. It is observed that the loadings for JASP PLS SEM remains the same.

Output from ADANCO, Mode A - Disattenuate composite correlations "FALSE"
![image](https://github.com/jasp-stats/jasp-issues/assets/86041835/8fa3e1b3-4ef1-49f6-8cfb-822bac986fb6)

Output from JASP, Mode A - Disattenuate composite correlations "FALSE"
![image](https://github.com/jasp-stats/jasp-issues/assets/86041835/89ba2653-22e6-42c8-a961-f4085db379ad)

It seems like the results of factor loadings remain the same for JASP.

Below attached the zipped project file in excel and in JASP format
[Project Files.zip](https://github.com/jasp-stats/jasp-issues/files/12344916/Project.Files.zip)

### Expected Behaviour

If "Disattenuate composite correlations" is checked in JASP, the result of factor loadings from JASP and ADANCO is consistent.

If "Disattenuate composite correlations" is unchecked, the result from JASP and ADANCO is not consistent. 

Output from JASP, Mode A - disattenuate composite correlations "FALSE" and output from Output from ADANCO, Mode A - disattenuate composite correlations "FALSE" should gives the same result.

### Steps to Reproduce

1. Specify the model, weighting approach "PLS-PM", Inner weighting scheme "Factorial"
2. Run the analysis
3. Check and uncheck  "disattenuate composite correlations"
4. Observe the result for factor loadings. It is supposed to be different but at present it is the same in JASP.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment]
@francischuah thanks for creating the issue and reporting the bug. There was a missing argument. It should be fixed in one of the next releases

**Comment by francischuah** [comment]
@juliuspfadt I saw JASP 0.18 has been release but this issue is not mentioned in the release notes. Is it that this issue has not been rectified?

**Comment by juliuspfadt** [comment]
Unfortunately, no. The pull-request still needs to be properly checked, so I am guessing it will be in the next release :)

**Comment by EJWagenmakers** [comment]
We hope to include this in a hotfix! (no promises, but we will try)
