### ISSUE TITLE
[Bug]: Run RMANOVA slowly and crash engine

### ISSUE THREAD

**Issue by Simson2023** [jasp-stats/jasp-issues#2264]
### JASP Version

0.17.3

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

Repeated measures anova

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

I have noticed that the bug is present on both Windows and MAC (Intel) systems. The program becomes unusable when attempting to analyze a relatively small data set, as the process takes excessively long or simply won't load. Additionally, an error message pops up stating that the engine crashed while attempting to run the analysis.

### Expected Behaviour

The analysis should have run but is taking ages or not responding at all.

### Steps to Reproduce

1. Open data set
2. Repeated measures
3. Load several variables for repeated measures
4. Select a between-subject factor (two groups)
5. Output takes endless or doesn't load at all. Once loaded engine crashes while trying to run the analysis.

I also had other analyses running, but they were either too slow or not responding at all. This problem seems to have persisted for quite some time. In earlier versions, I didn't seem to have this problem, though.

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by shun2wang** [comment]
Hi @Simson2023 thanks for the report, could you pls upload or email the data file has this problem? so that we can find the reason. with thanks.

**Comment by RensDofferhoff** [comment]
I have not been able to reproduce this yet.
As @shun2wang  suggested are you able to share the data/jasp file?
If not could you provide some details (size/types) of the data along with a more detail on what you did?
