### ISSUE TITLE
Unable to install JASP through SCCM

### ISSUE THREAD

**Issue by tdkelly** [jasp-stats/jasp-issues#2267]
### JASP Version

0.17.3

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I was having the same problem as last year where it would try to install additional components. Last year updating the video driver helped. This time around I updated the video and it will install when I am logged in via running the app through the GUI or using a powershell script. When I try to run it through SCCM through the system account it fails and rolls back and deletes everything it tried. It should be said it only happens on some systems, many of the same model are not having this issue. 

### Expected Behaviour

Software's should install

### Steps to Reproduce

1. Run install vie SCCM
2.
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @tdkelly, this is annoying, but we don't have SCCM here, and apparently the problem occurs only with few PC's, so it is really difficult for us to guess what causes this problem. I can imagine there is maybe some permission issue on those PC's, so you could ask your administrator to give you temporary admin rights to test if it then works. But as I said, this is a wild guess...
If I understand well, you can still install JASP if you don't use SCCM, so apparently this is not blocking for you.

**Comment by tdkelly** [comment]
Hello, 
                Thanks for the reply. It is strange almost like it does not like the system account which is what SCCM uses when installing software without a user logged in. We tried installing it on approx. 160 machines and all but 14 went fine. These are newly imaged machines, same model and some of the others and using the same image. I did check permissions, and all looked fine, all had updated video drivers so I am at a loss. Attached is the msi log maybe something in there I am missing. I did get around it on the 14 machines by logging in then running it. I would like to get this figured out to future proof our process., Thanks 
[jasp.zip](https://github.com/jasp-stats/jasp-issues/files/12410762/jasp.zip)
