### ISSUE TITLE
[Bug]: JASP-0.17.3.0-macOS-arm64.dmg missing

### ISSUE THREAD

**Issue by Ruud-St** [jasp-stats/jasp-issues#2268]
### JASP Version

0.17.3

### JASP Module

Unrelated

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

Version 17.3 for macOS arm64 is missing at the release page.
https://github.com/jasp-stats/jasp-desktop/releases/tag/v0.17.3

Cloud you please add this?
Thank you.

### Expected Behaviour

-

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by RensDofferhoff** [comment]
Hi!
I tried it a few times already but Github seems unhappy with the file size.
You can however download the file from our website: https://jasp-stats.org/download/

-Rens

**Comment by RensDofferhoff** [comment]
Its up on github now as well.

**Comment by Ruud-St** [comment]
Thank you for the quick responses and taken actions!
