### ISSUE TITLE
[Bug]: Engine crashed while opening jasp file

### ISSUE THREAD

**Issue by abaywudu** [jasp-stats/jasp-issues#2269]
### JASP Version

0.17.3

### JASP Module

SEM

### What OS are you seeing the problem on?

Windows 10

### Bug Description

when i tried to open jasp. it says jasp had been experienced unexpected internal error-the engin crashed
![image](https://github.com/jasp-stats/jasp-issues/assets/143053352/36c254cf-e98b-4940-804a-5e8aaf3b10ca)

### Expected Behaviour

when i tried to open jasp. it says jasp had been experienced unexpected internal error-the engin crashed

### Steps to Reproduce

1.no
2.
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by shun2wang** [comment]
Hi @abaywudu thanks for your report, could you upload the .jasp file (zip the file and drag to comment filed) here?  with thanks.
