### ISSUE TITLE
Enhancement request: Pairwise comparisons following repeated-measures ANOVA

### ISSUE THREAD

**Issue by luka-j** [jasp-stats/jasp-issues#227]
* Enhancement: Allow pairwise comparisons following repeated-measures ANOVA, i.e. a way to compare differences between levels of one factor, on every combination of levels of other factors.
* Purpose: For example, interpreting interactions. SPSS has a way to do this, but it lacks any graphical interface to do it, instead requiring /EMMEANS command in syntax.
* Example: Consider three-way ANOVA, with factors A (levels a1, a2), B (levels b1, b2), C (levels c1, c2). Desired feature would output a table akin to:

| A   | B  | C (1) | C (2) | MD (1-2)                  | SE of the difference | CI of the difference | p | ... |
|----|----|------|-------|-----------------------|---|----|---|---|
| a1 | b1 | c1    | c2     | c1-c2, on a1 and b1 | ...  |     |     |  |
|      | b2 | c1    | c2    |  c1-c2, on a1 and b2 |     |      |     |  |
| a2 | b1 | c1    | c2    |  c1-c2, on a2 and b1 |     |     |     |  |
|      | b2 | c1    | c2    | c1-c2, on a2 and b2 |      |     |     |  |

User should have an option to select factor for which comparisons are made (in the example above, it's C). It should, of course, work with factors which have more than two levels.
* Current state: It outputs only differences between levels of a single factor, which isn't very helpful when there are significant interactions.

_Please note this has [already been suggested](https://github.com/jasp-stats/jasp-desktop/issues/90), but the issue was closed without implementing the requested feature, and rather settling for an inferior solution._

**Comment by tomtomme** [comment]
@luka-j @JohnnyDoorn 
Since JASP 0.16.1 in 2022 we have post hoc tests for RM ANOVA which also covers interactions. So this seems done.

Please reopen if you disagree!
