### ISSUE TITLE
[Feature Request]: Plot Mean+SD in Descriptives

### ISSUE THREAD

**Issue by bmatyasb** [jasp-stats/jasp-issues#2270]
### Description

Plot with Mean and SD in the Descriptives

### Purpose

Create a plot showing Mean and SD

### Is your feature request related to a problem?

It often happens that statistical tests are used to compare averages. It may well be that most tests have the option of a graph showing the difference in means,  but it's usually barplot (not pretty, not popular) or dot+error, which shows the mean and 95CI/SE. However, neither of these show the data points. The boxplot available in the Descriptive would be ideal, but it does not show a mean.

### Is your feature request related to a JASP module?

Descriptives

### Describe the solution you would like

It would be a great help if in Descriptive statistics, in the Plots that can be customized, there could be an option to display the mean and the standard deviation around the mean.

### Describe alternatives that you have considered

The other, slightly more time-saving solution would be to show the figure on the boxplot. Say with a + sign. Although visual modelling has mean+sd, but visual modelling plots are not very aesthetic now.  I indicate that the most optimal would be to have a mean and standard deviation graph in the descriptive, where the data points would be visible.

**Comment by EJWagenmakers** [comment]
Just to be sure: the raincloud plots do not address your need?

**Comment by bmatyasb** [comment]
the raincloud plot is a big favourite of mine, but unfortunately it doesn't show the average+sd. I know that it shows distributions in a simple way, and for those who are good at statistics, that's fine. However, to this day, most reviewers of scientific papers find it hard to digest that they don't see mean and standard deviation in a plot comparing means. :( In fact, my experience is that some people don't even understand raincloud plots... 
The raincloud plot would be fine if the mean and standard deviation were on the point cloud. In addition, the boxplots already show the median and quartiles, and the density plot gives a perfect overall picture.
Of course, it could be done with other software, only if one is already working in JASP, it is convenient to go through the whole method in it...

**Comment by chantelanuit** [comment]
I agree with this request. When a researcher includes a figure in a paper, it needs to be in line with the statistic used in the procedure. Therefore, adding the mean on the plot would be essential when using the Raincloud plot to illustrate the data used  with a t-test / ANOVA for example. That might be nice to have an option to specify if the mean is to be added or not on the plot.

**Comment by EJWagenmakers** [comment]
Well it would be good to allow the raincloud plots to be customized a bit more. We were working on that but the project stalled -- I will see whether I can revive it.
Cheers,
E.J.

**Comment by chantelanuit** [comment]
In order to keep the JASP interface clean (more options = more cluttering), maybe would it be possible to add an option in the R syntax to add the mean, adjust the colors, ... just a suggestion. Or in the image edition sub-menu ?

**Comment by EJWagenmakers** [comment]
Maybe...or even a separate module even.

**Comment by tomtomme** [comment]
@bmatyasb and @chantelanuit 
The flexplot module in JASP allows displaying mean + SD when you feed it with a metric DV and a categorial IV and shows the raw data at the same time.

But sure, a cusomizable raincloudplot would be cool. 
So maybe you want to change the title of this issue accordingly.

**Comment by tomtomme** [comment]
@bmatyasb @chantelanuit 
now tracked here #1698
Lets discuss there.
