### ISSUE TITLE
[Bug]: Incorrect assumptions in the LDA

### ISSUE THREAD

**Issue by bmatyasb** [jasp-stats/jasp-issues#2272]
### JASP Version

0.17.3

### JASP Module

Machine Learning

### What analysis are you seeing the problem on?

Linear Discriminant

### What OS are you seeing the problem on?

Windows 11

### Bug Description

In the LDA conditions there is an Equal class means. What do you mean? To the best of my knowledge, the LDA has no such condition. I looked it up just in case, but I couldn't find it anywhere. 
However, there is no test for the multivariate normality, which is an assumption.
Am I getting something wrong?
https://en.wikipedia.org/wiki/Linear_discriminant_analysis
https://www.raybiotech.com/learning-center/linear-discriminant-analysis-model/#:~:text=LDA%20makes%20a%20lot%20of,are%20identical%20across%20different%20classes.
https://www.analyticsvidhya.com/blog/2021/08/a-brief-introduction-to-linear-discriminant-analysis/#:~:text=Assumptions%3A,classes%20has%20identical%20covariance%20matrices.

### Expected Behaviour

I don't think it should be there.

### Steps to Reproduce

1. NA
2.
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by koenderks** [comment]
I think it was more of a reality check, if the class means do not differ then I guess there is no point in trying to separate the classes using LDA. I've added multivariate normality checks in the linked PR.
