### ISSUE TITLE
[Bug]: Graph variation components has not been built

### ISSUE THREAD

**Issue by stataisr** [jasp-stats/jasp-issues#2273]
### JASP Version

0.17.3

### JASP Module

Quality Control

### What analysis are you seeing the problem on?

Gauge r&R (non-replicable measurements)

### What OS are you seeing the problem on?

Windows 10

### Bug Description

A bug happened! When conducting an analysis, the results contain tables with variance components, but a corresponding graph is not plotted for this data. In another example, such a graph was built
[tensile machines.zip](https://github.com/jasp-stats/jasp-issues/files/12479384/tensile.machines.zip)
[Doc1.zip](https://github.com/jasp-stats/jasp-issues/files/12479387/Doc1.zip)

### Expected Behaviour

This should have happened instead. This graph is from Minitab, the result tables from JASP and Minitab  are exactly the same
[Doc2.zip](https://github.com/jasp-stats/jasp-issues/files/12479409/Doc2.zip)

### Steps to Reproduce

1.
2.
3.
...
[Steps to Reproduce.zip](https://github.com/jasp-stats/jasp-issues/files/12479508/Steps.to.Reproduce.zip)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JTPetter** [comment]
Thanks for the report @stataisr . I can reproduce this and will look into it.
