### ISSUE TITLE
[Bug]: Percentage Process Variation Graph hadn't been built

### ISSUE THREAD

**Issue by stataisr** [jasp-stats/jasp-issues#2274]
### JASP Version

0.17.3

### JASP Module

Quality Control

### What analysis are you seeing the problem on?

Measurement System Analysis, Linearity Study

### What OS are you seeing the problem on?

Windows 10

### Bug Description

1. When analyzing the linearity and bias of the measurement system, the results table displays % linearity. Together with the % bias, it should be displayed on the chart Percentage Process Variation Graph. But this does not happen in this file.
2. If you press "Edit Image" on the Percentage Process Variation Graph, JASP closes without any warning
[Linearity.zip](https://github.com/jasp-stats/jasp-issues/files/12485480/Linearity.zip)

### Expected Behaviour

![image](https://github.com/jasp-stats/jasp-issues/assets/127410073/7fbc037f-aa38-4be6-8568-37d42ddec213)

### Steps to Reproduce

1.
2.
3.
...
[Steps to Reproduce.zip](https://github.com/jasp-stats/jasp-issues/files/12485584/Steps.to.Reproduce.zip)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JTPetter** [comment]
Same here, thanks for the report @stataisr . I can reproduce this and will look into it.
