### ISSUE TITLE
[Bug]: JASP Not Responding When Trying to Open Application

### ISSUE THREAD

**Issue by Picco211** [jasp-stats/jasp-issues#2275]
### JASP Version

0.17.3

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 11

### Bug Description

I just installed the application, rebooted, and then tried to open the application.  I am trying to open the application to do some analysis and the application goes to a white screen with JASP (Not Responding) showing in the title bar.  I have not been able to get past this point.  I have tried uninstalling and reinstalling, but no luck.

### Expected Behaviour

That the application would have opened and I would be able to do some analysis.

### Steps to Reproduce

1. Open the  app
2. See White Screen with JASP (Not Responding)
3.
...
![JASP Not Responding](https://github.com/jasp-stats/jasp-issues/assets/143721553/ac585a7c-680b-4a49-be3f-3cd00d034ee0)

### Log (if any)

Not able to access the logs since the application won't open.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @Picco211, could you start a command prompt, and change the current directory to where JASP was installed (type either `C:\Program Files (x86)\JASP` or `C:\Program Files\JASP`), and start JASP from the command line by typing:
`JASP.exe --logToFile --safeGraphics`
( this will start JASP with the 'safeGraphic' mode).
