### ISSUE TITLE
[Bug]: Bug happen on Assumption Checks on Linear Discriminant Machine Learning

### ISSUE THREAD

**Issue by charismamamet** [jasp-stats/jasp-issues#2278]
### JASP Version

0.17.2.1

### JASP Module

Machine Learning

### What analysis are you seeing the problem on?

Linear Discriminant Classification

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

When i click on any of the assumption checks, this message is showing.

This analysis terminated unexpectedly.

Error in cov(data[grouping = lev[i], ]): is.numeric(x) || is.logical(x) is not TRUE

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.mlClassificationLdaTableEqualityCovMat(dataset, options, jaspResults, ready, position = 10)

.boxM(dataset[, options[['predictors']]], dataset[, options[['target']]])

cov(data[grouping = lev[i], ])

stopifnot(is.numeric(x) || is.logical(x), is.atomic(x))

### Expected Behaviour

It would show the result of the assumption check without the error log

### Steps to Reproduce

1. I use the attached csv file
2. I choose the Linear Discriminant Classification on Machine Learning
3. I click the "Equality of Class Means" on the assumption check
4. Error message show
...
[Copy of all lang results - data entry.csv](https://github.com/jasp-stats/jasp-issues/files/12511994/Copy.of.all.lang.results.-.data.entry.csv)
[Copy of all lang results - data entry.zip](https://github.com/jasp-stats/jasp-issues/files/12512005/Copy.of.all.lang.results.-.data.entry.zip)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@charismamamet 
tested with jasp 0.18.3. 

Koendersk "fixed" this by adding a new error message:
```
Tests of Equality of Covariance Matrices     
 There are one or more levels in the target variable with less than two observations.
```

So maybe the data set is to small?
I hope this helps. Please reopen, if you have further questions.
