### ISSUE TITLE
Enhancement: ANCOVA post-hoc tests

### ISSUE THREAD

**Issue by kylebr1** [jasp-stats/jasp-issues#228]
* Enhancement:  JASP should conduct ANCOVA post-hoc tests on the adjusted group means instead of the non-adjusted group means. 
* Purpose: This would make it possible to determine which groups significantly differ from one another after running an ANCOVA.

**Comment by JohnnyDoorn** [comment]
Hi @kylebr1 
As of now, JASP uses the nlht function in combination with the mcp function, both from the Multcomp package in R, to conduct post-hoc tests. It is my understanding that these functions and the way they are called do use the adjusted group means, where the covariate is taken into account. 
Do you mean another adjustment to the means?
Kind regards,
Johnny

**Comment by kylebr1** [comment]
Hi Johnny,

I stand corrected; JASP does perform post-hoc tests for ANCOVA correctly. I must have previously misunderstood the results for my data. 

Thank you!

**Comment by AlexanderLyNL** [comment]
Thanks for getting back to us.

**Comment by EJWagenmakers** [comment]
Yes, and it is also useful for us to confirm again that we have this covered.
Cheers,
E.J.
