### ISSUE TITLE
[Bug]: JASP 0.18 cannot run Bayesian one-sample t-tests

### ISSUE THREAD

**Issue by RenzoLanfranco** [jasp-stats/jasp-issues#2280]
### JASP Version

0.18.0

### JASP Module

T-Tests

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

Hi. Some time ago, I reported that JASP 0.17.3 crashed when running Bayesian one-sample t-tests' sequential analyses with robustness check. According to the webpage, this has been solved in version 0.18 (Apple Silicon version). Unfortunately, now I've encountered a worse bug: Bayesian one-sample t-tests cannot be run. It gives the following error: "there is no package called 'mvtnorm'. The output table only contains NaNs.
I've tried running other Bayesian t-tests (e.g., paired), and they have the same problem. Frequentist t-tests don't show this bug.

<img width="1160" alt="Screenshot 2023-09-07 at 09 50 21" src="https://github.com/jasp-stats/jasp-issues/assets/40778736/e7845152-3ebd-4de5-9125-928794dc7755">

### Expected Behaviour

Bayesian one-sample t-tests should run smoothly.

### Steps to Reproduce

1. Load any dataset into JASP 0.18
2. Run Bayesian one-sample t-tests
3.
...

### Final Checklist

- [ X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @RenzoLanfranco, I cannot reproduce this issue, can you reproduce it with a dataset from the Data Library? 
We had some  issues with the macOS Silicon version, and we have just made a new version: https://static.jasp-stats.org/JASP-0.18.0.0-macOs-arm64-new.dmg Can you also try it?

**Comment by RenzoLanfranco** [comment]
Yes, I still can reproduce it. I've found other bugs too. The stable version of Jasp for Apple Silicon version (at least) is 0.17, by the way. I found another but that I'll report in a minute.

**Comment by boutinb** [comment]
Hi @RenzoLanfranco Can you tell us which dateset you use to reproduce this problem? I have tried several datasets form the Data Library, and all worked.

**Comment by tomtomme** [comment]
@RenzoLanfranco 
Please reopen, if you can share more details or find time to re-test with jasp. 0.18.3!
