### ISSUE TITLE
[Bug]: Jasp 0.18 wasn't able to save to a Google Drive folder

### ISSUE THREAD

**Issue by felipeviegas** [jasp-stats/jasp-issues#2281]
### JASP Version

0.18.0

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 11

### Bug Description

Hello guys, I wasn't able to save a JASP analysis to a Google Drive folder (with no mirroring settings). As I try, an error message informs: "Save failed. Unable to save file. File could not be opened." No problems on saving to regular folders in the machine. I had never had this problem with previous versions from Jasp.

### Expected Behaviour

Saved the file

### Steps to Reproduce

1. Computer must have Google Drive for Desktop
2. Create any analysis or data file in JASP.
3. Try to save it in one of the Google Drive folders. It (probably) must be the streaming settings of the program (as mine).
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Strange, I can add a JASP file on my Google Drive without problem.... Can you send me one which does not work?

**Comment by felipeviegas** [comment]
> Strange, I can add a JASP file on my Google Drive without problem.... Can you send me one which does not work?

Hello Bruno, thanks for the response. I had some other error with v0.18 and I had to roll back to 0.17.3 because I am in the middle of some various analysis. It was a different error, so I didn't even bother too much with the second one. I'll try again once this moment pass....

This data is the one I was trying to use. I believe there is nothing wrong about it! Let me know. Thanks.

[JASP.csv](https://github.com/jasp-stats/jasp-issues/files/12557426/JASP.csv)

**Comment by boutinb** [comment]
> I had some other error with v0.18 and I had to roll back to 0.17.3

But it is quite important for us to know what are these errors.... If you have time, can you tell us?

**Comment by felipeviegas** [comment]
I know Bruno. And I am sorry to that. But I have some three projects to analyse up to Sunday. I will get back to it. Promisse!

**Comment by richardnaar** [comment]
Difficulty Saving .jasp Files in Version 0.18.0.0

Hi, I think I am experiencing related issue.

Description:
Upon updating to version 0.18.0.0, I've encountered an issue when attempting to save .jasp files. This problem was not present in the previous version 0.17.3.

Additionally, a colleague using the same version (0.18.0.0) experienced a related issue. When saving a .jasp file located in Microsoft OneDrive, the save operation succeeds the first time. However, subsequent save attempts after making changes result in the following error:

"A file 'C:/Users/Kasutaja/OneDrive/Desktop/juku.jasp' or file 'C:/Users/Kasutaja/OneDrive/Desktop/juku.jasp.tmp' is being used by another application".

Environment:

JASP Version: 0.18.0.0 (issue not present in 0.17.3)
File Location: Microsoft OneDrive
Operating System: Windows 11 Enterprise

**Comment by shun2wang** [comment]
Hi @richardnaar and @felipeviegas can you try this version of JASP and see if it have same problem. you can download at http://static.jasp-stats.org/Nightlies/WindowsZip/JASP-nightly-stable-c7e0f72b5143dcd20b67966b50ff273ca65f6db4.zip unzip it and run `JASP.exe` file. if you still have problems please upload a screenshot and logs.

with thanks.

**Comment by felipeviegas** [comment]
Hello Wang, 

I was successfully able to save in a Google Drive folder with this version. I also ran a repeated measures ANOVA and it worked just fine. I ran the application directly from the desktop, after extracting it, but I believe this shouldn't be an issue. Jasp gave me a warning upon first time opening, that it had to make a few changes in folders, as I download it as a zip, but everything worked smoothly.

Thank you very much for the fix!

**Comment by shun2wang** [comment]
It was fixed by @JorisGoosen , thanks to him.

Just note that is a beta version, you may use it temporarily, the next release version (0.18.1) will be recommended.

**Comment by shun2wang** [comment]
ah @richardnaar with the version which i given? by run jasp.exe but not double click the .jasp file right?

**Comment by richardnaar** [comment]
Sorry, @shun2wang, I made a mistake. I accidentally reinstalled the old version. Sorry for that. I'll let you know how it goes.

**Comment by shun2wang** [comment]
@richardnaar it doesn't matter haha, if you still have issue it's better to open a new issue.

thanks!

**Comment by Christian-CT** [comment]
Hello, I am having the same problem with version 18.0. I can save to desktop, but not to Google Drive. Thank you. 
![image](https://github.com/jasp-stats/jasp-issues/assets/145491721/93635fcc-69a5-4387-98b9-e88798a34cd7)
![Captura de pantalla 2023-09-19 114529](https://github.com/jasp-stats/jasp-issues/assets/145491721/cbb5b8f4-7b08-441c-b61f-41263204243d)
