### ISSUE TITLE
[Bug]: Incorrect confidence interval in descriptive statistics

### ISSUE THREAD

**Issue by nctorbert** [jasp-stats/jasp-issues#2288]
### JASP Version

0.18.0

### JASP Module

Descriptives

### What analysis are you seeing the problem on?

Descriptive Statistics

### What OS are you seeing the problem on?

Windows 10

### Bug Description

When calculating the confidence interval for the mean in descriptive statistics, the resulting interval is too small. The correct confidence interval is obtained if analyzing the variable as a one sample t-test (against a Test Value of 0). 

![JASP CI](https://github.com/jasp-stats/jasp-issues/assets/144724964/c8974bdc-9fcf-487e-b44e-4b9650cb9dbb)

[Exam 01 23-24 F trait procrastination.csv](https://github.com/jasp-stats/jasp-issues/files/12579198/Exam.01.23-24.F.trait.procrastination.csv)

### Expected Behaviour

With a sample mean of 2.72, standard error of 0.306, and df = 19, the 95% confidence interval for the variable procrastination should have been [2.08, 3.36]

### Steps to Reproduce

1. Open the file Exam 01 23-24 F trait procrastination.csv in JASP
2. Select Descriptive Statistics
3. Move procrastination to Variables
4. Select Confidence Interval for the Mean
...
[Exam 01 23-24 F trait procrastination.csv](https://github.com/jasp-stats/jasp-issues/files/12579210/Exam.01.23-24.F.trait.procrastination.csv)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by vandenman** [comment]
Hi, thanks for reporting this issue!

In descriptives, we generally do not assume statistical models for the data.

So the confidence interval for the mean is based on the assumption that the mean follows a normal distribution and then computes the interval via $\bar{x} \pm z_{95}\times SE$.

In contrast, the one-sample t-test assumes that the data are normally distributed. From there the confidence interval can be derived from a t-distribution (e.g., [see Wikipedia](https://en.wikipedia.org/wiki/Confidence_interval#Example)).

I hope that clarifies the difference between the analyses. To make this more clear, I can add the t-test as an option under `Method` and update the documentation (which is lacking for this option).

Would that resolve the issue for you?

**Comment by nctorbert** [comment]
Thank you, that is helpful to know!

It would be useful to have a t distribution option, and if that can be added, I would appreciate it.

More broadly though, I do not believe it is appropriate to assume a normal distribution when calculating a confidence interval from sample data. Generally, I would only have my students use z (unit normal) if they can assume a normal distribution, and the population standard deviation is known. Typically, we are estimating the underlying population standard deviation, so instead of using the standard error of the mean, we are using the estimated standard error of the mean (calculated using the sample standard deviation). In this case, using the t distribution would be more appopriate, to include uncertainty about the true population standard deviation (affecting our certainty about the width of the sampling distribution of the mean). And, professionally, that is my assumption when looking at published results (that researchers used t rather than z to estimate a population mean).

**Comment by vandenman** [comment]
> I do not believe it is appropriate to assume a normal distribution when calculating a confidence interval from sample data.

That is certainly sensible, and also why there is the bootstrap method for these statistics. The choice of the default method, however, I leave to @EJWagenmakers.

**Comment by EJWagenmakers** [comment]
In Descriptives, it kinda makes sense to use the bootstrap as the default; however, that takes time. So I vote the t-based CI becomes the new default (but should we call it this, or indicate that it comes from a normal with variance unknown?)

**Comment by nctorbert** [comment]
I like that idea, but am not sure what to call it - probably either t-based or normal with unknown variance would be appropriate? I wonder if identifying it as t-based (normal with unknown variance) would work.
