### ISSUE TITLE
[Bug]: After editing the existing file,  it cannot be archived regardless of whether "save" or "save as" is used.

### ISSUE THREAD

**Issue by akwan168** [jasp-stats/jasp-issues#2289]
### JASP Version

0.18.0

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

save file

### What OS are you seeing the problem on?

Windows 10

### Bug Description

1. When a JASP file is placed in a folder with a Chinese name, after opening the file and editing it, it cannot be archived regardless of whether "save" or "save as" is used.
2. When the JASP file is placed in a folder with an English name, after opening the file and editing it, using the "save" function, you cannot save it with the original file name, but you can use the "save as" function and save it with a new file name.
3. I have videotaped the operation process, please see the video below:
    https://youtu.be/f6_j8CMQ0ng

### Expected Behaviour

please see the video below:     https://youtu.be/f6_j8CMQ0ng

### Steps to Reproduce

1. the bug is reported in following video：    https://youtu.be/f6_j8CMQ0ng
2.
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by shun2wang** [comment]
Yeah I can reproduce this, in logs we can see:

```
00:00:57.254: Runtime Exception in saveTask: File could not be opened.

00:01:20.539: Runtime Exception in saveTask: File 'D:/Users/username/Downloads/test.jasp' or 'D:/Users/username/Downloads/test.jasp.tmp' is being used by another application.

```
and in target save folder we can see:
Garbled cache file name like:

`ä¸­æç¹æ®-å­ç¬¦çæµè¯.jasp.tmp`

**Comment by JorisGoosen** [comment]
Aah, I can reproduce this and also just saving a file with some chinese text as name doesnt seem to work either...

**Comment by JorisGoosen** [comment]
Aah, I can reproduce this and also just saving a file with some chinese text as name doesnt seem to work either...
