### ISSUE TITLE
In network analysis appears error whenever I want to tick something

### ISSUE THREAD

**Issue by MinaSte** [jasp-stats/jasp-issues#229]
I just started the network analysis and when I want to tick whatever, centrality plot, clustering plot, or something another it appear msg JASP experienced an unexpected internal error and it close.
* JASP version: 0.9.1.0

My laptop is DELL latitude 5490, windows 10
* Analysis: Network analysis 
<img width="960" alt="jasp" src="https://user-images.githubusercontent.com/44463778/47490562-44021700-d849-11e8-882b-b37fc6f3bc97.PNG">

**Comment by MinaSte** [comment]
I would love just to check if there is some news about solution? I installed version 0.8.6.0 but on some later steps and there it is occuring same mistake in network analysis

**Comment by AlexanderLyNL** [comment]
The fix will be incorporated in the next version 0.9.3
