### ISSUE TITLE
This analysis terminated unexpectedly

### ISSUE THREAD

**Issue by stataisr** [jasp-stats/jasp-issues#2290]
### JASP Version

0.18.0

### JASP Module

Quality Control

### What analysis are you seeing the problem on?

Process Capability Study

### What OS are you seeing the problem on?

Windows 10

### Bug Description

[Massa.zip](https://github.com/jasp-stats/jasp-issues/files/12588646/Massa.zip)

### Expected Behaviour

[Expected.zip](https://github.com/jasp-stats/jasp-issues/files/12588689/Expected.zip)

### Steps to Reproduce

1.
2.
3.
...
[Steps.zip](https://github.com/jasp-stats/jasp-issues/files/12588711/Steps.zip)

### Log (if any)

![image](https://github.com/jasp-stats/jasp-issues/assets/127410073/823529d7-9dc6-4658-b224-1c1c97281c0f)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JTPetter** [comment]
Thanks for your report @stataisr. This will be fixed in the next version.
