### ISSUE TITLE
[Bug]: ifElse broken in computed columns drag-and-drop

### ISSUE THREAD

**Issue by sophieberkhout** [jasp-stats/jasp-issues#2291]
### JASP Version

0.18.0

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 10

### Bug Description

 Cannot drag variable into the ifElse function, and typing also does not work. (was also mentioned in #1430)

<img width="911" alt="image" src="https://github.com/jasp-stats/jasp-issues/assets/49243293/6c534845-2a8c-4cc6-9ded-356e78902315">

<img width="910" alt="image" src="https://github.com/jasp-stats/jasp-issues/assets/49243293/58a19288-ad38-4de8-b5f4-cdd5af40f76b">

### Expected Behaviour

We should be able to enter a variable and type something, like Freshness < 0.2 or something.

### Steps to Reproduce

1. Add computed column
2. Drag ifElse function
3. Try to drag variable to ifElse
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
With the Drag-and-drop option, this is indeed a bit tricky: as ifElse expect a boolean as first parameter, you have first to set the '<' (or other operator that returns a boolean), then you can add the column and type a value.
![Screenshot 2023-09-15 at 11 18 52](https://github.com/jasp-stats/jasp-issues/assets/503332/cd183f84-b25e-410e-ac85-96c565fdb3a3)

But you can also use directly the R option and specify yourself the ifElse function:
<img width="731" alt="Screenshot 2023-09-15 at 11 15 37" src="https://github.com/jasp-stats/jasp-issues/assets/503332/a1f6e02e-d64a-4de1-864f-e9ef6ebd5065">

At least on my Mac it works fine.

**Comment by sophieberkhout** [comment]
Ah okay, this works! It makes sense now, but it is not very intuitive to me. The R option works fine, but we are trying to avoid that for teaching.
