### ISSUE TITLE
[Bug]: could not find function "dicrete_range"

### ISSUE THREAD

**Issue by mspeiger** [jasp-stats/jasp-issues#2293]
### JASP Version

0.18.0

### JASP Module

T-Tests

### What analysis are you seeing the problem on?

Bayesian Wilcoxon signed rank test

### What OS are you seeing the problem on?

Windows 10

### Bug Description

<img width="418" alt="JASP Fehlermeldung" src="https://github.com/jasp-stats/jasp-issues/assets/145142901/feaeb0fe-0ff7-4ab4-8594-fae3be70ef13">

I want to modify the y-axis range of a raincloud plot based on a one sample Wilcoxon signed rank test. Once I am changing the lower value the attached error message occurs. Starting the program new is not solving the problem. This problem occurs with different data sets for me. Which were first analyzed with the 0.16 version and then the program was updated and the old jasp files opened. 

Unfortunately I cannot share the data due to data protection regulations of our insitute. 

### Expected Behaviour

<img width="420" alt="JASP error explanation" src="https://github.com/jasp-stats/jasp-issues/assets/145142901/f8dc4014-9fc5-4387-b89b-c1fcb0f29c84">

The lower value of the y axis should have changed from -300 to -200.
<img width="273" alt="JASP error explanation 2" src="https://github.com/jasp-stats/jasp-issues/assets/145142901/85f4a5ea-307f-4221-a68c-62d742f7eb81">

### Steps to Reproduce

1. Create a raincloud plot based on a Wilcoxon signed rank test
2. Modify the graph
3. change the values of the y axis

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by vandenman** [comment]
Hi, thanks for reporting the issue!

I just tried to replicate this on 0.18.0 but failed, but I couldn't reproduce the error.
If you refresh the analysis, does the issue persist?

**Comment by tomtomme** [comment]
@mspeiger 
I also cannot replicate this. I tried classic and bayes versions and ordinal and metric data. I even introduced missings and renamed my var to MeanADs, but all fine.

Please reopen, if you can still replicate this - and maybe share mockup data that shows this. Thx!
