### ISSUE TITLE
[Bug]: Crash while editing data

### ISSUE THREAD

**Issue by NotJustPretty** [jasp-stats/jasp-issues#2297]
### JASP Version

0.18.0

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 10

### Bug Description

Hello Dev team, 
I love the "New Data" input feature! I experience three crashes on three days while changing the columns type or editing data. No data was saved. JASP just shut off.
Thanks for the fantastic software!
Gerald

### Expected Behaviour

Should have changed the column type or the data

### Steps to Reproduce

I am sorry. Until now, I cannot reproduce. But will watch closely.

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by shun2wang** [comment]
@NotJustPretty  Hi, can you refer here https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/user-guide/logging-howto.md to upload the logs with this crash? thanks.

**Comment by boutinb** [comment]
We will release a new version this week, that solves some crashes, maybe you can try the beta version of this release: https://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-stable-ff9da08514647d5dda4cc2219afaa5fe0e81771a.msi

**Comment by NotJustPretty** [comment]
I will do that and turn on the Logs

**Comment by NotJustPretty** [comment]
Sorry. Cannot install that release as my Computer tells me in German: "This installer could not be opened. Let the producer check, if this is a valid Windows install package." 
![image](https://github.com/jasp-stats/jasp-issues/assets/125731516/a7b86848-c330-456e-bd99-d90a907616db)

**Comment by boutinb** [comment]
This beta version is not signed, and probably your PC does not allow this. Tomorrow we should have a signed version, and you can try it.
