### ISSUE TITLE
[Bug]: JASP 0.18 INTEL MACOS Ventura 13.5.2 (22G91)

### ISSUE THREAD

**Issue by JohnPayson** [jasp-stats/jasp-issues#2298]
### JASP Version

0.18.0

### JASP Module

Quality Control

### What analysis are you seeing the problem on?

DOE 2x2 factoorial

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

DOE module will not generate design. Of course won't save a useful *.csv file.

### Expected Behaviour

When Display Design is checked it should show the design in the right hand window. Instead an incomplete table is shown.

### Steps to Reproduce

1.Open DOE factorial in quality module.
2. Set for 2x2
3. Name factors
4. Check mark on Display design.
Design is not displayed.
Comment- It is working on a Windows installation I have at work. 

...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JohnPayson** [comment]
Thank you for looking into this.

**Comment by JohnPayson** [comment]
I have looked into this more myself. How embarrassing. I had not selected a row in the design table. Sorry to waste anybody's time. I am appreciating learning the DOE factorial module.

**Comment by EJWagenmakers** [comment]
No worries! Thanks for looking more into this yourself.
