### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by LeiLeigoodfriend** [jasp-stats/jasp-issues#2299]
### JASP Version

0.18.0

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 10

### Bug Description

engine crash

### Expected Behaviour

Pop-up window suddenly appears

### Steps to Reproduce

1. Get started with JASP
2. Use it normally and wait
3. It happened
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by shun2wang** [comment]
@LeiLeigoodfriend Hi, can you refer here https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/user-guide/logging-howto.md to upload the logs with this crash? which analysis did you run?

**Comment by boutinb** [comment]
Hi @LeiLeigoodfriend We need also a reproduction path to be able to solve this issue.
