### ISSUE TITLE
[Bug]: JASP 0.18 cannot run repeated-measures ANOVA

### ISSUE THREAD

**Issue by RenzoLanfranco** [jasp-stats/jasp-issues#2300]
### JASP Version

0.18.0

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

(frequentist) Repeated-measures ANOVA

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

I loaded a standard csv file with data in wide format: 3 x 3 design. When I try to run a (frequentist) repeated-measures ANOVA, it crashes and shows the error message attached. It's not the first time I see a message like this. It seems that JASP 0.18 has problems calling the mvtnorm package (Apple Silicon version 0.17 works properly)

<img width="1392" alt="Screenshot 2023-09-23 at 22 18 28" src="https://github.com/jasp-stats/jasp-issues/assets/40778736/482d4c25-9da6-4456-9f3c-6da0b5994684">

### Expected Behaviour

It should work.

### Steps to Reproduce

1. Load data set, as usual
2. Run RM anova model, as usual
3. Results window shows error
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @RenzoLanfranco Apparently there is something wrong with the installer. I have just tried the last beta version of the 0.18.1 (we will release it this week probably), and the analysis works for me. Can you try it: https://static.jasp-stats.org/Nightlies/macOS-arm64/JASP-nightly-stable-ff9da08514647d5dda4cc2219afaa5fe0e81771a.dmg?
