### ISSUE TITLE
[Bug]: Label filter not being applied, even though registering as ticked 

### ISSUE THREAD

**Issue by fredcito** [jasp-stats/jasp-issues#2301]
### JASP Version

0.18.0

### JASP Module

Other

### What analysis are you seeing the problem on?

Filtering in spreadsheet view via label editor

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

When applying the filter to a label in spreadsheet view, an 'x' appears duly by a category, but is not excluded in the spreadsheet (not greyed out, and appearing in data).  The excluded level can also be included in a statistical model. 

<img width="439" alt="image" src="https://github.com/jasp-stats/jasp-issues/assets/5058239/26ee5760-5e9e-4e2c-b605-add1d3eb86f4">

### Expected Behaviour

Filter should have excluded rows (it has worked well before this update)

### Steps to Reproduce

1. Closed all JASP engines, reopened, applied filter, same behavior 

### Log (if any)

[JASP 2023-09-24 13_51_04 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/12708532/JASP.2023-09-24.13_51_04.Desktop.log)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JorisGoosen** [comment]
@fredcito could you also upload the engine logs?

Is the data/jasp file shareable with us?

**Comment by fredcito** [comment]
Hi Joris,

thanks for getting in touch (and also to the whole team for the amazing work!).

This is a really weird bug, was just going to update the post; the same file has now started to work as it should.  Unfortunately I did not increase the number of logs to keep, and the previous engine log has been deleted.

Can I keep track of this and see if it recurs?

On a rather different topic I've been talking with my colleague Henrik Singmann whose code is used for some of JASP, including the repeated measures ANOVA follow-up tests. He mentioned that the default was for a long time model = "univariate", but since version 1.0 (2021-07-02), the default is model = "multivariate" (but both  still supported). He suggested that the better default for JASP current version would be "multivariate" if possible.

In any case, thank you again for your help, and sorry to not even be able to send a relevant log or reproducible error!

best
Fred



################################################
Fred Dick

Professor of Auditory Cognitive Neuroscience,
Director, Birkbeck/UCL Centre for NeuroImaging (BUCNI)
Dept of Experimental Psychology,
University College London (UCL)

26 Bedford Way, WC1H 0AP, London, UK
Email: ***@***.***
Lab website: https://alphalab-london.com
################################################


On 25 Sep 2023 at 13:52 +0100, Joris Goosen ***@***.***>, wrote:

⚠ Caution: External sender


@fredcito<https://github.com/fredcito> could you also upload the engine logs?

Is the data/jasp file shareable with us?

**Comment by JohnnyDoorn** [comment]
@fredcito thanks for the suggestion, I agree that we should change this default option (the option was implemented by me after my last chat with Henrik, about exactly this). The reason we have left it so far is to make the follow-up test results match those of SPSS (and therewith, popular statistics text-books), but I feel that we have outgrown this and can do our own thing now if we feel it makes statistical/methodological sense.

**Comment by fredcito** [comment]
Hi all
thanks for this!  And yes, let's hope that the era of SPSS hegemony is at an end ....

best
Fred

################################################
Fred Dick

Professor of Auditory Cognitive Neuroscience,
Director, Birkbeck/UCL Centre for NeuroImaging (BUCNI)
Dept of Experimental Psychology,
University College London (UCL)

26 Bedford Way, WC1H 0AP, London, UK
Email: ***@***.***
Lab website: https://alphalab-london.com
################################################


On 26 Sep 2023 at 11:58 +0100, Johnny van Doorn ***@***.***>, wrote:

⚠ Caution: External sender


@fredcito<https://github.com/fredcito> thanks for the suggestion, I agree that we should change this default option (the option was implemented by me after my last chat with Henrik, about exactly this). The reason we have left it so far is to make the follow-up test results match those of SPSS (and therewith, popular statistics text-books), but I feel that we have outgrown this and can do our own thing now if we feel it makes statistical/methodological sense.
