### ISSUE TITLE
[Bug]: Chi-sqaure change with addtion of second model

### ISSUE THREAD

**Issue by jonathanbart** [jasp-stats/jasp-issues#2302]
### JASP Version

0.18.0

### JASP Module

SEM

### What analysis are you seeing the problem on?

Structural Equation Modelling

### What OS are you seeing the problem on?

Windows 10

### Bug Description

The bug occurs when estimating a measurement and then structural model. When estimating the second model (the structural model) in a second tab, the chi-squared value of the first model changes. This bug seems to only happen when using the Satorra-Bentler model test.

![image](https://github.com/jasp-stats/jasp-issues/assets/38770219/58007136-42f1-43ef-86de-149dc5f7a791)

![image](https://github.com/jasp-stats/jasp-issues/assets/38770219/1c1797eb-1b0f-409a-80b2-de3a06d7bc84)

### Expected Behaviour

I assume there should be no change in the initial model chi-square value. Unless my knowledge of SEM is lacking.

### Steps to Reproduce

Step of analysis:
1. Import attached data set
2. Change all variables to scale
3. Open Structual Equation Modelling module and change estimation option to:

- Error calculation: Robust
- Estimator: ML
- Model test: Satorra-Bentler

5. Estimate the following measurement model in Tab 1:

phy =~ phy1 + phy2
nut =~ nut1 + nut2
swb =~ swb1 + swb3 + swb4
ga =~ ga1 + ga2 + ga3

Note, the chi squared value for Model 1 is 68.307

6. In Tab 2 estimate the following structural model:

phy =~ phy1 + phy2
nut =~ nut1 + nut2
swb =~ swb1 + swb3 + swb4
ga =~ ga1 + ga2 + ga3
swb ~ phy + nut
ga ~ swb

Note, the chi-square for model 1 is now 68.269

[data.csv](https://github.com/jasp-stats/jasp-issues/files/12710817/data.csv)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment]
@jonathanbart thanks for creating the issue. There was a problem with the R-package  lavaan (which the SEM module is based on), because it uses always the standard chisq test statistic for the likelihood ratio difference test, even though you have specified to use the Satorra.Bentler test statistic.
