### ISSUE TITLE
[Bug]: Can not download graphs as pptx

### ISSUE THREAD

**Issue by Thaleia99** [jasp-stats/jasp-issues#2303]
### JASP Version

0.17.3

### JASP Module

Network

### What analysis are you seeing the problem on?

Network Analysis, when computing bootstrap options, and in descriptive statistics

### What OS are you seeing the problem on?

Windows 11

### Bug Description

When I try to download a graph as a pptx in order to edit it, a message shows up that says that the bootnet crashed, and when I look into my downloads and try to open said document it says error and that it doesn't exist. I've tried to download the graph as a pptx multiple times, but each time I experience the aforementioned problem. Do you maybe know why this is happening? Or do you know any other ways to edit a graph in JASP?

### Expected Behaviour

Normally, I should be able to download the graph as a pptx in order to edit it on PowerPoint.

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Can you try with the latest JASP version 0.18.0 (cf https://jasp-stats.org/download/) ?
