### ISSUE TITLE
Meta-Bug / Feature Request: split "scale" into "discrete metric" and "continuous metric"

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#231]
In JASP and SPSS you can choose between 3 levels of measurement: nominal, ordinal and a third. This third is known as interval/ratio (or metric), but I will just name it **the third** here, as this is not about a split of interval/ratio. 

I propose to split the third level of measurement into:
"discrete metric" and "continuous metric" or  as an alternative
"categorial scale" and "continuous scale"

My reasoning for the proposal is as follows.

When I start a first semester I teach my students that the practical need for the opposite terms "diskret / categorial" and "stetig / continuous" lies mostly within selecting a suitable plot, like shown here

![plots](https://user-images.githubusercontent.com/4428185/47705079-cca3fd00-dc25-11e8-95be-8a329d18b184.png) _(Bühner, M., & Ziegler, M. (2009). Statistik für Psychologen und Sozialwissenschaftler. Pearson Deutschland GmbH.)_

Field, A. (2018) page 185 also agrees here:
"SPSS needs to know, whether variables are categorical (nominal) or continuous (scale) when it creates the graphs", while he forgets ordinal, which is also mostly categorial/diskret. And he wrongly suggests that continuous == scale. On page 12 he explained it a bit better: continuous scales are diskret/categorial **or** continuous.

However JASP chooses and SPSS blocks plots by level of measurement instead of by diskret/categorial and continuous. While the level of measurement have only very indirectly to do with the best plot option. So this is a contradiction. It leads to huge confusion under my students, since they then start mixing the meaning and use case for levels of measurement and diskret/categorial vs. continuous. 
When they start asking "Why do the programs select/block the plot by level of measurement?" I try to reason, that most (if not all) nominal and ordinal are diskret/categorial. However continuous scales are diskret/categorial **or** continuous (Field, A. (2018) page 12).
Thus, my students infer that statistic programs are stupid. They then learn, that they can hack the programs by selecting another level of measurement, even if the level of measurement makes no sense for the given data and even if level of measurement is not the thing to talk about, when you think about the best plot to choose.

If you could implement my proposal I would have another selling point for JASP in front of my students and my colleagues. I could proudly say: Another thing that JASP does way better than SPSS :)
JASP would allow me do define the type of my data crystal clear and could thus offer a far superior auto-selection of plots.

Thx, Thomas

**Comment by tomtomme** [comment]
My take on this here was formulated way to complicated and my proposed solution was maybe over engineered. I will think of a more pragmatic way to solve this and close this for now. Part of the problem is also discussed here now: Allow frequency tables for scale data
#647

**Comment by JoKeyser** [comment]
Sorry to beat an "undead horse", but this issue is the closest I could find about my repeated confusion about the word use "scale" in JASP.

Where does the wording "scale" to denote the concept of "Interval scale" or "Ratio scale" come from?

I too find this utterly confusing and also hard/impossible to translate.

[Wikipedia's article on Level of measurement](https://en.wikipedia.org/wiki/Level_of_measurement) (claims to) follow Stevens' "nominal", "ordinal", "interval", and "ratio".

Similarly, Field (2024) on page 14 lists these:

> - Categorical (entities are divided into distinct categories):
>     - Binary variable: There are only two categories (e.g., dead or alive).
>     - Nominal variable: There are more than two categories (e.g., whether someone is an omnivore, vegetarian, vegan, or fruitarian).
>     - Ordinal variable: The same as a nominal variable but the categories have a logical order (e.g., whether people got a fail, a pass, a merit or a distinction in their exam).
> - Continuous (entities get a distinct score):
>     - Interval variable: Equal intervals on the variable represent equal differences in the property being measured (e.g., the difference between 6 and 8 is equivalent to the difference between 13 and 15).
>     - Ratio variable: The same as an interval variable, but the ratios of scores on the scale must also make sense (e.g., a score of 16 on an anxiety scale means that the person is, in reality, twice as anxious as someone scoring 8). For this to be true, the scale must have a meaningful zero point.

**Comment by tomtomme** [comment]
Good question. I have not idea why "scale" is used instead of metric or continuous, which seem far more specific and common in use; since every variable is measured on a "scale" and thus the term seems to generic to me. Maybe some english native person can hook us up with an explanation?

But I think we currently translate scale as "metrisch" everywhere, and that seems fine to me.

**Comment by JoKeyser** [comment]
@tomtomme I agree, our solution for German seems OK, still I think it would be worthwhile to simplify this in English, especially for beginners (as you indicated above), and also to make life easier for the rest of the translators.
Not sure if/when/how it should be re-addressed this with a wider group; maybe it's good to state the issue again as clearly as possible, without a specific solution? I think it's not really resolved, but probably it's also not the most urgent issue.

**Comment by tomtomme** [comment]
Yes, I recommend making this its own issue
