### ISSUE TITLE
It takes too long to be installed

### ISSUE THREAD

**Issue by mrrezaie** [jasp-stats/jasp-issues#2310]
### JASP Version

0.18.0

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 10

### Bug Description

It took ~45 min to finish installation. Is it normal? 

These two steps took too long:
Checking space requirement
Copying new files

### Expected Behaviour

I think it shouldn't take such long time.

### Steps to Reproduce

I just downloaded the latest version and installed it.

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by RensDofferhoff** [comment]
Sorry for the inconvenience.
We are actively working on a new installer and a windows store listing to provide a better experience in the future.
It takes around 10 minutes on a fast desktop machine. If you disk is quite full and/or the machine is less powerful it will take longer. 

I will update this issue when the new installer is out. 
That way we may compare the runtimes and hopefully it will be an order of magnitude better.

**Comment by mrrezaie** [comment]
Thanks for your response. The drive was not full, and I have core i5 CPU. I'm looking forward your enhancements. Thanks again.

**Comment by RensDofferhoff** [comment]
hmm strange it took so long in that case. How much RAM does your system have?

**Comment by mrrezaie** [comment]
I have 6 Gb RAM, I just tested installing a heavier software and it didn't take as long as JASP. One thing: I use another drive for installing the software, not C:/.

**Comment by shun2wang** [comment]
>One thing: I use another drive for installing the software, not C:/.

This may be the reason. I guess msi installer will extract and copy files to `C:/program files(x86)`  first and then copy this to another drive target paths.

**Comment by mrrezaie** [comment]
Really? Why?

When I choose another drive, the installer freezes for a several minuets and also, **checking space requirement** takes too long.

**Comment by RensDofferhoff** [comment]
We are now on the Windows Store:
https://apps.microsoft.com/detail/JASP/9P08CWG12JNL?launch=true%20&mode=mini

This install method should be significantly faster.
We will soon provide the seem installer standalone aswell.

**Comment by mrrezaie** [comment]
Thank you so much, I also found your portable version (the zip file) which didn't require installation. Best regards, -Mohammadreza
