### ISSUE TITLE
[Bug]: gfortran files missing in Mac OS (Intel) package

### ISSUE THREAD

**Issue by Gambraw** [jasp-stats/jasp-issues#2312]
### JASP Version

0.18.0

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

ANOVA

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

I updated JASP to version 0.18.1 on my MacBook running Venture 13.5.2 today. I had been running JASP version 0.17.
On any JASP file, including the example files, I get an error message when I try to run an ANOVA. It occurs as soon as I identify the required dependent variable and fixed factor.

<img width="1254" alt="Screenshot 2023-09-29 at 4 54 58 PM" src="https://github.com/jasp-stats/jasp-issues/assets/146487915/483e63e0-776b-44d7-9acf-b5cf424bd937">

The error seems to be caused by missing gfortran resources. I looked at the installed JASP package and the referenced gfortran folder is missing from the referenced location.

<img width="905" alt="Screenshot 2023-09-29 at 4 59 14 PM" src="https://github.com/jasp-stats/jasp-issues/assets/146487915/03ece445-e9ce-4134-a0ed-dec571397db9">

### Expected Behaviour

The ANOVA calculations should have been performed using the referenced resources and results displayed.

### Steps to Reproduce

I have reproduced this bug using my own data files as well as the ANOVA example files included in JASP.
I checked the downloaded .dmg package and the gfortran folder is missing from there, as well.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JohnnyDoorn** [comment]
Hi @Gambraw ,

I tagged one of the main developers here, hopefully he can help. In the meantime, have you tried it with the latest version of JASP (0.18.1)? 

Kind regards
Johnny

**Comment by Gambraw** [comment]
Hi Johnny,
Thanks for checking on this. I did have this issue with version 0.18.1, I must have mis-tagged it when opening this issue. I'm going to try 0.18.0 and see how that works for me.

**Comment by JohnnyDoorn** [comment]
Ah in that case there is a bug! Hopefully @boutinb, @JorisGoosen, or @RensDofferhoff have an idea of what might be up.

**Comment by Gambraw** [comment]
I didn't find a link to download version 0.18.0, so I tried 0.17.3.
In 0.17.3, the ANOVA module works as expected with the same data sets.

**Comment by JorisGoosen** [comment]
@Gambraw could you try this nightly: https://static.jasp-stats.org/Nightlies/macOS-arm64/JASP-nightly-stable-ea61bc8c96c7bcc3013d325a84444efcf47ce484.dmg

It is an experimental testversion but it should work now thanks to @RensDofferhoff

**Comment by Gambraw** [comment]
@JorisGoosen, I tried the nightly version you linked and the ANOVA function is working with several data files I've been working with.
Thank you!

**Comment by RensDofferhoff** [comment]
@Gambraw Its now in the release as well!
So this should be resolved now
