### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by nurnai** [jasp-stats/jasp-issues#2314]
### JASP Version

0.17.3

### JASP Module

Descriptives

### What analysis are you seeing the problem on?

when clicking descriptives after using z score plug in

### What OS are you seeing the problem on?

Windows 10

### Bug Description

When I click on descriptives it will crash and not let me proceed.

### Expected Behaviour

Descriptives should open up for my data

### Steps to Reproduce

1.
2.
3.
...

### Log (if any)

![Screenshot (1)](https://github.com/jasp-stats/jasp-issues/assets/146698215/cbc0f70a-d87e-4607-9bfd-16812a719f0a)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @boutinb We have a new release 0.18.1, maybe you can try it? And if the error is still in this version, can you set a detailed reproduction path ?
