### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by SK3186** [jasp-stats/jasp-issues#2315]
### JASP Version

0.18.0

### JASP Module

SEM

### What analysis are you seeing the problem on?

Path Diagram

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

This analysis terminated unexpectedly.

Error in dyn.load(file, DLLpath = DLLpath, ...): unable to load shared object '/Applications/JASP.app/Contents/Frameworks/R.framework/Versions/4.2/Resources/library/Matrix/libs/Matrix.so':
  dlopen(/Applications/JASP.app/Contents/Frameworks/R.framework/Versions/4.2/Resources/library/Matrix/libs/Matrix.so, 0x0006): Library not loaded: '@executable_path/../Frameworks/R.framework/Versions/4.2/Resources/opt/local/gfortran/lib/libgfortran.dylib'
  Referenced from: '/Applications/JASP.app/Contents/Frameworks/R.framework/Versions/4.2/Resources/library/Matrix/libs/Matrix.so'
  Reason: tried: '/Applications/JASP.app/Contents/MacOS/../Frameworks/R.framework/Versions/4.2/Resources/opt/local/gfortran/lib/libgfortran.dylib' (no such file), '/usr/lib/libgfortran.dylib' (no such file)

### Expected Behaviour

A path diagram should be generated

### Steps to Reproduce

1.
2.
3.
...
[assessment_3_dataset_1.csv](https://github.com/jasp-stats/jasp-issues/files/12780541/assessment_3_dataset_1.csv)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment]
Hi @SK3186, thanks for creating the issue. I cannot really reproduce this. This does not seem to be a problem with the package but with some underlying executables. Maybe @JorisGoosen can help?

**Comment by RensDofferhoff** [comment]
Our apologies we will hopefully have this resolved by the end of today.

**Comment by RensDofferhoff** [comment]
If you download and install JASP again the issue should be resolved.
