### ISSUE TITLE
[Bug]: Repeated Measures ANOVA

### ISSUE THREAD

**Issue by mlapcn** [jasp-stats/jasp-issues#2317]
### JASP Version

0.18.0

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

Repeated Measures ANOVA

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

The analysis of a Repeated Measures ANOVA do not run. I tried with two different datasets and it doesn't work, occurring the same error (with another computer with the previous version of JASP it works perfectly). The analysis terminated unexpectadilly with the following message:

This analysis terminated unexpectedly.

Error in dyn.load(file, DLLpath = DLLpath, ...): unable to load shared object '/Applications/JASP.app/Contents/Frameworks/R.framework/Versions/4.2/Resources/library/Matrix/libs/Matrix.so':
  dlopen(/Applications/JASP.app/Contents/Frameworks/R.framework/Versions/4.2/Resources/library/Matrix/libs/Matrix.so, 0x0006): Library not loaded: '@executable_path/../Frameworks/R.framework/Versions/4.2/Resources/opt/local/gfortran/lib/libgfortran.dylib'
  Referenced from: '/Applications/JASP.app/Contents/Frameworks/R.framework/Versions/4.2/Resources/library/Matrix/libs/Matrix.so'
  Reason: tried: '/Applications/JASP.app/Contents/MacOS/../Frameworks/R.framework/Versions/4.2/Resources/opt/local/gfortran/lib/libgfortran.dylib' (no such file), '/usr/lib/libgfortran.dylib' (no such file)

Stack trace
.rmAnovaComputeResults(longData, options)

loadNamespace(x)

namespaceImportFrom(ns, loadNamespace(j <- i[[1]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]), i[[2]], from = package)

asNamespace(ns)

loadNamespace(j <- i[[1]], c(lib.loc, .libPaths()), versionCheck = vI[[j]])

namespaceImportFrom(ns, loadNamespace(j <- i[[1]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]), i[[2]], from = package)

asNamespace(ns)

loadNamespace(j <- i[[1]], c(lib.loc, .libPaths()), versionCheck = vI[[j]])

library.dynam(lib, package, package.lib)

dyn.load(file, DLLpath = DLLpath, ...)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

### Expected Behaviour

Run the analysis

### Steps to Reproduce

1. Open Repeated Measures analysis
2. Renamed the factor and defined the levels
3. Inserted the variables into de RM cells
4. ERROR
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JohnnyDoorn** [comment]
Hi @mlapcn,

I tagged one of the main developers here, hopefully he can help. In the meantime, have you tried it with the latest version of JASP (0.18.1)? 

Kind regards
Johnny

**Comment by mlapcn** [comment]
Yes, for RM it is fixed I think! Everything looks fine now. Thanks!
