### ISSUE TITLE
Non-unicode letters in csv file 

### ISSUE THREAD

**Issue by lindeloev** [jasp-stats/jasp-issues#232]
* JASP version: 0.9.1
* OS name and version: Windows 10, 64 bit
* Analysis: Loading data
* Steps to reproduce: Load the attached datasets

JASP replace non-ascii characters with "." or "?" when loading a csv file saved by Excel. I would expect JASP to load the data exactly as it is in the file. Luckily, JASP loads all characters from a csv file if it is saved by another editor (I used Notepad++). I suspect that this has something to do with the meta-data in the csv file?

I attach two datasets to demonstrate this. Try inspecting them raw and then see how JASP loads them. This is a bug report that there is a discrepancy for the "dansk ÆØÅ æøå Excel.csv" file.

BTW: when loading the "notepad" dataset in Excel, it completely messes it up, so at least JASP does better :-)

[non-ascii data.zip](https://github.com/jasp-stats/jasp-desktop/files/2534034/non-ascii.data.zip)

**Comment by lindeloev** [comment]
Hi @FransMeerhoff,

As you can see from my previous reply, **utf8commasep.csv** works just fine in JASP, Excel, and Notepad++. It's **msdoscommasep.csv** that reads incorrectly into JASP but OK into Excel (OK meaning that Excel shows the same characters as Notepad++. I converted from semi-colon to comma-delemited to import it into Excel)

Yes, **dansk æøå ÆØÅ from Excel.csv** reads correctly into Excel (shows the same as in Notepad++). Here is a screenshot from Excel:
![image](https://user-images.githubusercontent.com/1439417/48517522-de60e380-e866-11e8-8482-288eeaed9db0.png)

**Comment by boutinb** [comment]
@lindeloev I had a look again to this problem. The thing is that JASP is able to read Unicode (UTF-8, UTF-16 and UTF-32) encoded files, but Excel may save file with ISO encoding (ISO-9959-1) or typical Windows encoding. These encodings does not set a BOM (Byte Order Mark), and this makes quite difficult to guess which encoding was used.
I will look further, but the workaround is to save the file from Excel always with UTF-8 encoding

**Comment by JorisGoosen** [comment]
> @lindeloev I had a look again to this problem. The thing is that JASP is able to read Unicode (UTF-8, UTF-16 and UTF-32) encoded files, but Excel may save file with ISO encoding (ISO-9959-1) or typical Windows encoding. These encodings does not set a BOM (Byte Order Mark), and this makes quite difficult to guess which encoding was used.
> I will look further, but the workaround is to save the file from Excel always with UTF-8 encoding

The solution I made for this is:
On windows when a csv file lacks a BOM it assumes it is "natively encoded" which basically means: in the current locale.
This can of course go wrong, but in that case the only way around it is by using utf-8.

If however an utf-8 csv file is made without a BOM (with some other program or on linux/mac) then this heuristic goes wrong, which is why Ive added an option to disable that.
