### ISSUE TITLE
[Bug]: .jasp files saved in v 0.18.1.0 do not open in v 0.17.3.0

### ISSUE THREAD

**Issue by PeterKlaren** [jasp-stats/jasp-issues#2320]
### JASP Version

0.17.3

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

Loading a .jasp file

### What OS are you seeing the problem on?

Windows 10

### Bug Description

Is JASP backwards compatible?

Saved an analysis (multinomial test in the Frequencies module) as a .jasp file, tranferred it on a usb-stick to a laptop with v 0.17.3.0 installed, but the file wouldn't open.

### Expected Behaviour

Flawless import of a 0.18.1.0 .jasp file (see attachment) in v. 0.17.3.0.

[Exercise 12_7_3.zip](https://github.com/jasp-stats/jasp-issues/files/12783037/Exercise.12_7_3.zip)

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by RensDofferhoff** [comment]
> Is JASP backwards compatible?
We made breaking changes to allow for data editing.
0.17.3 JASP files will open on 0.18.x but not the other way around.

**Comment by PeterKlaren** [comment]
Clear! And thanks for inline editing. It saves A LOT of work in an international class with students running spreadsheet with different local settings.

**Comment by RensDofferhoff** [comment]
Great to hear that the new features are being used!

**Comment by PeterKlaren** [comment]
Hi Rens,

Just noted this morning that I can copy a data column from Excel to JASP's data editor, but when I try to copy a block of cells (multiple columns), JASP closes unannounced.

Peter

**Comment by RensDofferhoff** [comment]
Hi! 

I can reproduce this! Thanks for the catch.
I will make a new issue after diner and cite you in it so you can follow the progress.

- Rens

**Comment by RensDofferhoff** [comment]
Hi @PeterKlaren. The newest development nightly should have resolved this issue:
https://static.jasp-stats.org/Nightlies/
