### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by bchamb92** [jasp-stats/jasp-issues#2328]
### JASP Version

0.18.0

### JASP Module

SEM

### What analysis are you seeing the problem on?

Latent Variable Structural Equation Modelling 

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

This analysis terminated unexpectedly.

Error in dyn.load(file, DLLpath = DLLpath, ...): unable to load shared object '/Volumes/JASP-0.18.1.0-macOS-x86_64/JASP.app/Contents/Frameworks/R.framework/Versions/4.2/Resources/library/Matrix/libs/Matrix.so':
  dlopen(/Volumes/JASP-0.18.1.0-macOS-x86_64/JASP.app/Contents/Frameworks/R.framework/Versions/4.2/Resources/library/Matrix/libs/Matrix.so, 0x0006): Library not loaded: @executable_path/../Frameworks/R.framework/Versions/4.2/Resources/opt/local/gfortran/lib/libgfortran.dylib
  Referenced from: <1511B69B-6F80-3271-978B-CCD9719708A8> /Volumes/JASP-0.18.1.0-macOS-x86_64/JASP.app/Contents/Frameworks/R.framework/Versions/4.2/Resources/library/Matrix/libs/Matrix.so
  Reason: tried: '/Volumes/JASP-0.18.1.0-macOS-x86_64/JASP.app/Contents/Frameworks/R.framework/Versions/4.2/Resources/opt/local/gfortran/lib/libgfortran.dylib' (no such file), '/usr/lib/libgfortran.dylib' (no such file, not in dyld cache)

Stack trace

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

### Expected Behaviour

I as running the first step of SEM, it should have showed me other fit measures, Mardia's coefficient, parameter estimates, factor/residual variances + covariances etc. but instead I received this bug error.

### Steps to Reproduce

1. Load data set
2. SEM -> Structural Equation Modelling
3. Type code, eg. SES =~ SES1 + SES2 + SES3
Health =~ Health1 + Health2
Academic =~ Academic1 + Academic2
Stress =~ Stress1 + Stress2 + Stress3 + Stress4
4. Tick following boxes: Raw
Output options -> Additional fit measures, Mardia's coefficient, standardised estimates, path diagram, modification indices, hide low indices
5. RUN
<img width="1680" alt="Screenshot 2023-10-06 at 12 35 51 pm" src="https://github.com/jasp-stats/jasp-issues/assets/147117029/d8ae1e41-ad1d-407c-ac1f-162a1191739c">

...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [x] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by bchamb92** [comment]
> @bchamb92, thanks for taking the time to create this issue. If possible (and applicable), please upload to the issue website (#2328) a screenshot showcasing the problem, and/or a compressed (zipped) .jasp file or the data file that causes the issue. If you would prefer not to make your data publicly available, you can send your file(s) directly to us, [issues@jasp-stats.org](mailto:issues@jasp-stats.org)

[JASP_ERROR.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/12826142/JASP_ERROR.jasp.zip)

**Comment by juliuspfadt** [comment]
Hi @bchamb92, thanks for creating the issue. this seems very much like a duplicate of https://github.com/jasp-stats/jasp-issues/issues/2315. Could you try downloading the latest version of JASP and try again?
