### ISSUE TITLE
[Bug]: RM-ANOVA not workgin 

### ISSUE THREAD

**Issue by areeq1** [jasp-stats/jasp-issues#2330]
### JASP Version

0.18.0

### JASP Module

ANOVA

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

When three waves are inserted an error message appears
![Screenshot 2023-10-06 at 9 13 56 pm](https://github.com/jasp-stats/jasp-issues/assets/68887104/b176eabb-e76b-4031-b4b1-6625c59bfa48)

### Expected Behaviour

error message

### Steps to Reproduce

1. inserting three (or more) data points in RM-ANOVA

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @areeq1 did you try the last JASP version 0.18.1?

**Comment by areeq1** [comment]
Yes, same issue.

**Comment by boutinb** [comment]
Quite strange, I cannot reproduce this problem... Could you give a JASP file with this error? And you say that you use Apple silicon, but we had a similar problem with JASP for Apple Intel, which is solved with this link https://static.jasp-stats.org//JASP-0.18.1.0-macOS-x86_64_new.dmg

**Comment by areeq1** [comment]
It seems that it is working with the update. I had to re-run the analysis
to get the qnalysis work qith the new version. Sorry for confusion.

Regards
