### ISSUE TITLE
[Bug]: This analysis terminated unexpectedly.

### ISSUE THREAD

**Issue by PedroShiu** [jasp-stats/jasp-issues#2335]
### JASP Version

0.18.1

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

ANOVA Classic

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

When I try to perform an ANOVA classic analysis,
this happens.
Please help me with this. Thank you!
![Screen Shot 2023-10-11 at 1 22 35 AM](https://github.com/jasp-stats/jasp-issues/assets/147541073/538de667-058b-4d4d-aa9f-8d33c7126043)

### Expected Behaviour

An ANOVA analysis should have happened.

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by RensDofferhoff** [comment]
Have you perhaps accidentally downloaded the Intel version instead of the Apple Silicon version?

**Comment by boutinb** [comment]
If you have a Apple Intel, you should use this version: https://static.jasp-stats.org//JASP-0.18.1.0-macOS-x86_64_new.dmg (this has been updated on the website).

**Comment by PedroShiu** [comment]
> Have you perhaps accidentally downloaded the Intel version instead of the Apple Silicon version?

oh my.
Problem solved. I downloaded the Intel version when my Mac is using Silicon chips.
Thank you!!
