### ISSUE TITLE
[Bug]: "Label Editor" Tab needs more width for translations

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#2336]
### JASP Version

0.18.1

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

see screenshot

### What OS are you seeing the problem on?

Other

### Bug Description

see screenshot

### Expected Behaviour

more wide tab

### Steps to Reproduce

1. 
2.
3.
...

### Log (if any)

![Screenshot_20231011_083630](https://github.com/jasp-stats/jasp-issues/assets/4428185/b737325d-9051-4417-8408-18f512fa815a)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
This will be fixed for the next release.
