### ISSUE TITLE
[Bug]: Data library SEM file without .jasp file

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#2337]
### JASP Version

0.19 beta

### Bug Description

The data sets "social participation" and "grand point average" only come with a csv file in jasps data library

### Expected Behaviour

If I open those files with a click on the green button I expect, that a .jasp file with results and explanations is opened.

**Comment by JohnnyDoorn** [comment]
Great catch! I'll see if I can tag a knowledgeable SEM person in the JASP team.

**Comment by tomtomme** [comment]
still valid for 0.18.2 flatpak-beta from 30.11.23

**Comment by Kucharssim** [comment]
Afaik these data sets were originally added by @JMBKoch... I am not sure if he's involved anymore to add the examples? Perhaps we ought to delegate this to someone else. Perhaps we could just recreate the analyses in this blog post: https://jasp-stats.org/2022/02/22/latent-growth-curve-modeling-lgcm-in-jasp/

**Comment by tomtomme** [comment]
Now in progress here https://github.com/jasp-stats/jasp-desktop/pull/5456

**Comment by juliuspfadt** [comment]
ah very good!!! I completely forgot about this issue.
