### ISSUE TITLE
[Bug]: Second order factor in CFA

### ISSUE THREAD

**Issue by Vanja1105** [jasp-stats/jasp-issues#2340]
### JASP Version

0.17.2.1

### JASP Module

Factor

### What analysis are you seeing the problem on?

Confirmatory Factor Analysis

### What OS are you seeing the problem on?

Windows 11

### Bug Description

When comparing models within Confirmatory Factor Analysis, the model with and without a second-order factor shows identical results.
![slika](https://github.com/jasp-stats/jasp-issues/assets/147800846/93b3fc34-cea0-492d-8ea1-5545cb567f21)
![slika](https://github.com/jasp-stats/jasp-issues/assets/147800846/a7428f30-a9c3-4383-9b8b-eb34bba218f3)
![slika](https://github.com/jasp-stats/jasp-issues/assets/147800846/f5f415eb-2cfb-4688-8db3-e97caffc149a)

### Expected Behaviour

The chi-squared value, degrees of freedom, and fit indices should change; in other words, they should not be identical to the initial model.

### Steps to Reproduce

[ESCQ_13_Kina.zip](https://github.com/jasp-stats/jasp-issues/files/12890454/ESCQ_13_Kina.zip)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment]
Hi @Vanja1105, thanks for reporting. This is indeed not a bug, but a special case. When you have three factors with intercorrelations, the fit is exactly the same as if you had a second-order factor and no intercorrelations. This is because the g-factor loadings in the second-order model are completely determined from the intercorrelations in the basic model. BUT, that is only for three factors. If you increase the number of factors the relationship is not deterministic anymore and you will see the fit results change depending if you add a second-order factor or not.

**Comment by VinceHUG** [comment]
Many thanks to Julius because I was running crazy about this issue of 2nd and 1st order CFA having same fit indices AIC etc. in the special case of 3 factors.
Next Question then is : in this case, how to know which model is the best ?

**Comment by juliuspfadt** [comment]
You mean correlated factor model or second order model? You need your theory to tell you that! Statistically they are equivalent.

**Comment by VinceHUG** [comment]
Hi Julius, your comment that in case of 3 factors, 1st order and 2nd order CFA are statistically equivalent is most valuable in my research. I would like to cite you in an article on the development of a pychometric scale. Do you have a publication that I could add to my bibliography ?

**Comment by juliuspfadt** [comment]
So when your theory suggests a hierarchical model, go for it. They will fit the same. I dont have a publication that tells you exactly this. I think you dont need a citation for this, cause it can be mathematically shown.
