### ISSUE TITLE
[Bug]: Drag & Drop is not visible when computing a new variable

### ISSUE THREAD

**Issue by berenike02** [jasp-stats/jasp-issues#2343]
### JASP Version

0.18.1

### JASP Module

Other

### What analysis are you seeing the problem on?

Computing a new variable

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

![image](https://github.com/jasp-stats/jasp-issues/assets/147979177/16e71f2d-9c17-4a1c-817a-313cfab19d36)
![image](https://github.com/jasp-stats/jasp-issues/assets/147979177/f72cc04f-91f6-4367-9db8-008b1beb3258)
My problem is that, even though I am in the "Drag&Drop" option, there is no option for me to drag the variables from the left into the field for calculating.
The scale measurement of the old and the new variable are the same.
Zooming out didn't work either.

### Expected Behaviour

I should be able to compute a new variable by dragging the old variables to the field for calculation on the right. Then it should be possible to use any calculation for creating the new variable (variable 1 + variable 2 = new variable 3)

### Steps to Reproduce

1. Clicking on "Add computed column."
2. typing in the new variable's name and its measurement level - select the "hand" option (should be selected by default). ➝ "Create Column".
3. Calculate your new variable
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by mlapcn** [comment]
It happens the same with me, also with 18.1 and OS:macOS Intel. When you resolve the problem please also inform me. Thanks!

**Comment by boutinb** [comment]
Hi @mlapcn, @berenike02  & @charlotttt , could you try this version: https://static.jasp-stats.org/JASP-0.18.1.0-macOS-x86_64_new2.dmg ?

**Comment by berenike02** [comment]
> Hi @mlapcn, @berenike02 & @charlotttt , could you try this version: https://static.jasp-stats.org/JASP-0.18.1.0-macOS-x86_64_new2.dmg ?

Thank you very much!!! It works with the version from your hyperlink. :)

**Comment by boutinb** [comment]
Nice I will change the link in our download page.
