### ISSUE TITLE
[Bug] filter still active after reopen new session

### ISSUE THREAD

**Issue by PeterKlaren** [jasp-stats/jasp-issues#2344]
### JASP Version

0.18.1

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

Filtering data

### What OS are you seeing the problem on?

Windows 11

### Bug Description

In a csv data set >600 observations from 21 different student teams, I filter out team 18. Then close JASP to do some external editing on the data. Reopening the cleaned and dataset in a fresh JASP instance, the filter still is active, with no way to clear it?!

### Expected Behaviour

Filters should have been cleared upon reopening a data set.

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by PeterKlaren** [comment]
The screenshot show file handSpanBodyHeight2023_validated.csv, first imported in JASP, then two filters applied "team != 20" and "sex != N/A". Then closed, then opened again to see that the filters are still active with the filter field empty. Double clicking the dustbin is not effective.

BTW: I attempted this because JASP doesn't display a customizable scatter plot per team when N/A is present?

[handSpanBodyHeight2023_validated.csv](https://github.com/jasp-stats/jasp-issues/files/12915956/handSpanBodyHeight2023_validated.csv)

![image](https://github.com/jasp-stats/jasp-issues/assets/43278770/e3331976-273c-4b37-9d39-b596d52e93a4)

**Comment by boutinb** [comment]
Hi @PeterKlaren This will be fixed in the next release. The only workarounds I see now is either to start a new JASP session, or to set a dummy filter.

**Comment by JorisGoosen** [comment]
@PeterKlaren maybe give the N/A ones a label NA?
