### ISSUE TITLE
[Bug]: Cannot download on Mac

### ISSUE THREAD

**Issue by summerconkling** [jasp-stats/jasp-issues#2345]
### JASP Version

0.18.1

### JASP Module

Other

### What analysis are you seeing the problem on?

When downloading on Mac. Mac Big Sur version. Keeps crashing cannot open the application.

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

When downloading on Mac. Mac Big Sur version. Keeps crashing cannot open the application.

### Expected Behaviour

Should be able to download and open app to use.

### Steps to Reproduce

1.none
2.none
3.none
...
<img width="997" alt="Screen Shot 2023-10-16 at 5 31 25 PM" src="https://github.com/jasp-stats/jasp-issues/assets/148162805/75fe619b-0d96-4e78-9f19-8647b55db66c">

### Log (if any)

none

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @summerconkling Did you really download the right Mac Intel version: https://static.jasp-stats.org//JASP-0.18.1.0-macOS-x86_64_new.dmg ?
