### ISSUE TITLE
[Bug]: JASP does not open

### ISSUE THREAD

**Issue by AnguloB** [jasp-stats/jasp-issues#2347]
### JASP Version

0.18.1

### JASP Module

Unrelated

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

After installing JASP the software crashes unexpectedly and the application does not open. 

We have installed different JASP versions (earlier versions) and it happens to all of them. We have also updated the ios and keep having the same problem. 

Please find attached the report of the problem. This happened in a Macbook Retina (Early 2015), macOs Big Sur, Memory 8GB, 1.1Ghz Inter core. 

[crash.docx](https://github.com/jasp-stats/jasp-issues/files/12999298/crash.docx)

### Expected Behaviour

Open JASP

### Steps to Reproduce

1. Open the program

### Log (if any)

We can't access to the log, but we have provided JASP report. 

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @AnguloB Are you sure that you have installed the right JASP Version for Mac Intel (not the version for Mac Silicon)? The right one is this one: https://static.jasp-stats.org//JASP-0.18.1.0-macOS-x86_64_new.dmg

**Comment by AnguloB** [comment]
Thank you for the quick reply. 

For the name of the file it seems the same that we have installed it: 

JASP-0.18.1.0-macOS-×86_64_new.dmg

<img width="400" alt="Screenshot 2023-10-18 at 11 27 23 AM" src="https://github.com/jasp-stats/jasp-issues/assets/8128625/7706d53b-dbfb-4fd8-9538-35591517faad">

**Comment by boutinb** [comment]
Quite strange...
Could you start JASP form a terminal with the safeGraphics option in this way:
`/Applications/JASP.app/Contents/MacOS/JASP --safeGraphics`
If it still crashes, can you give me the output on the terminal?

**Comment by AnguloB** [comment]
It still crashes.. 
<img width="625" alt="Screenshot 2023-10-19 at 8 34 26 AM" src="https://github.com/jasp-stats/jasp-issues/assets/8128625/d188c874-4711-45ab-8917-7bc62af09947">

**Comment by boutinb** [comment]
Sorry, I forgot your issue... Do you have still this issue, even with the last version https://static.jasp-stats.org/JASP-0.18.2.0-macOS-x86_64.dmg ?
Also if it crashes, it should ask if you want to have a report. Could you send us this report?

**Comment by tomtomme** [comment]
@AnguloB 
Please reopen, if you can re-test with newer jasp including a new report. Thx!!
