### ISSUE TITLE
JASP crashes when trying to open file

### ISSUE THREAD

**Issue by hhoermann** [jasp-stats/jasp-issues#2348]
### JASP Version

0.18.1

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I am trying to open an existing jasp file. This file is about 6 months old and contains already 4 or 5 analyses. The number of data rows is about 5000. The process to open stops after about 10 sec and after another 50 sec the engine reports it has crashed. I can see the open file, but cannot further scroll through. It closes automatically.

### Expected Behaviour

The file should open w/o hesitation and should remain open so I can scroll through

### Steps to Reproduce

1. I simply click on that jasp file and wait for the engine to crash after 60 secs
2. I can also open JASP first and coose this file to open
3. I can open any other existing jasp file

### Log (if any)

[JASP 2023-10-18 12_48_24 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/13016665/JASP.2023-10-18.12_48_24.Desktop.log)

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by hhoermann** [comment]
![grafik](https://github.com/jasp-stats/jasp-issues/assets/120397096/824e4b86-9de9-4324-ad3b-d895983f515a)

**Comment by boutinb** [comment]
Hi @hhoermann Can you give this JASP file? (first change it into a zip file, and drag-and-drop it here)

**Comment by hhoermann** [comment]
I wished I could provide the data, but they are confidential. Do you have any idea for the reason of the crash? I guess it is unrelated to this specific data set. Earlier I had similar crash-issues when opening very large data sets.

**Comment by shun2wang** [comment]
Hi @hhoermann , How many columns and rows dose your dataset have. can you make a similar 'fake' dastaset for us? you can make fake value and variable names for example. it's hard to know what happend without a dataset, thanks.

**Comment by boutinb** [comment]
From the log you gave, the engines crash. Could you also give the logs of the engines?

**Comment by lkearns24** [comment]
Any resolution for this. I had the same problem after installing 18.1, I uninstalled it and re-installed 17.3 and still having the problem

**Comment by shun2wang** [comment]
@lkearns24 Could you also give the logs or jasp files? thanks
