### ISSUE TITLE
JASP wont open on Mac after download 

### ISSUE THREAD

**Issue by kbleuberry** [jasp-stats/jasp-issues#2349]
### JASP Version

0.18.1

### JASP Module

Other

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

I downloaded JASP on my MacbookPro (11.7.10, Intel) 
The application crashes as soon as I try to open it.

### Expected Behaviour

The program opens and starts up

### Steps to Reproduce

1. Download JASP for intel mac
2. Drag and drop into Applications 
3. Double click JASP to open 
...

### Log (if any)

<img width="962" alt="Screen Shot 2023-10-18 at 12 46 44 PM" src="https://github.com/jasp-stats/jasp-issues/assets/148390378/9fc437ac-26d1-4a94-9db5-30daab36feca">

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by shun2wang** [comment]
Hi @kbleuberry can you make sure that you have installed the right JASP Version for Mac Intel (not the version for Mac Silicon)? The right one is this one: https://static.jasp-stats.org//JASP-0.18.1.0-macOS-x86_64_new.dmg

@boutinb seems we should make sure inside JASP to avoid users installed wrong version on Mac Intel/Silicon. I had did that to avoid install JASP on arm/32bit Windows in the msi installer. samething could be done with JASP Mac Version?
