### ISSUE TITLE
[Feature Request]: ggplot2 for JASP

### ISSUE THREAD

**Issue by romanogino** [jasp-stats/jasp-issues#2350]
### Description

Add ggplot2 to JASP

### Purpose

Improve graphics

### Use-case

My JASP is 0.15.0 Windows 10

### Is your feature request related to a problem?

No, just to improve graphics and output

### Is your feature request related to a JASP module?

Descriptives

### Describe the solution you would like

An easy way to add ggplot2 to JASP, to improve graphics. Easy way for students that do not use JASP usually.

### Describe alternatives that you have considered

Some kind of push and pull to install ggplot2

### Additional context

My students do not want to use JASP because the output graphics do not have enough colors.

**Comment by tomtomme** [comment]
This might help in the meantime:

Most Jasp graphs can ne exported to .pptx and then edited in powerpoint. 

Also current Version 0.18.1 added more color schemes. 

And the visual modeling module flexplot offers some more visual styles.

Ggplot2 as an r package is already in jasp, but sure, the accessible GUI options could be improved in quantity.

**Comment by romanogino** [comment]
Thanks
The information is useful, good help.
r.

**Comment by boutinb** [comment]
Thanks @tomtomme

**Comment by tomtomme** [comment]
@romanogino 
feel free to close this issue, if the help was sufficient!

**Comment by romanogino** [comment]
Thanks for the information!! Issue closed.
