### ISSUE TITLE
[Bug]: Download sever static.jasp-stats.org downtime

### ISSUE THREAD

**Issue by ZehaEss** [jasp-stats/jasp-issues#2352]
### JASP Version

0.18.1

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 10

### Bug Description

After clicking on any download link from https://jasp-stats.org/download/ it redirects to a site with no https and claim the site wasn't found. 
After I took the screenshot of the site not found the behaviour changed slighty and it's now an err_connection_timed_out and it tries to connect repeatedly, then fails. I tried the older versions and they have the same issue. 
I checked with https://downforeveryoneorjustme.com and it seems static.jasp-stats.org is down. 
![Screenshot (66)](https://github.com/jasp-stats/jasp-issues/assets/76980907/097988b8-9342-42cc-b431-329b4ae1a8a6)
![image](https://github.com/jasp-stats/jasp-issues/assets/76980907/77b2ec91-4820-41ed-a226-603ec9e40304)

### Expected Behaviour

I suppose it should download a .msi or .zip file depending on the link.

### Steps to Reproduce

1. go to https://jasp-stats.org/download/
2. click on any link for windows or mac
3. 
4.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by shun2wang** [comment]
Ah, yes the website was shut down now, @boutinb or @JorisGoosen will fix that.

You can temporarily access GitHub release here to download https://github.com/jasp-stats/jasp-desktop/releases/tag/v0.18.1
