### ISSUE TITLE
[Feature Request]: Can't download JASP

### ISSUE THREAD

**Issue by reemsae** [jasp-stats/jasp-issues#2353]
### Description

JASP Download

### Is your feature request related to a problem?

Can't download JASP

**Comment by reemsae** [comment]
Still I can't download , show me steps if possible.

**Comment by shun2wang** [comment]
Sure😀 @reemsae 
1. open https://github.com/jasp-stats/jasp-desktop/releases/tag/v0.18.1
2. see the "Assets"
3. Choose the installation package that suits your system，for example if you are using windows, click [JASP-0.18.1.0-Windows-signed.msi](https://github.com/jasp-stats/jasp-desktop/releases/download/v0.18.1/JASP-0.18.1.0-Windows-signed.msi) to download it. macOS with Apple silicon should click [JASP-0.18.1.0-macOS-arm64.dmg](https://github.com/jasp-stats/jasp-desktop/releases/download/v0.18.1/JASP-0.18.1.0-macOS-arm64.dmg) , and the macOS Intel should click [JASP-0.18.1.0-macOS-x86_64_new.dmg](https://github.com/jasp-stats/jasp-desktop/releases/download/v0.18.1/JASP-0.18.1.0-macOS-x86_64_new.dmg).
