### ISSUE TITLE
jasp isn't working 

### ISSUE THREAD

**Issue by Duckydeb** [jasp-stats/jasp-issues#2354]
### JASP Version

0.17.3

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

repeated measures anova 

### What OS are you seeing the problem on?

Windows 10

### Bug Description

Jasp isn't moving or doing anything
says 'waiting for initialization' it's been 15 minutes. 
dissertation due Monday 
help please 

### Expected Behaviour

it should be analysing 

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [x] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by Duckydeb** [comment]
![jasp issue ](https://github.com/jasp-stats/jasp-issues/assets/148549247/bb775509-9673-43fc-9a5d-96bd4088753f)

**Comment by Duckydeb** [comment]
thanks

**Comment by tomtomme** [comment]
Have ypu tried the new version 0.18.1?

**Comment by tomtomme** [comment]
Also your file is on onedrive and has a very long name. Try saving localy with a short name

**Comment by tomtomme** [comment]
@Duckydeb 
could you resolve this?
If so, how?

**Comment by Duckydeb** [comment]
@tomtomme 

Thank you I got an extension on my dissertation. My supervisor helped to re code the
data and since then JASP has been fine.
Thank you
