### ISSUE TITLE
Results export error?

### ISSUE THREAD

**Issue by DrMarkGS** [jasp-stats/jasp-issues#236]
Using 0.9.1 I am trying to export results to an html file so that I can email them to a colleague.  Once exported and JASP closed  the file is name.html.tmp. I then remove the .tmp extension. When I try to open the file I get the following errors and possible fixes:

Make sure that you’ve got the right web address:  file://staff.gre-ad.gre.ac.uk/USR/MS/gm03/Documents/Baton%20strike%20force%20-%202%20ASPS.html                                     
Search for "file://staff.gre-ad.gre.ac.uk/USR/MS/gm03/Documents/Baton%20strike%20force%20-%202%20ASPS.html" on Bing                                    
 Refresh the page                                                                                                                                                Details
--

Any ideas?

**Comment by JorisGoosen** [comment]
This seems to be related then to your network-drive settings then, perhaps this also occurs with other software?
For instance, if you save a webpage from your browser to your networked drive, does it also get ".tmp" added to the end?

**Comment by JorisGoosen** [comment]
I am going to assume this was not a problem with JASP.
