### ISSUE TITLE
[Bug]: Mode now always calculated as "highest density estimate"

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#2360]
### JASP Version

0.18.1

### JASP Module

Descriptives

### What analysis are you seeing the problem on?

Mode

### What OS are you seeing the problem on?

Flatpak

### Bug Description

When calculating the Mode JASP notes:

"ᵃ More than one mode exists. For nominal and ordinal data, the first mode is reported. For continuous data, the mode with the highest density estimate is reported but multiple modes may exist. We recommend visualizing the data to check for multimodality."

Sadly changing the scale of the data from metric to nominal or ordinal does not change the result accordingly anymore.  JASP now always shows the "highest density estimate" and seems to ignore the chosen scale.

### Expected Behaviour

JASP should change the result of the Mode when the user changes the scale of the data

### Steps to Reproduce

1. open any dataset and calculate the mode
2. change the scale of the data 

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by m-guggenmos** [comment]
Hi all, I have just encountered a similar situation. Screenshot attached.
![Screenshot_20231114_084331](https://github.com/jasp-stats/jasp-issues/assets/459536/fa8715be-061f-4814-967b-98261a97f70f)
