### ISSUE TITLE
[Bug]: chi-squared continuity correction false?

### ISSUE THREAD

**Issue by PeterKlaren** [jasp-stats/jasp-issues#2361]
### JASP Version

0.18.1

### JASP Module

Frequencies

### What analysis are you seeing the problem on?

Contingency Tables

### What OS are you seeing the problem on?

Windows 11

### Bug Description

For a 2x2 table with some counts < 5, JASP correctly calculates chi-squared = 0.093 (p = 0.761), but with Yates' continuity correction an improbable chi-squared value 1.222e-30 (p = 1) is calculated.

![image](https://github.com/jasp-stats/jasp-issues/assets/43278770/632cb1d6-e191-4de6-a0b8-ef407bc6d2d5)
[bugChiSquared.zip](https://github.com/jasp-stats/jasp-issues/files/13114840/bugChiSquared.zip)

### Expected Behaviour

The correct chi-squared value with continuity correction should be: chi-squared = 0.117, p = 0.732.

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by EJWagenmakers** [comment]
Would be good to check; may depend on the R package used?!

**Comment by FBartos** [comment]
The results are the same as those obtained by R
```
> df <- data.frame(
+   "sex"    = c("male", "male", "female", "female"),
+   "weight" = c("heavy", "light", "heavy", "light"),
+   "count"  = c(6, 1, 8, 2)
+ )
> 
> dftab <- matrix(df$count, nrow = 2, ncol = 2, byrow = TRUE)
> dftab 
     [,1] [,2]
[1,]    6    1
[2,]    8    2
> 
> chisq.test(dftab, correct = FALSE)

	Pearson's Chi-squared test

data:  dftab
X-squared = 0.092517, df = 1, p-value = 0.761

Warning message:
In chisq.test(dftab, correct = FALSE) :
  Chi-squared approximation may be incorrect
> 
> chisq.test(dftab)

	Pearson's Chi-squared test with Yates' continuity correction

data:  dftab
X-squared = 1.2225e-30, df = 1, p-value = 1

Warning message:
In chisq.test(dftab) : Chi-squared approximation may be incorrect
```

Maybe the slightly confusing thing is that the correction corrects the test statistics to 0, but there might be some numerical imprecision in R? 
```
> all.equal(1.222e-30, 0)
[1] TRUE
```

Feel free to reopen with more questions.
