### ISSUE TITLE
[Bug]: Raincloud plot - specify the horizontal axis limits

### ISSUE THREAD

**Issue by chantelanuit** [jasp-stats/jasp-issues#2364]
### JASP Version

0.18.1

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

Raincloud plot

### What OS are you seeing the problem on?

Windows 11

### Bug Description

When using the Raincloud plot, sometimes the min and max values on the plot are not relevant. I understand that the density function might start and finish at values lower and higher that the min and max possible values on a variable. However, it is not relevant to display the min and max value of the density function on the plot. 

Example, with the min and max values that need to be set respectively at 0 and 100 (and not -50 and 150 as displayed by default on the plot): https://www.dropbox.com/scl/fi/nvk8amomybo2pxraizh7r/Raincloud_Axis.png?rlkey=cpnm0uvpsuzikcrb6jxunj72m&dl=0

I am trying to modify this behaviour with the R syntax, but cannot find the optional line to do it. I am also looking at the option in the syntax for changing the default colours in the plot. 

Here is the long syntax outputted with the "R" button in Jasp for the plot in the URL previously mentioned :

jaspAnova::Anova(
          data = NULL,
          version = "0.18.1",
          formula = DV ~ country,
          contrastCi = FALSE,
          contrastCiLevel = 0.95,
          contrasts = list(list(contrast = "none", variable = "country")),
          customContrasts = list(),
          descriptivePlotCiLevel = 0.95,
          descriptivePlotErrorBar = FALSE,
          descriptivePlotErrorBarType = "ci",
          descriptivePlotHorizontalAxis = "",
          descriptivePlotSeparateLines = "",
          descriptivePlotSeparatePlot = "",
          descriptives = FALSE,
          effectSizeEstimates = FALSE,
          effectSizeEtaSquared = TRUE,
          effectSizeOmegaSquared = FALSE,
          effectSizePartialEtaSquared = FALSE,
          homogeneityCorrectionBrown = FALSE,
          homogeneityCorrectionNone = TRUE,
          homogeneityCorrectionWelch = FALSE,
          homogeneityTests = FALSE,
          kruskalWallisFactors = list(),
          marginalMeanBootstrap = FALSE,
          marginalMeanBootstrapSamples = 1000,
          marginalMeanCiCorrection = "none",
          marginalMeanComparedToZero = FALSE,
          marginalMeanTerms = NULL,
          plotHeight = 420,
          plotHeightDescriptivesPlotLegend = 300,
          plotHeightDescriptivesPlotNoLegend = 300,
          plotHeightQQPlot = 300,
          plotWidth = 480,
          plotWidthDescriptivesPlotLegend = 430,
          plotWidthDescriptivesPlotNoLegend = 350,
          plotWidthQQPlot = 300,
          postHocCi = FALSE,
          postHocCiLevel = 0.95,
          postHocCorrectionBonferroni = FALSE,
          postHocCorrectionHolm = FALSE,
          postHocCorrectionScheffe = FALSE,
          postHocCorrectionSidak = FALSE,
          postHocCorrectionTukey = TRUE,
          postHocSignificanceFlag = FALSE,
          postHocTerms = NULL,
          postHocTypeDunn = FALSE,
          postHocTypeDunnet = FALSE,
          postHocTypeGames = FALSE,
          postHocTypeStandard = TRUE,
          postHocTypeStandardBootstrap = FALSE,
          postHocTypeStandardBootstrapSamples = 1000,
          postHocTypeStandardEffectSize = FALSE,
          qqPlot = FALSE,
          rainCloudHorizontalAxis = "country",
          rainCloudHorizontalDisplay = TRUE,
          rainCloudSeparatePlots = "",
          rainCloudYAxisLabel = "",
          restrictedAvailableCoefficients = FALSE,
          restrictedBootstrap = FALSE,
          restrictedBootstrapCiLevel = 0.95,
          restrictedBootstrapSamples = 1000,
          restrictedHeterogeneityCorrection = "none",
          restrictedInformedHypothesisTestForAllModels = FALSE,
          restrictedInterceptInclusion = FALSE,
          restrictedMarginalMeanForAllModels = FALSE,
          restrictedMarginalMeanTerms = NULL,
          restrictedModelComparison = "complement",
          restrictedModelComparisonCoefficients = FALSE,
          restrictedModelComparisonCoefficientsHighlight = TRUE,
          restrictedModelComparisonMatrix = FALSE,
          restrictedModelComparisonReference = "complement",
          restrictedModelComparisonWeights = TRUE,
          restrictedModelSummaryForAllModels = FALSE,
          restrictedModels = list(list(informedHypothesisTest = FALSE, marginalMean = FALSE, name = "Model 1", summary = FALSE, syntax = "")),
          simpleMainEffectFactor = "",
          simpleMainEffectModeratorFactorOne = "",
          simpleMainEffectModeratorFactorTwo = "",
          sumOfSquares = "type3",
          vovkSellke = FALSE,
          wlsWeights = "")

### Expected Behaviour

Having the options in the Jasp/R syntax to modify the X-axis min and max limit + colour in the raincloud plot.

### Steps to Reproduce

See attached image in the URL link of my message.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by chantelanuit** [comment]
The screenshot is already included as a link.

**Comment by EJWagenmakers** [comment]
If you click on the small triangle above the figure, you will see an option "edit image"; this then allows you to adjust the scales. I am closing this issue in the anticipation that this solves your problem.
