### ISSUE TITLE
[Bug]: Version 0.18.1.0 will not install. Windows Installer Package problem. 

### ISSUE THREAD

**Issue by 7techJim** [jasp-stats/jasp-issues#2365]
### JASP Version

0.18.1

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I am attempting to install this software using the msi installer from the downloads page. And I keep getting an error that states "There is a problem with this Windows Installer Package. A program run as a part of the setup did not finish as expected. Contact your support personnel or package vendor. I have tried getting a new installer, running system and driver updates, and rebooting the device and installing it with an admin profile and I keep getting the same error. 
![Screenshot_40](https://github.com/jasp-stats/jasp-issues/assets/148902070/d6e5734b-ed02-4e2f-9608-080cc136892f)

### Expected Behaviour

The program should have installed. 

### Steps to Reproduce

1. Download installer from website
2. Run the file to install
3. Installer will fail and rollback
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @7techJim hmm quite strange... I would try to restart your PC. If it still does not work, you can try to generate a log file by lauching the msi file from the command line (Cmd.exe) in this way (you have first to go to the folder where the msi file was downloaded: 
`msiexec /i "JASP-0.18.1.0-Windows.msi" /L*V "C:\log\msi.log"`
This will create the log file in C:\log\example.log, but of course you can choose another folder.

Already as a workaround, you can use also our ZIP file: https://static.jasp-stats.org/JASP-0.18.1.0-Windows.zip, and unzip it.
This will not really 'install' JASP, but just create a folder with all JASP files.
But of course, it would be better to know why the install (msi) file does not work on your PC.

**Comment by Mikeszk98** [comment]
11/6/2023, I too have a Windows 10 64bit computer and have tried multiple times trying to install JASP 0.18.1.0
Expect for downloading the zip file, I tried installing the msi file, restarting the computer and installing the msi file and pausing my security software and installing the msi file.  Nothing works.

**Comment by Mikeszk98** [comment]
OK, I downloaded the zip file.  It had 85 items.  Now what? 
Is there an install file?  What is it called?

**Comment by boutinb** [comment]
When you have unzipped the file in a folder, just start JASP from this folder (double-click JASP.exe).

**Comment by Mikeszk98** [comment]
Problem solved. Please close issue Mike Szymczuk Sent from my iPhoneOn Nov 8, 2023, at 4:07 AM, bruno boutin ***@***.***> wrote:﻿
When you have unzipped the file in a folder, just start JASP from this folder (double-click JASP.exe).
