### ISSUE TITLE
[Bug]: Can't save

### ISSUE THREAD

**Issue by FunkyLightning** [jasp-stats/jasp-issues#2366]
### JASP Version

0.18.1

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

All of them

### What OS are you seeing the problem on?

Windows 11

### Bug Description

Whenever I save I get an error message
![JASP error](https://github.com/jasp-stats/jasp-issues/assets/149006229/7752a68b-c4a3-43e0-a341-f510b607a820)

### Expected Behaviour

Letting me save

### Steps to Reproduce

1. Open a file
2. Try editing it
3. Attempt to save it

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
HI @FunkyLightning It looks like another (JASP) process is holding this file. Maybe a previous JASP process that was not closed in a right way. Could you restart your PC, and check whether this still happens.

**Comment by FunkyLightning** [comment]
I restarted it and got the same message whenever I tried to edit my file and save it. I had no other JASP process open. Should I just remake the file from scratch so I can add in my T-Tests to it? Should I record a video of what happened so it can be replicated?

**Comment by FunkyLightning** [comment]
I restarted it and got the same message whenever I tried to edit my file
and save it. I had no other JASP process open. Should I just remake the
file from scratch so I can add in my T-Tests to it? Should I record a video
of what happened so it can be replicated?

**Comment by boutinb** [comment]
This is quite strange... I have never seen this problem before. Does this problem occur with other JASP files? Could you for example just start JASP with a data file, add a simple descriptive analysis, save it as a JASP file, reload this JASP file, and see if you can make some changes and save it?

**Comment by FunkyLightning** [comment]
I just tried it with a new file called "Test" and I took a screenshot, I will send it via email but the same error happened.

**Comment by FunkyLightning** [comment]
I just tried it with a new file called "Test" and I took a screenshot, I will send it via email but the same error happened.

**Comment by boutinb** [comment]
You can add a screenshot here by dragging and dropping your file in this Github issue.

**Comment by boutinb** [comment]
I'm quite puzzled by this issue... Do you have a virus scanner? Are you able to stop it?

**Comment by FunkyLightning** [comment]
![NewScreenshot 2023-11-09 150919](https://github.com/jasp-stats/jasp-issues/assets/149006229/859454c4-18f3-48b7-bd6c-026418f7972e)
![NewScreenshot2 2023-11-09 151051](https://github.com/jasp-stats/jasp-issues/assets/149006229/f82b5434-68bd-46db-acef-76837c15e2a9)
I am puzzled as well. The software works fine but does not save. I am thinking of taking a video. I have no virus scanner on.

**Comment by FunkyLightning** [comment]
Meant to only send 1 screenshot, my apologies.

**Comment by shun2wang** [comment]
@FunkyLightning  If you look into the .tmp file path and refresh the exploer, what will happend? did you use 'save' or 'save as'?

**Comment by FunkyLightning** [comment]
@shun2wang I usually use save, I tried using save as (with the same file name) and it didn't work. 
![TempTestScreenshot 2023-11-10 114255](https://github.com/jasp-stats/jasp-issues/assets/149006229/2f75c756-7b69-45c5-89ea-ac01e69af2f5)
![TempTestScreenshot 2023-11-10 114159](https://github.com/jasp-stats/jasp-issues/assets/149006229/5d879e23-c14c-444e-8171-e5b521de72a3)

But then I tried saving it under a different file name (The file was named "Question1" and I hit save as then renamed it as "VQuestion1") and that worked. So I guess problem solved? It is interesting though...

**Comment by JorisGoosen** [comment]
Is one of these folders perhaps a dropbox/cloud-storage folder?

**Comment by JorisGoosen** [comment]
And the problem only kept occurring for this particular file?

**Comment by shun2wang** [comment]
This just looks like https://github.com/jasp-stats/jasp-issues/issues/2239#issuecomment-1685500605

**Comment by FunkyLightning** [comment]
@JorisGoosen It's not a dropbox/cloud-storage folder, and the error occurred on all my JASP files. However, since you guys discovered a work around via Save As instead of Save, I am satisfied and closing the thread. Thank you!
