### ISSUE TITLE
[Bug]: JASP has experienced an unexpected internal error: The engine crashed

### ISSUE THREAD

**Issue by MartinS071** [jasp-stats/jasp-issues#2367]
### JASP Version

0.18.1

### JASP Module

T-Tests

### What analysis are you seeing the problem on?

Paired Samples T-test

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I finished the Paired Samples T-test. Save the results in my Dropbox. Then, when I tried to open the jasp file, I got the message error:
JASP has experienced an unexpected internal error: The engine crashed 

![Capture_JASPcrashed](https://github.com/jasp-stats/jasp-issues/assets/17749210/d29e01af-5d9d-4558-8793-1494903a0ccf)
[allSymmetry_0p4mA_JASP_stat.zip](https://github.com/jasp-stats/jasp-issues/files/13182910/allSymmetry_0p4mA_JASP_stat.zip)

### Expected Behaviour

JASP won't open the file!

### Steps to Reproduce

1. File
2. Open
3. Recent files or Computer, I get the same error message.
...

### Log (if any)

[JASP 2023-10-26 16_59_51 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/13182897/JASP.2023-10-26.16_59_51.Desktop.log)
[JASP 2023-10-26 16_59_51 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/13182898/JASP.2023-10-26.16_59_51.Engine.0.log)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by MartinS071** [comment]
Thank you for sharing this wonderful statistical software!

Regards,

Martin

**Comment by lkearns24** [comment]
I am getting the same problem, i downloaded JASP 18.1 and it started crashing, and unistalled it and re-installed 17.3 but still crashing/
![image](https://github.com/jasp-stats/jasp-issues/assets/147950142/53bfe208-a658-44eb-a34a-96737f919cde)

**Comment by boutinb** [comment]
Hi @MartinS071 The database in your JASP file does not contain any data. This is as if the database was not saved. Could you do the same T-Test analysis, and save it in your local drive (not on your DropBox), and check whether you can open afterwards the JASP file?

**Comment by MartinS071** [comment]
Hi,

I have imported again the *.csv file and it is working. I guess the file got corrupted in the process.

Thanks,

Martin

De : bruno boutin ***@***.***>
Envoyé : 30 octobre 2023 08:45
À : jasp-stats/jasp-issues ***@***.***>
Cc : Martin Simoneau ***@***.***>; Mention ***@***.***>
Objet : Re: [jasp-stats/jasp-issues] [Bug]: JASP has experienced an unexpected internal error: The engine crashed (Issue #2367)


Hi @MartinS071<https://github.com/MartinS071> The database in your JASP file does not contain any data. This is as if the database was not saved. Could you do the same T-Test analysis, and save it in your local drive (not on your DropBox), and check whether you can open afterwards the JASP file?

**Comment by boutinb** [comment]
Fine that it works!
