### ISSUE TITLE
[Bug]:  linux folder /mnt/ not visible in Jasp-stats

### ISSUE THREAD

**Issue by LLR72** [jasp-stats/jasp-issues#2369]
### JASP Version

0.18.1

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

open shared folder

### What OS are you seeing the problem on?

Flatpak, ChromeOS

### Bug Description

Hi
I installed Jasp on my chromebook and would like to access google drive. I have shared my google drive with Linux in chrome os. Other Linux applications that I have running on my chromebook have access to linux shared folder /mnt/ but not Jasp.
Below here is Krita (dark theme) where you can see /mnt/ and on top Jasp (light theme) where the /mnt/ is missing.
![Screenshot 2023-10-29 09 34 47](https://github.com/jasp-stats/jasp-issues/assets/114344470/46dac5ea-6ba7-482a-8169-7a76a86bd63a)

### Expected Behaviour

Have access to shared folders

### Steps to Reproduce

1. reinstalled Jasp from flatpak
2. removed and reinstalled linux, install Jasp from flatpak without any succes.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by shun2wang** [comment]
@LLR72  Yes, JASP on Linux is packed as flatpak run as sandbox and we do not give it wide file system permissions. You can do this on your device to override permissions:

`flatpak override org.jaspstats.JASP --filesystem=/mnt`
or other paths what you want.note, a `sudo` you may need to use for that command.

**Comment by LLR72** [comment]
Thanks for the advice but it didn't work out of the box. I think it works if you are running Jasp as root. But I am running it local in Crostini on my Chromebook.
Flatpak is made after I stopped using Linux on desktop PC. After a short investigation I copied the library /Overrides/  with  the file org.jaspstats.JASP from /var/lib/flatpak/ to /home/ "local user"/.local/share/flatpak/ and now it works.
