### ISSUE TITLE
Changing variable levels messes up cell order

### ISSUE THREAD

**Issue by MichlF** [jasp-stats/jasp-issues#237]
Hi,

When I input three variables in an RANOVA in the "Repeated Measures Factors"-window and immediately input their individual levels, the order of these variables in the "Repeated measures cells"-window below makes sense:
It is var1, var2, var3. 
However, when I add a fourth variable, all of a sudden the order in the cells window is changed to var1, var2, var4, var3, while var3 is only labelled as "Level1" and "Level2" (assuming I have 2 levels for it). 

If I now go back and change level labelling it gets even weirder: the values for the third variable in the cells window take on the individual level labels that I change in a chronological order, no matter to which variable they actually belong to. For example, say var3 has level A and level B, and var4 has level C and level D, then after adding the fourth variable, the, for example, first two cells (after the first two vars) read, "C, level 1" and "D, level 2". If I change the first level of var3 from A to X, the first two cells read "X, level 1" and "D, level 2". So, now there is no variable order anymore but a level order because I can now change the first level of var4 from C to Y and the second level of var3 from B to Z (in that order) and the first two cells will now read "Y, level 1" and "Z, level 2". 
The first two cells are just mentioned for illustration. The pattern continues for all remaining cells.

In general, it is clear that adding a fourth variable messes something up. There is more unexpected behavior with a fourth variable that I don't go into detail here but I hope this already helps tracking the issue.

I cannot imagine this behavior is intentional. In any case, it is extremely annoying when you work with more than three variables with variables that have more than two levels.
I am using the most recent version and I have observed this in earlier versions as well.

Cheers,
Michl

**Comment by boutinb** [comment]
This is solved in 0.9.3 (to be released in April)
