### ISSUE TITLE
Forest plot measures

### ISSUE THREAD

**Issue by Fernandez-Felix** [jasp-stats/jasp-issues#2371]
### Description

I know that the appropriate scale to synthesize ORs or RRs is the "log scale", but interpreting them is easier using the original scale (OR or RR). I am trying to build the forest plot using ORs. However, it seems that it is not possible to exponentiate "Effect Size" in JASP.

### Purpose

I propose to aggregate the polled effect using "log scale" and then visualize the results (tables or forest plots) in ORs scale.

### Is your feature request related to a JASP module?

Meta Analysis

### Describe the solution you would like

I would like to visualize the results (tables or forest plots) in the original scales (i.e. OR or HR).

**Comment by FBartos** [comment]
Hi, that's a great request -- I will keep it in mind when updating the module!

**Comment by tomtomme** [comment]
forest plot requests:
https://github.com/jasp-stats/jasp-issues/issues/1542
https://github.com/jasp-stats/jasp-issues/issues/2210

**Comment by Fernandez-Felix** [comment]
Thank you,
This could help to interpret the results and improve the presentation.
However, if the x-axis of the forest plot still appears on a logarithmic
scale, it may not be sufficient. Ideally, the plot should also be rescaled.

Borja
