### ISSUE TITLE
[Bug]: empty module pane in edit mode

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#2373]
### JASP Version

0.18.1

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Flatpak

### Bug Description

![grafik](https://github.com/jasp-stats/jasp-issues/assets/4428185/601b87a8-d185-4e64-b156-3cd63fcb13fe)

### Expected Behaviour

the blue plus should be hidden in data edit mode or it should show the modules

### Steps to Reproduce

1. go into data edit mode
2. click blue plus
3. its empty

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by EJWagenmakers** [comment]
Agreed. I think it should be hidden.
EJ

**Comment by boutinb** [comment]
Yes we have changed this for the next release: this will be a menu to set properties of the current workspace: https://github.com/jasp-stats/jasp-desktop/pull/5276
