### ISSUE TITLE
[Feature Request]: calculations validations

### ISSUE THREAD

**Issue by sttrebo** [jasp-stats/jasp-issues#2375]
### Description

software validations?

### Purpose

for formal report submissions

### Use-case

when using JASP for formal reports, having the statistics calculations validated is a requirement in my industry.

### Is your feature request related to a problem?

no problem, just a question

### Is your feature request related to a JASP module?

Other

### Describe the solution you would like

validation reports or such type of data

**Comment by TarandeepKang** [comment]
Hi @sttrebo,

Let me start by saying that I'm not a member of the team, but an enthusiastic user of the software. With that in mind, the team have put substantial effort into verification of the output produced by the software. Details are available here: 

https://jasp-stats.org/2021/02/03/the-jasp-verification-project/

Including a link to a separate website that contains all validations they have conducted so for.

**Comment by tomtomme** [comment]
@sttrebo 
Sounds like this is solved. An update of the validation project may be needed, however I do not think that we need this issue as a reminder. Please reopen, if I am mistaken.
