### ISSUE TITLE
[Feature Request]: About MGCFA

### ISSUE THREAD

**Issue by Jiyoung-S** [jasp-stats/jasp-issues#2378]
### Description

JASP allows me to easily approach statistical analysis.  I'm currently conducting a Multi-group Confirmatory Factor Analysis (MGCFA) in the CFA section to verify measurement invariance (MI) of the scale. In JASP, during the MGCFA stage, I can choose from four options (Configural, Metric, Scalar, Strict). As far as I know, many researchers compare mean differences between groups when MI is achieved partially at least. This typically represents the last step in testing MI, known as structural invariance, which involves verifying variance, covariance, and mean invariance. It's conceptualized by setting the reference group's mean to 0 and comparing the differences with the means of other groups.  Is this option(or analysis) available? Or is the answer already in the results of the existing options, and I just can't find it?

### Purpose

MGCFA

### Use-case

Measurement Invariance

### Is your feature request related to a problem?

JASP allows me to easily approach statistical analysis.  I'm currently conducting a Multi-group Confirmatory Factor Analysis (MGCFA) in the CFA section to verify measurement invariance (MI) of the scale. In JASP, during the MGCFA stage, I can choose from four options (Configural, Metric, Scalar, Strict). As far as I know, many researchers compare mean differences between groups when MI is achieved partially at least. This typically represents the last step in testing MI, known as structural invariance, which involves verifying variance, covariance, and mean invariance. It's conceptualized by setting the reference group's mean to 0 and comparing the differences with the means of other groups.  Is this option(or analysis) available? Or is the answer already in the results of the existing options, and I just can't find it?

### Is your feature request related to a JASP module?

Factor

### Describe the solution you would like

structural invariance, which involves verifying variance, covariance, and mean invariance

### Describe alternatives that you have considered

structural invariance, which involves verifying variance, covariance, and mean invariance

**Comment by Jiyoung-S** [comment]
I have some additional questions.

1. What is the difference between Multigroup SEM in the SEM section and Multigroup CFA in the FACTOR section? When both are analyzed using the ML estimator, the results appear differently.

2. Unlike in SEM, in MGCFA, the results of invariance testing for the 4 groups are not directly compared; instead, I can only see individual results. Do I need to calculate the differences between each set of results myself?

**Comment by juliuspfadt** [comment]
@Jiyoung-S thanks for creating the issue. I think you are correct, constraining the structural parameters to be equal is not yet implemented in JASP. 

I know this might be annoying, but your remaining questions read as bugs and not as feature requests, so I would ask you to open up other issue(s) for these. And if you do so, be sure to provide a data file. It is always hard to come by data with more than two groups that works with in a SEM.
