### ISSUE TITLE
[Bug]: Scrolling list of variable names missing on left-hand side of Create Computed Column functionality

### ISSUE THREAD

**Issue by JimWeinrich** [jasp-stats/jasp-issues#2379]
### JASP Version

0.18.1

### JASP Module

Other

### What analysis are you seeing the problem on?

Create new calculated data column

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

I myself + several students have all experienced the same bug. After clicking the black + sign to create a new variable, we click the Hand icon to open the interface for drag and drop creation of a new computed column. The scrolling list of functions on the right-hand side of that box is squeezed but functions OK. There is supposed to be a scrolling box on the left that shows the names of all of the currently existing variables, so that we can click and/or drag/drop those variable names into the formula. But it's missing! More precisely, the scroll bar exists and scrolls (!!) but the actual list of names of the variables is not there. See screen shot:

<img width="169" alt="image" src="https://github.com/jasp-stats/jasp-issues/assets/30815406/ef9761d8-bee3-440b-8f1a-84eda08464ca">

Apologies if this bug has been previously reported; I looked but couldn't find it.

### Expected Behaviour

There should be a scrolling list of variable names on the left-hand side.

### Steps to Reproduce

Steps are specified above

### Log (if any)

I am not including a data file, because it happens with any data file open in JASP.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @JimWeinrich We know about this issue, and we have solved it. For this, download the newest version: https://static.jasp-stats.org//JASP-0.18.1.0-macOS-x86_64_new2.dmg

**Comment by JimWeinrich** [comment]
Great! Thank you!

--jw
