### ISSUE TITLE
[Bug]: the engine crashed

### ISSUE THREAD

**Issue by MinulSakinah** [jasp-stats/jasp-issues#2385]
### Description

internal error

### Purpose

statistic 

### Is your feature request related to a problem?

cannot use while open the CSV format file

### Describe the solution you would like

fix my JASP

**Comment by EJWagenmakers** [comment]
Dear Minul,
In order to help you out we need a reproducible path. For starters: What OS are you using, what csv file are we talking about, what is your JASP version, do you have screenshots, etc.
EJ
