### ISSUE TITLE
[Feature Request]: General Full Factorial Design in Quality Control

### ISSUE THREAD

**Issue by podojk** [jasp-stats/jasp-issues#2387]
### Description

Create General Full Factorial Design & Analyze

### Is your feature request related to a JASP module?

Quality Control

### Additional context

Hello! 
I would like to request assistance in performing a General Full Factorial Design using JASP statistical software. 
I would like to input the information regarding the factors and levels I want to analyze, generate the experimental design, and visualize the results. 
Could you please help me with this analysis? Thank you!

**Comment by tomtomme** [comment]
Those kind of requests are better served in the forum: https://forum.cogsci.nl/categories/jasp-bayesfactor
On GitHub we track only Bugs and Feature requests.
Would it be possible that you re-post your request on the forum?

**Comment by podojk** [comment]
hello @tomtomme, 
I can re-post on the forum, but what I requested is a feature that does not currently exist in JASP. 
I posted this here as a suggestion for a new feature. 

Would it be better to post it on the forum?

**Comment by JTPetter** [comment]
@podojk You can create general full factorial designs under DOE -> factorial design. You can set the number of factor levels to anything, you are not limited to two-level factorial designs. What JASP currently cannot do is create designs in which factors have different levels, e.g., one two-level factor and two three-level factors -- this is under development. The DOE -> Analyze design analysis should already be able to handle all kinds of general full factorial designs. Does this address what you were looking for or is there anything else missing?

**Comment by podojk** [comment]
@JTPetter Thank you for your attention to this matter. 
The feature I looking for was create a design in which factors have different levels.
I look forward to hearing from you regarding the potential timeline for the completion of this development.

**Comment by tomtomme** [comment]
> hello @tomtomme, 
> I can re-post on the forum, but what I requested is a feature that does not currently exist in JASP. 
> I posted this here as a suggestion for a new feature. 
> 
> Would it be better to post it on the forum?

Thanks for tje clarification, sorry dor my miaunderstandig. I guess I should go on vacation for some weeks :D

**Comment by JTPetter** [comment]
@podojk Currently we are aiming for Q1 2024 for this feature and other improvements in the DoE design creation/analysis! But of course, it is hard to predict how smoothly the implementation will go...
