### ISSUE TITLE
[Bug]: Installment of JASP 0.18.1.0 failed because program did not have permission to remove software

### ISSUE THREAD

**Issue by Mikeszk98** [jasp-stats/jasp-issues#2389]
### JASP Version

0.18.1

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

Installing JASP

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I was installing JASP 0.18.1.0 using JASP-0.18.1.0-Windows-signed.msi when the program stopped with a message that I cannot remove a program without administrative permission.

During the install process, does the installing software try and remove prior versions of JASP?

### Expected Behaviour

I suspect that older versions of JASP would have been removed and replaced by JASP 0.18.1.0

### Steps to Reproduce

1.Rerun the install program
2.
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by Mikeszk98** [comment]
Just prior to submitting the issue, I started to run the install file again.  Will follow up with a screen shot.

**Comment by Mikeszk98** [comment]
In addition, this time I checked the Advanced option box and elected to install JASP 0.18.1.0 under my own User folder.
Might this resolve the problem ?

**Comment by tomtomme** [comment]
yes, this could help

**Comment by EJWagenmakers** [comment]
Also, if you download the pre-installed zip file, then unzip to a folder of your choice, you can click "JASP.exe" to start the program.
EJ

**Comment by boutinb** [comment]
Hi @Mikeszk98, yes the installer tries to remove the old version. It could be that some processes are still accessing part of the old JASP version. To be completely sure, you can just restart your PC. If it still does not work, you can try to uninstall the old JASP version by using the Software Center of your PC (don't remove the JASP folder manually).

**Comment by Mikeszk98** [comment]
I elected to shut down my computer, restart my compute and use the msi file to install the JASP 0.18.1.0
When the program was installing JASP, there is an option to install the program under a specific user, I elected to install it under my name (note, I am the only user of my laptop). 
Installing JASP using the above option, it correctly installed.

I was able to open JASP 0.18.1.0 without problems and open a previous JASP file.

You may close ticket 2389.

**Comment by boutinb** [comment]
Happy this is solved!
