### ISSUE TITLE
BUG report on descriptive statistics splitted by groups

### ISSUE THREAD

**Issue by AL38000** [jasp-stats/jasp-issues#239]
bug reports
<!--- I got the following error message when I try to obtain a boxplot splitted by groups
![image](https://user-images.githubusercontent.com/35261633/48301894-01049c80-e4f5-11e8-8b88-e1bafff6f0df.png)

* JASP version:0  9 1 
* OS name and version:  windows 7
* Analysis: Descrpitives / Boxplot split by groups. I have missing values in some groups
* Steps to reproduce: dependant variable = Climat social ; independant variable = Anciennete (but the same bug happened with other factors such as fonction)
Image : 
![image](https://user-images.githubusercontent.com/35261633/48301938-9f90fd80-e4f5-11e8-92ee-b717d5dbdafb.png)
csv file : 

[Barometre social.zip](https://github.com/jasp-stats/jasp-desktop/files/2568441/Barometre.social.zip)

**Comment by AlexanderLyNL** [comment]
Hi @AL38000, 

Could you please elaborate and add the jasp file as a zip to this thread?

Cheers,
Alexander

**Comment by AL38000** [comment]
Here is the file requested
[Barometre.zip](https://github.com/jasp-stats/jasp-issues/files/2584352/Barometre.zip)

**Comment by AlexanderLyNL** [comment]
Hi @AL38000,

Thanks for the jasp-file, but I'm not sure about the specifics. Could you please elaborate?

Cheers,
Alexander

**Comment by AL38000** [comment]
The bug occurs when : 
- I want to display boxplots splitted by groups when grouping variable contains missing values
- Example :  display levels of "Satisfaction globale" or "Climat social" by "Fonction" or by "Appartenance"
Thanks !

**Comment by AlexanderLyNL** [comment]
Thanks again for reporting this, we're working on this and the leading issue is now Issue #304. I'll close this to avoid duplicates.
