### ISSUE TITLE
[Bug]: Cannot download JASP from website, server issue?

### ISSUE THREAD

**Issue by zaabd004** [jasp-stats/jasp-issues#2390]
### JASP Version

0.18.1

### JASP Module

Unrelated

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

I've tried to download JASP from the server multiple times on different computers now without success. The download just doesn't start.

### Expected Behaviour

Should've been able to download JASP using the links

### Steps to Reproduce

1. Go to the download page and try do download JASP
2. 
3.
4.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @zaabd004 There was probably a problem with our servers. But now it should work. Can you try again?

**Comment by zaabd004** [comment]
Dear Boutinb, I still have the same issue... It worked for a brief period yesterday, but I never got to download the whole thing.

**Comment by boutinb** [comment]
Strange, our server works... Maybe you can try from the GitHub server here: https://github.com/jasp-stats/jasp-desktop/releases/tag/v0.18.1. Choose the JASP-0.18.1.0-macOS-x86_64_new2.dmg for your case.
