### ISSUE TITLE
[Bug]: copy pasting data & switching scale looses labels or values

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#2391]
### JASP Version

0.19 beta

a) Copy pasting data looses labels or replaces values by labels
b) switching scale looses labels

### Steps to Reproduce
a)
- I open two data sets side by side in two distinct jasp windows.
- I enter edit mode in both
- I copy and paste labeled data from one to the other.
- Only the labels are copied, the values are lost. 

b) 
Switching from ordinal to scale and back - labels are lost

### expected behaviour
labels and values should both be copied, even when the scale is switched to metric, so that only the values are shown. So that when I switch back to ordinal or nominal I can read the labels again.
The bug seems to be related to https://github.com/jasp-stats/jasp-issues/issues/2388

**Comment by tomtomme** [comment]
some further analysis of this bug on my linux machine instead of the MacOS Intel machine of my student:

JASP to JASP
--------------------
If I copy from a JASP and paste into a JASP file (both from the data library):
![jasp-to-jasp](https://github.com/jasp-stats/jasp-issues/assets/4428185/f0dfc192-0033-48ba-961a-1f05e9d15025)

multiple problems here 
- the data is shifted one row down ONLY IF   I use the right click menu and click copy. This does not happen if I use the shortcut Strg+C and then paste (regardless of rightclick-paste via menu or Strg+V). This happens also for non-labeled data.
- The original values are replaced by the strings. 
- the name of the variable is lost
- the scale is altered


SAV to SAV
--------------------
If I copy from a SAV and paste into a SAV file (both appended):
[Archiv.zip](https://github.com/jasp-stats/jasp-issues/files/13297799/Archiv.zip)

![sav-to-sav](https://github.com/jasp-stats/jasp-issues/assets/4428185/e6d8ea56-f891-41a0-b121-cbb2665df6ea)

Same problems as above, and then one more:
- SAV files cannot be opened by double clicking on them. You can only open them through JASPs open menu (this might be a flatpak issue)


SAV to JASP
--------------------
If I copy from a SAV and paste into a JASP file same problems as above. 


Analysis:
--------------------
So I cannot reproduce the exact same problem that my students MacOS Intel machine had, when copying from SAV to JASP, where the values got lost completely. But for me on Linux flatpak the values get replaced by the labels, which is not much better. This also happens robustly for SAV, JASP and the mixture of both file types. Also the right click menu copy shifts the data one down and the variable name etc. are lost always.

**Comment by tomtomme** [comment]
Some of the bugs are solved in 0.18.2 flatpak-beta from 30.11.23   :D
- copy pasting from ODS file
- copy pasting by right click menu does not shift the data one cell down as before
- name and scale of copy pasted variable are now preserved 

Bugs that remain:
- when copy-pasting data to another jasp file, the values get replaced by the labels

**Comment by boutinb** [comment]
@JorisGoosen is working on reshaping the label / empty values code. Maybe he can take care of this issue at the same time.

**Comment by JorisGoosen** [comment]
Im trying to make the backend for the data so that it makes the least conversions as possible of the underlying data.
When we have a testversion of that we can see if the way it works then is good enough ^^
