### ISSUE TITLE
[Bug] Name of the Catagorical variables are being pulled from wrong table

### ISSUE THREAD

**Issue by MODerakhshan** [jasp-stats/jasp-issues#2392]
### JASP Version

0.18.1

### JASP Module

Quality Control

### What analysis are you seeing the problem on?

DOE Response Surface Design

### What OS are you seeing the problem on?

Windows 10

### Bug Description

in the input side the categorial factors are labeled as C & D. however in the output window the design is shown with the Categorical factors labeled as A & B instead of C & D. 

When I change the name of the continuous factor A to a, then in the output window, the table shows "a" for both Continuous and Categorical.

![Screenshot 2023-11-07 172346](https://github.com/jasp-stats/jasp-issues/assets/150195765/2e255064-f0a3-4565-ae97-cb912dd12758)

### Expected Behaviour

the Name of the Catagorical variables are being pulled from wrong table

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@MODerakhshan 
confirmed. Still an issue with 0.19 beta
