### ISSUE TITLE
[Bug]: quality control indivudal control chart won't run

### ISSUE THREAD

**Issue by mindyschwartz** [jasp-stats/jasp-issues#2394]
### JASP Version

0.18.1

### JASP Module

Quality Control

### What analysis are you seeing the problem on?

variable chart for indivudals

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

Error in tableIListCombined[['test3']]: subscript out of bounds

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = da
<img width="1234" alt="Screen Shot 2023-11-08 at 1 20 24 PM" src="https://github.com/jasp-stats/jasp-issues/assets/150285154/26f41e4e-4274-4ef3-9a4d-10617a579c59">
taset, options = options)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports
![image](https://github.com/jasp-stats/jasp-issues/assets/150285154/d547666b-0d60-4b1a-a4c3-4e7501985f4a)

### Expected Behaviour

produced a control chart

### Steps to Reproduce

1. entered data
2. ran quality control control chart for indivudal
3. entered variables and axis labels 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JTPetter** [comment]
Hi @mindyschwartz, thanks for your report. I cannot reproduce this error, would you mind sharing your dataset or JASP file here?

**Comment by mindyschwartz** [comment]
JASP file. It won't let me run a variable chart for individuals with
session# as the axis label and SCL or PT CON as the variable. I am able to
run the chart for all the other variables (OQ, WAI etc) but I get an error
message when I try to run it for these two variables.

**Comment by JTPetter** [comment]
@mindyschwartz I cannot see the JASP file, unfortunately. I think you might need to upload it on GitHub directly (and possibly change the ending to .zip).

**Comment by mindyschwartz** [comment]
[JASP data sheet_Without missing data.csv](https://github.com/jasp-stats/jasp-issues/files/13300400/JASP.data.sheet_Without.missing.data.csv)
does this work?

**Comment by mindyschwartz** [comment]
[JASP with input missing data.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/13301086/JASP.with.input.missing.data.jasp.zip)
this is the jasp file as a zip

**Comment by JTPetter** [comment]
@mindyschwartz Thanks, that worked. I could reproduce this with JASP 0.18.1. This is fixed already in the development code. So this will work in the next release (or if you need it earlier, you can download a nightly release at https://static.jasp-stats.org/Nightlies/ some time after https://github.com/jasp-stats/jaspQualityControl/pull/288 is closed)

**Comment by mindyschwartz** [comment]
thanks for the reply. I need it for a school assignment due at the end of
November. Will the nightly release or the JASP 0.18.1 be released before
then so I can run my analysis for the assignment in time?

**Comment by JTPetter** [comment]
@mindyschwartz I am pretty confident it should happen before the end of November. Otherwise, you can also download an older version from the JASP website, the bug is also apparently not present in JASP 0.17.3 for instance.
