### ISSUE TITLE
[Bug]:  Error in Bayesian A/B Test

### ISSUE THREAD

**Issue by JustMe3714** [jasp-stats/jasp-issues#2395]
### JASP Version

0.18.1

### JASP Module

Frequencies

### What analysis are you seeing the problem on?

Bayesian A/B Test

### What OS are you seeing the problem on?

Windows 11

### Bug Description

![bug data](https://github.com/jasp-stats/jasp-issues/assets/150305759/2a02efd6-e56c-4c27-bbec-ddd46d67b0f3)
![bug error](https://github.com/jasp-stats/jasp-issues/assets/150305759/684190ba-fd73-4658-b25e-5275c6a461a2)

### Expected Behaviour

Instead of results got the above attached error message.  This only requires four #s for input and no matter what I try I only get error messages.

### Steps to Reproduce

1.Enter four numbers 
2. Go to Frequencies> Bayesian A/B Test
3. Enter data accordingly

...

### Log (if any)

[JASP 2023-11-08 19_49_06 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/13302612/JASP.2023-11-08.19_49_06.Engine.0.log)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JustMe3714** [comment]
Hello, has anyone been able to duplicate this?  If so, will it be fixed in an update?  Thanks.

**Comment by EJWagenmakers** [comment]
I think the test expects binary values? Did you look at some examples of how this is coded?
EJ

**Comment by shun2wang** [comment]
OK，maybe I know what happend:

in the dataset if you input only one row, then other rows will be auto filled by "NaN" missing values. like:
```
                     V1                    V2                  V3                    V4
1                    17                   56                   14                    51
2                   NaN                  NaN                  NaN                  NaN
3                   NaN                  NaN                  NaN                  NaN
4                   NaN                  NaN                  NaN                  NaN
5                   NaN                  NaN                  NaN                  NaN
6                   NaN                  NaN                  NaN                  NaN
7                   NaN                  NaN                  NaN                  NaN
8                   NaN                  NaN                  NaN                  NaN
9                   NaN                  NaN                  NaN                  NaN
10                  NaN                  NaN                  NaN                  NaN

```

in the R package of `abtest` which this analysis used, where handle the dataset as:
```
data <- list(y1 = data$y1[length(data$y1)],
             n1 = data$n1[length(data$n1)],
             y2 = data$y2[length(data$y2)],
             n2 = data$n2[length(data$n2)])

if (data$y1 < 0 || data$y2 < 0 || data$y1 > data$n1 ||
    data$y2 > data$n2) {
  stop('y1 needs to be a number between 0 and n1 and y2 needs to be
         a number between 0 and n2',
       call. = FALSE)
}
```
so that will all returns "NA" values the conditional statements will failing.

@JorisGoosen @boutinb  I think this will also affect other analyses, if the conditional judgment of the R package does not handle such missing values as expected. So is there a better way to pass the dataset? or something I am missing here?

**Comment by JustMe3714** [comment]
Hello, thanks for the comments.  But even when I enter multiple rows of data, I still get an error message (please see screenshots).  What am I doing wrong? Thanks.
![data](https://github.com/jasp-stats/jasp-issues/assets/150305759/1c641798-14b0-4535-af20-3701c4d1bb81)
![error message](https://github.com/jasp-stats/jasp-issues/assets/150305759/77830aa4-1a81-401e-9d4e-2b3f09c53217)

**Comment by JustMe3714** [comment]
Thank you! Your temporary fix worked. Glad this will be fixed.
