### ISSUE TITLE
[Bug]: Export csv file from .jasp file will lost values

### ISSUE THREAD

**Issue by shun2wang** [jasp-stats/jasp-issues#2396]
### JASP Version

0.18.1

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 11

### Bug Description

When a jasp file with a filter applied is exported to a csv file, all values in the first column are lost. reproduce step as following. same like: https://github.com/jasp-stats/jasp-issues/issues/2388#issuecomment-1800828401

### Expected Behaviour

export all data without filter applied.

### Steps to Reproduce

1. make a .jasp file, first col as nominal variable, and some other columns with value.
2. applied filter for one of the columns.
3. make some analysis
4. save the .jasp file, repoen the file and try to export data as .csv file.

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by shun2wang** [comment]
[Test_save_csv.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/13307699/Test_save_csv.jasp.zip)
Use this file to reproduce, remove the .zip suffix

**Comment by boutinb** [comment]
Yes this is an important bug... It is solved and will be in the 0.18.2 (over 2/3 weeks hopefully).
