### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by abstractava** [jasp-stats/jasp-issues#2397]
### JASP Version

0.18.1

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

ANOVA

### What OS are you seeing the problem on?

Other

### Bug Description

Put in the dependent variable and fixed factor and got this
<img width="1194" alt="Screen Shot 2023-11-09 at 3 01 30 AM" src="https://github.com/jasp-stats/jasp-issues/assets/150329667/c4d593e0-d2b2-409d-b1e9-3307ed6eb2bb">

### Expected Behaviour

it should have given me the data output

### Steps to Reproduce

1. open file
2. click anova -> classical anova
3. move the anova box contents to the dependent variable box and fixed factors box
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JohnnyDoorn** [comment]
HI @abstractava ,

Hmm I cannot reproduce this - have you tried updating your version of JASP?
