### ISSUE TITLE
Feature request: Robust statistical analyses by Wilcox

### ISSUE THREAD

**Issue by kpriftis** [jasp-stats/jasp-issues#24]
Hi there and congratulations for JASP! It is wonderful! I already use it with my undergraduate students.

How about considering to implement in JASP,  robust analyses developed by Rand Wilcox (http://dornsife.usc.edu/labs/rwilcox/software/)? Robust analyses are extremely useful in psychological research, where in many cases the assumptions of classic parametric tests are violated. These analyses are already available in R: https://cran.r-project.org/web/packages/WRS2/index.html

All the very best,
Konstantinos Priftis

**Comment by TarandeepKang** [comment]
I would like to second the request for robust analyses, and add that Wilcox has now published an R package with an associated Behaviour Research Methods paper, which documents all of his procedures. https://doi.org/10.3758/s13428-019-01246-w

**Comment by psychresearch** [comment]
I made an account just to third the request for robust analyses!

**Comment by EJWagenmakers** [comment]
Yes, we should definitely do this, and increase the priority of this request.

**Comment by tomtomme** [comment]
@Suggestions-Only 
Welch ANOVA and Games-Howell post hoc tests are available since some time now.
MM-estimation for linear regression is not yet in.

@kpriftis 
Rand Wilcox methods are not yet implemented.  But we have at least one sort of non-parametric / robust / bootstrap option for most analyses in now

(P.S. Rand Wilcox is not to be confused with Frank Wilcoxon)

**Comment by tomtomme** [comment]
This is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/2305
Lets close this issue and discuss it at the more up to date issue 2305

**Comment by tomtomme** [comment]
wrs2 is now implemented as a community module. Is this sufficient?
