### ISSUE TITLE
bayesian contingency table and within-subjects design

### ISSUE THREAD

**Issue by IndrajeetPatil** [jasp-stats/jasp-issues#240]
In frequentist statistics, the contingency tables analysis will rely on-

- Pearson's chi-squared test for **between-subjects** design
- McNemar's test for **within-subjects** design

I couldn't find this in the documentation, so a bit confused by this: 
The Bayesian contingency table analysis in `jasp` supports both of these designs? Or only the between-subjects design? Or this is something to be specified with other options provided for this test?

**Comment by dontchaknowjo** [comment]
I'm wondering about this as well!

**Comment by IndrajeetPatil** [comment]
Apparently, only between-subjects designs are supported.

https://github.com/richarddmorey/BayesFactor/issues/150

**Comment by tomtomme** [comment]
@IndrajeetPatil 
McNemar is now available in the beta version of the frequencies module, available in the module library.

Cochrans test also known as Cochrans Q is tracked here https://github.com/jasp-stats/jasp-issues/issues/1445
