### ISSUE TITLE
[Bug]: can’t open files 

### ISSUE THREAD

**Issue by nphil3** [jasp-stats/jasp-issues#2400]
### JASP Version

0.18.1

### JASP Module

Other

### What OS are you seeing the problem on?

ChromeOS

### Bug Description

It won’t let me open files. I saved it as a csv and it won’t show up anywhere 

### Expected Behaviour

The file should show up

### Steps to Reproduce

1. Create csv file 
2. Try to open it in jasp
3. It won’t show up
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by EJWagenmakers** [comment]
From looking at the screenshot you sent through email, my guess is that you are using the version from Rollapp. This is a company not affiliated with us, and they have made it difficult to save files...unless you buy server space with them! I am therefore closing this issue (but I will note that for the Rollapp version there is a workaround, which is to log in to the OSF and upload/download files from there). I would strongly recommend using the version off the JASP website, which is also much improved compared to what Rollapp has. Please re-open this issue if my guess is wrong.
Cheers,
E.J.
