### ISSUE TITLE
I can't set the Dependent Variable on Bayesian linear mixed model analysis

### ISSUE THREAD

**Issue by sarah4747** [jasp-stats/jasp-issues#2401]
### JASP Version

0.18.1

### JASP Module

Mixed Models

### What analysis are you seeing the problem on?

bayesian linear mixed model

### What OS are you seeing the problem on?

Windows 11

### Bug Description

i want to do an analysis with BLMM. But I am not able to set the dependent variable.

### Expected Behaviour

I should be able to set the column Number_of_Accidents as the dependent variable.

### Steps to Reproduce

1. uploaded the .csv file
2. set up the fixed effect variable
3. set up the random effect grouping factor
...
[Book1.csv](https://github.com/jasp-stats/jasp-issues/files/13320958/Book1.csv)
[image](https://github.com/jasp-stats/jasp-issues/assets/150459747/cd5c09d3-2cf8-479f-8e40-a48ecf399f3f)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Most JASP modules have restrictions regarding the measurement scale of the data. 
The picture you uploaded shows, that your variable is set to ordinal scale
You can change it by clicking on the symbol left of the variable name  - in the data view.

**Comment by tomtomme** [comment]
@sarah4747 
I hope you could make it work. Pls reopen if not.
