### ISSUE TITLE
[Bug]: ANOVA isn't working

### ISSUE THREAD

**Issue by areejmirr** [jasp-stats/jasp-issues#2402]
### JASP Version

0.18.1

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

ANOVA

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

It gives the error message: 
Error in dyn.load(file, DLLpath = DLLpath, ...): unable to load shared object '/Applications/JASP.app/Contents/Frameworks/R.framework/Versions/4.2/Resources/library/Matrix/libs/Matrix.so':
  dlopen(/Applications/JASP.app/Contents/Frameworks/R.framework/Versions/4.2/Resources/library/Matrix/libs/Matrix.so, 6): Library not loaded: @executable_path/../Frameworks/R.framework/Versions/4.2/Resources/opt/local/gfortran/lib/libgfortran.dylib
  Referenced from: /Applications/JASP.app/Contents/Frameworks/R.framework/Versions/4.2/Resources/library/Matrix/libs/Matrix.so
  Reason: image not found

### Expected Behaviour

I should have a proper ANOVA conducted + Post hocs. 

### Steps to Reproduce

1.I entered DATA
2. clicked classical ANOVA
3.set the variables
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by areejmirr** [comment]
<img width="1440" alt="Screen Shot 2023-11-12 at 1 20 47 PM" src="https://github.com/jasp-stats/jasp-issues/assets/150616402/1c0e9847-3eff-4285-a2d9-142c0cbc3801">

**Comment by boutinb** [comment]
@areejmirr This is known problem on Mac Intel. we have a new version here: https://static.jasp-stats.org//JASP-0.18.1.0-macOS-x86_64_new2.dmg
We are planning to make a new official version over 2/3 weeks.
