### ISSUE TITLE
[Feature Request]: Add option to QML dropdown to prevent width from adjusting to longest element name 

### ISSUE THREAD

**Issue by maltelueken** [jasp-stats/jasp-issues#2404]
### Description

Currently, the QML dropdowns automatically adjust their width to the longest element label they have. While this is usually desirable, it can in some cases lead to the dropdown being cut off by the parent element.

### Purpose

In cases, where the space is limited and the length of the longest element is not known, there should be an option to prevent the width from adjusting.

### Use-case

In jaspProcess, the user can use their own variable names as elements for the dropdowns. For long variable names, the dropdowns are cut off.

### Is your feature request related to a JASP module?

Other

### Describe the solution you would like

An option in the `DropDown` component that disables the automatic width adjustment.

### Describe alternatives that you have considered

The options `fieldWidth` and `minControlWidth` don't solve the problem.

### Additional context

![image](https://github.com/jasp-stats/jasp-issues/assets/63114869/83867574-90fe-4d11-9b23-e9ca3c3916ac)

**Comment by tomtomme** [comment]
will this pull request solve this one? https://github.com/jasp-stats/jasp-desktop/pull/5586

**Comment by boutinb** [comment]
> will this pull request solve this one? [jasp-stats/jasp-desktop#5586](https://github.com/jasp-stats/jasp-desktop/pull/5586)

Yes
