### ISSUE TITLE
[Bug]: Translation of two statistical terms ("Intercept" and "Coefficients") do not show up in German translation of jaspRegression module

### ISSUE THREAD

**Issue by brandmaier** [jasp-stats/jasp-issues#2405]
### JASP Version

0.18.1

### JASP Module

Regression

### What analysis are you seeing the problem on?

Linear Regression

### What OS are you seeing the problem on?

Windows 11

### Bug Description

I believe there is a bug (or two) related to the translation of statistical terms in the regression module. The terms "intercept" and "coefficients" are shown in English even though German translations are provided in the respective po-files. This observation is based on JASP 0.18.1. Here is a screenshot:

![image](https://github.com/jasp-stats/jasp-issues/assets/116031/01743535-5b11-4e4c-9c12-aff372235df0)

I provided a pull request to fix the issue with the term `coefficients` in the JASP table header (https://github.com/jasp-stats/jaspRegression/pull/269 and related issue in jaspRegression https://github.com/jasp-stats/jaspRegression/issues/268 ) but fixing the term `coefficients` seems more complicated as it occurs in multiple different operations throughout the module.

The translations are actually provided in the PO files but never used.

Here is the excerpt from the German translation file (https://github.com/jasp-stats/jaspRegression/blob/master/po/R-de.po):
```
msgid "(Intercept)"
msgstr "(Konstante)"
```

and

```
msgid "Coefficients"
msgstr "Koeffizienten"
```

### Expected Behaviour

Instead of `(Intercept)`, JASP should show the translation. In German, this would be `(Konstante)` according to the PO file. Instead of "Coefficients", it should show the translation, which would be `Koeffizienten` in German according to PO file. 

### Steps to Reproduce

0. Set JASP to German (or any other language than German)
1. Open the Adam Sandler regression example dataset
2. Create a regression model with DV Freshness and IV year

...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Thanks Andreas for the report! :)

I also reported similar non-translatable strings a while ago here: 
https://github.com/jasp-stats/jasp-issues/issues/2080

The more reports, the sooner this bug will hopefully be resolved :D

While we are at it: Shouldn't "Intercept" be translated with "Schnittpunkt"? I know its a constant at the same time, but the translation guidelines argue, that we should translate as "directly" as possible.

**Comment by brandmaier** [comment]
I absolutely favor "Konstante" (or "Regressionskonstante") because this is the standard term used in German text books, like Bortz & Schuster or Eid et al.

**Comment by brandmaier** [comment]
Btw. the missing translation of "Coefficients" is now resolved (https://github.com/jasp-stats/jaspRegression/pull/269) but the other terms (like residuals in ANOVA) are more difficult to fix because they occur at so many places in the code.
