### ISSUE TITLE
[Bug]: Cannot compute new variable

### ISSUE THREAD

**Issue by Khouwers** [jasp-stats/jasp-issues#2407]
### JASP Version

0.18.1

### JASP Module

Other

### What analysis are you seeing the problem on?

Computing a new variable

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

When computing a new column, one of two problems arises: either no variables will be visible in the left-hand side to perform calculations on **or** in the case these do show up the computed variable will not have any data in the column. 

The first issue is exactly the same as described in [this forum](https://forum.cogsci.nl/discussion/8876/jasp-creating-a-new-variable) and does not occur in earlier versions.

### Expected Behaviour

Variables should be visible when wanting perform calculations to create a new variable

### Steps to Reproduce

1. Have a dataset with a dichotomous variable (e.g., gender)
2. Press the black cross to open the window that allows you to compute a new (dummy) variable
3. Be unable to compute this variable as no variables will appear

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
This is problem is known and was fixed here: https://static.jasp-stats.org//JASP-0.18.1.0-macOS-x86_64_new2.dmg
A new version. of JASP will come over 2/3 weeks.
