### ISSUE TITLE
[Bug]: File Not Responding 

### ISSUE THREAD

**Issue by ltabak18** [jasp-stats/jasp-issues#2410]
### JASP Version

0.18.1

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 11

### Bug Description

I cannot open this file anymore. Everytime I click on it it says file not responding. I can open other files just fine and was able to edit this one just earlier today. [
[Stress and Gender 1.zip](https://github.com/jasp-stats/jasp-issues/files/13355140/Stress.and.Gender.1.zip)
](url)

### Expected Behaviour

The file should open

### Steps to Reproduce

1. Click open
2.
3.
...

### Final Checklist

- [x] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Strange, I can open it without problem...  I have saved it again, maybe this version works for you:
[Stress and Gender 2.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/13362768/Stress.and.Gender.2.jasp.zip)

**Comment by tomtomme** [comment]
I can open it too, no problem. Sometimes it may help to restart the PC
