### ISSUE TITLE
The engine crashed...[Bug]: 

### ISSUE THREAD

**Issue by chengdi98** [jasp-stats/jasp-issues#2412]
### JASP Version

0.18.1

### JASP Module

Acceptance Sampling, Audit

### What OS are you seeing the problem on?

Windows 10

### Bug Description

The engine crashed...

### Expected Behaviour

The engine crashed...

### Steps to Reproduce

1.
2.
3.
...
The engine crashed...

### Log (if any)

The engine crashed...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by koenderks** [comment]
Hi @chengdi98,

Can you provide more information about what steps you took to encounter this problem. This issue is not very informative like this and it makes it very hard for us to find out where there is a problem. Please include screenshot, data file, and steps to reproduce where possible as outlined in the instruction. Thanks.

**Comment by Jaspzoli** [comment]
I have a crash issue as well with following conditions:

JASP Version 0.18.1

Edition	Windows 10 Enterprise
Version	22H2
Installed on	‎16/‎03/‎2022
OS build	19045.3693
Experience	Windows Feature Experience Pack 1000.19053.1000.0

Steps I do before it crashes:

1. Start JASP
2. Click on New Data icon
3. Copy the data from attached [Jasp_18_1_crash.xlsx](https://github.com/jasp-stats/jasp-issues/files/13451321/Jasp_18_1_crash.xlsx)'s cells A1:B5
4. Paste data to the A1 cell of JASP (either with CTRL+V or with right clicking on the cell and select PASTE)
5. JASP waits for some seconds and then closes without any notification
6. LOG files are here: [JASP 2023-11-23 15_59_42 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/13451355/JASP.2023-11-23.15_59_42.Desktop.log)
[JASP 2023-11-23 15_59_42 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/13451356/JASP.2023-11-23.15_59_42.Engine.0.log)

Sometimes if I try this with 7-8 times I can copy the data and JASP works fine. But in 90% of the cases it crashes.

Thanks for any tips what I should do different.

**Comment by koenderks** [comment]
@JorisGoosen @boutinb I've also seen this unknown crash 'the engine crashed' occurring in several modules on several people's pc's. It seems to only occur in 0.18.1 and gives no information regarding cause.

**Comment by boutinb** [comment]
It seems to me that the issues from @chengdi98 & @Jaspzoli have nothing to do with each other. It would have been beter to add another issue. But as said @koenderks, the first issue has not enough information to be handled.
For the second one (from @Jaspzoli), I cannot reproduce it, but a lot of changes have been made in 0.18.2. This version should be released soon, but a beta version can be tested here: https://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-development-83c35ec12607829fceaace8e8d623965f8a9df65.msi

**Comment by tomtomme** [comment]
@chengdi98 
Please reopen, if you can add more details

@Jaspzoli 
Please open a new issue if this persists with jasp 0.18.3 - some data editing bugs were fixed there.
