### ISSUE TITLE
[Bug]: non translatable string

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#2417]
### JASP Version

0.18.2 beta

### JASP Module

Frequencies

### What analysis are you seeing the problem on?

Binomial Test

### What OS are you seeing the problem on?

all

### Bug Description

![image](https://github.com/jasp-stats/jasp-issues/assets/4428185/46e63d14-8b98-4b39-bd35-91490f61a72f)

### Expected Behaviou r

Cannot find String in Weblate.

Translation would be "Konfidenzintervall des Anteils"

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@FBartos 
Can this be fixed for 0.18.2?

**Comment by FBartos** [comment]
This is a bit odd, seems to be gettext-ed here:
https://github.com/jasp-stats/jaspFrequencies/blob/master/R/binomialtest.R#L187-L190

```
    binomialTable$addColumnInfo(name = "lowerCI", title = gettext("Lower"), type = "number",
      overtitle = gettextf("%s%% CI for Proportion", 100 * options$ciLevel))
    binomialTable$addColumnInfo(name = "upperCI", title = gettext("Upper"), type = "number",
      overtitle = gettextf("%s%% CI for Proportion", 100 * options$ciLevel))
```

@vandenman ?

**Comment by shun2wang** [comment]
https://hosted.weblate.org/translate/jasp/jaspfrequencies-r/de/?checksum=bb6899c784361e5e&q=%25s%25%25+CI+for+Proportion&sort_by=-priority%2Cposition

@tomtomme It's on the Weblate already at above and can change it, you may searched by “95% ...” but not "CI for Proportion"?

**Comment by shun2wang** [comment]
Let's close it and people can make change on Weblate.
