### ISSUE TITLE
[Bug]: I can not download JASP (for windows). 

### ISSUE THREAD

**Issue by SuusMK** [jasp-stats/jasp-issues#2421]
### JASP Version

0.18.1

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 11

### Bug Description

When I try to download JASP loading takes too long, so the page will go to the 'can't reach this site'. The 'click here' link also does nothing.

### Expected Behaviour

When I click on the download for windows button, it should start the download within 5 seconds. 

### Steps to Reproduce

1. Download
2. Windows 64 bit
3. Then it takes too long and I get the waiting screen.

### Final Checklist

- [x] I have included a screenshot showcasing the issue, if possible.
- [x] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [x] I have accurately described the bug, and steps to reproduce it.

**Comment by SuusMK** [comment]
After trying at a later moment again, JASP did download.

**Comment by boutinb** [comment]
Hi @SuusMK, yes we have some problems with our server provide. I hope they can fix this quite quickly.
