### ISSUE TITLE
[Bug]: how to find out rules and sigma for control charts, variable charts for individuals in JASP

### ISSUE THREAD

**Issue by mindyschwartz** [jasp-stats/jasp-issues#2422]
### JASP Version

0.18.1

### JASP Module

Quality Control

### What analysis are you seeing the problem on?

variable chart for indivudals

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

I am looking to use the control charts, variable charts for individuals on JASP and I wanted to know where I can find a list of rules for determining the "out of control" data points (the ones that show up as red dots in the output)? I know in general there are rules such as x number of points being above or below the mean would create a "red dot" 
Also where can I find what sigma the charts are set to? 
I can't seem to find this info anywhere, if you could direct me to appropriate place to find this information.  

### Expected Behaviour

see question

### Steps to Reproduce

1.you can see the control chart, variable charts for individuals for each variable here (y = session number, x = the other variables) 
2.
3.
[JASP with input missing data.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/13418580/JASP.with.input.missing.data.jasp.zip)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JTPetter** [comment]
I assume our email conversation resolved this.
