### ISSUE TITLE
[Bug]: Outdated Webpages: Update FAQ & Mac installation

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#2425]
### JASP Version

0.18.1

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

FAQ on the homepage

### What OS are you seeing the problem on?

Other

### Bug Description

![image](https://github.com/jasp-stats/jasp-issues/assets/4428185/85bc9462-a40f-4ed9-86a4-308b87283575)

This is out of date since ZSAV support was added

![image](https://github.com/jasp-stats/jasp-issues/assets/4428185/1c26f7b1-e0a0-46f6-ba56-3f4f5bfebfa1)

Also I have not seen this "Developer cannot be verified" in a while. And the Apple support Info is from 2021. 

![image](https://github.com/jasp-stats/jasp-issues/assets/4428185/caf9282e-f474-445b-9148-40c7c9303ebe)

And this mention of XQuartz also seems outdated. Never have I seen a Mac that needed this. And I frequently help my students install it.

![image](https://github.com/jasp-stats/jasp-issues/assets/4428185/fd567086-fd40-4933-9526-7ed1be504594)

And this should possibly be mentioning the cooperation/community, or link to it.

### Expected Behaviour

should alle be updated

**Comment by boutinb** [comment]
Thank you @tomtomme ! I have updated the site.
