### ISSUE TITLE
[Bug]: The engine crashed while trying to run this analysis...

### ISSUE THREAD

**Issue by VasilChaly** [jasp-stats/jasp-issues#2428]
### JASP Version

0.18.1

### JASP Module

Quality Control

### What analysis are you seeing the problem on?

Any one and even during open old analysis after soft updating to latest version

### What OS are you seeing the problem on?

Windows 10

### Bug Description

After soft updating to latest version during opening program and starting work with data always get error message
![Screenshot 2023-11-24 143449](https://github.com/jasp-stats/jasp-issues/assets/151930249/47b4d04e-a1c0-41ca-b857-5d4eb2eeee8b)

[Mde-W+-OR-BT2-0130_B-13.11.2023.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/13459576/Mde-W%2B-OR-BT2-0130_B-13.11.2023.jasp.zip)

### Expected Behaviour

Correct program work

### Steps to Reproduce

1. I opened program in other computers. I got the same error message
2.
3.
...

### Log (if any)

I can't do it because after getting error message program is not active

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JTPetter** [comment]
@VasilChaly Thanks for reporting, since this is not specific to the Quality Control module, I have removed that label.

@boutinb Could you take a look or assign someone who might be able to troubleshoot this?

**Comment by koenderks** [comment]
Probably the same as https://github.com/jasp-stats/jasp-issues/issues/2412

**Comment by boutinb** [comment]
The JASP file contains a buggy Computed Column that makes it crash when upgraded to 0.18.1...
I will add a check to check that the Computed Columns are well formed.

**Comment by Franck6S** [comment]
I could had a screen copy, one additional evidence :
![CRASH](https://github.com/jasp-stats/jasp-issues/assets/152309774/a7a5c4f8-9ab8-4712-8766-492333adee29)

**Comment by boutinb** [comment]
We will release soon a new version, but for the time being you can try it with a beta version: https://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-matrixFix-19ecfd1cccce352c47dcbf7e1109e9d3f7f1bc4b.msi
