### ISSUE TITLE
[Bug]:Can't start JASP.

### ISSUE THREAD

**Issue by SunnyH666** [jasp-stats/jasp-issues#2438]
### JASP Version

0.16

### JASP Module

Other

### What OS are you seeing the problem on?

Windows 10

### Bug Description

After successfully installing JASP 16.0 on win10, clicking on JASP.exe, there is no response (nothing happens). I also tried installing 15.0 and still have the same problem. Of course I would like to try other newer versions, but using the msi installer, it reports an error: There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. . And after the pre-installed version is unzipped, clicking on JASP.exe is equally unresponsive.

### Expected Behaviour

No response

### Steps to Reproduce

1. Go to website and click on download [JASP 0.16.0 (Windows 64 Bit)]
2. Double click msi file
3. Open application folder and double-click to open > nothing happens.

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @SunnyH666 JASP 0.16 is already quite an old version. Could you try the newest version: https://jasp-stats.org/download/

**Comment by SunnyH666** [comment]
> Hi @SunnyH666 JASP 0.16 is already quite an old version. Could you try the newest version: https://jasp-stats.org/download/

I get an error when I install the latest version:  There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected.
The pre-installed version doesn't work either. After unzipping it, clicking on JASP.exe is equally unresponsive.

**Comment by SunnyH666** [comment]
> Hi @SunnyH666 JASP 0.16 is already quite an old version. Could you try the newest version: https://jasp-stats.org/download/

I just tried it again with just booting up and the error was reported as shown here
![微信图片_20231127214135](https://github.com/jasp-stats/jasp-issues/assets/101725476/c6bebb50-7325-4ddf-9da0-1608fe92d7fa)
![微信图片_20231127214148](https://github.com/jasp-stats/jasp-issues/assets/101725476/35d65b07-5a8d-48b6-b5d0-ab605aee97b2)
![微信图片_20231127214156](https://github.com/jasp-stats/jasp-issues/assets/101725476/4926f21b-7f92-49d3-b2aa-907dc7e37406)

**Comment by boutinb** [comment]
@SunnyH666 Could you restart your PC before installing JASP?

**Comment by tomtomme** [comment]
He already did!
But maybe you could check 
- if win10 updates are in place, 
- remove creative cloud etc from autostart
- check if enough disk space is left

**Comment by tomtomme** [comment]
Also: do you have admin priviliges? If not make sure to click on the advanced button during install. Then you can chosse to just install for the current user.

**Comment by SunnyH666** [comment]
> Also: do you have admin priviliges? If not make sure to click on the advanced button during install. Then you can chosse to just install for the current user.

I restarted my computer and installed it, and I still get the error message. As shown in the picture.
![微信图片_20231128210610](https://github.com/jasp-stats/jasp-issues/assets/101725476/c3800123-2794-41ba-bf50-f458b97f441d)
I have admin privileges. And if I choose to install only for the current user. The installation doesn't report any errors, but after the installation is complete, running JASP, it remains completely unresponsive, nothing happens after clicking on JASP.exe. And also, enough disk space is left; win10 updates are in place.

**Comment by tomtomme** [comment]
The next version should come in a week or so and with a new installer. Maybe that will help.

**Comment by SunnyH666** [comment]
Okay. Thanks a lot~~

**Comment by tomtomme** [comment]
Sorry that we could not help any further. If you have new error messages or logs, let us know.

Some more "educated" guesses:
- Maybe it has something to do with this "concrt140.dll" in windows/system32. If you have admin privileges you should be able to write to system32. 
- Maybe the downloaded JASP installer is corrupt and a redownload would help? 
- Maybe your drive is end of life? 
- Maybe it is some additional security setting that is activated by a virus scanner that prevents you from modifying files in system32. Maybe something is wrong with the windows installation

But at the end, I am obviously fishing in the dark here - while pressing thumbs nontheless :D
cheers, thomas

**Comment by tomtomme** [comment]
Here is some advice from microsoft concerning the DLL:
https://answers.microsoft.com/en-us/windows/forum/all/concrt140dll/9590dc9f-0129-4a57-9adc-1f7ea69e1893

**Comment by boutinb** [comment]
Also you have the possibility to use the pre-installed JASP version: https://jasp-stats.org/thank-you-for-downloading-jasp-win64-zip/
This is just a zip file you have to unzip in a folder: JASP is then not installed in your PC registry (you won't see it in the start menu), but you can still start JASP from the unzipped folder.

**Comment by tomtomme** [comment]
@boutinb 
The bug report mentions:
"And after the pre-installed version is unzipped, clicking on JASP.exe is equally unresponsive."

**Comment by boutinb** [comment]
Sorry @SunnyH666, I forgot this issue...
Do you have still this problem? Did you try the Windows Store version?

**Comment by SunnyH666** [comment]
> Sorry @SunnyH666, I forgot this issue... Do you have still this problem? Did you try the Windows Store version?

The one I downloaded from the Microsoft Store works fine. However, the version 0.18.1.0 that I installed before still won't open and can't be uninstalled.

![20240111212857](https://github.com/jasp-stats/jasp-issues/assets/101725476/38a1c0fb-be90-4599-be33-8712f8b9fd9f)

**Comment by SunnyH666** [comment]
> > Sorry @SunnyH666, I forgot this issue... Do you have still this problem? Did you try the Windows Store version?
> 
> The one I downloaded from the Microsoft Store works fine. However, the version 0.18.1.0 that I installed before still won't open and can't be uninstalled.
> 
> ![20240111212857](https://private-user-images.githubusercontent.com/101725476/295929305-38a1c0fb-be90-4599-be33-8712f8b9fd9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5ODAxMDksIm5iZiI6MTcwNDk3OTgwOSwicGF0aCI6Ii8xMDE3MjU0NzYvMjk1OTI5MzA1LTM4YTFjMGZiLWJlOTAtNDU5OS1iZTMzLTg3MTJmOGI5ZmQ5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQxMzMwMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZGVkMGQyYzhmZjRiNjEyM2Q4YmJiNmM2ZWRmNWUwMmMwZGYxZGM0YzBkZWI4MGQzNmE4YmVkMTM3MDZjZTg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bPdN5-nAqNrw2g_n29pVpvUQTIaTEjKPokQXyepfuFc)

Can I just delete the installation folder?

**Comment by tomtomme** [comment]
@SunnyH666 
Yes you can. You should also be able to start the uninstaller from within windows settings.

**Comment by SunnyH666** [comment]
Okay, thanks.
