### ISSUE TITLE
[Bug]: jdjjdjdjdhdhd

### ISSUE THREAD

**Issue by pascalK2** [jasp-stats/jasp-issues#2440]
### JASP Version

0.18.1

### JASP Module

Bsts

### What analysis are you seeing the problem on?

jdjjdyddydghd

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

hsshshhshshshshhshsjshxh jhqhjcw

### Expected Behaviour

jdhdhhdhjkshbbhdbjbsfkjdsdjddjdjdd

### Steps to Reproduce

1.
2.
3.
...
nncjdujjhehegegdgdgdgdusshsd

### Log (if any)

hdhdhdhdhdhdhd

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by pascalK2** [comment]
jdjdjddjd

**Comment by pascalK2** [comment]
djdjdhdhdhdhdh

**Comment by tomtomme** [comment]
I reported the user @pascalK2 for spamming us

**Comment by boutinb** [comment]
I did also
