### ISSUE TITLE
[Bug]: Informed Multinomial Crashes with Mac M2

### ISSUE THREAD

**Issue by mumair01** [jasp-stats/jasp-issues#2441]
### JASP Version

0.18.1

### JASP Module

Frequencies

### What analysis are you seeing the problem on?

Informed Multinomial

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

We were trying to test a multinomial model (4 > 1 = 2 = 3 = 5 = 6) with some empirical dice data. Right after we pressed Cmd-Return, we got a crash (see screen shot). 
[group8.csv](https://github.com/jasp-stats/jasp-issues/files/13479265/group8.csv)
<img width="1264" alt="Screenshot 2023-11-27 at 2 12 04 PM" src="https://github.com/jasp-stats/jasp-issues/assets/39278273/9ff865e1-1112-4aec-8761-df6c7f5f85b7">

### Expected Behaviour

A Bayesian analysis appearing in the results screen comparing the specified model with the null or encompassing model.

### Steps to Reproduce

1. Loaded data 
2. Selected frequencies --> Informed multinomial
3. Put the variable throw in as a factor. 
4. Entered the model (see above). 
5. Pressed cmd-return. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @mumair01 Strange, I cannot reproduce it with the same version. Could you also send us the log files (https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/user-guide/logging-howto.md)
We are also about to release the 0.18.2 version. Maybe you can try the beta version: https://static.jasp-stats.org/Nightlies/macOS-arm64/JASP-nightly-development-b38ff15729ce819b063ee4d88e91d98b2410718a.dmg

**Comment by FBartos** [comment]
I heard that @JohnnyDoorn is the only person with M2 Mac. Could you take a look please?

**Comment by JohnnyDoorn** [comment]
I'm still getting a crashed engine with https://static.jasp-stats.org/Nightlies/macOS-arm64/JASP-nightly-development-b38ff15729ce819b063ee4d88e91d98b2410718a.dmg

**Comment by boutinb** [comment]
I think this is solved in 0.18.2. I cannot reproduce it.
Reopen it if you have still a problem
