### ISSUE TITLE
[Bug]: Linear regression gives an error with aliased coefficients

### ISSUE THREAD

**Issue by Alexa202324** [jasp-stats/jasp-issues#2442]
### JASP Version

0.18.1

### JASP Module

Regression

### What analysis are you seeing the problem on?

Classical Linear Regression

### What OS are you seeing the problem on?

Windows 11

### Bug Description

This analysis terminated unexpectedly.

Error in vif.default(fit): there are aliased coefficients in the model

Stack trace
analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.linregCreateCoefficientsTable(modelContainer, model, dataset, options, position = 3)

.linregFillCoefficientsTable(coeffTable, model, dataset, options)

.linregGetCoefficients(model[[i]]$fit, model[[i]]$predictors, dataset, options)

.linregGetVIFAndTolerance(fit)

car::vif(fit)

vif.lm(fit)

NextMethod()

vif.default(fit)

stop('there are aliased coefficients in the model')

### Expected Behaviour

Should fill tables with data from IVs and DVs

### Steps to Reproduce

1. put DV into DV
2. put 3 IVs into Factors
3. error message

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by Alexa202324** [comment]
> @Alexa202324, thanks for taking the time to create this issue. If possible (and applicable), please upload to the issue website (#2442) a screenshot showcasing the problem, and/or a compressed (zipped) .jasp file or the data file that causes the issue. If you would prefer not to make your data publicly available, you can send your file(s) directly to us, [issues@jasp-stats.org](mailto:issues@jasp-stats.org)

![image](https://github.com/jasp-stats/jasp-issues/assets/152224303/f9f10650-8671-4e6a-845f-2eb325a1ac5e)

**Comment by Kucharssim** [comment]
Dear @Alexa202324,

typically, 'aliased coefficients' mean that some of your predictors are perfectly correlated and as a result one or more predictors are completely redundant. This causes the multicollinearity diagnostics (i.e., the VIF) to give this error message.

If this is not the case in your data, could you please share it with us so that we can take a look what goes wrong otherwise? Thank you.

**Comment by Alexa202324** [comment]
> Dear @Alexa202324,
> 
> typically, 'aliased coefficients' mean that some of your predictors are perfectly correlated and as a result one or more predictors are completely redundant. This causes the multicollinearity diagnostics (i.e., the VIF) to give this error message.
> 
> If this is not the case in your data, could you please share it with us so that we can take a look what goes wrong otherwise? Thank you.

I'm not sure how possible it is for that to have happened as it was randomised scores for various scales to simulate a data collection. Is there a way to send it securely?

**Comment by Kucharssim** [comment]
>  Is there a way to send it securely?

If you would prefer not to make your data publicly available, you can send your file(s) directly to us, [issues@jasp-stats.org](mailto:issues@jasp-stats.org)

**Comment by tomtomme** [comment]
@Alexa202324 
I hope you could resolve this. Please reopen if you have further details.
