### ISSUE TITLE
[Feature Request - Quality Control] Add specification limits to x-mR chart in process capability study

### ISSUE THREAD

**Issue by obwolfe** [jasp-stats/jasp-issues#2443]
### Description

Add Process Specification Limits (USL and LSL) to Control Chart Dialog box and Charts

### Purpose

Inclusion of USL and LSL to Control Charts helps with communication to shop floor staff and managment to sh

### Use-case

Show visually capability of process relative to USL and LSL

### Is your feature request related to a problem?

While the USL and LSL are included in the Process Capability screen, it is missing in the X-mR chart

### Is your feature request related to a JASP module?

Quality Control

### Describe the solution you would like

For the X-mR analysis, add USL and LSL fields to dialog (same as Capability Study) and add the USL and LSL llines to the control charts

### Describe alternatives that you have considered

Since, USL and LSL are in the Capabiulity Study dialog, just add the USL and LSL lines to the Capability Study Charts

### Additional context

The quality Control Module has a lot of promise, but needs some more development work to be practical for ongoing production SPC.

Please keep up the good work.  I look forward to further development of the QC module.

**Comment by KlerxRene** [comment]
Dear @obwolfe,

As we always teach in our Green/Black Belt classes: never ever put specification limits on (subgroup) control charts, you cannot compare apples (subgrouups) with oranges (individuals). Subgroups are used for control charts and control limits. Individuals have specification limits. In order to compare your performance with customer requirements, please use the performance indices (Pp and Ppk) and compare these to the acceptance criteria of your customer.

**Comment by obwolfe** [comment]
I recognize and understand the mixing of individual and subgroup averages in not correct.  That is why I referenced adding USL & LSL to X-mR charts.  If there is no interest in adding this feature, there are other software packages with quality control features that I can direct my clients to use.  The following is only one example that I found:
https://www.qimacros.com/control-chart/xmr-target-chart/

Thank you for your time and consideration of my feature request.

**Comment by JTPetter** [comment]
@obwolfe Thanks for clarifying and sharing an example. I agree that this should be included as an option. Note that the upcoming version 0.18.2 includes a lot of upgrades to the control charts sub-module. The version after this will then include updates to the Process Capability Studies and I will aim to include your feature until then. I think we are looking at Q1 2024 for the version that includes the Process Capability updates.

**Comment by KlerxRene** [comment]
@obwolfe 
Probably I did not read your request to the full extent.
Yes, the X-mR control chart is the only exception for which you may add specification limits to the chart. In that case individuals are compared with individuals.
@Jonas thanks for adding this option for the X-mR control chart in JASP 0.18.2, I look forward to the new features you developed.

**Comment by KlerxRene** [comment]
@obwolfe
Is it possible to communicate directly, please send an e-mail to Rene.Klerx@gmail.com

**Comment by AbraMath** [comment]
First of all, I want to thank you and the JASP team for the excellent work that you do!! :) 

May I suggest a couple of additions that could benefit industrial SPC use?
  - A toggle button to check for SPC rules (or not). 
  - Some users might rather like to use the Western Electric Rules (8 rules as found in ASTM E2587) to check for shift in process levels. An option to toggle the user's choice of SPC rules would be appreciated.

**Comment by JTPetter** [comment]
@AbraMath Thank you! I agree that your suggestions do indeed sound useful, I will implement them.

**Comment by AbraMath** [comment]
That's great to hear that you think these are worthwhile additions! Can't wait to use them! Thank you
