### ISSUE TITLE
Copy/Paste from Excel to JASP not working 

### ISSUE THREAD

**Issue by Franck6S** [jasp-stats/jasp-issues#2445]
### JASP Version

0.18.1

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

All analysis / Data editing

### What OS are you seeing the problem on?

Windows 10

### Bug Description

When try to paste data from Excel in JASP. action not performed. not the ability to paste a board with several columns  Working with one column only. Then it generates a "blank cell" at the end of the column that generate error when performing an analysis.

### Expected Behaviour

Willing to get back same functionality as 0.17.2.1 version with "header paste" enabling to switch data from Excel to JASP in one go.

### Steps to Reproduce

1.Copy dataset in Excel
2. in Data editing mode : Paste dataset in JASP
3.If Board of several column. Not working, if column per colmumn then pasting with one empty cell at the end.
![CopyPaste issue](https://github.com/jasp-stats/jasp-issues/assets/152309774/37a4c8aa-b3b2-4492-90ec-f89721e82d18)

...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
This will be possible in the next version that will be released soon. For the time being you can try the beta version: https://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-matrixFix-19ecfd1cccce352c47dcbf7e1109e9d3f7f1bc4b.msi

You will have to paste on the column header if you want to ensure that the first row is a column name.
