### ISSUE TITLE
Reading old file JASP Version 

### ISSUE THREAD

**Issue by Franck6S** [jasp-stats/jasp-issues#2446]
### JASP Version

0.18.1

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

Quality Control Module file analysis

### What OS are you seeing the problem on?

Windows 10

### Bug Description

When trying to open old JASP Version files, It genarate ever an error lmessage and open finally or stays stuck with error message
![error opening JASP old version](https://github.com/jasp-stats/jasp-issues/assets/152309774/574f15ab-a0cb-4380-a2a3-a4969a678ba6)

### Expected Behaviour

Haviong compatibility from old JASP files when opening with new version

### Steps to Reproduce

1.Opening JASP File on directory
2.Error message
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by shun2wang** [comment]
Hi @Franck6S thanks for your report. could you add a jasp file in the comment with that problem? it will help us(you) to find out the issue.

with thanks.

**Comment by boutinb** [comment]
I think this is related to https://github.com/jasp-stats/jasp-issues/issues/2428
Can you try this beta version https://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-matrixFix-19ecfd1cccce352c47dcbf7e1109e9d3f7f1bc4b.msi

**Comment by shun2wang** [comment]
@Franck6S thanks! and you can zip the jasp files and then attached to comments.
