### ISSUE TITLE
[Bug]:Invalid type error in homogeneityCorrection options: 'x 'x' y'

### ISSUE THREAD

**Issue by MoeOkuma** [jasp-stats/jasp-issues#2447]
### JASP Version

0.17.1

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

Repeated Measures ANOVA

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

t may be more of my own problem than JASP's; however, I would appreciate your help in resolving it.

A two-factor repeated analysis of variance is performed. The first factor is a between-participants factor with 3 levels, and the second is a within-participants factor with 2 levels. Since we found an interaction effect, we want to test for a simple main effect. However, I encountered an unexpected termination in the analysis. It is the error message from JASP:

Error in options$homogeneityCorrectionBrown || options$homogeneityCorrectionWelch: invalid 'x' type in 'x || y'.

Stack trace:

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports (see attached image).

<img width="1527" alt="スクリーンショット 2023-11-29 16 27 47" src="https://github.com/jasp-stats/jasp-issues/assets/152373735/1c8cf149-9ada-41f4-8fd1-f2357ec11990">

### Expected Behaviour

<img width="1527" alt="スクリーンショット 2023-11-29 16 41 12" src="https://github.com/jasp-stats/jasp-issues/assets/152373735/2fc58c6b-eb1d-4228-ba6b-0a2405ed1da3">
When repeated measures factor 1 is set as simple effect factor and between-participant factor is set as moderator factor 1, no error is produced.

However, when repeated measures factor 1 is set as moderator factor 1 and between-participant factor is set as simple effect factor, an error is produced.

### Steps to Reproduce

<img width="1680" alt="スクリーンショット 2023-11-29 17 01 19" src="https://github.com/jasp-stats/jasp-issues/assets/152373735/a89cd4cf-1a19-405f-80e0-710c6575aedf">
<img width="1680" alt="スクリーンショット 2023-11-29 17 01 13" src="https://github.com/jasp-stats/jasp-issues/assets/152373735/747a86dd-dab8-4837-9f43-620a35af7c4e">

1. Set the repeated measures factors based on the data in my data file.
2. Match the information from step 1 with the details in the repeated measures cell.
3. Enter the information for the between-participants factor into the corresponding field.
4. Confirm the presence of a significant difference in the interaction.
5. Proceed to test the simple main effect.
6. Select the cell for the Between-Participants factor in the Simple Effects Factor section and the cell for Repeated Measures Factor 1 in the Moderator Factor 1.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [x] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by MoeOkuma** [comment]
Dear JASP team,

Hello, my name is Moe Okuma. I have just reported the bug through Github,
and I will send you the data that is causing the bug via JASP.

Please let me know if there is any additional information I can provide to
help solve the problem.

Best regards,
Moe Okuma

2023年11月29日(水) 17:09 github-actions[bot] ***@***.***>:

**Comment by JohnnyDoorn** [comment]
I think this is fixed in the latest release since I cannot replicate this with a similar data set. Please reopen (and please include a jasp or data file so I can investigate the issue more closely).
