### ISSUE TITLE
Feature request: Reporting sample size in correlation matrices (and factor analyses)

### ISSUE THREAD

**Issue by hsorlie** [jasp-stats/jasp-issues#245]
* Enhancement: ...for both frequentist and bayesian correlation matrices. The output would need to look different depending on whether you were using listwise or pairwise exclusion, I suppose.
* Purpose: This is something you are almost always expected to report in a paper, when presenting a correlation matrix (or any factor analysis).

Thanks again!

**Comment by bellhaeuser** [comment]
This is really urgent! Without information about the sample size, correlations can't be interpreted correctly. Please implement this ASAP! I am using JASP in my class of teacher students and I really hope that you can fix this within the next 6 months before my next class will need JASP...

**Comment by EJWagenmakers** [comment]
This should be an easy fix; in the attached matrix plot, whenever "Statistics" is ticked, above the "r = " line, there can be an "n = " line. Now personally I don't think this is crucial, as the CI will reflect the impact of n. So if we report r, n, and the CI, then one of the three is redundant. However, I do believe that people would find it useful. @TimKDJ @koenderks ?

![image](https://user-images.githubusercontent.com/8603015/52273914-83152d80-294b-11e9-83b3-80ae06025005.png)

**Comment by EJWagenmakers** [comment]
of course it is prettiest to replace the "r = " line with an "n=" line and shift everything down one line, instead of adding one on top...

**Comment by TDJorgensen** [comment]
Thank you for addressing this issue!  I am currently teaching a course using JASP, and students have already noticed they cannot infer the *N* for the correlation because there is some missing data on both variables (not completely overlapping, so not immediately inferred from univariate Valid sample sizes). 

Not to rush your progress, but is there any news available about when the next version of JASP will be released?

**Comment by EJWagenmakers** [comment]
Has this now been addressed?

**Comment by boutinb** [comment]
@Kucharssim Did you add this issue in your rewrite?

**Comment by Kucharssim** [comment]
Yes, it's implemented
