### ISSUE TITLE
[Bug]: Merge Stat Learning Modules

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#2450]
### JASP Version

0.18.1

### JASP Module

Learn Bayes, Other

### What analysis are you seeing the problem on?

Learn Stats & Learn Bayes

### What OS are you seeing the problem on?

Other

### Bug Description

![image](https://github.com/jasp-stats/jasp-issues/assets/4428185/ddc6aba0-495d-4ade-a030-43077edf5891)

Most JASP modules have a Classical & a Bayesian section. But the Learn Stats Modules are separate. This seems inconsistent.

### Expected Behaviour

Merge both modules into one with the usual separator for Classical and Bayesian.

### Steps to Reproduce

1.
2. 
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Also: The classical "Learn Stats" module is missing from the github-drop-down menu.

**Comment by EJWagenmakers** [comment]
The GitHub issue is for the team, for instance @JorisGoosen . Wrt the combination into a single module: I get your argument, but (1) there isn't a clear mapping from one set of demo's to the other; (2) some demo's in Learn Stat are generic and apply equally well to both paradigms. Ideally the organization would be in three parts (generic, frequentist, Bayesian), but even then argument 1 would hold, and the module would be a little big too. So I prefer it as is, for now at least. :-) After we hsve looked at the GitHib issue, this can be closed for now.

**Comment by JorisGoosen** [comment]
Ill add some stuff to the issue templates
