### ISSUE TITLE
[Feature Request]: Sub-grouping data

### ISSUE THREAD

**Issue by zooeyjfp** [jasp-stats/jasp-issues#2452]
### Description

In the Edit Data section, be able so sort by a variable and turn cases on or off. Or otherwise be able to work with sub-groups.

### Purpose

Be able to work with subgroups of data. For instance run regressions for sub-groups.

### Use-case

I am looking at the relation of wind turbine perception to distance. I would like to separate whether the turbine blade, nacelle or whole blade sweep are visible.

### Is your feature request related to a problem?

No

### Describe the solution you would like

Sort data and turn cases on or off. Or have a subgroup command for all analyses.

### Describe alternatives that you have considered

Do data processing in Excel and creating Creating separate databases.

### Additional context

The addition of the edit module has been helpful. I would like more features. Though I recognize that it may be more important to work on additional analysis sections.

**Comment by tomtomme** [comment]
@zooeyjfp 
Sorting is discussed / requested here:
https://github.com/jasp-stats/jasp-issues/issues/2247
https://github.com/jasp-stats/jasp-issues/issues/2409
Lets discuss there

Turn groups on of can already be done via filtering
https://jasp-stats.org/2018/06/27/how-to-filter-your-data-in-jasp/

So do you agree, that we can close this one as a duplicate?

**Comment by zooeyjfp** [comment]
Yes, my request appears to be a duplicate.
