### ISSUE TITLE
[Bug]: Error in .extractErrorMessage(e): length(error) = 1 is not TRUE

### ISSUE THREAD

**Issue by giovanniconstantin** [jasp-stats/jasp-issues#2453]
### JASP Version

0.17.1

### JASP Module

Network

### What analysis are you seeing the problem on?

Network Analysis

### What OS are you seeing the problem on?

Windows 11

### Bug Description

Hello! I was trying to contact a simple network analysis and this message appeared:
This analysis terminated unexpectedly.

Error in .extractErrorMessage(e): length(error) = 1 is not TRUE

Stack trace
.networkAnalysisRun(mainContainer, dataset, options)

tryCatch(networkList[['network']] <- .networkAnalysisComputeNetworks(options, dataset), mgmError = function(e) {
    mainContainer[['generalTable']]$addFootnote(e[['message']])
}, error = function(e) {
    mainContainer$setError(.networkAnalysisCheckKnownErrors(e))
})

tryCatchList(expr, classes, parentenv, handlers)

tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), names[nh], parentenv, handlers[[nh]])

value[[3]](cond)

mainContainer$setError(.networkAnalysisCheckKnownErrors(e))

private$jaspObject$setError(x)

.networkAnalysisCheckKnownErrors(e)

.extractErrorMessage(e)

stopifnot(length(error) = 1)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

Have in mind that I tried to change the estimator but also other error messages appeared similar to that. 

### Expected Behaviour

The program should contact normally the simple network analysis as it does in similar cases, without having any issues. Its not the only data series that I imported to JASP and till now everything was fine.

### Steps to Reproduce

1. Change the estimator
2. 
![image](https://github.com/jasp-stats/jasp-issues/assets/152813024/89ceaa4f-3052-4ca0-9b8d-feba98af5526)

3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @giovanniconstantin, 0.17.1 is already quite old. Could you try the newest JASP version: https://jasp-stats.org/download/ ?

**Comment by tomtomme** [comment]
@giovanniconstantin 
I hope you could resolve this. Please reopen if not.
