### ISSUE TITLE
[Feature Request]: Fix faulty normality assessments when there multiple groups.

### ISSUE THREAD

**Issue by R180** [jasp-stats/jasp-issues#2454]
### Description

When there are multiple groups--such as with an independent-samples t test or an ANOVA--neither the Shapiro-Wilk normality test nor the QQ plot appears to properly account for unequal variances across groups. Specifically, normal distributions are mis-identified as non-normal when there variances are unequal. Thus, the normality assessments are, in part, assessing unequal variance.  This fault goes away if the normality assessment is done on scores that have been standardized within groups. So my suggestion is that jamovi's normality tests and assessments be modified so that they're run on Z scores.

### Describe the solution you would like

When multiple groups are involved, convert scores to per-group Z scores prior to computing Shapiro-Wilk or QQ plots.

### Additional context

[Faulty normality assessments when there multiple groups.zip](https://github.com/jasp-stats/jasp-issues/files/13541236/Faulty.normality.assessments.when.there.multiple.groups.zip)

**Comment by EJWagenmakers** [comment]
A suggestion for the Scottish program I assume...
