### ISSUE TITLE
[Bug]: JASP crashes when opening an .ods file with Cyrillic characters in the file name

### ISSUE THREAD

**Issue by AlexanderPdb** [jasp-stats/jasp-issues#2456]
### JASP Version

0.18.1

### JASP Module

Other

### What analysis are you seeing the problem on?

I tried to open a file (ods)

### What OS are you seeing the problem on?

Windows 10

### Bug Description

JASP crashes when I try to open a file whose filename or file path contains Cyrillic characters (ods). 
Previously I was using version 0.16.4 and there were no such problems there (But I used the LC_CTYPE setting)

### Expected Behaviour

JASP opens a file of type ods, which may contain Cyrillic characters in the file name or file path, and processes data from it normally.

### Steps to Reproduce

1. Create ods file with Cyrillic characters in the file name or file path (or use attached)
2. Run JASP 0.18.1
3. Open file via Main menu -> Open -> Computer
4. JASP crashes

### Log (if any)

[Книга1.ods](https://github.com/jasp-stats/jasp-issues/files/13545593/1.ods)
[JASP 2023-12-04 14_40_41 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/13545564/JASP.2023-12-04.14_40_41.Desktop.log)
[JASP 2023-12-04 14_40_41 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/13545565/JASP.2023-12-04.14_40_41.Engine.0.log)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JorisGoosen** [comment]
@AlexanderPdb what language settings does your pc have?

In "Region":
<img width="428" alt="image" src="https://github.com/jasp-stats/jasp-issues/assets/29062713/b09059f3-53e3-48e1-8d1e-d823c4511330">

And then when you click "change system locale":
<img width="414" alt="image" src="https://github.com/jasp-stats/jasp-issues/assets/29062713/a322011b-9113-4059-b5e2-43177f58e0e2">

I have the checkbox turned on (and it would solve your bug probably) but JASP also ought to work when the setting is off. In theory.

But it depends on whether your computer is set up in a proper cyrillic locale or not.
When I download your file from github the cyrillic characters have been stripped though.

**Comment by JorisGoosen** [comment]
Nvm, I can reproduce this on a windows 10 machine.

**Comment by JorisGoosen** [comment]
@RensDofferhoff this issue

**Comment by JorisGoosen** [comment]
Something might have been off the first time I tested as I cannot reproduce this at all anymore.
Neither can Rens.

@AlexanderPdb you have seen this problem more afterwards or was this a one time thing?

**Comment by tomtomme** [comment]
@JorisGoosen 
This works fine on linux / flatpak with current 0.19 beta and 0.18.3 stable
