### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Marcosport88** [jasp-stats/jasp-issues#2461]
### JASP Version

0.18.1

### JASP Module

Machine Learning

### What analysis are you seeing the problem on?

Prediction

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

I have followed the procedure to run a Prediction (Moaded Model: Regression).

I have imported my trained model and I have added the Features needed for the model. When I add all three Features, the analysis is not run and an error message appears. 
![Screenshot 2023-12-06 at 15 32 23](https://github.com/jasp-stats/jasp-issues/assets/153033287/c7b1323a-0a5d-467f-a41d-a6795d3072f2)
![Screenshot 2023-12-06 at 15 28 04](https://github.com/jasp-stats/jasp-issues/assets/153033287/5e38fbea-376c-49f4-822d-f4e663437c4d)

### Expected Behaviour

Instead of that, the software should finish running the Prediction using the new dataset and the predicted model I imported. 

### Steps to Reproduce

1. The bug appears every time I run this analysis. 
2.
3.
...

### Log (if any)

[Files.zip](https://github.com/jasp-stats/jasp-issues/files/13588133/Files.zip)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by koenderks** [comment]
You can resolve this issue by removing all the spaces and underscores from the variable names. This is a known issue and in the next version there will be a warning displayed when the variable names have spaces or underscores. Let me know if that helps!

**Comment by koenderks** [comment]
There is no screenshot attached to your post. Could you attach? Make sure that you have re-trained the model, in this data set the variable names should also be renamed to remove. Then predict using the new data, which also has the new variable names.

**Comment by koenderks** [comment]
Hi Marco,

Good to hear! It depends on whether you are doing regression or classification. For regression I would calculate the correlation between the predictions and the actual values via the correlation analysis in the regression module. For classification you can make a table of the actual labels versus the predicted labels via the contingency tables analysis in the Frequencies module. Does that help?

**Comment by Marcosport88** [comment]
Yes, this is great. So, since I am doing a regression analysis, do I need to do a simple correlation between the two variables (true values vs estimated) and see how they fit?
The last question: if I want to retrain the original model, do I need only to add the new data to the old file (increasing the sample)? In a few words, every time that I have some new data, I will need to add them to the original file and retrain the model. 

from online: "the model can then be retrained using all available data and applied to a new data set"

**Comment by koenderks** [comment]
Yes you can retrain the model by simply adding data to the data file. Also, the correlation can give you an idea about how close the predictions are, but you can test this in multiple ways. For instance, you could also perform a paired samples t test testing if the average difference is 0. That is kinda up to you, but correlation is usually intuitive. Good luck!

**Comment by Marcosport88** [comment]
thank you very much for your help!
regards
