### ISSUE TITLE
[Bug]: Editing (inserting) columns confuses SEM module

### ISSUE THREAD

**Issue by patc3** [jasp-stats/jasp-issues#2462]
### JASP Version

0.18.1

### JASP Module

SEM

### What analysis are you seeing the problem on?

Structural Equation Modeling

### What OS are you seeing the problem on?

Windows 10

### Bug Description

See GIF. An SEM analysis seems to keep its own record of columns when the analysis is created, without updating itself when you edit the data (using the new Edit data panel). For example here I run a simple regression y~x, then I go in Edit data and insert a new column between x and y, and the analysis no longer matches the syntax (x has been changed for the new column that's now in its column index in the dataframe)

![bug_SEM_insert_column2](https://github.com/jasp-stats/jasp-issues/assets/41131893/a50ea1d8-7bb8-467f-b4d8-0e3d2f2243fd)

### Expected Behaviour

The analysis should match the model syntax at all times, even when you insert or remove columns that are not included in the syntax. Here my model syntax was y\~x, but after inserting a column between y and x through Edit data, the analysis became y\~new_column (because the new column was inserted at the same place that x used to be).

### Steps to Reproduce

1. go to SEM > Structural Equation Modeling
2. run some model syntax, e.g. y~x
3. go in Edit data
4. insert a new column between some variables that are included in the model syntax

The new analysis will be using wrong variables even though the model syntax didn't change.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment]
I think this is due to how the textArea is defined for the SEM module and thus how the columns from the data set are defined. I can work around this, but maybe @boutinb can take a look.

**Comment by patc3** [comment]
In case it helps: duplicating the analysis also duplicates the problem (the new duplicated analysis doesn't have the correct matching between variable names and columns), but making a new SEM analysis correctly updates the variables available in the data. It's as if a list of columns based on indexes is created when the analysis is created, and is never updated thereafter.

**Comment by boutinb** [comment]
Good catch!
@JorisGoosen I see that when you add a column, the column encoder mapping is not updated... I'm not sure how it should work.

**Comment by boutinb** [comment]
You can reproduce this problem, even by adding first a column (after y1), and then adding a SEM analysis with y1 ~ y3: you will see y1 and y2 in the results...

![columnEncoderIssue](https://github.com/jasp-stats/jasp-issues/assets/503332/2d8e3d5d-ee05-4705-8412-a61c3110448b)

**Comment by JorisGoosen** [comment]
Should I fix this/ work on this?

**Comment by juliuspfadt** [comment]
If you can, yes :)
