### ISSUE TITLE
[ANOVA] Feature request: run ANOVA like the t-test (specify multiple DVs in the box)

### ISSUE THREAD

**Issue by zazaven** [jasp-stats/jasp-issues#2463]
### Description

Anova 

### Purpose

execute ANOVA more easy way

### Is your feature request related to a JASP module?

ANOVA

### Describe the solution you would like

I want to apply ANOVA with alot of dependent variables

**Comment by zazaven** [comment]
I have shown that is it possible to calculate multiple dependent variables
with fixed one  in ANOVA like spss
Thank you
Sincerely
Dr.Sabahattin Bor

**Comment by JohnnyDoorn** [comment]
Do you mean the MANOVA? That one is available in JASP in the ANOVA module (4th item in the submenu):
<img width="1429" alt="image" src="https://github.com/jasp-stats/jasp-issues/assets/15704203/b4b7d26d-9084-4265-86d1-ba19c221441f">

**Comment by zazaven** [comment]
I didnt mean MANOVA  ı am sending an example pic in SPSS

Johnny van Doorn ***@***.***>, 11 Ara 2023 Pzt, 17:58
tarihinde şunu yazdı:

**Comment by JohnnyDoorn** [comment]
Could you please send it to me by email? I don't see it on Github - my address is j.b.vandoorn <at> uva.nl

**Comment by JohnnyDoorn** [comment]
Just as a note - this request is about easily running many ANOVA's at once by specifying more than 1 DV at a time, like in the independent samples t-test, for instance.

**Comment by tomtomme** [comment]
@zazaven 
With the green + Button you can already easily run many ANOVAs. Specify all IVs and options once, then duplicate the analyis with the green + and only replace the DVs.
Is this a sufficient workaround in the meantime?

@JohnnyDoorn 
Is this an easy addition that you want to include or do we want to stick to the +button solution.

**Comment by EJWagenmakers** [comment]
I am leaning toward keeping the interface simple
