### ISSUE TITLE
the app is not efficiently working [Bug]: 

### ISSUE THREAD

**Issue by 12amna** [jasp-stats/jasp-issues#2464]
### JASP Version

0.18.2

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

on the descriptive data 

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

this message pops up every time I try using the app

### Expected Behaviour

not to get damage and to work efficiently 

### Steps to Reproduce

1.
2.
3.
...

### Log (if any)

![7F719194-F158-40D4-9AB8-5F1D135653E0](https://github.com/jasp-stats/jasp-issues/assets/153398614/154f259d-9935-4214-ada5-2bd00b8d2e89)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JorisGoosen** [comment]
We did not release 0.18.2 yet so how are you using it?
