### ISSUE TITLE
[Bug]: Cannot open saved JASP file with 18.2 portable nightly

### ISSUE THREAD

**Issue by patc3** [jasp-stats/jasp-issues#2468]
### JASP Version

0.18.2

### Commit ID

867fc558388c3745bf3fffe8cf30426b0f6e3833

### JASP Module

Other

### What analysis are you seeing the problem on?

Process

### What OS are you seeing the problem on?

Windows 10

### Bug Description

See GIF. Running the Process (beta) module works fine, but saving a file with it in it makes JASP crash when opening the file (Windows 10, tried on two different computers with the two most recent nightlies)
![process_shuts_off](https://github.com/jasp-stats/jasp-issues/assets/41131893/c4968102-bc18-4613-b303-dd8a754cbedd)

### Expected Behaviour

Opening JASP file shouldn't crash JASP

### Steps to Reproduce

1. run process analysis
2. save JASP file
3. open JASP file

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by patc3** [comment]
Actually, I'm not convinced this is related to Process, as I just tried the same thing but with a correlation analysis, and JASP crashes too... I have JASP 18.1 installed, and this is 18.2 portable version. It just looks like I can't open any JASP file created using this 18.2 portable version. (I also can't open it with JASP 18.1, as it says the file version is newer)

Sorry if I jumped the gun by blaming Process, also let me know if it's got to do with my having JASP 18.1 installed along with the 18.2 portable version

**Comment by boutinb** [comment]
There was a bug made with a version control... It will be solved with https://github.com/jasp-stats/jasp-desktop/pull/5347

**Comment by patc3** [comment]
You're right, it works now. Thanks a lot
