### ISSUE TITLE
[Bug]: Process: Renaming model erases input

### ISSUE THREAD

**Issue by patc3** [jasp-stats/jasp-issues#2469]
### JASP Version

0.18.2

### Commit ID

867fc558388c3745bf3fffe8cf30426b0f6e3833

### JASP Module

Other

### What analysis are you seeing the problem on?

Process

### What OS are you seeing the problem on?

Windows 10

### Bug Description

See GIF. Renaming a model in Process erases the input of that model.
![process_renaming_erases_model](https://github.com/jasp-stats/jasp-issues/assets/41131893/9cdc10aa-e705-4219-8a65-86534e41dd04)

### Expected Behaviour

Input shouldn't change, renaming should only change the name of the model. The rest of the UI in the analysis tab shouldn't change.

### Steps to Reproduce

1. add Process analysis
2. add a line using "variable" as input type
3. rename model

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Could you re-test with the current beta?
https://apps.microsoft.com/detail/9P08CWG12JNL?hl=de-de&gl=US

Thx!

**Comment by patc3** [comment]
Looks like it's fixed, but:
1) there's some optimizing to be done, as changing the name of the model re-runs the whole model
2) the old model still shows in plots and parameter estimates:

![image](https://github.com/jasp-stats/jasp-issues/assets/41131893/29d8e765-8632-4a89-90b5-e99364ac63d4)

![image](https://github.com/jasp-stats/jasp-issues/assets/41131893/1731a8e9-0506-438e-b8b3-0972796079b8)

![image](https://github.com/jasp-stats/jasp-issues/assets/41131893/1734bbf4-4dc7-44e5-9aba-d1e9767ae333)

![image](https://github.com/jasp-stats/jasp-issues/assets/41131893/d3a660ba-f4f6-4940-9167-7755f51fd22f)

**Comment by maltelueken** [comment]
I fixed the second in the PR. The first point about rerunning the model seems to be a general issue (also occurs for SEM), so I can't fix it in the module I think.
