### ISSUE TITLE
[Bug]: JASP NO FUNCIONA

### ISSUE THREAD

**Issue by smgggggggg** [jasp-stats/jasp-issues#2470]
### JASP Version

0.18.1

### JASP Module

Descriptives

### What analysis are you seeing the problem on?

JASP

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

La aplicación de JASP no me funciona y la necesito

### Expected Behaviour

<img width="1224" alt="Captura de Pantalla 2023-12-14 a les 10 26 50" src="https://github.com/jasp-stats/jasp-issues/assets/153815208/2fab374d-3331-4ae2-8569-772846e6b1f7">

### Steps to Reproduce

1. No funciona
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @smgggggggg , this is quite annoying, but without log I cannot guess what would be the problem. One possibiity is that you have chosen the Silicon/ARM installer in place of the Intel one. What is the name of the dmg file you have downloaded. For a Mac Intel, it should be JASP-0.18.1.0-macOS-x86_64_new2.dmg (https://static.jasp-stats.org/JASP-0.18.1.0-macOS-x86_64_new2.dmg)
As we are about to release a new version, maybe you could try also this beta version: https://static.jasp-stats.org/Nightlies/macOS-x86_64/JASP-nightly-development-0d9baf9a5cde7509b86f5d8a31dce41a7b05728e.dmg
