### ISSUE TITLE
[Bug]: (Process) Multiple mediated processes become one

### ISSUE THREAD

**Issue by patc3** [jasp-stats/jasp-issues#2473]
### JASP Version

0.18.2

### Commit ID

da184c66ca802b6787cf20f86300d1ed748e7149

### JASP Module

Other

### What analysis are you seeing the problem on?

Process

### What OS are you seeing the problem on?

Windows 10

### Bug Description

Trying to estimate multiple mediated processes (x1, x2, x3 --> m1 --> y1, y2), but multiple paths get the same label in the lavaan syntax (such that they become the same parameter in the model). Also only one mediation process is given under "Mediation effects".

![image](https://github.com/jasp-stats/jasp-issues/assets/41131893/d4a9ac6f-7368-4213-9c54-9243354b54eb)

![image](https://github.com/jasp-stats/jasp-issues/assets/41131893/13e3a61a-954b-4a53-a414-10679e3cc161)

![image](https://github.com/jasp-stats/jasp-issues/assets/41131893/16372654-9248-4caa-bc4c-0a4ca5ed0fde)

I'm pretty confused by what's going on here (particularly in the bottom table of total effects), but one thing's for sure, the model syntax is missing indirect effects (those for risk.work1 and risk.work2):

```
# -------------------------------------------
# Conditional process model generated by JASP
# -------------------------------------------

collision1.fv ~ c1*risk.general + b1*expo + c3*risk.work1.fv + c5*risk.work2.fv
expo ~ a1*risk.general + a2*risk.work1.fv + a3*risk.work2.fv
collision2.fv ~ c2*risk.general + b2*expo + c4*risk.work1.fv + c6*risk.work2.fv

# Residual covariances
collision1.fv ~~ collision1.fv

# Mediation, indirect, and total effects
risk.general__collision1.fv := c1
risk.general__collision2.fv := c2
risk.general__expo__collision1.fv := a1*b1
risk.general__expo__collision2.fv := a1*b2
tot.general__collision1.fv := c1 + c2 + a1*b1 + a1*b2
tot.general__collision2.fv := c1 + c2 + a1*b1 + a1*b2
tot.general__expo__collision1.fv := c1 + c2 + a1*b1 + a1*b2
tot.general__expo__collision2.fv := c1 + c2 + a1*b1 + a1*b2
totInd.general__collision2.fv := c2 + a1*b1 + a1*b2
totInd.general__expo__collision1.fv := c2 + a1*b1 + a1*b2
totInd.general__expo__collision2.fv := c2 + a1*b1 + a1*b2
```

So here for example we're missing a2\*b1 and a2\*b2, a3\*b1 and a3\*b2.

### Expected Behaviour

I would have expected all specified indirect effects to show up in "Mediation effects" table (as it does for example in the SEM module > Mediation analysis). The missing indirect effects are simply not generated in the lavaan syntax. Also something seems wrong with the total effects table (a bunch of identical rows, where the total effect for a given outcome involves paths affecting _other_ outcomes).

### Steps to Reproduce

1. Process model with variable input
2. add several mediator processes, possibly involving the same variables

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by maltelueken** [comment]
Hi @patc3, thanks for the issue. Would it be possible for you to share the .jasp file that produces the results shown above? If you don't want to share it publicly, you could also send it to me via email.

For the indirect effects, the module currently only looks a the path from the first exogneous variable to the dependent variable. This is because most models test the causal effect of one treatment variable. It would, however, be great indeed to look at all indirect effects at the same time.

There are a few other issues that your analyses brings up:
- The path plots show multiple dependent variables on top of each other
- Total effects should be separate for each dependent variable
- Some variable name splits are done on the unencoded variable names because the prefix `general` shows up in the total effects table which it is not supposed to

**Comment by maltelueken** [comment]
I addressed the three points in separate PRs, perhaps you could check the last (https://github.com/jasp-stats/jaspProcess/pull/72) whether it solves the issue in your data set?

**Comment by patc3** [comment]
Hi Malte, I'm impressed by how fast you made all these major changes...! 

It's definitely closer now, and some models that didn't used to work now work. I found one that sill confuses some of the effects (I'm using PR#72, so I assume the conceptual plot being wrong is expected?):

x1,x2 --> m1 --> y1
x2 --> m1 --> y2

![image](https://github.com/jasp-stats/jasp-issues/assets/41131893/16be9db5-1ef3-406d-aba8-ceccf14de8db)

![image](https://github.com/jasp-stats/jasp-issues/assets/41131893/181a5892-3559-4e69-ad32-e18054ce5530)

I'm assuming PR#70 might fix the labels. So perhaps the only problem here is that a superfluous indirect effect was computed (x1-->m1-->y2), which doesn't add additional parameters to the models so technically not a problem I guess

```
# -------------------------------------------
# Conditional process model generated by JASP
# -------------------------------------------

collision1 ~ c1*risk.general + b1*expo + c2*risk.work1
expo ~ a1*risk.general + a2*risk.work1
collision2 ~ b2*expo + c3*risk.work1

# Residual covariances
collision1 ~~ collision1

# Mediation, indirect, and total effects
risk.general__collision1 := c1
risk.general__expo__collision1 := a1*b1
risk.general__expo__collision2 := a1*b2
risk.work1__collision1 := c2
risk.work1__expo__collision1 := a2*b1
risk.work1__collision2 := c3
risk.work1__expo__collision2 := a2*b2
tot.risk__risk.general__collision1 := c1 + a1*b1
tot.risk__risk.general__expo__collision1 := c1 + a1*b1
tot.risk__risk.general__expo__collision2 := a1*b2
tot.risk__risk.work1__collision1 := c2 + a2*b1
tot.risk__risk.work1__expo__collision1 := c2 + a2*b1
tot.risk__risk.work1__collision2 := c3 + a2*b2
tot.risk__risk.work1__expo__collision2 := c3 + a2*b2
totInd.risk__risk.general__expo__collision1 := a1*b1
totInd.risk__risk.general__expo__collision2 := a1*b2
totInd.risk__risk.work1__expo__collision1 := a2*b1
totInd.risk__risk.work1__expo__collision2 := a2*b2
```

In the lavaan syntax, a1*b2 is not a combination that was requested (e.g. risk.work1__expo__collision2)

**Comment by patc3** [comment]
After more reflection, I've realized it might actually be desirable that the module shows all indirect effects implied by the model as it does now (for example, it affects the computation of total effects, correctly so). So unless you think different, I don't think I see any more problems, I think you've fixed everything.

**Comment by maltelueken** [comment]
I indeed thought it would be nice to get all the indirect effects, so the user doesn't have to specify duplicate paths in the GUI. Thanks a lot for testing this through. It always really helps to get this kind of feedback!

I will close this once the PRs are merged.
