### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by mcoussin** [jasp-stats/jasp-issues#2474]
### Description

Comments

### Purpose

Add comments in the Analysis section

### Is your feature request related to a problem?

No

### Is your feature request related to a JASP module?

Unrelated

### Describe the solution you would like

Create small comment boxes

### Additional context

Dear JASP team,

I'm a teacher who uses JASP with his Masters students. I would like to create some typical JASP analyses for different models (Linear regressions, Clustering...). I'd like to be able to edit the analyses in order to add comments concerning the implementation of the models and their interpretation within JASP. 
I think this could even be useful to the researcher, who could have a brief justification and interpretation of his results in his JASP file, without having to go through another file. 
Maybe I've missed something. But if comments are not implemented, I think it would be a good improvement towards a more complete software. 

Best regards,

**Comment by EJWagenmakers** [comment]
We offer extensive possibilities for annotation, including LaTeX support. For an example see the moving gif here (click on the image to start it): https://jasp-stats.org/how-to-use-jasp/annotations-2/ 
You can also check out the annotated JASP files in the JASP Data Library.
