### ISSUE TITLE
[Bug]: Error loading Process input upon opening JASP file

### ISSUE THREAD

**Issue by patc3** [jasp-stats/jasp-issues#2475]
### JASP Version

0.18.2

### Commit ID

da184c66ca802b6787cf20f86300d1ed748e7149

### JASP Module

Other

### What analysis are you seeing the problem on?

Process

### What OS are you seeing the problem on?

Windows 10

### Bug Description

Saving a JASP file with a Process analysis correctly recovers the output but not the input (when using variable input). See GIF. Either every box shows an error ("unknown [variablename] option in processDependent") or simply empty boxes and empty rows.

![image](https://github.com/jasp-stats/jasp-issues/assets/41131893/bfe54b65-ce5e-41e5-8ef2-71a373729658)

![image](https://github.com/jasp-stats/jasp-issues/assets/41131893/93d99a31-cc84-4a27-b08b-e9b588ce0e25)

![reopen-process](https://github.com/jasp-stats/jasp-issues/assets/41131893/99b8bdba-2b54-4a71-8ecc-2fa87d6f65bd)

### Expected Behaviour

Saving JASP file and re-opening should preserve analysis input in Process module

### Steps to Reproduce

1. create Process analysis using variable input
2. save file
3. re-open file: analysis input is no longer available (sometimes with red boxes indicating errors)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Could you re-test with the current beta?
https://apps.microsoft.com/detail/9P08CWG12JNL?hl=de-de&gl=US

Thx!

**Comment by patc3** [comment]
Looks like it's fixed

**Comment by tomtomme** [comment]
Nice!
Feel free to close this issue then :)
