### ISSUE TITLE
Issue viewing uploaded file to OSF [Bug]: 

### ISSUE THREAD

**Issue by georgelovell** [jasp-stats/jasp-issues#2477]
### JASP Version

0.18.1

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

Repeated Measures ANOVA

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I've a lot of demo files for my students that get uploaded to OSF so they can view them. <https://psyresearch.abertay.ac.uk/CogPracs.html>

The file for "Fast detection of objects" <https://osf.io/jb4h7/> doesn't seem to be viewable on OSF, despite it working ok locally and the same analysis having been used for a number of studies.

### Expected Behaviour

File not viewable on OSF: "This JASP file is corrupt and cannot be viewed. Missing META-INF/MANIFEST.MF"

### Steps to Reproduce

1.Follow the [link.](https://osf.io/7wxnz)
2. View the file on JASP
[ObjectDetectionMeansPerParticipant.zip](https://github.com/jasp-stats/jasp-issues/files/13702329/ObjectDetectionMeansPerParticipant.zip)

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by shun2wang** [comment]
@JorisGoosen @RensDofferhoff I saw you had make an PR for JASP new files version, dose this related?https://github.com/CenterForOpenScience/modular-file-renderer/pull/372

**Comment by RensDofferhoff** [comment]
Yes it is related @JorisGoosen tried to fix the filerender OSF uses for newer jasp files

**Comment by georgelovell** [comment]
p.s. it seems that all the analyses I've updated and pushed to OSF since version version 18 are now not visible on OSF.

Mental Rotation  https://osf.io/jk5ud/
RapidObjectDetection  https://osf.io/jb4h7/
ForgettingCurve_PartRep_Murdoch_1965  https://osf.io/gm7n5/
StroopTask Cogpracs  https://osf.io/b3xwg/
Predicting Coin Tosses  https://osf.io/5vrxk/

I've tried to go back to v17 and earlier but files created in 18 don't seem to be backwardly compatible, so I either have to rebuild each analysis or wait for a repair.

**Comment by RensDofferhoff** [comment]
We have made a PR to resolve this but it has yet to be merged by OSF.
Once that is done it should work again.

**Comment by JorisGoosen** [comment]
So the the thing is, we updated our fileformat but this requires a small change to the OSF filerenderer (aka their website).
But https://github.com/CenterForOpenScience/modular-file-renderer/pull/372 needs to be reviewed and merged by them.

We have no control over this...

**Comment by EJWagenmakers** [comment]
I'll try and pull some strings.

**Comment by georgelovell** [comment]
> I'll try and pull some strings.

No worries, if a solution at the OSF side cascades down at some point then that’s great. 

Easier than recreating the analyses. My own modules don’t run again until September.

Merry Xmas :-)

**Comment by shun2wang** [comment]
Fixed by https://github.com/CenterForOpenScience/modular-file-renderer/pull/372

**Comment by georgelovell** [comment]
That seems to have fixed things, thanks everyone.
