### ISSUE TITLE
[Bug]: ms-gaming overlay link

### ISSUE THREAD

**Issue by DevaGitH** [jasp-stats/jasp-issues#2479]
### JASP Version

0.18.1

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 10

### Bug Description

The package informs me that a new gaming add on will be required whenever I try to upload a new data file. 

### Expected Behaviour

it should have neatly accepted the data file. 

### Steps to Reproduce

1. either the software patch may be provided 
2. OR this requirement may be dropped. 
3.
...

### Log (if any)

![Screenshot 2023-12-19 110853](https://github.com/jasp-stats/jasp-issues/assets/154300214/3ba7eded-2ea6-4a3c-ae9a-21437a0fa961)

this may kindly be addressed 

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
This is a known problem: https://github.com/jasp-stats/jasp-issues/issues/862
You have apparently to disable the Game Bar: https://www.minitool.com/news/ms-gaming-overlay-popup.html

**Comment by boutinb** [comment]
We have made a (beta) version that might fix this issue: could you try this version https://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-fixMsGamingOverlay-1823b6a99d09cc70fd68d9103c9d6f4c8693bf27.msi ? (this version is not signed, so you will get a Windows warning about this).

**Comment by shun2wang** [comment]
Hi @DevaGitH Could you help us/you to have a quick test for beta version above? with thanks.

**Comment by scopsm** [comment]
I also experience this same issue on windows 10 and windows 11

**Comment by shun2wang** [comment]
@DevaGitH so could you also try this beta version?

 https://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-fixMsGamingOverlay-1823b6a99d09cc70fd68d9103c9d6f4c8693bf27.msi ? (this version is not signed, so you will get a Windows warning about this).

**Comment by scopsm** [comment]
When I click the link for beta version, I get the following:
<img width="816" alt="Screenshot 2024-01-22 at 11 49 30" src="https://github.com/jasp-stats/jasp-issues/assets/157131154/adb4f859-0f1f-4779-98c1-9032458dbf93">

**Comment by shun2wang** [comment]
@scopsm Sorry the link was out of date, we will make a new build soon!

@boutinb could you please trigger build now?

**Comment by shun2wang** [comment]
Hi @scopsm here is a new build to test:, can you try it? https://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-fixMsGamingOverlay-1823b6a99d09cc70fd68d9103c9d6f4c8693bf27.msi

thanks!

**Comment by scopsm** [comment]
@shun2wang 
I had 0.18.3 installed on my PC and uninstalled it before applying your new build as that is 0.18.2.
I installed your new build and for the user who installs it, it should turn off the Game Bar, correct?
If so, for that user, he then doesn't get the message in relation to GamingOverlay and Game Bar is off.

A new user logging into the same workstation and running up 0.18.2 does get the GamingOverlay message and GameBar is on for that 2nd user under Settings, Gaming and GameBar

I will confirm on a 2nd PC and see if I get the same behaviour though.

**Comment by shun2wang** [comment]
>I installed your new build and for the user who installs it, it should turn off the Game Bar, correct?

Yes, that's correct.

>A new user logging into the same workstation and running up 0.18.2 does get the GamingOverlay message and GameBar is on for that 2nd user under Settings, Gaming and GameBar

Ah, yes, we just set it for current user who installed it but not for all users(local machine). so that will be same behavior.

Thanks for your testing!

**Comment by shun2wang** [comment]
Hi @scopsm , here is a new build for testing : https://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-fixMsGamingOverlay-9f37ad9c034dc2ea7bc6ba7e65280479c7b83438.msi

can you help to test if it works for multiple users or with administrator permission. with thanks!

**Comment by scopsm** [comment]
@shun2wang ok, is that 0.18.2 or 0.18.3 version?

**Comment by shun2wang** [comment]
ah that's still based on 0.18.2, but you need to uninstall installed JASP now and restart the PC, and then install this build and restart it again to test. after test you can install 0.18.3 stable back.

if it works, the fix will be included next stable release.

**Comment by scopsm** [comment]
@shun2wang
I have downloaded and installed the latest msi and I don't get the same message about msgaming overlay now (when logged in with different accounts on the same PC).

So your new MSI turns off gaming mode for all users of the PC?

**Comment by scopsm** [comment]
@shun2wang Turns off GameBar I mean for all users of the PC

**Comment by shun2wang** [comment]
Yes exactly!

**Comment by boutinb** [comment]
Great! Thanks @shun2wang !
