### ISSUE TITLE
Dichotomous Covariates in Meta Analysis

### ISSUE THREAD

**Issue by christopherhillcsusb** [jasp-stats/jasp-issues#248]
I am attempting to run a covariate in the meta analysis function that is dichotomous. I have coded the variables as 0 or 1 in order to obtain an interpretable effect size estimate. I have done this in the past in JASP but it is giving me an error today. I have attached the screen shot for reference.

![screen shot 2018-11-15 at 10 01 48 am](https://user-images.githubusercontent.com/45077137/48572208-a5a02900-e8bd-11e8-9d5c-5c801e5fa87b.png)

![screen shot 2018-11-15 at 10 01 48 am](https://user-images.githubusercontent.com/45077137/48572155-7d182f00-e8bd-11e8-840f-9981e120d272.png)

**Comment by christopherhillcsusb** [comment]
I am using a Mac OS and the file is attached. 
[Meta Analysis Combined Effects.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/2586728/Meta.Analysis.Combined.Effects.jasp.zip)

**Comment by akashrajkn** [comment]
@christopherhillcsusb The analysis is not able to handle the header `Measurement (1 =Device)` which special characters. We'll look into fixing this; for now, you can run the analysis if you change the header names to only include alphanumeric characters. (Attached csv: I renamed the headers)

[meta_analysis_combined_effects.zip](https://github.com/jasp-stats/jasp-issues/files/2586801/meta_analysis_combined_effects.zip)

**Comment by AlexanderLyNL** [comment]
@christopherhillcsusb if you'd like to regress the meta-analysis on a dichotomous variable, please add the variable to the "Factors" box. On the other hand, if you'd like to regress on a continuous variable, then you should add it to the "Covariates" box. 

Cheers,
Alexander

**Comment by akashrajkn** [comment]
Fixed in PullRequest: jasp-stats/jasp-desktop#2932
