### ISSUE TITLE
Unable to save a file after creating

### ISSUE THREAD

**Issue by LoriSap** [jasp-stats/jasp-issues#2482]
### JASP Version

0.18.2

### JASP Module

Quality Control

### What analysis are you seeing the problem on?

Process Capability

### What OS are you seeing the problem on?

Windows 11

### Bug Description

After saving data, it will not reload.

### Expected Behaviour

My saved file should load

### Steps to Reproduce

1.Yes, have tried numerous times
2.Have copy and pasted with same issue
3.Have created new files and saved, will not reload
...

### Log (if any)

Aerospace regulations do not allow sharing of proprietary data

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
You are using 0.18.2 version, but this is a beta version. How old is this version? There were many issues we have solved during the development of 0.18.2, so if you install the last beta version https://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-development-c252d1288d7179b7f890925fb9ca37fa321a268f.msi, this might solve your problem.

**Comment by LoriSap** [comment]
We installed this last Thursday.

Lori Saponaro
Quality Specialist
SKF USA Inc.
20 Industrial Dr.
Hanover, PA.17331
(717)347-5258
***@***.***

**Comment by boutinb** [comment]
Could you send us one file you cannot load (in a zip format). If you don't want to send it in GitHub, you can send it to me via email (b.boutin at uva.nl)

**Comment by LoriSap** [comment]
I will try to mock up a file to send to you .  Aerospace regulations prohibit me sharing actual data.  Give me a little time and I will see what I can do

Lori Saponaro
Quality Specialist
SKF USA Inc.
20 Industrial Dr.
Hanover, PA.17331
(717)347-5258
***@***.***

**Comment by tomtomme** [comment]
Closing then. Please reopen if the issue surfaces again!
