### ISSUE TITLE
[Bug]: This analysis terminated unexpectedly.

### ISSUE THREAD

**Issue by jess20041** [jasp-stats/jasp-issues#2485]
### JASP Version

0.18.2

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

repeated measures anova

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

This analysis terminated unexpectedly.
<img width="893" alt="Screenshot 2023-12-21 at 14 24 57" src="https://github.com/jasp-stats/jasp-issues/assets/154532486/a1c1eac8-12ca-400b-ad8d-aa760085e8ed">

### Expected Behaviour

produse repeated measure anova

### Steps to Reproduce

1.insert factors names 
2. insert between-subjects factors 
3. error appears
...

### Log (if any)

[H1.csv](https://github.com/jasp-stats/jasp-issues/files/13742903/H1.csv)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
If you change the Repeated Measures Factor name to RMGender then it should work. As you have put a variable Gender as Between Subject Factor, then there is a clash between the 2 names.
