### ISSUE TITLE
[Bug]: Equivalence frequentist testing do not build plots, and do not allow for Cohen's d or SMDs, only raw scores

### ISSUE THREAD

**Issue by OscarLecuona** [jasp-stats/jasp-issues#2488]
### JASP Version

0.18.2

### JASP Module

Equivalence T-Tests

### What analysis are you seeing the problem on?

Independent Sample T-test, Paired sample T-test

### What OS are you seeing the problem on?

Windows 10, Windows 11

### Bug Description

Two bugs:
-"Equivalence bounds plot do not show up in any frequentist t-test, error message says "Problem while setting up geom".
![imagen_2023-12-22_141623272](https://github.com/jasp-stats/jasp-issues/assets/37160216/9662aa83-f67a-4c9d-a315-e66499258b76)

-Equivalence tests do not allow for Cohen's d or SMDs, only raw scores. Option "Cohen's d" for bounds gets NAs in the results and the note "argument 'eqbound_type' must be one of 'SMD', 'raw'".
![image](https://github.com/jasp-stats/jasp-issues/assets/37160216/b3138d2d-2a1d-4ddd-8be1-a9e75f190afe)

It seems the package TOSTer might be updated in R and thus create incompatibilities with current JASP?

### Expected Behaviour

- Equivalence bounds plots like the ones found in the tutorial: https://jasp-stats.org/2020/06/02/frequentist-and-bayesian-equivalence-testing-in-jasp/
- Able to specifiy bounds in Cohen's d or SMD.

### Steps to Reproduce

1. open JASP
2. load a database 
3. select "equivalence T-tests" and "independent samples T-test"
4. select a continuous variable in the "Variables box"
5. select a dichotomous variable in "Grouping variable" box
6. select "Equivalence bounds plot"
7. select "bounds specification as: Cohen's d"

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by shun2wang** [comment]
Hi @OscarLecuona I think this was fixed in next release, are you sure you are using our new pre-release? if not, can you try this version: https://github.com/jasp-stats/jasp-desktop/releases/download/v0.18.2.beta/JASP-0.18.2.beta-Windows.msi

**Comment by tomtomme** [comment]
Yes, this is at least fixed for me on manjaro linux with current 0.18.2 beta. So it should also work on windows now. Can we close this issue @OscarLecuona ? Did you try the beta?

**Comment by OscarLecuona** [comment]
Hi all,

I tried this in beta and worked fine. Thanks!
________________________________
De: Thomas Langkamp ***@***.***>
Enviado: sábado, 23 de diciembre de 2023 15:05
Para: jasp-stats/jasp-issues ***@***.***>
Cc: OscarLecuona ***@***.***>; Mention ***@***.***>
Asunto: Re: [jasp-stats/jasp-issues] [Bug]: Equivalence frequentist testing do not build plots, and do not allow for Cohen's d or SMDs, only raw scores (Issue #2488)


Yes, this is at least fixed for me on manjaro linux with current 0.18.2 beta. So it should also work on windows now. Can we close this issue @OscarLecuona<https://github.com/OscarLecuona> ? Did you try the beta?
