### ISSUE TITLE
[Feature Request]: how to install 

### ISSUE THREAD

**Issue by estatistics** [jasp-stats/jasp-issues#2489]
problems to installation guide - update installation guide:
for `linux  debian bookworm 12`

qt6 installation alone from the official guide was not even at close enough to solve errors. 
qtcreator compiling jasp_desktop has many errors hard to solve. 
Go to manual mode of cmake as listed below

```
# some extra 300-500mbs
sudo apt install qt6*dev;    

sudo apt install libgl1-mesa-dev libvulkan-dev libxcb-xinput-dev libxcb-xinerama0-dev libxkbcommon-dev libxkbcommon-x11-dev libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xkb1 libxcb-randr0 libxcb-icccm4;

#libreadstat is explicity asked to be installed otherwise not compiling;
sudo apt install libreadstat* jags;  
```

then add somewhere this code in CMakeLists.txt lets say before project(   JASP
```
set(CMAKE_PREFIX_PATH "/home/user/Qt6.6/Tools/CMake/bin/cmake")
set(ENV{GITHUB_PAT} <mygithubtoken>)
```

then
```
cd jasp_desktop;
mkdir build in jasp_desktop;
cd build;
sudo cmake  -DCMAKE_PREFIX_PATH="/home/user/Qt6.6/6.6.1/gcc_64/lib/cmake"  ../CMakeLists.txt;
sudo make install;
```

# errors

I try now some hours to find a way to install jaspGraphs.
Many problems here. 
Why you dont download it as zip file and then install it locally? 

- [jaspGraphs]: package 'jaspGraphs' is not available

**Comment by tomtomme** [comment]
Try setting up flatpak first:
https://linux.how2shout.com/how-to-enable-flatpak-on-debian-12-or-11-linux/#:~:text=Well%2C%20by%20default%20Flatpak%20will%20not%20be%20there,APT%20package%20manager%20and%20run%20the%20given%20syntax.

then install jasp through flatpak.
Installation instructions here: https://jasp-stats.org/linux-installation-guide/

**Comment by estatistics** [comment]
Dont want flatpak cause eating a lot of space without any good reason at the moment. 

I tried to run Rscript in _script folder to install jaspBase, and  also it complains about jasPGRAPHS.
Why your code cannot install it in linux using the latest github of jasp?  
Can I manually change something in the installation file?

**Comment by tomtomme** [comment]
I do not know, sorry. It has been quite some time since i manualy compiled something big as JASP. Maybe @vandenman can help? He uses Ubuntu afaik.

Also I do not see how you can save space with installing all those dev libs needed to compile qt and everything.
So I still would advise you to go the flatpak route in the meantime, because vandenman may not respond before the new year.

**Comment by estatistics** [comment]
ok thanks! I went to R and Jamovi. Why you dont merge with jamovi? I think both programs try to do the same thing.
Have nice christmas with peace and love for all sentient beings (5 years vegan)

**Comment by EJWagenmakers** [comment]
Jamovi is a JASP clone, set up by the first set of JASP software developers: this is why the look and feel is so similar. I think the world profits from having both programs around. Merging in any way is impossible. "The shot is simply not on the board"

**Comment by tomtomme** [comment]
@estatistics 
Have a nice christmas too and feel free to close this issue.
