### ISSUE TITLE
Copy-paste from Word to "Add Notes" in JASP

### ISSUE THREAD

**Issue by BTunca** [jasp-stats/jasp-issues#249]
Hi 

When I copy paste a text from Word to the "Add Notes" section in the output it looks like that:

![screenshot_5](https://user-images.githubusercontent.com/27208030/48670218-36704200-eb14-11e8-9dee-00113b2eb01e.png)

(I only copy-pasted the text "Full Model" here)

Thank you for your help!

* JASP version: 0.9.1
* OS name and version: W10

**Comment by EJWagenmakers** [comment]
Yes, this is undesirable. In general, I think our copy-paste functionality and the text boxes can use some more attention. Frans, Bruno, Joris?

**Comment by AlexanderLyNL** [comment]
@akashrajkn is working on it.

**Comment by BTunca** [comment]
Thank you! It would be great, for example, if it was possible to copy-paste images (to show the tested model).
