### ISSUE TITLE
[Bug]: Why does Partial least squares SEM not perform in JASP

### ISSUE THREAD

**Issue by YK-MBA** [jasp-stats/jasp-issues#2491]
### JASP Version

0.18.2

### JASP Module

SEM

### What analysis are you seeing the problem on?

Partial least squares SEM

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

Hi,

Thank you for providing PLS-SEM function in JASP.

measurement model

BSQ =~ Q5_1 + Q5_3 + Q5_4 + Q5_5 + Q5_6 + Q5_10
ASQ =~ Q5_22 + Q5_23 + Q5_24 + Q5_26 + Q5_27 + Q5_29
PQ =~ Q5_9 + Q5_11 + Q5_12 + Q5_13 + Q5_14 + Q5_15 + Q5_17
CO =~ Q5_7 + Q5_8 + Q5_19 + Q5_20 + Q5_21
SE =~ Q5_2 + Q5_16 + Q5_18 + Q5_25
Len =~ Q10
Sat =~ Q1

Regressions

Len ~ Sat
Len ~ SE
Len ~ ASQ
Len ~ BSQ
Len ~ PQ
Len ~ CO
Sat ~ SE
Sat ~ ASQ
Sat ~ BSQ
Sat ~ PQ
Sat ~ CO

Although the attached CSV file and the above model equations have been entered,I get the following error.

This analysis terminated unexpectedly.

Error in UseMethod('summarize'): no applicable method for 'summarize' applied to an object of class 'NULL'

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.plsSemParameters(modelContainer, dataset, options, ready)

.plsSemParameterTables(modelContainer[['results']][['object']][[1]], NULL, params, options, ready)

cSEM::summarize(fit)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

Could you tell me what I'm doing wrong?

BR,

<img width="608" alt="2023-12-25 8 38 24" src="https://github.com/jasp-stats/jasp-issues/assets/154795872/55654c38-1b7e-4cd2-8ef0-03485cee97df">
<img width="704" alt="2023-12-25 8 38 54" src="https://github.com/jasp-stats/jasp-issues/assets/154795872/729e19ec-c54e-44e3-a8f8-df930283faab">
[test 4-1-21 20231225.csv](https://github.com/jasp-stats/jasp-issues/files/13765157/test.4-1-21.20231225.csv)

### Expected Behaviour

working well

### Steps to Reproduce

1. input the CSV file
2.entered model
3.selected  
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment]
Hi @YK-MBA, thanks for creating the issue. Could you upload the data file with it? I see you tried to upload it, but it is not available for me to download. When you upload it I can help out further.

**Comment by YK-MBA** [comment]
Thank you for your reply!
I've uploaded CSV file
[test 4-1-21 20231225.csv](https://github.com/jasp-stats/jasp-issues/files/13766459/test.4-1-21.20231225.csv)

**Comment by juliuspfadt** [comment]
to me the issue seems to be because of the missing data. apparently the underlying R-package cSEM is not able to handle missing data at the moment, so I am creating a fix to remove the missings listwise.

**Comment by juliuspfadt** [comment]
If you do not want to wait for a new version of JASP, you would have to remove the rows containing missing data by yourself.

**Comment by YK-MBA** [comment]
Thank you so much for your advice!
I tried it with a file with the missing data deleted and the error disappeared.

Is there a way to output path diagrams with Partial least squares SEM?

**Comment by tomtomme** [comment]
The main SEM module and the Mediation submodule of SEM have this plot. Maybe those can be reused also for a PLS SEM? I do no nothing about PLS SEM... so I might be mistaken.

**Comment by juliuspfadt** [comment]
Unfortunately, at this point there is now way to output the path diagrams in PLS-SEM
