### ISSUE TITLE
[Bug]: This analysis terminated unexpectedly on visual modelling 

### ISSUE THREAD

**Issue by georgietinker** [jasp-stats/jasp-issues#2494]
### JASP Version

0.16.4

### JASP Module

Visual Modeling

### What analysis are you seeing the problem on?

moderation analysis

### What OS are you seeing the problem on?

Other

### Bug Description

This analysis terminated unexpectedly.

Error in UseMethod('.applyEnDeCoder', x): no applicable method for '.applyEnDeCoder' applied to an object of class 'character'

Stack trace
linmod(...)

flexplot:::linmod_jasp(jaspResults, dataset, options)

.linmod_compute(jaspResults, dataset, options, ready)

unlist(lapply(encodeColNames(options$interactions), FUN = function(x) encodeColNames(unlist(x$components))))

lapply(encodeColNames(options$interactions), FUN = function(x) encodeColNames(unlist(x$components)))

encodeColNames(options$interactions)

.applyEnDeCoder(x, fun, ...)

.applyEnDeCoder.list(x, fun, ...)

rapply(x, f = .applyEnDeCoder, how = 'replace', fun = fun, ...)

(function (x, fun, ...)
{
    UseMethod('.applyEnDeCoder', x)
})(X, ...)
![Screenshot 2023-12-28 at 17 10 53](https://github.com/jasp-stats/jasp-issues/assets/155095561/fe872a73-0567-4c62-8091-3c53e0194cad)

### Expected Behaviour

should have shown a graph 

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
You are on a pretty old jasp version.
Can you try the new one from the windows store?
https://apps.microsoft.com/detail/9P08CWG12JNL?hl=de-de&gl=US
Or which OS do you use?

**Comment by dustinfife** [comment]
I believe [this](https://github.com/dustinfife/flexplot/pull/125) fixes this issue.

**Comment by tomtomme** [comment]
@georgietinker 
Can you confirm and if so, close this issue?
