### ISSUE TITLE
Windows Installer stops on JASP 0.18.1.0 [Bug]: 

### ISSUE THREAD

**Issue by rwalkern** [jasp-stats/jasp-issues#2495]
### JASP Version

0.18.1

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

Installation issue

### What OS are you seeing the problem on?

Windows 11

### Bug Description

I have a problem installing the program.

![Screenshot 2023-12-28 144310](https://github.com/jasp-stats/jasp-issues/assets/155109261/aa387444-b643-4760-ba57-7b43a2d19712)

I also download the JASP-0.18.1.9-Windows zip file by the file do not run as well.

Running the JASPEngine.exe file give the following error
R.dll was not found

### Expected Behaviour

Software can be installed

### Steps to Reproduce

1. Running the Jasp-0.18.1.0 - Windows package
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Can you try if the new release on the windows store works for you?
https://apps.microsoft.com/detail/9P08CWG12JNL?hl=de-de&gl=US

**Comment by rwalkern** [comment]
I tried this link but it doesn't launch the installer.  I was able to install this application into my son's computer that is a Intel 3 CPU.  This computer that is failing is a AMR Ryzen 7 5700U with Radeon Graphics, with 16GB of RAM, I don't know if this is a know issue with this computers.

**Comment by tomtomme** [comment]
AMD processors should be fine. I use them all the time...

**Comment by rwalkern** [comment]
Any other suggestion on this issue, any log or troubleshooting that I can do

**Comment by tomtomme** [comment]
> I tried this link but it doesn't launch the installer. 

Can you tell me what happened instead? 
I guess you have to be logged in to your microsoft account to use the online version of the store. Was that the case?

**Comment by rwalkern** [comment]
Yes, I'm.  I was able to download the installer from the MS Store, but when I got this pop up window:

![image](https://github.com/jasp-stats/jasp-issues/assets/155109261/d93c47e0-0c8c-48ba-b0b0-772f3349aabd)

The application never starts.

**Comment by tomtomme** [comment]
Strange. No error message? The popup is just sitting there?
How about disc space. Enough left?
How about windows updates? All up to date? 
How about virus scanners. Temporal deactivation maybe helps?

I am obviously digging in the dark here.

**Comment by RensDofferhoff** [comment]
I'm very curious what causes this. 
I have never seen an issue where it doesn't start before.
Did you have JASP installed on this system previously ?

**Comment by RensDofferhoff** [comment]
Oh btw you need to start JASP not JASPEngine if you are using the ZIP release.

**Comment by rwalkern** [comment]
Hi
Yes I know, but on previous documented issues like mine it was a suggestion done to see why JASP didn't run, and it looks like it is also related with a missin R dll library.  On these bugs reports (1841 if not mistaken) they said it was fixed by updating the graphics drivers, but based on my windows I m up to date. 

Thanks
Robert Walker
Sent from Yahoo Mail on Android 
 
  On Tue, Jan 2, 2024 at 3:50 AM, ***@***.***> wrote:   


Oh btw you need to start JASP not JASPEngine if you are using the ZIP release.

**Comment by tomtomme** [comment]
You can still try to download a more up to date driver from: https://www.amd.com/en/support

Or even better from the support page of the laptop manufacturer.

**Comment by boutinb** [comment]
Can you try to start JASP from the command line (with cmd). If you have tried the zip file, go to the unzipped folder,  and just type JASP in the command line.  You should see then some output from JASP. You can also try to start JASP with the safe graphics mode: `JASP --safeGraphics`

**Comment by rwalkern** [comment]
Well, I unzipped the file under Program Files x86 instead of program files and it worked, with some issues about some missing icons.  Later on I run the MSI installer and this time it worked and now I have it installed.

Thanks a lot for the help

Robert

**Comment by tomtomme** [comment]
I can only imagine, that windows might have been busy doing some upgrades that conflicted with the installation process. Good that it is resolved now :)
Would you close this issue then? Thx.

**Comment by boutinb** [comment]
Still strange, but happy to hear that it works now.
