### ISSUE TITLE
[Bug]: Update keyword list

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#2496]
### JASP Version

0.18.2

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Other

### Bug Description

This keywords file
https://github.com/jasp-stats/jasp-issues/pull/2449/files#diff-2a1edc2bdaf87f47c1930f2c35b1ba723d47b7067bb9ae6353d402deee3e73fc

is missing the following modules:
- learn stats
- time series
- process
- predictive analytics
- R-Console
- Edita data mode

### Expected Behaviour

file should be up to date. 

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
I have added the modules.
R-Console and Edit mode are not modules. You can then just select 'unrelated' when choosing the module,
