### ISSUE TITLE
[Feature Request]: Integrate Flatpak Beta on nightlies-webpage

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#2497]
### Description

We have https://static.jasp-stats.org/Nightlies
This misses a flatpak section

### Purpose

Invite more testing from linux users

### Is your feature request related to a problem?

not enough devs and testers

### Describe the solution you would like

Integrate a table similar to the Win and Mac ones that links the now available "weekly" flatpak betas.

And add the following information / instructions (I will do a more detailed write up/ explanation of thoss commands aka a HowTo later):

```
flatpak remote-info --log flathub-beta org.jaspstats.JASP

flatpak remote-add flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo

flatpak install flathub-beta org.jaspstats.JASP

flatpak run --branch=beta org.jaspstats.JASP

flatpak run --branch=stable org.jaspstats.JASP
```

Also consider to add this to the regular flatpak installation procedure web page, since many linux users like experimenting with betas :D

**Comment by RensDofferhoff** [comment]
Good plan. I will need to make some changes to this page soon anyways to explain the MSIX testing procedure.

**Comment by RensDofferhoff** [comment]
This about what you envisioned ? https://static.jasp-stats.org/Nightlies/

**Comment by tomtomme** [comment]
Yes! Thanks!
