### ISSUE TITLE
[Bug]: No synchronization of the datafile after editing it in Excel and all variables get removed from the assignment boxes afterwards

### ISSUE THREAD

**Issue by AFicko** [jasp-stats/jasp-issues#2499]
### JASP Version

0.18.2

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

Synchronizing, Data import

### What OS are you seeing the problem on?

Windows 10

### Bug Description

Hi, 
I have just installed the latest version of JASP. I noticed a few strange things related to data import and data synchronization that did not happen in the previous version of JASP 16.4:
1. I uploaded the .csv data. JASP 18.2 seem to read the .csv file correctly only when the decimal separator is the decimal point and the thousands separator is the decimal comma. This was not the case in the 16 version. In 16.4 I could upload the .csv file saved in my native system settings (comma used for the decimal separator), but I can no longer do that in JASP 18.2. Is there any way to avoid changing my system settings in Excel?
2. When I open the data set in the default spreadsheet editor and add a column and save the file, JASP does not synchronize. CTRL+Y does not synchronize either. Instead, after switching JASP back from data editing mode to analysis mode, the dataview briefly says "synhronizing dataset" and then becomes empty. Only after going to SyncData menu and synchronizing with the current .csv file, which takes a very long time, data become visible again in data editing mode. However, all assignment boxes in the existing analyses depopulate (they become empty) and I have to start with all the analyses again.
Could you please give me some advice?

### Expected Behaviour

The dataset should synchronize automatically or by CTRL+Y and the existing analyses should be rerun automatically based on the updated dataset.

### Steps to Reproduce

1.Open a .csv file in JASP.
2. Open the .csv data in Excel by going to Sinchronization icon and selecting Open datafile with default spreadsheet editor
3. Add or change something in the file and save the .csv file.
3.Click on the icon Switch JASP to analyses mode
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JorisGoosen** [comment]
Aah oops, I broke the commas...

Im also adding some commas to our debug dataset so we dont miss this again

**Comment by boutinb** [comment]
Hi @AFicko We can reproduce the decimal issue and this will be fixed asap. 
I cannot reproduce the synchronization issue. When I add a column to a csv file, JASP synchronizes automatically and add this column to the dataset. But I'm not completely sure of your description. What I do is just:

- Load a csv file in Excel
- Load the same csv file in JASP
- Add a column in Excel
- Save in Excel: JASP add this column in the dataset.
If with this same path, JASP does not synchronize, could you try with a simple csv file with just 2 columns, 2 rows, and just integers?

**Comment by AFicko** [comment]
Hi @boutinb 
It works with a simple 2 x 2 csv file; JASP synchronizes automatically after saving the csv file. But it does not synchronize with my original file with 8000 lines and 133 variables of different types (in the attachment).
It seems to be the problem with this particular file.
[Primer.csv](https://github.com/jasp-stats/jasp-issues/files/13820766/Primer.csv)

**Comment by boutinb** [comment]
Hmm even with this file, it works for me (on Mac and Windows). But there are definitively a problem when handling the points and commas with such a file, and this might affect the synchronization. We will release soon a new version next to fix this issue, and we have already a beta version that solves it, I will give you a link so that you can test it.

**Comment by JorisGoosen** [comment]
Try any of the latest (topmost) nightlies here: https://static.jasp-stats.org/Nightlies/

**Comment by R180** [comment]
This happened to me recently, causing me to lose all of my computed columns (fortunately I was able to access a previous version of the JASP file to recover most of my work). However, I cannot reproduce the issue. Because I suspect it had something to do with using an xlsx rather than a csv file, I now have a practice of syncing to csv files only.

> RE: "_When I open the data set in the default spreadsheet editor and add a column and save the file, JASP does not synchronize. CTRL+Y does not synchronize either. Instead, after switching JASP back from data editing mode to analysis mode, the dataview briefly says "synhronizing dataset" and then becomes empty. Only after going to SyncData menu and synchronizing with the current .csv file, which takes a very long time, data become visible again in data editing mode. However, all assignment boxes in the existing analyses depopulate (they become empty) and I have to start with all the analyses again."_
