### ISSUE TITLE
Error p-value Paired Samples t-test

### ISSUE THREAD

**Issue by mservantufc** [jasp-stats/jasp-issues#250]
Hi,
I am using JASP 0.7.5.6. My data is attached. A Paired samples t-tests on variables AE1 and AE2 gives different p-values when I choose Measure 1 > Measure 2 than Measure 1 < Measure 2 (see attached). is it a bug?

[TD2_exo2.xlsx](https://github.com/jasp-stats/jasp-issues/files/2594278/TD2_exo2.xlsx)

![capture1](https://user-images.githubusercontent.com/45162680/48693689-8b768b80-ebda-11e8-8714-e2207afae542.PNG)
![capture2](https://user-images.githubusercontent.com/45162680/48693691-8d404f00-ebda-11e8-9d80-9c0ea2e7f940.PNG)

**Comment by vankesteren** [comment]
Hi @mservantufc,

no, this is not a bug; you are changing the alternative hypothesis and therefore the p-value correctly adjusts. 

You can use the help file in the hamburger menu to get an idea of what each option does!

![image](https://user-images.githubusercontent.com/11596858/48699340-879e3580-ebe9-11e8-8daf-ed0f895c63ba.png)
