### ISSUE TITLE
[Feature Request]: Read missing values from sav/readstat into column empty values

### ISSUE THREAD

**Issue by JorisGoosen** [jasp-stats/jasp-issues#2500]
### Description

SPSS files can contain well defined per column missing values. These are currently read by JASP and are interpreted correctly as missing values. But they are not stored in the column.

### Purpose

Make use of added functionality from https://github.com/jasp-stats/jasp-desktop/pull/5276 to store missing values properly from SPSS

### Use-case

pretty obvious I think

**Comment by tomtomme** [comment]
All stuff related to "missing values"
#2575
#2500
#2437
#396

**Comment by JorisGoosen** [comment]
@tomtomme do you have an example sav file for this?
I dont really want to buy a license for SPSS just to test this

**Comment by tomtomme** [comment]
Not until tuesday. If you need it earlier you could produce one with pspp. It is open source.
I have no access to a pc atm.

**Comment by JorisGoosen** [comment]
No hurry!

**Comment by shun2wang** [comment]
Here are some dataset of SPSS made: https://github.com/diazbastian/spss-sample-documents/tree/master/data-files/created-with-spss/spss-examples

**Comment by tomtomme** [comment]
@JorisGoosen 
Here is a nice big one with lots of labels and missing values defined
[missings.sav.zip](https://github.com/jasp-stats/jasp-issues/files/14839021/missings.sav.zip)

The first 8 variables should cover most combinations of variable type and sort of missing value (range, single value, string etc.)

Besides the information of the "missing values" we should also import description, type etc. 
So from the screenshot below the columns number:
1
2
5
6
7
10

![grafik](https://github.com/jasp-stats/jasp-issues/assets/4428185/513f130e-03c2-4d77-b1a0-561789609b28)

**Comment by JorisGoosen** [comment]
Im going to leave out the support for the `min<X<max` missing values because it doesnt really fit with the way they work in JASP.

Unless of course this is an indispensable feature, then Im sure we could cobble something together, but it would probably require some extra stuff in JASP.

**Comment by shun2wang** [comment]
[Here](https://github.com/WizardMac/ReadStat?tab=readme-ov-file#command-line-usage-with-csv-input) in readstat has a metadata for dataset files type and "missing", wich will including some custom missing value and system missing.

**Comment by tomtomme** [comment]
@JorisGoosen 
It is lower prio I think. So from my perspective leave it out for now.

Did you close the issue on purpose? Is this already implemented?

**Comment by JorisGoosen** [comment]
I closed it on purpose indeed, see: https://github.com/jasp-stats/jasp-desktop/commit/79ef8b5b9cbec06c46cfcbec6e7d5bc80fcb824b
