### ISSUE TITLE
[Bug]: Problem with pre-installed version

### ISSUE THREAD

**Issue by idobraca** [jasp-stats/jasp-issues#2502]
### JASP Version

0.18.2

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 11

### Bug Description

After extracting JASP from ZIP pre-installed version and starting it, many errors about missing icons appear. 
![2024-01-03 19_27_24-JASP](https://github.com/jasp-stats/jasp-issues/assets/2134191/a55f7b84-8555-430a-a2b4-8d48c290a6eb)
![2024-01-03 19_28_17-JASP](https://github.com/jasp-stats/jasp-issues/assets/2134191/ac623b6e-3629-4e23-ab08-c494b8f25079)

### Expected Behaviour

JASP should start.

### Steps to Reproduce

1. Download pre-installed ZIP version of JASP 0.18.2.
2. Extract it
3. Run JASP.exe

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @idobraca There was indeed a problem with this zip file. I have just changed with the right one. Can you try it?

**Comment by idobraca** [comment]
Hi @boutinb, now JASP is starting correctly. Thank you.

**Comment by IsakGideon** [comment]
I have no idea about how this issue can be solved. After installing using the official package, I encounter the same problem in this page. As you said, I deleted the .log file and then opened it. Unsurprisingly, I was notified to be patient and wait, after a long waiting, JASP opened itself and then told me (many) modules missing.
![image](https://github.com/jasp-stats/jasp-issues/assets/68316718/5e2ae962-cbf6-4905-8a2c-37cc5512acf4)

**Comment by IsakGideon** [comment]
Sorry, I forgot to mention that I used the 0.18.3 package to install but also encounter this problem.

**Comment by IsakGideon** [comment]
And after closing many "module missing" windows, I found that the analysis bar is abnormal.
![image](https://github.com/jasp-stats/jasp-issues/assets/68316718/f51d7be9-a65a-463c-a289-c886402db448)
Some functions were lacking. I don't know whether there is anyone who also get stuck in this problem.

**Comment by tomtomme** [comment]
- did you try uninstalling the old version before installing the new?
- Are you on win11, win10, macOS, which version, if?
- if on win, try installimg via MS Store
- how much RAM and disk space are left on your machine?
- do you use non-english locale?

**Comment by IsakGideon** [comment]
I've tried three times and it now work well. This is quite confusing. I used win11 system. I will take your notes to use the source from MS store when I have to install it on other devices. Thanks! @tomtomme
