### ISSUE TITLE
[Bug]: Audit - Sampling workflow gets stuck

### ISSUE THREAD

**Issue by JorisGoosen** [jasp-stats/jasp-issues#2503]
### JASP Version

0.18.2

### JASP Module

Audit

### What analysis are you seeing the problem on?

(Bayesian) Sampling

### What OS are you seeing the problem on?

Other

### Bug Description

@koenderks 

When you choose "Fill Variables" it doesnt reload with the selected entries anymore.

### Expected Behaviour

it should obviously reload

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
I this is solved by https://github.com/jasp-stats/jasp-desktop/pull/5370, no?

**Comment by koenderks** [comment]
Should be the case, yes
