### ISSUE TITLE
Engine crasjing on beta version trying to edit data: 

### ISSUE THREAD

**Issue by LoriSap** [jasp-stats/jasp-issues#2505]
### JASP Version

0.18.2

### JASP Module

Quality Control

### What analysis are you seeing the problem on?

Process Capability

### What OS are you seeing the problem on?

Windows 11

### Bug Description

Engine crashes when trying to edit data, now it is crashing also opening any file even before trying to edit

### Expected Behaviour

It should open file or allow data to be edited

### Steps to Reproduce

1.
2.
3.
...

### Log (if any)

![image](https://github.com/jasp-stats/jasp-issues/assets/152518797/b4d79930-baa6-4f04-865e-30daafc140d0)

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @LoriSap Without being able to reproduce it, this makes really difficult to help you... Could you send us an anonymized file that reproduces this issue?

**Comment by LoriSap** [comment]
I cannot open a file to anoymize.  That is the problem.  I had IT download the latest beta version we had 2 days ago and all seemed to be working again and then I started getting random glitches.  Some files open, some crash, others will not let me edit, some keep crashing while trying to filter-and I am not even filtering.  It seems possessed! 😊.

Lori Saponaro
Quality Specialist
SKF USA Inc.
20 Industrial Dr.
Hanover, PA.17331
(717)347-5258
***@***.***

**Comment by tomtomme** [comment]
@LoriSap 
Could you try if some of the recent nightlies fixes this for you?

https://static.jasp-stats.org/Nightlies/

**Comment by LoriSap** [comment]
Right now this has been working enough for my needs.  It is glitchy.  It works for a while and then another issue pops up but it does not always do the same thing with all my files.  I will try this is I have issues again .  Thank you

Lori Saponaro
Quality Specialist
SKF USA Inc.
20 Industrial Dr.
Hanover, PA.17331
(717)347-5258
***@***.***

**Comment by tomtomme** [comment]
Thanks. I will close this then. Feel free to reopen, if you can reproduce it.
