### ISSUE TITLE
Logistic regression - Problems with multicolinarity diagostics and formatting in JASP help 

### ISSUE THREAD

**Issue by PerPalmgren** [jasp-stats/jasp-issues#2507]
### JASP Version

0.18.1

### JASP Module

Regression

### What analysis are you seeing the problem on?

Logistic regression

### What OS are you seeing the problem on?

Windows 10

### Bug Description

Two things in the logistic regression module.
1) There seem to be a problem with the displayed VIF and Tolerance values when running multicolinearity diagnostics in the logistic regression module. They are the same for the predictors (see attached photo). 🙄 A similar problem was in the linear regression module in an earlier JASP version.
<img width="951" alt="Skärmklipp" src="https://github.com/jasp-stats/jasp-issues/assets/79397662/b6f7244b-0dd9-4963-ad10-a4ef4a10f906">
2) There seem to be some problem with formatting when using the JASP help "I" button (see attached photo).
<img width="935" alt="Skärmklipp2" src="https://github.com/jasp-stats/jasp-issues/assets/79397662/52fc5d28-cb7b-4f06-af86-2ce942fdb3ce">

### Expected Behaviour

Not the same VIF/Tolerance values for the predictors.

### Steps to Reproduce

1. NA
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
I can confirm this for 0.18.2
If I put in a third IV however, the VIF and Tolerance are calculated fine. The values are only identical if you put in only 2 IVs!

**Comment by tomtomme** [comment]
@Kucharssim  & @PerPalmgren 
Now that I think about it - I think it is expected for VIF/Tolerance to be the same for 2 IVs.
Thats what multicolinearity is all about, measuring "covariance" between IVs in respect to the DV. And when we have only 2 IVs, we have only one covariation.

Please reopen, if I misunderstood!
