### ISSUE TITLE
error when generating descriptive graphs

### ISSUE THREAD

**Issue by wroclai** [jasp-stats/jasp-issues#251]
Using the current (0.9.1) JASP flatpak on Arch Linux.

Under descriptive stats, when I attempt to make a box-plot I get the following error:
This analysis terminated unexpectedly.
Error in (structure(function (x) : could not find function 'tryToWriteImageJaspResults'

This was reportedly corrected (see https://github.com/jasp-stats/jasp-desktop/issues/2854), but it clearly persists. Using the same data on 0.9.1 for Mac works entirely as expected.

[jasp error report.zip](https://github.com/jasp-stats/jasp-issues/files/2597562/jasp.error.report.zip)

**Comment by JorisGoosen** [comment]
Can you try this in the new release 0.9.2?

**Comment by tomtomme** [comment]
While I am not the OP, this works for me with flatpacked 0.9.2 on manjaro

**Comment by JorisGoosen** [comment]
Good enough for me.
