### ISSUE TITLE
[Bug]: Latent Growth modeling get error

### ISSUE THREAD

**Issue by joanbak** [jasp-stats/jasp-issues#2510]
### JASP Version

0.18.2

### JASP Module

SEM

### What analysis are you seeing the problem on?

Latent Growth modeling

### What OS are you seeing the problem on?

Windows 11

### Bug Description

![KakaoTalk_20240105_131102398](https://github.com/jasp-stats/jasp-issues/assets/155708592/8926387b-3d9e-4281-9dfe-b1a44bee26fa)

### Expected Behaviour

![스크린샷 2024-01-05 143833](https://github.com/jasp-stats/jasp-issues/assets/155708592/dbfc7bfb-4665-47b2-b9c0-941ed6772a44)

### Steps to Reproduce

When analyzing the potential growth curve, if you put variables and put gender in the factor, you will get an error right away

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
I can replicate this with any data on linux. Just put any factor in and the error message appears.

**Comment by applepiereader** [comment]
I came here to report the same bug - just updated JASP (was still working with version 0.16) and suddenly these analyses won't work anymore.
The basic growth analysis is fine, but once I add a factor, it 'terminates unexpectedly'.

**Comment by tomtomme** [comment]
Related bugs
#2212
#2076
#2032
#2002

**Comment by juliuspfadt** [comment]
well so the currentNa error is easily fixed. I checked it with the data set from here: https://github.com/jasp-stats/jasp-issues/issues/2076. I think for the errors with the singularity problem there is something else going on for which I would need to see the data set.
