### ISSUE TITLE
[Feature Request]: No scary warning on missing known issues list

### ISSUE THREAD

**Issue by JorisGoosen** [jasp-stats/jasp-issues#2512]
### Description

JASP downloads a list with known-issues and without internet it complains in a warning. This is apaprently scaring people off. Instead we should just not show the warning.

### Purpose

Stop scaring people

### Use-case

exam halls etc

**Comment by boutinb** [comment]
Will be fixed by https://github.com/jasp-stats/jasp-desktop/pull/5382.
A new version will be released this week.
