### ISSUE TITLE
[Bug]: error when using RM ANOVA with 2 RM and 1 between subects factor

### ISSUE THREAD

**Issue by batelbuaron** [jasp-stats/jasp-issues#2513]
### JASP Version

0.18.2

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

Repeated Measures anova

### What OS are you seeing the problem on?

Windows 10

### Bug Description

when I try to run a RM ANOVA with 2 RM factors and 1 between factors i get the following error:
This analysis terminated unexpectedly.

Error in `.rowNamesDF<-`(x, value = value): duplicate 'row.names' are not allowed

Stack trace
doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.rmAnovaComputeResultsContainer(rmAnovaContainer, longData, options, ready)

.rmAnovaComputeResults(longData, options)

`rownames<-`(`*tmp*`, value = cases)

`row.names<-`(`*tmp*`, value = value)

`row.names<-.data.frame`(`*tmp*`, value = value)

`.rowNamesDF<-`(x, value = value)

stop('duplicate 'row.names' are not allowed')

this does not happen when using only 1 RM factor and 1 between subjects factor on the same data.

### Expected Behaviour

calculate a 2(RM)X2(RM)X3(Between) ANOVA

### Steps to Reproduce

1. insert 2 RM factors with 2 levels each
2.insert a between subjects factor with 3 groups
3.
...

### Log (if any)

This analysis terminated unexpectedly.

Error in `.rowNamesDF<-`(x, value = value): duplicate 'row.names' are not allowed

Stack trace
doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.rmAnovaComputeResultsContainer(rmAnovaContainer, longData, options, ready)

.rmAnovaComputeResults(longData, options)

`rownames<-`(`*tmp*`, value = cases)

`row.names<-`(`*tmp*`, value = value)

`row.names<-.data.frame`(`*tmp*`, value = value)

`.rowNamesDF<-`(x, value = value)

stop('duplicate 'row.names' are not allowed')

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
The error says it all:

duplicate 'row.names' are not allowed

Have you tried that?

**Comment by tomtomme** [comment]
@boutinb 
This is the same "bug" as here https://github.com/jasp-stats/jasp-issues/issues/2485 I presume?

Maybe we should include some guideline for the user, like better not to use spaces in variable names. Or if spaces are needed, then not to use the same terms in variable names twice. But I also would not know where to put this guidelines in the interface. If we would hide it behind one of the (i) icons, most people will never see it...

**Comment by boutinb** [comment]
Quite difficult to intercept this error in the interface. Better to check that in the analysis, but the error message is already quite clear...

**Comment by tomtomme** [comment]
just a note (for me) on a related issue:
https://github.com/jasp-stats/jasp-issues/issues/1489
