### ISSUE TITLE
[Feature Request]: List of hardware requirements

### ISSUE THREAD

**Issue by JoKeyser** [jasp-stats/jasp-issues#2514]
### Description

The website could feature an up-to-date list of hardware requirements (and maybe recommendations) to run JASP.

### Purpose

Allow people to decide if their current computing device is sufficient to run JASP, or another device is required.

### Use-case

For example, students may not own an appropriate device, and may want/have to buy another device for a JASP-based course.

### Is your feature request related to a JASP module?

Unrelated

### Describe the solution you would like

I think the hardware requirements should be listed along with the software requirements, either at the [download page](https://jasp-stats.org/download/) and/or the [FAQ](https://jasp-stats.org/faq/).

### Describe alternatives that you have considered

Currently, there is only indirect information provided on the download page, mediated by the software requirements.

### Additional context

As a stats teacher, I notice that new students don't necessarily have a device that supports JASP. I would like to be able to point them to a list of requirements (and possibly also recommendations). With the increasing amount of supported devices, it is no longer obvious to me what is a suitable (hardware) platform.

Of course, parts of the list may be offloaded by pointing people to existing lists, e.g. what hardware supports the minimum required Windows version, etc.

**Comment by RensDofferhoff** [comment]
We can certainly add this to the download page.

Currently we support:
PC: AMD64/intel x86_64, Windows 10 version 19041.0 or higher
Mac: Apple Silicon/Intel, MacOS Ventura 13.5 or higher
Linux: AMD64/intel x86_64/ARM64 Linux machines capable of running flatpaks (basically all modern Linux flavors, including Chromebooks with some effort).

We recommend at 8GB RAM with a minimum of 4GB.

> I notice that new students don't necessarily have a device that supports JASP
What sort of devices are these. I cant promise anything but if there is a common device we do not support I can of course take a look if we can target it.

**Comment by shun2wang** [comment]
Windows 10 version should be 1809 or higher. 
cuz R 4.0+ required.

**Comment by RensDofferhoff** [comment]
I need some features of 2004 for MSIX.
It doesn't really matter as both those versions aren't even supported by Microsoft anymore. 
2020 is already ancient history apparently 😢

**Comment by RensDofferhoff** [comment]
@JoKeyser I added a System requirements list to the download page: https://jasp-stats.org/download-jasp/
Was this about what you wanted?

**Comment by JoKeyser** [comment]
@RensDofferhoff and @shun2wang , thank you for your quick replies, this is already super helpful.

>> I notice that new students don't necessarily have a device that supports JASP

> What sort of devices are these? I cant promise anything but if there is a common device we do not support I can of course take a look to see if we can target it.

To be honest I don't know; some have just some random Apple or Android tablets that have their own app store, etc. Maybe we could explicitly state that e.g. Android devices are not supported?

If possible, I would make it as simple as possible for people to match a given product with the list of requirements. I guess the CPU arch is the real bottleneck, and it would be impossible to list all the CPU models that apply.


For now, I'm super happy with this addition; here is a just slightly more reordered suggestion:

---

## System Requirements

To install JASP, you need about 4 GB of free disk space.

To run JASP, you need a minimum of 4 GB RAM.
We recommend at least 8 GB RAM.

### Supported platforms

JASP is compatible with multiple operating sytems and CPU architectures:

- Windows 10 version 2004 or higher, with an AMD64 or Intel x86_64 CPU.
- MacOS Ventura 13.5 or higher, with an Apple Silicon or Intel CPU.
- Any Linux distribution that supports [Flatpak](https://jasp-stats.org/linux-installation-guide/).
  This includes [Chromebooks](https://jasp-stats.org/chromebook-installation/) that came out 2019 or later.
  Compatible CPUs are AMD64, or Intel x86_64, or ARM64.
- Other: Try the web version.

**Comment by RensDofferhoff** [comment]
Thanks for the suggestions.
The update page is now live.

**Comment by tomtomme** [comment]
Sometimes JASP also works on Windows devices with ARM processors. But I could not yet figure out which ARM cpus work.
Apple AND Android tablets do not work in general, since JASP is not included in their stores and sideloading isn't a thing on Apple while it is on Android, but that does not help since flatpak is not supportet on Android afaik.
So I would vote for adding this info:

"Apple and Android tablets are not supported. But some windows tablets are."

**Comment by RensDofferhoff** [comment]
done!

**Comment by tomtomme** [comment]
I had another look at the download page. 
Further above it states:

"Apple no longer supports macOS 10.15 (Catalina) and below. Please upgrade your OS or use an older version of JASP instead."

This is old news, since https://en.wikipedia.org/wiki/MacOS_version_history#Releases states, that only verstion 12-14 are still supported by now. Maybe drop the OS version info from above and only update it in the new "system requirements" section below. 

> MacOS Ventura 13.5 or higher, with an Apple Silicon or Intel CPU.

would need to be corrected to 

> MacOS Ventura 12 or higher, with an Apple Silicon or Intel CPU.

Wouldn't it?

**Comment by boutinb** [comment]
> "Apple no longer supports macOS 10.15 (Catalina) and below. Please upgrade your OS or use an older version of JASP instead."

Thanks thomas for the sharp look. I have updated the site.
But I still find that a warning below the macOS column is still needed. People does not take the time to read everything on the page, so an extra warning here is not too much.
