### ISSUE TITLE
[Bug]: quick / click filtering does not work

### ISSUE THREAD

**Issue by richlv** [jasp-stats/jasp-issues#2515]
### JASP Version

0.18.2

### JASP Module

Unrelated

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

Clicking the quick filter checkmarks...

<img width="196" alt="image" src="https://github.com/jasp-stats/jasp-issues/assets/112888/75b718e6-5391-44c9-8497-48f7f397a5ed">

...does not perform any filtering in analysis.

<img width="141" alt="image" src="https://github.com/jasp-stats/jasp-issues/assets/112888/49a2c9e4-8670-4c0e-8064-be010b6525ce">

### Expected Behaviour

Clicking on filter options affects analysis.

### Steps to Reproduce

1. Load any dataset with ordinal or nominal scales.
2. Deselect some values.
3. Perform any analysis and observe all values still included.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @richlv, that is quite strange because I cannot reproduce this issue. Maybe you could share your data?

**Comment by richlv** [comment]
Thank you for looking into this.
I've sent a link to the file to issues@jasp-stats.org .
In that file, I have quick-filtered out one of the "Dzimums" values. Looking at analyses, it all seems to be included.

**Comment by richlv** [comment]
Looks like I spotted the crucial condition.
If I add any R filtering (like "!is.na(Laiks)" in the data file), quick filters do not apply at all.

**Comment by JorisGoosen** [comment]
You need to combine it with the variable `generatedFilter`

So something like `!is.na(Laiks) & generatedFilter'

**Comment by JorisGoosen** [comment]
Haha yeah somebody changed the icon but not the text, ill change it

**Comment by JorisGoosen** [comment]
well dumping lines below "works" in the sense that it is valid code. But I guess if you dont know R it is hard to understand how it works.

Basically the R script here is ran and then the last line is "returned" as the filter.

So before your change the filter looks like:
```
generatedFilter <- ***Some code generated by clicking labels and other things***
generatedFilter
```

Which means it return that generatedFilter.

However if you change that too:
```
generatedFilter <- ***Some code generated by clicking labels and other things***
generatedFilter
!is.na(Laiks)
```

It just returns the result from the last line, which is just the rows that are not NA in Laiks.

So doing:
```
generatedFilter <- ***Some code generated by clicking labels and other things***
generatedFilter & !is.na(Laiks)
```
is the way because it combines both the "generatedFilter" (which as you can possibly derive from the name is the filter as generated by the GUI of JASP) and the manually entered filter (which is `!is.na(Laiks)`)
Hope this helps make it a bit clearer for you

**Comment by richlv** [comment]
Thanks, mentioning the & syntax made it clear immediately.
Would the editable block make sense like so?
```
# Add filters using R syntax here. By default the non-R filter(s) are passed with generatedFilter.
# To include generated filters, append clauses with "&": generatedFilter & ...
# Click the (i) icon in the lower right corner for further help.
generatedFilter
```

**Comment by JorisGoosen** [comment]
Yes it would, Ill make some changes for that and Ill also make sure it becomes translatable. Because currently it is locked to english and it seems more explanation there is helpful
