### ISSUE TITLE
[Bug]: structural equations analysis problem

### ISSUE THREAD

**Issue by APadroSolanet** [jasp-stats/jasp-issues#2516]
### JASP Version

0.18.1

### JASP Module

SEM

### What analysis are you seeing the problem on?

structural equation modeling

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

This is the log with the error:
[structural_equation_error_message.csv](https://github.com/jasp-stats/jasp-issues/files/13852874/structural_equation_error_message.csv)

This is the jasp file compressed:
[all_surveys_cat_eusk.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/13852881/all_surveys_cat_eusk.jasp.zip)

### Expected Behaviour

The analysis should be estimated

### Steps to Reproduce

No

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by richlv** [comment]
Just copying the beginning of the CSV (?) file for easier searching.

```
This analysis terminated unexpectedly.
Error in A %*% P.inv: requires numeric/complex matrix/vector arguments

Stack trace
"tryCatchOne(expr, names, parentenv, handlers[[1]])"
"doTryCatch(return(expr), name, parentenv, handler)"
"withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)"
"analysis(jaspResults = jaspResults, dataset = dataset, options = options)"
".semFitTab(jaspResults, modelContainer, dataset, options, ready)"
".withWarnings(do.call(lavaan::lavTestLRT, lrt_args))"
"withCallingHandlers(expr, warning = wHandler)"
"do.call(lavaan::lavTestLRT, lrt_args)"
"(function (object, ..., method = 'default', A.method = 'delta', scaled.shifted = TRUE, H1 = TRUE, type = 'Chisq', model.names = NULL)"
```

**Comment by tomtomme** [comment]
I cannot repdroduce the error with JASP 0.18.2
Everything seems fine, using your .jasp file. Can you re-test with 0.18.2?
