### ISSUE TITLE
[Bug]: .jasp file does not open / load after downloading 0.18.2

### ISSUE THREAD

**Issue by LindaHoffmann** [jasp-stats/jasp-issues#2517]
### JASP Version

0.18.2

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 11

### Bug Description

I cannot open my .jasp file after downloading the newest version of the tool.  When trying to open it in jasp 0.18.2.0, the loading page pops up and closes immediately. 

Could you please help me to understand how this can be fixed? I have attached the respective .jasp file for you as a zip file.
Thanks for your help!
[data_environmentalbehaviour__v8.zip](https://github.com/jasp-stats/jasp-issues/files/13854413/data_environmentalbehaviour__v8.zip)

### Expected Behaviour

file should have opened

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by RensDofferhoff** [comment]
Do you remember the version with which you created this file?

**Comment by LindaHoffmann** [comment]
yes, it was the version 0.18.1.0
________________________________
Von: RensDofferhoff ***@***.***>
Gesendet: Sonntag, 7. Januar 2024 23:27
An: jasp-stats/jasp-issues ***@***.***>
Cc: LindaHoffmann ***@***.***>; Author ***@***.***>
Betreff: Re: [jasp-stats/jasp-issues] [Bug]: .jasp file does not open / load after downloading newest version of the tool (Issue #2517)


Do you remember the version with which you created this file?

**Comment by RensDofferhoff** [comment]
Very interesting bug!
Do you remember how you generated the "Umweltverhalten gesamt DT" column.
This is the source of the fault.
Its seems you generated it using the computed column feature but the 'formula' is gone and no information on how to generate it is stored anymore.

I tweaked the JASP file by hand so it is no longer a computed column. Now it opens again. Please check that it is in order:
[data_environmentalbehaviour__v8_fixed.zip](https://github.com/jasp-stats/jasp-issues/files/13858428/data_environmentalbehaviour__v8_fixed.zip)

Of course there is an underlying issue that caused this file to generate this way. We need to resolve this so any information on the history of this file is helpful!

**Comment by RensDofferhoff** [comment]
@JorisGoosen what do you make of the internal db state.
Perhaps we should just make columns codetypes revert to normal columns and throw a warning instead letting the error propagate.

**Comment by boutinb** [comment]
We will make a new version soon (hopefully this week) that fixes this issue.

**Comment by LindaHoffmann** [comment]
Thank you so much for the super quick help! Yes, I could open the fixed file that you've sent me 🙂

________________________________
Von: RensDofferhoff ***@***.***>
Gesendet: Montag, 8. Januar 2024 11:05
An: jasp-stats/jasp-issues ***@***.***>
Cc: LindaHoffmann ***@***.***>; Author ***@***.***>
Betreff: Re: [jasp-stats/jasp-issues] [Bug]: .jasp file does not open / load after downloading newest version of the tool (Issue #2517)


@JorisGoosen<https://github.com/JorisGoosen> what do you make of the internal db state?
Perhaps we should just make columns codetypes revert to normal columns and throw a warning instead letting the error propagate.
