### ISSUE TITLE
[Bug]: CSV Data Import: Incorrect handling of decimal separators

### ISSUE THREAD

**Issue by Ambroise-D** [jasp-stats/jasp-issues#2518]
### JASP Version

0.18.2

### JASP Module

Other

### What analysis are you seeing the problem on?

Data editing module

### What OS are you seeing the problem on?

Windows 10

### Bug Description

After upgrading from JASP 18.1 to 18.2, I've noticed that the software now interprets decimal separators in CSV files incorrectly. Specifically, it reads variables as text type because it don't treats commas as decimal separators (or it don't modify it to dot). This behavior was not present in JASP 18.1. where csv with commas were properly imported by program. 
![jasp_comparission](https://github.com/jasp-stats/jasp-issues/assets/155983415/cf4243ce-660d-4c31-82d3-2f0fe570c5a4)

### Expected Behaviour

I would expect JASP 18.2 to read variables with commas as decimal separators as continuous variables, similar to how it was handled in JASP 18.1.

### Steps to Reproduce

1. Import a CSV file with variables that contain commas as decimal separators.
2. Observe that JASP 18.2 interprets these variables as text types instead of continuous variables.
3. Verify that the same CSV file was correctly imported in JASP 18.1, with variables interpreted as continuous variables.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
This is a known issue (cf. https://github.com/jasp-stats/jasp-issues/issues/2499), and we will make a hotfix release asap.
