### ISSUE TITLE
[Bug]: Computed column with arithmetic operations on Scalar & Nominal vars return no errors

### ISSUE THREAD

**Issue by RensDofferhoff** [jasp-stats/jasp-issues#2520]
### JASP Version

0.18.2

### Commit ID

96d6b46acbf3820f9c603b6b76911cf6fe052e76

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 10

### Bug Description

Computed column with arithmetic operations on Scalar & Nominal vars return no errors.
The cells simply get cleared/stay empty.
These operations are not allowed in the drag and drop interface.

### Expected Behaviour

Either we should return a nice error for all nominal and scalars.
Or we should allow these operations for scalar and integer nominal and only throw error for nominal Text

### Steps to Reproduce

1. Open debug dataset
2. Create computed column
3. Enter facFive * 2 in R field
4. Compute it
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by RensDofferhoff** [comment]
@JorisGoosen  Its not critical for this hotfix I think.
But one of us should pick this up later.

**Comment by JorisGoosen** [comment]
I dont think allowing nominal + scalar operations is a good idea. It would be better to throw an error for that
Nominal does mean there is no implied distance between elements. In this regard there is no difference between it and nominal text.

For ordinal we could take the level as number and make operations possible though.

**Comment by tomtomme** [comment]
@JorisGoosen & @shun2wang 
Also fine. But then, please make this happen: https://github.com/jasp-stats/jasp-issues/issues/2065

**Comment by JorisGoosen** [comment]
So for syntax mode we have a bunch of plans laying around and one of them includes better handling of the data from JASP in R.

Im linking this here: https://github.com/jasp-stats/INTERNAL-jasp/issues/2332 but it is an internal issue so not everyone might have access. When implementing that we can keep this in mind for sure.

**Comment by JorisGoosen** [comment]
Ive implemented a feature in computed columns where you can "force" the input columntype to the outputtype.
