### ISSUE TITLE
[Feature Request]: Output factor loadings when computing frequentist McDonald's omega

### ISSUE THREAD

**Issue by wolfvanpaemel** [jasp-stats/jasp-issues#2525]
### Description

Output factor loadings when computing frequentist McDonald's omega (it is offered as an option in the Bayesian version)

### Purpose

increase consistency with Bayesian version

### Is your feature request related to a JASP module?

Reliability

### Describe the solution you would like

Give users the possibility to ask for factor loadings when computing frequentist McDonald's omega (like in the Bayesian version)

**Comment by juliuspfadt** [comment]
Perfectly valid request!
