### ISSUE TITLE
[Bug]: website issues for 0.18.3

### ISSUE THREAD

**Issue by richlv** [jasp-stats/jasp-issues#2528]
### JASP Version

0.18.2

### Bug Description

I'd ping @JASPStats@fosstodon.org , but it doesn't seem to be active much :)

A few issues on the website regarding the 0.18.3 release:

a) https://jasp-stats.org/download/ claims it was released on "January 2nd, 2024" - seems to be Jan 12th actually.
b) Issue links in https://jasp-stats.org/release-notes/ are broken for this version, for example:
```
<a href"https:="" github.com="" jasp-stats="" jasp-issues#2515="">2515</a>
```
### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Thank you really much for telling us these mistakes. I've just fixed it.

**Comment by boutinb** [comment]
Oops, I was really not careful. Thanks again! I've corrected the links.

**Comment by richlv** [comment]
Thank you :)
