### ISSUE TITLE
Dutch localization

### ISSUE THREAD

**Issue by djdekker** [jasp-stats/jasp-issues#253]
* Enhancement: add Dutch localization to JASP
* Purpose: to make JASP more accessible to users who are not proficient in English
* Use-case: use in Dutch high school where pupils are required to use JASP to learn frequentist statistics for their thesis research

**Is your feature request related to a problem? Please describe.**
Our pupils are 16 to 18 years old and are not at all used to statistical terms in English. They are taught statistics in the Dutch language. So translating JASP into Dutch would make JASP a lot more accessible to them.

**Describe the solution you'd like**
Create a Dutch localization of JASP.

**Describe alternatives you've considered**
1. Teaching in English is no option at our Dutch school.
2. Using SPSS 25 is no option because it has no Dutch localization either. And it is too expensive.
3. Using PSPP 1.2.0 is no option: although it has Dutch localization, it lacks the ease of use of JASP.

**Comment by JorisGoosen** [comment]
JASP is nu ook beschikbaar in het nederlands
