### ISSUE TITLE
[Bug]: Binary Classification > Load data and specify... fails to accept continuous ("Marker") and binary discrete ("Positive condition") variables

### ISSUE THREAD

**Issue by tomcipco** [jasp-stats/jasp-issues#2531]
### JASP Version

0.18.3

### JASP Module

Learn Bayes

### What analysis are you seeing the problem on?

Binary Classification

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

This analysis terminated unexpectedly.

Error: Unable to call JAGS

Stack trace
withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.bcComputeResults(jaspResults, dataset, options, ready)

.bcComputeResultsFromData(options, dataset, ready)

.bcDrawPosteriorSamples(newOptions)

.bcRunJags(model = .bcJagsModel, monitor = c('prevalence', 'sensitivity', 'specificity'), data = jags_data, summarise = FALSE, sample = options[['samples']], burnin = options[['burnin']], thin = options[['thinning']], n.chains = options[['chains']], silent.jags = TRUE, inits = inits)

runjags::run.jags(...)

setup.jagsfile(model = model, n.chains = n.chains, data = data, inits = inits, monitor = monitor, modules = modules, factories = factories, jags = jags, call.setup = TRUE, method = method, mutate = mutate)

setup.jags(model = outmodel, monitor = outmonitor, data = outdata, n.chains = n.chains, inits = outinits, modules = modules, factories = factories, response = response, fitted = fitted, residual = residual, jags = jags, method = method, mutate = mutate)

stop('Unable to call JAGS', call. = FALSE)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

### Expected Behaviour

Calculation of classification estimates plus ROC analysis based on a continuous variable (="Marker") and a discrete/nominal variable (=Positive Condition(binary))

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by tomcipco** [comment]
@Kucharssim, thanks for the reply.
screenshot and subset of data file added - thank you!
![binary classification issue](https://github.com/jasp-stats/jasp-issues/assets/94222723/1d93192e-463d-4169-9347-bb10329a0efd)
[subset.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/13962002/subset.jasp.zip)

**Comment by Kucharssim** [comment]
Dear @tomcipco,

thanks for sending the files!

The problem doesn't seem to be in the analysis not accepting the data, but it seems JAGS cannot be called for some reason.  The analysis with your data runs fine on my computer (Apple Silicon). Just to double check, can you try if you get any output if you switch `Input type` to `Uncertain estimates`? Alternatively, does the JAGS module in JASP work for you?

**Comment by tomcipco** [comment]
@Kucharssim , Uncertain estimates also produces the same error message as described.
How can I test if the JAGS module works properly?
Thanks!
![binary classification issue 2](https://github.com/jasp-stats/jasp-issues/assets/94222723/596b89d1-1bbc-4797-af68-81d95c893a53)

**Comment by Kucharssim** [comment]
Thanks for the info!

> How can I test if the JAGS module works properly?

For example, you can download this .jasp file (https://osf.io/ewqha), open it in JASP, and refresh the analysis (click on the triangle next to the title in the output, and select "Refresh all").

**Comment by tomtomme** [comment]
@tomcipco 
The subset.jasp file also works fine for me on jasp 0.18.3 flatpak (linux)
Maybe the macbook needs a restart or a re-install of jasp. If jasp was updated several times there may also be some old / invalid configs, so uninstalling / reinstalling may do the trick? At least on linux deleting old configs and starting completely fresh fixed some stuff in the past for me. Not lately however...

**Comment by tomcipco** [comment]
@Kucharssim, thank you for the Malaria Rapid Diagnostic Test-data.
The JAGS module refresh worked out of the box.
However after @tomtomme 's hints "restart or a re-install of jasp" did not reveal any positive results...
Cheers

**Comment by geblogt** [comment]
> Thanks for the info!
> 
> > How can I test if the JAGS module works properly?
> 
> For example, you can download this .jasp file (https://osf.io/ewqha), open it in JASP, and refresh the analysis (click on the triangle next to the title in the output, and select "Refresh all").

How should I do this. I am to dumb for this, sorry!

**Comment by tomcipco** [comment]
??? @geblogt, it's clearly described by @Kucharssim.
Download the file, open the file within JASP and refresh the analysis...
Compared to my issue described in #2537, testing the functionality of the JAGS module as @Kucharssim explained works at least for me...
Cheers

**Comment by tomtomme** [comment]
@Kucharssim 
who on the team has a macOS intel machine to check this?

**Comment by RensDofferhoff** [comment]
@Kucharssim What version are you running?
I can reproduce this on both apple silicon and intel macs

**Comment by geblogt** [comment]
> ??? @geblogt, it's clearly described by @Kucharssim. Download the file, open the file within JASP and refresh the analysis... Compared to my issue described in #2537, testing the functionality of the JAGS module as @Kucharssim explained works at least for me... Cheers

Ok Thank you, but it does not work on my Mac if I do it the described way. Therefore I kindly asked if someone could explain it to me...

**Comment by Kucharssim** [comment]
> What version are you running?

I am running the official release 0.18.3, https://github.com/jasp-stats/jasp-desktop/commit/123cb32f4f0459196195787e819b249bfd8677aa

**Comment by RensDofferhoff** [comment]
How strange, I have the same version.
Do you have jags installed standalone perhaps? (on path).

@JorisGoosen Can you also reproduce this?

**Comment by RensDofferhoff** [comment]
JAGS  module is working btw

**Comment by Kucharssim** [comment]
> Do you have jags installed standalone perhaps? (on path).

Yeah I do...

**Comment by RensDofferhoff** [comment]
So I confirmed it only works if you install jags https://sourceforge.net/projects/mcmc-jags/.

I have no clue why it doesnt take the jags in the package but will try to find it out

**Comment by JorisGoosen** [comment]
> How strange, I have the same version. Do you have jags installed standalone perhaps? (on path).
> 
> @JorisGoosen Can you also reproduce this?

Yes it is broken on my system too (and I dont have JAGS installed indeed)

**Comment by tomtomme** [comment]
This is not problem with the flatpak release. Works fine for me. I checked and I do not have jags installed externally.

**Comment by boutinb** [comment]
Also broken on my Mac ARM (No JAGS installed)

**Comment by RensDofferhoff** [comment]
@tomtomme Yes its only on Mac.
Windows and linux are fine.
I will try to figure out why this happened

**Comment by tomcipco** [comment]
> So I confirmed it only works if you install jags https://sourceforge.net/projects/mcmc-jags/.
> 
> I have no clue why it doesnt take the jags in the package but will try to find it out

@RensDofferhoff: I "manually" installed jags from the mentioned source (https://sourceforge.net/projects/mcmc-jags/).
After restarting JASP the binary classification module seems to work properly.
Thanks, Tom

**Comment by JorisGoosen** [comment]
Also broken on windows...

**Comment by RensDofferhoff** [comment]
could you try msix? just for my sanity.
This issue might be more difficult than I thought.

**Comment by JorisGoosen** [comment]
Ive tested the zip of 0.18.3 and it is also broken

**Comment by RensDofferhoff** [comment]
This issue should be resolved in the next release!
