### ISSUE TITLE
Change Variable Settings / Label Editor results in Crash [Bug]: 

### ISSUE THREAD

**Issue by zacmessick** [jasp-stats/jasp-issues#2533]
### JASP Version

0.18.3

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 11

### Bug Description

This bug happens under two conditions. First, if I try changing a column type, the system freezes, gives me a "not responding" error, and typically crashes. Second, if I exclude a single observation (or an entire group in a nominal set) by clicking on the check-mark to make it an X, the same thing occurs: the system freezes, I get the "not responding" error, and it typically crashes.

### Expected Behaviour

Ideally, I would be able to change the column type and include/exclude individual observations or groups without the system crashing. 

### Steps to Reproduce

1. Double click on a column title to change variable settings
2. Click on a check mark to try to exclude the observation
3.
...
![image](https://github.com/jasp-stats/jasp-issues/assets/78495882/6aaa8ccc-5db9-49ef-94bf-d8751c9cebb7)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
According to your screenshot, your file resides on OneDrive. Does this happen, if you save the file locally too? Also - could you share the .jasp file you used? You can change the file ending from .jasp to .zip or something and then upload it here.

**Comment by zacmessick** [comment]
Good point re: OneDrive. Unfortunately, after I moved the file locally the same issue still occurred. 

Because much of the data that I have is sensitive, I tried making a fake data set to send with the issue. In the fake set that I made, I was able to modify the labels and create exclusions without any issue.
Thus, I believe the issue is actually caused by the fact that I typically first do a set of analyses (e.g., RM ANOVA and descriptives) and _then_ do exclusions. To confirm this, I just removed all of my analyses from one of the files that crashes and, indeed, I was able to manipulate the columns/labels/exclusions.
Is this typical? i.e., is it common that removing an observation leads to a crash if a set of analyses have been conducted?

**Comment by tomtomme** [comment]
I have never experienced it. Maybe the analysis you run is overwhelming your PC? How much RAM is used by JASP when you have run the analyses and how much is still free?
RM anovas with big data can be quite demanding

**Comment by RensDofferhoff** [comment]
How large is your dataset approximately?

**Comment by zacmessick** [comment]
Not particularly large. Typically up to 40 columns with 16-32 observations in the rows.
My best guess is that running multiple RM ANOVAs is stressing the engines, even though my computer’s memory and CPU are not spiking

Zachary Pierce-Messick
________________________________

**Comment by tomtomme** [comment]
@zacmessick 
I have seen many similar bugs during the last week going through old issues - RM ANOVA related. For such an analysis 40 x 16 is not small and needs quite some compute. 

However - On my linux machine I have no problem to change scale or add filters during such a heavy computation. Just tested with 0.18.3. So this might be windows 11 related. Or my pc is just fast enough - recent 8 core AMD processor, 32 GB RAM.

So if I understand you correctly: You first let all your analysis finish - and then the problem goes away?

**Comment by boutinb** [comment]
Difficult to guess what happens on your PC, since we cannot reproduce this problem.
What can help is if you can send us the log files (https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/user-guide/logging-howto.md).
You can also open the Engines Overview: In Preferences/Advanced/Engine options, click on the "Show Engines" button, so that you can see the state of the engines. Can you describe us what you see when JASP freezes?

**Comment by tomtomme** [comment]
@zacmessick 
please reopen, if you can share more details, like the points boutinb raised above.
Thx!

**Comment by zacmessick** [comment]
Hi Thomas. Thanks for the followup. As someone else suggested, it appears that the issue is due to how many repeated measures analyses I use in a single JASP file. If I use one or two, then I am able to modify the data without issue. More than that, however, leads to it crashing. My workaround is keeping separate analyses in separate JASP files.


________________________________

**Comment by zacmessick** [comment]
My assumption is that it stems from limitation of my CPU. It doesn't prohibit any analyses (I’m able to run mixed ANOVAs with multiple factors and many levels). It’s mildly inconvenient to have to either delete analyses or start a new file to change variables, but it isn’t the end of the world.
It’s when I have, for example, a 2x2x10 ANOVA. I need to keep that jasp file pretty much dedicated to that one analysis rather than including another of similar size.
________________________________

**Comment by tomtomme** [comment]
@zacmessick 
What CPU model do you have exactly and how much RAM? And do you use an SSD or an HDD?

**Comment by zacmessick** [comment]
I'm working with a Surface Pro 8.
8gb RAM, i5- Intel processor, SSD.


________________________________

**Comment by tomtomme** [comment]
@zacmessick 
yeah thats a nice portable. But its not really for heavy computing. The CPU can sustain only 15W loads for longer and throttles to 2Ghz then. The 8GB of RAM should be fine because the data set is not that large. For reference, I have seen bigger sets eating up 12GB of RAM on my machine here https://github.com/jasp-stats/jasp-issues/issues/617
So yeah, I think we cannot do much about it. Sorry.
