### ISSUE TITLE
[Bug]: JASP-non-normal-distribution-issue

### ISSUE THREAD

**Issue by VesnaBoskov** [jasp-stats/jasp-issues#2536]
### JASP Version

0.18.1

### JASP Module

Quality Control

### What analysis are you seeing the problem on?

Process Capability Study

### What OS are you seeing the problem on?

Windows 10

### Bug Description

This analysis terminated unexpectedly.

Error in fitdistrplus::fitdist(data, 'lnorm', method = 'mle', control = list(maxit = 500, : the function mle failed to estimate the parameters, with the error code 100

![Process Capability Study issue](https://github.com/jasp-stats/jasp-issues/assets/157103906/0aba5b9c-786e-4c04-a858-73332bc08540)
[inter diameter_DAYE.zip](https://github.com/jasp-stats/jasp-issues/files/13987261/inter.diameter_DAYE.zip)

### Expected Behaviour

During the JASP Process CapabilityStudy  with a non-normal distribution, an error occurred: 

Error in fitdistrplus::fitdist(data, 'lnorm', method = 'mle', control = list(maxit = 500, : the function mle failed to estimate the parameters,with the error code 100 .

If I use chose normal distribution - no issue (see picture attached)
![Process Capability Study_Normal distribution](https://github.com/jasp-stats/jasp-issues/assets/157103906/aaa76d72-7abe-4b3d-a4aa-168e52922c5b)
But distribution is Non-normal, so the report is incorrect.

### Steps to Reproduce

1. Quality Control
2.Process CapabilityStudy 
3. Non-normal distribution
...

### Log (if any)

[JASP 2024-01-19 09_04_17 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/13987230/JASP.2024-01-19.09_04_17.Desktop.log)
[JASP 2024-01-19 09_04_17 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/13987231/JASP.2024-01-19.09_04_17.Engine.0.log)
[JASP 2024-01-19 09_04_17 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/13987232/JASP.2024-01-19.09_04_17.Engine.1.log)
[JASP 2024-01-19 10_40_29 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/13987233/JASP.2024-01-19.10_40_29.Desktop.log)
[JASP 2024-01-19 10_40_29 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/13987234/JASP.2024-01-19.10_40_29.Engine.0.log)
[JASP 2024-01-19 10_41_36 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/13987235/JASP.2024-01-19.10_41_36.Desktop.log)
[JASP 2024-01-19 10_41_36 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/13987236/JASP.2024-01-19.10_41_36.Engine.0.log)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JTPetter** [comment]
@VesnaBoskov Thank you for reporting. This error means that the distribution could not be fitted to your data. I believe this usually happens if the data are very extreme or very differently distributed than the selected distribution. The next versions of JASP contain a clearer error message. 

@Kucharssim Do you maybe have a better understanding of this error? Is there anything I can do to prevent this, for instance increasing the iterations?

**Comment by VesnaBoskov** [comment]
Thank you very much for fast answer. 

Unfortunately, increasing the number of repetitions is not possible. We have no more samples - we had a limited amount of material to test. All the material has been used up (these are samples from the new material supplier).

If the distribution were normal, the JASP Process Capability Analysis report would be OK, but distribution is non - normal (it makes sense, because we use a small sample - a fraction from the supplier's production - therefore it cannot have a normal distribution)

**Comment by VesnaBoskov** [comment]
"I believe this usually happens if the data are very extreme or very differently distributed than the selected distribution" . 

Can you help me - what kind of distribution is this?
![Distribution](https://github.com/jasp-stats/jasp-issues/assets/157103906/006154bd-2b7d-46ac-8f7b-d1d27017b39b)

**Comment by JTPetter** [comment]
@VesnaBoskov I was referring to the number of iterations in the mathematical estimation of the parameters, not in your sample. Your data does not appear to resemble any of the distributions available in JASP. Maybe one of the 3-parameter distributions (lognormal or Weibull) might be able to run without an error, but I doubt the fit will be great...

**Comment by VesnaBoskov** [comment]
Thank you, I already tried, JASP accepts Weibull distribution (not 3-parameter Weibull).
![Distribution_Weibull](https://github.com/jasp-stats/jasp-issues/assets/157103906/73796ee6-797b-446d-95ab-232bc7a13cb7)

**Comment by EJWagenmakers** [comment]
This distribution seems bimodal (this can be fit using the Distributions module). The time series suggests a trend. It may not be very reasonable to summarize such non-stationary data with a distribution to begin with.
EJ

**Comment by VesnaBoskov** [comment]
Thank you very much for the answers. I will check with my team.

**Comment by tomtomme** [comment]
@VesnaBoskov 
Do you have any updates? 
I mark this as a feature request to make the error message more informative since JTPetter is already working on that via the linked pull request above.

**Comment by VesnaBoskov** [comment]
I don't have any update. You can close this issue alert.
Thanks to the whole team for their help.
