### ISSUE TITLE
[Bug]: Unable to call JAGS error in binary classification

### ISSUE THREAD

**Issue by geblogt** [jasp-stats/jasp-issues#2537]
### JASP Version

0.18.3

### JASP Module

Learn Bayes

### What analysis are you seeing the problem on?

not able to create a ROC due to error

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

Trying to make a binary classification. 
Error field: 
"The analysis terminated unexpectedly.
Error: Unable to call JAGS
withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.bcComputeResults(jaspResults, dataset, options, ready)

.bcComputeResultsFromData(options, dataset, ready)

.bcDrawPosteriorSamples(newOptions)

.bcRunJags(model = .bcJagsModel, monitor = c('prevalence', 'sensitivity', 'specificity'), data = jags_data, summarise = FALSE, sample = options[['samples']], burnin = options[['burnin']], thin = options[['thinning']], n.chains = options[['chains']], silent.jags = TRUE, inits = inits)

runjags::run.jags(...)

setup.jagsfile(model = model, n.chains = n.chains, data = data, inits = inits, monitor = monitor, modules = modules, factories = factories, jags = jags, call.setup = TRUE, method = method, mutate = mutate)

setup.jags(model = outmodel, monitor = outmonitor, data = outdata, n.chains = n.chains, inits = outinits, modules = modules, factories = factories, response = response, fitted = fitted, residual = residual, jags = jags, method = method, mutate = mutate)

stop('Unable to call JAGS', call. = FALSE)

### Expected Behaviour

it should give me a binary classification with the given data.

### Steps to Reproduce

I can
1. take my data
2. choose Learn Bayes > binary classification
3. Load data and specify threshold
4. give marker (Screening test)
5. give positive condition (an other screening tests result (positive and negative))
6. 
7. 
...

### Final Checklist

- [x] I have included a screenshot showcasing the issue, if possible.
- [x] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [x] I have accurately described the bug, and steps to reproduce it.

**Comment by geblogt** [comment]
![Bildschirmfoto 2024-01-19 um 11 27 59](https://github.com/jasp-stats/jasp-issues/assets/157113118/20b94094-ad19-47eb-9975-62736911fef8)

**Comment by geblogt** [comment]
As the data belongs to an ongoing study, I cannot upload it as a zip file due to data protection guidelines.

**Comment by geblogt** [comment]
Furthermore: The bug occurs when the data is set like in the following pic:
![Bildschirmfoto 2024-01-19 um 11 33 06](https://github.com/jasp-stats/jasp-issues/assets/157113118/306e2c4a-12bf-4c44-918c-05c7bc427582)

**Comment by geblogt** [comment]
If I change it, another error occurs, as you can see in the following two pictures:
![Bildschirmfoto 2024-01-19 um 11 34 20](https://github.com/jasp-stats/jasp-issues/assets/157113118/599084b0-ee47-448f-a23f-e6f8fdcc8c81)
![Bildschirmfoto 2024-01-19 um 11 34 39](https://github.com/jasp-stats/jasp-issues/assets/157113118/29d8d6f2-9964-4013-b1a2-a1142a06954c)
This error can (of course) not be solved since the screening test both are positive (patient sick) if a patient scores fewer points.

**Comment by tomtomme** [comment]
@Kucharssim 
https://github.com/jasp-stats/jasp-issues/issues/2531 seems to be the same bug 

Maybe isolated to macos intel

**Comment by RensDofferhoff** [comment]
As a workaround you could install jags https://sourceforge.net/projects/mcmc-jags/ standalone.
The analysis will work again.

We will try to fix this for the next version of jasp

**Comment by RensDofferhoff** [comment]
This should be fixed in the next release!
