### ISSUE TITLE
[Bug]:sync data is not synchronized all the time and results for baysian is computing all the time without results 

### ISSUE THREAD

**Issue by YaoOlivia** [jasp-stats/jasp-issues#2538]
### JASP Version

0.18.3

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

repeated measures ANOVA

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

<img width="1532" alt="baysian computing all the time" src="https://github.com/jasp-stats/jasp-issues/assets/157116005/60256ea8-7895-4c64-9c63-578029b47197">

### Expected Behaviour

i hope, after click on "refresh results", i can get updated results 

### Steps to Reproduce

1. open an existing .jasp file which was i created with analysis previously
2. Sync data-computer-"an updated .csv file"
3. "refresh all" in results part
<img width="1046" alt="step2" src="https://github.com/jasp-stats/jasp-issues/assets/157116005/d47391d2-f252-46bb-ac1a-b0df68d5b48d">
<img width="746" alt="step3" src="https://github.com/jasp-stats/jasp-issues/assets/157116005/c18a531e-7ff2-4da8-b0de-91ba8859e3f2">
 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Could you share the jasp file? Rename it to "something.zip" first, then drag and drop it here.

**Comment by tomtomme** [comment]
I guess this already answers the question to all your trouble. If you try a RM ANOVA on such big data, computation may need hours and even more for a RM BANOVA. I experienced it even with a very fast machine!
Even only data synchronization may need a minute or two, if you change big chunks of your data.
You can mail the jasp file to my work-mail thomas.langkamp@medicalschool-hamburg.de or to the jasp team (I guess [info@jasp-stats.org](mailto:info@jasp-stats.org)) - if you want us to check it out.

**Comment by YaoOlivia** [comment]
Hi Thomas, thanks! i will send you emails about it. Actually, i don't think my data is very big, i only have 65 participants.

**Comment by tomtomme** [comment]
depending on the number of RMs this might be quite large already for a bayesian rm anova - you are on an intel mac - so thats an older laptop and I still guess you will have to wait over night to let the analysis finish. 
I have not received your file yet. Is it to large for email too? then maybe upload it to some cloud and share the link

**Comment by tomtomme** [comment]
also we had bugs like this: https://github.com/jasp-stats/jasp-issues/issues/1391
a user that probably overwhelmed his pc doing over 50 analysis. Seeing that your file is 51 MB in size, this might be the case here too

**Comment by YaoOlivia** [comment]
Hi Thomas! Sorry i tried to send email to you but also it said the zip file is too big. But I think maybe you are right, I have approximate 40 analysis in one file. I will split the analysis first and let you know whether it works! Thanks and Schönes Wochenende :)

**Comment by tomtomme** [comment]
Dir auch ein schönes :)

**Comment by boutinb** [comment]
I did some tests and my results are automatically refreshed when I synchronize a JASP file with another dataset (this is a feature which is tested for each release, but you never know...).
Just a question: if you don't synchronize, but just refresh all your analyses in your JASP file, how long does it take to recompute all the analyses?

**Comment by YaoOlivia** [comment]
> I did some tests and my results are automatically refreshed when I synchronize a JASP file with another dataset (this is a feature which is tested for each release, but you never know...). Just a question: if you don't synchronize, but just refresh all your analyses in your JASP file, how long does it take to recompute all the analyses?

it takes a long time to refresh baysian anova results! (maybe hours, i ran again on two computers, with windows version 0.18.3. They all need more than two hours and on my mac laptop, the procedure seems never finished running. However, when i use windows version 0.15.0.0, it only needs less than 5min :(

**Comment by boutinb** [comment]
So I think this is just a PC capacity issue. 40 bayesian analyses in one file can be quite heavy indeed, so I would just split this file, or use this 0.15 windows PC, that seems really powerful!
I close this issue. If you have other remarks, just reopen it.

**Comment by YaoOlivia** [comment]
> So I think this is just a PC capacity issue. 40 bayesian analyses in one file can be quite heavy indeed, so I would just split this file, or use this 0.15 windows PC, that seems really powerful! I close this issue. If you have other remarks, just reopen it.

Hi, could you have a look at my file? i split it but it still takes very long time to refresh...

**Comment by tomtomme** [comment]
@YaoOlivia 
I can take a look, if you upload.

However - you did not mean to say windows 0.15, did you? Were you talking about jasp 0.15 and that that only needs 5 min?
@boutinb  - would that be possible? Some fundamental change in bayesian computation between 0.18 and 0.15?

**Comment by YaoOlivia** [comment]
> @YaoOlivia I can take a look, if you upload.
> 
> However - you did not mean to say windows 0.15, did you? Were you talking about jasp 0.15 and that that only needs 5 min? @boutinb - would that be possible? Some fundamental change in bayesian computation between 0.18 and 0.15?


[paradigm_analysis_1_three factors baysian.zip](https://github.com/jasp-stats/jasp-issues/files/14024633/paradigm_analysis_1_three.factors.baysian.zip)

Hi Thomas, I mean 0.18 for both windows and mac os, they run very slow especially for three-way baysian anova (see attachment).

**Comment by EJWagenmakers** [comment]
We changed the RM ANOVA to include random effects, see https://jasp-stats.org/2022/07/29/bayesian-repeated-measures-anova-an-updated-methodology-implemented-in-jasp/
You can still select the old analysis, or use the Laplace approximation. Does that help?
EJ

**Comment by YaoOlivia** [comment]
> > @YaoOlivia I can take a look, if you upload.
> > However - you did not mean to say windows 0.15, did you? Were you talking about jasp 0.15 and that that only needs 5 min? @boutinb - would that be possible? Some fundamental change in bayesian computation between 0.18 and 0.15?
> 
> [paradigm_analysis_1_three factors baysian.zip](https://github.com/jasp-stats/jasp-issues/files/14024633/paradigm_analysis_1_three.factors.baysian.zip)
> 
> Hi Thomas, I mean 0.18 for both windows and mac os, they run very slow especially for three-way baysian anova (see attachment).

BTW, for this analysis procedure with four three-factor RM baysian anova (attached), i have spent one day to refresh the results, and it is still on going on computing the Bayes factors for the second analysis...

**Comment by YaoOlivia** [comment]
> We changed the RM ANOVA to include random effects, see https://jasp-stats.org/2022/07/29/bayesian-repeated-measures-anova-an-updated-methodology-implemented-in-jasp/ You can still select the old analysis, or use the Laplace approximation. Does that help? EJ

Hi EJ, thanks for your reply. Is there any computing speed difference between the older version and newer version? Because now i am using the newer version and it's extremely slow...

**Comment by tomtomme** [comment]
@YaoOlivia 
Yes, the inclusion of random effects certainly impacts computation time. That is why EJ suggests the faster approximation.

**Comment by YaoOlivia** [comment]
Dear all,
Thanks for your help! I tried the laplace approximation in the addition panel, it runs very fast now!
