### ISSUE TITLE
[Bug]: Data disappear when changing column type 

### ISSUE THREAD

**Issue by amielaugustin** [jasp-stats/jasp-issues#2539]
### JASP Version

0.18.1

### JASP Module

Other

### What analysis are you seeing the problem on?

Just a data editing problem

### What OS are you seeing the problem on?

Windows 10

### Bug Description

Hello everybody, 

In the data editing, I've created a new column with a continuous variable. I copied and pasted the data from another column which was by default an ordinal variable that I turned into a continuous variable. I've first defined my column as a continuous variable before copy and paste the data, and when I copy and paste, the variable turns automatically in an ordinal type. So then, I change the variable type and when I do it, then the data just disappear. Someone has an explanation for that ? Something that can be important for you to know is the fact that I have a filter on my data, and some lines (participants) are just not taken into account but this is before the copy and paste, so it shouldn't change anything. If you need more information feel free to ask. If this is something that can help you more, data ranges in a scale from 1 to 7. 

Thanks a lot for reading,
Augustin 

### Expected Behaviour

I would have expected that the data remain in the variable type that I had specified and that no data disappear when I change back the variable type.

### Steps to Reproduce

1. Create a new column in a data set 
2. Apply a filter which doesn't take into account some of the lines 
3. Copy and paste another column from the data set. 
... 

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
There was a filter bug in 0.18.1 and I also saw this "data disappering" stuff with data from one of my students. Data editing was very new and a bit buggy in that version. So could you try the current version 0.18.3 and try it there?

**Comment by amielaugustin** [comment]
Thank you for your reply tomtomme. I'll download the new version and let you know if something changes.

**Comment by amielaugustin** [comment]
Unfortunately it still doesn't work even with the last version of JASP..

**Comment by amielaugustin** [comment]
Ohhh that's fine, I know what was the problem. I've created a function column instead of a variable column. And by doing this we need to define the type of computed column that we want. And we can choose for example "drag-and-drop", which I did, and now it's working. Do I need to close this issue if it's fixed ? 

Thanks for your help

**Comment by tomtomme** [comment]
Happy to hear its solved. Closing then.
