### ISSUE TITLE
explained variance-R2 in lavaan output

### ISSUE THREAD

**Issue by BTunca** [jasp-stats/jasp-issues#254]
Hi!

I was wondering whether it is possible to get the R2 values for dependent variables in lavaan-SEM output to report explained variance. 

As far as I know it can be called in R with "inspect(fit, 'r2')" command.

Thank you very much for your consideration,

B.Tunca

**Comment by vankesteren** [comment]
You can look forward to this in the next version of JASP!

![afbeelding](https://user-images.githubusercontent.com/11596858/55788939-9ebac280-5ab9-11e9-9bb0-8c2ca22183ce.png)

**Comment by BTunca** [comment]
Beautiful! Thank you!
