### ISSUE TITLE
[Bug]: Supporters missing in  JASPs community window

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#2540]
### JASP Version

0.19 beta

### Bug Description
Missing in community window

- [NSDSK](https://www.nsdsk.nl/) Academy (The Dutch Foundation for the Deaf and Hard of Hearing Child)
- [The Department of Communication at Appalachian State University](https://communication.appstate.edu/)

Community window within jasp could be updated automagically by pointing to https://jasp-stats.org/community-institutional-members/ 

### Steps to Reproduce

1.click jasps blue hamburger button
2.click community
3.see missing supporters

**Comment by tomtomme** [comment]
done since newes 0.19 beta

**Comment by tomtomme** [comment]
Strange - was the patch reverted? The two bronze educators are missing again!

![image](https://github.com/jasp-stats/jasp-issues/assets/4428185/d0894fb4-1887-487e-91e0-f7df4f9cd305)

**Comment by JorisGoosen** [comment]
Huh? Oops I guess

**Comment by JorisGoosen** [comment]
I dont think they were ever added to JASP?
But anyway, Ill do it now.
