### ISSUE TITLE
[Feature Request]: flexible permutation times in the feature importance function of machine learning model

### ISSUE THREAD

**Issue by rd24911** [jasp-stats/jasp-issues#2543]
### Description

thank you for adding feature importance function in the new version of machine learning modules! That helps a lot. However, I found the ranking of important features is not very stable by 50 permutations. I know it could be a limitation of dataset but would it be possible to add flexible permutation choices(e.g. 50, 100, 1000 permutations?)

### Purpose

improve the explanability of machine learning models

### Is your feature request related to a JASP module?

Machine Learning

### Describe the solution you would like

flexible permutation choices(e.g. 50, 100, 1000 permutations?)

### Describe alternatives that you have considered

either a fixed choices or a manually adjustable option would be nice

### Additional context

I'm quite new to JASP and thank you a lot to develop such a user-friendly and powerful statistical software!

**Comment by koenderks** [comment]
Good idea @rd24911, for large datasets a large number of permutations can be very slow but it's always good to have the option to adjust based on your preferences. I've implemented this now, hopefully will be in the next version.
