### ISSUE TITLE
Error in validObject(.Object): invalid class 'Fit' object: invalid object for slot 'fx.group' in class 'Fit': got class 'NULL', should be or extend class 'numeric'

### ISSUE THREAD

**Issue by Patriciajro** [jasp-stats/jasp-issues#2545]
### JASP Version

0.18.3

### JASP Module

SEM

### What analysis are you seeing the problem on?

Strutural Equation Modeling

### What OS are you seeing the problem on?

Windows 11

### Bug Description

This analysis terminated unexpectedly.

Error in validObject(.Object): invalid class 'Fit' object: invalid object for slot 'fx.group' in class 'Fit': got class 'NULL', should be or extend class 'numeric'

Stack trace
.semMITable(fit, modelname, modindices, options, ready)

lavaan:::modificationIndices(fit)

lav_object_extended(object, add = FULL, all.free = TRUE)

lavaan(LIST, slotOptions = lavoptions, slotSampleStats = object@SampleStats, slotData = object@Data, slotCache = object@Cache, sloth1 = lavh1)

lav_model_fit(lavpartable = lavpartable, lavmodel = lavmodel, lavimplied = lavimplied, x = x, VCOV = VCOV, TEST = TEST)

new('Fit', npar = max(lavpartable$free), x = x.copy, partrace = PARTRACE, start = lavpartable$start, est = est, se = se, fx = fx, fx.group = fx.group, logl = logl, logl.group = logl.group, iterations = iterations, converged = converged, control = control, Sigma.hat = if (lavmodel@conditional.x) implied$res.cov else implied$cov, Mu.hat = if (lavmodel@conditional.x) implied$res.int else implied$mean, TH = if (lavmodel@conditional.x) implied$res.th else implied$th, test = test)

initialize(value, ...)

initialize(value, ...)

validObject(.Object)

stop(msg, ': ', errors, domain = NA)

### Expected Behaviour

The program should refreshed the results

### Steps to Reproduce

This bug happened when i was inserting a modification indice code
<img width="959" alt="Captura de ecrã 2024-01-24 181539" src="https://github.com/jasp-stats/jasp-issues/assets/157634536/b9331bf6-db81-43e7-872c-077878c18524">

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@Patriciajro 
I guess we need your jasp file and/or log-files to solve this one.
Before dragging and dropping the jasp file here rename it to .zip.

And here is the howto on how to get the logs:
https://github.com/jasp-stats/jasp-desktop/blob/stable/Docs/user-guide/logging-howto.md#logs-location
