### ISSUE TITLE
sensitivity, specificity, PPV, NPV, and Cox proportional hazard regression

### ISSUE THREAD

**Issue by laithashour3** [jasp-stats/jasp-issues#2549]
### Description

these are important statistical methods in medical research. specifically as diagnostic statistical tests.

### Purpose

To allow statisticians to define the accuracy and performance of different measurements' tools

### Is your feature request related to a problem?

no

### Is your feature request related to a JASP module?

Other

### Describe the solution you would like

adding these features to JASP would be great

### Describe alternatives that you have considered

using other statistical packages

**Comment by EJWagenmakers** [comment]
We offer sensitivity, specificity, NPV and PPV (and much more) in the "Learn Bayes" module, under "Binary classification". See also the associated preprint "Correct conclusions from fallible medical tests: A tutorial with JASP" at https://osf.io/preprints/osf/jksz6. We are also working on parametric survival models. So I am closing this issue.
