### ISSUE TITLE
standardized and Pearson residuals in Chi-squared output

### ISSUE THREAD

**Issue by AL38000** [jasp-stats/jasp-issues#255]
* Enhancement: adding some statistics in chi-squared output  : Pearson residuals, standardized and adjusted standardized residuals
* Purpose: these residuals are very useful  in order to perform (sort of...) post hoc tests on contingency tables.

**Comment by DrMarkGS** [comment]
This would be very useful for students i.e z = (observed - expected)/sqrt expected - then flag if these are significant.

Cheers
Mark

**Comment by tomtomme** [comment]
Those features are done.
This issue can be closed.
