### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by JohanACHARD** [jasp-stats/jasp-issues#2552]
### JASP Version

0.18.3

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

Bayesian RM-ANOVA

### What OS are you seeing the problem on?

Windows 11

### Bug Description

 I found myself again with big differences between Bayesian and frequentist with an RM-ANOVA.

But after a pause for reflection, when I turned JASP back on, the model converged totally differently... (version 0.18.3 JASP). I tried again after a pause, and the results diverged but remained stable this time (cf screenshots). I tried with other computer with JASP 0.16.4 (screen 4).

![DJY9P38MSSHB](https://github.com/jasp-stats/jasp-issues/assets/135587553/45eef499-0edb-4d8f-81a7-f06485b2cdf7)
![PP76DX566J2D](https://github.com/jasp-stats/jasp-issues/assets/135587553/ac69e4aa-5a3c-4f67-97e8-962109f47874)
![EM3QLDUUESRD](https://github.com/jasp-stats/jasp-issues/assets/135587553/11108b41-eb0e-4731-9646-6be0b55bffd8)
![AG819ZQUDXTU](https://github.com/jasp-stats/jasp-issues/assets/135587553/664bc8c1-c281-4d72-9017-f8e621c76b16)

What do you think? A stability problem ?

### Expected Behaviour

I expect same (or similar) result when I reopening and perfom Bayes RM-Anova

Git-hub link with data: https://github.com/JohanACHARD/jasp_RM_anova_difference_freq_bayesian/blob/f27e10fc869be6a0762b8d25d55b518a6b53ecbd/meanMT.jasp  

### Steps to Reproduce

No... now JASP compute similar result.... intriguing when I re try the analysis a new time

### Log (if any)

 https://github.com/JohanACHARD/jasp_RM_anova_difference_freq_bayesian/blob/f27e10fc869be6a0762b8d25d55b518a6b53ecbd/meanMT.jasp  

[mean_MT.csv](https://github.com/jasp-stats/jasp-issues/files/14062816/mean_MT.csv)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@JohanACHARD 
Was Johnnys answer sufficient for your, so that we can close this one?

**Comment by JohanACHARD** [comment]
Hello team, 
Thanks for your help, I tried to reproduce this problem using your recommendations but I couldn't do it.

Thanks, that's it for me!
