### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Dhiyaafsha75** [jasp-stats/jasp-issues#2554]
### JASP Version

0.18.3

### JASP Module

Reliability

### What analysis are you seeing the problem on?

Regression

### What OS are you seeing the problem on?

Windows 11

### Bug Description

![image](https://github.com/jasp-stats/jasp-issues/assets/158147693/b00f584e-6f30-4278-afed-30113e94ffbd)

### Expected Behaviour

![image](https://github.com/jasp-stats/jasp-issues/assets/158147693/f9bf9349-b618-41d5-b978-69859257e3d9)

### Steps to Reproduce

1. while i use the program for a 3 minutes suddenly that notification appear
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@Dhiyaafsha75 
I guess we need your jasp file or log-files to solve this one. 
Before dragging and dropping the jasp file here rename it to .zip.

And here is the howto on how to get the logs:
https://github.com/jasp-stats/jasp-desktop/blob/stable/Docs/user-guide/logging-howto.md#logs-location
