### ISSUE TITLE
[Feature Request]: mark excluded subjects

### ISSUE THREAD

**Issue by mrrezaie** [jasp-stats/jasp-issues#2557]
Hi,

[Is there any way to exclude subjects (outliers) from analyses?]

I want to exclude a couple of subjects from analyses without removing their data. It would be great if you add this option in "Edit Data" section. Excluded subjects can be distinguished by red highlights or checkbox. Thank you

**Comment by EJWagenmakers** [comment]
This can already be accomplished by setting a filter (e.g., https://www.youtube.com/watch?v=lNXyNRezMWU) Please reopen if I misunderstood the issue.

**Comment by mrrezaie** [comment]
Wow, this is so robust. Thanks!!!
