### ISSUE TITLE
[Bug]: Install Issue with macOS Sonoma

### ISSUE THREAD

**Issue by DianaAngela** [jasp-stats/jasp-issues#2560]
### JASP Version

0.18.3

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Other

### Bug Description

I am unable to install JASP 18.3 on my MacBook Pro with macOS Sonoma.  I had JASP 18.1 installed and it worked perfectly.  Then when I tried to install 18.3, I only receive the below message.  I receive the below message when trying to install earlier versions of JASP as well.

[JASPinstallissue.docx](https://github.com/jasp-stats/jasp-issues/files/14130837/JASPinstallissue.docx)

![JASP install issue](https://github.com/jasp-stats/jasp-issues/assets/158518130/0d837ae6-de0e-4f1e-8c2f-2223333448d0)

"You can't open the application "JASP" because this application is not supported on this Mac."

### Expected Behaviour

JASP 18.3 should have been installed properly.

### Steps to Reproduce

1. click "Download JASP"
2. once downloaded, move to applications folder
3. open new version of JASP
4. receive the above message when trying to open JASP
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Did you make sure to download the version specific to your machine? We have an apple silicon and an intel version. You can check which kind of machine you have under the apple button and then "about this computer" (or similar)

**Comment by DianaAngela** [comment]
I finally got it downloaded properly.  Thanks for your assistance and patience.

**Comment by tomtomme** [comment]
nice. So I am closing this. Feel free to open a new issue if you encounter one.
