### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by maddiebar22** [jasp-stats/jasp-issues#2561]
### JASP Version

0.18.3

### JASP Module

Other

### What analysis are you seeing the problem on?

Opening the program

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

When I try to open Jasp it tells me that the engine crashed

<img width="1284" alt="Screenshot 2024-02-02 at 10 31 00 PM" src="https://github.com/jasp-stats/jasp-issues/assets/62128332/f6806b24-8c63-47c1-bc98-5656a05ac0d3">

### Expected Behaviour

Jasp should open without a problem.

### Steps to Reproduce

1. Download the Mac Silicon package from Jasp website
2. Open Jasp on Mac
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [x] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Are you on a macOS version of 12 or greater? Does your Mac really contain apple silicon or might it be an intel chip?

**Comment by maddiebar22** [comment]
I am using Ventura 13.3 and my Mac has an M2 chip

**Comment by tomtomme** [comment]
That should work then. 
I guess we need log-files to solve this one. Here is the howto on how to get them on mac:

Mac
On Mac one should open a terminal from Applications -> Utilities -> Terminal in the finder. Then if you've installed JASP without changing it's name you should be able to start it as follows:

```
cd /Applications/JASP.app/Contents/MacOS/
./JASP --logToFile
```

You will also see some lines of output there in the terminal, these might be useful to a developer in case JASP doesn't even reach a state in which it can start logging. Presumably you still do not see a JASP window opening now, so you'll have to [navigate manually to the logfiles](https://github.com/jasp-stats/jasp-desktop/blob/stable/Docs/user-guide/logging-howto.md#logs-location).

**Comment by maddiebar22** [comment]
When I navigated manually to the logfiles nothing came up. 
<img width="916" alt="Screenshot 2024-02-03 at 3 25 21 PM" src="https://github.com/jasp-stats/jasp-issues/assets/62128332/68475c8d-ad96-4fdd-ae00-2e811fc8f2a7">

**Comment by maddiebar22** [comment]
Also when I initially tried navigating to the log files in the terminal using the command provided it returned this: zsh: no such file or directory: cd/Applications/Jasp.app/Contents/MacOS/./JASP

I haven't changed the name of JASP so that shouldn't be an issue

**Comment by tomtomme** [comment]
@maddiebar22 
Did you have older jasp versions installed before? Did you try uninstalling all of them and then re-installing?

@boutinb 
Do you have any idea? I am grasping for straws here...

**Comment by maddiebar22** [comment]
I did have an older version that worked back in June. If I remember it correctly it needed to be updated and when I tried to do that it started giving me this problem. 

Do you have an uninstaller script that I could try?

**Comment by tomtomme** [comment]
@maddiebar22 
Does this not work? https://support.apple.com/en-us/102610

**Comment by maddiebar22** [comment]
I just did that, and I am still getting the same message that the engine crashed

**Comment by maddiebar22** [comment]
I tried to open JASP using the terminal and received this: 

(base) maddiebarter@Maddies-Laptop\n>\nMaddies-Laptop ~ % cd /Applications/JASP.app/Contents/MacOS/
./JASP --logToFile
Making new argument list for Application startup: ./JASP --logToFile
Starting JASP 0.18.3 from commit 123cb32f4f0459196195787e819b249bfd8677aa and branch stable
QtWebEngineQuick initialized
Application initialized
Application init entered
MainWindow constructor started
TempFiles::createSessionDir(): '/Users/maddiebarter/.JASP/temp/30032' about to be (removed and re)created.
Going to construct the necessary models for JASP to function.
Desktop:	Checking qm file: /Applications/JASP.app/Contents/Resources/Translations/jaspDesktop-zh_Hans.qm
Desktop:	Language (Chinese) not registered in LanguageModel, adding it now
Desktop:	Checking qm file: /Applications/JASP.app/Contents/Resources/Translations/jaspDesktop-de.qm
Desktop:	Language (German) not registered in LanguageModel, adding it now
Desktop:	Checking qm file: /Applications/JASP.app/Contents/Resources/Translations/jaspDesktop-fr.qm
Desktop:	Language (French) not registered in LanguageModel, adding it now
Desktop:	Checking qm file: /Applications/JASP.app/Contents/Resources/Translations/jaspDesktop-nl.qm
Desktop:	Language (Dutch) not registered in LanguageModel, adding it now
Desktop:	Checking qm file: /Applications/JASP.app/Contents/Resources/Translations/jaspDesktop-es.qm
Desktop:	Language (Spanish) not registered in LanguageModel, adding it now
Desktop:	Checking qm file: /Applications/JASP.app/Contents/Resources/Translations/jaspDesktop-tr.qm
Desktop:	Invalid translation file found with name: jaspDesktop-tr.qm
Desktop:	Checking qm file: /Applications/JASP.app/Contents/Resources/Translations/jaspDesktop-eo.qm
Desktop:	Invalid translation file found with name: jaspDesktop-eo.qm
Desktop:	Checking qm file: /Applications/JASP.app/Contents/Resources/Translations/jaspDesktop-gl.qm
Desktop:	Language (Galician) not registered in LanguageModel, adding it now
Desktop:	Checking qm file: /Applications/JASP.app/Contents/Resources/Translations/jaspDesktop-pl.qm
Desktop:	Language (Polish) not registered in LanguageModel, adding it now
Desktop:	Checking qm file: /Applications/JASP.app/Contents/Resources/Translations/jaspDesktop-pt.qm
Desktop:	Language (Portuguese) not registered in LanguageModel, adding it now
Desktop:	Checking qm file: /Applications/JASP.app/Contents/Resources/Translations/jaspDesktop-ru.qm
Desktop:	Language (Russian) not registered in LanguageModel, adding it now
Desktop:	Checking qm file: /Applications/JASP.app/Contents/Resources/Translations/jaspDesktop-ja.qm
Desktop:	Language (Japanese) not registered in LanguageModel, adding it now
Desktop:	Checking qm file: /Applications/JASP.app/Contents/Resources/Translations/jaspDesktop-zh_Hant.qm
Desktop:	Language (Chinese) not registered in LanguageModel, adding it now
Desktop:	Checking qm file: /Applications/JASP.app/Contents/Resources/Translations/jaspDesktop-pt_BR.qm
Desktop:	Invalid translation file found with name: jaspDesktop-pt_BR.qm
Desktop:	Checking qm file: /Applications/JASP.app/Contents/Resources/Translations/jaspDesktop-id.qm
Desktop:	Language (Indonesian) not registered in LanguageModel, adding it now
Desktop:	Opened internal sqlite database for creation at '/Users/maddiebarter/.JASP/temp/30032/internal.sqlite'.
Desktop:	DataSet::DataSet(index=-1)
Desktop:	UPDATE DataSet 1 with Empty Values: {
	"emptyValuesPerColumn" : {},
	"missingDataPerColumn" : {},
	"workspaceEmptyValues" : 
	[
		".",
		"NA",
		"NaN",
		"nan"
	]
}

Desktop:	DataSetPackage::reset()
Desktop:	DataSet::DataSet(index=-1)
Desktop:	UPDATE DataSet 1 with Empty Values: {
	"emptyValuesPerColumn" : {},
	"missingDataPerColumn" : {},
	"workspaceEmptyValues" : 
	[
		".",
		"NA",
		"NaN",
		"nan"
	]
}

Desktop:	UPDATE DataSet 1 with Empty Values: {
	"emptyValuesPerColumn" : {},
	"missingDataPerColumn" : {},
	"workspaceEmptyValues" : 
	[
		".",
		"NA",
		"NaN",
		"nan"
	]
}

Desktop:	DataSetPackage::endLoadingData
Desktop:	ColumnEncoder::setCurrentNames(#0)
Entering eventloop
During startup - Warning messages:
1: package ‘utils’ in options("defaultPackages") was not found 
2: package ‘stats’ in options("defaultPackages") was not found 
qt.qpa.fonts: Populating font family aliases took 41 ms. Replace uses of missing font family ".AppleSystemUIFontMonospaced" with one that exists to avoid this cost. 
Error: function 'Rcpp_precious_remove' not provided by package 'Rcpp'
Execution halted
During startup - Warning messages:
1: package ‘utils’ in options("defaultPackages") was not found 
2: package ‘stats’ in options("defaultPackages") was not found 
Compositor returned null texture
Error: function 'Rcpp_precious_remove' not provided by package 'Rcpp'
Execution halted

**Comment by maddiebar22** [comment]
I think I was also able to find the log files
[JASP 2024-02-04 13_51_42 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/14157947/JASP.2024-02-04.13_51_42.Desktop.log)
[JASP 2024-02-04 13_51_42 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/14157949/JASP.2024-02-04.13_51_42.Engine.0.log)

**Comment by tomtomme** [comment]
I found a related bug report https://github.com/jasp-stats/jasp-issues/issues/1131 mentioning this solution: 
```
If you could follow the steps under "Change your computer’s name " from [this apple manual](https://support.apple.com/lt-lt/guide/mac-help/mchlp2322/mac) and change the computers name from "PSYC-A41610" to something shorter.

Then once you've done that you can check by running uname -a and then hopefully it should be just a single line.
When it is I think JASP should start without a hitch.
```

**Comment by maddiebar22** [comment]
You're amazing. Changing my host name worked and I no longer have the issue!

**Comment by tomtomme** [comment]
@maddiebar22 
What was the hostname before and what after?

@boutinb 
How can we warn the user about this during installation or how can we make the installer / R more robust in such a case? These errors pertaining user and host name on MacOS come up quite frequently :/

**Comment by maddiebar22** [comment]
I think I had tried to rename my hostname when I got a new computer and I messed up and renamed it something weird like Maddies-Laptop/n>/Maddies-Laptop. I just renamed it to MaddiesLaptop and it resolved the issue

**Comment by boutinb** [comment]
Thank you @tomtomme to have found the error (during the week-end!).
That's true that is not the first time that we have problems with usernames having strange characters, but it is the first time that someone had a newline in his username... @JorisGoosen  did a lot of work so that it works even with Chinese username, but newline might be too exotic. From the error message, it's the Rcpp package that seems to have some difficulties here, I'm not so sure we can do a lot here... I guess that even R Studio would not have worked on your machine.
So let's just close this issue for now.
