### ISSUE TITLE
[Bug]: Unexpected Error running CFA

### ISSUE THREAD

**Issue by TrendyJorge** [jasp-stats/jasp-issues#2564]
### JASP Version

0.18.3

### JASP Module

Factor

### What analysis are you seeing the problem on?

CFA

### What OS are you seeing the problem on?

Windows 11

### Bug Description

While running CFA, the analysis retur an error iwth the following message: "This analysis terminated unexpectedly.
Error in diag(scales) %*% truevar: non-conformable arguments
Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])
doTryCatch(return(expr), name, parentenv, handler)
withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)
analysis(jaspResults = jaspResults, dataset = dataset, options = options)
.cfaTableReliability(jaspResults, options, cfaResult)
semTools::compRelSEM(cfaResult[['lav']], return.total = TRUE)
omega cat(truevar = commonCov, denom = totalCov, threshold = threshold[[b]][myIndNames], scales = latScales[[b]][myIndNames])"

### Expected Behaviour

The expected output is the results of the requested analysys.

### Steps to Reproduce

1. I load the dataset correctly (already run EFA, descriptive, etc with no issues
2. Once I choose CFA, the error appears after the creation of the second factor
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@TrendyJorge 
Can you share your jasp file by renaming it to .zip and then dragging it here?

**Comment by TrendyJorge** [comment]
[Análise respostas Survey - 20240204_1.zip](https://github.com/jasp-stats/jasp-issues/files/14157907/Analise.respostas.Survey.-.20240204_1.zip)
this is the jasp file with the error

**Comment by tomtomme** [comment]
You have very long variable names with special characters like ' and é and . and spaces. Can you try to remove some of those and move those long names into the description field if they are really needed?

**Comment by TrendyJorge** [comment]
Ok. give me a couple of minutes...

**Comment by TrendyJorge** [comment]
It works!!!!!

**Comment by TrendyJorge** [comment]
The problem was in the names. too long and with some special characters. Thank you for your quick and helpful advice!!!

**Comment by tomtomme** [comment]
@TrendyJorge 
nice!

@juliuspfadt 
Do you think it is feasible to fix this? 
I guess not accepting spaces, ' and other special characters in var names is not related to CFA only.
Maybe we should give the user a warning, when he tries to use such characters or even try to prevent them and convert them when importing data, so that every strange sign becomes a - or something...

**Comment by TrendyJorge** [comment]
It is already fixed. Avoiding long names and the use of special characters,
it works fine!
Thanks.
jorge

**Comment by tomtomme** [comment]
@TrendyJorge 
I know it is fixed for you! But what about others that do not yet know about those characters being "special"! We need to adress this in general for everybody.

**Comment by TrendyJorge** [comment]
Ok, now I understand. Here are all the "not conventional" characters used
in my dataset: ç ê / ó í () é á ã '.
Perhaps the problem is with the "/". I've removed only this character from
the labels and the CFA analysis is running well and without errors.
So, my suggestion is to avoid the use of "/" in all labels.
Hope this helps everybody avoid some problems in the future.
Thank you very much and Keep up the fantastic job with JSAP!

Best regards
Jorge

**Comment by tomtomme** [comment]
@juliuspfadt 
Now that the bug is isolated to using "/" in var names - how can we prevent the user from using that sign in a var name?

**Comment by juliuspfadt** [comment]
We might throw an error when the syntax is checked. A list of these characters would be crucial for this, you are certain it is only the "/"? As you correctly pointed out we had issues with these characters before, maybe Bruno has an idea @boutinb?

**Comment by TrendyJorge** [comment]
In my dataset the problem is only generated by this "/" character, 100%
sure. I made the check, deleting only this character from the labels and
the analyses run very well, without issues.
But, I might suggest a very strong recommendation to generate labels in
JASP and avoid this kind of issue in the future: Use short labels, avoid
special characters "/\*+-_€@#$% &()" as well as "spaces".
I will follow this "rule" on my future datasets for sure.
I remember in SPSS, all these special characters* can not be used* (the
program simply and automatically doesn't allow this). Perhaps could be a
suggestion to improve the upcoming versions of JASP :)
Hope my opinion can help you guys.
Regards

**Comment by tomtomme** [comment]
@boutinb & @JorisGoosen 
Gathered from this & #2113, #1503 some signs should not be allowed to enter in var names & labels:

- /
- +
- -
- [
- ]

Is this implementable?

**Comment by tomtomme** [comment]
Now tracked here: https://github.com/jasp-stats/jasp-issues/issues/2625
