### ISSUE TITLE
 [Bug]: JASP file damaged

### ISSUE THREAD

**Issue by mspeiger** [jasp-stats/jasp-issues#2566]
### JASP Version

0.18.3

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

Opening the file

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I ran several analyses with JASP on an CSV file and saved it as JASP file. When I try to open it now JASP reports: cannot open the file: JASP does not support loading the file-tape "JAS".
Apparently something went wrong saving the file, but when I open it with Windows Explorer it has the correct ending (.jasp) as all the other JASP files that are working fine.
So this is a single incident. I tried with the same and other data sets before and after and everything is fine.

Unfortunately I cannot share the JASP file, because of data protection issues. 

I just wanted to ask  if this is a known issue with a solution. Otherwise I will probably just drop it..

### Expected Behaviour

The file should have opened

### Steps to Reproduce

1.Create a jasp file and save it?
2.
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by mspeiger** [comment]
<img width="181" alt="JASP Error" src="https://github.com/jasp-stats/jasp-issues/assets/145142901/b8eaab5d-6d62-4ba4-96e1-1f702592b131">

**Comment by boutinb** [comment]
Hi @mspeiger, in the property window of your file, it says also that the file is of type `.JAS`.
What I can see, is that the name of this file is quite long with space and brackets... what is the whole name of this file? Could you just rename it with a shorter name test.jasp, and test if it works?

**Comment by tomtomme** [comment]
@mspeiger 
Did you save those with jasp 0.18.2 and can you open them with 0.18.2 using e.g. the zipped version from here? https://jasp-stats.org/previous-versions
