### ISSUE TITLE
[Feature Request]: PLS-SEM improvements

### ISSUE THREAD

**Issue by juliuspfadt** [jasp-stats/jasp-issues#2567]
### Description

Some improvements to the PLS SEM module in JASP

- [ ] Confidence intervals for HTMT and VIF

### Purpose

Increase its usefulness of course.

### Use-case

https://github.com/jasp-stats/jasp-issues/issues/2356#issuecomment-1931615329

### Is your feature request related to a JASP module?

SEM

### Describe the solution you would like

Implement the features

**Comment by FloSchuberth** [comment]
I think it shouild be:
1) Implement HTMT(2); There are two versions of the HTMT, see Henseler et al (2015) and Roemer et al (2021). for that purpose you can use the cSEM::calculateHTMT() function
2) Report Confidence intervals for the HTMT(2). For that purpose you can use the cSEM::calculateHTMT() function.
3) Report VIF for the structural model. These VIFs are already calculated by the csem() function. and stored under $Estimates$VIF. Alternatively, you can use assess(csemObject,.quality_criterion = 'vif')


References:
Henseler, J., Ringle, C. M., & Sarstedt, M. (2015). A new criterion for assessing discriminant validity in variance-based structural equation modeling. Journal of the Academy of Marketing Science, 43(1), 1–21.

Roemer, E., Schuberth, F., & Henseler, J. (2021). HTMT2 – an improved criterion for assessing discriminant validity in structural equation modeling. Industrial Management & Data Systems, 121(12), 2637–2650. https://doi.org/10.1108/IMDS-02-2021-0082

**Comment by juliuspfadt** [comment]
lets just track this over here https://github.com/jasp-stats/jasp-issues/issues/2601
