### ISSUE TITLE
[Bug]: downloading mediation model as powerpoint

### ISSUE THREAD

**Issue by PaulLJMU** [jasp-stats/jasp-issues#2568]
### JASP Version

0.18.2

### JASP Module

SEM

### What analysis are you seeing the problem on?

Mediation analysis

### What OS are you seeing the problem on?

Windows 11

### Bug Description

![mediation bug](https://github.com/jasp-stats/jasp-issues/assets/103045269/681a67fe-e245-4629-a12e-2da29a5ff0ff)

it says error saving plot. 'x' is a list, but does not have components 'x' and 'y'

### Expected Behaviour

on previous versions (running this on 0.18.2) the plot would wonload as powerpoint for editing

### Steps to Reproduce

1. Click plot drop-down
2. Save as
3. Choose PowerPoint format
4. Click Save
...
[Uploading JASP correlations and regression.zip…]()

### Log (if any)

[JASP 2024-02-07 09_59_17 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/14192234/JASP.2024-02-07.09_59_17.Engine.0.log)
[JASP 2024-02-07 09_59_17 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/14192235/JASP.2024-02-07.09_59_17.Desktop.log)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@PaulLJMU 
thx for reporting this issue. Can you try uploading your file again? Atm its just a link to this issue.

**Comment by PaulLJMU** [comment]
Thomas,
Which file are you referring to? Data zip file??

**Comment by PaulLJMU** [comment]
Thomas, I have tried to add the data/results file again as a zip folder but I expect it is only a link again. Your upload will not allow an actual JASP file format
[JASP correlations and regression (2).zip](https://github.com/jasp-stats/jasp-issues/files/14192733/JASP.correlations.and.regression.2.zip)

**Comment by tomtomme** [comment]
@PaulLJMU 
This time your upload worked fine. I refreshed the analysis because you used the older jasp 0.18.2. With jasp 0.18.3 saving as pptx worked fine - at least on linux / flatpak version of jasp.
Can you re-test with 0.18.3?

**Comment by PaulLJMU** [comment]
It takes over 15minutes to install via our network app player so it will be later today before I get back to you

**Comment by PaulLJMU** [comment]
Thomas, the issue is resolved. Thank you.
Paul

**Comment by PaulLJMU** [comment]
Thomas, ignore my message just deleted.
It has not worked. Same error message again. I did refresh results before trying to save image as powerpoint

**Comment by tomtomme** [comment]
@boutinb & @juliuspfadt 
Can someone replicate this on Win11? I can't replicate on flatpak. Saving mediation model graph as pptx does not work for Paul

**Comment by tomtomme** [comment]
@PaulLJMU 
Thx for testing! Any updates?

**Comment by PaulLJMU** [comment]
Hi Thomas, sorry I didnt get back to you.
I can download (save as) PP file from home PC running windows 10 and JASP 18.0.2 and the most recent version. I expect the problem is to do with our Network configuration. 
I can work with the solution of using home PC because our IT service would only refer me back to JASP.
Thanks for your help anyway.

**Comment by tomtomme** [comment]
Ok, then closing for now.
