### ISSUE TITLE
[Bug]: Error in tableIListCombined[['test3']]: subscript out of bounds

### ISSUE THREAD

**Issue by AdrianSkorczyk** [jasp-stats/jasp-issues#2569]
### JASP Version

0.18.1

### JASP Module

Quality Control

### What analysis are you seeing the problem on?

Process Capability Study

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I tried to do capability study and this problem occur:
his analysis terminated unexpectedly.

Error in tableIListCombined[['test3']]: subscript out of bounds

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.pcReport(dataset, measurements, parts, operators, options, ready, jaspResults, splitFactor, wideFormat) 

### Expected Behaviour

Capability process

### Steps to Reproduce

1. I checked data format, it's OK

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by JTPetter** [comment]
Hi @AdrianSkorczyk ,

I assume this is fixed already in JASP 0.18.3, but could you please send me the data file so I can confirm?

**Comment by AdrianSkorczyk** [comment]
Please

Z góry dziękuję / Thank you in advance
Pozdrawiam / Best Regards

Adrian Skorczyk

Tel: +48 61 8743 158, Mob: +48 785 052 515
E-mail: ***@***.******@***.***>

SKF Polska S.A
Nieszawska 15, 61-022 Poznań, Polska

www.skf.com<http://www.skf.com/>, Facebook<https://www.facebook.com/SKFGroup>, Youtube<https://www.youtube.com/user/SKFOfficial>, Linkedin<https://www.linkedin.com/company/skf>, Twitter<https://twitter.com/skfgroup>

SKF Polska Spółka Akcyjna z siedzibą w Poznaniu,
ul. Nieszawska 15, 61-022,
zarejestrowana w Sądzie Rejonowym Poznań-Nowe Miasto i Wilda w Poznaniu,
VIII Wydział Gospodarczy Krajowego Rejestru Sądowego,
pod nr KRS 0000084052;
NIP 777-00-00-212;
kapitał zakładowy Spółki - 74.029.320,00 PLN w całości opłacony.

Administratorem Państwa danych osobowych jest SKF Polska S.A. z siedzibą w Poznaniu (61-022), ul. Nieszawska 15. Dane osobowe będą przetwarzane w celu prowadzenia korespondencji na podstawie prawnie uzasadnionego interesu Administratora, tj. art. 6 ust. 1 lit. f RODO. Więcej informacji dotyczących przetwarzania danych osobowych zawartych jest w Polityce prywatności<https://www.skf.com/pl/footer/privacy-policy>.
Niniejsza wiadomość e - mail może zawierać informacje poufne i prawnie chronione, kierowana jest do określonego adresata. Jeśli jesteście Państwo jego omyłkowym odbiorcą, proszę zawiadomić o tym nadawcę wiadomości oraz usunąć niniejszą wiadomość. Kopiowanie, ujawnianie lub rozpowszechnianie materiału zawartego w tym e-mailu jest zabronione.

***@***.***
The SKF purpose | SKF<https://www.skf.com/group/organisation/about-skf/purpose>

**Comment by tomtomme** [comment]
@AdrianSkorczyk 
Sending via email does not work. Please rename your file to .zip and drag and drop it here on the website. thx!

**Comment by AdrianSkorczyk** [comment]
Try now

Z góry dziękuję / Thank you in advance
Pozdrawiam / Best Regards

Adrian Skorczyk

Tel: +48 61 8743 158, Mob: +48 785 052 515
E-mail: ***@***.******@***.***>

SKF Polska S.A
Nieszawska 15, 61-022 Poznań, Polska

www.skf.com<http://www.skf.com/>, Facebook<https://www.facebook.com/SKFGroup>, Youtube<https://www.youtube.com/user/SKFOfficial>, Linkedin<https://www.linkedin.com/company/skf>, Twitter<https://twitter.com/skfgroup>

SKF Polska Spółka Akcyjna z siedzibą w Poznaniu,
ul. Nieszawska 15, 61-022,
zarejestrowana w Sądzie Rejonowym Poznań-Nowe Miasto i Wilda w Poznaniu,
VIII Wydział Gospodarczy Krajowego Rejestru Sądowego,
pod nr KRS 0000084052;
NIP 777-00-00-212;
kapitał zakładowy Spółki - 74.029.320,00 PLN w całości opłacony.

Administratorem Państwa danych osobowych jest SKF Polska S.A. z siedzibą w Poznaniu (61-022), ul. Nieszawska 15. Dane osobowe będą przetwarzane w celu prowadzenia korespondencji na podstawie prawnie uzasadnionego interesu Administratora, tj. art. 6 ust. 1 lit. f RODO. Więcej informacji dotyczących przetwarzania danych osobowych zawartych jest w Polityce prywatności<https://www.skf.com/pl/footer/privacy-policy>.
Niniejsza wiadomość e - mail może zawierać informacje poufne i prawnie chronione, kierowana jest do określonego adresata. Jeśli jesteście Państwo jego omyłkowym odbiorcą, proszę zawiadomić o tym nadawcę wiadomości oraz usunąć niniejszą wiadomość. Kopiowanie, ujawnianie lub rozpowszechnianie materiału zawartego w tym e-mailu jest zabronione.

***@***.***
The SKF purpose | SKF<https://www.skf.com/group/organisation/about-skf/purpose>

**Comment by tomtomme** [comment]
Again, email does not work. Use the website github.com
