### ISSUE TITLE
PCA scores

### ISSUE THREAD

**Issue by Lukemo403** [jasp-stats/jasp-issues#2571]
### Description

no posisiblity to save PCA scores

### Purpose

use it in our analyses - Key aspect to use Jasp instead of spss

### Is your feature request related to a JASP module?

Factor

### Describe the solution you would like

button to save selected solution in the data file

### Additional context

It's not clear from the closed threads the state of the art of the problem...are you going to solve this problem (very relevant missing feature)? Thanks a lot

**Comment by juliuspfadt** [comment]
thanks for creating the issue. it is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/101
