### ISSUE TITLE
[Bug]: Variable Charts For Individuals

### ISSUE THREAD

**Issue by JoseCLopez** [jasp-stats/jasp-issues#2572]
### JASP Version

0.18.1

### JASP Module

Quality Control

### What analysis are you seeing the problem on?

Variable Charts For Individuals

### What OS are you seeing the problem on?

Windows 11

### Bug Description

![Bug JASP IMR](https://github.com/jasp-stats/jasp-issues/assets/159469512/c5da53b0-6a70-47f0-a654-340dc82d2baa)

### Expected Behaviour

to create an individual moving range chat file attached
[Diameter.csv](https://github.com/jasp-stats/jasp-issues/files/14212326/Diameter.csv)

### Steps to Reproduce

1. From JASP
2. Quality Control
3. Variable Chart for Individual
4. Select Variables "Diameter"
5. Bug
...

### Log (if any)

[Diameter.csv](https://github.com/jasp-stats/jasp-issues/files/14212381/Diameter.csv)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by JTPetter** [comment]
@JoseCLopez Thank you for your report. This is already fixed in 0.18.3.
