### ISSUE TITLE
[Bug]: Can't plot interactions for BANOVAs and RM BANOVAs

### ISSUE THREAD

**Issue by AugustOlsson** [jasp-stats/jasp-issues#2573]
### JASP Version

0.18.3

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

Bayesian ANOVA and Bayesian Repeated Measures ANOVA

### What OS are you seeing the problem on?

Windows 11

### Bug Description

With the new update one cannot make graphs with interaction. I can add one independent variable to the "Horizontal axis", but I can't add the other independent variable to the "Separate lines". This works fine for frequentist ANOVAs though. I realised that the bug is only present when independent variables are string variables. That is, if I rename my conditions into numbers, then I can make the plot. See the attached file. The dependent variable is RMSE, the independent variables are Format and Task. The interaction plot can't be made with Format and Task. However, once I recoded the variables into numbers (variables Verb/Num and Add/IckeAdd) I can make the plot. There was no problem making graphs with independent variables as string variables in earlier versions, and it works fine for frequentist analyses.

As you see in the screenshot the button to put the variable "Format" into the "Separate lines" is grey and can't be pressed.

### Expected Behaviour

In the jasp file I have included both a frequentist anova and a bayesian anova analyses. For the frequentist it is possible to make a graph of the interaction with means and confidence intervals, I should of course be able to make the same graph with means and credible intervals

### Steps to Reproduce

Have a dataset with a dependent variable and independent variables with verbal names. 
Try and make a graph with both independent variables where one is on the horizonal axis and one is separate lines
The second variable can't be added to the "separate lines"
[Graph_bug.zip](https://github.com/jasp-stats/jasp-issues/files/14220193/Graph_bug.zip)
![image](https://github.com/jasp-stats/jasp-issues/assets/36534473/4cba1444-2d55-4361-acc0-930f880d13f4)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Can confirm. Checked on 0.18.3 flatpak. 
The BANOVAs descriptive plot boxes also indicate this. They include icons for nominal and ordinal data, but not nominal text. 
It is strange however, that the ANOVAs do not have this limitation. So this is a feature request and a bug at the same time.

**Comment by AugustOlsson** [comment]
Can also not that there was no problem making these interaction graphs for BANOVAs, with nominal text in version 0.17.1

Best,
August

**Comment by JohnnyDoorn** [comment]
If I understand correctly, @JorisGoosen is reworking the data engine in such a way that nominal text and nominal variables are no longer separate entities, which would hopefully solve this bug.

**Comment by JorisGoosen** [comment]
> If I understand correctly, @JorisGoosen is reworking the data engine in such a way that nominal text and nominal variables are no longer separate entities, which would hopefully solve this bug.

I am indeed, at https://github.com/jasp-stats/jasp-desktop/pull/5367

**Comment by JohnnyDoorn** [comment]
I think this is solved in 0.19, please reopen if necessary
