### ISSUE TITLE
[Bug]: unidimensional reliability 

### ISSUE THREAD

**Issue by maaikeevl** [jasp-stats/jasp-issues#2576]
### JASP Version

0.18.3

### JASP Module

Reliability

### What analysis are you seeing the problem on?

Unidimensional reliability

### What OS are you seeing the problem on?

Windows 11

### Bug Description

I was trying to do an unidimensional reliability test to see the cronbach's alpha and the item-rest correlation. I used a file from excel and had opened it in Jasp. When I moved the variables from the left to the right, to put them in the variables box, I suddenly got an error. It said the following:

This analysis terminated unexpectedly.

Error in library.dynam(lib, package, package.lib): DLL 'Bayesrel' not found: maybe not installed for this architecture?

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.frequentistComputeScaleResults(jaspResults, dataset, options, model)

loadNamespace(x)

library.dynam(lib, package, package.lib)

stop(gettextf('DLL %s not found: maybe not installed for this architecture?', sQuote(chname)), domain = NA)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

And I don't know what to do. I tried it with another excel file but that didn't work too, it said the same thing. I have windows 11 and Jasp 0.18.3 and I have a Lenovo laptop. 

### Expected Behaviour

It should have shown the chronbach's alpha and the item-rest correlation from the variables I selected

### Steps to Reproduce

1. I opened a csv file from Excel in Jasp
2. I pressed the button for the unidimensional reliability
3. I tried to move the variables from the left to the right, into the variable box
4. Then the bug happened

...

### Log (if any)

<img width="960" alt="Schermafbeelding 2024 bug" src="https://github.com/jasp-stats/jasp-issues/assets/159622193/c0888088-1d80-452b-9da7-17beb90216d6">

[Questionnaire jaspfile error.csv](https://github.com/jasp-stats/jasp-issues/files/14229076/Questionnaire.jaspfile.error.csv)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@maaikeevl 
I downloaded your csv and put in vars as shown. I cannot replicate the error message with jasp 0.18.3. 
McDonalds Omage gives me a NaN and a note, that calculation with CFA failed. I can change that in "advanced options" to PFA and get results. 
Cronbachs alpha does compute just fine also.

Can you share your .jasp file by renaming to .zip and drag and drop here?
Maybe easier to debug then, than with just the csv

**Comment by maaikeevl** [comment]
Thank you for your message! I dropped the zip file here
________________________________
Van: Thomas Langkamp ***@***.***>
Verzonden: zaterdag 10 februari 2024 15:30
Aan: jasp-stats/jasp-issues ***@***.***>
CC: Linschooten, M.I. van (Maaike) ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [jasp-stats/jasp-issues] [Bug]: unidimensional reliability (Issue #2576)


CAUTION: This email originated from outside of Utrecht University. Do not click links or open attachments unless you recognize the sender and know the content is safe.


@maaikeevl<https://github.com/maaikeevl>
I downloaded your csv and put in vars as shown. I cannot replicate the error message with jasp 0.18.3.
McDonalds Omage gives me a NaN and a note, that calculation with CFA failed. I can change that in "advanced options" to PFA and get results.
Cronbachs alpha does compute just fine also.

Can you share your .jasp file by renaming to .zip and drag and drop here?
Maybe easier to debug then, than with just the csv

**Comment by tomtomme** [comment]
@maaikeevl 
You tried to drop the file via mail. This does not work. Please do as I described.

**Comment by tomtomme** [comment]
@RensDofferhoff 
so this seems to be the same error as https://github.com/jasp-stats/jasp-issues/issues/2585
both systems run a non-english locale (spanish and netherlands) according to the screenshots. Might that interfere with the installation process of bayesrel.dll?

**Comment by RensDofferhoff** [comment]
I dont think language is a factor.
I have tried alot of machines with dutch,english and japanese but I have not found any instance of this bug as of yet.

**Comment by maaikeevl** [comment]
I deleted JASP from my computer and downloaded it again and now it's working again. But thank you for your help and suggestions!

**Comment by tomtomme** [comment]
@maaikeevl 
thx for the feedback :)
good to know that its working now.
closing then

**Comment by tomtomme** [comment]
@maaikeevl 
We are still investigating the source of the issue. Any chance you ran antivirus software like McAffee? 
The latest user with that error had.
