### ISSUE TITLE
[Bug]: Problem with Weblate: "Billing plan has exceeded its limits."

### ISSUE THREAD

**Issue by JoKeyser** [jasp-stats/jasp-issues#2577]
### JASP Version

Others

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Other

### Bug Description

Currently, translations via Weblate are impossible; all components are blocked.

Weblate reports that the billing plan was exceeded:

> Your billing plan has exceeded its limits.
>
> Your billing plan has exceeded its limits. You can still use the service, but are recommended to upgrade the billing plan.
>
> Appeared yesterday, last seen 14 hours ago

### Expected Behaviour

Would be nice to be able to use Weblate for translations.

### Steps to Reproduce

Go to any module on https://hosted.weblate.org/projects/jasp/ and try to interact with it.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
confirmed

**Comment by boutinb** [comment]
Solved!
