### ISSUE TITLE
[Bug]: Error running CFA

### ISSUE THREAD

**Issue by TrendyJorge** [jasp-stats/jasp-issues#2578]
### JASP Version

0.18.3

### JASP Module

Factor

### What analysis are you seeing the problem on?

CFA

### What OS are you seeing the problem on?

Windows 11

### Bug Description

When running CFA, the analysis terminated unexpectedly, returning the following error log:
This analysis terminated unexpectedly.

Error in lav_samplestats_icov(COV = cov[[g]], ridge = 1e-05, x.idx = x.idx[[g]], : lavaan ERROR: sample covariance matrix is not positive-definite
Stack trace
doTryCatch(return(expr), name, parentenv, handler)
withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)
analysis(jaspResults = jaspResults, dataset = dataset, options = options)
.cfaTableHtmt(jaspResults, options, cfaResult)
semTools::htmt(model = cfaResult[['model']], data = dataset, missing = cfaResult[['lav']]@Options[['missing']])
lavaan::lavCor(data, missing = missing, ordered = ordered)
lavaan(slotParTable = PT.un, slotData = lav.data, model.type = 'unrestricted', missing = missing, baseline = baseline, h1 = TRUE, se = se, test = test, estimator = estimator, ...)
lav_samplestats_from_data(lavdata = lavdata, lavoptions = lavoptions, WLS.V = WLS.V, NACOV = NACOV)
lav_samplestats_icov(COV = cov[[g]], ridge = 1e-05, x.idx = x.idx[[g]], ngroups = ngroups, g = g, warn = TRUE)
stop('lavaan ERROR: sample covariance matrix is not positive-definite')

Can you please give me some advice on how to fix this?
Thanks

### Expected Behaviour

The normal CFA outputs

### Steps to Reproduce

1.
2.
3.
...
[CFA with error.zip](https://github.com/jasp-stats/jasp-issues/files/14229587/CFA.with.error.zip)

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Confirmed. Same error also on 0.19beta flatpak.

**Comment by tomtomme** [comment]
@juliuspfadt 
any idea what this error is about?

**Comment by juliuspfadt** [comment]
The error does tell you that something with the included variables is wrong. Given that the sample covariance matrix is not positive definite. Factor 6 and Factor 8 are identical. Remove one of them and the analysis runs.

**Comment by TrendyJorge** [comment]
Ok, now I understand. The error was generated as a consequence of the
model. It must be reworked. I thought it was a bug.
Thank you :D
Jorge
