### ISSUE TITLE
boxplot:  lower and upper inner fence incorrectly computed? 

### ISSUE THREAD

**Issue by mservantufc** [jasp-stats/jasp-issues#258]
I don't understand how lower and upper inner fences are computed in JASP. 

* JASP version: 0.9.1.0
* OS name and version: windows 10
* Analysis: boxplot
* Bug description:
* Add JASP files as a zip:
[Calme_Bruit.txt](https://github.com/jasp-stats/jasp-issues/files/2615902/Calme_Bruit.txt)

* Screenshot: 
![capture](https://user-images.githubusercontent.com/45162680/49019688-cfdfc980-f18e-11e8-9b3b-d12690943e4c.PNG)

Here the lower and upper inner fences (i.e., end points of each whisker) seem to correspond to min and max. 

Consider now this second dataset:
[Exo3-TD1_JASP.xlsx](https://github.com/jasp-stats/jasp-issues/files/2615953/Exo3-TD1_JASP.xlsx)
* Screenshot: 
![capture2](https://user-images.githubusercontent.com/45162680/49020562-0b7b9300-f191-11e8-93b8-e5d61029a80a.PNG)

For the "enfants" condition, the fences don't correspond to min and max anymore. I thought the lower inner fence would be equal to Q1 - 1.5*interquartile range but this would give 12.5, which doesn't correspond to the graph. Could you please clarify how fences are computed? 

EDIT: my bad, the endpoints of whiskers represent adjacent values. They seem ok. Sorry

**Comment by EJWagenmakers** [comment]
@vankesteren ?

**Comment by AlexanderLyNL** [comment]
The edit suggests that this is fixed. Please reopen if that's not the case.
