### ISSUE TITLE
[Feature Request]: The silly request

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#2580]
### Description

Crush issue counter <500

### Purpose

fun

### Additional context

Dear Team,
I now went through all issues. But the counter is still >500 - unacceptable ;)
Together we can do better! Remember: All for one and one for all! There were so many issues I did not know enough about...
Lets crush this thing!

**Comment by FBartos** [comment]
Thanks Tom for going through all the issues! You have been doing a fantastic job!

**Comment by JTPetter** [comment]
Agreed, thanks @tomtomme !

**Comment by juliuspfadt** [comment]
I agree, this is invaluable work!

**Comment by JohnnyDoorn** [comment]
Amazing stuff =)

**Comment by tomtomme** [comment]
Same as you all. You closed 60 plus of my issues over the last years + 1700 issues from all the other people. How amazing is that?

**Comment by boutinb** [comment]
Only 25 issues to close!!! Thank you again @tomtomme ! That's really great!

**Comment by tomtomme** [comment]
And 70 of those are waiting for requesters... So the stretch goal is n<450

**Comment by JorisGoosen** [comment]
> Same as you all. You closed 60 plus of my issues over the last years + 1700 issues from all the other people. How amazing is that?

:o !

**Comment by tomtomme** [comment]
Done. Now onto the stretch goal :D
