### ISSUE TITLE
JASP won't open

### ISSUE THREAD

**Issue by Alina335** [jasp-stats/jasp-issues#2581]
### JASP Version

0.18.3

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

The program doesn't run at all

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I have Windows 10, x64. I downloaded the program (from the official site), then installed it. Succesfull. But it won't open! I clicked on it, 2-3 seconds of waiting and then - nothing. I reinstalled, installed on another disk (D:\) but nothing changed. Please, help me!
The same situation was here https://forum.cogsci.nl/discussion/6216/getting-installed-jasp-to-run
but no solution was found.
I used [dependency walker] as it was recommended here https://github.com/jasp-stats/jasp-issues/issues/681
And I get dwi file that I attached here.
I will be appreciate for any help as soon as possible, because I need this program to teach students statistic) Thank you!
[JASP.zip](https://github.com/jasp-stats/jasp-issues/files/14232101/JASP.zip)

### Expected Behaviour

JASP need to open as expected)

### Steps to Reproduce

1.restart computer
2.reinstalled program
3. used [dependency walker]
[JASP.zip](https://github.com/jasp-stats/jasp-issues/files/14232108/JASP.zip)

...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by RensDofferhoff** [comment]
We are currently moving away from the msi installer. Could you try installing JASP using the windows store? (Please uninstall any JASP currently on the system). https://apps.microsoft.com/detail/9P08CWG12JNL

**Comment by Alina335** [comment]
Thank you for your advice, but I tried to do it earlier. Now I repeated it with your link, but the situation is the same: I downloaded the file (560 Kb), I opened it then I got the message: 'We move you to Microsoft Store to finish download' and my browser again opened THE SAME page as the one where I downloaded that file. And once again the circle starts... Maybe, I did something wrong?

**Comment by Alina335** [comment]
I installed Windows store, found JASP, clicked 'install' and nothing happened. But now Windows store writes me "You have bought/ installed this product". Wow, such a bizarre :)

**Comment by tomtomme** [comment]
@Alina335 
What kind of machine / laptop do you have? Does it maybe have an ARM processor from Quallcom or some limited windows version? Is windows fully updated?

**Comment by RensDofferhoff** [comment]
How very bizarre. It really does not show up in the start menu or it doesnt start? A reboot does not resolve the issue?

Lets try the most bullet proof way, Download the Zip file here:
https://jasp-stats.org/thank-you-for-downloading-jasp-win64-zip/
expand it anywhere (lets go with any place on the  C:\ drive like your download folder). 
Double click on JASP application.

**Comment by Alina335** [comment]
> @Alina335 What kind of machine / laptop do you have? Does it maybe have an ARM processor from Quallcom or some limited windows version? Is windows fully updated?

No, I have Intel. I add a screenshot of my computer parameters, of course, it's in my language, but I guess you you find all info that you need.
And about updating I turn it off, course after them I accidentally find blue screen on my machine or other bad bugs.
<img width="431" alt="72758902" src="https://github.com/jasp-stats/jasp-issues/assets/110854513/a72c86dc-8ed2-4cb7-b69b-a887f80c09a9">

**Comment by Alina335** [comment]
> How very bizarre. It really does not show up in the start menu or it doesnt start? A reboot does not resolve the issue?
> 
> Lets try the most bullet proof way, Download the Zip file here: https://jasp-stats.org/thank-you-for-downloading-jasp-win64-zip/ expand it anywhere (lets go with any place on the C:\ drive like your download folder). Double click on JASP application.

After downloading *exe from the site (not from the Microsoft/Windows store) I installed it and the program was in the start menu, but it won't open. After downloading from the Microsoft/Windows store I even can't install it.

Thank you for zip-file, I downloaded it and open. After that, I got the message: 
"JASP has been installed from a zip and it needs to recreate certain paths for your analyses to work. Please be patient and wait for the application to show before attempting to start JASP again."

Actually, I waited, but in the Task Manager I saw no JASP task, so, I suppose, we've back to the start. I waited for a really long time, like 10-15 minutes, but nothing happened. I attach a message from JASP.
Thank you for trying to solve my problem!

<img width="378" alt="5467890-0" src="https://github.com/jasp-stats/jasp-issues/assets/110854513/614bd635-0e08-4030-a8cb-f047a63e9f9a">

**Comment by RensDofferhoff** [comment]
I just checked your windows version. Its very old with a release date of November 13, 2018.
Are you certain you cant update it? 

You could try and start the JASP.exe from the command prompt this might give us some more logs to work with.
Press the windows key and type "cmd". In the command prompt type "start <path>\JASP.exe" 
replace <path> with the folder path/location likely something like C:\Users\(Your Account)\Downloads\JASP-0.18.3.0-Windows\

**Comment by Alina335** [comment]
Yes, I made some corrections in administrative panel some time ago (and I even do not remember what I did there) and now I see in Windows Update that I have current version, even if its wrong.
I also tried to use your prompt like "start C:\Users(My Account)\Downloads\JASP-0.18.3.0-Windows\JASP.exe" but again nothing happened. As I understood I need to get newest Windows version, so I will try tomorrow, cause now I've already a little bit tired))
Thank you!!

**Comment by Alina335** [comment]
> I just checked your windows version. Its very old with a release date of November 13, 2018. Are you certain you cant update it?

That's it! You were 100% right: it was because of my Windows version. I updated it (and it was a bad headache for me!) and everything work as expected. JASP is installed even from *msi and works as good as the cloud version that I tested previously.

Thank you for your advice! Have a nice day or evening! :) 👍

**Comment by tomtomme** [comment]
@Alina335 
happy you could solve it. 
closing!
