### ISSUE TITLE
[Bug]: Error JASP has experienced an unexpected internal error: The enging crashed... JASP cannot continue and will close

### ISSUE THREAD

**Issue by cshaw111** [jasp-stats/jasp-issues#2583]
### JASP Version

0.18.3

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

When i open the application

### What OS are you seeing the problem on?

Other

### Bug Description

When i open the application the error comes up and i have to exit the application

### Expected Behaviour

JASP should open normally

### Steps to Reproduce

1. click on JASP 
<img width="1278" alt="Screen Shot 2024-02-12 at 9 40 54 am" src="https://github.com/jasp-stats/jasp-issues/assets/159733106/42785958-34ed-4079-b873-450275ee10b4">
application
2. error appears
3.
...

### Log (if any)

N/A

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @cshaw111 , which OS (Windows, Mac, Linux) and which version do you use?

**Comment by tomtomme** [comment]
@boutinb 
screenshot tells me its macOS

**Comment by cshaw111** [comment]
Hello - yes its macOS

**Comment by boutinb** [comment]
Also the OS version is needed: you see that in the 'About this Mac' popup window

**Comment by cshaw111** [comment]
Hi,
Intel UHD Graphics 630 1536 MB and Sonoma 14.3.1

Thanks!

From: bruno boutin ***@***.***>
Date: Tuesday, 13 February 2024 at 8:40 pm
To: jasp-stats/jasp-issues ***@***.***>
Cc: Cassidy Shaw ***@***.***>, Mention ***@***.***>
Subject: Re: [jasp-stats/jasp-issues] [Bug]: Error JASP has experienced an unexpected internal error: The enging crashed... JASP cannot continue and will close (Issue #2583)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Also the OS version is needed: you see that in the 'About this Mac' popup window

**Comment by boutinb** [comment]
From a Terminal, could you type '/Applications/JASP.app/Contents/MacOS/JASP' to start JASP
Could you give the output in the terminal? Please use the GitHub website to answer.
