### ISSUE TITLE
[Bug]:  error when carrying out 2-way repeated-measures ANOVA

### ISSUE THREAD

**Issue by tvgerdjikov** [jasp-stats/jasp-issues#2584]
### JASP Version

0.16.2

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

repeated-measures (two independent variables)

### What OS are you seeing the problem on?

Windows 10

### Bug Description

The error triggers when running a two-way repeated measures ANOVA. Users create the  data file using .csv file format in Excel and import into JASP. 

The strange thing is that some users get the error and others don't even though both are doing the exact same analysis.

Somehow this seems related to the users' IT account because it replicates when they log into another computer.

What's also puzzling is that we did not get the same error last year although we did the exact same analysis.

The error happens when they start specifying 'repeated measures cells' for a two-way ANOVA but not for a one-way ANOVA.

The JASP version is 16.2. 

This is a screenshot of the error message:

![error message](https://github.com/jasp-stats/jasp-issues/assets/38953715/b699b079-d46d-480f-9493-dcd81185b977)

### Expected Behaviour

Two-way repeated-measures output should have produced.

### Steps to Reproduce

1. These are outlined under bug description.
2. The error occurs when specifying 'repeated measures cells' on the attached csv file
[Tutorial 4 repeated measures.csv](https://github.com/jasp-stats/jasp-issues/files/14236513/Tutorial.4.repeated.measures.csv)

3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
I cannot replicate this wiht jasp 0.18.3 - can you update to the current version?
I also saved your csv as a jasp file - please check if my settings are intended by you.
[Tutorial.4.repeated.measures.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/14236837/Tutorial.4.repeated.measures.jasp.zip)
The file is renamed to .zip to be able to upload it here - just delete the .zip from the name before opening in jasp.
