### ISSUE TITLE
Error in library.dynam(lib, package.lin): DLL 'Bayesrel' not found 

### ISSUE THREAD

**Issue by EBotes** [jasp-stats/jasp-issues#2585]
### JASP Version

0.18.3

### JASP Module

Reliability

### What analysis are you seeing the problem on?

Unidimensional reliability

### What OS are you seeing the problem on?

Windows 11

### Bug Description

![Captura de pantalla 2024-02-12 110059](https://github.com/jasp-stats/jasp-issues/assets/100236401/2f8d5bf0-0f52-49fb-a99d-3e19df4da9fb)

### Expected Behaviour

Reliability should be provided

### Steps to Reproduce

1. Run reliability

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@EBotes 
Can you share your .jasp file by renaming to .zip and drag and drop here?
Sending it via mail does NOT work! Thx!

**Comment by EBotes** [comment]
Hi, yes sure. Please find attached the jasp file and log files.
[JASP 2024-02-11 21_08_03 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/14238716/JASP.2024-02-11.21_08_03.Desktop.log)
[JASP 2024-02-11 21_08_03 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/14238718/JASP.2024-02-11.21_08_03.Engine.1.log)
[Spanish L1 dataset invariance FLE.zip](https://github.com/jasp-stats/jasp-issues/files/14238725/Spanish.L1.dataset.invariance.FLE.zip)

**Comment by tomtomme** [comment]
@EBotes @juliuspfadt 
I downloaded the jasp file in jasp 0.18.3 flatpak / linux and refreshed the analysis without getting any error.

**Comment by EBotes** [comment]
Hi, I also now tried it on a different computer (windows 10; JASP 18.3) and it does run perfectly. Any idea of why it might not work on the one laptop with windows 11? We have tried re-installing JASP and get the same error

**Comment by boutinb** [comment]
Hi @EBotes How did you install JASP on WIndows 11: MSI, ZIP or Windows Store?

**Comment by EBotes** [comment]
Hi, through the MSI download on the website

**Comment by RensDofferhoff** [comment]
I cannot reproduce this on my windows 11 machine with the msi or Store releases.
Could you check if a reinstall fixes the issues (the windows store installer is faster) ?
Perhaps the long msi installation process partially failed.

**Comment by tomtomme** [comment]
same error as https://github.com/jasp-stats/jasp-issues/issues/2576
both systems run a non-english locale (spanish and netherlands)

**Comment by RensDofferhoff** [comment]
I see no way that is possible. But you never know. I going to find some Windows 11 machine to test

**Comment by RensDofferhoff** [comment]
@EBotes did you do anything special when installing?
Did you install it to the D:\ disk or something.

I have tried on 4 machines but none of them show this issue

**Comment by RensDofferhoff** [comment]
Could you try and install JASP from the windows store?
It uses a different installer type which might resolve the issue

**Comment by tomtomme** [comment]
@RensDofferhoff 
another one with non-english local, same error message on win 11 for reliability module...

**Comment by EBotes** [comment]
Hi all, apologies for the later response, I was away for a few days. We reinstalled now using the Windows store and everything works! Thank you so much!

**Comment by RensDofferhoff** [comment]
Hi thanks for reporting back.
Its good to know the Store install can be used to work around the issue

**Comment by tomtomme** [comment]
@EBotes 
We are still investigating the source of the issue. Any chance you ran antivirus software like McAffee? 
The latest user with that error had.

**Comment by EBotes** [comment]
Hi Thomas, the antivirus installed on the laptop is from Norton, let me know if you need any other info, happy to provide it!

**Comment by tomtomme** [comment]
@EBotes 
Would be interesting to know for us, if the install via https://jasp-stats.org works, if you deactivate the antivirus first.

**Comment by tomtomme** [comment]
@EBotes 
Did you have a chance on testing this without Norton Antivirus activated? If you have no time for testing, please also let us know.
