### ISSUE TITLE
html output preview in OSF

### ISSUE THREAD

**Issue by BTunca** [jasp-stats/jasp-issues#259]
Hi!

When I export the output to OSF, ODF preview for the JASP HTML file is simply the HTML code, when I download the file from OSF it looks normal though.

![capture](https://user-images.githubusercontent.com/27208030/49068273-9064bc00-f226-11e8-8064-39f86b8358bb.PNG)

Sorry if that is more of an issue with OSF preview.

Thanks one more time for JASP,

BTunca

**Comment by JorisGoosen** [comment]
This is more an OSF-viewer thing than anything we are responsible for, OSF decides it wants to show html like a text file and we can't force it to do something else. Maybe you could ask them?

You could however export to pdf and this should show up correctly, that is, the same way as opening it on your computer. I Now notice there is a bug with our export though.. #260 hopefully I can fix it before the next release and then this advice will be useful!

**Comment by JorisGoosen** [comment]
Ooh yeah, and a JSAP file itself will actually show the results on OSF when you select it. Maybe this is what you want?

**Comment by BTunca** [comment]
Hi! 

I am using JASP in a graduate seminar and some students had trouble installing the software due to admin rights on their computers. I therefore decided to go with the rollapp version, which does not allow saving without a premium account. My solution was that students could export their results to their OSF pages. Hence the HTML output instead of pdf.

Is it possible to export a jasp file to OSF? As far as I can see export data option exports a .csv datafile.

Thanks again for your assistance!

**Comment by AlexanderLyNL** [comment]
We also offer a pre-installed zipped version of JASP for this specific case. Would this help?

https://jasp-stats.org/download-pre-installed-version-jasp/

**Comment by JorisGoosen** [comment]
@AlexanderLyNL  that would be a specific issue I think.

@BTunca If you choose "Save As" from the file menu you can then subselect OSF and work directly on it. 
<img width="1192" alt="schermafbeelding 2018-11-27 om 12 47 45" src="https://user-images.githubusercontent.com/29062713/49080055-abddc000-f242-11e8-9f66-f3ea0901b56e.png">

**Comment by BTunca** [comment]
@JorisGoosen Unfortunately free version of rollapp does not allow the "save" option.

**Comment by BTunca** [comment]
@JorisGoosen Thank you, that works with rollapp also!

@AlexanderLyNL Thank you! Too many Apple users, unfortunately.

**Comment by JorisGoosen** [comment]
@BTunca great!

Too bad our Apple version can't be installed on their mac's though, it is much more up to date than rollapp.

**Comment by BTunca** [comment]
@JorisGoosen I might be the first person to instruct students to install JASP. I will contact the IT-people to safe-list it for the future (or even pre-install it!)
