### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by gdaem1** [jasp-stats/jasp-issues#2591]
### JASP Version

0.18.3

### JASP Module

Descriptives

### What analysis are you seeing the problem on?

Descriptive Statistics

### What OS are you seeing the problem on?

Windows 10

### Bug Description

Spelling error on the bottom of the descriptives table. It reads "The mode is computed assuming that variables are discreet." 

### Expected Behaviour

The message should read "The mode is computed assuming that variables are discrete." 

Difference between discreet vs discrete: 'discreet' means to be quiet, keep things secret. Discrete means individual or detached.

### Steps to Reproduce

1. Run descriptive statistics.
2. Choose 'Mode' for the central tendency.
3. Message is shown at the bottom of the result table.
4.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
confirmed. pretty funny bug :D - @vandenman?

**Comment by vandenman** [comment]
@gdaem1, @tomtomme oof that is a bad spelling mistake on my part, thanks for pointing this out! This should be fixed in the next version.
