### ISSUE TITLE
[T-Test] Plot descriptives using SE instead of CI%

### ISSUE THREAD

**Issue by seanhinkle46** [jasp-stats/jasp-issues#2592]
### Description

t-test descriptives plot: need standard error option

### Purpose

Quality of life, some prefer/require graphs with SE bars and t-test does not provide that option

### Use-case

Graphing t-test results

### Is your feature request related to a JASP module?

T-Tests

### Describe the solution you would like

SE option on descriptive plot in t-test (or other missing locations)

### Describe alternatives that you have considered

You can get the plot I am describing via an ANOVA tab, but that is tedious/confusing

### Additional context

Thank you for your help!

**Comment by tomtomme** [comment]
@seanhinkle46 
You can get it this way already, just put in the 68% here:
![image](https://github.com/jasp-stats/jasp-issues/assets/4428185/fcc0eae2-6c43-48b7-a86b-6d74d26cb7f7)

So can we close this?
