### ISSUE TITLE
reliability[Bug]: 

### ISSUE THREAD

**Issue by MaudScholten** [jasp-stats/jasp-issues#2593]
### JASP Version

0.18.3

### JASP Module

Reliability

### What analysis are you seeing the problem on?

Unidimensional Reliability

### What OS are you seeing the problem on?

Windows 11

### Bug Description

<img width="907" alt="jasp problem" src="https://github.com/jasp-stats/jasp-issues/assets/160042719/000cbeca-9f4e-44e5-8c2b-2c9505f1e553">
[Decathlon problem.zip](https://github.com/jasp-stats/jasp-issues/files/14281774/Decathlon.problem.zip)

When i tried to use the function; this was in on the screen:

"This analysis terminated unexpectedly.

Error in library.dynam(lib, package, package.lib): DLL 'Bayesrel' not found: maybe not installed for this architecture?

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.frequentistComputeScaleResults(jaspResults, dataset, options, model)

loadNamespace(x)

library.dynam(lib, package, package.lib)

stop(gettextf('DLL %s not found: maybe not installed for this architecture?', sQuote(chname)), domain = NA)"

### Expected Behaviour

I should see the reliability

### Steps to Reproduce

1. insert variables into variables space
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
same as #2585 and #2576

@MaudScholten 
How did you install - from windows store or via download form jasp-stats.org?
And are you using a non-english locale?
And can you share your .jasp file by renaming to .zip and drag and drop here?

**Comment by MaudScholten** [comment]
I installed it from a download form i think, it was via a link in my study
programme. My laptop is non-english, but the Jasp app is in English.

Op wo 14 feb 2024 om 16:49 schreef Thomas Langkamp ***@***.***

**Comment by tomtomme** [comment]
which language is your laptop. The other two issue reports had spanish and netherlands. The bayesrel R package or the jasp installer may have problems on win 11 in combo with non-englisch

**Comment by MaudScholten** [comment]
my language was netherlands!

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Thomas Langkamp ***@***.***>
Verzonden: Wednesday, February 14, 2024 7:59:41 PM
Aan: jasp-stats/jasp-issues ***@***.***>
CC: MaudScholten ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [jasp-stats/jasp-issues] reliability[Bug]: (Issue #2593)


which language is your laptop. The other two issue reports had spanish and netherlands. The bayesrel R package or the jasp installer may have problems on win 11 in combo with non-englisch

**Comment by RensDofferhoff** [comment]
We have had one report that installing jasp via the windows store resolves the issue.
Could you check if this also works for you?

**Comment by MaudScholten** [comment]
yes, problem is resolved, thanks!

Op do 15 feb 2024 om 15:01 schreef RensDofferhoff ***@***.***

**Comment by tomtomme** [comment]
@MaudScholten 
thx for the feedback :)
good to know that its working now.
closing then

**Comment by tomtomme** [comment]
@MaudScholten 
We are still investigating the source of the issue. Any chance you ran antivirus software like McAffee? 
The latest user with that error had.
