### ISSUE TITLE
[Bug]: Help not available in the Conditional Process Module 0.18.3

### ISSUE THREAD

**Issue by chantelanuit** [jasp-stats/jasp-issues#2595]
### JASP Version

0.18.3

### JASP Module

Process

### What OS are you seeing the problem on?

Windows 11

### Bug Description

The extensive help module that was available in 0.18.2 for the Conditional Process Model is not available anymore in 0.18.3 (when you click the blue information button) 
![Process](https://github.com/jasp-stats/jasp-issues/assets/24530165/ceada13e-aaef-41ff-9509-aa3dfa9afceb)

### Expected Behaviour

Display extensive help 

### Steps to Reproduce

1. click information button in the Processus (beta) module
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@chantelanuit 
Interesting. Help file is there for me on flatpak / linux running 0.18.3 and 0.19 beta, also when switching locales. Have you installed from the Microsoft Store or via download from jasp-stats.org?
Either way you could try the install route you did not take yet.

**Comment by chantelanuit** [comment]
From https://jasp-stats.org/thank-you-for-downloading-jasp-win64

**Comment by chantelanuit** [comment]
Did the install with Microsoft Store link, same problem.

**Comment by boutinb** [comment]
I see that you have JASP in french. Can you switch to english (and restart JASP), and try again?

**Comment by shun2wang** [comment]
@chantelanuit Did you checked the button in Preference->advanced->Generate markdown files for help ?

that's will override help files.

**Comment by tomtomme** [comment]
@shun2wang 
Confirm - that button needs to be unchecked. If checked almost all documentation disappears. Any explanation, what that button does or why everything disappears? There is no documentation of the button in the help file

**Comment by chantelanuit** [comment]
Thanks @shun2wang, you found the cause of the problem.

**Comment by boutinb** [comment]
Hmm, this button should not be available in production. I'll have a look.

**Comment by tomtomme** [comment]
@boutinb 
Yes, as discussed here: https://github.com/jasp-stats/INTERNAL-jasp/issues/2249

**Comment by maltelueken** [comment]
As mentioned in https://github.com/jasp-stats/INTERNAL-jasp/issues/2249, the option `Generate markdown files for help` is now only available in developer mode. This should prevent users from accidentally removing the help files, so I will close this issue.

**Comment by tomtomme** [comment]
confirmed. Unchecking developer mode also lets "generate markdown..." disappear in new beta.
