### ISSUE TITLE
[Bug]: Incorrect test accuracy for decision tree classifier when one class doesn't contain any prediction

### ISSUE THREAD

**Issue by thangngoc89** [jasp-stats/jasp-issues#2596]
### JASP Version

0.18.3

### JASP Module

Machine Learning

### What analysis are you seeing the problem on?

Decision tree classifier

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

In decision tree classifier, if there is a class that has no prediction, test accuracy calculation is lower than expected.

## Main bug: Decision tree with no predictions in class 4
<img width="669" alt="image" src="https://github.com/jasp-stats/jasp-issues/assets/3049054/1d85e7b9-4422-4286-bf6a-dba5166fe59e">
In the above confusion matrix, the classifier couldn't predict class 4. Expected accuracy should be:

```
(20 + 53 + 15) / 134 = 0.66
```

---
## Correct case: Decision tree with predictions in class 4
Trying to adjust parameters of the decision tree to force the prediction of class 4, the accuracy is correctly calculated.

<img width="737" alt="image" src="https://github.com/jasp-stats/jasp-issues/assets/3049054/ac386dab-1513-4e31-aa78-ff28731514f0">

```
(23 + 42 + 6 + 11) / 134 = 0.61
```
---
## Correct case: SVM classifier with no predictions in class 4

For SVM classifier without any predictions in class 4, the accuracy is correctly calculated:

<img width="668" alt="image" src="https://github.com/jasp-stats/jasp-issues/assets/3049054/7eff07b0-921e-4f41-a05c-501949958227">

```
(20 + 47 + 16) / 134 = 0.62
```

[jasp bug report.zip](https://github.com/jasp-stats/jasp-issues/files/14308750/jasp.bug.report.zip)

### Steps to Reproduce

I've included the jasp file with seed so you can observe the result just like the screenshot I've included above.
Here are the steps to reproduce from scratch:

1. Load the csv file (jasp_bug_report.csv). This is the actual data used in an unpublished manuscript. However, I've anonymized the files to avoid leaking information.
2. Add a new Decision tree classification analysis
3. Add `y` as target. Add `x1`, `x2`, `x3`, `x4` as features.
4. In `Data Split Preferences`, set `Test set indicator` to `split`
5. In `Training Parameters`, set `seed = 1`. Set tree complexity to `Fixed, complexity penalty = 0.01`
6. Observe the result as report above

Here is screenshots of full analysis setting:
<img width="647" alt="image" src="https://github.com/jasp-stats/jasp-issues/assets/3049054/578a52c6-5035-4e13-bd9f-197973421e13">
<img width="648" alt="image" src="https://github.com/jasp-stats/jasp-issues/assets/3049054/d605fa75-586a-44e3-8df3-d876d38e7f62">

...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@koenderks 
can you comment on the difference of the reportet test accuracy (0.54) vs. the calculation of @thangngoc89  (0.66)?

**Comment by koenderks** [comment]
I do not know what is causing this from the top of my head, I will investigate whenever the development module installation works again!

**Comment by koenderks** [comment]
Should be fixed with the above PR

<img width="1263" alt="image" src="https://github.com/jasp-stats/jasp-issues/assets/25059399/2decfa11-6526-43aa-8263-7111e589c670">

**Comment by thangngoc89** [comment]
Thank you all. Much appreciated!
