### ISSUE TITLE
[Bug]: Unidimensional Reliability (error in library.dynam)

### ISSUE THREAD

**Issue by willemijnUU** [jasp-stats/jasp-issues#2599]
### JASP Version

0.18.3

### JASP Module

Reliability

### What analysis are you seeing the problem on?

Unidimensional Reliability

### What OS are you seeing the problem on?

Windows 11

### Bug Description

I have to practice with unidimensional reliability for school, but it doesn’t work. I’ve tried deleting and downloading JASP again, deleting and downloading the file again and using different data, but I get the same error message every single time. And I’m not the only one. I know of at least one other student with the same problem
![image](https://github.com/jasp-stats/jasp-issues/assets/160480362/1e352435-2289-4281-a618-eb9bd43c673c)

### Expected Behaviour

It should have done the analysis

### Steps to Reproduce

1. Open a file
2. Click on reliability -> classical, Unidimensional Reliability
3. Add variables

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@willemijnUU 
Try installing via Windows Store please. That fixed it for multiple users.
Can you also share your .jasp file by renaming to .zip first and then drag and drop it here?
Also - do you use a non-english locale?

@RensDofferhoff @juliuspfadt 
Something is off here. Again this error. We have duplicates here: 
https://github.com/jasp-stats/jasp-issues/issues/2585
https://github.com/jasp-stats/jasp-issues/issues/2576
#2593

All on Win11 using msi with this "bayesrel" dll not found error.

**Comment by RensDofferhoff** [comment]
ah the mysterious issue returns!
Like @tomtomme suggested please reinstall (preferably using the windows store) and see if the issue remains.

**Comment by tomtomme** [comment]
@willemijnUU 
Since you are not responding, I guess the MSIX install route via win store did work?
It worked for 4 other people. The latest report indicates that the install problems you ran in was caused by antivirus software like McAffee. Do you have that installed? Btw, I would not advise using such software since Win11 has antivirus software already included, named windows defender and it usually does a better job than external / extra scanners.
