### ISSUE TITLE
Support PDF Export

### ISSUE THREAD

**Issue by JorisGoosen** [jasp-stats/jasp-issues#260]
Exporting results as PDF from JASP does not export graphs and the table has a weird makeup:
<img width="1389" alt="schermafbeelding 2018-11-27 om 10 12 39" src="https://user-images.githubusercontent.com/29062713/49070923-0ff58980-f22d-11e8-9d01-acab59d2ba0a.png">
left is pdf and right the exact same results in JASP

**Comment by JorisGoosen** [comment]
This is apparently not officially supported.

**Comment by dendrite75** [comment]
Is there a way to export results in a .doc or .rtf file?

**Comment by PsyTechMMU** [comment]
Transferring and/or exporting results is where JASP falls down to me. Exporting to HTML seemed a bit weird to me anyway, but as the only option it's far from ideal. At least exporting to .doc and .pdf please. :)

**Comment by JorisGoosen** [comment]
Well, we would like to add it. We're not entirely sure how to break up the output into proper pages, Should we simply keep them inline as is and just break whenever we reach A4/paper size?
Or should we go for separate "Figures" pages.
Or something else.

If anyone has suggestions, we would love to hear them.

**Comment by PsyTechMMU** [comment]
> Well, we would like to add it. We're not entirely sure how to break up the output into proper pages, Should we simply keep them inline as is and just break whenever we reach A4/paper size?
> Or should we go for separate "Figures" pages.
> Or something else.

It's these kinds of formatting things that make me wonder whether export to .doc/docx might be a better and more flexible approach for a start, perhaps with an option for inline or breaking at page ends. At last with a Word document, the results can be fixed/tweaked and then easily exported to PDF.

It's just such a shame that JASP makes a number of things easier (including formatting of tables etc.), but then is a bit of a pain to actually use.

**Comment by TimKDJ** [comment]
If you to the results panel and click on the downwards arrow next to `Results` there is a `copy` option. If you press this and then go to a Word document you can paste it.

<img width="280" alt="Schermafbeelding 2020-03-11 om 17 55 38" src="https://user-images.githubusercontent.com/18737241/76442710-9f429400-63c1-11ea-9066-5408e2af81b9.png">

Admittedly this doesn't look as nice as html, which I suppose, is the reason we don't formally export it to this format yet...

**Comment by JorisGoosen** [comment]
@PsyTechMMU we really do try to not make it a pain to use... In fact, we work really hard to make things easier but sadly enough we cannot do everything at once. 

I do agree that exporting it to doc(x) would make it a lot easier for the user to rearrange the contents as they see fit. I do not have word here though, so I cannot check how the copy command's output actually looks.

And as far as the pdf export goes, I guess we could implement in such a way that we simply give the user several options:
- export results as is, but move to a new page whenever a table, plot or collection would have to be split. Unless it wouldn't fit on 1 page anyway.
- give tables and plots their own pages? Maybe this isn't actually that useful.
- what do you mean by "inline" exactly?

**Comment by JorisGoosen** [comment]
Also exporting to PDF from html is really not that hard either, at least on Linux & MacOS this is built into the browser/OS. And Im pretty sure most pdf-readers and such software on Windows also adds this option.

Aka, print to PDF.

**Comment by EJWagenmakers** [comment]
Yes. We discussed this before (save as pdf or save as word/open office; how about save as .tex?) but other issues took priority. Let's put this back on the agenda.

**Comment by PsyTechMMU** [comment]
> Admittedly this doesn't look as nice as html, which, I suppose, is the reason we don't formally export it to this format yet...

Exactly. It's not really copying per se, as the pasted version is very differently formatted.



> @PsyTechMMU we really do try to not make it a pain to use... In fact, we work really hard to make things easier but sadly enough we cannot do everything at once.

Apologies if my tone sounded wrong/annoyed/disappointed; I know and appreciate that you all work to make JASP easier to use and better. I just want to provide feedback and hopefully help it be _even_ better for me, my research colleagues, and students. I wouldn't recommend it to undergrads, post-docs, and career researchers alike if I didn't think it was mostly **not** a pain to use overall.



> I do agree that exporting it to doc(x) would make it a lot easier for the user to rearrange the contents as they see fit. I do not have word here though, so I cannot check how the copy command's output actually looks.

Quite different. Attached should be the output of the "Beer Goggles" data output from the library (copied to Word, then exported to PDF so you can see it).
[Beer Goggles.pdf](https://github.com/jasp-stats/jasp-issues/files/4323538/Beer.Goggles.pdf)



> And as far as the pdf export goes, I guess we could implement in such a way that we simply give the user several options:
> 
> * export results as is, but move to a new page whenever a table, plot or collection would have to be split. Unless it wouldn't fit on 1 page anyway.

Yep, sounds like a good default.



> * give tables and plots their own pages? Maybe this isn't actually that useful.

I can see it having its place for table/plot-heavy outputs, especially if the option included a reference/link to the relevant table/figure.



> * what do you (@PsyTechMMU) mean by "inline" exactly?

The same as you, I think. I used that term because you did. :)




> Yes. We discussed this before (save as pdf or save as word/open office; how about save as .tex?) but other issues took priority. Let's put this back on the agenda.

Good news. I personally haven't (yet) adventured (and lost myself) in the tex world, but if it's an easy add, why not? However, I'd stress the usual/common use-cases e.g., Word being preferable IF the export to .doc(x) allows flexibility of formatting/moving etc. afterwards. I think the existing copy function is most of the way there though really.

From my perspective, I would love to see JASP development focus on improving workflows of current analyses/features (cf. the few enhancements I've suggested recently here) and truly making it the alternative to SPSS for a whole generation of Psychology students. :)

**Comment by JorisGoosen** [comment]
> Apologies if my tone sounded wrong/annoyed/disappointed; I know and appreciate that you all work to make JASP easier to use and better. I just want to provide feedback and hopefully help it be _even_ better for me, my research colleagues, and students. I wouldn't recommend it to undergrads, post-docs, and career researchers alike if I didn't think it was mostly **not** a pain to use overall.

No problem! Although I am happy you clarified, sometimes tone can be hard to read from a text-only interaction. ;)

> Quite different. Attached should be the output of the "Beer Goggles" data output from the library (copied to Word, then exported to PDF so you can see it).
> [Beer Goggles.pdf](https://github.com/jasp-stats/jasp-issues/files/4323538/Beer.Goggles.pdf)

This doesn't even use the same font... And the tables aren't even remotely the same.
 
> The same as you, I think. I used that term because you did. :)

Ah! Oops.
 
> > Yes. We discussed this before (save as pdf or save as word/open office; how about save as .tex?) but other issues took priority. Let's put this back on the agenda.
> 
> Good news. I personally haven't (yet) adventured (and lost myself) in the tex world, but if it's an easy add, why not? However, I'd stress the usual/common use-cases e.g., Word being preferable IF the export to .doc(x) allows flexibility of formatting/moving etc. afterwards. I think the existing copy function is most of the way there though really.

Well, tex has a bit of a steeper learning curve but gives much more flexibility in pagination and formatting after export. But having it all would be best obviously.

> From my perspective, I would love to see JASP development focus on improving workflows of current analyses/features (cf. the few enhancements I've suggested recently here) and truly making it the alternative to SPSS for a whole generation of Psychology students. :)

And that is basically why we haven't come around to this issue yet. :)

**Comment by lklende** [comment]
I experience that exporting to pdf, unlike export to html, only export the very first result. Would be nice if you could fix this issue, so that all the reults on the reult page were included in the pdf file.

**Comment by JorisGoosen** [comment]
@lklende thanks for the feedback, but this issue is actually for "implementing pdf export", which I did quite a while ago. So this issue will be closed and shouldve been.

Could you make a separate issue for your problem because I dont think Ive heard about this problem before.
