### ISSUE TITLE
JASP not responding on Chromebook[Bug]: 

### ISSUE THREAD

**Issue by annasofiaseger** [jasp-stats/jasp-issues#2602]
### JASP Version

0.18.3

### JASP Module

Unrelated

### What OS are you seeing the problem on?

ChromeOS

### Bug Description

JASP opens but is not responding. The only thing you can do is to change the window size and then you get from the start screen into attached view and you get the attached popup screen with this text. 

ASP was started without associated data file (csv, sav or ods file). But to edit the data, JASP starts a spreadsheet editor based on this file and synchronize the data when the file is saved. Does this data file exist already, or do you want to generate it?

Regardeless of choice JASP closes down and if you open again you're in the same loop again.
![image](https://github.com/jasp-stats/jasp-issues/assets/160946445/f73f7adb-17a8-4571-a654-b91eea59fa00)
![Screenshot 2024-02-22 20 36 07](https://github.com/jasp-stats/jasp-issues/assets/160946445/c8fa2052-a4d3-4748-8e23-fc072d100156)

I have uninstalled JASP and reinstalled. No change.

### Expected Behaviour

To be able to do choices in the JASP menus and open files etc.

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@RensDofferhoff @boutinb 
any idea? never have seen this warning. It does also not appear in closed bugs.

**Comment by boutinb** [comment]
Hi @annasofiaseger Quite strange indeed, this message should appear only when the user clicks on the Synchronization button. What happens if you click on the Cancel button?
