### ISSUE TITLE
[Bug]: Error in library.dynam(lib, package, package.lib): DLL 'Bayesrel' not found

### ISSUE THREAD

**Issue by Myrna1234** [jasp-stats/jasp-issues#2604]
### JASP Version

0.18.3

### JASP Module

Reliability

### What analysis are you seeing the problem on?

Cronbach's alpha

### What OS are you seeing the problem on?

Windows 11

### Bug Description

tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.frequentistComputeScaleResults(jaspResults, dataset, options, model)

loadNamespace(x)

library.dynam(lib, package, package.lib)

stop(gettextf('DLL %s not found: maybe not installed for this architecture?', sQuote(chname)), domain = NA)

<img width="508" alt="Screenshot error undimensional reliability" src="https://github.com/jasp-stats/jasp-issues/assets/161042720/c62ec514-1fec-41a6-933f-63191557c2bd">

### Expected Behaviour

I should get a Cronbach's alpha result, insteat I get this bug.
I think something didnt download as should have. 
I hope someone can help me.

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [x] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by Myrna1234** [comment]
I've deleted JASP en redownloaded it. When I did that, I saw this (see the picture as well) in McAfee:
C:\ Program Files
(x86)\JASP\Modules\renv-cache\v5\Bayesrel\0.7.7\2d3273dff153eeBf837f4d77d49b22g\Bayesrel\libs\x64\Bayesrel.dll

I said that it was safe so I marked is as solved. But unfortunetly it still doesn't work.

**Comment by juliuspfadt** [comment]
@RensDofferhoff I think we have seen this before... what was the fix? Download JASP from the windows store?

**Comment by RensDofferhoff** [comment]
We have been seeing this issue a lot recently with no clear cause. Virus scanners are a new aspect to it.
Could you try installing jasp from the windows store instead ?
This worked for others

**Comment by Myrna1234** [comment]
Yes, I will try that! Thanks both for the quick reactions!

**Comment by Myrna1234** [comment]
IT WORKKSSSS!!!! THANK YOU ALL SOOO MUCHHH!!!

**Comment by RensDofferhoff** [comment]
Great this gives us more hint towards the cause as well!
Microsoft rubber stamps the individual components of the MSIX and it runs somewhat containerized. So the virus scanner probably does not interfere as opposed to the MSI where the dll gets sniped. 

I really dont want to install McAfee to test...

**Comment by tomtomme** [comment]
just linking the duplicates
https://github.com/jasp-stats/jasp-issues/issues/2585
https://github.com/jasp-stats/jasp-issues/issues/2576
https://github.com/jasp-stats/jasp-issues/issues/2593
https://github.com/jasp-stats/jasp-issues/issues/2604
