### ISSUE TITLE
[Feature Request]: Associate JASP with .ods files

### ISSUE THREAD

**Issue by RNE365** [jasp-stats/jasp-issues#2609]
### Description

Associate Open Document spreadsheet files (.ods) with JASP for Windows Explorer

### Purpose

Make JASP easier to use

### Use-case

The user has a multi-sheet Excel workbook containing various data. Exporting as .ods would enable native access by JASP. Currently, JASP is not offered when the user selects the "Open with" option in Windows Explorer 

### Is your feature request related to a problem?

The cannot readily associated .ods files with JASP. The default is Excel.

### Is your feature request related to a JASP module?

Unrelated

### Describe the solution you would like

As a user I want to open .ods file in JASP by clicking on them in Windows Explorer

### Describe alternatives that you have considered

Hacking the registry.

### Additional context

I don't believe this is going to be a big ask, and yet it will make using JASP easier, better, and faster.

**Comment by RNE365** [comment]
Alas, without hacking the Registry, the only files I can associate with JASP appear to be .csv (which I've already done), .jasp .sav - for some reason JASP doesn't list in "Program Files" (maybe this is because I installed via the Windows Store), so I can't even navigate to the app.


________________________________

**Comment by RensDofferhoff** [comment]
I will sort this out! I must alter the manifest

**Comment by tomtomme** [comment]
@RNE365 
So this will be in the next jasp version 0.19!

Thx Rens for the quick fix!
