### ISSUE TITLE
[Feature Request]: Enable the user to determine which signal detection rules they whish to apply

### ISSUE THREAD

**Issue by RNE365** [jasp-stats/jasp-issues#2611]
### Description

SPC signal detection rules 

### Purpose

Make JASP more flexible

### Use-case

The user wants to specify the SPC signal detection rules

### Is your feature request related to a problem?

The current "Out-of-control Signals" appear to be applied to both average and range charts, which is incorrect usage.

### Is your feature request related to a JASP module?

Quality Control

### Describe the solution you would like

Provide the option to switch certain signal detection rules on and off.

### Additional context

Donald J. Wheeler and Rip Stauffer wrote a paper detailing the efficacy of SPC signal detection rules. 

JASP "Test 2" used on the "Variable Charts Individuals" is likely to result in false alarms.

https://www.spcpress.com/pdf/DJW322.Oct.17.Using%20Extra%20Detection%20Rules.pdf

**Comment by RNE365** [comment]
Partially a request, but the application of any detection rules on the Range Chart other than Rule 1 (points above the UCL) is incorrect.

Thanks.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tomtomme** [comment]
I closed this duplicate because the discussion was going on in your other  issue. Do you whish to leave both open?
