### ISSUE TITLE
[Bug]: Open a .jasp file in old version

### ISSUE THREAD

**Issue by Claudiaguia** [jasp-stats/jasp-issues#2613]
### JASP Version

0.17.3

### JASP Module

Unrelated, Other

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

Hi, im trying to open a .jasp file, exported in 0.18.3 version and open it in my computer (with version 0.17.3 intel) and simply can't. Is there any way to make it work? My computer doesn't support new versions. 
Thank you so much for your help! 

### Expected Behaviour

it should open the saved file.

### Steps to Reproduce

not applicable

### Log (if any)

not applicable

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@Claudiaguia 
I do not think that it is possible. 
But you could export results and data separately to open those on old systems.

Are you sure that you cannot update your old machine to MacOS 12 or newer? What machine exactly is it? What MacOS version does that machine run currently?

**Comment by Claudiaguia** [comment]
Hi, Thomas

 Thank you so much for your quick answer.
 Unfortunately it cannot be updated. I´ll leave a photo with all the info. of my machine.


Thank you once again,
Cláudia Guia
________________________________
De: Thomas Langkamp ***@***.***>
Enviado: 26 de fevereiro de 2024 17:39
Para: jasp-stats/jasp-issues ***@***.***>
Cc: Claudiaguia ***@***.***>; Mention ***@***.***>
Assunto: Re: [jasp-stats/jasp-issues] [Bug]: Open a .jasp file in old version (Issue #2613)


@Claudiaguia<https://github.com/Claudiaguia>
I do not think that it is possible.
But you could export results and data separately to open those on old systems.

Are you sure that you cannot update your old machine to MacOS 12 or newer? What machine exactly is it? What MacOS version does that machine run currently?

**Comment by tomtomme** [comment]
You can upload the photo via the github website. Via mail does not work

**Comment by Claudiaguia** [comment]
![printscreen](https://github.com/jasp-stats/jasp-issues/assets/161358446/9c940f7f-e68a-41ca-9d9b-3ad38b8e4ab3)

**Comment by boutinb** [comment]
To open a JASP file from 0.18.3 in a JASP 0.17 version will not work. The only way is to upgrade your old computer (it's anyway quite dangerous to keep an OS version which has no security update anymore). If you can't, the only solution is then to make a new JASP file by adding the analyses and the settings as in your 0.18.3 JASP file.
