### ISSUE TITLE
Machine learning regression add scaled MSE to evaluation metrics for backwards compatibility with versions prior to 0.18.3

### ISSUE THREAD

**Issue by Prakash-Books** [jasp-stats/jasp-issues#2619]
### JASP Version

0.18.3

### JASP Module

Machine Learning

### What analysis are you seeing the problem on?

Regression 

### What OS are you seeing the problem on?

Windows 11

### Bug Description

MSE Errors in Machine Learning Regressions

### Expected Behaviour

Machine Learning Regression output MSE shows Large Numbers. Ealier versions it was between 0 and 1, which is correct.

### Steps to Reproduce

1.Select any data for Machine Learning Regression
2. Select the Boosting Regressing
3. Check the Test MSE result
4. Note (Screen shots of HR dataset used in JASP 18.3 and JASP 16.4 versions are attached. Both gives difference MSE.
5.Jasp 16.4 gives MSE  0.028 where as JASP 18.3 gives MSE 72237.01
![JASP183](https://github.com/jasp-stats/jasp-issues/assets/138115910/b7110316-b931-4f1b-83ac-effff7ef01d4)
![JASP 164](https://github.com/jasp-stats/jasp-issues/assets/138115910/961ef172-28fd-43f2-a819-fe911438a4a6)

### Log (if any)

done

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by koenderks** [comment]
There is no reason why the MSE **should** lie between 0 and 1, since its range goes from 0 to infinity. However, what we did before was scale the target variable in all machine learning regression analyses. From version 0.18.2 (see also release notes here https://jasp-stats.org/release-notes/), we do not scale the target variable anymore since we figured that in practice predictions are preferably made using the unscaled target variable. However, that means that the MSE is now computed using the unscaled target variable and corresponding predictions. If you want to obtain the MSE from before v0.18.2, you can manually scale the target variable.

All the best

**Comment by Prakash-Books** [comment]
Dear Koen Derks,

I am the author of  book Titled "Practical Machine Learning - No Coding,
Easy and Fast Track Using JASP"
In the entire book Regression part is explained to analyse the result of
MSE and draw conclusions that if the MSE is near zero, good predictions are
possible.

Below is the link of my book.

https://www.amazon.com/Practical-Machine-Learning-No-coding-Software/dp/B0BW2LM8MJ

Park University USA is planning to use JASP and My book for introducing
machine learning for under graduate students.
The book drew good responses and at this point of time use may find it
difficult due to drastic changes.

Suggested th add one more row "MSE(Scaled)"  in the evaluation matrix so
that progression changes along with earlier versions  results also can be
made available to the users.

[image: image.png]

I am also authoring 2 new books,  HR analytics and Supply Chain Analytics
using JASP,  where it is mentioned that  scaled MSE (between 0 and 1) to
analyse the regression results. Adding one more row in evaluation metrics
will help the users to draw conclusions the level of predictions.

Best Regards
Dr. Prakash










https://www.amazon.com/Practical-Machine-Learning-No-coding-Software/dp/B0BW2LM8MJ

**Comment by koenderks** [comment]
Hi @Prakash-Books,

I've put the scaled MSE in the evaluation metrics now, it will be in the next release. Thanks for the suggestion.

**Comment by Prakash-Books** [comment]
Thanks a lot.

Best Regards.
Prakash
