### ISSUE TITLE
[Bug]: Missing Data in Repeated Measures ANOVA

### ISSUE THREAD

**Issue by gveciana** [jasp-stats/jasp-issues#2621]
### JASP Version

0.18.3

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

Repeated Measures ANOVA

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

I am trying to conduct a 6 X 3 repeated measures ANOVA for 54 participants. It has a lot of empty cells because not every single person saw every single combination of stimuli. If I leave the empty cells as "0", the repeated measures anova will run. If I remove too many of the zeros I get the below error message:

"Error while loading data. Please verify your repeated measures observations"

Is there a way to deal with empty cells in a repeated measures anova?
[Q1 RM.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/14476165/Q1.RM.jasp.zip)

### Expected Behaviour

Instead of the error message, the repeated measures anova test results should have displayed.

### Steps to Reproduce

1. input data into sheet
2. remove rougly 40% of the cells and make them empty
3. run repeated measures anova
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
This feature will come with the next jasp version hopefully. Sry, but it may need a month or two. The devs might have more details.
