### ISSUE TITLE
Failure to convert variable to continuous: values contain text[Bug]: 

### ISSUE THREAD

**Issue by cudzz** [jasp-stats/jasp-issues#2623]
### JASP Version

0.18.3

### JASP Module

Unrelated, ANOVA

### What analysis are you seeing the problem on?

Before-- Just opening data

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

I have data that I uploaded to JASP before (with fewer subjects) where the program automatically interpreted the variables I needed to be continuous as such. Now after cleaning up my fresh subset of data from new subjects in excel and exporting it as a cvs file, the variables will not change. They also won't change manually when I try to and the following message pops up: "failure to convert variable to continuous: values contain text".

I have also checked my data multiple times and don't have text in the columns that I want to change.

### Expected Behaviour

It should look like this: 
<img width="1135" alt="Screen Shot 2024-03-04 at 11 28 39" src="https://github.com/jasp-stats/jasp-issues/assets/162157359/888829d1-203e-43dc-8631-1af15018cfd0">

It's showing up like this: and I cannot change it.
<img width="1135" alt="Screen Shot 2024-03-04 at 11 29 10" src="https://github.com/jasp-stats/jasp-issues/assets/162157359/800b3934-b5a7-49a9-a8ea-745c263efe4a">

### Steps to Reproduce

Need help with this!

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [x] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@cudzz 
Can you share your CSV file?

**Comment by boutinb** [comment]
@cudzz Can you give us the dataset?

**Comment by cudzz** [comment]
[Raw Data-Table 1.csv](https://github.com/jasp-stats/jasp-issues/files/14498115/Raw.Data-Table.1.csv)

**Comment by cudzz** [comment]
[number valence data march 2024.csv](https://github.com/jasp-stats/jasp-issues/files/14498195/number.valence.data.march.2024.csv)

**Comment by cudzz** [comment]
[Number valence March 2024 .zip](https://github.com/jasp-stats/jasp-issues/files/14498225/Number.valence.March.2024.zip)

**Comment by cudzz** [comment]
[For JASP-Table 1.csv.zip](https://github.com/jasp-stats/jasp-issues/files/14498260/For.JASP-Table.1.csv.zip)

**Comment by cudzz** [comment]
Hi! Did you receive my file ^^?

**Comment by boutinb** [comment]
[For JASP-Table 1.csv.zip](https://github.com/jasp-stats/jasp-issues/files/14521177/For.JASP-Table.1.csv.zip)

There were trailing comma's at the end of your file. I've just removed them, and it works now.
