### ISSUE TITLE
[Bug] Missing dynamic  library in ANOVA on macOS

### ISSUE THREAD

**Issue by Kashish131103** [jasp-stats/jasp-issues#2624]
### JASP Version

0.18.3

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

Anova 

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

<img width="1470" alt="Screenshot 2024-03-04 at 10 23 39 PM" src="https://github.com/jasp-stats/jasp-issues/assets/162223301/ca58599b-1182-4123-a80f-a323619de5ed">

### Expected Behaviour

an analysis of the effect of an independent variable on the dependent variable should have been carried out. 

### Steps to Reproduce

1.   Press anova on the ribbon of options. then selected anova. then put independent variable in factor box
2. put dependent variable in dependent variable box 
3. then it shows this analysis terminated unexpectedly. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by Kashish131103** [comment]
I cannot send my file as it is a part of my assignment. Can you check from
here itself?

**Comment by tomtomme** [comment]
@Kashish131103 
This is a known bug (MacOS intel only) which we thought was fixed with jasp 0.18.1
Are you sure you are on 0.18.3?
And what is the exact version of your MacOS? 

Solved duplicates:
#2408
#2402
#2328
#2317
#2315

**Comment by boutinb** [comment]
HI @Kashish131103 What really strange is that the error message says that it finds the Matrix.so library in the R framework of JASP but in the 4.2 R version: since 0.18, we are using the 4.3 R version, there in no 4.2 version, so it seems that you are using an older JASP version. Can you check this by opening "About JASP" window ?

**Comment by Kashish131103** [comment]
Ok, I will check.

**Comment by tomtomme** [comment]
@Kashish131103 
Did you check your jasp version?
