### ISSUE TITLE
[Bug]: Correlation table messed up when column names have square brackets

### ISSUE THREAD

**Issue by patc3** [jasp-stats/jasp-issues#2625]
### JASP Version

0.18.3

### JASP Module

Regression

### What analysis are you seeing the problem on?

Correlation

### What OS are you seeing the problem on?

Windows 10

### Bug Description

The default table (with "Display pairwise" unchecked) doesn't show properly when column names have square brackets in their name (at least I'm guessing that's what the problem is). This is how the data are exported from LimeSurvey.

![image](https://github.com/jasp-stats/jasp-issues/assets/41131893/1c1569e5-f871-4453-8aba-75dc911d8c0b)

![image](https://github.com/jasp-stats/jasp-issues/assets/41131893/5bab73b9-9539-4f40-a280-5226b5758454)

![image](https://github.com/jasp-stats/jasp-issues/assets/41131893/16d55ca2-dba1-4c88-809d-8041ef9c2c12)

![image](https://github.com/jasp-stats/jasp-issues/assets/41131893/d6405989-2f32-4e4b-a90a-0b5ef40ac29e)

This happens with or without Pearson/Spearman. The problem disappears (i.e. doesn't happen) when I check "Display pairwise":

![image](https://github.com/jasp-stats/jasp-issues/assets/41131893/c4bf893c-5347-4d82-866c-d176e3636f5d)

### Expected Behaviour

Table should have been a correlation matrix

### Steps to Reproduce

1. have column names with square brackets in their name (I assume that's what causes this)
2. go to module regression > correlation
3. put variables in variables box

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@patc3 
Thanks for the report. This is a long standing known bug also for ANOVA, CFA, etc.
https://github.com/jasp-stats/jasp-issues/issues/2564
https://github.com/jasp-stats/jasp-issues/issues/2113
https://github.com/jasp-stats/jasp-issues/issues/1503

Throughout those issues we gathered that the following signs should not be allowed to enter in var names & labels:

/
"+"
"-"
[
]

Let us hope that this can be fixed for 0.19

**Comment by patc3** [comment]
Thanks a lot for the info @tomtomme

**Comment by shun2wang** [comment]
Well, as I took a rough glance, the problems may not be exactly the same. Some of them with special characters in the title indeed. This problem also has problems with result styles, such as `colspan` css style matching problems. I will see what Bruno and Joris's assessment here.

**Comment by JorisGoosen** [comment]
> @patc3 Thanks for the report. This is a long standing known bug also for ANOVA, CFA, etc. #2564 #2113 #1503
> 
> Throughout those issues we gathered that the following signs should not be allowed to enter in var names & labels:
> 
> / "+" "-" [ ]
> 
> Let us hope that this can be fixed for 0.19

Well these really ought to be allowed...
I will have a look at this before the 0.19 release comes up I hope!

**Comment by JorisGoosen** [comment]
I suppose I could replace those by [html codes](https://psdtowp.net/html-codes-special-characters.html)
So `[ -> &#91;` and such, specifically for columnnames of `jaspTable`s
