### ISSUE TITLE
[Bug]: ICC calculation in the reliability module does showinh only "." for output values.

### ISSUE THREAD

**Issue by utkb** [jasp-stats/jasp-issues#2627]
### JASP Version

0.18.3

### JASP Module

Reliability

### What analysis are you seeing the problem on?

ICC

### What OS are you seeing the problem on?

Linux, Flatpak, Ubuntu

### Bug Description

ICC calculation in the reliability module does showinh only "." for output values. For double checking, i used "Interrater Data from Shrout and Fleiss (1979)" from JASP data respiratory.

This is normal output:
![resim](https://github.com/jasp-stats/jasp-issues/assets/13717035/e32e6ff5-75af-4c95-b8b0-07079972100f)

But when i click refresh:
![resim](https://github.com/jasp-stats/jasp-issues/assets/13717035/5fcc4784-d739-4544-bfc1-56ef3d331600)

The output values disappear.

### Expected Behaviour

I expect the normal output with values.

### Steps to Reproduce

1. Import Interrater Data from Shrout and Fleiss (1979) or any appopriate data.
2. Refresh all calculations.

### Log (if any)

[JASP 2024-03-07 11_17_07 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/14521099/JASP.2024-03-07.11_17_07.Desktop.log)
[JASP 2024-03-07 11_17_07 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/14521100/JASP.2024-03-07.11_17_07.Engine.0.log)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment]
@utkb thanks for creating the issue. I cannot replicate this on my MacBook. Maybe someone with a linux can... @tomtomme ?

**Comment by utkb** [comment]
Thank you for your answer and effort. I checked this issue on a fresh install of Ubuntu 22.04 version, and i can confirm this issue effects also fresh install. But i checked if problem is dependent on language settings. If i change system language and format to English, thare is no issue.

**Comment by tomtomme** [comment]
@utkb 
Your screenshot shows the problem using the english locale. But now you say with english it is fine? How is that possible?

On Manjaro I can also not reproduce (neither with 0.18.3 nor 0.19beta)

**Comment by utkb** [comment]
> @utkb Your screenshot shows the problem using the english locale. But now you say with english it is fine? How is that possible? What locale did you test besides en?
> 
> And what about a fresh ubuntu install + updates available for 22.04?
> 
> On Manjaro I can also not reproduce (neither with 0.18.3 nor 0.19beta, english, german and spanish)

Yes, it is strange but I was not changed the JASP locale settings but system locale settings.

**Comment by tomtomme** [comment]
@utkb 
thx. that answers my first question. I cannot replicate this on manjaro however. I use german as system locale, switched to english and back to german via plasma settings and via manjaro settings manager and refreshed the analysis at each step in jasp 0.18.3.

Remaining questions:

- [ ] What locale did you test besides en?
- [ ] What about a fresh ubuntu install + updates available for 22.04?
- [ ] And if you have time to test: What about ubuntu 22.10 or even 23.10 etc.?

**Comment by utkb** [comment]
I realized issue in Turkish locale. I will test for last two question.

**Comment by utkb** [comment]
> What locale did you test besides en?

The problem is in the Turkish Locale.

> What about a fresh ubuntu install + updates available for 22.04?

This not solved the problem.

> And if you have time to test: What about ubuntu 22.10 or even 23.10 etc.? Maybe it is a flatpak bug that is solved already, but it may not be shipped with ubuntu 22.04 (yet).

I tested it with fresh install of up-to-date Manjaro XFCE. Selected Manjaro because rolling relase and have new version of packages. This propblem exists in Manjaro too.

**Comment by JorisGoosen** [comment]
Well, maybe its not an UTF-8 locale?

Perhaps @utkb can post the output from the command `locale` in the turkish locale with the problem.

**Comment by utkb** [comment]
[utkub@utku-standardpcq35ich92009 Masaüstü]$ locale
LANG=tr_TR.utf8
LC_CTYPE="tr_TR.utf8"
LC_NUMERIC=tr_TR.UTF-8
LC_TIME=tr_TR.UTF-8
LC_COLLATE=tr_TR.UTF-8
LC_MONETARY=tr_TR.UTF-8
LC_MESSAGES=tr_TR.UTF-8
LC_PAPER=tr_TR.UTF-8
LC_NAME=tr_TR.UTF-8
LC_ADDRESS=tr_TR.UTF-8
LC_TELEPHONE=tr_TR.UTF-8
LC_MEASUREMENT=tr_TR.UTF-8
LC_IDENTIFICATION=tr_TR.UTF-8
LC_ALL=

**Comment by JorisGoosen** [comment]
Thanks @utkb !

Is "utku-standardpcq35ich92009 Masaüstü" your hostname by any change ?
As in, what is the output of `hostname`?

**Comment by tomtomme** [comment]
@utkb 
Oh no! If its the infamous username / hostname bug again... you will need to shorten your host / username to make it work. R cannot handle certain long hostnames. 
See 
https://github.com/jasp-stats/jasp-issues/issues/1131
https://github.com/jasp-stats/jasp-issues/issues/2561

**Comment by utkb** [comment]
> @utkb Oh no! If its the infamous username / hostname bug again... you will need to shorten your host / username to make it work and maybe also remove all ü ä spaces dots etc. R cannot handle certain long hostnames. See duplicates #1131 #2289 #2598 #2561

I take this hostname from Virtual Machine Manjaro System that i install for testing the issue. On my actual system my hostname "utku". But i have same problem here.

**Comment by JorisGoosen** [comment]
So @utkb at your normal system its basically something like utku@utku right? No spaces there then...

@tomtomme could you try the same turkish locale?
(Saves me setting up a linux system just now ;))

**Comment by RensDofferhoff** [comment]
testing it

**Comment by RensDofferhoff** [comment]
@JorisGoosen So it works on seemingly all locals except Turkish.
So that explains why we never noticed.
I have no real explanation aside that some dep 50 layers deep doesn't handle a conversion? Googling utf8 turkish shows a bunch of issues.

**Comment by utkb** [comment]
Yes, we normally not alone, if a problem exists in Turkish, also can be found in French and others have special characters.

I can use normally with English locale, but I can run all tests for solution of problem. Thank you very much and please ask me if you require any additional tests.

**Comment by JorisGoosen** [comment]
So weird...
Especially given that there shouldnt be any conversions at all anyway if its all in utf-8, especially on linux...

**Comment by tomtomme** [comment]
So this seems all very unfortunate but I guess we have to close this one now. Since this seems not to be fixable, right?

**Comment by tomtomme** [comment]
@JorisGoosen 
Yes, but it could only be fixed by the r-maintainer? Or does someone from the JASP team maintain this package, @juliuspfadt ?

**Comment by JorisGoosen** [comment]
Well, we dont know what exactly is broken. First step would have to be to narrow down the actual culprit here, only then do we even know who might or might not fix it...
