### ISSUE TITLE
[Bug]: Edit data buttons do not switch lang

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#2628]
### JASP Version

0.19 beta and 0.18.3

### Commit ID

f5f90baafeb87752846230cf5c87bae2d132dfda

### What analysis are you seeing the problem on?

edit data ribbon buttons

### What OS are you seeing the problem on?

Flatpak

### Bug Description

mixed language after switch, here for spanish:
![image](https://github.com/jasp-stats/jasp-issues/assets/4428185/a3408407-86a4-4adf-abf7-b33c9b86b191)

same for german
![image](https://github.com/jasp-stats/jasp-issues/assets/4428185/3669dff1-6694-4866-b1aa-bfe88678c318)

etc:
![image](https://github.com/jasp-stats/jasp-issues/assets/4428185/18189f12-65ab-4fab-8764-3174617057ab)

The translations are in weblate and jasp already, they just do not switch. Also for all other ribbon buttons of edit data mode

### Expected Behaviour

lang should switch

### Steps to Reproduce

1. open jasp
2. switch lang

**Comment by chantelanuit** [comment]
Same issue in French. I was wondering why even after adding the correct translation on the weblate, it would no be updated in the application.

**Comment by tomtomme** [comment]
I just saw this is a known issue and already discussed internally here: https://github.com/jasp-stats/INTERNAL-jasp/issues/2372

**Comment by chantelanuit** [comment]
The page you referred to leads to a #404 error

**Comment by tomtomme** [comment]
Yeah sry, its an internal issue

**Comment by boutinb** [comment]
Yes this is a well-known issue. But after starting JASP again, you get fortunately the right language.

**Comment by boutinb** [comment]
Hello @chantelanuit , this is because the string 'Edit Data' was not yet translated into 'Éditer les données' pour 0.18.3. This has been translated since, and this will work for 0.19. 
If you are interested in helping us for translating JASP in Franch, please read this document https://jasp-stats.org/translation-guidelines/.
