### ISSUE TITLE
[Bug]: Descriptive Statistics and ANOVA crashed when I tried using them.

### ISSUE THREAD

**Issue by mbm54635** [jasp-stats/jasp-issues#2630]
### JASP Version

0.18.3

### JASP Module

ANOVA, Descriptives

### What analysis are you seeing the problem on?

Not sure.

### What OS are you seeing the problem on?

Windows 10

### Bug Description

[JASP info.pdf](https://github.com/jasp-stats/jasp-issues/files/14529433/JASP.info.pdf)

I have attached the file showing, I hope, the OS, which may not be windows 10. I tried creating a descriptive analysis and an ANOVA off of data that would not transfer in. Then I was unable to use the data either when I typed the data directly and manually into the data area.

### Expected Behaviour

The engine would not run or whatever was the crash. There are two pictures that cover this in the pdf.

### Steps to Reproduce

1. Type data in.
2. Select Descriptive Statistics or ANOVA
3. Program should not crash and should give good answers.
4.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@mbm54635 
you are on win10 

- [ ] Can you show a screenshot of the error message or was there just a crash without an error?
- [ ] What kind of data did you type in?
- [ ] Can you ope any given data from the data library or load CSV files?

**Comment by mbm54635** [comment]
OK. So you are telling me I was on win10 for that computer?

**Comment by tomtomme** [comment]
Yes, since you wrote:  "I hope, the OS, which may not be windows 10"

Can you answer / check:

- [ ]  What kind of data did you type in? Can you show a screenshot from the data view? Or upload the file?
- [ ]  The anova did not crash - it does produce no result because you did not include a Factor. Probably your region var should be nominal and moved up one box.

**Comment by mbm54635** [comment]
The data had the titles 'region' and 'complaints' and I tried importing
from a csv, if I am right? Then numbers. Then I typed the info in, with the
titles in row one, then i moved data up and made the titles in the title
area above the data. What is nominal? Did I already try this? (Per what I
said here start of this email.)

**Comment by tomtomme** [comment]
Statistical data can have 3 levels of measurement: nominal, ordinal and scale (metric). You can change those in data view, see https://www.youtube.com/watch?v=i47IYCaI0rg

I can help only if you upload your csv file or show me a screenshot of the full data set. The variable names do not matter that much, I already saw them in the screenshots you uploaded.

**Comment by mbm54635** [comment]
This is the data. I do not have JASP on the computer I am using currently,
that one is back at the apartment. JASP also said that JASP was unable to
use this data set, cause could not load the doc as .xlsx.

**Comment by tomtomme** [comment]
you cannot upload data via email. please go to the github website and drag and drop the data set there. If the file type is .jasp rename it to .zip before. 
And yes, xlsx is not supported, but CSV and ODS are.

**Comment by mbm54635** [comment]
[WickedWitch.csv.xlsx](https://github.com/jasp-stats/jasp-issues/files/14530082/WickedWitch.csv.xlsx)
 
Will this work? I seem to be unable to download this document as any except the above.

**Comment by tomtomme** [comment]
the data works fine for me, see:
![image](https://github.com/jasp-stats/jasp-issues/assets/4428185/60797840-b149-4afe-8476-e669d5ed6c59)


I saved it in ODS format in Excel for you, then opened in JASP and everything is fine.
Here the ODS
[WickedWitch.ods](https://github.com/jasp-stats/jasp-issues/files/14530141/WickedWitch.ods)

**Comment by mbm54635** [comment]
OK. Cool. That was last weeks assignment, I will try to complete some of this weeks assignment using what you did, that is, saving in ODS format. I usually use Apache OpenOffice, should this work there also? I really appreciate your assistance!

**Comment by tomtomme** [comment]
Yes. Openoffice is okay. But you should update to libreoffice. The apache version is not maintained anymore.
