### ISSUE TITLE
Need to import to JASP in .ods form probably[Bug]: 

### ISSUE THREAD

**Issue by mbm54635** [jasp-stats/jasp-issues#2632]
### JASP Version

0.18.3

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I have access only to a pdf file, which I can open, or a other type of file that I have no idea how to open. The problem is that I might need to import into OpenOffice to set the materials as an .ods. The file kept trying to open under microsoft, however, I am unable to get access to this, my password does not work. So all I have is a pdf document, can this be set to .ods for me? I had trouble opening my other info bit. If I cannot import the pdf, how would I go about placing the materials into JASP to run the program? Could I open the document into sheets (google.com excel equivalent)? Then save as .ods? Or type into sheets then download as .ods? Have a great day!

### Expected Behaviour

I should be able to open the spreadsheet into OpenOffice or google.com sheets.

### Steps to Reproduce

1. Try to open document link by clicking on.
2. Document allows me to open into google.com sheets or OpenOffice, not try to open in MS, to which I have no access.
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by mbm54635** [comment]
Would just typing into a google spreadsheet and then download as .ods work? Or copying them? I might try this right now.

**Comment by tomtomme** [comment]
Yes. Typing in and saving as ods will work. also copy pasting from pdf to some spreadsheet-program should work. then save as ods and open in jasp. Please know, that such issues are better served in jasps forum https://forum.cogsci.nl/categories/jasp-bayesfactor
Because this issue tracker is for bugs and feature requests.
Thanks
