### ISSUE TITLE
[Bug]: Results are not displayed

### ISSUE THREAD

**Issue by cristiancdepy** [jasp-stats/jasp-issues#2637]
### JASP Version

0.18.3

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

All analysis

### What OS are you seeing the problem on?

Windows 10

### Bug Description

![imagen](https://github.com/jasp-stats/jasp-issues/assets/22536660/6b166e86-1795-4f7f-8673-d2f466cd8394)
I can't view the results, they are there but it doesn't allow me to view it, the gray background

### Expected Behaviour

The graphs and results of the analyzes should be displayed

### Steps to Reproduce

1. Select any analysys
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @cristiancdepy, If you open a data file with JASP, can you see the data, and can you then an analysis ?

**Comment by cristiancdepy** [comment]
Hi @boutinb, i can see the data but not the analysis and graphic, because the windows is gray as in the image i attached, could it be a Windows 10 library?? 

![imagen](https://github.com/jasp-stats/jasp-issues/assets/22536660/8ec19336-bbea-4fa3-aaeb-fd77adf1d2c2)

**Comment by tomtomme** [comment]
Is your windows 10 fully updated?

**Comment by tomtomme** [comment]
Or a virus scanner that blocked something during install? Also install via ms store might help.

**Comment by shun2wang** [comment]
@cristiancdepy could you open cmd.exe and path to jasp.exe, to run:

`JASP.exe --webEngineArgs --remote-debugging-port=1234`

then open the Microsoft edge browser view this page:
`http://localhost:1234`
then see if error messages in 'console' window.

**Comment by boutinb** [comment]
@boutinb You can also try to start JASP with the safeGraphics option. For this:
- Start a command prompt by typing command prompt in the Start menu.
- Type "c:\Program Files (x86)\JASP\JASP.exe --safeGraphics" > logJASP.txt
- Check whether you have still the same problem.
- If yes, type 'notepad logJASP.txt'
- Send me these log files in a comment of this GitHub issue.

**Comment by cristiancdepy** [comment]
After restarting the computer several times, it starts showing the graphics, it could be a Windows 10 update. Problem solved. Thank you so much.

![imagen](https://github.com/jasp-stats/jasp-issues/assets/22536660/aa6768b5-8ef5-49cd-9130-74d6227f6fcb)

**Comment by boutinb** [comment]
Nice to hear it solved! Did you start JASP with the safeGraphics mode as I told you? Because once you have started with this setting, it is stored and afterwards JASP starts always with this setting. You can unset this in JASP if you uncheck the checkbox 'Safe Graphics mode' in the hamburger menu, Preferences/Interface/Miscellaneous options. This setting takes effect only when you restart JASP. I tell you that because it might be that this setting could have solved your problem.
