### ISSUE TITLE
[Feature Request]: grey out "Missing values" and show them as they are instead of a dot

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#2638]
### Description

Since some time now cells show a dot, when they are empty, or when they contain "missing value". Would be cool to show the missing values as they are, but greyed out instead of the dot.

### Purpose

Missing values can be a valuable source of information and during data editing, when some have to be entered or altered it would be cooĺ to see them. Different missing value codes can mean different things, like 

- I did not understand the question
- I do not care
- I do not want to answer this question 
- I cannot answer this question
- No valid measurement / implausible / out of range (e.g. 200 years old)
- No measurement due to low battery etc. 
- no measurement due to lost signal
- no measurement due to ...

### Use-case

To improve questionaires or distinguish different measurement errors of measurement instruments already in data view.

### Is your feature request related to a problem?

Currently missings and empty cells look the same.

### Alternatives and Problem
I can already distinguish the frequencies of those missing values codes if I introduce labels, like discussed here: https://github.com/jasp-stats/jasp-issues/issues/396
But this does not help during data editing. Of course I could just delay to enter the missing value codes into the list of missing values and I would then see those missing values in data view instead of the dot. But when I import a file like a SAV that has already missing values I might miss that they are there... because they just look like an empty cell / dot.

related: https://github.com/jasp-stats/jasp-issues/issues/2500

**Comment by boutinb** [comment]
In the https://github.com/jasp-stats/jasp-desktop/pull/5367 PR prom @JorisGoosen, there is already the feature to show in grey the real value when it differs from the displayed value for scale column. I think it would be great to generalise this, to always display in grey the real value in grey when it differs from the displayed value (either because of a label, or an empty value), for all columns.

**Comment by JorisGoosen** [comment]
But right now in my PR:
- if scalar: left text is value and greyed out right text is label
- else: right text is label and greyed out right text is value

But if something is set as an empty value what do you show?
Is the right text the label suddenly for ordinal/nominal. Or suddenly the value for scalar?

I guess the best would be to add for empty values:
- if scalar: left text is empty-value-label and greyed out right text is label
- else: right text is  empty-value-label and greyed out right text is value

Would that work?

**Comment by tomtomme** [comment]
Did you mean

else: "left" text is empty-value-label and greyed out right text is value

?

**Comment by JorisGoosen** [comment]
Oops yes, edited it

**Comment by tomtomme** [comment]
Then I am all for it :D

**Comment by tomtomme** [comment]
loving how this was implemented. Much much love!!!
