### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by tangyuanduorou** [jasp-stats/jasp-issues#2639]
### JASP Version

0.18.3

### Commit ID

no

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

anova

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

nk

### Expected Behaviour

nk

### Steps to Reproduce

1.mld
2.
3.
...

### Log (if any)

no

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by JohnnyDoorn** [comment]
Hi @tangyuanduorou ,

Could you be a bit more descriptive of the bug you encounter? I do not see any description or screenshot in your bug report.

Kind regards
Johnny
