### ISSUE TITLE
JASP keeps crashing while performing network analysis 

### ISSUE THREAD

**Issue by pdf1337** [jasp-stats/jasp-issues#264]
Keeps crashing after I load in variables to perform a network analysis. 

Version 0.9.1.
Windows 10

![image](https://user-images.githubusercontent.com/45609577/49475376-e8259900-f7cb-11e8-84a1-d93ebcf68c65.png)

**Comment by akashrajkn** [comment]
@pdf1337 Thank you for reporting the issue. Can you send me the `.jasp` or `.csv` file containing the data?

**Comment by pdf1337** [comment]
Thanks for your responds. Attached the data. So I'm able to plot the network, but when I'm trying to fiddle around with it (e.g. adjust node size or calculation method), it shuts down. 

[Data_for_support.zip](https://github.com/jasp-stats/jasp-issues/files/2650246/Data_for_support.zip)

**Comment by akashrajkn** [comment]
@pdf1337 could you please attach the file again? The one attached is an empty archive. (If possible could you save the `.jasp` file before changing the options?)

**Comment by pdf1337** [comment]
Any news on this?

**Comment by akashrajkn** [comment]
@pdf1337 I didn't have a chance to check it out. I'll take a look at it tomorrow and let you know.

**Comment by pdf1337** [comment]
Any luck on resolving this issue?

**Comment by App-State-Prof** [comment]
I was trying to run network analysis today. If I try to change the estimator, or change the variable posting from node to Legend, Jasp shuts down.

**Comment by AlexanderLyNL** [comment]
The fix will be incorporated in the next version 0.9.3

**Comment by sujitiiml** [comment]
I am using a dataset of 27 items scale consisting of about 10000 responses. The file is in CSV format. Every time I try to visualise the network, JASP crashes and closes unexpectedly..... I am using Windows 10 with 64 bit... Using JASP 0.9.2
Attaching the screenshot and dataset...


![jasp](https://user-images.githubusercontent.com/42088066/57757204-925a0300-7712-11e9-9154-1002bde631fc.PNG)
[data.xlsx](https://github.com/jasp-stats/jasp-issues/files/3181425/data.xlsx)

**Comment by TimKDJ** [comment]
@sujitiiml the "Network plot" does not work correctly in 0.9.2 (basically you cannot change any input option once you select "Network plot"), but this problem is fixed in 0.9.3.

We'll release 0.9.3 in the coming weeks.
