### ISSUE TITLE
[Bug]: Probability density function of F(1,95) with highlighted area

### ISSUE THREAD

**Issue by hugoquene** [jasp-stats/jasp-issues#2640]
### JASP Version

0.18.3

### JASP Module

Other

### What analysis are you seeing the problem on?

Probability, F-distribution

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

Using Distributions module, I tried to draw a probability density graph of F(1,95), with the area between F=0 and F=1 highlighed. The horizontal axis ranges from 0 to 10. Drawing the graph works fine but highlighting the area from 0 to 1 results in an error, see below. 
Mac OSX 14.2.1, macmini 2023, Apple M2 chip, 24 GB RAM. 
--
 
This analysis terminated unexpectedly.

Error in if (y < 0.1 * max_y) y <- y * 5 else y <- y/3: missing value where TRUE/FALSE needed

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.ldShowDistribution(jaspResults = jaspResults, options = options, name = gettext('F-distribution'), parSupportMoments = .ldFParsSupportMoments, formulaPDF = .ldFormulaFPDF, formulaCDF = .ldFormulaFCDF, formulaQF = .ldFormulaFQF)

.ldFillPDFContainer(pdfContainer, options, formulaPDF)

.ldPlotPDF(pdfContainer, options)

.ldFillPlotPDF(pdfPlot, options)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

### Expected Behaviour

proper area under the curve of F highlighted. 

### Steps to Reproduce

1. select Predictions, F distribution
2.df1=1, df2=95, ncp=0, display Probability density function, Range x from 0 to 10
3.Highlight Probability, Interval from 0 to 1
...bingo

### Log (if any)

<img width="1326" alt="Screenshot 2024-03-19 at 21 35 36" src="https://github.com/jasp-stats/jasp-issues/assets/24574995/a186d948-282a-4e97-80fc-d703024291a7">

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
confirmed. same on flatpak

![grafik](https://github.com/jasp-stats/jasp-issues/assets/4428185/4646caf4-fa50-4d07-afed-1dd97967a9d5)
