### ISSUE TITLE
Jasp 0.18.3.0 not downloading to my laptop

### ISSUE THREAD

**Issue by peterubuane** [jasp-stats/jasp-issues#2642]
### JASP Version

0.18.3

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

I am unable to download jasp to my windows 10 laptop. The download stops before completion and says "couldn't download download. Needs authorisation."

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I am unable to download jasp to my windows 10 laptop. The download stops before completion and says "couldn't download download. Needs authorisation."

### Expected Behaviour

Simply download and then install

### Steps to Reproduce

![20240321_221330](https://github.com/jasp-stats/jasp-issues/assets/71087979/8474a37f-5466-48fa-964d-14c4be1aac7e)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Interesting. Sounds like the laptop might be handled by your university? And that your IT Department blocks such downloads? Then you would need to ask your IT for permission.

**Comment by peterubuane** [comment]
No. My laptop is not on my institution's network at all.

Thank you.


Dr Peter Odion Ubuane, MBChB, FWACPaed
Consultant Paediatrician
Institute of Maternal & Child Health/Department of Paediatrics
Lagos State University Teaching Hospital
1-5 Oba Akinjobi Way
Ikeja, Lagos, Nigeria
+234-8085645675

**Comment by boutinb** [comment]
Hi @peterubuane But the message says that you need authorization. If you are admin of your laptop, there should not be any problem to download it, so apparently you have no full privilege on this laptop.
What you can do to avoid this problem, is to download it via the Microsoft store, if not you can stil try the pre-installed version.

**Comment by peterubuane** [comment]
Thank you very much. Downloading it via microPeter store was the
perfect solution!

God bless you!

Dr Peter Odion Ubuane, MBChB, FWACPaed
Consultant Paediatrician (Neonatal Unit)
Institute of Maternal & Child Health/Department of Paediatrics
Lagos State University Teaching Hospital
1-5 Oba Akinjobi Way
Ikeja, Lagos, Nigeria
+234-8085645675
