### ISSUE TITLE
[Bug]: Error editing plot 

### ISSUE THREAD

**Issue by glacier103** [jasp-stats/jasp-issues#2645]
### JASP Version

0.18.3

### JASP Module

Visual Modeling

### What analysis are you seeing the problem on?

Linear regression

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

I cannot edit the scale for my plot. The low limit of my data is 13 and upper limit is 50, but JASP doesn't allow me to change the y-axis. I can, however, edit the x-axis to my desired numbers.
<img width="803" alt="Screenshot 2024-03-23 at 10 41 33 PM" src="https://github.com/jasp-stats/jasp-issues/assets/164692790/1d98a8dd-801f-4355-84b7-2e0aa58f4c58">

### Expected Behaviour

I should be able to change the y-axis scale starting from 0 to 50. 

### Steps to Reproduce

1. I used the latest version of JASP but still cannot fix the bug. 
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
@dustinfife I cannot reproduce the error, but I cannot either change the min and max of the ticks. On the other hand I change the labels of the existing ticks.

**Comment by tomtomme** [comment]
@glacier103 
The plot shown is part of a multiplot right? Can you share your .jasp file by renaming to .zip and drag&drop it here?
