### ISSUE TITLE
Looking for Proportional test type within JASP 

### ISSUE THREAD

**Issue by Franck6S** [jasp-stats/jasp-issues#2647]
### Description

Wanted to perform proportional test

### Purpose

Performing proportional test

### Use-case

performing comparison of several samples/cases

### Is your feature request related to a problem?

Do not find it into JASP 0.18.3

### Is your feature request related to a JASP module?

Equivalence T-Tests

### Describe the solution you would like

Being able to alanyse a series proportion of sample of population

### Describe alternatives that you have considered

It was done with Minitab 

### Additional context

Please see example case photos
![Sample of population to test 1_2](https://github.com/jasp-stats/jasp-issues/assets/152309774/329e33d7-409e-41be-91ca-5629a4704445)
and related response expected to be performed in JASP : 
![image](https://github.com/jasp-stats/jasp-issues/assets/152309774/df4a3cf5-90ef-4d28-9d6e-92318a4eb77d)

**Comment by UGatgithub** [comment]
I support this idea from Franck.

**Comment by tomtomme** [comment]
Seems to me like a multinomial test
![image](https://github.com/jasp-stats/jasp-issues/assets/4428185/cde9afbe-89cf-4fd2-a240-faa3a26bb113)

You can replicate this with the example file from data library => frequencies => memory of life stresses

The downside here would be that the module expects, that your data / variables  already deliver counts. You cannot just throw in raw data of say a dozen dichotomous variables. Is this the thing you search for?
Or does the multinomial test suffice?

**Comment by FBartos** [comment]
I think what the author is looking for is the "Binomial Test" in "Frequencies". It produces the proportion estimates and CI
![image](https://github.com/jasp-stats/jasp-issues/assets/38475991/8b313247-7ca6-46f2-bffd-ffd9f6f83e6a)

The only difference is that it produces the figures for each variable individually (and for each lvl, i.e., the proportion of both zeroes and ones).
![image](https://github.com/jasp-stats/jasp-issues/assets/38475991/d8a87537-c20c-423b-bbc3-57755e734e70)

Please, reopen the issue if this does not solve it.
Frantisek
