### ISSUE TITLE
Feature request: Standardized residuals in lavaan SEM

### ISSUE THREAD

**Issue by BTunca** [jasp-stats/jasp-issues#265]
Hi!

I was wondering whether the lavaan output could include standardized residuals matrix. Here is how the output looks in R:

![image](https://user-images.githubusercontent.com/27208030/49514452-65b4dc00-f894-11e8-8d15-09ec43aceadc.png)

Thanks a lot!

BTunca

**Comment by vankesteren** [comment]
We will think about this in the next implementation of the SEM analysis!

**Comment by juliuspfadt** [comment]
this should be solved by now.
