### ISSUE TITLE
File JASP cannot be download [Bug]: 

### ISSUE THREAD

**Issue by ekal2001** [jasp-stats/jasp-issues#2650]
### JASP Version

0.18.3

### JASP Module

Other

### What OS are you seeing the problem on?

Windows 10

### Bug Description

Whenever try to download JASP in my laptop, it shows file was not available on site

### Expected Behaviour

Supposedly does not have any issue to download

### Steps to Reproduce

Cannot download

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Strange. It works for me. Did you try the Windows Store?
