### ISSUE TITLE
[Bug]: forecast is not working on JASP during  the ARIMA analyze

### ISSUE THREAD

**Issue by Raghavikasi** [jasp-stats/jasp-issues#2651]
### JASP Version

0.18.3

### JASP Module

Time Series

### What analysis are you seeing the problem on?

forecast 

### What OS are you seeing the problem on?

Windows 11

### Bug Description

This analysis terminated unexpectedly.

Error in seq.POSIXt(lastT, by = increment, length.out = (options$forecastLength + : 'from' must be a 'POSIXt' object

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.tsCreateTableForecasts(jaspResults, fit, dataset, datasetRaw, options, ready, position = 7, dependencies = c(.tsArimaDependencies(), .tsDataDependencies(), 'forecast', 'forecastLength'))

.tsForecasts(fit, dataset, datasetRaw, options, jaspResults, ready)

seq.POSIXt(lastT, by = increment, length.out = (options$forecastLength + 1))

stop(''from' must be a 'POSIXt' object')
![Screenshot_20200819-090750_Gallery-1](https://github.com/jasp-stats/jasp-issues/assets/165448529/49011136-c23a-4805-a4f1-e0a8537afbd8)
![jasp](https://github.com/jasp-stats/jasp-issues/assets/165448529/e611ddd6-325a-4fde-9d29-0199242f808f)

### Expected Behaviour

yes

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
@Raghavikasi Why did you close this issue?

**Comment by CASteinman** [comment]
This should not have been closed.  It is still a problem.

**Comment by tomtomme** [comment]
@Raghavikasi 
@CASteinman 

To reproduce and understand this error:
Could you share your .jasp-file by renaming to .zip and drag and dropping it here?
thx

**Comment by CASteinman** [comment]
No, sorry.  I posted that error weeks ago and have moved on.  I no longer am working with that file.  But I posted up as much as the request normally asks for. Did it ask for a copy of the file?  I probably would have loaded it up.

But fyi, its not just that file.  I have had that error other times, I just decided to report it this once. 
    On Monday, September 2, 2024 at 03:47:27 AM CDT, Thomas Langkamp ***@***.***> wrote:  
 
 


@Raghavikasi
@CASteinman

To reproduce and understand this error:
Could you share your .jasp-file by renaming to .zip and drag and dropping it here?
thx

**Comment by tomtomme** [comment]
@CASteinman 
sorry for the delay. 
yeah would be cool if you can provide _any_ file that shows the error. 
and yeah the checklist above asks for such a file.
