### ISSUE TITLE
Internal functioning error 

### ISSUE THREAD

**Issue by wingsofdesire** [jasp-stats/jasp-issues#2652]
### JASP Version

0.18.3

### JASP Module

Mixed Models

### What analysis are you seeing the problem on?

Linear Mixed Models

### What OS are you seeing the problem on?

Windows 11

### Bug Description

![Screenshot 2024-03-31 161446](https://github.com/jasp-stats/jasp-issues/assets/81795388/9caa1041-ed72-4517-a338-24a67b55214e)

After updating JASP, I'm getting this error preventing me from running linear mixed model analysis:

Error evaluating: sink(.outputSink);
jaspBase::runJaspResults(name=name, title=title, dataKey=dataKey, options=options, stateKey=stateKey, functionCall=moduleCall)

### Expected Behaviour

I tried re-installing JASP and restarting the system, but still getting this error. 

### Steps to Reproduce

I get this error when I run a mixed model analysis with my CSV file. What else can I try?

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @wingsofdesire Why did you close this issue?
