### ISSUE TITLE
Contrasts in within-subjects designs can't be computed using a contrast-specific error term (as recommended in the literature)

### ISSUE THREAD

**Issue by mservantufc** [jasp-stats/jasp-issues#2653]
### JASP Version

0.18.3

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

Repeated measures ANOVA

### What OS are you seeing the problem on?

Windows 10

### Bug Description

When computing a custom contrast in a one-way repeated measures ANOVA, unticking the box "Assume equal variances" returns the error message "Unequal variances only available for main effects of within-subjects factors". It seems important to fix this bug as (1) contrast-specific error terms are generally recommended for RM ANOVAs (e.g., Boik, 1981; Maxwell & Delanay, 2018)  and (2) this feature is available for post-hoc tests (one can untick the option "Pool error term for RM factors", and JASP does not return an error message), which is confusing. In addition, is there any reason why the labels "Assume equal variances" vs. "Pool error term for RM factors" differ between the contrast and post-hoc menus? Unticking them should do the same thing (i.e, do not pool the error term). Am I missing something?   
Screen capture of the bug:
<img width="949" alt="bug" src="https://github.com/jasp-stats/jasp-issues/assets/45162680/1a55cae8-81aa-4c82-b715-6c78b257128c">

### Expected Behaviour

Unticking the box "Assume equal variances" should compute a contrast-specific error term.  

### Steps to Reproduce

1. Compute a repeated-measures ANOVA using the datafile provided above.  
2. Compute a custom contrast
3.Untick the option "Assume equal variances"
See attached JASP file
[Bug_report.zip](https://github.com/jasp-stats/jasp-issues/files/14826621/Bug_report.zip)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JohnnyDoorn** [comment]
Hi @mservantufc ,

Last month [I updated JASP's default behavior in RM ANOVA](https://github.com/jasp-stats/jaspAnova/pull/319), to align with your point/references. We were still in the mode of replicating SPSS' default behavior, but I think it's time to leave them behind and do what seems most proper, so in the next release (in May) the RM ANOVA will by default use the multivariate model (i.e., allow specific error-terms). This change also extends the applicability of the issue, so also for interactions, and will now be called the same option under the "model" "contrast" and "posthoc tests" tabs: "Pool error term for follow-up tests", which will be unchecked by default.

Cheers
Johnny
