### ISSUE TITLE
[Feature Request]: Add/expand d-family effect sizes for repeated measures

### ISSUE THREAD

**Issue by TarandeepKang** [jasp-stats/jasp-issues#2654]
### Description

Several measures implemented in the newly updated version of the effectsize package

### Purpose

Better more transparent reporting of analyses

### Use-case

Repeated measures data

### Is your feature request related to a JASP module?

ANOVA, T-Tests

### Describe the solution you would like

Implement new effect sizes

### Additional context

These would, I think, be useful and widely adopted. For more details on the available options see this blog post from the developers:

https://easystats.github.io/effectsize/reference/repeated_measures_d.html

**Comment by tomtomme** [comment]
@TarandeepKang 
Thx for the request.

Seems to be a duplicate of 
https://github.com/jasp-stats/jasp-issues/issues/38
And
https://github.com/jasp-stats/jasp-issues/issues/1915

Correct?

**Comment by TarandeepKang** [comment]
Apologies, yes it is! I thought I looked rather thoroughly to make sure I wasn't duplicating. I will close now.

**Comment by tomtomme** [comment]
no problemo! 
Keep the ideas coming :D
