### ISSUE TITLE
[Bug]: Unidimensional omega of Relibability/Unidimensional Reliability differs from that of Factor/CFA

### ISSUE THREAD

**Issue by KilianSander** [jasp-stats/jasp-issues#2655]
### JASP Version

0.18.3

### JASP Module

Factor, Reliability

### What analysis are you seeing the problem on?

Unidimensional Omega

### What OS are you seeing the problem on?

Windows 10

### Bug Description

When calculating reliability for a unidimensional scale consisting of several items, you can use the `Relibability` module's `Unidimensional Relibability` or use the `Reliability` check box under `Additional Output` in `Confirmatory Factor Analysis` from the `Factor` module.
For Coefficient/Cronbach's &alpha;, both ways show the same result. But for Coefficient/McDonald's &omega;, results differ.
Attached you'll find a toy example with simulated data.
[different_omegas.zip](https://github.com/jasp-stats/jasp-issues/files/14872052/different_omegas.zip)

I know this isn't really a bug, but I don't think it's a feature request either.

### Expected Behaviour

According to Cho (2016, Table 3) congeneric, composite, construct reliability, omega, unidimensional omega and several other names denote the same reliability coefficient. Therefore, I would expect the same result in both modules.

Cho, E. (2016). Making reliability reliable: A systematic approach to reliability coefficients. *Organizational Research Methods*, *19*(4), 651–682. https://doi.org/10.1177/1094428116656239

### Steps to Reproduce

1. A data set with at least 3 indicator variables is needed
2. Reliability > Unidimensional Relibability
Select all indicator variables as Variables
Analysis > Scale Statistics: Tick McDonals &omega;
3. Factor > Confirmatory Factor Analysis
Select all indicator variables and assign them to Factor 1
Additional Output: Tick Reliability
4. Compare McDonald's &omega; from 2 with Coefficient &omega; from 3

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment]
@KilianSander, thanks for creating the issue. Weird, cause using your .jasp file I get the same values for omega:
![Screenshot 2024-04-04 at 16 02 16](https://github.com/jasp-stats/jasp-issues/assets/38500953/69511707-fa10-4b2c-b47a-5c7ca8701b65)

**Comment by KilianSander** [comment]
Hi @juliuspfadt, that's weird, indeed.
What makes this even weirder is that the results I get do not match any of your values:

![different-omegas-screenshot](https://github.com/jasp-stats/jasp-issues/assets/63347705/36894fc9-ee4f-4c54-9c77-b3df2b537527)

**Comment by KilianSander** [comment]
Could you re-run the analyses with the attached data? Just to check if we get different results because data was re-simulated in JASP on different computers.
[different_omegas.csv](https://github.com/jasp-stats/jasp-issues/files/14873262/different_omegas.csv)

**Comment by juliuspfadt** [comment]
You may either close this, or you might think that you would also like to see this definition of omega in the CFA. I think we left the default behavior of semtools as is, because people using factor analysis like these defaults. but anyways, very good catch on your side!

**Comment by KilianSander** [comment]
Thank you for the explanation!

I think the default settings are reasonable. Perhaps, for the sake of transparency, a note should be added to both modules' tables clarifying the calculation, for example in the factor analysis reliability table,
>*Note*. Coefficient &omega; is based on the observed covariance matrix.

**Comment by juliuspfadt** [comment]
Hmm. I think notes under tables should only express for the user-unexpected things happening during the analysis. In this case omega will always be based on one of the covariance matrices, so I will add an explanation to the help file of both modules.

**Comment by KilianSander** [comment]
Good solution. I think it's important that it's documented somewhere in addition to the source code.
