### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by lprimvera** [jasp-stats/jasp-issues#2657]
### Description

I love the PROCESS program but it does not do percentile bootstrapping

### Is your feature request related to a problem?

The feature I requested is the preferred method

### Is your feature request related to a JASP module?

Process

### Describe the solution you would like

add the option

**Comment by maltelueken** [comment]
Just to clarify, do you mean bootstrap percentile intervals? There is already an option for this (`Options` -> `Bootstrap` -> `Type`), however, it is currently broken. Fixing this is on our radar.

**Comment by lprimvera** [comment]
I look forward to this.  In an online article by Dave Kenny, he reports research that shows the bias correct percentile bootstrapping is too liberal (testing at .05 actually results in .07).  I have suggested for those who want to use JASP (a great program), that they use the bias-corrected percentile bootstrapping but test at Alpha = .01.  An inelegant solution, but a good quick fix.

Lou


[https://touro.box.com/shared/static/0eot2o1gmk4yow2hl4bwyvifyabvj130.png]
Louis H. Primavera Ph.D.
Associate Provost
Office of the Provost
Cell: 516.662.3454
***@***.******@***.***>
www.touro.edu<http://touro.edu/>
[facebook]<https://urldefense.proofpoint.com/v2/url?u=http-3A__facebook.com_wearetouro&d=DQMFAg&c=odzYs1kPF7h99M0Vn1uLzg&r=AbAFlD9fKKb1JUz09TFcfsS2csApBvg2TpwKtVPD0h0&m=xOkCtlsE-QYS3rHeVa0W7KsZNBwaNzH3Oh8gd-3_ApA&s=KD3t6uUrTN_GR9rZO_Cep-A2y4DOJBje8uln9IkC9kI&e=>
[https://touro.box.com/shared/static/dfvz431yevi05t92ahms9fum8vxk27sn.png]<https://urldefense.proofpoint.com/v2/url?u=http-3A__twitter.com_wearetouro&d=DQMFAg&c=odzYs1kPF7h99M0Vn1uLzg&r=AbAFlD9fKKb1JUz09TFcfsS2csApBvg2TpwKtVPD0h0&m=xOkCtlsE-QYS3rHeVa0W7KsZNBwaNzH3Oh8gd-3_ApA&s=pIqW9bjoHIXkC5CcX48hfqwehT-MpR27FpYEzOdYLdg&e=>
[https://touro.box.com/shared/static/8t6hz22v2g61frfkkh009o5rpdzn9uw4.png]<https://urldefense.proofpoint.com/v2/url?u=http-3A__instagram.com_wearetouro&d=DQMFAg&c=odzYs1kPF7h99M0Vn1uLzg&r=AbAFlD9fKKb1JUz09TFcfsS2csApBvg2TpwKtVPD0h0&m=xOkCtlsE-QYS3rHeVa0W7KsZNBwaNzH3Oh8gd-3_ApA&s=6sSXOkaSRAlBr14ITcJ_wacRiL1BbRX9zy_XAeznCd8&e=>
[https://touro.box.com/shared/static/ujo3knaz4n715fw34bc3ksh5w3u1odhd.png]<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.linkedin.com_edu_school-3Fid-3D19065&d=DQMFAg&c=odzYs1kPF7h99M0Vn1uLzg&r=AbAFlD9fKKb1JUz09TFcfsS2csApBvg2TpwKtVPD0h0&m=xOkCtlsE-QYS3rHeVa0W7KsZNBwaNzH3Oh8gd-3_ApA&s=PoSuicblXoOHXIhjLrudoOyrHe6-j_7Y6olKcFC8PBk&e=>
