### ISSUE TITLE
[Bug]: Nonparametric Repeated Measures - Optional Grouping Factor

### ISSUE THREAD

**Issue by Menste** [jasp-stats/jasp-issues#2658]
### JASP Version

0.18.1

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

Nonparametric Repeated Measures - Friedman Test

### What OS are you seeing the problem on?

Windows 11

### Bug Description

Quando vado a svolgere il test, non ho la possibilità di inserire nulla nella sezione "Optional Grouping Factor".
Se lo faccio il test si blocca (compare l'icona dell'aggiornamento dei dati ma dura ore senza cambiare nulla).
Alcune volte mi restituisce una schermata di errore.
Non son molto pratico del software e mi ci sono approcciato da poco. Sapreste aiutarmi a capire come mai non è possibile aggiungere l'Optional Grouping Factor?

### Expected Behaviour

I can use my Optional Grouping Factor in a nonparametric MR test.

### Steps to Reproduce

1. go on Anova
2. select classic Repeated Measures Anova
3. select Nonparametrics
4. Add RM Factor (so far it works)
5. Add optional grouping factors
![Jasp_error](https://github.com/jasp-stats/jasp-issues/assets/90631096/6b69b2bc-8062-4663-a1ed-12398e833937)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JohnnyDoorn** [comment]
Hi @Menste ,

Could you also share your jasp file, or try this analysis with the latest JASP version? That way I can try to reproduce the bug, because with my own data this analysis just works. 

Cheers,
Johnny

**Comment by Menste** [comment]
Dear Johnny,
I've tried with the last version.
I attach the error message and the project
thanks in advance
[Project.zip](https://github.com/jasp-stats/jasp-issues/files/14904018/Project.zip)
![Jasp_error2](https://github.com/jasp-stats/jasp-issues/assets/90631096/73bd4413-2ede-4c71-8e0c-1a1d5eaf48a5)

**Comment by JohnnyDoorn** [comment]
Hi @Menste.

Unfortunately this is just a limitation of the test and you'll find a similar error when doing it in R, where you need a unreplicated block design (1 obervation per grouping factor). You can explore other analyses in the mixed modeling module, which is more flexible in this sense. 

Cheers
Johnny
