### ISSUE TITLE
Show 'Alternative Hypothesis' instead of 'Hypothesis'

### ISSUE THREAD

**Issue by JohnnyDoorn** [jasp-stats/jasp-issues#266]
* Enhancement: Change the text in JASP to clarify that it concerns the alternative hypothesis 

It can also be "Alt. Hypothesis"

**Comment by EJWagenmakers** [comment]
Hadn't this been done already?

**Comment by EJWagenmakers** [comment]
@ASarafoglou , @vandenman : is this still in the development version? It is not yet there in the present JASP version.

**Comment by ASarafoglou** [comment]
Bruno said he will fix it when we switched to the QML version!

Op zo 30 dec. 2018 om 23:35 schreef EJWagenmakers <notifications@github.com>

**Comment by juliuspfadt** [comment]
Should be solved
