### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by rainadhaliwal** [jasp-stats/jasp-issues#2663]
### JASP Version

0.18.2

### JASP Module

Other

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

"you cant open the application JASP because this application is not supported on this MAc" my Macbook Air uses ventura 13.4. please help

### Expected Behaviour

it should have downloaded 

### Steps to Reproduce

Im not sure what this means

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Could you try with version 0.18.3?

**Comment by boutinb** [comment]
Just to be sure, you need to download the right version for Apple Silicon: https://static.jasp-stats.org/JASP-0.18.3.0-macOS-arm64_2.dmg
