### ISSUE TITLE
[Bug]: Change reporting of p-values in table when it is rounded to 1: a value of 1.00 cannot be reached

### ISSUE THREAD

**Issue by chantelanuit** [jasp-stats/jasp-issues#2664]
### JASP Version

0.18.3

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

e.g. posthoc test table in the ANOVA module (but generalized issue)

### What OS are you seeing the problem on?

Windows 11

### Bug Description

Like other statistical programs, a _p_-value close to 1 is rounded to 1 in tables. This behavior needs to be changed because of value of 1.00 cannot be reached. In all these situations, I suggest that the appropriate display should be **> .999** instead.

e.g.
![pvalues](https://github.com/jasp-stats/jasp-issues/assets/24530165/ac77a29d-5305-4bfc-ace1-9c0c82150239)

### Expected Behaviour

> .999

### Steps to Reproduce

Every table when _p_ is displayed as equal to 1.

### Log (if any)

NO log

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
You can use the setting to display exact p-values.
![image](https://github.com/jasp-stats/jasp-issues/assets/4428185/43f4f697-0da3-48ba-890f-4b24ca736688)

Does this suffice?

**Comment by chantelanuit** [comment]
Thanks @tomtomme, 

I am aware of this option. However, _p_ < .001 is displayed (instead of rounded value of 0) even when the exact _p_-values option is not selected. Since a _p_-value cannot reach 1, I suggest that **a value of 1 should never be displayed**, even when the exact _p_-value option is not selected. For learners in statistics, displaying  a value of 1 is sending the wrong message that there is an absolute certainty regarding a result.

**Comment by EJWagenmakers** [comment]
A p-value of 1 is attained whenever the sample test statistic is perfectly consistent with H0 (i.e., all data are more extreme than the one observed). In a t-test, p=1 when t=0; in a binomial test against theta=0.5, p=1 when s=n/2.
EJ

**Comment by chantelanuit** [comment]
Thank you EJ for the specific example. However, when a Bonferroni correction is requested (my example above),  _p_ = 1 is a form of artifact of the alpha familywise correction technique. I have a hard time understanding why reporting _p_ = 1 for that situation in a manuscript would be correct and I would rather report _p_ > .999. For my example, _t_ is not equal to zero, e.g. _t_ = 1.2245 and _p_ bonf = 1 (see the first post, second line of the table).

**Comment by EJWagenmakers** [comment]
Hmm yes, this does provide an opportunity to rant about frequentist statistics (next you will point out that variances should not be estimated to be negative :-)). I don't have a strong opinion on this, and I suggest we go with what is common practice. What *is* common practice?

**Comment by chantelanuit** [comment]
Good question, difficult answer. There seems to be articles with either reports of _p_ = 1 or _p_ > .999. In the field of psychology (and nearby fields), may I suggest that "common practice" (be it good or bad) was set for a very long time by the dominant statistical software: **SPSS**. So I suggest that the way the software report results has a lot to do with establishing the common or dominant practice and that should not be underestimated. However, my point is the following one: if we do not report _p_=0 and rather use _p_ < .001 (or smaller), why would _p_=1 be acceptable then ?

**Comment by EJWagenmakers** [comment]
> if we do not report p=0 and rather use p < .001 (or smaller), why would p=1 be acceptable then ?

Because p=0 cannot occur (unless the data are *impossible* under H0), but p=1 occurs every time the sample is perfectly consistent with H0. So p=0 cannot happen, but p=1 can happen, and in fact does happen.

**Comment by chantelanuit** [comment]
But then, would you report _p_ = 1 in a manuscript when adjusting for multiple comparisons? In these situations, the data is almost never perfectly consistent with H0.

For reference, there is an interesting discussion here on tiny _p_-values: https://stats.stackexchange.com/questions/78839/how-should-tiny-p-values-be-reported-and-why-does-r-put-a-minimum-on-2-22e-1

**Comment by EJWagenmakers** [comment]
"But then, would you report p = 1 in a manuscript when adjusting for multiple comparisons? In these situations, the data are almost never perfectly consistent with H0."

I think I would. It would mean that there is no reason whatsoever to doubt H0, as the little doubt there is has been completely nullified by the multiplicity.
EJ

**Comment by chantelanuit** [comment]
Thanks for sharing your perspective

**Comment by tomtomme** [comment]
@chantelanuit 
Interesting discussion to follow. The original issue now seems resolved, thus I am closing. Please comment if I am wrong!
