### ISSUE TITLE
[Bug]: ANOVA Descriptives Plots Not Working

### ISSUE THREAD

**Issue by quentingronau** [jasp-stats/jasp-issues#2665]
### JASP Version

0.18.3

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

ANOVA -> Descriptives Plots

### What OS are you seeing the problem on?

Other

### Bug Description

Today I taught Bayes to honours students, and one of them experienced an odd issue when trying to create an ANOVA Descriptives Plot. Specifically, for the "Singers" data set, they were trying to create a plot that has "Pitch" on the x-axis, and separate lines for "Gender" (the dependent variable being "Height"). They could drop Pitch into the correct box, but when they tried to drag and drop "Gender" into the separate lines box it just did not work (i.e., the variable could not be dropped there). They were using JASP 0.18.3 on a Mac with Sonoma 14.1.2. Is this perhaps a known issue? I am unable to provide a screenshot or give more information as this only happened on the student's laptop.

### Expected Behaviour

Work as expected.

### Steps to Reproduce

-

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by JohnnyDoorn** [comment]
Quentin! Good to hear you're still rocking the singers data set in BANOVA =) I can indeed replicate the issue on my own machine (M2 Mac with JASP 0.18.3) and I think there's some funky stuff going on with this "nominal text".
Thanks to some amazing rewrites of the JASP data management by @JorisGoosen , this is no longer an issue in 0.19 (will probably be released in May) - in the meantime the student could use [the latest nightly build](https://static.jasp-stats.org/Nightlies/). See here the side by side comparison of 0.18.3 vs 0.19:
<img width="1440" alt="image" src="https://github.com/jasp-stats/jasp-issues/assets/15704203/8cb40922-5087-4130-bcb6-b5e4fab2533b">

Sending hugs from across the pond!

**Comment by quentingronau** [comment]
Hi Johnny,

That's great, thanks! Otherwise students really seemed to like JASP which is always nice to see.

Greetings from Down Under!
