### ISSUE TITLE
[Bug]: PROCESS model terminated unexpectedly 

### ISSUE THREAD

**Issue by dareump** [jasp-stats/jasp-issues#2666]
### JASP Version

0.18.3

### JASP Module

Process

### What analysis are you seeing the problem on?

Mediation Analysis (Hayes Model 4)

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

This analysis terminated unexpectedly.

Error in sort.int(sapply(medPaths, length), index.return = TRUE): 'x' must be atomic

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.procModelSyntax(jaspResults, options)

.procModelSyntaxSingleModel(modelsContainer[[modelName]], modelOptions)

.procMedEffectsSyntax(graph, container[['modProbes']]$object, container[['contrasts']]$object)

sort.int(sapply(medPaths, length), index.return = TRUE)

stop(''x' must be atomic')

### Expected Behaviour

A mediation analysis 

### Steps to Reproduce

1.n/a
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@dareump 
I cannot replicate this error with jasp 0.18.3 and data from the data library. Could you share your .jasp-file by renaming it to .zip and drag and dropping it here?

**Comment by tomtomme** [comment]
or send your file(s) directly to us, [issues@jasp-stats.org](mailto:issues@jasp-stats.org)

**Comment by maltelueken** [comment]
I think this error occurred in some cases when a variable in the analysis had the `Ordinal` type. This is fixed in https://github.com/jasp-stats/jaspProcess/pull/91.
