### ISSUE TITLE
JASP-0.9.1.0 for windows crashes when trying to export 300 dpi tiff image

### ISSUE THREAD

**Issue by BeStud** [jasp-stats/jasp-issues#267]
* JASP version: 0.9.1.0.
* OS name and version: Windows 7, 64bit
* Analysis:
* Bug description: Cannot save any figures as high resolution tiff; when I try, JASP crashes
* Add JASP files as a zip:
* Screenshot: 
* Expected behaviour:
* Steps to reproduce:

**Comment by AlexanderLyNL** [comment]
This should be fixed in 0.9.2. Please reopen if this reoccurs.
