### ISSUE TITLE
[Bug]: Download file not found

### ISSUE THREAD

**Issue by myssiak** [jasp-stats/jasp-issues#2673]
### JASP Version

0.18.1

### JASP Module

Unrelated

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

Hi, we are trying to download version 0.18.1 for Intel MacOS, but it seems the file is not found (link https://static.jasp-stats.org/JASP-0.18.1.0-macOS-x86_64_new2.dmg). Could you please resolve? Thanks in advance

### Expected Behaviour

Download

### Steps to Reproduce

1. Go to https://jasp-stats.org/previous-versions
2. Click [JASP 0.18.1 (Intel MacOS Big Sur and above)](https://static.jasp-stats.org/JASP-0.18.1.0-macOS-x86_64_new2.dmg)

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Strange. When I click on the link the download works immideatly? Have you been on an unstable Wifi maybe?

**Comment by boutinb** [comment]
Me too, if I click on the link, then I get the file downloaded. So I think this was just a glitch from the network, or from our server.
