### ISSUE TITLE
[Bug]: Error in tableRListCombined[['test3']]: subscript out of bounds

### ISSUE THREAD

**Issue by VesnaBoskov** [jasp-stats/jasp-issues#2674]
### JASP Version

0.18.1

### JASP Module

Quality Control

### What analysis are you seeing the problem on?

Process Capability Study

### What OS are you seeing the problem on?

Windows 11

### Bug Description

Error in tableRListCombined[['test3']]: subscript out of bounds

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.qcImRChart(options, dataset, ready, jaspResults, measurements, subgroups = splitFactor, wideFormat = wideFormat)

### Expected Behaviour

[Hight_18 inch.csv](https://github.com/jasp-stats/jasp-issues/files/15039243/Hight_18.inch.csv)
[Hight_18 inch.pdf](https://github.com/jasp-stats/jasp-issues/files/15039273/Hight_18.inch.pdf)
![JASP bug](https://github.com/jasp-stats/jasp-issues/assets/157103906/46f7373e-fea3-4783-9828-44b38dfbe078)

### Steps to Reproduce

1. Open csv file Hight
2. Start Quality Control 
3. Process Capability Study
4. Specify subgroup size manually from 5 to 1
5. Measurements - Hight => I receive Error message
...

### Log (if any)

[JASP 2024-04-19 12_59_22 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/15039346/JASP.2024-04-19.12_59_22.Desktop.log)
[JASP 2024-04-19 12_59_22 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/15039347/JASP.2024-04-19.12_59_22.Engine.0.log)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@VesnaBoskov 
Could you re-test with jasp 0.18.3?

**Comment by JTPetter** [comment]
I don't think there were any updates to this analysis with 0.18.3. But I strongly suspect this is already fixed in the upcoming 0.19, will confirm later.

**Comment by JTPetter** [comment]
@VesnaBoskov Thanks for the report! I could confirm that this is fixed already in the upcoming release.

**Comment by VesnaBoskov** [comment]
Thanks, Petter.
