### ISSUE TITLE
[Bug]: Dunn's post hoc non functional

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#2678]
### JASP Version

Others

### Commit ID

97f99295e463d69df042fdb741c910dfcc0d1d3a

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

ANVOVA classical

### What OS are you seeing the problem on?

Flatpak

### Bug Description

![image](https://github.com/jasp-stats/jasp-issues/assets/4428185/c9948943-2752-4683-9ec5-2c8432d64f03)

Checking Dunn's post hoc does not produce a result

### Expected Behaviour

Dunns post hoc should show up

### Steps to Reproduce

1. Check Dunn's post hoc

### Log (if any)

-------- Application Info --------
JASP Version: JASP 0.19
Build Branch: HEAD
Build Date: Apr 22 2024 12:56:16 (Netherlands)
Last Commit: 97f99295e463d69df042fdb741c910dfcc0d1d3a

-------- Basic Info --------
Operating System: KDE Flatpak runtime
Product Version: 6.5
Kernel Type: linux
Kernel Version: 6.6.26-1-MANJARO
Architecture: x86_64
Install Path: /app/bin
System Local: de_DE

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JohnnyDoorn** [comment]
Thanks for testing this stuff @tomtomme, very useful to have some extra eyes!
