### ISSUE TITLE
[Bug]: Jasp automatically closes when trying to open new CSV dataset

### ISSUE THREAD

**Issue by Elizakitch** [jasp-stats/jasp-issues#2680]
### JASP Version

0.18.3

### JASP Module

Other

### What analysis are you seeing the problem on?

Opening a new dataset

### What OS are you seeing the problem on?

Other

### Bug Description

I am unable to upload a new dataset into Jasp without the application closing. I open the Jasp Application on my desktop, then go to open a data file > Open > Computer, then select the data file (CSV) I want, and the application automatically closes. I have tried to upload a smaller file size, restart my computer and the application, but none of these actions have worked. I am using a Mac (OS Sonoma 14.4.1 (23E224)). I'm not sure if there's something I am doing wrong? 

### Expected Behaviour

I should be able to open a data file (CSV) without the application automatically closing. 

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by Elizakitch** [comment]
I'm not really able to upload a screenshot of the problem, there's no error message or anything that appears, the application simply closes without warning when I try to upload a dataset, but I'll send the data file that I am trying to open directly to you. Thanks!

**Comment by tomtomme** [comment]
Can you share the data file you tried?
Can you open data frim the data library?

**Comment by Elizakitch** [comment]
Hi Thomas,

I sent it to this address: ***@***.***, but I have attached it to this email also.

I haven't tried to upload from the data library, it's the first time I'm trying to open this dataset with Jasp so it won't be in the library (at least I can't see it?).

Thanks,
Eliza


Eliza Kitchener (she/her)

PhD student

School of Health

University of the Sunshine Coast | Moreton Bay campus



[cid:6e7d40d2-a64e-4f53-ac70-50cacf154a84]



I acknowledge the Gubbi Gubbi/Kabi Kabi and Turrbal people as the Traditional Owners

of the land upon which I learn and teach, and pay my respects to Elders past and present.

________________________________

**Comment by tomtomme** [comment]
That is not what I asked. 
Indeed your data cannot be in the data library.
So 

1. Can you share the data file you tried? Rename it to .zip and drag and drop it here, if so.
2. Can you open data frim the data library? Go to the data library and click on a file there.

Those are two independent questions?

**Comment by boutinb** [comment]
You can also try to open a data file in the data library (Open, Data Library...).

**Comment by Elizakitch** [comment]
Hi,

Thank you for your help, I think the program was having trouble due to the layout of my CSV file. I transposed the data and it seems to be working fine now.

Thanks,
Eliza


Eliza Kitchener (she/her)

PhD student

School of Health

University of the Sunshine Coast | Moreton Bay campus



[cid:66605b0d-b9c4-4aae-af3f-aa311918885b]



I acknowledge the Gubbi Gubbi/Kabi Kabi and Turrbal people as the Traditional Owners

of the land upon which I learn and teach, and pay my respects to Elders past and present.

________________________________
