### ISSUE TITLE
[Bug]: Changing column type failed

### ISSUE THREAD

**Issue by nalyderry** [jasp-stats/jasp-issues#2681]
### JASP Version

0.18.2

### JASP Module

Unrelated

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

1. I have converted an Excel dataset into .csv format. 
2. Once I opened the converted file in JASP, the data that has commas in it would automatically be set into the nominal category 
3. I cannot change the category into another category, when I try to change it it just says **Changing column type failed**: Failed to convert column to continuous: values contain text. 
4. I tried to change remove the commas in the Excel dataset and converted it again into .csv format and opened it again in JASP and I was able to change the column type. 
5. However, the values/results were significantly different than the ones shown by my professor and classmates. 

### Expected Behaviour

I should be able to change the column type despite the commas, all of my classmates were able to do it even those using MacOS. 

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@nalyderry 
Can you re-test this with the current version 0.18.3?

**Comment by tomtomme** [comment]
Please reopen if error persists with current jasp
