### ISSUE TITLE
[Bug]: JASP crashes when trying to open

### ISSUE THREAD

**Issue by isabelw30** [jasp-stats/jasp-issues#2683]
### JASP Version

0.16

### JASP Module

Unrelated

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

When I try to open JASP from both the lauchpad as from finder, it crashes. It shows the welcome page for about 2 to 3 seconds and then it just goes away. There is no notification or anything. It just won't open. I deleted and redownloaded JASP (also different versions) 4 times, but nothing changes. Can anyone help me please?

### Expected Behaviour

JASP should have opened.

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
- [ ] Can you state the version of MacOS you are running? Click on the apple on the top left and then on "about my mac" to find out the version number. Apple support versions 12, 13, 14 at the moment. 
- [ ] Also are you sure, you have an "Intel" processor / CPU or is it maybe a Apple Silicon M1, M2 or M3? Via the above way, you can also find this out.
- [ ] Also, did you try the most recent jasp version 0.18.3?

**Comment by isabelw30** [comment]
- macOS Mojave 10.14.6
- Intel Core i5
And yes I tried the most recent version of JASP, but unfortunately I can't download it because I don't have the latest iOS version. I can't get the latest iOS version.

**Comment by tomtomme** [comment]
There you have it. MacOS 10 is not supported anymore. You need to update or switch the machine if no update is available for MacOS on your machine.
Sorry.

**Comment by isabelw30** [comment]
But is that recent? Because I was using it about two weeks ago (with JASP version 0.16) and it worked perfectly fine. So you would say something else is the problem? Previous versions should work on older updates.

**Comment by tomtomme** [comment]
Yes, previous jasp versions should work on older macOS systems. But this is not guaranteed. There might have been an update to some software on your system that broke jasp. 
Maybe someone from the core team has time to investigate this via log files? 

But if your mac does not get any OS updates it might even be that old, that there are now hardware level errors. So, hard to diagnose either way. 
So how old is your mac?

**Comment by boutinb** [comment]
We support only Mas OS versions that are supported by Apple self at the moment we release a new version. As Apple ends support for Mojave since November 30, 2021, we don't support Mojave for quite long already (cf https://jasp-stats.org/previous-versions/). It might happen that a not supported version still run, but there is no guarantee.
Also for yourself, as Apple does not release security update for this version, this is in fact quite dangerous to stay on Mojave.
