### ISSUE TITLE
[Bug]: Bayesian Generalized Linear Mixed Models error fixed effects variable less than two levels

### ISSUE THREAD

**Issue by NilsSim** [jasp-stats/jasp-issues#2684]
### JASP Version

0.18.3

### JASP Module

Mixed Models

### What analysis are you seeing the problem on?

Bayesian Generalized Linear Mixed Models

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

I received the error message "Number of factor levels is < 2 in "condition". But the variable had exactly two levels, namely "0" and "1". 
![screen](https://github.com/jasp-stats/jasp-issues/assets/56731401/7df898bc-ddad-4407-bd46-44956759ef86)

### Expected Behaviour

The analysis should work with a categorical fixed effects variable that has 2 levels, indicated with 0 and 1

### Steps to Reproduce

1. Enter continous variable for Dependent variable
2. Enter categorical variable with values "0" and "1"
3. Enter categorical variable with around 10 level under random effects grouping factors
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@NilsSim 
Can you share your zipped data file by drag and dropping here? (eMailing it does not work)

**Comment by NilsSim** [comment]
Hi Tom,

Thank you for the super rapid reply and help! You find the zip enclosed. Greetings
Nils

[bug_jasp.csv.zip](https://github.com/jasp-stats/jasp-issues/files/15108734/bug_jasp.csv.zip)

**Comment by tomtomme** [comment]
The variables contained in your upload do not match your screenshot. Also it would be good if you can upload a .jasp file including all settings instead of the CSV which includes only raw data.
I already tried to replicat the error with data from jasps data library without success. I do not get the error with other data, so I suspect your data is the "issue". Maybe missing values or so...

**Comment by NilsSim** [comment]
The analysis/data you shared works for me too.
Would you have an idea why I received the error message for my data?

Am Do., 25. Apr. 2024 um 13:32 Uhr schrieb Thomas Langkamp <
***@***.***>:

**Comment by tomtomme** [comment]
Only,if you can share the data from the screenshot

**Comment by tomtomme** [comment]
Please reopen, if you can share your data. If it is private then send it directly to us, [issues@jasp-stats.org](mailto:issues@jasp-stats.org)
