### ISSUE TITLE
[Bug]: Analysis Terminated Unexpectedly 

### ISSUE THREAD

**Issue by lan-nes** [jasp-stats/jasp-issues#2685]
### JASP Version

0.18.3

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

Marginal Means

### What OS are you seeing the problem on?

Windows 11

### Bug Description

![Screenshot 2024-04-28 154113](https://github.com/jasp-stats/jasp-issues/assets/168325568/5c788c81-1687-4f35-a8a6-600a90a56929)

Dataset = 2x2 Multi-Factor Between-Groups ANOVA

Ran Classic ANOVA Analysis, ran Descriptives Statistics Analysis for 1xDV, ran assumption checks (homogeneity and Q-Q), calculated descriptive statistics for interactions, and calculated effect sizes (both eta and partial). Then tried to run Marginal Means for both IV's and their interaction and received the error message. Have received one before when trying to do the same thing.

### Expected Behaviour

I believe the Marginal Means should have shown up in a table in the results section with the rest of the analysed data.

### Steps to Reproduce

1. 2 nominal IV's and 1 scale DV
2. run classic ANOVA
3. move DV variable into other box and IV's into fixed factors box
4. calculate effect sizes (both eta and partial)
5. try to calculate Marginal Means by moving both IV's and their interaction into the other box

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@lan-nes 
I cannot replicate this with 0.18.3 and data from the data library. Can you share your .jasp file by renaming it to .zip and drag and dropping it here?

**Comment by tomtomme** [comment]
or send your file(s) directly to us, [issues@jasp-stats.org](mailto:issues@jasp-stats.org)
