### ISSUE TITLE
[Bug]: JASP Bug

### ISSUE THREAD

**Issue by cralsdorf** [jasp-stats/jasp-issues#2686]
### JASP Version

0.18.3

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 11

### Bug Description

The system told me that there was a crash due to a bug.

### Expected Behaviour

Not really sure what the issue was. It just told me there was a crash. 
![image](https://github.com/jasp-stats/jasp-issues/assets/168372656/630b5b1e-da53-47ee-ab93-f982ee272503)

### Steps to Reproduce

1. Open JASP
2. Open
3. Recent Files
4. Crash reported
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Thx for the report. However if the crash is not reproducible and if you cannot tell us what lead to the crash, then there is not much we can do, I am afraid.

**Comment by boutinb** [comment]
Does this crash happen always, or just once?
