### ISSUE TITLE
[Bug]: SEM module mislabels models

### ISSUE THREAD

**Issue by SachaEpskamp** [jasp-stats/jasp-issues#2690]
### JASP Version

0.18.3

### JASP Module

SEM

### What analysis are you seeing the problem on?

SEM model comparison

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

When comparing multiple SEM models, the models are shown in the reverse order in the table.

### Expected Behaviour

The models should be in the correct order.

### Steps to Reproduce

1. Load Political Democracy example data
2. Enter models:

Model 1: 
f =~ y1 + y2 + y3 + y4

Model 1: 
f =~ y1 + y2 + y3 + y4
y1 ~~ y2
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment]
@SachaEpskamp, nice catch! thanks.
