### ISSUE TITLE
[Feature Request]: Reminder to update flatpak runtimes before 0.19 release

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#2691]
### Description

the flatpak runtimes org.kde.Sdk & org.kde.Platform branch 6.5 are end-of-life - and latest 0.19beta still depends on them. Maybe the update process could be automated in the future?

### Purpose

security & potential bug fixes

**Comment by shun2wang** [comment]
Well, I'm afraid we won't be in a hurry to upgrade the Qt version because 6.5 LTS is a very stable Qt version. Flatpak/Flathub usually "sweetly" warn about "outdated" runtimes, but I don't think that makes any sense.

**Comment by tomtomme** [comment]
6.5 LTS is a good target for commercial / paying customers only. For open source projects like KDE or JASP there are no further updates available since 6.5.4 in january., see:
https://www.qt.io/blog/commercial-lts-qt-6.5.4-released

So using 6.5 is already kind of unsecure. We need to move constantly I am afraid, like KDE does. So the flatpak warning is very real.
You may have missed the discussion about a year ago about the Qt company closing of LTS releases to paying customers only.

**Comment by tomtomme** [comment]
Some more details on those restrictions here:
https://wiki.qt.io/Qt_version_history#cite_note-KDE-5

So sadly no LTS for us until Qt changes their mind... but there is no indication they will atm.

**Comment by RensDofferhoff** [comment]
I will bring this up in the upcoming meeting

**Comment by shun2wang** [comment]
Yes, I know that Qt's policy, but in software development it is safe to keep library dependencies or programming language two version lag, which is beneficial to maintaining software stability. The suggested risk is not the real risk I meam.
