### ISSUE TITLE
[Bug]: Datafile does not open

### ISSUE THREAD

**Issue by Grandessa2000** [jasp-stats/jasp-issues#2693]
### JASP Version

0.18.3

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 11

### Bug Description

With all relevant (containing more than a small test evaluation) Jasp files that I have saved, I have the problem that Jasp hangs as soon as I try to open the file. The display bar: Loding JASP file loads completely, but then nothing happens until I get the message, no feedback from the programme, want to close the programme (from Windows)

### Expected Behaviour

Programme opens my data files normally

### Steps to Reproduce

1. Click on the file in my saved folder to open it with JASP.
2.Programme hangs up
3.
...

### Log (if any)

<img width="959" alt="image" src="https://github.com/jasp-stats/jasp-issues/assets/168676441/1549d1d2-b56d-415c-ac32-a264d6d0e5d3">

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Thx for the report! Can you share the file? See above

**Comment by boutinb** [comment]
Hi @Grandessa2000, how big are your JASP files? We have made a lot of changes in the loading of JASP file for the next release (released probably end of May), but you can already try a development version: https://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-development-c6423f0742e7b840aa9e07f66c87a441e199d34b.msi
Be careful this version is not fully tested yet, it is just to check whether this version would solve your problem.

**Comment by Grandessa2000** [comment]
They are between 15.000 und 40.000 KB. Unfortunately I cannot share the files due to data protection.

**Comment by tomtomme** [comment]
@Grandessa2000 
Sounds like you reach the limit of 1000 columns perhabs? We now use SQLite to store the data in the background, which imposes this limit unfortunately.

**Comment by RensDofferhoff** [comment]
@Grandessa2000 What are your pc specs?
The file you send opens fine on linux.
I will try on a windows machine now

**Comment by RensDofferhoff** [comment]
The provided test file works fine on all my machines. 
@JorisGoosen Can you reproduce this ?

**Comment by tomtomme** [comment]
Can confirm. Opens also on my machine in 0.18.3
 (I overlooked the file before)

**Comment by RensDofferhoff** [comment]
hmmmm,  @Grandessa2000 aside form PC specs, do you have any anti-virus software of any kind?

**Comment by Grandessa2000** [comment]
I have now got the test to run, but my actual data is still not there, not even on another computer.

I use the Windows programme for virus protection.
My computer specifications are  
Processor AMD Ryzen 7 5825U with Radeon Graphics 2.00 GHz
Installed RAM 16.0 GB (14.8 GB usable)
System type 64-bit operating system, x64-based processor

Is it possible to send a file to check whether it is due to the file without publishing it on the Internet, because this is not possible under data protection law, as the data has not yet been published?

**Comment by tomtomme** [comment]
you can send your file(s) directly to us, issues@jasp-stats.org
