### ISSUE TITLE
[Bug]: McAffee Anti Virus blocks jasp download

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#2694]
### JASP Version

0.18.3 on Win11

### Bug Description

After downloading JASP an error message appears, that the downloaded file needs to be authorized. The .msi file gets converted into .txt
This seems to be a containment feature of McAffee antivirus for blocking potentially dangerous executables.

### Expected Behaviour

Circumventing McAffees containment of the .msi-download - if somehow possible. I know we can always advice to use the MS store to download JASP instead, but atm we are still also advertising the download from jasp-stats.org

### Steps to Reproduce

1. Download from jasp-stats.org with McAffee activated

**Comment by shun2wang** [comment]
Could you report a mistake check to McAffee? in the Mcaffee software report or contact where maybe have this entry.

**Comment by tomtomme** [comment]
Good idea. I will ask the student that had this problem to do so and report back here afterwards.

**Comment by RensDofferhoff** [comment]
Yeah I am not sure how to handle this issues. 
I want to get rid of the MSI but there is still an issue with codesigning.

**Comment by tomtomme** [comment]
I checked the report formularities with McAffee: https://www.mcafee.com/support/?articleId=TS103032&page=shell&shell=article-view#:~:text=If%20you%20think%20your%20file%20has%20been%20incorrectly,the%20information.%20Type%20the%20Captcha%20code.%20Click%20Submit.

For files larger than >50 you have to contact customer support. I chatted with them to no avail. They just said that I have to deactivate McAfee and did not really seem to understand what I wanted... ugh.

**Comment by tomtomme** [comment]
After more fiddling with the chat(bot?) it turned out that only the .exe needs to be send and that its <50MB. So I did it:
![Bildschirmfoto_20240708_105803](https://github.com/jasp-stats/jasp-issues/assets/4428185/cd155aa5-8928-48bb-9b22-9771e6c124ef)
