### ISSUE TITLE
[Feature Request]: Presenting the results in post hoc tests for n-factorial ANOVA fixing one of the factors and showing the statistical difference among the levels of the other factor

### ISSUE THREAD

**Issue by wpsilvestre** [jasp-stats/jasp-issues#2696]
### Description

Presenting the results in post hoc tests for n-factorial ANOVA fixing one of the factors and showing the statistical difference among the levels of the other factor

### Purpose

Easing the analysis of n-factorial design with post hoc tests in ANOVA

### Use-case

This feature would benefit any user that works with Jasp

### Is your feature request related to a problem?

No

### Is your feature request related to a JASP module?

ANOVA

### Describe the solution you would like

Although the ANOVA has the feature of marginal means with the 95 % confidence interval, this is not very intuitive for novice or occasional users. In addition, in the present form, it is difficult to understand the contrasts since all comparisons are shown together

### Describe alternatives that you have considered

The marginal means plot may help, but for factors with more levels the interpretation of the graph may become difficult.

### Additional context

Some softwares, when assessing factorial design using ANOVA, and conducting post hoc tests, decompose the interaction in tables, by fixing one of the factors, and presenting the differences among the levels of the other. This is important to build an interaction table, showing the means ad using letters in column and row to indicate statistical differences among levels and factors.

@JohnnyDoorn , I have added a statistical report of such a software that bring this unfolded interaction information for your assessment: [Factorial design with 2 Factors.pdf](https://github.com/jasp-stats/jasp-issues/files/15188321/Factorial.design.with.2.Factors.pdf)

I don't know if this is feasible, but I believe it would be great for Jasp users, especially when interaction tables are needed to explain the data along with graphs and other features. Thank you for your attention.

**Comment by tomtomme** [comment]
Is this what you mean?
https://github.com/jasp-stats/jasp-issues/issues/637
https://github.com/jasp-stats/jaspAnova/pull/343

Then this will be available around May / June in 0.19

**Comment by wpsilvestre** [comment]
@tomtomme , I'm not sure if this is what I mean. Anyway, when the latest Jasp version (0.19) is released, I'll test it and, if it is not what I mean, I can reopen this topic.

**Comment by JohnnyDoorn** [comment]
Closing for now because I do think it's implemented now - please reopen if not!
