### ISSUE TITLE
ARIMA

### ISSUE THREAD

**Issue by ekraiz** [jasp-stats/jasp-issues#2699]
### JASP Version

0.18.3

### JASP Module

Time Series

### What analysis are you seeing the problem on?

ARIMA

### What OS are you seeing the problem on?

Windows 11

### Bug Description

I experimented the ARIMA model on a linear series, 1,2,3....  and got a massage ARIMA cannot be fit.

### Expected Behaviour

It should have been a perfect fit

### Steps to Reproduce

1.  added data
2.  set to manual model
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@ekraiz 
Thx for the report. Can you share your data file? Rename the .jasp file to .zip, then you can drag and drop it here.

**Comment by tomtomme** [comment]
or send your file(s) directly to us, [issues@jasp-stats.org](mailto:issues@jasp-stats.org)
