### ISSUE TITLE
Factor scores (principal components and exploratory factor analysis)

### ISSUE THREAD

**Issue by diogenesbido** [jasp-stats/jasp-issues#27]
Please, add this option:
- Factor / Principal.. = add "save scores" (Bartllet or regression *)
- Factor / Exploratory... = add "save scores" (Bartllet or regression *) 
- = or show the factor weights.

**Comment by tkasci** [comment]
Would be really nice to see this implemented.

**Comment by juliuspfadt** [comment]
lets track this issue here: https://github.com/jasp-stats/jasp-issues/issues/101

**Comment by tomtomme** [comment]
Duplicate. Can be closed.
