### ISSUE TITLE
Chart legend not shown in repeated measures ANOVA

### ISSUE THREAD

**Issue by vicenteinefo** [jasp-stats/jasp-issues#270]
* JASP version: 0.9.2
* OS name and version: MacOS X El Captian 10.11.6
* Analysis: Repeated measures ANOVA 
* Bug description: the chart legend is not shown
* Screenshot: 
![captura de pantalla 2018-12-11 a las 20 23 13](https://user-images.githubusercontent.com/29978768/49824533-9d36f300-fd82-11e8-86c2-4ab3bbe07565.png)
* Expected behavior: chart legend shown at the right of the chart

**Comment by hyuksulee** [comment]
I want the problem solved as well!!!

**Comment by Jinboasltw** [comment]
Me too.

**Comment by boutinb** [comment]
Done in 0.9.3

**Comment by kierstin2697** [comment]
When will 9.3 be available, because it would be nice to have this fixed now
