### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by CopperOx12** [jasp-stats/jasp-issues#2700]
### JASP Version

0.18.3

### JASP Module

ANOVA

### What OS are you seeing the problem on?

Windows 11

### Bug Description

[InsuranceSurvey_ANOVA.xlsx](https://github.com/jasp-stats/jasp-issues/files/15214620/InsuranceSurvey_ANOVA.xlsx)

### Expected Behaviour

Unexpected crash, happened multiple times with this file

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@CopperOx12 
Thx for the report. When I click the file I get an completely empty xlsx file.
Please try again to upload your file here and please include some more details on when JASP crashed exactly and if there was an error message. 

Also note: JASP cannot open xlsx files. You would need to convert it to CSV or ODS before.
