### ISSUE TITLE
[Bug]: Cannot generate Random data

### ISSUE THREAD

**Issue by Mambosatin** [jasp-stats/jasp-issues#2701]
### JASP Version

0.18.3

### JASP Module

Distributions

### What analysis are you seeing the problem on?

All distribution models

### What OS are you seeing the problem on?

Windows 10

### Bug Description

Impossible to generate more than one random data, as min and max number of samples equal 1
![image](https://github.com/jasp-stats/jasp-issues/assets/104917143/73e56016-808a-4144-8777-f935859509bd)

### Expected Behaviour

Ability to generate as many random samples as possible

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@Mambosatin 
This depends on the amount of rows you have in your data. It seems your current open data set has only one row initialized. Then you can only generate 1 row of new data. This is a limitation of our current data editing engine, sorry. 
But I marked this as a feature request. Please rename the title accordingly. Thx!
It should be possible to initialize new rows automatically. 
@JorisGoosen: Would this be feasible?

**Comment by JorisGoosen** [comment]
Actually, if @Mambosatin just enters a number on row `N` (s)he can then generate `N` random samples.

We did do on purpose that analyses/computed-columns cannot just generate more rows because that could get messy real quick. (At least for computed columns)

I can see how it could be nice here but there is a very easy workaround so its not very likely were implementing this soon.

**Comment by Mambosatin** [comment]
Hi, thx for your answers.
@JorisGoosen, I understand your "workaround", but new rows are generated by 21, means that if I want to generate 2000 random data, I have to enter at first 96 dummy numbers. Not so user friendly.

**Comment by JorisGoosen** [comment]
Aah yes @Mambosatin you are right, I should bring the resize dataset button back probably.

**Comment by JorisGoosen** [comment]
@boutinb why did you remove that "Resize Data" button again?
In https://github.com/jasp-stats/jasp-desktop/commit/5efc3599ff3e3d2ea4ec7a226f397707f731c69d 

I think you get the honor of putting it back monsieur!
