### ISSUE TITLE
[Bug]: Bar Plots with ordinal data not sorted

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#2707]
### JASP Version

Others

### Commit ID
4825b388f588478d5e4fae448240ab5ded435d86

### JASP Module

Descriptives

### What analysis are you seeing the problem on?

bar plot

### What OS are you seeing the problem on?

Flatpak

### Bug Description

![image](https://github.com/jasp-stats/jasp-issues/assets/4428185/f4a68ab5-8d41-4488-8c3a-6100e740d3ca)

### Expected Behaviour

For ordinal data the values of the bar plots x-axis should automatically be sorted

### Steps to Reproduce

1. put in some data
2. choose ordinal
3. plot bar graph

**Comment by JorisGoosen** [comment]
Hmmm, I was wondering whether or not I should do the automatic sorting or not, but I guess I should: https://github.com/jasp-stats/INTERNAL-jasp/issues/2523

**Comment by tomtomme** [comment]
So with latest nightly I still get:

**Comment by JorisGoosen** [comment]
> If I put in data manually.

it only gets sorted on load.
the only way to do it the way you expect is if we can enable sorting on a column.
I cant just sort it all the time after all, given that some order miht be desired thats different?

Or does it make no sense to have the labels in a different order then the values would indicate

**Comment by tomtomme** [comment]
So I can enter, then save, close, load and then it is sorted? I will test this asap. 
If so, we can leave it as is.

**Comment by JorisGoosen** [comment]
No sorry I should rephrase that: on import it sorts, not on load.
