### ISSUE TITLE
JASP homogeneity test for repeated measures ANOVA[Bug]: 

### ISSUE THREAD

**Issue by roseth90** [jasp-stats/jasp-issues#2711]
### JASP Version

0.18.3

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

homogeneity test for repeated measures ANOVA

### What OS are you seeing the problem on?

Windows 11

### Bug Description

This analysis terminated unexpectedly.

Error in str2lang(x): :2:0: unexpected end of input
1: resids ~
   ^

### Expected Behaviour

Would have given results.

### Steps to Reproduce

inserting data and asking for the homogeneity test for repeated measures ANOVA and givin ERROR.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
I cannot replicate this error with data from the library. Does this file work for you?
[Bugs.zip](https://github.com/jasp-stats/jasp-issues/files/15237015/Bugs.zip)

If so please share your jasp file also by zipping it first and then drag and drop it here.

**Comment by roseth90** [comment]
![JASP ERROR](https://github.com/jasp-stats/jasp-issues/assets/169171676/acbc3d54-2dcb-437b-a0a8-3e3d4b211eab)
![JASP ERROR](https://github.com/jasp-stats/jasp-issues/assets/169171676/f7823bc0-1c78-4003-94dd-07eb899efa2b)
[Moodulid_DATA_Ethel - Sheet17.csv](https://github.com/jasp-stats/jasp-issues/files/15237101/Moodulid_DATA_Ethel.-.Sheet17.csv)

could add rar file or jasp file, sent my original data

**Comment by tomtomme** [comment]
you can add jasp file, when you zip it before or if you just rename it to .zip

**Comment by tomtomme** [comment]
maybe try to get rid of the / in the name of the first var

**Comment by tomtomme** [comment]
aah nooo! You added "Vanus" to covariates! That should not even be possible! Add it to Between Subject FActors!

**Comment by tomtomme** [comment]
@JohnnyDoorn 
Covariates in RM ANOVA should be need to be metric. Can/Should we enforce this?

**Comment by roseth90** [comment]
Sorry, I al also very new to statistics and JASP as well. But I do want to add AGE as the covariate, even changing it now to 'scale', then error occurs:
![image](https://github.com/jasp-stats/jasp-issues/assets/169171676/048619a8-4995-41fb-9d13-8658f1ffbec6)

**Comment by JohnnyDoorn** [comment]
@tomtomme are you using 0.18.3? For me the analysis runs fine on the 0.19 nightly (using the csv provided above), whether Varius is a covariate or between factor. Although a homogeneity test is only possible when a between subjects factor is specified, and else you get an informative error message. 
![image](https://github.com/jasp-stats/jasp-issues/assets/15704203/ad8626e0-b9a9-4a64-909c-ad2a6d6c7b5b)

@roseth90 could you retry with the[ latest development version](https://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-development-a2ea390e3d127f56f515b4407dcd5d48d003a74e.msi)? It has all the latest features, although it's a development version so some things might not work.

**Comment by tomtomme** [comment]
confirmed - the correct error message is shown in 0.19beta - for metric and for ordinal Covariates.
