### ISSUE TITLE
[Feature Request]: Want to code "Unclear" "No answer" or "I do not want to answer" with 99 or 999

### ISSUE THREAD

**Issue by romanogino** [jasp-stats/jasp-issues#2716]
### Description

I need to code 99 as a mistake, not a number.

### Purpose

99 or 999 is a label for not answer o lost answer. Must avoid mathematical operations.

### Is your feature request related to a problem?

I coded 99 as a mistake, data lost or no answer, but being a number, it affects the results of sums and mathematical operations.

### Is your feature request related to a JASP module?

Descriptives

### Describe the solution you would like

Some value (maybe 98 and 99 or 999) for “unclear” and “missing/ skipped”

### Additional context

Perhaps there is some procedure I do not know. In that case, I apologize.

**Comment by boutinb** [comment]
As you closed this issue, I suspect you found the missing value settings?

**Comment by romanogino** [comment]
I found it! Thanks for your support. Best regards. r.
