### ISSUE TITLE
[Bug]: Please update to latest KDE - in flatpak - reporting KDE 6.5 is in EOL

### ISSUE THREAD

**Issue by tshering1980** [jasp-stats/jasp-issues#2717]
### JASP Version

0.18.3

### JASP Module

Other

### What OS are you seeing the problem on?

Linux, Flatpak, Debian

### Bug Description

Installed flatpak version of JASP - on Debian 12. Keeps reporting KDE Platform 6.5 is EOL & to upgrade to latest version.

### Expected Behaviour

KDE Platform 6.5 should have automatically upgraded to latest stable version

### Steps to Reproduce

1. Donload flatpak version of JASP 
2. Keep reporting KDE Platform 6.5 is End of Life & to upgrade to latest stable version
![Screenshot_20240511_095012](https://github.com/jasp-stats/jasp-issues/assets/48855303/49a049a9-5294-4900-a9dc-0fcd738c6288)

3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by RensDofferhoff** [comment]
Our upcoming release will upgrade to a newer version.

**Comment by tshering1980** [comment]
Thank you for your response
