### ISSUE TITLE
[Bug]: file not available when i'm done download it.. 3 times.

### ISSUE THREAD

**Issue by shasheKai** [jasp-stats/jasp-issues#2718]
### JASP Version

0.18.3

### JASP Module

Unrelated, Machine Learning

### What analysis are you seeing the problem on?

file can not be downloaded

### What OS are you seeing the problem on?

Windows 10

### Bug Description

![Eror JASP even downloa](https://github.com/jasp-stats/jasp-issues/assets/169573626/5ed4b85f-9395-4f35-95f7-17fa90f87d0f)

### Expected Behaviour

the file was missing

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@shasheKai 
Thx for the report.
Your screenshot shows, that you are running JASP 0.14.3 via rollApp. From there you try to download the update for 0.18.3. This will not work. If you want to use current JASP 0.18.3 then go to http://jasp-stats.org/download and hit the big black button named "get it from microsoft". Or if you do not have/want a microsoft account then the button above.
I hope this helps! Please reopen if not!
