### ISSUE TITLE
Descriptives do not report median or IQR, only mean and sd

### ISSUE THREAD

**Issue by tultimatte** [jasp-stats/jasp-issues#272]
Descriptives and descriptive statistics, e.g. in T-Test and ANOVA, do not report median or IQR, only mean and sd.

Thank you!

* JASP version: 0.9.1
* OS name and version: Win 10 1809

**Comment by tultimatte** [comment]
Would it be possible to add IQR at least in 'Descriptive Statistics'?
It is very time consuming to calculate IQR by hand for every non-parametric data.
Thank you!

- JASP version: 0.9.2
- OS name and version: Win 10 1809
- Analysis: Descriptives - Descriptive Statistics

**Comment by AlexanderLyNL** [comment]
Hi tultimatte,

For the Descriptives to provide the interquartile ranges, please open the Statistics tab and choose Quartiles. 

<img width="1312" alt="screen shot 2019-01-10 at 12 11 06" src="https://user-images.githubusercontent.com/10271675/50964978-fe143100-14d0-11e9-955c-a5ead918771c.png">

Please reopen if this is not the case for you.

Cheers,
Alexander

**Comment by tultimatte** [comment]
Hi Alexander,
Thanks for your reply.
Descriptives only provide Quartiles 1, 2, and 3. However, IQR is Q3-Q1 and should be reported with medians (cf. URL: https://en.wikipedia.org/wiki/Interquartile_range).
Would it be possible to include IQR with Descriptive Statistics?
It is very time-consuming to calculate Q3-Q1 by hand for every column.
Thanks a lot,
Daniel

**Comment by EJWagenmakers** [comment]
I agree this is a good idea, and easy enough to add
E.J.

**Comment by tultimatte** [comment]
Any chance that this will be integrated in the next release? :)
Thank you very much!

**Comment by AlexanderLyNL** [comment]
Yes, please discuss further here:

https://github.com/jasp-stats/jasp-issues/issues/364

In particular, regarding the ordering.
