### ISSUE TITLE
[Bug]: frequency table option is missing from Descriptive statistics 

### ISSUE THREAD

**Issue by Biswojit2011** [jasp-stats/jasp-issues#2723]
### JASP Version

0.18.3

### JASP Module

Descriptives

### What analysis are you seeing the problem on?

Frequency table option is not available 

### What OS are you seeing the problem on?

Windows 10

### Bug Description

![IMG_20240514_230724](https://github.com/jasp-stats/jasp-issues/assets/169835488/c82824f1-98b2-41e4-9731-5365d7dd8a8f)
Frequency table option is missing or not available on descriptive statistics of JASP Apk.. so not able to create frequency table... Kindly help me.

### Expected Behaviour

Frequency table option should be available within descriptive statistics option.

### Steps to Reproduce

1.
2.
3.
...
Yes

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Thx for the report. Just maximize the window and you will be able to scroll down further until you see the frequency table option. 
At the moment the win task bar is hiding it
