### ISSUE TITLE
[Feature Request]: Add overarching README to jasp-stats organization

### ISSUE THREAD

**Issue by PabRod** [jasp-stats/jasp-issues#2724]
### Description

Create a README for the landing page for developers (https://github.com/jasp-stats)

### Purpose

Be more welcoming to code contributors, and save time for all sides

### Describe the solution you would like

GitHub allows to create README's for users and organizations. They live in a special repo called .github, and render at the main page. See here a (not particularly beautiful) example: https://github.com/Team-Nabla

### Additional context

Please note that I am professionally involved in this project. If you give me writing rights, I'll be happy to write it or, at least, start it myself :)

**Comment by tomtomme** [comment]
@PabRod 
Great suggestion :)
Would be cool if you can write a draft

@boutinb 
maybe PabRod could also be added to the "issue collaborators" group? But I do not know if this will give him access to that part.

**Comment by PabRod** [comment]
@JorisGoosen just:

- Added me to [senior-collaborators](https://github.com/orgs/jasp-stats/teams/senior-collaborators)
- Suggested using `jasp-desktop`'s [README](https://github.com/jasp-stats/jasp-desktop) as a reference for the content

Thanks, @JorisGoosen!

**Comment by PabRod** [comment]
It seems that being part of `senior-collaborators` doesn't grant me rights to **create** a new repository within the organization.

Can someone help me with this? I need either:

- permission 
or 
- that someone with permission (@JohnnyDoorn?) creates an empty repo at `./jasp-stats/.github`.

Thanks in advance!

**Comment by PabRod** [comment]
I've created a (very) minimal [working version](https://github.com/jasp-stats/.github). It just points to [the readme file](https://github.com/jasp-stats/jasp-desktop/blob/development/README.md) in the `jasp-desktop` repository which, to my understanding, is the starting welcome point for developers.

We can consider the main issue fixed (the unexistence of a general readme), and keep adding content to it when needed.

**Comment by JorisGoosen** [comment]
It is indeed much more friendly now!
