### ISSUE TITLE
[Bug]: Flexplot citation shows wrong version

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#2725]
### JASP Version

0.19

### Commit ID

4825b388f588478d5e4fae448240ab5ded435d86

### JASP Module

Visual Modeling

### What analysis are you seeing the problem on?

flexplot

### What OS are you seeing the problem on?

Flatpak

### Bug Description

If I click "copy citations" via the black triangle of flexplots bar plot, then I get:

    Fife, Dustin A. (2019). Flexplot (Version 0.9.2) [Computer software].

That version is wrong

### related
https://github.com/jasp-stats/jasp-issues/issues/875

**Comment by boutinb** [comment]
@dustinfife This is in flexplot/flexplot_jasp2.R: here the addCitation method is called with the string "Fife, Dustin A. (2019). Flexplot (Version 0.9.2) [Computer software]."

**Comment by dustinfife** [comment]
I just updated it
