### ISSUE TITLE
Error when running moderator analysis [Bug]: 

### ISSUE THREAD

**Issue by aleon-leon** [jasp-stats/jasp-issues#2727]
### JASP Version

0.18.3

### JASP Module

Regression

### What analysis are you seeing the problem on?

Classical linear regression

### What OS are you seeing the problem on?

Windows 11

### Bug Description

![help](https://github.com/jasp-stats/jasp-issues/assets/170219888/d8b5aa09-549b-492c-a00a-245e2038c302)
[PSYCHOL_6602OL_Assessment_2.zip](https://github.com/jasp-stats/jasp-issues/files/15367536/PSYCHOL_6602OL_Assessment_2.zip)
When I run this analysis with 'relationship_satisfaction' variable as the DV and 'life_stress' and 'attachment_style' as the covariates/factors and try to add a product term of 'life_stress'*'attachment_style' I receive the attached error "Error in if (levels[i] = '') params[i] else paste0(params[i], ' (', levels[i], : missing value where TRUE/FALSE needed"

### Expected Behaviour

It should run the regression

### Steps to Reproduce

1. Set up a classical linear regression
2. Enter variables as described above
3. Add product term of 'life_stress'*'attachment_style'
4. Error
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JohnnyDoorn** [comment]
Hi @aleon-leon,

I cannot seem to replicate your bug, see the attached jasp file (change the extension from .zip to .jasp and then open it with JASP 0.18.3): 
[PSYCHOL_6602OL_Assessment_2_Interaction.zip](https://github.com/jasp-stats/jasp-issues/files/15375327/PSYCHOL_6602OL_Assessment_2_Interaction.zip)
Maybe I misunderstood how to reproduce the bug. Else, you can try to run the analysis with the lastest development version of JASP ([download here](https://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-development-51f9dfe5003626bc408164b240df8c6fb61787a8.msi)), which has fixed some issues that seem related to the bug you report. 

Kind regards
Johnny

**Comment by tomtomme** [comment]
I can replicate this bug with 0.18.3. It depends on the order in which you enter the variables to the analysis. This bug was already discussed and is now solved within the latest beta which you can get from here:  https://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-development-eaf4ba837e4fa817ec87fd8acd11c52ab0e64739.msi

But you can also stay on 0.18.3 and just enter the variables from top to bottom - then it should just work. Please let us know, if this helps. And please reopen this issue if not. Thx again for the report!
