### ISSUE TITLE
[Feature Request]: Add null (ANOVA) model analysis in the lineer mixed model module.

### ISSUE THREAD

**Issue by ertugruluyar-github** [jasp-stats/jasp-issues#2728]
### Description

Null (ANOVA) model analysis in the lineer mixed model module.

### Purpose

I don't want the calculate ICC for all my possible models.

### Use-case

I need ICC value that automaticly calculated for null (ANOVA) model analysis for my PISA 2022 analysis.

### Is your feature request related to a problem?

I can't calculate the ICC value, because I couldn't find the level-2 variance value on the result table of the One-Way ANOVA.

### Is your feature request related to a JASP module?

ANOVA, Mixed Models

### Describe the solution you would like

Add an null analysis in the mixed model analysis module.

### Describe alternatives that you have considered

Add level-2 variance and ICC value on the result of the One-Way ANOVA analysis.

### Additional context

I didn't find the level-2 variance value on the One-Way ANOVA analysis, there is a sum of square value for the level-1 and level-2 in the table, the value of the level-1 sum of square (variance) value correct because I did the same analysis on jamovi software. But, for level-2 (intercept) sum of square value is not same with jamovi's level-2 variance value. So, I couldn't calculate the ICC value, and it is irritating because this analysis should be in the mixed model module, and jamove has this. I am comparing this softwares for my analyisis which I am gonna do in my thesis with PISA 2022 data. JASP has OSF.io integration and it is good but these type of little irritating things not good and jamovi has +1 for this reason. And I think, I can upload my files manually on OSF with jamovi. So, jamovi is a bit above on this rank.

SO, PLAESE HELP ME! How can I calculate ICC value on One-Way ANOVA analysis.

JASP:
![jasp anova](https://github.com/jasp-stats/jasp-issues/assets/70096810/459d30c1-f1e3-4fd3-a657-31da1fbe93c3)

jamovi:
![jamovi anova](https://github.com/jasp-stats/jasp-issues/assets/70096810/77c040d9-9982-4ddc-b4a3-30d5ba679ddc)

**Comment by ertugruluyar-github** [comment]
I found this in an workshop in OSF:
![JASP One-Way ANOVA ICC](https://github.com/jasp-stats/jasp-issues/assets/70096810/12608156-a1bc-4055-a770-e35183da9279)

I did not calculated this before, in JASP, I had to choose the effect size options and I didn't know that.
Is the Eta or omega squared values represent the ICC value in null mixed model analysis?
Which one should I choose and why?

Thanks.

**Comment by FBartos** [comment]
Hi Ertuğrul,

I will respond to the mixed-effect model part of the question and @JohnnyDoorn might tackle the ANOVA effect sizes later.
The 18.3 version of JASP does not allow fitting an intercept-only model. However, we recently received requests for this feature, and it will be included in the next version (released quite soon). If you want, you can try the nightly (developmental, yet not tested build here: http://static.jasp-stats.org/Nightlies/)

Cheers.
Frantisek

**Comment by ertugruluyar-github** [comment]
Hi, František, thank you for your response. I have time for my analysis so I am gonna try JASP.
Also, I noticed that there is no ICC cell on the random effects' table but there are variance's values. If JASP provide ICC value automatically as jamovi has wouldn't be good? Because, I am gonna do multiple analysis, and each time I have to calculate this value by hand, therefore there is a risk that I could make a mistake.
Also, why the two values that specified with red rectangle different from each other?

**Comment by FBartos** [comment]
Yes, providing ICCs directly is a good suggestion. I will try to incorporate it in the next release (alongside different effect size calculations which I planed on adding).

I will leave the ANOVA question to Johnny as I don't really work with the analysis that often.
Frantisek

**Comment by JohnnyDoorn** [comment]
Hi @ertugruluyar-github ,

If I understand correctly, the only remaining question/issue you have left is about whether the omega or partial effect size is recommended? I recently switched the default effect size in ANOVA to be omega squared since that one is less biased (see this article by [Kroes, A. D. A., & Finley, J. R. (2023)](https://jasonrfinley.com/pubs/KroesFinley2023_OmegaSquared.pdf)). If you have more than one predictor, I would recommend using the partial version of that effect size instead, since that one accounts for other predictors. The new JASP version (released soon, you can check the version @FBartos linked above) will have more complete effect sizes, as well as confidence intervals for those. 

Cheers,
Johnny
