### ISSUE TITLE
Let the user edit the range of each axis on a scatter plot.

### ISSUE THREAD

**Issue by R180** [jasp-stats/jasp-issues#2729]
### Description

Currently, users can edit a plot, but not if it's 'complex' in that it consists of multiple plot objects. All of the ways of getting a scatter plot in JASP involve complex, multiple plot objects.

### Use-case

Eg., a user may want each axis to cover the entire range of the variable being plotted.

### Describe the solution you would like

In DESCRIPTIVES / BASIC PLOTS / CORRELATION PLOTS, make the produced scatter plot a truly basic plot so that it can be edited.

**Comment by tomtomme** [comment]
I just found an old issue discussing this: 
https://github.com/jasp-stats/jasp-issues/issues/1354

There are several workarounds for you at the moment:
- Save the plot as pptx and edit it in Powerpoint. 
- plot the scatterplot with visual modeling => flexplot

This is certainly only a temporary solution until we can make multiplots editable.
Your request mentions another possible workaround (renounce multiplots in descriptives), which might also be a nice solution. Which solution would you prefer? Or is one of the workarounds above already sufficient?

Related: https://github.com/jasp-stats/jaspGraphs/pull/72

**Comment by R180** [comment]
Hi. Thanks. Unfortunately, I don't think there are any workarounds at the moment. Pptx files are graphic files that permit editing things such as line colors, text, and fonts, but not the data-range of an axis. Flexplot could work in principle. However, there's a current bug in flexplot that permits editing the scatterplot's x axis range but prevents editing the scatterplot's y axis range (see below). So I think the flexplot option would be fine if the bug were fixed. 
![image](https://github.com/jasp-stats/jasp-issues/assets/16230091/142c7fed-5800-4498-b05a-edabcc0989d8)

**Comment by tomtomme** [comment]
@R180 @dustinfife 
This may have been my error. If I set it this way, I can change the axis:
![grafik](https://github.com/user-attachments/assets/2b77f3e6-c6fa-4f92-a70d-bb3c25776c13)

Tested with current 0.19.2 beta
So I guess we can close this one for now?
Editable multiplots are certainly still a feature we are striving for, but this is on the ToDo here: 
https://github.com/jasp-stats/jasp-issues/issues/1354
