### ISSUE TITLE
What the person who wrote the textbook on Doing Bayesian Data Analysis said about JASP

### ISSUE THREAD

**Issue by VHAdderly** [jasp-stats/jasp-issues#273]
What the person who wrote the major US textbook on Doing Bayesian Data Analysis has to say about JASP:

I sent an email to the author of one of the definitive textbooks on doing Bayesian data analysis to get his opinion on the JASP program and to ask him if he thought it would be a good program to use for teaching Bayesian data analysis to beginning stats students. Maybe you guys should contact him.

 This was his reply:

I'm reluctant about JASP at this point for two reasons; first it emphasizes frequentist stats (just a free version of SPSS), and second its Bayesian components emphasize Bayes factors, or at least did in early versions. As you may know, I am not a fan of Bayes factors (see the five main caveats about Bayes factors in this article: https://link.springer.com/article/10.3758/s13423-017-1272-1). But maybe JASP will eventually develop into something I'd be more enthusiastic about; it's just not there yet. I understand the Jamovi is also developing (https://www.jamovi.org/).

I have no definite plans for writing a third edition of DBDA or for another stats book, though I certainly have thought about it. There are other projects I'd like to work on first.

Thanks for your interest and kind remarks.

John

John K. Kruschke 
Provost Professor, Indiana University
The Bayesian New Statistics: article

**Comment by VHAdderly** [comment]
For more on this see the following short article

https://www.frontiersin.org/articles/10.3389/fams.2017.00012/full

**Comment by EJWagenmakers** [comment]
Yes, we are keenly aware of the fact that John does not apply Bayes' rule to models and parameters with quite the same gusto. That is his choice. Note that for very many statistical analyses, JASP can be used both for Bayesian estimation and for Bayesian hypothesis testing. This is neither a bug report nor a feature request, so I am closing this issue. If you have specific issues with the interpretation of analyses in JASP I would direct you to the JASP forum instead.
Cheers,
EJ
