### ISSUE TITLE
Table doesn't calculate results: 2x2 mixed design repeated measures ANOVA [Bug] 

### ISSUE THREAD

**Issue by leahomann** [jasp-stats/jasp-issues#2732]
### JASP Version

0.17.0

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

2x2 mixed design repeated measures ANOVA

### What OS are you seeing the problem on?

Windows 11

### Bug Description

Best description is my picture.

Background: My dependent variable is called "accuracy". I want to examine the accuracy depending on the "spacing" (smalll/large) of a visual stimulus (within-person factor), with numeracy skills ("NUFaehigkeiten") as a between-person factor. I therefore want to calculate Spacing x Numeracy.

When I enter just one factor in "repeated measures factors", it doesn't calculate anything, only when I add a second repeated measures factor, it calculates something.
![image](https://github.com/jasp-stats/jasp-issues/assets/84978906/8d9ee0c1-751e-4e23-a0cb-9cba0d4c929c)

Don't know if I missed something and it's my fault or if it's actually a bug.

### Expected Behaviour

It should calculate something (as seen in the pictures attached, taken from YouTube screenshots), as my data are formatted the same way, with one repeated measures factor and one between subject factor. I downloaded JASP >1 year but <3 years, so well within the timeframe of the versions probably used in the video.

![image](https://github.com/jasp-stats/jasp-issues/assets/84978906/73b24edb-8033-43ff-a294-14d6007693fa)
![image](https://github.com/jasp-stats/jasp-issues/assets/84978906/82407cc2-85db-48ea-8640-b34a1d5dbe25)

### Steps to Reproduce

1. Just filling in the same stuff I did in my picture, it never works

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Thx for the report. Can you try with version 0.18.3?

**Comment by leahomann** [comment]
Sorry for the late answer, I ran into some trouble updating which took a while to fix.
It worked, the table is showing numbers, and I can interpret the results! :)
Thanks! I'm still a bit curious why it didn't work with the old version? It was downloaded in February 2022, which was between the two screenshots I attached above which show it worked ... well.

**Comment by tomtomme** [comment]
I do not know and cannot test older versions on my linux machines, sorry
