### ISSUE TITLE
[Bug]: choppy panel dragging after entering data

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#2733]
with 0.18.3 and latest 0.19 beta

### What analysis are you seeing the problem on?

entering data

### Bug Description

After entering some data, dragging panels via the 3 vertical grey dots gets extremely choppy, like 1fps slideshow.
This does not happen when starting with data from the data library! Only when I enter values myself. The amount in the screenshot is enough to trigger it. 
Might be intel+wayland related? But strange that it does not occur with loaded data...

### Expected Behaviour

JASP should stay fluent as always

### Steps to Reproduce

1. open jasp
2. enter some columns of data
3. drag an analysis panel

**Comment by tomtomme** [comment]
Exactly

**Comment by RensDofferhoff** [comment]
Great find!
