### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by akhfiya** [jasp-stats/jasp-issues#2741]
### JASP Version

0.18.3

### JASP Module

Reliability

### What analysis are you seeing the problem on?

undimensional reliability

### What OS are you seeing the problem on?

Windows 11

### Bug Description

why does loading unidimensional reliability results take so long? Even at that time I tried almost waiting for the results to come out for around 2-3 hours, I wanted to see Cronbach alpha and item-rest correlations so it was very hampered because the application took a very long time to load. It should be noted, my internet connection is very smooth, but why does it take so long to load? What needs to be done so that it doesn't take long to load?
![Screenshot (8)](https://github.com/jasp-stats/jasp-issues/assets/170903498/68e6af6e-547f-4914-aa8d-8e0859e1d7db)

### Expected Behaviour

loading unidimensional reliability (cronbach alpha and item-rest correlations) take soooooooooooo longggg, the results to come out for around 2-3 hours.

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment]
Dear @akhfiya, thanks for creating the issue. Several reasons why this is taking so long come to mind. Did you specify any of the other options in the analysis? For instance some bootstrapping? If you select the omega coefficient, like in your screenshot, the analysis fits a CFA in the background, and depending on your data, that can sometimes take a bit more time, although usually not 2-3h. If you are only interested in alpha, you should only select alpha and try de-selecting everything related to bootstrapping. If you were to share your zipped .jasp file I could be of more help.

**Comment by tomtomme** [comment]
@akhfiya 
any news for us on this one?
