### ISSUE TITLE
[Bug]: Label changes silently discarded when clicking on cells

### ISSUE THREAD

**Issue by richlv** [jasp-stats/jasp-issues#2744]
### JASP Version

0.18.3

### JASP Module

Other

### What analysis are you seeing the problem on?

Label editing

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

Open label editing. Edit a label. Click on another column name and back on the original column - change is preserved.
Edit a label. Click in another column cell (not on the column name) and back on the original column - change is silently discarded.

### Expected Behaviour

Change to be preserved.

### Steps to Reproduce

As per above.

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JorisGoosen** [comment]
This is fixed in the latest nightlies no?
https://static.jasp-stats.org/Nightlies/
