### ISSUE TITLE
[Bug]: JASP is not responding on Descriptive Statistics 

### ISSUE THREAD

**Issue by Ranazlgt** [jasp-stats/jasp-issues#2749]
### JASP Version

0.18.3

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

descrptive statistics

### What OS are you seeing the problem on?

Windows 11

### Bug Description

whenever i try to check descriptive statistics, JASP freezes as it shows that jasp is not responding. please this issue is urgent as my research assignment is due very soon as i need to access jasp to analyze data and check variables. 

### Expected Behaviour

JASP should not freeze and i should be able to move the variables.

### Steps to Reproduce

[](url)
i cant i just need some help, i tried to delete and resinstall JASP but its not working it keeps on freezing. i tried to change the file format but still its not working, it is csv.

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by Ranazlgt** [comment]
![Screenshot (4)](https://github.com/jasp-stats/jasp-issues/assets/171040479/1f66f4e9-dd5a-41a4-95ab-b1b9159e656c)

**Comment by tomtomme** [comment]
@Ranazlgt 
Any news for us on this one? Success stories also welcome :D

**Comment by coi96** [comment]
I'm having the same issue on Chromebook right now. it says waiting for initialization and I really need it to work today

**Comment by boutinb** [comment]
I have got this problem once (but could not reproduce this afterwards), and just by switching the Interface language (in Preferences) to another language temporarily solved this problem.
