### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [jasp-stats/jasp-issues#275]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [FileEvent](https://github.com/jasp-stats/jasp-desktop/blob/f15ad108e94b1905231f82f0c8de7c963e21ecef/JASP-Desktop/data/fileevent.cpp#L52 "Destructor for FileEvent")
- [DataSetView::setItemDelegate](https://github.com/jasp-stats/jasp-desktop/blob/43205648adf2b28ea805a15c2b60381a9bcda2c5/JASP-Desktop/qquick/datasetview.cpp#L680 "DataSetView::setItemDelegate function")
- [OnlineDataNode::deleteActionFilter](https://github.com/jasp-stats/jasp-desktop/blob/f15ad108e94b1905231f82f0c8de7c963e21ecef/JASP-Desktop/osf/onlinedatanode.cpp#L45 "OnlineDataNode::deleteActionFilter function")

**Comment by boutinb** [comment]
Hi @elfring 
You are right, you can delete null ptr, it does not harm. Next time I will change something in this file, I will suppress this if.

**Comment by elfring** [comment]
Why did you close this issue before a corresponding source code update?
