### ISSUE TITLE
[Bug]: Flexplot - only allow 2 variables in the input boxes?

### ISSUE THREAD

**Issue by JohnnyDoorn** [jasp-stats/jasp-issues#2750]
### JASP Version

Others

### Commit ID

https://github.com/jasp-stats/jasp-desktop/commit/1ad17d3f9a420348e808a20679333a3669794f55

### JASP Module

Visual Modeling

### What analysis are you seeing the problem on?

Flexplot

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

Flexplot doesn't use 3rd variables in the two assignment boxes (paneled and independent), or maybe there are some cases where it does? It also gives an error sometimes:
![image](https://github.com/jasp-stats/jasp-issues/assets/15704203/eb3d9c83-34af-4c0b-8338-c7c40d1578dd)

### Expected Behaviour

Limit the number of variables, which could also help with some errors I think

### Steps to Reproduce

1. specify a 3rd variable in any of the boxes
2. 
3.
...

### Log (if any)

change ext to .jasp
[flexplotexample.zip](https://github.com/jasp-stats/jasp-issues/files/15470480/flexplotexample.zip)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by dustinfife** [comment]
Flexplot shouldn't allow a third paneled variable.

**Comment by JohnnyDoorn** [comment]
Are there cases where it can handle a third independent variable? There it also seems that the limit is/should be 2.

**Comment by boutinb** [comment]
You can add `maxRows: 2` in the VariablesList to prevent from having more than 2 variables.

**Comment by tomtomme** [comment]
@dustinfife 
Can you clarify? 
Limit for paneled variable = 2
Limit for independent var = 2

correct?

**Comment by JohnnyDoorn** [comment]
I'll add it to the qml
