### ISSUE TITLE
[Bug]: Changes to column types are not saved when you reopen the file. 

### ISSUE THREAD

**Issue by yoon9751** [jasp-stats/jasp-issues#2751]
### JASP Version

0.18.3

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 11

### Bug Description

While cleaning data, some categorical variables that are displayed as scales need to be appropriately changed, either to ordinal or nominal. However, after saving those changes and reopening the file, they do not persist.   

### Expected Behaviour

Saved changes should be retained. 

### Steps to Reproduce

1. Open an original, uncleaned data file on JASP
2. Change Column Types for categorical variables from scale to either nominal or ordinal
3. Save them
4. Re-open the data file
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@yoon9751 
Thx for the report

**I can confirm this for**
nomi to ordi
ordi to nomi

**not for**
ordi to scale
nomi to scale
scale to ordi
scale to nomi

I also tested this in the latest 0.19 beta and it is fixed there!
If you want to try it, see https://static.jasp-stats.org/Nightlies/
