### ISSUE TITLE
[Bug]: No Distributions, Reliability, SEM and Visual Modeling

### ISSUE THREAD

**Issue by dewbloom23** [jasp-stats/jasp-issues#2755]
### JASP Version

0.18.3

### JASP Module

Reliability

### What OS are you seeing the problem on?

Windows 10

### Bug Description

Dear customer service, 
on my PC, JASP doesn't show Distributions, Reliability, SEM and Visual Modeling
![jasp customer support](https://github.com/jasp-stats/jasp-issues/assets/126025830/f27a9c54-a31b-4f11-be9c-724f2da5febc) :'(. 

### Expected Behaviour

It should show Distributions, Reliability, SEM and Visual Modeling

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Click the big blue + sign on the top right to add them
