### ISSUE TITLE
[Bug]: JASP V 0.18.3 does not display the results panel on windows 10

### ISSUE THREAD

**Issue by BryanAbuchery** [jasp-stats/jasp-issues#2756]
### JASP Version

0.18.3

### JASP Module

Acceptance Sampling, ANOVA, Audit, Bain, Bsts, Circular Statistics, Cochrane Meta-Analyses, Descriptives, Distributions, Equivalence T-Tests, Factor, Frequencies, JAGS, Learn Bayes, Learn Stats, Machine Learning, Meta Analysis, Mixed Models, Network, Predictive Analytics, Process, Prophet, Quality Control, Regression, Reliability, Robust T-Tests, SEM, Survival, Summary Statistics, T-Tests, Time Series, Visual Modeling, Other

### What analysis are you seeing the problem on?

No results panel for all analyses

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I can´t use JASP because the results panel shows nothing 

### Expected Behaviour

Display something on results panel

### Steps to Reproduce

1. Launch JASP
2. Import any data
3. Run analyses
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@BryanAbuchery 
Thx for the report. 

- [ ] Is Win10 fully up to date?
- [ ] Did you try installing JASP via the windows store?
- [ ] Did you try restarting the machine / PC?

**Comment by shun2wang** [comment]
Hi @BryanAbuchery Sounds a results panel initialize problems, could you try the test version: https://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-development-aa916600683f72ca0d1611b3c33bce2bc53824cf.msi 
You can also try updating PC graphics driver.

Please note that this is a development version only and may have other issues. The official version will be released soon later.

**Comment by BryanAbuchery** [comment]
Hello everyone. I did follow the suggestions left here. Sorry I couldn't provide data, but I was able to export the results in .pdf where I was able to see them, just not in real time during the analyses. However the test version also provided helped. I will update the PC drivers soon and hope that it helps. Thanks everyone!

**Comment by shun2wang** [comment]
>However the test version also provided helped.

Great, then the fix will including in the next release. thanks.
