### ISSUE TITLE
RM Bayesian ANOVA display bug

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-issues#276]
From the Forum:
http://forum.cogsci.nl/index.php?p=/discussion/4667/repeated-measures-bayesian-anova-possible-bug#latest

@vandenman 

Cheers,
E.J.

**Comment by boutinb** [comment]
@vandenman Can you have a look?

**Comment by vandenman** [comment]
@boutinb I can replicate the error with the last JASP version, but not with development. It looks like a bug in the RM ANOVA widget that overwrites the levels of the 3rd factor when entering the names of the levels of the 4th factor. On the R side the names don't get updated any more, so the wrong names appear.

**Comment by TimKDJ** [comment]
This was fixed with the QML rewrite.
