### ISSUE TITLE
[Feature Request]: increase consistency between Bayesian and frequentist reliability

### ISSUE THREAD

**Issue by wolfvanpaemel** [jasp-stats/jasp-issues#2760]
### Description

in the Bayesian reliability module, there is an option to compute the standardized version of all coefficients (omega, lambda, GLB, alpha), whereas in the frequentist reliability module, this option only exists for alpha. while the standardized version of these coefficients are not being used a lot (except for maybe alpha), users might value the consistency between the Bayesian and frequentist versions

### Purpose

increase consistency between Bayesian and frequentist reliability

### Is your feature request related to a problem?

no

### Is your feature request related to a JASP module?

Reliability

### Describe the solution you would like

add the standardized version of all the other coefficients besides alpha to the frequentist calculations

**Comment by tomtomme** [comment]
@wolfvanpaemel 
this is now being worked on
