### ISSUE TITLE
[Feature Request]: avoid clutter in Bayesian reliability module

### ISSUE THREAD

**Issue by wolfvanpaemel** [jasp-stats/jasp-issues#2761]
### Description

unlike in its frequentist counterpart, the Bayesian reliability automatically provides a CI. especially when several coefficients are required, this can become can cluttered. 

### Is your feature request related to a problem?

no

### Is your feature request related to a JASP module?

Reliability

### Describe the solution you would like

follow the design of the frequentist reliability, and make the output of the CI optional

### Additional context

making the CI optional in the Bayesian reliability, as it is in the frequentist counterpart, will increase consistency between both modules

**Comment by JoKeyser** [comment]
For the record: On top of consistency with the frequentist output, _progressive disclosure_ of results is one of [JASP's vision and goals](https://jasp-stats.org/community-vision-and-goals/).
