### ISSUE TITLE
[Bug]: error message when trying to perform LGCM in JASP

### ISSUE THREAD

**Issue by caroliee** [jasp-stats/jasp-issues#2764]
### JASP Version

0.18.3

### JASP Module

SEM

### What analysis are you seeing the problem on?

Latent growth curve model

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I was executing a latent growth curve model with 6 time points. When I added a factor "group" (1 = intervention, 2 = control) the following error message shows up:

Error in .lgcmEnrichData(dataset, options): object 'currentNa' not found

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.lgcmEnrichData(dataset, options)

options(na.action = currentNa)

### Expected Behaviour

Regression coefficients for the groups should be displayed

### Steps to Reproduce

I have the same issue when i perform the latent curve model with the example dataset from this JASP tutorial site: https://jasp-stats.org/2022/02/22/latent-growth-curve-modeling-lgcm-in-jasp/
![LGCM gpa dataset with factor](https://github.com/jasp-stats/jasp-issues/assets/171804679/52a2549e-a22d-4efe-a32b-276f27568ea7)
![LGCM my dataset with factor group](https://github.com/jasp-stats/jasp-issues/assets/171804679/aa612d67-7654-4149-ae25-5cbd61e77afc)
![LGCM my dataset without factor](https://github.com/jasp-stats/jasp-issues/assets/171804679/7e69fc98-8af0-4393-8dfa-7ee10442d92f)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment]
@caroliee, thanks for creating the issue. I think this should be fixed in the next release (https://github.com/jasp-stats/jaspSem/pull/205), alternatively you can try one of the JASP nightly versions, it should also already be fixed there.

**Comment by caroliee** [comment]
Hi @juliuspfadt, can you tell me when the next release will be with this bug fix or if there is a previous version of JASP where the error message was not there? Thank you very much for helping!

**Comment by tomtomme** [comment]
It will be out in some weeks we hope

**Comment by MCube78** [comment]
Had the exact same issue, I confirm the latest nightly (07-09-24) works.

**Comment by caroliee** [comment]
Great, thanks for letting me know!
