### ISSUE TITLE
[Bug]: .JASP file does not open after update to 0.18.3

### ISSUE THREAD

**Issue by z3r0c001MD** [jasp-stats/jasp-issues#2768]
### JASP Version

0.18.3

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 10

### Bug Description

After saving the .jasp data file I can't open it anymore. It worked fine and suddenly I get an error right at the end of loading the database saying: unable to open file because: Entry 'resources/8/_0_t-622283608.png' has zero bytes data...

Please see attached image and .jasp file.
I've updated to the 0.18.3 version recently, the original .jasp file was created on 0.17.3 earlier but I opened it after the update, made changes and saved a couple of times without issues... What I've noticed it that the analysis some plots did not appear but after I uncheck/ checked the plots and scatterplots options it generated them back.

The last thing I did before the error appeared is to export the results into an html file.

Can you please help me? I am in urgent need to open that .jasp database! Thank you!

![JASP error bug](https://github.com/jasp-stats/jasp-issues/assets/172150073/fe13d261-3aa9-41dc-9bad-e12579bdeb24)

### Expected Behaviour

The file should open

### Steps to Reproduce

1. Open jasp file
2. at the end of loading the file I get the error

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Thx for the report! Good to know how this can be fixed!

**Comment by boutinb** [comment]
Yes, but still really strange these empty png files...
