### ISSUE TITLE
ROC and PR curve (after classification)

### ISSUE THREAD

**Issue by MCube78** [jasp-stats/jasp-issues#277]
* Enhancement: ROC curve (sensitivity vs 1-specificity curve) & PR curve (precision [i.e., sensitivity] vs recall curve)
* Purpose: To create a graphic display for one or more models
* Use-case: I run a binary logistic regression with one model and plot an ROC or PR curve (in fact I might want to be able to plot multiple ROC or multiple PR curves on the same graphs)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
A button!!! :-p

**Describe alternatives you've considered**
I think there are 2 features that would accomplish that:
1. you could just have an option that creates ROC or PR graphs (or both!!) for any classification model, that might just be a button in the performance diagnostics or performance metrics section.
2. Alternatively (or even better, in addition) you could allow exporting the sensitivity, specificity, and recall values, so one can export them and create plots with multiple ROC or multiple PR curves which is a convenient way of comparing model performances.

**Additional context**
Only additional request: keep at it, I heart JASP!

**Comment by EJWagenmakers** [comment]
@vankesteren ?
