### ISSUE TITLE
Multiple samples represented on one graph : histogram

### ISSUE THREAD

**Issue by Franck6S** [jasp-stats/jasp-issues#2770]
### Description

Graphical representation

### Purpose

graphical analysis

### Use-case

Comparison of several samples

### Is your feature request related to a problem?

Limited capacity in usage of JASP for graphical analysis

### Is your feature request related to a JASP module?

Descriptives

### Describe the solution you would like

display on a graph (histogram) of several  samples to be able to compare and having related tables of parameters of sample (ie Mean, standard deviation, samples quantity,...)

### Describe alternatives that you have considered

Using box plot , but limited outcomes regarding visualisation

### Additional context

Example of expected outcome :
![image](https://github.com/jasp-stats/jasp-issues/assets/152309774/628ae111-ddd7-490a-903d-622f509a7eac)

Box plot trials without expected success 
![image](https://github.com/jasp-stats/jasp-issues/assets/152309774/ec8db9e4-a62c-467e-9cbf-9f3a6b436972)

**Comment by tomtomme** [comment]
This is available via 0.19beta. 0.19 final might release in a month or so.
If you eant to test the beta, see https://static.jasp-stats.org/Nightlies/

**Comment by tomtomme** [comment]
Also: In 0.18.3 you can create grouped density plots via descriptives, customizable plots, frequency plots. There you will also find the option to switch to (stacked or dodged) histogram in 0.19.
