### ISSUE TITLE
[Bug]: Error when saving plots as SVG

### ISSUE THREAD

**Issue by JoKeyser** [jasp-stats/jasp-issues#2773]
### JASP Version

JASP 0.19 

### Commit ID

`2f53f98b336720bfb44241df4145741a46b1d75e`

### JASP Module

Descriptives

### What OS are you seeing the problem on?

Ubuntu 22.04.4 LTS, Flatpak 1.14.4.

### Bug Description

Similar to #1775, when I try to save plots as SVG, I get the error message "path must point to a valid file".

![jasp-error](https://github.com/jasp-stats/jasp-issues/assets/8722846/bb724d58-fc33-4ed3-986d-9b7f2d9b2fcf)

Note that in #1775, it's claimed that it worked fine on 0.18.3, maybe a regression?

### Expected Behaviour

JASP should save the plot as SVG file.

### Steps to Reproduce

1. Select to save figure from Descriptives module, as SVG

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Strange. Saving as SVG works fine for me. Maybe ubuntu specific. Or something broken in an older flatpak version. 
I have:
flatpak --version
Flatpak 1.15.8


-------- Application Info --------
JASP Version: JASP 0.19
Build Branch: HEAD
Build Date: May 23 2024 21:22:50 (Netherlands)
Last Commit: 2f53f98b336720bfb44241df4145741a46b1d75e

-------- Basic Info --------
Operating System: KDE Flatpak runtime
Product Version: 6.7
Kernel Type: linux
Kernel Version: 6.6.32-1-MANJARO
Architecture: x86_64
Install Path: /app/bin
System Local: de_DE

**Comment by JoKeyser** [comment]
@tomtomme , thanks for checking; that's strange. Maybe it's indeed specific to Ubuntu; I'm running Ubuntu 22.04.4 LTS.

We have the same app version, but Flatpak is different.
And/or maybe, we have different settings within JASP..?

```
flatpak --version
Flatpak 1.14.4
```

```
-------- Application Info --------
JASP Version: JASP 0.19
Build Branch: HEAD
Build Date: May 23 2024 21:22:50 (Netherlands)
Last Commit: 2f53f98b336720bfb44241df4145741a46b1d75e

-------- Basic Info --------
Operating System: KDE Flatpak runtime
Product Version: 6.7
Kernel Type: linux
Kernel Version: 5.15.0-112-generic
Architecture: x86_64
Install Path: /app/bin
System Local: en_US
```

**Comment by tomtomme** [comment]
I just tried again and cleared all settings beforehand. SVG export works. I tried saving in home and in a sub-directory. Where do you try to save? I had flatpak apps in the past (like MS teams) that had only access to the Download folder.

**Comment by tomtomme** [comment]
Also, in the issue you linked, vandenman did pointed to the font type. Do you have a non-default font set in JASP?

**Comment by JoKeyser** [comment]
@tomtomme thanks for checking again.

I'm trying to save to folders outside `Downloads`, and that works with PNG and other formats, but not with SVG.
So the only difference in my behaviour is whether I set the saving option to SVG or PNG, for example.

I'm not aware that I changed the font type, it's set to `Standard: DejaVu Sans` and `Standard: Fira Code`.

Is there a way to reset all settings?

![jasp-settings1](https://github.com/jasp-stats/jasp-issues/assets/8722846/c82e7059-140e-43ea-9b37-62cae12bead5)

**Comment by tomtomme** [comment]
My "user interface options" look exactly like yours.
To reset all settings I delete the following folder:

/home/tom/.var/app/org.jaspstats.JASP/

You could also try without "use native file dialogs" etc.

And check the content of /home/tom/.local/share/flatpak/overrides/org.jaspstats.JASP

This contains for me:
[Context]
devices=all;
features=devel;
filesystems=home:create;host:create;host-os:create;

**Comment by JoKeyser** [comment]
Hmmm... ok I also tried all those things, but the problem persists; it's always the same error.

Specifically:

- I removed the folder `$HOME/.var/app/org.jaspstats.JASP/` to delete all settings.
- I tried to enable or disable the setting "use native file dialogs".
- I tried to read `$HOME/.local/share/flatpak/overrides/` but I don't have an `overrides` folder there.

**Comment by JoKeyser** [comment]
In addition, here are JASP log files of me opening JASP, trying to save a figure as SVG, and then closing JASP:

[JASP 2024-06-11 17_31_46 Engine 0.log](https://github.com/user-attachments/files/15791645/JASP.2024-06-11.17_31_46.Engine.0.log)
[JASP 2024-06-11 17_31_46 Desktop.log](https://github.com/user-attachments/files/15791646/JASP.2024-06-11.17_31_46.Desktop.log)

**Comment by tomtomme** [comment]
Maybe the the missing override file is the culprit. I will try tomorrow what happens if I delete it.

**Comment by tomtomme** [comment]
That is also not it. Deleted the override file and can still save svgs. Maybe then it is the different-flatpak-version-thing. But as you have all noticed by now, I am clueless and grasping for straws.

@shun2wang 
any ideas?

**Comment by JoKeyser** [comment]
@tomtomme thank you for checking so much.

Now I noticed that when I try to update JASP, I get this message, do you see that as well?

```
flatpak update org.jaspstats.JASP
Looking for updates…

Info: runtime org.kde.Platform branch 6.5 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Platform and SDK
Info: applications using this runtime:
   org.jaspstats.JASP

Nothing to do.
```

I get the same message when I try to `flatpak upgrade org.kde.Platform`.

Not sure if I can to resolve this, or is this the case for everyone using flatpak?

**Comment by shun2wang** [comment]
> I get the same message when I try to flatpak upgrade org.kde.Platform.

Hi @JoKeyser the  message what you see is not related, we will update runtime in the next release. could you share the files so we can look into it? I'ii try to reproduce...

@tomtomme This might not related to flatpak/system because flatpak including a same runtime and env for every Linux based OS.

**Comment by JoKeyser** [comment]
@shun2wang thanks for the clarification about `org.kde.Platform`.

@shun2wang , the error is not specific to any file; I can reproduce the error by opening the Sleep:Descriptives example from the Data Library (before trying to save the boxplot figure, JASP prompts me re-run the analysis, since the example was saved with an earlier version).

**Comment by tomtomme** [comment]
@shun2wang 
I suspect a flatpak bug, becaues JoKeyer: Flatpak 1.14.4 and me Flatpak 1.15.8

@JoKeyser 
yes, everybody gets the message about the old runtime. It is a security warning with few implications.

**Comment by shun2wang** [comment]
I cannot reproduce it on Linux or with flatpak. but it's not related to that.

@vandenman it might be a `systemfont` registry problem I guess, if I understand right in the logs:
```
	"resultFont" : "freesans,sans-serif",
```
according to https://systemfonts.r-lib.org/index.html#system-defaults and the user's settings pic it should returen "ejaVu Sans" ? from https://github.com/jasp-stats/jaspBase/blob/a5ae69e40614045667a3fbafaf337a95e8a40f3c/R/common.R#L180 should JASP `register_font` for all font or specified?

**Comment by tomtomme** [comment]
@JoKeyser 
Is this still an issue on ubuntu or did a flatpak update came along that maybe fixed it?
Also atm with 0.19.2 beta all default fonts are now for me "noto sans". So sth. has changed there.

**Comment by JoKeyser** [comment]
Hi, I just tested again and it works now, nice!

For reference, I've tested with Ubuntu 22.04.5 LTS, Flatpak 1.14.10, and JASP 0.19.2, though from Flatpak I get "0.19.1", see below.

```
flatpak info org.jaspstats.JASP/x86_64/stable

JASP - Classical and Bayesian Statistics

          ID: org.jaspstats.JASP
         Ref: app/org.jaspstats.JASP/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 0.19.1
     License: AGPL-3.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 2,2 GB
     Runtime: org.kde.Platform/x86_64/6.7
         Sdk: org.kde.Sdk/x86_64/6.7

      Commit: b8bd39f299bb40beed57d8d54032cab9ccd12bf6fe301dec1f72c9132dc7ae5a
      Parent: b4365db815bb2b8e661394126377159f1d0d7fc4919601648f47564302a387e0
     Subject: v0.19.1 (08562cfa)
        Date: 2024-09-10 17:14:14 +0000
```

So from my point of view, this bug is fixed.
