### ISSUE TITLE
[Bug]: I get a error saying: Unable to open file because: No entry (internal.sqlite) found in archive file.

### ISSUE THREAD

**Issue by lanqian21** [jasp-stats/jasp-issues#2775]
### JASP Version

0.18.3

### JASP Module

Other

### What analysis are you seeing the problem on?

Opening the file

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I get a error saying: Unable to open file because: No entry (internal.sqlite) found in archive file.

<img width="249" alt="Error jasp" src="https://github.com/jasp-stats/jasp-issues/assets/172372242/4340c218-dc17-49c9-85db-9e9408a61322">

### Expected Behaviour

The file should have opened

### Steps to Reproduce

1. I open jasp
2. try to open my file
3. then I get the error
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
HI @lanqian21 How old is this JASP file, from which JASP version does it come?
Would it be possible to get this JASP file?

**Comment by tomtomme** [comment]
@lanqian21 
This happened to me also occasionally. 
I think it happened mostly if an analysis was still computing something and I saved during that time and closed JASP to early. Then the file was not completely saved and could not be opened. It may have also to do with working with older files from earlier jasp versions, but I cannot remember exactly if this was always the case when this happend to me.
