### ISSUE TITLE
[Bug] process did not get a vector or list as column

### ISSUE THREAD

**Issue by ektas55** [jasp-stats/jasp-issues#2777]
### JASP Version

0.18.3

### JASP Module

Process

### What analysis are you seeing the problem on?

PROCESS

### What OS are you seeing the problem on?

Windows 11

### Bug Description

I am trying to work On PROCESS but it is showing error This analysis terminated unexpectedly.

Error in x$`[[<-`(i, value): Did not get a vector or list as column..
Stack trace
doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.procRsquared(jaspResults, options, modelsContainer)

`[[<-`(`*tmp*`, '__var__', value = NULL)

`[[<-.jaspTableR`(`*tmp*`, '__var__', value = NULL)

x$.__enclos_env__$private$setField(field, value)

`[[<-`(`*tmp*`, field, value = NULL)

.local(x, i, j, ..., value = value)

x$`[[<-`(i, value)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

### Expected Behaviour

Should have shown output

### Steps to Reproduce

1. No
2.
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@ektas55 
thx for the report. Can you rename the .jasp file you used to .zip and upload it here so we can try to reproduce the error?
Sadly the error message alone does not tell the whole story of what went wrong.

**Comment by maltelueken** [comment]
Thanks for creating the issue, my suspicion is that this bug is already solved in the new release, but without the .jasp file I can't be sure.

**Comment by tomtomme** [comment]
@ektas55 
any news for us on this one? Can you upload the file?
