### ISSUE TITLE
there is no package called 'withr'

### ISSUE THREAD

**Issue by MCube78** [jasp-stats/jasp-issues#278]
* JASP version: 0.9.2 (this bug was not present in 0.9.1)
* OS name and version: Windows 10
* Analysis: 
Attached figure 1: Binary Logistic Regression > Plots display conditional estimates > Show data points
Attached figure 2: Descriptives-->Jitter elements

* Bug description: When I try to display individual datapoints on graphs it gives this error (this bug was not present in the 0.9.1 version)
TEXT from JASP output:
This analysis terminated unexpectedly.
Error in loadNamespace(name): there is no package called 'withr'
Stack trace
f(...)
with_seed_null(params$seed, transform_position(data, trans_x, trans_y))
withr::with_seed
getExportedValue(pkg, name)
asNamespace(ns)
getNamespace(ns)
tryCatch(loadNamespace(name), error = function(e) stop(e))
tryCatchList(expr, classes, parentenv, handlers)
tryCatchOne(expr, names, parentenv, handlers[[1]])
value[[3]](cond)
To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

* Add JASP files as a zip:
* Screenshot: 
Example 1 (binary logistic)
![jasp_bug](https://user-images.githubusercontent.com/29030917/50189285-7e33e600-02d9-11e9-861d-ad98c9d609e1.png)

Example 2 (descriptives, boxplot jitter elements)
![jasp_bug2](https://user-images.githubusercontent.com/29030917/50189286-81c76d00-02d9-11e9-8a7e-5b2bd9775a80.png)

* Expected behaviour: see individual points on graphs
* Steps to reproduce: 
Example 1. Go to binary logistic regression > Plots > Display conditional estimates plot > show data points (error happens here -- see figure)
Example 2. Go to descriptives > select some variable > Plots > Boxplot > Jitter element (error happens here -- see figure)

UPDATE: I re-installed JASP0.9.1 and, on the exact same data set, I am able to plot without an issue individual data points. So this must definitely be something that has changed between 0.9.1 and 0.9.2. I hope this helps solve it.

**Comment by FransMeerhoff** [comment]
Hi @MCube78 

Thanks for reporting this.
This is indeed an omission in the R framework package list we deliver.
We will solve this asap.  As a work-around I've attache a zip file with the missing package.
If you unzip this and copy this to the C:\Program Files\JASP\R\library folder you'r problem will be solved.
[withr.zip](https://github.com/jasp-stats/jasp-issues/files/2791387/withr.zip)

Kind regards 
Frans Meerhoff

**Comment by FransMeerhoff** [comment]
This is solved in the new release 0.9.3
