### ISSUE TITLE
[Feature request]: Allow Mixed models to only estimate the random effects.

### ISSUE THREAD

**Issue by qymera0** [jasp-stats/jasp-issues#2780]
### Description

It would be interesting if we could specify a mixed model with only random effects. In Engineering and Industrial Statistics, this is a very common case, where you want to just estimate a process variance, but no systematic effect is present. 

### Purpose

Increase the flexibility of different model structures.

### Is your feature request related to a problem?

No

### Describe the solution you would like

Allow specify the models like this: y ~ 1 + (1 | z) 

### Describe alternatives that you have considered

I tried to manually change the formula at R console, but when I hit ctrl + enter, it gives me an error.

### Additional context

This case can be complementary of the feature request I did related to add nested random terms.

**Comment by FBartos** [comment]
Hi, this feature was recently added, and it will be in the upcoming release! 🎊

**Comment by qymera0** [comment]
Thank you so much! Your software is really fantastic!
