### ISSUE TITLE
[Bug]: lack of Polish translation - Correlation Matrix table - variable

### ISSUE THREAD

**Issue by iGrzegorz** [jasp-stats/jasp-issues#2783]
### JASP Version

0.18.3

### JASP Module

Regression

### What analysis are you seeing the problem on?

Correlation

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

in the correlation table, there is untranslated item "Variable" which should be translated in Polish to "zmienna"
![Zrzut ekranu 2024-06-17 o 17 44 02](https://github.com/jasp-stats/jasp-issues/assets/133985123/17156315-93c2-40c6-95d9-2fbe9d2fa41e)
olish to "zmienna"

### Expected Behaviour

see header in polish

### Steps to Reproduce

1.switch language to Polish
2.run correlation
3.throw any variables to get correlation matrix

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Did you try putting the translation in via weblate? I am from the german translation team so I am happy to explain the process if you have some minutes to spare. 
The translations are made possible by the community / volunteers in their free time!

Otherwise I could put in this one translation for you. 
However I would not be able to translate the other missing english to polish translations, since polish is only 63% translated atm and I do not speak polish at all! Sry!

**Comment by iGrzegorz** [comment]
Hey @tomtomme please put this one for me. I will be happy to help with at least some of the missing translations during holiday

**Comment by JohnnyDoorn** [comment]
Thanks @iGrzegorz and @tomtomme! There might have been an issue in the code, where this particular string was not labelled as a string that needs translation, which I've just fixed. Maybe it still needs the Polish translation though, so great if you could take a look =)

**Comment by tomtomme** [comment]
@JohnnyDoorn @iGrzegorz 
Did someone already put the translation into weblate? I cannot find a non-translated "Variable" in the regression module QML or R. Or does weblate need some more time to reflect the code change?

https://hosted.weblate.org/zen/jasp/jaspregression-r/pl/?offset=1&q=Variable&sort_by=-priority%2Cposition
https://hosted.weblate.org/zen/jasp/jaspregression-qml/pl/?offset=1&q=Variable&sort_by=-priority%2Cposition

**Comment by JohnnyDoorn** [comment]
I think it was already translated and I just needed to mark it as a translatable:
![image](https://github.com/jasp-stats/jasp-issues/assets/15704203/33f34da5-273d-42d9-9521-25d415f1ce32)
