### ISSUE TITLE
[Bug]: Using The Visual Modeling

### ISSUE THREAD

**Issue by helenum** [jasp-stats/jasp-issues#2784]
### JASP Version

0.18.3

### JASP Module

Visual Modeling

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

I have received this error message:
Error in dyn.load(file, DLLpath = DLLpath, ...): unable to load shared object '/Applications/JASP.app/Contents/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/dplyr/libs/dplyr.so':
  dlopen(/Applications/JASP.app/Contents/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/dplyr/libs/dplyr.so, 0x0006): Library not loaded: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libR.dylib
  Referenced from: <7E9BA906-F6A6-3212-A05E-D321043276A1> /Applications/JASP.app/Contents/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/dplyr/libs/dplyr.so
  Reason: tried: '/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libR.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libR.dylib' (no such file), '/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libR.dylib' (no such file), '/usr/lib/libR.dylib' (no such file, not in dyld cache)

### Expected Behaviour

Performing the visual modeling.

### Steps to Reproduce

1. Opening The Visual Modeling
2.
3.
..

### Log (if any)

Error in dyn.load(file, DLLpath = DLLpath, ...): unable to load shared object '/Applications/JASP.app/Contents/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/dplyr/libs/dplyr.so':
  dlopen(/Applications/JASP.app/Contents/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/dplyr/libs/dplyr.so, 0x0006): Library not loaded: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libR.dylib
  Referenced from: <7E9BA906-F6A6-3212-A05E-D321043276A1> /Applications/JASP.app/Contents/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/dplyr/libs/dplyr.so
  Reason: tried: '/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libR.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libR.dylib' (no such file), '/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libR.dylib' (no such file), '/usr/lib/libR.dylib' (no such file, not in dyld cache)

### Final Checklist

- [x] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by helenum** [comment]
I cannot upload the jasp file (it is in grey).
<img width="1820" alt="Captura de ecrã 2024-06-17, às 20 07 00" src="https://github.com/jasp-stats/jasp-issues/assets/46959367/ea5f66b0-76a6-4a46-bf00-49901880ccf9">

**Comment by helenum** [comment]
The csv file, however, is this: 
[AUC_DADOS_PARA_JASP.csv](https://github.com/user-attachments/files/15875880/AUC_DADOS_PARA_JASP.csv)

**Comment by dustinfife** [comment]
I can't reproduce that on my computer.

**Comment by boutinb** [comment]
Hi @helenum Which version of MacOS do you have? You can download your JASP file, by changing the suffix to .zip (test.jasp -> test.zip).

**Comment by tomtomme** [comment]
@helenum 
The CSV you provided does not contain "1_SPECIFICITY", just and empty V9 see

![grafik](https://github.com/jasp-stats/jasp-issues/assets/4428185/cc1ff44a-7c3c-42ca-ac0a-e7cdd4f0d954)

It does contain SPECIFICITY and that produces a nice graph.

![grafik](https://github.com/jasp-stats/jasp-issues/assets/4428185/c0eaba84-8b0a-44e7-b673-4d58e6197ff0)

So it is crucial to know what you have done to SPECIFICITY so that we can reproduce the bug. Please rename your .jasp to .zip and upload it here like boutinb described. Thx!

**Comment by tomtomme** [comment]
@helenum 
Any news on this one for us?
