### ISSUE TITLE
[Feature Request]: merge multiple contingency tables

### ISSUE THREAD

**Issue by Janek912** [jasp-stats/jasp-issues#2788]
### Description

Contingency tables feature now produces multiple table while selecting multiple rows and one column (2 tables per case - 1 for counts and one for p value)

### Use-case

Often contingency tables are used to test relationship of one outcome dependent on multiple variables. Interpretation of such results, as well as exporting the to one table is not efficient with multiple small tables as it is currently

### Is your feature request related to a JASP module?

Frequencies

### Describe the solution you would like

An option to merge all of the tables in one big vertical table consisting of all the rows and columns selected in the analysis, with the p value added in additional column

**Comment by tomtomme** [comment]
could you add a screenshot that shows in more detail what you are thinking of?
