### ISSUE TITLE
[Bug]: Variable Name with Japanese is truncated opening a ods file

### ISSUE THREAD

**Issue by momoldo** [jasp-stats/jasp-issues#2789]
### JASP Version

0.18.3

### JASP Module

Unrelated

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

I attempted this ods file to JASP.
![image](https://github.com/jasp-stats/jasp-issues/assets/37210369/be7cd41b-4e85-4862-975a-b3e034ca93db)

This is a result opend in JASP
![image](https://github.com/jasp-stats/jasp-issues/assets/37210369/99c122c4-dc98-4f55-86ed-d77d34a86319)

The name of the fifth variable consists five Kanji characters, but after opening in JASP, this consists three Kanji characters.
This situation don't happen when I open csv file.  It's not a serious problem, but kanji characters in a csv file sometimes happen another problem when it opened.

### Expected Behaviour

It is not serious.  If it is easy to repair, I need to repair the problem.

### Steps to Reproduce

I can't recognize what kanji character  happens this problem.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by shun2wang** [comment]
I didn't saw this problem,.@momoldo could you please share your .ods file and we will have a look?

**Comment by momoldo** [comment]
This file causes this problem...
[小売価格2020年6月.ods](https://github.com/user-attachments/files/15914486/2020.6.ods)

I'm checking if another ods file causes same problem.
This file "testfile.ods" is no problem.
[testfile.ods](https://github.com/user-attachments/files/15914735/testfile.ods)

Do this file "testfile2.ods" causes problem?
[testfile2.ods](https://github.com/user-attachments/files/15914758/testfile2.ods)

**Comment by shun2wang** [comment]
yeah, confirmed this is a importing ods problems, if rows names in `ruby-xxx` then we read them as names. because we read xml depth at `text:p`, seems libreOffice/MS-Office will drop them in `text:ruby-text`.

see:

```xml
<table:table-cell office:value-type="string" table:style-name="ce2">
    <text:p>
        <text:ruby text:style-name="ru1">
            <text:ruby-base>都市名</text:ruby-base>
            <text:ruby-text text:style-name="T5">トシメイ </text:ruby-text>
       </text:ruby>
    </text:p>
</table:table-cell>
```

**Comment by momoldo** [comment]
Thank you for your job!
I understood it.

**Comment by JorisGoosen** [comment]
<img width="612" alt="afbeelding" src="https://github.com/user-attachments/assets/5d19fc72-7d37-4fed-b3cc-c11fdb9beabe">

Is what I see when I open it in libre office on my system, where it doesnt even show anything in the headers?

**Comment by shun2wang** [comment]
It's OK for me on Linux/Window in LibreOffice:
![image](https://github.com/user-attachments/assets/cb16180b-f56e-4078-8822-f18dc970191d)

**Comment by JorisGoosen** [comment]
```
都市名 | マグロ | ジャガイモ | 喫茶店珈琲 | 民営家賃 | 水道料金
```

is what it gets loaded as on linux, looking like boxes...
Does ods have some weird encoding settings that we dont know about?

**Comment by JorisGoosen** [comment]
This issue might be solved by the PR https://github.com/jasp-stats/jasp-desktop/pull/5703 but there might be some strange issues with such characters in ods. Not sure whats up, but if it works on Shun and momoldo's systems I guess it works where it needs to.
