### ISSUE TITLE
Further Customization of Plots

### ISSUE THREAD

**Issue by wjames35** [jasp-stats/jasp-issues#279]
Enhancement: Allow users to edit numbers on the axes of descriptive plots (e.g., creating a graph with a true zero point), add labels to axes, and add more options for setting error bars (such as being able to set error bars to two standard errors from the mean). 
 
Purpose: My students perform analyses such as t-tests and ANOVAs in different courses and they would enjoy using the plots/graphs produced in JASP within their presentations and papers for classes outside of my own. However, other instructors have formatting requirements that the students cannot presently meet with JASP (e.g., having a zero point on a graph). Making these changes would permit the students to use JASP across more contexts. This would be very helpful to them. Thanks!

**Comment by EJWagenmakers** [comment]
Thanks for this request. We are well aware of the issue and are working hard to fix this in a comprehensive way. Because this is taking a little longer than anticipated we might add some select functionality earlier.

**Comment by dendrite75** [comment]
I have the same request. In the current context, it is not possible to ask my students to use JASP to represent their data with boxplot with Jitter. 
The graphs adjust their scale according to the data of each variable. 
Is there any other way to do it?

**Comment by juliusverrel** [comment]
This would be extremely useful. As an alternative (or temporary) solution, it would be useful to have an option to export mean and dispersion (SE, SD, CI, ...) as a table, for plotting in a different program.

**Comment by Brennan090** [comment]
I also have the exact same request.  Love the program but not being able to edit plots (axes values, lines, colors etc.) is making the use of these plots very limited.

**Comment by EJWagenmakers** [comment]
Definitely. We are well aware of this, and hope to present a complete solution this year.
Cheers,
E.J.

**Comment by andersolarsson** [comment]
Further editing possibilities for graphs would be extremely helpful for the classes I teach as well as for research - scale changes, adding and removing labels, customising colors et.c.

**Comment by EJWagenmakers** [comment]
In the next blog post we show how changing labels, fonts, colors etc can be handled through our new "save as pptx" feature. We are working on a more elegant solution that also allows scale changes.

**Comment by wjames35** [comment]
Thank you for keeping me posted! You all have done a wonderful service creating JASP! Best, Brian
________________________________
