### ISSUE TITLE
[Bug]: Error in diag(scales) %*% truevar: non-conformable arguments

### ISSUE THREAD

**Issue by hjmo63** [jasp-stats/jasp-issues#2791]
### JASP Version

0.18.3

### JASP Module

Factor

### What analysis are you seeing the problem on?

Comfirmatory Factor Analysis

### What OS are you seeing the problem on?

Windows 10

### Bug Description

This is text that appear in the error message (see the image attached):

****
This analysis terminated unexpectedly.
Error in diag(scales) %*% truevar: non-conformable arguments
Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])
doTryCatch(return(expr), name, parentenv, handler)
withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)
analysis(jaspResults = jaspResults, dataset = dataset, options = options)
.cfaTableReliability(jaspResults, options, cfaResult)
semTools::compRelSEM(cfaResult[['lav']], return.total = TRUE)
omegaCat(truevar = commonCov, denom = totalCov, threshold = threshold[[b]][myIndNames], scales = latScales[[b]][myIndNames])
To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports
****

The aim was to run a CFA. The curiosity about thist error is that it only occurs when the option "Reliability" under the section "Additional Output" was on!
The data file can be provided by private email on request, as the data is protected by confidentiality and informed consent.

### Expected Behaviour

The reliability figures were expected to be presented.

### Steps to Reproduce

1. In order to avoid the bug, the opion "Reliability" under the section "Additional Output" was disable.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment]
Hi thanks for the report. This is a know issue that is already reported here https://github.com/jasp-stats/jasp-issues/issues/2294. Unfortunately it is out of our hands. You can read more in the original issue.

**Comment by hjmo63** [comment]
Thank you!

Julius Pfadt ***@***.***> escreveu (terça, 25/06/2024 à(s)
14:32):
