### ISSUE TITLE
[Bug]: SEM-Error in diag(scales) %*% truevar: non-conformable arguments

### ISSUE THREAD

**Issue by AnhGian84** [jasp-stats/jasp-issues#2792]
### JASP Version

0.18.3

### JASP Module

SEM

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

Error in diag(scales) %*% truevar: non-conformable arguments

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.cfaTableReliability(jaspResults, options, cfaResult)

semTools::compRelSEM(cfaResult[['lav']], return.total = TRUE)

omegaCat(truevar = commonCov, denom = totalCov, threshold = threshold[[b]][myIndNames], scales = latScales[[b]][myIndNames])

### Expected Behaviour

Error in diag(scales) %*% truevar: non-conformable arguments

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.cfaTableReliability(jaspResults, options, cfaResult)

semTools::compRelSEM(cfaResult[['lav']], return.total = TRUE)

omegaCat(truevar = commonCov, denom = totalCov, threshold = threshold[[b]][myIndNames], scales = latScales[[b]][myIndNames])

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment]
Hi thanks for the report. This is a know issue that is already reported here https://github.com/jasp-stats/jasp-issues/issues/2294. Unfortunately it is out of our hands. You can read more in the original issue.
