### ISSUE TITLE
[Bug]: ROC for Naive Bayes Classification does not work

### ISSUE THREAD

**Issue by bayesfaqt** [jasp-stats/jasp-issues#2794]
### JASP Version

0.18.3

### JASP Module

Machine Learning

### What analysis are you seeing the problem on?

ROC Plot for Naive Bayes Classification

### What OS are you seeing the problem on?

Windows 11

### Bug Description

![Error - NBC-ROC](https://github.com/jasp-stats/jasp-issues/assets/173763312/a89d68d4-88f0-4a0c-9b10-d6d30ff17a46)

[Data - CLF - NBC - Gender Weights.csv](https://github.com/user-attachments/files/15965559/Data.-.CLF.-.NBC.-.Gender.Weights.csv)

### Expected Behaviour

I would like to test Naive Bayes classification on simple data: a nominal-scale target and a nominal-scaled feature. I get statistics for the classification, data split details and a confusion matrix. However, I get the error - a screenshot of which is attached - when I check ROC in the Plots option

### Steps to Reproduce

1. Read data (file attached)
2. Run  ML/NB within Classification
3. Drag Gender as Target
4. Drag Weight>75 as Feature
5. Check ROC curves under the Plots options
...

### Log (if any)

[JASP 2024-06-25 11_38_50 Engine 0.log](https://github.com/user-attachments/files/15965780/JASP.2024-06-25.11_38_50.Engine.0.log)
[JASP 2024-06-25 11_38_50 Desktop.log](https://github.com/user-attachments/files/15965781/JASP.2024-06-25.11_38_50.Desktop.log)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by koenderks** [comment]
The first thing I would advise you to do is to change the variable name 'weight < 75' to something that has only letters and no spaces. Something like 'lowWeight' or something. I think the '<' could cause a problem. Let me know if that works!

**Comment by bayesfaqt** [comment]
Hi! Thanks for your instant reply. Changing the features name to Weight, get the same problem

![image](https://github.com/jasp-stats/jasp-issues/assets/173763312/5b77ff77-ac8b-4958-a1b4-4d82482ebc52)

**Comment by tomtomme** [comment]
confirmed on flatpak 0.18.3 and 0.19beta

**Comment by koenderks** [comment]
Okay, thanks for trying. I is indeed a bug, it will be fixed in the next release. In the meantime, here is a screenshot of the ROC-curves for your data if you use 'Set seed: 1' in the training parameters section. Setting the seed ensures that we use the same training and testset. You should be able to replicate the numbers in the table using this seed, and then the ROC-curves match.

<img width="1481" alt="image" src="https://github.com/jasp-stats/jasp-issues/assets/25059399/321534dc-0032-4026-9066-ffc5687f3ba3">

If you need any more screenshots, don't hesitate to ask.

**Comment by bayesfaqt** [comment]
Thank you again for your prompt response

**Comment by bayesfaqt** [comment]
Great!
