### ISSUE TITLE
[Bug]: JASP do not open in MacBook Sonoma 14.4.1

### ISSUE THREAD

**Issue by dudsalva** [jasp-stats/jasp-issues#2797]
### JASP Version

0.18.3

### JASP Module

Unrelated

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

**When I try to download JASP, a window appears saying that it needed to be closed abruptly. I have tried updating my software, uninstalling, restarting my computer, and yes, I am the administrator of my Mac, but nothing works. When I type in the terminal to open the application, this is the response:** 

/Applications/JASP.app/Contents/MacOS/JASP --safeGraphics
Setting special options for software rendering (aka safe graphics).
Making new argument list for Application startup: /Applications/JASP.app/Contents/MacOS/JASP --safeGraphics --disable-gpu
Starting JASP 0.18.3 from commit 123cb32f4f0459196195787e819b249bfd8677aa and branch stable
QtWebEngineQuick initialized
The available OpenGL surface format was either not version 3.2 or higher or not a Core Profile.
Chromium on macOS will fall back to software rendering in this case.
Hardware acceleration and features such as WebGL will not be available.
Application initialized
Application init entered
MainWindow constructor started
TempFiles::createSessionDir(): '/Users/dudazsalvador/.JASP/temp/41440' about to be (removed and re)created.
Going to construct the necessary models for JASP to function.
Desktop: Checking qm file: /Applications/JASP.app/Contents/Resources/Translations/jaspDesktop-zh_Hans.qm
Desktop: Language (Chinese) not registered in LanguageModel, adding it now
Desktop: Checking qm file: /Applications/JASP.app/Contents/Resources/Translations/jaspDesktop-de.qm
Desktop: Language (German) not registered in LanguageModel, adding it now
Desktop: Checking qm file: /Applications/JASP.app/Contents/Resources/Translations/jaspDesktop-fr.qm
Desktop: Language (French) not registered in LanguageModel, adding it now
Desktop: Checking qm file: /Applications/JASP.app/Contents/Resources/Translations/jaspDesktop-nl.qm
Desktop: Language (Dutch) not registered in LanguageModel, adding it now
Desktop: Checking qm file: /Applications/JASP.app/Contents/Resources/Translations/jaspDesktop-es.qm
Desktop: Language (Spanish) not registered in LanguageModel, adding it now
Desktop: Checking qm file: /Applications/JASP.app/Contents/Resources/Translations/jaspDesktop-tr.qm
Desktop: Invalid translation file found with name: jaspDesktop-tr.qm
Desktop: Checking qm file: /Applications/JASP.app/Contents/Resources/Translations/jaspDesktop-eo.qm
Desktop: Invalid translation file found with name: jaspDesktop-eo.qm
Desktop: Checking qm file: /Applications/JASP.app/Contents/Resources/Translations/jaspDesktop-gl.qm
Desktop: Language (Galician) not registered in LanguageModel, adding it now
Desktop: Checking qm file: /Applications/JASP.app/Contents/Resources/Translations/jaspDesktop-pl.qm
Desktop: Language (Polish) not registered in LanguageModel, adding it now
Desktop: Checking qm file: /Applications/JASP.app/Contents/Resources/Translations/jaspDesktop-pt.qm
Desktop: Language (Portuguese) not registered in LanguageModel, adding it now
Desktop: Checking qm file: /Applications/JASP.app/Contents/Resources/Translations/jaspDesktop-ru.qm
Desktop: Language (Russian) not registered in LanguageModel, adding it now
Desktop: Checking qm file: /Applications/JASP.app/Contents/Resources/Translations/jaspDesktop-ja.qm
Desktop: Language (Japanese) not registered in LanguageModel, adding it now
Desktop: Checking qm file: /Applications/JASP.app/Contents/Resources/Translations/jaspDesktop-zh_Hant.qm
Desktop: Language (Chinese) not registered in LanguageModel, adding it now
Desktop: Checking qm file: /Applications/JASP.app/Contents/Resources/Translations/jaspDesktop-pt_BR.qm
Desktop: Invalid translation file found with name: jaspDesktop-pt_BR.qm
Desktop: Checking qm file: /Applications/JASP.app/Contents/Resources/Translations/jaspDesktop-id.qm
Desktop: Language (Indonesian) not registered in LanguageModel, adding it now
Desktop: Opened internal sqlite database for creation at '/Users/dudazsalvador/.JASP/temp/41440/internal.sqlite'.
Desktop: DataSet::DataSet(index=-1)
Desktop: UPDATE DataSet 1 with Empty Values: {
"emptyValuesPerColumn" : {},
"missingDataPerColumn" : {},
"workspaceEmptyValues" :
[
".",
"NA",
"NaN",
"nan"
]
}

Desktop: DataSetPackage::reset()
Desktop: DataSet::DataSet(index=-1)
Desktop: UPDATE DataSet 1 with Empty Values: {
"emptyValuesPerColumn" : {},
"missingDataPerColumn" : {},
"workspaceEmptyValues" :
[
".",
"NA",
"NaN",
"nan"
]
}

Desktop: UPDATE DataSet 1 with Empty Values: {
"emptyValuesPerColumn" : {},
"missingDataPerColumn" : {},
"workspaceEmptyValues" :
[
".",
"NA",
"NaN",
"nan"
]
}

Desktop: DataSetPackage::endLoadingData
Desktop: ColumnEncoder::setCurrentNames(#0)
Entering eventloop
2024-06-25 08:28:45.990 JASP[41440:2261991] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.
qt.qpa.fonts: Populating font family aliases took 52 ms. Replace uses of missing font family ".AppleSystemUIFontMonospaced" with one that exists to avoid this cost.
[41440:97027:0625/082846.639302:ERROR:validation_errors.cc(117)] Invalid message: VALIDATION_ERROR_DESERIALIZATION_FAILED
[41440:97027:0625/082846.639330:ERROR:interface_endpoint_client.cc(694)] Message 1861446869 rejected by interface network.mojom.NetworkService
[41440:97027:0625/082846.710884:FATAL:message_pump_kqueue.cc(387)] Check failed: . kevent64: Bad file descriptor (9)
zsh: trace trap /Applications/JASP.app/Contents/MacOS/JASP --safeGraphics
dudazsalvador@MacBook-Air-de-Eduarda-3 ~ % [41448:259:0625/082846.763846:ERROR:mach_port_rendezvous.cc(311)] bootstrap_look_up org.chromium.Chromium.MachPortRendezvousServer.1: Permission denied (1100)
[41447:259:0625/082846.763833:ERROR:mach_port_rendezvous.cc(311)] bootstrap_look_up org.chromium.Chromium.MachPortRendezvousServer.1: Permission denied (1100)
[41448:259:0625/082846.763864:ERROR:child_thread_impl.cc(226)] Mach rendezvous failed, terminating process (parent died?)
[41447:259:0625/082846.763919:ERROR:child_thread_impl.cc(226)] Mach rendezvous failed, terminating process (parent died?)
Loading required namespace: ragg

### Expected Behaviour

The app should have opened

### Steps to Reproduce

I just downloaded JASP, placed it in my Applications folder, and when I try to open it, this window appears.
![WhatsApp Image 2024-06-25 at 19 16 09](https://github.com/jasp-stats/jasp-issues/assets/85078492/a3f6e1cf-4347-4ba1-b68f-d802977418c8)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@dudsalva 
Thx for the report. What version of MacOS do you run? Current JASP supports versions 12 to 14.
Also: What happens if you click the repair button?
