### ISSUE TITLE
Multiple comparison in Bayesian ANOVA

### ISSUE THREAD

**Issue by fplatz** [jasp-stats/jasp-issues#28]
Hi! 

I wondered if it possible to include the option of specifying hypotheses within the Bayesian approach of ANOVA. I would like to perform a bf analysis for multiple comparisons ('(linear) contrast analysis').

Thanks a lot for this program! I like it really much!

**Comment by tomtomme** [comment]
@fplatz 
Closing, since this is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/2195
Please reopen, if you disagree.
