### ISSUE TITLE
Add option to see the comparison distribution with  sample score plotted upon it

### ISSUE THREAD

**Issue by wjames35** [jasp-stats/jasp-issues#280]
Enhancement: For significance tests (e.g., t-tests), please consider adding an option to see a visual depiction of the comparison distribution (e.g., t-distribution) with the sample score plotted upon it. 

Purpose: When teaching null hypothesis significance testing, it can be a challenge to connect the concepts of plotting a sample score on the null comparison distribution with the value of the p-value. In class you may do things like plotting the sample score on the comparison distribution (and seeing if the sample score exceeds the cutoff value derived from a table). In contrast, with software, one just looks directly at the p-value. This difference could be confusing for a student learning this material for the first time. Hence, this is an opportunity for JASP to bridge this gap.  Adding this enhancement will make JASP even better for teaching undergraduate statistics. Notably, JMP statistical software presently does this for analyses such as t-tests. (though JASP is still better for teaching undergrads than JMP in my view!). Thanks!

**Comment by EJWagenmakers** [comment]
This is a great suggestion, I think. 
@Kucharssim, @ASarafoglou let's discuss how this can perhaps fit in with our other plans

**Comment by tomtomme** [comment]
@wjames35 
We have the distribution module now, to show such graphs. However it could be nice to have those graphs in the t-Test / ANOVA etc. modules too. 

@Kucharssim 
Is this feasible? Its a lot of duplication. Or should we just point to the distribution module and close this one....
Maybe we could just embed a link say in the t-Test analysis window that brings you directly to the correct Distribution module and even syncs the necessary parameters... 

@boutinb 
Is it possible to start a moduel from within a module with a link?

**Comment by EJWagenmakers** [comment]
Also note the functionality in our new "Learn Stats" module that may be useful for teaching

**Comment by tomtomme** [comment]
Thx for the hint. I just have revisited the module. 

@wjames35 
Under "Learn Stats => p-values => t-distribution 
you get exactly what you want and even more :D
So I am closing this one for now.
Please reopen, if this is not sufficient for you!
