### ISSUE TITLE
[Feature Request]: show standardized residuals in Multinomial Test and in Contingency Tables (Descriptives table)

### ISSUE THREAD

**Issue by hugoquene** [jasp-stats/jasp-issues#2801]
### Description

standardized residuals in two tests of Frequency module

### Purpose

evaluate standardized residuals of categorical model

### Use-case

see example at https://hugoquene.github.io/QMS-EN/ch-chi-square-tests.html#jasp-15

### Is your feature request related to a problem?

see https://hugoquene.github.io/QMS-EN/ch-chi-square-tests.html#jasp-15

### Is your feature request related to a JASP module?

Frequencies

### Describe the solution you would like

obtain standardized residuals (available in R) as explained in https://hugoquene.github.io/QMS-EN/ch-chi-square-tests.html#r-17

### Additional context

see https://hugoquene.github.io/QMS-EN/ch-chi-square-tests.html#r-17 for the desired standardized residuals, it would be nice to obtain these (with their associated p values, based on standard normal distribution) in the Descriptives table of Frequencies > Multinomial (Classical) and Frequencies > Contingency (Classical).

**Comment by tomtomme** [comment]
@hugoquene 
thx for the request. 
So for contingency tables the book you cite seems a bit out of date. We have standardized Pearson residuals now in JASP, see:

![grafik](https://github.com/jasp-stats/jasp-issues/assets/4428185/7e886fa3-5d75-448c-9a36-cef69c6cdb4d)

Those were added in version 0.16.4 (3 October 2022), see https://jasp-stats.org/release-notes/

For the classical multinomial test you seem to be correct however. This is a valid request.

**Comment by tomtomme** [comment]
I have just added this request to a list of requests concerning the multinomial test here: https://github.com/jasp-stats/jasp-issues/issues/566

Thus we can close this one as a duplicate and discuss further details over there. 

@hugoquene 
Please reopen this issue if you disagree.
