### ISSUE TITLE
[Bug]: Time Series Analysis Stationarity transformation 

### ISSUE THREAD

**Issue by wooyoung32** [jasp-stats/jasp-issues#2804]
### JASP Version

0.18.3

### JASP Module

Time Series

### What analysis are you seeing the problem on?

Transformation under stationarity 

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

I've noticed that when I perform data transformation, I get identical results using the methods "Detrend using linear regression + Log" and "Detrend using linear regression". Initially, I thought this might be due to the "Detrend using linear regression" step generating negative data values, causing the "Log" step not to work.  To check if the problem was the negative value of the data, I ran using "Difference"(which also produces negative values) instead of "Detrend using linear regression". However, the "Difference + Log" and "Difference" produced different results.

### Expected Behaviour

Results from "Detrend using linear regression + Log" and "Detrend using linear regression" should differ.

### Steps to Reproduce

1. Do "Detrend using linear regression + Log" transformation
2. Do "Detrend using linear regression" transformation
3. Compare the results
[Pennsylvania monthly offences data_2013.csv](https://github.com/user-attachments/files/16059230/Pennsylvania.monthly.offences.data_2013.csv)

...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@sophieberkhout 
Can you help out here?
I can confirm this even for current 0.19 beta:
![grafik](https://github.com/jasp-stats/jasp-issues/assets/4428185/a629d5f4-857a-4b1b-907b-ecb68372a4e1)

**Comment by sophieberkhout** [comment]
I believe I have found the problem and will be able to fix it soon.

**Comment by tomtomme** [comment]
still valid for 0.19.2 beta flatpak

@sophieberkhout 
any update on this one?

jasp file to test:
[Pennsylvania.monthly.offences.data_2013x.jasp.zip](https://github.com/user-attachments/files/17492787/Pennsylvania.monthly.offences.data_2013x.jasp.zip)
