### ISSUE TITLE
[Feature Request]: Black + also for "Edit Data" mode

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#2805]
### Description

Currently the black + button is only available in "Analysis" Mode

### Purpose

Consistency. All data editing features should be available in "Data Edit" mode

### Use-case

faster adding new variables

### Is your feature request related to a problem?

Users search for the black + button in "Edit Data" mode and cannot find it.

### Is your feature request related to a JASP module?

Unrelated

### Describe the solution you would like

see title

### Describe alternatives that you have considered

Add new vars via the "Insert" button while in "Edit Data" mode, but that feels slower because you have to choose from several options.

### Additional context

![image](https://github.com/jasp-stats/jasp-issues/assets/4428185/0d7eae96-a8de-4c46-9138-1ef3055305d4)

**Comment by boutinb** [comment]
This is a function that existed before Data Editing, but now in Edit mode, this function would be quite strange. Where to add it, since you can just click on the header of an empty column to add a (computed) column.

**Comment by tomtomme** [comment]
Interesting. I was not even aware of that possibility. This double clicking is an invisible feature. And that is why I like the expliciteness of the black +. And every student I know, who got to know the black + searches for it in "edit data" mode without success.

So I see some options:
a) Make it more visible that there is the possibility of double-clicking for a new variable within "edit data" mode. For example every empty column header could contain a  +. Mockups below.
b) put the black + also in "edit data" mode
c) put the black + only in "edit data" mode, where it kind of belongs
d) nuking the black + alltogether

Atm a) seems the best to me, but my mockups do not look quite right yet:
![xx](https://github.com/jasp-stats/jasp-issues/assets/4428185/fb792322-85fa-45bd-89a1-84f44aee554c)
![x](https://github.com/jasp-stats/jasp-issues/assets/4428185/54200a10-3283-48c3-8466-f76d7fc6dcfd)

**Comment by EJWagenmakers** [comment]
The explicit x seems a good idea to me.

**Comment by boutinb** [comment]
I would vote for the green + in  Edit Mode, seems to me more intuitive. 
Since we have now an Edit mode, I wanted to remove the back + in Analysis mode: adding a column seems to me an Edit function. But I was told that people would miss this functionality.
