### ISSUE TITLE
[Bug]: warning/error message "Get an app to open this 'ms-gamingoverlay' link"

### ISSUE THREAD

**Issue by PeterKlaren** [jasp-stats/jasp-issues#2812]
### JASP Version

0.18.3

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 11

### Bug Description

The pop-up message "Get an app to open this 'ms-gamingoverlay' link" already appears at start-up.

### Expected Behaviour

No warning/error message. JASP seems to run fine upon ignoring this.

### Steps to Reproduce

1. Double-click the JASP 0.18.3 desktop icon (linking to "C:\Program Files (x86)\JASP\JASP.exe").
2.
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by PeterKlaren** [comment]
![image](https://github.com/jasp-stats/jasp-issues/assets/43278770/84cc23b3-f6fa-4b94-b922-7ccb14a65b3f)

**Comment by EJWagenmakers** [comment]
I thought we had fixed this long ago...

**Comment by shun2wang** [comment]
> I thought we had fixed this long ago...

I  just fixed it in .msi installer but this may installed with the Microsoft store?

for Microsoft store we have another fix https://github.com/jasp-stats/jasp-desktop/pull/5409 but.not merge it now. so maybe @RensDofferhoff should do it while build for MSIX.

**Comment by RensDofferhoff** [comment]
@shun2wang  C:\Program Files (x86)\JASP\JASP.exe is the msi for sure. 
Windows store has a different path

**Comment by shun2wang** [comment]
so the fix not in 0.18.3 then it should be included in 0.19.

**Comment by shun2wang** [comment]
I can confirm it will be fixed in the next release of 0.19.

duplicated with https://github.com/jasp-stats/jasp-issues/issues/2479
