### ISSUE TITLE
[Bug]: Save Machine learning model

### ISSUE THREAD

**Issue by thomask712001** [jasp-stats/jasp-issues#2819]
### JASP Version

0.18.3

### JASP Module

Machine Learning

### What analysis are you seeing the problem on?

ML Random Forest

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

Always get this error when I try to save a trained model. I have the same problem in, as far as I can tell, all Machine Learning Regression and Classification modules.

This analysis terminated unexpectedly.

Error in str2lang(x): :1:150: unexpected input
1: KSS ~ sex + ALSFRS.Bulbar + ALSFRS.Fine.Motor + ALSFRS.Gross.Motor + sprak.benamna + sprakfoerstaelse + minne.direkt.hagkomst + sprak.rattstavning + 6.ex
                                                                                                                                                         ^

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.mlRegressionTableSummary(dataset, options, jaspResults, ready, position = 1, type = 'knn')

.decodeJaspMLobject(model)

.decodeJaspMLobject.kknn(model)

formula(paste(decodeColNames(as.character(model$terms)[2]), '~', paste0(decodeColNames(strsplit(as.character(model$terms)[3], split = ' + ', fixed = TRUE)[[1]]), collapse = ' + ')))

formula.character(paste(decodeColNames(as.character(model$terms)[2]), '~', paste0(decodeColNames(strsplit(as.character(model$terms)[3], split = ' + ', fixed = TRUE)[[1]]), collapse = ' + ')))

str2lang(x)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

### Expected Behaviour

Model file should have been created.

### Steps to Reproduce

1.
2.
3.
...
After having generated clusters/groupings, I try to save the model. JASP refuses. I have tried different ML procedures. I have also tried to save the model at various locations. Won't make any difference. 

### Log (if any)

[JASP 2024-07-08 15_31_29 Desktop.log](https://github.com/user-attachments/files/16130412/JASP.2024-07-08.15_31_29.Desktop.log)

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by koenderks** [comment]
Please try to remove all dots (".") and numbers from the variable names first and then try again. If that still does not work, please post a screenshot if possible.

Koen

**Comment by thomask712001** [comment]
Many thanks. I will try again later.

/Thomas

**Comment by thomask712001** [comment]
It worked! Thanks for your help!
