### ISSUE TITLE
Instructions on how to install on Ubuntu trusty

### ISSUE THREAD

**Issue by probonopd** [jasp-stats/jasp-issues#282]
* Enhancement: Instructions on how to install on Ubuntu trusty.
* Purpose: Looking for instructions on how to install on Ubuntu trusty.
* Use-case: Ubuntu trusty is the oldest currently still-supported LTS release of Ubuntu.

**Is your feature request related to a problem? Please describe.**
Some users still use Ubuntu trusty and cannot update to newer distributions. Ubuntu trusty is the oldest currently still-supported LTS release of Ubuntu.

**Describe the solution you'd like**
A clear and concise description of ow to install on Ubuntu trusty.

**Describe alternatives you've considered**
Update to newer distribution, not possible on some lab machines.

**Additional context**
Please always target the _oldest still-supported_ rather than the _newest_ LTS release.

**Comment by boutinb** [comment]
@FransMeerhoff Kun je antwoorden?

**Comment by FransMeerhoff** [comment]
Hi @probonopd 

Did you miss the instructions on https://jasp-stats.org/linux-installation-guide/  or do you have problems with these instructions?

**Comment by probonopd** [comment]
Hi @FransMeerhoff, the page does not describe how to install on Ubuntu trusty. I see only Bionic which is newer than the oldest still-supported Ubuntu LTS release.

**Comment by FransMeerhoff** [comment]
HI @probonopd 

I agree. But as the documentation states Installation under Ubuntu 18.04 (Bionic Beaver) can ALSO be handled through a PPA. However for the Ubuntu trusty version the flatpak installation should work. Did you try the flatpak installation? Moreover the end of life date of the trusty version is april 2019. 

Kind regards 
Frans Meerhoff

**Comment by probonopd** [comment]
Thanks @FransMeerhoff. I am interested in AppImages that run on all still-supported releases of Ubuntu. Looking forward to April 2019 then ;-)

**Comment by FransMeerhoff** [comment]
Hello @probonopd 
We will update the Ubuntu version state on April 2019 and close this issue for now.

Kind regards
Frans Meerhoff
