### ISSUE TITLE
[Feature Request]: Problem loading

### ISSUE THREAD

**Issue by purnama30** [jasp-stats/jasp-issues#2820]
### Additional context

![Screenshot_2](https://github.com/jasp-stats/jasp-issues/assets/175080959/1cf77dd6-0a68-4700-900b-c1a4b625e690)

**Comment by purnama30** [comment]
thankyou for your information and response,,,, i will try to update JASP

**Comment by tomtomme** [comment]
@purnama30 
any news for us?
