### ISSUE TITLE
[Bug]: certificate for MSIX nightlies does not appear to be available (404)

### ISSUE THREAD

**Issue by TarandeepKang** [jasp-stats/jasp-issues#2824]
### JASP Version

Others (0.19)

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 11

### Bug Description

MSIX nightlies cannot be downloaded because the certificate is not available from https://static.jasp-stats.org/JASPSelfSignCert.cer and the page gives a 404 error. MSI can be downloaded without error.

### Expected Behaviour

Certificate should be available?

### Steps to Reproduce

1.
2.
3.
...
as above

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by RensDofferhoff** [comment]
Apologies, this is fixed now
