### ISSUE TITLE
[Bug]: CFA isn't running

### ISSUE THREAD

**Issue by farisakeumala** [jasp-stats/jasp-issues#2827]
### JASP Version

0.19.0

### JASP Module

Factor

### What analysis are you seeing the problem on?

Confirmatory Factor Analysis

### What OS are you seeing the problem on?

Windows 11

### Bug Description

It is said that "waiting for module engine to initialize" when i was done with putting the factors in

### Expected Behaviour

The CFA is running

### Steps to Reproduce

1. Click on Factor menu
2. Choose CFA
3. Input Factor 1, 2, and 3
4. Wait for it to run

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@farisakeumala 
thx for the report.
I cannot reproduce this error with 0.19 flatpak (sorry I cannot test on win11).
However from my experience I suspect that 

- [ ]  restarting the PC or
- [ ]  updating win11 or
- [ ]  axing and re-adding the analysis

might already solve the issue.

If not - can you share your .jasp file by renaming it to .zip and drag and drop it here?
Thx!

**Comment by boutinb** [comment]
It works also on Mac and Windows 10. @RensDofferhoff do you have a Windows 11?

**Comment by RensDofferhoff** [comment]
I cannot reproduce this on windows 11. Perhaps a reboot to check if it reoccurs like @tomtomme  suggested
