### ISSUE TITLE
[Bug]: Cant conduct Cronbach's alpha analysis in JASP

### ISSUE THREAD

**Issue by AmitUzan** [jasp-stats/jasp-issues#2828]
### JASP Version

0.18.3

### JASP Module

Reliability

### What analysis are you seeing the problem on?

Cronbach's alpha

### What OS are you seeing the problem on?

Windows 11

### Bug Description

[Bug]: I'm  trying to perform a reliability analysis (Cronbach's alpha) in JASP, but I'm unable to move my columns to the variables section to conduct the analysis.

### Expected Behaviour

shoukd have been able to move the Cols
![Screenshot 2024-07-17 120738](https://github.com/user-attachments/assets/78a37ab0-893e-4171-bc23-ea1a92b83355)

### Steps to Reproduce

1.cant move columns to variables side
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by EJWagenmakers** [comment]
The column headers are inside the spreadsheet -- so the first row does not contain data, but text; this means that JASP will classify the columns as text, and these cannot be analysed. If you read in the data such that the headers are the column names (and not in the spreadsheet itself) it will work.
