### ISSUE TITLE
[Bug]: Error in chi-squared continuity correction

### ISSUE THREAD

**Issue by PeterKlaren** [jasp-stats/jasp-issues#2829]
### JASP Version

0.18.3

### JASP Module

Frequencies

### What analysis are you seeing the problem on?

Contingency Tables

### What OS are you seeing the problem on?

Windows 11

### Bug Description

Analysing a 3x2 table, calculated chi-squared and chi-squared with continuity correction, the test statistic's value (and, hence, p-value) are exactly the same.
The continuity correction is a conservative one and should yield a smaller test statistic.

### Expected Behaviour

See the data set in the preview. Chi-squared is correctly calculated to be 10.896. My calculation says that the continuity correction should give a chi-squared value of 8.535 (df = 2, p = 0.014).
![image](https://github.com/user-attachments/assets/8b1b0d54-013e-4ee5-9cb4-ef60ff87b79b)

### Steps to Reproduce

1. Load csv dataset in JASP;
2. Select Frequencies module, then Contingency Tables;
3. Select categorical variables in Rows and Columns, counts in Counts;
4. In Statistics pulldown, select "chi-squared" and "chi-squared continuity correction".
...

### Log (if any)

[marriageTherapy.zip](https://github.com/user-attachments/files/16267363/marriageTherapy.zip)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Confirmed!
Also for different data sets! But only if the "Counts" field is used. If I use raw data via "Rows" and "Columns" then the correction seems to work!

@FBartos 
Can you also confirm?

**Comment by tomtomme** [comment]
@FBartos 
still valid for 0.19.2 beta flatpak

file is attached in report above

**Comment by FBartos** [comment]
Hi @PeterKlaren , could you please let me know what formula/function do you use for the correction computation? I just checked the R-documentation of the `chisq.test` function, and it states that the correction is applicable only for 2x2 tables. 

We clearly need to add a footnote to the table stating this, but maybe there is an alternative function for calculating the correction.

Cheers,
Frantisek

**Comment by PeterKlaren** [comment]
Hi Frantisek,

I use Yates continuity correction (subtracting 0.5 from the absolute value |O - E|) that indeed only is valid for 2x2 tables.

Kind regards,

Peter
________________________________
