### ISSUE TITLE
[Bug]: Flexplot image editing does not work

### ISSUE THREAD

**Issue by bmatyasb** [jasp-stats/jasp-issues#2833]
### JASP Version

0.19.0

### JASP Module

Descriptives

### What analysis are you seeing the problem on?

Flexplot

### What OS are you seeing the problem on?

Windows 11

### Bug Description

When editing the generated flexplot, an error message is displayed when setting the axis limits. This is not consistent, sometimes it comes up, sometimes not. But if it comes up, you cannot edit the plot any further. I don't know if this is the case with other plots. The flexplot in Visual Modelling didn't have the problem after repeated attempts, only the Descriptive Statistics flexplot.
![image](https://github.com/user-attachments/assets/74cb0c90-a677-425f-ae52-c19e46b59b1d)

### Expected Behaviour

Simply set the axis limits.

### Steps to Reproduce

loading iris data
create flexplot, (y = Sepal.Length, Petal.Width) 
click on image edit
change the limits of the x or y axis

### Log (if any)

[JASP 2024-07-19 07_33_42 Engine 0.log](https://github.com/user-attachments/files/16302755/JASP.2024-07-19.07_33_42.Engine.0.log)
[JASP 2024-07-19 07_33_42 Desktop.log](https://github.com/user-attachments/files/16302756/JASP.2024-07-19.07_33_42.Desktop.log)
[JASP 2024-07-19 07_33_42 Engine 1.log](https://github.com/user-attachments/files/16302757/JASP.2024-07-19.07_33_42.Engine.1.log)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@bmatyasb 
thx for the report! Can you share the .jasp file by renaming to .zip and drag and dropping it here? Or is the iris data part of the data lib?
thx

**Comment by bmatyasb** [comment]
Yes, it is part of the data lib.

Thomas Langkamp ***@***.***> ezt írta (időpont: 2024. júl.
25., Cs 13:35):

**Comment by tomtomme** [comment]
Where can I find it exactly?

**Comment by tomtomme** [comment]
I really cannot find a data file called iris in the data library. Also the documentation of the data library does not mention a variable "petal.width"

**Comment by bmatyasb** [comment]
In the software it is in the machine learning library, called iris. I'm not
on the computer at the moment, but I'll do a print screen soon.

Thomas Langkamp ***@***.***> ezt írta (időpont: 2024. júl.
26., P 18:38):

**Comment by tomtomme** [comment]
got it, thx!
If I choose the marked options it works.
![grafik](https://github.com/user-attachments/assets/5fab580a-b1be-41f6-bf57-b958f7212057)

Choosing "based on data" and setting y to start from 1 does have no effect at all for me. I also do not get an error message. Maybe this is a Win 11 error (I am on linux flatpak).

@boutinb or @dustinfife 
Can you test changing the y-axis for on Win 10 or 11 to confirm the error? 
File here: 
[iris.zip](https://github.com/user-attachments/files/16394794/iris.zip)

**Comment by mlotinga** [comment]
I've also experienced exactly the same error for flexplot in JASP 0.19.0 on Windows 11.

It worked fine in 0.18.3.

**Comment by mlotinga** [comment]
I reinstalled JASP 0.18.3.0 followed by reinstalling JASP 0.19.0.0 and now the issue seems to have gone away for me. Weird.

**Comment by tomtomme** [comment]
@mlotinga 
Strange. Maybe there were old config-files or cache-files somewhere that lead to this?

@bmatyasb
maybe you could also go that route of reinstalling 0.18.3 and then reinstalling 0.19 to see if this helps you too? Or even installing via windows store instead of the msi-installer from our homepage?

**Comment by tomtomme** [comment]
@mlotinga I retested this with newest 0.95.2 and all works fine now.
