### ISSUE TITLE
[Bug]: This analysis terminated unexpectedly.  Error in X[ii, ii, drop = FALSE] %*% y[ii]: non-conformable arguments 

### ISSUE THREAD

**Issue by ykim47** [jasp-stats/jasp-issues#2834]
### JASP Version

0.18.3

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

Repeated Model Anova

### What OS are you seeing the problem on?

Windows 11

### Bug Description

When I select the post-hoc tests and select the tab, 
![post hoc test ](https://github.com/user-attachments/assets/6fc0d1e8-c600-4565-b3ae-625ffea2a7ec)

This analysis terminated unexpectedly.

Error in X[ii, ii, drop = FALSE] %*% y[ii]: non-conformable arguments

Stack trace
analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.rmAnovaPostHocTable(rmAnovaContainer, dataset, longData, options, ready)

as.data.frame(emmeans::eff_size(referenceGrid[[var]], sigma = sqrt(mean(sigma(fullModel$lm)^2)), edf = df.residual(fullModel$lm), level = bonfAdjustCIlevel))

emmeans::eff_size(referenceGrid[[var]], sigma = sqrt(mean(sigma(fullModel$lm)^2)), edf = df.residual(fullModel$lm), level = bonfAdjustCIlevel)

regrid(con, transform = 'response')

.est.se.df(object, do.se = TRUE)

t(apply(object@linfct[use.elts, , drop = FALSE], 1, function(x) {
    if (!any(is.na(x)) && estimability::is.estble(x, object@nbasis, tol)) {
        x = x[active]
        est = sum(bhat * x)
        if (do.se) {
            se = sqrt(.qf.non0(object@V, x))
            df = object@dffun(x, object@dfargs)
        }
        else se = df = 0
        c(est, se, df)
    }
    else c(NA, NA, NA)
}))

apply(object@linfct[use.elts, , drop = FALSE], 1, function(x) {
    if (!any(is.na(x)) && estimability::is.estble(x, object@nbasis, tol)) {
        x = x[active]
        est = sum(bhat * x)
        if (do.se) {
            se = sqrt(.qf.non0(object@V, x))
            df = object@dffun(x, object@dfargs)
        }
        else se = df = 0
        c(est, se, df)
    }
    else c(NA, NA, NA)
})

FUN(newX[, i], ...)

.qf.non0(object@V, x)

such error appears. 

### Expected Behaviour

could you please tell me instructions to fix the error?

### Steps to Reproduce

1.  Everything is fine before I click on the post hoc test.
2. Error appeared when I moved the last tab (Questions*Length) to the right section.
3.
...
![post hoc test ](https://github.com/user-attachments/assets/b5063250-14df-4c70-a714-cc91fbbd9a44)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@ykim47 
thx for the report! Can you share the .jasp file by renaming to .zip and drag and dropping it here? 
I cannot reproduce this with data from the data library.
thx
