### ISSUE TITLE
Rasch Model

### ISSUE THREAD

**Issue by 1417chandrayp** [jasp-stats/jasp-issues#2835]
### Purpose

Item analysis for cognitive test

**Comment by tomtomme** [comment]
@1417chandrayp 
Thx for the request! This seems to be a duplicate of https://github.com/jasp-stats/jasp-issues/issues/160
Do you agree?
If so, we should close this one and discuss Rasch and other IRT models over there.

**Comment by tomtomme** [comment]
@1417chandrayp this is now available as a community module in jasps module store :)
