### ISSUE TITLE
[Bug]: Multinomial Analisys 

### ISSUE THREAD

**Issue by casanovacruz** [jasp-stats/jasp-issues#2844]
### JASP Version

0.18.3

### JASP Module

Frequencies

### What analysis are you seeing the problem on?

Multinomial 

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

Se adjunta bug

### Expected Behaviour

Error in `[<-.data.frame`(`*tmp*`, seq_along(factLevelOrder), , value = structure(list(: replacement element 1 has 5 rows, need 6

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.multinomReadData(dataset, options)

`[<-`(`*tmp*`, seq_along(factLevelOrder), , value = list(Recuento de mrun = c(815, 1706, 2124, 1224, 610), Grupo = 1:5))

`[<-.data.frame`(`*tmp*`, seq_along(factLevelOrder), , value = list(Recuento de mrun = c(815, 1706, 2124, 1224, 610), Grupo = 1:5))

stop(sprintf(ngettext(N, 'replacement element %d has %d row, need %d', 'replacement element %d has %d rows, need %d'), k, N, n), domain = NA)

### Steps to Reproduce

1. Análisis multinomial
2.
3.
...

### Log (if any)

Error in `[<-.data.frame`(`*tmp*`, seq_along(factLevelOrder), , value = structure(list(: replacement element 1 has 5 rows, need 6

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.multinomReadData(dataset, options)

`[<-`(`*tmp*`, seq_along(factLevelOrder), , value = list(Recuento de mrun = c(815, 1706, 2124, 1224, 610), Grupo = 1:5))

`[<-.data.frame`(`*tmp*`, seq_along(factLevelOrder), , value = list(Recuento de mrun = c(815, 1706, 2124, 1224, 610), Grupo = 1:5))

stop(sprintf(ngettext(N, 'replacement element %d has %d row, need %d', 'replacement element %d has %d rows, need %d'), k, N, n), domain = NA)
![Captura de pantalla 2024-07-24 a la(s) 22 22 34](https://github.com/user-attachments/assets/8f822463-b1d2-4717-98ce-a7f0d077fdb7)

### More Debug Information

Error in `[<-.data.frame`(`*tmp*`, seq_along(factLevelOrder), , value = structure(list(: replacement element 1 has 5 rows, need 6

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.multinomReadData(dataset, options)

`[<-`(`*tmp*`, seq_along(factLevelOrder), , value = list(Recuento de mrun = c(815, 1706, 2124, 1224, 610), Grupo = 1:5))

`[<-.data.frame`(`*tmp*`, seq_along(factLevelOrder), , value = list(Recuento de mrun = c(815, 1706, 2124, 1224, 610), Grupo = 1:5))

stop(sprintf(ngettext(N, 'replacement element %d has %d row, need %d', 'replacement element %d has %d rows, need %d'), k, N, n), domain = NA)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@casanovacruz 
thx for the report! Can you share the .jasp file by renaming to .zip and drag and dropping it here? 
I cannot reproduce the error with data from the data library.
thx

**Comment by tomtomme** [comment]
I checked with 0.19 and the data library file and your settings. I cannot reproduce the error with that data file. 
I will have to close this one for now.
Feel free to reopen, if you see the error with jasp 0.19 still and if you can share your data as described above.
