### ISSUE TITLE
This analysis terminated unexpectedly[Bug]: 

### ISSUE THREAD

**Issue by IAMTrish** [jasp-stats/jasp-issues#2848]
### JASP Version

0.19.0

### JASP Module

Descriptives

### What analysis are you seeing the problem on?

Q-Q plot

### What OS are you seeing the problem on?

Windows 11

### Bug Description

This analysis terminated unexpectedly.

Error in quantile.default(varCol, probs = c(0.25, 0.75)): (unordered) factors are not allowed

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.descriptivesQQPlot(dataset = dataset, options = options, qqvar = var)

stats::quantile(varCol, probs = c(0.25, 0.75))

quantile.default(varCol, probs = c(0.25, 0.75))

stop('(unordered) factors are not allowed')

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

### Expected Behaviour

A copy of Q-Q plots

### Steps to Reproduce

1. Added data to a table
2. Added my independent variables to the Variable box
3. Went into Basic Plot menu
4. Clicked Q-Q plots
...

### More Debug Information

This analysis terminated unexpectedly.

Error in quantile.default(varCol, probs = c(0.25, 0.75)): (unordered) factors are not allowed

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.descriptivesQQPlot(dataset = dataset, options = options, qqvar = var)

stats::quantile(varCol, probs = c(0.25, 0.75))

quantile.default(varCol, probs = c(0.25, 0.75))

stop('(unordered) factors are not allowed')

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports
![Screenshot 2024-07-26 110707](https://github.com/user-attachments/assets/43e9076f-26bf-4cff-bf61-677bde43209e)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@IAMTrish
I cannot replicate the error with my data. Can you share your data file by renaming .jasp to .zip and drag and drop it here?
thx
