### ISSUE TITLE
[Bug]: Error in one-sample t-test

### ISSUE THREAD

**Issue by Alejandro-84** [jasp-stats/jasp-issues#2851]
### JASP Version

0.19.0

### JASP Module

T-Tests

### What analysis are you seeing the problem on?

One sample t-test

### What OS are you seeing the problem on?

Windows 11

### Bug Description

When I was using the one-sample t-test, I checked the boxes to get both the z-test and t-test at once, no problem here. 
![image](https://github.com/user-attachments/assets/539abbc7-31f4-4750-8aea-d7accd9cf58e)

However, when I checked the box for the Location estimate, a warning box popped up 
![image](https://github.com/user-attachments/assets/ec5806bc-9ffe-4ec6-ad17-08c2ca6a57bb)

This warning disappears if I add the Wilcoxon signed rank test (i.e., the three tests at once)
![image](https://github.com/user-attachments/assets/25ae3c69-472b-46e8-b27a-45f12c2fa3c7)

### Expected Behaviour

No warning should appear and the test results should be displayed without the necessity of including the Wilcoxon signed rank test.

### Steps to Reproduce

1. Open the T-Tests module and select the one-sample t-test under the Classical analysis
2. Select the variable you want (I used the "Sleep" dataset included in the Descriptives library).
3. Check the boxes for the Student and Z Test, then check the box for the Location estimate (the warning should appear).
4. Check the box for the Wilcoxon signed-rank test, and the warning should disappear.
...

### More Debug Information

-------- Application Info --------
JASP Version: JASP 0.19
Build Branch: development
Build Date: Jul 13 2024 09:52:18 (Netherlands)
Last Commit: 8b929b98f058f23dd8c8cf3e891be5a77b2ebc0b

-------- Basic Info --------
Operating System: Windows 11 Version 23H2
Product Version: 11
Kernel Type: winnt
Kernel Version: 10.0.22631
Architecture: x86_64
Install Path: C:/Program Files (x86)/JASP
Platfotm Name: windows
System Local: en_CA

-------- Extra Info --------
Current code page
Active code page: 437
Active code page: 65001

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Confirmed with 0.19 flatpak.
Renamed file with error: 
[Sleep.jasp.zip](https://github.com/user-attachments/files/16834997/Sleep.jasp.zip)

**Comment by tomtomme** [comment]
Still there with 0.19.1

**Comment by boutinb** [comment]
I cannot reproduce this in the last nightly build.

**Comment by tomtomme** [comment]
This was fixed in the meantime also on my end.
