### ISSUE TITLE
[Bug]: filter being ignored in 0.19

### ISSUE THREAD

**Issue by jasonckchan** [jasp-stats/jasp-issues#2853]
### JASP Version

0.19.0

### JASP Module

T-Tests

### What analysis are you seeing the problem on?

independent samples t-test

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

When attempting to do an independent samples t-test (either NHST or Bayesian), JASP pops up an error message of "maximum number of levels is 2. Variable Cdn has 4 levels."  This happens despite the fact that I've used filter to limit the number of levels in the Cdn variable to just two things. This is a new issue that did not occur in 0.18.3.

The issue does not appear to affect ANOVA, however.

### Expected Behaviour

Please see above

### Steps to Reproduce

1. Choose independent samples t-test
2. insert DV
3. insert grouping IV with more than two levels (it doesn't matter if I filter the data before or after starting the analysis)
![Filter](https://github.com/user-attachments/assets/1efc541a-d8d7-4303-bcdf-d4f6305f5fdc)
![Error](https://github.com/user-attachments/assets/a4106d04-74ce-43f1-afdd-6a6dd3d343ba)

4. Get error message
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
This is solved in https://github.com/jasp-stats/jasp-desktop/pull/5645
We should definitely release a new version for this bug.
