### ISSUE TITLE
No Print Button option

### ISSUE THREAD

**Issue by TAPSCEO** [jasp-stats/jasp-issues#2855]
### JASP Version

0.19.0

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

All modules

### What OS are you seeing the problem on?

Windows 11

### Bug Description

I am not able to print my work for my senior thesis. WHen I try to export data it simply reopens the file in the JASP app. There is no print option and I ned to show my work. Copy and paste is not enough and the copy and paste to flexplot and other bar graphs does not copy and paste to google docs. Please address this issue ASAP

### Expected Behaviour

A PRINT BUTTON SHOULD BE EASILY ACCESSIBLE

### Steps to Reproduce

1.CREATE A NEW DATA SET
2.ANALYZE IT
3.TRY TO PRINT IT
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by EJWagenmakers** [comment]
Have you tried "Export Results" and then select either html or pdf? Then you can issue a print command from the html or pdf viewer.

**Comment by tomtomme** [comment]
Also:
You can copy paste results to a locally instaaled program like word or libreoffice writer. Then you can upload that to google docs. Sadly it is not possible to directly copypaste to a browser window. But that is why you can export to html all at once, open that in a browser and copy paste from there to google docs.
Also you could upload such a html file to OSF.io and just put a link into your thesis pointing there.
