### ISSUE TITLE
[Bug]: Process (beta) module. This analysis terminated unexpectedly

### ISSUE THREAD

**Issue by Tendall98** [jasp-stats/jasp-issues#2856]
### JASP Version

0.19.0

### JASP Module

Process

### What analysis are you seeing the problem on?

Classical Process Model

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

I ran the process model. I used bootstrapping which took a while to work. After the analysis loaded, I started clicking through some options and the following message appeared: 

Error in if (mod[['inputType']] = 'inputVariables') {: argument is of length zero

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.procIsReady(options)

sapply(options[['processModels']], .procModelIsComplete)

lapply(X = X, FUN = FUN, ...)

FUN(X[[i]], ...)
![Screenshot 2024-07-30 at 12 35 13](https://github.com/user-attachments/assets/29c68f46-bddc-419c-b6d9-fee387512928)

### Expected Behaviour

The results of the analysis are no longer displayed.

### Steps to Reproduce

I had one dependent variable, 10 continuous predictors and 1 categorical predictor. 7 continuous predictors were being tested as mediators. 3 were tested at continuous independent variables and one was tested as a categorical independent variable. 

### More Debug Information

-------- Application Info --------
JASP Version: JASP 0.19 (Intel)
Build Branch: development
Build Date: Jul 13 2024 09:59:11 (Netherlands)
Last Commit: 8b929b98f058f23dd8c8cf3e891be5a77b2ebc0b

-------- Basic Info --------
Operating System: macOS 14.5
Product Version: 14.5
Kernel Type: darwin
Kernel Version: 23.5.0
Architecture: x86_64
Install Path: /Applications/JASP.app/Contents/MacOS
Platfotm Name: cocoa
System Local: en_GB

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
To help us reproducing and understanding this error:
Could you share your .jasp-file by renaming to .zip and drag and dropping it here?
thx
