### ISSUE TITLE
[Bug]: This analysis terminated unexpectedly.  Error in options$modelTerms[[length(glmObj)]]: subscript out of bounds  Stack trace

### ISSUE THREAD

**Issue by june-svg** [jasp-stats/jasp-issues#2860]
### JASP Version

0.19.0

### JASP Module

Regression

### What analysis are you seeing the problem on?

logistic regression

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

the error occurred while i was doing backward multi binary reg

### Expected Behaviour

i was expecting to have different models of otucomes printed?

### Steps to Reproduce

1.go regg
2. log reg
3.put dv and ivs
4. put backwards enter method

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@june-svg 
can you share your .jasp file here by renaming it to .zip and then drag and dropping it here?
