### ISSUE TITLE
[Bug]: Time Series Analysis - Vector memory limit of 16.0 gb researched see mem.maxVSize()

### ISSUE THREAD

**Issue by AJBEssex** [jasp-stats/jasp-issues#2864]
### JASP Version

0.19.0

### JASP Module

Time Series

### What analysis are you seeing the problem on?

All time series analysis

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

I see following termination when running an ITS analysis - n=25,000 sample:

This analysis terminated unexpectedly.

Error: vector memory limit of 16.0 Gb reached, see mem.maxVSize()

Slack trace - does seem to load. 

File is formatted correctly. Model does run on prophet, but only on the maximum a posteriori option., 

### Expected Behaviour

I think the model should run?

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by AJBEssex** [comment]
Thanks. Sent an email.

**Comment by tomtomme** [comment]
@AJBEssex 
The error message suggests that your machine does have 16GB of RAM and that this might not be enough. Can you try this on a machine with 32 GB of RAM?

**Comment by boutinb** [comment]
How big is your datafile? Could you send it to us?
