### ISSUE TITLE
[Cronbach´s Alpha]: JASP 0.19 Windows 11

### ISSUE THREAD

**Issue by romanogino** [jasp-stats/jasp-issues#2866]
### JASP Version

0.19.0

### JASP Module

Reliability

### What OS are you seeing the problem on?

Windows 11

### Bug Description

https://github.com/user-attachments/assets/8b4fc3ec-4de8-43c0-bae8-0d8e18391c58

In SPSS I can do it, 25 variables, 19 good and 6 bad, but I have a result for Cronbach in SPSS, however in JASP there is no result. 

### Expected Behaviour

In SPSS I can do it, 25 variables, 19 good and 6 bad, but I have a result for Cronbach in SPSS, however in JASP there is no result. 

### Steps to Reproduce

1. Open the file
2. Clic on Reliability
3. Choose the variables...
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment]
@romanogino thanks for creating the issue. I dont understand, you have not chosen coefficient alpha but omega in the video you posted. Also could you maybe translate the error message the shows up?

**Comment by romanogino** [comment]
The error occurs when a statistical test cannot be processed and remains in memory and all other tests come out with the same error, even if there is no reason for the error. I discovered it after several attempts. Sorry for the post, it is cancelled.
