### ISSUE TITLE
[Bug]: Type 2  and 3 Gauge R&R % Tolerance does not match minitab

### ISSUE THREAD

**Issue by SISV10** [jasp-stats/jasp-issues#2867]
### JASP Version

0.19.0

### JASP Module

Quality Control

### What analysis are you seeing the problem on?

Type 2  and 3 Gauge R&R 

### What OS are you seeing the problem on?

Windows 11

### Bug Description

JASP and Minitab calculations do not match.

[Gage_R&R.zip](https://github.com/user-attachments/files/16551199/Gage_R.R.zip)

### Expected Behaviour

I would expect for both software's to give the same calculated values. 
![jasp](https://github.com/user-attachments/assets/1eba1416-1c80-4580-ac4b-9e05394e0908)
![minitab1](https://github.com/user-attachments/assets/43c44c5d-a321-4d9f-a30a-fe92d02a0553)
![minitab2](https://github.com/user-attachments/assets/4b3c6bc5-5c6d-40d7-9c4c-178daa9315a8)

### Steps to Reproduce

1.
2.
3.
...

### Log (if any)

The JASP file attached has two analysis, tinned length and overall length. Tinned length matches Minitab exactly, but overall length does not. 

### More Debug Information

-------- Application Info --------
JASP Version: JASP 0.19
Build Branch: development
Build Date: Jul 13 2024 09:52:18 (Netherlands)
Last Commit: 8b929b98f058f23dd8c8cf3e891be5a77b2ebc0b

-------- Basic Info --------
Operating System: Windows 11 Version 23H2
Product Version: 11
Kernel Type: winnt
Kernel Version: 10.0.22631
Architecture: x86_64
Install Path: C:/Program Files (x86)/JASP
Platfotm Name: windows
System Local: en_US

-------- Extra Info --------
Current code page
Active code page: 437
Active code page: 65001

Host Name:                 LAPTOP-SN25GKAP
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22631 N/A Build 22631
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          N/A
Registered Organization:   N/A
Product ID:                00355-61204-07267-AAOEM
Original Install Date:     12/21/2023, 11:25:34 PM
System Boot Time:          7/31/2024, 3:02:14 PM
System Manufacturer:       LENOVO
System Model:              21FC002AUS
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 186 Stepping 2 GenuineIntel ~2400 Mhz
BIOS Version:              LENOVO N3UET22W (1.09 ), 11/15/2023
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-08:00) Pacific Time (US & Canada)
Total Physical Memory:     32,440 MB
Available Physical Memory: 21,337 MB
Virtual Memory: Max Size:  34,488 MB
Virtual Memory: Available: 20,850 MB
Virtual Memory: In Use:    13,638 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\LAPTOP-SN25GKAP
Hotfix(s):                 6 Hotfix(s) Installed.
                           [01]: KB5039895
                           [02]: KB5027397
                           [03]: KB5031274
                           [04]: KB5033055
                           [05]: KB5040442
                           [06]: KB5039338
Network Card(s):           2 NIC(s) Installed.
                           [01]: Intel(R) Wi-Fi 6E AX211 160MHz
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.0.1
                                 IP address(es)
                                 [01]: 192.168.0.149
                                 [02]: fe80::93d8:bc7:c4a6:d7d1
                           [02]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JTPetter** [comment]
Thanks for reporting! Some interesting rounding issues led to this. Added a fix for the next version.

**Comment by boutinb** [comment]
@JTPetter Can we close this?

**Comment by JTPetter** [comment]
@boutinb Yes! Excuses, forgot to link the PR that solved this

**Comment by SISV10** [comment]
> Thanks for reporting! Some interesting rounding issues led to this. Added a fix for the next version.

Hello I just re-ran this on JASP 0.19.1 and the error still occurred.
