### ISSUE TITLE
Releasing constraints

### ISSUE THREAD

**Issue by grijlaa1** [jasp-stats/jasp-issues#2868]
### JASP Version

0.19.0

### JASP Module

SEM

### What analysis are you seeing the problem on?

SEM: release unity regression coefficients into condition specific ons

### What OS are you seeing the problem on?

Windows 11

### Bug Description

Error: lavaan->ldw_parse_get_modifier():  
   invalid modifier specification at line 10, pos 81
EE2 ~ b21*Effort2 + c21*TopicK2 + c22(c221,c222,c223)*TopicInt2 + c23*Diff2
                                                                                ^

Stack trace
lavaan::sem(model = originalSyntax, data = dataset, group = options[['group']])

eval(sc, parent.frame())

eval(sc, parent.frame())

lavaan::lavaan(model = originalSyntax, data = dataset, group = options[['group']], model.type = 'sem')

lav_lavaan_step01_ovnames_initflat(slotParTable = slotParTable, model = model, dotdotdot.parser = dotdotdot$parser)

lavParseModelString(model, parser = 'new')

ldw_parse_model_string(model.syntax = model.syntax, as.data.frame. = as.data.frame.)

ldw_parse_get_modifier(formul1, FALSE, opi, modelsrc, types, rme, rmeprev)

lav_msg_stop(gettext('invalid modifier specification'), tl[1], footer = tl[2])

stop(msg, call. = FALSE, domain = NA)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

### Expected Behaviour

I would have expected three coefficients, one per condition

### Steps to Reproduce

1. I closed Jasp,
2. cleaned the cache
3. ran the procedure again, with variants
...

### Log (if any)

-------- Application Info --------
JASP Version: JASP 0.19
Build Branch: development
Build Date: Jul 13 2024 09:52:18 (Netherlands)
Last Commit: 8b929b98f058f23dd8c8cf3e891be5a77b2ebc0b

-------- Basic Info --------
Operating System: Windows 11 Version 23H2
Product Version: 11
Kernel Type: winnt
Kernel Version: 10.0.22631
Architecture: x86_64
Install Path: C:/Program Files (x86)/JASP
Platfotm Name: windows
System Local: nl_NL

-------- Extra Info --------
Current code page
Active code page: 437
Active code page: 65001

Host Name:                 LTF231130
OS Name:                   Microsoft Windows 11 Enterprise
OS Version:                10.0.22631 N/A Build 22631
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          UvA
Registered Organization:   IC
Product ID:                00329-00000-00003-AA286
Original Install Date:     27-5-2024, 15:57:12
System Boot Time:          9-8-2024, 07:14:39
System Manufacturer:       LENOVO
System Model:              21FHS04U00
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 186 Stepping 3 GenuineIntel ~1700 Mhz
BIOS Version:              LENOVO R27ET34W (1.19 ), 26-6-2024
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
Total Physical Memory:     32.449 MB
Available Physical Memory: 20.099 MB
Virtual Memory: Max Size:  34.497 MB
Virtual Memory: Available: 21.913 MB
Virtual Memory: In Use:    12.584 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    uva.nl
Logon Server:              \\ADDC-PRD-UVA3
Hotfix(s):                 4 Hotfix(s) Installed.
                           [01]: KB5039895
                           [02]: KB5027397
                           [03]: KB5040442
                           [04]: KB5039338
Network Card(s):           2 NIC(s) Installed.
                           [01]: Intel(R) Wi-Fi 6E AX211 160MHz
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.178.1
                                 IP address(es)
                                 [01]: 192.168.178.158
                                 [02]: fe80::7bb3:4157:2795:68c
                           [02]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: No
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

### More Debug Information

Error: lavaan->ldw_parse_get_modifier():  
   invalid modifier specification at line 10, pos 81
EE2 ~ b21*Effort2 + c21*TopicK2 + c22(c221,c222,c223)*TopicInt2 + c23*Diff2
                                                                                ^

Stack trace
lavaan::sem(model = originalSyntax, data = dataset, group = options[['group']])

eval(sc, parent.frame())

eval(sc, parent.frame())

lavaan::lavaan(model = originalSyntax, data = dataset, group = options[['group']], model.type = 'sem')

lav_lavaan_step01_ovnames_initflat(slotParTable = slotParTable, model = model, dotdotdot.parser = dotdotdot$parser)

lavParseModelString(model, parser = 'new')

ldw_parse_model_string(model.syntax = model.syntax, as.data.frame. = as.data.frame.)

ldw_parse_get_modifier(formul1, FALSE, opi, modelsrc, types, rme, rmeprev)

lav_msg_stop(gettext('invalid modifier specification'), tl[1], footer = tl[2])

stop(msg, call. = FALSE, domain = NA)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by grijlaa1** [comment]
Screenshot is available now, and data
![Screenshot 2024-08-09 094919](https://github.com/user-attachments/assets/e813f8b0-d2bb-42a0-8ca6-105d5d7116af)
)

**Comment by grijlaa1** [comment]
and data

[Trial op TQ_Beliefs_SE_Recall_merged_centred wide file stripped.csv](https://github.com/user-attachments/files/16557987/Trial.op.TQ_Beliefs_SE_Recall_merged_centred.wide.file.stripped.csv)

**Comment by grijlaa1** [comment]
[For Julius.zip](https://github.com/user-attachments/files/16558418/For.Julius.zip)

This should be the file then?

**Comment by grijlaa1** [comment]
The issue, more general, is that now in version 19 it is impossible to write Sem codes as
y = b11(b111,b112,b113) etc to specify three condition specific coefficients, when departing from b11, as used for the whole group analysis.

**Comment by juliuspfadt** [comment]
so the issue is actually with the R-package `lavaan` which we use to run SEM in JASP. With version 0.6.17 this was the warning we got for your model2 code: 
<img width="603" alt="Screenshot 2024-08-12 at 10 21 24" src="https://github.com/user-attachments/assets/c0a69278-de85-4e50-a18a-37fe1b702aa1">
But with version 0.6.18 this gives an error instead of a warning. What exactly are you trying to achieve with the constraints?

**Comment by juliuspfadt** [comment]
If your goal is to have the regression coefficients constrained to be equal across the conditions, but for the predictor TopicInt2 you want to release them, then I believe this line `EE2 ~ b21*Effort2 + c21*TopicK2 + c(c221,c222,c223)*TopicInt2 + c23*Diff2` instead of the one you have should work
