### ISSUE TITLE
Binomial test analysis terminated unexpectedly

### ISSUE THREAD

**Issue by qyugit** [jasp-stats/jasp-issues#287]
* JASP version: Version 0.9.2
* OS name and version: macOS Mojave 10.14.3
* Analysis: Binomial test
* Bug description: 

> This analysis terminated unexpectedly.
> 
> Error in stats::binom.test(counts, n, p = options$testValue, alternative = hyp, : 'n' must be a positive integer >= 'x'
> 
> Stack trace
> analysis(dataset = dataset, options = options, perform = perform, callback = the.callback, state = oldState)
> 
> .binomialTest(dataset, options, perform, variables)
> 
> stats::binom.test(counts, n, p = options$testValue, alternative = hyp, conf.level = options$confidenceIntervalInterval)
> 
> stop(''n' must be a positive integer >= 'x'')

[binomial_catch.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/2737590/binomial_catch.jasp.zip)

1. Go to 'Frequencies'
2. Click on 'Binomial Test'
3. Select variables (all the variables not including V1) into the testing window

**Comment by TimKDJ** [comment]
Thanks for the report @qyugit. 

Strange indeed. It seems to have something to do with the fact that all your variable names are numbers.
We'll fix this, but in the mean time (if you would still like to analyse this data) you can use the .csv attachment.

[binomial_catch copy.csv.zip](https://github.com/jasp-stats/jasp-issues/files/2792054/binomial_catch.copy.csv.zip)

**Comment by boutinb** [comment]
The error is in fact quite tricky: a column name has the same name as the number of columns.
In the next release, I will add a 'V' to column whose name is an integer: that will solve automatically this problem, and also solve any problem with filtering where name of column can be directly used in R script.
