### ISSUE TITLE
[Feature Request]: Degrees of freedom for RM ANOVA's post hoc tests

### ISSUE THREAD

**Issue by RenzoLanfranco** [jasp-stats/jasp-issues#2874]
### Description

Currently, JASP doesn't provide degrees of freedom for RM ANOVA's post hoc comparisons. This is important, especially because results may vary depending on whether the error of the model is pooled or not.

### Purpose

To display degrees of freedom for post hoc pairwise comparisons.

### Is your feature request related to a JASP module?

ANOVA, Mixed Models, T-Tests

**Comment by tomtomme** [comment]
@JohnnyDoorn 
Any idea if this is feasible?
