### ISSUE TITLE
[Bug]: Data file corrupted after saving and is unusable

### ISSUE THREAD

**Issue by burker72** [jasp-stats/jasp-issues#2877]
### JASP Version

0.19.0

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

file save after data entry

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

This morning file was opened and an observation was appended; then file was saved and program exited normally. This evening an attempt was made to open the file and the following error was received:

Unable to open file because:
Running ```
ALTER TABLE Columns  DROP 	COLUMN isComputed;
``` failed because of: `no such column: "isComputed"

### Expected Behaviour

Data file should have opened for editing or analysis

### Steps to Reproduce

1. I tried to open the file using two differnt computers, each running the most recent MacOS. No joy.
2. Cannot attach   data file for unknown reason.
3.
...

### More Debug Information

Unable to open file because:
Running ```
ALTER TABLE Columns  DROP 	COLUMN isComputed;
``` failed because of: `no such column: "isComputed"

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by RensDofferhoff** [comment]
Are you able to share the file here?
