### ISSUE TITLE
[Bug]: SEM Analysis Terminated Unexpectedly 

### ISSUE THREAD

**Issue by ezgi-sakman** [jasp-stats/jasp-issues#2879]
### JASP Version

0.19.0

### JASP Module

SEM

### What analysis are you seeing the problem on?

SEM

### What OS are you seeing the problem on?

Windows 11

### Bug Description

Hello, 

I am new in JASP and ran into an error while trying to run a SEM analysis and I was hoping you could help me. 

I typed the following syntax to the section "model": 

In_Laws =~ Dunur_1 + Dunur_2 + Dunur_3R + Dunur_4R + Dunur_5
Ebv_Zor =~ Yetkinlik_1 + Yetkinlik_2 + Yetkinlik_3
Ebv_Yetk =~ Yetkinlik_4 + Yetkinlik_5 + Yetkinlik_8 + Yetkinlik_6_R + Yetkinlik_7_R
Prt_Sup =~ Erken_Ebev_Uygulama_44_CECPAQ + Erken_Ebev_Uygulama_13_CECPAQ + Erken_Ebev_Uygulama_10_CECPAQ + Erken_Ebev_Uygulama_41_CECPAQ + Erken_Ebev_Uygulama_8_CECPAQ + Erken_Ebev_Uygulama_37_CECPAQ + Erken_Ebev_Uygulama_9_CECPAQ + Erken_Ebev_Uygulama_36_CECPAQ + Erken_Ebev_Uygulama_5_CECPAQ + Erken_Ebev_Uygulama_12_CECPAQ + Erken_Ebev_Uygulama_35_CECPAQ + Erken_Ebev_Uygulama_33_CECPAQ + Erken_Ebev_Uygulama_34_CECPAQ
Prt_Disc =~ Erken_Ebev_Uygulama_20_CECPAQ + Erken_Ebev_Uygulama_27_CECPAQ + Erken_Ebev_Uygulama_23_CECPAQ + Erken_Ebev_Uygulama_28_CECPAQ + Erken_Ebev_Uygulama_31_CECPAQ + Erken_Ebev_Uygulama_14_CECPAQ + Erken_Ebev_Uygulama_18_CECPAQ

Ebv_Zor ~ M_Age + Employ + Edu + Income + In_Laws
Ebv_Yetk ~ M_Age + Employ + Edu + Income + In_Laws
Prt_Sup ~ M_Age + Employ + Edu + Income + In_Laws + Ebv_Zor + Ebv_Yetk
Prt_Disc ~ M_Age + Employ + Edu + Income + In_Laws + Ebv_Zor + Ebv_Yetk

In_Laws, Ebv_Zor, Ebv_Yetk, Prt_Sup, and Prt_Disc are my latent variables and M_Age, Employ, Edu, and Income are the covariates I want to include in the model (which are available on the data file). 

But I got the following error message.: 

This analysis terminated unexpectedly.

Error in if (nrow(originalSyntaxTable[originalSyntaxTable$op = ':=', : argument is of length zero

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.semParameters(modelContainer, dataset, options, ready)

.semParameterTables(modelContainer[['results']][['object']][[1]], NULL, params, options, ready, modelContainer, dataset)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

I am attaching a screenshot of what I got on JASP and also my data file.

I really appreciate your time and support!

### Expected Behaviour

I was hoping to get a SEM output 

### Steps to Reproduce

When I re-ran the analysis after closing and re-opening JASP, I got the same error message 

### Log (if any)

![Sreenshot](https://github.com/user-attachments/assets/63f278dc-a227-4299-9d0c-373d29f384ec)
[1. Data.zip](https://github.com/user-attachments/files/16677265/1.Data.zip)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment]
@ezgi-sakman thanks for creating the issue. The error message is indeed annoying. I checked your code and it seems that your latent variable names are also names of of observed variables in the data set. That is not allowed in the syntax. You may try changing the latent variable names. A newer version of JASP will give a more informative error message :)

**Comment by juliuspfadt** [comment]
okay. so the error message is once again not very informative. I am working with a development version that will soon be available for everyone. However, the error I get says that the "Income" variable is the issue because it is scaled as nominal and should be ordinal. I rescaled the variable to ordinal and now the error is that the model did not converge. I rescaled the variable to continuous and I get a completely different error that has nothing to do with the scaling.

**Comment by juliuspfadt** [comment]
Ah, when I scale the "income" variable as continuous and I remove the path plot, then it actually works. I am uncertain why the R-package for eat path plot gives an error. I will need to investigate.

**Comment by ezgi-sakman** [comment]
Hi Julius,

Thank you so much for your time in exploring this! Oddly, when I fixed 
the income variable to be continuous, I was able to have the model run 
and also get the path diagram. I am attaching the output.

May I have a couple of follow-up questions if you have the time? Please 
excuse me if these are silly questions, as I mentioned in my first 
correspondence, this is my first time with JASP, so I am a bit confused.

My first question is about improving the model based on fit indices. I 
used LISREL to do SEM in the past and the modification indices part 
would tell me how much of a reduction in chi square I would get if I let 
the errors between certain variables to correlate to improve the model. 
I was a bit confused as to how to interpret the fit indices part of the 
JASP output, would you mind guiding me as to what I should be looking 
for to improve the model?

My other question is about the test of my model. The model I am trying 
to test with SEM is a mediation model. With LISREL I would have to write 
a separate syntax and have the software run it to get the total, direct, 
and indirect effects as tests of the mediation model. With JASP, do I 
need to write a new model syntax to get those metrics, or should I be 
using the "Mediation Analysis" button under the "SEM" tab? Would that 
analysis give me SEM-based mediation model test or just a regular 
mediation analysis?

I deeply appreciate your time and support,

With my best regards,

Ezgi

---
Ezgi Sakman, Ph.D.

Lecturer
Department of Psychology
Bilkent University
06800 Bilkent Ankara/Turkey
Office: H354-B Phone: +90 312 290 2193

Associate Editor
Journal of Social and Personal Relationships

On 2024-08-22 11:46, Julius Pfadt wrote:

> Ah, when I scale the "income" variable as continuous and I remove the 
> path plot, then it actually works. I am uncertain why the R-package for 
> eat path plot gives an error. I will need to investigate.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/jasp-stats/jasp-issues/issues/2879#issuecomment-2304115500
[2]

**Comment by juliuspfadt** [comment]
Nice that the analysis worked :)
Regarding your first question, I think you can use the modification indices in JASP like you did before. You find them in the "Output options" section. The column "mi" will tell you the improvement to the chi-square statistic. 
Regarding your second question, for a latent mediation analysis you will have to use the SEM analysis and specify the model accordingly. The "mediation analysis" will run a regular mediation with observed variables.

**Comment by ezgi-sakman** [comment]
Thank you so much for your prompt reply Julius!

OK, great! I wasn't sure which metric to check for model improvement. 
Speaking of model fit, I noticed one odd thing about goodness of fit 
measures - although several of the metrics were quite close to what I 
got for this model with LISREL, the RMSEA value was quite off (LISREL 
gave 0.345 while JASP gave 0.057). Would you have any idea as to why 
this might be?

As for mediation, yes I would like to test a SEM-based mediation model. 
I checked out the tutorials at the lavaan.ugent.be website for finding a 
syntax to specify that to the model and I was able to find something 
like this:

set.seed(1234)
X <- rnorm(100)
M <- 0.5*X + rnorm(100)
Y <- 0.7*M + rnorm(100)
Data <- data.frame(X = X, Y = Y, M = M)
model <- ' # direct effect
              Y ~ c*X
            # mediator
              M ~ a*X
              Y ~ b*M
            # indirect effect (a*b)
              ab := a*b
            # total effect
              total := c + (a*b)
          '
fit <- sem(model, data = Data)
summary(fit)

But I wasn't sure if this would work for JASP as I think this code is 
for R. I would be so grateful for any insight you might have as to how I 
could modify this syntax for JASP.

I really appreciate your time and patience with me :)

With my best,

Ezgi

---
Ezgi Sakman, Ph.D.

Lecturer
Department of Psychology
Bilkent University
06800 Bilkent Ankara/Turkey
Office: H354-B Phone: +90 312 290 2193

Associate Editor
Journal of Social and Personal Relationships

On 2024-08-22 17:52, Julius Pfadt wrote:

> Nice that the analysis worked :)
> Regarding your first question, I think you can use the modification 
> indices in JASP like you did before. You find them in the "Output 
> options" section. The column "mi" will tell you the improvement to the 
> chi-square statistic.
> Regarding your second question, for a latent mediation analysis you 
> will have to use the SEM analysis and specify the model accordingly. 
> The "mediation analysis" will run a regular mediation with observed 
> variables.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/jasp-stats/jasp-issues/issues/2879#issuecomment-2304873863
[2]

**Comment by juliuspfadt** [comment]
what you are referring to is regular mediation that runs through lavaan and is fit using SEM technique but does not involve latent variables. Essentially all you need is the model syntax for a lavaan model. 
When we talk about latent mediation we mean that the variables, predictor, outcome, mediator, are latent, meaning they are modelled with indicators. If, in your example, the variables X Y and M were latent you would add this to your syntax in addition to what you already have. 
```r
X =~ x1+x2+x3
Y =~ y1+y2+y3
M =~ m1+m2+m3
 ```
Of course assuming the variables x1 ... m3 are observed variables in your data set. I dont know if that makes it more clear, otherwise I can only refer you to textbooks.

**Comment by ezgi-sakman** [comment]
Hi Julius,

Thank you very much for your reply. That makes a lot of sense, things 
are clearer for me now, thanks!

May I bother you with one last question regarding goodness of fit 
measures? Although several of the metrics were quite close to what I got 
for this model with LISREL, the RMSEA value was quite off (LISREL gave 
0.345 while JASP gave 0.057). Would you have any idea as to why this 
might be?

I really appreciate your time and support!

Best,

Ezgi

---
Ezgi Sakman, Ph.D.

Lecturer
Department of Psychology
Bilkent University
06800 Bilkent Ankara/Turkey
Office: H354-B Phone: +90 312 290 2193

Associate Editor
Journal of Social and Personal Relationships

On 2024-08-23 15:48, Julius Pfadt wrote:

> what you are referring to is regular mediation that runs through lavaan 
> and is fit using SEM technique but does not involve latent variables. 
> Essentially all you need is the model syntax for a lavaan model.
> When we talk about latent mediation we mean that the variables, 
> predictor, outcome, mediator, are latent, meaning they are modelled 
> with indicators. If, in your example, the variables X Y and M were 
> latent you would add this to your syntax in addition to what you 
> already have.
> 
> X =~ x1+x2+x3
> Y =~ y1+y2+y3
> M =~ m1+m2+m3
> 
> Of course assuming the variables x1 ... m3 are observed variables in 
> your data set. I dont know if that makes it more clear, otherwise I can 
> only refer you to textbooks.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/jasp-stats/jasp-issues/issues/2879#issuecomment-2307024967
[2]

**Comment by juliuspfadt** [comment]
I can't say how LISREL is computing the RMSEA, we are using the R-package `lavaan`. Essentially, the RMSEA is based on the minimised fit function and the model degrees of freed (if I remember correctly). It seems strange that it would differ so dramatically. I suspect that there might be some options set in the background of either of the two methods that lead to a difference in fit. You can always compare other fit indices, such as the SRMR or the CFI.

**Comment by ezgi-sakman** [comment]
Thank you very much for all your help Julius, I really appreciate it!

Have a great day!

Best,

Ezgi

---
Ezgi Sakman, Ph.D.

Lecturer
Department of Psychology
Bilkent University
06800 Bilkent Ankara/Turkey
Office: H354-B Phone: +90 312 290 2193

Associate Editor
Journal of Social and Personal Relationships

On 2024-08-26 14:07, Julius Pfadt wrote:

> I can't say how LISREL is computing the RMSEA, we are using the 
> R-package lavaan. Essentially, the RMSEA is based on the minimised fit 
> function and the model degrees of freed (if I remember correctly). It 
> seems strange that it would differ so dramatically. I suspect that 
> there might be some options set in the background of either of the two 
> methods that lead to a difference in fit. You can always compare other 
> fit indices, such as the SRMR or the CFI.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/jasp-stats/jasp-issues/issues/2879#issuecomment-2309944324
[2]

**Comment by juliuspfadt** [comment]
Likewise :)
