### ISSUE TITLE
Custom contrasts in JASP?

### ISSUE THREAD

**Issue by mservantufc** [jasp-stats/jasp-issues#288]
Following my discussion with EJ on the forum:
Different contrasts can be performed in JASP (deviation, simple, difference, Helmert, repeated, polynomial). 
It would be nice to be able to compute custom contrasts (using something akin to the "special" function in SPSS). 
Best,
Mathieu

**Comment by pandelis** [comment]
Another very nice option would be to be able compute these custom contrasts with an interface like Statistica !

![image](https://user-images.githubusercontent.com/3620214/51900478-b2f58b80-23b5-11e9-8028-70a07adb632c.png)

Best,

**Comment by lithos** [comment]
...also  a very minor tweak but could you put an arrow/dropdown indicator on the type (default none) took me ages to work out i had to click 'none' to change it . when i do click 'none' i get an arrow !

mac os x JASP 9.0.1, 9.02   Thanks again for awesome work

**Comment by JohnnyDoorn** [comment]
I need that widget from @JorisGoosen, @boutinb or maybe @akashrajkn - once we get that it's very simple to implement custom contrasts in R/JASP.

**Comment by JorisGoosen** [comment]
Did you make an issue for that widget?

**Comment by JohnnyDoorn** [comment]
https://github.com/jasp-stats/INTERNAL-jasp/issues/411

**Comment by mservantufc** [comment]
Hi Guys,
I was wondering if this custom contrast project was achieved ? I'll start my stats class in january, and it would be good for students to have this feature implemented.
Best,
Mat

**Comment by JohnnyDoorn** [comment]
Hi Mat,

The implementation is almost finished, and will be in the new release - now it's just a question of when the other targets are met and it can be released. We are aiming for early January, but unfortunately we cannot promise any strict deadline.

Cheers,
Johnny

**Comment by pandelis** [comment]
Hi,

Waoow ! 
That means that we should be able to teach using JAPS this semester ! (lectures on ANOVA will begin on February).
This is such a good news for us ! (JASP will be a lot easier to teach and to manipulated than previous softwares that we used so we will be able to go further)

Thanks for your fantastic work !
Boris

**Comment by pandelis** [comment]
Hi,

Would you have any idea when the future release will be done, please ?

Best

**Comment by JorisGoosen** [comment]
We begin testing next week, we are finishing all the work going into this release this week. Hopefully that way we are on time for your semester's start.

If you want to take a sneak peek you can take a look at [our nightlies](http://static.jasp-stats.org/Nightlies/), but keep in mind that there might be bugs (and if you find them let us know!).
And it would probably unwise to make JASP-files in the nightly versions and then use them in the released version. But at least you can take a look at the new version.

**Comment by pandelis** [comment]
Many thanks for the informations !

**Comment by boutinb** [comment]
The nightly version does not have yet a working custom contrast... At the end of the week hopefully.

**Comment by pandelis** [comment]
Stupid question but is it possible to install easily different versions of JASP (on Windows) ? 
As it uninstall the already installed ones, I only found the following procedure for the moment:
-Installing JASP nightly
-Copy it in a directory
-Re-install JASP stable
Would there be a more direct way ?

**Comment by pandelis** [comment]
I found a solution for the double install of JASP : I keep the stable one in a different folder than "Programmes|JASP" and everything is ok.

**Comment by boutinb** [comment]
We will make a ZIP version of the Nightly builds. Coming soon.

**Comment by boutinb** [comment]
There are there! http://static.jasp-stats.org/Nightlies/

**Comment by pandelis** [comment]
Thanks ! Impressive !
I reported possible problems using custom contrasts in the bug section.

**Comment by pandelis** [comment]
My ANOVA lectures will begin Tuesday 11. 
Is there any hope custom contrasts will work by then ?
Best

**Comment by JohnnyDoorn** [comment]
Hi Pandelis, 

I will implement the custom cntrasts for RM ANOVA this week, so they should be in the nightly by the end of the week. I'll also look into the one issue where you need to specify more than 1 contrast to make it work, but it might just be a necessity in custom contrasts in R. 

Cheers
Johnny

**Comment by pandelis** [comment]
Thanks !
I noticed another thing in between ANOVA with 2 factors.
Imagine 1 factor is gender and another is quantity of beers (0,2,4) and the effect on attractiveness.

 It would be nice to be able to do things like only for women I would like to see the effect of 0 vs (2 and 4) beers. But if I do that (1 for men and 0 for women) it complains that "Some contrasts do not sum to 0".
In other terms it is not possible for the moment to test interaction contrasts.
Best

**Comment by JohnnyDoorn** [comment]
Hi @pandelis 

The RM ANOVA custom contrasts are now also added, so tomorrow's nightly builds will have it I think. I have also removed the sum to 0 constraint.
I am closing this issue now, please make a new one if you encounter any problems!

Kind regards
Johnny
