### ISSUE TITLE
[Bug]: Internal Error

### ISSUE THREAD

**Issue by trisha1111111** [jasp-stats/jasp-issues#2880]
### JASP Version

0.19.0

### JASP Module

Descriptives

### What OS are you seeing the problem on?

Windows 10

### Bug Description

After a few minutes from logging in in the JASP it keeps popping up a notification about an internal error and I have to redo my work again. So tiring. 

### Expected Behaviour

Please fix this bug as I think i'm the only  one experiencing this. 

### Steps to Reproduce

1.
2.
3.
...
n/a

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by RensDofferhoff** [comment]
Could you describe what you do that might cause the problem?
Are your data files large? What are your PC specs?
