### ISSUE TITLE
[Bug]: Intermittent blank result while using JASP 0.19

### ISSUE THREAD

**Issue by peterubuane** [jasp-stats/jasp-issues#2881]
### JASP Version

0.19.0

### JASP Module

Descriptives

### What analysis are you seeing the problem on?

Descriptive and independent ttest

### What OS are you seeing the problem on?

Windows 10

### Bug Description

Intermittently, I experience blanking of the JASP results section while doing analysis. I have to close and restart the software to get over this. What could be the reason?
![screenshot JASP 0 19 error](https://github.com/user-attachments/assets/cdd69a92-14d6-4aa0-a13a-93cbc4cbf3f1)

I didn't experience this with JASP 0.18.3 before deleting it and installing this new version.

### Expected Behaviour

produce result 

### Steps to Reproduce

1.
2.
3.
...
happens again and again

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by shun2wang** [comment]
Hi thanks for your report. Could you follow these steps to get more information?

1. Can you upload this file (zip it and drag drop it in the comment)?
2. Path to the directory where the `JASP.exe` located for example: `C:\Program Files (x86)\JASP`
3. Let's assume it is path above, then in the opened command prompt enter:
```
cd "C:\Program Files\JASP"
JASP.exe --webEngineArgs --remote-debugging-port=12345
```
4. Open the Edge or Chrome browser and input this url: `http://localhost:12345/` then open the first `JASP` in `Inspectable pages`
5. Click `console` in the right panel, and give us screenshot what you see.

**Comment by boutinb** [comment]
I had this issue once or twice (but have no reproduction path), and by just showing thew data again, or by changing the width of the result pane, the results were displayed again.

**Comment by catarinaqmc** [comment]
I am having the same issue. I am trying to run a CFA, but the output with the results keeps on going blank and I have to close and restart the software, I can not even export the results.

**Comment by shun2wang** [comment]
> Hi thanks for your report. Could you follow these steps to get more information?
> 
> 1. Can you upload this file (zip it and drag drop it in the comment)?
> 2. Path to the directory where the `JASP.exe` located for example: `C:\Program Files (x86)\JASP`
> 3. Let's assume it is path above, then in the opened command prompt enter:
> 
> ```
> cd "C:\Program Files\JASP"
> JASP.exe --webEngineArgs --remote-debugging-port=12345
> ```
> 
> 4. Open the Edge or Chrome browser and input this url: `http://localhost:12345/` then open the first `JASP` in `Inspectable pages`
> 5. Click `console` in the right panel, and give us screenshot what you see.

Hi @catarinaqmc did you try this above.
