### ISSUE TITLE
[Bug]: unable to open jasp application

### ISSUE THREAD

**Issue by Lrx5253** [jasp-stats/jasp-issues#2888]
### JASP Version

0.19.0

### JASP Module

Unrelated

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

im trying to download Jasp and it wont let me open the application. 

### Expected Behaviour

it should let me open and download it 

### Steps to Reproduce

1.
2.
3.
...
no

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Which Mac version did you download, what is the name of the file. We have 2 Mac versions, for Intel and Silicon (ARM), and you need to download the right one for you Mac.
