### ISSUE TITLE
[Bug]: Rater Agreement Issue

### ISSUE THREAD

**Issue by overossm** [jasp-stats/jasp-issues#2889]
### JASP Version

0.19.0

### JASP Module

Reliability

### What analysis are you seeing the problem on?

Fleiss' kappa

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

[JASP Dissertation Coding Data Sept. 2024.jasp.zip](https://github.com/user-attachments/files/16830185/JASP.Dissertation.Coding.Data.Sept.2024.jasp.zip)

I am trying to calculate fleiss' kappa for five raters. When I add a third variable, it brings up the error I pasted below. 

This analysis terminated unexpectedly.

Error in ratings[i, ]: subscript out of bounds

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.computeFleissKappaTable(dataset, options, ready)

.fleissKappaMod(dataset, detail = TRUE)

### Expected Behaviour

provide fleiss' kappa coeffeicient result

### Steps to Reproduce

No not with different data

### More Debug Information

This analysis terminated unexpectedly.

Error in ratings[i, ]: subscript out of bounds

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.computeFleissKappaTable(dataset, options, ready)

.fleissKappaMod(dataset, detail = TRUE)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment]
@overossm thanks for creating the issue. I cannot reproduce an error with the jasp file you attached. Can you try creating it again and this time only use the one analysis that gives an error?

**Comment by tomtomme** [comment]
@juliuspfadt @overossm 
I also get no error with that file on 0.19 flatpak.
Did you test on macos julius?

**Comment by boutinb** [comment]
I have a Mac Silicon, and I don't get any error either... Can you specify exactly step by step what you do to get this error?

**Comment by juliuspfadt** [comment]
I tested on macOS yes.

**Comment by juliuspfadt** [comment]
I tested on macOS yes.
