### ISSUE TITLE
[Bug]: when i save trained model it shows strange characters in note pad file

### ISSUE THREAD

**Issue by medoteto** [jasp-stats/jasp-issues#2894]
### JASP Version

0.19.0

### JASP Module

Machine Learning

### What analysis are you seeing the problem on?

random forest classfication

### What OS are you seeing the problem on?

Windows 10

### Bug Description

when i save trained model it shows strange characters in note pad file

### Expected Behaviour

[iris.csv](https://github.com/user-attachments/files/16853532/iris.csv)

### Steps to Reproduce

1.i import data to jasp software i add machine learning  i open random forest classfication
2.when i see results i save trained model in my pc
3.when i open note pad file i see strange characters not english characters as seen in csv note pad i uploaded in this bug messege
[iris.csv](https://github.com/user-attachments/files/16853585/iris.csv)
       
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by shun2wang** [comment]
Hi @medoteto thanks for the report. please give us more debug information: open JASP's About window, click "copy debug information" button and paste them in the comment.

**Comment by shun2wang** [comment]
Ah wait, the result should be exported as `.jaspML` but not a `.cav` file anyway.

**Comment by medoteto** [comment]
On Wednesday 4 September 2024 at 03:30:13 GMT+2, Shun Wang ***@***.***> wrote:  
 
 


Ah wait, the result should be exported as .jaspML but not a .cav file anyway.

**Comment by medoteto** [comment]
the problem in strange characters in saved trained model jasp file why this problem happen and how can we solve this problem?

**Comment by shun2wang** [comment]
Sorry, I mean the trained model can only saved as `.jaspML` but not `.csv` file, and then it can be re-load in `Prediction`. You can pay attention to whether the file suffix is ​​correct when saving the model.

**Comment by medoteto** [comment]
i want see out of bag predictions in jasp machine learning random forest model where i can see it in jasp software
    On Wednesday 4 September 2024 at 04:57:15 GMT+2, Shun Wang ***@***.***> wrote:  
 
 


Sorry, I mean the trained model can only saved as .jaspML but not .csv file, and then it can be re-load in Prediction. You can pay attention to whether the file suffix is ​​correct when saving the model.

**Comment by medoteto** [comment]
how can i see out of bag predictions in jasp machine learning random forest?

    On Wednesday 4 September 2024 at 06:08:35 GMT+2, muhammad tamer ***@***.***> wrote:  
 
  i want see out of bag predictions in jasp machine learning random forest model where i can see it in jasp software
    On Wednesday 4 September 2024 at 04:57:15 GMT+2, Shun Wang ***@***.***> wrote:  
 
 


Sorry, I mean the trained model can only saved as .jaspML but not .csv file, and then it can be re-load in Prediction. You can pay attention to whether the file suffix is ​​correct when saving the model.

**Comment by koenderks** [comment]
The workflow is as follows (see also https://jasp-stats.org/2022/04/26/how-to-predict-with-machine-learning-models-in-jasp-classification/)

1. Train a model on training data
2. Save the trained model as .jaspML file
3. Load the trained model (i.e., .jaspML file) into the 'Prediction analysis' in a new JASP session in which you have loaded the data that you want to make predictions for.
4. Now you can view the predictions of the model for the new data

**Comment by medoteto** [comment]
ok thank you very much
    On Wednesday 4 September 2024 at 10:14:23 GMT+2, Koen Derks ***@***.***> wrote:  
 
 


The workflow is as follows (see also https://jasp-stats.org/2022/04/26/how-to-predict-with-machine-learning-models-in-jasp-classification/)
   
   - Train a model on training data
   - Save the trained model as .jaspML file
   - Load the trained model (i.e., .jaspML file) into the 'Prediction analysis' in a new JASP session in which you have loaded the data that you want to make predictions for.
   - Now you can view the predictions of the model for the new data
