### ISSUE TITLE
[Bug]: Quality Control - Process Capability Study - Histogram Upper and Lower specification limit do not scale the histogram

### ISSUE THREAD

**Issue by johnnygeling** [jasp-stats/jasp-issues#2895]
### JASP Version

0.19.0

### JASP Module

Quality Control

### What analysis are you seeing the problem on?

Process capability study

### What OS are you seeing the problem on?

Windows 10

### Bug Description

The histogram can show the Target, Upper spec limit and Lower spec limit. 
When select the 'Display specification limit's' the histogram is not rescaled using these specification limits. So it is possible the limits are not visible. 

![afbeelding](https://github.com/user-attachments/assets/654c1d19-69c4-44fb-ba37-d848bc52463f)
USL and LSL not visible. 

![afbeelding](https://github.com/user-attachments/assets/06e485ba-93c6-4258-a96e-8255296a58f1)
Moved the specification limits into the existing scale. 

### Expected Behaviour

When showing the specification limits it is expected that the horizontal scale of the histogram is adjusted and all element, in this case the specification limits, are visible. 

### Steps to Reproduce

1. Create a process capability study
2. fill in the specification limits
3. Check the histogram. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by johnnygeling** [comment]
Thanks.

**Comment by johnnygeling** [comment]
Hello, 

Is this fix included into version 0.19.1? 
Johnny

**Comment by JTPetter** [comment]
Hi Johnny,

no, did not make it into 0.19.1 unfortunately.

**Comment by boutinb** [comment]
0.19.1 was a hotfix version. 0.19.2 with this fix should be released in November.
