### ISSUE TITLE
[Feature Request]: Consider bumping major version number to 1.x.y

### ISSUE THREAD

**Issue by Joao-O-Santos** [jasp-stats/jasp-issues#2897]
### Description

Please consider bumping the major version number to 1

### Purpose

Communicate the maturity of JASP and better adhere to a [semantic versioning scheme](https://semver.org)

### Use-case

Clearly communicating incompatible versions of JASP through major version bumps and having easier to understand version numbers.

### Is your feature request related to a problem?

No

### Is your feature request related to a JASP module?

Unrelated

### Describe the solution you would like

Bumping the major version to 1.0.0 in the next release.

### Describe alternatives that you have considered

I considered you may be trying to communicate JASP is still in active development, and that there are many features you still want to add, or changes you want to make for it to meet your vision, but I believe you're being too humble.

**Comment by EJWagenmakers** [comment]
We are working hard to complete full R syntax integration, and this will result in JASP 1.0. So you are correct, but we are really close and that's why this issue can be closed.
