### ISSUE TITLE
[Bug]: I am unable to Open jasp with all methods

### ISSUE THREAD

**Issue by Neurogamer2605** [jasp-stats/jasp-issues#2899]
### JASP Version

0.19.0

### JASP Module

Other

### What OS are you seeing the problem on?

Windows 11

### Bug Description

Hi, I installed jasp from Microsoft store but it doesn't open it. I try to open it via a jasp file with a dataset but nothing happens. Checking the computer activity I see that it is in the background but it still doesn't start. Even trying to start it from the unzipped folder of the site it still doesn't start. I tried to disable the antivirus in both cases. Can you help me?

### Expected Behaviour

Open the application

### Steps to Reproduce

1.try ti open
2. Nothing
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Thx for the report.
What kind of CPU does your system have? Did you try restarting the system before?

**Comment by Neurogamer2605** [comment]
I have a Laptop Omen 16 with an amd radeon rx 6600m. Yes of course, I
restarted the PC many times, even reboot.

Il ven 6 set 2024, 20:48 Thomas Langkamp ***@***.***> ha
scritto:

**Comment by tomtomme** [comment]
Maybe a graphics driver issue. Make sure that that one is up to date.
Also maybe try installing via msi instead of winstore

**Comment by tomtomme** [comment]
If that does not help please:

 Could you please upload the logs, see: https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/user-guide/logging-howto.md

To get into safe graphics mode
set the environment to QSG_RHI_BACKEND=opengl on your PC. you can do with:
a. open the "cmd.exe" with administrator permission
b. input setx "QSG_RHI_BACKEND" "opengl" /m and enter.
try again restart JASP.

**Comment by boutinb** [comment]
You can also try to start JASP with the safeGraphics option. For this:

-     Start a command prompt by typing command prompt in the Start menu.
-     Type "c:\Program Files (x86)\JASP\JASP.exe --safeGraphics"

**Comment by Neurogamer2605** [comment]
Through the prompt works, but will I always have to open it that way?

Il giorno lun 9 set 2024 alle ore 10:03 bruno boutin <
***@***.***> ha scritto:

**Comment by boutinb** [comment]
> Through the prompt works, but will I always have to open it that way?

No, once the safeGraphics is set, it is kept in the preferences, so you should be able to start JASP directly now.
