### ISSUE TITLE
Enhancement request: Import data from database.

### ISSUE THREAD

**Issue by aknight1-uva** [jasp-stats/jasp-issues#29]
As mentioned in the meeting:
An import from database(s) might be useful to some (commercial) users.
First thoughts on construction:
1. Use an ODBC connector to access the databases.
2. Have the user enter an SQL statement ("JOIN") somewhere (An "Import options" dialogue?).
A full featured DB browser would be overkill.
Points to think about:
- DB type to JASP type mapping.
- A RDMS could easily produce more data than the memory available to JASP can hold.
- If people are using large datasets (from a DB or elsewhere), might we get performance issues?

**Comment by MarielleZZ** [comment]
For many obvious reasons I would like to introduce JASP in my non-commercial foundation. However, our data has just been moved to the cloud and we're currently teaching our researchers to work with a database connection (ODBC with SPSS). To make my case for switching to JASP it would be really helpful if we could establish a database connection.   

My organization uses health data and is certainly not an exception in having data stored in databases.
