### ISSUE TITLE
strange behavior with Bayesian RM-ANOVA

### ISSUE THREAD

**Issue by ronenno1** [jasp-stats/jasp-issues#290]
* JASP version: 0.9.2 (also 0.8.6)
* OS name and version: Ubuntu 18.04.1 LTS (also Windows 10 Pro)
* Analysis: Bayesian RM ANOVA 
* Bug description: I ran both classical and Bayesian 2 ways -  RM -ANOVA. by using the  the classical analysis I got main effect to one variable ("cong") and I didn't get main effect to the second variable (go_nogo). I also didn't get interaction. When I ran the Bayesian analysis I got deviance to the existing of the main effect to the second variable go_nogo).  As far as I understand Bayesian statistic, the pattern should be the same. I understand that it possible to find that by using Bayesian analysis effect will disappear, but I'm not really sure how it possible to find different effects. Am I miss something?

JASP files as a zip: [times.zip](https://github.com/jasp-stats/jasp-issues/files/2779602/times.zip)

Thanks a lot in advance,
Ronen.

**Comment by ronenno1** [comment]
Hi again.
I still don't have any solution to this issue.
For being sure that I didn't miss anything, I ran more 2 tests:

1. one-way (both classical and Bayesian) RM-ANOVA to the 'cong' variable.
2. paired samples t-test (both classical and Bayesian) for the 'go_nogo' task.

The results for these 2 tests were same (at least in the pattern):
There was a different between the levels of the 'cong' variable (F=22.16, p<.001, BF10=21,142.844) and no different found in the go_nogo variable(t=1.385, p=.184, BF01 = .539).

However, the results for the two-way ANOVA (as I described before) in the Bayesian analysis:

![image](https://user-images.githubusercontent.com/17266793/52913658-daf75100-32c8-11e9-8f59-46a248f9cd6b.png)

is different from the clasical one:

![image](https://user-images.githubusercontent.com/17266793/52913663-ea769a00-32c8-11e9-9df0-34ba8f850137.png)

In addition, the "behaviour" of the Bayesian analysis is also different from the results given by the analysis of each variable separately (as given from the one-way ANOVA and from the paired samples t-test)

I can't find any mistake in my steps and I'll really appreciate your comments.

In any case, the jasp file (that includes the latest analysis) is attached as a zip file: [jasp_inc_ttest_anova.zip](https://github.com/jasp-stats/jasp-issues/files/2872991/jasp_inc_ttest_anova.zip)
 
Thanks a lot in advance,
Ronen.

**Comment by EJWagenmakers** [comment]
Hi Ronen @vandenman (relevant because of the paper you are writing)

I can take a look. Actually, the home for conceptual/interpretational issues such as these is the JASP Forum. On the Forum you will see similar discussions. It would be great if you could post your issues there (several people other than me will see it and may chip in with comments).

Usually large discrepancies are due to model misspecification (lack of homogeneity of variance, skewed distributions, etc)

Cheers,
E.J.

**Comment by ronenno1** [comment]
Thank a lot, I'll publish it there :)

Ronen.
