### ISSUE TITLE
[Bug]: Coffecient table in logistic regression display wrong value when reversing reference value (categorical data)

### ISSUE THREAD

**Issue by PerPalmgren** [jasp-stats/jasp-issues#2900]
### JASP Version

0.19.0

### JASP Module

Regression

### What analysis are you seeing the problem on?

Logistic regression

### What OS are you seeing the problem on?

Windows 10

### Bug Description

In logistic regression. When switching the reference category in the label editor, thus, changing 0=No and 1=Yes the categorical value in the table thus not follow the change. The footnote changes but no the value in the table. (See screen shot)  
![Jasp 1](https://github.com/user-attachments/assets/9916ae57-f331-4f30-872d-b9a0c05b3cc7)
![JASP2](https://github.com/user-attachments/assets/857a19d2-7d68-429c-944d-baa18eb2b95d)

### Expected Behaviour

The table should follow the change of reference category.

### Steps to Reproduce

1.See screen shot
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@PerPalmgren 
which value exactly do you mean?
Most of them are changing the sign as expected.

**Comment by PerPalmgren** [comment]
@tomtomme In the left column “excercise prescription” in the second screen shot the label with (Yes) ought to to change to (No) when  changing reference category, thus corresponding with the footnote. Now this does not make great sense.🙄

**Comment by PerPalmgren** [comment]
![JASP2](https://github.com/user-attachments/assets/309b5fe2-42b2-44dc-bb79-8c627964a2fc)

**Comment by PerPalmgren** [comment]
![JASP2_rev](https://github.com/user-attachments/assets/2f64b43e-2cac-4a30-b9ce-0d61bbe5fe46)

**Comment by JohnnyDoorn** [comment]
Hi @PerPalmgren,

If I understand correctly,  the footnote describes the dependent variable (Heart attack) reference class, not that of the independent variable (Exercise). The results will stay the same, but flipped (Exercise will either decrease probability of heart attack, or decrease probability of no heart attack). 

Cheers
Johnny

**Comment by PerPalmgren** [comment]
You can close this issue because it was me who was wrong.
All the best
Per
