### ISSUE TITLE
[Bug]: Jasp installation

### ISSUE THREAD

**Issue by silverfish514** [jasp-stats/jasp-issues#2904]
### JASP Version

0.19.0

### JASP Module

Other

### What OS are you seeing the problem on?

Windows 11

### Bug Description

I have downloaded the application and run it. At the end of the installation the application requests a system reboot before using it. I allow the reboot but then nothing occurs regarding JASP. No application available and no requests to continue the installation. Tried to run a repair but it didn't help, after going through the installation again it asked for the reboot and nothing occurred again. I have two Jasp files downloaded in my files, and when I press them, the picture below appears. I tried deleting the files 3 times already and reinstalling them, but it still doesn't work. I don't know how to solve this and I urgently need Jasp for my studies.

![Screenshot 2024-09-09 162650](https://github.com/user-attachments/assets/e21660ed-308a-4cb4-9945-d39bd27dd906)

### Expected Behaviour

Jasp opening and working?

### Steps to Reproduce

1. I download Jasp, and I open it from the browser.
2. A pop up opens and it tells me that Jasp will start downloading.
3. It downloads, it makes me reboot the system, I reboot the system and nothing happens.
4. I go into the computer files, press Jasp, it downloads once.
5. After it's downloaded, another pop-up appears that tells me that I have to repair or remove Jasp.
6. I press Repair, I wait for the reparation, the pop up and Jasp automatically close.
7. I open Jasp from the computer files, the same thing happens all over again.

### Log (if any)

no log files

### More Debug Information

I cannot access Jasp

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
There was apparently a problem during the installation of JASP on your system. To repair this, you may need to change settings in the registry, which can be quite difficult.
Better is to install JASP via the Windows store: https://apps.microsoft.com/detail/9p08cwg12jnl?launch=true%20&mode=mini&hl=en-us&gl=NL
If this does not work either, you can try to download the ZIP version (https://jasp-stats.org/download/).
