### ISSUE TITLE
[Bug]: SEM model

### ISSUE THREAD

**Issue by panosgl** [jasp-stats/jasp-issues#2905]
### JASP Version

0.19.0

### JASP Module

SEM

### What analysis are you seeing the problem on?

SEM

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

This analysis terminated unexpectedly.

Error in if (nrow(originalSyntaxTable[originalSyntaxTable$op = ':=', : argument is of length zero

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.semParameters(modelContainer, dataset, options, ready)

.semParameterTables(modelContainer[['results']][['object']][[1]], NULL, params, options, ready, modelContainer, dataset)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

### Expected Behaviour

# latent variables
CIQ =~ CIQ_1 + CIQ_2 + CIQ_3 + CIQ_4 + CIQ_5 + CIQ_6 + CIQ_7 + CIQ_8 + CIQ_9
Avoidant_Style =~ RD12_1 + RD12_3 + RD12_4 + RD12_8 + RD12_10 + RD12_11
Credulity =~ ETS_7 + ETS_8 + ETS_14
Mistrust =~ ETS_3 + ETS_4 + ETS_5 + ETS_6 + ETS_11 + ETS_12 + ETS_13
PTSD_DSM =~ PTSD_1 + PTSD_2 + PTSD_3 + PTSD_4 + PTSD_5 + PTSD_6 + PTSD_7 + PTSD_8 + PTSD_9 + PTSD_10 + PTSD_11 + PTSD_12 + PTSD_13 + PTSD_14 + PTSD_15 + PTSD_16 + PTSD_17
# regressions
Avoidant_Style ~ CIQ
Credulity ~ Avoidant_Style
Mistrust ~ Avoidant_Style 
PTSD_DSM ~ CIQ + Avoidant_Style + Credulity + Mistrust
# residual (co)variances
Credulity ~~ Mistrust

### Steps to Reproduce

pSem::SEM(
          version = "0.19",
          models = list(list(name = "Model 1", syntax = list(columns = list("JaspColumn_19_Encoded", "JaspColumn_20_Encoded", "JaspColumn_21_Encoded", "JaspColumn_22_Encoded", "JaspColumn_23_Encoded", "JaspColumn_24_Encoded", "JaspColumn_25_Encoded", "JaspColumn_26_Encoded", "JaspColumn_27_Encoded", "JaspColumn_103_Encoded", "JaspColumn_104_Encoded", "JaspColumn_105_Encoded", "JaspColumn_106_Encoded", "JaspColumn_95_Encoded", "JaspColumn_96_Encoded", "JaspColumn_97_Encoded", "JaspColumn_98_Encoded", "JaspColumn_99_Encoded", "JaspColumn_100_Encoded", "JaspColumn_160_Encoded", "JaspColumn_128_Encoded", "JaspColumn_137_Encoded", "JaspColumn_138_Encoded", "JaspColumn_139_Encoded", "JaspColumn_140_Encoded", "JaspColumn_141_Encoded", "JaspColumn_142_Encoded", "JaspColumn_143_Encoded", "JaspColumn_144_Encoded", "JaspColumn_129_Encoded", "JaspColumn_130_Encoded", "JaspColumn_131_Encoded", "JaspColumn_132_Encoded", "JaspColumn_133_Encoded", "JaspColumn_134_Encoded", "JaspColumn_135_Encoded", "JaspColumn_136_Encoded", "JaspColumn_35_Encoded", "JaspColumn_47_Encoded", "JaspColumn_48_Encoded", "JaspColumn_38_Encoded", "JaspColumn_39_Encoded", "JaspColumn_44_Encoded"), model = "
CIQ =~ JaspColumn_19_Encoded + JaspColumn_20_Encoded + JaspColumn_21_Encoded + JaspColumn_22_Encoded + JaspColumn_23_Encoded + JaspColumn_24_Encoded + JaspColumn_25_Encoded + JaspColumn_26_Encoded + JaspColumn_27_Encoded
Avoidant_Style =~ JaspColumn_35_Encoded + JaspColumn_38_Encoded + JaspColumn_39_Encoded + JaspColumn_44_Encoded + JaspColumn_47_Encoded + JaspColumn_48_Encoded
Credulity =~ JaspColumn_99_Encoded + JaspColumn_100_Encoded + JaspColumn_106_Encoded
JaspColumn_160_Encoded =~ JaspColumn_95_Encoded + JaspColumn_96_Encoded + JaspColumn_97_Encoded + JaspColumn_98_Encoded + JaspColumn_103_Encoded + JaspColumn_104_Encoded + JaspColumn_105_Encoded
PTSD_DSM =~ JaspColumn_128_Encoded + JaspColumn_129_Encoded + JaspColumn_130_Encoded + JaspColumn_131_Encoded + JaspColumn_132_Encoded + JaspColumn_133_Encoded + JaspColumn_134_Encoded + JaspColumn_135_Encoded + JaspColumn_136_Encoded + JaspColumn_137_Encoded + JaspColumn_138_Encoded + JaspColumn_139_Encoded + JaspColumn_140_Encoded + JaspColumn_141_Encoded + JaspColumn_142_Encoded + JaspColumn_143_Encoded + JaspColumn_144_Encoded

Avoidant_Style ~ CIQ
Credulity ~ Avoidant_Style
JaspColumn_160_Encoded ~ Avoidant_Style 
PTSD_DSM ~ CIQ + Avoidant_Style + Credulity + JaspColumn_160_Encoded

Credulity ~~ JaspColumn_160_Encoded
", modelOriginal = "# latent variables
CIQ =~ CIQ_1 + CIQ_2 + CIQ_3 + CIQ_4 + CIQ_5 + CIQ_6 + CIQ_7 + CIQ_8 + CIQ_9
Avoidant_Style =~ RD12_1 + RD12_3 + RD12_4 + RD12_8 + RD12_10 + RD12_11
Credulity =~ ETS_7 + ETS_8 + ETS_14
Mistrust =~ ETS_3 + ETS_4 + ETS_5 + ETS_6 + ETS_11 + ETS_12 + ETS_13
PTSD_DSM =~ PTSD_1 + PTSD_2 + PTSD_3 + PTSD_4 + PTSD_5 + PTSD_6 + PTSD_7 + PTSD_8 + PTSD_9 + PTSD_10 + PTSD_11 + PTSD_12 + PTSD_13 + PTSD_14 + PTSD_15 + PTSD_16 + PTSD_17
# regressions
Avoidant_Style ~ CIQ
Credulity ~ Avoidant_Style
Mistrust ~ Avoidant_Style 
PTSD_DSM ~ CIQ + Avoidant_Style + Credulity + Mistrust
# residual (co)variances
Credulity ~~ Mistrust
"))))

### Log (if any)

pSem::SEM(
          version = "0.19",
          models = list(list(name = "Model 1", syntax = list(columns = list("JaspColumn_19_Encoded", "JaspColumn_20_Encoded", "JaspColumn_21_Encoded", "JaspColumn_22_Encoded", "JaspColumn_23_Encoded", "JaspColumn_24_Encoded", "JaspColumn_25_Encoded", "JaspColumn_26_Encoded", "JaspColumn_27_Encoded", "JaspColumn_103_Encoded", "JaspColumn_104_Encoded", "JaspColumn_105_Encoded", "JaspColumn_106_Encoded", "JaspColumn_95_Encoded", "JaspColumn_96_Encoded", "JaspColumn_97_Encoded", "JaspColumn_98_Encoded", "JaspColumn_99_Encoded", "JaspColumn_100_Encoded", "JaspColumn_160_Encoded", "JaspColumn_128_Encoded", "JaspColumn_137_Encoded", "JaspColumn_138_Encoded", "JaspColumn_139_Encoded", "JaspColumn_140_Encoded", "JaspColumn_141_Encoded", "JaspColumn_142_Encoded", "JaspColumn_143_Encoded", "JaspColumn_144_Encoded", "JaspColumn_129_Encoded", "JaspColumn_130_Encoded", "JaspColumn_131_Encoded", "JaspColumn_132_Encoded", "JaspColumn_133_Encoded", "JaspColumn_134_Encoded", "JaspColumn_135_Encoded", "JaspColumn_136_Encoded", "JaspColumn_35_Encoded", "JaspColumn_47_Encoded", "JaspColumn_48_Encoded", "JaspColumn_38_Encoded", "JaspColumn_39_Encoded", "JaspColumn_44_Encoded"), model = "
CIQ =~ JaspColumn_19_Encoded + JaspColumn_20_Encoded + JaspColumn_21_Encoded + JaspColumn_22_Encoded + JaspColumn_23_Encoded + JaspColumn_24_Encoded + JaspColumn_25_Encoded + JaspColumn_26_Encoded + JaspColumn_27_Encoded
Avoidant_Style =~ JaspColumn_35_Encoded + JaspColumn_38_Encoded + JaspColumn_39_Encoded + JaspColumn_44_Encoded + JaspColumn_47_Encoded + JaspColumn_48_Encoded
Credulity =~ JaspColumn_99_Encoded + JaspColumn_100_Encoded + JaspColumn_106_Encoded
JaspColumn_160_Encoded =~ JaspColumn_95_Encoded + JaspColumn_96_Encoded + JaspColumn_97_Encoded + JaspColumn_98_Encoded + JaspColumn_103_Encoded + JaspColumn_104_Encoded + JaspColumn_105_Encoded
PTSD_DSM =~ JaspColumn_128_Encoded + JaspColumn_129_Encoded + JaspColumn_130_Encoded + JaspColumn_131_Encoded + JaspColumn_132_Encoded + JaspColumn_133_Encoded + JaspColumn_134_Encoded + JaspColumn_135_Encoded + JaspColumn_136_Encoded + JaspColumn_137_Encoded + JaspColumn_138_Encoded + JaspColumn_139_Encoded + JaspColumn_140_Encoded + JaspColumn_141_Encoded + JaspColumn_142_Encoded + JaspColumn_143_Encoded + JaspColumn_144_Encoded

Avoidant_Style ~ CIQ
Credulity ~ Avoidant_Style
JaspColumn_160_Encoded ~ Avoidant_Style 
PTSD_DSM ~ CIQ + Avoidant_Style + Credulity + JaspColumn_160_Encoded

Credulity ~~ JaspColumn_160_Encoded
", modelOriginal = "# latent variables
CIQ =~ CIQ_1 + CIQ_2 + CIQ_3 + CIQ_4 + CIQ_5 + CIQ_6 + CIQ_7 + CIQ_8 + CIQ_9
Avoidant_Style =~ RD12_1 + RD12_3 + RD12_4 + RD12_8 + RD12_10 + RD12_11
Credulity =~ ETS_7 + ETS_8 + ETS_14
Mistrust =~ ETS_3 + ETS_4 + ETS_5 + ETS_6 + ETS_11 + ETS_12 + ETS_13
PTSD_DSM =~ PTSD_1 + PTSD_2 + PTSD_3 + PTSD_4 + PTSD_5 + PTSD_6 + PTSD_7 + PTSD_8 + PTSD_9 + PTSD_10 + PTSD_11 + PTSD_12 + PTSD_13 + PTSD_14 + PTSD_15 + PTSD_16 + PTSD_17
# regressions
Avoidant_Style ~ CIQ
Credulity ~ Avoidant_Style
Mistrust ~ Avoidant_Style 
PTSD_DSM ~ CIQ + Avoidant_Style + Credulity + Mistrust
# residual (co)variances
Credulity ~~ Mistrust
"))))

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Please drag and drop the zipped file here on github.com. Attaching via mail does not work

**Comment by panosgl** [comment]
[Aftermath COVID-19_2024_new.jasp.zip](https://github.com/user-attachments/files/16948994/Aftermath.COVID-19_2024_new.jasp.zip)

**Comment by juliuspfadt** [comment]
Thank you. Two things, JASP should show the correct error message. I am working on a fix. The actual errors are (on my computer) with the Mardia's coefficient, if you uncheck that another error shows up that is connected to the path model plot. Unchecking that does eventually lead to the results showing up.

**Comment by panosgl** [comment]
HI, I unchecked the Mardia but it shows the same error message. I can't
find the second one that I have to uncheck

Panayiotis Lianos, MSc, PhD
Assistant Professor of School Psychology
School of Social Sciences
Department of Psychology
University of Ioannina 45110
Greece
tel: +30 2651005755


Στις Τρί 10 Σεπ 2024 στις 9:53 μ.μ., ο/η Julius Pfadt <
***@***.***> έγραψε:

**Comment by juliuspfadt** [comment]
You are right. my bad. I checked in R and the factor name "Mistrust" collides with the name of an observed variable in the data set. If you rename it should work. and forget what I mentioned about the madras coefficient, and the path plot. these were issues with my computer

**Comment by panosgl** [comment]
Perfect, it worked fine-so simple!
Another quick question: how do I edit plots? It says "can't be edited
because it was created with qgraph instead of ggplot"
Thank you,
Panayiotis Lianos, MSc, PhD
Assistant Professor of School Psychology
School of Social Sciences
Department of Psychology
University of Ioannina 45110
Greece
tel: +30 2651005755


Στις Τετ 11 Σεπ 2024 στις 3:06 μ.μ., ο/η Julius Pfadt <
***@***.***> έγραψε:

**Comment by tomtomme** [comment]
@panosgl 
In that case you can only export the plot to svg or pptx and edit in e.g. powerpoint or krita
