### ISSUE TITLE
[Bug]: wrong wording on homepage

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#2906]
### JASP Version

0.19.0

![grafik](https://github.com/user-attachments/assets/bc914884-fbd8-4f52-a185-80354524e375)

### Expected Behaviour

It is not named "windows store" anymore. 
Also make the buttons consistent accross the page always with OR without "version"

**Comment by boutinb** [comment]
Good remarks. I have updated the page https://jasp-stats.org/download/
