### ISSUE TITLE
[Bug]: Incorrect affiliation for a member of your scientific advisory panel (Prof Jon Forster) on Webpage 

### ISSUE THREAD

**Issue by TarandeepKang** [jasp-stats/jasp-issues#2907]
### JASP Version

0.19.0

### JASP Module

Other

### What OS are you seeing the problem on?

Windows 11

### Bug Description

Prof Forster is no longer at Southampton but is Head of Statistics at Warwick for approx. 5 years

### Expected Behaviour

accurate affiliation

### Steps to Reproduce

Incorrect info wherever details of advisory  board appear.  

### Log (if any)

na

### More Debug Information
https://warwick.ac.uk/fac/sci/statistics/staff/academic-research/forster/

Amusingly, even his Google Scholar is outdated, but you may confirm by searching affiliation on recent publications? 

https://scholar.google.co.uk/citations?hl=en&user=5x1VElYAAAAJ&view_op=list_works&sortby=pubdate

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Thanks. I have updated the site.
