### ISSUE TITLE
[Feature Request]: i suggest to add out of bag predctions to jasp machine learning random forest classfication model

### ISSUE THREAD

**Issue by medoteto** [jasp-stats/jasp-issues#2909]
### Description

i suggest to add out of bag predctions to jasp machine learning random forest classfication model

**Comment by koenderks** [comment]
Do you have a concrete use case for this? What would you want do with these predictions? Adding these to the data would be highly impractical since for a trained random forest algorithm with 100 trees this would amount to 100 columns. Currently, they are summarized in a figure.
