### ISSUE TITLE
JASP crashes when loading .txt (UTF-8) and .csv

### ISSUE THREAD

**Issue by malguen** [jasp-stats/jasp-issues#291]
* JASP version: 0.9.2
* OS name and version: macOS High Sierra Version 10.13.4 (17E199)
* Analysis:
* Bug description: JASP crashes when loading .txt (UTF-8; 10MB) and .csv (5MB) files
* Add JASP files as a zip:
* Screenshot: 
* Expected behaviour:
* Steps to reproduce: 
1. Go to 'Open > Browse > Downloads > select either .csv or .txt files' and then JASP immediately crashes

**Comment by boutinb** [comment]
Hi @malguen Can you send your data file in zip format?

**Comment by boutinb** [comment]
Hi @malguen I still don't see your ZIP file in this issue. Maybe you can send me it directly to b.boutin@uva.nl . I have tried also to load a file with a column Clock.Information and it worked without problem. So I would like really much to test with your data file.

**Comment by boutinb** [comment]
Hi @malguen Sorry, but I have not received any mail...

**Comment by malguen** [comment]
Hi @boutinb. Thank you for following up! I have emailed you again at b.boutin@uva.nl. Please let me know if you still don't find my email.

**Comment by boutinb** [comment]
Hi @malguen I have got your file! I know what is going wrong. But the time being, there is a workaround, just suppress the column Clock.information: it is an XML string that anyway does not have to be loaded in JASP, I suppose.

**Comment by malguen** [comment]
Hi @boutinb Thank you so much for your help! That makes sense that Clock.information has to be removed to load on JASP, which is consistent with what I have found. Thank you so much again!

**Comment by boutinb** [comment]
This will be solved next release
