### ISSUE TITLE
[Bug]: error

### ISSUE THREAD

**Issue by anikmonika** [jasp-stats/jasp-issues#2911]
### JASP Version

0.19.0

### JASP Module

Descriptives

### What OS are you seeing the problem on?

Windows 11

### Bug Description

everytime l go to descriptives statistic the bug keep appearing and make my work log out immedietly

### Expected Behaviour

error message keep appearing

### Steps to Reproduce

1. descriptives statistic
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Thx for the report.
Can you share the error Message and your zipped jasp file please?
