### ISSUE TITLE
[Feature Request]:Installing to driver other than C:?

### ISSUE THREAD

**Issue by oldHornPlayer** [jasp-stats/jasp-issues#2912]
### Description

Installing to driver other than C:?

### Purpose

Disk space management

### Is your feature request related to a problem?

I have limited space on my C: drive; would it be possible to install to the D: drive?

### Is your feature request related to a JASP module?

Other

### Describe the solution you would like

install to the D: drive

**Comment by tomtomme** [comment]
@oldHornPlayer 
As far as I remember the msi-installer allows this if you use the "advanced" button.
Also you could use the zip-install on any drive. And probably also the microsoft-store install should allow to switch drive (but that one I have not yet tested).
Does this help?
