### ISSUE TITLE
[Bug]: Group number doesn't update after filtering out some of them

### ISSUE THREAD

**Issue by nothik** [jasp-stats/jasp-issues#2916]
### JASP Version

0.19.0

### JASP Module

T-Tests

### What analysis are you seeing the problem on?

Independent Samples T-Test

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I have a grouping variable with 3 groups. When I filter out one of them, all corresponding entries appear in grey in the database. However, when I try running an independent samples t-test, I get an error message saying that there are 3 groups. Even when I use the edit function and completely delete the rows where the 3rd group appears, the system still remembers that there were initially 3 groups. 

### Expected Behaviour

The system should understand (as it did in previous versions of JASP) that there are now 2 groups remaining so that an independent samples t test is possible.

### Steps to Reproduce

1.Open a database with one grouping variables with 3 groups, and one numerical variable.
2.Filter out one group.
3.Try making a t-test.
...

### Final Checklist

- [x] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by nothik** [comment]
![image](https://github.com/user-attachments/assets/16b3c7b5-7842-4722-988b-3b28d0d9ead1)

**Comment by nothik** [comment]
I can't upload the .jasp file: 
![image](https://github.com/user-attachments/assets/94c2fe27-01e8-446d-a3ba-a20911badf75)

**Comment by EJWagenmakers** [comment]
This was the reason for our 0.19.1 hotfix I believe! Could you try the latest version? I am closing this issue in the expectation that 0.19.1 has it fixed. Feel free to re-open if that is not the case.
