### ISSUE TITLE
[Feature Request]: Add "Letter" size option for pdf output

### ISSUE THREAD

**Issue by idwidw** [jasp-stats/jasp-issues#2918]
### Description

A4 vs Letter format for pdf output

### Purpose

Add "letter" page size to options for Results Output function directed to a pdf file..

### Is your feature request related to a problem?

pdf files formatted for A4 page size do not print correctly in countries where "Letter" page size is the typical page size for printing.

### Is your feature request related to a JASP module?

Other

### Describe the solution you would like

Add an option to allow "Export Results" to a PDF file to choose between A4 and Letter page size options.

### Describe alternatives that you have considered

One can print A4 formatted pdf files using the "fit" option in Acrobat, but this wastes printing space.

### Additional context

I recognize that the A4 page size is the default for Europe. However, for the US and several other countries, the Letter page size is the default.

**Comment by boutinb** [comment]
The page size option exists in the Qt WebEngineView::printToPdf (https://doc.qt.io/qt-6/qml-qtwebengine-webengineview.html#printToPdf-method) we use, o it is something easy to implement. Maybe just a Preference setting will suffice.
