### ISSUE TITLE
[Bug]: Jasp will not open previously used file

### ISSUE THREAD

**Issue by ataylor92110** [jasp-stats/jasp-issues#2922]
### JASP Version

0.19.0

### Commit ID

icannotfindthis

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

Opening a file I previously saved in Jasp

### What OS are you seeing the problem on?

Windows 10

### Bug Description

First things first. I am a programming moron. I took a Fortran class around 1975 with punch cards (they made nice Christmas wreaths when spray painted gold and put on a wire circle ;-) but have not touched programming since then. 

When I try to open my file with analyses it won't open. It is large but I don't know how to "fix" that. I included here two screen shots:
(1) of the csv file size and the same file saved as a jasp file with analysis.
(2) the task manager in case that tells you anything (It tells me nothing)![Screenshot 2024-09-21 150156](https://github.com/user-attachments/assets/289ef0b2-29db-4ee0-965c-407e83e2f696)
![Screenshot 2024-09-21 150110](https://github.com/user-attachments/assets/aebe89c8-9530-4c4f-a246-54cc3e711b2d)

When I try to open my file with analyses it won't open. It is large but I don't know how to "fix" that. I included here two screen shots:
(1) of the csv file size and the same file saved as a jasp file with analysis.
(2) the task manager in case that tells you anything (It tells me nothing)

Here is the data file, zipped.  Even the zipped JASP file was too large to attach here; it was 27 Mb
[F23S24combo.zip](https://github.com/user-attachments/files/17085901/F23S24combo.zip)

### Expected Behaviour

The file should have opened up with the my analyses so I can work on them. 

### Steps to Reproduce

1. Select JASP file from menu
2. Wait while it's opening
3. Click anywhere and "X" in upper right corner turns red.
4.
5.
...

### Log (if any)

I'm not sure which file you need but these look all wrong based on dates because it looks like September 21 instead of today or yesterday. But it's all I've got. 
[JASP 2024-09-21 14_59_24 Desktop.log](https://github.com/user-attachments/files/17085888/JASP.2024-09-21.14_59_24.Desktop.log)
[JASP 2024-09-21 14_59_24 Engine 0.log](https://github.com/user-attachments/files/17085889/JASP.2024-09-21.14_59_24.Engine.0.log)
[JASP 2024-09-21 14_59_50 Desktop.log](https://github.com/user-attachments/files/17085890/JASP.2024-09-21.14_59_50.Desktop.log)
[JASP 2024-09-21 14_59_50 Engine 0.log](https://github.com/user-attachments/files/17085891/JASP.2024-09-21.14_59_50.Engine.0.log)

### More Debug Information

-------- Application Info --------
JASP Version: JASP 0.19.1
Build Branch: lockfiletesting
Build Date: Sep  9 2024 19:00:04 (Netherlands)
Last Commit: 8ac10c9c7aec029fdd695262d7bb4c3742a8ec89

-------- Basic Info --------
Operating System: Windows 11 Version 23H2
Product Version: 11
Kernel Type: winnt
Kernel Version: 10.0.22631
Architecture: x86_64
Install Path: C:/Program Files/WindowsApps/45842JASP.JASP_0.19.1.0_x64__wz6q9dg667qsj
Platfotm Name: windows
System Local: en_US

-------- Extra Info --------
Current code page
Active code page: 437
Active code page: 65001

Host Name:                 DESKTOP-MJVEMTG
OS Name:                   Microsoft Windows 11 Home
OS Version:                10.0.22631 N/A Build 22631
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          wearethetaylors gmail.com
Registered Organization:   N/A
Product ID:                00356-02710-59835-AAOEM
Original Install Date:     11/13/2022, 8:33:35 AM
System Boot Time:          9/20/2024, 12:56:56 PM
System Manufacturer:       LENOVO
System Model:              82R7
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 154 Stepping 4 GenuineIntel ~1200 Mhz
BIOS Version:              LENOVO J7CN50WW, 6/18/2024
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-08:00) Pacific Time (US & Canada)
Total Physical Memory:     5,703 MB
Available Physical Memory: 754 MB
Virtual Memory: Max Size:  23,111 MB
Virtual Memory: Available: 13,790 MB
Virtual Memory: In Use:    9,321 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\DESKTOP-MJVEMTG
Hotfix(s):                 5 Hotfix(s) Installed.
                           [01]: KB5042099
                           [02]: KB5012170
                           [03]: KB5027397
                           [04]: KB5043076
                           [05]: KB5043937
Network Card(s):           3 NIC(s) Installed.
                           [01]: Intel(R) Wireless-AC 9560
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                           [02]: Aruba Virtual Adapter
                                 Connection Name: Local Area Connection
                                 Status:          Hardware not present
                           [03]: Aruba L2 Virtual Adapter
                                 Connection Name: Ethernet 2
                                 Status:          Hardware not present
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JorisGoosen** [comment]
@ataylor92110 looks like your datafile is not so big.

How many analyses are you adding?
And what kinds?
Only ANOVA's?

**Comment by ataylor92110** [comment]
I don't need to add more analyses, I just want to open the file and use the
ones I have in a manuscript. I need to share the results of the analyses
with my collaborators.

But it won't even open. It just freezes the program and the only way to
close out of it is to use the task manager. Just clicking the X does not
close it. It is truly frozen.

And yes, I mostly did Anova and t-test and some descriptives and I always
get the graphs. I think maybe the graphs add too much to the size of the
file???

Thanks for the response, I hope we can get me moving forward soon! I have
been having many problems with JASP of late :-(

Annette

Annette Kujawski Taylor, Ph.D.

she/her/hers ("What Are Personal Pronouns & Why Do They Matter?"
<https://www.mypronouns.org/what-and-why>)
Professor, Emerita, Psychological Sciences
University of San Diego
***@***.***

**Comment by tomtomme** [comment]
Can you try uploading the file to osf.io and see if the results display there when shown online in a browser?

**Comment by ataylor92110** [comment]
Oh. That worked!

I already have an OSF account so I created a new project for this because I
did not pre-register it earlier (goes back to being a baby when it comes to
understanding how tech works and find the whole preregistration process to
be a gross mystery despite watching videos, etc. SIGH (this all makes me so
tired, which is why I re-tired because I was tired over and over and over
again).

Anway, that old person digression aside, yes there they are displayed,
graphs and all!

Thank you.

But here is a follow up question: If my collaborator looks at this and
says, hmmm...let's add on an analysis, then how can I open the file? Would
I need to create a new JASP file from the original csv file? Would that be
best?

Thank you again. Sorry this is all so confusing to me.

(and now I can go back and build the preregistration a bit late)

Annette

Annette Kujawski Taylor, Ph.D.

she/her/hers ("What Are Personal Pronouns & Why Do They Matter?"
<https://www.mypronouns.org/what-and-why>)
Professor, Emerita, Psychological Sciences
University of San Diego
***@***.***

**Comment by tomtomme** [comment]
Yeah starting from scratch with the csv would be an option. But if your collaborator can ooen the current jaspfile from osf he can maybe axe some unneded analysis, so that you can open it too again?

**Comment by ataylor92110** [comment]
But I don't know how to axe the unneeded analyses if I cannot open the file.

I see the output in OSF but I cannot edit that output and then download the
edited file.

I am back to chasing my tail in a circle.

Thanks, again. I truly do very much appreciate the help because I truly am
barely literate in these things despite a lifetime of using some program or
other. The problem with "using a program" is I never understood the magic
in the coding.

I actually don't mind starting new analyses in a new file. I had to hand
analyze my thesis data in the 1970s so this is a great improvement!

Incidentally, I am able to open much smaller files in JASP on my laptop,
which is why I think I just don't have the computing power for opening a
larger file. The university no longer buys my laptops for me ;-) and I have
to be budget-conscious.
Annette


Annette Kujawski Taylor, Ph.D.

she/her/hers ("What Are Personal Pronouns & Why Do They Matter?"
<https://www.mypronouns.org/what-and-why>)
Professor, Emerita, Psychological Sciences
University of San Diego
***@***.***

**Comment by tomtomme** [comment]
> But I don't know how to axe the unneeded analyses if I cannot open the file.

That is why I thought your colleague / collaborator could dowload the file for you and axe analysis. But I also can try if you send it to thomas.langkamp@medicalschool-hamburg.de

Or if you post the osf link

**Comment by ataylor92110** [comment]
Ok. I'm not at home right now and with the time change you will be done for
today but I will send it so you have it tomorrow. Good deal. Maybe your can
figure out why I have a problem.

**Comment by tomtomme** [comment]
Yeah - opens fine on my end. Any idea which analysis I could axe? There are like 30 rm anovas...
also it might just need very long on your end to open - how long have you given it?
Have you tried opening it after a fresh restart and maybe closing some background tasks before so that your RAM is not already filled up (like closing antivir stuff, dropbox etc. temporarily)

**Comment by tomtomme** [comment]
there you go:
[F23S24combo.zip](https://github.com/user-attachments/files/17117175/F23S24combo.zip)

you could re-add the accuracy-anovas by saving the jasp file under a different name and do those there.
Also if you again want to add more / other analysis just safe under a new name to have like 15 analyis max per file maybe.
hope this helps.

**Comment by ataylor92110** [comment]
Awesome, thank you so much!

I will try to break up analyses into files and label the files with what's
in them :-)

Annette




Annette Kujawski Taylor, Ph.D.

she/her/hers ("What Are Personal Pronouns & Why Do They Matter?"
<https://www.mypronouns.org/what-and-why>)
Professor, Emerita, Psychological Sciences
University of San Diego
***@***.***

**Comment by tomtomme** [comment]
Nice. So I will close this one for now. Feel free to reopen if needed.

**Comment by ataylor92110** [comment]
Ok, thanks.


Annette Kujawski Taylor, Ph.D.

she/her/hers ("What Are Personal Pronouns & Why Do They Matter?"
<https://www.mypronouns.org/what-and-why>)
Professor, Emerita, Psychological Sciences
University of San Diego
***@***.***
