### ISSUE TITLE
[Bug]: independent t sample not loading .

### ISSUE THREAD

**Issue by Coy96** [jasp-stats/jasp-issues#2923]
### JASP Version

0.19.0

### JASP Module

T-Tests

### What analysis are you seeing the problem on?

Independent t test 

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

Independent t test sample not loading. 

### Expected Behaviour

The other ones like one sample test load fine but the independent one doesn’t give out numbers 

### Steps to Reproduce

1.upload
 Date 
2.click t test
3.click independent 
4. Choose the variable 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by Coy96** [comment]
![Uploading Screenshot 2024-09-08 12.41.36 PM.png…]()

**Comment by tomtomme** [comment]
Thx for the report. The screenshot does not load. Sharing your zipped jasp file would als be needed. Also make sur to try with jasp 0.19.1
