### ISSUE TITLE
Comments font colour

### ISSUE THREAD

**Issue by DrMarkGS** [jasp-stats/jasp-issues#293]
I see that EJ raised this back in 2016
* Enhancement:
The be able to change font colour in the comments box or add custom text boxes
* Purpose:
As part of their statistics assessments - students upload their commented JASP files.  In order to provide visible feedback I would like to add praise/comments/suggestions/ errors to these files.  I think this would be valuable to lecturers who are increasing using JASP to teach statistics.

Cheers
Mark

**Comment by JorisGoosen** [comment]
I think @akashrajkn had a look at this before, maybe he can shed some light on this.
