### ISSUE TITLE
 The distribution options within the descriptive function flash and the skew value appears as an error.

### ISSUE THREAD

**Issue by MIAcuna** [jasp-stats/jasp-issues#2930]
### JASP Version

0.19.0

### JASP Module

Descriptives

### What analysis are you seeing the problem on?

Distribution

### What OS are you seeing the problem on?

Other

### Bug Description

The distribution options within the descriptive function flash and the skew value appears as an error.

### Expected Behaviour

<img width="644" alt="Captura de pantalla 2024-09-24 a la(s) 12 31 29 p  m" src="https://github.com/user-attachments/assets/ec88ef45-6e46-4444-8b14-f8a8e0ca3dd6">

### Steps to Reproduce

Run the analysis. 

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@MIAcuna 
thx for the report. 
Can you share more details? E.g. on:

- [ ] full screenshot (yours is cut of)
- [ ] zipped jasp-file
- [ ] details about your MacOS (via jasp main menu => about => copy debug info

thx
