### ISSUE TITLE
[Bug]: Cannot perform sphericity test because there are only two levels of the RM factor, or because the SSP matrix is singular

### ISSUE THREAD

**Issue by lawriesm** [jasp-stats/jasp-issues#2932]
### JASP Version

0.18.0

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

Repeated Measures ANOVA

### What OS are you seeing the problem on?

Windows 10

### Bug Description

Running a simple 1-way repeated measures ANOVA with 1 RM factor with 3 levels, but I get the bug "Cannot perform sphericity test because there are only two levels of the RM factor, or because the SSP matrix is singular". Error is independent of names given
![image](https://github.com/user-attachments/assets/b4b3b4a8-e44e-411c-ad9e-4f7c6d5817cf)

### Expected Behaviour

There should be a test for sphericity and adjusted values in the ANOVA table

### Steps to Reproduce

1. Load csv/jasp file
2. Click to launch repeated measures dialogue box
3. Move 3 variables to the Repeated Measures cells box
4. Under "Assumptions" click "Sphericity Tests"
...

### Log (if any)

[JASP 2024-09-25 17_18_15 Desktop.log](https://github.com/user-attachments/files/17134871/JASP.2024-09-25.17_18_15.Desktop.log)
[JASP 2024-09-25 17_36_39 Desktop.log](https://github.com/user-attachments/files/17134872/JASP.2024-09-25.17_36_39.Desktop.log)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JohnnyDoorn** [comment]
Hi @lawriesm ,

Thanks for your report, are you able to share your data as a .csv or .jasp file? You can upload them here as a zipped file. That will help me figure out what is going wrong.

Cheers,
Johnny

**Comment by lawriesm** [comment]
Hi Johnny,

Absolutely. I've attached it as a zipped Jasp file as requested. If you
need anything else just ket me know.

I'm going to try a newer version tomorrow, but our students are still on
this version, so any help/guidance is greatly appreciated.

Thanks and best regards,

Lawrie

**Comment by lawriesm** [comment]
[Body Image Data Set Week 4 Workshop.zip](https://github.com/user-attachments/files/17135590/Body.Image.Data.Set.Week.4.Workshop.zip)
Hi Jonny,
Sorry about that.  I've attached it here and hopefully this time you'll get it.
All the best,
Lawrie

**Comment by JohnnyDoorn** [comment]
Hi Lawrie,

Thanks, I had a look at your data, and I am getting the same error about a singular SSP matrix in R when conducting the RM ANOVA. This happens when there is a high degree of correlation between your repeated measures, and/or little variation. It does look like your rm measures are highly correlated, but not outlandishly so (approx 0.7 between before-halfway, and after-halfway). Is this an educational data set? If so, maybe you can introduce some additional noise to the measures and see if that improves the singularity error? You could also fit a mixed effects model instead of the rm anova if that fails. 

Kind regards,
Johnny

**Comment by lawriesm** [comment]
Hi Johnny,
It is an old dataset that we've used each year, but we've only this year moved to JASP from SPSS so it's the first time we've had the error.  I'll see if I can add some random noise to get it working tomorrow and get back to you, as I'm really not keen or returning to SPSS.
All the best,
Lawrie

**Comment by JohnnyDoorn** [comment]
Hi @lawriesm,

Ah I understand - for what it's worth, here is an updated csv with a bit of noise introduced to the before stroop column. Now the sphericity test works (while still having the same effects), but it does seem like there is a very high degree of sphericity.
[stroop_noisy.csv](https://github.com/user-attachments/files/17145941/stroop_noisy.csv)


Cheers
Johnny

**Comment by lawriesm** [comment]
Hi Johnny,
Thanks so much for that, it's very much appreciate it.  We'll use the updated data and the high sphericity isn't necessarily a bad thing as we'll use it as a demonstration in the lesson.  I'll be sure to check the correlation of our demo datasets in future and now I know a bit of noise can help there.
Thanks again and all the best,
Lawrie
