### ISSUE TITLE
[Bug]: Custom Contrast

### ISSUE THREAD

**Issue by Liz-d4** [jasp-stats/jasp-issues#2933]
### JASP Version

0.19.0

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

two-way OMNIBUS ANOVA

### What OS are you seeing the problem on?

Windows 11

### Bug Description

![JASP_Bug](https://github.com/user-attachments/assets/83230e86-fb67-4fbc-9d45-a1f5793e323c)

### Expected Behaviour

Expected: option to conduct custom contrasts with appropriate coefficients

### Steps to Reproduce

1. Conduct ANOVA
2. Select Contrast drop down
3. Select 'custom' on the interactive effect 
4. Bug appears
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JohnnyDoorn** [comment]
Hi @Liz-d4 ,

Could you maybe share your .jasp file (by uploading it as a zip file) - then I can look where it goes wrong, because as far as I know the custom contrasts work here. 

Cheers 
Johnny
