### ISSUE TITLE
[Feature Request]: How can I import an excel file database for analysis?

### ISSUE THREAD

**Issue by rgorta** [jasp-stats/jasp-issues#2938]
### Description

Excel data base analysis

### Purpose

Import excel database

**Comment by tomtomme** [comment]
You mean xlsx? Save as ods and open that with jasp

**Comment by rgorta** [comment]
Super thanks!!!
Rocío

**Comment by EJWagenmakers** [comment]
Also, we have this functionality under development and it should make it into our next release, so I am closing this issue.
EJ
