### ISSUE TITLE
[Bug]: Independent samples t-test error with Q-Q plots when missing data is present

### ISSUE THREAD

**Issue by Alejandro-84** [jasp-stats/jasp-issues#2939]
### JASP Version

0.19.0

### JASP Module

T-Tests

### What analysis are you seeing the problem on?

Independent Samples T-Test

### What OS are you seeing the problem on?

Windows 10

### Bug Description

When I run an independent samples t-test and check the box for "Q-Q plot residuals" under the "Assumption Checks" section, I get the Q-Q plot as expected (two groups of n = 6 each):

![image](https://github.com/user-attachments/assets/82117c89-579e-4199-9f03-c13f0b2b9b0b)

However, if I perform the same steps using the same variable but with one group having one missing value (two groups: group 1, n = 6; group 2, n = 5 [1 score missing]), the analysis stops, and I get this error message:

![image](https://github.com/user-attachments/assets/f723b58f-1119-439c-b1b0-8776b1366853)

This problem disappears when the option of "Missing values" changes from "Exclude cases per dependent variable" to "Exclude cases listwise".

"Exclude cases per dependent variable" option:
![image](https://github.com/user-attachments/assets/84b80420-3b4f-43cf-9102-f22843425ca6)

"Exclude cases listwise" option:
![image](https://github.com/user-attachments/assets/21575606-0e5a-436c-805c-ee85097608e5)

 What is interesting is that if you perform the test by using ANOVA, this problem does not occur.

ANOVA with all cases (two groups, n = 6 per group):

![image](https://github.com/user-attachments/assets/c23c5c6b-f070-4bb8-b751-7fe9427e7f8a)

ANOVA with one missing score (two groups: group 1, n = 6; group 2, n = 5 [1 score missing]):

![image](https://github.com/user-attachments/assets/cd2b047b-92f4-4ae4-9051-f3403aac78b5)

This is the dataset I used. 
[T-test.qq.zip](https://github.com/user-attachments/files/17186061/T-test.qq.zip)

### Expected Behaviour

The Q-Q plot should be generated even though one group presents missing values (such as in ANOVA). 

### Steps to Reproduce

1. Open JASP, have two dependent variables, one with full cases and another with at least one missing score, and one categorical independent variable.
2. Open the T-Tests module and select the Independent Samples T-Test option.
3. Drop the dependent variable with complete scores into the "Dependent Variables" box and add the independent variable into the "Grouping variable" box. Check the "Q-Q plot residuals" box under "Assumption checks." All should run normally. 
4. Drop the dependent variable with missing scores into the "Dependent Variables" box and add the independent variable into the "Grouping variable" box. Check the "Q-Q plot residuals" box under "Assumption checks"; the error window should appear.
...

### More Debug Information

-------- Application Info --------
JASP Version: JASP 0.19.1
Build Branch: lockfiletesting
Build Date: Sep  9 2024 19:00:04 (Netherlands)
Last Commit: 8ac10c9c7aec029fdd695262d7bb4c3742a8ec89

-------- Basic Info --------
Operating System: Windows 10 Version 22H2
Product Version: 10
Kernel Type: winnt
Kernel Version: 10.0.19045
Architecture: x86_64
Install Path: C:/Program Files (x86)/JASP
Platfotm Name: windows
System Local: en_CA

-------- Extra Info --------
Current code page
Active code page: 437
Active code page: 65001

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@Alejandro-84 
thx for the report. Confirmed on 0.19.1 flatpak. Also confirmed if missing is not at the end of the data set and if missing is coded as missing value.
