### ISSUE TITLE
[Bug]: Process (beta) module: Adding/removing conditional continuous effects to probe does not automatically update results

### ISSUE THREAD

**Issue by rphars** [jasp-stats/jasp-issues#2942]
### JASP Version

Others

### JASP Module

Process

### What analysis are you seeing the problem on?

Classical process model

### What OS are you seeing the problem on?

Windows 10

### Bug Description

When running a classical process model (I tried Hayes configuration, model 1), the advanced tab contains the option to probe conditional continuous effects. If the values to probe the effects at are added, removed or changed in any way, the output (tables) is not automatically updated to reflect these changes. See screenshot in which I removed the 50th percentile, but it is still visible in the output.

![jasp-br](https://github.com/user-attachments/assets/83004f4d-39e8-4391-a198-1369fe147f77)

Output is updated (with the correct percentiles) as soon as the model is re-estimated (e.g. estimator or missing value handling is changed).

Note: I'm running 0.19.1, the option was not selectable in the bug report window yet.

### Expected Behaviour

Output (specifically: tables) should be automatically updated to reflect the change in values selected by the user.

### Steps to Reproduce

1. Run Hayes configuration model 1 with one dv, one iv and one moderator in the classical process model and set them as independent X and moderator W.

2. Subsequently: add, remove or change values where conditional continuous effects are probed.

I tried multiple (very small) datasets and also tried model 2, same issue. I did not try the 'paths' input type.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@maltelueken 
Can you reproduce this one?

@rphars 
thx for the report

**Comment by maltelueken** [comment]
The Nightlies are currently not working for me, but I will look into this once they are working again.
