### ISSUE TITLE
[Bug]: Filter function does not affect the results in the computed columns

### ISSUE THREAD

**Issue by Alejandro-84** [jasp-stats/jasp-issues#2945]
### JASP Version

0.19.0

### JASP Module

Other

### What analysis are you seeing the problem on?

Computed variables

### What OS are you seeing the problem on?

Windows 11

### Bug Description

I have a variable with 20 scores (adult years of age), and one of them is a data entry error (200). If I calculate the mean using the Descriptive statistics module, I get a mean of 72.5

![image](https://github.com/user-attachments/assets/98b36ded-0af9-4776-a5f6-2c185efef48a)

If I use the label editor to filter that case out, I get the right statistics (e.g., mean = 65.8)
![image](https://github.com/user-attachments/assets/848c37c7-e4fa-4711-befd-3393158a8ca3)

![image](https://github.com/user-attachments/assets/4b859f09-148f-4036-9111-ba9421454925)

However, when I calculated the standardized scores (z-scores) using the zScores function in JASP, I realized it still considers the filtered case for the calculation.

![image](https://github.com/user-attachments/assets/8e91bbb6-9290-407a-aa34-c5138f7b2522)

![image](https://github.com/user-attachments/assets/2db55aec-4351-400e-bddd-ae21aa742da4)

Which led to incorrect z-scores.

I tried with another function, in this case the mean function and it returned a mean of 72.55, including the 20 cases, even though the filter is still active. 

![image](https://github.com/user-attachments/assets/a2ef5608-183c-4bb7-96bd-f2b630f65291)

And the max function returns the 200 scores (even though it was filtered out)

![image](https://github.com/user-attachments/assets/ffdb8424-96ab-4d83-9114-296feb6df4d5)

However, if I add this number (200) to the missing values list, it is not a problem anymore. The z-score was not calculated for this score.

![image](https://github.com/user-attachments/assets/abe1f117-1960-4a78-8db7-6779b86d74c2)

And the mean function returns the mean that excludes that case (i.e., 65.8):

![image](https://github.com/user-attachments/assets/5228410b-c39d-4e3a-be2c-7440bd690a8b)

And the max function returns 80

![image](https://github.com/user-attachments/assets/00eda5a5-998f-4017-be53-565145e1bf5c)

So, I wonder if this issue also happens with all the other functions. 

This is the dataset I used. 
[age.zip](https://github.com/user-attachments/files/17218451/age.zip)

### Expected Behaviour

The filter function should exclude the filtered cases from the calculations, just as it excludes them from the other JASP modules. 

### Steps to Reproduce

1. Create a new column (variable), and calculate the z-scores from the original variable using the z-Scores function (this also applies to the mean and max functions).
2. Filter out the data entry error using the label editor. The z-scores will not change (the data entry error is not excluded).
3. Add the data entry error to the missing values list. The z-scores will change (the data entry error is excluded)
4. Open the descriptive statistics module; the results from either the label editor (filter) or the missing values list will be the same (both filter the data entry error).
...

### More Debug Information

-------- Application Info --------
JASP Version: JASP 0.19.1
Build Branch: lockfiletesting
Build Date: Sep  9 2024 19:00:04 (Netherlands)
Last Commit: 8ac10c9c7aec029fdd695262d7bb4c3742a8ec89

-------- Basic Info --------
Operating System: Windows 11 Version 23H2
Product Version: 11
Kernel Type: winnt
Kernel Version: 10.0.22631
Architecture: x86_64
Install Path: C:/Program Files (x86)/JASP
Platfotm Name: windows
System Local: en_CA

-------- Extra Info --------
Current code page
Active code page: 437
Active code page: 65001

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@Alejandro-84 
thx for the very detailed bug report!
However we are already aware, see: https://github.com/jasp-stats/jasp-issues/issues/2553
So I have to close this as a duplicate. Please reopen if you disagree!
And maybe next time just upload the .jasp zipped here, then you do not have to create so many screenshots.
