### ISSUE TITLE
[Bug]: In the Lavaan program, when a "label" is set on a path and then executing, if you check the box to obtain the standardized value of the path coefficient, an error message will be reported.

### ISSUE THREAD

**Issue by akwan168** [jasp-stats/jasp-issues#2948]
### JASP Version

0.19.0

### JASP Module

SEM

### What analysis are you seeing the problem on?

structural eqution modeling

### What OS are you seeing the problem on?

Windows 10

### Bug Description

When labels are set on the path in the Lavaan, and these labels will be used for future calculations (for example, calculating mediation effects, total effects), if "standardized estimates" is not checked, SEM can execute successfully, but if "standardized estimates" is checked , JASP will report an error.
Please watch the video: https://youtu.be/xMSLNyGiJeI

### Expected Behaviour

Please watch the video: https://youtu.be/xMSLNyGiJeI

### Steps to Reproduce

1. Please download the data files: https://reurl.cc/1b7ZOV
2. Please watch the video: https://youtu.be/xMSLNyGiJeI
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment]
thanks for creating the issue. This is already fixed by https://github.com/jasp-stats/jaspSem/pull/248 and will be available in the next release of JASP.
