### ISSUE TITLE
[Bug]: Do we follow Qt or Apple/MS support window?

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#2949]
### JASP Version

0.19.1

### Bug Description

Support status of MacOS 12: Unsupported by Apple as of September 16, 2024, see https://en.wikipedia.org/wiki/MacOS_Monterey
But Qt 6.17 still supports it. Whom do we follow?

**Comment by shun2wang** [comment]
We are following build system and dependencies support on platforms.  it is still supported both by R(macOS11+) and Qt(macOS12+), so we shoud keep to support it:-)

0.19.1 version had added in issue report.

**Comment by tomtomme** [comment]
okay thx for the eyplainer. I thought we followed the apple-support. 
So I will leave this open for maybe 0.20 because Qt will likely loose support for macOS 12 in the not to distant future.

**Comment by tomtomme** [comment]
So I just read, when we switch to qt 6.18 LTS in the future, even that one will still support macOS 12. 
And also I just learned that qt 6.17 still supports macOS 11

So is this really what we do @boutinb ? Do we follow apple support or Qt support window? Atm our homepage says we follow apple. If not we should change the wording on our download-page from:

"Apple no longer supports macOS 11 (Big Sur) and below. Please upgrade your OS or use an older version of JASP instead."

to 

"JASP/Qt no longer supports macOS 10.15 (Catalina) and below. Please upgrade your OS or use an older version of JASP instead."

and below to

"Apple: MacOS BigSur 11 or higher, with an Apple Silicon or Intel processors. iPad OS and iOS devices are not supported¹."

**Comment by boutinb** [comment]
We should support only what Apple support (that does not mean that it does not work). So when we release 0.19.2 we should update the WebSite to say we don't support MacOS 12 (Monterey) anymore.

**Comment by tomtomme** [comment]
related: #2721

**Comment by tomtomme** [comment]
Nice release!!! :D
On the homepage the system requirements still need to be updated:


Apple: MacOS Monterey ### 13 or higher, with an Apple Silicon or Intel processors. iPad OS and iOS devices are not supported¹.

**Comment by tomtomme** [comment]
Same for windows, if we also follow Microsofts support window we should up from win10 2004 to 
Version 22H2 	
which is currently the only supported win10 version

"Microsoft: Windows 10 version _**22H2**_ or higher are supported. Devices with ARM processors² including tablets with Qualcom Snapdragon are supported in combination with Windows 11."

**Comment by boutinb** [comment]
> Apple: MacOS **_Ventura 13_** or higher, with an Apple Silicon or Intel processors. iPad OS and iOS devices are not supported¹.

The current sentence _Apple no longer supports macOS 12 (Monterey) and below_ is correct, but you are right: it's better to use a positive sentence, than a negative one.

**Comment by boutinb** [comment]
Windows 10 22H2 with ARM does not work ?

**Comment by boutinb** [comment]
Ah yes! Thanks!
