### ISSUE TITLE
Can't display conditional estimate plot for binary regression

### ISSUE THREAD

**Issue by gustavobrp** [jasp-stats/jasp-issues#295]
JASP VERSION: 0.9.2
OS: WINDOWS 10 64 BIT
ANALYSIS: Binary Logistic Regression > Display conditional estimate plots
DESCRIPTION: Trying to get a display conditional estimate plot for the results of a binary logistic regression model. I receive the following message instead: 

"This analysis terminated unexpectedly.

Error in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : Metric information not available for this family/device

Stack trace
grid.draw.gTree(x$children[[i]], recording = FALSE)

recordGraphics(drawGTree(x), list(x = x), getNamespace('grid'))

drawGTree(x)

grid.draw(x$children[[i]], recording = FALSE)

grid.draw.grob(x$children[[i]], recording = FALSE)

recordGraphics(drawGrob(x), list(x = x), getNamespace('grid'))

drawGrob(x)

drawDetails(x, recording = FALSE)

drawDetails.text(x, recording = FALSE)

grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, resolveHJust(x$just, x$hjust), resolveVJust(x$just, x$vjust), x$rot, x$check.overlap)"

![image](https://user-images.githubusercontent.com/47039230/51935513-3da5ad00-23ed-11e9-848e-dec8138324c2.png) 
![image](https://user-images.githubusercontent.com/47039230/51935591-5f9f2f80-23ed-11e9-9468-c29f4d26798e.png)

Thanks in advance.

**Comment by boutinb** [comment]
@vandenman Can you have a look to this problem?

**Comment by vandenman** [comment]
Hi, this looks like a machine specific issue. Does the error also occur when you try to create a plot in a different analysis, for example, the density plots in descriptives?

**Comment by gustavobrp** [comment]
Hi guys, thanks for the help. The density plot for the age variable in my database worked. 

![image](https://user-images.githubusercontent.com/47039230/52414134-9f8ba400-2aca-11e9-961b-210ca8b5c1b1.png)

**Comment by vandenman** [comment]
That's odd. In your first screenshot, I noticed that there are some nonstandard characters in the name of the dependent variable (e.g., Ã). Does the error persist if you change the variable name into something else, using only the Roman alphabet without any accents?

**Comment by gustavobrp** [comment]
Ok! Tried that and changed the characters, but now it gives another error. See below.

Error in loadNamespace(name): there is no package called 'withr'

Stack trace
f(...)

with_seed_null(params$seed, transform_position(data, trans_x, trans_y))

withr::with_seed

getExportedValue(pkg, name)

asNamespace(ns)

getNamespace(ns)

tryCatch(loadNamespace(name), error = function(e) stop(e))

tryCatchList(expr, classes, parentenv, handlers)

tryCatchOne(expr, names, parentenv, handlers[[1]])

value[[3]](cond)

![image](https://user-images.githubusercontent.com/47039230/52416208-3c047500-2ad0-11e9-83e3-8e738e6a054f.png)

**Comment by vandenman** [comment]
Thanks for the quick reply! I can reproduce this issue. Can you also copy-paste the name of the dependent variable you were using before? That way we can try to sort out why that one crashed as well.

**Comment by gustavobrp** [comment]
Hi, sorry for taking too long to answer. The name of the dependent variable was "TP_SITUAÇÃO_FINAL_BIN" and i changed later for the test to: "TP_SITUACAO_FINAL_BIN".

**Comment by gustavobrp** [comment]
I know this is closed, but, I tried again to display the conditional estimate plot and didn't worked. Some news about this issue?
