### ISSUE TITLE
[Bug]: Cannot type in letter "y"

### ISSUE THREAD

**Issue by Dan-csvfile** [jasp-stats/jasp-issues#2951]
### JASP Version

0.19.1

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

n/a

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

When I want to manually add new data in JASP via the 'New Data' button, I can type in any letter EXCEPT "y." I have not had any issues with typing "y" until now. The only thing that changed (software-wise) is that I have updated my Mac software, but I do not know if this caused the bug. I have deleted and re-downloaded JASP and ensured that the column type is set to 'Nominal,' but I still cannot type in the forbidden letter "y." Can someone help me out?

### Expected Behaviour

I should be able to type "y" like any other letter into my data set.

### Steps to Reproduce

1. Opened JASP.
2. Clicked on 'New Data.'
3. Double-clicked on the first column to change column info (name: tonsillectomy, column type: nominal).
4. Clicked on the first box under the 'tonsillectomy' column to enter my values (i.e., yes/no).
5. When pressing on the 'y' button, nothing appears on the screen, but I can type in 'es' and 'no,' or any other letter, with no problem

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
This is indeed a weird bug... This will be solved in the next release.
For the time being, the best thing to do is to copy paste the string you want to insert in a cell.
