### ISSUE TITLE
[Feature Request]: add option to configure ribbon bar size (include button and menu in the ribbon)

### ISSUE THREAD

**Issue by armgong** [jasp-stats/jasp-issues#2952]
### Description

currently the default ribbon bar size is too big, especially for small screen. Have options to configure ribbon bar size will solve this

### Purpose

have options to configure the ribbon bar size

**Comment by tomtomme** [comment]
We have this under settings, interface. There you can zoom,jasps interface. Also with strg++ or -- shortcuts. Is this suficient? Results can be zoomed separately via strg+mouswheel

**Comment by armgong** [comment]
@tomtomme the zoom function will make whole interface bigger or smaller, but  I prefer only change the ribbon bar size (its  kind of waste screen show area now), and keep the other part of UI unchanged

**Comment by JorisGoosen** [comment]
It is kind a big yeah

**Comment by boutinb** [comment]
Fixed by https://github.com/jasp-stats/jasp-desktop/pull/5746
