### ISSUE TITLE
ANOVA post-hoc tests: Tukey LSD vs. HSD

### ISSUE THREAD

**Issue by Robert-M-French** [jasp-stats/jasp-issues#2953]
### JASP Version

0.19.1

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

post-hoc tests

### What OS are you seeing the problem on?

Windows 11

### Bug Description

[Bug]: When I do a Classical ANOVA in JASP version 0.19.1 and click on the post-hoc tab with, for example, a Bonferroni correction, the output says "Standard (LSD)" and then shows the comparisons.  But, perhaps I'm wrong, but no one used LSD (Least Significant Difference) anymore, just like Newman-Keuls anymore.  Tukey HSD (Honest Significant Difference) is generally the preferred post-hoc.  Is the heading "Standard (LSD)" a typo that should read "Standard (HSD)" or is the analysis really a Tukey LSD?  Thanks for any help on this issue.

### Expected Behaviour

It should read, I believe:  "Standard (HSD)"

### Steps to Reproduce

1.I load my csv datafile in which the grouping variable is "Division", from 1 to 9, the dependent variable is "IQ"
2. The ANOVA shows significant differences:  p<0.001
3. The post-hocs ask for a correction, so I use "Tukey"
4. I enter "Division" as the variable to conduct the post-hoc on.
5. JASP outputs the post-hoc table, but the heading of the table is "Standard (LSD)" 
6. Should this be "Standard (HSD)" Is the program doing an HSD or an LSD analysis?
...

### More Debug Information

-------- Application Info --------
JASP Version: JASP 0.19.1
Build Branch: lockfiletesting
Build Date: Sep  9 2024 19:00:04 (Netherlands)
Last Commit: 8ac10c9c7aec029fdd695262d7bb4c3742a8ec89

-------- Basic Info --------
Operating System: Windows 11 Version 23H2
Product Version: 11
Kernel Type: winnt
Kernel Version: 10.0.22631
Architecture: x86_64
Install Path: C:/Program Files (x86)/JASP
Platfotm Name: windows
System Local: en_US

-------- Extra Info --------
Current code page
Active code page: 437
Active code page: 65001

Host Name:                 BOB-DELL
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22631 N/A Build 22631
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          rfrench
Registered Organization:   N/A
Product ID:                00355-62843-83631-AAOEM
Original Install Date:     3/16/2024, 1:59:29 PM
System Boot Time:          10/3/2024, 2:16:55 AM
System Manufacturer:       Dell Inc.
System Model:              Precision 7560
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 141 Stepping 1 GenuineIntel ~2496 Mhz
BIOS Version:              Dell Inc. 1.33.0, 7/8/2024
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC+01:00) Brussels, Copenhagen, Madrid, Paris
Total Physical Memory:     31,953 MB
Available Physical Memory: 19,443 MB
Virtual Memory: Max Size:  34,001 MB
Virtual Memory: Available: 16,386 MB
Virtual Memory: In Use:    17,615 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\BOB-DELL
Hotfix(s):                 4 Hotfix(s) Installed.
                           [01]: KB5042099
                           [02]: KB5027397
                           [03]: KB5043076
                           [04]: KB5043937
Network Card(s):           2 NIC(s) Installed.
                           [01]: Intel(R) Ethernet Connection (14) I219-LM
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [02]: Intel(R) Wi-Fi 6E AX210 160MHz
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.1.1
                                 IP address(es)
                                 [01]: 192.168.1.100
                                 [02]: fe80::e0ba:c684:39be:d14a
                                 [03]: 2a02:8428:1813:4201:6ccb:995b:b5ce:b7e9
                                 [04]: 2a02:8428:1813:4201:88c4:65e5:1d14:32d3
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

![JASP_post_hoc](https://github.com/user-attachments/assets/2f69cbb2-2c6a-47e6-8684-8fef48fa01bc)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JohnnyDoorn** [comment]
Hi @Robert-M-French,

Thanks for your report. You're right that the name is a bit misleading, since the default option is to use Tukey's p-value correction (see the checkboxes in the posthoc menu), so we use HSD by default. If turned off (which I just see results in an error) and no correction is applied it would be LSD. In any case, I will update the name so it is more accurate. I think simply removing the "(LSD)" and calling it "Standard" would be best. 

Kind regards,
Johnny
