### ISSUE TITLE
[Bug]: SEM error "Error in if (nrow(originalSyntaxTable[originalSyntaxTable$op = ':=', : argument is of length zero"

### ISSUE THREAD

**Issue by manishakhulbe** [jasp-stats/jasp-issues#2957]
### JASP Version

0.19.0

### JASP Module

SEM

### What analysis are you seeing the problem on?

Structural Equation Modeling

### What OS are you seeing the problem on?

Windows 10

### Bug Description

On trying to run the model, the error shows up. Is this about mixing Likert and contitnuous data and using DWLS?
![sc1](https://github.com/user-attachments/assets/11402cec-104a-450b-a3db-ed6e6b46df5b)
[SEM KG (DWLS).zip](https://github.com/user-attachments/files/17294926/SEM.KG.DWLS.zip)

### Expected Behaviour

The model should have been applied.

### Steps to Reproduce

1. I made sure the variables were the right type.
2. I ran my lavaan code.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment]
@manishakhulbe thank you for creating the issue. JASP does not provide the correct error. This is what I get. 
![Screenshot 2024-10-09 at 09 34 49](https://github.com/user-attachments/assets/1043a21d-886b-4c7c-ac6e-753d60806388)
Try changing the missing option. on my computer the path plot also creates an error but that might be different for you

**Comment by manishakhulbe** [comment]
@juliuspfadt Thanks for looking into this! I changed the option for missing data handling, and it does work now.
