### ISSUE TITLE
bug in the repeated measures ANOVA line plots

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-issues#296]
From the twitterverse: https://twitter.com/micahgallen/status/1090273513833779201
"in the latest release 0.9.2.0 there is a bug in the repeated measures ANOVA line plots - the legend for seperate lines draws off the screen. Expanding the plot eventually shows it. Reproduced on two windows machines.

**Comment by AlexanderLyNL** [comment]
Duplicate issue #270
