### ISSUE TITLE
[Bug]: commas as decimal separators importing from ods is broken

### ISSUE THREAD

**Issue by frforest47** [jasp-stats/jasp-issues#2963]
### JASP Version

0.19.1

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

toutes les analyses

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

Erreurs de lecture du fichier original LibreOffice, non respect des virgules au lieu des points, certaines variables X 10, 100 ou 1000 sans correspondance avec les décimales orignales, toutes les variables affichées avec des points dans Jasp; quand une analyse réussit à se rendre au bout sans crash, résultats complètement farfelus, mais le système s'effondre avant la plupart du temps. J'ai des images concernant la mauvaise lecture, ci-joint.
<img width="960" alt="Jasp erreurs de lecture" src="https://github.com/user-attachments/assets/304a1782-6157-40b6-aecc-66d174ae4a5e">
À gauche, le fichier original Libre Office, à droite le fichier généré par Jasp.  Seule la colonne "cal act OR" semble avoir été lue correctement, et la colonne "pas quot" affiche 6 décimales après un point, et non une virgule; de plus, cette colonne est classée comme qualitative.J'ai essayé de nombreuses versions de Jasp, sans en trouver une qui fonctionne correctement; j'ai aussi ssayé plusieurs versions e LibreOffice, sans plus de résultats. Je travaille avec ces 2 logiciels depuis de nombreuses années, sans problème. Ce n'est que depuis les modifications du système OS (actuellement: 15.0.1, mais je ne sais pas à partir de quelle version les problèmes sont apparus, ça change tellement vite!) que j'éprouve ces difficultés. Le coupable: Mac OS, LibreOffice, ou Jasp ???? Que faire ??? Merci!

### Expected Behaviour

Lecture des fichiers LibreOffice comme avant, sans problème, et analyses subséquentes aussi comme avant, sans problème.

### Steps to Reproduce

1. Ouvrir un fichier LibreOffice
2. Le fichier Jasp est déjà corrompu à la simple lecture
3. Crash de Jasp, ou résultats d'analyses complètement farfelus
[JASP 2024-10-12 11_01_18 Desktop.log](https://github.com/user-attachments/files/17350561/JASP.2024-10-12.11_01_18.Desktop.log)
[JASP 2024-10-12 11_01_18 Engine 0.log](https://github.com/user-attachments/files/17350562/JASP.2024-10-12.11_01_18.Engine.0.log)
[JASP 2024-10-12 11_05_40 Desktop.log](https://github.com/user-attachments/files/17350563/JASP.2024-10-12.11_05_40.Desktop.log)
[JASP 2024-10-12 11_05_40 Engine 0.log](https://github.com/user-attachments/files/17350564/JASP.2024-10-12.11_05_40.Engine.0.log)
[JASP 2024-10-12 11_07_01 Desktop.log](https://github.com/user-attachments/files/17350565/JASP.2024-10-12.11_07_01.Desktop.log)
[JASP 2024-10-12 11_07_01 Engine 0.log](https://github.com/user-attachments/files/17350566/JASP.2024-10-12.11_07_01.Engine.0.log)

...

### Log (if any)

JASP 2024-10-12 11_01_18 Desktop.log
JASP 2024-10-12 11_01_18 Engine 0.log
JASP 2024-10-12 11_05_40 Desktop.log
JASP 2024-10-12 11_05_40 Engine 0.log
JASP 2024-10-12 11_07_01 Desktop.log
JASP 2024-10-12 11_07_01 Engine 0.log

### More Debug Information

-------- Application Info --------
JASP Version: JASP 0.19.1 (Intel)
Build Branch: development
Build Date: Sep  9 2024 22:46:00 (Netherlands)
Last Commit: 8ac10c9c7aec029fdd695262d7bb4c3742a8ec89

-------- Basic Info --------
Operating System: macOS 15.0
Product Version: 15.0
Kernel Type: darwin
Kernel Version: 24.0.0
Architecture: x86_64
Install Path: /Applications/JASP.app/Contents/MacOS
Platfotm Name: cocoa
System Local: en_CA

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by shun2wang** [comment]
I can't read the text, but from the pictures, the left and right sides just show different precisions, JASP shows the exact value.If that's the case, it just depends on decimal placess showing you set in the LibreOffice.

**Comment by tomtomme** [comment]
@shun2wang 
this is about strange results when importing an ODS file that uses comma instead of dot as a separator (most browsers can translate websites on the fly, maybe (re)activate this).

@frforest47 @boutinb 
 JASP supported commas on import from ODS just fine in the past - so this is a regression. On import those commas got recoded as dots however as intended. But now the decimal places move on import - the screenshots show this! I can also reproduce this with some data I just made up here:

[x.ods.zip](https://github.com/user-attachments/files/17360844/x.ods.zip)
[x.jasp.zip](https://github.com/user-attachments/files/17360845/x.jasp.zip)

This is a bad regression. Thx for reporting it!

**Comment by frforest47** [comment]
I am sorry to have written in french... my english is not so good.
Concerning your answer, I think it is more than a simple number of decimal
places I have set in LibreOffice. Loor at the column "km tot" (total number
of kilometers) in the LibreOffice image, on the left. The setting was: 2
decimals, for all the cells in the column. If we look now in the same
column as read by Jasp on the right, the first rows seem to have been
multiplied by 100, but the decimals do not correspond: 2.40 X 100 is not
242.3, 5,50 X 10 is not 555.5, and so on. At line 13, the LibreOffice value
of 3.45 was multiplied by 1000, as in the line 14. Then line 15 and 16,
back to the X 100. Line 17, the multiplication is only by 10. ...  Then, of
course, all the analysis I do using the column "km tot" in Jasp give bad
results... Where is the error? In my new Mac Os system 15.0.1, in the
LibreOffice transmission to Jasp, or in the Jasp opening of the file? Thank
you, Shun Wang.
Francs Forest

Le lun. 14 oct. 2024, à 03 h 47, Shun Wang ***@***.***> a
écrit :

**Comment by shun2wang** [comment]
Yes you are right, it was my oversight, there is indeed a problem here, thanks!

**Comment by boutinb** [comment]
If you can send us a file where we can reproduce this, that would be quite handy.

**Comment by tomtomme** [comment]
I already uploaded a file here https://github.com/jasp-stats/jasp-issues/issues/2963#issuecomment-2410377605
Shunwang already has a fix in the pipeline https://github.com/jasp-stats/jasp-desktop/pull/5703
