### ISSUE TITLE
"Unknown error" when attempting bayesian linear regression

### ISSUE THREAD

**Issue by earlycapistran** [jasp-stats/jasp-issues#297]
* JASP version: 0.8.5.1
* OS name and version: Linux Mint 18.2
* Analysis: Bayesian linear regression
* Bug description: When attempting to run a Bayesian linear regression, I get the message "An unknown error ocurred. Please contact the authors" after adding a covariate. I have tried with several data sets and get the same error message each time.

As a test, I tried carrying out another bayesian analyses (bayesian t-test) and got a more detailed error message (see second screenshot): This analysis terminated unexpectedly.

Error in dyn.load(file, DLLpath = DLLpath, ...): unable to load shared object '/usr/lib/R/site-library/stringi/libs/stringi.so':
  /usr/lib/R/site-library/stringi/libs/stringi.so: undefined symbol: DATAPTR

Stack trace
analysis(dataset = dataset, options = options, perform = perform, callback = the.callback, state = oldState)

.extractErrorMessage(result)

stringr::str_trim

getExportedValue(pkg, name)

asNamespace(ns)

getNamespace(ns)

tryCatch(loadNamespace(name), error = function(e) stop(e))

tryCatchList(expr, classes, parentenv, handlers)

tryCatchOne(expr, names, parentenv, handlers[[1]])

value[[3]](cond)
 
* Add JASP files as a zip:
[cpue.zip](https://github.com/jasp-stats/jasp-issues/files/2818988/cpue.zip)
* Screenshot: 
![screenshot](https://user-images.githubusercontent.com/47227446/52084665-68137980-2557-11e9-8eeb-2085142b3add.png)
![screenshot2](https://user-images.githubusercontent.com/47227446/52085106-77df8d80-2558-11e9-896b-9b4c56eb8ef9.png)

**Comment by vandenman** [comment]
Thanks for reporting this!
Since version 0.8.5.1, we've completely reworked the Bayesian linear regression. I cannot reproduce this error with version JASP 0.9.1 and I'm fairly sure that if you update to the latest JASP (version 0.9.2) the error will disappear.

**Comment by FransMeerhoff** [comment]
Hi @earlycapistran 

Sorry for the late reaction, but did yo try the JASP flatpak version (described in https://jasp-stats.org/linux-installation-guide/. which contains 0.9.2 at the moment that would probably solve your problem.

Kind regards
Frans Meerhoff
