### ISSUE TITLE
[Bug]: Equivalence Paired Samples T-Test [Incorrect sign]

### ISSUE THREAD

**Issue by rodney1975** [jasp-stats/jasp-issues#2970]
### JASP Version

0.19.1

### JASP Module

Equivalence T-Tests

### What analysis are you seeing the problem on?

Paired Sample T-Test

### What OS are you seeing the problem on?

Windows 11

### Bug Description

The point estimate has the incorrect sign e.g. 0.5 rather than -0.5
![Screenshot 2024-10-15 123452](https://github.com/user-attachments/assets/4f916c2b-64d0-498d-8da3-8ea2084eabf0)

### Expected Behaviour

Should see the point estimate between th e 90% CI, skwed toward one because of the incorrect sign  - positive or negative

### Steps to Reproduce

1. Happens every time 
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Thx for the report. I am no expert in this equivalence t-Test. But are you talking about Cohens d being -0.497? And you think +0.497 is correct?
And then you want it to be between the CI which goes from -0.181 to 0.05? That certainly does not make sense. Changing the sign of -0.5 to 0.5 does not make it fit into the CI. 

So yeah, I am at a loss here. 
@Jillderon or @vandenman any idea?
