### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by herculaninho** [jasp-stats/jasp-issues#2973]
### Description

Is it possible do to a network meta-analysis in JASP?

### Purpose

Because JASP is based on R, and there is a package called netmeta, it would be awesome if we could peform network meta-analysis easily with JASP.

### Use-case

Network Meta-analysis

### Is your feature request related to a problem?

No

### Is your feature request related to a JASP module?

Meta Analysis

### Describe the solution you would like

I don't think there is a solution, but I think adding the package netmeta? Because there is already a module called Network Analysis, that does a web graphic with nodes and relationships between things.

### Describe alternatives that you have considered

I think adding the feature of using the netmeta package, I don't think so, The current use of meta-analysis module is perfect, using effect sizes and standard errors is really complete for all analysis I ever done.

**Comment by FBartos** [comment]
Hi, thanks for the suggestion! We are already tracking the issue (https://github.com/jasp-stats/jasp-issues/issues/1646) and we will add network meta-analysis at some point in the future. Unfortunately, it's currently not on the top of our priority list.
Best,
Frantisek
