### ISSUE TITLE
[Feature Request]: reminder: Qt 6.7  => 6.8 LTS for 0.20

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#2977]
### Description

OSS/standard support for Qt 6.7 will end 2025-03-26, see https://doc.qt.io/qt-6/qt-releases.html#supported-versions.
So 0.20 is probably a good target to switch to Qt 6.8. 
Qt 6.8 will still support MacOX 12 according to https://doc.qt.io/qt-6/supported-platforms.html

### Purpose

security

**Comment by boutinb** [comment]
Yes we are aware of it, and checked it: and JASP had already some problems with Qt 6.8. So we postponed Qt 6.8 to 0.20.

**Comment by tomtomme** [comment]
Closing as duplicate, see above
