### ISSUE TITLE
[Bug]: Attributes Agreement Analysis terminates when Standard (optional field) is left blank

### ISSUE THREAD

**Issue by 49er60** [jasp-stats/jasp-issues#2979]
### JASP Version

0.19.1

### JASP Module

Quality Control

### What analysis are you seeing the problem on?

Attributes Agreement Analysis

### What OS are you seeing the problem on?

Windows 11

### Bug Description

![JASP bug Attributes Agreement Analysis](https://github.com/user-attachments/assets/47dfa1ba-2381-4c79-ae61-3f5f95215f7e)
[GB252 ATT MSA Attribute R&R.csv](https://github.com/user-attachments/files/17467356/GB252.ATT.MSA.Attribute.R.R.csv)

### Expected Behaviour

![image](https://github.com/user-attachments/assets/168985d8-6a66-4c93-a7d7-11a5b4fc539c)

### Steps to Reproduce

1. Leave optional Standard field blank
2.
3.
...

### Log (if any)

[JASP 2024-10-21 16_44_40 Desktop.log](https://github.com/user-attachments/files/17467333/JASP.2024-10-21.16_44_40.Desktop.log)
[JASP 2024-10-21 16_44_40 Engine 0.log](https://github.com/user-attachments/files/17467334/JASP.2024-10-21.16_44_40.Engine.0.log)
[JASP 2024-10-21 16_44_40 Engine 1.log](https://github.com/user-attachments/files/17467335/JASP.2024-10-21.16_44_40.Engine.1.log)

### More Debug Information

-------- Application Info --------
JASP Version: JASP 0.19.1
Build Branch: lockfiletesting
Build Date: Sep  9 2024 19:00:04 (Netherlands)
Last Commit: 8ac10c9c7aec029fdd695262d7bb4c3742a8ec89

-------- Basic Info --------
Operating System: Windows 11 Version 23H2
Product Version: 11
Kernel Type: winnt
Kernel Version: 10.0.22631
Architecture: x86_64
Install Path: C:/Program Files (x86)/JASP
Platfotm Name: windows
System Local: en_US

-------- Extra Info --------
Current code page
Active code page: 437
Active code page: 65001

Host Name:                 PF46Y7B7
OS Name:                   Microsoft Windows 11 Enterprise
OS Version:                10.0.22631 N/A Build 22631
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Rockwell Automation User
Registered Organization:   Rockwell Automation
Product ID:                00330-80000-00000-AA886
Original Install Date:     3/20/2023, 10:07:33 AM
System Boot Time:          10/21/2024, 4:16:41 PM
System Manufacturer:       LENOVO
System Model:              21D7S0X800
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 151 Stepping 2 GenuineIntel ~2100 Mhz
BIOS Version:              LENOVO N3FET38W (1.23 ), 9/27/2023
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-06:00) Central Time (US & Canada)
Total Physical Memory:     32,434 MB
Available Physical Memory: 16,961 MB
Virtual Memory: Max Size:  37,298 MB
Virtual Memory: Available: 17,893 MB
Virtual Memory: In Use:    19,405 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\PF46Y7B7
Hotfix(s):                 5 Hotfix(s) Installed.
                           [01]: KB5042099
                           [02]: KB5012170
                           [03]: KB5027397
                           [04]: KB5043076
                           [05]: KB5043937
Network Card(s):           4 NIC(s) Installed.
                           [01]: Cisco AnyConnect Virtual Miniport Adapter for Windows x64
                                 Connection Name: Ethernet 5
                                 Status:          Hardware not present
                           [02]: Intel(R) Wi-Fi 6E AX211 160MHz
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.1.1
                                 IP address(es)
                                 [01]: 192.168.1.57
                                 [02]: fe80::55e7:d8d2:829d:4387
                                 [03]: 2603:6000:bef0:1a0:2124:72d2:d0e8:1c50
                                 [04]: 2603:6000:bef0:1a0:68d9:ec86:6fdf:3dc5
                                 [05]: 2603:6000:bef0:1a0::102d
                           [03]: Intel(R) Ethernet Controller (3) I225-LMvP
                                 Connection Name: Ethernet 6
                                 Status:          Media disconnected
                           [04]: Realtek USB GbE Family Controller
                                 Connection Name: Ethernet 3
                                 Status:          Media disconnected
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JTPetter** [comment]
Thanks for reporting. I could reproduce this with 0.19.1, but it is already fixed for the coming version.
