### ISSUE TITLE
[Bug]: ARIMA analysis terminated unexpectedly 

### ISSUE THREAD

**Issue by dustiii-p** [jasp-stats/jasp-issues#2982]
### JASP Version

0.19.1

### JASP Module

Time Series

### What OS are you seeing the problem on?

Other

### Bug Description

Error in minT:maxT: NA/NaN argument

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.tsDataWithMissingRowsHandler(datasetFiltered, options, ready)

### Expected Behaviour

It should run the analysis

### Steps to Reproduce

1. Time Series -> ARIMA
2. enter variables
3. error popped up
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
almost finished via https://github.com/jasp-stats/jaspTimeSeries/pull/38
thx @sophieberkhout !
