### ISSUE TITLE
[Bug]: Error in if (nrow(originalSyntaxTable[originalSyntaxTable$op = ':=', : argument is of length zero

### ISSUE THREAD

**Issue by larsvantuin** [jasp-stats/jasp-issues#2983]
### JASP Version

0.19.1

### JASP Module

SEM

### What analysis are you seeing the problem on?

Structural equation modelling

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

<img width="825" alt="Screenshot 2024-10-24 at 08 40 49" src="https://github.com/user-attachments/assets/594e1e55-4241-4504-9d87-655123bc5258">
[20241023 jur data JASP.csv.zip](https://github.com/user-attachments/files/17502459/20241023.jur.data.JASP.csv.zip)

### Expected Behaviour

The model should run

### Steps to Reproduce

1.
2.
3.
...

### Log (if any)

[JASP 2024-10-23 17_45_59 Desktop.log](https://github.com/user-attachments/files/17502496/JASP.2024-10-23.17_45_59.Desktop.log)
[JASP 2024-10-23 17_45_59 Engine 0.log](https://github.com/user-attachments/files/17502497/JASP.2024-10-23.17_45_59.Engine.0.log)

### More Debug Information

-------- Application Info --------
JASP Version: JASP 0.19.1 (Apple Silicon)
Build Branch: development
Build Date: Sep  9 2024 13:50:55 (Netherlands)
Last Commit: 28c9e9916b15ff84dfb998ad5db78a421b985aa0

-------- Basic Info --------
Operating System: macOS 14.6
Product Version: 14.6
Kernel Type: darwin
Kernel Version: 23.6.0
Architecture: arm64
Install Path: /Applications/JASP.app/Contents/MacOS
Platfotm Name: cocoa
System Local: en_NL

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by larsvantuin** [comment]
Dear support staff, 

I very much appreciate your help. I think it must be something in the lavaan syntax, but after checking and rechecking and reading up on other reported issues, I can't find what the issue is. 

All the best wishes

Lars van Tuin, PhD

**Comment by juliuspfadt** [comment]
Dear @larsvantuin, I think attaching the zipped .jasp file has not worked. Could you try that again?

**Comment by larsvantuin** [comment]
Dear Julius,

Here is the zipfile again. Hope it works this time. I had zipped the CSV-file iso the JASP-file

￼
I will also upload it on the site

Thank you so much for your support. 

BTW: I had tried the same lavaan syntax in the PLS and that one worked. Strange.

All the best

Lars

**Comment by larsvantuin** [comment]
[20241023 jur data JASP.jasp.zip](https://github.com/user-attachments/files/17506048/20241023.jur.data.JASP.jasp.zip)

**Comment by juliuspfadt** [comment]
Hi Lars, the issue was with "ML" as estimator when data is categorical. I am very sorry about the uninformative error. The fix is already in (https://static.jasp-stats.org/Nightlies/). It is important we get the next version released soon. 
![Screenshot 2024-10-24 at 13 47 46](https://github.com/user-attachments/assets/479b03f4-6f0f-4c45-bc23-ab6257893b48)

**Comment by larsvantuin** [comment]
Hi Julius, thank you so much for looking into it. I followed the link to Nightlies, but I am unclear about which file to download. Can you help me with that?

**Comment by tomtomme** [comment]
I would try this semi-stable one: https://static.jasp-stats.org/Nightlies/WindowsZip/JASP-nightly-stable-8ac10c9c7aec029fdd695262d7bb4c3742a8ec89.zip

just unpack the zip and start jasp.exe to test

**Comment by larsvantuin** [comment]
i'll get on it!

**Comment by tomtomme** [comment]
If you need a proper installation try the msix installer: https://static.jasp-stats.org/Nightlies/WindowsMSIX/JASP-nightly-stable-8ac10c9c7aec029fdd695262d7bb4c3742a8ec89.msix

**Comment by larsvantuin** [comment]
Do you also have a version for Mac?

**Comment by juliuspfadt** [comment]
https://static.jasp-stats.org/Nightlies/macOS-arm64/JASP-nightly-development-e975c43c274acbf0fa4af4e198cf5d20d73863fa.dmg

**Comment by juliuspfadt** [comment]
you would look into the "macOS arm64" box, then click on the "JASP dmg" File that has Branch development :) 
![Screenshot 2024-10-24 at 15 48 45](https://github.com/user-attachments/assets/e0ee485d-7842-487c-9206-a44258bbda8b)

**Comment by Goose11213** [comment]
I am also getting the same error. Additionally, I am not being able to install the latest stable build specified above. 
I get certificate issue when trying to bypass it and I launched the latest JASP version I receive a "the quote execution cannot proceed because libstdc++-6 the dll was not found". Any suggestions?

**Comment by larsvantuin** [comment]
Hi Julius, thank you again for your support. The SEM now works like a charm. However, an analysis with an ML estimator would be so helpful in preparing the study for publication. Do you have any idea when that will be added to JASP?

**Comment by juliuspfadt** [comment]
> I am also getting the same error. Additionally, I am not being able to install the latest stable build specified above. I get certificate issue when trying to bypass it and I launched the latest JASP version I receive a "the quote execution cannot proceed because libstdc++-6 the dll was not found". Any suggestions?

I am afraid I dont know what you mean with the latest stable build, what branch are you referring to? What system are you on? I have little idea what the error message means, you might try an earlier version? Might be best to open another issue for this?

**Comment by juliuspfadt** [comment]
> Hi Julius, thank you again for your support. The SEM now works like a charm. However, an analysis with an ML estimator would be so helpful in preparing the study for publication. Do you have any idea when that will be added to JASP?

I think you could try estimator PML. Other than that, if `lavaan` does not offer it, we dont have it 🤷🏻‍♂️
