### ISSUE TITLE
[Bug]: Issue with ANOVA analysis

### ISSUE THREAD

**Issue by Nazla122** [jasp-stats/jasp-issues#2986]
### JASP Version

0.18.0

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

Classical ANOVA

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

It just said this instead of analysing the data: 

Error in dyn.load(file, DLLpath = DLLpath, ...): unable to load shared object '/Applications/JASP.app/Contents/Frameworks/R.framework/Versions/4.2/Resources/library/Matrix/libs/Matrix.so':
  dlopen(/Applications/JASP.app/Contents/Frameworks/R.framework/Versions/4.2/Resources/library/Matrix/libs/Matrix.so, 0x0006): Library not loaded: @executable_path/../Frameworks/R.framework/Versions/4.2/Resources/opt/local/gfortran/lib/libgfortran.dylib
  Referenced from: <1511B69B-6F80-3271-978B-CCD9719708A8> /Applications/JASP.app/Contents/Frameworks/R.framework/Versions/4.2/Resources/library/Matrix/libs/Matrix.so
  Reason: tried: '/Applications/JASP.app/Contents/Frameworks/R.framework/Versions/4.2/Resources/opt/local/gfortran/lib/libgfortran.dylib' (no such file), '/usr/lib/libgfortran.dylib' (no such file, not in dyld cache)

### Expected Behaviour

It should have analysed the data normally into some tables 

### Steps to Reproduce

1.I imported a CSV file into JASP
2. Clicked on ANOVA
3. Crashed
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by JohnnyDoorn** [comment]
Hi @Nazla122 ,

Can you retry this with the latest JASP Version (0.19.1)? Because I think it's been fixed in the meantime. Please reopen if the issue stil persists

Cheers,
Johnny
