### ISSUE TITLE
[Bug]: R Syntax doesn't work

### ISSUE THREAD

**Issue by LarsdeVreugd** [jasp-stats/jasp-issues#2990]
### JASP Version

0.19.1

### JASP Module

Regression

### What analysis are you seeing the problem on?

Linear Regression

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

I encountered this issue in my own analysis, made a mock data-set to show the error.
The issue is about the R Syntax:

Step 1: mock data-set
<img width="697" alt="Step1" src="https://github.com/user-attachments/assets/d5a1f7d6-3512-4b60-b7a1-6b7016a7c614">

Step 2: Made a linear regression model of B and C on A
<img width="958" alt="Step2" src="https://github.com/user-attachments/assets/5623efeb-650e-4251-961d-41bf00e447b5">

Step 3: Made a new regression model
<img width="958" alt="Step3" src="https://github.com/user-attachments/assets/207191d7-1035-42e2-97df-9ade8b7ea892">

Step 4: Copied R Syntax from the first regression model
<img width="958" alt="Step4" src="https://github.com/user-attachments/assets/109c40c2-d441-4018-bbd3-cfe75e1be4d4">

Step 5: When I paste the syntax in the new model, it gives an error (see screenshot). The error also occurs when I type the R syntax instead of
<img width="958" alt="Step5" src="https://github.com/user-attachments/assets/66208531-760b-4871-9580-157d696c2a63">
 copying it.

### Expected Behaviour

The syntax function is great and would be nice if it works :) 

### Steps to Reproduce

See pictures

### Log (if any)

Evaluating R-code:
options(renv.config.install.verbose=FALSE)
Output:

00:00:00.000: Received: '{
	"moduleCode" : ".libPaths(c('/Applications/JASP.app/Contents/MacOS/../Frameworks/R.framework/Versions/4.4-arm64/Resources/library', '/Applications/JASP.app/Contents/Modules/jaspRegression'));\n  library('jaspRegression');\nreturn('succes!')",
	"moduleName" : "jaspRegression",
	"moduleRequest" : "loading",
	"typeRequest" : "moduleLoadRequest"
}
' so now clearing my send buffer
00:00:00.001: Engine received moduleLoadRequest message
00:00:00.002: About to run module request for module 'jaspRegression' and code to run:
'.libPaths(c('/Applications/JASP.app/Contents/MacOS/../Frameworks/R.framework/Versions/4.4-arm64/Resources/library', '/Applications/JASP.app/Contents/Modules/jaspRegression'));
  library('jaspRegression');
return('succes!')'
jaspRCPP_evalRCode runs: 
".libPaths(c('/Applications/JASP.app/Contents/MacOS/../Frameworks/R.framework/Versions/4.4-arm64/Resources/library', '/Applications/JASP.app/Contents/Modules/jaspRegression'));
  library('jaspRegression');
return('succes!')"
Evaluating R-code:
returnVal = 'null';	tryCatch(    suppressWarnings({	returnVal <- eval(parse(text=.rCode))     }),	    error	= function(e) { .setRError(  paste0(toString(e$message), '
', paste0(sys.calls()[sys.nframe():2], collapse='
'))) } 	); returnVal	
Output:

00:00:00.069: Was succesful, now crafting answer.
00:00:00.069: Sending it.
00:00:00.174: Received: '{
	"rCode" : "jaspRegression::RegressionLinear(\n          version = \"0.19\",\n          formula = VariableA ~ VariableB + VariableC,\n          covariates = list(\"VariableB\", \"VariableC\"),\n          weights = list(types = list(), value = \"\"))",
	"requestId" : 2,
	"returnLog" : false,
	"typeRequest" : "rCode",
	"whiteListed" : false
}
' so now clearing my send buffer
00:00:00.175: Engine received rCode message
jaspRCPP_evalRCode runs: 
"jaspRegression::RegressionLinear(
          version = "0.19",
          formula = VariableA ~ VariableB + VariableC,
          covariates = list("VariableB", "VariableC"),
          weights = list(types = list(), value = ""))"
Evaluating R-code:
returnVal = 'null';	tryCatch(    suppressWarnings({	returnVal <- eval(parse(text=.rCode))     }),	    error	= function(e) { .setRError(  paste0(toString(e$message), '
', paste0(sys.calls()[sys.nframe():2], collapse='
'))) } 	); returnVal	
Output:
00:00:00.188: DataSet::DataSet(index=1)

00:00:00.195: R Code yielded error

### More Debug Information

-------- Application Info --------
JASP Version: JASP 0.19.1 (Apple Silicon)
Build Branch: development
Build Date: Sep  9 2024 13:50:55 (Netherlands)
Last Commit: 28c9e9916b15ff84dfb998ad5db78a421b985aa0

-------- Basic Info --------
Operating System: macOS 14.6
Product Version: 14.6
Kernel Type: darwin
Kernel Version: 23.6.0
Architecture: arm64
Install Path: /Applications/JASP.app/Contents/MacOS
Platfotm Name: cocoa (<There's a typo here)
System Local: en_NL

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @LarsdeVreugd, I have seen this problem. This will be fixed in 0.19.2 (mid november).
