### ISSUE TITLE
[Bug]: Segfault when clicking on "New Data" and then "Analysis"

### ISSUE THREAD

**Issue by m-guggenmos** [jasp-stats/jasp-issues#2998]
### JASP Version

0.19.1

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Linux, Flatpak

### Bug Description

The following sequence 

1. Start JASP
2. Click on "New Data"
3. Click on the cell in row 1, column 2
4. Click on "Analysis"

results in a segfault for me.

In the console I see the following output when this happens:

```
/usr/include/c++/13.2.0/bits/stl_vector.h:1125: constexpr std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = double; _Alloc = std::allocator<double>; reference = double&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
/app/bin/org.jaspstats.JASP: line 10:     3 Aborted                 (core dumped) JASP
```

### Expected Behaviour

No segfault

### Steps to Reproduce

See bug description

### More Debug Information

-------- Application Info --------
JASP Version: JASP 0.19.1
Build Branch: HEAD
Build Date: Sep 10 2024 13:48:11 (Netherlands)
Last Commit: a7ca00d09fc8a4c990031d10ba3d20a43c86d823

-------- Basic Info --------
Operating System: KDE Flatpak runtime
Product Version: 6.7
Kernel Type: linux
Kernel Version: 6.11.0-9-generic
Architecture: x86_64
Install Path: /app/bin
Platfotm Name: wayland
System Local: en_US

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by shun2wang** [comment]
Yeah, looks a similar issue.

**Comment by tomtomme** [comment]
yep. can confirm.

**Comment by JorisGoosen** [comment]
Well, the annoying thing is it seems to only crash when build as a flatpak... 
Not a local release build, so lets see if I can figure out whats wrong some other way

**Comment by JorisGoosen** [comment]
Maybe @shun2wang or @m-guggenmos can test the flatpak I made at:
```
flatpak install --user https://dl.flathub.org/build-repo/143150/org.jaspstats.JASP.flatpakref
flatpak run --branch=test org.jaspstats.JASP
```
I did already test it and it stopped crashing for me now.

**Comment by shun2wang** [comment]
OK, tested and looks good to me.
