### ISSUE TITLE
Contingency tables adding layers

### ISSUE THREAD

**Issue by conorgissane** [jasp-stats/jasp-issues#300]
Contingency tables with layers

* JASP version: JASP 0.9.2.0
* OS name and version:
* Analysis: Contingency tables
* Bug description: 
This analysis terminated unexpectedly.

Error in base::parse(text = ss.filter.string): :1:14: unexpected string constant
1: XYWdlX2dy='''20 - 29'

* Add JASP files as a zip:
* Screenshot: 
* Expected behaviour:
* Steps to reproduce: 
1. Go to '...'Frequencies >contingency tables
2. Click on '...
[2019-02-04 (1).zip](https://github.com/jasp-stats/jasp-issues/files/2828792/2019-02-04.1.zip)
[2019-02-04 (1).zip](https://github.com/jasp-stats/jasp-issues/files/2828801/2019-02-04.1.zip)

.'
This analysis terminated unexpectedly.

Error in base::parse(text = ss.filter.string): :1:14: unexpected string constant
1: XYWdlX2dy='''20 - 29'
                 ^

Stack trace

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

**Comment by TimKDJ** [comment]
@conorgissane is there any chance you could attach the .jasp file in which this error occurred (you will need to zip it)?
If it has sensitive information you could also email it to me at t.dejong@jasp-stats.org
