### ISSUE TITLE
[Bug]: broken qml in non-english versions

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#3000]
### JASP Version

0.19.1 & 0.19.2 beta

### JASP Module

Cochrane Meta-Analyses

### What analysis are you seeing the problem on?

dichotomous and continous outcomes

### What OS are you seeing the problem on?

Flatpak

### Bug Description

![grafik](https://github.com/user-attachments/assets/da061e64-62d8-4d5f-9b4e-30f58dd1a9b1)

**Comment by FBartos** [comment]
this is quite an odd bug, I though it would be translation related, but I can't find any `qsTr("")` / `gettext("")` potentially causing the issue

**Comment by boutinb** [comment]
Cochrane does not work at all with the new Meta Analysis: https://github.com/jasp-stats/INTERNAL-jasp/issues/2688

**Comment by tomtomme** [comment]
cochrane in my 0.19.2 beta works IF english. My beta might be outdated however.

I tested stable and beta with other languages now and all other than english are broken, if I select Keywords and also if I select Topics (but less obvious there).

-------- Application Info --------
JASP Version: JASP 0.19.2
Build Branch: HEAD
Build Date: Nov  7 2024 21:16:25 (Netherlands)
Last Commit: afa1ecd99de9e210c366d43b321731abb479dcf0

-------- Basic Info --------
Operating System: KDE Flatpak runtime
Product Version: 6.7
Kernel Type: linux
Kernel Version: 6.6.54-2-MANJARO
Architecture: x86_64
Install Path: /app/bin
Platfotm Name: wayland
System Local: de_DE

**Comment by boutinb** [comment]
I have just solved another QML issue in Cochrane. The german version works for me.
