### ISSUE TITLE
[Bug]: Informed Multinomial Crashing on Mac M2

### ISSUE THREAD

**Issue by mumair01** [jasp-stats/jasp-issues#3001]
### JASP Version

0.19.1

### JASP Module

Frequencies

### What analysis are you seeing the problem on?

Informed Multinomial 

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

We are running an order restricted hypothesis on a dice problem, which causes the engine to crash. 

<img width="1272" alt="Screenshot 2024-11-07 at 10 35 07 AM" src="https://github.com/user-attachments/assets/38fcf045-2012-4833-b3bb-3b513dead44f">

### Expected Behaviour

It should have the following output (which was run on the intel version), where this analysis runs correctly. 
<img width="1272" alt="Screenshot 2024-11-07 at 10 35 07 AM" src="https://github.com/user-attachments/assets/2bccbad2-4f86-4d05-9e23-05469442d86d">

### Steps to Reproduce

1. Load dataset
2. Select informed multinomial
3. Change some of the priors
4. Enter model 1=2=3=4=5=6
5. Add model 1=2<3=4<5=6
6. Press command + enter
...

### More Debug Information

The following file also crashes after loading. 
[135_original.jasp.zip](https://github.com/user-attachments/files/17664108/135_original.jasp.zip)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by FBartos** [comment]
@JorisGoosen & @boutinb , we have this Mac silicon-specific issue again. Can we deal with it?

**Comment by FBartos** [comment]
yes, this is M processor MacOS related, but it is probably stemping from some of the high precision R packages --- it works fine on windows for me and we had some similar issues before that were thought to be resolved

**Comment by JorisGoosen** [comment]
I think the issues we resolved were the desktop crashing by getting a very small number back from the engine.
If the engine is crashing... Well, we'll have to look into it

**Comment by JorisGoosen** [comment]
I can definitely reproduce this on mac M1...

**Comment by boutinb** [comment]
I can reproduce this also. It happens even with Model 1 is : `1=2<3=4<5=6`. With  `1=2=3=4=5=6` there is no problem.

**Comment by JorisGoosen** [comment]
Also nice workaround: download the x86 version for mac, then the testfile seems to load and run without a problem ^^

**Comment by RensDofferhoff** [comment]
This should now be resolved in the latest nightly

**Comment by RensDofferhoff** [comment]
This should now be resolved in the latest nightly

**Comment by JorisGoosen** [comment]
Indeed, the newest arm nightly is fine now
