### ISSUE TITLE
Wont allow me to download

### ISSUE THREAD

**Issue by Julialr** [jasp-stats/jasp-issues#301]
I recently tried to download your program. I followed the download instructions to download it onto my windows laptop, but when I clicked "run" it came up with a pop up saying that "This installation package is not supported by this processor type. Contact your product vendor." I'm not sure where to go from here. I still want to download the program. What should I do? Thank you for your time.

**Comment by TimKDJ** [comment]
I'm guessing you tried to install the 64-bit version of JASP while you have a 32-bit installation of Windows. You can verify this is the case by looking up your version, [Microsoft provides information on how to do so on their website](https://support.microsoft.com/en-us/help/13443/windows-which-operating-system).

If you're indeed on 32-bit windows you need to use the following installer:
[https://static.jasp-stats.org/JASP-0.9.2.0-32-bit.msi](https://static.jasp-stats.org/JASP-0.9.2.0-32-bit.msi)

**Comment by FransMeerhoff** [comment]
Hi @Julialr 

We assume that your problem is solved by downloading the  correct-bits version of JASP.
If not please reopen this issue.

Kind regards
Frans Meerhoff
