### ISSUE TITLE
[Bug]: filtering

### ISSUE THREAD

**Issue by mishiando** [jasp-stats/jasp-issues#3011]
### JASP Version

0.19.1

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

filtering, :534: unexpected string constant 4:5:generated Filter'^

### What OS are you seeing the problem on?

Windows 11

### Bug Description

[photo.pdf](https://github.com/user-attachments/files/17734179/photo.pdf)

### Expected Behaviour

The data was filterd.

### Steps to Reproduce

1. I imported the data with csv file
2. Then, I filtered gender=female and grade=4th
3. I cannot see the data selected. I can see the red message "unexpected string constant 4:5:generated Filter'^"
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
@mishiando  Did you close this issue by mistake, or there was no real  issue?
