### ISSUE TITLE
[Bug]: Error in if (nrow(originalSyntaxTable[originalSyntaxTable$op = ':=', : argument is of length zero

### ISSUE THREAD

**Issue by milospetkovic5ko** [jasp-stats/jasp-issues#3012]
### JASP Version

0.19.1

### JASP Module

SEM

### What analysis are you seeing the problem on?

Structural Equation Model (SEM)

### What OS are you seeing the problem on?

Other

### Bug Description

![Screen Shot 2024-11-13 at 22 35 45](https://github.com/user-attachments/assets/8c4903ea-1e4c-49d0-a2ec-1ba2e85349df)

**I am trying to do the SEM test. I have tried multiple times, but it shows me the following error:**

This analysis terminated unexpectedly.

Error in if (nrow(originalSyntaxTable[originalSyntaxTable$op = ':=', : argument is of length zero

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.semParameters(modelContainer, dataset, options, ready)

.semParameterTables(modelContainer[['results']][['object']][[1]], NULL, params, options, ready, modelContainer, dataset)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

### Expected Behaviour

The SEM should work. 
[SEM example.xlsx](https://github.com/user-attachments/files/17739572/SEM.example.xlsx)

I have added data in excel.

What should I do?

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment]
thanks for reporting the issue, we know about the issue, and it is fixed in the next version of JASP. If you can't wait, the nightly versions of JASP already have the fix. Try the development built for your system https://static.jasp-stats.org/Nightlies/.
