### ISSUE TITLE
[Feature Request]: To open blank dataset direrectly

### ISSUE THREAD

**Issue by Anne1208n** [jasp-stats/jasp-issues#3014]
### Description

When working on current JASP project, then we want to open a new project with a blank datasheet, it requires to re-initiate the JASP software.

### Purpose

To work several worksheet in JASP software not to open several JASP interface

### Use-case

For user experience

### Is your feature request related to a problem?

NA

### Is your feature request related to a JASP module?

Unrelated

### Describe the solution you would like

When working on current project, there has a button to create a blank datasheet

**Comment by tomtomme** [comment]
This will be in Version 0.19.2!

**Comment by Anne1208n** [comment]
> This will be in Version 0.19.2!

Great! many thanks.
