### ISSUE TITLE
[Bug]: Data doesn't open fully.

### ISSUE THREAD

**Issue by nesachan** [jasp-stats/jasp-issues#3017]
### JASP Version

0.19.1

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Other

### Bug Description

Whenever I want to open a file the data only opens one column, leaving all other data out. I can't get to open a file with all the data that goes with it, it only shows one part of it. 

### Expected Behaviour

By opening a file the full data should be shown in JASP, however this is not the case.

### Steps to Reproduce

1.Open > Files
2.Edit data > Synchronisation
3.Copy Paste
4. Sync data 
these are the steps I took to try to get it to work. (failed tho)
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by nesachan** [comment]
<img width="1281" alt="Scherm­afbeelding 2024-11-15 om 12 00 54 PM" src="https://github.com/user-attachments/assets/16d15dae-a0bf-4350-91d3-33d517da3fb8">

**Comment by tomtomme** [comment]
Thx for sharing the screenshot. Can you share the file with the data in question too? Otherwise it will not be possible for us to fix this.

**Comment by nesachan** [comment]
Of course, 
[georgia_student_survey.csv](https://github.com/user-attachments/files/17775779/georgia_student_survey.csv)
This is the file with the data

**Comment by tomtomme** [comment]
Interesting. The file opens fine for me. Here it is saved with jasp after importing it via 1. from your list above.
[georgia_student_survey.jasp.zip](https://github.com/user-attachments/files/17776056/georgia_student_survey.jasp.zip)

Just remove the .zip from the name to open it after downloading.

Can you give me some system informations on your machine? Idealy via
main menu => about => copy debug info

**Comment by nesachan** [comment]
I just figured out that the problem is solved if I download the files directly through my phone and then airdrop it to my MacBook. So from now on I will do it this way, but thank you very much for your help and looking into it.
