### ISSUE TITLE
[Bug]: manual setting X-axis of forest plot fails

### ISSUE THREAD

**Issue by rick-jasp** [jasp-stats/jasp-issues#3018]
### JASP Version

0.19.1

### JASP Module

Meta Analysis

### What analysis are you seeing the problem on?

Classical Meta-Analysis

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

I'm trying to use the same scale for the X-axis of a forest plot from several related meta-analyses. When I use the "edit image" option to manually set the X-axis, it accepts my new settings for the axis ticks, but does not apply them as entered. 

### Expected Behaviour

The program applies all of my revised settings except setting that would expand the X-axis beyond the minimum needed to encompass all confidence intervals in the current forest plot. This prevents me from using the same X-axis scaling for all of my related forest plots. Is this a bug? Or is there some work-around that I have not discovered? 
Maybe this is a feature request...

### Steps to Reproduce

1.
2.
3.
...
Enter any classical meta-analysis data and display the forest plot. Click on the edit image option for the forest plot. Try to expand the X-axis setting beyond the minimum needed for the confidence intervals in the current meta-analysis. It doesn't work.

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by FBartos** [comment]
Hi @rick-jasp , the classical Meta-Analyses (including the forest plot) are completely reworked in the upcoming release and you will be able to change the x-axis there manually. 
Cheers,
Frantisek
