### ISSUE TITLE
[Bug]: Process using Hayes Model 4 does not accept 3 mediators as it should

### ISSUE THREAD

**Issue by cjpetrucci** [jasp-stats/jasp-issues#3019]
### JASP Version

0.19.1

### JASP Module

Process

### What analysis are you seeing the problem on?

parallel multiple mediation with 3 mediators

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

Analysis originally ran with just the first mediator using Hayes Model 4 (and inputting 3 continuous mediators). then I created the model paths -see screen shot. and received this error message in screen shot.
![Screenshot 2024-11-17 at 12 14 31 PM](https://github.com/user-attachments/assets/ff76a651-aecc-4d32-955f-c2cd71f4c3a9)

### Expected Behaviour

Per the Hayes text, appendix b, p. 588 of 3rd edition, preset mediation models (most) accept up to 10 mediators.

### Steps to Reproduce

1.
2.
3.
...
I reproduced it multiple times by trying to create the model.

### Log (if any)

No log.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Thx for the Report. That certainly does not sound correct. Will try confirming later on my system. Can you help me with that by sharing your zipped jasp File?

**Comment by cjpetrucci** [comment]
Thank you so much for your time. Here is the zipped JASP file. I had to get permission from the student whose data it is.

￼
Carrie Petrucci, MSW, Ph.D.
Cell Phone: 818.667.9167 
Email: ***@***.***
--------------------------------------------
View my research on SSRN Author page:
http://ssrn.com/author=2053895
-------------------------------------------

The information contained in this email, including any attachment(s), is intended solely for the confidential use of the sender and recipient(s) named above and may be privileged and confidential. If the reader of this email is not the intended recipient, or the employee or agent responsible to deliver to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify the sender immediately by reply email and delete the original message from your computer.

**Comment by tomtomme** [comment]
thx, but sending via mail does not work. pleas zip the file and drag and drop it directly on github here

**Comment by maltelueken** [comment]
I cannot reproduce the error either. In version 19.2, it will be possible to add multiple mediators for models 4 and 5.
