### ISSUE TITLE
Unexpected error when performing linear regression (JASP version 0.9.2)

### ISSUE THREAD

**Issue by dinomandy** [jasp-stats/jasp-issues#302]
* JASP version: 0.9.2
* OS name and version: Windows 10 version 1803
* Analysis: linear regression
* Bug description: JASP has experienced an unexpected internal error
* Add JASP files as a zip:
* Screenshot: 
![image](https://user-images.githubusercontent.com/47439769/52457625-d1b60800-2b95-11e9-976e-a679a002069e.png)

* Expected behaviour:
* Steps to reproduce: 
1. Go to 'Regression --> Linear Regression'
2. Click on '"Salary per day" as dependent variables and the rest as independent variables --> maintain all default functions --> OK'
3
[data.zip](https://github.com/jasp-stats/jasp-issues/files/2843529/data.zip)
. See error

**Comment by TimKDJ** [comment]
There is a character encoding problem in the column name "Salary per Day ()" -- notice the way JASP shows the the pound character.
As a workaround I've converted your dataset from ISO-8859-1 to utf-8 and it works fine for me now. I've attached it.

[Supermodel_UTF8.csv.zip](https://github.com/jasp-stats/jasp-issues/files/2844486/Supermodel_UTF8.csv.zip)

**Comment by dinomandy** [comment]
Thanks for your quick response.  I shall retry it again!  Many thanks!
