### ISSUE TITLE
[Bug]: two-tailed Fisher's exact test

### ISSUE THREAD

**Issue by Diesfeldt** [jasp-stats/jasp-issues#3021]
### JASP Version

0.18.1

### JASP Module

Frequencies

### What analysis are you seeing the problem on?

Contingency Tables

### What OS are you seeing the problem on?

Windows 11

### Bug Description

I try to reproduce in JASP the results of a two-tailed Fisher’s exact test, as discussed on page 134 in Pandit JJ, Picton P, Mashour G. Penehcyclidine and awareness during anaesthesia: caution with zero numerators. Anaesthesia 2013; 68: 121–35. JASP gives the same p-value for a one-tailed and a two-tailed test. However, the 95%-CI of the log odds ratio does not contain zero in the one-tailed test, but contains zero in the two-tailed test. What is going on?
[Pandit2013.zip](https://github.com/user-attachments/files/17802981/Pandit2013.zip)

### Expected Behaviour

JASP should give different p-value for a one-tailed and a two-tailed test. 

### Steps to Reproduce

1.
2.
3.
...
JASP should give different p-value for a one-tailed and a two-tailed test. 

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Thx for the Report. That certainly does not sound correct. Will try confirming later on my system

**Comment by Diesfeldt** [comment]
Thank you very much, Thomas. I am looking forward to the results of your enquiry.

Best,

Han Diesfeldt

________________________________
Van: Thomas Langkamp ***@***.***>
Verzonden: dinsdag 19 november 2024 09:23
Aan: jasp-stats/jasp-issues ***@***.***>
CC: Han Diesfeldt ***@***.***>; Author ***@***.***>
Onderwerp: Re: [jasp-stats/jasp-issues] [Bug]: two-tailed Fisher's exact test (Issue #3021)


Thx for the Report. That certainly does not sound correct. Will try confirming later on my system

**Comment by Diesfeldt** [comment]
Thanks again, the analysis for the dancing cats and dogs is fine, indeed. I enclose my JASP-file. I now see I sent a different but irrelevant file to Git-hub, sorry for that. I hope you will find the data that are enclosed in the file. If not, let me know and I send you an Excess data file (it is just a small table).

Best,

Han


________________________________
Van: Thomas Langkamp ***@***.***>
Verzonden: dinsdag 19 november 2024 10:08
Aan: jasp-stats/jasp-issues ***@***.***>
CC: Han Diesfeldt ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [jasp-stats/jasp-issues] [Bug]: two-tailed Fisher's exact test (Issue #3021)


@Diesfeldt<https://github.com/Diesfeldt>
So I tried this in jasp 0.19.1 flatpak and cannot confirm:

grafik.png (view on web)<https://github.com/user-attachments/assets/6ec28fc1-5d0e-4ed0-b420-72731b4b2272>

Also the jasp file - remove the .zip from the file name to open:
Dancing Cats.jasp.zip<https://github.com/user-attachments/files/17812457/Dancing.Cats.jasp.zip>

The file you attached sadly did not contain any data, only two analysis:
grafik.png (view on web)<https://github.com/user-attachments/assets/2c9e4f3e-1331-4136-a467-1e9e43be7908>

Could you provide your zipped jasp file so that I can check if something with your data is special?

**Comment by Diesfeldt** [comment]
[Pandit2013Count1.zip](https://github.com/user-attachments/files/17813488/Pandit2013Count1.zip)

**Comment by tomtomme** [comment]
I can confirm your observation even with jasp 0.19.2 beta (flatpak). 
But I think this is an extreme edge case. As soon as I fill the one count-cell with a value >0 I get different p-values as expected. 
@FBartos: Any idea on this one?
Also @Kucharssim had some interesting observations regarding fishers exact test here: https://github.com/jasp-stats/jasp-issues/issues/2362#issuecomment-1798093500

Maybe the solution to this riddle lies in between those lines.

**Comment by Diesfeldt** [comment]
Thanks very much, Thomas. I understand the issue of extreme counts. Rather than to rely on Fisher's exact test, one could always use the Bayesian A/B test in JASP Summary Statistics.  Cells having a zero count are no problem. The outcome is very clear, for any hypothesis, one-sided or two-sided.

Thanks again for helping me to understand the riddle.

Best,

Han Diesfeldt


________________________________
Van: Thomas Langkamp ***@***.***>
Verzonden: dinsdag 19 november 2024 13:54
Aan: jasp-stats/jasp-issues ***@***.***>
CC: Han Diesfeldt ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [jasp-stats/jasp-issues] [Bug]: two-tailed Fisher's exact test (Issue #3021)


I can confirm your observation even with jasp 0.19.2 beta (flatpak).
But I think this is an extreme edge case. As soon as I fill the one count-cell with a value >0 I get different p-values as expected.
@FBartos<https://github.com/FBartos>: Any idea on this one?
Also @Kucharssim<https://github.com/Kucharssim> had some interesting observations regarding fishers exact test here: #2362 (comment)<https://github.com/jasp-stats/jasp-issues/issues/2362#issuecomment-1798093500>

Maybe the solution to this riddle lies in between those lines.

**Comment by tomtomme** [comment]
@Diesfeldt 
So from your point of view this issue can now be closed?

**Comment by Diesfeldt** [comment]
Yes, that is okay with me. Thank you and best regards,

Han Diesfeldt

________________________________
Van: Thomas Langkamp ***@***.***>
Verzonden: dinsdag 19 november 2024 14:57
Aan: jasp-stats/jasp-issues ***@***.***>
CC: Han Diesfeldt ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [jasp-stats/jasp-issues] [Bug]: two-tailed Fisher's exact test (Issue #3021)


@Diesfeldt<https://github.com/Diesfeldt>
So from your point of view this issue can now be closed?
