### ISSUE TITLE
[Bug]: wrong description  in translate.md 

### ISSUE THREAD

**Issue by armgong** [jasp-stats/jasp-issues#3022]
### JASP Version

0.19.1

### JASP Module

Unrelated, Machine Learning

### What OS are you seeing the problem on?

Windows 10

### Bug Description

recently , do some translate in jaspmachinelearning (QML-zh_Hans.po), modify the po file ,then want to compile it to qm but failed.
the  translate.md (https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/development/translate.md ) 
~~~
The Qt JASP interface .qm file: jasp_xx.qm
From a terminal run:
> ~/Qt/5.14.2/clang_64/bin/lrelease ./Desktop/po/jasp_xx.po -qm jasp_xx.qm
This creates a jasp_xx.qm.
~~~
but when execute this command , it just stuck there, no return and no any output. 

### Expected Behaviour

success compile po to qm 

### Steps to Reproduce

I installed qt 6.8.0
~~~
c:\Qt\6.8.0\msvc2022_64\bin\lrelease.exe QML-zh_Hans.po -qm QML-zh_Hans.qm
~~~
but when execute this command , it just stuck there, no return and no any output. 

I also try  using  msgfmt compile QML-zh_Hans.po to qm file  ,but  also failed
~~~
# msgfmt.exe --qt -o QML-zh_Hans.qm QML-zh_Hans.po
QML-zh_Hans.po:157:8: syntax error
QML-zh_Hans.po:157: keyword "Tables" unknown
QML-zh_Hans.po:161:8: syntax error
QML-zh_Hans.po:161: keyword "Plots" unknown
QML-zh_Hans.po:173:8: syntax error
QML-zh_Hans.po:173: keyword "Tables" unknown
QML-zh_Hans.po:177:8: syntax error
QML-zh_Hans.po:177: keyword "Plots" unknown
QML-zh_Hans.po:181:8: syntax error
QML-zh_Hans.po:181: keyword "Training" unknown
QML-zh_Hans.po:185:8: syntax error
QML-zh_Hans.po:185: keyword "Algorithmic" unknown
QML-zh_Hans.po:189:8: syntax error
QML-zh_Hans.po:189: keyword "Tables" unknown
QML-zh_Hans.po:193:8: syntax error
QML-zh_Hans.po:193: keyword "Coefficients" unknown
QML-zh_Hans.po:221:8: syntax error
QML-zh_Hans.po:221: keyword "Plots" unknown
QML-zh_Hans.po:237:8: syntax error
QML-zh_Hans.po:237: keyword "Training" unknown
C:\msys64\ucrt64\bin\msgfmt.exe: too many errors, aborting
~~~

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by armgong** [comment]
ohhh, i add wrong char in the po file , now  using msgfmt to create the qm file is ok .

**Comment by boutinb** [comment]
Can we close this issue?

**Comment by armgong** [comment]
Now I can use msgfmt compile po to qm , but when replace the old qm file with it ,  the UI only show eng instead chinese (jaspmachinelearning)

**Comment by armgong** [comment]
Now I can use msgfmt compile po to qm , but when replace the old qm file with it ,  the UI only show eng instead chinese (jaspmachinelearning)

**Comment by armgong** [comment]
after correct po file now lrease also work , now close this issue
