### ISSUE TITLE
[Bug]: Analysis terminated unexpectedly when trying to tick Z test in a One Sample T-Test

### ISSUE THREAD

**Issue by enzoootj** [jasp-stats/jasp-issues#3023]
### JASP Version

0.19.1

### JASP Module

T-Tests

### What analysis are you seeing the problem on?

One Sample T-Test

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

This is what happened when I tick the analysis for Z test in the One Sample T-Test:

Error in ttest$addFootnote(paste(tzNote, wNote)): jaspTable$addFootnote expects 'message' to be a string!

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.ttestOneSampleMainTable(jaspResults, dataset, options, ready, type)

ttest$addFootnote(paste(tzNote, wNote))

stop('jaspTable$addFootnote expects 'message' to be a string!', domain = NA)

### Expected Behaviour

It should've been executed smoothly without any problems at all.

### Steps to Reproduce

1. Click on One Sample T-Test
2. Move the data you want to analyse
3. Under "Tests", there is a checbox for Z test
4. Click on it

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by enzoootj** [comment]
Sure thing. Embedded are the screenshot and the jasp file
<img width="775" alt="SCR-20241120-cjlh" src="https://github.com/user-attachments/assets/89d077fa-868e-44a5-8036-0d19339dedc6">
[Yuyo Quantitative.jasp.zip](https://github.com/user-attachments/files/17819822/Yuyo.Quantitative.jasp.zip)

**Comment by tomtomme** [comment]
I can confirm the issue with 0.19.1. It is fixed as a workaround by also selecting the wilcoxon-signed-rank test. 
The error is already fixed in 0.19.2 beta which will be released in some weeks. I hope this helps!

**Comment by tomtomme** [comment]
See also the duplicate https://github.com/jasp-stats/jasp-issues/issues/2851
