### ISSUE TITLE
[Feature Request]: cronbach's analysis

### ISSUE THREAD

**Issue by golubtsova** [jasp-stats/jasp-issues#3025]
### Description

I can't find cronbach's analysis is the version 0.19

### Purpose

study

### Use-case

uni

### Is your feature request related to a problem?

I can't find cronbach's analysis is the version 0.19

### Is your feature request related to a JASP module?

Reliability

**Comment by juliuspfadt** [comment]
it is "Coefficient alpha" in the unidimensional reliability module

**Comment by golubtsova** [comment]
Thank you so much
