### ISSUE TITLE
Bayesian Regression: Log(BF) in effects table

### ISSUE THREAD

**Issue by JohnnyDoorn** [jasp-stats/jasp-issues#303]
* JASP version: 0.9.2
* OS name and version: Manjaro Linux
* Analysis: Bayesian linear regression
* Bug description: If switching to log(BF), only the Bayes factors in the model table are converted, and not in the effects table (inclusion BF).

* Screenshot: 
![jasp_bayeslinreg_logbfeffectstable](https://user-images.githubusercontent.com/15704203/52526741-1a42f380-2c72-11e9-8d75-c753e1799826.png)

* Expected behaviour: Take log of BF(inclusion) in the effects table

**Comment by vandenman** [comment]
@TimKDJ can probably be fixed in jasp-stats/jasp-desktop#3028
