### ISSUE TITLE
[Bug]: Not sure what is going on 

### ISSUE THREAD

**Issue by AliciaBo** [jasp-stats/jasp-issues#3032]
### JASP Version

0.19.1

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

Anova

### What OS are you seeing the problem on?

Windows 11

### Bug Description

The analysis terminated unexpectedly error in load namespace there is no package called EMMEANS stack trace

### Expected Behaviour

The test should produce comparison results for two variables for an ANOVA test

### Steps to Reproduce

1.Anova test 
2.add variables
3.click descriptive statistics

...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
closed as duplicate
