### ISSUE TITLE
[Bug]: Copy'n'paste from Note is very slow on macOS

### ISSUE THREAD

**Issue by iandol** [jasp-stats/jasp-issues#3034]
### Description

For each analysis we can add a Note. I use it to remind me which filter I need for that analysis block. I would like to be able to copy text from it. But because it is an editable section you can't make selections easily.

### Purpose

Add R filter code to note and be able to copy it quickly

### Use-case

Filtering data for each analysis module result

### Is your feature request related to a problem?

Once https://github.com/jasp-stats/jasp-issues/issues/1330 is fixed, I wouldn't need to put R Code in my notes

### Is your feature request related to a JASP module?

Unrelated

### Additional context

I want to select an analysis result , then copy the R code for the filter `Visual-Area == "V1" & subject == "amb"` from the Note:

<img width="699" alt="image" src="https://github.com/user-attachments/assets/e47b795a-99fb-403f-8f9e-43d993a393e3">

But this text is not selectable, maybe this only happens on macOS (i.e. maybe the select behaviour is OS specific?)

**Comment by shun2wang** [comment]
Hi @iandol  Did you have tried `Command+C` to copy it? I can select and copy paste from note on Windows/Linux, but I don't think it has anything related with the system..

**Comment by iandol** [comment]
I can't select with the mouse, so there is nothing to ⌘c -- I can double click it to enter an edit mode, then try to select, although selection is still hard for code in edit mode. Possibly I should accept to not use code display in the editor and it should make selection easier...

**Comment by shun2wang** [comment]
Well, maybe @boutinb on macOS can try this, I can select code block anyway on my PC.

**Comment by iandol** [comment]
https://github.com/user-attachments/assets/aa7dc91c-d2f0-4a14-8f1f-04097f1b6af8

I restarted JASP and things are a bit better. Selection is extremely slow. The screencast has my drag events visualised, you can see I drag to select the text but no highlight is visible. At the last attempt I wait ~4 seconds and finally I get the selection and I can copy. I do have 21 analysis blocks, but everything else in the GUI seems fast and responsive...

M2 macbook air 16GB.

**Comment by shun2wang** [comment]
You are not use a release version right? which nightly build did you used? just copy the debug info from "about window"and paste below:

**Comment by iandol** [comment]
-------- Application Info --------
JASP Version: JASP 0.19.2 (Apple Silicon)
Build Branch: HEAD
Build Date: Nov 23 2024 06:13:44 (Netherlands)
Last Commit: ed6c07b49b0fd4d6afa2040139c66d49079db9fc

-------- Basic Info --------
Operating System: macOS Sequoia (15.2)
Product Version: 15.2
Kernel Type: darwin
Kernel Version: 24.2.0
Architecture: arm64
Install Path: /Applications/JASP.app/Contents/MacOS
Platfotm Name: cocoa
System Local: en_US


https://github.com/user-attachments/assets/9601c08a-7ce7-452d-a657-2c6603b956a5

Using Vivaldi (a chrome-based browser)

**Comment by shun2wang** [comment]
we cannot reproduce it on Mac. so we will waiting for a reproduce path to find out.what happened.

**Comment by iandol** [comment]
I can't share my current jasp file, but tried to recreate one with mock data:

[scientific_environmental_data.jasp.zip](https://github.com/user-attachments/files/17927741/scientific_environmental_data.jasp.zip)

This is still faster than my real project, but as I've added analyses the selection speed has got slower:

https://github.com/user-attachments/assets/d9d96d40-2586-4a89-a3a9-1292969da477

The screencast shows about 15 frames from when I first click to the highlight showing (20fps video so ~0.7secs?).

**Comment by shun2wang** [comment]
hi @iandol you can email to me (shuonwang(at)gmail.com)then we will find a chance to remote debug this.

**Comment by iandol** [comment]
@shun2wang -- email sent, though did my attached jasp show no slowdown?
@tomtomme -- I used H.265, which plays back without issue on my macbook (Vivaldi, a Chrome-based browser), but indeed the same browser but on Ubuntu and the videos fail (**though if you download the MP4 and play it in VLC it works**). I will use H.264 going forwards...

**Comment by iandol** [comment]
H264:

https://github.com/user-attachments/assets/0d3717f3-25f1-45fb-b96a-ce42a463e127

**Comment by tomtomme** [comment]
Just noticed, all vids work on android

**Comment by iandol** [comment]
@shun2wang -- sorry I did not get back to you. However testing in the new 0.19.2 release and my issue has gone, so we can close this I think, thank you all for a great release and really looking forwards to the next version (I really hope per analysis filtering makes it)!

**Comment by shun2wang** [comment]
Ah, that's good! because old quill.js(used by jasp nodes) version had performance problems indeed. 0.19.2 was updated it.
