### ISSUE TITLE
[Bug]: Kan bestand niet openen omdat:....

### ISSUE THREAD

**Issue by gdjonge** [jasp-stats/jasp-issues#3035]
### JASP Version

0.19.1

### JASP Module

Other

### What analysis are you seeing the problem on?

Data import of csv

### What OS are you seeing the problem on?

Windows 10

### Bug Description

[Jasp bug report.pdf](https://github.com/user-attachments/files/17899510/Jasp.bug.report.pdf)

### Expected Behaviour

Cannot import csv file 216 rows and 4000 columns
[ovariancancer_obs Jasp.csv](https://github.com/user-attachments/files/17899528/ovariancancer_obs.Jasp.csv)

### Steps to Reproduce

1.
2.
3.
...

### More Debug Information

Same problem with Jasp on Imac

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
I thought @JorisGoosen changed this limit.

**Comment by JorisGoosen** [comment]
It is @RensDofferhoff who found a setting to change in https://github.com/jasp-stats/jasp-desktop/commit/22034712b121d8fdaa13ddfd03768aaff74d0723 but that only works for conan, and we do not use that on linux. (Which we could add, I guess we forgot, maybe we can have a specific issue for that?)

It should however work on macos/windows.

**Comment by shun2wang** [comment]
>maybe we can have a specific issue for that?
Yes, we have this: https://github.com/jasp-stats/INTERNAL-jasp/issues/2421

**Comment by JorisGoosen** [comment]
That is more for having more than 16k columns.

I mean specifically for fixing the build on linux. This issue itself is from someone who cant open it on windows, which I assume now *does* work in the win/mac nightlies

**Comment by TarandeepKang** [comment]
Hi all, I confirm that I can open this file in approximately five minutes on my Windows 11 Asus ZenBook, Intel Core i7, 16 GB RAM. Is that roughly what is to be expected? 

Below is some debug information.

Best

Tarandeep
-------- Application Info --------
JASP Version: JASP 0.19.2
Build Branch: development
Build Date: Nov 14 2024 15:42:34 (Netherlands)
Last Commit: b9879fd2ebc5048e619cc8a28fd467f45adab1ea

-------- Basic Info --------
Operating System: Windows 11 Version Dev
Product Version: 11
Kernel Type: winnt
Kernel Version: 10.0.27754
Architecture: x86_64
Install Path: C:/Program Files (x86)/JASP
Platfotm Name: windows
System Local: en_GB

-------- Extra Info --------
Current code page
Active code page: 850
Active code page: 65001

**Comment by JorisGoosen** [comment]
So yeah, this should now work fine on windows and macos.

It does not work on linux, but we could build sqlite there with the same flags.
However this issue is not the best place to treack this.
