### ISSUE TITLE
[Feature Request]: Spanish Language

### ISSUE THREAD

**Issue by LolaAguilar** [jasp-stats/jasp-issues#3040]
### Description

I would like to platform to be translated to spanish so I can use it more easily

### Purpose

Efficiency

### Is your feature request related to a problem?

I couldn´t find language adjustments

### Describe the solution you would like

Options of other languages for usage

**Comment by EJWagenmakers** [comment]
Click the hamburger item on the top right -> Preferences -> Interface -> Preferred langues -> select Spanish from a list with 14 options :-)
Let us know if it remains unclear
