### ISSUE TITLE
[Bug]: The engine crashed while trying to run the filter...

### ISSUE THREAD

**Issue by CatarinaCanelas** [jasp-stats/jasp-issues#3045]
### JASP Version

0.19.1

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 11

### Bug Description

When I open my database there's a message in red saying that the engine crashed while trying to run the filter, even before I tried to do any analysis. But if I do try to run something it doesn't work and says ''waiting for initialization (of the engine) 
![jasp bug](https://github.com/user-attachments/assets/99f3463e-32e3-4d10-baf2-ddae74d47d4a)

### Expected Behaviour

It shouldn't show that message and should allow me to run the analyses.

### Steps to Reproduce

I opened my data base only.

### More Debug Information

-------- Application Info --------
JASP Version: JASP 0.19.1
Build Branch: lockfiletesting
Build Date: Sep  9 2024 19:00:04 (Netherlands)
Last Commit: 8ac10c9c7aec029fdd695262d7bb4c3742a8ec89

-------- Basic Info --------
Operating System: Windows 10 Version 1809
Product Version: 10
Kernel Type: winnt
Kernel Version: 10.0.17763
Architecture: x86_64
Install Path: C:/Program Files (x86)/JASP
Platfotm Name: windows
System Local: pt_PT

-------- Extra Info --------
Current code page
Active code page: 850
Active code page: 65001

Host Name:                 FUNCIONASEUFDP
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17763 N/A Build 17763
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Nuno
Registered Organization:   
Product ID:                00330-80000-00000-AA168
Original Install Date:     10/01/2019, 13:54:07
System Boot Time:          24/11/2024, 20:27:59
System Manufacturer:       Dell Inc.
System Model:              Latitude E6540
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 60 Stepping 3 GenuineIntel ~2801 Mhz
BIOS Version:              Dell Inc. A26, 09/10/2018
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             pt;Português (Portugal)
Input Locale:              pt;Português (Portugal)
Time Zone:                 (UTC+00:00) Dublin, Edimburgo, Lisboa, Londres
Total Physical Memory:     16 289 MB
Available Physical Memory: 8 257 MB
Virtual Memory: Max Size:  19 221 MB
Virtual Memory: Available: 9 324 MB
Virtual Memory: In Use:    9 897 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\FUNCIONASEUFDP
Hotfix(s):                 25 Hotfix(s) Installed.
                           [01]: KB4580979
                           [02]: KB4470788
                           [03]: KB4480056
                           [04]: KB4486153
                           [05]: KB4486173
                           [06]: KB4493510
                           [07]: KB4494174
                           [08]: KB4499728
                           [09]: KB4504369
                           [10]: KB4509095
                           [11]: KB4512577
                           [12]: KB4512937
                           [13]: KB4521862
                           [14]: KB4523204
                           [15]: KB4524244
                           [16]: KB4539571
                           [17]: KB4549947
                           [18]: KB4561600
                           [19]: KB4562562
                           [20]: KB4566424
                           [21]: KB4570332
                           [22]: KB4577586
                           [23]: KB4580325
                           [24]: KB4587735
                           [25]: KB4586793
Network Card(s):           5 NIC(s) Installed.
                           [01]: Intel(R) Ethernet Connection I217-LM
                                 Connection Name: Local Area Connection
                                 Status:          Media disconnected
                           [02]: Intel(R) Centrino(R) Advanced-N 6235 Driver
                                 Connection Name: Wireless Network Connection
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.1.1
                                 IP address(es)
                                 [01]: 192.168.1.170
                                 [02]: fe80::54f2:174d:b05:84b7
                                 [03]: 2a01:11:8030:6390:e041:1c8a:1e8d:41d
                                 [04]: 2a01:11:8030:6390:54f2:174d:b05:84b7
                           [03]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
                           [04]: TAP-Windows Adapter V9
                                 Connection Name: Local Area Connection 2
                                 Status:          Media disconnected
                           [05]: Dell Wireless 5570 HSPA+ (42Mbps) 4G LTE Mobile Broadband Card
                                 Connection Name: Ethernet 2
                                 Status:          Media disconnected
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
I cannot reproduce this error. 
Do you get this error only when loading data from a database, or can you load data from a csv file?

**Comment by CatarinaCanelas** [comment]
It happens with csv as well.

![image](https://github.com/user-attachments/assets/29107733-485a-4c0c-83b2-b690633aa15d)

**Comment by shun2wang** [comment]
@CatarinaCanelas  Could you open the Windows Process Explorer and see if it has multiple JASP running instance or JASPEngine?

**Comment by CatarinaCanelas** [comment]
This is what I see
![image](https://github.com/user-attachments/assets/f708ef1f-29e5-4edb-8ed3-bdcb0893fe01)

**Comment by CatarinaCanelas** [comment]
Is that one supposed to be killed as well? It doesn't let me

![image](https://github.com/user-attachments/assets/17719a34-7303-47c4-8d06-23a4eb6b8564)

**Comment by tomtomme** [comment]
then restart your computer. That forces a restart of every app

**Comment by shun2wang** [comment]
@boutinb @JorisGoosen Is there anything we can do here?  maybe there are multiple instances of JASP running might have some conflicts, I have no idea.

**Comment by CatarinaCanelas** [comment]
This issue has been happening for a week, if uninstalled and installed about 5x or more, I've restarted everything and nothing works. I also updated my drivers but it crashed my pc so I had to undo the changes.

**Comment by JorisGoosen** [comment]
@CatarinaCanelas did you install JASP from a ZIP or an installer from our website, our perhaps from the microsoft store?

Also perhaps @tomtomme is right, it could be your harddrive is full. Or perhaps there is something else wrong with the machine? (given that you had to "undo the changes")

**Comment by CatarinaCanelas** [comment]
I realized now I have windows 10 pro, not 11. I installed from your website (not zip). I have a 16gb ram and 60gb of free space... I just uninstalled and installed again and nothing. Could I try the previous version? How different is it?

**Comment by JorisGoosen** [comment]
Maybe try the one from the microsoft store. 
Just uninstall the one you have and then install it from there.

**Comment by CatarinaCanelas** [comment]
Ok so my boyfriend fixed it. The windows needed an update that we were not able to complete online so he had to do it through the windows offline tool, after many updates Jasp is finally working perfectly.

**Comment by boutinb** [comment]
Fine!! Enjoy JASP hopefully now!

**Comment by JorisGoosen** [comment]
Sounds like a very practical boyfriend to have around ^^
