### ISSUE TITLE
[Bug]: Cannot find object in prediction using various models

### ISSUE THREAD

**Issue by vladimirsim** [jasp-stats/jasp-issues#3048]
### JASP Version

0.19.1

### JASP Module

Machine Learning

### What analysis are you seeing the problem on?

Prediction

### What OS are you seeing the problem on?

Windows 11

### Bug Description

The prediction table based on a trained KNN model did not load.

### Expected Behaviour

The prediction table should load.

### Steps to Reproduce

1. Train a KNN model on a training dataset and save it
2. Open Machine Learning> Prediction>Prediction
3. Load a test or prediction dataset (different from the training dataset) and load the trained model
4. Load the features from the trained model. The prediction table fails to load.
I am attaching a printscreen:
![image](https://github.com/user-attachments/assets/71f46ca7-d7c8-4fa0-aa3d-352ca4bcb621)

This is the trained KNN model:
[KNNTrainedModelVladimirsim.zip](https://github.com/user-attachments/files/17946960/KNNTrainedModelVladimirsim.zip)

...

### Log (if any)

[JASP 2024-11-28 10_52_36 Desktop vladimirsim.zip](https://github.com/user-attachments/files/17946921/JASP.2024-11-28.10_52_36.Desktop.vladimirsim.zip)

### More Debug Information

**This is the error message which I got while trying to predict values using a trained KNN model:**
This analysis terminated unexpectedly.

Error in eval(predvars, data, env): object 'Good' not found

Stack trace
jaspStateR$new(object = object, dependencies = dependencies)

initialize(...)

.mlPredictionGetPredictions(model, dataset)

.mlPredictionGetPredictions.kknn(model, dataset)

kknn:::predict.train.kknn(model[['predictive']], dataset)

kknn(formula(terms(object)), object$data, newdata, k = object$best.parameters$k, kernel = object$best.parameters$kernel, distance = object$distance)

model.frame(formula, data = train)

model.frame.default(formula, data = train)

eval(predvars, data, env)

eval(predvars, data, env)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by koenderks** [comment]
https://github.com/jasp-stats/jaspMachineLearning/pull/393 should have fixed this for 0.19.2, but I can't know for sure if I don't have the data. You might test this fix yourself using the latest development version from https://static.jasp-stats.org/Nightlies/

**Comment by koenderks** [comment]
The bug fix was only incorporated into the development version yesterday (23 hours ago), so I would assume that only the latest nightly from 27-11-24 (in the evening) might have this fix in it. Could you try the latest version?

**Comment by koenderks** [comment]
Good to hear! I'm closing this issue then
