### ISSUE TITLE
width of descriptives plot in RM ANOVA

### ISSUE THREAD

**Issue by SophiaCruwell** [jasp-stats/jasp-issues#305]
* JASP version: 0.9.2
* OS name and version: Mojave 10.14.2
* Analysis: Repeated Measures ANOVA
* Bug description: There's something wrong with the width of the descriptives plots as they come out. It's not major – if you drag them around a little bit they kind of look normal – but it's probably not what it's meant to be like.
* Add JASP files as a zip: 
[LooksOrPersonality.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/2851584/LooksOrPersonality.jasp.zip)
* Screenshot: 
![screenshot 2019-02-11 at 16 01 26](https://user-images.githubusercontent.com/33629901/52571666-4f884680-2e16-11e9-851e-b9b7764dc352.png)
* Expected behaviour: showing nice plots immediately 
* Steps to reproduce: 
1. Go to ANOVA, RM ANOVA
2. Fill in the RM Factors & Cells as in the screenshot/file
3. Get descriptives plots: Put Looks on Horizontal axis, Charisma in separate lines and Strategy in Separate Plots
4. See error – squashed plots

**Comment by AlexanderLyNL** [comment]
@koenderks consider this an extension of issue #270
