### ISSUE TITLE
[Bug]: Case number of casewise diagnostic does not match row number

### ISSUE THREAD

**Issue by Micronsm** [jasp-stats/jasp-issues#3054]
### JASP Version

0.19.1

### JASP Module

Regression

### What analysis are you seeing the problem on?

Linear Regression / Casewise diagnostics

### What OS are you seeing the problem on?

Windows 10

### Bug Description

Case Numbers of casewise diagnostic from linear regression does not match the row number (e.g. 467)  in the dataset (first row under filter symbol). If the module detects outliers, they can checked and then filtered or deleted by hand. If this is done, the outlier is still there, now with a new Case Number (mostly 467-1 = 466).

Dataset with ~900 rows.

![Casewise1](https://github.com/user-attachments/assets/5a613b0a-a597-40b1-9190-3541c2dd3db0)
![Casewise2](https://github.com/user-attachments/assets/f351bd79-ec21-4065-9b45-dbd39b1e597d)
![Casewise3](https://github.com/user-attachments/assets/1a267d6a-19df-4ddf-9892-df7ef7ca9c70)

Still the case in _JASP-nightly-HEAD-aef9532c4158cd42d5ef341c086eeed801790478_.
When using this version, the generated columns (calculation of mean values of other columns in the data set) are emptied after deleting individual rows = linear regression fails to compute afterwards.

### Expected Behaviour

The Case Number should match the row number to enable the data to be allocated accurately

### Steps to Reproduce

1. Linear Regression
2. Add variables
3. Statistics
4. Casewise diagnostic
5. Check Case Number of outlier
6. Delete Case Number in dataset
7. Casewise diagnostic still shows outlier
...

### More Debug Information

-------- Application Info --------
JASP Version: JASP 0.19.1
Build Branch: lockfiletesting
Build Date: Sep 9 2024 19:00:04 (Netherlands)
Last Commit: 8ac10c9c7aec029fdd695262d7bb4c3742a8ec89

-------- Basic Info --------
Operating System: Windows 10 Version 22H2
Product Version: 10
Kernel Type: winnt
Kernel Version: 10.0.19045
Architecture: x86_64
Install Path: C:/Program Files (x86)/JASP
Platfotm Name: windows
System Local: de_DE

-------- Extra Info --------
Current code page
Aktive Codepage: 850.
Aktive Codepage: 65001.

Hostname: **********
Betriebssystemname: Microsoft Windows 10 Education
Betriebssystemversion: 10.0.19045 Nicht zutreffend Build 19045
Betriebssystemhersteller: Microsoft Corporation
Betriebssystemkonfiguration: Eigenständige Arbeitsstation
Typ des Betriebssystembuilds: Multiprocessor Free
Registrierter Benutzer: **********
Registrierte Organisation:
Produkt-ID: 00328-00000-00000-AA757
Ursprüngliches Installationsdatum: 02.10.2021, 11:30:08
Systemstartzeit: 28.11.2024, 20:00:10
Systemhersteller: Micro-Star International Co., Ltd.
Systemmodell: MS-7A40
Systemtyp: x64-based PC
Prozessor(en): 1 Prozessor(en) installiert.
[01]: AMD64 Family 25 Model 33 Stepping 0 AuthenticAMD ~3501 MHz
BIOS-Version: American Megatrends International, LLC. B.90, 25.07.2022
Windows-Verzeichnis: C:\windows
System-Verzeichnis: C:\windows\system32
Startgerät: \Device\HarddiskVolume1
Systemgebietsschema: de;Deutsch (Deutschland)
Eingabegebietsschema: de;Deutsch (Deutschland)
Zeitzone: (UTC+01:00) Amsterdam, Berlin, Bern, Rom, Stockholm, Wien
Gesamter physischer Speicher: 32.694 MB
Verfügbarer physischer Speicher: 20.922 MB
Virtueller Arbeitsspeicher: Maximale Größe: 37.558 MB
Virtueller Arbeitsspeicher: Verfügbar: 18.172 MB
Virtueller Arbeitsspeicher: Zurzeit verwendet: 19.386 MB
Auslagerungsdateipfad(e): C:\pagefile.sys
Domäne: WORKGROUP
Anmeldeserver: \**********
Hotfix(es): 40 Hotfix(e) installiert.
[01]: KB5045933
[02]: KB5030841
[03]: KB5000736
[04]: KB5011048
[05]: KB5011054
[06]: KB5012170
[07]: KB5015684
[08]: KB5046613
[09]: KB5006753
[10]: KB5007273
[11]: KB5011352
[12]: KB5011651
[13]: KB5014032
[14]: KB5014035
[15]: KB5014671
[16]: KB5015895
[17]: KB5016705
[18]: KB5018506
[19]: KB5020372
[20]: KB5022924
[21]: KB5023794
[22]: KB5025315
[23]: KB5026879
[24]: KB5028318
[25]: KB5028380
[26]: KB5029709
[27]: KB5031539
[28]: KB5032392
[29]: KB5032907
[30]: KB5034224
[31]: KB5036447
[32]: KB5037018
[33]: KB5037240
[34]: KB5037995
[35]: KB5039336
[36]: KB5041579
[37]: KB5043935
[38]: KB5043130
[39]: KB5046823
[40]: KB5005699
Netzwerkkarte(n): 4 Netzwerkadapter installiert.
[01]: TAP-Windows Adapter V9 for OpenVPN Connect
Verbindungsname: LAN-Verbindung
Status: Medien getrennt
[02]: OpenVPN Data Channel Offload
Verbindungsname: OpenVPN Connect DCO Adapter
Status: Medien getrennt
[03]: Realtek PCIe GbE Family Controller
Verbindungsname: Ethernet 2
Status: Medien getrennt
[04]: Intel(R) Wireless-AC 9260 160MHz
Verbindungsname: WLAN 2
DHCP aktiviert: Ja
DHCP-Server: 192.168.178.1
IP-Adresse(n)
[01]: 192.168.178.23
[02]: fe80::33c:1046:2c0f:1aa5
[03]: fd00::680e:445e:42ae:c399
[04]: 2001:9e8:8e3f:4d00:680e:445e:42ae:c399
[05]: fd00::44ff:7105:5773:3002
[06]: 2001:9e8:8e3f:4d00:a411:da18:3125:1926
Anforderungen für Hyper-V: Erweiterungen für den VM-Überwachungsmodus: Ja
Virtualisierung in Firmware aktiviert: Nein
Adressübersetzung der zweiten Ebene: Ja
Datenausführungsverhinderung verfügbar: Ja

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@Micronsm 
could you share your zipped jasp file by drag and dropping it here? that makes it easier to debug

**Comment by tomtomme** [comment]
for me this works fine with the data library file college success on 0.19.1 and 0.19.2 beta flatpak. So it might be a windows or data specific error

**Comment by JohnnyDoorn** [comment]
This was indeed a bug if there is missingness in the data, but I already fixed it and it should be in 0.19.2 (released next week). Apologies for the confusion @Micronsm. 

Kind regards
Johnny
