### ISSUE TITLE
[Bug]: ANOVA - This analysis terminated unexpectedly - Error in `[[<-.data.frame`(`*tmp*`, 'cases', value = c('W21-Q05', : replacement has 4 rows, data has 3

### ISSUE THREAD

**Issue by TeamA2XDev** [jasp-stats/jasp-issues#3057]
### JASP Version

0.19.1

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

Classical ANOVA

### What OS are you seeing the problem on?

Windows 11

### Bug Description

Received the following error message:

This analysis terminated unexpectedly.

Error in `[[<-.data.frame`(`*tmp*`, 'cases', value = c('W21-Q05', : replacement has 4 rows, data has 3

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

AncovaInternal(jaspResults, dataset = NULL, options)

.anovaTable(anovaContainer, options, ready)

.anovaResult(anovaContainer, options)

`[[<-`(`*tmp*`, 'cases', value = c('W21-Q05', 'W21-Q06', 'W21-Q05 ✻ W21-Q06', 'Residuals'))

`[[<-.data.frame`(`*tmp*`, 'cases', value = c('W21-Q05', 'W21-Q06', 'W21-Q05 ✻ W21-Q06', 'Residuals'))

stop(sprintf(ngettext(N, 'replacement has %d row, data has %d', 'replacement has %d rows, data has %d'), N, nrows), domain = NA)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports
[2024-11-30 - Survey Results - Working Copy-v1.1-BugReport.zip](https://github.com/user-attachments/files/17965866/2024-11-30.-.Survey.Results.-.Working.Copy-v1.1-BugReport.zip)
![Screenshot 2024-11-30 150026H GMT](https://github.com/user-attachments/assets/083b3f5a-b1f1-4c68-ad49-29cd468bb8e9)

### Expected Behaviour

- Completed ANOVA analysis for each fixed factor plus residuals
- Kruskal-Wallis test results for each variable
- Dataset does not appear to be the cause as the same dataset generates Kruskal-Wallis test results in PSPP v.2.0.0-g5b54d1

### Steps to Reproduce

1. Load dataset
2. Select "ANOVA" from "ANOVA > Classical"
3. Set Column "ID" as dependent variable
4. Select Q05 and Q06 from any of these workflows as the fixed factors: W03, W04, W05, W06, W12, W13, W16, W17, W19, W20, W21
5. Model > Sum of squares = Type I
6. Nonparametrics > Kruskal-Wallis Test > Select Q05 and Q06 from any of these workflows as the variables: W03, W04, W05, W06, W12, W13, W16, W17, W19, W20, W21
7. Analysis terminates and error message appears

### Log (if any)

[JASP 2024-11-30 15_47_11 Desktop.log](https://github.com/user-attachments/files/17965867/JASP.2024-11-30.15_47_11.Desktop.log)
[JASP 2024-11-30 15_47_11 Engine 0.log](https://github.com/user-attachments/files/17965868/JASP.2024-11-30.15_47_11.Engine.0.log)

### More Debug Information

-------- Application Info --------
JASP Version: JASP 0.19.1
Build Branch: lockfiletesting
Build Date: Sep  9 2024 19:00:04 (Netherlands)
Last Commit: 8ac10c9c7aec029fdd695262d7bb4c3742a8ec89

-------- Basic Info --------
Operating System: Windows 11 Version 23H2
Product Version: 11
Kernel Type: winnt
Kernel Version: 10.0.22631
Architecture: x86_64
Install Path: C:/Program Files (x86)/JASP
Platfotm Name: windows
System Local: en_US

-------- Extra Info --------
Current code page
Active code page: 437
Active code page: 65001

Host Name:                 A2XPLHQBCND1131
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22631 N/A Build 22631
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Windows User
Registered Organization:   
Product ID:                00330-53524-10069-AAOEM
Original Install Date:     2023-12-27, 23:20:32
System Boot Time:          2024-11-30, 15:33:28
System Manufacturer:       HP
System Model:              HP EliteBook x360 1030 G7 Notebook PC
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 166 Stepping 1 GenuineIntel ~1803 Mhz
BIOS Version:              HP S93 Ver. 01.18.01, 2024-08-26
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb
Total Physical Memory:     32,060 MB
Available Physical Memory: 19,228 MB
Virtual Memory: Max Size:  34,108 MB
Virtual Memory: Available: 19,151 MB
Virtual Memory: In Use:    14,957 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\A2XPLHQBCND1131
Hotfix(s):                 4 Hotfix(s) Installed.
                           [01]: KB5045935
                           [02]: KB5027397
                           [03]: KB5046732
                           [04]: KB5046729
Network Card(s):           4 NIC(s) Installed.
                           [01]: Intel(R) Wi-Fi 6 AX201 160MHz
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     10.0.0.1
                                 IP address(es)
                                 [01]: 10.0.0.102
                                 [02]: fe80::325a:4374:1b44:34bb
                                 [03]: 2a02:a311:398:8e80:34e3:36e0:3706:fd62
                                 [04]: 2a02:a311:398:8e80:190d:368d:531d:c7cc
                           [02]: Generic Mobile Broadband Adapter
                                 Connection Name: Cellular
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 10.81.23.163
                                 [02]: fe80::c0da:d8d8:b25f:c2db
                           [03]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
                           [04]: Realtek USB GbE Family Controller
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Thx for the report. First of all your Win11 installation is seriously out of date: Windows 11 Version 23H2
But the chance that this is the problem here is quite low. It is possibly data related, especially since the error message says "replacement has 4 rows, data has 3"
I tried KW-Test with 2 factors and type I SumofSquares with my 0.19.1 installation and data from the library and its fine.
PSPP is no benchmark here, since certainly is not using exactly the same algorithms and data processing steps as JASP. 

So, can you drag and drop your zipped jasp-file here?

**Comment by TeamA2XDev** [comment]
Hi Thomas,

Thank you for looking into this report. Feedback follows:

- The OS version is correct; the impacted computer is a managed workstation configured to receive Windows feature updates semi-annually to maintain a feature update cadence of n-2. It is fully updated with security patches
- Following this bug report, it was discovered that the test was being run using untransformed data (the dependent variable was not a latent variable that had been transformed to the same scale as the fixed factors). This has been rectified and the desired results have been obtained. The closure of this bug report has been considered but it would be helpful to confirm that this is the intended application behavior in such scenarios
- Attached is the data file created to reproduce this issue

Thanks again and your assistance is much appreciated.

[2024-11-30 - Survey Results - Working Copy-v1.1-BugReport.zip](https://github.com/user-attachments/files/17975790/2024-11-30.-.Survey.Results.-.Working.Copy-v1.1-BugReport.zip)

**Comment by tomtomme** [comment]
Interesting. In the data you send the DV is just an ID running from number 1 to 35. How can this be the correct variable to analyze?

Also: 
![grafik](https://github.com/user-attachments/assets/21391132-2aa3-470f-af56-55be8c954147)


Here you see two of your IVs in a cross tab. Many cells contain 0 data. For an ANOVA every cell would at least need 1 or 2 observations. To make it robust at least 10 per cell would be needed.

**Comment by tomtomme** [comment]
Yes.
