### ISSUE TITLE
JASP crashes after Network analysis

### ISSUE THREAD

**Issue by CogniMath** [jasp-stats/jasp-issues#306]
Hi, I need to perform a Network analysis (with bootstrap) and after is completed , JASP crashes.

**Comment by vandenman** [comment]
Thanks for reporting the error! Can you perhaps include the dataset you are using, and tell us the steps we can take to reproduce the error?

**Comment by AlexanderLyNL** [comment]
The fix will be incorporated in the next version 0.9.3
