### ISSUE TITLE
[Bug]: Error in .subset2(x, i, exact = exact)

### ISSUE THREAD

**Issue by ZeynepFirtina** [jasp-stats/jasp-issues#3061]
### JASP Version

0.19.1

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

Mixed ANOVA

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

This analysis terminated unexpectedly.

Error in .subset2(x, i, exact = exact): attempt to select less than one element in get1index

Stack trace

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

### Expected Behaviour

I just wanted to click pool error term for follow up tests and flag significant comparisons

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by JohnnyDoorn** [comment]
Hi @ZeynepFirtina ,

Can you upload the .jasp file where you encountered the error? you can do so by changing the file extension from .jasp to .zip, but you can also email the .jasp file to me. That way I can get a closer look to see where the error lies.

Cheers,
Johnny

**Comment by tomtomme** [comment]
attaching a file via mail does not work. Please share your zipped jasp file by drag and dropping it here.

**Comment by JohnnyDoorn** [comment]
This was fixed in https://github.com/jasp-stats/jaspAnova/pull/384, so will be in 0.19.2.
