### ISSUE TITLE
Jasp Update

### ISSUE THREAD

**Issue by Aneesa66** [jasp-stats/jasp-issues#3065]
### Description

Jasp update

### Purpose

university assignment

### Additional context

i am trying to update my version of Jasp (0.19.1.0) to get the 'Officer' package version that came out in October 2024. How can I get access to this as i need to use on of the features?

**Comment by tomtomme** [comment]
@Aneesa66 
I cannot think of anything within JASP that is called "Officer". What do you mean?

**Comment by Aneesa66** [comment]
It’s fine, I meant the office package that comes with the jasp .19. I have figured out how to use the feature I was looking for. Thanks anyway

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tomtomme** [comment]
Thx for the feedback. I have still no idea what "the office package" is, but I understand that we can close this issue. Please reopen if I misunderstood.

**Comment by shun2wang** [comment]
JASP 0.19.2 will include `officer 0.6.7` version so maybe it's your purpose.

**Comment by tomtomme** [comment]
Interesting. There is indeed such an R-Package within JASP since 0.13: https://jasp-stats.org/2020/07/28/a-hack-for-editing-jasp-graphs/
