### ISSUE TITLE
[Bug]: Over translation in Japanese Environment

### ISSUE THREAD

**Issue by momoldo** [jasp-stats/jasp-issues#3077]
### JASP Version

0.19.2

### JASP Module

Regression

### What analysis are you seeing the problem on?

Regression -> Traditional -> Correlation -> Plot -> Scatterdiagram -> Statistics

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

Only in Japanese mode, output of Scatter diagram contains wrong r discription.
![image](https://github.com/user-attachments/assets/cb8a754e-6385-4481-acf0-ed0b232f92e3)

The discription "r = -0.260" is proper, but in Japanese mode  "イタリック(r)=-0.260".
This bug is seen from 0.19.0.

### Expected Behaviour

The same output is suitable between In English and in Japanese.
![image](https://github.com/user-attachments/assets/7980dabb-e13b-4119-9dd9-78e6456667d8)
 

### Steps to Reproduce

1. Preferences -> Interface -> Choose language -> ja - 日本語
2. 回帰 -> 伝統的 -> 相関
3. add variables 
4. プロット -> 散布図 -> 統計量
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
We've just released 0.19.2, so you will have to wait for the next release (3-4 months) to have this fix.
