### ISSUE TITLE
[Bug]: Informed Multinomial gives fatal error message no matter what I try to do

### ISSUE THREAD

**Issue by janderuiter** [jasp-stats/jasp-issues#3080]
### JASP Version

0.19.2

### JASP Module

Frequencies

### What analysis are you seeing the problem on?

Informed Multinomial

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

I was trying to use the Informed Multinomial (Bayesian -- of course) and whatever I did, I got an angry red error message screen in my results window. 

I tried to do a proportions (descriptive), a table, and a model comparison. 

I then thought it was because I read a .jasp file so I then tried for a 4th time with just a .csv dataset, and the same thing happened when I asked for a table. 

Screenshots and test dataset attached. 
![Screenshot 2024-12-11 at 18 13 50](https://github.com/user-attachments/assets/4d049db4-d075-4039-aa4d-6da3081a7b5f)
![Screenshot 2024-12-11 at 18 05 53](https://github.com/user-attachments/assets/c0b70894-2de1-407f-a25a-04ad50ce71ae)
![Screenshot 2024-12-11 at 18 04 42](https://github.com/user-attachments/assets/2cc1ed82-89eb-4259-9197-c5c1f2774c8c)
![Screenshot 2024-12-11 at 18 03 22](https://github.com/user-attachments/assets/27b1c801-31ac-4752-8829-a4e3f74b5c5a)
[135.csv](https://github.com/user-attachments/files/18103492/135.csv)

### Expected Behaviour

I should have seen the results of the analyses I requested. 

### Steps to Reproduce

1. Start JASP 
2. Load Dataset
3. Select "count" as factor
4. go to informed multinomial (under Frequencies)
5. Pick any analysis
...

### More Debug Information

-------- Application Info --------
JASP Version: JASP 0.19.2 (Apple Silicon)
Build Branch: development
Build Date: Dec  9 2024 12:29:50 (Netherlands)
Last Commit: 410d926e25afc551d362204f8e57971185234544

-------- Basic Info --------
Operating System: macOS Sequoia (15.1)
Product Version: 15.1
Kernel Type: darwin
Kernel Version: 24.1.0
Architecture: arm64
Install Path: /Applications/JASP.app/Contents/MacOS
Platfotm Name: cocoa
System Local: en_US

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
This is quite annoying. @janderuiter do you have brew installed on your Mac?

**Comment by RensDofferhoff** [comment]
As a workaround you could install the intel version of MacOS JASP 0.19.2.
This sounds a little weird and the first time you run it, it wil take some time to startup.
Apologies for the inconvenience! I'm working on it as we speak.

**Comment by janderuiter** [comment]
Apparently I do:

Homebrew 4.0.22
Homebrew/homebrew-core (git revision 876af4a754b; last commit 2023-06-14)
Homebrew/homebrew-cask (git revision 5463cd240c; last commit 2023-06-14)

**Comment by boutinb** [comment]
Can you type in a terminal:
```
brew install gmp
```
Then
```
brew install mpfr
```
And start JASP again.
This is of course just a workaround. We will fix this as soon as possible.

**Comment by janderuiter** [comment]
Hi,

Thanks for suggesting a workaround.

However, just in case this is interesting information regarding the
debugging process, it didn't work (see screen shot).

Best, JP

**Comment by tomtomme** [comment]
Thx. But we cannot see the Screenshot. Please drag and drop it via GitHub.com

**Comment by RensDofferhoff** [comment]
@janderuiter It should be resolved in [this Nightly build ](https://static.jasp-stats.org/Nightlies/macOS-arm64/JASP-nightly-stable-410d926e25afc551d362204f8e57971185234544.dmg)

**Comment by janderuiter** [comment]
This last nightly build worked and didn't produce any error messages during
initial testing. Thanks!

**Comment by RensDofferhoff** [comment]
@janderuiter Thanks for your bug report! We didn't notice this since the missing libraries were installed on the test systems. Work is being done to make a test so this doesn't reoccur.

Feel free to reopen if anything pops up still.
