### ISSUE TITLE
[Bug]: bayes factor robustness check for A/B Test

### ISSUE THREAD

**Issue by Diesfeldt** [jasp-stats/jasp-issues#3086]
### JASP Version

0.19.1

### JASP Module

Summary Statistics

### What analysis are you seeing the problem on?

Bayesian A/B Test

### What OS are you seeing the problem on?

Windows 11

### Bug Description

Asking for a Bayes factor robustness check, I get an error 'length=3' in coercion to 'logical(1)'
[GronauABTest.zip](https://github.com/user-attachments/files/18135131/GronauABTest.zip)

### Expected Behaviour

The Bayes factor robustness check would give the expected graphic

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by EJWagenmakers** [comment]
I think we fixed this in 0.29.2. I am closing this issue -- please let me know if the error nevertheless persists in 19.2

**Comment by Diesfeldt** [comment]
Thanks very much. I will keep an eye on JASP 19.2

Best,

Han Diesfeldt


________________________________
Van: EJ ***@***.***>
Verzonden: zaterdag 14 december 2024 10:02
Aan: jasp-stats/jasp-issues ***@***.***>
CC: Han Diesfeldt ***@***.***>; Author ***@***.***>
Onderwerp: Re: [jasp-stats/jasp-issues] [Bug]: bayes factor robustness check for A/B Test (Issue #3086)


I think we fixed this in 0.29.2. I am closing this issue -- please let me know if the error nevertheless persists in 19.2

**Comment by boutinb** [comment]
> Thanks very much. I will keep an eye on JASP 19.2 Best, Han Diesfeldt

Maybe this is not clear, but 0.19.2 is already released: https://jasp-stats.org/

**Comment by Diesfeldt** [comment]
Thanks again. I will download the latest JASP version.

Best,

Han Diesfeldt

________________________________
Van: bruno boutin ***@***.***>
Verzonden: maandag 16 december 2024 12:04
Aan: jasp-stats/jasp-issues ***@***.***>
CC: Han Diesfeldt ***@***.***>; Author ***@***.***>
Onderwerp: Re: [jasp-stats/jasp-issues] [Bug]: bayes factor robustness check for A/B Test (Issue #3086)


Thanks very much. I will keep an eye on JASP 19.2 Best, Han Diesfeldt

Maybe this is not clear, but 0.19.2 is already released: https://jasp-stats.org/
