### ISSUE TITLE
[Bug]: Inability to initiate installation of JASP on Mac - M4 Mac mini

### ISSUE THREAD

**Issue by Cons-Trux** [jasp-stats/jasp-issues#3088]
### JASP Version

0.19.2

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

Inability to install JASP after downloading 

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

![Screenshot 2024-12-15 at 8 26 58 AM](https://github.com/user-attachments/assets/20feeb81-c783-4339-8ecf-db18503d4029)

### Expected Behaviour

JASP should have. been able to  install

### Steps to Reproduce

1.Use a Mac mini with M4 apple silicon
2.Access the JASP download page
3.Download JASP choosing the 'Apple Silicon" option 
4. After it has downloaded, double click on the .dmg file
5. Error message as per the attached  screen shot appears
6. Inability to install JASP
...

### More Debug Information

I was downloading the version that is currently on the JASP web site - as of 15th dec 2024 @ 0900Hrs

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
Thx for the Report. There might be Something wrong. But have you tried redownloading?

**Comment by Cons-Trux** [comment]
Hi! ThereI have tried downloading the software at least 6 times now.I delete previous downloads before installing new download but get the same response. Thank youBest Regards,Eugene MagnusMobile : 97973798On 15 Dec 2024, at 18:49, Thomas Langkamp ***@***.***> wrote:﻿
Thx for the Report. There might be Something wrong. But have you tried redownloading?

**Comment by boutinb** [comment]
How big is your dmg file? Can you also check its SHA256 checksum in a terminal: `shasum -a 256 JASP-0.19.2.0-MacOS-arm64.dmg` 
This sould be: 4b6692c5b7d05d11f993ae5ee15eb7334e1ac80cf0f07483812740d60d17ce92

**Comment by Cons-Trux** [comment]
Hey! Bruno,1. Thank u so much for the follow up. 2. I left the issue with a friend to help resolve and he was able to do it for me. 3. So I now have JASP on my M4 Mac mini. 4. All resolved, I’m not sure what he did though! Thank you again for following up Trying my best to promote JASP!! Well at least at Uni!! Best Regards,Eugene MagnusMobile : 97973798On 16 Dec 2024, at 17:33, bruno boutin ***@***.***> wrote:﻿
How big is your dmg file? Can you also check its SHA256 checksum in a terminal: shasum -a 256 JASP-0.19.2.0-MacOS-arm64.dmg
This sould be: 4b6692c5b7d05d11f993ae5ee15eb7334e1ac80cf0f07483812740d60d17ce92

**Comment by tomtomme** [comment]
Thx for the feedback. If you ever have a chance to ask him what he did, make sure to tell us!
Closing for now :D

**Comment by Cons-Trux** [comment]
Thank you Gents/Ladies,1. Your professionalism is truly commendable. 2. Thank you for being attentive & very professional .  Best Regards,Eugene MagnusMobile : 97973798On 16 Dec 2024, at 18:13, Thomas Langkamp ***@***.***> wrote:﻿
Closed #3088 as completed.
