### ISSUE TITLE
[Bug]: plot editor crash

### ISSUE THREAD

**Issue by matgdpt** [jasp-stats/jasp-issues#3089]
### JASP Version

0.19.2

### JASP Module

Other

### What analysis are you seeing the problem on?

分散分析，T検定

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

グラフのy軸の数値をFormとToの数字を誤って同じ数字を入力してしまったところ，以下のメッセージが出てきました。
プロット編集が予期せず終了しました。poloEditingOptionsで致命的なエラーが発生しました：poloEditingOptionsを計算するとエラーが発生しました:!関数”scales_add_defaults"を見つけることができませんでした
![tempImageCxUuBd](https://github.com/user-attachments/assets/68189963-cf3d-40c3-8655-be3c7ec65953)

### Expected Behaviour

グラフのy軸の数字を入れて，エラーが起きずにy軸の数字を正しく入力でき，グラフに反映されること

### Steps to Reproduce

1.グラフの下にある小さい矢印を押す
2.グラフの編集を押す
3.y軸を押す
4.軸の表示からシーケンスの指定を押す
5.FromとToに同じ数字を入力する

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by matgdpt** [comment]
卒論に使う材料です。卒論を今日中に仕上げないといけないため，早急の対応をよろしくお願いいたします。

**Comment by boutinb** [comment]
@matgdpt Please make your issue in English, our Japanese is quite difficult to understand for us....

**Comment by tomtomme** [comment]
closing as duplicate of https://github.com/jasp-stats/jasp-issues/issues/3092
