### ISSUE TITLE
[Feature Request]: Pls add test for paired proportions, McNemar's test

### ISSUE THREAD

**Issue by christinetong** [jasp-stats/jasp-issues#3100]
### Description

Add McNemar's test

### Purpose

To test for differences between proportions computed from related (paired) groups

### Use-case

E.g., proportion of patients with a specific symptom before and after a treatment

### Is your feature request related to a problem?

No

### Is your feature request related to a JASP module?

Unrelated

### Describe the solution you would like

Add McNemar's test

**Comment by tomtomme** [comment]
thx for the certainly valid request. 
We are aware this glaring gap, see https://github.com/jasp-stats/jasp-issues/issues/1445
So I will close this as a duplicate. Lets hope for it to surface soonTM

**Comment by tomtomme** [comment]
@christinetong 

McNemar is now available in the beta version of the frequencies module, available in the module library.

Cochrans test also known as Cochrans Q is tracked here https://github.com/jasp-stats/jasp-issues/issues/1445
