### ISSUE TITLE
JASP Friedman Conover test doesn't match R (posthoc.friedman.conover.test)

### ISSUE THREAD

**Issue by rachael-reavis** [jasp-stats/jasp-issues#314]
* JASP version: 0.9.1
* OS name and version: Mac Sierra 10.12.6
* Analysis: Connover's post hoc test (for Friedman)
* Bug description: I'm not sure if it's a bug or just something I'm doing wrong, but when I run friedman.test in R I get the same result. However, I get different t-stats & p-values for the Connover's follow-up using posthoc.friedman.conover.test -- I tried finding the underlying R code that JASP is using, but I couldn't figure out where it was.

* Add JASP files as a zip:
* Screenshot: ![screen shot 2019-02-25 at 10 41 58 am](https://user-images.githubusercontent.com/10504204/53349049-3f7a6780-38ea-11e9-8524-20ccb71fa787.png)
![screen shot 2019-02-25 at 10 43 18 am](https://user-images.githubusercontent.com/10504204/53349050-4012fe00-38ea-11e9-9828-2ba50bf25b23.png)
* Expected behaviour:
* Steps to reproduce:

**Comment by JohnnyDoorn** [comment]
Hi Rachael,
Could you please provide a .jasp or csv file? If you prefer, you can send it to me at j.b.vandoorn(at)uva.nl
Kind regards,
Johnny

**Comment by JohnnyDoorn** [comment]
Got it, thanks Rachael - I will look into this!

**Comment by JohnnyDoorn** [comment]
Hi Rachael,

Wanted to let you know that this is now fixed in the next JASP release. The issue was a package upgrade that we were not aware of. We used part of the PMCMRplus package, which is the sequal to the PMCMR package. It seems that the Conover test differs in results between these two packages, and I believe the output from PMCMRplus is the correct one. JASP now gives the same results as that one again. 
Please let me know / reopen this issue if you have any additional questions/comments!

Kind regards
Johnny

**Comment by rachael-reavis** [comment]
Thanks!

**Comment by ksp200425** [comment]
Hi, I have a question on this. Has there been any issues with this update and PMCMRplus? I haven't been able to get the same results for the Conover test between R (with PMCMRplus) and JASP.

**Comment by JohnnyDoorn** [comment]
Hi @ksp200425,

Do you have a numeric example? When I conduct a Conover test in JASP and PMCMRplus I get the same results, for instance for the [Bush Tucker Food example from the data library](https://jasp-stats.github.io/jasp-data-library/myChapters/chapter_3.html#bush-tucker-food):
<img width="744" alt="image" src="https://github.com/jasp-stats/jasp-issues/assets/15704203/be1ff89a-9209-4f75-bb90-6eabc8f20f06">
JASP file (change extension to .jasp): 
[BushTuckerFoodConover.zip](https://github.com/jasp-stats/jasp-issues/files/15390876/BushTuckerFoodConover.zip)

Running it in R:
```
dat <- read.csv("Bush Tucker Food.csv")
# convert to long:
y <- unlist(dat[, 2:5])
gr <- rep(letters[1:4], each = 8)
id <- rep(1:8, 4)
PMCMRplus::frdAllPairsConoverTest(y, gr, id, p.adjust.method = "holm")

	Pairwise comparisons using Conover's all-pairs test for a two-way balanced complete block design

data: y, groups and blocks

  a      b      c     
b 0.0054 -      -     
c 0.0082 0.7991 -     
d 0.2565 0.2071 0.2565

P value adjustment method: holm
```

Kind regards
Johnny

**Comment by ksp200425** [comment]
Ok I see, I did get it right in R, but for some reason got something different in JASP. I'm sorry if there is something I'm missing!
![image](https://github.com/jasp-stats/jasp-issues/assets/170429343/a2e16a5f-235e-4ba9-91c8-f7f3e4fa27fb)
.

**Comment by JohnnyDoorn** [comment]
My apologies, I was using the development version of JASP (available [here](https://static.jasp-stats.org/Nightlies/)), which already included a fix to bring the JASP results up to date with PMCMRplus, which also had a bug fix in their latest release. The new version will officially release somewhere in the coming weeks though!

**Comment by ksp200425** [comment]
Oh, Thank you so much! I will try it again with the development version.
