### ISSUE TITLE
Add scroll bar to Compute Column feature

### ISSUE THREAD

**Issue by hanneoberman** [jasp-stats/jasp-issues#316]
* Enhancement: scroll bar next to variables to select for computing new columns. 
* Purpose: give visual feedback for scrolling through the variables in the data.
* Use-case: the undergrads I teach had trouble recognizing where to select existing variables to create a new var.

**Is your feature request related to a problem? Please describe.**
Not a problem, just usability.

**Describe the solution you'd like**
Add a scroll bar to the Compute Column feature: when using the option to select (pointing finger, not R) to create a new variable, the existing variables are presented at the top left of the screen. I'd like it of this list of variables was easier recognizable as a scrollable list. A scroll bar next to the list would give users visual feedback to scroll through the available variables.

**Describe alternatives you've considered**
Not applicable.

**Additional context**
With list I mean the 'Moon', 'Other' and 'diff' variables.

![jasp](https://user-images.githubusercontent.com/38891540/53633225-2984e380-3c17-11e9-8540-b9efde289f14.PNG)

**Comment by JorisGoosen** [comment]
I've added some scrollbars

**Comment by hanneoberman** [comment]
Nice! Thanks :)

**Comment by JorisGoosen** [comment]
You're welcome and it does look better ^^
