### ISSUE TITLE
Using JASP in Mojave, will not generate any plots

### ISSUE THREAD

**Issue by paulamarentette** [jasp-stats/jasp-issues#317]
* JASP version: 0.9.2
* OS name and version: Mojave 10.14.3
* Analysis: intro stats class, trying to produce an independent t, with plot
* Bug description: 

Error in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : extrémités de polygone non trouvés

Stack trace
lapply(vps, push.vp, recording)

FUN(X[[i]], ...)

push.vp.vpTree(X[[i]], ...)

push.vp(vp$parent, recording)

push.vp.viewport(vp$parent, recording)

grid.Call.graphics(C_setviewport, vp, TRUE)

(function (x) 
{
    widthDetails(x)
})(list(label = 'hearing', x = 0, y = 0.5, just = 'centre', hjust = 0.5, vjust = 1, rot = 90, check.overlap = FALSE, name = 'GRID.text.90', gp = list(fontsize = 20.4, col = 'black', fontfamily = '', lineheight = 0.9, font = 1), vp = NULL))

widthDetails(x)

widthDetails.text(x)

grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, resolveHJust(x$just, x$hjust), resolveVJust(x$just, x$vjust), x$rot, 0)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

* Add JASP files as a zip: added
* Screenshot: added in zip file
* Expected behaviour: I expected a plot
* Steps to reproduce: 
1. Go to '...' .open csv file, generate independent t, use hearing as DV, meal as grouping
2. Click on '....' descriptive plot
[for github.zip](https://github.com/jasp-stats/jasp-issues/files/2927254/for.github.zip)

**Comment by TimKDJ** [comment]
I cannot open your attachment as it appears to be an alias of a folder in your local environment (it points to "/Applications/for github").
Could you zip the actual folder and attach that?

**Comment by paulamarentette** [comment]
[for github.zip](https://github.com/jasp-stats/jasp-issues/files/2942058/for.github.zip)

**Comment by paulamarentette** [comment]
sorry for the mix-up, this is the actual folder...
I can't make any kind of plot right now, not just the one above.
 I'm using JASP in my stats class, and this is not helping me teach effectively! Thanks for your help troubleshooting my problem.
Paula

**Comment by TimKDJ** [comment]
Your dataset works fine for me.
I can run an independent samples t-test and obtain a descriptives plot.

The error you report seems to be linked to the fonts you have installed on your machine.
You could check if Arial is available in your Font Book and see if there are any duplicates (edit>Look for Enabled Duplicates). I'm simply going on suggestions posted [here](https://stackoverflow.com/questions/10581440/error-in-grid-calll-textbounds-as-graphicsannotxlabel-xx-xy-polygon), though.

Have you encountered this issue before @vandenman?

**Comment by AlexanderLyNL** [comment]
We've seen a similar issue before and it was solved by Akash:

https://github.com/jasp-stats/jasp-desktop/issues/2496#issuecomment-398072694

**Comment by paulamarentette** [comment]
Yes indeed, that fixed it. Thanks for the help.
