### ISSUE TITLE
Forecasting - ARIMA

### ISSUE THREAD

**Issue by tjfountain** [jasp-stats/jasp-issues#318]
Is forecasting available in JASP? Specifically ARIMA? Thanks!

**Comment by EJWagenmakers** [comment]
Great suggestion, I would love to see the time series stuff added. We haven't done this yet though.
E.J.

**Comment by tjfountain** [comment]
E.J.,

Thanks for the quick response. I wish I could help, but I'm hopeless when
it comes to coding.
I'll just have to hope someone smarter than me takes an interest in ARIMA
and ITS and builds it.

Warm regards,


*T. Joseph Fountain, MS*
Psychology
307.855.2173
MAKE YOUR WAY HERE

*The sole purpose of human existence is to kindle a light in the darkness
of mere being.*

- Carl Jung (1961)

**Comment by juliuspfadt** [comment]
@boutinb, I see that there is a repo named time series, but do we have anyone working on this?

**Comment by EJWagenmakers** [comment]
Yes, it is @sophieberkhout

**Comment by tomtomme** [comment]
ARIMA is done in the Time Series Module.
@tjfountain - can you check if this covers your needs and close this issue, if so?
