### ISSUE TITLE
Problems with including more than 1 categorical variable as covariates in two-way mixed ANCOVA

### ISSUE THREAD

**Issue by tommyng730** [jasp-stats/jasp-issues#319]
* JASP version: 0.9.2
* OS name and version: Mojave 10.14.2
* Analysis: Two-way mixed ANCOVA
* Bug description:

This analysis terminated unexpectedly.

Error in X[ii, ii, drop = FALSE] %*% y[ii]: non-conformable arguments

Stack trace
analysis(dataset = dataset, options = options, perform = perform, callback = the.callback, state = oldState)

.resultsPostHoc(referenceGrid, options, dataset, fullModel)

summary(pairs(referenceGrid[[var]], adjust = 'tukey'))

summary.emmGrid(pairs(referenceGrid[[var]], adjust = 'tukey'))

.est.se.df(object)

t(apply(object@linfct[use.elts, , drop = FALSE], 1, function(x) {
    if (!any(is.na(x)) && estimability::is.estble(x, object@nbasis, tol)) {
        x = x[active]
        est = sum(bhat * x)
        if (do.se) {
            se = sqrt(.qf.non0(object@V, x))
            df = object@dffun(x, object@dfargs)
        }
        else se = df = 0
        c(est, se, df)
    }
    else c(NA, NA, NA)
}))

apply(object@linfct[use.elts, , drop = FALSE], 1, function(x) {
    if (!any(is.na(x)) && estimability::is.estble(x, object@nbasis, tol)) {
        x = x[active]
        est = sum(bhat * x)
        if (do.se) {
            se = sqrt(.qf.non0(object@V, x))
            df = object@dffun(x, object@dfargs)
        }
        else se = df = 0
        c(est, se, df)
    }
    else c(NA, NA, NA)
})

FUN(newX[, i], ...)

.qf.non0(object@V, x)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

I notice that the error happened only when I included more than 3 covariates. Thank you for your help!

**Comment by TimKDJ** [comment]
It shouldn't be possible to add categorical predictors as covariates in an ANCOVA...
Could you send me your .jasp file so I can see where it goes wrong exactly?

You can attach the jasp file here as a .zip or send it to me at t.dejong@jasp-stats.org

**Comment by JorisGoosen** [comment]
Too long without a response.
