### ISSUE TITLE
GUI enhancement: Rescalable windows, stationary variable lists

### ISSUE THREAD

**Issue by Anna-LenaSchubert** [jasp-stats/jasp-issues#32]
When running analyses with a lot of variables (possibly with very long variable names), it would be very useful if the windows within the analysis specifications were rescalable (i.e., get larger if you rescale the size of the global analysis window).

Moreover, when you drag variables into the analysis window, the list of variables always resets to the first variable. This is very exhausting when you want to add 10+ variables to an analysis and have to assign them correctly (e.g., repeated measures-ANOVA). It would be great if the list stayed (optionally?) at the point of the last variable you selected.

**Comment by FransMeerhoff** [comment]
Hi @Anna-LenaSchubert 

FYI
Of course we added a lot of new features in previous versions but the next coming release 0.9.3 will have a complete panel redesign and a lot of more functionality like computed columns, filtering and the possibility to add modules dynamically. We expect to release the next version in about a month or so.

Kind regards
Frans Meerhoff
