### ISSUE TITLE
missing api-ms-win-crt-runtime-l1-1-0.dll windows 8.1

### ISSUE THREAD

**Issue by Nega100** [jasp-stats/jasp-issues#321]
* JASP version: JASP 0.9.2
* OS name and version: Windows 8.1
* Bug description: missing api-ms-win-crt-runtime-l1-1-0.dll

Hi all
I encountered error when install JASP 0.9 in Win 8 64 bit. However this error never happen in JASP 0.8
The error is api-ms-win-crt-runtime-l1-1-0.dll missing error in pop up box window.
I tried to install Microsoft Visual C++ and find proper instalation file for Win 8. I also try to copy/paste in sytem32 and sysWOW64 but the error still exist. For the last hope I try to reinstall the system but nothing positive happen.
Thanks for the help

**Comment by FransMeerhoff** [comment]
Hi @Nega100 ,

Can you try to install the Visual Studio 2017 Runtime manually? You can find this at https://support.microsoft.com/nl-nl/help/2977003/the-latest-supported-visual-c-downloads
You must choose there (of course) the x64 version.

Kind Regards
Frans Meerhoff

**Comment by Nega100** [comment]
Hi FransMeerhoff,
I'm really really sorry, accidentally I click tab close in GitHub. I did
what you suggest. At the first time the download seems error and stuck. I
tried for several times and there are no progress. Meanwhile I install
packages in Python 3.7 and there are some packages that required Visual
Studio. After Visual Studio get installed, I try to install Microsoft
Visual C++ and success within minute. JASP is run with no problem.Love
it!!..Many thanks and sorry for the accident.
