### ISSUE TITLE
Larger font for outliers using box plots 

### ISSUE THREAD

**Issue by kevinvschie** [jasp-stats/jasp-issues#322]
* Enhancement: present outliers in larger font.
* Purpose: better readability 
* Use-case:

**Is your feature request related to a problem? Please describe.**
No specific problem, but when performing data inspection using box plots, the font of outliers is extremely small. Stretching out the image, makes the box plot larger, but resizes the outlier font type back to the small font.

**Describe the solution you'd like**
That the font size increases when images are stretched out to facilitate data inspection.

**Describe alternatives you've considered**

**Additional context**

**Comment by tomtomme** [comment]
@kevinvschie 
Since you can zoom the output with Strg+mouswheel and you can resize plots while retaining font sizes, this should be no issue.
Am I correct?
If so, feel free to close this issue.
