### ISSUE TITLE
Dealing with missing values

### ISSUE THREAD

**Issue by PeterKlaren** [jasp-stats/jasp-issues#324]
* JASP version: 0.9.2
* OS name and version: Windows 10
* Analysis: Descriptives, Box plot
* Bug description: JASP can't deal with missing values
* Add JASP files as a zip:
* Screenshot: 
![image](https://user-images.githubusercontent.com/43278770/54016353-e250a280-4182-11e9-9be8-eb74467985fe.png)

* Expected behaviour: R's "na.rm" should work by default.
* Steps to reproduce: 
1. Go to 'Decriptives'
2. Select variable (here: 'alkphos') and split by 'lab'
This analysis terminated unexpectedly.

Error in quantile.default(v, probs = c(0.25, 0.75)): missing values and NaN's not allowed if 'na.rm' is FALSE

Stack trace
analysis(jaspResults = jaspResults, dataset = dataset, options = options, state = oldState)
.descriptivesSplitPlot(dataset = dataset, options = options, variable = var)
quantile(v, probs = c(0.25, 0.75))
quantile.default(v, probs = c(0.25, 0.75))
stop('missing values and NaN's not allowed if 'na.rm' is FALSE')
To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

BTW: https://jasp-stats.org/bug-reports is a dead-end url.

Cheers,

Peter

**Comment by TimKDJ** [comment]
Thanks for reporting the issue (and notifying us about the url!)
I fixed the problem and the fix will be available in the next JASP version.
For the time being, you'd have to remove the missing values from your grouping variable.
