### ISSUE TITLE
JASP crashes on launch

### ISSUE THREAD

**Issue by michal1981** [jasp-stats/jasp-issues#325]
Hello,

I installed JASP 0.9.2.0 on Windows 7 Professional v. 6.1.7601 service pack 1 compilation 7601.

It crashes immediately upon launching ("JASP,exe has stopped working,")

Details of the error are as follows (sorry, the labels are in Polish, but I'm sure you know what they refer to):

Nazwa zdarzenia problemu:	APPCRASH
  Nazwa aplikacji:	JASP.exe
  Wersja aplikacji:	0.0.0.0
  Sygnatura czasowa aplikacji:	5c093852
  Nazwa modułu z błędem:	ntdll.dll
  Wersja modułu z błędem:	6.1.7601.24308
  Sygnatura czasowa modułu z błędem:	5be8601e
  Kod wyjątku:	c0000005
  Przesunięcie wyjątku:	000000000002a365
  Wersja systemu operacyjnego:	6.1.7601.2.1.0.256.48
  Identyfikator ustawień regionalnych:	1045
  Dodatkowe informacje 1:	1b95
  Dodatkowe informacje 2:	1b9515686fcee41ba08706a4fd8649bf
  Dodatkowe informacje 3:	c14a
  Dodatkowe informacje 4:	c14aeeb7bcf66bccfcc23025ec7ad7b2

Would be grateful for any tips. Tried uninstalling and installing again, but the same happens.

Best,

Michal

**Comment by FransMeerhoff** [comment]
Hi @michal1981 

Do you have more information about the status of this issue?

I could not find out from the information above, if you use a 64-bit or 32 bit version.
But I assume that you choose the right setup regarding this. Can you confirm that to us?

If you have still problems could you try the following:

1)
Can you try to install the Visual Studio 2017 Runtime manually? You can find this at https://support.microsoft.com/nl-nl/help/2977003/the-latest-supported-visual-c-downloads
I assume that you have  a 64 bits, though I cannot  machine so choose there the x64 version.
Check if JASP will start now.

If JASP still will not run
2)
Form a terminal or Command prompt navigate to
$>  cd "c:\Program Files\JASP"
run there
$>  JASP.exe > %TEMP%\JASPlog.txt
Could you send us the JASPlog.txt file?
$> dir %TEMP%\JASPlog.txt 
will show you where the logfile resides

If you have problems using the command prompt please let us know.

Kind regards
Frans Meerhoff

**Comment by Erlix322** [comment]
Let's reopen this one. same problem and also nothing is written to the log file

**Comment by JorisGoosen** [comment]
@Erlix322 are you using the same OS and version of JASP?
Do you get the exact same errormessage?

**Comment by JorisGoosen** [comment]
Sorry if you mean all of that with "same problem" but it really helps to have information explicit in these kinds of scenarios.

**Comment by AlexanderLyNL** [comment]
@Erlix322 could you please open a new issue. The issue template specifies certain information that we need to get a better understanding of your problem. 

https://github.com/jasp-stats/jasp-issues/issues/new?assignees=&labels=&template=bug_report.md&title=

Thanks,
Alexander
