### ISSUE TITLE
Error in Descriptives Plot (Paired Samples T-Test)

### ISSUE THREAD

**Issue by Brett-Milliner** [jasp-stats/jasp-issues#331]
While running a T-Test I met the following bug:

Error in descriptivesPlots[[1]]:  添え字が許される範囲外です 
Stack trace
analysis(dataset = dataset, options = options, perform = perform, callback = the.callback, state = oldState)

I'm using Mojave Ver. 10.14.3 (18D109)

* JASP version:
* OS name and version:
* Analysis:
* Bug description:
* Add JASP files as a zip:
* Screenshot: 
* Expected behaviour:
* Steps to reproduce:

**Comment by TimKDJ** [comment]
Could you save the .jasp file that contains this error and attach it here as a .zip or email it to me at t.dejong@jasp-stats.org
