### ISSUE TITLE
Some feedback after a year of teaching JASP to students (in France)

### ISSUE THREAD

**Issue by mservantufc** [jasp-stats/jasp-issues#334]
Hi guys,
A BIG thanks from my (french) students that enjoyed JASP and are now able to do statistics without having to get a crack to run SPSS or Statistica. Plus they really enjoyed JASP's interface. Some feedback (after a year of teaching -I've already discussed some issues on the forum, below is a summary) : 
1-In within-subjects designs, contrasts are computed using the pooled error term (which is generally not recommended e.g., Maxwell & Delaney). More problematic, there's no way to change this (which is strange, because you can decide whether to use the pooled error term for post-hoc tests or analyses of simple main effects).
2-Personally, I've never found Helmert, simple, deviation, repeated and difference contrasts very useful (besides, I never remember which one does what, and have to look them up each time I want them). I think it'd be more useful to have a menu in which one could enter custom coefficients (both for between- and within-subjects designs, and even mixed designs). I've heard many colleagues arguing "I don't want to use JASP because you cannot specify contrast coefficients".
3-Currently, one can only compute main-effect contrasts. It would be great to be able to compute simple main-effect contrasts, and interaction contrasts.
4-I don't understand the logic of computing post-hoc pairwise comparisons independently for each factor (when you have a design with at least 2 factors). Shouldn't all possible combinations given the design be considered ? That would of course considerably reduce the power of the comparisons, but this is the price to pay for post-hoc tests. 
 5- When creating a variable, it would be great (from the menu) to be able to do simple arithmetics with variables (say I'd like to define variableD = 2*variableA-variableB - variableC ; I can compute + or -, but not 2*something).  
Cheers,
Mat

**Comment by akashrajkn** [comment]
@mservantufc For 5, on the latest version of jasp (`v0.9.2`), it is possible to compute such a variable
```
D = variableA * 2 + variableB - variableC
```

**Comment by JohnnyDoorn** [comment]
Hi Mat,

That's great to hear, and thanks for the feedback!
(1-3) Specifying custom contrasts is at the top of our to do list, as this seems a much desired feature. When I get to work on the contrast analyses, I will look into pooled/non-pooled error terms and possible interaction contrasts. For now you can look into the simple main effects analysis and the next point:
(4)  The next version of JASP (0.9.3), will have posthoc tests for interactions (both within and between factors). 

Kind regards
Johnny

**Comment by mservantufc** [comment]
@JohnnyDoorn   I forgot another thing. When computing simple main effects in a within-subjects design, it would be great to have the Sum of Squares, df, and Mean Square associated to the Residual. I see that you don't use the pooled error term to compute these main effects (here again, would be good to have the option).
Cheers

**Comment by tomtomme** [comment]
@mservantufc 
Since custom contrasts are available now, can you check if there is still something left from your list to implement? If not, feel free to close this issue. Thx.
