### ISSUE TITLE
Principle Axis Factoring 

### ISSUE THREAD

**Issue by alexgeavis** [jasp-stats/jasp-issues#335]
Recently had paper rejected on basis that PCA was used instead of PA2 in a factor analysis. Are there plans for PA2 to be integrated?

**Comment by TimKDJ** [comment]
@AlexanderLyNL ?

**Comment by AlexanderLyNL** [comment]
Yes, it will be included in the EFA overhaul.

**Comment by vankesteren** [comment]
This option will indeed be implemented in the next version of EFA, however I don't believe there will be a large difference (if at all) with the default method of estimation in EFA (MinRes). This is what the psych package documentation has to say about PFA and MinRes:

> Principal axes may be used in cases when maximum likelihood solutions fail to converge, although fm="minres" will also do that and tends to produce better (smaller RMSEA) solutions.
