### ISSUE TITLE
Feature request: upload .omv files

### ISSUE THREAD

**Issue by tressoldi** [jasp-stats/jasp-issues#336]
It could be useful to use .omv files generated by Jamovi.

**Comment by TimKDJ** [comment]
We definitely have plans to expand JASP's ability to read other data formats.
Once we tackle this we'll see if this specific format is feasible or not.

**Comment by tomtomme** [comment]
@tressoldi
Feel free to close this issue import and export of more formats is discussed in
https://github.com/jasp-stats/jasp-issues/issues/611
