### ISSUE TITLE
Logistic regression plot

### ISSUE THREAD

**Issue by kairuggeri** [jasp-stats/jasp-issues#337]
I think the image explains everything, but simply put: the plot for logistic regression is not working now. I've used it many times in the past, but today it is failing. I also see this when I restart and/or attempt to run with other datasets.

![image](https://user-images.githubusercontent.com/9501949/55646890-4f6b4e00-57aa-11e9-997f-5bc6c004e003.png)

**Comment by TimKDJ** [comment]
Thanks for reaching out to us and apologies for our delayed response!

In 0.9.2 there is a package missing from our setup which breaks some plots in Descriptives and apparently also here, in logistic regression.
This is fixed in 0.9.3 which is due in a few weeks.

**Comment by kairuggeri** [comment]
Wonderful, thank you!

**Comment by kairuggeri** [comment]
Hi Tim,

 

Love the newest JASP!!! Cannot wait to incorporate the ML module into my class (probably next summer; doubt I can prep in time for current semester). Just had two very quick questions:

 

1.      Is there any way to save a full set of analyses directly into PDF? I try to run sets in class and add in notes, then save and upload for students to review later. The only issue with saving as a JASP file (the only way I can see now) is that it limits how they can make use of it. If not yet, is that something possible in the future?

2.      For the ML module, is there a recommended sister document that covers all functions/features? I can see the blog and I can find the R package files, but was trying to find something that I can provide for students to complement what I can cover in class.

 

Thanks so much for all you do!!!


Best wishes,

Kai

 

 

--

Dr Kai Ruggeri

 <https://www.mailman.columbia.edu/people/our-faculty/dr2946> Assistant Professor

Health Policy & Management

Mailman School of Public Health

Columbia University

**Comment by TimKDJ** [comment]
1. At the moment you can export the results as html (top left hamburger menu -> Export Results) or you can copy them to a word editor (in the results panel scroll to the top "Results" element and click on the little arrow -> Copy -> in e.g., Microsoft Word paste it). 
2. The blog post is the main source of information. We also provide a description of all inputs in the help file of each analysis (you click on the blue "i" icon in the input panel of an analysis). Not sure if there's anything else in the pipeline: @koenderks, @AlexanderLyNL?

For future reference, it'd be very helpful if you could open a separate issue with a fitting title, so people can search for issues and see if something related has already been posted.

**Comment by koenderks** [comment]
For now, the blog posts (there are two more to come) and the help files will have to do. We took the features from the book "James, G., Witten, D., Hastie, T., & Tibshirani, R. (2013). An Introduction to Statistical Learning. Springer Texts in Statistics." that you may use as a reference. However, we might think about creating a more JASP-like manual or paper that explains how to use the function in the machine learning module, in order to increase the teaching value of the module.

**Comment by AlexanderLyNL** [comment]
Could you also please tell us the questions your class encounters regarding this module? This will help us identify complications that we then further expand on in blog posts, or other tutorial style papers we write.

**Comment by kairuggeri** [comment]
Hello,

 

I’m happy to do so but we aren’t likely to make it for this semester. Will certainly keep you posted if I am able to get it in before the end, though. 

 

Kai

**Comment by kairuggeri** [comment]
Thanks so much for this information. I will keep an eye out for those blogs and recommend to the motivated students that want to go further to look into that book. Really looking forward to anything you guys produce!

**Comment by kairuggeri** [comment]
Thanks very much for this.

 

1.      Yes, this is a great function. The only thing it lacks is that students cannot see exactly how the data were entered. This is really great, though.

2.      Perfect, thanks very much for all this input.

 

Noted about the new submission. Was trying to save you the hassle but I understand what you mean.
