### ISSUE TITLE
Model names in SEM

### ISSUE THREAD

**Issue by MaksimRudnev** [jasp-stats/jasp-issues#339]
* JASP version: 0.9.2
* OS name and version: MacOS Mojave
* Analysis: SEM
* Bug description:
When adding new models under "Advanced -> Model name" the only updated field is "Chi-square test statistic" whereas  various "Additional fit measures" are updated to the last model only, and fit of previous model is not printed, so the comparison of model fit is impossible. For example, I wanted to compare CFI of Model 1 and Model 2, and it wasn't possible.

**Comment by vankesteren** [comment]
Hi Maksim, nice to see you on here as well ;)

Multiple models in SEM have been a very experimental (and kind of buggy) feature for a while now, and will get an overhaul as soon as the new JASP interface we are currently working on has stabilised. You can probably expect an overhaul of this system by version 9.5 or 9.6. 

As a workaround for your specific problem, I would suggest to just make two separate analyses and compare across these two.

Thanks for submitting this issue!

**Comment by MaksimRudnev** [comment]
Oh hi, I didn't realize you are a JASP contributor as well.

Looking forward to version 9.5/6.

**Comment by JorisGoosen** [comment]
Is this in 0.10.?.0?

**Comment by vankesteren** [comment]
no!

**Comment by MaksimRudnev** [comment]
I have checked "Additional fit measures" in v.0.10. The tables with CFi, RMSEA etc. update in line with _the last_ model rather than than all the models. Chi-square and information criteria are shown for several models.

![image](https://user-images.githubusercontent.com/29795088/60720618-3e55e880-9f23-11e9-8f15-f7ec4f098d57.png)

![image](https://user-images.githubusercontent.com/29795088/60720608-3302bd00-9f23-11e9-9ca5-3b8ce2e815e0.png)

**Comment by LSLindeloo** [comment]
@juliuspfadt It is already possible to show additional fit measures for each of the specified models atm. So if I didn't misinterpret the request, this issue can be closed :-)

**Comment by juliuspfadt** [comment]
Perfect!
