### ISSUE TITLE
post-hocs for ANOVA

### ISSUE THREAD

**Issue by ebenau** [jasp-stats/jasp-issues#341]
I know others have requested (dating back to as recently as Aug. 6, 2018) that there be post-hocs for anova/RM Anova in the program...I was wondering how far out you think that feature will be? Once that's in place, there'd be little to no reason for me (and most of the psychophysiology world) to use SPSS ever again. Thanks!

**Comment by EJWagenmakers** [comment]
@JohnnyDoorn ?

**Comment by JohnnyDoorn** [comment]
Hi Ebenau,

Do you mean post-hoc tests for interactions? These will be in the next JASP release (0.9.3), which will be released in a couple of weeks. 
Univariate post-hoc tests are already in JASP though.

Kind regards,
Johnny

**Comment by ebenau** [comment]
Hi Johnny,

Yes, that’s exactly what I mean. I’m very excited to hear it will be in a couple of weeks.

I’m really, really liking JASP…serious kudos to you guys. If you can do CFA I can also get rid of Stata.

Erik

**Comment by JohnnyDoorn** [comment]
Hi Erik,

That's great to hear, thanks! As for CFA, @vankesteren has recently revamped the SEM module, and I think this also includes CFA now - maybe he can shed some more light on this. As far as I can tell this will also be in the new version of JASP!

Cheers,
Johnny

**Comment by EJWagenmakers** [comment]
Yes, CFA is in the upcoming version as far as I know, and it looks *awesome*
E.J.
********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room G 0.29
University of Amsterdam, Nieuwe Achtergracht 129B
Letter: PO Box 15906, 1001 NK Amsterdam
Parcel: Valckenierstraat 59,  1018 XE Amsterdam

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Blog: bayesianspectacles.org
Email: EJ.Wagenmakers@gmail.com
Cell: (+31) 6 45626624

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************
