### ISSUE TITLE
Jitter element causes crash!

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-issues#343]
...while demonstrating JASP :-((
![image](https://user-images.githubusercontent.com/8603015/55973735-7af8a780-5c86-11e9-821d-ae85ffd47b0f.png)

**Comment by PeterKlaren** [comment]
Hi EJ,

My students in my Stats101 class had exactly the same problem. Issue solved by copying R's withr package from my R installation to JASP's R package directory.

Peter Klaren

**Comment by EJWagenmakers** [comment]
Yes, this has now been fixed in the upcoming version. The culprit was a missing value (without missing values, the split functionality does work)
EJ

**Comment by AlexanderLyNL** [comment]
I'll close this, as it's fixed in 0.9.3 which should be out soon. Please reopen if it reoccurs.
