### ISSUE TITLE
Expected counts in multinomial test don't transfer

### ISSUE THREAD

**Issue by PeterKlaren** [jasp-stats/jasp-issues#345]
* JASP version: 0.9.2.0
* OS name and version: different OSs, Windows and Mac
* Analysis: Frequencies > Multinomial test, and Frequencies > Chi squared test
* Bug description: Expected counts are already in a dataframe, but do not transfer well to the output of a multinomial test. Compare the column "expected" in the dataframe, and the column "Expected: expected" in the Results of the multinomial test.
* Add JASP files as a zip:
* Screenshot: 
![afbeelding](https://user-images.githubusercontent.com/43278770/56063930-f3d42e00-5d70-11e9-9d03-8e0ac7cd888c.png)

* Expected behaviour:
* Steps to reproduce:

**Comment by vankesteren** [comment]
Hi Peter,

this is probably because the expected counts are normalized: the expectation needs to have the same sum as the observations for the multinomial test.

**Comment by PeterKlaren** [comment]
Owww... This is embarassing... The problem was noted by two students in my Stats101 class and I did not check whether there calculated expected values were OK... Should have!
Recalculated the data now and everything works fine. Apologies! (Better remove my post...)

Peter

**Comment by AlexanderLyNL** [comment]
Thanks for the feedback. It appears that nothing everything is clear, and we'll try to improve this.

@MyrtheV Could you please clarify this, when writing the documentation? 

 I'll close this for now.
