### ISSUE TITLE
Reconsider 1st rule on assigning variable types

### ISSUE THREAD

**Issue by PeterKlaren** [jasp-stats/jasp-issues#346]
* Enhancement: Small dataframes with variables' values that are integer are imported as 'scale'.
* Purpose: Smooth operation of small datasets, no errors in descriptive statistics
* Use-case:

**Is your feature request related to a problem? Please describe.**
Datasets smaller than 25 rows containing integer values (e.g., IQ values) are assigned a nominal variable type. This interferes with proper display of correlation and density plots in Descriptives. See the screeenshots.

**Describe the solution you'd like**

Drop your first rule of assigning variables (see https://jasp-stats.org/getting-started/). Or change it so that integers with for instance >5 different values ("levels") are imported as nominal. Or reverse the rule so that integers are imported as a "scale" variable, to be changed to "nominal" manually.

**Describe alternatives you've considered**

**Additional context**
![afbeelding](https://user-images.githubusercontent.com/43278770/56065646-be7e0f00-5d75-11e9-9c63-52b2aaaebf63.png)

![afbeelding](https://user-images.githubusercontent.com/43278770/56065679-dc4b7400-5d75-11e9-8496-81c622e2a4a8.png)

**Comment by EJWagenmakers** [comment]
I think this makes sense

**Comment by AlexanderLyNL** [comment]
https://github.com/jasp-stats/jasp-desktop/pull/3158

In the next version (0.9.3) the user can change the cut off in the preference menu. We have not change the cut off to 25 by default though, but @fransmeerhoff can do that easily.

**Comment by FransMeerhoff** [comment]
Hi @PeterKlaren @EJWagenmakers @AlexanderLyNL 

Indeed we've added the possibility to define your own threshold for this in the preference menu in the new release. However the default value has been set to 10. An argument for this choice might be that a lot of questionnaires use scales from 1-10.
So if everybody is happy the possibility to change  the cut off and a default of 10, we can leave is this way.
