### ISSUE TITLE
Request: more helpful error message in correlation plot

### ISSUE THREAD

**Issue by djdekker** [jasp-stats/jasp-issues#347]
* Enhancement: more helpful error message
* Purpose: make user understand what (s)he's doing wrong and how to correct this
* Use-case: user requests statistics without selecting correlation coefficient

How to reproduce current behavior:
In **Regression** > **Correlation Matrix** check the checkboxes **Correlation matrix** and **Statistics** and make sure that no checkbox under **Correlation Coefficients** is checked. Now an R error message appears:

> This analysis terminated unexpectedly.
> Error: Column 'y' must be a 1d atomic vector or a list

Instead, I'd like to see an error message like this:

> Statistics cannot be shown when no correlation coefficients are selected. Please check one or more Correlation Coefficients checkboxes.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Kucharssim** [comment]
Dear @djdekker ,

thank you for reporting this error. I can reproduce it using version 0.9.2, but it appears to be fixed in the upcoming version. Please, feel free to reopen this issue if it occurs in the future.

Best,
Simon
