### ISSUE TITLE
JASP 0.9.2.0 crashes on Windows 10 64bit

### ISSUE THREAD

**Issue by coreysparks** [jasp-stats/jasp-issues#349]
* JASP version: 0.9.2.0
* OS name and version: Windows 10 64 bit
* Analysis:
* Bug description: JASP crashed on startup
* Add JASP files as a zip:
* Screenshot: attached
![Capture](https://user-images.githubusercontent.com/5359657/56589553-181ede80-65ab-11e9-80c9-74e368055e04.PNG)

* Expected behaviour:
* Steps to reproduce: 
1. Go to 'start menu, open JASP
2. Click on "nothing, it just crashes'

**Comment by isakohrlund** [comment]
Same issue.

**Comment by FransMeerhoff** [comment]
Hello @coreysparks 

Thanks for this info, and sorry for the inconvenience
Unfortunately we do not know exactly what's going on in such a case.
Sometimes one of the following actions (which are relatively easy to try) can help you out.

1. Can you try to install the Visual Studio 2017 Runtime manually?
You can find this at https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads. In your case  choose the x64 version i.e. vc_redist.64.exe. After installing, try to start JASP again.

2. If this still not works, please download our zipped installed version. You can find it at
https://jasp-stats.org/download-pre-installed-version-jasp/. After downloading this zipped file, unzip it to some folder and try to start JASP by double clicking the JASP.exe in this unzipped folder (By default JASP.0.9.2)

If this still not works: 

-We are interested in the following info:
We like to know what kind of Display Adapter your system uses.
You can find it by right clicking the Start button, choose the System tab and then Display Drivers.
Updating this driver might also be a solution for your problem.

-We are about to release a new version of JAPS 0.9.3 in a couple of weeks. (with a lot of bug fixes, a new panel redesign and other improvements) So you can also wait until this version
is released. Of course, we hope that this version will run on your system. But anyway we've added new logging features that should clarify what this problem causes.

Kind regards
Frans Meerhoff

**Comment by FransMeerhoff** [comment]
Hi @coreysparks 

Can you please tell us what the status of this issue is?

Kind regards 
Frans Meerhoff

**Comment by FransMeerhoff** [comment]
Hi @coreysparks 

Please reopen this issue if the status of this issue changed, or if the problem still occurs on the new release coming soon.

Kind regards
Frans Meerhoff
