### ISSUE TITLE
Custom contrasts

### ISSUE THREAD

**Issue by felixthoemmes** [jasp-stats/jasp-issues#35]
A nice feature might be to able to code your own contrast. SPSS calls this the LMATRIX in ANOVA designs (or MMATRIX in repeated measures designs). In R there is a function called fit.contrast() in the gmodels package. This would allow estimation of an interaction contrast. Currently, only pre-build contrasts are possible. 

Would also be highly interested in a Bayesian counterpart. Using the BayesFactor package it is easy to get credible intervals for interaction contrasts, but unsure how to get a Bayes Factor for one contrast of interest.

**Comment by tomtomme** [comment]
Custom Contrasts for classical ANOVA is done since some time, but still missing for the bayesian counterpart.
