### ISSUE TITLE
Feature request: additional features for regression

### ISSUE THREAD

**Issue by romina-gonzalez-musso** [jasp-stats/jasp-issues#351]
Hi everyone,
My name is Romina and I work in a University. I teach statistics applied to forestry. First of all, I would like to say that I’m very happy with this software since it’s ideal and very suitable for teaching.

We usually estimate forests parameters using Regression Models. In JASP we can do this but there are some features that could be added to make better analysis. 

ENHANCEMENT:
- Adding confidence and prediction intervals in scatter plots.
- The possibility of fitting and linearizing non-linear models.

PURPOSE: 
- Intervals: for analizing if any value in the interval is a plausible value of the parameter, while values outside the interval are implausible. It provides a range for the true population value. 
- Non-linear models: to obtain best-fit values of the parameters, or to compare the fits of alternative models. 

USE-CASE:
In forests inventories/surveys. Stand variables (such as diameter, tree height, volume) are not always the same. When fitting model for making predictions for a whole forest, it is important to analize all the  possibilities to choose a proper model.   

I look foward to hearing from you and your opinions on the matter.
Greetings,
Romina

**Comment by tomtomme** [comment]
@romina-gonzalez-musso 

Done: 
"Adding confidence and prediction intervals in scatter plots."


Unclear:
"The possibility of fitting and linearizing non-linear models."

How do you want this feature to be implemented? 
Currently the flexplot module allows visualizing non-linear models. Also the computed column feature alows linearizing those models. Is this sufficient? If so, feel free to close this issue.
Thx.

**Comment by romina-gonzalez-musso** [comment]
Hi Tom!
Great! I will explore this new features in a while. Thanks for the amazing job!
