### ISSUE TITLE
JASP outputs cell comment instead of cell content

### ISSUE THREAD

**Issue by isakohrlund** [jasp-stats/jasp-issues#352]
* JASP version: 0.9
* OS name and version: Windows 10
* Analysis: - (data view)
* Bug description: When there is a comment in a cell (made in Excel), JASP outputs the comment in the data view instead of the actual cell content.
* Add JASP files as a zip:
* Screenshot: 
* Expected behaviour: JASP should read the cell content, not the comment. I use comments in my original files to make notes about what different numbers mean, the quality of the data etc.
* Steps to reproduce: Create an .ods file (do not know of any other format that support comments that JASP can read) with some data, comment on e.g. cell A1 using Excel's comment function, load in JASP and look at the column heading.

**Comment by JorisGoosen** [comment]
Could you add the file you are trying to load or some other simple example ods for us?

**Comment by isakohrlund** [comment]
Sorry for not responding earlier. I can upload something once I'm back from
my vacation in August. You should be able to replicate it though. Just add
a comment to a cell in Excel, save, open in JASP and see what it outputs in
the data view.

Best regards
Isak

Den ons 3 juli 2019 15:31Joris Goosen <notifications@github.com> skrev:

**Comment by JorisGoosen** [comment]
Well, I do not have excel so that would be pretty hard but I will see your example file here when you get back.

Enjoy your vacation! ;)

**Comment by isakohrlund** [comment]
Sorry for my late response. Here is an example. There is a comment, made in Excel, in column 2 row 1 and column 3 row 2. As you can see, JASP does not read the column 2 heading (which is "Column 2"), but tries to read the comment (staring with "Author:"). The comment is Column 3 row 2 does not seem to cause any trouble though. 

The file was created in Excel 2016 as an .xlsx, and then saved as an .ods.
[Excel comment JASP bug.zip](https://github.com/jasp-stats/jasp-issues/files/3625891/Excel.comment.JASP.bug.zip)

**Comment by JorisGoosen** [comment]
Thanks!

I will take a look sometime after the upcoming release.

**Comment by tomtomme** [comment]
Still valid for JASP 0.18.2 beta

**Comment by JorisGoosen** [comment]
Ill try to remember looking at it this release. I guerss I have to get a license again for microsoft office
