### ISSUE TITLE
Feature Request: Multiple simple effects analysis in single ANOVA

### ISSUE THREAD

**Issue by itaitu** [jasp-stats/jasp-issues#353]
Hi,
Would it be possible to add an option to conduct multiple simple effects tests in a single ANOVA analysis?

For example, say i have 2X2 dataset, with first variable with levels "A" and "B" and a second with levels "1" and "2". I added an ANOVA. now, i have the option to add a simple effect analysis of the first variable in both levels of the other variable, and the opposite, **but not both at the same ANOVA analysis.**

I added an example of what it should look like.
![Anova_feature](https://user-images.githubusercontent.com/45493794/57224524-68b62300-7012-11e9-99be-83d0f6c1fc47.png)

Thanks

**Comment by JorisGoosen** [comment]
@JohnnyDoorn is this now implemented?

**Comment by JohnnyDoorn** [comment]
No, at some point I should sit with your or Bruno to have a widget developed for this (something with tabs would be suitable here I think, and we need a similar widget for SEM anyway)

**Comment by JorisGoosen** [comment]
Ok, so for a future version then, we can do that then yeah.

**Comment by tomtomme** [comment]
@JohnnyDoorn @itaitu 
Is this still needed? We have the green + Button now that makes it really fast to duplicate the analysis and then you would only need to switch that one factor.
From my point of view this seems done.
