### ISSUE TITLE
PLS-SEM

### ISSUE THREAD

**Issue by aagejo** [jasp-stats/jasp-issues#354]
Feature request: PLS-SEM

PLS-SEM is an increasingly popular method in particular for small-N sample analysis.

I would like to have PLS-SEM in new versions of JASP. Do you currently have plans for this?

**Comment by JASPUSER09990** [comment]
Agree. Hope JASP can support PLS-SEM.

**Comment by vankesteren** [comment]
Note to self: once it has a stable release, we can use the `cSEM` package by @M-E-Rademaker and @FloSchuberth for this ([link](https://github.com/M-E-Rademaker/cSEM)).

**Comment by vankesteren** [comment]
Update: I see that cSEM is now on CRAN, I should check if it has all the features we would want!

**Comment by FloSchuberth** [comment]
@vankesteren What kind of features are you looking for? Perhaps I can help :)

**Comment by vankesteren** [comment]
Hey, thanks for the offer! I expect cSEM to already have all the features we need, I will check this with the new update of the SEM module soon. I will contact you should I need any help 👍

**Comment by FloSchuberth** [comment]
Hey Erik-Jan, you are welcome. It is a pretty cool idea to include PLS in JASP. I already received some requests whether this will be soon possible. So I am happy to hear that you take care of that ;) I agree that most of the commonly emloyed tests and metrics are provided by cSEM. In fact we cover all the features of the commercial software packages like SmartPLS and ADANCO and most of the features of the existing R packages such as plspm, matrixpls, etc. Of course, in case you face limitations of the cSEM package, please let me know and I can implement it.

As I am not familar with JASP, can you include R packages there? You mentioned that there is a SEM module. Is it also based on a counterpart in R? If yes, do you know which package is used as template? lavaan?
  
Best regards, 
Flo

**Comment by FloSchuberth** [comment]
I also saw that you write guidelines paper for certain statistical techniques using JASP, perhaps this also provides an opportunity to cooperate once it is implemented in JASP. If you are interested in sth like that, please let me know as well :)

**Comment by Anatoliy-Livov** [comment]
In my faculty, from Lecturers to Phd students, if they did SEM,  SmartPLS is preferred but it's commercial software and my school doesn't buy. Many students even lecturers choose pirated or trial version. I think if JASP supported PLS-SEM, it will be a good news for them.

**Comment by FloSchuberth** [comment]
> In my faculty, from Lecturers to Phd students, if they did SEM, SmartPLS is preferred but it's commercial software and my school doesn't buy. Many students even lecturers choose pirated or trial version. I think if JASP supported PLS-SEM, it will be a good news for them.

And of course, if you do not want to wait till PLS is implemented in JASP, you can use R package cSEM (sorry for the self-promotion).

**Comment by Anatoliy-Livov** [comment]
For business research students, it is quite hard to master R for
statistical analysis. I hope that JASP should be more windowed to be more
friendly for business research students.

**Comment by FloSchuberth** [comment]
Yes, I fully understand that and I guess that is also the reason for JASP. Let's hope that you will find there soon an implementation of PLS-PM.

**Comment by Anatoliy-Livov** [comment]
> Yes, I fully understand that and I guess that is also the reason for JASP. Let's hope that you will find there soon an implementation of PLS-PM.

TQ

**Comment by morimora** [comment]
Hi.
Any updates?

**Comment by boutinb** [comment]
@JMBKoch Could you tell whether there is a planning for this feature?

**Comment by JMBKoch** [comment]
@boutinb This is unfortunately unfeasible for now.

**Comment by ariefjusuf** [comment]
Thank you @juliuspf  and @LSLindeloo

**Comment by Kucharssim** [comment]
Implemented by https://github.com/jasp-stats/jaspSem/pull/94

**Comment by FloSchuberth** [comment]
@Kucharssim: Could please let me know when PLS-SEM will be available in JASP. I tried the current version (0.16.4) and I couldn't find PLS-SEM in there.

**Comment by Kucharssim** [comment]
@FloSchuberth it will be available in the next release (0.17.0) coming up early next year.
