### ISSUE TITLE
JASP will not switch between scale, nominal, and ordinal

### ISSUE THREAD

**Issue by JRM2016** [jasp-stats/jasp-issues#356]
* JASP version:
* OS name and version:
* Analysis:
* Bug description:
* Add JASP files as a zip:
* Screenshot: 
* Expected behaviour:
* Steps to reproduce: 
I have attempted to attach the file but I can not get it to the right file type to attach so here is a pasted word for word what the error says
This analysis terminated unexpectedly.

Error in (structure(function (...) : Evaluation error: factor level [6] is duplicated.

Stack trace
analysis(jaspResults = jaspResults, dataset = dataset, options = options, state = oldState)

.readDataSetToEnd(columns.as.numeric = variables)

.fromRCPP('.readDatasetToEndNative', unlist(columns), unlist(columns.as.numeric), unlist(columns.as.ordinal), unlist(columns.as.factor), all.columns ≠ FALSE)

do.call(obj, args)

(function (...) 
{
    .External(InternalFunction_invoke, xp, ...)
})(NULL, c('Record Low in F (Year)', 'Peak Wind Gust in Miles per hour (Year)'), NULL, NULL, FALSE)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

**Comment by TimKDJ** [comment]
Github is happy with .zip's -- if you could compress and attach your .jasp file that would be very helpful.
