### ISSUE TITLE
Need help with error importing 'Effect Size Standard Error'

### ISSUE THREAD

**Issue by Emmagsin** [jasp-stats/jasp-issues#357]
his analysis terminated unexpectedly.

Error in (function (class, type, ...) : Could not find message for class error and type NA

Stack trace 
analysis(dataset = dataset, options = options, perform = perform, callback = the.callback, state = oldState)

.hasErrors(dataset, perform, type = c('infinity', 'observations'), custom = error_if(any(dataset[[b64(stderrName)]] <= 0), 'Non-positive standard errors encountered in variable '', stderrName, ''. Standard errors should be positive. Please check your input.'), all.target = numeric.variables, observations.amount = '< 2', exitAnalysisIfErrors = TRUE)

base::do.call(.generateErrorMessage, c(list(type = msgType, opening = opening, concatenate = errors[['message']], variables = varsToAdd, grouping = grouping), args))

(function (type, opening = FALSE, concatenate = NULL, grouping = NULL, ...) 
{
    if (!is.character(type) || length(type) = 0) {
        stop('Non-valid type argument provided')
    }
    if (grepl(' ', type, fixed = TRUE) = TRUE) {
        message <- type
    }
    else {
        args <- c(list(grouping = grouping, class = 'error', type = type), list(...))
        message <- do.call(.messages, args)
    }
    if (!is.null(concatenate) || opening = TRUE) {
        message <- paste0('
', message, '
')
    }
    if (is.character(concatenate) && length(concatenate) = 1) {
        endOfString <- substr(concatenate, nchar(concatenate) - 4, nchar(concatenate))
        if (endOfString = '') {
            concatenate <- substr(concatenate, 1, nchar(concatenate) - 5)
        }
        message <- paste0(concatenate, message)
    }
    if (opening = TRUE) {
        openingMsg <- .messages('error', 'opening')
        if (grepl(openingMsg, message, fixed = TRUE) = FALSE) {
            message <- paste0(openingMsg, '
', message)
        }
    }
    if (type = 'varCovData' && !is.null(args$variables)) {
        nPairs <- length(args$variables$var1)
        if (nPairs > 10) {
            msg <- sprintf('
Note: There are %d pairs of variables perfectly correlated. The first 10 are: ', nPairs)
        }
        else {
            msg <- '
Note: The following pair(s) of variables is/are perfectly correlated: '
        }
        message <- paste0(message, msg)
        for (i in seq_len(nPairs)) {
            message <- paste0(message, args$variables$var1[[i]], ' and ', args$variables$var2[[i]])
            if (i < length(args$variables$var1)) {
                message <- paste0(message, '; ')
            }
            else if (i = length(args$variables$var1)) {
                message <- paste0(message, '. Note that if you have specified a weights variable, the correlations are computed for the weighted variables.
')
            }
        }
    }
    return(message)
})(type = 'NA', opening = TRUE, concatenate = NULL, variables = NULL, grouping = NULL, dataset = list(XRWZmZWN0IFNpemUgU3RhbmRhcmQgRXJyb3I = c(0.279821372, 0.279642629, 0.229564806, 0.318433667, 0.368781778, 0.214009346, 0.219544984, 0.087177979, 0.133790882, 0.338673884, 0.236854386, 0.299833287, 0.337786915, 0.34423829, 0.117046999, NaN, NaN, NaN, NaN, NaN)), all.target = 'Effect Size Standard Error', observations.amount = '< 2', infinity.target = 'Effect Size Standard Error', infinity.grouping = NULL, 
    infinity.groupingLevel = NULL, observations.target = 'Effect Size Standard Error', observations.grouping = NULL, observations.groupingLevel = NULL)

do.call(.messages, args)

(function (class, type, ...) 
{
    m <- list()
    m$error$opening <- 'The following problem(s) occurred while running the analysis:'
    m$error$grouping <- 'after grouping on {{grouping}}'
    m$error$exception <- 'This analysis terminated unexpectedly.

{{error}}
Stack trace 

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports'
    m$error$infinity <- 'Infinity found in {{variables}}'
    m$error$factorLevels <- 'Number of factor levels {{factorLevels.amount}} in {{variables}}'
    m$error$variance <- 'Variance = {{variance.equalTo}} in {{variables}}'
    m$error$observations <- 'Number of observations {{observations.amount}} in {{variables}}'
    m$error$levene <- 'Cannot compute statistic reliably: number of observations {{observations.amount}} in {{variables}}'
    m$error$limits <- 'Values in {{variables}} outside interval [{{limits.min}}, {{limits.max}}]'
    m$error$varCovMatrix <- 'Dataset is not a proper variance-covariance matrix. Please load only a positive definite symmetrical matrix as your dataset.'
    m$error$varCovData <- 'The variance-covariance matrix of the supplied data is not positive-definite. Please check if variables have many missings observations or are collinear'
    m$footnote$leveneSign <- 'Levene's test is significant (p < .05), suggesting a violation of the equal variance assumption'
    m$footnote$VovkSellkeMPR <- 'Vovk-Sellke Maximum p-Ratio: Based the p-value, the maximum possible odds in favor of H₁ over H₀ equals 1/(-e p log(p)) for p ≤ .37 (Sellke, Bayarri, & Berger, 2001).'
    m$footnote$binomNeq <- 'Proportions tested against value: {{value}}.'
    m$footnote$binomLess <- 'For all tests, the alternative hypothesis specifies that the proportion is less than {{value}}.'
    m$footnote$binomGreater <- 'For all tests, the alternative hypothesis specifies that the proportion is greater than {{value}}.'
    message <- m[[class]][[type]]
    if (is.null(message)) 
        stop(paste('Could not find message for class', class, 'and type', type))
    args <- list(...)
    if (length(args) > 0) 
        message <- .parseMessage(message, class, ...)
    return(message)
})(grouping = NULL, class = 'error', type = 'NA', variables = NULL, dataset = list(XRWZmZWN0IFNpemUgU3RhbmRhcmQgRXJyb3I = c(0.279821372, 0.279642629, 0.229564806, 0.318433667, 0.368781778, 0.214009346, 0.219544984, 0.087177979, 0.133790882, 0.338673884, 0.236854386, 0.299833287, 0.337786915, 0.34423829, 0.117046999, NaN, NaN, NaN, NaN, NaN)), all.target = 'Effect Size Standard Error', observations.amount = '< 2', infinity.target = 'Effect Size Standard Error', infinity.grouping = NULL, infinity.groupingLevel = NULL, 
    observations.target = 'Effect Size Standard Error', observations.grouping = NULL, observations.groupingLevel = NULL)

stop(paste('Could not find message for class', class, 'and type', type))

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

**Comment by JohnnyDoorn** [comment]
Hi Emmagsin,

Could you tell me which analysis you tried to run, and with which data? That way I can try to reproduce your error. I'm guessing it's meta-analysis, and there are negative standard errors in your data, but I am not sure.

Kind regards,
Johnny

**Comment by TimKDJ** [comment]
@JohnnyDoorn: The problem lies in the fact that `any(dataset[[b64(stderrName)]] <= 0)` returns `NA` rather than a boolean, which `error_if()` then happily converts to `"NA"`; `.hasErrors()` assumes this is an identifier of an error message type, which it is not.

We'll have to see what sort of data causes this... because for me the check works fine.

**Comment by JorisGoosen** [comment]
@Emmagsin could you upload this data for us?
