### ISSUE TITLE
File name is shown wrong

### ISSUE THREAD

**Issue by jens-k** [jasp-stats/jasp-issues#361]
* JASP version: 0.9.2
* OS name and version: Windows 7
* Analysis: doesn't matter
* Bug description: When opening a file the name of which includes dots, the file name is only shown up to the first dot. JASP seems to think this dot marks the file extension. However, only the last dot in a file name should be considered as such.
* Add JASP files as a zip:
* Screenshot: 
![image](https://user-images.githubusercontent.com/10050167/58333395-989c5d80-7e3d-11e9-998b-33428c4ce24f.png)
* Expected behaviour: The whole filename should be shown.

**Comment by boutinb** [comment]
Solved in 0.10.1
