### ISSUE TITLE
Ability to change the font in the results (tables and plots)

### ISSUE THREAD

**Issue by meterfiller** [jasp-stats/jasp-issues#363]
It would help a lot to have an option to display results in other font families, particularly Times New Roman. Most of us are psychologists here, and we mostly submit in APA format which requires Times New Roman. I've spent a lot of time figuring out how to get my figures in R showing up in Times New Roman (it's easy now that I know how to do it) but I like using JASP for a mini-meta I'm working on and the results figures can't really be submitted as is in their current font. 

**Describe the solution you'd like**
Add a Preference to choose the font family. Ideally one preference for the UI font, and another for the results font; I like working in a sans-serif font, but I need my results to show up in TNR, especially figures.

**Describe alternatives you've considered**
The only alternative I've found so far is to make a table in Excel with the right font and then paste a cropped version of the figure onto that table. Pretty insane and not a long term solution at all. This really stresses me out :s

**Comment by EJWagenmakers** [comment]
Great suggestion.
@TimKDJ : we were going to discuss the tables anyway, let's discuss this as well. Wednesday, June 5, 11:00?

**Comment by tultimatte** [comment]
I would like to second that :)
Thank you very much,
Daniel

**Comment by TimKDJ** [comment]
This will be included in 0.15
