### ISSUE TITLE
Intercalas correlation coefficient 

### ISSUE THREAD

**Issue by vicenteinefo** [jasp-stats/jasp-issues#365]
* Enhancement: add the ICC calculation in the reliability analysis section
* Purpose: to calculate the ICC for reliability studies with multiple quantitative variables 
* Use-case: in sports science is typically asses the reliability of instruments that report quantitative variables, nowadays we need to compute this calculation using other statistical packages like SPSS.

**Comment by DrMarkGS** [comment]
Would really support this

**Comment by juliuspfadt** [comment]
By now, this is solved
