### ISSUE TITLE
Feature request: Mediation and Moderation analysis

### ISSUE THREAD

**Issue by zekeqr** [jasp-stats/jasp-issues#366]
* Enhancement: To add mediation and moderation analysis features
* Purpose: To analyse and identify hypothetical causation (mediation) and moderation effects
* Use-case: Statistics, Psychology, Research

**Is your feature request related to a problem? Please describe.**
There are no such functions in JASP yet. 

**Describe the solution you'd like**
I would like to be able to run mediation / moderation analysis using JASP, or the capability to import the libraries created by Andrew Hayes

**Describe alternatives you've considered**
It is possible to run it using SPSS, but SPSS is not free and very expensive. It is also possible to run it using R, but the lack of a proper GUI may cause it to be confusing for students.

**Additional context**
Though moderation is statistically equivalent to a factorial ANOVA (which is found in JASP), there are more advanced functions to identify the effect of the moderating variable that is not used in a factorial ANOVA analysis, thus this request. 

Thank you very much !

**Comment by vankesteren** [comment]
Mediation analysis is in progress! For moderation analysis we would need a bit more investigation and thought on where to put it.

**Comment by zekeqr** [comment]
Good to know ! Mediation and Moderation are usually taught together (at least for my university), so maybe you could group them together as well :)

Andrew Hayes has created PROCESS, an extension of SPSS and SAS and offers it for free. 
http://processmacro.org/download.html

Just a thought, perhaps it could be integrated into JASP similar to how it is being integrated into SPSS or SAS? (Not sure if this process is easier or more difficult for the developers, so just a suggestion). 

Thank you for the quick reply. Looking forward to the next update with MANOVA ! :)

**Comment by vankesteren** [comment]
Thanks for the feedback, I will look into categorical mediators when I develop this.

As to your question regarding the method, I am not sure what you mean by "newer theoretical perspective". The Baron & Kenny method (causal steps) is quite old and has some theoretical downsides. I am not sure what Hayes uses in PROCESS, but in general, we will be performing mediation analysis using a structural equation modeling framework, where the mediation test will be a test of the a*b indirect effect paths (product of coefficient method), with significance tests based on either the delta method standard errors or (bias-corrected) bootstrap confidence intervals. 

See also this paper for more information: https://link.springer.com/article/10.3758/BRM.40.3.879

There will be a good help file for this function!

**Comment by Musing-about** [comment]
To follow up on your post, @vankesteren: Hayes’ PROCESS macro for SPSS uses the "modern approach", i.e., it calculates a*b and constructs a bootstrap confidence interval. However, it doesn’t use SEM to calculate the paths a and b, but OLS regression instead. Which leads me to the question: Will JASP’s new functionality allow to choose between SEM and OLS regression to analyse mediation effects? I think being able to do that with ordinary regression will be important for many psychologists.

**Comment by AlexanderLyNL** [comment]
In JASP 0.10.1
