### ISSUE TITLE
Error: object 'reverse' not found

### ISSUE THREAD

**Issue by drio22** [jasp-stats/jasp-issues#367]
This occurs during a posthoc (Tukey) on an ANOVA  Its the only variable I have that had this error.  As a result, I am assuming it is something in my data but not sure what this means so its hard to track down.   I am using the latest version on a Windows platform. 0.9.2

**Comment by TimKDJ** [comment]
Could you attach the .jasp file where this error occurs to this issue or send it to me at t.dejong@jasp-stats.org?
