### ISSUE TITLE
Incorporate r's sample and predict functions

### ISSUE THREAD

**Issue by ImproveSWB** [jasp-stats/jasp-issues#368]
* Enhancement: Allow users to develop a model on a subset of data and to test the model on a holdout sample (typically named "train") 
* Purpose: Current models cannot be applied against different data. Without a holdout sample, or incorporating a mechanism such as a jackknife, model fit tends to be optimistic.
* Use-case:
For users interested in developing predictive models, there is a need to be able to apply the model/algorithm on data that was not used to develop the model. 
**Is your feature request related to a problem? Please describe.**
 

**Describe the solution you'd like**
 
Add two modules in "+", "Sample" and "Predict"
Sample, would allow the user to specify how the current data set is to be sampled and then generate two files, "Train", and "Test". Subsequent modeling would use the "Train" file.
After developing a model, a user would then invoke the "Predict" function, and apply the model to the data set "Train". In addition to using r's predict function, the application would then run summary on the model and compute a confusion matrix,
**Describe alternatives you've considered**
 In the absence of this functionality, a researcher would need to generate the two files externally either in Excel or r and then manually apply the model in another application.

**Additional context**

**Comment by juliuspfadt** [comment]
@ImproveSWB, thanks for the request, and sorry for the late response. I think this is an excellent point, @EJWagenmakers? How feasible is this, @JorisGoosen?

**Comment by EJWagenmakers** [comment]
This functionality is an inherent part of the machine learning model. I am not sure whether we need it for any other models, specifically? If there is a specific set of other models that we wish to do this for, then we could implement the same functionality as was done for machine learning, perhaps.

**Comment by JorisGoosen** [comment]
As EJ states, this is integrated into machine learning module already and is indispensable there.
Im not sure how this would be useful for other analyses?

**Comment by juliuspfadt** [comment]
well, how about SEM and cross validation?

**Comment by EJWagenmakers** [comment]
It would be possible, but I wonder how big the need really is. leave-one-out CV is essentially AIC (Stone, 1977 I think). We could build in k-fold CV for SEM, but I'd like to see a feature request for this first
