### ISSUE TITLE
Opening .sav files with JASP on Mac OS Mojave

### ISSUE THREAD

**Issue by tomsalomon** [jasp-stats/jasp-issues#369]
* JASP version: 0.9.2
* OS name and version: Mac OS Mojave 10.14
* Analysis:
* Bug description:
When trying to open an SPSS .sav file with JAPS via double-click or 'open with', the file won't open unless JASP is already running. If JASP is running in the background double-clicking  a .sav file work

* Add JASP files as a zip:
[sav_file_JASP.zip](https://github.com/jasp-stats/jasp-issues/files/3251853/sav_file_JASP.zip)

* Screenshot: 
* Expected behaviour:
JASP program should be able to open and load the data file when opening .sav file
* Steps to reproduce: 
1. Using Mac OS, define JASP as the defualt app to open .sav files.
2. Double click a .sav file.
3. first open JASP and then repeat steps 1-2.

**Comment by boutinb** [comment]
I have just tried with version 0.10.0, and it works on my Mac. Can you try with the this JASP version?

**Comment by tomsalomon** [comment]
Hey, 

I updated to version 0.10.0 and still have the same issue. sav files only open if JASP is already running in the background. 
You can see a demonstration in this screen recording I made:
https://drive.google.com/file/d/1OMQeOap6B1SGg4t0unQujMn6ujp4IuK7/view?usp=sharing

Thanks!

**Comment by boutinb** [comment]
This is quite strange...
Could you start JASP from the terminal like this: 
      /Applications/JASP.app/Contents/MacOS/JASP datasav.sav
Do you have the same behaviour? And if yes, can you send me the output of the terminal?
Thanks

**Comment by tomsalomon** [comment]
When I try to open via the terminal I get slightly different yet still dysfunctional behavior.
JASP opened and after 1-2 seconds closed without opening the data file.

This is the output I get on the terminal:

GVA info: Successfully connected to the Intel plugin, offline Gen75 
qrc:/components/JASP/Widgets/ComputeColumnWindow.qml:330:2: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/ComputeColumnWindow.qml:330:2: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:362:4: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:362:4: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:112:4: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:112:4: QML Dialog: Binding loop detected for property "implicitWidth"
QNetworkReplyHttpImplPrivate::_q_startOperation was called more than once QUrl("https://jasp-stats.org/jasp-version/")
Property 'data'' of object 'QQuickRootItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'resources'' of object 'QQuickRootItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'states'' of object 'QQuickRootItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transitions'' of object 'QQuickRootItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transformOriginPoint'' of object 'QQuickRootItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transform'' of object 'QQuickRootItem' has no notify signal and is not constant, value updates in HTML will be broken!
Don't know how to handle 'mode', use qRegisterMetaType to register it.
Don't know how to handle 'format', use qRegisterMetaType to register it.
Don't know how to handle 'mirroring', use qRegisterMetaType to register it.
Don't know how to handle '', use qRegisterMetaType to register it.
Property 'data'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'resources'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'states'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transitions'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transformOriginPoint'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transform'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Don't know how to handle '', use qRegisterMetaType to register it.
Property 'data'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'resources'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'states'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transitions'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transformOriginPoint'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transform'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'data'' of object 'SplitView_QMLTYPE_63_QML_162' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'resources'' of object 'SplitView_QMLTYPE_63_QML_162' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'states'' of object 'SplitView_QMLTYPE_63_QML_162' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transitions'' of object 'SplitView_QMLTYPE_63_QML_162' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transformOriginPoint'' of object 'SplitView_QMLTYPE_63_QML_162' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transform'' of object 'SplitView_QMLTYPE_63_QML_162' has no notify signal and is not constant, value updates in HTML will be broken!
Don't know how to handle '', use qRegisterMetaType to register it.
Property 'data'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'resources'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'states'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transitions'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transformOriginPoint'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transform'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'data'' of object 'QQuickRectangle' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'resources'' of object 'QQuickRectangle' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'states'' of object 'QQuickRectangle' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transitions'' of object 'QQuickRectangle' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transformOriginPoint'' of object 'QQuickRectangle' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transform'' of object 'QQuickRectangle' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'gradient'' of object 'QQuickRectangle' has no notify signal and is not constant, value updates in HTML will be broken!
Don't know how to handle '', use qRegisterMetaType to register it.
Property 'data'' of object 'QQuickWebEngineView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'resources'' of object 'QQuickWebEngineView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'states'' of object 'QQuickWebEngineView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transitions'' of object 'QQuickWebEngineView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transformOriginPoint'' of object 'QQuickWebEngineView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transform'' of object 'QQuickWebEngineView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'userScripts'' of object 'QQuickWebEngineProfile' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'data'' of object 'QQuickWebEngineHistory' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'resources'' of object 'QQuickWebEngineHistory' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'states'' of object 'QQuickWebEngineHistory' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transitions'' of object 'QQuickWebEngineHistory' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transformOriginPoint'' of object 'QQuickWebEngineHistory' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transform'' of object 'QQuickWebEngineHistory' has no notify signal and is not constant, value updates in HTML will be broken!
Don't know how to handle '', use qRegisterMetaType to register it.
Property 'transports'' of object 'QQmlWebChannel' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'registeredObjects'' of object 'QQmlWebChannel' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'userScripts'' of object 'QQuickWebEngineView' has no notify signal and is not constant, value updates in HTML will be broken!
Don't know how to handle '', use qRegisterMetaType to register it.
Property 'data'' of object 'QQuickItem_QML_164' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'resources'' of object 'QQuickItem_QML_164' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'states'' of object 'QQuickItem_QML_164' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transitions'' of object 'QQuickItem_QML_164' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transformOriginPoint'' of object 'QQuickItem_QML_164' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transform'' of object 'QQuickItem_QML_164' has no notify signal and is not constant, value updates in HTML will be broken!
Don't know how to handle '', use qRegisterMetaType to register it.
R_HOME: /Applications/JASP.app/Contents/Frameworks/R.framework/Versions/3.5/Resources/
R_HOME: /Applications/JASP.app/Contents/Frameworks/R.framework/Versions/3.5/Resources/
R_HOME: /Applications/JASP.app/Contents/Frameworks/R.framework/Versions/3.5/Resources/
R_HOME: /Applications/JASP.app/Contents/Frameworks/R.framework/Versions/3.5/Resources/

**Comment by tomsalomon** [comment]
I don't know if it has something to do with that - the file that could not be opened via the terminal was a file with some variable properties (e.g. categorical variables with labels). 
I now tried to open a different file with just a few scale variables and it did work via the terminal!

I still get these 'HTML will be broken' warning (even though the file did open)
I attach the two files if that helps.

This is the output I get for the file that can be opened via the terminal.

sherman220-1:SPSS file tomsalomon$ GVA info: Successfully connected to the Intel plugin, offline Gen75 
qrc:/components/JASP/Widgets/ComputeColumnWindow.qml:330:2: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/ComputeColumnWindow.qml:330:2: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:362:4: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:362:4: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:112:4: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:112:4: QML Dialog: Binding loop detected for property "implicitWidth"
R_HOME: /Applications/JASP.app/Contents/Frameworks/R.framework/Versions/3.5/Resources/
R_HOME: /Applications/JASP.app/Contents/Frameworks/R.framework/Versions/3.5/Resources/
R_HOME: /Applications/JASP.app/Contents/Frameworks/R.framework/Versions/3.5/Resources/
R_HOME: /Applications/JASP.app/Contents/Frameworks/R.framework/Versions/3.5/Resources/
QNetworkReplyHttpImplPrivate::_q_startOperation was called more than once QUrl("https://jasp-stats.org/jasp-version/")
Property 'data'' of object 'QQuickRootItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'resources'' of object 'QQuickRootItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'states'' of object 'QQuickRootItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transitions'' of object 'QQuickRootItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transformOriginPoint'' of object 'QQuickRootItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transform'' of object 'QQuickRootItem' has no notify signal and is not constant, value updates in HTML will be broken!
Don't know how to handle 'mode', use qRegisterMetaType to register it.
Don't know how to handle 'format', use qRegisterMetaType to register it.
Don't know how to handle 'mirroring', use qRegisterMetaType to register it.
Don't know how to handle '', use qRegisterMetaType to register it.
Property 'data'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'resources'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'states'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transitions'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transformOriginPoint'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transform'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Don't know how to handle '', use qRegisterMetaType to register it.
Property 'data'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'resources'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'states'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transitions'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transformOriginPoint'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transform'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'data'' of object 'SplitView_QMLTYPE_56_QML_155' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'resources'' of object 'SplitView_QMLTYPE_56_QML_155' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'states'' of object 'SplitView_QMLTYPE_56_QML_155' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transitions'' of object 'SplitView_QMLTYPE_56_QML_155' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transformOriginPoint'' of object 'SplitView_QMLTYPE_56_QML_155' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transform'' of object 'SplitView_QMLTYPE_56_QML_155' has no notify signal and is not constant, value updates in HTML will be broken!
Don't know how to handle '', use qRegisterMetaType to register it.
Property 'data'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'resources'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'states'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transitions'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transformOriginPoint'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transform'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'data'' of object 'QQuickRectangle' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'resources'' of object 'QQuickRectangle' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'states'' of object 'QQuickRectangle' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transitions'' of object 'QQuickRectangle' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transformOriginPoint'' of object 'QQuickRectangle' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transform'' of object 'QQuickRectangle' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'gradient'' of object 'QQuickRectangle' has no notify signal and is not constant, value updates in HTML will be broken!
Don't know how to handle '', use qRegisterMetaType to register it.
Property 'data'' of object 'QQuickWebEngineView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'resources'' of object 'QQuickWebEngineView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'states'' of object 'QQuickWebEngineView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transitions'' of object 'QQuickWebEngineView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transformOriginPoint'' of object 'QQuickWebEngineView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transform'' of object 'QQuickWebEngineView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'userScripts'' of object 'QQuickWebEngineProfile' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'data'' of object 'QQuickWebEngineHistory' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'resources'' of object 'QQuickWebEngineHistory' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'states'' of object 'QQuickWebEngineHistory' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transitions'' of object 'QQuickWebEngineHistory' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transformOriginPoint'' of object 'QQuickWebEngineHistory' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transform'' of object 'QQuickWebEngineHistory' has no notify signal and is not constant, value updates in HTML will be broken!
Don't know how to handle '', use qRegisterMetaType to register it.
Property 'transports'' of object 'QQmlWebChannel' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'registeredObjects'' of object 'QQmlWebChannel' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'userScripts'' of object 'QQuickWebEngineView' has no notify signal and is not constant, value updates in HTML will be broken!
Don't know how to handle '', use qRegisterMetaType to register it.
Property 'data'' of object 'QQuickItem_QML_157' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'resources'' of object 'QQuickItem_QML_157' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'states'' of object 'QQuickItem_QML_157' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transitions'' of object 'QQuickItem_QML_157' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transformOriginPoint'' of object 'QQuickItem_QML_157' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transform'' of object 'QQuickItem_QML_157' has no notify signal and is not constant, value updates in HTML will be broken!
Don't know how to handle '', use qRegisterMetaType to register it.

[SPSS_files.zip](https://github.com/jasp-stats/jasp-issues/files/3317602/SPSS_files.zip)

**Comment by tomsalomon** [comment]
Sorry for all the trouble. After another test, I figured the reason the file did not open was probably that it only had variables defined in it with no actual data. Once I filled in some random numbers it did open from the terminal (but not form Finder by double-clicking or right click ==> open with).

**Comment by boutinb** [comment]
But the file you sent me had data in it. It was another file?

**Comment by tomsalomon** [comment]
Hey, sorry for the delayed response.
In the zip I added have two files (attached here again): 
[SPSS_files.zip](https://github.com/jasp-stats/jasp-issues/files/3355100/SPSS_files.zip)
  
1. Works.sav - have data in it. Can open through the terminal.
2. Doesnt_work.sav - have only variable defined, without fille data. Cannot be opened by JASP in any way.

Neither one of the files can open JASP with a double click (or right click).

**Comment by JorisGoosen** [comment]
Thank you!

We will see what we can do

**Comment by JorisGoosen** [comment]
Fixed
