### ISSUE TITLE
Assumption checks - Homogeneity of regression slopes

### ISSUE THREAD

**Issue by andyroberts1234** [jasp-stats/jasp-issues#37]
Hi there,

It would be great if, for ANCOVA, in the assumption checks section there was an option to plot comparative regression slopes to allow the visual checking of the homogeneity of regression slopes assumption.

Something similar to the plot shown here for example [(https://goo.gl/images/6wiOSb)]

Thanks

Andy

**Comment by tomtomme** [comment]
can be closed as it is implemented for a while now (in ancova and flexplot and even in descriptives)
