### ISSUE TITLE
Rewrite BAIN module in JASP for CRAN package

### ISSUE THREAD

**Issue by JorisGoosen** [jasp-stats/jasp-issues#370]
In the upcoming release of JASP (0.10.0) we have included the BAIN module written by @koenderks. This uses a [custom (and older) version](https://github.com/jasp-stats/BAIN-for-JASP) of [BAIN](https://github.com/cjvanlissa/bain).

It would be great if we could rewrite our interface to use the newer version, because that version is actually on CRAN and that makes life much much easier, not too mention will make it easier for us to get access to any bugfixes or new features that get added.

In a mail-conversation @cjvanlissa mentioned that he would be willing to support us in rewriting the code so that's nice.

**Comment by koenderks** [comment]
Slight comment: We would have to rewrite the R code, not the interface.

**Comment by koenderks** [comment]
This will be implemented in https://github.com/jasp-stats/jasp-desktop/pull/3615
