### ISSUE TITLE
Blach window under REHL/CentOS 7

### ISSUE THREAD

**Issue by martindyrba** [jasp-stats/jasp-issues#371]
* JASP version: 0.9.2
* OS name and version: CentOS 7.4 with xrdp remote display connection
* Analysis: Unsupported Qt version available in CentOS (Qt 4.8) ?
* Bug description: On our linux server, the image/GUI remains black and does not show any content. However, it is still possible to click the buttons (such as open file)...
* Add JASP files as a zip:
* Screenshot: 
![grafik](https://user-images.githubusercontent.com/51474670/59088884-1023bf80-8909-11e9-9dac-80d37186d55a.png)

* Expected behaviour:
* Steps to reproduce: 
1. just open JASP from command line

**Comment by JorisGoosen** [comment]
@martindyrba have you tried the new version 0.10?

**Comment by martindyrba** [comment]
Ok, thank you for this information. For the new version, everything seems to work fine now :)
![jasp_0 1 0](https://user-images.githubusercontent.com/51474670/59826648-02bdfa80-9337-11e9-88f5-5582f5e34308.png)
