### ISSUE TITLE
Meta-analysis --- add meta-regression visualizations

### ISSUE THREAD

**Issue by OliverSchultheiss** [jasp-stats/jasp-issues#373]
* Enhancement: Subgroup analysis and meta-regression plots
* Purpose: Enable

First of all, congratulations & 1000 thank-yous for creating JASP! It is a giant leap forward for stats users and teachers in terms of ease of use, integration of Bayesian methods, and integration with OSF. Goes to show that our European taxes are being put to some excellent use (I understand that development of JASP was aided by an ERC grant).

I currently use the meta-analysis module for work on a paper. But I was missing two crucial features:

One is the ability to get subgroup analysis output for mixed-effects models (i.e., models that include a factor). It would be great to have a box with "subgroup analysis" which, if checked, would give me the estimates and CIs for each subgroup generated by the factor. Currently, I can do this only by saving a separate JASP project for each filter setting and then collecting the info from the different outputs this generates and putting it into one table.

The other feature I am missing is the visualization of meta-regression results; that is, a regression plot that shows the covariate on the x axis and the effect size measure on the y axis, with plot symbols of varying sizes to represent each effect size estimate and its SE.

It would be great if these features could be included in a future upgrade.

Keep up the great work! You are providing an essential and wonderful service to science with JASP.

Cheers,
Oliver

**Comment by raoelg** [comment]
Hi Oliver,

Great suggestions, thanks! We will need to see how this is feasible in general, because you seem to presume having only one factor and/or one continuous moderator. We're definitely looking at including an option to extract estimated marginal means based on categorical/factor moderators.

Raoul

**Comment by OliverSchultheiss** [comment]
Hi Raoul,

thanks for your reply. I was not necessarily assuing that there is only one moderator. I certainly have more than one in my current meta-analysis, although I test for them one by one and not for more than one simultaneously. Not sure whether current meta-analytic techniques can even accomodate for that….

Best wishes,
Oliver

**************************************************************************************************
Oliver C. Schultheiss, Dr. phil.
Professor of Psychology
Chair for Experimental Psychology, Motivation, and Affective Neuroscience
Institute of Psychology
Friedrich-Alexander University
Nägelsbachstr. 49 b
91052 Erlangen
Germany
Email: Oliver.Schultheiss@fau.de<mailto:Oliver.Schultheiss@psy.phil.uni-erlangen.de>
Phone: +49 9131 85-20880
Secretary: +49 9131 85-20879
URL: http://www.psych2.phil.uni-erlangen.de/~oschult/humanlab/index.htm

“[NASA] should be focused on the much bigger things we are doing, including Mars (of which the Moon is a part)“
-- Donald J. Trump, on Twitter, June 7 2019
**************************************************************************************************

Von: Raoul Grasman <notifications@github.com>
Gesendet: Mittwoch, 12. Juni 2019 03:15
An: jasp-stats/jasp-issues <jasp-issues@noreply.github.com>
Cc: Schultheiss, Oliver <oliver.schultheiss@fau.de>; Author <author@noreply.github.com>
Betreff: Re: [jasp-stats/jasp-issues] Meta-analysis (#373)


Hi Oliver,

Great suggestions, thanks! We will need to see how this is feasible in general, because you seem to presume having only one factor and/or one continuous moderator. We're definitely looking at including an option to extract estimated marginal means based on categorical/factor moderators.

Raoul

**Comment by tomtomme** [comment]
@OliverSchultheiss & 
- subgroup analysis seems done, since you can now put factors into the meta analyis and get a coefficient table showing estimates and CIs. Correct?

@raoelg & @FBartos 
is the plot that Oliver described feasible?
- meta-regression plot: x covariate; y effect size; symbols size representing ES & SE probably as intervals

**Comment by OliverSchultheiss** [comment]
Dear Thomas,

thanks for the update and for taking care of this. I’ll be sure t check out the new JASP functionality as soon as I have an opportunity to apply it.

Keep up the great work at Team JASP!

Best wishes,
Oliver

**************************************************************************************************
Oliver C. Schultheiss, Dr. phil.
Professor of Psychology
Chair for Experimental Psychology, Motivation, and Affective Neuroscience
Institute of Psychology
Friedrich-Alexander University
Nägelsbachstr. 49 b
91052 Erlangen
Germany
Email: ***@***.******@***.***>
Phone: +49 9131 85-20880
Secretary: +49 9131 85-20879
URL: http://www.psych2.phil.uni-erlangen.de/~oschult/humanlab/index.htm
**************************************************************************************************


Von: Thomas Langkamp ***@***.***>
Gesendet: Dienstag, 6. Februar 2024 21:15
An: jasp-stats/jasp-issues ***@***.***>
Cc: Schultheiss, Oliver ***@***.***>; Mention ***@***.***>
Betreff: Re: [jasp-stats/jasp-issues] Meta-analysis (#373)


@OliverSchultheiss<https://github.com/OliverSchultheiss> &

  *   subgroup analysis seems done, since you can now put factors into the meta analyis and get a coefficient table showing estimates and CIs. Correct?

@raoelg<https://github.com/raoelg> & @FBartos<https://github.com/FBartos>
is the plot that Oliver described feasible?

  *   meta-regression plot: x covariate; y effect size; symbols size representing ES & SE probably as intervals

**Comment by FBartos** [comment]
I will do a larger revamp of the meta-analysis module this year and keep this in mind
