### ISSUE TITLE
Cannot load rcpp

### ISSUE THREAD

**Issue by performlabrit** [jasp-stats/jasp-issues#375]
New developer here.  Working from the latest dev branch commit 6d9636296e81861d892ac5b45fd7502a8c84d9af.

Mac Mojave 10.14.4.

Upon build, I get two (likely related) errors:

`dlopen(/Users/gjdiaz/Documents/Code/jasp-desktop/Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp/libs/Rcpp.so, 6):-1: error: Library not loaded: @executable_path/../Frameworks/R.framework/Versions/3.5/Resources/lib/libR.dylib`

and 

`:-1: error: lazy loading failed for package 'JASPgraphs'`

The build is otherwise successful, but this (predictably) prevents plotting within JASP.  Note that I have verified that rcpp is installed and current through the R console.  I can also confirm that the file Rcpp.so is in the appropriate location on my hard drive.

**Comment by FransMeerhoff** [comment]
HI @performlabrit 

It seems that there is something wrong with the location of your the Frameworks location
Our build environment has the following structure all these folders on the same level:
- boost_1_64_0 (boost headers git pulled from jasp-required-files on github)
- jasp-desktop (sources cloned from jasp-desktop on github)
- build-jasp (where the actual executables are build, name given in Qt)
- Frameworks (git pulled from jasp-required-files on github)

Probably unnecessary to say but you can get the jasp-required-files from
>git clone https://github.com/jasp-stats/jasp-required-files
>git checkout MacOS  (in the jasp-required-files)
And afterwards make a symbolic link to the Framworks, better than a copy
>ln -s ./jasp-required-files/Frameworks/  Frameworks

I think that you Frameworks folder at the moment is one level to deep

If this is on the case please update the jasp-required-files with the latest version.

Hope this will help you out.
Kind regards 
Frans Meerhoff

**Comment by performlabrit** [comment]
Frans, thanks for the feedback.  I can confirm that path pointer to rcpp.so does point to the correct location ( /Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp/libs/Rcpp.so ).

The frameworks folder is at the correct level, and I am using the most recent version of required files (downloaded yesterday)

Here are two screenshots showing the directory structure:
https://imgur.com/a/Jd5wMlI

**Comment by performlabrit** [comment]
No luck.  Here is my directory structure:

![Screen Shot 2019-06-12 at 11 46 28 AM](https://user-images.githubusercontent.com/8962011/59366404-46e24700-8d08-11e9-8ef2-e79522b11194.png)

I still get the same issues when building (see my original post).  Here's a demonstration that the rcpp.so file is in fact in the correct location:

![Screen Shot 2019-06-12 at 12 10 52 PM](https://user-images.githubusercontent.com/8962011/59367963-2e276080-8d0b-11e9-8942-3492d53fe564.png)

As a result, JASPgraphs cannot be lazy-loaded. At run-time, when trying to make a plot, I get the error that plots cannot be shown because JaspGraphs is not installed.

There are some (perhaps unrelated) issues with the instructions that you should probably be aware of, and that may explain things.

- Your screenshot in the build instructions shows that the /Resources/ folder (originally compiled to the build directory) should be moved to the same root level as the boost, jasp-desktop, frameworks etc. folders.  Is that the case?  It doesn't seem to make sense (or help) to move it.

- Of the files that I am supposed to add to my build directory manually (those in blue on the screenshot in your build instructions, step 3 for the mac), some are not included in the required files directory. 








https://imgur.com/a/R8OkQpX

**Comment by FransMeerhoff** [comment]
Hi @performlabrit 

Could you please install R version 3.5.2. that's the version our Frameworks is based on.
You can find it at: 
https://cran.r-project.org/bin/macosx/R-3.5.2.pkg

Kind regards
Frans Meerhoff

PS We will update the install info on github about this.

**Comment by performlabrit** [comment]
?This did solve the problem.  Thank you for your help, Frans!


________________________________

**Comment by AlexanderLyNL** [comment]
Thanks for the feedback!
