### ISSUE TITLE
Box plot diagrams are not showing full text on y axis

### ISSUE THREAD

**Issue by SterArcher** [jasp-stats/jasp-issues#376]
The y axis does not show full text.
* Enhancement: Make axis customizable.
* Purpose: Ability to export data to publish in journals etc. and show them in an appropriate manner.

![image](https://user-images.githubusercontent.com/29688990/59158892-7ce1ba00-8ac1-11e9-9606-912ea32926ec.png)

**Comment by FransMeerhoff** [comment]
Hi @SterArcher 

Your enhancement request is definitely understandable, but this can only be solved right now by 
reducing this very long variable name in your data. (B.T.W.  double clicking on the data panel will open your favorite spreadsheet editor to fix)
BUT, the good news, is that we are indeed busy with a more general solution to make plots editable.
In this way most plot parameters should not be fixed but changeable.
So your wish will be full-filled in some future release (hard to say which)

I close this issue for this moment.
Please check our website for new releases or reopen this issue if you have any more comment on this issue.

Kind regards
Frans Meerhoff
