### ISSUE TITLE
Petitesse: slow download

### ISSUE THREAD

**Issue by lindeloev** [jasp-stats/jasp-issues#377]
This is really in the miniature-importance User eXperience-category: JASP is slow to download; ~ 350 kb/s (not a limit on my broadband). A quick download would make it possible to get JASP up and running immediately for students and collaborators. And it feels sleeker with immediate gratification!

**Comment by EJWagenmakers** [comment]
Strange, it took 10 seconds for me to download, so that's about 25 MB/sec

**Comment by lindeloev** [comment]
Maybe it's a non-issue then. I had slow speeds at work and at home. Same is true of Jamovi, BTW, but not in general where I also see >10 MB/s usually.

**Comment by JorisGoosen** [comment]
It seems like sometimes our server has slower and faster days/times. I assume the host has some maximum on the bandwidth allowance per time-period or something like that that causes this. Or just general traffic.
