### ISSUE TITLE
Correction for d (classical t-tests)

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-issues#38]
From the forum -- we could look into this and when we like it we could offer it as an option or provide it in addition to the current d:
"I know your focus is more on the Bayesian analyses, but a brief comment on the classic t-tests: The Cohen's d reported in the output table for (classic) paired t-tests seems to be uncorrected for the correlation between observations. This can lead to overestimation of the effect size according to some authors (e.g., [1] ) Perhaps it would be good to mention that the d value is uncorrected?
[1] alternative formulae for example in Dunlap, W. P., Cortina, J. M., Vaslow, J. B., & Burke, M. J. (1996). Meta-analysis of experiments with matched groups or repeated measures designs. Psychological Methods, 1(2), 170."

**Comment by hcp4715** [comment]
I recently encountered this issue and posted my question in the forum: https://forum.cogsci.nl/discussion/3013/what-denominator-does-the-cohens-d-use-on-jasp

Assume that we calculate Cohen's d as suggested [here](https://janhove.github.io/analysis/2017/02/22/confidence-intervals-for-standardised-effect-sizes), i.e., use `effsize::cohen.d(..,  paired=T, ...)` to calculate Cohens'd and `MBESS::ci.smd()` to calculate the Confidence intervals, the Cohens' d is not corrected for the correlation between the pair of data, neither the confidence intervals.

**Comment by boutinb** [comment]
@JohnnyDoorn Can you have a look to this issue?

**Comment by JohnnyDoorn** [comment]
Yes, I commented on the issue - where I list how we calculate cohen's d for paired samples, and how we use MBESS to get the confidence interval. It would be nice to have include more types of effect sizes here - just like we did for the 2-sample t-test.

**Comment by tomtomme** [comment]
Same request of providing more effect size options for ANOVA post hoc tests here:
https://github.com/jasp-stats/jasp-issues/issues/1915
