### ISSUE TITLE
UI suggestions: a more native feel

### ISSUE THREAD

**Issue by lindeloev** [jasp-stats/jasp-issues#381]
JASP 0.10
Windows 10, 64-bit

The new JASP interface feels non-native in many ways. Here are some suggestions to make it feel more native to the OS. Sorry for putting all of this in a single issue. It's an attempt not to spam :-)

# Drop shadow
I find the drop-shadow over drop-down menus a bit confusing as it deviates from typical OS behavior. It’s as if the drop-down is not part of the button.
![image](https://user-images.githubusercontent.com/1439417/59331957-73409800-8cf5-11e9-884e-5715858070e6.png)

# Hover consistency
When you hover a menu item (e.g. “Descriptives”) it enlarges. Everywhere else in the UI (and in most OS'es in general), hover turns the background gray. Gray + no zoom would give that comforting consistent "native" feel.

# Data library "memory"
When you’ve selected something in “Data Library”  (e.g. “Regression”) and then go to Open  Data Library, that category is already selected. I would expect it to just go to the root of the data library every time I go there for a consistent experience.

# Clicking BAIN title
Clicking the category titles here (e.g., "T-tests") causes the menu to go disappear. The typical behavior is just to do nothing and let it stay.
![image](https://user-images.githubusercontent.com/1439417/59332327-3de87a00-8cf6-11e9-933b-1a75071f5ebe.png)

**Comment by EJWagenmakers** [comment]
Team, let's discuss each of these on Friday

**Comment by boutinb** [comment]
Drop shadow & Click titles in popup menu would be solved in 0.10.1
