### ISSUE TITLE
Minor bug

### ISSUE THREAD

**Issue by DrMarkGS** [jasp-stats/jasp-issues#382]
* JASP version: 0.10
* OS name and version: Windows & professional

* Bug description: JASP icon showing as a blank icon in the toolbar

* Screenshot: 
![jasp icon not showing](https://user-images.githubusercontent.com/39003008/59342144-1519b200-8d01-11e9-8f4e-9f214280fddd.PNG)

**Comment by JorisGoosen** [comment]
This remains after rebooting?

**Comment by DrMarkGS** [comment]
Will let you know

**Comment by DrMarkGS** [comment]
Fine now on restart

**Comment by AlexanderLyNL** [comment]
Please reopen if the issue reoccurs.
