### ISSUE TITLE
Another minor point

### ISSUE THREAD

**Issue by DrMarkGS** [jasp-stats/jasp-issues#383]
Just a small point
When performing the non-parametric RMANOVA the option to run the unspecified test( I assume Friedman) is accompanied with the appropriate post-hoc test (Conovers) in the same menu. However for a normal ANOVA, Kruskal-Wallace test does not have the same type of self-contained option - but requires the user to select Dunn test in the Post hoc tests menu. Perhaps it would be better to have all the non-parametric options in the same area.

**Comment by DrMarkGS** [comment]
To add to this it would be good to have non-parametric descriptives option to show median, MAD and IQRs
Cheers folks

**Comment by tomtomme** [comment]
Showing Median, MAD and IQR would be very cool for all non-parametric tests!

Also: ANOVAs Dunn's post hoc test is still in the "wrong" section in JASP 0.18.2 beta. Should be moved to the non-parametrics section for sure.

@DrMarkGS - Maybe rename this issue to "Add descriptives for non-parametric tests & move Dunns test to nonparametric section". Maybe this can help in upping the issue in priority :D
