### ISSUE TITLE
Between*Within interactions for mixed ANOVA

### ISSUE THREAD

**Issue by vicenteinefo** [jasp-stats/jasp-issues#384]
* Enhancement:
Post-hoc test for between*within interactions in mixed ANOVA

* Purpose:
Analyse between*within interactions in mixed ANOVA

* Use-case:
The 2x2 and 3x3 mixed ANOVA are common designs in Sports Sciences

Other post-hoc test for between-between or within-within interactions are already included

**Describe the solution you'd like**
 

Add this option in the post-hoc test menu as did with other interactions 

<img width="1440" alt="Captura de pantalla 2019-06-12 a las 13 00 44" src="https://user-images.githubusercontent.com/29978768/59347651-7c416180-8d15-11e9-99f9-448564f38bf8.png">

**Comment by JohnnyDoorn** [comment]
Hi Vicente,

Fair point, we'll look into implementing this!

Cheers,
Johnny

**Comment by vicenteinefo** [comment]
Thanks for the prompt response.

I hope the update does not take long, I was waiting for this new update (0.10) with great enthusiasm and now was a little disappointing.

You are doing a great job with this fantastic app

**Comment by JohnnyDoorn** [comment]
@boutinb fixed this issue - the next release will have mixed posthoc tests as well!
