### ISSUE TITLE
Incorrect degrees of freedom for Welch's independent t-test [JASP 0.10]

### ISSUE THREAD

**Issue by sinisalakic** [jasp-stats/jasp-issues#386]
First of all, very enthusiastic about the new version! Thanks for the hard work guys!

* JASP version: 0.10
* OS name and version: OSX 10.13.6 
* Analysis: Independent samples t-test
* Bug description: When computing Welch's t-test if one selects _Confidence interval_ for standardized _Effect size_ one doesn't get the corrected number of degrees of freedom (when subsamples differ in size and variability), but copied dfs from the regular Student's test 😮 .

![uncorrectedDFs](https://user-images.githubusercontent.com/42962473/59450508-a7a57880-8e09-11e9-9579-a020ed0994ab.png)

Without selecting CIs, one obtains the corrected values which should be the case.

![correctedDFs](https://user-images.githubusercontent.com/42962473/59450579-cb68be80-8e09-11e9-88ba-5af4b6cd8eb8.png)

**Comment by sinisasub** [comment]
I can verify that the same exact issue exists on the Windows version. It appears to be a new bug, I tested it on 0.9.1.0 and it works fine there. A minor bug, but something to be addressed nevertheless. Keep up the good work guys!

**Comment by AlexanderLyNL** [comment]
Thank you both for figuring this out! We'll fix this.

**Comment by JohnnyDoorn** [comment]
Thanks for reporting, I fixed it and it will be in the next release.

**Comment by AlexanderLyNL** [comment]
I did this (on my own branch) by removing the following line:

https://github.com/jasp-stats/jasp-desktop/blob/e5649a374b7753d56930b82bd007ec0d55757262/JASP-Engine/JASP/R/ttestindependentsamples.R#L351

**Comment by JohnnyDoorn** [comment]
Yes, let's discuss this in person (because what you did implies something
different from what I did)
