### ISSUE TITLE
Incomplete labeling of outliers

### ISSUE THREAD

**Issue by karenzagorski** [jasp-stats/jasp-issues#387]
* JASP version: 0.10
* OS name and version:Windows, Version	10.0.17134 Build 17134
* Analysis: Side-by-Side boxplots with labeled outliers
* Bug description: Some outliers don't get labels
* Add JASP files as a zip:[bug report.zip](https://github.com/jasp-stats/jasp-issues/files/3294324/bug.report.zip)1
* Screenshot: ![1](https://user-images.githubusercontent.com/51867699/59566960-aef89c00-902c-11e9-9b5e-aa6286170eeb.png)
* Expected behaviour: All outliers should have a label
* Steps to reproduce: 
1. Descriptive statistics. Lifespan(variables) vs exposure(split)
2. Plot as box plot. Check label outliers
3. Groups 2 4 and 5 have unlabeled outliers, group 1 is labeled properly

**Comment by TimKDJ** [comment]
@AlexanderLyNL in your PR jasp-stats/jasp-desktop#3320 you changed the quantile algorithm type from 7 (R standard) to 6 (SPSS standard). This gives different quantiles. ggplot does not allow you to set the quantile type and by default uses type 7. I also noticed we use `quantile()` in other analyses and do not use type 6.

I think the only way to change the ggplot is to completely overwrite the boxplot element and add our own outlier dots. Should we really perform this switch from 7 to 6?

**Comment by EJWagenmakers** [comment]
I have a strong preference for whatever R uses over whatever SPSS uses...

**Comment by AlexanderLyNL** [comment]
Sure we can change everything from 6 to 7. Would you like to do this? Or should I?

**Comment by TimKDJ** [comment]
Yeah I can do it -- I was just wondering what the best course of action was

**Comment by AlexanderLyNL** [comment]
I thought that it would be good to have the output consistent with SPSS, but that doesn't seem to be the case, so let's follow the R default instead.
