### ISSUE TITLE
Error in multigroup SEM

### ISSUE THREAD

**Issue by meskisu** [jasp-stats/jasp-issues#388]
* JASP version: 0.10
* OS name and version: Windows 10
* Analysis: Structural Equation Modeling 
* Bug description: I want to perform SEM analysis in JASP and everything is OK. But I could not perform multigroup SEM analysis. When I defined my "gender" variable as grouping variable and then chose "loadings" from equality constraints, I had an bug report saying that 
"This analysis terminated unexpectedly.
Error in xy.coords(x, y, xlabel, ylabel, log): 'x' is a list, but does not have components 'x' and 'y'
Stack trace
analysis(dataset = dataset, options = options, perform = perform, callback = the.callback, state = oldState)
.writeImage(width = pathDiagram$width, height = pathDiagram$height, plot = p, obj = TRUE)
plot(plot)
plot.default(plot)
xy.coords(x, y, xlabel, ylabel, log)
stop(''x' is a list, but does not have components 'x' and 'y'')"

**Comment by TimKDJ** [comment]
Can you attach the .jasp file in which this error occurs so I can take a look?
If you'd rather not share it publicly then emailing to t.dejong [at] jasp-stats.org works too

**Comment by TimKDJ** [comment]
I just pushed a fix for this problem. Thanks for reporting it to us!
