### ISSUE TITLE
JASP just closes

### ISSUE THREAD

**Issue by TexasGent777** [jasp-stats/jasp-issues#391]
* JASP version: 0.9.2
* OS name and version: Windows 10
* Bug description: JASP just crashes/closes when I try to open files. As soon as I press Open>Computer>Browse, once the window comes up, the app just completely closes. No error message or anything. Just a clean, complete shutdown. It happens within seconds. I've used the pre-installed and downloaded versions of JASP 0.9.2.
* Add JASP files as a zip:
* Screenshot: 
* Expected behaviour: I would like to be able to browse my computer so I could open files. 
* Steps to reproduce: 
1. Open JASP (I've tried both normally and as an admin, doesn't make a difference)
2. Click on "File"
3. Click on "Open"
4. Click on "Computer"
5. Click on "Browse"
6. Watch Browse window pop up
7. Mouse gains "hourglass" for about 1-2 seconds
8. JASP completely closes

**Comment by TexasGent777** [comment]
Addendum:

Uninstalled and downloaded 0.10.0.

Same exact problem.

**Comment by boutinb** [comment]
Can you set log option (Preferences/Advanced/Logging options) and send us the log file after JASP crashes?

**Comment by TexasGent777** [comment]
[JASP 2019-06-20 09_41_05 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/3310896/JASP.2019-06-20.09_41_05.Engine.0.log)
[JASP 2019-06-20 09_41_05 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/3310897/JASP.2019-06-20.09_41_05.Engine.1.log)
[JASP 2019-06-20 09_41_05 Engine 2.log](https://github.com/jasp-stats/jasp-issues/files/3310898/JASP.2019-06-20.09_41_05.Engine.2.log)
[JASP 2019-06-20 09_41_05 Engine 3.log](https://github.com/jasp-stats/jasp-issues/files/3310899/JASP.2019-06-20.09_41_05.Engine.3.log)
[JASP 2019-06-20 09_41_05 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/3310900/JASP.2019-06-20.09_41_05.Desktop.log)

Looks like it made 5 log files for just the 30 seconds I had the app open

**Comment by JorisGoosen** [comment]
Yeah, we run 5 separate processes (4 with R and 1 with the user interface) and it is useful to see what happens where.

**Comment by JorisGoosen** [comment]
It seems that the engine crashes as soon as it tries to send a message back to the user interface.

Could you try starting JASP as admin and could you check if you have enough space left on your C: drive?

**Comment by TexasGent777** [comment]
[JASP 2019-06-23 13_21_53 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/3318387/JASP.2019-06-23.13_21_53.Engine.0.log)
[JASP 2019-06-23 13_21_53 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/3318388/JASP.2019-06-23.13_21_53.Engine.1.log)
[JASP 2019-06-23 13_21_53 Engine 2.log](https://github.com/jasp-stats/jasp-issues/files/3318389/JASP.2019-06-23.13_21_53.Engine.2.log)
[JASP 2019-06-23 13_21_53 Engine 3.log](https://github.com/jasp-stats/jasp-issues/files/3318390/JASP.2019-06-23.13_21_53.Engine.3.log)
[JASP 2019-06-23 13_21_53 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/3318391/JASP.2019-06-23.13_21_53.Desktop.log)

This is with me running it as an admin. Also, I have 320gb of free space on my C: drive

**Comment by thesaw123** [comment]
I am having this same problem.  Any solutions yet?

**Comment by JorisGoosen** [comment]
I'm thinking that to figure out what goes wrong here JASP needs to log something more. The upcoming release of this week can include some more diagnostic logging. Because right now I am at a loss as to what goes wrong.

**Comment by DmitryPrigodich** [comment]
Same with me: Ubuntu 19.04, installed from flatpak, as PPA were not working.
Launching from console gives such info:
```
Gtk-Message: 22:37:03.933: Failed to load module "canberra-gtk-module"
Gtk-Message: 22:37:03.933: Failed to load module "canberra-gtk-module"
QGLXContext: Failed to create dummy context
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
qrc:/components/JASP/Widgets/ComputeColumnWindow.qml:330:2: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/ComputeColumnWindow.qml:330:2: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:362:4: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:362:4: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:112:4: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:112:4: QML Dialog: Binding loop detected for property "implicitWidth"
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 
```
And some more added:
```
R_HOME: /app/lib64/R/
R_HOME: /app/lib64/R/
```

**Comment by DmitryPrigodich** [comment]
@JorisGoosen Well, launching after update shows this and tries to show me the window but fails.
`
flatpak run org.jaspstats.JASP

Gtk-Message: 21:36:08.566: Failed to load module "canberra-gtk-module"
Gtk-Message: 21:36:08.566: Failed to load module "canberra-gtk-module"
QGLXContext: Failed to create dummy context
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
qrc:/components/JASP/Widgets/ComputeColumnWindow.qml:330:2: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/ComputeColumnWindow.qml:330:2: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:362:4: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:362:4: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:112:4: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:112:4: QML Dialog: Binding loop detected for property "implicitWidth"
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 

R_HOME: /app/lib64/R/
R_HOME: /app/lib64/R/
R_HOME: /app/lib64/R/
R_HOME: /app/lib64/R/
`

Same with safe graphics:
`
flatpak run org.jaspstats.JASP --safeGraphics
Gtk-Message: 21:39:07.806: Failed to load module "canberra-gtk-module"
Gtk-Message: 21:39:07.806: Failed to load module "canberra-gtk-module"
QGLXContext: Failed to create dummy context
qrc:/components/JASP/Widgets/ComputeColumnWindow.qml:330:2: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/ComputeColumnWindow.qml:330:2: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:362:4: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:362:4: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:112:4: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:112:4: QML Dialog: Binding loop detected for property "implicitWidth"
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 

R_HOME: /app/lib64/R/
R_HOME: /app/lib64/R/
R_HOME: /app/lib64/R/
R_HOME: /app/lib64/R/
`

**Comment by JorisGoosen** [comment]
@DmitryPrigodich it is probably easier if we continue this in issue #348.

@TexasGent777 or @thesaw123 could either of you try to run the new 0.10.2 version and send us the logfiles (if the problem persists of course)?
