### ISSUE TITLE
SPSS data file won't upload in JASP

### ISSUE THREAD

**Issue by Amysbell123** [jasp-stats/jasp-issues#392]
This is the error message i got:

'Unable to open file.
Unknown record type ' ' found.
The SAV importer cannot yet read this file.
Please report this error at 
https://github.com/jasp-stats/jasp-desktop/issues
including a small sample .SAV file that produces this message.'

I can not upload the SPSS file in this message either unfortunately. I have send my data file to the e-mail from the JASP website. Maybe someone can help me from there?

I used the latest version of JASP and I tried it also on someone else his computer, so I think there is something wrong with my data file, but I don't know what it is.

I hope some of you can help me!

**Comment by JorisGoosen** [comment]
We are planning on doing a rewrite of the code we use to read "foreign" data-formats, like spps's, this however will not be done even for the next release.

What you could try in the meantime is to export your data from SPSS as a "csv" file. That should import into JASP without trouble.
