### ISSUE TITLE
SEM module doesn't recognize intercepts

### ISSUE THREAD

**Issue by MaksimRudnev** [jasp-stats/jasp-issues#394]
* JASP version: 0.10
* OS name and version: macOS
* Analysis: SEM
* Bug description: adding intercept statements like `x ~ 1` throws error and doesn't affect results

* Steps to reproduce: 
The .jasp file included as an example of SEM. Turn on "Include mean structure" option. Add constraint of intercept (blue). It breaks (red).

<img width="613" alt="bug" src="https://user-images.githubusercontent.com/29795088/59888108-00eb4a00-93be-11e9-8b5a-de29dab5f53e.png">

**Comment by TimKDJ** [comment]
I pushed a fix for this; thanks for letting us know
