### ISSUE TITLE
Bayesian RM ANOVA crash

### ISSUE THREAD

**Issue by JohnnyDoorn** [jasp-stats/jasp-issues#398]
* JASP version: 0.10
* OS name and version: Manjaro
* Analysis: Bayesian RM ANOVA
* Bug description: 
load bugs data -> select any grouping variable -> crash:
jasp: /usr/include/boost/signals2/detail/lwm_pthreads.hpp:60: void boost::signals2::mutex::lock(): Assertion `pthread_mutex_lock(&m_) == 0' failed.
17:41:32: The program has unexpectedly finished.

**Comment by JorisGoosen** [comment]
This is in the development version right?
Can you check if the latest version has this problem? I think I fixed it.
