### ISSUE TITLE
Installation for Ubuntu 18.10 Cosmic

### ISSUE THREAD

**Issue by JueGoWinDo** [jasp-stats/jasp-issues#399]
Hello,
Would you make the installation for Ubuntu 18.10 Cosmic? 
Thanks!

**Comment by JorisGoosen** [comment]
Hello,

Have you tried installing the flatpak-version of JASP? This should work on Ubuntu 18.10 as well.

**Comment by JueGoWinDo** [comment]
Hello,

Yes, but

Err:22 http://ppa.launchpad.net/jasp-uva/jasp/ubuntu cosmic Release                                     
  404  Not Found [IP: 91.189.95.83 80]
Err:23 http://ppa.launchpad.net/marutter/c2d4u3.5/ubuntu cosmic Release                                        
  404  Not Found [IP: 91.189.95.83 80]

It would seem that the files for Cosmic are missing.

**Comment by JorisGoosen** [comment]
Well, the PPA is not the same as flatpak. PPA relies on files in Ubuntu and the ones we need are outdated.

Perhaps you could make sure you have flatpak installed [flatpak on ubuntu](https://flatpak.org/setup/Ubuntu/) and then follow the flatpak install-instructions of JASP, which are basically opening a terminal and running `flatpak install http://static.jasp-stats.org/flatpak/JASP.flatpakref`.

After that you can start jasp by running `flatpak run org.jasp.JASP` or you can use the installed shortcut/icon in your applications folder. Although I have heard that some people have trouble with that last one on Ubuntu. If that is the case we can help you further of course.

**Comment by JueGoWinDo** [comment]
Hi JorisGoosen
I have followed your directions, but see below

Version 1 (without final dot)
flatpak install http://static.jasp-stats.org/flatpak/JASP.flatpakref
error: No such ref 'app/org.jasp.JASP/i386/master' in remote jasp-origin

Version 2 (with final dot)
flatpak install http://static.jasp-stats.org/flatpak/JASP.flatpakref.
Looking for matches…
error: No remote refs found similar to ‘http://static.jasp-stats.org/flatpak/JASP.flatpakref.’

**Comment by JorisGoosen** [comment]
Aah, you are running 32bit... We haven't distributed that for linux because I was kind of expecting that nobody used it anymore.

We are planning to do a new release next week. I can make sure that we also supply a 32bit version then.

**Comment by JueGoWinDo** [comment]
Hi JorisGoosen
Thank you very much!

**Comment by JorisGoosen** [comment]
@JueGoWinDo I'm uploading the new version of JASP now, including a 32bit build. maybe you can try it out by calling `flatpak update && flatpak install org.jaspstats.JASP` ?
