### ISSUE TITLE
Factor/Component Score saving & Bayesian PCA/FA

### ISSUE THREAD

**Issue by abnormally-distributed** [jasp-stats/jasp-issues#40]
Would it be possible to get factor scores saved for principal component and factor analyses? 

It would also be pretty interesting to see a Bayesian version of PCA or FA. I've tried figuring out some of the packages in R about Bayesian PCA, and while I am pretty decent with R, the packages available were a bit difficult to use.

**Comment by juliuspfadt** [comment]
although this issue was earlier, we should track the progress here: https://github.com/jasp-stats/jasp-issues/issues/101

**Comment by tomtomme** [comment]
@juliuspfadt 
Shouldn't we close duplicates?
