### ISSUE TITLE
Repeated measures factorial ANOVA misreading data in JASP 0.10 on MacOS

### ISSUE THREAD

**Issue by RW22** [jasp-stats/jasp-issues#400]
* JASP version: 0.10
* OS name and version: MacOS 10.14.5
* Analysis: Repeated measures factorial ANOVA
* Bug description: When clicking on the triangle to 'move' the data to the repeated measures cells, the data are ordered incorrectly (new bug: was working fine in JASP 0.9.2)
* Add JASP files as a zip:
* Screenshot: First screenshot shows a 2 x 6 repeated measures ANOVA with factor A having 2 levels and factor P having 6 levels. In 'Repeated Measures Cells', the names are lined up as expected, i.e., A1P1, A1P2, A1P3, ... , A2P1, ... A2P6. The data are lined up such that P1 (which is A1P1) is followed by P2 (which is A1P2), and so on. The orders match.
* Screenshot: Second screenshot shows what happens after clicking on the triangle to copy. P1 was correctly placed next to A1P1; P2 was correctly placed next to A1P2; but suddently, N5 is placed next to A1P3. This should be P3. N6 is placed next to A1P4; this should be P4. Then, we're back to P3 but it is next to A1P5.
* Expected behaviour: Copying over the info to the repeated measures cells should not change the order. JASP 0.9.2 does this correctly.
[files.zip](https://github.com/jasp-stats/jasp-issues/files/3320998/files.zip)

* Steps to reproduce: 
1. Open attached file 'bug1-2x6.txt' in JASP 0.10 and JASP 0.9.2
2. Set first repeated measures factor to A, with levels A1 and A2
3. Set second repeated measures factor to P, with levels P1 through P6
4. Click on triangle to copy data. Data are now mismatched with cells.

**Comment by boutinb** [comment]
Fix in 0.10.1

**Comment by RW22** [comment]
Wow, that was fast. Thanks!

JASP is an excellent application and I very much appreciate the work you
and all the others put into it.
