### ISSUE TITLE
Implement a Bayesian equivalent for multinomial or chi square goodness of fit

### ISSUE THREAD

**Issue by ibecav** [jasp-stats/jasp-issues#401]
* Enhancement:  The frequencies tab already supports frequentists methods.  And you have a great article here https://jasp-stats.org/2018/03/06/conduct-multinomial-test-chi-square-test-jasp/ on using them.  It would be nice to have a Bayesian equivalent like the one you support for Bayesian contingency tables.

* Purpose:  To continue to support Bayesian methods alongside frequentist

* Use-case:  Same use cases as https://jasp-stats.org/2018/03/06/conduct-multinomial-test-chi-square-test-jasp/

**Describe the solution you'd like**
Add a sub menu item as you have for chi squared independence tests

**Comment by AlexanderLyNL** [comment]
Hi Chuck, 

Thanks for the request. We just added this analysis in our newest release, version 0.10, which you can find here

https://jasp-stats.org/download/

I'll close this for now. Please reopen if something else is unclear. 

Cheers,
Alexander

**Comment by ibecav** [comment]
Thank you!
