### ISSUE TITLE
Jasp crashes, and causes my system to crash.  I have uninstalled and reinstalled but is does not function

### ISSUE THREAD

**Issue by thesaw123** [jasp-stats/jasp-issues#402]
* JASP version:
* OS name and version:
* Analysis:
* Bug description:
* Add JASP files as a zip:
* Screenshot: 
* Expected behaviour:
* Steps to reproduce:

**Comment by JorisGoosen** [comment]
Duplicate of https://github.com/jasp-stats/jasp-issues/issues/391

**Comment by JorisGoosen** [comment]
And if it is not, then please flesh out this issue to give a fuller description of the problem.
