### ISSUE TITLE
Repeated Contrasts

### ISSUE THREAD

**Issue by oildrop** [jasp-stats/jasp-issues#404]
* JASP version: 0.10
* OS name and version: Mac Mojave
* Analysis: Repeated Contrast of RM Data
* Bug description:

Hello, I'm not sure if this is a bug or a decision intentionally made, but when I run a RM ANOVA and then choose Repeated Contrast, the output seems to Pool the Error Term.

For instance, in SPSS, using the attached file, if I treat each column as a separate level and then run a Repeated Contrast the resulting p-value between V1 and V2 is 0.236. I also get p=0.236 if I run a paired sample t-test between V1 and V2.

However in Jasp, a Repeated Contrast gives me a value of 0.184 while a paired t-test gives me a value of 0.236.

If I then check the "Pool Error Term from RM Factors" under the Post Hoc tab in Jasp, I can reproduce the 0.184 p-value (if I run a Bonferroni I get p=0.552 which when divided by 3 is 0.184). If I untick this box, I get a Bonferroni p-value of 0.708 (which divided by 3 is 0.236). 

So it looks like in Jasp when a Repeated Contrast is run on Repeated Measure data, it defaults to Pooling the Error Term.  If so, is this what it is meant to do?

Many thanks for your help.

[testDataRM.txt](https://github.com/jasp-stats/jasp-issues/files/3345398/testDataRM.txt)

**Comment by TimKDJ** [comment]
@JohnnyDoorn?

**Comment by JohnnyDoorn** [comment]
Hi @oildrop,

Yes, adding the option to (un)pool the error term for RM ANOVA contrasts is still on my todo list. I will get to this during the rewrite process.

Cheers,
Johnny

**Comment by JohnnyDoorn** [comment]
This is now in the RM ANOVA development - the next release will have the option to unpool the error term.

Kind regards,
Johnny
