### ISSUE TITLE
Solved: Font book -> File -> Restore standard fonts. Repeated measures ANOVA with covariate: Descriptive plots error

### ISSUE THREAD

**Issue by LillianEmilieMeryl** [jasp-stats/jasp-issues#405]
* JASP version: 1.0.1
* OS name and version: Mac Moave, 10.14.5
* Analysis: terminated unexpectedly. 
* Bug description: When I run a repeated measures anova with covariate JASP does not show me the descriptive plot. It was no problem in the previous version with the same steps/same file. Here is the error mesage:

lapply(vps, push.vp, recording)

FUN(X[[i]], ...)

push.vp.vpTree(X[[i]], ...)

push.vp(vp$parent, recording)

push.vp.viewport(vp$parent, recording)

grid.Call.graphics(C_setviewport, vp, TRUE)

(function (x) 
{
    widthDetails(x)
})(list(label = 'Training', x = 0.5, y = 0.5, just = 'centre', hjust = 0.5, vjust = 0.5, rot = 0, check.overlap = FALSE, name = 'GRID.text.132', gp = list(fontsize = 17, col = 'black', fontfamily = '', lineheight = 0.9, font = c(plain = 1)), vp = NULL))

widthDetails(x)

widthDetails.text(x)

grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, resolveHJust(x$just, x$hjust), resolveVJust(x$just, x$vjust), x$rot, 0)

Thank you for any advise!

* Add JASP files as a zip:
[Processed_dataX.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/3345801/Processed_dataX.jasp.zip)

* Screenshot: ![Screenshot 2019-07-01 at 15 35 42](https://user-images.githubusercontent.com/52414478/60440852-ff1f5300-9c15-11e9-97e3-1c70ec23e3e7.png)
* Expected behaviour: 
* Steps to reproduce:

**Comment by TimKDJ** [comment]
Usually this problem occurs when there is something wrong with the fonts in your font book.
Can you try the following to see if that fixes your problem:

Open `Font Book` -> `File` -> `Restore standard Fonts`

**Comment by LillianEmilieMeryl** [comment]
Thank you so much! I enables the Arial family and now it works perfectly again!!!
All the best
Lillian

**Comment by AlexanderLyNL** [comment]
Thanks for letting us know that it got fixed!
