### ISSUE TITLE
JASP 0.10: Network analysis layout no longer fixable by data. 

### ISSUE THREAD

**Issue by markcrookrumsey** [jasp-stats/jasp-issues#406]
* JASP version: 0.10
* OS name and version: Windows 10 Enterprise
* Analysis: Network Analysis
* Bug description:

JASP 0.9 allowed the ability to fixed nodes to a certain position when performing network analysis. However, although 'data' button is still there under graphical options -> Layout, there is no way of putting the x & y positions in. 

![image](https://user-images.githubusercontent.com/33759352/60470381-5e33a500-9cb4-11e9-95da-a7b22b892f54.png)

* data:

[data.zip](https://github.com/jasp-stats/jasp-issues/files/3347545/data.zip)

Thank you for fixing the network analysis crash bug.

**Comment by TimKDJ** [comment]
@vandenman was this changed?

**Comment by vandenman** [comment]
@TimKDJ I think the rewrite to qml messed up the input for a data based layout, see the attached screenshot of jasp 0.10.0 (left) and jasp 0.9.1 (right).

![afbeelding](https://user-images.githubusercontent.com/21319932/60494864-94b6f300-9ca7-11e9-9fce-7948c0b9a34d.png)

**Comment by TimKDJ** [comment]
Eh. Yeah. There's a bit missing there.
I can add it again

**Comment by TimKDJ** [comment]
We also no longer have parallel bootstrapping; is this by design?

**Comment by TimKDJ** [comment]
@markcrookrumsey in the next release of JASP this feature will be available again. We recently did a big rework of the analysis input forms and this one slipped through the cracks. Thanks for notifying us!
