### ISSUE TITLE
Cyrillic Text messed up in MatrixPlot axis

### ISSUE THREAD

**Issue by JorisGoosen** [jasp-stats/jasp-issues#407]
In the current release candidate for 0.10.1.0 and probably 0.10.0.0 as well there is a problem in the Correlation Plot of Descriptives when Cyrillic (and probably other non-ascii chars) are used in the names.
Other plots have no problem.

See: ![CyrillicMessesUpMatrixPlot](https://user-images.githubusercontent.com/29062713/60522455-4d515680-9ce9-11e9-9ee4-74bcc874ffba.png)

To test this: [CyrillicJaspFile.zip](https://github.com/jasp-stats/jasp-issues/files/3350664/CyrillicJaspFile.zip)

**Comment by JorisGoosen** [comment]
As noted in https://github.com/jasp-stats/jasp-issues/issues/66#issuecomment-508002310:
The background of the subplots stays white, might be nice to fix that as well when you are at it.

See:
<img width="886" alt="Schermafbeelding 2019-07-03 om 10 46 37" src="https://user-images.githubusercontent.com/29062713/60577609-f0ed4600-9d7f-11e9-88f7-c720218af41c.png">

**Comment by boutinb** [comment]
Solved on 0.10.1 (next week)
