### ISSUE TITLE
Results panel empty using JASP 0.10 on MacOS Mojave

### ISSUE THREAD

**Issue by jwrschultz** [jasp-stats/jasp-issues#408]
Hello,

I am having the identical problem as posted in issue #390 (same MacOS and JASP version; Results panel empty, but results appear when exported). I guess this is simply a display problem on Mac. I understand that it is hard to understand where the problem comes from if you cannot replicate it. Please let me know if I can do anything to help you figure out how it occurs. I will revert to using JASP 0.9.2 meanwhile.

Best wishes and thanks for the fantastically useful software!
Johannes

Johannes Schultz, PhD
Center for Economics and Neuroscience and
Institute for Experimental Epileptology and Cognition Research
University of Bonn
Nachtigallenweg 86
53127 Bonn
Email: johannes.schultz@ukbonn.de
Tel./phone: +49 228 73 8282

**Comment by JorisGoosen** [comment]
Hey thanks for posting this here, I will just reopen the original issue then. To keep all info together.
