### ISSUE TITLE
Missing labels in JASP file crash on load

### ISSUE THREAD

**Issue by JorisGoosen** [jasp-stats/jasp-issues#409]
If you try to load a JASP file that misses the labels for some of the values in the data the application crashes hard.

This is bad, so I suggest that instead of crashing hard it should log the fact that it couldn't find it and then simply show missing-value, aka nothing.

Or maybe it is better to simply show the value as Label in that case?

What do @boutinb @AlexanderLyNL @TimKDJ think?

**Comment by TimKDJ** [comment]
I think showing the value as label makes sense. (I'm assuming otherwise the value is treated as missing entirely?)

**Comment by JorisGoosen** [comment]
Yeah the value isn't accessible anymore...

It's better to just show the value as Label, but I'll have to see how that fits into the file-loading.

**Comment by smathot** [comment]
Thanks for picking up on this so quickly! @JorisGoosen sent me a fixed version of the `.jasp` file that triggered this issue initially. And yes, that fixed version does open as you'd expect.

**Comment by JorisGoosen** [comment]
And in this file, I noticed that for instance in the column the first rows of "education" are all 0, was that originally the case?

**Comment by smathot** [comment]
No, the data is garbled actually. There seem to be 0 values that are pushing the real values down, if that makes sense.

**Comment by JorisGoosen** [comment]
That makes sense, and is not that good.

So, in what version of JASP did you make this file? And can you still open it in that version?

**Comment by smathot** [comment]
I think I made it in 0.9.2 also installed through flatpak. Do you know how I can downgrade to that version?

**Comment by JorisGoosen** [comment]
See https://github.com/flatpak/flatpak/wiki/Tips-&-Tricks#downgrading

**Comment by JorisGoosen** [comment]
I have also sent you a pm on cogsci with a new resaved version of your data. the education column should now be fine. I wonder though what was originally on the first 7 columns of distracted and what on the rest.

**Comment by smathot** [comment]
The data is still garbled. I sent you the `.csv` so you can see what it should look like. I'm not sure it's worth getting to the bottom of this though; who knows what garbled this? That doesn't necessarily need to have been JASP. As long as JASP deals more gracefully with these types of situations, then that seems like a good solution to me already.
