### ISSUE TITLE
Sorting of Included Variables in EFA table

### ISSUE THREAD

**Issue by stjep** [jasp-stats/jasp-issues#41]
Not sure if this is the intended behavior, but the sorting of the Included Variables in the EFA Factor Loadings table is not ideal. It's neither numerical, nor faithful to the original data file. Screenshot is attached where the included variables are named Q1-Q141. The first three variables in the output are Q1, Q10, and Q100, instead of Q1, Q2, Q3.

![screenshot 2017-03-10 10 19 34](https://cloud.githubusercontent.com/assets/3305421/23800701/604459d4-057b-11e7-8fa2-10f8640ad135.png)

**Comment by vankesteren** [comment]
@JorisGoosen this is the readdataset issue to be solved in the cpp part

**Comment by JorisGoosen** [comment]
Fixed

**Comment by jdebeer2005** [comment]
I have same issue -contingency table.

[cont table.docx](https://github.com/jasp-stats/jasp-issues/files/4590622/cont.table.docx)

**Comment by JorisGoosen** [comment]
@jdebeer2005 could you perhaps make a new issue for your problem? It would be good to link to this issue in there.

That way we can keep better track of what issues we found when.
