### ISSUE TITLE
PCA - correlation or covariance matrix 

### ISSUE THREAD

**Issue by BehrensF** [jasp-stats/jasp-issues#412]
Hi, 
I am currently trying to run a PCA in JASP. I am new to this method, but from what I have read, you can normally choose between basing your analysis on a correlation or covariance matrix. I do not see this option in JASP or can find any information about which method JASP is using as a default. Do you have any information on that?

Best, 
Friederike

**Comment by vankesteren** [comment]
JASP uses the correlation matrix! Would you want to have the option to base your analysis on the covariance matrix? We might be able to implement that soon :)

**Comment by BehrensF** [comment]
Thanks! 
Yes, that would be fantastic if the option could be implemented :)

**Comment by vankesteren** [comment]
We use the `principal` function of the `psych` package. You can find more information [here](https://www.rdocumentation.org/packages/psych/versions/1.8.12/topics/principal#l_details)
