### ISSUE TITLE
Contradictory results for the paired and one sample test 

### ISSUE THREAD

**Issue by NikitaKhromov-Borisov** [jasp-stats/jasp-issues#413]
* JASP version: 0.9.2
* OS name and version: Win 10
* Analysis: Paired sample t-test (PST) and One sample test (OST)
* Bug description: PST gives contradictory results. For the Wilcoxon test ES = -0.03 with  95% CI from -0.27 to 0.21 with p = 0.0007, but for t-test ES = 0.35 with 95% CI from 0.13 to 0.57 and p = 0.002.
At the same time, OST for the same data expressed as paired differences for the Wilcoxon tets ES = -0.65 with 95% CI from -0.77 to -0.49 and the same p = 0.0007
* Add JASP files as a zip: 
[TS.ZIP](https://github.com/jasp-stats/jasp-issues/files/3369752/TS.ZIP)
* Screenshot: 
* Expected behaviour:
* Steps to reproduce:

**Comment by JohnnyDoorn** [comment]
The effect sizes ignored the ties in your data, so that's why the results are not symmetric. Your effect size for Wilcoxon should have been 0.4727195. I updated the calculations and it should be correct in the next version!
