### ISSUE TITLE
Some analysis broke

### ISSUE THREAD

**Issue by JPAXG** [jasp-stats/jasp-issues#414]
This analysis terminated unexpectedly.

Error in ggplot2::theme(panel.grid.minor = ggplot2::element_blank(), plot.title = ggplot2::element_text(size = 18), : argument formel 'axis.line' correspondant à plusieurs arguments fournis

Stack trace
analysis(dataset = NULL, options = options, perform = perform, callback = the.callback)

.screePlot(dataset, options, perform)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

**Comment by JorisGoosen** [comment]
Hello @JAPXG 

Did you read the template for this bug report?

Maybe you could give us some information on what you are trying to do.

Like, which analysis, what data you are using, which version of JASP etcetera.
