### ISSUE TITLE
JASPEngine.exe - System error

### ISSUE THREAD

**Issue by MAgojam** [jasp-stats/jasp-issues#415]
* JASP version: 0.10.1.0 (32 bit)
* OS name and version: win10 pro (ITA - 32 bit)
* Screenshot: 
![ScreenShot](https://user-images.githubusercontent.com/36552289/60972579-d50d1580-a326-11e9-838e-9a1969542658.png)

Hi, @JorisGoosen.
Some of my students, who use Lenovo L530 (32 bit) laptops with Win10 pro (ITA) have installed jasp from: [http://static.jasp-stats.org/Nightlies/Windows32/JASP-nightly-development-43126467ffbc847a99c698f87cf272052374708c.msi](url)
without problems, but at the launch of jasp the error appears, "The execution of the code cannot continue because R.ddl was not found." ,
as you can see in the attached screenshot.

Can you help?

Thanks and best regards.
Maurizio

**Comment by JorisGoosen** [comment]
Hello Maurizio,

I will take a look tomorrow, I have an idea what went wrong.

**Comment by MAgojam** [comment]
Hi, @JorisGoosen.
Now works!

Thank you very much for your attention and quick intervention to resolve the reported problem.
My students also thank you, because they are happy to be able to use their 32-bit PCs, with an updated and increasingly attractive jasp.

Cheers,
Maurizio

**Comment by JorisGoosen** [comment]
Thank you very much for the kind words!
