### ISSUE TITLE
Descriptives with Nominal Text bug in Correlation Plot

### ISSUE THREAD

**Issue by JorisGoosen** [jasp-stats/jasp-issues#416]
The title says it all, [bluh.csv](https://github.com/jasp-stats/jasp-issues/files/3385968/bluh.csv.zip) was used and results in:
![problemDescriptives](https://user-images.githubusercontent.com/29062713/61120220-be88ca80-a49c-11e9-9045-6a233a21c474.png)

@vandenman you just looked at this plot right? Maybe you have a quick fix?
Or @TimKDJ?

Not sure if this is important enough to hold up the release any longer.

**Comment by TimKDJ** [comment]
It works fine for me on freshly rebased debug version.
Can you reproduce this @vandenman?

**Comment by JorisGoosen** [comment]
Aaaaah!

I am running R 3.6.0 here. So that is the problem then.

**Comment by AlexanderLyNL** [comment]
Any idea why it breaks down with R 3.6.0 and not with 3.5.2? This might be valuable information for once we upgrade to R 3.6.1

https://www.r-bloggers.com/r-3-6-1-is-now-available/

**Comment by TimKDJ** [comment]
They deprecated calling `var()` on a factor. We'll have to avoid doing that when we move to 3.6.0.
They are already warning for this behaviour in 3.5.2:
```
Warning message:
In var(z) :
  Calling var(x) on a factor x is deprecated and will become an error.
  Use something like 'all(duplicated(x)[-1L])' to test for a constant vector.
```

**Comment by JorisGoosen** [comment]
This should crop up in the unit-test when we switch R versions then so it will be hard to avoid.

**Comment by vandenman** [comment]
I could reproduce it (because I was running R 3.6.0 on Ubuntu). I only have a quick and dirty fix because more appropriate solutions would require me to rewrite large parts of descriptives.
