### ISSUE TITLE
Switching data type from scale to ordinal or nominal sets data in column/variable to zero

### ISSUE THREAD

**Issue by p-deli** [jasp-stats/jasp-issues#417]
* JASP version: 0.10.0
* OS name and version: macOS Mojave (10.14.5)
* Analysis: n/a
* Bug description: When switching variable type from Scale to Ordinal or Nominal sets all data in that column to 0 (zero) but only if data is made of "0.5" and "-0.5" (or "0.4" and "-0.4", or "0.4", "0", and "-0.6", etc.). With a mixture of data such as "0", "0.6", "-0.4", "1", etc. in the same variable/coumn there is no problem, switching between variable types does not cause the issue.
* Add JASP files as a zip: [Variable_type_issue.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/3385959/Variable_type_issue.jasp.zip)
* Screenshot: None
* Expected behaviour: That data is kept as is in the mentioned column
* Steps to reproduce: 
1. Open file Variable_type_issue.jasp
2. Click on the variable type of "Variable 3" 
3. Change the variable type to Ordinal or Nominal
4. All data contained in the column are set to 0 (zero)
5. Repeat the same action with say "Variable 4" and switching from Ordinal to any other variable type does not cause problems
6. Repeat with "Variable 5", "Variable 18", or "Variable 21" and the issue reappears, but not "Variable 8" (which is also originally Scale), nor "Variable 10"
7. The issue won't happen to "Variable 11" because lower, there are some field that have #NULL data
8. Have a try with the attached file…

**Comment by boutinb** [comment]
This is solved in 0.10.1 (next week): if you have a column with doubles, you can then transform it from scale to nominal, but not to ordinal (only if the values are integers). It will not set the values to 0 anymore!

**Comment by p-deli** [comment]
@boutinb 👍 thank you very much for this excellent news!
