### ISSUE TITLE
Live from workshop in Chili: Summary Stats crashes! 

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-issues#418]
For many participants, opening "Bayesian independent samples t-test" in the Summary Stats Module makes JASP crash hard. Screenshots to follow. Seems a problem mostly for the Mac, but also on some windows machines.
E.J.

**Comment by MaartenMarsman** [comment]
Here is a screenshot on the issue from my machine (OSX).

<img width="1248" alt="Screenshot 2019-07-15 at 15 01 03" src="https://user-images.githubusercontent.com/52934067/61241867-6fe46600-a712-11e9-9d2e-fc32f7680a23.png">

**Comment by AlexanderLyNL** [comment]
Thanks for reporting this, could you please send us the log files? Joris added this option into it. The log files can be activated as follows:

![logging](https://user-images.githubusercontent.com/10271675/61243021-5d385400-a747-11e9-8299-49b0792ced63.gif)

**Comment by MaartenMarsman** [comment]
Here it is.

[JASP 2019-07-15 15_28_58 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/3393874/JASP.2019-07-15.15_28_58.Desktop.log)

**Comment by AlexanderLyNL** [comment]
The tech team look more into this. Could you please do me a favour and check whether this error also occurs in version 0.10.0?

https://jasp-stats.org/previous-versions/

**Comment by EJWagenmakers** [comment]
At the workshop, participants reported that it was *not* a problem for 0.9.2. Not sure about 0.10.0. I cannot check this myself because it works fine on my laptop (all versions). Also, one Mac user reported that it did not crash when she tried it a second time (! this seems really weird).

**Comment by TimKDJ** [comment]
Could you attach the other logfiles that are in the folder as well? There should be several

**Comment by TimKDJ** [comment]
Never mind, I can reproduce the problem

**Comment by TimKDJ** [comment]
We have a fix for this and we'll upload a new version later today
