### ISSUE TITLE
Two problems with Bayesian Linear Regression.

### ISSUE THREAD

**Issue by MaartenMarsman** [jasp-stats/jasp-issues#419]
I use the "life expectancy" dataset on the latest JASP version (0.10.1).

Here is the output from BLG:

<img width="908" alt="Screenshot 2019-07-15 at 16 04 30" src="https://user-images.githubusercontent.com/52934067/61245650-fd2bb880-a71a-11e9-963d-04a54bef1a84.png">

Observe that (1) the Null-model is not included in the list, and (2) that the prior model probabilities do not add up to one. 

Now I switch the reporting from "comparing against best model" to "compare against null":

<img width="878" alt="Screenshot 2019-07-15 at 16 06 14" src="https://user-images.githubusercontent.com/52934067/61245723-2d735700-a71b-11e9-84de-e36928cf1c1f.png">

Fortunately, the Null-model is now back. But the prior model probabilities still do not add up to one. 

Another issue that seems related to this is one that I experienced with the "album sales" data. Below is the output that I got:

<img width="702" alt="Screenshot 2019-07-15 at 15 51 03" src="https://user-images.githubusercontent.com/52934067/61245853-74f9e300-a71b-11e9-94ff-ca0295651d20.png">

Notice that the Null-model is included twice. The prior model probabilities do add to one now. 

Best, Maarten

**Comment by MaartenMarsman** [comment]
OK, I see now that there is a limit to no. of models. That explains why in the first case the PMP's do not add to one. Apologies for my confusion. I do want to add that it is a bit strange that we include 10 models with the option "compare against best", excluding the null, but 11 models with the option "compare against null", which includes the null. It's a choice, but still.

The issue with including two null models in the last example remains unsolved, however. 

Cheers, Maarten

**Comment by AlexanderLyNL** [comment]
Could you please add the JASP file? Is this in version 0.10.1? The info requested in the issue's template provides us with a bit more insight on this.

**Comment by EJWagenmakers** [comment]
Yes it is in 0.10.1. The data set is in the library so it should be straightforward to check this.
@vandenman : I think we should do a little more to prevent Maarten's confusion that there are only 10 models. This can be accomplished most easily by the following actions:
1. Perhaps, when the best 10 models are shown, the table can have a footnote, for instance:
NB. Table displays only a subset of models. To see all models, select "No" under "Limit No. Models Shown".
2. For the incomplete table, we might add an extra row with "..." as entries for every column, thereby indicating that the table is incomplete.

E.J.

**Comment by vandenman** [comment]
@TimKDJ I suppose these suggestions are probably best incorporated in https://github.com/jasp-stats/jasp-desktop/pull/3028 ?

**Comment by TimKDJ** [comment]
Yes, I'll take care of it

**Comment by TimKDJ** [comment]
@MaartenMarsman I can't reproduce your issue with regards to the double null model.
What steps do I have to take to obtain this sitation?

I tried the following:
-> Add "adverts" to Dependent
-> Add "sales" & "airplay" to Covariates
-> Add the interaction of "sales" with "airplay"
-> Tick random boxes (bayes factor, order, limit no models shown)

But in all cases I only see a single null model.

**Comment by vandenman** [comment]
It need not be the null model:
![afbeelding](https://user-images.githubusercontent.com/21319932/61539186-f5189500-aa08-11e9-916c-482c183d66e4.png)

Here the .jasp file:

[doubleModelBayLinReg.zip](https://github.com/jasp-stats/jasp-issues/files/3411281/doubleModelBayLinReg.zip)

let me know if that still doesn't reproduce the issue!

**Comment by MaartenMarsman** [comment]
Hi, 

I can reproduce it as follows. Start with empty model, adverts as dependent. Then go to down to model. Select both sales and airplay (using the command button on Mac) and add them simultaneously. Attached also the jasp file (I changed the file extension from .jasp to .zip for Github..)

Best, Maarten


[Album Sales.zip](https://github.com/jasp-stats/jasp-issues/files/3416879/Album.Sales.zip)

**Comment by tomtomme** [comment]
seems solved:
![image](https://github.com/jasp-stats/jasp-issues/assets/4428185/db907520-c024-44a6-90ec-567f14d5b531)

I testet with the above album_sales.zip aka .jasp and had to move one variable back and forth to force a recompute.

I guess this can be closed then.
