### ISSUE TITLE
Character encoding issues in Mediation module

### ISSUE THREAD

**Issue by SvenHeimbuch** [jasp-stats/jasp-issues#420]
* JASP version: 0.10.1 (flatpak)
* OS name and version: Arch Linux
* Analysis: Mediation
* Bug description: Weird Characters instead of variable names
* Expected behaviour: "Normal" characters
* Steps to reproduce: 
1. Go to 'Open - Data Library - Regression - Adam Sandler'
2. Click on 'SEM - Mediation'
3. Put 'Year' as Predictor - 'Box Office' as Mediator - 'Freshness' as Outcome
4. It is reproducible with any other dataset - no matter if special characters are present or not
* Screenshot: ![Mediation_Bug](https://user-images.githubusercontent.com/27767378/61276446-5d206e80-a7b0-11e9-9de7-835dd2dcd77f.png)

**Comment by SvenHeimbuch** [comment]
Still present in JASP for Linux flatpak 0.10.2 and on Windows 0.10.1.

**Comment by gkruger1** [comment]
Also present in JASP 0.10.2 for Mac.

**Comment by JorisGoosen** [comment]
Also happens here: https://github.com/jasp-stats/jasp-issues/issues/430

**Comment by vit-trebicky** [comment]
Me too. JASP ver 0.10.2, Win10PRO in Czech. File opened from SPSS .sav file.

**Comment by vankesteren** [comment]
This has now been fixed in development.

__Workaround__
Make sure your variable names don't start with a capital letter. Weird fix but ok 🤷‍♂

**Comment by SvenHeimbuch** [comment]
> This has now been fixed in development.
> 
> **Workaround**
> Make sure your variable names don't start with a capital letter. Weird fix but ok

Thanks for the workaround. I can confirm that it works. :-)
