### ISSUE TITLE
Ranked alternative to Bayesian paired samples t-test

### ISSUE THREAD

**Issue by ArranReader** [jasp-stats/jasp-issues#421]
JASP currently provides a 'non-parametric' alternative with the Bayesian independent samples t-test (Mann-Whitney). Would it be possible to implement a ranked version (e.g., Wilcoxon) of the paired samples t-test for within-subjects designs?

**Comment by konstantinakilteni** [comment]
That would be very useful indeed!

**Comment by EJWagenmakers** [comment]
Yes, @JohnnyDoorn has already developed the theory and the R code, and the JASP implementation is high on our to-do list!
E.J.

**Comment by ArranReader** [comment]
Fantastic - thank you for all your hard work!

**Comment by JohnnyDoorn** [comment]
This has been implemented some time ago, so closing this.
