### ISSUE TITLE
Refer to GitHub page on crash?

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-issues#422]
It would perhaps be nice if, when JASP crashes, the user is attended to the fact that this can be reported on our GitHub page...

At a minimum, we could add this information to the message that "JASP needs to close"

Cheers,
E.J.

**Comment by EJWagenmakers** [comment]
...now the box says "if you could report your experience to the JASP team that would be appreciated" (or something similar). What happens is that people send emails to report their experience, but we really want them to use GitHub instead...

**Comment by JorisGoosen** [comment]
The messagebox now has a "[Report](https://jasp-stats.org/bug-reports/)" and "Exit" button.

Text is: 
```
JASP has experienced an unexpected internal error:
The engine crashed...

JASP cannot continue and will close.

It would however be greatly appreciated if you could report this error to the JASP team.
```

**Comment by EJWagenmakers** [comment]
Suggested minor tweak in the text, final sentence:

We would be grateful if you could report this error to the JASP team.
