### ISSUE TITLE
Filetype .jasp is not supported!

### ISSUE THREAD

**Issue by MAgojam** [jasp-stats/jasp-issues#423]
* JASP version: 0.10.2
* OS name and version: win 10Pro 64bit (ITA)
* Screenshot: 
![Screenshot_20190718](https://user-images.githubusercontent.com/36552289/61483136-7a199500-a99c-11e9-9f0d-c8d86732918a.png)

Hi, @JorisGoosen.
I'm still here asking for your help.

As you can see from the attached screenshot, the last jasp update does not seem to recognize the .jasp file type.
This is done with recent files, used up until yesterday, but I have also tried and do so with the examples from the Data Library.
Can you help?

Thanks, as always and my best regards.
Maurizio

**Comment by TimKDJ** [comment]
Judging by the build date of your JASP version you downloaded a development version (or "nightly"). These versions incorporate our very latest code changes and aren't well tested. 
I would recommend you download the release version from https://jasp-stats.org/download/ instead -- this one doesn't have the issue you describe.

If you like living on the bleeding edge, then the latest development build has also solved the issue :)

**Comment by JorisGoosen** [comment]
@MAgojam and all the fixes needed to run on all your students vms are in 0.10.2 (the latest release).
