### ISSUE TITLE
JASP freezing on launch [WORKAROUND SEE tkasci's COMMENT]

### ISSUE THREAD

**Issue by luisbm1634** [jasp-stats/jasp-issues#424]
* JASP version: 0.10.2
* OS name and version: MacOS Mojave
* Analysis: None
* Bug description: JASP 0.10.2 freezes for up to a minute on launch. The entire OS is unavailable during this period - no open program responds to mouse clicks, I can't use keyboard shortcut to open the force quit applications window, etc. If I have activity monitor open when I launch JASP then activity monitor also stops updating realtime CPU usage and becomes unresponsive. I did see a brief (less than a sec) return to responsiveness after several seconds of unresponsiveness in activity monitor while JASP was loading - it showed multiple iterations of JASP engine running that together was using more than 100% of available CPU resources. I'm thinking this may have something to do with the problem. Replacing JASP 0.10.2 with JASP 0.10.0 resolved all problems with loading JASP.

EDIT: see [this comment](https://github.com/jasp-stats/jasp-issues/issues/424#issuecomment-515439963) for the workaround.

**Comment by JorisGoosen** [comment]
Hmm, on startup the engines load some R-packages, maybe some of the new packages we added have a startup-sequence that is heavy on older macs.

@djdekker  and @luisbm1634, how old are your macs (or which type are they exactly)?

**Comment by luisbm1634** [comment]
Hi Joris,

I have a 2017 13 inch MacBook Pro with a 3.1 GHz Intel Core i5 and 8 GB
LPDDR3 memory.

**Comment by JorisGoosen** [comment]
Well, that doesn't sound too bad actually. We'll have to find somebody at UvA with something similar to figure out what is making JASP startup so slow or freeze.

@MyrtheV do you see the same on your mac with the new version?

**Comment by djdekker** [comment]
Hi Joris,
I have got a 2017 iMac 3.4 GHz Intel Core i5 with 8GB of RAM.

**Comment by MyrtheV** [comment]
I don't have this issue, but I am on macOS Sierra.

**Comment by JorisGoosen** [comment]
Hmm, maybe this is related to some changes me & @boutinb made to synching datafiles and the engines. I will have to take a closer look to the changes and how they migt effect a Mac when I am working on one again.

**Comment by mjkofler** [comment]
I also have this issue with 0.10.2. After the initial 1 minute or so when my whole system is unresponsive, it also freezes for shorter durations when opening files. Altogether it takes about 5 minutes to open JASP and get a dataset open ... "ok, who installed the SPSS module?" :-)

macOS Mojave 2.9 GHz Intel i7, 16 GB RAM, Radeon Pro 460 4 GB + Intel HD Graphics 530 1536 MB

**Comment by tkasci** [comment]
Same issue here, JASP 10.2, 2016 Macbook Pro, OSX 10.14.6. 

One quick fix I found out: run JASP from the command line. Open a Terminal and paste this:
`/Applications/JASP.app/Contents/MacOS/JASP` - when I do this, the app starts normally without freezing.

**Comment by JorisGoosen** [comment]
@tkasci that is quite a good find!

@mjkofler, @djdekker or/and @luisbm1634 is this the same on your systems?

**Comment by mjkofler** [comment]
This works for me  - JASP opens quickly when opened via Terminal (/Applications/JASP.app/Contents/MacOS/JASP). Thanks @tkasci !

**Comment by luisbm1634** [comment]
This also works for me. Good workaround!

**Comment by mjkofler** [comment]
In case it helps, when I started JASP via command line it returned the following: 

qrc:/components/JASP/Widgets/ComputeColumnWindow.qml:330:2: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/ComputeColumnWindow.qml:330:2: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:362:4: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:362:4: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:112:4: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:112:4: QML Dialog: Binding loop detected for property "implicitWidth"
QNetworkReplyHttpImplPrivate::_q_startOperation was called more than once QUrl("http://jasp-stats.org/jasp-version/")
Property 'data'' of object 'QQuickRootItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'resources'' of object 'QQuickRootItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'states'' of object 'QQuickRootItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transitions'' of object 'QQuickRootItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transformOriginPoint'' of object 'QQuickRootItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transform'' of object 'QQuickRootItem' has no notify signal and is not constant, value updates in HTML will be broken!
Don't know how to handle 'mode', use qRegisterMetaType to register it.
Don't know how to handle 'format', use qRegisterMetaType to register it.
Don't know how to handle 'mirroring', use qRegisterMetaType to register it.
Don't know how to handle '', use qRegisterMetaType to register it.
Property 'data'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'resources'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'states'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transitions'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transformOriginPoint'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transform'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Don't know how to handle '', use qRegisterMetaType to register it.
Property 'data'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'resources'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'states'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transitions'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transformOriginPoint'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transform'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'data'' of object 'SplitView_QMLTYPE_37_QML_191' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'resources'' of object 'SplitView_QMLTYPE_37_QML_191' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'states'' of object 'SplitView_QMLTYPE_37_QML_191' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transitions'' of object 'SplitView_QMLTYPE_37_QML_191' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transformOriginPoint'' of object 'SplitView_QMLTYPE_37_QML_191' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transform'' of object 'SplitView_QMLTYPE_37_QML_191' has no notify signal and is not constant, value updates in HTML will be broken!
Don't know how to handle '', use qRegisterMetaType to register it.
Property 'data'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'resources'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'states'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transitions'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transformOriginPoint'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transform'' of object 'QQuickItem' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'data'' of object 'QQuickRectangle' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'resources'' of object 'QQuickRectangle' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'states'' of object 'QQuickRectangle' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transitions'' of object 'QQuickRectangle' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transformOriginPoint'' of object 'QQuickRectangle' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transform'' of object 'QQuickRectangle' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'gradient'' of object 'QQuickRectangle' has no notify signal and is not constant, value updates in HTML will be broken!
Don't know how to handle '', use qRegisterMetaType to register it.
Property 'data'' of object 'QQuickWebEngineView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'resources'' of object 'QQuickWebEngineView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'states'' of object 'QQuickWebEngineView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transitions'' of object 'QQuickWebEngineView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transformOriginPoint'' of object 'QQuickWebEngineView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transform'' of object 'QQuickWebEngineView' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'userScripts'' of object 'QQuickWebEngineProfile' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'data'' of object 'QQuickWebEngineHistory' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'resources'' of object 'QQuickWebEngineHistory' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'states'' of object 'QQuickWebEngineHistory' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transitions'' of object 'QQuickWebEngineHistory' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transformOriginPoint'' of object 'QQuickWebEngineHistory' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transform'' of object 'QQuickWebEngineHistory' has no notify signal and is not constant, value updates in HTML will be broken!
Don't know how to handle '', use qRegisterMetaType to register it.
Property 'transports'' of object 'QQmlWebChannel' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'registeredObjects'' of object 'QQmlWebChannel' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'userScripts'' of object 'QQuickWebEngineView' has no notify signal and is not constant, value updates in HTML will be broken!
Don't know how to handle '', use qRegisterMetaType to register it.
Property 'data'' of object 'QQuickItem_QML_193' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'resources'' of object 'QQuickItem_QML_193' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'states'' of object 'QQuickItem_QML_193' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transitions'' of object 'QQuickItem_QML_193' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transformOriginPoint'' of object 'QQuickItem_QML_193' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'transform'' of object 'QQuickItem_QML_193' has no notify signal and is not constant, value updates in HTML will be broken!
Don't know how to handle '', use qRegisterMetaType to register it.
R_HOME: /Applications/JASP.app/Contents/Frameworks/R.framework/Versions/3.5/Resources/
R_HOME: /Applications/JASP.app/Contents/Frameworks/R.framework/Versions/3.5/Resources/
R_HOME: /Applications/JASP.app/Contents/Frameworks/R.framework/Versions/3.5/Resources/
R_HOME: /Applications/JASP.app/Contents/Frameworks/R.framework/Versions/3.5/Resources/

**Comment by djdekker** [comment]
@JorisGoosen I won't have access to my Mac for a couple of weeks. I'll try as soon as I'm back.

**Comment by JorisGoosen** [comment]
@luisbm1634 @djdekker @mjkofler @tkasci we have just uploaded a new version of the Mac OSX installer DMG, maybe (one of) you could try this and see if it starts normally when the icon is double-clicked?

**Comment by vicenteinefo** [comment]
I have downloaded this new version from the webpage and it seems starts pretty well and faster the before.

**Comment by luisbm1634** [comment]
I can also confirm that the version I downloaded this morning starts up quickly and without issue. Thanks!

**Comment by JorisGoosen** [comment]
Aah ok so the problem was that the earlier version wasn't signed and apparently that causes problems on some macs.. Good to know!
