### ISSUE TITLE
Bayesian Mann-Whitney unstable BF estimates and performance revisited #289 & #299

### ISSUE THREAD

**Issue by ibecav** [jasp-stats/jasp-issues#425]
**Thanks for all the hard work and continuing improvement on JASP.**

* JASP version: 0.10.2
* OS name and version: MacOS 10.14.5 (mojave)
* Analysis: Bayesian Independent samples t-test (Mann Whitney)
* Bug description: Issues #289 & #299 are closed and I agree they are partially solved but hopeful for more improvement and clarification.

* Dataset for reproducibility sake (ggplot2::mpg) filtered for class == "compact" | class == "pickup"

I tried to run the analysis on a much larger dataset N>1,000 but it ran for hours so for reproducibility sake I dropped back to a subset of `ggplot2::mpg`

I read your earlier responses and understand attending to the ties induces uncertainty. But just wanted to report that even with this modest dataset it's still wildly variant. Running with default iterations = 1,000 microbenchmark reports about mean ~ 5 seconds to get through `.rankSumGibbsSampler` trying to increase iterations to 10,000 takes the mean to about 1 minute for very little decrease in the variability of BF10.  It's changing by orders of magnitude like 66907.48, 15518.86, 116086.6 etc.. with 10,000 iterations

Any chance of further improvements?  And a specific sub questions...

Is it the number of ties that most influences accuracy, or total N, or iterations?  Trying to shape my expectations about when to avoid using it or what I can do to shape performance.

Thanks.

**Comment by ibecav** [comment]
A quick follow-on thought.  In light of evidence that at least with frequentists methods a ttest against ranked data yields the same conclusions as a MW especially as sample size grows would it make sense to aim users with larger data sets in that direction rather than the computational pain of doing it the "correct way"?  **_I'm not at all sure and not complaining_** just looking for practical solutions... A recent article https://psycnet.apa.org/record/2012-00717-007 and enclosing the analysis from JASP with ggplot2::mpg data set including rank

[MWBayesian.zip](https://github.com/jasp-stats/jasp-issues/files/3411862/MWBayesian.zip)

**Comment by EJWagenmakers** [comment]
Would be interesting to see the degree to which approximately the same results obtain when N grows large (and ties are impossible, or not too abundant)
E.J.

**Comment by ibecav** [comment]
Sadly for my work, ties tend to be abundant. That's why I'm interested in the drivers for performance and practical solutions/work-arounds.  Thanks for the quick response and great work by you and your team.

**Comment by tomtomme** [comment]
@ibecav 
Is the performance issue still prevalent in the current JASP version?
If so, feel free to close the issue.
