### ISSUE TITLE
Contingency Tables blurry text for variables in the "Columns" field 

### ISSUE THREAD

**Issue by gibbona1** [jasp-stats/jasp-issues#428]
* JASP version: 0.10.2.0
* OS name and version: Windows 10
* Analysis: Contingency Tables
* Bug description: Any variables put in the columns field have blurry text, in the initial window opened.
* Add JASP files as a zip:
[Contingency Tables Blurry.zip](https://github.com/jasp-stats/jasp-issues/files/3416574/Contingency.Tables.Blurry.zip)

* Screenshot: 
![Screenshot 2019-07-22 11 25 02](https://user-images.githubusercontent.com/33295389/61621587-81c68b80-ac73-11e9-92cb-01b8b6c21d7b.png)

* Expected behaviour: This field should display clear text like the other three lists in Contingency Tables. This doesn't seem to be a zooming problem since zooming in to 110% or more or zooming out to 90% or less gives clear text. There is no problem when I go fullscreen either, just the 100% zoom on the initial window opened. 
* Steps to reproduce: 
1. Go to 'Contingency Tables'
2. Click on any nominal or ordinal fields and add to 'Columns' field
3. Look at the columns field

**Comment by tomtomme** [comment]
This is fixed for me on 0.18.2 beta (flatpak manjaro linux)

@gibbona1 
can you re-test on windows?
current stable 0.18.1 is probably sufficient

**Comment by gibbona1** [comment]
@tomtomme I checked with the nightly build from December 29th (0.18.2) on Windows 11 and this problem is fixed. It must be long since dealt with since I opened the issue.
Hope this helps!

**Comment by tomtomme** [comment]
Thx! Please close this issue then!
