### ISSUE TITLE
Installing multiple versions of JASP

### ISSUE THREAD

**Issue by PeterKlaren** [jasp-stats/jasp-issues#429]
I guess a simple question... Installed JASP 0.10.0.0 on a new pc, but cannot seem to be able to install v 0.9.2.0 as well. JASP's msi comes up with the message that a more recent version is already installed. When I change the order of installing, v 0.10.0.0 overrides v 0.9.2.0.

I would like to run both versions as I use v 0.9.2.0 for two statistics courses. It runs well on our faculty's servers. I also want to explore v 0.10.0.0's new features. Thanks for any tips!

Peter

**Comment by JorisGoosen** [comment]
Hey @PeterKlaren you could install a zipped version of JASP.
The [previous version can be found here](https://jasp-stats.org/previous-versions) and for 0.9.2 there are specific links to [the 64bit version](https://static.jasp-stats.org/JASP-0.9.2.0-64-bit.msi) and [the 32bit version](https://static.jasp-stats.org/JASP-0.9.2.0-32-bit.msi).
