### ISSUE TITLE
post hoc comparisons after repeated measures anova. Same Mean differences, t and p values for all the comparisons

### ISSUE THREAD

**Issue by ajestudillo** [jasp-stats/jasp-issues#431]
* JASP version: 0.10.2
* OS name and version: Windows 10
* Analysis: post hoc comparison after repeated measures anova
* Bug description: the mean difference, standard error,  t value and p value for all my comparisons is identical, despite that looking at the descriptives and graphs, the differences between conditions are clear. Also, regardless of the kind of corrction, the p value is always the same. 
* Add JASP files as a zip:

[AOI_dwell_match_mismatch.zip](https://github.com/jasp-stats/jasp-issues/files/3424980/AOI_dwell_match_mismatch.zip)

* Screenshot: 
![image](https://user-images.githubusercontent.com/38860772/61764269-2b8c5080-ae0b-11e9-91c3-bf38af01d0ef.png)

**Comment by JohnnyDoorn** [comment]
Hi @ajestudillo 

I tried to replicate your issue on my version, and when I remove your model terms (in the "model" submenu) and posthoc terms (in the "post hoc tests" menu), and then add them again, I get the proper posthoc table. Can you try doing that and see if that works? There is some internal issue in the analysis with refreshing the results I think, but this might fix it.

Kind regards,
Johnny

**Comment by ajestudillo** [comment]
Hi @JohnnyDoorn 

Thanks for your reply. Unfortunately, it didn't work for me. In fact, in a very similar analysis with a completely different dataset, I have the same problem.

**Comment by ajestudillo** [comment]
Something weird. I tried from another computer and at first I didn't have this issue. But when I repeated the analysis all the values are again the same.

**Comment by JorisGoosen** [comment]
@JohnnyDoorn is this now implemented?

**Comment by JohnnyDoorn** [comment]
Yes, fixed.
