### ISSUE TITLE
"Unfortunately the plot could not be resized" only if Contrasts are invoked in ANOVA

### ISSUE THREAD

**Issue by p-deli** [jasp-stats/jasp-issues#432]
* JASP version: 0.10.1
* OS name and version: macOS Mojave version 10.14.6 (18G84)
* Analysis: ANOVA
* Bug description: When releasing the mouse after having resized the Descriptives Plot I get a "Unfortunately the plot could not be resized. Error message: no plot object was found" and the graph is not resized.
* Add JASP files as a zip: none
* Screenshot: none
* Expected behaviour: That the graph be resized after having dragged its lower right corner and released the mouse/trackpad.
* Steps to reproduce: 
1. Menu ANOVA
2. Select ANOVA
3. Select a Fixed Factor
4. Click the appropriate arrow to pass it in the Fixed Factors field
5. Select a DV
6. Click the appropriate arrow to pass it in the Dependent Variable field
7. Unfold Descriptive Plots
8. Select the Factor
9. Click the arrow to pass it in the Horizontal Axis field
10. Unfold Contrasts
11. Select deviation
12. Try to resize the graph

However, if the contrast part is done before the plot, there is no resize problem of the latter.

**Comment by TimKDJ** [comment]
Thanks for making us aware of this issue. I can indeed reproduce the problem on my machine.
@JohnnyDoorn I'm going to assume this will be fixed as a by-product of your analysis rewrite. Good to still check it though.

**Comment by JorisGoosen** [comment]
@JohnnyDoorn is this fixed now?

**Comment by JohnnyDoorn** [comment]
Yes
