### ISSUE TITLE
Non parametric tests JASP

### ISSUE THREAD

**Issue by Jiheene** [jasp-stats/jasp-issues#433]
Hello everyone,

I am a french student. 

I have a question about the non-parametric test of JASP (Wilcoxon, Kruskal-Wallis, Friedman...).

Do we have to calculate the ranks (sum of ranks...) ? Or organise the data (in ranks) ?

Or is it an operation performed automatically by JASP before performing the calculations ?

Thank you a lot for our aids!

* JASP version: JASP 0.10.0.0
* Analysis: Kruskal-Wallis, Wilcoxon, Friedman.

**Comment by EJWagenmakers** [comment]
This is automatically performed by JASP, you do not need to do anything.
E.J.

**Comment by Jiheene** [comment]
Thank you a lot for our response! :)
