### ISSUE TITLE
Opening a jasp file with filters on results in error

### ISSUE THREAD

**Issue by SvenHeimbuch** [jasp-stats/jasp-issues#434]
* JASP version: 0.10.2 (flatpak)
* OS name and version: Arch Linux with flatpak 1.4.2 (but also the same on Windows 10)
* Analysis: Bayesian ANOVA
* Bug description: Reopen a .jasp file with filters applied results in error (see screenshot). "Refresh All" brings the results back.
* Add JASP files as a zip: [singers-filtered.zip](https://github.com/jasp-stats/jasp-issues/files/3431226/singers-filtered.zip) (rename .zip to .jasp)
* Screenshot: ![jasp-0102-error-banova-filter](https://user-images.githubusercontent.com/27767378/61870591-c30ea380-aede-11e9-8f48-da493461d633.png)

* Expected behaviour: Show the saved results with applied filters on reopening a .jasp file
* Steps to reproduce: 
1. Use the "Singers" data from the library
2. Apply filter to the variable "Pitch", e.g., filter level 4 = very low
3. Save the file with the applied filter
4. Reopen the saved file results in the error

> This analysis terminated unexpectedly.
> 
> Error in .BANOVArunAnalysis(jaspResults, dataset, options, 'ANOVA'): argument 'jaspResults' is missing, with no default
> 
> Stack trace
> analysis(dataset = dataset, options = options, perform = perform, callback = the.callback, state = oldState)
> 
> .BANOVArunAnalysis(jaspResults, dataset, options, 'ANOVA')
> 
> .BANOVAestimateModels(jaspResults, dataset, options, dataInfo, analysisType)

[singers-filtered-logs.zip](https://github.com/jasp-stats/jasp-issues/files/3431224/singers-filtered-logs.zip)

**Comment by JorisGoosen** [comment]
This issue is already fixed in the current development version.
