### ISSUE TITLE
Garbled variable names in mediation analysis

### ISSUE THREAD

**Issue by mike-ology** [jasp-stats/jasp-issues#436]
* JASP version: 10.2
* OS name and version: Windows 10 Enterprise 1903
* Analysis: Mediation Analysis
* Bug description: Garbled variable names in mediation analysis (see attached screenshots)
* Add JASP files as a zip: Occurs with my own data files, but also with the built-in examples
[JASP file.zip](https://github.com/jasp-stats/jasp-issues/files/3449548/JASP.file.zip)
* Screenshot: Attached

![Capture3](https://user-images.githubusercontent.com/30823597/62179008-8da20400-b37d-11e9-995c-5edf099f24ca.PNG)
![Capture2](https://user-images.githubusercontent.com/30823597/62179009-8da20400-b37d-11e9-8877-74d9ac54275d.PNG)
![Capture](https://user-images.githubusercontent.com/30823597/62179010-8da20400-b37d-11e9-80e9-507de526c64f.PNG)

**Comment by AlexanderLyNL** [comment]
Hi Mike,

The temporary fix is to change the first letter of your variable name from a capital letter to a lower case letter, see also

https://github.com/jasp-stats/jasp-issues/issues/420
https://github.com/jasp-stats/jasp-issues/issues/435

The better solution is included in the next JASP release. Please reopen if the workaround doesn't work for you. 

Cheers,
Alexander
