### ISSUE TITLE
Second-order factor box

### ISSUE THREAD

**Issue by ppiress** [jasp-stats/jasp-issues#438]
* JASP version: 0.10.2
* OS name and version: Windows 10
* Analysis: Confirmatory Factor Analysis
* Bug description: The tutorial indicates there is a second-order factor box in for the confirmatory factor analysis, but there is no such box or option. I don't know if it is still going to be implemented... 
* Screenshot: 
![image](https://user-images.githubusercontent.com/19862411/62301636-5a2faa00-b44f-11e9-9da0-024e93299806.png)

**Comment by vankesteren** [comment]
Oops! Yes, this will be implemented :)

**Comment by VinceHUG** [comment]
In a Second Order CFA, when looking at the reliability, JASP gives one line "total" with Omega and alpha, and one line "SecondOrder" with only Omega. Which one is the Hierarchical Omega ?
