### ISSUE TITLE
Red line on Path Diagram in SEM

### ISSUE THREAD

**Issue by meskisu** [jasp-stats/jasp-issues#439]
In the path diagram some of the lines are green and some of them are red. The paths which are illustrated red are also significant loading value. But I don't know why are they red. 
Could anyone help me about what does red line or green line mean in SEM Path Diagram.

**Comment by vandenman** [comment]
Usually, red lines are negative loadings and green lines are positive loadings. @vankesteren is this right?

**Comment by meskisu** [comment]
Ohh, How I did not realize it. Thanks.
