### ISSUE TITLE
No results for SEM Robust DWLS 

### ISSUE THREAD

**Issue by acescos** [jasp-stats/jasp-issues#440]
JASP does not print the robust results when I use ordinal variables on Structural Equation Modeling and choose the “DWLS” option.
However, when I perform the calculations using lavaan R package with 

fit<-cfa(mymodel, data=data, ordered=names(data))

the result includes a second column for the robust results. 
JASP seems to print only the output from the first column of the lavaan output. 
Both results may differ from each other. 
Therefore, I request the output of the estimates also include an option to show the robust results.

**Comment by vankesteren** [comment]
I will look into this in the next iteration of the SEM analysis!

**Comment by acescos** [comment]
That's great! I hope to see the enhancement of the software soon!

**Comment by juliuspfadt** [comment]
This will be fixed with the next release, see here: https://github.com/jasp-stats/jaspSem/pull/122

**Comment by tomtomme** [comment]
@acescos 
Can you check if this is fixed for you and close this issue?
