### ISSUE TITLE
Labelled outliers don't match case number when using filters

### ISSUE THREAD

**Issue by mike-ology** [jasp-stats/jasp-issues#443]
* JASP version: 0.10.2
* OS name and version: Win10
* Analysis: Descriptives
* Bug description: If run a descriptives module with the box plot analysis and Label Outliers enabled, AND am currently filtering my dataset, the case number for an outlier may not match the actual case in the dataset. Case numbers in the box plot skip any filtered out cases so the numbers no longer match. See an example in my attached screenshot, where outlier '49' actually refers to case '51' because 2 earlier cases have been filtered out. Ideally, these two numbers should match, as JASP pointed me to the wrong case and I was wondering what was wrong in my dataset...
* Add JASP files as a zip:
* Screenshot: 
![Capture](https://user-images.githubusercontent.com/30823597/62588700-4a094600-b8f9-11e9-9064-d53c799b37ce.PNG)

* Expected behaviour:
* Steps to reproduce:

**Comment by JorisGoosen** [comment]
Fixed
