### ISSUE TITLE
Internal Error unknown

### ISSUE THREAD

**Issue by NoelleScience03** [jasp-stats/jasp-issues#444]
Analysis:

Bug description:every time I try to run Jasp an error window shows up saying 'Jasp ha experienced an unexpected internal error' and the program must be closed.

Add JASP files as a zip:

Screenshot:
jasperror

Expected behaviour:
Internal error returns back

Reproduction steps: 
> Open Jasp in Windows 10
> Upload Excel file (size = 136 KB (140.112 bytes))
> Seek file
> Select file
> Systems shows representation columns and rows
> Click on button Audit
> Click on Audit workflow
See error:

![image](https://user-images.githubusercontent.com/53795278/62612571-ec302a80-b907-11e9-9965-02c24d390d03.png)

**Comment by JorisGoosen** [comment]
Hey @NoelleScience03, too bad Audit doesn't seem to work for you.

Is it possible for you to share the datafile your using? It might be helpful for us to be able to check it ourselves.

**Comment by NoelleScience03** [comment]
Hi Joris, ik zie dat het niet afhangt van het soort bestand. Ook wanneer ik andere bestanden gebruik krijg ik dezelfde error in Jasp.

**Comment by JorisGoosen** [comment]
Hoi Noelle,

Zou het mogelijk zijn dat je de logging van JASP aanzet (Menu -> Preferences -> Advanced -> Logging), dan een file opent en de aangemaakt logfiles (1 desktop file en 4 engine files) hier aan dit issue toevoegt? Je kan de map met logfiles direct openen vanuit preferences trouwens.

**Comment by NoelleScience03** [comment]
Hoi Joris,

Bij deze het JASP Log bestand. 

[JASP 2019-08-08 16_31_14 Log_file.txt](https://github.com/jasp-stats/jasp-issues/files/3496986/JASP.2019-08-08.16_31_14.Log_file.txt)

**Comment by JorisGoosen** [comment]
Hey @NoelleScience03,

Dank je voor het bestand! Alleen zou je misschien nog de 4 logs van de engines kunnen uploaden?

Verder vroeg ik me af of je eventueel een van de databestanden zou kunnen delen die niet werken met Audit. Dan kunnen we gelijk testen of het hier ook kapot gaat.

**Comment by diogenesbido** [comment]
[1] I open the “Fear of Statistics” dataset (example within the JASP, n=2571)
[2] Some results of Reliability analysis are showed
[3] When I change to Descriptive statistics, JASP stops after 2 to 4 seconds.
[4] I updated Windows and java just now, then I reinstalled JASP but the issue remains.

[5] I open the “Fear of Statistics” dataset again, and I run exploratory factor analysis, correlation, paired t-test, but when I select “Descriptive statistics”, JASP stops again.

[6] My PC = DELL Inspiron 14 5000
- Windows 10 Home Single Language
- 2019
- System: Intel Core i7-4510U  CPU @ 2.00 GHz  2.60 GHz
- RAM: 16.0 GB
- 64 bits


![image](https://user-images.githubusercontent.com/21972472/63258691-01378280-c253-11e9-89ca-507d66da8127.png)


![image](https://user-images.githubusercontent.com/21972472/63258714-0f859e80-c253-11e9-9c49-46802ad71eb6.png)

**Comment by NoelleScience03** [comment]
Hi Joris,

The error occurs without importing files. It happens only when I open the software and click on Audit > audit workflow. 

Where can I find the engine files? Further information about my laptop:

Laptop = DELL XPS 13 9370
Windows specifications = 
Windows 10 Pro
Version 1803

System: Intel (R) Core(TM) i7-8550U CPU @ 1.80GHz 1.99 GHz
RAM: 16.0 GB
System type: 64 bits x64 based processor

Thanks!

**Comment by JorisGoosen** [comment]
@diogenesbido it seems you have a different issue than stated hee, could you open a new issue for your problem please?

@NoelleScience03 the engine-logfiles are supposed to be right next to the other logfile. Basically named the same but with "Engine #" instead of "Desktop".

**Comment by juhy-git** [comment]
Hi,
same behavior as described by @diogenesbido for me and a few other people (from about 25 people in a course). JASP stops when clicking on "Descriptive statistics", "Mediation analysis" and "CFA". It happens always, data doesn't seem to matter.

Windows 10 Pro
Intel (R) Core(TM) i5-8250U CPU @ 1.60GHz 1.80 GHz
RAM 8.0 GB
64 bits

**Comment by JorisGoosen** [comment]
@NoelleScience03 I understood from @koenderks that you do not actually have these engine logfiles...

Would it be possible for you to come by with your computer to me? Because it is really hard for me to figure out what goes wrong without access to a computer that has this problem. None of the Windows systems I have have this problem..

**Comment by boutinb** [comment]
Hi @NoelleScience03 
It seems that your problem occurs also by other people. I have tried many configurations on different PC's, but I still cannot reproduce this problem. So it seems that JASP cannot work properly with a peculiar component/feature/setting on Windows PC. It would help us a lot if we can use directly your PC. Is there any possibility that you can come here, or you can lend your PC to Koen from 1 day?
Kind regards,
Bruno

**Comment by boutinb** [comment]
I have made a hotfix (http://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-WindowsJaspResultsHotfix-b6bdd74a8493a70ad565bf5dbced07b835b9b45d.msi) that solves similar problem. Could you try it? This version is not signed, so your computer may say that it does not trust it. It may be also slower.
