### ISSUE TITLE
Error Message upon opening *.sav -> bad allocation

### ISSUE THREAD

**Issue by flaihai** [jasp-stats/jasp-issues#445]
Dear JASP Team,
JASP worked fine for me so far. Today, I tried to open another *.sav file and I would get the error message "unable to open file - bad allocation". I edited the file, saved it with a new name - no help.
What's wrong this time?
Thanks so much for your help!
Jan

![JASP](https://user-images.githubusercontent.com/53866972/62628025-d6802c80-b92a-11e9-8185-6e93b70d12d7.jpg)

* JASP version:
* OS name and version:
* Analysis:
* Bug description:
* Add JASP files as a zip:
* Screenshot: 
* Expected behaviour:
* Steps to reproduce:

**Comment by JorisGoosen** [comment]
There seem to be some problems in the `.sav` reading code. For the next version of JASP I've added [Readstat](https://github.com/WizardMac/ReadStat) support which should solve this problem.

I can only help you now by either suggesting that you try to save/export your `.sav` as a `csv` file or you send me your `sav` file and I will saves it as a `jasp` file for you.

**Comment by AlexanderLyNL** [comment]
If possible, could you please add the sav file in zip to this thread? Then we can confirm whether it indeed does the trick.

**Comment by flaihai** [comment]
Hey guys,
thank you so much for your friendly and quick help! I attached the orignal file that I tried to open. This file is only a test file created by an online questionnaire and contains just three sets of data. So it is not really important to me. But next time, when the file contains the full set of data it would be nice being able to open it directly.
Cheers,
Jan
[Jans sav file.zip](https://github.com/jasp-stats/jasp-issues/files/3477764/Jans.sav.file.zip)

**Comment by AlexanderLyNL** [comment]
Hi Jan,

Thanks for this use-case. I can confirm that:
1. [Current version workaround] if you save the data set as csv, JASP 0.10.2 can open the data
2. [Better solution] The next release of JASP can open the sav file without any problems thanks to Readstat package, which Joris implemented. 

With the workaround and the improvement in our next release, I'm considering this issue solved, but please reopen if saving the data as a csv doesn't work for you at the moment. 

Cheers,
Alexander

**Comment by JorisGoosen** [comment]
Aah I've tested it and it will work in the next version, happy to help!
