### ISSUE TITLE
Assumptions test in Pearson r

### ISSUE THREAD

**Issue by iron78** [jasp-stats/jasp-issues#446]
* Enhancement: normality test, outlier detection, histogram, shapiro-wilk test
* Purpose: in the conduct of research
* Use-case: I am currently conducting a research study and that i will be using Pearson r, i need to check the assumptions before proceeding further.

**Comment by AlexanderLyNL** [comment]
Hi Iron78,

You can find many of these features in Description. We haven't implemented a bivariate normal test yet, but you can also do the nonparametric test to check the robustness of the results. Please reopen if something's still unclear. 

Cheers,
Alexander

**Comment by iron78** [comment]
thank you so much, i updated my copy of JASP and the features were present

ronald
