### ISSUE TITLE
Reversed scaled items not applied to Mcdonald's ω 

### ISSUE THREAD

**Issue by Jaurell** [jasp-stats/jasp-issues#448]
I was trying out the reliability module and noticed that the Mcdonald's ω was much lower than it's supposed to be. The data is 6 items with 3 items reversed scaled. The output for chronbach's alpha changed to the correct value when i defined the 3 items under "reversed scaled items" but Mcdonald's stayed the same. 

If i manually reversed the items i get the correct ω.

Best regards
Jaurell

Version - JASP 0.10.2 for windows

**Comment by AlexanderLyNL** [comment]
Hi Jaurell,

Thanks for figuring this out. Could you please add the JASP file as a zip to this thread?

Cheers,
Alexander

**Comment by Jaurell** [comment]
> Hi Jaurell,
> 
> Thanks for figuring this out. Could you please add the JASP file as a zip to this thread?
> 
> Cheers,
> Alexander

I'm sorry, I don't understand what file you want. Do you mean the folder for the installation or the data?

/Jaurell

**Comment by AlexanderLyNL** [comment]
Hi Jaurell,

You mention data consisting of 6 items and 3 items reversed scaled. Could you please send us this data? With the data at hand, we can study the issue more carefully. 

Cheers,
Alexander

**Comment by Jaurell** [comment]
Of course. The data is simulated so no problems. The reversed items are a2, a4 and a5.

[JASP_data_reversed_items.zip](https://github.com/jasp-stats/jasp-issues/files/3492804/JASP_data_reversed_items.zip)

/Jaurell

**Comment by TimKDJ** [comment]
@gibbona1 can you verify this in your rewrite?
