### ISSUE TITLE
Feature Request: Weighting (for Descriptives)

### ISSUE THREAD

**Issue by dschmuecker** [jasp-stats/jasp-issues#45]
Probably simple to implement and helpful for those who work with weighted data: Weight by weighting variable for descriptive output (specifically Descriptive Statistics and Frequencies).

**Comment by juliuspfadt** [comment]
lets move the discussion to the other two issues about weighting. thus, marking this as a duplicate of https://github.com/jasp-stats/jasp-issues/issues/73.

**Comment by tomtomme** [comment]
Duplicate. Can be closed.
