### ISSUE TITLE
Add permutation tests (nparcomp)

### ISSUE THREAD

**Issue by chantelanuit** [jasp-stats/jasp-issues#454]
* Enhancement: Add a series of permutation tests that are suitable for a wide range of distributional problems that could not be adequately addressed by commonly used non-parametric tests
* Purpose: Include permutation tests in JASP that are not available in SPSS or in other commonly used GUI software; include tests that do not rely on the assumption of random sampling of observations.
* Use-case:

**Is your feature request related to a problem? Please describe.**
 
"Randomization rather than random sampling is the norm is biomedical research" (Ludbrook & Dudley, 1998). This is also still the case in social sciences research. Therefore, randomization tests should be used more commonly, because they do not rely on the random sampling assumption required by the _t_ or _F_ tests.

Furthermore, adding a feature that is not available in other commercial statistical packages and that has a wide range of applications will support a better statistical treatment of data among researchers.

**Describe the solution you'd like**
 
The studentized permutation test based on the two-sample rank statistic of Brunner and Munzel (2000) is a widely applicable and robust method (Neubert & Brunner, 2007; https://doi.org/10.1016/j.csda.2006.05.024). It addresses the Behrens-Fisher problem (heteroscedasticity) and is available in R (package nparcomp; https://www.rdocumentation.org/packages/nparcomp/versions/3.0/topics/npar.t.test). This would be a welcome addition to the Student, Welch and Mann-Whitney tests already available in R. Please not that the package also provides a permutation test for correlated samples.

Additionally, the GFD package, although not rank-based, provides a studentized permutation version of the Wald-type statistic, does not require normally distributed data or variance homogeneity, and is available for ANOVA methods (https://www.jstatsoft.org/article/view/v079c01). 

**Describe alternatives you've considered**
 

**Additional context**

**Comment by chantelanuit** [comment]
Hello,

I am writing for a follow-up regarding the request for the Brunner-Munzel (BM) test. I noticed that Jamovi implemented it in the BM test additional module (https://www.mdpi.com/2624-8611/5/2/26). It would be nice to have it also in Jamovi. The wonderful Raincloud plot is a great figure to illustrate this test (stochastic dominance, the whole distributions are compared). I attach a screen capture of the way the BM test is illustrated in Jamovi: [(https://www.dropbox.com/scl/fi/0adnuayyixea2id5cfobq/BM-test.png?rlkey=2li1fxplcpxhfgcz8x01t5jyq&dl=0)]

It would however be nice to refer to the **_A_ measure of stochastic superiority** when presenting the effect size related to this permutation test. To my knowledge, Vargha and Delaney (2000; https://psycnet.apa.org/record/2000-05316-001) were the first to coin this term. Other authors termed this statistic differently. Furthermore, Jamovi uses the mathematical expression that operationalizes the measure in the table column title; I suggest that would better be included as a note under the table.

Best regards,

**Comment by EJWagenmakers** [comment]
It would make sense to include this, in some way. Team: let's discuss.

**Comment by TarandeepKang** [comment]
Hi All,

My apologies for the partial duplication of this issue in my other issue, I would like to add that Julian Karch has written a very useful pedagogical paper, and has made all versions of this test available in a single package, which underpins his Jamovi module:

Karch, J. D. (2021). Psychologists Should Use Brunner-Munzel’s Instead of Mann-Whitney’s U Test as the Default Nonparametric Procedure. Advances in Methods and Practices in Psychological Science, 4(2), 251524592199960. https://doi.org/10.1177/2515245921999602
Karch, J. D. (2023). bmtest: A Jamovi Module for Brunner–Munzel’s Test—A Robust Alternative to Wilcoxon–Mann–Whitney’s Test. Psych, 5(2), Article 2. https://doi.org/10.3390/psych5020026

Please do note that in my other issue also requested a broader range of more general robust procedures as implemented in the WRS2 package.

**Comment by tomtomme** [comment]
This is also a duplicate of the more recent https://github.com/jasp-stats/jasp-issues/issues/2305
Let us close this issue and gather all relevant papers & R-Packages etc. in 2305

**Comment by tomtomme** [comment]
wrs2 is now implemented as a community module. Is this sufficient?
