### ISSUE TITLE
Jasp won't open 

### ISSUE THREAD

**Issue by anneleenheyns** [jasp-stats/jasp-issues#455]
Hello JASP team,
The program does not want to open.
I have already removed it and downloaded it a few times, but it will not open when I click on it.
I have windows 8, 64bit.
I should use JASP for a research at the KULeuven.

Thanks in advance!
Anneleen

* JASP version: 0.10.2.0

**Comment by JorisGoosen** [comment]
Could you try to install [c++ redistributable](https://aka.ms/vs/16/release/vc_redist.x64.exe) ?

It is supposed to be included in the installer but perhaps something went wrong.

**Comment by bsenevir** [comment]
I'm having the same issue. The program opens to the main window and I can see it spinning up resources, but after about 30s it crashes.

I tried installing the C++ redistributable then re-installing JASP, no luck.

Windows 10, 64 bit, 18362.295

**Comment by JorisGoosen** [comment]
@anneleenheyns you get the same behaviour as @bsenevir ?

And tell me, is the interface responsive during those 30sec? Because you could turn on the logging and then we can see what JASP has to tell us.
Otherwise I can explan how to start it from the commandprompt.

**Comment by anneleenheyns** [comment]
c ++ redistributable doesn't help on my computer either. Nothing appears on my computer when I click on it to open it.
I am currently resolving it by using another computer on which it works.
Thanks a lot for the help!

**Comment by boutinb** [comment]
We have made a new version (0.11). Do you have still the same problem?

**Comment by scroono** [comment]
I have the same problem - but it has occurred after upgrading from the previous version of JASP. Crashes on splash screen; regardless of loading as administrator or base user; and have tried the C++ redistributable, after a restart. Win 10; 64 bit.

**Comment by JorisGoosen** [comment]
@scroono maybe you could open a separate issue?
We don't actually have a splash screen...
