### ISSUE TITLE
Include credibility intervals in descriptives

### ISSUE THREAD

**Issue by ianhussey** [jasp-stats/jasp-issues#46]
## Environment (for enhancement requests)
 
* Enhancement: Include credibility intervals in the descriptives for all BF tests
* Purpose: Graphs for BF tests include credibility intervals, but exact values for these are not included in the descriptive tables. Would it be possible to include them in a future release?

**Comment by juliuspfadt** [comment]
@ianhussey, if I understand correctly the issue should be fixed in at least the latest JASP version?

**Comment by ianhussey** [comment]
Great! I don't use JASP much more these days to check this out myself, but good to hear about the feature addition.
