### ISSUE TITLE
RMANOVA crash

### ISSUE THREAD

**Issue by DrMarkGS** [jasp-stats/jasp-issues#460]
Adding gender to 2way RMANOVA as a covariate in todays workshop resulted in

Descriptives plots
Descriptives Plot
This analysis terminated unexpectedly.

Error in array(0, dim = c(steps, nparam, 2), dimnames = list(NULL, names(weightedMeans), : length of 'dimnames' [2] not equal to array extent

Stack trace
analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.BANOVArunAnalysis(jaspResults, dataset, options, 'RM-ANOVA')

.BANOVAestimatePosteriors(jaspResults, dataset, options, model)

.BANOVAsamplePosteriors(jaspResults, dataset, options, model, posteriors)

array(0, dim = c(steps, nparam, 2), dimnames = list(NULL, names(weightedMeans), c('x', 'y')))

* JASP version: 0.10.2
* OS name and version: Mac OS Mojave 10.14.4

Cheers
Mark

**Comment by DrMarkGS** [comment]
Sorry forgot to say it was Bayesian analysis

**Comment by TimKDJ** [comment]
Could you attach the data (or .jasp file as a .zip) that caused this?
