### ISSUE TITLE
Error message when trying to open .sav file

### ISSUE THREAD

**Issue by LuthienT** [jasp-stats/jasp-issues#463]
* JASP version:.0.10.2.0
* OS name and version: Windows 10
* Analysis:
* Bug description: When I try to open a .sav data file from SPSS, I get an error message stating "unable to open file. Bad allocation". I would use the .csv workaround and use that file type instead, but when I've tried that, my data set goes all strange on me and some rows end up half missing and in the wrong cells. 
* Add JASP files as a zip: My data's sensitive, so unfortunately I can't include it here.
* Screenshot: 
![image](https://user-images.githubusercontent.com/54633304/63865442-820c2200-c9a9-11e9-8d4c-68cf403350bf.png)
* Expected behaviour:
* Steps to reproduce:

**Comment by TimKDJ** [comment]
Unfortunately we won't be able to do much without the data file.
Would you be okay with sending it to us via email (t.dejong3 [at] uva.nl)

**Comment by boutinb** [comment]
Reopen this issue, if you send us the SPSS file.
Bruno
