### ISSUE TITLE
embedded nul in string

### ISSUE THREAD

**Issue by LiorAbramson** [jasp-stats/jasp-issues#464]
Hi,

I conducted a Bayesian repeated-measures ANOVA in JASP with two repeated measures factors (with two levels) and one Between-subjects factor (two levels). 
I asked to compare the model to the null model, and added to the null model all the effects except for the three-way interaction (which I am interested in). 

I got the following error message: 

"This analysis terminated unexpectedly.
Error in rawToChar(as.raw(out)): embedded nul in string: 'target0v6��FW�@'
Stack trace"

Could you help me understand what does it mean?

Thank you very much,
Lior

**Comment by vandenman** [comment]
Well, it means something went wrong internally with base64 encoding, which we use to support non-standard characters (e.g., characters like ἄλφαמ).

Could you perhaps share the .jasp file in this thread so we can find out what went wrong? That way, we can fix the error for the next release.

**Comment by LiorAbramson** [comment]
Thank you! (and sorry for the slow response).
I actually reinstalled JASP and now everything works fine, so this is solved.  
However, now I have a follow-up question. the BF values of the three-way interaction (on 416 participants)  are fluctuating quite highly when I run the same analysis for several times (BF varies between 2 and 2.7). I know the values are supposed to fluctuate a bit, but - are these considered reasonable variations? 

Thanks again,
Lior

**Comment by EJWagenmakers** [comment]
Dear Lior,

These fluctuations are not wild. The numerical stability of the outcome should also be reflected in the % error column. If you desire more stable results you can go to the Advanced tab and increase the number of samples.

Cheers,
E.J.

**Comment by juliuspfadt** [comment]
this issue seems solved :)
