### ISSUE TITLE
Bug when running Mediation analysis in JASP 0.10.2

### ISSUE THREAD

**Issue by cbflynn1970** [jasp-stats/jasp-issues#465]
* JASP version: 0.10.2
* OS name and version: Mac OS 10.13.6 (High Sierra)
* Analysis: Mediation analysis

* Bug description: I received the following bug message from JASP when trying to run the mediation analysis (minus the quotes on the front and end):

"This analysis terminated unexpectedly.
Error in rawToChar(as.raw(out)): embedded nul in string: 'x8avxa50'(xad'
Stack trace
analysis(jaspResults = jaspResults, dataset = dataset, options = options)
.medParTable(jaspResults, medResult, options, ready)
.unv(rep(rep(options$dependent, each = length(options$mediators)), length(options$predictor)))
.fromBase64(substr(v, 2, nchar(v)))
rawToChar(as.raw(out))"

* Add JASP files as a zip:
[Complete Data.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/3556923/Complete.Data.jasp.zip)

* Expected behaviour: I'm new to this analysis so I was just testing it. I don't know what I was supposed to see, but I'm pretty sure it wasn't the error message, unless the data is set up incorrectly for this analysis. 

* Steps to reproduce: 
1. With the data file loaded, click on Mediation Analysis from the SEM Module

2. In the analysis, I added the following variables:
Predictor: SM Time 1
Mediators: Neuroticism-Overall, CE Time 3
Outcome: Final Score

The test never completes. I tried multiple mediator variables, but no luck - same error. The messages says submit the error message to the bug reports, so the error message is above.

**Comment by TimKDJ** [comment]
Thanks for the report!
I had a look at the problem and it seems that this was [fixed as a side-effect of a different bug fix](jasp-stats/jasp-desktop/pull/3444).

We're hoping to release a new version which includes this fix in the coming weeks. In the mean time, here are the results of the analysis you specified:
[result-export-cbflynn1970.html.zip](https://github.com/jasp-stats/jasp-issues/files/3559603/result-export-cbflynn1970.html.zip)

**Comment by cbflynn1970** [comment]
Thank you.
