### ISSUE TITLE
Custom contrasts 2.0

### ISSUE THREAD

**Issue by mservantufc** [jasp-stats/jasp-issues#467]
Hello,
I just had a look at the new JASP releases. Unless I missed something, custom contrasts still cannot be computed. So I am reopening old discussions on this forum (https://github.com/jasp-stats/jasp-issues/issues/288) and (https://github.com/jasp-stats/jasp-issues/issues/334) and wonder if you guys planned to implement this in the next couple of months. 

Thanks for the awesome work,
Mathieu

**Comment by JohnnyDoorn** [comment]
Hi Mathieu,

Yes, we are currently working on developing a gui element that allows custom contrasts!

Cheers
Johnny

**Comment by mservantufc** [comment]
Hi Johnny,
Thanks for the update. Any idea when this feature will be released ? (I am asking because I need to plan my stat courses and update the software on university computers).
Cheers

**Comment by AlexanderLyNL** [comment]
When do you teach?

**Comment by mservantufc** [comment]
Classes will start in January 2020. Ideally, I'd need to upgrade university computers a month before.

**Comment by AlexanderLyNL** [comment]
We'll take that into account in our plans, and try to make this work.

**Comment by mservantufc** [comment]
Thanks guys, very much appreciated.

**Comment by JorisGoosen** [comment]
But this issue can be best followed in the original #288 right?
