### ISSUE TITLE
Specific Eigenvalues and Proportion of Variance Explained in PCA

### ISSUE THREAD

**Issue by amsa1234** [jasp-stats/jasp-issues#468]
Is it possible to include the following two pieces of (closely interrelated) information when displaying the results of PCAs? I think both of these are standard in reporting PCA results.

1) The specific eigenvalues: Right now, these have to be estimated by only looking at the scree plot. This can be particularly confusing when factors nominally clear the eigenvalue = 1 threshold (e.g., eigenvalue = 1.1), and are very difficult or impossible to see accurately in the scree plot (moreover, small eigenvalues ~ 1 are especially difficult to locate because the simulated 95th quantile information runs across that part of the scree plot). Clearly this information is already calculated, given that we can select the minimum eigenvalue of interest in determining the number of factors, now it just needs to be displayed somewhere. 

2) Proportion of variance explained by each factor: This is important and provides some further information when evaluating the results of the PCA.

Both of these, I think, are standard requirements in reporting PCAs. In their absence, researchers presumably need to run an initial PCA on JASP to get a feel for the number and nature of factors, but then head off to another programme to determine the specific eigenvalues and the proportion  of variance explained by each factor. 

One reason to prioritise this feature is that it appears to already exist in JASP. It does not have to be created from scratch. As such, it is probably just a matter of making some of the results that are already generated when running the PCA visible to the user.

**Comment by vankesteren** [comment]
I completely agree and am taking this into account in the rewrite of the PCA, which will be available soon :)

**Comment by douglasbarraza** [comment]
Thank you so much!!!!

**Comment by 16665k00** [comment]
Indeed, many thanks!

**Comment by douglasbarraza** [comment]
Beste van Kesteren

Im sorry to bother you with this, all those numbers and/or codes mean we are able to get the % of variance explained???

Best,

**Comment by juliuspfadt** [comment]
@amsa1234, I apologize for the late response. All these features should be part of the latest JASP release, could you go an have a look?

**Comment by amsa1234** [comment]
Dear Julius,

Thank you very much. I believe these issues were addressed and the
necessary features/display added back in 2019!

Best wishes
