### ISSUE TITLE
Filter not working properly.

### ISSUE THREAD

**Issue by Bevers1** [jasp-stats/jasp-issues#469]
* JASP version: 0.10.2
* OS name and version: Windows 10 Enterprise, 1709, 16299.1331
* Analysis: Descriptive statistics
* Bug description: Click Filter not working properly for categorical variable. When "happy" is selected with a tick, the data itself is not selected - see screenshot. There are other variations  as well e.g. when I deselect "anxious" and "calm", only "anxious" is deselected on the actual dataset.
* Add JASP files as a zip: [Data_Music&Creativity_Ritter&Ferguson.zip](https://github.com/jasp-stats/jasp-issues/files/3565949/Data_Music.Creativity_Ritter.Ferguson.zip)
* Screenshot:  ![Screenshot](https://user-images.githubusercontent.com/53490394/64113144-67f38a80-cd81-11e9-88e2-02fb1fb78891.png)
* Expected behaviour: Condition 1 "happy" is ticked and therefore the data should be selected and included in analysis but is not.
* Steps to reproduce: 
1. Open dataset
2. Use click filter - does not properly select cases as it should

Note: I tried to restart JASP to fix the problem but it refused to even open the file after (freezing on "loading dataset" - file is attached in zip)

**Comment by Bevers1** [comment]
Update: If I delete every single variable apart from "ODT" and "condition" then it appears to work properly. So perhaps it is something to do with another variable in the dataset affecting it?

(Note: this is a random dataset I got off the OSF so I'm not sure what most of the variables mean)

**Comment by JorisGoosen** [comment]
So there are two issues here one was that strings that contain a columnname were encoded..
And @Bevers1 had columns in the dataset with the name being the same as the labels in "condition". This is solved by the PR.

Then there also seems to be something wrong with the selection of labels to filter. This will be fixed in version 0.12.
