### ISSUE TITLE
Plot labels in Hebrew

### ISSUE THREAD

**Issue by meirsendik** [jasp-stats/jasp-issues#470]
Thank you for adding Hebrew support in your software. However, when I put the variables in Hebrew, it appears  in the plots in the wrong direction – from left to right instead of right to left. Can you please try to solve this?

**Comment by JorisGoosen** [comment]
Hey @vandenman do you know if it is easy(/possible) to flip the plot-labels right-to-left?

**Comment by vandenman** [comment]
Flipping the labels is straightforward, but I'm not sure how to detect when they need to be flipped.

**Comment by JorisGoosen** [comment]
We could use the output of `https://doc.qt.io/qt-5/qguiapplication.html#layoutDirection-prop` and pass it on to R on startup.

**Comment by meirsendik** [comment]
Sorry about my ENGLISH:
In the tables it's OK because it's right to left. but in the plots it's left to right. Hebrew is always right to left. You can see the pictures. If I will flip the lables straightforward the plots will be OK but the tables not.
![image](https://user-images.githubusercontent.com/29006060/64178075-6f8e5e80-ce69-11e9-9913-597a604e4ca9.png)

![image](https://user-images.githubusercontent.com/29006060/64178113-8765e280-ce69-11e9-8bc4-a194504e537f.png)

**Comment by JorisGoosen** [comment]
Hey @meirsendik,

Don't worry about your english!
We understand the problem and we'll try to fix it.

**Comment by meirsendik** [comment]
thank you!
i will be glad if you notice me when the problem is fixed.
in Hebrew we say: TODA RABA!

**Comment by JorisGoosen** [comment]
לא תודה

**Comment by tomtomme** [comment]
@meirsendik 
Is this still an issue? 
For some reason I cannot select Hebrew in JASP 0.18.1

**Comment by meirsendik** [comment]
no


מאיר סנדיק,
מכללה ירושלים,
050-2289084


‫בתאריך יום ב׳, 1 בינו׳ 2024 ב-20:53 מאת ‪Thomas Langkamp‬‏ <‪
***@***.***‬‏>:‬

**Comment by tomtomme** [comment]
@meirsendik 
Cool :)
Then please close this issue. Thx

**Comment by meirsendik** [comment]
Great!

בתאריך יום ה׳, 4 בינו׳ 2024, 23:40, מאת Thomas Langkamp ‏<
***@***.***>:

**Comment by tomtomme** [comment]
@meirsendik 
I closed this, since you seemed to confirm, that this is fixed on your side. Now this "Great!" sounds like you think, that I have fixed something, which I did not! Should I reopen?

**Comment by meirsendik** [comment]
It looks good now.

בתאריך יום ו׳, 5 בינו׳ 2024, 12:31, מאת Thomas Langkamp ‏<
***@***.***>:
