### ISSUE TITLE
eta squared and partial eta squared are identical in an ANOVA with 2 main effects and one interaction effect

### ISSUE THREAD

**Issue by Mosen111** [jasp-stats/jasp-issues#471]
* JASP version: 2019 newest
* Analysis: ANOVA
* Bug description: eta squared and partial eta squared are the same in an ANOVA with 2 main effects and one interaction effect. they should be different. I tried with 3 other sets of variables. the same results. 
* Screenshot: 
![image](https://user-images.githubusercontent.com/54839119/64158019-bd5b9480-ce72-11e9-86ec-fbb686f53bff.png)

**Comment by Mosen111** [comment]
update: I tried with 2 other data sets and it worked well.

**Comment by AlexanderLyNL** [comment]
Seems like a state error.

**Comment by JohnnyDoorn** [comment]
Hi Mosen111,

If you want, you can send me your data set and I can try to verify the result with my current version (which has rewritten ANOVA code), to see if this has been fixed (or if it was erroneous to begin with).
You can send it by email to j.b.vandoorn <at> uva.nl

Kind regards
Johnny

**Comment by Mosen111** [comment]
Thanks. I just used a random file for testing and obtained the problematic results (don't know which file I used). When I used 2 data sets which I use to teach anova, the JASP results are correct. If i ever face a similar error in my future ANOVA analyses, I will make sure to send you the data set. cheers

**Comment by JohnnyDoorn** [comment]
Thanks, I think this is resolved now.
