### ISSUE TITLE
JASP not installing on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by shubhamsharma1609** [jasp-stats/jasp-issues#472]
I followed the instructions to install jasp through flatpak i.e.
`flatpak install http://static.jasp-stats.org/flatpak/JASP.flatpakref`

and when I run `flatpak run org.jaspstats.JASP`, I am getting the following error 

`Gtk-Message: 14:24:52.006: Failed to load module "unity-gtk-module"
Gtk-Message: 14:24:52.680: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:24:52.680: Failed to load module "canberra-gtk-module"
QIBusPlatformInputContext: invalid portal bus.
QGLXContext: Failed to create dummy context
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
qrc:/components/JASP/Widgets/ComputeColumnWindow.qml:330:2: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/ComputeColumnWindow.qml:330:2: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:362:4: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:362:4: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:112:4: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:112:4: QML Dialog: Binding loop detected for property "implicitWidth"
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 
shubham@Scientist:~$ R_HOME: /app/lib64/R/
R_HOME: /app/lib64/R/
R_HOME: /app/lib64/R/
R_HOME: /app/lib64/R/
`
Kindly help.

**Comment by JorisGoosen** [comment]
Could you try to install `org.flatpak.qtdemo` like so: `flatpak install flathub org.flatpak.qtdemo` and see if that runs?

**Comment by shubhamsharma1609** [comment]
I tried `flatpak install flathub org.flatpak.qtdemo`  and  it shows installation complete. After that when I execute `flatpak run org.jaspstats.JASP`. I get the following error 

`Gtk-Message: 20:31:04.774: Failed to load module "unity-gtk-module"
Gtk-Message: 20:31:04.800: Failed to load module "canberra-gtk-module"
Gtk-Message: 20:31:04.800: Failed to load module "canberra-gtk-module"
QIBusPlatformInputContext: invalid portal bus.
QGLXContext: Failed to create dummy context
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
qrc:/components/JASP/Widgets/ComputeColumnWindow.qml:330:2: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/ComputeColumnWindow.qml:330:2: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:362:4: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:362:4: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:112:4: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:112:4: QML Dialog: Binding loop detected for property "implicitWidth"
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) `

**Comment by JorisGoosen** [comment]
Ok, but could you try running the qtdemo as: `flatpak run org.flatpak.qtdemo` and see if that works?

**Comment by shubhamsharma1609** [comment]
I tried and got this 
`Gtk-Message: 20:49:32.557: Failed to load module "unity-gtk-module"
Gtk-Message: 20:49:32.598: Failed to load module "canberra-gtk-module"
Gtk-Message: 20:49:32.598: Failed to load module "canberra-gtk-module"
QIBusPlatformInputContext: invalid portal bus.
Qt: Session management error: Could not open network socket
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QApplication(0x7ffc7e591ed0), parent's thread is QThread(0x556ee3458100), current thread is QThread(0x556ee35f1300)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QApplication(0x7ffc7e591ed0), parent's thread is QThread(0x556ee3458100), current thread is QThread(0x556ee35f1300)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QApplication(0x7ffc7e591ed0), parent's thread is QThread(0x556ee3458100), current thread is QThread(0x556ee35f1300)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QApplication(0x7ffc7e591ed0), parent's thread is QThread(0x556ee3458100), current thread is QThread(0x556ee35f1300)
QObject::installEventFilter(): Cannot filter events for objects in a different thread.
Invalid Context= "stock" line for icon theme:  "/run/host/share/icons/ubuntu-mono-dark/stock/16/"
Invalid Context= "stock" line for icon theme:  "/run/host/share/icons/ubuntu-mono-dark/stock/22/"
Invalid Context= "stock" line for icon theme:  "/run/host/share/icons/ubuntu-mono-dark/stock/24/"
Invalid Context= "stock" line for icon theme:  "/run/host/share/icons/ubuntu-mono-dark/stock/32/"
Invalid Context= "stock" line for icon theme:  "/run/host/share/icons/ubuntu-mono-dark/stock/48/"
Invalid Context= "stock" line for icon theme:  "/run/host/share/icons/ubuntu-mono-dark/stock/64/"
Invalid Context= "stock" line for icon theme:  "/run/host/share/icons/ubuntu-mono-dark/stock/128/"
Invalid Context= "stock" line for icon theme:  "/run/host/share/icons/ubuntu-mono-dark/stock/16/"
Invalid Context= "stock" line for icon theme:  "/run/host/share/icons/ubuntu-mono-dark/stock/22/"
Invalid Context= "stock" line for icon theme:  "/run/host/share/icons/ubuntu-mono-dark/stock/24/"
Invalid Context= "stock" line for icon theme:  "/run/host/share/icons/ubuntu-mono-dark/stock/32/"
Invalid Context= "stock" line for icon theme:  "/run/host/share/icons/ubuntu-mono-dark/stock/48/"
Invalid Context= "stock" line for icon theme:  "/run/host/share/icons/ubuntu-mono-dark/stock/64/"
Invalid Context= "stock" line for icon theme:  "/run/host/share/icons/ubuntu-mono-dark/stock/128/"
qrc:/qml/main.qml:40:5: QML DemoPage: Binding loop detected for property "implicitWidth"
`

In addition I am getting a window
![flatpack demo](https://user-images.githubusercontent.com/11288303/64186594-bc376100-ce8c-11e9-9698-fcb3002b4216.png)

**Comment by shubhamsharma1609** [comment]
Kindly help what should be done as I do not have any knowledge of flatpack and how can I run jasp ?

**Comment by JorisGoosen** [comment]
@shubhamsharma1609 I'm trying to help you, but I am also trying to figure out what went wrong.

You could try `flatpak run org.jaspstats.JASP --safeGraphics`, maybe that helps.

Besides that, I see that your ubuntu is kind of old. So maybe you are also using an old version of Ubuntu. Could you do the following:
```bash
sudo add-apt-repository ppa:alexlarsson/flatpak
sudo apt update
sudo apt install flatpak
```

**Comment by shubhamsharma1609** [comment]
Still crashing,did exactly what you have specified. Getting the following error :
`Gtk-Message: 21:14:16.594: Failed to load module "unity-gtk-module"
Gtk-Message: 21:14:16.625: Failed to load module "canberra-gtk-module"
Gtk-Message: 21:14:16.625: Failed to load module "canberra-gtk-module"
QIBusPlatformInputContext: invalid portal bus.
QGLXContext: Failed to create dummy context
qrc:/components/JASP/Widgets/ComputeColumnWindow.qml:330:2: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/ComputeColumnWindow.qml:330:2: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:362:4: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:362:4: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:112:4: QML Dialog: Binding loop detected for property "implicitWidth"
qrc:/components/JASP/Widgets/FilterWindow.qml:112:4: QML Dialog: Binding loop detected for property "implicitWidth"
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 
`

**Comment by shubhamsharma1609** [comment]
Tried with and without safe graphics but still getting the same error.

**Comment by JorisGoosen** [comment]
can you run `glxgears` from the `mesa-utils` package?

It seems something is wrong with your OpenGL.

**Comment by shubhamsharma1609** [comment]
It is running perfectly.
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
36797 frames in 5.0 seconds = 7359.310 FPS
38623 frames in 5.0 seconds = 7724.489 FPS
38429 frames in 5.0 seconds = 7684.793 FPS
38444 frames in 5.0 seconds = 7688.573 FPS
38964 frames in 5.0 seconds = 7792.683 FPS
39060 frames in 5.0 seconds = 7811.878 FPS
38883 frames in 5.0 seconds = 7776.506 FPS
39445 frames in 5.0 seconds = 7888.553 FPS
39690 frames in 5.0 seconds = 7937.996 FPS
39108 frames in 5.0 seconds = 7821.483 FPS
39473 frames in 5.0 seconds = 7894.375 FPS

**Comment by JorisGoosen** [comment]
So which version of flatpak are you running now?

And, if that is `1.4.2` could you run `flatpak update`?

**Comment by JorisGoosen** [comment]
And could you post the output of `flatpak --gl-drivers`?

**Comment by shubhamsharma1609** [comment]
nvidia-384-130
default
host

**Comment by JorisGoosen** [comment]
And do you also have an intel videocard perhaps?

**Comment by shubhamsharma1609** [comment]
Yes.Intel HD graphics 620,in addition with nvidia one.

**Comment by JorisGoosen** [comment]
So how do you switch between intel/nvidia for your software?
I use bumblebee for instance. Could you try running JASP with Nvidia?

**Comment by shubhamsharma1609** [comment]
Switched between both using `sudo prime-select nvidia`.But nothing happening.

**Comment by JorisGoosen** [comment]
Hmm, I think I might have to change some things in the way the flatpak is set up. There might be a permission missing. 

It is a bit strange though that this doesn't always cause problems. For instance, on my own laptop with nvidia + intel there is no problem running on either GPU..

**Comment by shubhamsharma1609** [comment]
Please look into the issue and kindly solve. As I am planning to use it for studying statistics course.Kindly address this issue.

**Comment by JorisGoosen** [comment]
@shubhamsharma1609 I will change some things for the next release that might help. But that will be released in like 2 weeks. And I cannot promise that it will work.

Something you might try is change some things with your drivers.

Maybe try out bumblebee as opposed to prime?

**Comment by JorisGoosen** [comment]
Or maybe try Ubuntu 18.04?

**Comment by shubhamsharma1609** [comment]
There are some other applications that might not run on ubuntu 18.04, also wifi issues are still there on ubuntu 18.04. Therefore, I am not upgrading yet as far as the most stable Ubuntu version is concerned ubuntu 16.04 serves everything. All drivers are working perfectly in ubuntu 16.04 now.

**Comment by JorisGoosen** [comment]
Well, maybe you could just try it from a live-usb just to see if JASP does actually work then?
No need to install 18.04 on the computer.

**Comment by JorisGoosen** [comment]
@shubhamsharma1609 I've made a test-version of the new release and I've changed some options regarding graphics and video cards.

Maybe you could try this: http://static.jasp-stats.org/flatpak/JASP-Test.flatpakref ? 

I'm curious if it works better for you and if the OpenGL errors are gone?
