### ISSUE TITLE
JASP freezes when clicking on 'computer files/browse'

### ISSUE THREAD

**Issue by Filiol** [jasp-stats/jasp-issues#473]
JASP version: 0.10.2
* OS name and version: Chrome OS 76.0.3809.136 
Bug description: Jasp freezes when I go to open -- computer -- browse/documents/desktop. I have to manually shut down the program and due to that I can't import any data files or use JASP.

**Comment by JorisGoosen** [comment]
That is a shame but also a duplicate of https://github.com/jasp-stats/jasp-issues/issues/466
