### ISSUE TITLE
JASP freezes on some analyses on Windows

### ISSUE THREAD

**Issue by JorisGoosen** [jasp-stats/jasp-issues#474]
Issue as reported by @diogenesbido in https://github.com/jasp-stats/jasp-issues/issues/444#issuecomment-522510272

And by @juhy-git as:
same behavior as described by @diogenesbido for me and a few other people (from about 25 people in a course). JASP stops when clicking on "Descriptive statistics", "Mediation analysis" and "CFA". It happens always, data doesn't seem to matter.

EDIT:
It seems there is a common denominator here all jaspResults analyses seem to break on Windows systems where the engine also doesn't make logfiles.

**Comment by JorisGoosen** [comment]
Hey @diogenesebido and @juhy-git, could you try out if the same problem occurs with the newest development version from: http://static.jasp-stats.org/Nightlies/ ?

**Comment by JorisGoosen** [comment]
And when you've run it could you add the logfiles here?

**Comment by juhy-git** [comment]
Hi @JorisGoosen, yes, the problem still occurs in the newest development version.
[JASP 2019-09-05 11_47_07 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/3578615/JASP.2019-09-05.11_47_07.Desktop.log)

**Comment by JorisGoosen** [comment]
@juhy-git thanks for testing!

Could you also add the 4 logfiles of the engines?

**Comment by JorisGoosen** [comment]
Aah and I see an interesting errormessage in the logfile about the data you use. Maybe you could also send me that datafile?

**Comment by juhy-git** [comment]
I have only the one logfile in the "Logs" folder. Are the 4 logfiles of the engines somewhere else?

Data is here: 
[D4_CFA_data_2f.zip](https://github.com/jasp-stats/jasp-issues/files/3578682/D4_CFA_data_2f.zip)

**Comment by JorisGoosen** [comment]
Hmm, those logfiles ought to be next to the desktop log. Maybe the engines aren't starting properly on your system... That would explain why your analyses don't run.

Could you check if the engine's actually start? As in, when you start JASP and you check the running processes, do you see `JASP.exe`/`jasp` running and 4 instances of `JASPEngine`?

**Comment by juhy-git** [comment]
Yes, there are 4 instances of JASPEngine in total. But only two of them are in the "Apps" category. The other two are in the "Background processes" category.

**Comment by JorisGoosen** [comment]
You are running Windows right?
Could you try to run JASP as Admin and see if the logs show up then?

**Comment by juhy-git** [comment]
Yes, Windows.

JASP as Admin: Still only the desktop logfile, no logfiles of the engines.

**Comment by JorisGoosen** [comment]
Thanks for checking these things.

You mentioned three analyses that do not work so I wonder, can you run any analysis at all?

**Comment by juhy-git** [comment]
Yes, Linear and Logistic Regression, Exploratory Factor Analysis and Structural Equation Modeling run well and no problem there.

**Comment by krasenferdinandov** [comment]
Some tests continue to freeze dialogue windows (MANOVA, BINOMIAL TEST, CONFIRMATORY FACTOR ANALYSIS) and ask for program to be restarted.
![errors](https://user-images.githubusercontent.com/26842960/65131728-6f18ca80-da08-11e9-95bc-760035157737.png)

**Comment by JorisGoosen** [comment]
@krasenferdinandov and if I may ask, do you also lack engine logfiles? (Aka you only see desktop logfiles in the logfolder?)

**Comment by krasenferdinandov** [comment]
no, I just already have tried x32 version and the problem is still there...

На ср, 18.09.2019 г. в 11:47 ч. Joris Goosen <notifications@github.com>
написа:

**Comment by JorisGoosen** [comment]
@krasenferdinandov but to help me fix the problem:
Could you turn on logging and see if you have engine logfiles?
Or do you only see desktop logfiles?

**Comment by boutinb** [comment]
Hello  @diogenesbido & @krasenferdinandov 
I have tried many configurations on different PC's, but I cannot reproduce this problem. So it seems that JASP cannot work properly with a peculiar component/feature/setting on Windows PC. It would help me a lot if you answer these questions so that I can maybe find the source of this problem.
. The problem might come from the character set used in your PC. Which language do you use on your PC? Do you use normal latin letters, special latin letters (like ü, ø, ę) or another alphabet?
. The problem might come from permission problem. Is your PC from your work, or is it your own PC. Has the account you use an administrator right (you can install anything without asking someone else), or do you need to use a special account to install JASP?
. The problem might also come from a particular hardware/Operating system. Do you use Windows 10? And which edition, is it Windows 10 Home edition, Windows 10 Enterprise, Windows 10 Education, Windows 10 Mobile?
. Also it is quite important for us to know exactly which analysis makes this crash: can you try both Descriptives Statistics and Reliability Analysis and tell us which one crashes?

We have also a version that does not need installation (http://static.jasp-stats.org/JASP-0.11.0.3-x64.zip), can you download it, unzip it, and check if this JASP version has the same problem?

I know it is a lot of questions, but we need your help to solve this problem.
Kind regards,
Bruno

**Comment by krasenferdinandov** [comment]
Thank you for questions. I will answer as soon as I can after I check these
properties you had proposed.
I looking forward version 11,0...
Best wishes,
Krasen

На пн, 30.09.2019 г. в 11:49 ч. bruno boutin <notifications@github.com>
написа:

**Comment by boutinb** [comment]
Hallo, I have found something that could help your problem.
Could you try this version: http://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-WindowsJaspResultsHotfix-4fac875f1aaccfc0547bb72d5413341506536b0d.msi
This is an 'unsigned' version, that means that your PC will warn you that it does not know from whom it is. It might be also slower.
Can you try both Descriptives Statistics & Reliability Analysis?

**Comment by krasenferdinandov** [comment]
Thank you and I appreciate your concerns. Everything with Descriptives and
Reliability is ok, Only manova, confirmatory and logistic analysis still
generate errors. I will try this version and will feed you back as soon as
I can.


На вт, 1.10.2019 г. в 15:41 ч. bruno boutin <notifications@github.com>
написа:

**Comment by krasenferdinandov** [comment]
Version 11.0 is working perfectly, not taking the lag into account. Thank
you very much. It is perfectly compatible with Win10.
What about mediation analysis? It is not included into the analytic package
anyway...

Best regards!
Krasen

На вт, 1.10.2019 г. в 19:30 ч. Красен Фердинандов <
krasenferdinandov@gmail.com> написа:

**Comment by AlexanderLyNL** [comment]
Hi Krasen, 

Thanks for getting back to us. The hotfix seems to work. I'll close this issue then. Please open a new issue if the problem reoccurs. 

Cheers,
Alexander

PS: You can find mediation under SEM.

**Comment by krasenferdinandov** [comment]
I just found another issue:
[image: save failed.png]

На вт, 1.10.2019 г. в 23:46 ч. AlexanderLyNL <notifications@github.com>
написа:

**Comment by boutinb** [comment]
Sorry, but the image was not send. Can you explain how you came to this error ( a reproduction path)?
Bruno

**Comment by krasenferdinandov** [comment]
[image: save failed.png]
I've tried to save the job that I have been doing and the errors just
appeared.

На ср, 2.10.2019 г. в 10:25 ч. bruno boutin <notifications@github.com>
написа:

**Comment by boutinb** [comment]
Can you tell me exactly what you do? You load a data file, then which analysis do you open, which option do you select? And do you click on the save as menu? And which error do you get exactly (I cannot see the png file in github).
Can you send me also the JASP log files (in JASP: go to File Menu/Preferences/Advanced).
Thanks,
Bruno

**Comment by boutinb** [comment]
I cannot see the png file, because apparently you answer directly via email: you have to answer via GitHub if you want to attach a file.

**Comment by krasenferdinandov** [comment]
After I get the data file, I finished job and try to close the program,
after answering me to save the job, I tried and the problem had appeared.

save failed
unable to save file
boost::filesystem::file_size

На пт, 4.10.2019 г. в 13:06 ч. bruno boutin <notifications@github.com>
написа:

**Comment by boutinb** [comment]
Can you save it on an OSF account?

**Comment by JorisGoosen** [comment]
Seeing as how the OP hasn't responded for quite a while and this is actually a different issue as far as I can see I now close this issue.
