### ISSUE TITLE
Jasp 0.10.2 doesn't display results

### ISSUE THREAD

**Issue by sblnin** [jasp-stats/jasp-issues#476]
On my desktop (macOS Majave 10.14.6), JASP 0.9.2. works fine. When I try to install JASP 0.10.2, when I first start JASP, it always crashes without any error messages. If I start it once more, it opens, but now the results window on the right always stays empty
whatever analysis I setup. The same jasp file, opened in 0.9 works just fine. 
Mysteriously, on my laptop runing the same OS, 0.10.2 works just fine. Does anyone have an idea what might be the issue? Does version 10.2 use something version 9 does not? (Java or the like?).

**Comment by JorisGoosen** [comment]
Hey @sblnin we changed the interface of JASP when we switched to 0.10.

There seems to be a problem on some Macs (#390) where the results do not show. I do not know what causes this. But I've added a solution in JASP: software rendering.

You can enable it by going to `Preferences -> Advanced -> Safe Graphics` and then restart JASP. I think the results should show up now.

**Comment by sblnin** [comment]
Fantastic. This does solve the issue. Thank you so much

**Comment by psywang** [comment]
Thank u, I have solved this issue.
