### ISSUE TITLE
No new folder to save jasp result with Debian OS

### ISSUE THREAD

**Issue by jean-staps** [jasp-stats/jasp-issues#477]
Hello,
I work with debian 9 and jasp 0.10.2, i can't save my result in a desired folder. My result (*.jasp) are saved in a "default" folder (for example /run/user/1000/doc/a51846cf/ - see image herewith).
![bug_jasp_debian 9](https://user-images.githubusercontent.com/54662922/64615083-1e86e900-d3da-11e9-835e-167b589af94a.png)

Best regards!
Jean

**Comment by JorisGoosen** [comment]
@jean-staps could you post the output if you run `flatpak --version` in a terminal?

**Comment by JorisGoosen** [comment]
And, if you actually check the folder you selected, is the file there?

**Comment by jean-staps** [comment]
Hi,
If i run flatpak --version i obtain Flatpak 0.8.9
If i check the folder i selected, the file is not here.
Moreover this morning when i try to open my jasp file i can't because my jasp file disapear (i can't see them from the jasp browse menu and with the debian file explorer)
I run jasp on windows and no problem.
![bug](https://user-images.githubusercontent.com/54662922/64697856-0c707d80-d4a2-11e9-9bd7-cadf18d8620e.png)

Thanks!!

**Comment by jean-staps** [comment]
Hi,
Ok problem solved, JASP work well on debian now!
Thanks a lot!

**Comment by JorisGoosen** [comment]
Great, enjoy using it!
