### ISSUE TITLE
Entire analysis output failed to open; error message appeared

### ISSUE THREAD

**Issue by ataylor92110** [jasp-stats/jasp-issues#478]
* JASP version: 0.9.2
* OS name and version: Windows 10 Enterprise
* Analysis: Independent Samples t-test
* Bug description: I closed JASP earlier this morning after I performed very many analyses last night. I did save the file as per instructions on  screen. I had performed a large number of independent samples t-tests. In addition, I had copied  and pasted into the "notes" section an large number of summary descriptive statistics.  NOTE; n between  closing and re-opening I updated the data set by adding in several  participants' data that was late in arriving but otherwise I didn't do anything unusual to the data set. 
* Add JASP files as a zip: 

I  don't know how to save my JASP files as a zip. When I am in  Jasp all I see as options are to save as a JASP file. And  when I try to save my output I'm only given html as an option. I'm so confused :-( 

* Screenshot: ![jasp_error_message](https://user-images.githubusercontent.com/55157337/64639337-83cbe180-d3bc-11e9-899e-6ebbf949a751.png)
* Expected behaviour: The old output would show up (I have done this several  times in the past with other data sets) and then I could do more analyses. I did wonder, since this is the first time I ever made changes to  a prior data set how that would affect the analyses? Would I have to reanalyze with the larger data set? Or would  it automatically redo the analyses based on  the added data points? 
* Steps to reproduce:

**Comment by TimKDJ** [comment]
> JASP version: 0.9.2

We're about to release version 0.11 -- we made a huge number of improvements so I would definitely recommend upgrading

> The old output would show up (I have done this several times in the past with other data sets) and then I could do more analyses. I did wonder, since this is the first time I ever made changes to a prior data set how that would affect the analyses? Would I have to reanalyze with the larger data set? Or would it automatically redo the analyses based on the added data points?

When you make changes to the data file that is associated with a .jasp file, then the next time you open that .jasp file JASP will update your dataset and all analyses. We're actually in the process of investigating if this analysis refresh works entirely correct. We noticed that renaming variables might break some things. Did you rename any variables that were previously in an analysis?

It could also be specifically related to dataset you're analyzing now:
- Did you add cases that made the row count exceed 3000?
- Did you remove cases that made the row count less than 3?

You cannot do a shapiro-wilk test when the number of observations is not between 3 and 3000

**Comment by ataylor92110** [comment]
Thank you for the reply. See my answers to your questions below.

Annette

Annette Kujawski Taylor, Ph.D.
Professor, Retired, Psychological Sciences
University of San Diego
taylor@sandiego.edu


On Wed, Sep 11, 2019 at 1:04 AM Tim de Jong <notifications@github.com>
wrote:

> JASP version: 0.9.2
>
> We're about to release version 0.11 -- we made a huge number of
> improvements so I would definitely recommend upgrading
>
> The old output would show up (I have done this several times in the past
> with other data sets) and then I could do more analyses. I did wonder,
> since this is the first time I ever made changes to a prior data set how
> that would affect the analyses? Would I have to reanalyze with the larger
> data set? Or would it automatically redo the analyses based on the added
> data points?
>
> When you make changes to the data file that is associated with a .jasp
> file, then the next time you open that .jasp file JASP will update your
> dataset and all analyses. We're actually in the process of investigating if
> this analysis refresh works entirely correct. We noticed that renaming
> variables might break some things. Did you rename any variables that were
> previously in an analysis?
>

No,  I merely added three cases. Nothing was renamed. Only data for three
additional participants were added.

> It could also be specifically related to dataset you're analyzing now:
>
>    - Did you add cases that made the row count exceed 3000?
>    - Did you remove cases that made the row count less than 3?
>
> You cannot do a shapiro-wilk test when the number of observations is not
> between 3 and 3000
>

No, the number went from 136 to 139. And I don't think I did the
shapiro-wilk test. Hmmm...now I wonder if I should have ;-)

I think I might have figured it out: I was saving the file as a CSV file
but somehow, mysteriously, honest, I did NOT do it, it started to save
itself as a txt file! I don't  know how and did not notice. I wonder if
when I re-opened JASP if that messed everything up? But it was a CSV file
originally....must have been because how else could I have done 15 t-tests?

**Comment by TimKDJ** [comment]
JASP can also read .txt files, so it may have been that format all along?
Could you maybe attach the .jasp file that contains the old analyses and the data file that you edited? You can send them to me at t.dejong3 [at] uva.nl

**Comment by vandenman** [comment]
closed due to inactivity (feel free to reopen if the issue is still relevant).
