### ISSUE TITLE
Post Hoc Error

### ISSUE THREAD

**Issue by yuriamos** [jasp-stats/jasp-issues#479]
When i try to do a post hoc for a significant factor of my ANOVA, Jasp show this error:

**Error in `[<-.data.frame`(`*tmp*`, 't.ratio', value = c(1.13525668517033, : replacement has 3 rows, data has 1

Stack trace
analysis(dataset = dataset, options = options, perform = perform, callback = the.callback, state = oldState)

.resultsPostHoc(referenceGrid, options, dataset, fullModel)

`[<-`(`*tmp*`, 't.ratio', value = c(1.13525668517033, 2.06055957410306, 1.01832893406019))

`[<-.data.frame`(`*tmp*`, 't.ratio', value = c(1.13525668517033, 2.06055957410306, 1.01832893406019))

stop(sprintf(ngettext(N, 'replacement has %d row, data has %d', 'replacement has %d rows, data has %d'), N, n), domain = NA)**

Can anyone help me? thk

**Comment by TimKDJ** [comment]
Could you please fill out the template for bug reports:

* JASP version:
* OS name and version:
* Analysis:
* Bug description:
* Add JASP files as a zip:
* Screenshot: 
* Expected behaviour:
* Steps to reproduce: 
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Comment by yuriamos** [comment]
JASP version: 0.10
OS name and version: macOS Mojave version 10.14.5
Analysis: Repeated Measures ANOVA GORT
Bug description: "This analysis terminated unexpectedly"
Add JASP files as a zip: [DATASET ANOVA.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/3599824/DATASET.ANOVA.jasp.zip)
Screenshot:
![Schermata 2019-09-11 alle 10 44 11](https://user-images.githubusercontent.com/55183444/64682105-2b124c80-d481-11e9-9bb6-a7d59f41f2a2.png)

Expected behaviour: Jasp show the post hoc test
Steps to reproduce: Go to "Repeated Measures ANOVA GORT", open Post Hoc Tests, move "EMOTION" to right

**Comment by TimKDJ** [comment]
Thanks! I can reproduce the problem. We're currently performing a rewrite on the ANOVA code and I'll make sure a fix for this is incorporated.
