### ISSUE TITLE
Move analyses within JASP

### ISSUE THREAD

**Issue by kevinvschie** [jasp-stats/jasp-issues#481]
* Enhancement: Move analyses in JASP.
* Purpose: Easily move analyses in JASP
* Use-case: Sometimes you are requested to do an extra analysis (e.g., by a reviewer) or you simply realized you have forgotten to do one. Now, you can perform that analysis, but JASP will add it as the last analysis you have performed. Though this solution is fine, for clarity you usually want to place it near related analyses. Now that isn't possible.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be great if the analyses you had done were movable blocks. So you can reorder which analysis is first, second, etc. 

**Describe alternatives you've considered**
 

**Additional context**

**Comment by TimKDJ** [comment]
It is actually possible since JASP 0.12. If you long press the analysis then you can move it around.
Are you already on this version, or is this behaviour not intuitive enough?

**Comment by AlexanderLyNL** [comment]
![changeAnalysisOrder](https://user-images.githubusercontent.com/10271675/64693636-f8278300-d497-11e9-91c2-6c692423b0fc.gif)

**Comment by kevinvschie** [comment]
Ah I see. I have version 0.10 (the only one my work allows me to download).
It's great that you can move stuff around in the newer version, but even
there I'd say that it is still not intuitive enough. Usually when you're
able to move stuff around you often see a little icon of three short
horizontal lines placed underneath each other. Perhaps that could be added
to make it even more clear?

**Comment by TimKDJ** [comment]
Yeah, we thought about changing the cursor, but the problem is that a short click opens the analysis form. Only a long click serves the purpose of dragging. So there are two different types of behaviour we need to convey. We did add a tooltip to make it more clear though.

Hopefully your work will allow you to upgrade to our newer versions; 0.11 is right around the corner :)

**Comment by kevinvschie** [comment]
Is there anywhere I can see what added features are to the latest (two)
updates? I might be able to convince the admin here if there are
functions in the new JASP versions I might actually need.

**Comment by TimKDJ** [comment]
https://jasp-stats.org/release-notes/
