### ISSUE TITLE
Change minimum and maximum of y-axis

### ISSUE THREAD

**Issue by zieglesth** [jasp-stats/jasp-issues#482]
* Enhancement:
* Purpose:
* Use-case:

**Is your feature request related to a problem? Please describe.**
The graphs in JASP are great, much better than in SPSS. However, one cannot change the minimum and maximum of the y-axis. This would be necessary if there are two different graphs and you want to juxtapose them and have the same min and max to make measures comparable. 

**Describe the solution you'd like**
It would be great to be able to change minimum and maximum of the y-axis in graphs as it is possible in SPSS. Please, invent a solution for changing minimum and maximum of the y-axis in graphs. 

**Describe alternatives you've considered**
 

**Additional context**

**Comment by TimKDJ** [comment]
We're actually working on that as we speak (as part of plot editing). It's a big endeavour though, so it may be a couple of months.

**Comment by AugustOlsson** [comment]
Hi,

There is as far as I can see still no possibility to edit the y-axes range in Jasp. It is especially disturbing that one can even get different y-axis when one has three variables and uses one of them for separate plots. I can get one Y-axis for one plot and another one for the other even though all data comes from the same analyses.

PS. There seems to be a potential bug in the repeated-measure BANOVA graph tool, at least when plotting a mixed design. The intervals in the graph no longer corresponds to the intervals described in descriptives. The descriptives are the same as in the previous jasp-version (when it also corresponded to the intervals). Is this a bug or an effect of the graph including both between and within-subject variance?

**Comment by EJWagenmakers** [comment]
Hi AugustOlsson,

You raise both a feature request and a potential bug report. Wrt the first, the upcoming version of JASP will have a graph editor that allows you to change the axes ranges (and a number of other things, like tick marks and fonts). We are testing this version now and we hope to release it soon. Wrt the second, I recommend you make a separate request together with some screenshots so we can address this efficiently. So I am closing this issue.

E.J.

**Comment by AugustOlsson** [comment]
Hi EJ,

Sorry for posting two things in one message. That was thoughtless of me. Sounds like a great addition with the graphtool (I would be pleased with just automatically having the same y-axis on graphs created within the same analysis). Thank you for your great work. 

I'll write a more detailed bug-report when I have some time on my hands!

August
