### ISSUE TITLE
mediation analysis: estimator unknown

### ISSUE THREAD

**Issue by Mosen111** [jasp-stats/jasp-issues#483]
* Enhancement: when one uses estimator "auto" in mediation analysis, they expect the estimator used to be reported by JASP, but apparently the estimator remains unknown to the user. This could be added.
Thanks

**Comment by vankesteren** [comment]
Added this to the footnote!

**Comment by pyoka** [comment]
Help me
How can you use JASP to analyze data with three 3 Moderating variables. For example the Moderating effects of W,X,Y on the relationship between A and B .
A- independent variable
B- Dependent variable
W,X and Y - are moderating variables
Your help will highly be appreciated
Hastings Munyenyembe
Student
JASP user
