### ISSUE TITLE
Calculations feature is not working and other issues

### ISSUE THREAD

**Issue by BridgetUT** [jasp-stats/jasp-issues#484]
I am having an issue using the compute column feature in JASP. It worked fine yesterday but now it will not seem to realize my math functions. I am doing only simply adding of columns and it is laying them out vertically and not computing, instead giving me an error and asking for the terms, while it won't allow me to drop the column names into the red areas highlighted. . any ideas??

I am not a developer so i don't know what else to provide here. Thank you.  I am using this in my class this semester and now I'm totally stuck...

* JASP version:10.2
* OS name and version: MAC high sierra
* Analysis: Formula
* Bug description: I have tried reinstalling JASP but now it won't open the program at all
* Add JASP files as a zip:
* Screenshot: 
* Expected behaviour:
* Steps to reproduce: Add variables and math formula...

**Comment by boutinb** [comment]
Hi @BridgetUT.
Sorry for the late answer. We were quite busy to release a new version (0.11). Can you try it? If you have still this problem, can you send us your JASP file?
Kind regards,
Bruno
