### ISSUE TITLE
Specification of credible interval probability for Bayesian t-test

### ISSUE THREAD

**Issue by EtzAlex** [jasp-stats/jasp-issues#485]
* Enhancement: Give user the option to specify credible intervals with percentages other than .95.
* Purpose: This would give us more flexibility in reporting our results.
* Use-case: In some cases you want to report 90%, or even 80% credible intervals. 

**Describe the solution you'd like**
 
I would prefer a small box in the options window where you input the desired probability. It could have a default entry, like other boxes, that you could change to the value you want.

**Comment by juliuspfadt** [comment]
I think this is implemented by now
