### ISSUE TITLE
Bloated JASP files?

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-issues#486]
From the forum:

"Super big fan of your work. Was just curious what bloats JASP files so much.

Example 1: Data file is 27.9 kB, associated JASP file is 47.6 MB (!). There are two 2x3 repeated-measures ANOVAs in there, each with 15 post-hoc tests and 1 graph at 300 dpi.

Example 2: Data file is 173.0 kB, associated JASP file is 917 MB (!!!). This has an embarrassingly big repeated-measures ANOVA in there (2*2*24), with two graphs at 300 dpi.

It can't just be the images, given the huge difference between the files. Are the values saved in a memory-intensive way, or are a lot of in-between steps saved too?"

My initial guess was that, if it's the Bayesian ANOVA, the jasp file might save the samples too...

**Comment by JorisGoosen** [comment]
917MB! :o

That is way too much! 
I think the initial guess is probably right, maybe a lot of state is stored? @JohnnyDoorn did you notice this while rewriting the analyses?

**Comment by JohnnyDoorn** [comment]
Could this be related to that bug where JASP is not clearing the state cache?
I asked on the forum  whether its a Bayesian or freq analysis, hopefully that will narrow it down =)

**Comment by JorisGoosen** [comment]
@JohnnyDoorn it might.. But only if it's a jaspResults analysis already. Which I guess it isn't yet?

**Comment by AlexanderLyNL** [comment]
It's not in jaspResult yet.

**Comment by AlexanderLyNL** [comment]
It would be interesting to have there csv and the inputs, then we can see if the same occurs with jaspResult.

**Comment by JorisGoosen** [comment]
Yeah my thought exactly

**Comment by JorisGoosen** [comment]
@JohnnyDoorn did you manage to get your hands on the csv and the steps orig-poster took?

**Comment by JorisGoosen** [comment]
@JohnnyDoorn *BUMP* (Close this issue if nothing happened I guess?)

**Comment by JohnnyDoorn** [comment]
Heard nothing, sent an email a while ago but no luck..
