### ISSUE TITLE
Variable jumps out of 'Variables' box after name is changed

### ISSUE THREAD

**Issue by djdekker** [jasp-stats/jasp-issues#487]
* JASP version: **0.10.2**
* OS name and version: **macOS Mojave 10.14.6**
* Analysis: **Descriptive Statistics** (probably any analysis that has a 'Variables' box)
* Bug description: **When a variable is included in an analysis, it is listed in the 'Variable' box on the interface sheet. After changing the variable name, the variable jumps out of the 'Variables' box. The analysis remains unchanged.**
* Screenshot: **https://www.youtube.com/watch?v=PUFiOAs7RfM**
* Expected behaviour: **I expect the variable to remain in the 'Variable' box with its new name.**

**Comment by boutinb** [comment]
Yes, I have seen already this problem. I will have a look how to solve it.

**Comment by djdekker** [comment]
With JASP 0.13 this does not happen anymore. Closing the issue.
