### ISSUE TITLE
Assumption checks section in correlation matrix procedure

### ISSUE THREAD

**Issue by vicenteinefo** [jasp-stats/jasp-issues#488]
* Enhancement: To add an “Assumptions Check” section to check normality assumptions for the Pearson’s correlation coefficient. 
* Purpose: To be sensible respect the other statistics procedures
* Use-case: To check normality assumption in order to implement the appropriate correlation coefficient of the data

<img width="1360" alt="Captura de pantalla 2019-09-16 a las 11 32 37" src="https://user-images.githubusercontent.com/29978768/64947732-e9fdac00-d875-11e9-8635-797fdcfc27c2.png">

**Comment by Kucharssim** [comment]
This feature is implemented for the next release.
