### ISSUE TITLE
Improvement of assumption checks section in ANOVA procedure

### ISSUE THREAD

**Issue by vicenteinefo** [jasp-stats/jasp-issues#490]
* Enhancement: To add assumption checks of normality of residuals (Shapiro will test)
* Purpose: To have an objective assessment of normality
* Use-case:

**Additional context**

<img width="289" alt="Captura de pantalla 2019-09-16 a las 11 52 27" src="https://user-images.githubusercontent.com/29978768/64948974-76a96980-d878-11e9-8974-cbe2997b1632.png">

**Comment by tomtomme** [comment]
I would say the Q-Q plot is sufficient. I guess Shapiro-Wilk is also not possible for more than one independent variable - is it? There is also nothing that is more objective with Shapiro-Wilk, since you can choose the alpha level to your liking. Correct me if I am wrong.

**Comment by vicenteinefo** [comment]
And what about add an option to Save a the residuals in a new computed variables in the dataset and then would be possible to apply the Shapiro will test for this new variable?

**Comment by tomtomme** [comment]
@vicenteinefo 
I realized we have already a multivariate shapiro-wilk-test within MANOVA. The multi is problably related to the DVs there. But it really would be fair to have the same options of testing normality accross the board. 

So we have:
- QQ-Plots in Regression & AN(C)OVA & t-Tests
- Shapiro-Wilk in MANOVA & t-Tests
- Rainclouds in AN(C)OVA & t-Tests

So would be cool to have all 3 everywhere, if possible (rainclouds probably not important for regression since we have a similar residual plot already.

**Comment by JohnnyDoorn** [comment]
Great summing up @tomtomme - this is more or less in line with what I want to implement in the next months (QQ plots in more analyses, export residuals in anova/regression, see if AIC/BIC can easily be added there), now that I have some more time to deciate to JASP again.

**Comment by tomtomme** [comment]
Some stuff in progress now: https://github.com/jasp-stats/jaspTTests/pull/240

**Comment by wpsilvestre** [comment]
@tomtomme since the #2695 wil be tracked here, what is the status of such an implementation? Is it feasible to add such a featur to ANOVA?

**Comment by tomtomme** [comment]
@wpsilvestre 
This is the status from my summing up above:

- Kolmogorov-Smirnov & shapiro-wilk within (RM) AN(C)OVA & Regression are currently missing, however there we can now - with 0.19beta - export residuals to test in distribution module, where SW and KS are available. This is not super-user-friendly but a step in the right direction. I cannot say if and when SW and KS will be available directly in those modules. But I would guess that it is feasible

**Comment by wpsilvestre** [comment]
@tomtomme , it would be great if this test are made available directly in ANOVA module with the homoscedasticity test and Q-Q plots. But I also understand that this takes time and effort. Thanks for the feedback.

**Comment by TarandeepKang** [comment]
To avoid duplication of #2726 ( now closed) 

The most widely used test is the Hosmer-Lemshshow for logistic regression and other glms. But it is no longer necessarily considered the best. The le Cessie-van Houwelingen-Copas-Hosmer shows better performance in simumulations and is recommended by Frank Harrell in his RMS textbook.

The Hosmer-lemeshow is implemented in a few different versions for logistic regression and other glms here
https://cran.r-project.org/web/packages/generalhoslem/index.html

And

le Cessie-van Houwelingen-Copas-Hosmer is available

https://search.r-project.org/CRAN/refmans/DescTools/html/HosmerLemeshowTest.html

or

https://www.rdocumentation.org/packages/rms/versions/6.8-0/topics/residuals.lrm

Hosmer, D. W., Hosmer, T., Le Cessie, S., & Lemeshow, S. (1997). A Comparison of Goodness-of-Fit Tests for the Logistic Regression Model. Statistics in Medicine, 16(9), 965–980. [https://doi.org/10.1002/(SICI)1097-0258(19970515)16:9<965::AID-SIM509>3.0.CO;2-O](https://doi.org/10.1002/(SICI)1097-0258(19970515)16:9%3C965::AID-SIM509%3E3.0.CO;2-O)
Hosmer, D. W., & Lemesbow, S. (1980). Goodness of fit tests for the multiple logistic regression model. Communications in Statistics - Theory and Methods, 9(10), 1043–1069. https://doi.org/10.1080/03610928008827941
le Cessie, S., & van Houwelingen, J. C. (1991). A Goodness-of-Fit Test for Binary Regression Models, Based on Smoothing Methods. Biometrics, 47(4), 1267–1282. https://doi.org/10.2307/2532385
LEMESHOW, S., & HOSMER, D. W., JR. (1982). A REVIEW OF GOODNESS OF FIT STATISTICS FOR USE IN THE DEVELOPMENT OF LOGISTIC REGRESSION MODELS1. American Journal of Epidemiology, 115(1), 92–106. https://doi.org/10.1093/oxfordjournals.aje.a113284

**Comment by JohnnyDoorn** [comment]
@TarandeepKang thanks for the suggestion! So I guess the best one to add would be the Cessie-van Houwelingen-Copas-Hosmer?
As for the tildwell test (adding log of the predictor and adding the interaction?), this seems better to leave manually specified. 
It might have to wait for the next JASP version though, since we are already in the testing phase for 0.19. 
I did recently add a plot to logistic regression to visualize the model's predictions - I am not entirely sure, but could this also be used to test the linearity of the logit? It only shows the model predictions and not the data, so I don't think so..
<img width="509" alt="image" src="https://github.com/jasp-stats/jasp-issues/assets/15704203/8bee0627-b8b5-49fc-833d-4b9ed2ba246a">

**Comment by TarandeepKang** [comment]
Hi @JohnnyDoorn, If I were you I would use the DescTools implementation and offer both maybe with the usual, tick box? I don't think you can use this plot in that way, I've never seen that way, but that doesn't mean is not possible. I'm not a statistician like you, just an interested user. As for the Menard references that Thomas gives above, I confess I have never come across that test, so you may need to do some more research? I don't understand the question (if indeed you're asking one) about the box-Tidwell test? Apologies if I being obtuse!

Best,

Tarandeep

**Comment by JohnnyDoorn** [comment]
HI @TarandeepKang 
No worries - I'm just curious what could be useful for users! I'll look into the tickboxes for the Cessie and Hosmer tests from Desctools, that seems easy enough.

**Comment by TarandeepKang** [comment]
Sorry just one more thing! It is worth pointing out that the generalhoslem package also contains versions of this test that are suitable for ordinal and multinomial regression ()? Could you consider adding those to the other GLMs?.

**Comment by PerPalmgren** [comment]
Great if a test for linearity for the logistic module was implemented as it is one important assumption to be tested in logistic regression, The assumption requires there to be a linear relationship between the continuous independent variables and the logit transformation of the dependent variable. Now my students have to leave JASP and test this in SPSS (and where it is a bit cumbersome). Great if JASP could provide a more elegant way to test this assumption for logistic regression.

**Comment by EJWagenmakers** [comment]
As a temporary workaround, you can do this manually: use compute columns to create the logit of the dependent variable, as well as squared versions of the independent variables. Then use linear regression and assess whether the quadratic term(s) are worth including.

**Comment by EJWagenmakers** [comment]
But I agree it would be good to include that test explicitly. @vandenman we have it for correlation already, right? Maybe we should add it to regression and logistic regression too...

**Comment by vandenman** [comment]
We have it also for the t-tests, probably a good idea to add it here too.

**Comment by tomtomme** [comment]
maybe lets track all this now here: https://github.com/jasp-stats/jasp-issues/issues/2878
This thread is a bit confusing

**Comment by PerPalmgren** [comment]
For Logistic regression will a possibilty to test the assumption of "linearity in the logit" by included? As the litterature points aut that one of the most important assumptions in logistic regression is the  linear relationship between any continuous independent variables and the logit transformation of the dependent variable.
