### ISSUE TITLE
Bubble chart and distribution plot for 2 or more variables

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#491]
* Enhancement: Bubble plot and distribution plot for 2 or more varaibles
* Purpose: Enrich JASPs features in exploratory data analysis
* Use-case: exploratory data analysis

**Is your feature request related to a problem? Please describe.**
Already in 1962 John W. Tukey criticized parts of statistics to focus too much on confirmatory analysis and a lack of methods for exploratory data analysis. See https://projecteuclid.org/euclid.aoms/1177704711
From my point of view little has changed. We have a diverse spectrum of plots available, but few use them because statistics-software often does not implement them. Also tudents learn a myriad of tests and then forget about the descriptive basics because they were also just numbers. To visualize the basics better might help remember them for longer. 

**Describe the solution you'd like**
Add bubble chart and distribution plot for 2 or more varaibles to the descriptives section. Then maybe add polar density plot, radar chart, ring plot, barcodes, area chart, mosaic plot, array of icons etc. as you go.

For plot examples and also some R code see
- https://www.washingtonpost.com/graphics/2019/local/school-diversity-data/?noredirect=on
- https://flowingdata.com/2019/04/16/income-level-breakdowns-by-state/
- https://simplystatistics.org/2019/08/28/you-can-replicate-almost-any-plot-with-ggplot2/
- https://flowingdata.com/2019/08/21/how-to-make-a-polar-density-plot-in-r/
- https://www.spiegel.de/wissenschaft/natur/wetter-daten-rekord-sommer-wie-warm-war-2019-im-vergleich-zu-2018-a-1280048.html
- https://de.wikipedia.org/wiki/Diagramm

The bubble chart was also requested here: https://github.com/jasp-stats/jasp-issues/issues/453

**Comment by EJWagenmakers** [comment]
Good ideas! We need more of these plots. A team in the US is working to add some of these, I believe.

**Comment by tomtomme** [comment]
<img width="960" alt="Screenshot_20191220_190552" src="https://user-images.githubusercontent.com/4428185/71280582-e6d5f880-235b-11ea-8c0f-61b5b91e0b93.png">

I made this for my students lately. Maybe it can be used as a guideline for the most important plot types. Some boxes have one or more alternatives of otherwise very similar plots. Of those only one is really needed.

**Comment by EJWagenmakers** [comment]
I think this organisation is very helpful. @TimKDJ @boutinb let's discuss how we can best use this to our advantage.

**Comment by tomtomme** [comment]
As some of the above charts are now available in jasps visual modeling I will close this for now. There are still gaps like area-charts, stacked charts, ring chart, barcode and radar / spider / web chart. But for those I will open a new issue.
