### ISSUE TITLE
MAD incorrect value?

### ISSUE THREAD

**Issue by vicenteinefo** [jasp-stats/jasp-issues#492]
* JASP version: 0.10.2
* OS name and version: Mac OS 10.14.6
* Analysis: Descriptive statistics
* Bug description: MAD seems to be incorrectly calculated
* Add JASP files as a zip:
[MAD bug.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/3621053/MAD.bug.jasp.zip)

* Screenshot: 

<img width="1360" alt="Captura de pantalla 2019-09-17 a las 13 30 35" src="https://user-images.githubusercontent.com/29978768/65038073-67491f80-d94f-11e9-8141-0f1c9e1ca3b7.png">

* Expected behaviour: When I compute MAD in excel following either of these instructions. https://www.youtube.com/watch?v=GFgXIfOtYC4 or https://en.wikipedia.org/wiki/Median_absolute_deviation

See attached excel file below

[MAD bug.zip](https://github.com/jasp-stats/jasp-issues/files/3621051/MAD.bug.zip)

The result is different from JASP 
Excel MAD = 2.00 vs JASP MAD = 2.97

**Comment by boutinb** [comment]
Hi @vicenteinefo, the MAD value that gives JASP is the default value given by R:

> Compute the median absolute deviation, i.e., the (lo-/hi-) median of the absolute deviations from the median, and (by default) adjust by a factor for asymptotically normal consistency.

This adjustment is in fact a constant 1.4826, and 2 * 1.4826 = 2.9652
Maybe we should call it MAD Adjusted.

**Comment by vicenteinefo** [comment]
Cool, thanks for the explanation, I’ll update my notes for my students

**Comment by AlexanderLyNL** [comment]
Bruno added both options to the descriptives. In the newest version, you'll be able to choose both of them.
