### ISSUE TITLE
Distribution plot not updating for 'split' variables

### ISSUE THREAD

**Issue by fsnagovsky** [jasp-stats/jasp-issues#493]
* JASP version: 0.10.2

* OS name and version: Mac OS Mojave 10.14.6

* Analysis: Descriptive statistics / distribution plot

* Bug description: When running descriptive statistics for a variable by a 'split' variable, the frequency tables are correct, but the distribution plots are not. Specifically, the distribution plots for each level of the split variable are the same as the overall distribution. See attached screenshots, and screenshots for JASP 0.9.2.0 for comparison. 

* Add JASP files as a zip: 
[2019_POLS1009_AES_Dataset.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/3628602/2019_POLS1009_AES_Dataset.jasp.zip)

* Screenshot: 
Frequency table for JASP 0.10.2
<img width="1280" alt="Frequency tables JASP 0 10 2" src="https://user-images.githubusercontent.com/44389637/65191999-12291d00-dab9-11e9-9cfa-539ce148411b.png">

Distribution plot for JASP 0.10.2
<img width="1280" alt="Distribution plots JASP 0 10 2" src="https://user-images.githubusercontent.com/44389637/65192020-1ead7580-dab9-11e9-9fab-430f4b0fc0e3.png">

Distribution plot for JASP 0.9.2.0 (for comparison)
<img width="1280" alt="Distribution plots JASP 0 9 2 0" src="https://user-images.githubusercontent.com/44389637/65192030-24a35680-dab9-11e9-9b0a-820217fe7265.png">

* Expected behaviour: Distribution plots for each level of the 'split' variable.

* Steps to reproduce: 
1. Go to 'Descriptives'
2. Click on 'Descriptive Statistics'
3. Add 'polint' (as an example - others produce the same error) to 'Variables'
4. Add 'sex' (as an example - others produce the same error) to 'Split'
5. Check 'Frequency Tables'
6. Under 'Plots', check 'Distribution plots'
7. See error

**Comment by EJWagenmakers** [comment]
We definitely need to fix this before the new release.

**Comment by AlexanderLyNL** [comment]
Fixed in 0.11, out soon.
