### ISSUE TITLE
Bland-Altman plots in JASP

### ISSUE THREAD

**Issue by aliburdett** [jasp-stats/jasp-issues#494]
* Enhancement: Add ability to generate Bland-Altman plots in JASP
* Purpose: When analysing agreement between two methods of measurement, it is usual/useful to be able to display results as a plot of difference versus mean for each data pair, alongside bias and 95% confidence LoAs
* Use-case: Assessing level of agreement between two different measurement methods

**Is your feature request related to a problem? Please describe.**
Correlation plots can be misleading when verifying level of agreement between two different measurement methods.  A Bland Altman plot gives a much better visualisation of the level of agreement.

**Describe the solution you'd like**
Ability to generate Bland-Altman plots as described in:  "Statistical Methods for Assessing Agreement Between Two Methods of Clinical Measurement", J.Bland, D.Altman, Lancet, 1986; i: 307-310

**Describe alternatives you've considered**
 

**Additional context**

**Comment by EJWagenmakers** [comment]
Good suggestion, thanks!

**Comment by DrMarkGS** [comment]
To add to that the non-parametric version - Passing-Bablock regression. R Package ‘mcr’
Cheers
Mark

**Comment by sinisalakic** [comment]
To join the measurement agreement party: maybe you could incorporate Lin's concordance correlation coefficient (readily available in several R packages)?

See:
[What is Lin's CCC?](https://www.statisticshowto.datasciencecentral.com/concordance-correlation-coefficient/)
[Comparing linear r and CCC](https://academic.csuohio.edu/kneuendorf/c63310/CorrsCompared10.pdf)
[One R package calculating CCC](https://cran.r-project.org/web/packages/agRee/agRee.pdf)
