### ISSUE TITLE
QGLXContext: Failed to create dummy context

### ISSUE THREAD

**Issue by allefeld** [jasp-stats/jasp-issues#497]
Installed JASP under Debian 10 via flatpak. Starting it results in an error message:

```
$ flatpak run org.jaspstats.JASP
QGLXContext: Failed to create dummy context
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
failed to acquire GL context to resolve capabilities, using defaults..
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
```

Because it appears to be an OpenGL related error, I thought it has to do with the Nvidia driver. I followed this guide: https://www.linuxuprising.com/2018/06/how-to-get-flatpak-apps-and-games-built.html
However, the correct runtime for the driver version (418.74) is already installed:

```
$ flatpak list
Description                                                                          Application                        Version Branch Arch   Origin      Installation
Freedesktop Platform - Shared libraries                                              org.freedesktop.Platform           19.08.1 19.08  x86_64 flathub     system
nvidia-418-74                                                                        …desktop.Platform.GL.nvidia-418-74         1.4    x86_64 flathub     system
html5-codecs                                                                         …freedesktop.Platform.html5-codecs         18.08  x86_64 flathub     system
JASP - Offers standard analysis procedures in both their classical and Bayesian form org.jaspstats.JASP                 0.10.0  master x86_64 jasp-origin system
Adwaita theme - Adwaita widget theme matching the GNOME adwaita theme                org.kde.KStyle.Adwaita                     5.12   x86_64 flathub     system
KDE Software Development Kit - Tools and headers for developing applications using … org.kde.Sdk                                5.12   x86_64 flathub     system
Zotero - Collect, organize, cite, and share research                                 org.zotero.Zotero                  5.0.74  stable x86_64 flathub     system
```

Importantly, other OpenGL applications run flawlessly.

* JASP version: 0.10.0
* OS name and version: Debian 10 stable/buster

**Comment by JorisGoosen** [comment]
Can you update?
I changed some thigns for the new 0.11 release that "should" fix this.

**Comment by allefeld** [comment]
Thanks! But now I get another error:

```
$ flatpak run org.jaspstats.JASP

Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/ac/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

bwrap: Can't mkdir parents for /app/lib/x86_64-linux-gnu/GL: Read-only file system
```

I installed JASP as root, and then ran it as user.

**Comment by allefeld** [comment]
I also tried running as root, but get the same bwrap error.

**Comment by JorisGoosen** [comment]
Did you try restarting?

**Comment by JorisGoosen** [comment]
Also, does it work or not?

**Comment by JorisGoosen** [comment]
Hmm, it seems there was an upstream problem, what is the output of `flatpak update`?

**Comment by allefeld** [comment]
I now restarted the computer, same result. JASP stops with the error message.

```
$ flatpak update
Looking for updates…
Nothing to do.
```

**Comment by JorisGoosen** [comment]
[this issue](https://github.com/flathub/net.lutris.Lutris/issues/53) looks similar to yours.

**Comment by JorisGoosen** [comment]
Right now I am testing jasp for flathub, maybe you can try: `flatpak install --user https://dl.flathub.org/build-repo/8366/org.jaspstats.JASP.flatpakref` and see if that one works?

**Comment by allefeld** [comment]
It does. Is JASP 32 bit, or has some 32 bit components?

```
$ flatpak list
Description                                                                      Application                      Version Branch Arch   Origin      Installation
nvidia-418-74                                                                    …sktop.Platform.GL.nvidia-418-74         1.4    x86_64 flathub     system
html5-codecs                                                                     …eedesktop.Platform.html5-codecs         18.08  x86_64 flathub     system
JASP - Offers standard analysis procedures in both their classical and Bayesian… org.jaspstats.JASP               0.11.0  master x86_64 jasp-origin system
Adwaita theme - Adwaita widget theme matching the GNOME adwaita theme            org.kde.KStyle.Adwaita                   5.12   x86_64 flathub     system
KDE Software Development Kit - Tools and headers for developing applications us… org.kde.Sdk                              5.12   x86_64 flathub     system
```

I started from a clean flatpak installation, everything except JASP was pulled in automatically.

**Comment by allefeld** [comment]
Should I run that as user or as root?

**Comment by JorisGoosen** [comment]
It looks like you are using the x64 version of it so it shouldn't depend on any 32bit things. But maybe it didn't install the required GL dependencies.

**Comment by JorisGoosen** [comment]
just user

**Comment by JorisGoosen** [comment]
It seems that flatpak can't follow all dependencies properly in all cases: https://github.com/flatpak/flatpak/issues/3094

**Comment by JorisGoosen** [comment]
So then we need to figure out which one you are missing.

**Comment by JorisGoosen** [comment]
maybe manually do `flatpak install org.freedesktop.Platform.GL.default org.kde.Sdk/x86_64/5.12`

**Comment by allefeld** [comment]
Still waiting on the user install, I'll try that next.

**Comment by allefeld** [comment]
So, installing `build-repo/8366` didn't make a difference, and neither did installing `org.freedesktop.Platform.GL.default`. `org.kde.Sdk/x86_64/5.12` was already installed. I still get the same error message.

Can you give me a complete list of the dependencies?

**Comment by JorisGoosen** [comment]
Well, that is in fact the complete list of dependencies...
It might be a mismatch between your nvidia driver and the installed `org.freedesktop.Platform.GL.nvidia` you have. I just checked however and it gives like 90+ options in flathub. That might be a bit overkill.

**Comment by JorisGoosen** [comment]
What does `nvidia-smi` say on your system?

**Comment by allefeld** [comment]
Shouldn't `org.freedesktop.Platform.GL.nvidia-418-74` ensure compatibility with the driver?

```
# nvidia-smi 
Wed Sep 25 16:07:30 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.74       Driver Version: 418.74       CUDA Version: N/A      |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro P4000        On   | 00000000:21:00.0  On |                  N/A |
| 46%   31C    P8     8W / 105W |    496MiB /  8097MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1021      G   /usr/lib/xorg/Xorg                           258MiB |
|    0      1275      G   /usr/bin/krunner                               2MiB |
|    0      1277      G   /usr/bin/plasmashell                          77MiB |
|    0      1519      G   /usr/bin/akonadi_archivemail_agent             2MiB |
|    0      1539      G   /usr/bin/akonadi_mailfilter_agent              2MiB |
|    0      1543      G   /usr/bin/akonadi_sendlater_agent               2MiB |
|    0      1735      G   ...quest-channel-token=5282775868419654859   147MiB |
+-----------------------------------------------------------------------------+
```

**Comment by JorisGoosen** [comment]
Yes it should but I figured it would be nice to see this confirmed.

**Comment by JorisGoosen** [comment]
I'll see which dependencies I have here besides those listed above.

**Comment by allefeld** [comment]
Since the error message is about being unable to mkdir, is it maybe related to permissions or groups? On my system there isn't even an `/app` directory.

**Comment by JorisGoosen** [comment]
The `/app` folder is inside the flatpak sandbox, each flatpak app sees a different root filesystem, it's own.

Here my installed runtimes/apps:
```
[jasp@localhost ~]$ flatpak list
Description                                                                                                            Application                                               Version        Branch       Arch         Origin            Installation
Flatpak Developer Demo - Flatpak Developer Demo                                                                        org.flatpak.qtdemo                                        1.1.3          stable       x86_64       flathub           system
html5-codecs                                                                                                           org.freedesktop.Platform.html5-codecs                                    18.08        x86_64       flathub           system
Freedesktop SDK - Tools and headers for developing applications                                                        org.freedesktop.Sdk                                       18.08.36       18.08        x86_64       flathub           system
appstream-glib                                                                                                         org.freedesktop.appstream-glib                                           stable       x86_64       flathub           system
JASP - Offers standard analysis procedures in both their classical and Bayesian form                                   org.jaspstats.JASP                                        0.11.0         master       x86_64       jasp-origin       system
Adwaita theme - Adwaita widget theme matching the GNOME adwaita theme                                                  org.kde.KStyle.Adwaita                                                   5.12         x86_64       flathub           system
KDE Application Platform - Shared libraries used by KDE applications                                                   org.kde.Platform                                                         5.12         x86_64       flathub           system
QGnomePlatform - Qt Platform Theme aimed to accommodate GNOME settings                                                 org.kde.PlatformTheme.QGnomePlatform                                     5.12         x86_64       flathub           system
KDE Software Development Kit - Tools and headers for developing applications using the KDE application platform        org.kde.Sdk                                                              5.12         x86_64       flathub           system
QGnomePlatform-decoration - Qt Platform Theme aimed to accommodate GNOME settings                                      org.kde.WaylandDecoration.QGnomePlatform-decoration                      5.12         x86_64       flathub           system
```

**Comment by JorisGoosen** [comment]
Doesn't look very different from yours..

**Comment by allefeld** [comment]
True. I just installed them all, in the versions listed, and it doesn't make a difference.

I notice you don't have anything OpenGL-related installed. Is there maybe an option to run JASP without OpenGL?

**Comment by JorisGoosen** [comment]
Does this `flatpak install org.freedesktop.Platform/x86_64/18.08` help?

And I haven't installed those because that is a virtual machine.

There is a way to run JASP with software rendering. `flatpak run org.jaspstats.JASP --safeGraphics`, maybe that works for you?

**Comment by allefeld** [comment]
Did both, didn't help. :(

I think it doesn't even get as far as processing command line options. At least `flatpak run org.jaspstats.JASP --help` doesn't work either.

**Comment by JorisGoosen** [comment]
Maybe you could try to run the older version and see if that works with --safeGraphics?

**Comment by JorisGoosen** [comment]
And I think it might be a good plan to open an issue on flatpak or something, because this seems to be related to the runtimes somehow...

**Comment by JorisGoosen** [comment]
What flatpak version are you using btw?

**Comment by allefeld** [comment]
I found this similar flatpak issue: https://github.com/flatpak/flatpak/issues/1341

I don't understand the answers though, it seems to be about how to build the flatpak package. Maybe you can have a look?

my flatpak version is 1.2.4

**Comment by JorisGoosen** [comment]
Yeah I saw the issue but it seems to be unrelated. We just got JASP into flathub so I think when it finishes building there and is available in that main repository we can try and see if it works properly then.

It is doesn't I will open an issue in the flatpak repository because this seems to be a bug in it...

**Comment by allefeld** [comment]
I prepared a issue for flatpak referencing this one, should I post it? I'm not sure I'm the right person to do so, because I know next to nothing about flatpak (app) development.

**Comment by JorisGoosen** [comment]
Very proactive, but I think it's best to wait until it is in flathub. Maybe the dependency problem solves itself after you install it from there right?

And if it doesn't then it should be fairly easily reproducable then, which helps us because they will be more likely to help us out.

**Comment by allefeld** [comment]
Sounds good. Would be great if you could let me know when it is in flathub.
Thanks!

**Comment by JorisGoosen** [comment]
I will!

**Comment by JorisGoosen** [comment]
@allefeld JASP is now available at flathub: https://flathub.org/apps/details/org.jaspstats.JASP

**Comment by allefeld** [comment]
That was fast!

Unfortunately, the situation is unchanged:
```
$ flatpak run org.jaspstats.JASP
bwrap: Can't mkdir parents for /app/lib/x86_64-linux-gnu/GL: Read-only file system
error: ldconfig failed, exit status 256
```

I started again from a clean slate, here is the list of packages pulled in by the installation:

```
$ flatpak list
Description                                                                         Application                       Version Branch Arch   Origin  Installation
nvidia-418-74                                                                       ?esktop.Platform.GL.nvidia-418-74         1.4    x86_64 flathub system
html5-codecs                                                                        ?reedesktop.Platform.html5-codecs         18.08  x86_64 flathub system
JASP - Offers standard analysis procedures in both their classical and Bayesian fo? org.jaspstats.JASP                0.11.0  stable x86_64 flathub system
Adwaita theme - Adwaita widget theme matching the GNOME adwaita theme               org.kde.KStyle.Adwaita                    5.12   x86_64 flathub system
KDE Software Development Kit - Tools and headers for developing applications using? org.kde.Sdk                               5.12   x86_64 flathub system
```

`?` stands for the `...` character which was apparently lost in copy & paste.

**Comment by JorisGoosen** [comment]
Well, then I think it is time to make an issue on flatpak, I'll set it up and mention you in it specifically. I am going on vacation for a bit more than a week tomorrow, so I won't be able to help for a while. 

All information should however be available in the flathub repo we use and here.

**Comment by allefeld** [comment]
Good. Can you link in the flatpak issue to this one?
Have a nice vacation!

**Comment by JorisGoosen** [comment]
https://github.com/flatpak/flatpak/issues/3136

Thanks!

**Comment by markovendelin** [comment]
Have been hit with the same issue making it impossible to use JASP as distributed at Flathub.

When rebuilding JASP locally without https://github.com/flathub/org.jaspstats.JASP/blob/master/org.jaspstats.JASP.json#L7 (`"inherit-extensions" : [ "org.freedesktop.Platform.GL" ],`), I can confirm that JASP starts and works as expected.

**Comment by allefeld** [comment]
https://github.com/flatpak/flatpak/issues/3136#issuecomment-541423837
