### ISSUE TITLE
Feature request: Fisher's Exact Test

### ISSUE THREAD

**Issue by jlwoodard** [jasp-stats/jasp-issues#500]
I would be very interested if JASP could provide Fisher's Exact Test as part of the Contingency Table statistics. Particularly for small samples, having an option to select Fisher's Exact Test for any number of rows and columns, along with selecting the option for a one-sided or a two-sided test, could be very useful.

I believe Fisher's Exact Test is available in R using fisher.test. I saw a previous post about this feature request going back to 2017 and just wondered if it might still be considered for implementation in a future release. Many thanks in advance!

John

**Comment by EJWagenmakers** [comment]
We do offer it, but you have to click "log odds ratio (2x2 only)". Strangely, this only computes a 95% CI. A p-value would be nice, and so would the ability of a one-sided test, I agree.
@TimKDJ : maybe a nice task for Frantisek?
