### ISSUE TITLE
Program closes

### ISSUE THREAD

**Issue by modelistatistik** [jasp-stats/jasp-issues#502]
* JASP version: 0.11.0.0
* OS name and version:
* Analysis: Machine learning
* Bug description: https://prnt.sc/pbbqsd
* Add JASP files as a zip: https://yadi.sk/d/WaNfNOihEmuC6Q 
* Screenshot: https://prnt.sc/pbbqsd
* Expected behaviour:
* Steps to reproduce:

**Comment by JorisGoosen** [comment]
Ill add this info to the issue you already opened...

**Comment by modelistatistik** [comment]
True, windows 10..
