### ISSUE TITLE
plots unavailable

### ISSUE THREAD

**Issue by MelJucla** [jasp-stats/jasp-issues#503]
* JASP version:0.11
* OS name and version:Mojave 10.14.6
* Analysis:
* Bug description:It is impossible to obtain plots. I've tried to download different versions of Jasp but the problem remains. And I've tried with different data files. Here is an error message : 
This analysis terminated unexpectedly.
Error in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : extrémités de polygone non trouvés
* Add JASP files as a zip:
* Screenshot: 
* Expected behaviour:
* Steps to reproduce:

**Comment by TimKDJ** [comment]
Could you try the fix suggested in https://github.com/jasp-stats/jasp-issues/issues/405

**Comment by MelJucla** [comment]
I've tried and it doesn't work.
Here the full error message : 

Error in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : extrémités de polygone non trouvés

Stack trace
lapply(vps, push.vp, recording)

FUN(X[[i]], ...)

push.vp.vpTree(X[[i]], ...)

push.vp(vp$parent, recording)

push.vp.viewport(vp$parent, recording)

grid.Call.graphics(C_setviewport, vp, TRUE)

(function (x) 
{
    widthDetails(x)
})(list(label = 'RM Factor 1', x = 0.5, y = 0.5, just = 'centre', hjust = 0.5, vjust = 0.5, rot = 0, check.overlap = FALSE, name = 'GRID.text.91', gp = list(fontsize = 17, col = 'black', fontfamily = '', lineheight = 0.9, font = c(plain = 1)), vp = NULL))

widthDetails(x)

widthDetails.text(x)

grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, resolveHJust(x$just, x$hjust), resolveVJust(x$just, x$vjust), x$rot, 0)

**Comment by TimKDJ** [comment]
What did you try exactly, restoring standard fonts or enabling the arial font family?

**Comment by MelJucla** [comment]
restoring standard fonts

**Comment by MelJucla** [comment]
My mistake, I restarted my computer and it works again!!!
Thanks!

**Comment by TimKDJ** [comment]
Glad to hear :)
