### ISSUE TITLE
version number bugged on macOS

### ISSUE THREAD

**Issue by core-code** [jasp-stats/jasp-issues#504]
the version numberer embedded into  of JASP-0.11.0.3 is wrong

1.) download JASP-0.11.0.3.dmg
2.) inspect the version number using Quick Look  or Column View in the macOS Finder
3.) instead of version 0.11.0.3 it claims to be 0.11.0.0. it seems you forgot to update the version  number for this release

technical detail: the 'CFBundleShortVersionString' entry in your Info.plist file is wrong.

also, it is impossible to view the version number using the 'Get Info' window because you are including the CFBundleGetInfoString entry in the Info.plist file. this key has been deprecated for more than 10 years and should never be included in any app.

**Comment by core-code** [comment]
<img width="595" alt="Screenshot 2019-09-29 at 21 30 47" src="https://user-images.githubusercontent.com/1261954/65838203-f1569800-e300-11e9-8747-4fc384081338.png">

**Comment by AlexanderLyNL** [comment]
Thanks for reporting this. We'll look into this.

**Comment by AlexanderLyNL** [comment]
Solved: https://github.com/jasp-stats/jasp-desktop/pull/3563
