### ISSUE TITLE
JASP crashed when opening "descriptive statistics"

### ISSUE THREAD

**Issue by jumatr** [jasp-stats/jasp-issues#505]
* JASP version: JASP 0.11 and JASP 0.10.2

* OS name and version: Windows 10 Home (version 1903); Processor: Inter Core i3-606U CPU

* Bug description: When I open the the descriptive statistics module, JASP crashes. I experienced the error with JASP 0.11 and JASP 0.10.2. This error didn't happen with JASP 0.9.

* Add JASP files as a zip: 
[JASP_data.zip](https://github.com/jasp-stats/jasp-issues/files/3670476/JASP_data.zip

* Screenshot: 
![error jasp](https://user-images.githubusercontent.com/55980785/65871984-dd05b000-e37f-11e9-8f19-d281e475b043.JPG)

* Steps to reproduce: 
1. Load data (either .jasp or ..csv format)
2. Click on 'descriptive statistics"
3. See error

**Comment by boutinb** [comment]
Hi @jumatr, what is your username on your PC?

**Comment by jumatr** [comment]
I think my username is " Júlia Martí Trilla "

**Comment by jumatr** [comment]
I don't know if is "Júlia Martí Trilla" or "Jú"

**Comment by boutinb** [comment]
Would it be possible to add a user with just 'normal' latin characters (in place from ú, just a u), and start JASP from this new user?

**Comment by jumatr** [comment]
Hi,
I have modified the username (now is Julia) and JASP still crashing.

**Comment by boutinb** [comment]
Hi @jumatr, could you try this version: http://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-WindowsJaspResultsHotfix-4fac875f1aaccfc0547bb72d5413341506536b0d.msi
This is an 'unsigned' version, that means that your PC will warn you that it does not know from whom it is. It might be also slower.
Can you try both Descriptives Statistics & Reliability Analysis?

**Comment by jumatr** [comment]
Hi,
I have tried both and it works well. The error didn't happen in this version.
Thank you!

**Comment by boutinb** [comment]
Fine, I will make an official hotfix version.
