### ISSUE TITLE
Error in data frame: Undefined Columns Selected (When running simple main effects for a 3-way fully-within ANOVA)

### ISSUE THREAD

**Issue by coolside22** [jasp-stats/jasp-issues#506]
* JASP version: 0.10.2
* OS name and version: Windows 10. Version: 10.0.18362
* Analysis: Running simple main effects for a 3-way fully-within ANOVA
* Bug description: Received an error description: Error in data frame, undefined columns selected when trying to run simple main effects. Running the same analysis on SPSS yields the same results, except SPSS successfully runs the simple main effects analysis without issue. 
* Add JASP files as a zip:
[FullyWithin.zip](https://github.com/jasp-stats/jasp-issues/files/3670970/FullyWithin.zip)
* Screenshot: 
![Error Image When Running Simple Main Effects](https://user-images.githubusercontent.com/20704425/65877733-f67a1c80-e3be-11e9-9989-cbd07fcb8187.png)
* Expected behaviour: Simple main effects should run successfully.
* Steps to reproduce: 
1. Run a Repeated Measures ANOVA
2. Specify three Repeated Measures Factors (C, T, and M)
3. C has three levels (1,2,3). T has two levels (1,2), and M has three levels (1,2,3)
4. Insert the variables respectively into 'Repeated Measures Cells'. It should already be in order.
5. Attempt running any simple main effects analysis and the error will appear. Analysis is successfully run on SPSS without error.

**Comment by JohnnyDoorn** [comment]
Thanks for reporting! We are currently rewriting some analyses and this seems fixed in the rewrite.

**Comment by coolside22** [comment]
Thanks Johnny!

May I know if you have a date for when this will be fixed?

**Comment by Lumossssss** [comment]
Hey I met the same problem now. Do you think it has already been solved? Thanks.
