### ISSUE TITLE
Plots not generating

### ISSUE THREAD

**Issue by jennie0530** [jasp-stats/jasp-issues#507]
Whenever I run some data, none of the plots are generated. I'm not sure but I think the first few times were fine but after some time, plots have stopped being generated altogether in any of the statistics (e.g., Q-Q plots, interaction plots, etc.). I don't know what the problem is and can't seem to find the solution anywhere. 

My OS is Windows 10 Home.

Please help!

**Comment by AlexanderLyNL** [comment]
Hi jennie0530,

We're happy to look into this more carefully, but to help out, we require some more information. Could you please fill out the bug issue template, as shown here? 

https://github.com/jasp-stats/jasp-issues/issues/new?assignees=&labels=&template=bug_report.md&title=

It would also be informative to include the jasp file. Please zip the file first before you drag and drop it into the template. 

Cheers,
Alexander
