### ISSUE TITLE
LOS RESULTADOS DECIMALES CON CERO 

### ISSUE THREAD

**Issue by cristony** [jasp-stats/jasp-issues#509]
* JASP version: 11
* OS name and version: WINDOWS 64
* Analysis: ANALYISIS FACTORIAL
* Bug description:The graphs of the factor analysis in the values of factor loads (eg 0.15) do not benefit the graph of the value 0. but should be used .15 for a better view of the results because mostly the values overlap one on top of the other and do not allow a adequate visualization of the statistical graph.
* Add JASP files as a zip:
* Screenshot: 
* Expected behaviour:
* Steps to reproduce:

**Comment by TimKDJ** [comment]
Could you attach the jasp file or a screen shot of your problem?
I'm not entirely sure if I know what you mean

**Comment by cristony** [comment]
In the correlation of square factors these are many in the graph the values are superimposed and not well illustrated in the graph because they use the number 0.00, should omit the 0 and put .00 to better illustrate the values.
I also have suggestions on the analysis of mediation the names of the variables change to codes and do not become incomprehensible.
When I perform SEM analysis I do not get the graphs always comes out this error hopefully can be solved

________________________________
De: Tim de Jong <notifications@github.com>
Enviado: miércoles, 2 de octubre de 2019 03:31
Para: jasp-stats/jasp-issues <jasp-issues@noreply.github.com>
Cc: cristony <cristony_777@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [jasp-stats/jasp-issues] LOS RESULTADOS DECIMALES CON CERO (#509)


Could you attach the jasp file or a screen shot of your problem?
I'm not entirely sure if I know what you mean

**Comment by TimKDJ** [comment]
It would still really help me if you could attach a .jasp file that demonstrates exactly what you mean. To do so, go to this link https://github.com/jasp-stats/jasp-issues/issues/509 and drag and drop the (compressed) .jasp file.

To solve overlapping axis labels: making the figure bigger might do the trick (there is a little drag handle on the bottom right corner of the image)

In the future we will add support to adjust the names of the plot labels, but this is not yet possible at the moment.

**Comment by cristony** [comment]
Hello, I hope I can also correct the errors I sent you in the previous message regarding the mediation analysis and the names of incomprehensible variables and the SEM analysis regarding the lack of graphics.

________________________________
De: Tim de Jong <notifications@github.com>
Enviado: viernes, 4 de octubre de 2019 04:36
Para: jasp-stats/jasp-issues <jasp-issues@noreply.github.com>
Cc: cristony <cristony_777@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [jasp-stats/jasp-issues] LOS RESULTADOS DECIMALES CON CERO (#509)


It would still really help me if you could attach a .jasp file that demonstrates exactly what you mean. To do so, go to this link #509<https://github.com/jasp-stats/jasp-issues/issues/509> and drag and drop the (compressed) .jasp file.

To solve overlapping axis labels: making the figure bigger might do the trick (there is a little drag handle on the bottom right corner of the image)

In the future we will add support to adjust the names of the plot labels, but this is not yet possible at the moment.
