### ISSUE TITLE
rmANOVA analysis terminated

### ISSUE THREAD

**Issue by natinatifilfil** [jasp-stats/jasp-issues#510]
I am trying to run a rmANOVA (2x2x2x4) and run into this error:

Any idea what this means?
I am using a 0.9.2.0 version and a csv. file 
Thanks! 

This analysis terminated unexpectedly.

Error in if (is.finite(value)) {: argument is of length zero

Stack trace
analysis(dataset = dataset, options = options, perform = perform, callback = the.callback, state = oldState)

.rmAnovaWithinSubjectsTable(dataset, options, perform, model, stateSphericity, status)

.clean(result[index, 'F value'])

**Comment by boutinb** [comment]
We have released version 0.11(https://jasp-stats.org/download/). Can you try it with this new version?
If the error still occurs, can you send us the csv file?
Kind regards,
Bruno

**Comment by AlexanderLyNL** [comment]
Or zip the jasp file and drag it into this thread: 

https://github.com/jasp-stats/jasp-issues/issues/510

**Comment by natinatifilfil** [comment]
It worked with an update!
Thank you!


Natalia Filvarova
BA Experimental Psychology (University of Oxford)
MSc Systemic Neurosciences (Graduate School of Systemic Neurosciences, LMU)
PhD Researcher in Multisensory Integration and Perception (Fraunhofer IVV
Insititute)
Founder at NeuroCamp e.V. <https://www.neurocamp-munich.com/>
WEF Global Shaper
https://www.linkedin.com/in/natalia-filvarova

**Comment by AlexanderLyNL** [comment]
Thanks for the feedback!
