### ISSUE TITLE
JASP won't reopen existing JASP files.

### ISSUE THREAD

**Issue by bivalau66** [jasp-stats/jasp-issues#513]
* JASP version: 0.10.2
* OS name and version: Windows 10
* Analysis:
* Bug description: I have lots of JASP files as I've been using it for a few years now, but when I try to reopen an existing file (even ones created with this version) it's 50/50 whether the file will open properly or just sit on the processing bar forever. Either way it takes at least 5 minutes for the file to open. 
* Add JASP files as a zip:
* Screenshot: 
* Expected behaviour:
* Steps to reproduce:

**Comment by boutinb** [comment]
Hi @bivalau66 Can you send us one JASP which does not work?

**Comment by Izymil** [comment]
Hello! I see that the problem hadn't been solved and I have practically identical issue. I would like to attach a file, but I got "We don't support that file type" message.

**Comment by vandenman** [comment]
to upload files to GitHub you need to zip them first (unless they are images or plain text).

**Comment by Izymil** [comment]
[cannot-load.zip](https://github.com/jasp-stats/jasp-issues/files/6010131/cannot-load.zip)
Thanks! There you go

**Comment by boutinb** [comment]
Hi @Izymil I can load it without problem, but maybe is my PC stronger than yours. You wrote that you use JASP 0.10.0. This is quite an old version. Did you try the current 0.14.1 version?
