### ISSUE TITLE
Pie charts in plot section

### ISSUE THREAD

**Issue by ruzeldev** [jasp-stats/jasp-issues#514]
Cake graphs in the "plot" section
* Enhancement: Develop the "pie chart" option in the "plot" section.
* Purpose: To be able to decide between "pie chart" and "distribution plots" for the graphical analysis of the categorical data.
* Use-case:

**Describe the solution you'd like**
Place the option "pie chart" above or below the option "distribution plots"

**Describe alternatives you've considered**
Develop a module with alternative forms of graphical analysis (such as pie charts, stacked bars, etc.). Other ways of analyzing categorical data could be included. 

**Additional context**
![image](https://user-images.githubusercontent.com/34621235/66370773-f2be3b00-e966-11e9-80b2-ede3e07ae36a.png)

**Comment by AlexanderLyNL** [comment]
Hi ruzeldev, 

This will be available in the next version of JASP 0.12. It now only needs refining and testing. 

Cheers,
Alexander
