### ISSUE TITLE
JASP ignores values that have no corresponding labels

### ISSUE THREAD

**Issue by gyunter** [jasp-stats/jasp-issues#517]
Hello,

When I open `sav` file  that has a variable with ordinal values from 1 to 7 and labels are set only for the uttermost values (1 and 7), JASP totally ignores all other values from the dataset, leaving them blank. Is this an intended attitude? I have tried importing the same dataset to Stata and Stata leaves "unlabled" values as is.

Consequently, when I try to conduct descriptive analysis, no wonder I get an error:
```This analysis terminated unexpectedly.

Error in (new('C++Function', .Data = function (...) : map::at:  key not found
```

Can't provide dataset unfortunately.
Thanks.

**Comment by gyunter** [comment]
It works like a charm when I remove all the labels from the variable:

<img width="200" alt="Screenshot 2019-10-10 at 13 13 02" src="https://user-images.githubusercontent.com/32836/66560292-c3bee980-eb5f-11e9-9d95-d2761b2fccd6.png">

But for partly-labled variables, this happens on`sav`-file import:

<img width="428" alt="Screenshot 2019-10-10 at 13 18 30" src="https://user-images.githubusercontent.com/32836/66560669-7f801900-eb60-11e9-9da1-8a1e68b0fabe.png">

**Comment by gyunter** [comment]
You can use [this](https://www.guide-market-research.com/app/download/13631503227/Oddjob.sav) dataset to reproduce the issue.

**Comment by boutinb** [comment]
OK, I see. I will try to fix it.
Thanks,
Bruno

**Comment by JorisGoosen** [comment]
@gyunter I've figured out what went wrong with the file you sent us. I've also fixed this in our current development version.

The next release of JASP will take a while though.

To enable you to use the software I have two suggestions:
A) For each partly-labelled column you either remove all labels or add in the missing one's.
B) If you don't want to do that you could consider using our [nightly version of JASP](https://static.jasp-stats.org/Nightlies/). Tomorrow there will be an installer there that contains the fix I've just made. That JASP however is quite experimental and not properly tested yet so it would be for your own risk.
