### ISSUE TITLE
JASP crashes unexpectedly on macOSX

### ISSUE THREAD

**Issue by LoulouLouis** [jasp-stats/jasp-issues#518]
* JASP version:0.11.1
* OS name and version: MacOS 10.14.6
* Analysis:logistic regression
* Bug description:after successfully uploading my dataset, I clicked on logistic regression within the regression icon and I got the message saying that due to unexpected internal error, JASP crashed,  it did it several times and I just cannot process my data any further.
* Add JASP files as a zip:
* Screenshot: 
<img width="1248" alt="Screen Shot 2019-10-10 at 9 42 01 am" src="https://user-images.githubusercontent.com/56371478/66529351-a7648200-eb4a-11e9-91ca-4927b9b38282.png">

* Expected behaviour:
* Steps to reproduce:

**Comment by FransMeerhoff** [comment]
HI @LoulouLouis 

- Could you send us the log files that JASP generates?
If you go to the file open menu there is a Preference option -> and then Advanced.
At the bottom of that option menu you can check if log files are written and the 'show logs' button directs you to the location of the log files. (Restart and reproduce your problem)
- Could you send us the data file? (By drag and drop it to this issue)
- Is this problem specific for this data and analysis combination. Do you encounter other problems with different data sets and analyses too?

Thanks for reporting and
kind regards Frans Meerhoff

**Comment by LoulouLouis** [comment]
Hello Frans,
Please find attached the logs generated after one single trial.
The day before yesterday, similar issue happened, but I don't remember what I was trying to do at that time. Please let me know if you want me to do some more test runs.
I hope this helps.

Cheers


Louis

________________________________
De : FransMeerhoff <notifications@github.com>
Envoyé : jeudi 10 octobre 2019 17:50
À : jasp-stats/jasp-issues <jasp-issues@noreply.github.com>
Cc : LoulouLouis <l_louis77@hotmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [jasp-stats/jasp-issues] JASP crashes unexpectedly on macOSX (#518)


HI @LoulouLouis<https://github.com/LoulouLouis>

  *   Could you send us the log files that JASP generates?
If you go to the file open menu there is a Preference option -> and then Advanced.
At the bottom of that option menu you can check if log files are written and the 'show logs' button directs you to the location of the log files. (Restart and reproduce your problem)
  *   Could you send us the data file? (By drag and drop it to this issue)
  *   Is this problem specific for this data and analysis combination. Do you encounter other problems with different data sets and analyses too?

Thanks for reporting and
kind regards Frans Meerhoff

**Comment by boutinb** [comment]
Hello @LoulouLouis, we did not get the attached files. If you want to send a file, use the GitHub website (not your email). If GitHub does not accept the type of file you want to send, zip it first.
Cheers,
Bruno

**Comment by LoulouLouis** [comment]
[JASP 2019-10-14 09_34_21 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/3722568/JASP.2019-10-14.09_34_21.Desktop.log)
[JASP 2019-10-14 09_34_21 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/3722569/JASP.2019-10-14.09_34_21.Engine.0.log)
[JASP 2019-10-14 09_34_21 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/3722570/JASP.2019-10-14.09_34_21.Engine.1.log)
[JASP 2019-10-14 09_34_21 Engine 2.log](https://github.com/jasp-stats/jasp-issues/files/3722571/JASP.2019-10-14.09_34_21.Engine.2.log)
[JASP 2019-10-14 09_34_21 Engine 3.log](https://github.com/jasp-stats/jasp-issues/files/3722572/JASP.2019-10-14.09_34_21.Engine.3.log)

**Comment by LoulouLouis** [comment]
Hello, please let me know if you received the logs.

Thank you, 

Best regards

Louis

**Comment by boutinb** [comment]
Hello @LoulouLouis,
Can you also send us your dataset?

**Comment by boutinb** [comment]
In ZIP format.

**Comment by LoulouLouis** [comment]
[Logistic regr A1B1C1D1.csv.zip](https://github.com/jasp-stats/jasp-issues/files/3728420/Logistic.regr.A1B1C1D1.csv.zip)

**Comment by boutinb** [comment]
OK, I can reproduce your problem. R crashes causing the crash of JASP. I see what I can do...

**Comment by LoulouLouis** [comment]
Hello, 
I was wondering if you managed to find out what the issue was?
Thanks 

Louis

**Comment by FransMeerhoff** [comment]
Hello @LoulouLouis 

Sorry for the late reaction, but we can report you that this issue is solved in the coming release.
We plan to publish this release JASP 0.12 at the end of this year.
So I close this issue for now.

Thanks again for reporting and helping us.

Kind regards
Frans Meerhoff
