### ISSUE TITLE
JASP 0.11.1.0 won't open on macOS Catalina

### ISSUE THREAD

**Issue by djdekker** [jasp-stats/jasp-issues#519]
* JASP version: 0.11.1.0
* OS name and version: macOS Catalina (10.15)
* Analysis: When starting the app, macOS displays an error message and won't allow JASP to start.
* Bug description: JASP does not start because "Apple cannot check the file for malicious software".
* Add JASP files as a zip: n/a
* Screenshot: 
<img width="532" alt="jasp-error" src="https://user-images.githubusercontent.com/5346286/66697636-de1bd300-ecd7-11e9-8638-47e36475e115.png">

* Expected behaviour: the program should start, just like the previous version did
* Steps to reproduce: 
1. download JASP for Mac 0.11.1.0
2. open the .dmg file and copy JASP to the Apps folder
3. double click on JASP in the Apps folder

**Comment by AlexanderLyNL** [comment]
When opening the app, do you right click it and then open? Or do you double click it? Furthermore, could you please check in your settings "Security & Privacy" whether apps are allowed from "App Store and identified developers"?

**Comment by djdekker** [comment]
Thank you! Right clicking does the trick. macOS still responds with a warning about checking for malicious software, but that can be dismissed and then does not appear anymore. On my computer apps from Apple and identified developers are permitted.
