### ISSUE TITLE
Two step cluster analysis

### ISSUE THREAD

**Issue by djstepz1** [jasp-stats/jasp-issues#520]
The addition of a two step cluster analysis module would be a worthy addition to JASP. 
Clustering is now a widely used technique and two step cluster is an ideal approach for use in JASP, with its simpler output than those used in k-means and hierarchical methods. There are numerous benefits to clustering that are more easily adjusted for than in other correlational methods.

In other software it is also possible to input clustered data as a categorical variable within the data after running a cluster analysis, though I m not sure how this could be implemented it would be a great addition.

**Comment by AlexanderLyNL** [comment]
In JASP 0.11.1 you can do a k-means cluster analysis, and subsequently add the predicted clusters to the data set. These clusters can then be used for further analyses. Let us know whether this suffices for what you have in mind, if not, could you please specify the use-case, so we know what we can work towards.
