### ISSUE TITLE
Different results when using CFA command and SEM command

### ISSUE THREAD

**Issue by RAYDIGIUSEPPE** [jasp-stats/jasp-issues#521]
Hello All
I am running a CFA on a large data set (more than 2000  subjects and 24 items). I have run the CFA with the lavaan program on the JASP SEM command. I use DWLQ estimator.  I get good results. I am using now the new release of JASP 0.11.1.0
This version has a CFA command under factor analysis and you have to click the variables into a box that represents the items for each factor.
When I do the same analysis this way I can enter up to 3 factors. When I get to entering the fourth factor, I get a box that pops up and says
" lavann warning: Covariance matrix of latent variables is not positively definite. use lavaanspect (fit, "cov.lv) to investigate"
Does anyone know what the same analysis runs on the SEM command but not the CFA command? This data set does have correlated factors and is multivariate nonnormal.
Does anyone know how to access "avaanspect (fit, "cov.lv)"
Thank you in advance.

**Comment by vankesteren** [comment]
Did you select the same estimator in CFA? 
Could you check that the syntax in the CFA is the same as the syntax you enter in SEM (under `additional output` > `lavaan syntax`)

It is definitely possible to obtain the same results, but there are a few differences between both analyses.
