### ISSUE TITLE
Bayesian meta analysis 

### ISSUE THREAD

**Issue by NilsSim** [jasp-stats/jasp-issues#524]
* JASP version: 0.11.1
* OS name and version: MacOS Mojave 10.14.5
* Analysis: Bayesian Meta-Analyse, see screenshot
* Bug description:
* Add JASP files as a zip:
* Screenshot: 
* Expected behaviour:
* Steps to reproduce: 
<img width="680" alt="Untitled" src="https://user-images.githubusercontent.com/56731401/67147153-8f9ba500-f292-11e9-9eee-06f01c45bea9.png">

**Comment by TimKDJ** [comment]
Thanks for the report. Could you by any chance attach the .jasp file as .zip?
Or email it to me at t.dejong3 [at] uva nl

Just a note of warning, the Bayesian Meta Analysis is in a very early stage of development, so there may be a number of glitches

**Comment by TimKDJ** [comment]
We'll have a look, thanks for sending the dataset

**Comment by sophieberkhout** [comment]
I believe the problem here was a BF of infinity. An appropriate error message was added a while ago.
