### ISSUE TITLE
Follow Up From "Error in data frame: Undefined Columns Selected

### ISSUE THREAD

**Issue by coolside22** [jasp-stats/jasp-issues#526]
![Capture](https://user-images.githubusercontent.com/20704425/67179883-69007a00-f40a-11e9-8b5c-cdd5eb053f4f.JPG)

Thanks for the previous revert on this issue! My professor would like to further inquire if there's an **estimated date for when this issue will be fixed?** This is because we're currently running a statistics course using JASP and would like to know if this issue will be resolved before the semester ends, so we can update our students.

Thank you! Apologies if this is not the right section to be posting this.

**Comment by TimKDJ** [comment]
We're currently working on a rather big internal code restructure (which will enable us to add some cool features such as syntax mode). Considering the scale of the task this means that 0.12 won't be out for a little while. It will take a couple of months at least.
