### ISSUE TITLE
Pearson Correlation matrix needs n or degrees of freedom

### ISSUE THREAD

**Issue by ToddDaniel** [jasp-stats/jasp-issues#528]
* Enhancement: The Pearson correlation matrix results table does not report the n for the number of pairs in a correlation. This is needed to report the degrees of freedom for the correlation in APA style. 
* Purpose: APA style for writing up a correlation is r(198) = .68, p <. 001. The correlation table reports r and p but does not provide the degrees of freedom. 
* Use-case:

**Is your feature request related to a problem? Please describe.**
 

**Describe the solution you'd like**
 
I would like the correlation matrix table for Pearson, Spearman, and Kendal to report the number of pairs that were used for each correlation coefficient. 

**Describe alternatives you've considered**
 I tried using descriptive statistics, which gives me the number of cases for each variable, but I need the number of pairs for each correlation. When the dataset does not contained matched pairs for every case, the df for correlation can vary. Therefore, it is important to know the number of pairs for each correlation coefficient. 

**Additional context**

I am reporting this about Pearsons's correlation, but the same issue holds true for Spearman's and Kendall's tau, as well. 
I will attach screen shots for SPSS and JASP to illustrate the difference
<img width="1108" alt="Example SPSS Output" src="https://user-images.githubusercontent.com/7915843/67299884-d2d45e80-f4b2-11e9-8844-2095b94c9820.png">
<img width="630" alt="Example JASP Results" src="https://user-images.githubusercontent.com/7915843/67299886-d2d45e80-f4b2-11e9-9e9a-4f81d6cb8df3.png">

**Comment by EJWagenmakers** [comment]
Yes, good point! JASP team, who can add this?
EJ

**Comment by Kucharssim** [comment]
I just implemented this in the newest rewrite, so it will appear in the future release.

**Comment by EJWagenmakers** [comment]
Woh. ESP?

**Comment by ToddDaniel** [comment]
Thanks! That was amazingly fast. Looking forward to the next release
