### ISSUE TITLE
Incorrect means in descriptives from t-test

### ISSUE THREAD

**Issue by AKMartin478** [jasp-stats/jasp-issues#529]
* JASP version: 0.11.1
* OS name and version: Mac OSX
* Analysis: Bayesian t-test
* Bug description: Incorrect means in descriptives from t-test that do not match the correct means from the descriptives toolbox
* Add JASP files as a zip: 
* [Screenshot:](url) 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/56954249/67463362-a3754b80-f684-11e9-857b-7a7b1672f11f.png">

* Expected behaviour:
* Steps to reproduce:

**Comment by EJWagenmakers** [comment]
??!
@JohnnyDoorn can you take a look?

**Comment by JohnnyDoorn** [comment]
Hi @AKMartin478 

Thanks for reporting, could you please send the jasp file to me? (j.b.vandoorn (at) uva.nl)
That way I can take a closer look at your case, because I cannot reproduce this behavior on other data sets.

Kind regards,
Johnny

**Comment by AKMartin478** [comment]
Attached

Thanks
Andrew

**Comment by JohnnyDoorn** [comment]
Hi @AKMartin478 ,

Sorry, I don't see your file (I think you need to either mail me directly and not through github, or upload it explicitly to github).

Cheers
Johnny

**Comment by fplatz** [comment]
Hi! 

I've the same problem as described above by @AKMartin478. Attached you'll find my dataset along with the JASP file for further investigation. 

Cheers
Friedrich
[Data&Jasp-File.zip](https://github.com/jasp-stats/jasp-issues/files/3814101/Data.Jasp-File.zip)

**Comment by JohnnyDoorn** [comment]
Hi Friedrich,

Thanks for your report - we're currently sorting it out (@vandenman we talked about this right?)

Cheers,
Johnny

**Comment by vandenman** [comment]
Hi, it looks like ordinal data is incorrectly converted to numeric in the t-tests. A workaround is to click the icon next to the variable name and change the data type to scale (see screenshot).

![image](https://user-images.githubusercontent.com/21319932/68304835-e41e8d00-00a6-11ea-86e6-4c38accc169f.png)

**Comment by fplatz** [comment]
Thanks @vandenman for the quick reply!
