### ISSUE TITLE
Feature Request: Inter-rater Reliability

### ISSUE THREAD

**Issue by dansom** [jasp-stats/jasp-issues#53]
Dear Jasp Team,

again a big "Thank you" up first! Great work you're doing.

As I abandoned SPSS and am using Jasp as my sole graphical stats program, I would love if you could implement the calculation of Inter-rater Reliabilities. This is a feature often used by researchers, which so far is not implemented in JASP(at least couldn't find it)

Thanks for your considering,

Daniel

**Comment by lithos** [comment]
yes please, just helping out on a 2nd year course and would like to show this in JASP as well as SPSS (as i have for most of our tests a slow shift to a better app)

cheers

**Comment by boutinb** [comment]
@vandenman can this feature be added for the next release?

**Comment by juliuspfadt** [comment]
the feature is implemented by now in the ICCs.
