### ISSUE TITLE
Cohen's d corrected for multiple comparisons in post-hoc test

### ISSUE THREAD

**Issue by vicenteinefo** [jasp-stats/jasp-issues#531]
* Enhancement: to implement the corrected Cohen's d for multiple comparisons in post-hoc tests
* Purpose: to report effect size of post-hoc test in future research papers
* Use-case: nowadays, it is a common requisite in the author guidelines of sports science journals

**Describe the solution you'd like**
 
to implement a checkbox to compute the Cohen's d corrected for multiple comparisons 

**Describe alternatives you've considered**
 
I have been computing the effect size using the same formula as JASP uses in the paired samples  t-test d = t/sqrt(n). Then I compute the effect size using the t value of the post-hoc table of the ANOVA and the n value of the correspondent group

**Additional context**

See attached file for more details

<img width="681" alt="Captura de pantalla 2019-10-24 a las 20 38 38" src="https://user-images.githubusercontent.com/29978768/67602835-c9c7e380-f777-11e9-91c3-8b6b18fc1ee5.png">

**Comment by juliuspf** [comment]
Due to some tricky wording this wasn't closed through https://github.com/jasp-stats/jaspAnova/pull/90, but it should have been
