### ISSUE TITLE
JASP 0.11.1 Linux Mint 19.2 crashes when selecting Label Outliers of Boxplots

### ISSUE THREAD

**Issue by decuser** [jasp-stats/jasp-issues#533]
JASP version: 0.11.1
OS name and version: Linux Mint 19.2 64 bit
Analysis: JASP crashes when trying to add label to outliers in boxplots:

![boxplot](https://user-images.githubusercontent.com/3193121/67729011-72b35000-f9bd-11e9-9c05-a7fa1f4af6c3.png)

Expected behaviour: Display the boxplot and label the outliers.
Steps to reproduce: 
1.Open the Fear of Statistics dataset
2. Click on Descriptives->Descriptive Statistics
3. Select Q01 as the Variable to plot
4. Select Plots->Boxplots
5. Click Label Outliers
JASP crashes.

This is repeatable, and it doesn't do this on Mac, same version of JASP.

**Comment by decuser** [comment]
I originally came across this doing the boxplot following Learning Statistics with JASP in the aflsmall_margins.csv dataset with the afl.margins variable:

https://github.com/tomfaulkenberry/JASPbook/tree/master/data

**Comment by juliuspfadt** [comment]
@decuser, I apologize for the late reply. With the newest JASP version this issue seems to be resolved. Can you confirm?
