### ISSUE TITLE
Variable type locked (nominal)

### ISSUE THREAD

**Issue by agnesuq** [jasp-stats/jasp-issues#535]
* JASP version: 0.11.1
* OS name and version: Windows
* Bug description: Columns with nominal variables have a small lock icon. I am unable to change variable type. I have the latest version of JASP and no missing data in the columns.

![JASP](https://user-images.githubusercontent.com/57159878/67818715-fecc9100-fafd-11e9-9a07-90affc3111b2.PNG)

**Comment by TimKDJ** [comment]
That's not actually a lock icon. It's a little `a` -- it means your column consists of strings. These cannot be coerced to integers
