### ISSUE TITLE
ANOVA aliased coefficients error

### ISSUE THREAD

**Issue by agnesuq** [jasp-stats/jasp-issues#536]
* JASP version: 0.11
* OS name and version: Windows
* Analysis: Anova
* Bug description: I get the 'There are aliased coefficients in the model' when trying to use 'Major' as a fixed factor. I am not sure why. Please see the attached dataset. I am able to use 'Country' as a fixed factor.

* Screenshot: 
![ANOVA](https://user-images.githubusercontent.com/57159878/67823156-b026f300-fb0d-11e9-8ccb-03b1900f7f67.PNG)

* Steps to reproduce: 
[Data - cleaned.xlsx](https://github.com/jasp-stats/jasp-issues/files/3786596/Data.-.cleaned.xlsx)

1. Run ANOVA test, with Major as a Fixed Factor.
2. See error

**Comment by tomtomme** [comment]
This issue is fixed in JASP 0.18.1.
can be closed
