### ISSUE TITLE
Error when trying to get Correlation Plot

### ISSUE THREAD

**Issue by anishau24** [jasp-stats/jasp-issues#537]
* JASP version: 0.9.2
* OS name and version: El Capitan 10.11.6
* Bug description: I'm unable to get correlation plots for my data. It gives me the error shown in this screenshot. I've tried redownloading JASP and restarting my computer and starting a new file as well.
* Screenshot: ![Screen Shot 2019-10-30 at 11 05 21 AM](https://user-images.githubusercontent.com/57158544/67885644-312dbc80-fb05-11e9-9b50-7e8e9cdc7bc1.png)
* Expected behaviour: It's supposed to give me correlation plot but it gave me this error instead.

**Comment by TimKDJ** [comment]
0.9.2 is a rather old version, I would recommend getting the latest version to see if that fixes your problem: https://jasp-stats.org/download/
