### ISSUE TITLE
Wrong calculation of mean and sd in scale reliability Statistics on the Reliability Analysis page

### ISSUE THREAD

**Issue by lklende** [jasp-stats/jasp-issues#540]
* JASP version: 0.11.1.0
 
* OS name and version: Windows 7 Professional
* Analysis: Reliability Analysis -> Scale Reliability Statistics 
* Bug description: The scale reliability Statistics on the Reliability Analysis page of Descriptive statistic calculate wrong values for mean and SD. The values are calculated without taking into considertion reversed variables. See Field's Fear of Statistics example. It is only the values for Cronbaqs alfa that are altered when reversed values are involved.
* Expected behaviour: The value for mean and SD should alter when moving variables into the field of the Reversed-Scaled Items

#### Steps to reproduce:
1. Open "Fear of Statistics" example
2. Go to 'Descriptives'
3. Look at the Scale Reliability Statistics on report page
4. When variable Q03 is moved to or from  Reversed Scaled Items, the mean and sd should alter
5. You can only apprahend the error when you realise that the value does not alter

**Comment by juliuspf** [comment]
I think with the new release, we can close this issue

**Comment by AlexanderLyNL** [comment]
Hi Julius, do you mean that this is solved with 0.13, or the next one? I think you mean 0.13, so I close this. If not, please reopen.

**Comment by juliuspf** [comment]
Ja sorry, with the recent release 0.13.0 we fixed this issue.

**Comment by mshyde** [comment]
Hi Julius, 

I just downloaded the newest version for Mac, but the reliability analyses aren't available in this version. I double-checked if it's the right version after installing. I was wondering whether there are any updates on this?

**Comment by EJWagenmakers** [comment]
In the latest version, Reliability have moved away from the ribbon and is now available as a module. (click on the + sign on the top right to see the modules, then check the box to activate)

**Comment by juliuspf** [comment]
see here: https://jasp-stats.org/wp-content/uploads/2020/07/Bayesian_Reliability-1.gif

**Comment by mshyde** [comment]
Thank you! Perfect. And I am sorry I didn't see that, I only checked all the dropdown menus from the modules that I had already added. 

I had just downloaded an older version and just reverse coded my items manually before entering them, which worked as well, but it's nice to use one version again!
