### ISSUE TITLE
Multigroup CFA doesn't work

### ISSUE THREAD

**Issue by MTom68** [jasp-stats/jasp-issues#541]
* JASP version: 0.11.1
 
* OS name and version: Windows 10 Home Version 1803
* Analysis: Confirmatory Factor Analysis
* Bug description: Multigroup CFA doesn't work, after defining grouping variable it produces error report (see attached screenshot)
![Screenshot 2019-11-05 12 57 55](https://user-images.githubusercontent.com/57398271/68207935-5ec8a900-ffd0-11e9-8516-d33a47b86458.png)
![Screenshot 2019-11-05 12 57 55](https://user-images.githubusercontent.com/57398271/68207939-5ff9d600-ffd0-11e9-8755-871bf854b67d.png)

* Expected behaviour: correct analysis

**Comment by AlexanderLyNL** [comment]
Could you please share the jasp file as a zip? Then we can look into it more thoroughly.

**Comment by MTom68** [comment]
Hi,
I have the attached JASP file - however, I wonder if it contains the data
as well since the original data set is in SPSS...
Please let me know whether this is the right file or should I send the
original SPSS.

Obviously, data is confidential. Please handle it accordingly.

Thanks for your help,
Tamas



AlexanderLyNL <notifications@github.com> ezt írta (időpont: 2019. nov. 7.,
Cs, 10:17):

**Comment by MTom68** [comment]
Hi, did you get my previous post?
Would it work for checking the problem or should I provide any other
information?
Meanwhile, we encountered a similar problem (not on my computer):
multigroup CFA analysis works for one dichotomous variable but doesn't work
for other (non-dichotomous) variables.

Best, Tamás


Martos, Tamás <martos.m.tamas@gmail.com> ezt írta (időpont: 2019. nov. 22.,
P, 18:23):

**Comment by vankesteren** [comment]
Hi Tamás,

I'll work on this ASAP after the christmas/new years break!

Erik-Jan

**Comment by MTom68** [comment]
Great, thanks for the info.
Tamas


Erik-Jan van Kesteren <notifications@github.com> ezt írta (időpont: 2019.
dec. 20., P, 11:28):

**Comment by MTom68** [comment]
Hi, could you eventually get forward with this issue?
Thanks, Tamas

Dr. Tamás Martos, Ph.D., habil.
clinical health psychologist
associate professor
Institute of Psychology
University of Szeged
https://www.researchgate.net/profile/Tamas_Martos
+36 30 9649935


Martos, Tamás <martos.m.tamas@gmail.com> ezt írta (időpont: 2019. dec. 20.,
P, 11:54):

**Comment by boutinb** [comment]
@vankesteren Is this implemented in 0.12?

**Comment by vankesteren** [comment]
It seems to work on my machine. @MTom68 One more question: was the grouping variable you tried to enter here a computed column?

**Comment by MTom68** [comment]
Thanks for the feedback, we will check it out.
The grouping variables were originally assessed ones, that is, not
computed. Does it make a difference, it means?
thanks, Tamas

Dr. Tamás Martos, Ph.D., habil.
clinical health psychologist
associate professor
Institute of Psychology
University of Szeged
https://www.researchgate.net/profile/Tamas_Martos
+36 30 9649935


Erik-Jan van Kesteren <notifications@github.com> ezt írta (időpont: 2020.
ápr. 1., Sze, 13:39):

**Comment by HeikoBreitsohl** [comment]
Hi!
I get the same error message as in the first screenshot by MTom68 whenever I check the "Include mean structure" option under the Model Options menu. This happens regardless of which factor scaling method is selected.
