### ISSUE TITLE
BugReport - Chi-square goodness-of-fit test 

### ISSUE THREAD

**Issue by secircle** [jasp-stats/jasp-issues#544]
* JASP version: 0.11.1

* OS name and version: Windows 10
* Analysis: Chi-square goodness-of-fit test procedure 

* Bug description: Mismatch on the descriptive data and data label (see ppt file)

* Expected behaviour:
It seems 0.9.1 works okay, but there is an error for the proportion in 0.9.1 as well. 

#### Steps to reproduce:
[JASP_MultinominalTestError.pptx](https://github.com/jasp-stats/jasp-issues/files/3816622/JASP_MultinominalTestError.pptx)

[M303_Uber_Rank.zip](https://github.com/jasp-stats/jasp-issues/files/3816633/M303_Uber_Rank.zip)

**Comment by boutinb** [comment]
@vandeman Can you check this problem?

**Comment by vandenman** [comment]
Thank you for reporting the problem! The problem was fixed already by @ASarafoglou . if you use a nightly build the correct figure is displayed.
