### ISSUE TITLE
Issue with reading in SAV files

### ISSUE THREAD

**Issue by Alan-Pickering** [jasp-stats/jasp-issues#545]
* JASP version:0.11.1

Windows 
* OS name and version: 
7
* Analysis: 
Importing a .sav SPSS file into Jasp, 
* Bug description:
 JASP dos not seem to read the system missing values for variables from SPSS files correctly and it scrambles the file (at least for the variables with SPSS system missing values)
* Expected behaviour:
Should either read them all correctly (ideally) or create a consistent value for all of them (less good but if this is known then the data can be filtered in Jasp)

1) Open the file (this is a sample data file from an OSF source)
[Lab_Study_2.zip](https://github.com/jasp-stats/jasp-issues/files/3819208/Lab_Study_2.zip)
2) extract SPSS file Study 2 Data for Sharing.sav
3) Open in Jasp
4) do Jasp descriptive stats on a variable with system missing data
      Variable WattsRC 
5) Look at output
Jasp reports there are 160 cases for WattsRC at this stage, with 23 missing, including some WattsRC which have a value of zero
6) Compare SPSS on the same file
the SPSS shows there are 158 valid cases and 25 with system missing values!!
and no cases with a zero value
7) find the cases in Jasp data which have value of zero for variable WattsRC by manually scanning data column
the last two cases in the file now have a value of zero for WattsRC !? (the values are 60 and 100 in original SPSS file)
8) to facilitate seeing how JASP has read in the data incorrectly, I made a new SPSS file in which I simply sorted the file Study 2 Data for Sharing.sav by pprn in "ascending" order (the nominal variable coding each participant), and dragged over the WattsRC variable to lie next to it. I resaved as SPSS file.
This file is here
[Lab Study 2 Data for Sharing sorted by pprn and move WattsRC.zip](https://github.com/jasp-stats/jasp-issues/files/3819592/Lab.Study.2.Data.for.Sharing.sorted.by.pprn.and.move.WattsRC.zip)
9) now when I open this new file in Jasp it is correct and has processed all the system missing values for WattsRC correctly
10) I made another version of the original SPSS file in which I just sorted by pprn, so that WattsRC was uninvolved, and this file worked fine when read into JASP
NB in all these operations I was careful never to have the same file open in SPSS and JASP at the same time

Summary
a) Jasp isn't reading in all files correctly where there are SPSS system missing values for some variables. 
b) It seems to scramble the relationship of the variable with missing data to the other variables in the file. 
c) It is a pretty hard to spot issue given that a trivial operation on the SPSS file avoided the bug

**Comment by JorisGoosen** [comment]
First of all, thank you for the incredibly detailed bug report!
I have just installed SPSS and will make sure the problems you noticed will not occur again.

**Comment by Alan-Pickering** [comment]
Glad to have been of some help. Jasp is excellent. Thanks for making this tool available.

Best

Alan

Sent from my iPad

On 22 Jan 2020, at 12:13, Joris Goosen <notifications@github.com> wrote:

﻿

First of all, thank you for the incredibly detailed bug report!
I have just installed SPSS and will make sure the problems you noticed will not occur again.

**Comment by JorisGoosen** [comment]
Well thanks for this issue and the dataset, it helped me test the reading of sav's quite a bit.
SPSS does allow people to enter weird data though, but I think JASP can now handle it quite a bit smoother.
