### ISSUE TITLE
Whitelist the lag function for creating new variables

### ISSUE THREAD

**Issue by tkasci** [jasp-stats/jasp-issues#546]
* JASP version: 0.1.11

* OS name and version: macOS 10.15.1
* Bug description: The `lag` function is used to lag a variable. This is useful for time series analysis and should be whitelisted.
* Expected behaviour: `lag` should create the lagged version of a variable.

#### Steps to reproduce:
1. Open any data set with a numeric variable
2. Create computet column using R code
3. Enter `lag(variable)` where `variable` is any numeric variable in the data set.
4. Error: `Non-whitelisted function used: lag`

**Comment by boutinb** [comment]
This will be in JASP 0.12
