### ISSUE TITLE
bayesian binomial sequential analysis, reversed label of strength of evidence on graph?

### ISSUE THREAD

**Issue by tjbelliveau** [jasp-stats/jasp-issues#548]
* JASP version: 0.11.1

#### Steps to reproduce: Frequencies > Bayesian Binomial > Sequential Analysis
Unless I am misinterpreting the graph, the label which populates the field for Strength of Evidence does not correspond with the data / evidence graph below, and I suspect it's reversed

![image](https://user-images.githubusercontent.com/57575906/68535822-82fcf080-0316-11ea-8625-b808ec1ac674.png)

**Comment by TimKDJ** [comment]
Thanks for bringing this to our attention, we've fixed it
