### ISSUE TITLE
there is no package called 'withr'

### ISSUE THREAD

**Issue by DrDaveExeter** [jasp-stats/jasp-issues#551]
* JASP version: Version 0.9.2

* OS name and version: Win7
* Analysis: Logit
* Bug description: Error with plot
* Expected behaviour: I see a plot

#### Steps to reproduce:
1. Go to '...' Regression
2. Click on '....' Logistic Regression
3. Analysis works fine

Model summary
--

> Model | Deviance | AIC | BIC | df | Χ² | p | McFadden R² | Nagelkerke R² | Tjur R²
> H₀ |   | 1337 |   | 1339.249 |   | 1344.294 |   | 1147 |   
> H₁ |   | 1249 |   | 1267.003 |   | 1312.415 |   | 1139 |   | 88.245 |   | < .001 |   | 0.066 |   | 0.108 |   | 0.226 |  
>  
> Coefficients |   |   |   |  
>   | 95% Confidence   interval |   |   |   |  
>   | Estimate | Standard Error | Odds Ratio | z | p | Lower bound | Upper bound |   |   |   |  
> (Intercept) |   | -1.801 |   | 0.234 |   | 0.165 |   | -7.704 |   | < .001 |   | -2.259 |   | -1.342 |   |   |   |   |  
> SEX |   | 0.068 |   | 0.1 |   | 1.07 |   | 0.675 |   | 0.499 |   | -0.129 |   | 0.264 |   |   |   |   |  
> PARHOME |   | 0.142 |   | 0.036 |   | 1.153 |   | 4.008 |   | < .001 | *** | 0.073 |   | 0.212 |   |   |   |   |  
> ethnic6 |   | -0.107 |   | 0.086 |   | 0.898 |   | -1.244 |   | 0.214 |   | -0.276 |   | 0.062 |   |   |   |   |  
> RESILIENTG |   | -0.207 |   | 0.071 |   | 0.813 |   | -2.909 |   | 0.004 | ** | -0.346 |   | -0.068 |   |   |   |   |  
> DISABLED |   | 0.067 |   | 0.167 |   | 1.07 |   | 0.402 |   | 0.687 |   | -0.26 |   | 0.394 |   |   |   |   |  
> ARGUEHME |   | 0.19 |   | 0.105 |   | 1.21 |   | 1.806 |   | 0.071 |   | -0.016 |   | 0.397 |   |   |   |   |  
> DVPHYS |   | 0.604 |   | 0.286 |   | 1.829 |   | 2.107 |   | 0.035 | * | 0.042 |   | 1.165 |   |   |   |   |  
> ENJOYLES |   | 0.298 |   | 0.065 |   | 1.347 |   | 4.571 |   | < .001 | *** | 0.17 |   | 0.426 |   |   |   |   |  

Note.  risky2 level   '1' coded as class 1.
--

4. But asking for plot produces a crash every time

> This analysis terminated unexpectedly.
> Error in loadNamespace(name): there is no package called 'withr'
> Stack trace

[Risky2017.xlsx](https://github.com/jasp-stats/jasp-issues/files/3841671/Risky2017.xlsx)

**Comment by TimKDJ** [comment]
This is fixed in our newer versions (see https://jasp-stats.org/download/)

**Comment by DrDaveExeter** [comment]
Thanks, should have thought of that!

**Comment by TimKDJ** [comment]
No worries :)
We've added loads of features since 0.9.2 -- enjoy!
