### ISSUE TITLE
Path diagram doesn't show; gives error message

### ISSUE THREAD

**Issue by user-group** [jasp-stats/jasp-issues#552]
* JASP version: 0.11.1
* OS name and version: MacOS
* Analysis: Structural Equation Modeling, Advanced, Path Diagram
* Bug description:

The box for "Path diagram" is ticked, but no path diagram is presented.
Instead, a red error message appears, stating:

"attempt to select more than one element in integerOneIndex"

#### Steps to reproduce:
1. Load the data file (which I can share, but can't make public)
2. Include the model description in the Lavaan model input box
3. Ensure that the "Path diagram" option is ticked.
4. Run analysis.

**Comment by Marian-Popa** [comment]
I had the same problem in JASP 0.11.1, and it persists now, in JASP .12.
OS Win 10.
Data file: BFI
Analysis: Structural Equation Modeling, Advanced, Path Diagram
Syntax:
Agreableness =~ A1+A2+A3+A4+A5
Extraversion =~ E1+E2+E3+E4+E5
Consciousness =~ C1+C2+C3+C4+C5
Nevrotism =~ N1+N2+N3+N4+N5
Openess =~ O1+O2+O3+O4+O5

Path Diagram Error:
attempt to select more than one element in integerOneIndex

Marian Popa

**Comment by Marian-Popa** [comment]
Problem solved after setting to Scale the measurement level of all variables in the model!

Marian Popa

**Comment by AlexanderLyNL** [comment]
Thanks for confirming it's been fixed.

**Comment by user-group** [comment]
Could you indicate how to do this, please?

**Comment by Marian-Popa** [comment]
In Data window, one left click on the icon associated to variable name, then change the level from Nominal or Ordinal, to Scale. And so on, for all variables in the model. 
m. popa
