### ISSUE TITLE
JASP in an RDS environment: clipboard doesn't work

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-issues#554]
From the JASP Forum:

"I wonder if anyone else has had a similar experience and can offer some advice...
We use JASP in an RDS environment, distributing it to our end users as a RemoteApp.

However, the clipboard doesn't work.

If I run the program locally, the copy function is fine. If I connection to the console / admin RDP session, then the clipboard also works. However if I use a "regular" RDP session or use it in a RemoteApp, the clipboard doesn't seem to function.

Just to add, the clipboard is fine for other apps, and I've confirmed that the clipboard is enabled in the .rdp file.

Has anyone else come across this before?"

**Comment by tomtomme** [comment]
@boutinb 
I guess this one can be closed, since this bug depends on the exact RDP / RDS software used and we have no details on that. Not even the OS (version).
We also had no other issues regarding RDP or RDS over the years

**Comment by boutinb** [comment]
What is strange is that apparently the copy/paste works for other applications. I wonder what was exactly copied from JASP. the whole result, the table or only the plots.. But as we don't have access to the original requester (I have tried it to find him on our JASP forum, but could not find him), we will probably never know. So let's close it.
