### ISSUE TITLE
Syncing JASP-SPSS 26

### ISSUE THREAD

**Issue by Saguaroman** [jasp-stats/jasp-issues#555]
* JASP version:  0.11.1
* OS name and version: Windows 10
* Analysis:  Syncing data files
* Bug description: When I make changes in an SPSS data file linked to a JASP file, the changes don't show up in the JASP data.

* Expected behaviour: When I double click the SPSS file opens, I make changes to numbers in the SPSS file and I expect those will show up in the JASP file, either instantly, or at least when I actively request that it sync files via sync data-current file. This doesn't happen, but JASP does recognize the correct local file (i.e., it "knows" which SPSS file to sync with, but doesn't pay attention to changes in that file).  I have both the JASP files and SPSS files saved on a local disk in the same directory.  

[test.zip](https://github.com/jasp-stats/jasp-issues/files/3864667/test.zip)

#### Steps to reproduce:
1. Unzip the attached JASP and SPSS files. 
2. Open the JASP file and double-click in data to open paired SPSS file.
3. Make any change in the SPSS file and save. 
4. Does the change appear in the JASP file? It doesn't for me... 

[test.zip](https://github.com/jasp-stats/jasp-issues/files/3864671/test.zip)

**Comment by Saguaroman** [comment]
Hi:  Has there been any progress on this issue?  I continue to have this problem across multiple machines. It is going to be a challenge to teach stats with JASP this coming semester if editing SPSS data files isn't possible. Thanks!  Jake

**Comment by JorisGoosen** [comment]
Hello, I didn't have the chance to look at it yet but was certainly planning to do so before the next release, it sounds like it probably isn't too involved to fix.

**Comment by JorisGoosen** [comment]
So it turns out @boutinb already fixed this while working on other synchronization issues.
We are planning to start testing next week and hopefully a release soon after (barring, of course, bugs).

**Comment by Saguaroman** [comment]
Many thanks!
