### ISSUE TITLE
JASP crashes when creating a new column

### ISSUE THREAD

**Issue by jasminemoreira** [jasp-stats/jasp-issues#557]
* JASP version: 0.11
* OS name and version: MacOS Mojave
* Analysis: none
* Bug description: crash
* Expected behaviour: create a new column

#### Steps to reproduce:
1. Open a CSV tables
2. Add a new column using "+" button
3. Fill the name
4. Choose the type
5. Click on "Create Column" 
6. See error

[logs.zip](https://github.com/jasp-stats/jasp-issues/files/3869301/logs.zip)

**Comment by JorisGoosen** [comment]
So it just crashes directly after you click "Create Column"?

And does it also crash with a different data?

**Comment by jasminemoreira** [comment]
The error simply disappeared after a couple of days. I can't reproduce it anymore and I have no clue about what was wrong. I did not change the table neither updated anything. Sorry about that, I think this issue can be closed.

**Comment by JorisGoosen** [comment]
Well, at least it works now!
