### ISSUE TITLE
JASP Crashes on big tables analysis  

### ISSUE THREAD

**Issue by jasminemoreira** [jasp-stats/jasp-issues#561]
JASP version: 0.11
OS name and version: MacOS Catalina
Analysis: Contingency Tables
Bug description: Crashing
Expected behaviour: Not crashing

#### Steps to reproduce:
1. Go to Frequencies
2. Click on Contingency Tables
3. Chose two fields (TP_TURNO, TP_GRAU_ACADEMICO)

[teste.csv.zip](https://github.com/jasp-stats/jasp-issues/files/3898298/teste.csv.zip)

**Comment by bulgerland** [comment]
I'm encountering the same issue with a 9MM+ record file. I am unable to share the file due to client restrictions.

**Comment by JorisGoosen** [comment]
@bulgerland are you also working on MacOS Catalina?

**Comment by bulgerland** [comment]
I am. We broke the file up into 3MM record segments and had the same issue.

**Comment by jasminemoreira** [comment]
@JorisGoosen I do!

**Comment by JorisGoosen** [comment]
@jasminemoreira yeah I saw, that is why I asked.

I'll check it out before the next release. And unless something truly crazy is going on it will be fixed then, next release will probably be next month somewhere.

**Comment by jasminemoreira** [comment]
@JorisGoosen Thank you very much!!! :-)

**Comment by JorisGoosen** [comment]
So it turns out we already fixed it, for me 0.11.1 crashes and the development version for 0.12 works already.
