### ISSUE TITLE
More graphic outputs in regression/classification tree analysis

### ISSUE THREAD

**Issue by App-State-Prof** [jasp-stats/jasp-issues#564]
Thank you for the new machine learning module. Is is possible to add more graphic outputs for regression and classification trees? I am currently using Radiant, a GUI add on to R studio.

Please see below, tree output helps in publications.

![tree](https://user-images.githubusercontent.com/33431829/69913606-ae4f9880-1407-11ea-973a-39f6aa544675.JPG)

Dr. Thomas Mueller
Appalachian State University

**Comment by koenderks** [comment]
I remember that we have also had discussions about this output when implementing the module. The issue we ran into back then was that the results of the random forest and boosting analyses are based on multiple trees, and we were unsure whether showing one of these might be appropriate. Except it you specify one tree? After that, priorities kind of shifted to other things. 

It would be useful to implement this in the next release. Maybe you can advise on how to handle this? How does Radiant handle this?

**Comment by App-State-Prof** [comment]
Koen thank you for looking into this. It has been a while since I ran tests
for regression and classification trees. However, for the test settings I
used, one tree was represented for each test. I would different types of
tests, and parameters, to build different trees. Then I would use the one
that made the most sense to my readers for the related Journal article.

**Comment by koenderks** [comment]
Thanks for the comment. I believe that the problem with showing one tree in the boosting and random forest methods is that they do not resemble the total outcomes. The total outcomes are based on an ensemble of trees, so showing one might not be representative of the solution. 

I think the solution to this issue is the following. Add a new analysis: `decision trees` (which only creates 1 tree) for classification and regression. In such a way there is no confusion about the output.

**Comment by App-State-Prof** [comment]
Koen that is excellent. I will be honest, simplicity is best for me. A
decision tree option for classification and regression trees would be the
best for students, too!


Thomas S. Mueller PhD MBA
Professor, Advertising Communication
Faculty in Residence, founder Active Living RLC
Appalachian State University
(828)262-2228
profwriter.com

**Comment by koenderks** [comment]
Hi @App-State-Prof,

JASP 0.16.1 has just released and includes the requested decision tree analyses in the machine learning module. Any feedback would be much appreciated!

**Comment by App-State-Prof** [comment]
All looking good so far! Have to be sure to use highly abbreviated variable
labels, also stretch and shift graphics sizing to show the detail in the
tree. Here's my latest data test in regression with affective involvement
as Target for perception of social action advertising:

[image: image.png]
Thomas S. Mueller PhD MBA
Professor, Department of Communication
Faculty in Residence, founder Active Living RLC
Appalachian State University
(828)262-2228
profwriter.com

**Comment by App-State-Prof** [comment]
Can you tell me, what are the numbers depicted on on the edges between the
nodes? Variables were measured on a 1-7 likert scale. I am used to splits
based on the parameters of those measures. This is how the output looks
using R Studio with the add on Radiant:

[image: image.png]
Thomas S. Mueller PhD MBA
Professor, Department of Communication
Faculty in Residence, founder Active Living RLC
Appalachian State University
(828)262-2228
profwriter.com

**Comment by App-State-Prof** [comment]
Not sure what I changed, now I am seeing the likert measure splits:

[image: image.png]
Thomas S. Mueller PhD MBA
Professor, Department of Communication
Faculty in Residence, founder Active Living RLC
Appalachian State University
(828)262-2228
profwriter.com

**Comment by koenderks** [comment]
Yes that's true about the short labels etc. I'll try to find a way to make this more user friendly in a next version! Unfortunately I cannot see the images you tried to include, but the numbers in the tree indeed give the split point. Hoewever, by default all analyses standardize the predictors, so they are not likert anymore. However, if you uncheck "scale predictors" under advanced options the analysis should use the raw data and show the liker split points. Heads up, I already noticed a bug for predictors that consist of text, but have fixed it for a next version.

**Comment by App-State-Prof** [comment]
Thanks again...instead of copy and paste images I saved as files, they are
attached.

Thomas S. Mueller PhD MBA
Professor, Department of Communication
Faculty in Residence, founder Active Living RLC
Appalachian State University
(828)262-2228
profwriter.com

**Comment by App-State-Prof** [comment]
Another insight...when I drag from bottom right and manipulate dimensions
of image it "resets" and takes a better form. See attached.

Thomas S. Mueller PhD MBA
Professor, Department of Communication
Faculty in Residence, founder Active Living RLC
Appalachian State University
(828)262-2228
profwriter.com

**Comment by koenderks** [comment]
Yes you can resize the image to make it more readable. The complexity parameter is indeed something that affects the tree. In contrast to the other analyses in the ml module, currently we lack optimization for the decision tree analyses. The plan for 0.17 is to add optimization over this complexity parameter.

Best,
Koen

**Comment by App-State-Prof** [comment]
This is great for now. Just told students in my research class to upgrade
to 16.1. I'll add a decision tree assignment later in the course!


Thomas S. Mueller PhD MBA
Professor, Department of Communication
Faculty in Residence, founder Active Living RLC
Appalachian State University
(828)262-2228
profwriter.com

**Comment by koenderks** [comment]
Hi @App-State-Prof,

If you go to https://github.com/jasp-stats/jasp-issues/issues/564, you see that there are still no images visible ;) Regardless, I would suggest one of two options: 1) making a new issue for this at https://github.com/jasp-stats/jasp-issues/issues, or 2) starting a new discussion on https://forum.cogsci.nl/categories/jasp-bayesfactor. Of course, we'll gladly assist with any questions regarding interpretation!
