### ISSUE TITLE
"Drag and drop" to build SEM models

### ISSUE THREAD

**Issue by App-State-Prof** [jasp-stats/jasp-issues#565]
I have attempted to use the Structural Equation Model in JASP but it requires coding. See below this is the open source GUI I have been using. It's "drag and drop" to build model, much like AMOS, then import data into model. Can we add this non code model building into the JASP SEM module?

http://onyx.brandmaier.de/

![onyx](https://user-images.githubusercontent.com/33431829/69913726-85c89e00-1409-11ea-83a0-fd07cae055c3.JPG)

Thank you!
Dr. Thomas Mueller
Appalachian State University

**Comment by vankesteren** [comment]
Hey Thomas,

we are aware of onyx, and while it is free it is unfortunately not open source, and the license is unclear. This makes it hard/impossible for us to integrate this. In the future, we might look at a graphical interface for SEM, but for now it is not on top of our to-do list.

The documentation states that it is possible to generate `lavaan` code from the onyx interface, however, so you can paste it into JASP from there!

Erik-Jan

**Comment by App-State-Prof** [comment]
Erik-Jan thank you...I will try to bring the code over from Onyx...would
like to experiment with that.

Thomas S. Mueller PhD MBA
Professor, Advertising Communication
Faculty in Residence, founder Active Living RLC
Appalachian State University
(828)262-2228
profwriter.com
