### ISSUE TITLE
Exploratory Graph Analysis

### ISSUE THREAD

**Issue by sujitiiml** [jasp-stats/jasp-issues#567]
Can we have incorporate exploratory graph analysis similar to "EGA" package by Golino (2018) (https://github.com/hfgolino/EGAnet).

I believe this is necessary and will add to the functionality and usefulness of network analysis in JASP.

**Comment by tomtomme** [comment]
this is a duplicate of the more precise https://github.com/jasp-stats/jasp-issues/issues/2414

Issue can be closed
