### ISSUE TITLE
Problems with displaying figures 

### ISSUE THREAD

**Issue by YifeiLi121** [jasp-stats/jasp-issues#568]
The figures are not displayed in JASP.  I can only see it afer saving as photos.

**Comment by boutinb** [comment]
Can you give me more information as described in the Bug Report template of the issue?

**Comment by FransMeerhoff** [comment]
Hi @YifeiLi121 

Can you please give us a detailed description of your problem and/or the status of this issue?
We cannot help you further without a reproduction path.

Kind regards
Frans Meerhoff

**Comment by FransMeerhoff** [comment]
Hi @YifeiLi121 

Please reopen this  problem persists.

Kind regards
Frans Meerhoff
