### ISSUE TITLE
Contingency table with non-standard characters in value labels (SPSS file)

### ISSUE THREAD

**Issue by spacek123** [jasp-stats/jasp-issues#57]
I'm using SPSS file with variables that uses some value labels with non-standard characters (non-latin-1 sets, or '¦' etc.). Descriptive frequencies are working as expected but Contingency table analysis results in strange behaviour: these variables are working when set in Rows but return missing cells (.) when set in Columns.

example:
![image](https://cloud.githubusercontent.com/assets/25134207/26776449/7ba5830e-49d9-11e7-8efb-3786ca5fe79e.png)

## Environment (for bugs)
* JASP version: 0.8.1,2
* OS name and version: Windows 10 64bit
* Analysis: Contingency table

**Comment by JorisGoosen** [comment]
If I run this in the latest version of JASP (0.10.0.0) refreshing the analysis fills up the missing values so the problem seems to be fixed.
