### ISSUE TITLE
Innstallation and opening in Mac failed

### ISSUE THREAD

**Issue by LorentzEL** [jasp-stats/jasp-issues#570]
* JASP version:

* OS name and version: MAc OS Catalina 10.15.1
* Analysis: I want to install and use the latest version of JASP. 
* Bug description: The program cannot be opened. Because Mac cannot check the program for "bad" programs.
* Expected behaviour: what can I do?

**Comment by FransMeerhoff** [comment]
Hi @LorentzEL 

We are aware of this problem (signing of the software has changed in Catalina) but there is a simple work-around for this issue:
After installation:
- If you go to the application folder and you RIGHT click on the JASP app and open it, it opens a window about the check about the malicious software. Now click on OK
- If you RIGHT click on the JASP app for the second time and open there is now and 'Open' option on the  dialog. Click on this Open button, but do not wait for this.
-  Now double click on the JASP.app JASP should start now.

I hope this will help you out.
If not please let me now.

Kind regards 
Frans Meerhoff.

**Comment by LorentzEL** [comment]
Thank you very much. I found my way around the problem. 
Best regards

Lorentz

**Comment by AlexanderLyNL** [comment]
Thanks for reporting back.
