### ISSUE TITLE
3-way repeated measures ANOVA

### ISSUE THREAD

**Issue by galitshaham** [jasp-stats/jasp-issues#571]
* JASP version: 0.11.1.0
* OS name and version: Windows 10
* Analysis: repeated measures ANOVA
* Bug description: When adding my variables I get the following error and no results. What is this about?
--------------------------
[FacesInContextValidation2.zip](https://github.com/jasp-stats/jasp-issues/files/3983548/FacesInContextValidation2.zip)

This analysis terminated unexpectedly.

Error in `[<-.data.frame`(`*tmp*`, i, 'GG', value = c(XTGFiZWw = 0.748248791567315, : replacement has 2 rows, data has 1

Stack trace
analysis(dataset = dataset, options = options, perform = perform, callback = the.callback, state = oldState)

.resultsSphericity(options, epsilon, mauchly, model)

`[<-`(`*tmp*`, i, 'GG', value = c(XTGFiZWw = 0.748248791567315, `XTGFiZWw:XQm9keQ:XRmFjZQ` = 0.886307254042842))

`[<-.data.frame`(`*tmp*`, i, 'GG', value = c(XTGFiZWw = 0.748248791567315, `XTGFiZWw:XQm9keQ:XRmFjZQ` = 0.886307254042842))

stop(sprintf(ngettext(N, 'replacement has %d row, data has %d', 'replacement has %d rows, data has %d'), N, n), domain = NA)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

**Comment by JohnnyDoorn** [comment]
This is fixed in the rewrite, please reopen if not fixed in the next release.
