### ISSUE TITLE
Adjust slope or wrap long labels

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#574]
In JASP 0.11.1 I get overlapping labels even if I stretch the graph quite a bit, see the middle plot here:
<img width="1206" alt="Screenshot_20191220_185717" src="https://user-images.githubusercontent.com/4428185/71281167-834cca80-235d-11ea-9750-93c709f9373a.png">

Would be nice to adjust the slope / angle of long labels. Or to auto-wrap the labels into more rows.

**Comment by boutinb** [comment]
We will add Plot editing so that you can adjust the labels. Not the next release, but the release afterwards. But maybe can @vandenman give you some tricks to get a better plot.

**Comment by tomtomme** [comment]
Thats good to hear :) Thanks for the info. Some tricks would be apreciated.

**Comment by vandenman** [comment]
Unfortunately, this is the best we can do at the moment. You could rename the labels to be shorter or use abbreviations.

**Comment by tomtomme** [comment]
@boutinb: Is plot editing with label adjusting still in the pipeline? The feature did not make it for 0.13 or 0.14 as far as I can tell.

**Comment by boutinb** [comment]
No, that's true... but in 0.15 it will be there. Really!

**Comment by tomtomme** [comment]
pressing thumbs :D
