### ISSUE TITLE
Linear Discriminant Classification

### ISSUE THREAD

**Issue by jazjef** [jasp-stats/jasp-issues#575]
* JASP version: 0.11.1

* OS name and version: Windows 10
* Analysis: Linear Discriminant Classification
* Bug description: coefficients exist, but 'constants' for the functions are missing
* Expected behaviour: function coefficients should be accompanied by their constants----these are necessary to create the classification equation.

#### Steps to reproduce: 
Simply run any 'Linear Discriminant Classification' analysis ..... constants are not generated in the output along with the coefficients.

**Comment by koenderks** [comment]
Alright, thanks! Should be implemented in the next release via Pull Request https://github.com/jasp-stats/jasp-desktop/pull/3710. 

See image below:

![image](https://user-images.githubusercontent.com/25059399/71767935-e4ee6680-2f11-11ea-9657-731526c445bd.png)

**Comment by koenderks** [comment]
If you keep track of when the pull request is merged into the development branch, you can download the version of JASP containing the fix for the constants the following day at http://static.jasp-stats.org/Nightlies/
