### ISSUE TITLE
Post-hoc tests in frequentist ANOVA - wrong answer I believe

### ISSUE THREAD

**Issue by nelsoncowan** [jasp-stats/jasp-issues#576]
I have carried out a repeated measures ANOVA in the same way using Bayesian and frequentist ANOVA methods and you can tell from the marginal means that the post-hoc tests in the frequentist ANOVA are somehow wrong. The attached file provides all of the information you need....By the way, I wish the marginal means could be shown within the Bayesian analysis as well.
[CowanIssueFrequestistPostHocs.zip](https://github.com/jasp-stats/jasp-issues/files/4020723/CowanIssueFrequestistPostHocs.zip)

**Comment by EJWagenmakers** [comment]
@JohnnyDoorn ?

**Comment by JohnnyDoorn** [comment]
I think this was resolved by email, please reopen this issue if something is still unclear =)
