### ISSUE TITLE
OSX : Filename in the Dock

### ISSUE THREAD

**Issue by McAlyster** [jasp-stats/jasp-issues#578]
* Enhancement: Display the name of the file in the Dock or the swtich app banner 
* Purpose: Really handy when many JASP files are open 
* Use-case: Let's say I have 5 JASP documents open, one per experimental blocks I am currently working on. When I want to switch (with a keyboard shortcut) from a JASP doc to another, I have to let the document getting displayed to see its title.The name of the document is not displayed on the switch app banner neither it is on the dock.

**Is your feature request related to a problem? Please describe.**
 

**Describe the solution you'd like**
 

**Describe alternatives you've considered**
 

**Additional context**

![jasp-feature-req](https://user-images.githubusercontent.com/202794/71781962-ecc30f00-2fd4-11ea-8b64-d5723c8fb0fb.jpg)
![jasp-feature-req2](https://user-images.githubusercontent.com/202794/71782013-68bd5700-2fd5-11ea-95ba-ed154fa10df1.jpg)

**Comment by JorisGoosen** [comment]
This has been implemented.

**Comment by tomtomme** [comment]
@McAlyster 
Is this still an issue? Can other apps on OSX do this?

**Comment by JorisGoosen** [comment]
This issue looks like it would be good to implement but honestly given that noone can come up with an actual app that does this and the answers here that indicate that it doesnt seem possible.
