### ISSUE TITLE
Reporting a bug in 0.11.1 with contingency tables.

### ISSUE THREAD

**Issue by amandairions** [jasp-stats/jasp-issues#579]
* JASP version: 0.11.1

* OS name and version: High Sierra 10.13.6
* Analysis: 
* Bug description:

Error in (new('C++Function', .Data = function (...) : map::at:  key not found

Stack trace
analysis(dataset = dataset, options = options, perform = perform, callback = the.callback, state = oldState)

.readDataSetToEnd(columns.as.factor = factors, columns.as.numeric = counts.var)

.fromRCPP('.readDatasetToEndNative', unlist(columns), unlist(columns.as.numeric), unlist(columns.as.ordinal), unlist(columns.as.factor), all.columns ≠ FALSE)

do.call(obj, args)

(new('C++Function', .Data = function (...) 
{
    .External(InternalFunction_invoke, xp, ...)
}, pointer = , docstring = character(0), signature = character(0)))(NULL, NULL, NULL, c('whotargets', 'wmantype'), FALSE)

* Expected behaviour: An output containing a contingency table with the variables whotargets and wmantype

#### Steps to reproduce:
1. Go to '...' Frequencies --> Contingency Tables
2. Click on '....' whotargets, wmantype, Expected Counts, Total Percentages
3. See error

**Comment by boutinb** [comment]
Hello @amandairions, can you send a JASP file with your error?

**Comment by FransMeerhoff** [comment]
HI @amandairions 

We are not able to solve your problem without the previous request of boutinb.
Please let us know if it is not possible to send us the JASP file, or can you provide another way so that we can reproduce your problem here, e.g. a simplified version of you dataset.

Kind regard,
Frans Meerhoff
