### ISSUE TITLE
JASP crashes for mixed bayesian anova

### ISSUE THREAD

**Issue by metamorphose42** [jasp-stats/jasp-issues#58]
## Environment (for bugs)

* JASP version: 0.8.1.2
* OS name and version: macOS Sierra 10.12.4
* Analysis: Bayesian repeated measures ANOVA (mixed design)
## Environment (for enhancement requests)
Hi,
I'm trying to run a bayesian mixed design ANOVA (within:2x2x2 &between:x2x2). It works for just the within but when I add the between subject factors it doesn't compute (see screenshot for how I input my data) 

and then shuts JASP down. It gave me the message to let you guys know (see screenshot).
Thanks!
* Enhancement:
* Purpose:

<img width="1075" alt="screen shot 2017-06-10 at 15 29 52" src="https://user-images.githubusercontent.com/18419722/27003152-beb1701a-4df1-11e7-8255-4efec970aee9.png">

<img width="1389" alt="screen shot 2017-06-10 at 15 22 19" src="https://user-images.githubusercontent.com/18419722/27003096-e7f16d5a-4df0-11e7-963a-7eee94006ec1.png">

**Comment by JorisGoosen** [comment]
It seems there is no longer any problem here except for combinatorial explosion, which indicates I can close this issue.
