### ISSUE TITLE
Partial Plots don't display regression line

### ISSUE THREAD

**Issue by blogfrey** [jasp-stats/jasp-issues#581]
* JASP version:  Version 0.11.1

* OS name and version:  Win 10
* Analysis: 
* Bug description:  Partial plots display a horizontal regression line in multiple linear regression.  Instead, they should display the same slope as the multiple regression coefficient.  Please correct this, or tell me how I can change a setting to correct it.  Thank you.
* Expected behaviour:  See above.

**Comment by boutinb** [comment]
@Kucharssim Can you have a look to this problem?

**Comment by blogfrey** [comment]
Thank you for your help.

Dan
