### ISSUE TITLE
Feature request: Add reporting of dependent variable in regression table output

### ISSUE THREAD

**Issue by blogfrey** [jasp-stats/jasp-issues#582]
Hello,
Can you please add, in the linear regression table output, a listing of the dependent variable used in the model?  While a small point, it facilitates efficient management of one's analyses, especially if one is assessing multiple models.  Thank you.

**Comment by boutinb** [comment]
@Kucharssim can you see also this issue? It it is easy to add, can you decide whether it should be in the next release?

**Comment by blogfrey** [comment]
Thank you.

**Comment by FransMeerhoff** [comment]
@TimKDJ 

A pull request is ready for this but Travis fails, can you have a look at this?

**Comment by TimKDJ** [comment]
This will be included in 0.12

**Comment by blogfrey** [comment]
Thank you.
