### ISSUE TITLE
Jasp for MacOs Catalina version 10.15.2

### ISSUE THREAD

**Issue by tayavictoria** [jasp-stats/jasp-issues#584]
I cannot open the Jasp app, as it says "JASP can’t be opened because Apple cannot check it for malicious software" " this software needs to be updated. contact the developer for more information". When will this be solved? or is there a way to get around this?

**Comment by boutinb** [comment]
Hi @tayavictoria, we are aware of this problem with OS Catalina. You can still open JASP by right-clicking the icon app, and selecting the open menu. The first time it will give a warning, the second time it should open JASP.
The next JASP release (over 1 month) should not have this problem.

**Comment by boutinb** [comment]
Hi @tayavictoria Did you manage to open JASP?

**Comment by tayavictoria** [comment]
Hi,
Yes I was able to open it but the functions didn’t work.

**Comment by FransMeerhoff** [comment]
HI @tayavictoria 

Can you please tell us a bit more precise about the 'functions didn't work' ?
- You can open JASP and see the welcome screen and I assume you are using version JASP 0.11.1?
- Can you open a data file afterwards? 
- Does some special analysis fail with this data?
- If so is it possible to sent us this data file or the JASP file that you are using, else please describe more detailed what functions you use, that would help us a lot.

Kind regards
Frans Meerhoff

**Comment by FransMeerhoff** [comment]
Hi @tayavictoria 

Please reopen or make new issue with detailed description, if the problem still occurs.

Kind regards,
Frans Meerhoff
