### ISSUE TITLE
Multilevel analysis on binary logistics

### ISSUE THREAD

**Issue by LorentzEL** [jasp-stats/jasp-issues#587]
I'm looking for a manual to describe both theoretical approach and actual steps when performing  logistic regression using dichotomous variables both as dependent and independent variables.
In other words: I would like to do a logistic regression calculating OR or RR on dichotomous or ordinal variables, but taking into a count that the the study population have some sort of nested relationship and are not true independent individuals.

Am I using the wrong terminology when I search for this? 
Where should I look?

Best regards

**Comment by boutinb** [comment]
@EJWagenmakers Could you answer @LorentzEL ?

**Comment by EJWagenmakers** [comment]
I think there are two issues. The first is that you wish to do logistic regression using dichotomous/ordinal predictors. @vankesteren can confirm, but I believe that this is detected and taken into account automatically (in the corresponding R functions) The second issue is that "the study population have some sort of nested relationship and are not true independent individuals". I am not quite sure what you mean -- can you give a concrete example? In general, whenever I hear "nested relationship" I immediately think of hierarchical/multi-level models (which we will implement in JASP soon).
Cheers,
E.J.

**Comment by vankesteren** [comment]
@EJWagenmakers I agree, this is a feature request for multilevel GLM

This is indeed not yet implemented in JASP!

**Comment by TomasAPalma** [comment]
@vankesteren @EJWagenmakers Any idea when you will be able to include such feature in JASP? Very looking forward for that!

**Comment by LorentzEL** [comment]
Thank you very much for all answers. This is indeed a feature request of multilevel GLM, which I'm also looking forward to see in JASP.
