### ISSUE TITLE
Feature request to analysis health data

### ISSUE THREAD

**Issue by Kibria2017** [jasp-stats/jasp-issues#59]
1. (a) non-linear, (b) ordinal, (c) conditional logistic regression and (d) multinomial logistic Regression
2. Poisson Regression including (a) negative binomial, (b) zero-inflated and (c) zero truncated Poisson regression
3. Survival Analyses - (a) log-rank test, (b) kaplan-meyer and (c) cox proportional hazard

Thanks

**Comment by tomtomme** [comment]
AFAIK non-linear regression capabilities are only partly tackled by flexplot, see: 
https://github.com/jasp-stats/jasp-issues/issues/1779 

All others available now in generalized linear modell and with the upcoming 0.18.2 in the survival analyses.
Can be closed then?

**Comment by boutinb** [comment]
Yes
