### ISSUE TITLE
JASP loses/transforms/does not display some data from SPSS database (.sav file)

### ISSUE THREAD

**Issue by p-deli** [jasp-stats/jasp-issues#590]
* JASP version: 0.11.1

* OS name and version: macOS 10.15.2 (Catalina)
* Analysis: 
* Bug description: when opening a .sav file (SPSS database), the data that has negative coding is replaced by another value. For example, Gender was coded -.5 for Male and .5 for Female was entirely replace by 0 = Female. Data that has been coded -.5 = Inter, 0 = Neutral, .5 = Indep, for example, becomes 0 = Indep.
I therefore went to recode, in SPSS,
[JASP-SPSS_Databases.zip](https://github.com/jasp-stats/jasp-issues/files/4077281/JASP-SPSS_Databases.zip)
 Gender to 1 = Male and 2 = Female, then when I open the new database, nothing appears in the column, however when I click on the label, value and label are correct.
* Expected behaviour: that imported data is not lost and/or transformed and that it appears in the columns of the data view.

"My" issue might be linked to this one: https://github.com/jasp-stats/jasp-issues/issues/550

For what it's worth, SPSS version is 25.0.0.0 (25.0.0.0)

Thanks and best regards

++++

**Comment by FransMeerhoff** [comment]
HI @p-deli ,

Thanks for reporting this and sending us the the data files.
We are busy trying to find what's going on here.
@boutinb  Can you have a look at this one ?

Kind regards 
Frans Meerhoff

**Comment by FransMeerhoff** [comment]
@JorisGoosen 

Can you have a look at this issue? ( I'm not really sure if not already busy with it)

Cheers Frans

**Comment by JorisGoosen** [comment]
@p-deli It sure does sound related to that issue, I'll check if my changes there fixed this.
