### ISSUE TITLE
calc problem

### ISSUE THREAD

**Issue by aegemen** [jasp-stats/jasp-issues#591]
Hi,

I used linux mint 19 and Libreoffice 6.3. I want to change default spreadsheet editor in JASP with calc

but ı cant change. I tried many times, but the spreadsheet editor can not be activated in JASP

![Ekran Görüntüsü - 2020-01-13 22-22-38](https://user-images.githubusercontent.com/60071339/72685049-33e1f180-3af7-11ea-8856-bad6da5e4117.png)

**Comment by JorisGoosen** [comment]
Aah yeah there seems to be a bug starting the editor when changing the editor manually on linux.
A workaround for now is simply setting calc as your default editor for csv in linux mint.

On my system I cannot manually enter one or I get roughly the same error as you. Just using the system defined default editor (in my case calc as well) works fine.
Changing what default application to use should be as simple as right-clicking it in some file-manager and choosing "Open With Other Application" or something.

**Comment by aegemen** [comment]
Sorry,
I guess you couldn't explain the problem correctly. I can't use  "calc" in JASP.

**Comment by JorisGoosen** [comment]
I can try again!

There is a bug in JASP with manually entering the executable name for the default spreadsheet editor. I'm going to fix this and in the next release you will be able to use it.

For now the only way I can help you with the version you use now is suggest a workaround. 
1. You  go to Preferences - Data and check "Use default editor".
2. You set your default spreadsheet editor in Linux Mint itself to "Calc" aka the executable you manually entered. This can be done in a file manager through the "Open With" menu action.

Is that a better explaination?

**Comment by aegemen** [comment]
JorisGoosen,
thanks a lot for your interest. I waiting the nex release....thanks again..

**Comment by JorisGoosen** [comment]
@aegemen have you tried the workaround I suggested?

**Comment by JorisGoosen** [comment]
I'm sorry to say that it won't actually be possible to select a different spreadsheet editor in JASP on linux. It cannot work due to the isolating nature of the sandbox that flatpak creates. 

I'm afraid the only way to make JASP use a spreadsheet editor in linux is through selecting a different default editor for the MIME type in your OS.
