### ISSUE TITLE
The names of the variables in comparison are lost.

### ISSUE THREAD

**Issue by MAgojam** [jasp-stats/jasp-issues#594]
* JASP version: 0.12
* Nightly builds: Jan 20 2020 10:52:32
* OS name and version: win10 pro (ita)
* Bug description: In the "Paired Samples T-Test" table, the gray lines lose the names of the variables in comparison.
See the attached screenshot.
![screenshot](https://user-images.githubusercontent.com/36552289/72891881-8698f480-3d15-11ea-9b9f-41741015c28e.PNG)

Thank you for your time.
Cheers,
Maurizio

**Comment by TimKDJ** [comment]
Yeah we performed a rather big code restructure and this slipped through -- whoops! I'll fix this soon; thanks for reporting.
