### ISSUE TITLE
Log odds ratio plots not correct?

### ISSUE THREAD

**Issue by DrMarkGS** [jasp-stats/jasp-issues#595]
* JASP version: 0.12 Dec 17 2019
* OS name and version: Windows 10
* Analysis: Bayesian contingency table
* Bug description: Log odds ratio plots annotated incorrectly

Data gives a BF10 of 5790 in favour of null hypothesis - in the plots both BFs are reported as BF-0 and the pizza plot appears to show evidence in favour of the null.
![image](https://user-images.githubusercontent.com/39003008/72972075-ad613480-3dc2-11ea-9557-0e9856567cda.png)

**Comment by TimKDJ** [comment]
That doesn't look right, I'll check it out

**Comment by FransMeerhoff** [comment]
Hi @TimKDJ 

As a reminder, can you have a look at this one?

Cheers Frans
