### ISSUE TITLE
Planned comparisons/contrasts with multiple levels

### ISSUE THREAD

**Issue by PeterKlaren** [jasp-stats/jasp-issues#596]
* Enhancement: Contrasts (ANOVA) that are composed of multiple groups
* Purpose: More versatile planned comparisons.
* Use-case:

**Describe the solution you'd like**
 
Combining levels of a factor in a contrast. The current ones in JASP 0.11.1 (simple, deviation, Helmert, etc.) are fixed.
For instance a contrast C=(μ1+μ2)/2−(μ3+μ4)/2.
**Describe alternatives you've considered**
 

**Additional context**

**Comment by FransMeerhoff** [comment]
Hi @JohnnyDoorn 
Can you consider this request?

**Comment by JohnnyDoorn** [comment]
Hi Peter,

I just added this functionality last night! So it will be in the next release (scheduled for next month).

Cheers,
Johnny

**Comment by PeterKlaren** [comment]
Hi Johnny, Wow! Thanks for your quick action! I am currently writing a syllabus for an undergraduate statistics course for bioscientists (using JASP), and just noticed that the fixed contrasts that JASP (and other software as well) offers are a bit limited. Most of all: how amazingly short the lines of communication with you people are! Problem/request/wish list solved within 24 hourse. Truly JASP’s forte! Cheers, and thanks again, Peter Verzonden vanuit Mail voor Windows 10 Van: JohnnyDoornVerzonden: vrijdag 24 januari 2020 14:46Aan: jasp-stats/jasp-issuesCC: PeterKlaren; AuthorOnderwerp: Re: [jasp-stats/jasp-issues] Planned comparisons/contrasts with multiple levels (#596) Hi Peter,I just added this functionality last night! So it will be in the next release (scheduled for next month).Cheers,Johnny—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by JohnnyDoorn** [comment]
Thanks Peter, that's very nice to hear - good luck with the course!
