### ISSUE TITLE
Displaying frequency graphs

### ISSUE THREAD

**Issue by ErinMMiller** [jasp-stats/jasp-issues#597]
My student has a HP Laptop 15-da0xxx and we are using JASP 0.11.1 We are doing simple distribution plots and frequency tables of interval and categorical data. The descriptive statistics are displayed but under Distribution Plots it is blank for her.

**Comment by FransMeerhoff** [comment]
Hi @ErinMMiller 

Is it possible that you, or your student, send us the JASP or data file where this problem occurs.
Or otherwise give us some more info how to reproduce this issue, and some more details.  E.g. we assume that she is working on a Windows Laptop.

Kind regards
Frans Meerhoff

**Comment by FransMeerhoff** [comment]
Hi @ErinMMiller 

We are in the test phase of releasing JASP 0.12 
Please reopen this issue if this problem still occurs on the new version.
We are not able to reproduce it.

Kind regards
Frans Meerhoff
