### ISSUE TITLE
Error with Bayesian Log Linear Regression in JASP

### ISSUE THREAD

**Issue by juliandefreitas** [jasp-stats/jasp-issues#60]
JASP version: 0.8.1.1
OS name and version: macOS Sierra, version 10.12.5

Hello,

When I run bayesian log linear regression in JASP, I keep getting the error "leading minor of order [x] is not positive definite". I don't get this error when running the frequentist log linear regression. Any help would be appreciated.

Thanks,
Julian

**Comment by Andreea-Szoke** [comment]
Hello! I have the same problem.
JASP Version 0.11.1, Windows 8.1 Pro
I don't know how to fix the problem...
Any help, please?

**Comment by juliuspfadt** [comment]
@juliandefreitas, @Andreea-Szoke, could you try with the latest JASP version and see if the error persists?
