### ISSUE TITLE
Unable to open dmg file to install

### ISSUE THREAD

**Issue by Hskeow9** [jasp-stats/jasp-issues#600]
* JASP version: 11.1.0
* OS name and version: macOS Catalina 10.15.2
* Bug description: Unable to open dmg file to install
* Expected behavior: The photo of my desktop screen is below. If you can't view it, can send it to you via email. I double-clicked the link, and file was trying to verify. Nothing happened after that. I've heard that there have been issues of people trying to install JASP with macOS Catalina. Any suggestions?

<img width="684" alt="Screen Shot 2020-01-27 at 2 38 51 PM" src="https://user-images.githubusercontent.com/60366158/73213026-10313380-4115-11ea-826b-775e9262ee4b.png">

**Comment by FransMeerhoff** [comment]
Ii @Hskeow9 ,

We are quite sure that you have to be VERY patient. It can sometime take almost half an hour that the verifying takes. se e.eg https://appletoolbox.com/why-is-macos-catalina-verifying-applications-before-i-can-open-them/
But if this succeeds you still have to do the following
After installation:
- If you go to the application folder and you RIGHT click on the JASP app and open it, it opens a window about the check about the malicious software. Now click on OK
- If you RIGHT click on the JASP app for the second time and open there is now and 'Open' option on the dialog. Click on this Open button, but do not wait for this!
- Now double click on the JASP.app JASP should start now.
I hope this will help you out, but please let us know you if you don't succeed.

Kind regards 
Frans Meerhoff

**Comment by FransMeerhoff** [comment]
HI @Hskeow9 

If the workaround described in the previous reply did not help, please reopen this issue.

Kind regards
Frans Meerhoff
