### ISSUE TITLE
Problem custom contrast

### ISSUE THREAD

**Issue by pandelis** [jasp-stats/jasp-issues#603]
* JASP version: 0.12 Jan 30 
[__Tests Contrastes Regression.zip](https://github.com/jasp-stats/jasp-issues/files/4138357/__Tests.Contrastes.Regression.zip)

I guess you already know it but for a simple one factor ANOVA with 3 levels, we need to enter 2 custom contrasts to have a result. (only 1 does not work)
In a simple one factor RM Anova, for the moment I cannot make custom contrasts for the moment.
"Error in lapply(X = X, FUN = FUN, ...): argument 'customContrast' is missing, with no default"
Stack trace

**Comment by FransMeerhoff** [comment]
HI @JohnnyDoorn 

Can you have a look at this issue?

Cheers Frans

**Comment by JohnnyDoorn** [comment]
Hi Pandelis, 

I just implemented the RM ANOVA contrasts - they will be merged shortly and then will become available in the nightly builds, in time for your class on the 11th. 

I removed the restriction where the contrasts need to sum to 0 - I guess that was a little bit of unnecessary paternalism. I am going to close this for now, please reopen if you have further questions or issues!

Cheers
Johnny
