### ISSUE TITLE
Request for help in JASP cannot continue & will close problem

### ISSUE THREAD

**Issue by redisol1621** [jasp-stats/jasp-issues#605]
* JASP version: JASP.011.1.0 
 Window 
* OS name and version: Window 10 64 bit
* Analysis:  Exploratory Factor Analysis
* Bug description: JASP experienced an unexpected internal error. The engine crashed ...
JASP cannot continue and will close
* Expected behaviour:

**Comment by FransMeerhoff** [comment]
@redisol1621 

Thanks for reporting this, but can you please send us the JASP file where this problem arises?
Or give us at least a clear description how to reproduce this problem, e.g. by using a data file from the data library?

Kind regards,
Frans Meerhoff

**Comment by redisol1621** [comment]
Thank you for your reply, here below I attached the SPSS file and the
problem arise when I run Exploratory Factor Analysis. As I mentioned before
I used Window 10, 64 bit and use the latest JASP version 0.11.1.0 for 64
bit. I used only the continuous variables to run the analysis on the
datasheet.
Best regards,
Solomon Dribsa

**Comment by FransMeerhoff** [comment]
Hi @redisol1621 

I'm sorry to say but we did receive your attached file.
Could you please try this again? You must put it in a zip file and drag and drop it to this issue.
Not from the reply of the mail message but from  this issue https://github.com/jasp-stats/jasp-issues/issues/605 in your browser.

Kind regards
Frans Meerhoff

**Comment by redisol1621** [comment]
[ezyzip.zip](https://github.com/jasp-stats/jasp-issues/files/4200509/ezyzip.zip)
here is the file

**Comment by redisol1621** [comment]
I attache the file

**Comment by FransMeerhoff** [comment]
HI @redisol1621 

Thanks for sending us the data file.
We can reproduce is now.

Hi @vankesteren, can you have a look at this one ?

![Screenshot 2020-02-18 at 10 27 36](https://user-images.githubusercontent.com/15656960/74723481-f0d08680-523a-11ea-81de-edaeda1b2549.png)

Cheers 
Frans Meerhoff

**Comment by vankesteren** [comment]
This is fixed in the next version of JASP!
