### ISSUE TITLE
No Copy LaTeX in Reliability Analysis table "Item Reliability Statistics" 

### ISSUE THREAD

**Issue by StaerkS** [jasp-stats/jasp-issues#608]
* JASP version: 0.11.1

* OS name and version: WIN10
* Analysis: Reliability
* Bug description: No Copy LaTeX in Reliability Analysis table "Item Reliability Statistics" possible, no sign "Latex code copied to clipboard" by clicking on "Copy LaTex", html works. In other tables it works but maybe more tables concerned.
* Expected behaviour: Repairing Copy to Clipboard

**Comment by FransMeerhoff** [comment]
Hi @StaerkS 

I tried this here on a Windows 10, with JASP 0.11.1 but I did could not reproduce it.
That's very strange because it is quite unlikely related to data.
And did you indeed checked that nothing was copied to the clipboard, so that perhaps only the message 'Latex Code to copied to clipboard' was missing?
Could you send as a JASP file where this problem occurs?
 
Kind regards
Frans Meerhoff

**Comment by StaerkS** [comment]
Hi,

yes I've checked the clipboard, really nothing in it, problem only in "Item Reliability Statistics".
Now I've tested it in a separate  JASP-File (attached+screenshot). The same problem, klick on "Copy Latex", no "Latex Code to copied to clipboard" sign, empty clipboard. I will test it later on my mac also.
Thanks for help!

Kind regards
Stefan

[JASP.zip](https://github.com/jasp-stats/jasp-issues/files/4191132/JASP.zip)

**Comment by FransMeerhoff** [comment]
Hi @StaerkS 

Thanks for sending us the JASP file.
We are now able to reproduce the problem.
 
@akashrajkn  can you have a look at this one?
(The problem also occurs an the development version)

Kind regards
Frans Meerhoff

**Comment by JorisGoosen** [comment]
@FransMeerhoff you could also assign an issue to someone if they should look at it.

**Comment by akashrajkn** [comment]
(Workaround) In JASP v0.14.1, if you refresh the analysis, copy latex code works. I am still investing why this is happening

[relability_clip_problem_test.zip](https://github.com/jasp-stats/jasp-issues/files/6239257/relability_clip_problem_test.zip)

**Comment by tomtomme** [comment]
I checked again with 0.18.2 beta. 
Normal copy paste works.
Latex copy paste does still only work after a analysis refresh.

**Comment by tomtomme** [comment]
Hi @shun2wang 
Why did you close this? The bug report is still valid. Or is this a "won't fix" situation because of the available workaround?

**Comment by tomtomme** [comment]
Ah sure. Should also have tested with some new file / data. Will do next time.
