### ISSUE TITLE
Keep row names visible when scrolling large tables (e.g. correlation matrices)

### ISSUE THREAD

**Issue by andyroberts1234** [jasp-stats/jasp-issues#61]
## Environment (for enhancement requests)
 
* Enhancement: When reading correlation matrices it is often hard to view the whole matrix in a single window. A useful feature would be to keep row names visible (i.e variable names/statistic used) when scrolling. This could work similar to the freeze panes option in excel (but not necessarily optional in JASP)
* Purpose: To improve readability of large matrices

**Comment by tomtomme** [comment]
Since we have heatmaps and the "display pairwise" option I think this can be closed.
