### ISSUE TITLE
Unable to save image or JASP files on a Linux Mint 19.3 platform

### ISSUE THREAD

**Issue by BP-sudo** [jasp-stats/jasp-issues#610]
* JASP version: 0.11.1

* OS name and version: Linux Mint v19.3
* Analysis: 
* Bug description: When I try to save an image or a JASP file, the new window which opens lacks a save button. Instead, it only offers 'Cancel' or 'Open'. Clicking on Open does not save anything.
* Expected behaviour: There should be a 'Save' button, and a drop-down menu offering different save formats.

#### Steps to reproduce: Please see the following screenshots.

![image](https://user-images.githubusercontent.com/60969335/74357070-40d0c880-4db7-11ea-875c-3e138175a21b.png)
Here, if I click the inverted triangle by the image, I get the following window without a Save option.

![image](https://user-images.githubusercontent.com/60969335/74357268-96a57080-4db7-11ea-8418-3dbf33b5eea0.png)

I'd be very grateful for your help. I've spent a lot of time today trying to get this to work. Thank you.

**Comment by FransMeerhoff** [comment]
Hi @BP-sudo 

Thanks for reporting this.
To get thing a bit clear first : saving an image or saving a JASP file or results can be done from different locations (from the result screen or from the file menu).  Can you tell me what you are using. 

See the images below.

<img width="375" alt="Screenshot 2020-02-13 at 09 19 18" src="https://user-images.githubusercontent.com/15656960/74415009-ccdc0200-4e42-11ea-842c-7a3a9d14624e.png">

<img width="147" alt="Screenshot 2020-02-13 at 09 27 12" src="https://user-images.githubusercontent.com/15656960/74415149-13316100-4e43-11ea-8c6f-6a3c1f21d501.png">

Kind regards 
Frans Meerhoff

**Comment by BP-sudo** [comment]
Thank you for your reply. I have tried saving from both the results screen and the file menu. I end up with the same problem.

**Comment by FransMeerhoff** [comment]
@JorisGoosen 

Can you have a look at this one.
No idea what's going on here.

Cheers Frans

**Comment by JorisGoosen** [comment]
Yes, I'll take a look at what's going on.

**Comment by JorisGoosen** [comment]
Hmm, if I look here on my system (arch linux) then everything works as expected. @BP-sudo could you give me the output of: `flatpak --version'

**Comment by BP-sudo** [comment]
Please could you
        explain how I access this. 
      
    Thank you.
    B
    
    On 21/02/2020 09:39, Joris Goosen
      wrote:
    
    
      
      Hmm, if I look here on my system (arch linux) then everything
        works as expected. @BP-sudo
        could you give me the output of: `flatpak --version'
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jasp-stats/jasp-issues/issues/610?email_source=notifications\u0026email_token=AORFC55S5BCA3PPVQSEYNGDRD6OM3A5CNFSM4KT5NVZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMSDRXA#issuecomment-589576412",
"url": "https://github.com/jasp-stats/jasp-issues/issues/610?email_source=notifications\u0026email_token=AORFC55S5BCA3PPVQSEYNGDRD6OM3A5CNFSM4KT5NVZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMSDRXA#issuecomment-589576412",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by JorisGoosen** [comment]
Yeah sure, just open a terminal (just typing `terminal` after you open the application menu in mint should get you one).
And then you type `flatpak --version` in there.

**Comment by BP-sudo** [comment]
Thank you.
    The output is:
    Flatpak 1.0.9
      
    
    On 21/02/2020 10:42, Joris Goosen
      wrote:
    
    
      
      Yeah sure, just open a terminal (just typing terminal
        after you open the application menu in mint should get you one).
        And then you type flatpak --version in there.
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jasp-stats/jasp-issues/issues/610?email_source=notifications\u0026email_token=AORFC53DXOCKJZKZHNIESBTRD6VXZA5CNFSM4KT5NVZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMSJF6Q#issuecomment-589599482",
"url": "https://github.com/jasp-stats/jasp-issues/issues/610?email_source=notifications\u0026email_token=AORFC53DXOCKJZKZHNIESBTRD6VXZA5CNFSM4KT5NVZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMSJF6Q#issuecomment-589599482",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by JorisGoosen** [comment]
Aah yes, this is a pretty old version, that might be the problem here.
If you would open up your terminal again and run the following three lines:
```
sudo add-apt-repository ppa:alexlarsson/flatpak 
sudo apt update 
sudo apt install flatpak
```
This will prompt you for your password and will then get flatpak straight from the principal author. After that I am hoping your problem will disappear!

**Comment by BP-sudo** [comment]
Thank you.
    I can now save JASP
        files!
    There are a couple of
        slight problems:
    
      The Save button is
          still labelled Open
      Once I save using
          the Open button, the JASP window freezes. I cannot do anything
          with it. I can't even close it. However, I can open a new JASP
          window and proceed as normal.
    
    I can live with both
        of these issues.
    I am extremely
        grateful to you. Thank you again.
    
    On 21/02/2020 11:10, Joris Goosen
      wrote:
    
    
      
      Aah yes, this is a pretty old version, that might be the
        problem here.
        If you would open up your terminal again and run the following
        three lines:
      sudo add-apt-repository ppa:alexlarsson/flatpak 
sudo apt update 
sudo apt install flatpak

      This will prompt you for your password and will then get
        flatpak straight from the principal author. After that I am
        hoping your problem will disappear!
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jasp-stats/jasp-issues/issues/610?email_source=notifications\u0026email_token=AORFC56UNQTD6VMFFTA522TRD6ZEBA5CNFSM4KT5NVZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMSLTNQ#issuecomment-589609398",
"url": "https://github.com/jasp-stats/jasp-issues/issues/610?email_source=notifications\u0026email_token=AORFC56UNQTD6VMFFTA522TRD6ZEBA5CNFSM4KT5NVZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMSLTNQ#issuecomment-589609398",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by JorisGoosen** [comment]
Great!

Something you can try in the terminal to solve these problems: 'flatpak update'.
And then probably it will update a bunch of other required components. Maybe that helps with the last problems?

**Comment by BP-sudo** [comment]
Alas, this didn't
        solve the last problems. However, it seems that at least I can
        iconise the frozen JASP windows. I'm happy to leave them in that
        state and just open a new one when needed. Presumably they'll
        all close when I switch off my machine.
    Again, I am most
        grateful to you. JASP is a great program; much more intuitive
        than RStudio, which I used to use (but which won't work on Linux
        Mint 19.x).
    
    On 21/02/2020 11:41, Joris Goosen
      wrote:
    
    
      
      Great!
      Something you can try in the terminal to solve these problems:
        'flatpak update'.
        And then probably it will update a bunch of other required
        components. Maybe that helps with the last problems?
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jasp-stats/jasp-issues/issues/610?email_source=notifications\u0026email_token=AORFC55YU4BXZXJPAEWKXM3RD64VPA5CNFSM4KT5NVZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMSN6KY#issuecomment-589618987",
"url": "https://github.com/jasp-stats/jasp-issues/issues/610?email_source=notifications\u0026email_token=AORFC55YU4BXZXJPAEWKXM3RD64VPA5CNFSM4KT5NVZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMSN6KY#issuecomment-589618987",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by JorisGoosen** [comment]
Too bad that did not help.

If they do not exit by themselves you can use the following command in a terminal: `killall org.jaspstats.JASP -s 9`
Beware though, this will immediately close all running instances of JASP.

A new release is in the works and this one adds support for different file-dialogs, maybe these will help. For now I guess the current workaround will have to do and at least you can save.

Happy to hear you enjoy using JASP!
