### ISSUE TITLE
Data not synchronising

### ISSUE THREAD

**Issue by DrMarkGS** [jasp-stats/jasp-issues#616]
@boutinb 

Screen shots and logs as requested
![image](https://user-images.githubusercontent.com/39003008/75035715-0a2a3a80-54a8-11ea-97e9-a0a1ddc45735.png)

![image](https://user-images.githubusercontent.com/39003008/75035738-1dd5a100-54a8-11ea-91ee-14eec85705d7.png)

[JASP 2020-02-19 15_42_30 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/4236082/JASP.2020-02-19.15_42_30.Engine.0.log)
[JASP 2020-02-19 15_42_30 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/4236083/JASP.2020-02-19.15_42_30.Engine.1.log)
[JASP 2020-02-19 15_42_30 Engine 2.log](https://github.com/jasp-stats/jasp-issues/files/4236084/JASP.2020-02-19.15_42_30.Engine.2.log)
[JASP 2020-02-19 15_42_30 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/4236085/JASP.2020-02-19.15_42_30.Desktop.log)

**Comment by DrMarkGS** [comment]
Just noted this
![image](https://user-images.githubusercontent.com/39003008/75041136-dfde7a00-54b3-11ea-9490-d9496117a858.png)

**Comment by FransMeerhoff** [comment]
Hi @DrMarkGS 

The log file states:
Sync file does not exist: L:/JASP/JASP data/JASP Bayes data/Bayesian correlation.csv
Like the error message but more specific.

Could you check that out please?

Kind regards
Frans Meerhoff

**Comment by TimKDJ** [comment]
Let's keep this centralized in https://github.com/jasp-stats/jasp-test-release/issues/622

**Comment by DrMarkGS** [comment]
I loaded the file directly from my external L: hard drive – so JASP must be able to see it.
Downloaded the Feb 25th nightly and everything seems ok now.
Mark
