### ISSUE TITLE
Memory issue with Repeated Measures

### ISSUE THREAD

**Issue by ghost** [jasp-stats/jasp-issues#617]
I've thoroughly enjoyed your product thus far and am excited to have a good option for repeated measures ANOVA.

I am currently having an issue when I run a repeated-measures ANOVA. When I attempt to run one, I get an error stating "cannot allocate vector of size 325.1 Mb".

I checked R and my memory limit is 16g, so I don't understand why I'm getting this error. How do I allocate more memory to JASP?

![JASP Error](https://user-images.githubusercontent.com/29062713/75674361-2e92cd80-5c85-11ea-94f0-749bd804d226.png)
![JASP Error (data)](https://user-images.githubusercontent.com/29062713/75674363-2f2b6400-5c85-11ea-99c5-6872703e0aae.png)
[Data Copy.csv.zip](https://github.com/jasp-stats/jasp-issues/files/4275205/Data.Copy.csv.zip)

**Comment by vandenman** [comment]
Thanks for the bug report! If you're using the 32-bit version of JASP then R can only use ~4GB of RAM. 

Either way, can you perhaps attach the .jasp file or tell us about the size of your data set (no. rows/ columns) so we can see why the analysis is using so much memory?

**Comment by JorisGoosen** [comment]
@shaunstearns which operating system are you using?

**Comment by shaunstearns** [comment]
I'm using Windows 10.

**Comment by JorisGoosen** [comment]
@vandenman it looks like the data is ~10000 rows by couple of dozen columns.

If I run the 0.11.1 version on linux I get a crash. However, the 0.12 test version keeps going. Although it takes forever. And it seems to require at least 5.2GB.

So then the question for @shaunstearns is, are you using the 32bit or 64bit version of windows?
And maybe you want to test with the latest test version? See here: http://static.jasp-stats.org/Nightlies/

Maybe that one works for you. But you should definitely use a 64bit version.

**Comment by JorisGoosen** [comment]
@shaunstearns let me know if you've tested the new version of JASP that I linked to.

**Comment by JorisGoosen** [comment]
@JohnnyDoorn or @vandenman do you think a runtime >45m is reasonable? I'll leave it running to see what happens, but it feels like it is a bit long.

**Comment by JohnnyDoorn** [comment]
Here is a simple example in R of a RM ANOVA with a dataset of 10,000 rows - for me it's also running very long already so I think the problem is more related to R/afex, I'll contact Henrik about it.

library(afex)
nObs <- 1e4
x <- paste0("t_", rep(1:3, each = nObs))
y <- rnorm(3 * nObs)
id <- factor(rep(1:nObs, 3))
df <- data.frame(x = x, y = y, id = id)
aov_car(y ~ x * Error(id/x), data = df)

**Comment by JorisGoosen** [comment]
Well, at least it means that the memory issue is probably solved, for me it peaked at 6GB and then went down a bit to ~4GB. Although the only person who could confirm it would be @shaunstearns, because theoretically something else could be going on there.

**Comment by shaunstearns** [comment]
Well, it took hours to run, gave me some omnibus stats and then immediately
crashed my computer (twice).

What is the recommended sample max for analysis in the program?

Best,
Shaun Stearns, PhD
Research Scientist
Google Scholar
<https://scholar.google.com/citations?user=yEon0LUAAAAJ&hl=en>
410-703-5645

**Comment by JorisGoosen** [comment]
Well, this seems to be more of a limitation in the actual ANOVA RM algorithm, I understood from colleagues that mixed models are more appropriate for such a large set of observations.

If I understood correctly @JohnnyDoorn or @vandenman ?

**Comment by vandenman** [comment]
The algorithm we currently use does not integrate out the random effects. Thus the resulting model scales with N and quickly becomes enormous. As a results, both R and JASP crash when analyzing this data (unless you're working on a computer with incredible specs).

A module for linear models with mixed effects is in the works, so hopefully that will solve the problem.

**Comment by JorisGoosen** [comment]
@vandenman that would be referring to https://github.com/jasp-stats/jasp-issues/issues/69 right?

**Comment by vandenman** [comment]
Yes #69 can hopefully deal with it. I haven't tested that yet though.

**Comment by tomtomme** [comment]
I tried this big dataset with RM ANOVA and it filled up 12 GB of RAM on my linux machine. I let it ran 15 minutes and it did go nowhere. No crash, no progress bar, no error message. 
We should do something about this. If n > 1000 or something, there should be a popup or message of some kind to better use the mixed-linear-model module. Also a hint that a manual wide to long conversion is needed for that.

**Comment by JohnnyDoorn** [comment]
I think this issue is solved by specifying the option to "use multivariate model for follow-up tests" in 0.18 - in version 0.19 this option is renamed (and its meaning reversed) to "pool error term for follow-up tests". Using the multivariate model is a lot more memory-efficient. Please reopen if not.
