### ISSUE TITLE
Reloading data file does not work (any more)  0.11.1

### ISSUE THREAD

**Issue by LTanas** [jasp-stats/jasp-issues#619]
* JASP version: 0.11.1

* OS name and version: Windows 10
* Bug description: Im editing a file in SPSS and doing an analysis in JASP. After I edit and save the file in SPSS, JASP (earlier versions) used to refresh the data/synchronize with the new file. This does not work anymore. Nor does the manual Ctrl+Y option work. I need to manually re open the file "Recent files" -> "Open data file" and this opens the updated file in a new JASP window. Closing SPSS after editing the file does not change this behavior.

**Comment by JorisGoosen** [comment]
@boutinb I can take a look and see if I can reproduce this on windows as well.

**Comment by boutinb** [comment]
@JorisGoosen Yes, thanks

**Comment by JorisGoosen** [comment]
I can confirm that the 0.11.1 does not sync when a .sav file changes. The current development does but it doesn't handle it well, I'm looking into it now.
