### ISSUE TITLE
Feature Request: Multivariate Analysis of Variance (MANOVA)

### ISSUE THREAD

**Issue by stefanroettger** [jasp-stats/jasp-issues#62]
Dear JASP developers,

first of all thanks for your excellent work, I was thrilled when I discovered JASP and I think it has a good chance to become the standard of statistical computing in social sciences over the next couple of years.

I would like to suggest the multivariate analysis of variance (MANOVA) for implementation in one of the upcoming versions.
As far as my daily research work is concerned, this family of analysis is what I frequently use and thus miss most in JASP.

Best regards,
Stefan

**Comment by SaraGarofalo** [comment]
I support this request, too. It would be incredibly handy!
Can you tell us if it is at least foreseen? Thanks

**Comment by TimKDJ** [comment]
MANOVA was implemented in 0.10

**Comment by rsbalkin** [comment]
we need discriminant analysis as a MANOVA post hoc
