### ISSUE TITLE
This analysis terminated unexpectedly.

### ISSUE THREAD

**Issue by lafanecm** [jasp-stats/jasp-issues#620]
When I clicked on 'Inferential Plots' for a Logistic Regression, I got this error:

Error in loadNamespace(name): there is no package called 'withr'

Stack trace
f(...)

with_seed_null(params$seed, transform_position(data, trans_x, trans_y))

withr::with_seed

getExportedValue(pkg, name)

asNamespace(ns)

getNamespace(ns)

tryCatch(loadNamespace(name), error = function(e) stop(e))

tryCatchList(expr, classes, parentenv, handlers)

tryCatchOne(expr, names, parentenv, handlers[[1]])

value[[3]](cond)

**Comment by TimKDJ** [comment]
If memory serves this is a rather old error. Am I correct in thinking you do not use JASP version 11.1?

**Comment by lafanecm** [comment]
You are correct - I'm using 0.9.2.0 release. Will update now and see what happens! Thank you!

**Comment by lafanecm** [comment]
It works with the latest version - thank you!

**Comment by TimKDJ** [comment]
That's good to hear!
