### ISSUE TITLE
Missing fields in correlation matrix after copying to MS Excel

### ISSUE THREAD

**Issue by viktorsvetsky** [jasp-stats/jasp-issues#621]
* JASP version: 0.11.1
* OS name and version: Windows 10 Pro
* Analysis: Bayesian Correlation Matrix
* Bug description: When I chosen Copy in Results in menu of Bayesian Correlation Matrix and than make Ctrl + V, there are lot of missing fields in the Excel, especcialy correlation koeficients itself.
* Expected behaviour: Matrix should copy to Excel properly.

#### Steps to reproduce:
1. Go to 'Regression'
2. Click on 'Bayesian Correlation Matrix'
3. Make matrix.
4. Go to the right part of screen to results window.
5. Click on the menu (triangel) next to Bayesian Kendall's Tau
6. Choose 'Copy'
7. Open MS Excel
8. Press "Ctrl+V"
9. See that in some cells there are missing data. Only '#FIELD!' is present. 

[bug.zip](https://github.com/jasp-stats/jasp-issues/files/4264337/bug.zip)

**Comment by tomtomme** [comment]
I tested this with libreoffice calc and with Excel in the Browser. Both copies were fine.
