### ISSUE TITLE
Incorrect P(inc|data) for Effects across mathed models in Mixed Bayesian ANOVA

### ISSUE THREAD

**Issue by AugustOlsson** [jasp-stats/jasp-issues#625]
* JASP version: 0.11.1

* OS name and version: Windows 10 Education
* Analysis: 10(ws)x2(bs)x2(bs) Bayesian Repeated Meassures ANOVA (MIXED)
* Bug description: 
When chosing the "effects across mathed models" version of effects the P(inc|data) seems to be very off. 

There is a very clear effect of "Block" in my data, evident from the BFinc factor. However the P(inc|data) seems to sugest that the evidence for inclusion is very low. I am interpreting this as a bug - but I might be missing something? Comparing the P(inc|data) when effects are not calculated across matched models there is a clear and understandeble relationship between the P(inc|data) and the BFinc factor.

Se tables in the attached document.

**Comment by vandenman** [comment]
Thank you for posting the report! That looks like a bug indeed. However, it is difficult for me to reproduce the problem. Could you perhaps attach the jasp file as a zip file on the issue?

**Comment by AugustOlsson** [comment]
Hi Vandenman,

I cannot upload the datafile here, since the forum is public and it concerns ongoing research. However I could email it to you personally if that works (given that you of course do not disseminate the data). If that approach is feasible, could you provide med with your email adress?

Best,
August

**Comment by vandenman** [comment]
Of course, I will not spread the data. My email is d.vandenbergh@jasp-stats.org.

**Comment by vandenman** [comment]
Just a heads up, I did not receive any email. In case you send one, something probably went wrong.

**Comment by AugustOlsson** [comment]
Oh, thats strange. I send an email just after you posted your email (to: d.vandenbergh@jasp-stats.org). Could it have gone to junkmail? I'll try again tomorrow when I'm back at work.

/August

**Comment by AugustOlsson** [comment]
Hi,

Just sent you another email. If this one doesn't find you either. Could you email me at august.collsioo@psyk.uu.se and I'll respond with the files.

**Comment by vandenman** [comment]
I received the email! I'll see if I can reproduce the problem and will keep you updated about any progress.

**Comment by vandenman** [comment]
So in the next version, we show both the posterior exclusion probabilities and the posterior inclusion probabilities, hopefully that clears things up. If anything else comes up feel free to reopen this issue or open another issue!
