### ISSUE TITLE
Robustness check plot error

### ISSUE THREAD

**Issue by PhilKuhnke** [jasp-stats/jasp-issues#626]
* JASP version: 0.11.1

* OS name and version: Windows, MacOS
* Analysis: Bayesian One Sample T-Test
* Bug description: Sometimes, the robustness check plot for BF_10 shows the BF_01 value for the user prior, and vice versa. In both plots, the dot for the user prior is missing. This bug occurs on both Windows and MacOSX (I have not tested Linux yet).

![Robustness_BF01](https://user-images.githubusercontent.com/6231936/76018641-b34d4800-5f20-11ea-94d9-4aaab4dbe2ce.png)
![Robustness_BF10](https://user-images.githubusercontent.com/6231936/76018645-b3e5de80-5f20-11ea-8936-d45800653777.png)

[JASP_file.zip](https://github.com/jasp-stats/jasp-issues/files/4294843/JASP_file.zip)

**Comment by akashrajkn** [comment]
In JASP `v0.14.1`, this issue does not occure

[Bayesian_OneSampleTtest_v014.zip](https://github.com/jasp-stats/jasp-issues/files/6239577/Bayesian_OneSampleTtest_v014.zip)
