### ISSUE TITLE
95% CIs for means

### ISSUE THREAD

**Issue by lukeplonsky** [jasp-stats/jasp-issues#628]
* Enhancement: CIs for means (not mean differences)
* Purpose: Help researchers understand their distributions and make more informed inferences
* Use-case: many

**Describe the solution you'd like**
- I understand that there's been a good deal of discussion and, ultimately, a decision on (not) providing CIs for means within the Descriptives function. However, there is currently no place anywhere in JASP to get CIs for means. Would you please consider adding 95% (and, possibly, 99%) CIs either under Descriptives and/or t-tests?

**Describe alternatives you've considered**
- A user can manually calculate 95% CIs with the M +/- (SE*1.96) but this a bit clunky and introduces potential for human error.

**Comment by juliuspfadt** [comment]
I think this is implemented by now. Feel free to reopen this issue, if anything remains unclear.
