### ISSUE TITLE
ANOVA Interactions without main effects

### ISSUE THREAD

**Issue by PhilKuhnke** [jasp-stats/jasp-issues#630]
For (repeated-measures) ANOVAs, is it possible to add the option to entertain models with interactions but without the corresponding main effects? E.g. the model AxB, whereas currently only the model A + B + AxB can be entertained. 
This could be an option to be ticked in the "Additional Options" tab, similar to how it is an option in the BayesFactor R package ('whichModels' option: 'all' vs. 'withmain'). 
It is often informative to look at these models (and their Bayes Factor), especially in situations where a cross-over interaction is plausible.

**Comment by FransMeerhoff** [comment]
Hi @PhilKuhnke 

Thanks for your suggestion.

@JohnnyDoorn Can you have a look at this one?

Kind regards 
Frans Meerhoff

**Comment by AlexanderLyNL** [comment]
The problem with models that include interactions without the main effects is that it leads to paradoxical inferences, which is why we did not include this option. @vandenman could you please add the relevant reference?

**Comment by EJWagenmakers** [comment]
From https://link.springer.com/article/10.3758/s13423-017-1323-7:
"Consistent with the principle of marginality, JASP does not include interactions in the absence of the component main effects; for instance, the interaction-only model “Gender × Pitch” may not be entertained without also adding the two main effects (for details, examples, and rationale see Bernhardt & Jung, 1979, Griepentrog, Ryan, & Smith 1982, McCullagh & Nelder, 1989; Nelder, 1998, 2000; Peixoto, 1987, 1990; Rouder, Engelhardt, et al., in press; Rouder, Morey, et al., in press; Venables, 2000)."

**Comment by PhilKuhnke** [comment]
I see, thanks a lot for the explanation and references!

**Comment by AlexanderLyNL** [comment]
I consider this issue fixed now. If unclear, please reopen.
