### ISSUE TITLE
Renaming Option in Graphs

### ISSUE THREAD

**Issue by imarevic** [jasp-stats/jasp-issues#631]
It would be nice to be able to rename parts of the rendered plot (e.g. axis). I am sure there must be a way in Qt to do this.

**Comment by vandenman** [comment]
Hi, I assume that you're talking about plot editing? If so, this is high on our to-do list (we hope to have this not in the upcoming release but in the one after that). Either way, this issue looks like a duplicate of https://github.com/jasp-stats/jasp-issues/issues/78, so I'm closing it. 

Feel free to re-open if I misunderstood the request!
