### ISSUE TITLE
Network analysis, multiple comparisons 

### ISSUE THREAD

**Issue by AL38000** [jasp-stats/jasp-issues#634]
* JASP version:0.11.1
 
* OS name and version: windows
* Analysis: Network
* Bug description: impossible to obtain a threshold value corrected ofr multiple comparisons
* Expected behaviour: 

#### Steps to reproduce:
1. Go to 'network'
2. Click on 'estimator/cor'
3. Scroll down to 'analysis options . cor' then 'threshold method - holm'
[Data PCB.zip](https://github.com/jasp-stats/jasp-issues/files/4312992/Data.PCB.zip)

4. See error 'this analysis terminated unexpectedly'

**Comment by juliuspfadt** [comment]
@AL38000, sorry for the late response. I cannot recreate the issue with the latest JASP version. Can you confirm?
