### ISSUE TITLE
Split parameter for all (relevant) analyses...

### ISSUE THREAD

**Issue by PsyTechMMU** [jasp-stats/jasp-issues#635]
* Enhancement: Add the 'Split' optional parameter to all relevant analyses
* Purpose: Analysis-specific tests on subsets of data without additional files and filtering
* Use-case: Perform any analyses on subsets of data within each analysis e.g., paired-samples t-tests within each group

**Comment by nahorp** [comment]
I would like to see this as well. It'd be great to be able to conduct analyses on subsetted data, all in one .jasp file rather than having multiple files.

**Comment by juliuspfadt** [comment]
I think this is also a kind of duplicate of https://github.com/jasp-stats/jasp-issues/issues/385

**Comment by juliuspfadt** [comment]
Let's all track this here: https://github.com/jasp-stats/jasp-issues/issues/1330

**Comment by tomtomme** [comment]
can be closed, since duplicate of 
https://github.com/jasp-stats/jasp-issues/issues/333
https://github.com/jasp-stats/jasp-issues/issues/385
https://github.com/jasp-stats/jasp-issues/issues/1330
