### ISSUE TITLE
Analyses order not retained...

### ISSUE THREAD

**Issue by PsyTechMMU** [jasp-stats/jasp-issues#639]
JASP version: 0.11.1
OS name and version: WIndows 10

Repro:
1. Open JASP file with mutliple analyses e.g., Album Sales from the data library (Regression)
2. Re-order one or more analyses  e.g., drag Descriptives to the bottom and save again
3. Close and reopen the JASP file
Observed: analyses are not in the saved order e.g., Descriptives is back at the top
Expected: order of analyses should be retained from when last saved

**Comment by FransMeerhoff** [comment]
Hi @PsyTechMMU 

Sorry for the late reaction, but we're in the middle of a test phase of a new JASP 0.12 release.
I'll check if this bug can be solved before that release.

Kind regards 
Frans Meerhoff

**Comment by JorisGoosen** [comment]
Aah, I can take a look at this. Maybe we forgot to update a certain list in JASP.
