### ISSUE TITLE
New version 12 chops off variable names in Network analysis

### ISSUE THREAD

**Issue by App-State-Prof** [jasp-stats/jasp-issues#641]
* JASP version: 0.12
 Windows 10
* OS name and version:
* Analysis: Network analysis cuts off variable names
* Bug description: When I set "Show variable names in legend" the new version cuts off the variable names
* Expected behaviour: Variable names are complete, this worked in prior versions.

![image](https://user-images.githubusercontent.com/33431829/76785249-7d635b80-678b-11ea-9051-58ef8dc11551.png)

![Network analysis consumer energy incentives Figure 3](https://user-images.githubusercontent.com/33431829/76786133-0af37b00-678d-11ea-9ddf-86d577c06af9.png)

[18 24 college or degree.xlsx](https://github.com/jasp-stats/jasp-issues/files/4339617/18.24.college.or.degree.xlsx)

**Comment by App-State-Prof** [comment]
FYI, I just checked to see if the underscore between words was the difference. It was not.

**Comment by JorisGoosen** [comment]
If you resize the plot a bit by dragging the bottomright corner a bit, do they show up again?
Or do they stay out of view?

**Comment by App-State-Prof** [comment]
Joris they stay out of view. They have somehow been cropped when they are
placed into that field.

**Comment by JorisGoosen** [comment]
@vandenman is this something that would be easy to fix?

**Comment by vandenman** [comment]
Unfortunately, this is not straightforward to fix because qgraph (the R package we use to visualize networks) uses base graphics, and those don't rescale fonts when resizing an image.

**Comment by App-State-Prof** [comment]
It seemed to scale the variable names to fit in the image in past versions.
Has there been some sort of change to the R code?

**Comment by JorisGoosen** [comment]
Could we not set the width of the graph just a bit bigger? Or does qgraph ignore that as well?

And we have changed quite some things in the r code, although qgraph seems to be the same version as before, so why it changed now?

Although, if I look at the two screenshots @App-State-Prof added then in seems that the ppi changed, the older one seems to be a factor of 2 smaller (so the ppi is double).

@App-State-Prof could you perhaps check in the menu: `Preferences -> Results -> Plot options` what kind of ppi settings you have?
Perhaps setting a custom one would give a different result?

**Comment by vandenman** [comment]
Hmm I just tried to replicate this on development but it seems to work as intended:

small image, variable names are cropped:
![image](https://user-images.githubusercontent.com/21319932/76861050-43ae5580-685c-11ea-83f7-525a0914b39a.png)

bigger image, less cropping:
![image](https://user-images.githubusercontent.com/21319932/76861112-5c1e7000-685c-11ea-9186-a0c8247aa043.png)

Perhaps this is specific to Windows 10?

@JorisGoosen We could do all that and it would work for this specific case, but not in general. Ideally, resizing scales the font so that it works for all (reasonable) cases.

**Comment by App-State-Prof** [comment]
I have never accessed that setting before. It is set to 380. I tried to low
and high of that number, no difference. Also checked "Use PPI of screen
plots" and no change, either.

[image: image.png]
Thomas S. Mueller PhD MBA
Professor, Advertising Communication
Faculty in Residence, founder Active Living RLC
Appalachian State University
(828)262-2228
profwriter.com

**Comment by App-State-Prof** [comment]
When you state resizing from small to larger image, how are you doing that?
Grabbing the lower right corner of the image and stretching it larger?

Thomas S. Mueller PhD MBA
Professor, Advertising Communication
Faculty in Residence, founder Active Living RLC
Appalachian State University
(828)262-2228
profwriter.com

**Comment by vandenman** [comment]
> When you state resizing from small to larger image, how are you doing that?
Grabbing the lower right corner of the image and stretching it larger?

Exactly that!

**Comment by App-State-Prof** [comment]
When I drag the image larger, the variable names remain cropped.

Thomas S. Mueller PhD MBA
Professor, Advertising Communication
Faculty in Residence, founder Active Living RLC
Appalachian State University
(828)262-2228
profwriter.com

**Comment by JorisGoosen** [comment]
Thank you for testing those options.

I'm working on windows, I'll try it out as well.

**Comment by JorisGoosen** [comment]
Hmm, so actually if I resize quite a bit (On windows 10) i can get:
![image](https://user-images.githubusercontent.com/29062713/76876153-d1e10680-6871-11ea-99f0-2503c3e6ed12.png)

**Comment by JorisGoosen** [comment]
It's not quite optimal and I think it couldn't hurt to make the default width of the plot likes twice what it is now if a legend is to be shown?

**Comment by App-State-Prof** [comment]
This is odd. I stretched the image very large. Then let go of the lower
right corner of the image. It seemed to correct for about a second, then
snapped back with variables showing! Seems one must "over stretch" to
capture the variables.

So this is about technique, rather than coding. Glad to know, I will tell
my students!



[image: image.png]


Thomas S. Mueller PhD MBA
Professor, Advertising Communication
Faculty in Residence, founder Active Living RLC
Appalachian State University
(828)262-2228
profwriter.com

**Comment by JorisGoosen** [comment]
Ah, that certainly is odd, I can't reproduce that behaviour. For me it unflinchingly resizes the plot to wherever I let go of the the corner...

**Comment by App-State-Prof** [comment]
Nonetheless is now works to capture the full variable names. I just made a
short video and sent to my students so they will know.

Thank you for helping I'm a big JASP promoter...just talking to an
analytics director at Bank of America telling her about JASP.


Thomas S. Mueller PhD MBA
Professor, Advertising Communication
Faculty in Residence, founder Active Living RLC
Appalachian State University
(828)262-2228
profwriter.com

**Comment by JorisGoosen** [comment]
I'm happy to hear you like our software that much, and good that this workaround is good enough for now.

I do think that enlarging the plot automatically with a legend would be a good plan though. @vandenman do you want to do this? I vaguely remember you being responsible for the network analysis and this seems like a small change.

**Comment by vandenman** [comment]
Sure I'll take care of it. Two other issues regarding network analysis are already on my plate and this would be easy to incorporate. For now, I'll just make the width larger if there is a legend. Perhaps we should think of a more general solution though (maybe similar to how RStudio does this?) as resizing can be a bit clunky/ unintuitive.

**Comment by App-State-Prof** [comment]
Thanks to you all on this fine service. I was just telling my research
methods class in a video how great you are at updates and development for
the new versions.

**Comment by EJWagenmakers** [comment]
Update: changing the "legend to plot ratio" setting solves the problem (maybe this is what you added as a fix, @vandenman ?). "It was set at .4, variables chopped off...set to .8, variables included in full."
