### ISSUE TITLE
Repeated Measure ANOVA cannot be run

### ISSUE THREAD

**Issue by luluLeng** [jasp-stats/jasp-issues#642]
I ran a 2 * 3 RMANOVA, but received something like this when I added the very last variable.

This analysis terminated unexpectedly.

Error in df[[termsRM.base64[i]]]: subscript out of bounds

Stack trace
analysis(dataset = dataset, options = options, perform = perform, callback = the.callback, state = oldState)

.resultsSphericity(options, epsilon, mauchly, model)

.approxChi(df[[termsRM.base64[i]]], n[[termsRM.base64[i]]], epsilonTable[i, 'W'])

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

**Comment by FransMeerhoff** [comment]
HI @luluLeng 

Could you give us some more info about this issue?
-What OS are you running ?
-Which version of JASP do you use ?
- Could you send us the datafile if possible with a clear reproduction ? 

Kind regards,
Frans Meerhoff
