### ISSUE TITLE
Running a basic SEM.  Measurement model was fine but structural model had this error message:

### ISSUE THREAD

**Issue by kszechy** [jasp-stats/jasp-issues#644]
"This analysis terminated unexpectedly.

Error in rawToChar(as.raw(out)): embedded nul in string: '�0��'

Stack trace"

* JASP version: 0.11.1

* OS name and version:  Windows 10 64 bit
* Analysis: Here is the syntax:

#measurement model
JobSat =~ JS1 + JS2 + JS3 + JS4 + JS5R
OrgComm =~ OC1 + OC2 + OC3 + OC4 
EnvSupp =~ EP1 + EP2 + EP3 + EP4
AttCow = ~ AC1 + AC2 + AC3 + AC4
StayInt =~ SI1 + SI2 + SI3 + SI4 

#structural Model
OrgComm ~ EnvSupp + AttCow + JobSat
StayInt ~ OrgComm
* Bug description: see above
* Expected behaviour:  should run the SEM with output  UPDATE:  Actually I did get the model to run.  I only get this error message if I try to select R2 in statistics.  Not sure why?

#### Steps to reproduce: see syntax above

[HBAT_SEM_KSversion.zip](https://github.com/jasp-stats/jasp-issues/files/4345782/HBAT_SEM_KSversion.zip)

**Comment by FransMeerhoff** [comment]
HI @vankesteren 
Could you have a look at this one, or else re-assign it?
Cheers Frans

**Comment by vankesteren** [comment]
I am also not sure why this is occurring, but I just checked it in version 0.12 and it should be fixed once this version is released!

@kszechy if you are in a hurry, you can get the latest nightly build from [the nightlies website](http://static.jasp-stats.org/Nightlies), where this problem should no longer occur.
