### ISSUE TITLE
Import data from Google sheets?

### ISSUE THREAD

**Issue by App-State-Prof** [jasp-stats/jasp-issues#645]
It has come to my attention some students do not have Microsoft products - Word, Excel, etc.

Would it be possible to work in Google sheets, then import from there into JASP?

Or, is there another open source product students could export to from Google Sheets, then import to JASP?

Considering the global community, it would be most inclusive to allow users to import from open source tools when using JASP.

**Comment by EJWagenmakers** [comment]
Surely Google sheets will allow a "save as .csv"? Also, OpenOffice and LibreOffice are open source alternatives with Excel-like ability.

**Comment by App-State-Prof** [comment]
Thank you! 

I tried a Google sheets save to .cvs, but that downloaded and opened in Excel.

Per your suggestion, I reviewed the OpenOffice website and will recommend this to all students who may not be able to afford Microsoft products. 

I'd suggest that after we get beyond the current social/health challenge, there will be a massive need for business products that do not cost employers and owners $$$ to access. I love JASP - and other open source products - no $$$ to purchase or license, students who move into small business will not have barriers to conducting professional research.

**Comment by EJWagenmakers** [comment]
So you use Google sheets to save a file as .csv; then you open JASP; then, from within JASP, you go to "open" and select the csv file from your computer. This should work, right? And yes, the corona crisis will hopefully make people realize that open-source software is the way to go!

**Comment by App-State-Prof** [comment]
Right now, if I save from Google sheets to .csv it downloads and opens in Excel. I am assuming if Excel was not on my computer - but OpenOffice Calc was, it would open in that program. Then bring from there into JASP.

**Comment by JorisGoosen** [comment]
This just means that your browser automatically assumes that whenever you download/click-a-link-ending-in-csv-extension you want it to open in Excel/Calc.

No problem, this can either be disabled somewhere in your browser. 
The easier options for you right now are:
- Save-as a csv from excel
- Right click the link in your downloads list in the browser and choose show-in-explorer. From there you should be able to open it in JASP.

**Comment by JorisGoosen** [comment]
Let me know if you run in more trouble but for the rest this isn't really a JASP issue but a local configuration thing, so Im closing this.

**Comment by App-State-Prof** [comment]
Great thank you. I will work with students who have access problems.

Thomas S. Mueller PhD MBA
Professor, Advertising Communication
Faculty in Residence, founder Active Living RLC
Appalachian State University
(828)262-2228
profwriter.com
