### ISSUE TITLE
Jasp keep crashing maybe after xsplit installation

### ISSUE THREAD

**Issue by ymhuang1005** [jasp-stats/jasp-issues#646]
Originally I was able to run JASP on my computer without problem. Last week, it just kept crashing when I tried to perform any analysis. It's not version issue as I just installed the latest version and it still kept complaining about an internal problem. However, I did manage to perform the analysis for once during my dozen attempts. 

I've only installed xsplit in between the last time I run JASP without problem and this time... I might be wrong though.

**Comment by FransMeerhoff** [comment]
Hi @ymhuang1005 

Thanks for reporting this but we need some  more info to help you out.

- What OS  and version has your computer (e.g. Windows 10 or Mac..) ?
- Which version of JASP it concerns ?
-  'It's not version issue as I just installed the latest version and it still kept complaining about an internal problem' I do not know exactly what you mean by that. Did you try to re-install JASP with the latest version and that gives an internal error and there is no more info about this internal error?

Kind regards
Frans Meerhoff

**Comment by vandenman** [comment]
Closed due to inactivity, feel free to reopen if the problem reoccurs!
