### ISSUE TITLE
Mac OS update - now JASP crashes

### ISSUE THREAD

**Issue by coxongithub** [jasp-stats/jasp-issues#648]
* JASP version: 0.11.1.0

* OS name and version: Mac OS Mojave 10.14.6 (18G4032)
* Analysis: 
* Bug description: Click on JASP icon, but crashes immediately, does not launch
* Expected behaviour: Click on JASP icon, JASP launches

#### Steps to reproduce:
1. Go to '...' JASP
2. Click on '....' JASP
4. See error: Crash report

**Comment by uhkeller** [comment]
It crashes immediately for me too, also on MacOS 10.14.6. It's a fresh install of JASP, haven't run it before. I'll attach the "problem details" that the crash reporter provides.
[jasp_crash_report.txt](https://github.com/jasp-stats/jasp-issues/files/4403031/jasp_crash_report.txt)

**Comment by JorisGoosen** [comment]
Thanks for reporting this issue and uploading the crash report as well, could you try out this (beta) version of the upcoming release: https://static.jasp-stats.org/JASP-0.12_notarized.dmg

I'm pretty sure this will solve that crash if the attached problem report @uhkeller is to be believed.

**Comment by uhkeller** [comment]
Yes, this version works. Thanks for the quick response!

**Comment by AlexanderLyNL** [comment]
Thanks for informing us that the fix works! Joris worked hard on getting the code notarised and I'm glad that it works. Please reopen if the issue resurfaces.
