### ISSUE TITLE
Custom Contrasts and RM Anova

### ISSUE THREAD

**Issue by pandelis** [jasp-stats/jasp-issues#649]
Hi

In an RM ANOVA when I contrast Oeil with Phasme and Larves, results are different in JASP and in Statistica and UDSAnova. Results alos differ for other contrasts...
image
![image](https://user-images.githubusercontent.com/3620214/77773728-4ffb9500-704a-11ea-8656-d17cf30bd768.png)

image
![image](https://user-images.githubusercontent.com/3620214/77773772-5be75700-704a-11ea-9042-77cac2c028f6.png)

Here are the datas:
[05 NourritureContrasteIntra.txt](https://github.com/jasp-stats/jasp-issues/files/4394504/05.NourritureContrasteIntra.txt)

 The difference is coming from the fact that UDSAnova and Statistica use a non pooled term error for within factors which is not the case for emmeans. They use a term error specific to the contrast.
In case this would be useful here are references concerning this contrast problem :

Winer, B. J. (1971). Statistical principles in experimental design. New-York: McGraw-Hill.
Myers, J. L. (2007). Fundamentals of Experimental Design. Collecting Spatial Data. Boston: Allyn & Bacon. https://doi.org/10.1007/978-3-540-31175-1_3
Myers, J. L., Well, A., & Lorch, R. F. (2010). Research Design and Statistical Analysis. Routledge. Retrieved from https://books.google.fr/books?id=nbsOIJ_saUAC

Best regards

**Comment by boutinb** [comment]
@JohnnyDoorn It's quite important to know if this something we have to solve for the release next week.

**Comment by JohnnyDoorn** [comment]
I think we can leave this for now, for the next release i'll have another look at the pooling/unpooling of error terms - we have it now as much in line with the emmeans as possible (for contrasts and post ho tests), which I think is good.

**Comment by tomtomme** [comment]
@JohnnyDoorn and @pandelis
Do you still consider this an issue?
We have the option to Pool error terms for post hoc tests now, but not for contrasts.
