### ISSUE TITLE
Jasp does not save all analyses

### ISSUE THREAD

**Issue by vdsmagt** [jasp-stats/jasp-issues#65]
## Environment (for bugs)

* JASP version: 8.1.2.
* OS name and version: 10.12.5
* Analysis: jasp does not save all analyses.
I have a data set, and on that set I do a number of analyses (both bayesian and frequentist), starting with a paired t-test. (then a bayesian paired t-test, f-paired t-test, b-paired t-test, f-repAnova and b-repAnova) all on different columns. I annotate the analysis  so i can send everything to my PhD student so we can discuss this later. 
However, when I reopen the file Jasp only appears to have saved the first analysis and I have lost everything else.

## Environment (for enhancement requests)
 
* Enhancement:
* Purpose:

**Comment by JorisGoosen** [comment]
I will close this issue as it actually depends on #340 and if that is resolved this issue will no longer occur.
