### ISSUE TITLE
Unexpected error on JASP

### ISSUE THREAD

**Issue by carolasom99** [jasp-stats/jasp-issues#650]
* JASP version: 0.11.1.0

* OS name and version: Windows 10
* Analysis: When I try to make an independent T-Test I immediatly get an "Unespected Internal Error" message.
* Bug description: It crashes JASP and closes immediatly
* Expected behaviour: I should be able to compare the variables I am trying to calculate.

#### Steps to reproduce:
1. Open ModeraciónDhPEFAnálisis-FINAL (2).sav
2. Click on T-Tests
3. Click on Independent Samples T-Test
4. Move variable PO underneath the Variables and Genero under Grouping Variable
5. See error

**Comment by JorisGoosen** [comment]
Sorry to hear you got an unexpected error, we are working hard on a new release and maybe you could test out [this beta version](http://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-development-f13579fc0b376d66f96084b5c1d57e2141d81588.msi)?

Maybe we already solved the problem you ran into.

**Comment by JorisGoosen** [comment]
We have released a new version today that probably solves your problem.
