### ISSUE TITLE
Cannot Open JASP

### ISSUE THREAD

**Issue by juliablumk** [jasp-stats/jasp-issues#651]
* JASP version: 0.11.1
* OS name and version: macOS Catalina 10.15.4
* Analysis: I have been using JASP since last year and suddenly it can't open the program anymore. Tried to download it again and it's not opening even after allowing it to open in system and preferences. 
* Bug description: "JASP" can't be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information.

 Steps to reproduce:
1. Go to website and download for Mac
2. Click on the download
3. Follow all instructions for installation 

<img width="434" alt="Screen Shot 2020-03-30 at 6 43 28 PM" src="https://user-images.githubusercontent.com/62900135/77941808-05348400-72bb-11ea-8dba-3a84630972ea.png">

**Comment by AlexanderLyNL** [comment]
I think that the following helps:

https://jasp-stats.org/installation-guide/

In particular,

> Newer versions of OS X need to have their “Gatekeeper” options relaxed, before they will allow software to be used that was downloaded from the internet (more info). You will need to change your Gatekeeper settings to “Allow applications downloaded from anywhere”. Having relaxed the Gatekeeper settings, the next step is to ‘right click’ or ‘control-click’ JASP in your Applications directory, and select ‘Open’ from the menu. This will present a window saying that JASP is from an unidentified developer; selecting “Open” will start JASP.

If this works for you, then please close this issue.

**Comment by juliablumk** [comment]
Thank you, I did follow all instructions and it does not open JASP.

**Comment by AlexanderLyNL** [comment]
It's probably a notarisation issue. Could you please try the following build:

https://static.jasp-stats.org/JASP-0.12_notarized.dmg

Then follow the instructions as described in the link
- finder 
- applications
- right click on jasp and select "open"

The newest version of macOS now requires notarisation, and this version should do the trick.

**Comment by juliablumk** [comment]
Okay it started working using the build, but I can't open it on the normal way. Is it possible that I can open JASP the normal way one day again? Thank you for your help.

**Comment by AlexanderLyNL** [comment]
It should open normally the next time you open it. Or when you click on a jasp-file. I consider the problem solved. Please reopen if the problem resurfaces.
