### ISSUE TITLE
Error for Between-Subjects Factor Marginal Means (Mixed-Design ANCOVA)

### ISSUE THREAD

**Issue by nickkitchen1** [jasp-stats/jasp-issues#653]
* JASP version: 0.11.1

* OS name and version: Linux Ubuntu 19.10
* Analysis: Mixed-Design ANCOVA (One 2-level repeated measure of "TimePoint" (Early/Late), Two 2-level between-subjects factors of "AgeGroup" (Older/Younger) and "VisGroup" (Vis+/Vis-) and 1 continuous covariate of normalized physical ctivity ("PA_ZScore")
* Bug description: Error message appears when trying to get marginal means for VisGroup*AgeGroup, specific error message below (also see attached image)...

Error in if (is.finite(value)) {: argument is of length zero
Stack trace
analysis(dataset = dataset, options = options, perform = perform, callback = the.callback, state = oldState)
.rmAnovaMarginalMeansTable(dataset, options, perform, status, fullModel)
.clean(r$lsmean[index])

* Expected behaviour: Output marginal means of VisGroup*AgeGroup in output table

#### Steps to reproduce:
1. Open attached .txt file named "PVLDAdapt_OLsRmvd_JASP.txt" and go to ANOVA -> Repeated Measures ANOVA
2. Enter "TimePoint" as RM Factor 1, then name Level 1 as "Early" and Level 2 as "Late". Move the DV variables "PVLD_Early" and "PVLD_Late" across into Repeated Measures Cells
3. Add "VisGroup" and "AgeGroup" to the Between-Subjects Factors, and "PA_ZScore" to the Covariate box
4. Under Additional Options, try and move VisGroup*AgeGroup across for Marginal Means, error appears

Extra Notes: 

1) It seems like the AgeGroup factor has not coded properly and is defaulting to the VisGroup codes of "Vis-" and "Vis+" - this is apparent if you try and get marginal means for AgeGroup which doesn't throw an error but appears with the VisGroup field codes

2) As an additional comment (maybe its necessary to make a separate inquiry for this) it would be preferable be able to get marginal means for all factors for this type of analysis to, as with the descriptive statistics output table (in my case AgeGroup*VisGroup*TimePoint). Only as these adjusted means are what I will need to plot to summarise the output of the model

![JASP_MixANCOVA_Error](https://user-images.githubusercontent.com/62970182/78086674-88b1ac00-7373-11ea-9029-ddc83a2116d9.png)
[PVLDAdapt_OLsRmvd_JASP.txt](https://github.com/jasp-stats/jasp-issues/files/4412078/PVLDAdapt_OLsRmvd_JASP.txt)

**Comment by tomtomme** [comment]
I checked and this is fixed with version 0.18.2

@nickkitchen1 
If it is not fixed on your side, feel free to reopen.
