### ISSUE TITLE
data upload error

### ISSUE THREAD

**Issue by williamares** [jasp-stats/jasp-issues#657]
* JASP version: 0.11.1

* OS name and version: Windows 10
* Analysis: 
* Bug description: I am having an upload issue.  I am uploading an excel created CSV file into JASP.  This file has 80 rows.  When uploading to JASP it is only showing 55 rows. It was showing only 59 rows with the same data yesterday.  On occasion, after resaving the data file with a different name it may work, but if I save, and reopen the .JASP file for my data analysis, it will show a truncated row count again.

**Comment by boutinb** [comment]
Hello @williamares, could you send the csv file (in zip format)?
