### ISSUE TITLE
Unexpected internal error - Exploratory Factor Analyses

### ISSUE THREAD

**Issue by Peeetrs** [jasp-stats/jasp-issues#659]
* JASP version: 0.11.1

* OS name and version: Windows 10
* Analysis: I saved my work to continue making Exploratory Factor Analyses but then when I removed one item from the variables, it reported unexpected internal error.
* Bug description: JASP couldn´t continue a closed.
* Expected behaviour: The variable will be removed and Factor Loadings will be recalculated.

#### Steps to reproduce:
1. Go to 'Exploratory Factor Analyses'
2. Try to remove any variable
3. See error
File: https://drive.google.com/open?id=1jxZsZZLmiha0HvbfSfg1dHItNDkLo3zN 
(it was too big to upload it here - even in .zip version)

**Comment by juliuspfadt** [comment]
@Peeetrs, I apologize for the late reply. If still possible, could you try with the latest JASP version, there have been quite some changes to the factor module since you made the issue :)
