### ISSUE TITLE
Translation to German: When/how to help best?

### ISSUE THREAD

**Issue by JoKeyser** [jasp-stats/jasp-issues#661]
With the first translation to Dutch becoming available, I was wondering if I can help with the translation to German?

Would it be helpful at this point in time, and if so, how best to do this? I guess the simplest approach would be to send a pull request with a `jasp_de.po` file, analogous to [jasp_nl.po](https://github.com/jasp-stats/jasp-desktop/blob/development/JASP-Desktop/po/jasp_nl.po)?

Would be happy to get this started, if it doesn't create unnecessary work for you.

**Comment by JorisGoosen** [comment]
Thank you for offering your help!

We are looking into some ways to simplify the translation process on some points. It would be a shame if you started now and it would turn out to be a waste of time.

But I think that translating an analogous file to jasp_nl.po as you suggest couldn't hurt. Right @boutinb and @FransMeerhoff ?

**Comment by JoKeyser** [comment]
@JorisGoosen thank you for your fast reply.
Simplifying the translation process will of course be great, but not necessary for me personally. The only blocker for me would be if the `.po`-file wouldn't be the format you need in the end. I'll wait for an answer from @boutinb or @FransMeerhoff :).

**Comment by JorisGoosen** [comment]
Well, the thing is, that `.po`-file is in the right format going forward. But it is only for the application's interface. There is also a `R-nl.po` [here](https://github.com/jasp-stats/jasp-desktop/tree/development/JASP-Engine/JASP/po) that must be taken into account, it translates the messages from the analyses R-code.

Besides that we have some temporary workarounds for translating help-files and menu's etc. Those are the ones that definitely need some work by us first. But translating just those two `.po` should be a large part of the effort already.

**Comment by boutinb** [comment]
Thank you really much for your offer to translate JASP in german. As said @JorisGoosen, we will have to change some algorithms for the translations. But you can already translate the 2 po files (when the 0.12 version will be released, hopefully next week), they will be used anyway. And it will easy to add them to the release.
We will make also a document for best practice (for Capital letters for example). We will contact you just after the release.

**Comment by JoKeyser** [comment]
Just in case anyone is interested in collaboration: I've started a branch with some initial translations, see https://github.com/JoKeyser/jasp-desktop/tree/translate-to-German.

**Comment by JoKeyser** [comment]
I've added PR #4031, not to be merged yet, but to keep track of my first steps, in case others want to collaborate.
@JorisGoosen , @boutinb , feel free to delete this, in case this creates more headaches for you than it solves.

**Comment by JoKeyser** [comment]
#4031 was merged, it should trickle down to Weblate soon for further edits. I'm closing this issue.

**Comment by EJWagenmakers** [comment]
I'm thrilled to see the German translation! Total geil! :-)
