### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by janderuiter** [jasp-stats/jasp-issues#663]
I re-downloaded JASP 0.11.1 and it crashes on my mac (tried multiple times)

Report:

Process:               JASP [43714]
Path:                  /Applications/JASP.app/Contents/MacOS/JASP
Identifier:            org.jasp-stats.jasp
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           JASP [43714]
User ID:               501

Date/Time:             2020-04-07 12:04:37.651 -0400
OS Version:            Mac OS X 10.14.6 (18G4032)
Report Version:        12
Bridge OS Version:     3.0 (14Y904)
Anonymous UUID:        AE5C4822-4AAB-91A9-86FD-1DC3804057E3

Time Awake Since Boot: 310000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 000000010f798000-000000010fc9a000 [ 5128K] r-x/rwx SM=COW  

Thread 0 Crashed:
0                                 	0x000000011ed27000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffee0467b70
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x000000011ed27000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0

Binary Images:
       0x10f798000 -        0x10fc99fff + (0) <BF4B3F77-F534-3819-AC30-2C3B65DF94F7> 
       0x11ed26000 -        0x11ed9070f + (655.1.1) <C192CA31-D059-3770-9882-D864FEFA0C96> 

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 34013084
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=6652K resident=0K(0%) swapped_out_or_unallocated=6652K(100%)
Writable regions: Total=8696K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8696K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
__DATA                             684K        4 
__LINKEDIT                        1096K        2 
__TEXT                            5556K        2 
shared memory                        8K        2 
===========                     =======  ======= 
TOTAL                             71.2M       12 

Model: MacBookPro13,3, BootROM 265.0.0.0.0, 4 processors, Intel Core i7, 2.9 GHz, 16 GB, SMC 2.38f7
Graphics: kHW_IntelHDGraphics530Item, Intel HD Graphics 530, spdisplays_builtin
Graphics: kHW_AMDRadeonPro460Item, AMD Radeon Pro 460, spdisplays_pcie_device, 4 GB
Memory Module: BANK 0/DIMM0, 8 GB, LPDDR3, 2133 MHz, 0x802C, 0x4D5435324C31473332443450472D30393320
Memory Module: BANK 1/DIMM0, 8 GB, LPDDR3, 2133 MHz, 0x802C, 0x4D5435324C31473332443450472D30393320
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x15A), Broadcom BCM43xx 1.0 (7.77.61.3 AirPortDriverBrcmNIC-1305.9)
Bluetooth: Version 6.0.14d6, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.0 Bus
USB Device: USB2.0 Hub
USB Device: USB 2.0 Hub
USB Device: USB 2.0 BILLBOARD
USB Device: Mass Storage Device
USB Device: Officejet Pro 8100
USB Device: Miscellaneous Device
USB Device: iBridge
USB Device: USB3.0 Hub
USB Device: Portable SSD T5
Thunderbolt Bus: MacBook Pro, Apple Inc., 41.1
Thunderbolt Bus: MacBook Pro, Apple Inc., 41.1

**Comment by AlexanderLyNL** [comment]
Hi Jan, 

Apple changed their software restriction policies. Could you please give the following notarised version of jasp a try? It's a developmental build that still needs finalising, and we would appreciate it if you could tell us whether this works out for you:

https://static.jasp-stats.org/JASP-0.12_notarized.dmg

Cheers,
Alexander

**Comment by janderuiter** [comment]
Hi Alexander!

Yes, this version worked! Thanks!

Best, JP

**Comment by janderuiter** [comment]
What's new in v0.12?

**Comment by AlexanderLyNL** [comment]
Everything, but this is not necessary 0.12 yet, because it's a development build.

**Comment by janderuiter** [comment]
OK! I'll be using this one for now then if you don't mind. When is the
official one coming out?
