### ISSUE TITLE
Significance for path coefficients in mediation analysis

### ISSUE THREAD

**Issue by Saguaroman** [jasp-stats/jasp-issues#664]
* Enhancement: Consider including confidence intervals / significance levels for X-M and M-Y paths in mediation analysis (the component paths of the indirect effect).

At least as far as I can tell, this is not provided in the current version.   Thank you.

**Comment by vankesteren** [comment]
Also mentioned [here](https://forum.cogsci.nl/discussion/6895/mediation-analysis?).

**Comment by tomtomme** [comment]
I just checked this in JASP 0.18.2 SEM Mediation analysis module. 
Every path now has CIs and p's. 
And we also have the PROCESS module now!
