### ISSUE TITLE
I can not run JASP on my MacBook with MacOS#10.15.4. It says that your software must be updated.

### ISSUE THREAD

**Issue by Mohammad-Agahi** [jasp-stats/jasp-issues#665]
* JASP version:

* OS name and version:
* Analysis: 
* Bug description:
* Expected behaviour:

**Comment by AlexanderLyNL** [comment]
Hi Mohammad-Agahi, 

Apple changed their software restriction policies. Could you please give the following notarised version of jasp a try? It's a developmental build that still needs finalising, and we would appreciate it if you could tell us whether this works out for you:

https://static.jasp-stats.org/JASP-0.12_notarized.dmg

Cheers,
Alexander

**Comment by Mohammad-Agahi** [comment]
Dear Alexander

I would like to be thankful to you.
This version that you sent is working now. 
I just have a question, this version has all the abilities of the normal version ?

Best Regards
Mohammad

**Comment by JorisGoosen** [comment]
@Mohammad-Agahi it is almost the same as the new version 0.12 we have just released. To be sure you can install that from [our website](https://jasp-stats.org)
