### ISSUE TITLE
Service unavailable (install Jasp on Linux Mint by flathub)

### ISSUE THREAD

**Issue by Calacio** [jasp-stats/jasp-issues#666]
* JASP version: last one - trying download an install by flathub
* OS name and version: Linux Mint Tricia
* Analysis: error during install
* Bug description: 
Hi! I am from Brazil, and I am so sorry for my poor english!
I was trying install Jasp on my Linux Mint Tricia by command line and by repository flathub, but there was a error message:

vinicius@ThinkPad-T61 ~ $ flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

vinicius@ThinkPad-T61 ~ $ flatpak install flathub org.jaspstats.JASP
Instalando em system:
org.jaspstats.JASP/x86_64/stable flathub 0fa4e309df0e
  permissões: ipc, network, wayland, x11, dri
  acesso a arquivo: home, xdg-config/kdeglobals:ro, xdg-run/dconf, ~/.config/dconf:ro
  acesso a dbus: com.canonical.AppMenu.Registrar
Isto está bom [y/n]: y
Instalando: org.jaspstats.JASP/x86_64/stable de flathub
[####################] Baixando arquivos: 723/10513 12,9 MB (102,2 kB/s)     
**erro: Falha ao instalar org.jaspstats.JASP/x86_64/stable: Enquanto executava pull de app/org.jaspstats.JASP/x86_64/stable a partir do remoto flathub: Server returned status 503: Service Unavailable**

* Expected behaviour: normal install and running

#### Steps to reproduce:
1. Go to Jasp page
2. Click on Donwload
3. Scroll down to OS chose and click install

**erro: Falha ao instalar org.jaspstats.JASP/x86_64/stable: Enquanto executava pull de app/org.jaspstats.JASP/x86_64/stable a partir do remoto flathub: **Server returned status 503: Service Unavailable****

**Comment by JorisGoosen** [comment]
Hi,

It seems the flathub servers sometimes have trouble processing all requests.

This can sometimes be resolved by simply trying it again. Could you try that?

**Comment by Calacio** [comment]
Hi! Yes! First time I thought it could be something like this! So I have tried several times in different days, but the error continues since a month ago... I think there is some broken or missing link for donwload Linux installation version!
For Win is everything ok, but I am not win users, I am Linux user instead!

Enviado do Yahoo Mail no Android 
 
  <div>Em sáb, 11 11e abr 11e 2020 às 10:16, Joris Goosen</div><div><notifications@github.com> escreveu:</div>   


Hi,

It seems the flathub servers sometimes have trouble processing all requests.

This can sometimes be resolved by simply trying it again. Could you try that?

**Comment by JorisGoosen** [comment]
Sorry to hear it has been giving you trouble, if however I try it right now (I like linux as well) it uhm, just works... 

So despite the fact that you have tried it before I would suggest trying it again. I do hope that they manage to get it working more stably in the future.

**Comment by Calacio** [comment]
Hi, Joris, 

I saw the last release was april 9, and that is great! But I yet have trouble installing it:

vinicius@ThinkPad-T61 ~ $ flatpak install flathub org.jaspstats.JASP
Instalando em system:
org.jaspstats.JASP/x86_64/stable flathub af9a419bb68c
 permissões: ipc, network, wayland, x11, dri
 acesso a arquivo: home, xdg-config/kdeglobals:ro, xdg-run/dconf, ~/.config/dconf:ro
 acesso a dbus: com.canonical.AppMenu.Registrar
Isto está bom [y/n]: y
Instalando: org.jaspstats.JASP/x86_64/stable de flathub
[####################] 1 metadata, 0 content objects fetched; 592 B transferred 
erro: Falha ao instalar org.jaspstats.JASP/x86_64/stable: Message recipient disconnected from message bus without replying
vinicius@ThinkPad-T61 ~ $

Do you think it is something with computer? It was working well with version 0.8.5 ...

If you coud help me, thank you very much!

VFC     Em terça-feira, 14 de abril de 2020 06:25:27 GMT-3, Joris Goosen <notifications@github.com> escreveu:  
 
 


Sorry to hear it has been giving you trouble, if however I try it right now (I like linux as well) it uhm, just works...

So despite the fact that you have tried it before I would suggest trying it again. I do hope that they manage to get it working more stably in the future.

**Comment by JorisGoosen** [comment]
```
vinicius@ThinkPad-T61 ~ $ flatpak install flathub org.jaspstats.JASP
Instalando em system:
org.jaspstats.JASP/x86_64/stable flathub af9a419bb68c
 permissões: ipc, network, wayland, x11, dri
 acesso a arquivo: home, xdg-config/kdeglobals:ro, xdg-run/dconf, ~/.config/dconf:ro
 acesso a dbus: com.canonical.AppMenu.Registrar
Isto está bom [y/n]: y
Instalando: org.jaspstats.JASP/x86_64/stable de flathub
[####################] 1 metadata, 0 content objects fetched; 592 B transferred 
erro: Falha ao instalar org.jaspstats.JASP/x86_64/stable: Message recipient disconnected from message bus without replying
vinicius@ThinkPad-T61 ~ $
```

**Comment by JorisGoosen** [comment]
This is a weird error indeed.

To verify that it isn't your OS that is messed up: maybe you could try a live-usb of Mint and check if you can install JASP there?

Ooh but first, which flatpak do you use?
```
# just run this in your terminal:
flatpak --version
```

**Comment by JorisGoosen** [comment]
Because Ubuntu and Mint have a habit of using a quite old version of flatpak and you might want to add this ppa: https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak
