### ISSUE TITLE
JASP  issue in Windows and Macos 

### ISSUE THREAD

**Issue by sultan-455** [jasp-stats/jasp-issues#668]
* JASP version:

* OS name and version:
* Analysis: 
* Bug description:
* Expected behaviour:

**Comment by sultan-455** [comment]
Hi, I am using JASP in Windows and macOS and both of them I have issues with them, I have a Midterm Exam after a few hours and I don't know what I am gonna do. when I choose exploratory factor analysis I can't insert the variables.
<img width="1360" alt="Screen Shot 2020-04-12 at 3 59 45 AM" src="https://user-images.githubusercontent.com/63523669/79057385-21003880-7c72-11ea-8614-0cfd0e47c574.png">

**Comment by EJWagenmakers** [comment]
Hi sultan-455,
You can see from the icon next to the input field that JASP expects a continuous variable here, and the one you are trying to use has been classified as ordinal (as indicated by the small histogram icon next to the variable name). To make it work, go back to the data spreadsheet view, select the measurement-level icon next to the variable, and change it to continuous (the little ruler). Once that is done you should then be able to use that variable for your analysis.
Cheers,
EJ
