### ISSUE TITLE
Resizing Window before pressing "OK"

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-issues#67]
Currently, the output window can only be resized (i.e., selecting the vertical separator and moving it left and right) *after* clicking "OK". Sometimes you already want to resize the window before pressing OK. Maybe there is a good reason for this (e.g., not wanting to have the resizing interfere with the input GUI). Hmm that's probably it, right?
E.J.

**Comment by akashrajkn** [comment]
Fixed in the upcoming version (v0.9.3)
