### ISSUE TITLE
CFA/SEM - Measurement model

### ISSUE THREAD

**Issue by Marian-Popa** [jasp-stats/jasp-issues#671]
Measurement model results in CFA and SEM (Structural Equation Modeling) 
* Enhancement:
Adding Composite Reliability, Average Variance Extracted, Maximum Shared Variance, Average Shared Variance).
* Purpose:
Promote a correct and complete interpretation of the models. Structuring the results in Measurement Model and Structural Model would favor their interpretation and increase the quality of reporting.

**Comment by Marian-Popa** [comment]
It found that lavaan do not have functions for CR, AVE, and Validity (Discriminant & Convergent), so I have to retract this sugestion.

**Comment by vankesteren** [comment]
I super agree on the restructuring of the output for SEM, we'll do this soon!

**Comment by Marian-Popa** [comment]
I'm so glad to hear that!
You, team JASP, are doing a great job!

Marian
