### ISSUE TITLE
Adjusted p-value for multiple testing

### ISSUE THREAD

**Issue by Marian-Popa** [jasp-stats/jasp-issues#672]
Adding adjusted p-values for multiple testing 
* Enhancement:
Option for computing adjusted p-values (or both, adjusted & unadjusted) in Correlation module.

**Comment by tomtomme** [comment]
Lets discuss the topic "adjusting p-values" (for various  measures like contrasts, regression etc.) here https://github.com/jasp-stats/jasp-issues/issues/637
