### ISSUE TITLE
JASP Engine Crashing IMMEDIATELY after clicking logistic regression

### ISSUE THREAD

**Issue by shiveshkabra** [jasp-stats/jasp-issues#674]
* JASP version: 0.11.1

* OS name and version: macOS Catalina 10.15.4 
* Analysis: Logistic Regression
* Bug description: Immediate JASPEngine crash notification after pressing "logistic regression" before even selecting the options
* Expected behaviour: Should not crash

#### Steps to reproduce:
1. Open data
2. Click on 'Regression'
3. From drop down, select "logistic regression"

**Comment by boutinb** [comment]
@shiveshkabra We have just release a 0.12 version. Could you try it?
