### ISSUE TITLE
Adding PROCESS by Hayes to JASP

### ISSUE THREAD

**Issue by cbflynn1970** [jasp-stats/jasp-issues#675]
* Enhancement: Andrew Hayes has published that he will be porting his moderation-mediation package PROCESS to R sometime in April 2020. I know that JASP uses a lot of R sub-processes. Any consideration for porting PROCESS for R into the JASP environment? 

* Purpose: Provide a robust way to run various models of moderation and mediation
**Is your feature request related to a problem? Please describe.**
The current mediation is great, but has limits on the number of mediators one can use, and the variety of models one can use. 

**Describe the solution you'd like**
Porting PROCESS would provide a more robust mediation/moderation solution

**Describe alternatives you've considered**
I use PROCESS in SPSS now, but would like to get out of the proprietary environment and be able to do everything in JASP.

**Comment by boutinb** [comment]
@vandenman: do you know this package?

**Comment by EJWagenmakers** [comment]
This is something to discuss with @vankesteren

**Comment by vankesteren** [comment]
Thank you for your suggestion, we'll keep an eye on this! 

Just FYI, we're generally not fans of the obscure `model 17`, `model 4` etc. user interface of `PROCESS`. Which type of model do you want to run? We might be able to provide a nice user interface for that model, specifically.

Also, I was wondering what you mean by "has limits on the number of mediators one can use"? How many mediators do you want to use? See below a JASP mediation model with 16 mediators, that seems like a lot to me already?

![image](https://user-images.githubusercontent.com/11596858/79352724-80906980-7f3a-11ea-8140-acac9c7ad0c0.png)

**Comment by cbflynn1970** [comment]
I get the dislike of the models; I don’t particularly care for them myself, however, PROCESS does provide a variety of moderated-mediated models that are useful. Having the ability to run models with moderators before and after the mediator would be nice, but primarily before the mediation variable. I guess you can create moderated variables in the data set and just run those, but it would be nice if you could just specify multiple moderators in the model and where they fall in the paths. I think just having the ability to do multiple moderators with the current capabilities of the mediation would probably be sufficient.

In terms of PROCESS this would be similar to models 1-3, 5, 7, 8, 9, 14, 21, etc.

Yes, 16 mediators is a lot; I’ll never run that many. So I guess what I would really like is an easy way to add moderation to the mediation model.

And while I’m asking, what’s the possibility of adding an HLM module and a visual model builder to the SEM module (a la AMOS; I shy away from writing code, even in Llavaan)?

Just a compliment to all of you, I really like JASP - It’s my go-to software for stats and I really appreciate that it is available freely. I prefer to do most of my work on my Mac but getting a good stats package for Mac was hard. I tried R but it’s a little over my head and interest. I just want a package where I can input my data and run it and JASP has been great. I use it with my students for class projects as well. So kudos to all of you for the great work.

Dr. Brian Flynn
Assistant Professor of Management
Coggin College of Business
University of North Florida
904-620-1118
brian.flynn@unf.edu<mailto:brian.flynn@unf.edu>

On Apr 15, 2020, at 11:04 AM, Erik-Jan van Kesteren <notifications@github.com<mailto:notifications@github.com>> wrote:



Thank you for your suggestion, we'll keep an eye on this!

Just FYI, we're generally not fans of the obscure model 17, model 4 etc. user interface of PROCESS. Which type of model do you want to run? We might be able to provide a nice user interface for that model, specifically.

Also, I was wondering what you mean by "has limits on the number of mediators one can use"? How many mediators do you want to use? See below a JASP mediation model with 16 mediators, that seems like a lot to me already?

[image]<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F11596858%2F79352724-80906980-7f3a-11ea-8140-acac9c7ad0c0.png&data=02%7C01%7Cbrian.flynn%40unf.edu%7C397881495c4340c657d808d7e14e3bcf%7Cdf29b2fa8929482f9dbb60ff4df224c4%7C1%7C0%7C637225598441990028&sdata=aSO91ODpoKs5Qs%2FaWqsVSbnQY%2F9Tc9jpFpGknSgOA80%3D&reserved=0>

**Comment by lwnn25** [comment]
Dear all,

I find that JASP can use PROCESS code in R console directly.

First, download the PROCESS R file on https://haskayne.ucalgary.ca/CCRAM/resource-hub.

Second, copy all the codes in the PROCESS R file and paste into R console in JASP. Run the code and wait for the information - "PROCESS is now ready for use."

Third, write the code for mediation or moderation analysis and run it.

Here is an example for mediation analysis:

process(data = data, y = "maths", x = "age", m ="intelligence", model = 4)

Just replace names of y, x, m and the model with your data and analysis. 
 
Enjoy it.

**Comment by EJWagenmakers** [comment]
Thanks! The upcoming version of JASP will have a PROCESS model with
 extensive functionality and GUI!
EJ
