### ISSUE TITLE
Error in bayesian linear regression

### ISSUE THREAD

**Issue by Kev025** [jasp-stats/jasp-issues#676]
Hi, I'm conduction bayesian linear regression with new JASP version. But there is the error message
![Capture d’écran 2020-04-14 à 20 06 55](https://user-images.githubusercontent.com/62613088/79258550-985ce480-7e8b-11ea-9608-6e74d244cfc3.png)

**Comment by AlexanderLyNL** [comment]
Could you please fill out the bug report template? 

https://github.com/jasp-stats/jasp-issues/issues/new?assignees=&labels=&template=bug_report.md&title=

Because without this additional information we cannot locate the problem exactly, and fix the bug.

**Comment by Kev025** [comment]
Oh sorry, I did it : https://github.com/jasp-stats/jasp-issues/issues/677

Thanks

**Comment by vandenman** [comment]
Closed to avoid duplicates, let's discuss any updates in #677
