### ISSUE TITLE
EFA: Factor correlation

### ISSUE THREAD

**Issue by hynekcigler** [jasp-stats/jasp-issues#678]
* JASP version: 0.12

* OS name and version: Windows 10
* Analysis: Exploratory factor analysis
* Bug description: In factor correlation matrix JASP reports probably correlation of factor score estimates, not phi matrix (the model matrix of factor correlation). E.g. if no rotation is selected, there are still some non-zero values in the matrix of factor correlations.
* Expected behaviour: Model matrix should be reported.

**Comment by vankesteren** [comment]
Hi @hynekcigler, 

thanks for the suggestion, I just checked and you are completely correct! I will change the default to reporting the model matrix, and provide an option for obtaining the factor score correlations.

Erik-Jan

**Comment by hynekcigler** [comment]
Great, thank you! If you are going to make some changes in the EFA analysis, I would suggest also to provide residual correlation matrix (which is necessary to investigate model fit). But the change in factor correlation reporting is essential!

**Comment by vankesteren** [comment]
This change has just been made.
![image](https://user-images.githubusercontent.com/11596858/81149770-2144d880-8f7f-11ea-9c13-ce7ac360ba6b.png)

Would you say the residual correlation matrix belongs under "assumption checks" as FA assumes uncorrelated observed variables conditional on the factors?

**Comment by hynekcigler** [comment]
This looks great! :) Yes, this is one option; another is to include it directly in Tables. Both make sense.

**Comment by vankesteren** [comment]
![image](https://user-images.githubusercontent.com/11596858/81153172-f2306600-8f82-11ea-85d0-c4ec22c663c9.png)

alright, added it to the tables. Expect this in one of the next versions of JASP!

**Comment by hynekcigler** [comment]
Awesome! :)

**Comment by juliuspf** [comment]
As this is part of EFA now, I will close it. @hynekcigler feel free to reopen if any issues remain.
