### ISSUE TITLE
Very slow estimation of correlation matrix

### ISSUE THREAD

**Issue by hynekcigler** [jasp-stats/jasp-issues#679]
* JASP version: 0.12
* OS name and version: Windows 10
* Analysis: Correlation (Regression -> Classical -> Correlation
* Bug description: Very slow estimation of correlation matrix

I have [not-so-big dataset](https://is.muni.cz/www/hynek.cigler/vaha4.csv) (N=1000). If I run a correlations over all the 28 items (vah.a1-vah.b28), the estimation is extremely slow and the analysis fails soon. It is slow even if I run it over just e.g. three or four variables. If the dataset is loaded, these variables are set as ordinal. I tried to set them as continous, but the estimation is slow too. On the other hand, running e.g. factor analysis (which needs also an estimation of covariance matrix) is quick, so the problem is only in the correlation matrix. I tried Pearson and Spearman correlations, both are similarly slow.

**Comment by AlexanderLyNL** [comment]
It is indeed quite slow. I did the computations for you on my own JASP development build:

[vaha4.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/4484213/vaha4.jasp.zip)

Let me know if you can open it. I also added the Bayesian equivalent to the file for your convenience. Those computations are done relatively quickly it seems. 

This is definitely not ideal, and it seems that some (permutation based?) computations are done. @Kucharssim is that correct? If so, can we not do that by default?

**Comment by hynekcigler** [comment]
Thank you. Actually, I don't need these computations on my own as I use R usually, but my students are given this dataset for their assignment to perform exploratory factor analysis (and I would like them to report correlation matrix). 
Anyway, the estimation is slow even if I did not ask for signifficance, where any permutation test is not needed (and even the permutation test performed directly in R takes just a few seconds).

**Comment by Kucharssim** [comment]
Yes, this is likely caused by calculating CIs for Kendall’s tau which is by mistake now computed even if it’s not requested. I’ll fix this.
