### ISSUE TITLE
Enhancement: add intervals to correlation matrix

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-issues#68]
A useful suggestion from the JASP twitter account: adding "bands" around the best-fitting line in the correlation matrix plot (maybe upon demand).

![adilsaribaysuggestion](https://user-images.githubusercontent.com/8603015/27656994-70c3310a-5c4b-11e7-9442-9140f86670f4.jpg)

**Comment by Kucharssim** [comment]
We will have this in linear regression, @maltelueken is just working on this: https://github.com/jasp-stats/jasp-issues/issues/879.
