### ISSUE TITLE
Jasp won't open

### ISSUE THREAD

**Issue by lilymouth** [jasp-stats/jasp-issues#681]
* JASP version: 0.12.0.0

* OS name and version: Windows 10 x64
* Bug description: JASP does not open
* Expected behaviour:

I have already removed it and downloaded it a few times, but it will not open when I click on it.

Thanks in advance!
lilymounth

**Comment by JorisGoosen** [comment]
Hello Lily,

Sorry to hear that, but to figure out what is going wrong you can help us out by downloading [dependency walker](http://www.dependencywalker.com/depends22_x64.zip).
You don't need to install it, just unpack it somewhere. Then you start it and use it to open `JASP.exe` (probably in `C:\program files\JASP`).

And then save the resulting data as a "*.dwi" and attach that here?

**Comment by bont007** [comment]
Hello,

same problem here with Jasp 0.12.2, both 32 and 64bit on Win10, both pre-installed and msi versions. dwi file attached. Jasp 0.11. works fine. Thanks.

Thomas

[Jasp12dwi.zip](https://github.com/jasp-stats/jasp-issues/files/4594254/Jasp12dwi.zip)

**Comment by JorisGoosen** [comment]
Thank you for uploading the dwi, Ill have look soon!

**Comment by bont007** [comment]
Added: 0.12.2 works fine on a different machine of mine with the same setting. So is the problem caused by inadvertedly deleting dll's during routine cleanup?

**Comment by JorisGoosen** [comment]
@bont007 it could be that but it could also be that you installed some other piece of software on the second system. And that also installed some dependency that we are missing but need.
I didn't have the time yet to look at your log but will do so before the next release. 

The fact the older version of JASP works is a bit suspicious though.

Maybe you could also upload a `dwi` from the system where JASP 0.12.2 *does* work?

**Comment by JorisGoosen** [comment]
@bont007 do you think it would be possible for you to upload the `dwi` from the system where it works?

And what do you meanup with "inadvertedly deleting dll's during routine cleanup"?
Does that mean you just randomly delete dll's from your system?

**Comment by bont007** [comment]
Thanks. I did send you the DWI, surely may upload it again. "Inadvertedly" means that I may have removed necessary files by 1. deleting the former Jasp installation, and 2. letting Glary Utilities clean up registry, temporary files and whatever junk might have remained. No manual interference in system though. Is Jasp to be rather installed on a former version?--Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 22.05.20, 17:37 schrieb Joris Goosen <notifications@github.com>:

   
  @bont007 do you think it would be possible for you to upload the dwi from the system where it works? 
  And what do you meanup with "inadvertedly deleting dll's during routine cleanup"? Does that mean you just randomly delete dll's from your system?

**Comment by JorisGoosen** [comment]
Aah well, I only see a single zip file here at the issue with `dwi` from your system, it seems both 32bit and 64bit versions. But I thought that was from the system where it did **not* work?

So if you could also attach one from your system where it **does** work then that would give me a good comparison, although I guess I could also just look at a log I generate here myself.

If you mean by "1. deleting the former jasp installation" that you manually removed the files then that could cause a problem, but if that was just removing it through the "Programs & Features" settings menu of Windows that should be fine.

**Comment by JorisGoosen** [comment]
Hmm, it seems all of the dlls load fine on your system. I see no problems there.

So it seems it *could* start, but as the window is not opening something else seems to be going wrong.

Maybe @bont007 could help us by sending us the logfiles of an attempt to start JASP?

If you could manually start JASP from a command prompt as follows: `c:\users\thoma\desktop\jasp-0.12.2-win64\JASP.EXE --logToFile`. It might still not start but hopefully it will write some sensible logfiles that will help.

These logfiles are probably at `C:\Users\thoma\AppData\Roaming\JASP\JASP\Logs` and then there should be at least one called "JASP 2020-05-?? ??_??_?? Desktop.log" and 4 others with the same name except that "Destop" -> "Engine #" 

It would be very informative to get those logs.

**Comment by JorisGoosen** [comment]
Without more information from either of the two users with this specific problem @bont007 or @lilymouth I really cannot do anything.
