### ISSUE TITLE
0.12.1 crashes OSX

### ISSUE THREAD

**Issue by mpeters2** [jasp-stats/jasp-issues#683]
OSX 10.15.3
2019 iMac

1) Crashes when I try to perform a simple repeated-measures ANOVA.  Previous version (0.11.1) was able to perform these just fine with the same data set (csv file)

2) When I go to quit Jasp, it crashes.

**Error Message**
`This analysis terminated unexpectedly.

Error in ref_grid(object, ...): Can't handle an object of class  “NULL” <br> Use help('models', package = 'emmeans') for information on supported models.

Stack trace<
tryCatchOne(expr, names, parentenv, handlers[[1]])
doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.referenceGrid(rmAnovaContainer, options, ready)

emmeans::emmeans(fullModel, formula)

ref_grid(object, ...)

stop(data)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports"
`

**Comment by boutinb** [comment]
Can you send us your csv file (in a zip format), and the exact steps you do in JASP?

**Comment by mpeters2** [comment]
Attached is a simplified version of the csv file, but it also produces an error.  I tested other modules, and they all seem to work as expected. I’m only getting a crash with the Repeated Measures ANOVA.



1) “Paired Samples T-Test” works
“Bayesian Repeated Measures ANOVA” works
“Descriptives” works (see second screen shot)

2) Steps to create a crash

2.1) Import csv file
2.2) Select “ANOVA->Repeated Measures ANOVA”
2.3) Create a Repeated Measures Factor with 2 levels (I first found this crash after upgrading and trying to run a 3-way RM ANOVA).
2.4) Assign variables to Repeated Measures Cells

Result: Crash

Some screen shots:

[cid:0031e5ef-4f77-493d-98d1-6713f626d5bf@namprd05.prod.outlook.com]
[cid:0ff9351f-395b-4ac2-9e17-4405316ee442@namprd05.prod.outlook.com]

**Comment by boutinb** [comment]
I am afraid you did a reply from your email client, and the attached files do not come through. Could you use GitHub to send the files?

**Comment by mpeters2** [comment]
Here is a .zip of the .csv:
[test.csv.zip](https://github.com/jasp-stats/jasp-issues/files/4494813/test.csv.zip)

**Comment by mpeters2** [comment]
Screen shots:
<img width="347" alt="Screen Shot 2020-04-17 at 9 55 35 AM" src="https://user-images.githubusercontent.com/26334076/79605928-c7a76780-80be-11ea-8cad-cd1c2fee6f2d.png">
<img width="1190" alt="Screen Shot 2020-04-17 at 9 55 27 AM" src="https://user-images.githubusercontent.com/26334076/79605929-c7a76780-80be-11ea-8fdb-0586eb924c9c.png">

**Comment by boutinb** [comment]
@JohnnyDoorn Can you have a look?

**Comment by JohnnyDoorn** [comment]
I can replicate this in JASP, but not on jaspTools. I think there is an issue when columns or factor levels are named either "b", "c", or "e". @JorisGoosen or @vandenman have you encountered anything related to this, or do you know if JASP does something with those names internally (maybe because they have a special status)?

**Comment by JohnnyDoorn** [comment]
@mpeters2 maybe in the meantime you can try to run the analysis with other column names in your data and different factor level names? I think that would solve your issue in the meantime, while, we look into the underlying cause.  For me it works when I use "aa" and "bb", for instance.
Or does the analysis also crash for you with other names?

**Comment by JorisGoosen** [comment]
> @JorisGoosen or @vandenman have you encountered anything related to this, or do you know if JASP does something with those names internally (maybe because they have a special status)?

As far as I know those names aren't special. They used to be encoded to base64 right? Did you keep that? Because the automatic encoding that took factors into account is still not turned on, so that can't be it.

**Comment by mpeters2** [comment]
"a","b", and "c" were not the original columns names. 

 In the original, much larger file that first demonstrated the crash, the column names were: "0above-ss6", "25above-ss6", "50above-ss6", etc.

Factor names were:
"Set Size" (with "ss6" and "ss12" as levels)
"target above/below" (with "above" and "below" as levels)
"opacity" (with "0", "25", "50", and "100" as levels)

One thing I did notice is that in 0.12.1, the variables disappear from the left-hand column when I add them to the analysis.  I don't know if that is a clue, but you can see it when comparing the screen shots below.

This first screenshot is a successful run with JASP 0.11.1:

![image](https://user-images.githubusercontent.com/26334076/79769051-a1b9d700-82f9-11ea-9a1e-84b2873f6ab6.png)




This screenshot is from JASP 0.12.1:

![image](https://user-images.githubusercontent.com/26334076/79769115-b9915b00-82f9-11ea-8581-a6ba039e531f.png)

**Comment by JorisGoosen** [comment]
Well, it seems we have figured out what the problem is. I will build a testversion so you can confirm that.

**Comment by boutinb** [comment]
In 0.11.1, the variables disappear also on my mac... But I suppose it is the right thing, @JohnnyDoorn ?

**Comment by AlexanderLyNL** [comment]
The variables should move from left to right. In RM ANOVA: Once a variable is chosen for a repeated measures cell it should not be put in another cell, in the other input fields.

**Comment by JorisGoosen** [comment]
@mpeters2 could you test this version of JASP with your original dataset: http://static.jasp-stats.org/Nightlies/MacOS/JASP-nightly-stable-cd88f8ccbdfbf5f4e00b95ed088392f0a8424ade.dmg

**Comment by mpeters2** [comment]
It works!

**Comment by JorisGoosen** [comment]
A new official release of JASP with this fix will probably come out later this week. But in any case soon, until then you can keep using this one if you like.

**Comment by etidoni** [comment]
After the new release I still have Jasp crashing when when I go to quit after a RManova.

mac OS catalina 10.15.4, JASP 0.12.2

**Comment by boutinb** [comment]
This issue was found and is already fixed for the next release.
