### ISSUE TITLE
Adding the stem-and-leaf and dot plots in JASP

### ISSUE THREAD

**Issue by chantelanuit** [jasp-stats/jasp-issues#684]
Hello Jasp Jeam,

In his book "The Grammar of Graphics", Wilkinson (2005, p. 137) suggests that: 

> Statistics texts and statistical packages that recommend the histogram as the graphical starting point for a data analysis are giving bad advice. The same goes for kernel density estimates. These are appropriate second stages for graphical data analysis. **The best starting point for getting a sense of the distribution of a variable is a tally, stem-and-leaf, or a dot plot**. A dot plot is a special case of a tally (perhaps best thought of as a delta-neighborhood tally). Once we see that the data are not granular, we may move on to a histogram or kernel density, which smooths the data more than a dot plot.

It would therefore be nice if the JASP team could add both the stem-and-leaf and dot plots in a future revision of the program. Here are examples of dot plots: https://www.tutorialgateway.org/r-ggplot2-dot-plot/

Michael

**Comment by FransMeerhoff** [comment]
Hi @vandenman @vankesteren : Do you think it's not too hard and useful? Or ask other people to have a look also?

**Comment by vandenman** [comment]
Two questions:

1. Isn't a stem-and-leaf plot is basically a table, not a plot? I think that if we make it into an actual plot (like they do [here](https://stackoverflow.com/a/26533522/4917834)) then the values cannot be copied anymore.

2. A dot plot is just a histogram with dots rather than bars?

**Comment by chantelanuit** [comment]
> 1. Isn't a stem-and-leaf plot is basically a table, not a plot? I think that if we make it into an actual plot (like they do [here](https://stackoverflow.com/a/26533522/4917834)) then the values cannot be copied anymore.

**If you create it like a table, it is fine. It is useful to be able to copy the values.**

> 2. A dot plot is just a histogram with dots rather than bars?

**No, it's not. On a dot plot, you see all individual scores, therefore you can see granularity in data that the histogram would have hidden. For this reason, Wilkinson (1999) suggests that a dotplot is one of the first graphs to use, before the creation a histogram. Please see the following article:

https://www.cs.uic.edu/~wilkinson/Publications/dotplots.pdf**

**Comment by TimKDJ** [comment]
The stem and leaf tables will be in JASP 0.15.
I don't think there are immediate plans for the dot plots.

**Comment by vandenman** [comment]
A dot plot implementation is here: https://github.com/jasp-stats/jasp-desktop/pull/4348. It still needs some work but it'll probably also make 0.15.

**Comment by chantelanuit** [comment]
Nice addition. Thank you for the follow-up !

**Comment by vandenman** [comment]
Both have been added to JASP so I'm closing this issue (stem-and-leaf: https://github.com/jasp-stats/jaspDescriptives/pull/2, dot plots: https://github.com/jasp-stats/jaspDescriptives/pull/5). These will be available in the next jasp release (0.15)
