### ISSUE TITLE
JASP crashes directly when I try to open it

### ISSUE THREAD

**Issue by UniM79** [jasp-stats/jasp-issues#686]
* JASP version: 0.12.1.0
* OS name and version: Mac OS 10.13.6 High Sierra
* Analysis: 
* Bug description: I downloaded JASP following the installation instructions. There were no problems while doing that. But when I now click on the icon of JASP to start the program it first seems that it is opening, but after a few seconds the icon in the dock disappears and JASP just crashes. I don't get any error description. I already deleted and downloaded the program again.
* Expected behaviour:

**Comment by boutinb** [comment]
Hi @UniM79 
Could you open a terminal, and type the following

- cd /Applications/JASP.app/Contents/MacOS
- ./JASP

You will get many messages in terminal. Could you send me these messages?

Bruno

**Comment by boutinb** [comment]
@UniM79 Could you manage to start JASP in the way I mentioned? I would like really much to know what it's going wrong on your Mac.

**Comment by UniM79** [comment]
Yes! Thanks a lot. Now it is working.

**Comment by boutinb** [comment]
@UniM79 But does it work now also if you start JASP by double-clicking its icon?
