### ISSUE TITLE
This analysis terminated unexpectedly. 

### ISSUE THREAD

**Issue by modelistatistik** [jasp-stats/jasp-issues#689]
* JASP version:JASP 0.12.1

* OS name and version: Windows 10 Turkish
* Analysis: **Flexplot**
* Bug description: **Turkish Characters**
* Expected behaviour: implementation of analysis

#### Steps to reproduce:

Hi all, 

Thanks for flexplot module. But Turkish characters not working now. 
Do you check this problem? 

Thanks for interest. 
Gokhan
![123](https://user-images.githubusercontent.com/52344191/79880413-a74a1680-83f8-11ea-96e1-453a49907d7a.jpg)

**Comment by modelistatistik** [comment]
Other problem. 
Picture 1: https://prnt.sc/s3dxdz
Picture 2: https://prnt.sc/s3dxnn

I am exporting this figure, but eps formatting is problem. 
Do you check this situation? 

Thanks for interest. 
Gokhan

**Comment by boutinb** [comment]
@dustinfife Can you have a look to this issue?

**Comment by dustinfife** [comment]
Hi @boutinb 

I may need some guidance on this one. It seems like it doesn't like the special characters. How does JASP usually handle this?

As for the missing labels in illustrator, I'm not sure if that's a flexplot problem. Do you know bruno?

**Comment by boutinb** [comment]
Maybe @vandenman can say more about it (Tim is unfortunately ill)

**Comment by dustinfife** [comment]
The issue was the spacing in the variable names. Visual modeling wasn't properly encoding the names of the variables. That is fixed in [this commit](https://github.com/dustinfife/flexplot/commit/ec34711a8b24740e45441317ff0b508747c2441e) in flexplot

**Comment by modelistatistik** [comment]
Thanks for solving. 

 

Best regards,

 



Bu mesaj ve ekleri mesajda gönderildiği belirtilen kişi/kişilere özeldir ve
gizlidir. Bu mesajın muhatabı olmamanıza rağmen tarafınıza ulaşmış olması
halinde mesaj içeriğinin gizliliği ve bu gizlilik yükümlülüğüne uyulması
zorunluluğu tarafınız için de söz konusudur. Mesaj ve eklerinde yer alan
bilgilerin doğruluğu ve güncelliği konusunda gönderenin ya da şirketimizin
herhangi bir sorumluluğu bulunmamaktadir. Şirketimiz mesajın ve bilgilerinin
size değişikliğe uğrayarak veya geç ulaşmasından, bütünlüğünün ve
gizliliğinin korunamamasından, virüs içermesinden ve bilgisayar sisteminize
verebileceği herhangi bir zarardan sorumlu tutulamaz. 

This message and attachments are confidential and intended solely for the
individual(s) stated in this message. If you received this message although
you are not the addressee you are responsible to keep the message
confidential. The sender has no responsibility for the accuracy or
correctness of the information in the message and its attachments. Our
company shall have no liability for any changes or late receiving, loss of
integrity and confidentiality, viruses and any damages caused in anyway to
your computer system.

**Comment by juliuspf** [comment]
Seems like this can be closed. @modelistatistik feel free to reopen if your issue remains.
