### ISSUE TITLE
Feature Request: linear mixed effects models

### ISSUE THREAD

**Issue by freestone-lab** [jasp-stats/jasp-issues#69]
I'd love to see linear mixed effects models in JAPS. The standard R packages are lmer, glmer, and bayesian implementations include stan_lmer and stan_glmer (and probably others).

**Comment by JorisGoosen** [comment]
@FBartos were you working on this?

**Comment by FBartos** [comment]
Yes, it should be out soon (not the 0.12 though).

**Comment by JorisGoosen** [comment]
Good, then this is now your issue ;)

**Comment by TimKDJ** [comment]
https://github.com/jasp-stats/jasp-desktop/pull/4129

This will be included in 0.13 which is due in a couple of weeks.
