### ISSUE TITLE
Analysis terminated unexpectedly

### ISSUE THREAD

**Issue by wegmannm** [jasp-stats/jasp-issues#690]
* JASP version:0.12.1

* OS name and version:windows 10 64 bit
* Analysis: visual modeling, mixed modeling
* Bug description:analysis terminated unexpectedly
[golfRBDlong.txt](https://github.com/jasp-stats/jasp-issues/files/4516807/golfRBDlong.txt)

* Expected behaviour:

#### Steps to reproduce:
1. Go to 'visual modeling...'
2. Click on 'mixed modeling....'
3. Scroll down to '.enter distance for dependent variable...'
enter brand for fixed variable
enter golfer for random variable (changed to nominal before entering)

**Comment by vandenman** [comment]
Thanks for the bug report! Could you please also tell us the following:

1. What is the error message that appears?
2. What is the "golfer" variable? It is missing from golfRBDlong.txt

I'm able to reproduce an error, but I'd like to verify that it's the same one you have. 

The error message I get is: `Error in sample.int(length(x), size, replace, prob): cannot take a sample larger than the population when 'replace = FALSE'`

**Comment by wegmannm** [comment]
[image: image.png]
 I've included the screen shot  above showing the error.
Also, I've attached the file that I used which has golfer, brand and
distance as the 3 variables
Thanks for the quick response,
M. Wegmann

**Comment by vandenman** [comment]
If you reply to a GitHub via email your message comes through clearly, but unfortunately, any attachments and/ or images are lost. Could you use GitHub directly to add attachments?

**Comment by dustinfife** [comment]
Without seeing your dataset, I have a suspicion about what's happening (especially if @vandenman has reproduced the error). The module defaults to selecting six clusters to plot. If you have less than six clusters, it will throw an error. I recently fixed flexplot to not choose more clusters than exist, but, in the mean time, you can reduce the number of clusters to plot.

**Comment by wegmannm** [comment]
![image](https://user-images.githubusercontent.com/8289317/80108355-d15b2000-8541-11ea-88bb-cfdeaa8978db.png)

[rbdlong (1).txt](https://github.com/jasp-stats/jasp-issues/files/4522994/rbdlong.1.txt)
