### ISSUE TITLE
JASP crashed

### ISSUE THREAD

**Issue by Loraageorg** [jasp-stats/jasp-issues#692]
* JASP version: 0.12.1
* OS name and version: Windows 8.1 (6.3)

* Analysis: 
* Bug description:
* Expected behaviour:

#### Steps to reproduce:

-----------------------------------------------------------------------

### Debug information:
**Engine # 0** process *crashed* and it's state is *initializing*.
**Engine # 1** process *crashed* and it's state is *initializing*.
**Engine # 2** process *crashed* and it's state is *initializing*.
**Engine # 3** process *crashed* and it's state is *initializing*.

[Commit used](https://github.com/jasp-stats/jasp-desktop/commit/8e9f71703aeec0b2aabd15f3092fa144a91259ef)

**Comment by boutinb** [comment]
@Loraageorg We need to know what you do exactly before the crash. Do you open JASP and it crashes immediately, or do you try to load a file, or to add an analysis ?
