### ISSUE TITLE
Degrees of freedom for correlations

### ISSUE THREAD

**Issue by kadesoto** [jasp-stats/jasp-issues#7]
Any sense in having the total N or degrees of freedom in correlation plots? Also, is it worth having a way to compute simple correlations without having to do a matrix?

**Comment by tomtomme** [comment]
We are still missing n the scatterplot statistics, but n is now available in the table and we have the requested pairwise comparisons. 
So this can be closed?

**Comment by boutinb** [comment]
Yes
