### ISSUE TITLE
Plotting bug

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-issues#70]
Contingency tables: plot of posterior distribution (tightly concentrated on zero) shows zeros on the x-axis.
See attached file.

![image](https://user-images.githubusercontent.com/8603015/28423741-2d72a3f4-6d6c-11e7-869c-fb9dc2135b84.png)

Data:

Bla | Bladiebla | Count
-- | -- | --
Yes | Yes | 221536
No | Yes | 220264
Yes | No | 2203496
No | No | 2203105

E.J.

**Comment by JorisGoosen** [comment]
@akashrajkn is this done?

**Comment by akashrajkn** [comment]
As of v0.14.1, this does not occur (File attached for reference)

![lor](https://user-images.githubusercontent.com/6959308/113203492-65faf180-926c-11eb-9cdf-960db5802fb9.png)

[lor.zip](https://github.com/jasp-stats/jasp-issues/files/6239143/lor.zip)
