### ISSUE TITLE
Audit export sample as .csv?

### ISSUE THREAD

**Issue by AlexanderLyNL** [jasp-stats/jasp-issues#701]

**Comment by AlexanderLyNL** [comment]
It's already possible to export to csv. Or do you mean something else?

**Comment by koenderks** [comment]
I have these buttons and I would like to export an R (a selected sample from the population) that I provide to .csv when a user presses this button.

**Comment by AlexanderLyNL** [comment]
This was done for 0.14.1, wasn't it?

**Comment by koenderks** [comment]
Yes
