### ISSUE TITLE
Network analysis - Changing Legend does not change the Centrality Plot

### ISSUE THREAD

**Issue by andremonezi** [jasp-stats/jasp-issues#702]
*** JASP version:** 0.12.1

*** Analysis:** Network
*** Bug description:** This new version has advanced in-network graphic models, but the centrality plot is still having problems.
Note that on the centrality plot (shown in the legend), the system still displays the legend.
When the nodes only display the number (the name of the variable is displayed in the legend), the centrality plot still displays the variable name. Thus
![Probem](https://user-images.githubusercontent.com/64216719/80123730-ad113a80-8565-11ea-9170-0efdacf5e044.JPG)
, it is not possible to insert the same data in a scientific article, for example.
Please, see the images attached.

* Expected behaviour:

**Comment by vandenman** [comment]
Thanks for the bug report! The legend box only influences the network plot, not any of the other plots. However, I see that there is a real use case for having this button control all legends rather than just the one of the network plot. I'll put it on my to-do list!

**Comment by vandenman** [comment]
Okay so I've now changed it to 3 options:

Old:
![image](https://user-images.githubusercontent.com/21319932/80794760-08ad7a80-8b9b-11ea-8209-b34974109dde.png)

![image](https://user-images.githubusercontent.com/21319932/80794694-d9970900-8b9a-11ea-9303-7cbbb06e190e.png)

New option 1:
![image](https://user-images.githubusercontent.com/21319932/80794781-1531d300-8b9b-11ea-88f9-639c9c97eae3.png)

![image](https://user-images.githubusercontent.com/21319932/80794740-f7646e00-8b9a-11ea-9b94-64067c3630d2.png)

I'll see if I can tweak the spacing of the legend which now looks a bit odd.

New option 2:
![image](https://user-images.githubusercontent.com/21319932/80794839-2d095700-8b9b-11ea-9890-dc31baecbdd0.png)

![image](https://user-images.githubusercontent.com/21319932/80794842-2ed31a80-8b9b-11ea-863d-ce7cd1a31c93.png)

is this what you had in mind?

**Comment by andremonezi** [comment]
Dear Don van den Bergh, 

Thanks for your speedy response. They looked great, but I found something that might be another bug. Note that the plot ratio should be the same for all three measures of centrality. In the image, you can see that the valuables are different depending on the centrality, and this cannot be altered.

**Also, I would like to take this message and request two simple new features in network analysis.**
1) Insert the fourth measure of centrality that already exists in the R, called "expected influence."
2) Insert in the legend the possibility to view the value of the correlations.

I am requesting it because some time ago, we submitted an article to The International Journal of Psychology (see figure at the end of the manuscript), and one of the referees requested that we should insert the "expected influence" and the value of the correlations between the edges. 
Besides, our research group has worked a lot with network analysis in several types of research, and we realized that these two features in the field of psychology make theoretical sense. In Figure 1, we evaluated the prevalence of emotional disorders and its association with internet addiction among psychologists and students of psychology and we used these two features. At present, we recently submitted this manuscript.
We have been used the R to run these graphs and centrality levels. 
Hugs!!









![Centrality](https://user-images.githubusercontent.com/64216719/80802621-35a36280-8b86-11ea-8e66-ecc06cf0d8ec.JPG)
[Andrade et al.pdf](https://github.com/jasp-stats/jasp-issues/files/4563932/Andrade.et.al.pdf)
![Figure 1](https://user-images.githubusercontent.com/64216719/80802632-3d630700-8b86-11ea-957c-f1bc7a7dd0a9.png)

**Comment by vandenman** [comment]
The centrality measures are standardized, but that does not mean they necessarily have the same scales on the axes. For example, in R this gives me:
```r
set.seed(1)
u1 <- scale(rnorm(100))
u2 <- scale(rcauchy(100))
layout(t(1:2))
hist(u1)
hist(u2)
```
![image](https://user-images.githubusercontent.com/21319932/80804073-5da9ba80-8bb4-11ea-8916-0db0d571f50a.png)

both are standardized with mean 0 and standard deviation 1 yet the scale on the axes differs vastly. Granted this is an extreme example, but it shows that it can be very difficult to automatically choose the appropriate scale. In this example, the plot would be heavily skewed if we'd restrict the axes.

We hope to have editable plots in the near future which should allow you to adjust individual plot elements like axes breaks.


Considering the 'expected influence', I found two definitions in the [qgraph manual](http://sachaepskamp.com/qgraph/reference/centrality.html): 

- Expected incoming influence - the sum of incoming edge weights connected to a node.
- Expected outgoing influence - the sum of outgoing edge weights connected to a node.

This is what you are referring to? If so it should be straightforward to implement.

Considering 'Insert in the legend the possibility to view the value of the correlations.', do you mean the values inside the edges, like in the network plots in the paper? Otherwise, I'm afraid I do not understand what you're asking for.

**Comment by andremonezi** [comment]
Dear Don, 
Thanks for your attention! So, we hope in the future editable plots.

Regarding the expected influence, I was referring exactly to these two definitions! 
As regards to the value of the correlations, I mean the valuables inside the edges, like in the network plots. 

You have got these ideas.
If you implement both features, it would great!

[   ] s

**Comment by vandenman** [comment]
A screenshot of some intermediate progress:

![image](https://user-images.githubusercontent.com/21319932/81003655-7c75ae80-8e4b-11ea-8b98-4a1191a17cfd.png)

- Expected influence is now shown in the centrality plot

Inside the red box are some new options:
- The checkbox `Edge labels` draws or hides the edge strength.
- The input `Edge label size` controls the size of the drawn edge label (2 is twice as large).
- The input `Edge label position` controls where the edge label is drawn (0 is near one edge and 1 is near the other edge).

Let me know if this is what you meant or if I missed something!

**Comment by andremonezi** [comment]
Dear Don, 
Your job looks great! I have two questions:

1) Concerning the graphs, the value of the correlations will also be shown when the edges turn green or red (classic), ok?

2) Please note that there should be some feature to show the color of the edges in proportion to the value of the correlations. See that in my attached picture, we created a graph in the R, and the program highlighted only those strongest correlations, so the graph is not polluted. This is particularly important when using the LASSO method.

**Other  suggestion**
In the central plot, it would be useful if the user could choose which measurements (closeness, betweenness, expected influence, degree) will compose the plot. Thus, he can make a personalized image and ore adapted to his paper.
![Graph](https://user-images.githubusercontent.com/64216719/81058051-03ef0c00-8ea4-11ea-924f-766f6ccda3e7.JPG)

**Comment by vandenman** [comment]
1. If you change the `Edge palette` the figure will change accordingly. Here an example with `Edge palette` "Classic": 
![image](https://user-images.githubusercontent.com/21319932/81146389-77624d80-8f78-11ea-8e50-5dfd3e23426f.png)

2. By adjusting the value of `Min edge strength` it's possible to exclude edges below a certain threshold. By adjusting `Cut` a shading can be imposed. The same figure with `Min edge strength` = 0.18 and `Cut` = 0.25:
![image](https://user-images.githubusercontent.com/21319932/81146590-e475e300-8f78-11ea-8594-26a1089366da.png)

Making the measures in the centrality plot toggle-able should be easy to add.

**Comment by andremonezi** [comment]
Great!!!!!!!!!!!!!!!!!!!

**Comment by andremonezi** [comment]
Another matter...
Note that when I use the "manual colors" the colors are the same, but should change according to the palette chosen (rainbow, colorblind, pastel, etc). 

It would be more interesting if the colors manual could display the colors from the respective palette!!

![EX1](https://user-images.githubusercontent.com/64216719/81223140-e4e39d80-8fbb-11ea-9665-84816ddec378.png)


![EX2](https://user-images.githubusercontent.com/64216719/81223149-ead97e80-8fbb-11ea-8125-2dae37121bff.png)
