### ISSUE TITLE
bug on Repeated Measures ANOVA

### ISSUE THREAD

**Issue by lartod** [jasp-stats/jasp-issues#705]
* JASP version: 0.12.1

* OS name and version: Windows 10
* Analysis: Repeated Measures ANOVA, non Bayesian 
* Bug description:

This analysis terminated unexpectedly. 

Error in ref_grid(object, ...): Can't handle an object of class  'NULL' 
Use help('models', package = 'emmeans') for information on supported models.

Slack Trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.referenceGrid(rmAnovaContainer, options, ready)

emmeans::emmeans(fullModel, formula)

ref_grid(object, ...)

stop(data)
* Expected behaviour:
It is a standard analysis that worked with all previous versions of JASP.

enter any data with  rm ANOVA

**Comment by boutinb** [comment]
We have just released a new version 0.12.2 that should solve this problem

**Comment by boutinb** [comment]
If the new version does not solve your problem, reopen this issue.

**Comment by salif08** [comment]
I have version 0.12.2 and this is still happening for me.

**Comment by boutinb** [comment]
@salif08 Can you give us the data you used, and a clear reproduction path?
