### ISSUE TITLE
"Model Name" dropdown missing from SEM module

### ISSUE THREAD

**Issue by tomfaulkenberry** [jasp-stats/jasp-issues#709]
* JASP version:  0.12.2.0

* OS name and version:  Mac OS 10.13.6
* Analysis:  SEM module - Structural Equation Modeling
* Bug description:  the "Model Name" dropdown box is missing from Structural Equation Modeling
* Expected behaviour:  in version 0.11.1.0, the "Model Name" option (under Advanced) gave the ability to compare model fits directly in one output.

![jasp11](https://user-images.githubusercontent.com/12158243/80277517-0c319500-86b5-11ea-9791-6c42cb5a98d9.png)

#### Steps to reproduce:
1. Go to SEM module
2. Click on Structural Equation Modeling
3. Scroll down to Advanced menu
4. "Model Name" no longer appears.

![jasp12](https://user-images.githubusercontent.com/12158243/80277521-15226680-86b5-11ea-9243-6fb7bd6ac334.png)

I know this doesn't fundamentally alter the ability to compare models, but it was nice to see all the model fits in one box. Was there a specific reason for dropping the Model Name box in version 0.12?

Thanks!
Tom

**Comment by vankesteren** [comment]
A lot has changed under the hood from .11 to .12, and this was no longer possible to implement as-is. It was also not very user-friendly! In the next update of the SEM module, we will fix this (soon!). We have great plans for improving the SEM module!

**Comment by tomfaulkenberry** [comment]
Thanks @vankesteren...that's what I suspected.  I will close the issue now.  I appreciate your response!
