### ISSUE TITLE
Python api for JASP

### ISSUE THREAD

**Issue by MooersLab** [jasp-stats/jasp-issues#71]
## Environment (for bugs)

* JASP version:
* OS name and version:
* Analysis:
## Environment (for enhancement requests)
 
* Enhancement: python api
* Purpose: To be able to iterate analyses in JASP with for loop

**Comment by tomtomme** [comment]
@MooersLab 
R-Syntax mode is now available since 0.17 :)
And we also have the R-Console module since some time. That allows:

```
Welcome to R in JASP!
R is (re)starting and has selected module jaspDescriptives
R awaits commands
R is installing or loading a module jaspDescriptives
R awaits commands
> for (i in 1: 4)
{
print(i ^ 2)
}
[1] 1
[1] 4
[1] 9
[1] 16
```

Does this suffice?
