### ISSUE TITLE
JASP version, operating system, what you were doing, the JASP file, or the data file, screenshots, etc.

### ISSUE THREAD

**Issue by MKoenders** [jasp-stats/jasp-issues#710]
* JASP version:0.11.1
 MacOS
* OS name and version: OS Cataline 10.15.4
* Analysis: Anova
* Bug description: This analysis terminated unexpectedly.
* Expected behaviour:

#### Steps to reproduce:

Hi there, 
I have created an Implicit Association Task and I tried out the analysis for this. While doing that I ran into some trouble. I tried to log the data in another way but I still get the same error. 
I want to be able to analyze the different reaction times of the conditions. In the file they are named: VA_negative, VA_positive.
I want to be able to see if the difference in reaction time (VA_positive - VA_negative) is significantly different. 
When entering this in Jasp, I keep on getting the same error. 

Note: eventually I also want take into account the data from the variable tech_usage in the same analysis. To see if this relationship of the IAT is influenced by this. 

_**This analysis terminated unexpectedly.

Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]): contrasts can be applied only to factors with 2 or more levels

Stack trace
analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.manovaComputeResults(jaspResults, dataset, options, ready)

stats::aov(terms(formula(modelFormula), keep.order = TRUE), datasetFac)

eval(lmcall, parent.frame())

eval(lmcall, parent.frame())

stats::lm(formula = terms(formula(modelFormula), keep.order = TRUE), data = datasetFac, singular.ok = TRUE)

model.matrix(mt, mf, contrasts)

model.matrix.default(mt, mf, contrasts)

`contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]])

stop('contrasts can be applied only to factors with 2 or more levels')_

Can you help with this?
I have included my datafile. 

[neurotask final test .xlsx](https://github.com/jasp-stats/jasp-issues/files/4532796/neurotask.final.test.xlsx)

**Comment by boutinb** [comment]
Hi @MKoenders In our new release (0.12) we have rewritten the ANOVA analysis. Could you try this new version?

**Comment by MKoenders** [comment]
Hi Boutinb, 
I have downloaded the latest version but I still get this error: Number of factor levels is < 2 in VA_negativeRT, VA_positiveRT.

**Comment by boutinb** [comment]
@JohnnyDoorn Can you have a look?

**Comment by JohnnyDoorn** [comment]
Hi @MKoenders,

From the error message I see that you were trying to run the MANOVA analysis, while your question implies that you would like to run a Repeated Measures (RM) ANOVA, where you want to compare VA_positive to VA_negative, within the individual. Or are these two conditions (positive/negative) compared between individuals? There seems to be a lot of missing cells in your data, with different rows for each individual that do not contain a value for all of the relevant data. For instance, if you want to compare VA_positive to VA_negative within the individual, and look at an additional factor, you need to have those observations in the same row, so that JASP knows which observations to compare to which. In your current data, this is not the case, so there are no observations upon which to base the inference. 
Does this clarify things for you? Please let me know if not, I'm happy to help more!

Cheers
Johnny

**Comment by MKoenders** [comment]
Hi Johnny, 

Thank you for your answer. So I see what you mean, sort of. I struggle a lot with statistics so I appreciate your help very much! 

I have a new file where I have deleted all the irrelevant information. So I want to compare VA_positive to VA_negative within the individual, but also between the conditions. The condition 1 is the order VA_positive and then VA_negative and condition 2 is the other way around. The condition can be found in column 'I'. 
Then I want to see if Age and Technology use are of influence on these effects (if there are any). That is why I wanted to perform a MANOVA. 

And as for the empty cells, the experiment is programmed that it only saves data that is correct. If someone makes a mistake, les say categorizes a VA-word in the wrong category, that reaction time is not saved. 

And are you saying that I should have the tech_usage, VA_negative, VA_positive and age values all in the same row to be able to compare them? I thought that this would be possible if they all had the same subject number. Or did I not understand this right?

I hope this is understandable in the way I wrote it down. If not, please let me know and I'll try to explain it in a different way. 

Thanks again!

Kind regards, 
Mira

[tussen data.xlsx](https://github.com/jasp-stats/jasp-issues/files/4597849/tussen.data.xlsx)

**Comment by JohnnyDoorn** [comment]
Hi Mira,

To see if Age and Technology are influences, you can add these either as between subjects factors (if they are nominal) or covariates (if they are continuous) in the RM ANOVA.
Unfortunately just having the ID numbers in your data set is not enough for JASP to piece together how it is structured, so you would need the observations of your repeated measure (VA reaction time), the additional factors and covariates,  all in one row, like so:

ID | VA_negativeRT | T_positiveRT | Technology | Age 
--
1 | 1440.48499999917 | 891.795000003185 | high | 25
2 | 459.154999989551 |1011.73500000732 | medium | 54
....

Then, you can add the VA RT scores as repeated measures in the RM ANOVA, add Technology as a between subjects factor, and age as a continuous covariate. 

Cheers
Johnny

**Comment by MKoenders** [comment]
This helps a lot, thanks! I'll make sure everything is in the same row for each participant. 

Is it an option to select several reaction times and merge those cells (e.g. separate the numbers by comma)? Will JASP be able to calculate the average from that? Or do I have to calculate the average for each person and then fill that in in the right row? 

I ask this because VA_negativeRT is made from several reaction times and the analysis only works with averages right? 

Kind regards, 
Mira

**Comment by JohnnyDoorn** [comment]
By default, in the RM ANOVA, JASP will see each row as belonging to a new individual. So if there are no other distinguishing features between those observations (for instance a different condition, or if you want to take time into account), one approach is to take the averages like you suggest. To do this, I would recommend Excel or Libreoffice for manipulation, as this is not something that is possible in JASP. 

Kind regards
Johnny
