### ISSUE TITLE
Chi-Square contribution in CFA/SEM invariance analysis

### ISSUE THREAD

**Issue by kszechy** [jasp-stats/jasp-issues#711]
* Enhancement:  Add in information on the contribution to the chi square for each group 
* Purpose:  For multi-group CFA when you are looking at configural invariance, constraining factor loadings, intercepts and residuals to look at weak, strong and strict invariance.  

**Is your feature request related to a problem? Please describe.**
 

I was running an SEM measurement model on some questionnaire data and comparing male and female respondents.  I was looking at model fit with gender as the grouping variable.  Then I added in several levels of constraints as described above to look at measurement invariance.   I was using the Mplus emulation.  I get good output with model fit chi square, df etc and all the fit indices.  What I do not get in the output is the contribution to the chi square of each of the groups (male and female)  

**Describe the solution you'd like**
 
Would like to see the contribution to the chi square of each group.

**Comment by vankesteren** [comment]
Great suggestion! We'll implement this as soon as it is convenient :)

**Comment by tomtomme** [comment]
@juliuspfadt 
There is a pull request from LSLindeloo almost done to fix this reviewed by Kucharssim. 
Maybe easy to pick this one up?
