### ISSUE TITLE
Feature request: Add the effects-coding option for factor scaling from the CFA module to the SEM module

### ISSUE THREAD

**Issue by HeikoBreitsohl** [jasp-stats/jasp-issues#713]
Dear JASP Team,

thank so much for incorporating the effects coding option for factor scaling into the CFA module (issue #103)!

May I suggest also making this available in the SEM module?

Thanks, and keep up the great work!

Best,
Heiko

**Comment by vankesteren** [comment]
We'll do this in the next update of the SEM module (soon!)

**Comment by juliuspf** [comment]
AFAIK, this is in SEM by now. I will close this. @HeikoBreitsohl Feel free to reopen if your issues remains.
