### ISSUE TITLE
SEM: Printing sample size and number of parameters (more prominently)

### ISSUE THREAD

**Issue by HeikoBreitsohl** [jasp-stats/jasp-issues#716]
* Enhancement: Print the sample size in the default output
Also, the number of parameters could be displayed by default, instead of in the Likelihood table that has to be requested.
* Purpose: Being able to check the used sample size (and number of parameters), as it is possible in many other SEM packages

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Perhaps a note in the Parameter Estimates table would be a good place, or in the Chi-squared table.

**Comment by vankesteren** [comment]
Thank you for the feature request! We will look into this in the next iteration of the SEM analysis

**Comment by tomtomme** [comment]
@HeikoBreitsohl 
There have been some improvements to SEM and above you can see that a patch regarding this issue was merged. Can you check if this is sufficient with jasp 0.18.3?
Thx

**Comment by HeikoBreitsohl** [comment]
@tomtomme 
Thanks, this is definitely an improvement!

**Comment by tomtomme** [comment]
Cool. Closing then! Feel free to open new issues if you find further shortcomings!
