### ISSUE TITLE
Shout out to the JASP team!

### ISSUE THREAD

**Issue by jtcoldren** [jasp-stats/jasp-issues#719]
As my stats class went from face-to-face to on-line in a few weeks, JASP was just what I needed.  My university moved SPSS to a virtual windows machine for statistics students.  It works okay in this environment, but is laggy and even more twitchy than usual.  I didn't have time to teach R in the middle of the semester, so JASP was great alternative.  User friendly and powerful for teaching stats, but it needs a bit more user flexibility.  Overall though, thanks to the team for a great product!

**Comment by EJWagenmakers** [comment]
:-)) Thanks! Your suggestions for improvement are very good -- in fact, they are among our top priorities for this year.
