### ISSUE TITLE
Correlation: pair-wise layout and menu names

### ISSUE THREAD

**Issue by lindeloev** [jasp-stats/jasp-issues#72]
I propose the following improvements to both Bayesian and frequentist correlations:

# 1. Option to choose between matrix and pair-wise layout
Correlating two variables results in the following output:

![image](https://user-images.githubusercontent.com/1439417/28771834-8668dcfa-75e4-11e7-8277-39aa97efe7d0.png)

This seems needlessly cluttered for something so simple. The matrix layout for a simple two-variable correlation is always something that I have to "excuse" to the students. A pair-wise presentation would be much easier to read in this case:

Variable pairs | Pearson’s r | Lower 95% CI | Upper 95% CI | p-value
-- | -- | -- | -- | --
Neuroticism-Extraversion | -0.35 | -0.425 | -0.271 | < .001

... which of course could be extended with more rows as values are added. This is both more compact and easier to read. In fact, I only see the matrix as a better communication when there are many variables AND only one value per cell (r-value, perhaps flagged). For this reason, I would also suggest that the "pair-wise" layout (better names are welcome!) be the default.

 To illustrate:

![image](https://user-images.githubusercontent.com/1439417/28773202-e539531e-75e8-11e7-8dc3-57f43325820e.png)

Versus

Variable pairs | Pearson’s r | Lower 95% CI | Upper 95% CI | p-value
-- | -- | -- | -- | --
Neuroticism-Extraverson | -0.35 | -0.425 | -0.271 | < 0.001
Neuroticism-Conscentiousness | -0.368 | -0.441 | -0.29 | < 0.001
Neuroticism-Agreeableness | -0.134 | -0.219 | -0.047 | 0.003
Extraversion-Conscentiousness | 0.065 | -0.023 | 0.151 | 0.149
Extraversion-Agreeableness | 0.055 | -0.033 | 0.142 | 0.223
Conscentiousness-Agreeableness | 0.159 | 0.072 | 0.243 | < 0.001

At least for the purpose of getting an impression of the values and intervals, I find the pair-wise presentation easier to decode. You don't have do the same amount of visual searching.

# 2. Remove the analysis for "Bayesian correlation pairs." 
.... since that would be included in the correlation widget per the suggestion above. It's confusing to have them listed as two different analyses when they are really the same analysis.

# 3. Change the name of the analysis to "Correlation" instead of "Correlation matrix." 
Some students have expressed confusion about this when they've only learned about "Correlation."

As always, great work JASP team! I hope you see this suggestion as a way to further distancing yourself from the confusing SPSS defaults :-)

**Comment by TimKDJ** [comment]
The changes you describe are incorporated in 0.12; better late than never, I suppose
