### ISSUE TITLE
Pixelated user interface with JASP 0.12.2.0

### ISSUE THREAD

**Issue by R180** [jasp-stats/jasp-issues#720]
With this new version (0.12.2.0), most of the UI is highly pixelated on my screen (Windows 10 Dell Latitude 5400), though the output portion seems fine. Tried uninstalling then reinstalling the software.

![image](https://user-images.githubusercontent.com/16230091/80647618-c837ea80-8a3c-11ea-9a35-a5574aa19dc7.png)

**Comment by DrMarkGS** [comment]
Same here on Windows 10 laptop - most obvious in the analysis titles and less so in the ribbon
Mark

**Comment by JorisGoosen** [comment]
Could either of you test [this zipped JASP](http://static.jasp-stats.org/Nightlies/WindowsZip/JASP-nightly-v0.12.2.0_noNativeTextRenderWin-d2c0ffff437b014344b84a064ecdff415e67256c.zip) or [this full installer](http://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-v0.12.2.0_noNativeTextRenderWin-d2c0ffff437b014344b84a064ecdff415e67256c.msi)?

They are both of the same build and I changed them to no longer use native text rendering on windows, which might solve this problem.

**Comment by DrMarkGS** [comment]
![image](https://user-images.githubusercontent.com/39003008/80707780-6c27a180-8ae2-11ea-9f71-47f22a11f6f4.png)
Still very pixelated I am afraid

**Comment by JorisGoosen** [comment]
Aah thank you for testing it, I think I know something else to try. Ill get back to you.

**Comment by JorisGoosen** [comment]
Then [this zip](http://static.jasp-stats.org/Nightlies/WindowsZip/JASP-nightly-v0.12.2.0-273972d90c9d69bf3383e44cc7236c5daca7be46.zip) or [this msi](http://static.jasp-stats.org/Nightlies/WindowsZip/JASP-nightly-v0.12.2.0-273972d90c9d69bf3383e44cc7236c5daca7be46.msi) might fare better?

**Comment by DrMarkGS** [comment]
msi link not working but am downloading the zip file ok.

**Comment by JorisGoosen** [comment]
http://static.jasp-stats.org/Nightlies/WindowsZip/JASP-nightly-v0.12.2.0-9bc9fb7d416745d6507714374619adfa3922db7e.zip should actually work

**Comment by JorisGoosen** [comment]
@DrMarkGS So the last one will actually work, sorry about the possible confusion.

**Comment by DrMarkGS** [comment]
Cannot get the zipped version to open on my PC - will download the last link you sent me

**Comment by R180** [comment]
For me, that version fixes the problem when I run the EXE file:

http://static.jasp-stats.org/Nightlies/WindowsZip/JASP-nightly-v0.12.2.0-9bc9fb7d416745d6507714374619adfa3922db7e.zip

(However, I don't know how to install it).

**Comment by JorisGoosen** [comment]
@R180 you could install http://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-v0.12.2.0-9bc9fb7d416745d6507714374619adfa3922db7e.msi but it isn't an official release.
We will probably bring one out next week with this fix. Until then you could definitely use this, but if you find other bugs be sure to mention it is a "nightly".

**Comment by DrMarkGS** [comment]
Looks fine with JASP-nightly-v0.12.2.0-9bc9fb7d416745d6507714374619adfa3922db7e

many thanks
Mark
