### ISSUE TITLE
Wrong plot and median

### ISSUE THREAD

**Issue by rreverberi7** [jasp-stats/jasp-issues#721]
* JASP version: 0.12.2

* OS name and version: Opensuse 15.1
* Analysis: Bayesian paired samples t test
* Bug description:Choosing 'Wilcoxon signed-rank', the 'prior and posterior' plot shows a positive median when it should be negative and the plot reflects this error. Choosing 'Student', median and plot are correct
* Expected behaviour: Median and plot should correspond to data

#### Steps to reproduce:
1. Go to 'Bayesian paired samples t test'
2. Click on 'Wilcoxon signed-rank, prior and posterior
[foo.zip](https://github.com/jasp-stats/jasp-issues/files/4557662/foo.zip)
'

**Comment by EJWagenmakers** [comment]
@JohnnyDoorn

**Comment by JohnnyDoorn** [comment]
@vandenman while trying to replicate this issue I ran into another issue when trying to plot the prior/posterior for the paired samples t-test (both student and wilcoxon): "The engine crashed while trying to run this analysis...", does it work for you on Ubuntu? 
This does not happen for the one and two sample t-tests strangely..
I will change the sign of the median to at least make the plot correct

**Comment by rreverberi7** [comment]
"does it work for you on Ubuntu?"

Sorry, I don't use Ubuntu, I use Opensuse 15.1 and Jasp runs without any crash, including the function where the wrong median and plot appear. I tried also the windows 64bit version (0.12.2) and the behavior is identical: no crash but wrong median and plot.

Please ask me if you need any other information.

**Comment by tomtomme** [comment]
I tested this on manjaro JASP 0.18.2 flatpak and all worked fine.
