### ISSUE TITLE
[Solved] Mac: Font book - Restore standard fonts - restart. New install of JASP: Won't graph, "Polygon edge not found"

### ISSUE THREAD

**Issue by rickogorman** [jasp-stats/jasp-issues#722]
* JASP version: 0.12.2, 0.11.x
macOS 
* OS name and version: macOS 10.14.6 (Mojave)
* Analysis: Plots
* Bug description: When I have a dataset open, and then click on any plotting options, JASP fails to plot, instead gives the error message 'polygon edge not found'. I have installed the latest JASP (0.12.2) on a laptop with same OS version and it works fine.
* Expected behaviour: JASP should plot scatterplots, etc. 

#### Steps to reproduce: I don't know! It is fine on one machine, not the other. SO there is something that JASP uses that is set differently between the two machines, I guess? I have attempted to uninstall JASP to do a clean install, but that didn't make a difference.

![Screenshot 2020-04-29 at Wed, 29 Apr  19 38 15](https://user-images.githubusercontent.com/3865672/80700687-0d5c2b00-8ad6-11ea-8373-8cdee8fde331.jpg)

**Comment by boutinb** [comment]
Hi @rickogorman, could you try to JASP with an extra argument? For this: 
- starts a terminal
- type 'cd /Applications/JASP.app/Contents/MacOS'
- type './JASP --safeGraphics'
Check if JASP has the same problem.

**Comment by rickogorman** [comment]
Same outcome as before.

**Comment by rickogorman** [comment]
I add some more now. I booted my Mac (iMac 2017 27") into safe mode. There, JASP works fine! The above problem does not manifest. So I then booted into normal mode and quit everything I could (I do run quite a few services, etc.). However, the problem remains in normal mode.

I used activity monitor to shut down as many as possible. I turned off on-demand virus scanning (Sophos). I could not shut down a couple of services from iStats for some reason (even force quitting via Activity Monitor).

**Comment by boutinb** [comment]
Hmm. It's quite strange. @JorisGoosen : do you have any idea what could cause this problem?

**Comment by vandenman** [comment]
It looks like the `grid` package throws an error. You could see if Arial is disabled (e.g., see [here](https://stackoverflow.com/questions/10581440/error-in-grid-calll-textbounds-as-graphicsannotxlabel-xx-xy-polygon) where someone has the same error message using R) but I have no idea why it works in safe mode.

**Comment by AlexanderLyNL** [comment]
If font type is a problem, then perhaps restoring the standard fonts might help. See also 

https://github.com/jasp-stats/jasp-issues/issues/405

**Comment by JorisGoosen** [comment]
Hmm, ive never heard of this problem but @AlexanderLyNL 's suggestion seems worthwhile to try!

**Comment by rickogorman** [comment]
OK, tried that, no cigar. I followed the steps (font book-->restore standard fonts) but the error still remains (it said no problems encountered, did make a fonts (removed) folder, to be honest I didn't see how I'd have messed up my fonts). Do I need to restart? Didn't see that step mentioned.

**Comment by AlexanderLyNL** [comment]
Restarting is always a good idea. Previously, we had some plot issues due to the plots not finding the right font. Sometimes these libraries get scrabbled a bit. It's typically not a big deal, and easily restored. If restoring and restarting doesn't help, could you then please add the log files in a zip to this thread for us to look into more carefully?

**Comment by rickogorman** [comment]
I take it back. I did try restarting and it is fixed! The original directions don't mention restarting, so worth getting that on the record. Thanks for your help!

**Comment by AlexanderLyNL** [comment]
Awesome. Thanks for getting back to us.

**Comment by sbittman** [comment]
How do I open my font book?  Is this part of JASP, or my OS?

**Comment by AlexanderLyNL** [comment]
This is part of macOS. You can open it in your Applications folder.
