### ISSUE TITLE
Paste Tables as Images

### ISSUE THREAD

**Issue by gsstoudt** [jasp-stats/jasp-issues#723]
Perhaps this is an odd request, but I would like my students to be able to copy/paste tables as images.  It makes it much easier for them to organize and write up their reports in Word (baby steps--it is intro stats).

**Comment by vandenman** [comment]
Why not take a screenshot? 

[Windows](https://support.microsoft.com/en-us/help/4027213/windows-10-open-snipping-tool-and-take-a-screenshot) has build-in support for this, for Linux it's quite easy to setup and for Mac I don't know as I don't use Mac. The screenshot tool I linked allows you to select a rectangular region, e.g., a table, to take a screenshot of. If you want to increase or decrease the font size/ resolution, first zoom JASP and then afterward take a screenshot. FWIW whenever I write a blog post for JASP I do it that way.

**Comment by AlexanderLyNL** [comment]
On mac you can take a screenshot with cmd+shift+4, which allows you to select the region.

**Comment by gsstoudt** [comment]
Both true.  Certainly not a high priority item, but it is a feature in other programs.  Thanks for the replies.

**Comment by EJWagenmakers** [comment]
I agree with the proposed workarounds, which are easy enough, but if adding this is easy I can see the value -- you don't need to select the box, for instance, and some people may not know about the screen capture programs.

**Comment by juliuspf** [comment]
so how easy is this @boutinb?

**Comment by boutinb** [comment]
Not easy... at least I don't know an easy way to do this. As a copy (latex) works already (and also screenshot is possible), I think we can set as won't fix.
