### ISSUE TITLE
Error in an independent sample T-test

### ISSUE THREAD

**Issue by Sarah226** [jasp-stats/jasp-issues#724]
* JASP version: 0.12.2

* OS name and version: Windows
* Analysis: ?
* Bug description:
This analysis terminated unexpectedly.

Error in .ttestIndependentMainFill(ttest, dataset, options, testStat, : object 'result' not found

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.ttestIndependentMainTable(jaspResults, dataset, options, ready, type)

.ttestIndependentMainFill(ttest, dataset, options, testStat, optionsList)

* Expected behaviour: a table

#### Steps to reproduce:
1. Go to '.T-test..'
2. Click on '..independent samples t test..'
3. Scroll down to '..fill in a variable and a grouping variable..'

**Comment by boutinb** [comment]
Hallo @Sarah226 . I cannot reproduce this problem on my Windows PC. Which version of Windows do you have? Does this problem occur with other analyses?
Could also set the log on: In Preferences/Advanced, set Log to file on, do again the steps to reproduce the error, and then click on the Show Logs button. You should see 1 desktop log file and 4 engine log files: could you send me these files (by adding these files in a comment in GitHub)?
Bruno

**Comment by Sarah226** [comment]
Hello @boutinb I have windows version 10 Pro, this problem does not occur with other analyses just with this specific one. I'm afraid I cant show you the data because it is for my study.


[JASP 2020-05-01 20_48_13 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/4565934/JASP.2020-05-01.20_48_13.Engine.1.log)
[JASP 2020-05-01 20_48_13 Engine 2.log](https://github.com/jasp-stats/jasp-issues/files/4565935/JASP.2020-05-01.20_48_13.Engine.2.log)
[JASP 2020-05-01 20_48_13 Engine 3.log](https://github.com/jasp-stats/jasp-issues/files/4565936/JASP.2020-05-01.20_48_13.Engine.3.log)
[JASP 2020-05-01 20_48_13 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/4565937/JASP.2020-05-01.20_48_13.Desktop.log)
[JASP 2020-05-01 20_48_13 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/4565938/JASP.2020-05-01.20_48_13.Engine.0.log)

I hope I did this the right way.

**Comment by boutinb** [comment]
@Sarah226 This error will be fixed in the next release. You can try it here:
 http://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-stable-142def8358c26741740d95b57c5f46dd848c066b.msi
Pay attention that this is a development version which is not full tested yet. But it would very interesting for us if this solves your problem.

**Comment by Sarah226** [comment]
At @boutinb it did solve my problem thank you very much. :)
