### ISSUE TITLE
Feature request: Enable translation via a web-based service (e.g. Weblate)

### ISSUE THREAD

**Issue by JoKeyser** [jasp-stats/jasp-issues#726]
* Enhancement: Integration with web-based translation service.
* Purpose: Simplify continuous translation from community.
* Use-case: Anyone wanting to translate with minimal technical hassle.

**Is your feature request related to a problem? Please describe.**  
Currently, the translation requires manual editing of `.po` files and additional steps to get the changes into the repository. (See https://github.com/jasp-stats/jasp-desktop/blob/stable/Docs/development/translate.md)
This is already a great step, but is unneccesarily complicated in the long run.

**Describe the solution you'd like**  
Integration with [Weblate](https://weblate.org/), offering free use of their hosted service for FLOSS projects such as JASP.
This reduces the task of translators to log in to a web service and type in the translation.
Weblate can then push the translation to the repository, giving people credit of their work.

**Describe alternatives you've considered**  
There are other web-based translation services, but usually they are not FLOSS themselves.

**Comment by EJWagenmakers** [comment]
Cool. @FransMeerhoff, what do you think?

**Comment by FransMeerhoff** [comment]
Hi @JoKeyser 

I think this is indeed a very good suggestion!
Speaking for myself, I do not have  experience with Weblate at the moment.
But at first glance, it looks very promising for translators and us to use. 
It has GiHub integration, workflow automation and could indeed be a time a saving and facilitating tool for developers/translators.
Moreover it is open source and has the possibility to host it for ourselves.

@EJWagenmakers  We were indeed busy with some online solution to facilitate the translation process. So this is definitely a tool we must investigate more.

Kind regards
Frans Meerhoff

**Comment by TimKDJ** [comment]
I was going to post something similar when I ran across [crowdin](https://crowdin.com/). It seems to be a pretty popular tool for this type of thing. Example of a software project that utilizes it: [Bitwarden](https://crowdin.com/project/bitwarden-desktop).

@FransMeerhoff we should have a look at a few of these tools to see what catches our fancy.

**Comment by FransMeerhoff** [comment]
@TimKDJ  Agree

**Comment by tomtomme** [comment]
I would contribute to translation, if something like weblate is ready to go :D

**Comment by JoKeyser** [comment]
@tomtomme, great, you should be able to translate already, see https://hosted.weblate.org/projects/jasp/

@FransMeerhoff , I think this issue can be closed, unless you consider this still under evaluation?
