### ISSUE TITLE
Adjusted standardized residuals to chi square tests

### ISSUE THREAD

**Issue by andremonezi** [jasp-stats/jasp-issues#727]
It would very interesting if JASP could provide standardized/adjusted standardized residuals for _a_ _posteriori_ comparisons when running chi-square tests. 

This feature is quite important mainly in those cases with contingency tables 3X3 or more. 
Regards,

**Comment by boutinb** [comment]
@EJWagenmakers What do you think? Is is something for Jiashun?

**Comment by andremonezi** [comment]
Dear all, what do you think about that?

**Comment by EJWagenmakers** [comment]
I'm seeing some other options we could add to the contingency table. So it's worth an upgrade. About the standardized residuals, this document describes a series of options with some really nice plots as well: http://www.sthda.com/english/wiki/chi-square-test-of-independence-in-r

**Comment by NenaRoncevic** [comment]
Dear colleagues, this is just to support idea to add options on standardized/adjusted standardized residuals in chi-square tests in future iterations of JASP. Thank you.

**Comment by tomtomme** [comment]
@andremonezi 
We have those residuals now, but we do not have the p-values for those post hoc tests.

@LSLindeloo 
You worked on the residuals. Are you planning on adding those p-values too?

**Comment by tomtomme** [comment]
closing as duplicate of https://github.com/jasp-stats/jasp-issues/issues/2861
