### ISSUE TITLE
Black window, freeze, and eventually whole system crash

### ISSUE THREAD

**Issue by Bobby87a** [jasp-stats/jasp-issues#732]
* JASP version: 0.12.2

* OS name and version: Ubuntu 20.04
* Analysis: 
* Bug description: after launching the app, jasp window appears with no content, black. Whole system freezes/crashes
* Expected behaviour: normal launch

#### Steps to reproduce:
1. install above mentioned version of JASP on Ubuntu 20.04 via flatpak
2. launch JASP, either via terminal or application overview (SUPER + a)
3. watch what happens

If its not my individual problem, maybe latest version of JASP has issues with new Ubuntu 20.04?

**Comment by JorisGoosen** [comment]
@Bobby87a what kind of videocard/GPU do you have in your system?
And did you update to the newest flatpak through https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak ?

**Comment by nduduk** [comment]
>     * JASP version: 0.12.2
> 
> 
>     * OS name and version: Ubuntu 20.04
> 
>     * Analysis:
> 
>     * Bug description: after launching the app, jasp window appears with no content, black. Whole system freezes/crashes
> 
>     * Expected behaviour: normal launch
> 
> 
> #### Steps to reproduce:
> 
>     1. install above mentioned version of JASP on Ubuntu 20.04 via flatpak
> 
>     2. launch JASP, either via terminal or application overview (SUPER + a)
> 
>     3. watch what happens
> 
> 
> If its not my individual problem, maybe latest version of JASP has issues with new Ubuntu 20.04?

I have the same problem.

**Comment by JorisGoosen** [comment]
Have you tried my suggestions?

**Comment by JorisGoosen** [comment]
And I would also be interested in which GPU you use.
