### ISSUE TITLE
JASP not sorting alpha numerics properly

### ISSUE THREAD

**Issue by jdebeer2005** [jasp-stats/jasp-issues#735]
* JASP version: 0.12 thee newest

* OS name and version: Win 10
* Analysis: JASP not sorting alpha numerics properly
* Bug description:  Contingency table - had a set of labels - did not sort in order-  Changed them, in HAJSP and then in the scsv file.  did not fix
* Expected behaviour:  I expect alpha numerics to sort properly

#### Steps to reproduce:
[sortin problem JASP .zip](https://github.com/jasp-stats/jasp-issues/files/4593967/sortin.problem.JASP.zip)

2. Click on '....'  Contengency Table  look at headings

**Comment by jdebeer2005** [comment]
Further to issue.  A work around is to reanme the csv file to something new.  Sort the labels, Alpha Numerically as you like them, Klugly at best, and then rerun the cont table.  sorts the way you want them to.  The issue was trying to create alpha numerics in JASP, but JASP sorted the data and labels the way it had originally read it in from the first file.

What did this teach me, as a teaching moment, get your data in correct format in the csv file and save and sort it correctly first.

Thanks

JDB

**Comment by vandenman** [comment]
Thanks for the issue! JASP does not sort the alpha numerics but instead, it uses the order of the ordinal variable. 

In the data view, click on the name of a variable:
![image](https://user-images.githubusercontent.com/21319932/81493786-9c6dfd80-92a3-11ea-8f48-6aefde2f195c.png)

Next, a window opens:
![image](https://user-images.githubusercontent.com/21319932/81493797-b3aceb00-92a3-11ea-8125-149de82db25a.png)

The order in the tables and plots should be the same order as that of the labels. On the right, there are up and down arrows that allow you to reorder the labels as you see fit. For example, this is the initial table:
![image](https://user-images.githubusercontent.com/21319932/81493818-ece55b00-92a3-11ea-89dd-1f9968f046e6.png)

After I switch `1V` and `2V`, the corresponding rows in the table, the first and second row, flip:
![image](https://user-images.githubusercontent.com/21319932/81493827-fff82b00-92a3-11ea-890f-ff281c8ed830.png)

Please let me know if that solves the problem!

**Comment by jdebeer2005** [comment]
Thank you sir, that does indeed solve my problem.  Far easier than the 6-hr work around I engaged in.

Thanks so much

All is well.

JDB
