### ISSUE TITLE
JASP crashed

### ISSUE THREAD

**Issue by jes1984** [jasp-stats/jasp-issues#736]
* JASP version: 0.12.2
* OS name and version: Windows 10 Version 1903

* Analysis: 
* Bug description:
* Expected behaviour:

#### Steps to reproduce:

-----------------------------------------------------------------------

### Debug information:
**Engine # 0** process *crashed* and it's state is *resuming*.
**Engine # 1** process *crashed* and it's state is *resuming*.
**Engine # 2** process *crashed* and it's state is *resuming*.
**Engine # 3** process *does not exist (anymore)* and it's state is *moduleRequest*.

[Commit used](https://github.com/jasp-stats/jasp-desktop/commit/eca7e082cdfa0ebf7c375a739ce6ad37fa4a4775)

**Comment by boutinb** [comment]
Hi @jes1984 Could you be a bit more descriptive? Do you have a 32 or 64 bit Windows version? Does it crash when you just start JASP or it during the loading of file, or during the running of an analysis? Did you try an older version of JASP?

**Comment by JorisGoosen** [comment]
And, have you ever installed a dynamic module?
