### ISSUE TITLE
SEM

### ISSUE THREAD

**Issue by Jiashun97** [jasp-stats/jasp-issues#739]
I have 2 questions: 

1. I was wondering why can’t I just copy a certain value of the output; 
2 the structural equation model (SEM) feature depends on Lavan package, it seems that the support for latent classification/profile analysis (LCA, LPA) is not very good  Will there be corresponding improvements?

have a nice day,

Zheng Hui
Shanghai Key Laboratory of Psychotic Disorders, Shanghai Mental Health Center, Shanghai Jiaotong University School of Medicine, Shanghai, China
zh.dmtr@gmail.com

**Comment by vankesteren** [comment]
Hi Jiashun, 

thank you for your comments. 
1. that's a good point! Maybe you can submit a separate enhancement request for this? It should be possible, but it's unrelated to the SEM module.
2. Yes, indeed LCA/LPA is not very well supported by lavaan, and accordingly it would be an entirely new analysis to implement. It's possible that this has already been requested, but if not, could you submit an enhancement request for this too?

Erik-Jan
