### ISSUE TITLE
JASP stopped working while excluding data using click marks

### ISSUE THREAD

**Issue by jdebeer2005** [jasp-stats/jasp-issues#741]
* JASP version: 0.12.2.0

* OS name and version: win 10
* Analysis:  Trying to filter database in the are where one clicks the check marks on left
* Bug description:  I can click tow checkmarks, but when I click the third JASP stops working
* Expected behaviour:  I expect to be able to click and exclude data at will
[Eurofish combo - YF & SJ May 12.zip](https://github.com/jasp-stats/jasp-issues/files/4623174/Eurofish.combo.-.YF.SJ.May.12.zip)

#### Steps to reproduce:
1. Go to '...' Database pane
2. Click on '....' check marks more than 2

**Comment by JorisGoosen** [comment]
Aah yeah, that is unfortunate. I just tried this out and JASPt does indeed stop working on clicking the third checkmark... 
I will check it out and fix it!

**Comment by AlexanderLyNL** [comment]
Also occurs on 0.12.1 on mac. It appears that the engine continues running after the third check mark. Hopefully that provides you with some extra information.

**Comment by jdebeer2005** [comment]
Now the darn thing will not clear the click marks and return to normal.

[Eurofish combined -SJ - May 11 - editied .zip](https://github.com/jasp-stats/jasp-issues/files/4625018/Eurofish.combined.-SJ.-.May.11.-.editied.zip)

**Comment by jdebeer2005** [comment]
JASP team, this is a very unfortunate bug.  If you create clicks to eliminate observations and then cannot clear them to the original recipe you lose your whole analysis set on the original data.  This is costing me a bunch of time, and creating errors in my reports being planned for publication.  Please fix.

JDB

**Comment by JorisGoosen** [comment]
@jdebeer2005 don't worry, we are working on it and it will be fixed in the next release!
Don't let the lack of activity here lure you into the thought that we have forgotten about it, we also need to fix other things.

For now I do have a workaround for you, although it does make the process less nice. But well, at least you can do your analyses this way.

If you load your data, first you set the filter(s) you like. Then only after that you should add the analyses.

In the meantime we will fix this problem and have a release out soon (probably next week) that just works. Hope this helps you in the meantime.

**Comment by JorisGoosen** [comment]
In fact just removing the ANOVA should fix the file you already sent.

**Comment by JorisGoosen** [comment]
> Now the darn thing will not clear the click marks and return to normal.
> 
> [Eurofish combined -SJ - May 11 - editied .zip](https://github.com/jasp-stats/jasp-issues/files/4625018/Eurofish.combined.-SJ.-.May.11.-.editied.zip)

And this is the same problem I guess? As in, it hangs when you change the checkmark?

**Comment by JorisGoosen** [comment]
Hmm, it seems our current development version already works. 

Maybe @jdebeer2005 and @AlexanderLyNL can test it with http://static.jasp-stats.org/Nightlies/MacOS/JASP-nightly-stable-350200722463bcd8c935d71c819007d49b2a7319.dmg ?

**Comment by JorisGoosen** [comment]
Maybe @jdebeer2005 can test http://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-stable-350200722463bcd8c935d71c819007d49b2a7319.msi

And @AlexanderLyNL can test it with http://static.jasp-stats.org/Nightlies/MacOS/JASP-nightly-stable-350200722463bcd8c935d71c819007d49b2a7319.dmg ?

**Comment by jdebeer2005** [comment]
I got a whole bunch of errors installing this, missing some 4 dlls.  Sorry, I did not log them,

**Comment by jdebeer2005** [comment]
Very sorry gentlemen, closing ANOVA did NOT clear the click marks.  As you see I tried a newer version, and that would not work after installation.   i am still at the same level I was yesterday.  Thanks for all your efforts.  i can wait.
JDB

**Comment by AlexanderLyNL** [comment]
I tested the new nightly, but the problem is still there for me.

**Comment by jdebeer2005** [comment]
Today I was changing the name value of a label from V to VPC-J.  I had to resort to changing a label value and saving the data set, and after 2 saves it simply closed the data set, and my label might or might not have been saved.  One by One, through 3 data sets.  Lots of saving and re-opening.  these are pretty big data set to me, 7,000 obs, 17,000 obs, and 22,000 obs.  I thinkit got tired of recalculation of ANOVA with each change of label.  Is the a pause button somewhere?  of, like Excel, F9 to recalc.

We are learning every day.

thanks

JDB

**Comment by JorisGoosen** [comment]
Well, my workaround probably works well here as well. Just modify your data without the ANOVA and then it shouldn't give so much grief.

**Comment by jdebeer2005** [comment]
thanks, and yes, that is what had to be done.
All is well now.

JDB

**Comment by JorisGoosen** [comment]
Hmm, it seems ANOVA just gets stuck completely whenever I change even one checkmark...
@JohnnyDoorn could you take a look on Win10? 
Maybe it is also broken on linux, so you could try that first if you'd like.

**Comment by JorisGoosen** [comment]
And you can try this out easily by loading the attached dataset and simply unchecking (for instance) "1V" in column "Precooker". 

ANOVA seems to take an awfully long time to calculate the needed results anyway, even if just refreshing. Could this be because +- 22000 rows is a lot for this kind of analysis?
Or is there some kind of problem on Windows with the ANOVA?

And if it is reasonable for it to take so long Im going to guess there was a reason we did not have callbacks everywhere right? I remember some issue where @JohnnyDoorn was also involved where someone was trying to do a large ANOVA as well but was recommended to use a mixed models analysis. @vandenman I think you were also involved in that discussion, does this ring a bell?

**Comment by jdebeer2005** [comment]
This morning I was changing labels, and sving each time, “trying different values for dummy variable” and the dataset suddenly closed, and then would not reopen.  Something a but a “data-bin” not found.

**Comment by JorisGoosen** [comment]
Well, the saving process **can** take a few seconds to complete and by your description it sounds like JASP crashed while you were saving it. The "data.bin" it cannot find is one of the entries in a jasp-file and it seems JASP crashed while trying to write that. Although not necessarily because of it.

I am really sorry to hear you are having all these problems with JASP...

**Comment by JorisGoosen** [comment]
> 
> 
> Today I was changing the name value of a label from V to VPC-J. I had to resort to changing a label value and saving the data set, and after 2 saves it simply closed the data set, and my label might or might not have been saved. One by One, through 3 data sets. Lots of saving and re-opening. these are pretty big data set to me, 7,000 obs, 17,000 obs, and 22,000 obs. I thinkit got tired of recalculation of ANOVA with each change of label. Is the a pause button somewhere? of, like Excel, F9 to recalc.
> 
> We are learning every day.
> 
> thanks
> 
> JDB

I will also see if we can add this feature per analysis because it seems rather useful to have, especially with larger datasets like the one you are using.

**Comment by jdebeer2005** [comment]
Sir, I am learning JASP real well.  You guys are doing a great job responding.

 

Thanks for all your help, and your commitment to freeware.  This is great.

 

JDB

**Comment by JohnnyDoorn** [comment]
> And you can try this out easily by loading the attached dataset and simply unchecking (for instance) "1V" in column "Precooker".
> 
> ANOVA seems to take an awfully long time to calculate the needed results anyway, even if just refreshing. Could this be because +- 22000 rows is a lot for this kind of analysis?
> Or is there some kind of problem on Windows with the ANOVA?
> 
> And if it is reasonable for it to take so long Im going to guess there was a reason we did not have callbacks everywhere right? I remember some issue where @JohnnyDoorn was also involved where someone was trying to do a large ANOVA as well but was recommended to use a mixed models analysis. @vandenman I think you were also involved in that discussion, does this ring a bell?

Yes, there is some code deeply embedded in the very basic lm() function in R (which is used by ANOVA), which does not handle big datasets very well. In the previous issue, @vandenman looked into this, but this is very hard to fix unfortunately.

**Comment by JorisGoosen** [comment]
So should we maybe add some kind of warning if a dataset is too large to be handled reasonably quick? Like, what are "normal" sizes of data to expect for an ANOVA?

**Comment by JorisGoosen** [comment]
Ok, so this issue has been solved, now when clicking the marks it will work instantly. Previously it would have worked, but it might have taken quite a lot of time...
Next version should contain this fix.
