### ISSUE TITLE
Can't change column type

### ISSUE THREAD

**Issue by jssallee** [jasp-stats/jasp-issues#743]
* JASP version: 0.9.2.0

I am trying to change numerous columns from nominal to scale and although I click on the correct type, JASP does not change this. 
columns that need to be changed to scale are: 1Years in LE; 1% Positive for Youth; 1Years in LE; 2KnowledgeMean; and 2SelfMean

[Final Survey Data-Coded.xlsx](https://github.com/jasp-stats/jasp-issues/files/4629565/Final.Survey.Data-Coded.xlsx)

**Comment by EJWagenmakers** [comment]
This means that at least one cell contains text.
