### ISSUE TITLE
FlexPlot issue

### ISSUE THREAD

**Issue by jdebeer2005** [jasp-stats/jasp-issues#745]
* JASP version: 0.12.2.0
 Windows
* OS name and version: W-10
* Analysis: Analysis terminated unexpectedly
* Bug description: Analysis terminated unexpectedly
* Expected behaviour: Expected to run a simple flexplot

#### Steps to reproduce:
1. Go to '...' Flexpot
2. Click on '....'  Dep Var -Precooker loss, independent var - precooker
Received an error msg.  I screen sniped it for your perusal.  Included in the JASP data set zip file

Apparently I cannot upload my file too large. so just sending the error msg in a zip file.

[2020-05-14 - Analysis teminated  unexpectedly -png .zip](https://github.com/jasp-stats/jasp-issues/files/4632004/2020-05-14.-.Analysis.teminated.unexpectedly.-png.zip)

**Comment by jdebeer2005** [comment]
Folks, i am thinking this is a scale problem.  As in too many observations.
I just ran Linear Modeling on the same data set and think I can up with the same error code
[2020-05-14 - Linear Modeling Error.zip](https://github.com/jasp-stats/jasp-issues/files/4632042/2020-05-14.-.Linear.Modeling.Error.zip)

**Comment by jdebeer2005** [comment]
Just ran it against General Linear Modeling, same darn error, I think.  
[GLM.zip](https://github.com/jasp-stats/jasp-issues/files/4632049/GLM.zip)

Hey, I cannot sent the JASP file, bloated, but am sending the csv file.

[Eurofish combined -SJ - May 14 - edited - removed outliers.zip](https://github.com/jasp-stats/jasp-issues/files/4632054/Eurofish.combined.-SJ.-.May.14.-.edited.-.removed.outliers.zip)

**Comment by TimKDJ** [comment]
At present flexplot does not allow special characters in column names (basically anything that isn't a letter or a number).

In the future we will ensure all modules allow this, but for now you'll have to rename the columns to use this analysis.

**Comment by jdebeer2005** [comment]
thanks, I will test that feature.

JDB

**Comment by jdebeer2005** [comment]
I see the issue, even a space is a char to FlexPlot.  Got it

**Comment by juliuspf** [comment]
@dustinfife, do you know if this is still an issue?

**Comment by tomtomme** [comment]
@jdebeer2005 
I tested with the uploaded data as a .jasp file from another of your issues. I could encounter the issue with this old file. However, if I removed the space and then re-added the space, everything worked fine. 
So in old files, one would have to rename the variables to get a working encoding, that now with 0.18.2 can handle spaces etc.
Thus I consider this fixed. If you disagree, feel free to reopen.
