### ISSUE TITLE
SEM: "<~" and "<-" operators do not operate?

### ISSUE THREAD

**Issue by Johno64** [jasp-stats/jasp-issues#746]
* JASP version: 0.12.2
 * OS name and version: WINDOWS 10 Pro
* Analysis: SEM Multigroup analysis
* Bug description: 

Operators "<~" and "<-" do not seem to work

1) If I use "<~" 
[example: AttVega <~ INATTVEGA + EXATVEGA]
I get the error message 
"Variable(s) in model syntax not recognized: Attvega"
If I just change "<~" to "=~" it does work

2) If I want to compute a model 
[example: VEGA.model <- 'AttVega =~ INATTVEGA + EXATVEGA']
I get the error message 
"lavaan ERROR: left hand side (lhs) of this formula: VEGA.model<-\u0027AttVega =~ INATTVEGA+EXATVEGA\u0027 contains either a reserved word (in R) or an illegal character "VEGA.model<-\u0027AttVega""
I tried different quotation marks but the problem persisted...

thanks in advance for helping out!
John

**Comment by vankesteren** [comment]
Hi John,

I don't believe that either `<-` or `<~` are proper `lavaan` syntax? Please  I assume you want to create composite variables? We do not yet support these. We might support these once #354 is implemented.

Erik-Jan

**Comment by Johno64** [comment]
Hi Erik-Jan,

I saw the <~ operator in a video by Erin Buchanan (Statistics of Doom), but
I couldn't find it anywhere else, so this may indeed not be in use.
The <- however is necessary I believe to compute a model, see the example
on Lavaan page http://lavaan.ugent.be/tutorial/groups.html

HS.model <- '  visual =~ x1 + x2 + x3
              textual =~ x4 + x5 + x6
              speed   =~ x7 + x8 + x9 'fit <- cfa(HS.model,
           data = HolzingerSwineford1939,
           group = "school")summary(fit)

Is there another way to compute a model?

Best,
John.

----------------------------------------------------------------------------------------------------------------
Prof. dr. John C.J. Hoeks
Communication and Information Sciences // Faculty of Arts // University of
Groningen //
Oude Kijk in 't Jatstraat 26,9712 EK, Groningen, The Netherlands //
+31(0)50 363 7443

I support the PlantPoweredCommunity
<https://www.change.org/p/public-events-organizers-plantpoweredcommunity-plant-based-food-at-public-and-social-events?recruiter=864666387&utm_source=share_petition&utm_medium=facebook&utm_campaign=share_petition.nafta_share_post_interaction.control>
campaign
- and you? Click the link to learn more!




<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusvrij.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by vankesteren** [comment]
Hi John,

in JASP, we accept the `lavaan` syntax, the part between the quotation marks that defines the model:
```
visual  =~ x1 + x2 + x3
textual =~ x4 + x5 + x6
speed   =~ x7 + x8 + x9
```
JASP does the rest for you, provided the variable names in your dataset match those in your model. You can set a grouping variable in the options pane.

Erik-Jan
