### ISSUE TITLE
Error message in RM ANOVA "not enough 'x' observations"

### ISSUE THREAD

**Issue by jlhartnett** [jasp-stats/jasp-issues#748]
* JASP version: 0.12.0.0
 Windows
* OS name and version:
* Analysis: 
* Bug description:* I tried to run a repeated measure ANOVA. When I started to use the post-hoc menu, the attached error occurred.
* Expected behaviour: I ran a RM ANOVA + post-hocs on this data in the previous version of JASP and did not encounter this problem. 
<img width="959" alt="JASP error RM ANOVA" src="https://user-images.githubusercontent.com/65495874/82148214-ecf3d680-9820-11ea-8d8c-0a768e12f663.png">
.

#### Steps to reproduce:
1. Go to RM ANOVA/Classic menu
2. Set up Repeated measures F
2. Go to Post-Hoc menu
3. Select variable, select Effect size, select Holm

**Comment by jlhartnett** [comment]
Hi! The error isn't happening now. Never mind.

**Comment by boutinb** [comment]
Do you have an idea why the error disappears?

**Comment by ChiaHsuanL** [comment]
Is there any follow-up on this issue? I have exactly the same problem... Thanks!
