### ISSUE TITLE
Descriptive statistics in RM ANOVA: They are not displayed in the order I entered them in

### ISSUE THREAD

**Issue by jlhartnett** [jasp-stats/jasp-issues#749]
* JASP version: 0.12.0.0
 Windows
* OS name and version: 
* Analysis: 
* Bug description: I specified my Repeated Measure Cells while conducting a RM ANOVA. My descriptive statistics display the variables in the opposite order than how they were entered. They are the opposite of the order in which they were entered.
<img width="678" alt="JASP table order" src="https://user-images.githubusercontent.com/65495874/82149123-6d680680-9824-11ea-9e6a-b6faab8c2f60.png">

* Expected behaviour: In previous versions, this did not happen. The ordering for descriptive statistics mimicked the order I specified in the GUI.

**Comment by tomtomme** [comment]
@jlhartnett 
Seems fine with 0.18.2
If you disagree, feel free to reopen
