### ISSUE TITLE
Exporting images of result tables

### ISSUE THREAD

**Issue by fspors** [jasp-stats/jasp-issues#75]
JASP version: 0.8.1.1
OS name and version: Windows 7
Analysis: Repeated-measures ANOVA
- Exporting images of graphs is possible, but that doesn't work for result tables
- Copying and pasting table content works in MS Word, but not in Google docs (or Google slides), and even in MS Word, the formatting changes
- Ideally would be to save images of result tables as they appear in the JASP analysis window

**Comment by tomtomme** [comment]
@fspors 
Is this really needed? Every OS I know of can do screenshots, if the original JASP-table style is preferred.  And you can even zoom the tables to the right size with Strg+mousewheel before taking the shot. 
The screenshot even hast the advantage of being able to take a shot of multiple tables at the same time. And if you use a good screenshot-tool, there is a built in annotation tool too.

**Comment by boutinb** [comment]
And we have also the Copy Latex feature. So I think we can close this issue.

**Comment by shun2wang** [comment]
>Copying and pasting table content works in MS Word, but not in Google docs (or Google slides), and even in MS Word, the formatting changes

Paste pic to Google docs not working now so I m going to fix it:-)

**Comment by shun2wang** [comment]
Or we can open a new one to track it internally?

**Comment by shun2wang** [comment]
OK I filed a new internal issue to track it more explicitly.

**Comment by tomtomme** [comment]
You are right, copy pasting plots to Docs is broken. 
However the originaly reported bug of copy pasting tables to docs & slides is fixed for me.
