### ISSUE TITLE
Confidence intervals for Spearman and tau

### ISSUE THREAD

**Issue by TarandeepKang** [jasp-stats/jasp-issues#752]
* Enhancement: Confidence intervals for Spearman and tau
* Purpose: enable the calculation of confidence intervals for these correlation procedures. 
* Use-case: in situations with non-parametric data, it is not currently possible to computer confidence intervals in this software, but data often violate the assumptions parametric tests, and therefore nonparametric alternatives are required.  Confidence intervals give an important extra piece of information besides simple significance tests. 

**Is your feature request related to a problem? Please describe.**
 

**Describe the solution you'd like**
 
A variety of approaches are available, this paper provides a good reference: 

Bishara, A.J., Hittner, J.B. Confidence intervals for correlations when data are not normal. Behav Res 49, 294–309 (2017). https://doi.org/10.3758/s13428-016-0702-8

See the code snippets in the supplementary material of the paper, as well as here:

https://rpubs.com/seriousstats/616206.

**Comment by EJWagenmakers** [comment]
Good suggestion! See also https://seriousstats.wordpress.com/2020/05/18/cis-for-spearmans-rho-and-kendalls-tau/amp/?__twitter_impression=true

**Comment by TarandeepKang** [comment]
These methods have now been implemented in the correlation package which is part of the easystats suite. See here: https://github.com/easystats/correlation/issues/80 This might make a JASP implementation easier?

**Comment by EJWagenmakers** [comment]
Definitely. @boutinb @TimKDJ , I think this might be a good project for a student to get into the grove of things perhaps?!

**Comment by JohnnyDoorn** [comment]
Hi @TarandeepKang 
These are already in JASP right? 
See screenshot below:
![Screenshot_20200520_120709](https://user-images.githubusercontent.com/15704203/82433985-8a097600-9a92-11ea-8a56-9a5fabfb0bf5.png)

**Comment by EJWagenmakers** [comment]
Johnny, I don't see this in JASP 0.12.0, and it is also not in a recent nightly. Perhaps it is on your branch?

**Comment by TarandeepKang** [comment]
I am sorry if I've wasted everyone's time, but at the moment I agree with EJ, in that I can't find them. 

 I was looking at the help file for this analysis and it states:

" Confidence Intervals: Confidence intervals for the population correlation (only available for the Pearson correlation)."

Perhaps you have been making additional changes on your end which are not available for us to use yet?

**Comment by JohnnyDoorn** [comment]
Hahaha this is pretty weird.. because I also have it on the release version on Linux (0.12). I remember implementing this a long time ago.

**Comment by EJWagenmakers** [comment]
To clarify: What I *cannot* find is the (nice) "Condition on" box for doing partial correlations, as shown in Johnny's screenshot. Ah, the fact that it is colored means it isn't yet in a release, right? So that explains it.
What I am able to do (both in 0.12.0 and a recent nightly) is tick boxes for Spearman and Kendall, then tick a box for the 95% CI, and I do get those intervals then. TarandeepKang, do you get the intervals if you tick all these boxes?

**Comment by JohnnyDoorn** [comment]
Yes that's what I meant - the pink box means it's my own debug build, that's why I double-checked with the release version.
![Screenshot from 2020-05-20 12-32-31](https://user-images.githubusercontent.com/15704203/82436456-208b6680-9a96-11ea-9c98-cadf8edeec47.png)

**Comment by TarandeepKang** [comment]
Yes, I'm able to use the tick boxes to activate kindle and Spearman, and get associated CIs. Apologies for the confusion, I do think it would be worth updating the help file and explaining the methods used for the calculation of CIs?

**Comment by JohnnyDoorn** [comment]
Yes, excellent suggestion! If i recall correctly, we use the z-approximation for both.

**Comment by AlexanderLyNL** [comment]
The current implementation of the confidence intervals for Kendall's tau and Spearman's rho is based on a permutation method, which makes the analysis slow when n is large. The z-approximation suffices however when n is large, which will replace the exact permutation confidence intervals in the next version. @Kucharssim can you update the help file once you're done with your implementation. 

To avoid further confusion, I'll close this now. Please reopen if something's still unclear.

**Comment by JorisGoosen** [comment]
@AlexanderLyNL wouldn't it be better to only close this issue after @JohnnyDoorn or @Kucharssim updates the helpfiles?

**Comment by AlexanderLyNL** [comment]
I'll open a new issue on the help files and assign that.
