### ISSUE TITLE
Missing output

### ISSUE THREAD

**Issue by JuliusWelzel** [jasp-stats/jasp-issues#753]
* JASP version: 0.12.2

* OS name and version: Win 10 Pro 64
* Analysis: Descriptive Statistics
* Bug description: The output window stays empty, I inspected the data which seems fine.
* Expected behaviour: Table output from data

#### Steps to reproduce:
1. Go to 'Descriptive'
2. Click on 'Descriptive Statistics
[functional_190110.zip](https://github.com/jasp-stats/jasp-issues/files/4656514/functional_190110.zip)

'

**Comment by boutinb** [comment]
@JuliusWelzel JASP has some difficulties to read your SPSS file. Could you try to export it first in a csv format, and start JASP with this csv file?

**Comment by JuliusWelzel** [comment]
@boutinb Yes, thanks this does work. However, the imported data looks normal to me, just the output was not working. I was wondering why this is?

**Comment by boutinb** [comment]
I have to look further why our SPSS reader has some problems with your file. Maybe some column names... and JASP should warns you also better that there is a problem!

**Comment by JuliusWelzel** [comment]
Perfect, thanks for the quick feedback!
