### ISSUE TITLE
AVE & CR

### ISSUE THREAD

**Issue by sarahtalib** [jasp-stats/jasp-issues#754]
* Enhancement: Automatically generate AVE (Average Variance Explained) and CR (Composite Reliability) 
* Purpose: To allow the auto-generation of AVE and CR without the need to switch between JASP and different software solutions. 
* Use-case: 

**Is your feature request related to a problem? Please describe.**
 

**Describe the solution you'd like**
 

**Describe alternatives you've considered**
 

**Additional context**

**Comment by Marian-Popa** [comment]
I fully support this proposal, in conjunction with my proposal (CFA / SEM - Measurement model # 671).
The general idea is to pay explicit attention to the measurement model. It would be extremely useful for it to be diagnosed not only globally (by fit indices), but also analytically (convergent and discriminant validity). To this end, it would be very useful to calculate such indicators as:
Average Variance Extracted, Composite Reliability, Maximum Shared Variance, Average Shared Variance, or Heterotrait-Monotrait Ratio of Correlations (HTMT) (Henseler, J., Ringle, CM, & Sarstedt, M. (2015). A new criterion for assessing discriminant validity in variance-based structural equation modeling. Journal of the academy of marketing science, 43 (1), 115-135.)

Best wishes to JASP team

**Comment by boutinb** [comment]
@vankesteren Could you answer this request?

**Comment by vankesteren** [comment]
I'll keep it in mind in my SEM rework! I do have to say that I am not familiar with these metrics, and whether the best place for them is in the SEM analysis or in CFA, for example, but the paper should help.

**Comment by Marian-Popa** [comment]
Thanks for your kind attention. I am aware that it's easy for us to send proposals, but it is not so easy to implement in JASP all the metrics in the world. 
AVE, CR, MSV, ASV & HTMT are associated with the measurement model. So, they can be implemented either in the CFA module or in SEM (with latent factors). Having such metrics, the measurement model could be assessed more specifically, not only by global fit indices: ”Almost all goodness-of-fit indexes (GFIs) for latent variable structural equation models are global GFIs that simultaneously assess the fits of the measurement and structural portions of the model.” (McNeish, D., & Hancock, G. R. (2018). The effect of measurement quality on targeted structural model fit indices: A comment on Lance, Beck, Fan, and Carter (2016). Psychological Methods, 23(1), 184-190. https://doi.org/10.1037/met0000157)
All my best,
Marian
