### ISSUE TITLE
Moderation 

### ISSUE THREAD

**Issue by sarahtalib** [jasp-stats/jasp-issues#755]
* Enhancement: Incorporate moderation analysis into JASP
* Purpose: to expand the features of JASP by including moderation analysis
* Use-case:

**Is your feature request related to a problem? Please describe.**
 

**Describe the solution you'd like**
 

**Describe alternatives you've considered**
 

**Additional context**

**Comment by boutinb** [comment]
@EJWagenmakers Could you answer this request?

**Comment by EJWagenmakers** [comment]
Already included, see https://jasp-stats.org/2020/03/12/mediation-and-moderation-analysis-in-jasp/
E.J.
