### ISSUE TITLE
error cannot allocate vector of size 5.9Gb

### ISSUE THREAD

**Issue by benlee88** [jasp-stats/jasp-issues#757]
received following  error while running logistic regression 

error cannot allocate vector of size 5.9Gb
stack trace 

Pl advice how to resolve this pro
<img width="309" alt="Capture" src="https://user-images.githubusercontent.com/54931694/82640062-8580c100-9c3c-11ea-946d-e65af5c27ad8.PNG">
blem

**Comment by JorisGoosen** [comment]
Is your dataset perhaps large? 
(If it is something you can share it is practical to do so because then we can check things)

And maybe your computer doesn't have a lot of RAM? How much is it?

Also, the template for this issue asked which OS you are using, it would be rather useful to know which one you are using...

**Comment by benlee88** [comment]
Hi,

The dataset is only 794KB in size
Has 7043 rows
Attached file

Installed 8G Ram

Os – windows 10

Ben

**Comment by vandenman** [comment]
Windows 10 64 bit or 32 bit? (unfortunately, R has less memory capacity on 32 bit, no matter what hardware you have). In addition, how many predictors and interaction effects did the model contain?

**Comment by benlee88** [comment]
Hi,

Only 2  covariates and 5 factors as predictors .

See below
And[cid:image001.png@01D6305F.9AD70EE0]

Error is [cid:image002.png@01D6327D.24ED4A80]

Consistently obtained

Ben

**Comment by vandenman** [comment]
By default, JASP adds all possible interaction effects between factors. You could try to remove all higher-order factors and then see if the analysis works. To do that, go to `Model`, select the interaction effects in the box `Model Terms` and remove what you're not interested in (probably a lot of them). Below a screenshot of the `Model Terms` box.

![image](https://user-images.githubusercontent.com/21319932/82791633-67020c00-9e6e-11ea-98bf-10c10facaf1f.png)


Could you let us know if the error persists with fewer interaction effects?

**Comment by JorisGoosen** [comment]
And a small note  for Ben, if you attach images in an email response to a github issue it sadly enough does not add them to the issue, so we can't see them.

If you could add them directly add https://github.com/jasp-stats/jasp-issues/issues/757 that could be useful.
