### ISSUE TITLE
Feature request, Paired Samples T-Test: Clarify correspondence between variables and measures

### ISSUE THREAD

**Issue by JoKeyser** [jasp-stats/jasp-issues#758]
* Enhancement: The interface should state if a variable is *Measure 1* or *Measure 2*.
* Purpose: Simplify choice of *Alt. Hypothesis* for one-tailed paired t-tests, and its interpretation.

**Is your feature request related to a problem? Please describe.**  
It is visually not 100% clear what variable in *Variable pairs* corresponds to *Measure 1* and *Measure 2*.

**Describe the solution you'd like**  
1. The interface should make unambiguously clear if a variable is considered *Measure 1* or *Measure 2*.

For example, the *Variable pairs* could indicate which variable will become *Measure 1* and *Measure 2*, like this:

![jasp_paired_proposal](https://user-images.githubusercontent.com/8722846/82671938-f5dd1180-9c3f-11ea-89e6-454e50862f26.png)

2. The *Note.* sentence in the results should use the same wording as in the interface: The formulation should not talk about *measure one* and *measure two* but instead of *Measure 1* and *Measure 2* again, or even better, dynamically use the variable names themselves.

**Additional context**  
Screenshot from version 0.12.2:

![jasp_paired_example](https://user-images.githubusercontent.com/8722846/82671353-fd4feb00-9c3e-11ea-92fc-0d439f199f0d.png)

In this example, there is no unambiguous visual indication if variable *Pre* is indeed *Measure 1* or rather *Measure 2*.

**Comment by EJWagenmakers** [comment]
Completely agree! Who can do this, team?

**Comment by vandenman** [comment]
I'll implement this for both the Bayesian and frequentist paired samples T-Test

**Comment by vandenman** [comment]
A small update:

- The main table has now `Measure 1` and `Measure 2` as column titles so that it's more clear what the radio button refers to.
- The footnote now refers to `Measure 1` and `Measure 2`.
- The footnote now gives an example using the first complete pair, if there is any.

![image](https://user-images.githubusercontent.com/21319932/83947148-996c1b80-a815-11ea-94c0-57b9d1c8fb48.png)

Any thoughts/ suggestions?

**Comment by JoKeyser** [comment]
I think this is great!
