### ISSUE TITLE
Unexpected closure

### ISSUE THREAD

**Issue by Laborioso** [jasp-stats/jasp-issues#761]
* JASP version:updated april 27
MAC
* OS name and version: MAC OS Catalina 10.15.4
<img width="928" alt="Captura de Pantalla 2020-05-22 a la(s) 15 08 55" src="https://user-images.githubusercontent.com/65785653/82706610-9c74e280-9c3f-11ea-8ef9-f5c67f73f8b9.png">

* Analysis: 
* Bug description:
* Expected behaviour:

**Comment by JorisGoosen** [comment]
Could you save your jasp-file and add it here?
