### ISSUE TITLE
Mixed Modeling (Visual Modeiling [BETA])

### ISSUE THREAD

**Issue by Bobuch** [jasp-stats/jasp-issues#763]
I ran my analysis with mixed modeling. Data are formatted with multiple lines per subject as in a mixed model. I ran the analysis with ITEMS as a random effect and it worked fine. ITEMS are simply words, house, car and so on.

But when I ran SUBJECTS 1-116, I got the error:
------------------------------------
This analysis terminated unexpectedly.

Error in `[<-.data.frame`(`*tmp*`, , term.re, value = structure(list(SUB = structure(c(61L, : replacement element 1 has 3 rows, need 8

Stack trace
withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

flexplot:::mixedmod_jasp(jaspResults, dataset, options)

.mixedmod_model_plot(jaspResults, options, ready)

.create_flexplot(jaspResults, modelplot, options, model.type)

visualize(mixedmod_results, plot = 'model', alpha = options$alpha, sample = options$nsamp, jitter = c(options$jitx, options$jity))

visualize.lmerMod(mixedmod_results, plot = 'model', alpha = options$alpha, sample = options$nsamp, jitter = c(options$jitx, options$jity))

`[<-`(`*tmp*`, , term.re, value = list(SUB = c(61, 77, 106)))

`[<-.data.frame`(`*tmp*`, , term.re, value = list(SUB = c(61, 77, 106)))

stop(sprintf(ngettext(N, 'replacement element %d has %d row, need %d', 'replacement element %d has %d rows, need %d'), k, N, n), domain = NA)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

------------

**Comment by boutinb** [comment]
@Bobuch I have asked the developer of this module to answer you.

**Comment by Bobuch** [comment]
Thank you.

————————
R.R.H., Ph.D.
Regents Professor

On May 27, 2020, at 2:28 AM, bruno boutin <notifications@github.com> wrote:

﻿

CAUTION: This email originated from outside of the University. Do not click links or open attachments unless you recognize the sender and know the content is safe.



@Bobuch<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Bobuch&d=DwMCaQ&c=H5Iu-V89wgp5zRbL6y0Ptc2lgooFyRqrlrd-0IU1a1U&r=0daRvUnp1AjHsJHLJCErcw43OZHib6G-IcOjeQPaOW8&m=23cbqSP-FEy0pAgmnxhr8m05xlgs3ubNJB683x0pGfM&s=GTyxSV9mfmkaqIpqlXReIbTFAga0f6OCo6AlMzuyJaI&e=> I have asked the developer of this module to answer you.

**Comment by dustinfife** [comment]
I believe this is a known issue (see https://github.com/jasp-stats/jasp-issues/issues/728). @boutinb, is there a way we can get a patch or something? The R code works currently.

In the mean time, you can change the number of clusters to a smaller number, then it should work. I believe what's happening is that visual modeling randomly selects 3 clusters to display in separate panels. If there's fewer than 3 clusters, it will throw that error.

**Comment by boutinb** [comment]
We are planning to release a new version over ~2 weeks. For the time being, I can send you a beta version. 
@Bobuch: which OS do you use: Windows 64/Windows32/Mac/Linux?

**Comment by Bobuch** [comment]
I use MacOS Catalina.

Than you so much JJ

————————
R.R.H., Ph.D.
Regents Professor

On May 28, 2020, at 8:01 AM, bruno boutin <notifications@github.com> wrote:

﻿

CAUTION: This email originated from outside of the University. Do not click links or open attachments unless you recognize the sender and know the content is safe.



We are planning to release a new version over ~2 weeks. For the time being, I can send you a beta version.
@Bobuch<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Bobuch&d=DwMCaQ&c=H5Iu-V89wgp5zRbL6y0Ptc2lgooFyRqrlrd-0IU1a1U&r=0daRvUnp1AjHsJHLJCErcw43OZHib6G-IcOjeQPaOW8&m=g__61L6slatwVAeWPJg8Vb54_fK-sY19Uv8GHWbZk-w&s=7PPm5hq-mNwRt1k32vH14vWznglQdfAu2aEBwbZTVKQ&e=>: which OS do you use: Windows 64/Windows32/Mac/Linux?

**Comment by Bobuch** [comment]
Dear Bruno,

For the random effect, I can only do one variable, it would be great to do two variables like Subject and items.

Thanks!!

I use MacOS.

————————
R.R.H., Ph.D.
Regents Professor

On May 28, 2020, at 8:01 AM, bruno boutin <notifications@github.com> wrote:

﻿

CAUTION: This email originated from outside of the University. Do not click links or open attachments unless you recognize the sender and know the content is safe.



We are planning to release a new version over ~2 weeks. For the time being, I can send you a beta version.
@Bobuch<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Bobuch&d=DwMCaQ&c=H5Iu-V89wgp5zRbL6y0Ptc2lgooFyRqrlrd-0IU1a1U&r=0daRvUnp1AjHsJHLJCErcw43OZHib6G-IcOjeQPaOW8&m=g__61L6slatwVAeWPJg8Vb54_fK-sY19Uv8GHWbZk-w&s=7PPm5hq-mNwRt1k32vH14vWznglQdfAu2aEBwbZTVKQ&e=>: which OS do you use: Windows 64/Windows32/Mac/Linux?

**Comment by boutinb** [comment]
Can you try this version: http://static.jasp-stats.org/Nightlies/MacOS/JASP-nightly-stable-0dc621d0e59e4f7563c24cdaa13c2d5db06d5174.dmg
This is not an official version!

**Comment by Bobuch** [comment]
Yes, I will. Thank you. I’ll get back to you shortly. I’m still at home.

————————
R.R.H., Ph.D.
Regents Professor

On May 28, 2020, at 9:54 AM, bruno boutin <notifications@github.com> wrote:

﻿

CAUTION: This email originated from outside of the University. Do not click links or open attachments unless you recognize the sender and know the content is safe.



Can you try this version: http://static.jasp-stats.org/Nightlies/MacOS/JASP-nightly-stable-0dc621d0e59e4f7563c24cdaa13c2d5db06d5174.dmg<https://urldefense.proofpoint.com/v2/url?u=http-3A__static.jasp-2Dstats.org_Nightlies_MacOS_JASP-2Dnightly-2Dstable-2D0dc621d0e59e4f7563c24cdaa13c2d5db06d5174.dmg&d=DwMCaQ&c=H5Iu-V89wgp5zRbL6y0Ptc2lgooFyRqrlrd-0IU1a1U&r=0daRvUnp1AjHsJHLJCErcw43OZHib6G-IcOjeQPaOW8&m=nQU-CcYvU3jIYNV59KizTO6Y_jTjzJO_0nwY3XQOgjU&s=pakt0JcfH092Vhqpa4IbzPz2uEGXSylMhHjAFVhVInw&e=>
This is not an official version!

**Comment by Bobuch** [comment]
Dear Bruno,

I still get the same issue, and only with the subject data. It seems that it works and then I ask for another function and it gives me the error message.



On May 28, 2020, at 8:00 AM, bruno boutin <notifications@github.com<mailto:notifications@github.com>> wrote:



CAUTION: This email originated from outside of the University. Do not click links or open attachments unless you recognize the sender and know the content is safe.





We are planning to release a new version over ~2 weeks. For the time being, I can send you a beta version.
@Bobuch<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Bobuch&d=DwMCaQ&c=H5Iu-V89wgp5zRbL6y0Ptc2lgooFyRqrlrd-0IU1a1U&r=0daRvUnp1AjHsJHLJCErcw43OZHib6G-IcOjeQPaOW8&m=g__61L6slatwVAeWPJg8Vb54_fK-sY19Uv8GHWbZk-w&s=7PPm5hq-mNwRt1k32vH14vWznglQdfAu2aEBwbZTVKQ&e=>: which OS do you use: Windows 64/Windows32/Mac/Linux?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jasp-2Dstats_jasp-2Dissues_issues_763-23issuecomment-2D635334984&d=DwMCaQ&c=H5Iu-V89wgp5zRbL6y0Ptc2lgooFyRqrlrd-0IU1a1U&r=0daRvUnp1AjHsJHLJCErcw43OZHib6G-IcOjeQPaOW8&m=g__61L6slatwVAeWPJg8Vb54_fK-sY19Uv8GHWbZk-w&s=bL0lbPQyhy34H59XbDuvhhWlUc3dR2n8JiD51R59o5c&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ANQ3JJAWDG6HZVLYCPM5EO3RTZOAPANCNFSM4NJAJ7FQ&d=DwMCaQ&c=H5Iu-V89wgp5zRbL6y0Ptc2lgooFyRqrlrd-0IU1a1U&r=0daRvUnp1AjHsJHLJCErcw43OZHib6G-IcOjeQPaOW8&m=g__61L6slatwVAeWPJg8Vb54_fK-sY19Uv8GHWbZk-w&s=g-IE-XAMB1GfH-E8yX7gRs4F1Fv1e34BZe2hN2Nkvdw&e=>.


[cid:AE1855B3-BFFD-4FDD-AFDF-8E5C5A6064AA@tamiu.edu]

**Comment by Bobuch** [comment]
Dear Bruno,

I still get the same issue, and only with the subject data.



On May 28, 2020, at 8:00 AM, bruno boutin <notifications@github.com<mailto:notifications@github.com>> wrote:



CAUTION: This email originated from outside of the University. Do not click links or open attachments unless you recognize the sender and know the content is safe.





We are planning to release a new version over ~2 weeks. For the time being, I can send you a beta version.
@Bobuch<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Bobuch&d=DwMCaQ&c=H5Iu-V89wgp5zRbL6y0Ptc2lgooFyRqrlrd-0IU1a1U&r=0daRvUnp1AjHsJHLJCErcw43OZHib6G-IcOjeQPaOW8&m=g__61L6slatwVAeWPJg8Vb54_fK-sY19Uv8GHWbZk-w&s=7PPm5hq-mNwRt1k32vH14vWznglQdfAu2aEBwbZTVKQ&e=>: which OS do you use: Windows 64/Windows32/Mac/Linux?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jasp-2Dstats_jasp-2Dissues_issues_763-23issuecomment-2D635334984&d=DwMCaQ&c=H5Iu-V89wgp5zRbL6y0Ptc2lgooFyRqrlrd-0IU1a1U&r=0daRvUnp1AjHsJHLJCErcw43OZHib6G-IcOjeQPaOW8&m=g__61L6slatwVAeWPJg8Vb54_fK-sY19Uv8GHWbZk-w&s=bL0lbPQyhy34H59XbDuvhhWlUc3dR2n8JiD51R59o5c&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ANQ3JJAWDG6HZVLYCPM5EO3RTZOAPANCNFSM4NJAJ7FQ&d=DwMCaQ&c=H5Iu-V89wgp5zRbL6y0Ptc2lgooFyRqrlrd-0IU1a1U&r=0daRvUnp1AjHsJHLJCErcw43OZHib6G-IcOjeQPaOW8&m=g__61L6slatwVAeWPJg8Vb54_fK-sY19Uv8GHWbZk-w&s=g-IE-XAMB1GfH-E8yX7gRs4F1Fv1e34BZe2hN2Nkvdw&e=>.


[cid:AE1855B3-BFFD-4FDD-AFDF-8E5C5A6064AA@tamiu.edu]

**Comment by boutinb** [comment]
@dustinfife Can you reproduce this problem? If not, @Bobuch could you send us your data, and an exact reproduction path of what you are doing?
Also: @Bobuch, to answer us, please use directly GitHub, not your email. When using your email client, it sends a lot of text not related to this issue.

**Comment by dustinfife** [comment]
Also, please send a screenshot of what you're doing.

**Comment by Bobuch** [comment]
Dear Bruno,

I am including the data with the different analyses saved. When I ran the analysis with Items as random effect, it works fine. When I ran the analysis with Subject (SUB) as random effect, the analysis terminates immediately. You will see what I mean.

Thanks!

[MIXED_JASP.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/4703260/MIXED_JASP.jasp.zip)

**Comment by Bobuch** [comment]
Dear Dustinfife,

I submitted the data file and saved the output so you can see.

On May 29, 2020, at 8:05 AM, dustinfife <notifications@github.com<mailto:notifications@github.com>> wrote:



CAUTION: This email originated from outside of the University. Do not click links or open attachments unless you recognize the sender and know the content is safe.





Also, please send a screenshot of what you're doing.

**Comment by Bobuch** [comment]
Dear Bruno,

I submitted the data file and saved the output so you can see. I responded to the GitHub list with the data. The subject column (SUB) is numerical… but it should not matter since those are the subjects.

Thank you for your great work.

Roberto


On May 29, 2020, at 1:37 AM, bruno boutin <notifications@github.com<mailto:notifications@github.com>> wrote:



CAUTION: This email originated from outside of the University. Do not click links or open attachments unless you recognize the sender and know the content is safe.





@dustinfife<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dustinfife&d=DwMCaQ&c=H5Iu-V89wgp5zRbL6y0Ptc2lgooFyRqrlrd-0IU1a1U&r=0daRvUnp1AjHsJHLJCErcw43OZHib6G-IcOjeQPaOW8&m=bDu7ny242G6vkB01UQjdKERpyxqxtvVy-ByJBtlPlNE&s=D6jFhOP4quiYJ02LD7KFzJkagQXK-yAm4NcTWWkuFdo&e=> Can you reproduce this problem? If not, @Bobuch<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Bobuch&d=DwMCaQ&c=H5Iu-V89wgp5zRbL6y0Ptc2lgooFyRqrlrd-0IU1a1U&r=0daRvUnp1AjHsJHLJCErcw43OZHib6G-IcOjeQPaOW8&m=bDu7ny242G6vkB01UQjdKERpyxqxtvVy-ByJBtlPlNE&s=TnP9xMZrQCjqLVSgC-6HQXQLPmfW6g0CAMDwQGKQ0mo&e=> could you send us your data, and an exact reproduction path of what you are doing?
Also: @Bobuch<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Bobuch&d=DwMCaQ&c=H5Iu-V89wgp5zRbL6y0Ptc2lgooFyRqrlrd-0IU1a1U&r=0daRvUnp1AjHsJHLJCErcw43OZHib6G-IcOjeQPaOW8&m=bDu7ny242G6vkB01UQjdKERpyxqxtvVy-ByJBtlPlNE&s=TnP9xMZrQCjqLVSgC-6HQXQLPmfW6g0CAMDwQGKQ0mo&e=>, to answer us, please use directly GitHub, not your email. When using your email client, it sends a lot of text not related to this issue.

**Comment by dustinfife** [comment]
Here's a quick fix: if you specify that SUB is a Scale variable, it works. I'm not sure why it's having issues in the background. I'll see if I can dig in to the code and see why that's happening.

**Comment by dustinfife** [comment]
Alright, I fixed the issue. @boutinb, here's the commit: https://github.com/dustinfife/flexplot/commit/0f1d85ccb2fae40da12506840ff60a4b0d9fd8a6

**Comment by Bobuch** [comment]
Dear Dustinfife,

That means that we’ll get an updated jasp version to implement it?

R

On May 29, 2020, at 2:10 PM, dustinfife <notifications@github.com<mailto:notifications@github.com>> wrote:



CAUTION: This email originated from outside of the University. Do not click links or open attachments unless you recognize the sender and know the content is safe.





Alright, I fixed the issue. @boutinb<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_boutinb&d=DwMCaQ&c=H5Iu-V89wgp5zRbL6y0Ptc2lgooFyRqrlrd-0IU1a1U&r=0daRvUnp1AjHsJHLJCErcw43OZHib6G-IcOjeQPaOW8&m=3wLZ4nNAEFQtsAFHIixHwU6Gv2FQhwDHy-ox-3KgQZs&s=vCJ6Uc440VMvUHaQmoDYmoITSnsOgO21aQoVa5gRRxc&e=>, here's the commit: dustinfife/flexplot@0f1d85c<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dustinfife_flexplot_commit_0f1d85ccb2fae40da12506840ff60a4b0d9fd8a6&d=DwMCaQ&c=H5Iu-V89wgp5zRbL6y0Ptc2lgooFyRqrlrd-0IU1a1U&r=0daRvUnp1AjHsJHLJCErcw43OZHib6G-IcOjeQPaOW8&m=3wLZ4nNAEFQtsAFHIixHwU6Gv2FQhwDHy-ox-3KgQZs&s=NTT53C4L9i_k8v598GNUZrex8rHcCXCjLddKhN1MA8A&e=>

**Comment by boutinb** [comment]
@dustinfife Can you do a Pull Request also to jasp-stats/jasp-desktop ?

**Comment by dustinfife** [comment]
I'd be happy to. Do you mind telling me how to do that? I've done plenty of pull requests within a repository, but not across one. 

Thanks!

**Comment by boutinb** [comment]
@dustinfife If I understand your fix, what we need to do is to update the flexplot package in the R framework of JASP, not the R JASP-Flexplot interface. So you don't need to do a Pull Request.
@vandenman could you update the flexplot package in JASP?

**Comment by boutinb** [comment]
HI @Bobuch, I have testes your JASP file with the new 'development' version, and it seems to work. But maybe if, you can test it also:
https://static.jasp-stats.org/Nightlies/MacOS/JASP-nightly-stable-aa7871b0a6f4bf29e841ad9d9f360867f0973d66.dmg
A real release should come soon.

**Comment by Bobuch** [comment]
Dear Bruno,

I will test it shortly. And will let you know. Thank you.

————————
R.R.H., Ph.D.
Regents Professor

On Jun 17, 2020, at 3:54 AM, bruno boutin <notifications@github.com> wrote:

﻿

CAUTION: This email originated from outside of the University. Do not click links or open attachments unless you recognize the sender and know the content is safe.



HI @Bobuch<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Bobuch&d=DwMCaQ&c=H5Iu-V89wgp5zRbL6y0Ptc2lgooFyRqrlrd-0IU1a1U&r=0daRvUnp1AjHsJHLJCErcw43OZHib6G-IcOjeQPaOW8&m=dLMy_JUMmXbqQCUrc6XYSRfZb2_mXNBI9N-fitHMEYY&s=ietFvQvT8OA01g1FdjhOUveuxrxRW7QLiLJw3mZC5K8&e=>, I have testes your JASP file with the new 'development' version, and it seems to work. But maybe if, you can test it also:
https://static.jasp-stats.org/Nightlies/MacOS/JASP-nightly-stable-aa7871b0a6f4bf29e841ad9d9f360867f0973d66.dmg<https://urldefense.proofpoint.com/v2/url?u=https-3A__static.jasp-2Dstats.org_Nightlies_MacOS_JASP-2Dnightly-2Dstable-2Daa7871b0a6f4bf29e841ad9d9f360867f0973d66.dmg&d=DwMCaQ&c=H5Iu-V89wgp5zRbL6y0Ptc2lgooFyRqrlrd-0IU1a1U&r=0daRvUnp1AjHsJHLJCErcw43OZHib6G-IcOjeQPaOW8&m=dLMy_JUMmXbqQCUrc6XYSRfZb2_mXNBI9N-fitHMEYY&s=PRL_ZoX4RwMggAoZ8hMtj1MLjRiLvy2wXiyMmnjQm1o&e=>
A real release should come soon.

**Comment by Bobuch** [comment]
Dear Bruno,

It works beautifully!!!! I wish I could do both Item and Subject as random effects. That is so cool that it now has R!!!


R


On Jun 17, 2020, at 8:14 AM, Heredia, Roberto R <rheredia@tamiu.edu<mailto:rheredia@tamiu.edu>> wrote:

Dear Bruno,

I will test it shortly. And will let you know. Thank you.

————————
R.R.H., Ph.D.
Regents Professor

On Jun 17, 2020, at 3:54 AM, bruno boutin <notifications@github.com<mailto:notifications@github.com>> wrote:

﻿


CAUTION: This email originated from outside of the University. Do not click links or open attachments unless you recognize the sender and know the content is safe.





HI @Bobuch<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Bobuch&d=DwMCaQ&c=H5Iu-V89wgp5zRbL6y0Ptc2lgooFyRqrlrd-0IU1a1U&r=0daRvUnp1AjHsJHLJCErcw43OZHib6G-IcOjeQPaOW8&m=dLMy_JUMmXbqQCUrc6XYSRfZb2_mXNBI9N-fitHMEYY&s=ietFvQvT8OA01g1FdjhOUveuxrxRW7QLiLJw3mZC5K8&e=>, I have testes your JASP file with the new 'development' version, and it seems to work. But maybe if, you can test it also:
https://static.jasp-stats.org/Nightlies/MacOS/JASP-nightly-stable-aa7871b0a6f4bf29e841ad9d9f360867f0973d66.dmg<https://urldefense.proofpoint.com/v2/url?u=https-3A__static.jasp-2Dstats.org_Nightlies_MacOS_JASP-2Dnightly-2Dstable-2Daa7871b0a6f4bf29e841ad9d9f360867f0973d66.dmg&d=DwMCaQ&c=H5Iu-V89wgp5zRbL6y0Ptc2lgooFyRqrlrd-0IU1a1U&r=0daRvUnp1AjHsJHLJCErcw43OZHib6G-IcOjeQPaOW8&m=dLMy_JUMmXbqQCUrc6XYSRfZb2_mXNBI9N-fitHMEYY&s=PRL_ZoX4RwMggAoZ8hMtj1MLjRiLvy2wXiyMmnjQm1o&e=>
A real release should come soon.
