### ISSUE TITLE
Tjur R^2 wrongly calculated?

### ISSUE THREAD

**Issue by schloenbachia** [jasp-stats/jasp-issues#764]
* JASP version: 0.12.2
* OS name and version: Windows 10
* Analysis: during logistic regression Tjur's R^2 is shown in the model summary
* Bug description: value seemed unrealistic, very low. I calculated with R and got a much more reasonable value
* Expected behaviour: see below

#### Steps to reproduce:
If you import the attached data into JASP and perform a logistic regression the Tjur R^2 is evaluated as 0.081, compared to a value of 0.5318 which I figured in R. The higher value is much more realistic, given 1. the scatterplot and 2. the other pseudo measures.

>>> In case attachment didn't work: Here's the data (some made up treatment data for logistic regression):

"","Dosis","Wirkung"
"1",0.59,1
"2",0.01,0
"3",0.29,0
"4",0.28,0
"5",0.81,1
"6",0.26,1
"7",0.72,1
"8",0.91,1
"9",0.95,1
"10",0.07,0
"11",0.75,1
"12",0.29,0
"13",0.1,0
"14",0.95,1
"15",0.42,1
"16",0.46,0
"17",0.97,1
"18",0.58,0
"19",0.96,1
"20",0.76,1
"21",0.71,1
"22",1,1
"23",0.51,0
"24",0.49,1
"25",0.65,1
"26",0.83,1
"27",0.48,0
"28",0.84,1
"29",0.51,0
"30",0.53,0

**Comment by Kucharssim** [comment]
Dear @schloenbachia,

thank you for the report, this is indeed a bug, the Tjur R^2 for your data is indeed 0.532. This will be fixed.

**Comment by schloenbachia** [comment]
Great, thanks!
