### ISSUE TITLE
Allow to copy version info from the About dialog

### ISSUE THREAD

**Issue by donovaly** [jasp-stats/jasp-issues#766]
The About dialog of JASP does not allow to copy any info from there. But to report bugs, in discussions in forums etc. one needs the info about the version of JASP one is currently using.

Therefore it would be helpful to have a buttoon in the About dialog that coies all relevant info to the clipboard so that one can easily paste it elsewhere.

Here is an example how the OpenSource software "FreeCAD" solved this:
![FreeCAD_Hkg9Z2vjvj](https://user-images.githubusercontent.com/1828501/82964011-99258200-9fc4-11ea-8fdf-6e5e482a2db8.png)

so I request such a button in JASP's About dialog.

**Comment by juliuspf** [comment]
@donovaly thanks for opening this issue, and I apologise for the late reply. What you report makes a lot of sense. Hopefully, we can fix this soon :)

**Comment by tomtomme** [comment]
@donovaly 
You can copy the Citation now, and that contains the version. 

However OS, date, build number etc. would also be useful and can still not be copied.

**Comment by tomtomme** [comment]
@donovaly 
This is now in progress: https://github.com/jasp-stats/jasp-desktop/pull/5430
:D
