### ISSUE TITLE
Descriptive plots

### ISSUE THREAD

**Issue by psych123** [jasp-stats/jasp-issues#767]
* JASP version: 0.12.2
* OS name and version: MacOS Catalina version 10.15.4
* Analysis: Bayesian two-way ANOVA
* Bug description: Error in if (xr[2] - xr[1] > 1000) {: missing value where TRUE/FALSE needed

I am currently trying to create a descriptive plot of the effect of two categorical variables on a continuous variable in a Bayesian ANOVA. I am aware that there is data missing for one combination of levels in my two variables so I believe that is why I am getting an error message. However, I have been able to do this in the past and was wondering if there is a way around it?

Thanks!

**Comment by JohnnyDoorn** [comment]
@vandenman I thought we had some check for this, do you know if this will be different in the next release? Else I can add something to the errorchecking function, as these situations are causing some confusion from time to time for users.

**Comment by tomtomme** [comment]
@psych123 
I tested this with 0.18.2 and it worked fine on linux. I guess MacOS will be fine too. If not, feel free to reopen!
