### ISSUE TITLE
Error making scatterplot

### ISSUE THREAD

**Issue by jaspforstats** [jasp-stats/jasp-issues#768]
* JASP version: 0.9.2

* OS name and version: Mac Os Sierra version 10.12.6
* Analysis: 
* Bug description: This analysis terminated unexpectedly.

Error in getAxisBreaks.ggplot_built(ggplot2::ggplot_build(x)): attempt to apply non-function

Stack trace
analysis(jaspResults = jaspResults, dataset = dataset, options = options, state = oldState)

.descriptivesMatrixPlot(dataset.factors, options, 'Correlation plot')

JASPgraphs::getAxisBreaks(plotMat[[row, row]])

getAxisBreaks.gg(plotMat[[row, row]])

getAxisBreaks.ggplot_built(ggplot2::ggplot_build(x))
* Expected behaviour:

**Comment by boutinb** [comment]
Hi @jaspforstats: you have to give us a reproduction path of this problem: which data, which analysis, which steps do you do in the analysis (which variables you select, which checkboxes you click, etc...). Without that we cannot know where the problem occurs.
