### ISSUE TITLE
Jasp 0.12.2 doesn't display results

### ISSUE THREAD

**Issue by RuneZO** [jasp-stats/jasp-issues#769]
* JASP version: 0.12.2

* OS name and version: Windows
* Analysis: any
* Bug description: The display window is empty no matter what I try to analyze. the only time something is visible at that window is if I copy an analysis, then it is written "copy of..."
* Expected behaviour: graphs and tables as I got before I updated to the latest version

**Comment by boutinb** [comment]
Hi @RuneZO Just to be sure: can you already see the loaded data, or the ribbon bar at the TOP of JASP (with the names of the analyses)? Or is it only the result of the analysis you don't see?

**Comment by RuneZO** [comment]
I have loaded data and can see them in Jasp. I can also see the ribbon bar with Descriptives, T-test...

**Comment by RuneZO** [comment]
I also tried "repair" app, but no difference.

**Comment by boutinb** [comment]
So if I understand well, it is the results of an analysis you cannot see.
Could you try the following:
. go to Menu/Preferences/Interface
. Click on the 'Safe Graphics Mode'
. Restart JASP

**Comment by RuneZO** [comment]
I tried that now, but get the same result

**Comment by RuneZO** [comment]
I just opened another dataset that is almost identical and Jasp gave me the results. I re-opened the first file again and still the same problem. I then went back to SPSS (where the file was from) and saved the first file again. When I now opened it in Jasp all works as it should.

I do not know why, but all is now functioning.

**Comment by boutinb** [comment]
Strange... If this problem occurs again, re-open this issue.
