### ISSUE TITLE
column/variable order csv/jasp

### ISSUE THREAD

**Issue by vdsmagt** [jasp-stats/jasp-issues#77]
## Environment (for bugs)

* JASP version: 0.8.1.2
* OS name and version: Mac OS 10.12.6
* Analysis:
After elaborating a .csv file (opened through Jasp), and adding multiple columns (not in systematic order, and changing the order several times), the column order in the JASP data viewer, AND in the variable list when starting/changing analyses is messed up. Some variables appear at the end of the list (right hand side of the column view, while in the .csv they are right in the middle). This does not affect analyses or output as far as I can see, but it makes large data-files more complicated to handle and more error prone.
Deleting and reinserting the column (or several columns) does not fix the problem. Also, deleting the original csv, have JASP recreate the csv (with the column now near the end of the .csv file) and then moving the column to the right location in the .csv does not change the column position in JASP. It might just be a specific of this column, but it beats me what...
[jasp-and-csv.zip](https://github.com/jasp-stats/jasp-desktop/files/1233796/jasp-and-csv.zip)

In the example file attached there alldrift R C is column 37 in the CSV file, but column/variable 77 in JASP.

**Comment by Statham-jasper** [comment]
Also encountered this problem after editing column headings in the .csv (in Excel) then saving. Many of the early headings are now at the end of the document. Seems to be no order to the way it has assigned the headings (e.g. it is not in the order I edited the heading titles, nor is it alphabetical as the headings are Q1:..., Q2.... etc). As per vdsmagt, doesn't affect analysis, but very frustrating finding a column from a large dataset. I am guessing the feature to change column orders wasn't added (I have the latest release and can't find a way to do this).
Thanks

**Comment by EJWagenmakers** [comment]
Ah yes, changing column order, that would be very nice! 
@JorisGoosen , what do you think?

**Comment by JorisGoosen** [comment]
Well, in this scenario, wouldn't it make more sense to have the column order in JASP always reflect the order in the data-file? 

As in, right now whenever a column heading changes JASP just moves it entirely to the back. Even if it knows which column it used to be.

**Comment by vdsmagt** [comment]
I would vote for this, yet in my original post that was not what happend.

**Comment by Statham-jasper** [comment]
Similar for me also, editing the column heading did not necessarily move it to the back (.csv was saved after the edit). But agree, if JASP simply reflected the order in the .csv this would solve the issue as it is very easy to edit there.

**Comment by tomtomme** [comment]
@vdsmagt 
Changing column order in JASP is now possible in the variable editor.
However, if you synchronize to an external CSV and make changes to the column order in the CSV, those changes in order are still not reflected / synchronized with JASPs data viewer.

**Comment by tomtomme** [comment]
@vdsmagt 
with current 0.19 beta changes in column order in CSVs and ODS files are now reflected in JASP. 
But only if you do not incorporate computed columns. 
So the options right now are
a) either use JASP to compute vars and then also edit data only in JASP
b) use Excel / LibreOffice to compute vars and edit data

Is this sufficient?

In short: Do not mix editors. You can try, but this may lead to crashes and other strange behaviour. 

@JorisGoosen: Maybe we should even enforce this and disable data editing & computing in JASP when synced to an external file.

**Comment by JorisGoosen** [comment]
Data editing already disables synching and computed columns are created especially to work together with synchronized data, so that doesnt need to be turned off.

However, this is about moving columns around? Thats doable by copy pasting no?

**Comment by tomtomme** [comment]
yes, copy pasting / moving columns in CSV or ODS is now reflected in JASP - but only until computed columns are added.
Also moving columns directly in JASP is now possible via copy pasting.

**Comment by JorisGoosen** [comment]
> only until computed columns are added

Aaah, that sounds like a bug actually

**Comment by tomtomme** [comment]
I will make a separate report then!
