### ISSUE TITLE
JASP crashed

### ISSUE THREAD

**Issue by jdebeer2005** [jasp-stats/jasp-issues#770]
* JASP version: 0.12.2
* OS name and version: Windows 10 Version 1909

* Analysis: 
* Bug description:
* Expected behaviour:

#### Steps to reproduce:

-----------------------------------------------------------------------

### Debug information:
**Engine # 0** process *crashed* and it's state is *resuming*.
**Engine # 1** process *crashed* and it's state is *resuming*.
**Engine # 2** process *crashed* and it's state is *resuming*.
**Engine # 3** process *does not exist (anymore)* and it's state is *moduleRequest*.

[Commit used](https://github.com/jasp-stats/jasp-desktop/commit/eca7e082cdfa0ebf7c375a739ce6ad37fa4a4775)

**Comment by boutinb** [comment]
Hi @jdebeer2005 When does this crash occur? When JASP just start, or when you load a dataset? Did you try with an older version of JASP?

**Comment by jdebeer2005** [comment]
This crash occurred at shutdown, OF MY COMPUTER.  I think this is a se;lf inflicted wound.  I would not know how to repeat it.   I had several programs operating, and tried to shutdown, and suddenly a popup message opened up and asked me if I wanted to report it to github.  I am a member so it it.  That is all I know.

Sorry for the bother.

JDB

**Comment by AlexanderLyNL** [comment]
I consider this issues solved then. Please reopen if it reoccurs.
