### ISSUE TITLE
JASP crashes when loading .csv data file 

### ISSUE THREAD

**Issue by giulia-mr** [jasp-stats/jasp-issues#771]
* JASP version: 0.12.2.0
Windows
* OS name and version: 8, 64-bit
* Bug description: I installed JASP yesterday and every time I try to load any .csv data file, it crashes. In another forum I found that this might have to do with insufficient storage space and made some space. There is now 19,4 GB free storage space on my computer but it still crashes. Could you help me with that please?

**Comment by boutinb** [comment]
Hu @giulia-mr Can you try to load a simple csv file like the one in the Data Library/Descriptives/Fear of Statistics?

**Comment by giulia-mr** [comment]
Thank you for your quick reply. I don't know how to find this fear of statistics data file? The file I tried to upload is a very simple csv file though

**Comment by boutinb** [comment]
If you select the Open menu, then you have the Data Library sub menu as last item (Recent Files, Computer, OSF & Data Library submenus). Hier you should see some folders: Books, 1. Descriptives, 2. T-Tests, etc.., and in the Descriptives folder, you have the 'Fear of Statistics' example.

**Comment by giulia-mr** [comment]
Thank you, I try to load this file but JASP crashes as well.

**Comment by giulia-mr** [comment]
I have uninstalled JASP and downloaded an older version now. With this version it works! Thank you anyways.

**Comment by boutinb** [comment]
But it is for us really important to understand why the current version of JASP does not work on your machine.
You can have 2 versions of JASP by downloading the ZIP file instead of the JASP installer (msi file). Could you download it: http://static.jasp-stats.org/JASP-0.12.2-win64.zip and unpack it. In this way, you can still work with the older version.
With the unzipped version, can you open JASP, go to the menu Preferences/Advanced, and click on 'Log to file'. Then open a file that makes JASP crashing. Restart JASP, and in the menu Preferences/Advanced, click the button 'Show logs'. Could you then send me the files you there?
Thank you really much.

**Comment by giulia-mr** [comment]
I understand! I tried to open JASP from the unzipped version, but then a message pops up saying that Windows SmartScreen prevents the execution of the program as it is a potential risk. There is no option to ignore this message. Any ideas?

**Comment by JorisGoosen** [comment]
You can click "More info" and then it will give you the option to run it anyway.

**Comment by giulia-mr** [comment]
Thanks. When I opened JASP as instructed by you, it strangely didn't crash now. I attached the log files anyways. 


[JASP 2020-06-05 22_43_55 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/4738412/JASP.2020-06-05.22_43_55.Desktop.log)
[JASP 2020-06-05 22_43_55 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/4738413/JASP.2020-06-05.22_43_55.Engine.0.log)
[JASP 2020-06-05 22_43_55 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/4738414/JASP.2020-06-05.22_43_55.Engine.1.log)
[JASP 2020-06-05 22_43_55 Engine 2.log](https://github.com/jasp-stats/jasp-issues/files/4738415/JASP.2020-06-05.22_43_55.Engine.2.log)
[JASP 2020-06-05 22_43_55 Engine 3.log](https://github.com/jasp-stats/jasp-issues/files/4738416/JASP.2020-06-05.22_43_55.Engine.3.log)
[JASP 2020-06-05 22_41_21 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/4738417/JASP.2020-06-05.22_41_21.Engine.0.log)
[JASP 2020-06-05 22_41_21 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/4738418/JASP.2020-06-05.22_41_21.Engine.1.log)
[JASP 2020-06-05 22_41_21 Engine 2.log](https://github.com/jasp-stats/jasp-issues/files/4738419/JASP.2020-06-05.22_41_21.Engine.2.log)








[JASP 2020-06-05 22_41_30 Engine 3.log](https://github.com/jasp-stats/jasp-issues/files/4738406/JASP.2020-06-05.22_41_30.Engine.3.log)
[JASP 2020-06-05 22_43_48 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/4738407/JASP.2020-06-05.22_43_48.Desktop.log)
[JASP 2020-06-05 22_43_48 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/4738408/JASP.2020-06-05.22_43_48.Engine.0.log)
[JASP 2020-06-05 22_43_48 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/4738409/JASP.2020-06-05.22_43_48.Engine.1.log)
[JASP 2020-06-05 22_43_48 Engine 2.log](https://github.com/jasp-stats/jasp-issues/files/4738410/JASP.2020-06-05.22_43_48.Engine.2.log)
[JASP 2020-06-05 22_43_48 Engine 3.log](https://github.com/jasp-stats/jasp-issues/files/4738411/JASP.2020-06-05.22_43_48.Engine.3.log)



[JASP 2020-06-05 22_41_30 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/4738404/JASP.2020-06-05.22_41_30.Engine.1.log)
[JASP 2020-06-05 22_41_30 Engine 2.log](https://github.com/jasp-stats/jasp-issues/files/4738405/JASP.2020-06-05.22_41_30.Engine.2.log)


[JASP 2020-06-05 22_41_21 Engine 3.log](https://github.com/jasp-stats/jasp-issues/files/4738401/JASP.2020-06-05.22_41_21.Engine.3.log)
[JASP 2020-06-05 22_41_30 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/4738402/JASP.2020-06-05.22_41_30.Desktop.log)
[JASP 2020-06-05 22_41_30 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/4738403/JASP.2020-06-05.22_41_30.Engine.0.log)

**Comment by JorisGoosen** [comment]
Thank you for trying it out and attaching the logs.

But of course, if it does not crash... Well, then there is no problem apparently?
Are you sure you used the latest version?

**Comment by giulia-mr** [comment]
Yes, I am sure this was the latest version. I have no idea, why it works now. I have been using the older version for the past week. Thank you anyways! I'll let you know when any other problems come up

**Comment by JorisGoosen** [comment]
Ok, well it seems that this issue can be marked closed then, if the problem returns we can reopen it!
