### ISSUE TITLE
Improved Text scaling

### ISSUE THREAD

**Issue by RuneZO** [jasp-stats/jasp-issues#772]
* Enhancement: As of now (version 0.12.2) the types are too big for my use on a laptop, and I would like to scale them down. I can do so by CTRL -, but then the text is not smooth anymore and becomes hard to read. The same happens if I scale it up (CTRL +)
* Purpose: improved visibility
![pic normal sice of text](https://user-images.githubusercontent.com/66037123/83119090-91063900-a0cf-11ea-8334-bf2406c041e9.JPG)
![pic 70% sice of text](https://user-images.githubusercontent.com/66037123/83119105-96fc1a00-a0cf-11ea-9c90-a1e1064448f9.JPG)
![pic 130% sice of text](https://user-images.githubusercontent.com/66037123/83119130-9d8a9180-a0cf-11ea-88d8-38e6de42668a.JPG)

**Comment by RuneZO** [comment]
The three pictures enclosed in the last post are
1. Normal size: The text font is smooth
2. 70% of the original size: The text font is hard to read
3. 130% of the original size: The text form is not nice, but ok to read

**Comment by RuneZO** [comment]
I forgot to mention that the text in the Result window is scaled in a perfect way at the same time as the text at the tab, the data, and the analysis windows are hard to read. See picture 
![pic difference](https://user-images.githubusercontent.com/66037123/83133662-7f2e9100-a0e3-11ea-9ce2-d804d3e2c8b0.JPG)

**Comment by boutinb** [comment]
We know about this problem. Could you download this version of JASP: http://static.jasp-stats.org/JASP-0.12.2-64bit.msi ?

**Comment by RuneZO** [comment]
Great. That updated version solved the problem perfectly

**Comment by boutinb** [comment]
Nice!
