### ISSUE TITLE
App does not display correctly (looks black)

### ISSUE THREAD

**Issue by el-librero1800** [jasp-stats/jasp-issues#775]
I am trying to run JASP 0.12.2 and I am using Kubuntu 20.04. I installed it using flatpak but each time I open JASP it looks almost all black. Most of the screen is black with some parts of green, white and blue (the colours used in JASP, see the picture). It is completely unusable. I would really appreciate if someone could figure out how to solve this issue.
![Screenshot_20200528_130637](https://user-images.githubusercontent.com/38179143/83177351-80ac8900-a0e4-11ea-8f7e-932999680ac2.png)

**Comment by JorisGoosen** [comment]
Wow, that looks very unusable indeed!

Could you tell me which version of flatpak you have? `flatpak --version` in a terminal should tell you.
And which GPU? (If you have `mesa-utils` installed you could run `glxinfo` in a terminal.

Furthermore, having a log of this would be useful, maybe you could start jasp in a terminal and copy the output here?

**Comment by el-librero1800** [comment]
Thanks a lot for your reply JorisGoosen. I am using flatpak v1.6.3, and I have an integrated GPU (Core i7 1068NG7) Intel Iris Plus Graphics G7. I am also uploading the results from the glxinfo command and the log from running JASP. I have not pasted these in here because is quite long in both cases.

Any help is really appreciated!

[glxinfo.txt](https://github.com/jasp-stats/jasp-issues/files/4717834/glxinfo.txt)
[jasp log.txt](https://github.com/jasp-stats/jasp-issues/files/4717835/jasp.log.txt)

**Comment by JorisGoosen** [comment]
Thanks you for attaching them as files instead of pastes!

So, maybe this already helps, wouldn't know, but your flatpak is a little bit out of date and you can use the ppa of the flatpak main author to get up to date: https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak

If that does not help then maybe you can try to start JASP in software rendering mode: `flatpak run org.jaspstats.JASP --safeGraphics`

**Comment by el-librero1800** [comment]
I could not update flatpack because the repository does not have a release file and apt asked me to change the configuration in order to use it. I have to find out how to do it because I don't know... But running JASP the way you told me (software rendering mode) worked perfectly. Thanks a lot!!

**Comment by JorisGoosen** [comment]
Good that that helped!

Enjoy JASP
