### ISSUE TITLE
JASP crashes on exit

### ISSUE THREAD

**Issue by drbenvincent** [jasp-stats/jasp-issues#777]
* JASP version: 0.12.2
* OS name and version: MacOS 10.15.5
* Analysis: happens closing any JASP file as far as I can tell. 
* Bug description: JASP crashes on closing (any JASP file?). Eg.
![Screenshot 2020-06-01 at 10 55 43](https://user-images.githubusercontent.com/6765047/83398204-d17af500-a3f6-11ea-9648-73edb3edad28.png)
Does not crash when there is no data loaded, ie opening JASP then immediately closing it.

**Comment by boutinb** [comment]
This problem is probably solved with the next version (release soon). Could you try this version: http://static.jasp-stats.org/Nightlies/MacOS/JASP-nightly-stable-2a00fceaabd0e5b6ffbfd247c9095537f517e201.dmg
This is not the official version yet, but should contain the fix that solves your problem.

**Comment by drbenvincent** [comment]
That seems to work - the GUI also feels a bit smoother and more responsive

**Comment by boutinb** [comment]
Nice, thanks!
