### ISSUE TITLE
Effect size statistics for large data sets

### ISSUE THREAD

**Issue by jdebeer2005** [jasp-stats/jasp-issues#778]
* Enhancement: Add Cohens d, Glass's delta or Hedges' g to the post hoc tests in ANOVA
* Purpose:  Cohens d, Glass's delta or Hedges' g are much clearer to interpret and report than eta squared.
* Use-case:  I have a 25,000 obs data set with many ANOVA cells, that need to be compared to each other .  the t-value and Scheffe are off the chart BUT that may only be a product of the large sample size per cell.  I ended up learning about Cohens d, Glass's delta or Hedges' g, and they were VERY helpful to interpret the data.

**Is your feature request related to a problem? Please describe.**
   NO

**Describe the solution you'd like**
 
Add Cohens d, Glass's delta or Hedges' g to the post hoc table

**Describe alternatives you've considered**
 
Did the calculations by hand

**Additional context**

I cannot share my paper publicly but can share portions with the JASP team upon request.
I had to do about a 100 calculations, simple enough, once the formula is developed

John DeBeer

**Comment by JohnnyDoorn** [comment]
Hi @jdebeer2005,

For post hoc tests conducted for main effects, there is a checkbox in the post hoc analysis menu "effect size", which adds the Cohen's d to the post hoc table. I am not sure anymore why this is not the case for post hoc tests for interaction effects, but I will look into this!

Cheers,
Johnny

**Comment by JohnnyDoorn** [comment]
Hi @jdebeer2005,

Under Post Hoc Tests, there is the checkbox, see the screenshot below:
![Screenshot from 2020-06-02 20-48-43](https://user-images.githubusercontent.com/15704203/83557843-a2f23c80-a512-11ea-923a-2c1097b9c601.png)

Kind regards
Johnny

**Comment by jdebeer2005** [comment]
Thank you sir.  I see it now.  And will use it.

 

Regards

 

JDB
