### ISSUE TITLE
chol.default(mat): the leading minor of order x is not positive definite

### ISSUE THREAD

**Issue by Andreea-Szoke** [jasp-stats/jasp-issues#779]
Hello! This is the error.. "chol.default(mat): the leading minor of order x is not positive definite"
JASP Version 0.11.1, Windows 8.1 Pro
Analysis: Multivariate logistic regression
I don't know how to fix the problem...
Any help, please?

**Comment by vandenman** [comment]
Hi, the latest version is JASP 0.12.2. Can you tell us if the problem persists with that version? You can download it from https://jasp-stats.org/download/.

**Comment by vandenman** [comment]
Unfortunately, attachments aren't uploaded if you reply by email. Could you upload it again using the GitHub's website?

**Comment by Andreea-Szoke** [comment]
Hi, here it is! I hope that now it will work.
[regresie reflux.xlsx](https://github.com/jasp-stats/jasp-issues/files/4721974/regresie.reflux.xlsx)

**Comment by vandenman** [comment]
Thanks! Just to clarify, the error you get looks something like the screenshot below?

![image](https://user-images.githubusercontent.com/21319932/83616326-fbafec80-a587-11ea-8ca2-efcc26609870.png)

**Comment by Andreea-Szoke** [comment]
Yes, exactly. And this happen with all the columns, not only with one parameter.

**Comment by vandenman** [comment]
Okay, so I think (but correct me if I'm wrong) you're interested in the model with all variables and perhaps a small number of interactions. However, if you add the variables to `Factors` then by default JASP adds all possible interaction effects between the variables. If you add the categorical predictors to `Factors` in groups of 2, and then under `Model` remove all the interaction effects the analysis runs for me (see below).

![output](https://user-images.githubusercontent.com/21319932/83622725-ab895800-a590-11ea-8cae-d9bab836026e.gif)

If you repeat this for all variables and add the dependent variable last the analysis works on my machine.

Let me know if that helps!

**Comment by Andreea-Szoke** [comment]
I wanted to introduce all the variables with p<=0.25 in the univariate analysis. I tried this method and it works for me too!

Thank you a lot for your support! Have a nice day!

**Comment by vandenman** [comment]
Happy to help!
