### ISSUE TITLE
Enhancement request: changing figures

### ISSUE THREAD

**Issue by kevinvschie** [jasp-stats/jasp-issues#78]
## Environment (for enhancement requests)
 
* Enhancement: being able to change elements of figures, such as the name of the y-axis (specifically when performing a RM BANOVA), or to change the location of the legend, change the indicators, change the length of the y-axis, change colors to own preferences etc. Also, it would be great if somewhere the numbers for the 95% credible interval could be displayed (reviewers want to see these).
* Purpose: more freedom in creating figures. Also, it seems to be more economical in space if a legend could be placed below a figure instead of on the right next to a figure.

**Comment by Ema51** [comment]
It would be really useful to be able to adjust dimension and dpi with precision before saving the pictures. Because I found really difficult to adjust the images after copying from JASP without losing quality or making a mess with the x and y axis written part

**Comment by MCube78** [comment]
On the same topic, sorry, I know this might not be high on the priority, but would it be possible not to have red and green as the first two colors populating the violin plots? ..for all those colorblind, but still JASP-worthy potential users..

**Comment by jandrushko** [comment]
I would like to see further improvements with the figure/plot editing within JASP. It would be good to have color options, changing axis ranges, titles, even changing plot types would be good

**Comment by juliuspfadt** [comment]
I think this is mostly solved with the current plot editing features
