### ISSUE TITLE
broken output, missing font TeXGyreHeros in flatpak

### ISSUE THREAD

**Issue by lindemann09** [jasp-stats/jasp-issues#780]
EDIT: Solution thanks to @JoKeyser:
`flatpak run --command=fc-cache org.jaspstats.JASP -f -v`

------------------------
Original issue:
JASP is not anymore usable under Ubuntu Linux. That is really a pity.  

Why is JASP not providing older versions of flatpaks or deb-packages (as for Win & MacOS) to ensure that updates do not break the system?

* JASP version: 0.11 and 0.12.2

* OS name and version: Ubuntu 20.04 LTS, XFCE,  flatpak,
 flatpak info
```
JASP - Standard statistical analyses, both classical and Bayesian

          ID: org.jaspstats.JASP
         Ref: app/org.jaspstats.JASP/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 0.12.2
     License: AGPL-3.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 815,3 MB
     Runtime: org.kde.Platform/x86_64/5.12
         Sdk: org.kde.Sdk/x86_64/5.12

      Commit: 6a0ccb20f6676c9ba886185de1c45a2dc97f87b6448c1fb817a3e05ba2fd9900
      Parent: 4d70008e68734a64cff6b6137ba6da65762bf23140b5565c4b33b0b98c6bb6e7
     Subject: Small addition to last release (24a8b8aa)
        Date: 2020-04-24 11:39:36 +0000
```
* Analysis: 
* Bug description:
Output in figures is broken. For any analysis. For example: Kitchen roll example. Load analysis, switch off prior & posterior plot and switch plots on again to redraw figure, see output figure:

![screenshot](https://raw.githubusercontent.com/lindemann09/cogpsy.eu/master/img/Screenshot_2020-06-02_20-33-59.png)

* ERROR LOG:
```


(process:10): Pango-WARNING **: 19:44:17.056: failed to create cairo scaled font, expect ugly output. the offending font is 'TeXGyreHeros 39.84375'
(process:10): Pango-WARNING **: 19:44:17.057: font_face status is: file not found
(process:10): Pango-WARNING **: 19:44:17.057: scaled_font status is: file not found
(process:10): Pango-WARNING **: 19:44:17.057: shaping failure, expect ugly output. shape-engine='PangoFcShapeEngine', font='TeXGyreHeros 39.84375', text='M'
(process:10): Pango-WARNING **: 19:44:17.074: failed to create cairo scaled font, expect ugly output. the offending font is 'TeXGyreHeros 47.8125'
(process:10): Pango-WARNING **: 19:44:17.074: font_face status is: file not found
(process:10): Pango-WARNING **: 19:44:17.074: scaled_font status is: file not found
(process:10): Pango-WARNING **: 19:44:17.074: shaping failure, expect ugly output. shape-engine='PangoFcShapeEngine', font='TeXGyreHeros 47.8125', text='M'
(process:10): Pango-WARNING **: 19:44:17.118: failed to create cairo scaled font, expect ugly output. the offending font is 'TeXGyreHeros 39.6767578125'
(process:10): Pango-WARNING **: 19:44:17.118: font_face status is: file not found
(process:10): Pango-WARNING **: 19:44:17.118: scaled_font status is: file not found
(process:10): Pango-WARNING **: 19:44:17.118: shaping failure, expect ugly output. shape-engine='PangoFcShapeEngine', font='TeXGyreHeros 39.6767578125', text='M'
(process:10): Pango-WARNING **: 19:44:17.120: failed to create cairo scaled font, expect ugly output. the offending font is 'TeXGyreHeros 27.7734375'
(process:10): Pango-WARNING **: 19:44:17.120: font_face status is: file not found
(process:10): Pango-WARNING **: 19:44:17.120: scaled_font status is: file not found
(process:10): Pango-WARNING **: 19:44:17.120: shaping failure, expect ugly output. shape-engine='PangoFcShapeEngine', font='TeXGyreHeros 27.7734375', text='+'
(process:10): Pango-WARNING **: 19:44:17.142: failed to create cairo scaled font, expect ugly output. the offending font is 'TeXGyreHeros 34.009765625'
(process:10): Pango-WARNING **: 19:44:17.142: font_face status is: file not found
(process:10): Pango-WARNING **: 19:44:17.142: scaled_font status is: file not found
(process:10): Pango-WARNING **: 19:44:17.142: shaping failure, expect ugly output. shape-engine='PangoFcShapeEngine', font='TeXGyreHeros 34.009765625', text='data | H0'

```

* Expected behaviour:

**Comment by JorisGoosen** [comment]
Thank you for reporting this bug!

We do not make deb-pkgs anymore because it was very painful to support ubuntu/debian's sometimes very outdated Qt libraries or divergent R versions. With flatpak this is not supposed to be problem.

And in fact, I would have expected all fonts to be part of the flatpak in fact. So how it can be missing is a bit of a mystery to me. But Im sure we can figure out what went wrong here.

@JohnnyDoorn didn't you have a problem like this as well? It seems to be the same font in fact.

**Comment by JorisGoosen** [comment]
@vandenman do we specify which font to use specifically in ggplot2?

And you use ubuntu as well right? Do you have this problem as well?
And @JohnnyDoorn did you have this problem on PopOs or Manjaro?

**Comment by vandenman** [comment]
We do not specify the font, so it should resort to the system default for R (this differs between Linux, macOS, and Windows). However, multiple people seem to be having this issue recently so something is going wrong. I don't have this issue on Kubuntu 18.04 though.

**Comment by JorisGoosen** [comment]
So the problem could be that it is defaulting to system default `TexGyre` but because it is flatpak it doesn't have access to that? Because it runs in a sandbox?

Would it be hard to bundle one such font and specify it as default?

**Comment by vandenman** [comment]
> Would it be hard to bundle one such font and specify it as default?

Specifying custom fonts is incredibly painful on Windows and macOS. On Linux, it's more doable though. We could also see if `https://github.com/r-lib/ragg/` makes that easier. Regardless, I unfortunately don't have a reproduction path for this. Maybe Johnny can help out with that.

**Comment by lindemann09** [comment]
> We do not make deb-pkgs anymore because it was very painful to support ubuntu/debian's sometimes very outdated Qt libraries or divergent R versions. With flatpak this is not supposed to be problem.

That makes sense. Thanks for your prompt reply.

> I don't have this issue on Kubuntu 18.04 though.

I have the issue only on Xubuntu 20.04 and didn't experience this problems with (X)Ubuntu 18.04.

**Comment by JorisGoosen** [comment]
Ok, I will install these in some VMs and see if I can reproduce it. Maybe they just changed the default font to something and that is all. Hopefully.

**Comment by JohnnyDoorn** [comment]
Yes, that was that problem we encountered a while ago on my Pop os, I tried to install that TexGyre library manually (it told me it was already installed though), but that did not help. I still have the issue on my stable flatpak build (broken text in plots).

**Comment by JorisGoosen** [comment]
Which version of pop are you using?

**Comment by JohnnyDoorn** [comment]
20.04 (LTS)

**Comment by JorisGoosen** [comment]
Ah ok, so that means it probably is broken on many Ubuntu(-derived) 20.04 distro's...

**Comment by JorisGoosen** [comment]
Aah, so I do not get the problem with the regular ubuntu 20.04.
So next up is Xubuntu 20.04.

**Comment by JorisGoosen** [comment]
Ok, so I've installed xubuntu and there the font and plots look fine as well...

@JohnnyDoorn and @lindemann09 do you maybe have latex or other tex stuff installed?
Because possibly that overwrites the default font used by ggplot?
Or maybe you also have copy of R?

Are either of you using a non-default system theme/font?

**Comment by JohnnyDoorn** [comment]
Ah that sounds plausible - I do have Latex installed.

**Comment by JorisGoosen** [comment]
> Ah that sounds plausible - I do have Latex installed.

And yeah, if I install texmaker (which includes latex) then the plots no longer work... It seems it overwrites some default that somehow gets smuggled into jasp.

So a workaround would be to uninstall any tex if it isn't being used...
But now I just need to figure out which settings/environment-variable/config-file is responsible for this problem.

**Comment by lindemann09** [comment]
> Ok, so I've installed xubuntu and there the font and plots look fine as well...
> 
> @JohnnyDoorn and @lindemann09 do you maybe have latex or other tex stuff installed?
> Because possibly that overwrites the default font used by ggplot?
> Or maybe you also have copy of R?
> 
> Are either of you using a non-default system theme/font?

Yes, I can confirm it is latex-font issue. The bug occurs *only*, if `texlive-fonts-recommended` is installed. I noticed the same bug in some ggplot-related packages. For instance, 

```
library(GGally)
ggpairs(mtcars[, c('mpg', 'cyl')])
```

**Comment by JorisGoosen** [comment]
Aah so this happens outside of JASP as well? Hmm.

I had already narrowed it down a little bit more to the pkg `tex-gyre`, just removing that fixes the problem here in my VM. Im trying out specifying some fonts in our ggplot interface to see if that helps.

@vandenman if you install `tex-gyre` I assume you also get the problem locally?
Maybe we ought to open a bugreport with the ggplot folks?

**Comment by lindemann09** [comment]
Yes, I can confirm that. It's sufficient to uninstall the tex-font that is used by `ggplot`. In the case of JASP `apt remove tex-gyre` is a workaround.

**Comment by JorisGoosen** [comment]
So Ive opened a bugreport with ggplot because if it also breaks outside of jasp and without flatpak there is something worse going on.

**Comment by JorisGoosen** [comment]
And there I got the following response, which mimicks what @vandenman might have mentioned earlier: 
> This an issue with the png device and how it interprets mono fonts. There is nothing we can do from the ggplot2 side, but I know the issue has been raised. You can use the devices from ragg instead to avoid it, though it doesn't provide a windowed device, only file devices

Would it be hard to switch to using `ragg` ? @TimKDJ and @vandenman ?
I like the added benefit of it never opening windows.

**Comment by vandenman** [comment]
Well, it shouldn't be hard to try out but it would require a lot of testing and there might be other issues we just don't know about yet. Remember when we wanted to switch to `svg`?

**Comment by JoKeyser** [comment]
Not sure if related, but I had a similar problem on Ubuntu 18.04, see #682.

The solution that worked for me was refreshing the font cache:
```
flatpak run --command=fc-cache org.jaspstats.JASP -f -v
```

**Comment by JorisGoosen** [comment]
Certainly worth a try!

I will check it out when I have the time. Maybe @lindemann09 has it time before me?

**Comment by lindemann09** [comment]
yes, it does indeed solve the issue for JASP. Thanks @JoKeyser.

Other ggplot based software, such as the library GGally, are however still affected, even if refreshing the system and local font cache.

**Comment by JorisGoosen** [comment]
So Ive added this fix to the linux install page: https://jasp-stats.org/linux-installation-guide/
