### ISSUE TITLE
Specific contrasts and analytical comparisons

### ISSUE THREAD

**Issue by FelipeMAffonso** [jasp-stats/jasp-issues#782]
* Enhancement: It would be nice to be able to specify contrasts before doing the simple main effects.
* Purpose: Analytical comparisons
* Use-case: Social science experiments rely on analytical comparisons many times.

**Describe the solution you'd like**

Suppose I have A, B, and C in an ANOVA design. A has 2 levels, B has 2 levels, and C has 3 levels. What if my simple simple main effects want to compare c1 with c2, then c2 with c3, or even the average of c1 and c2 with c3 within each level of A within each level of B (say, a1b1). It would be nice to be able to fully customize how to do contrasts in the software.

**Describe alternatives you've considered**
The only solution is using SPSS's LMATRIX.

**Comment by boutinb** [comment]
@FelipeMAffonso  I think this is already implemented in the next release, but @JohnnyDoorn can better confirm this (or not)

**Comment by JohnnyDoorn** [comment]
Hi @FelipeMAffonso 

Yes, this will be in the next version of JASP (coming soon!). It will have a neat widget to fully specify the contrasts you want, including for all cells of an interaction.

Cheers,
Johnny

**Comment by FelipeMAffonso** [comment]
Hi @JohnnyDoorn 

I am testing JASP 0.13 and I am having some trouble specifying contrasts.

When I create a custom contrast and click "add contrast", the "contrast tables" disappear, and the contrast is not added. So I cannot create sets of Comparisons unless I use the standard comparisons that are already in JASP (e.g., deviation, simple, etc.). But I can't do it using the custom ones.

In addition, I am having trouble specifying "simple interactions". That is: I want to verify the B*C interaction across different levels of A for a A*B*C design. How do I do this? Let me exemplify this with real data and what I do on SPSS. I have a 2*3*2 design dataset with the following factors: goal tradeoff (independent vs. interdependent) x 3 (process goal: maximize accuracy, baseline, minimize effort) x 2 (difficulty: difficult vs. easy).

If I run this code on SPSS:


UNIANOVA DV BY goaltradeoff difficulty processgoal 
  /METHOD=SSTYPE(3) 
  /INTERCEPT=INCLUDE 
  /PRINT ETASQ DESCRIPTIVE 
  /LMATRIX "Interaction within Independent"
difficulty*processgoal 1 0 -1 -1  0 1 goaltradeoff*difficulty*processgoal 1 0 -1 -1  0 1 0 0 0 0 0 0;
difficulty*processgoal 0 1 -1  0 -1 1 goaltradeoff*difficulty*processgoal 0 1 -1  0 -1 1 0 0 0 0 0 0
 /LMATRIX "interaction within Interdependent"
difficulty*processgoal 1 0 -1 -1  0 1 goaltradeoff*difficulty*processgoal 0 0 0 0 0 0 1 0 -1 -1  0 1;
difficulty*processgoal 0 1 -1  0 -1 1 goaltradeoff*difficulty*processgoal 0 0 0 0 0 0 0 1 -1  0 -1 1;
 /EMMEANS=tables(goaltradeoff*processgoal*difficulty) COMPARE(difficulty) ADJ(LSD)
  /EMMEANS=tables(goaltradeoff*processgoal*difficulty) COMPARE(processgoal) ADJ(LSD)
  /PLOT=PROFILE(processgoal*difficulty*goaltradeoff) TYPE=BAR ERRORBAR=NO MEANREFERENCE=NO
  /CRITERIA=ALPHA(.05) 
  /DESIGN=goaltradeoff processgoal difficulty goaltradeoff*processgoal goaltradeoff*difficulty 
    processgoal*difficulty goaltradeoff*processgoal*difficulty.

I get this result (for each of the "LMATRIX"es):

![image](https://user-images.githubusercontent.com/57021043/85720419-6901f980-b6be-11ea-8e63-c596584e42fe.png)

![image](https://user-images.githubusercontent.com/57021043/85720480-78814280-b6be-11ea-8602-61399f2e35d7.png)

These contrasts are: interaction of "difficulty" and "processgoal" on one level of goaltradeoff, and the interaction on another level of goaltradeoff. Note that they are orthogonal contrasts. I have two contrast estimates for each level of "goal-tradeoff". And these two contrast estimates are used for an overall F-test. In other words, I have two comparisons that lead to an overall F-test, which is the simple interaction test.

I am trying to replicate this analysis on JASP, but it's been difficult. 

Well. In reality, I have been able to reach the "Contrast Estimate" part:

![image](https://user-images.githubusercontent.com/57021043/85720944-e594d800-b6be-11ea-8aaa-29e626604aee.png)

As you can see, the 3.940 contrast estimate is the same estimate I get on SPSS (see L1, Custom Hypothesis Test #1). It is contrasting the "maximize accuracy" with "minimize effort" condition. It requires one more comparison to have two sets of orthogonal contrasts, i.e., I still need to have the comparison leading to the 4.140 estimate, which can be achieved (though I can't add both comparisons, see the beginning of this reply):

![image](https://user-images.githubusercontent.com/57021043/85721394-50deaa00-b6bf-11ea-822a-6bb904070f52.png)

So, what I need to be able to do is basically two things:

1) One is to be able to add both comparisons to the contrast coefficients table. If I click "Add Contrast", I get an error: "Please specify non-zero contrast weights". 

2) Suppose I have two comparisons that are orthogonal (such as my Custom Hypothesis Test #1 from SPSS). How do I get JASP to perform that F-test, which is the simple interaction test? I need the simultaneous test of both contrasts. Am I doing something wrong? I guess I am too focused on trying to get the syntax code from SPSS to JASP, but the actual implementation is different.

thanks!

Felipe

**Comment by JohnnyDoorn** [comment]
Hi @FelipeMAffonso ,

1. Do you have a JASP file where you encounter the error? Because for me this contrast specification works. If I understand correctly you get the error "Please specify non-zero contrast weights". and you cannot change the contrast weights because the input field disappears?

2. Yes, that would be a great functionality, and it's on my todo list for JASP, it will not be in 0.13 unfortunately, but hopefully the version after.

Cheers
Johnny

**Comment by FelipeMAffonso** [comment]
@JohnnyDoorn 

What I was trying to do was to add multiple contrast specifications. For example. If I go to Contrasts and click "Simple" (for that 3x2x2 design), I get 11 comparisons. Like this: 
![image](https://user-images.githubusercontent.com/57021043/85739073-7fb04c80-b6ce-11ea-840f-dee3b350bd3a.png)

But I want these comparisons to be custom contrasts. So, suppose I am trying to do the 1 0 -1 -1 0 1 0 0 0 0 0 0 specification. If I click "Custom" and specify these contrasts, I can get the "Comparison 1" column there. So far, so good. That's one of the specifications I use on SPSS to run that F test. If with that specification I click "Add Contrast", the "Please specify non-zero contrast weights" immediately appears. The contrast table goes away. Because of that, I can't add the second column I wanted (the Comparison 2) with the "0 1 -1 0 -1 1 0 0 0 0 0 0" specification (this specification is the second specification that creates the set of orthogonal contrasts to calculate the F interaction on SPSS). 

So while I can do multiple specification/comparison columns when the contrasts are pre-set (simple, difference, helmert, etc), I cannot do this with Custom contrasts. In other words, I can't do two sets of custom contrasts at the same time. Based on your response, I know I can't calculate the F test (for the simple interaction involving these two contrasts), but still, I believe that having the two columns would be a necessary step for this F test calculation, right?

Let me know if it's clear. I can also record my screen showing the problem, or also send you the dataset.

(BTW: with this functionality that is on your to-do list, would we be able to "mimic" what LMatrix does? Such as specifying simple interactions using orthogonal contrasts of a 2x2 within a level of a third factor? Also, would that work with within-subject designs?)

Thanks!!

**Comment by JohnnyDoorn** [comment]
Hi @FelipeMAffonso ,

The error message appears because the second column only contains zeroes - the moment you specify any contrast weights for comparison 2, this message should go away. Have you tried adding those in the widget? But maybe I am misunderstanding, do you have a screenshot of your input panel? 

Kind regards
Johnny

**Comment by JohnnyDoorn** [comment]
Hi @FelipeMAffonso ,

I just checked with my 0.13 version, and for me the custom contrasts work:
![Screenshot from 2020-06-26 13-29-07](https://user-images.githubusercontent.com/15704203/85852552-1ce3b180-b7b1-11ea-8f7f-688b807dd89e.png)

Please let me know if you are still experiencing issues!

Kind regards
Johnny

**Comment by FelipeMAffonso** [comment]
Hi @JohnnyDoorn 

I have checked and it is working. I want to apologize for posting here without double checking what the issue was.

Here's what happened: because I used 3 factors, the input for the custom contrasts was not fully appearing. When the second column of custom contrasts "appeared", it was hidden (I had to scroll to the right to find it). So it works. It's just what I wasn't seeing it.

So.. it is working. and it WAS working.

Thank you very much, and I look forward for the next functionalities!!

Felipe

**Comment by srk7774** [comment]
@JohnnyDoorn @FelipeMAffonso I am trying to replicate the findings in jasp.   I specified the following contrasts.  Facta: (2 -1 -1) , factb: (0 -1 1) and would like to check the interaction at level 1 of factc.  Could you please specifiy the values to be entered in the jasp contrasts. 
The above example is taken from Design and analysis by Keppel (4th Ed.).
Results: F = 14.017/1.889 = 7.42
F(1,70) = 3.98 @ 0.05
Also SS given for, Facta by factb at factc level2 is given 0.017


[table21.1.xlsx](https://github.com/jasp-stats/jasp-issues/files/4907049/table21.1.xlsx)

**Comment by TomasAPalma** [comment]
Hi guys,

I have a potentially silly question: I am running JASP version 0.13.1 (Mac), and, surprisingly, I don't have the option to perform custom contrasts for interactions!? As you can see in the attached screenshot, when I go the contrasts option within ANOVA, the interaction between the two factors is not listed there. I might be missing something, though. Can you help out?

Thanks!
Tomás Palma
![Screenshot 2020-07-21 at 16 28 29](https://user-images.githubusercontent.com/32547294/88074982-135f2680-cb70-11ea-9cae-b93ff9752d25.png)

**Comment by JohnnyDoorn** [comment]
Hi @srk7774 ,

I am not entirely sure what you mean. If you want those contrast analyses for a specific level of a factor, this is not yet possible yet unfortunately (see also comments above). 
Or are you getting wrong results compared to your source?

Kind regards,
Johnny

**Comment by JohnnyDoorn** [comment]
Hi Tomas,

I checked with my version, and there I do have the interaction effect. Is
the interaction effect in your model, and are you JASP 0.13.1?

Cheers
Johnny
