### ISSUE TITLE
Navigation Buttons

### ISSUE THREAD

**Issue by GitHubRequests** [jasp-stats/jasp-issues#783]
* Enhancement: Add arrow-buttons on bottom left and right of interface for spreadsheet of data in JASP to allow to scroll horizontally per column like Excel.
* Purpose: Finer access and control to specific data columns 
* Use-case: Needing to change columns into scale or ordinal or nominal data per column but having to use the scroll bar at the bottom without a more exact method of navigating through the data per column is difficult and can cause one to miss columns if scrolling went too far. Takes time away from analyzing data itself with having to clean/set it up.

**Is your feature request related to a problem? Please describe.**
 
Yes, I can't scroll per column horizontally with just the scroll bar as my mouse makes it go too far sometimes. I want bottom left and bottom right navigation arrows that will allow me to scroll through the data per column like in Excel.

**Describe the solution you'd like**
 
I want bottom left and bottom right navigation arrows that will allow me to scroll through the data per column like in Excel.

**Comment by tomtomme** [comment]
@GitHubRequests 
We have now edit data mode. In this mode you can click any cell and use the arrow keys for exact navigation. Would you consider this as a fix? (no arrows for the scrollbar yet)
