### ISSUE TITLE
Data synch issue reappeared

### ISSUE THREAD

**Issue by DrMarkGS** [jasp-stats/jasp-issues#786]
* JASP version: 0.12.2 (April 30th)
* OS name and version: Windows 10
* Analysis: Data synchronisation
* Bug description: Synch data file disappears

Hoi folks
Had this issue before:
Open file (from external hard drive)
Data sync shows the correct file
![JASP1](https://user-images.githubusercontent.com/39003008/83883679-b8967a80-a73b-11ea-8bb9-785d7d3dd358.png)

Double click in a cell - change the data and save the .csv file

On returning to JASP the data has not updated and looking at Data sync the file name has gone.
![JASP2](https://user-images.githubusercontent.com/39003008/83883831-eed3fa00-a73b-11ea-97f2-252587de34de.png)

Did manage to fix it before.
Mark

**Comment by boutinb** [comment]
Hallo @DrMarkGS, could you send the log files (Preferences/Advanced)?

**Comment by DrMarkGS** [comment]
Hi Bruno
Strangely it is working this morning. I did get the error last week!
I will keep the logging on in case it happens again.
Mark

**Comment by boutinb** [comment]
@DrMarkGS Do you edit your csv file with Excel?

**Comment by DrMarkGS** [comment]
Hi Bruno – yes all the time.
Mark

**Comment by boutinb** [comment]
Hi @DrMarkGS. For your background information, we had some problems with the synchronization of csv file generated by Excel on Windows: when changing the file, Excel set temporary the file empty, making JASP reading an empty file. We tried to cope with this by trying to read the file after a timeout, but this timeout is of course quite subjective. I have a look if we can do something more clever.

**Comment by DrMarkGS** [comment]
Cheers – good luck

**Comment by JorisGoosen** [comment]
@DrMarkGS do you still get this problem with the 0.13.1 release of JASP?

**Comment by DrMarkGS** [comment]
Hoi Joris
All seems fine at the moment
Mark
