### ISSUE TITLE
Estimates of effect size for Simple Main Effects (and Contrasts)

### ISSUE THREAD

**Issue by FelipeMAffonso** [jasp-stats/jasp-issues#787]
* Enhancement: Estimates of effect size for Simple Main Effects (and Contrasts)
* Purpose: Add a "Display: Estimates of effect size" (as in the main ANOVA tables) for simple simple effects, simple effects, and simple interaction effects (and analytical contrasts, which will come later)
* Use-case: Besides effect sizes for the higher order effects, some journals require the reporting of effect sizes for all significant effects.

**Describe the solution you'd like**
Add a "Display: Estimates of effect size" (as in the main ANOVA tables) for simple simple effects, simple effects, and simple interaction effects (and analytical contrasts, which will come later)

**Describe alternatives you've considered**
None (I need to use excel)

**Comment by JohnnyDoorn** [comment]
Not yet. @FelipeMAffonso , could you maybe provide a numeric example of how you would like to this implemented? That way I will have some sanity checks when implementing this feature. Apologies for this extremely late reaction..

**Comment by tomtomme** [comment]
@juliuspfadt & @JohnnyDoorn 
Estimates are implemented for contrasts but not for simple main effects yet.
This R-Package may be of help:

https://search.r-project.org/CRAN/refmans/bruceR/html/EMMEANS.html

**Comment by tomtomme** [comment]
@FelipeMAffonso @JohnnyDoorn 
Isnt this kind of covered by the new PROCESS module?

**Comment by tomtomme** [comment]
@FelipeMAffonso @JohnnyDoorn 
Closing, since estimates for contrasts are done and estimates for simple main effects are available via the process module.

please reopen, if you disagree!
