### ISSUE TITLE
Regression - Simple Slopes Analyses (probe interactions)

### ISSUE THREAD

**Issue by FelipeMAffonso** [jasp-stats/jasp-issues#789]
* Enhancement: Addition of Simple Slopes Analyses for Regression
* Purpose: Calculation of simple slopes (continuous-by-continuous with 1SD above and below the mean, categorical-by-continuous)
* Use-case: Data analyses involving interactions with regression

**Describe the solution you'd like**
I would like to be able to probe interactions by selecting conditioning values (-1SD, Mean, +1SD, or level 1 vs. level 2) of a moderator/IV to probe at different levels of other moderator/IV.

A good example on how to do this (and the output) is PROCESS's SPSS MACRO (http://www.processmacro.org/index.html). Here is another good reference (SAS): https://stats.idre.ucla.edu/sas/seminars/analyzing-and-visualizing-interactions/

Ideally, a simple check box "Probe Interactions if p-value = x" would be nice. Here is the output when an interaction is probed. Difficul (W) has two levels (0 and 1), and "goaltrad" is a binary variable (but it could be a continuous variable too). The output shows the effect of X on Y at different levels of W. It also has bootstrapping estimates. Notice that the effect of X on Y is significant for W = 1, but not for W = 0.

    Focal predict: goaltrad (X) 
          Mod var: difficul (W) 
 
Conditional effects of the focal predictor at values of the moderator(s): 
 
   difficul     Effect         se          t          p       LLCI       ULCI 
      .0000      .0533      .4477      .1191      .9052     -.8260      .9326 
     1.0000    -1.1067      .4477    -2.4717      .0137    -1.9860     -.2274

Notice that is is also important to analyze (and visualize) 3-way interactions. It would be nice to do this on JASP. The UCLA has nice pages on this. PROCESS does these calculations.

Alternatives: I use PROCESS on SPSS.

**Comment by boutinb** [comment]
@vandenman Could you have a look to this request?

**Comment by FelipeMAffonso** [comment]
Other important / nice reference:

https://journals.sagepub.com/doi/10.1509/jmr.12.0420

**Comment by tomtomme** [comment]
This can be closed

PROCESS is now available in beta:
https://github.com/jasp-stats/jasp-desktop/releases/tag/v0.18.2.beta

or via our nightly builds:
https://static.jasp-stats.org/Nightlies/

final 0.18.2 will be out soonTM.

**Comment by boutinb** [comment]
This is now released.
