### ISSUE TITLE
Feature request: Kaiser-Meyer-Olkin (KMO) index and Bartlett’s test of sphericity

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-issues#79]
From the JASP Email:

"It would be great if the principal component factor analysis can provide Kaiser-Meyer-Olkin (KMO) index and Bartlett’s test of sphericity, as well as eigenvalue and explained variance of each factor loading in the next version of JASP."

These are good ideas I think, one of us should look at this and give it an upgrade.

**Comment by App-State-Prof** [comment]
Good morning are there updates on KMO output and Bartlett's, also specific Eigen values, in linear regression? On some occasions, peer reviewers required these to be reported. Thank you!

**Comment by djdekker** [comment]
+1 for the feature request of **KMO** and **Bartlett's Test**. I'm using SPSS to check both to see whether a data set is suitable to perform a factor analysis. I'd appreciate your consideration of adopting them in JASP.

**Comment by vankesteren** [comment]
I will see what I can do in the rewrite of the EFA function!
