### ISSUE TITLE
Logistic Regression: Analytical Comparisons, Simple Effects, and Probing Interactions

### ISSUE THREAD

**Issue by FelipeMAffonso** [jasp-stats/jasp-issues#790]
* Enhancement: Logistic Regression: Analytical Comparisons, Simple Effects, and Probing Interactions
* Purpose: Do analytical comparisons, simple effects, probing interactions, and even simple interactions/simple simple effects like an ANOVA, but in logistic regression (binary DV).
* Use-case: Experiments with binary DVs.

**Describe the solution you'd like**

I would like to be able to to simple effects and contrasts similar to what happens in an ANOVA. Here are some interesting references:

https://us.sagepub.com/en-us/nam/interaction-effects-in-logistic-regression/book11268

and PROCESS Macro: http://www.processmacro.org/index.html

**Comment by boutinb** [comment]
@vandenman Can you have a look to this one also?

**Comment by FelipeMAffonso** [comment]
Perhaps this is also useful http://www.jeremydawson.co.uk/slopes.htm

**Comment by tomtomme** [comment]
@FelipeMAffonso 

Since the logistic regression module can include interactions and since PROCESS is now available in beta: 
https://github.com/jasp-stats/jasp-desktop/releases/tag/v0.18.2.beta
 
or via our nightly builds: 
https://static.jasp-stats.org/Nightlies/

Can this be closed?
