### ISSUE TITLE
R code editor / environment (like RStudio?)

### ISSUE THREAD

**Issue by FelipeMAffonso** [jasp-stats/jasp-issues#791]
* Enhancement: R code editor / environment (like RStudio?)
* Purpose: to run R codes, load additional R packages, and run additional analyses (and see the console) for datasets that are open in JASP. Such as when one has a SPSS open and runs some syntaxes.
* Use-case: Run things that are not yet in JASP using R code quickly, in the same software. For example, I would like to run some codes (with the data that is open in JASP) to run some analyses that are not in JASP.

**Describe the solution you'd like**
Something similar to "New -> Syntax" from SPSS, but like RSTudio (the code editor, the console, the packages, an environment...) INSIDE JASP.

**Comment by EJWagenmakers** [comment]
The upcoming release (planned for this month) will have a beta version of this idea.

**Comment by tomtomme** [comment]
can be closed
