### ISSUE TITLE
Data Editor and Data Management

### ISSUE THREAD

**Issue by FelipeMAffonso** [jasp-stats/jasp-issues#792]
* Enhancement: Data Editor and Data Management
* Purpose: To have a "Data View" and "Variable View" similar to SPSS. This would help A LOT with managing data.
* Use-case: Everyday use.

**Describe alternatives you've considered**
I usually take care of my data using SPSS and use JASP to do the analyses. It would be nice to centralize everything in JASP.

**Comment by EJWagenmakers** [comment]
A major item on our to-do list, but currently our main focus is on achieving better integration with R.

**Comment by FelipeMAffonso** [comment]
Great! Thanks

**Comment by tomtomme** [comment]
this is done
