### ISSUE TITLE
Analysis Terminated Bug Report

### ISSUE THREAD

**Issue by GitHubRequests** [jasp-stats/jasp-issues#795]
* JASP version: 0.12.2

* OS name and version: Windows 10 Home version 1909
* Analysis: Independent Sample T-Test
* Bug description:

"This analysis terminated unexpectedly.
Error in .ttestIndependentMainFill(ttest, dataset, options, testStat, : object 'result' not found
Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])
doTryCatch(return(expr), name, parentenv, handler)
withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)
analysis(jaspResults = jaspResults, dataset = dataset, options = options)
.ttestIndependentMainTable(jaspResults, dataset, options, ready, type)
.ttestIndependentMainFill(ttest, dataset, options, testStat, optionsList)
To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports
* Expected behaviour: perform t-test

**Comment by vandenman** [comment]
this sounds like a duplicate of https://github.com/jasp-stats/jasp-issues/issues/724 which got fixed in https://github.com/jasp-stats/jasp-desktop/pull/4069. So should be fixed in the next release!

**Comment by boutinb** [comment]
@GitHubRequests You can test this version (still in development) here: https://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-stable-87a4738a12e7d88c447389c9fd4b4f9c72d63ba6.msi
And check if it indeed solves your problem.

**Comment by BKTP2020** [comment]
Hi all, 

it's seems as if I'm not experiencing the same bug. I'm currently working on my thesis, so it would be great if the bug could be solved soon. The above link to a test version seems to be expired. 

I'm wondering about the little "a" for the grouping variable. 
Regarding the details of analysis: 

variable "Fehltage" contains all records (median is 0)
grouping varibale "Gruppe Fehltage" contains a split of the variable "Fehltage" (split by those records which are =0 and those that are >0)

Looking forward to your comment.

Here's the stack trace: 

his analysis terminated unexpectedly. 

Error in .ttestIndependentMainFill(ttest, dataset, options, testStat, : object 'result' not found

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.ttestIndependentMainTable(jaspResults, dataset, options, ready, type)

.ttestIndependentMainFill(ttest, dataset, options, testStat, optionsList)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

![Bug_JASP](https://user-images.githubusercontent.com/67604144/86043907-a1506180-ba49-11ea-953d-3628cc17b213.PNG)
