### ISSUE TITLE
Summary Statistics Bayesian Independent Samples T-Test: Labels in prior and posterior plots switch upon changing from BF10 to BF01, while they shouldn't

### ISSUE THREAD

**Issue by Diesfeldt** [jasp-stats/jasp-issues#796]
* JASP version: 0.12.1

* OS name and version:
* Analysis: 
* Bug description:
* Expected behaviour:

**Comment by boutinb** [comment]
@Diesfeldt Can you be a bit more descriptive about the issue?

**Comment by Diesfeldt** [comment]
Hi Bruno,

Thanks. I uploaded a text file which contains my question. See enclosed.

Hope to hear your response.

Best,

Han Diesfeldt


Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

Van: bruno boutin<mailto:notifications@github.com>
Verzonden: maandag 8 juni 2020 10:40
Aan: jasp-stats/jasp-issues<mailto:jasp-issues@noreply.github.com>
CC: Diesfeldt<mailto:h.diesfeldt@outlook.com>; Mention<mailto:mention@noreply.github.com>
Onderwerp: Re: [jasp-stats/jasp-issues] Summary Statistics Bayesian Independent Samples T-Test (#796)


@Diesfeldt<https://github.com/Diesfeldt> Can you be a bit more descriptive about the issue?

**Comment by boutinb** [comment]
The file was apparently not correctly uploaded in GitHub.
Can you try again? You have to do that from the GitHub site. If GitHub refuse to load your file, you can first zip the file.

**Comment by AlexanderLyNL** [comment]
Alternatively, you can also copy paste the content of the text file into the comment box. Furthermore, if it concerns a bug or feature request, it would be good to provide us with the requested information as displayed in the issue template, so we have enough information to handle the problem, see also our guideline here:

https://jasp-stats.org/2018/03/29/request-feature-report-bug-jasp/

**Comment by Diesfeldt** [comment]
Hi Alexander,

Thanks very much. This is my remark or question: JASP version 0.12.1
Input: t=2.166 n1 = 49 n2 = 536
If BF10 has been activated the plot says BF10 = 1.427, as in the Table. However, when activating  BF01, the Table correctly displays BF01 = 0.701, but the plot  says BF10 = 0.701. The pizza plot accordingly does not correctly display data|H1 and data|H0.

I can send you a copy of the JASP output by email. This comment box does not accept the JASP output results.

Best,

Han

**Comment by Diesfeldt** [comment]
Thanks very much, Alexander. I hope my remark is helpful. Thanks also for introducing me to JASP a few years ago.

Best,

Han

**Comment by AlexanderLyNL** [comment]
Hi Han,

This is very helpful for us. Despite many testing rounds before releasing a new version some issues remain. It's thanks to user reports that the remaining issues get removed. I hope you enjoy JASP, and feel free to request any missing features. Thanks again for reporting the bug.  

Cheers,
Alexander

**Comment by ASarafoglou** [comment]
I do not think that I can fix this issue before the next release, without having the JASP programmers around to help me out (I haven't coded for JASP since December). I would be thankful if the task would get allocated to somebody else, who can probably fix this issue in 20 minutes.

**Comment by akashrajkn** [comment]
I'll take this issue

**Comment by Diesfeldt** [comment]
Thank you very much.

Best,

Han Diesfeldt

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

Van: akash raj<mailto:notifications@github.com>
Verzonden: maandag 13 juli 2020 10:25
Aan: jasp-stats/jasp-issues<mailto:jasp-issues@noreply.github.com>
CC: Diesfeldt<mailto:h.diesfeldt@outlook.com>; Mention<mailto:mention@noreply.github.com>
Onderwerp: Re: [jasp-stats/jasp-issues] Summary Statistics Bayesian Independent Samples T-Test: Labels in prior and posterior plots switch upon changing from BF10 to BF01, while they shouldn't (#796)


I'll take this issue
