### ISSUE TITLE
Incorrect Values in 2x2x2 ANCOVA Table

### ISSUE THREAD

**Issue by luisbm1634** [jasp-stats/jasp-issues#797]
When running a 2x2x2 ANCOVA in JASP 0.12.2 on a mid-2017 MacBook Pro 13 inch, the ANCOVA table reports incorrect values for the CV and all interaction factors. Essentially, the values for these rows are swapped. The reported values for IV1*IV2 are replaced with those for IV2*IV3; the values for IV1*IV3 are replaced with those from IV1*IV2; the values for IV2*IV3 are replaced with those from the CV; the values for IV1*IV2*IV3 are replaced with those for IV1*IV3; and finally, the CV values are replaced with those from IV1*IV2*IV3. 

This issue is not seen in version 0.12.2 when running a 2x2 ANCOVA. It is also not seen when running a 2x2 or 2x2x2 ANCOVA in an earlier version of JASP (0.11.1). 

It is possible that 0.12.2 is actually reporting the correct values for the CV and interaction terms, and it is earlier versions that were reporting these values incorrectly. However, I did run a linear regression using all terms (including interaction terms) and found that on both versions of JASP that I have installed (0.12.2 and 0.11.1), the interaction and CV term p-values line up identically with those reported in the ANCOVA table from version 0.11.1, not 0.12.2. Hence, I believe that version 0.12.2 is reporting the 2x2x2 ANCOVA results incorrectly.

**Comment by boutinb** [comment]
Hallo @luisbm1634 It would be helpful if you can send us a JASP file that shows this problem

**Comment by luisbm1634** [comment]
Hi Bruno,

Attached are sample JASP files, one from JASP 0.12.2 and the other from
JASP 0.11.1. I ran the same data set (also attached) through an identical
analysis in each version. The data set is just a set of 3 different IVs
(each with 2 levels), a single DV, and a single CV. IVs are dummy coded.
DVs are data that I generated using a random number generator.

To ensure that you can see the output as it appeared in each version of
JASP, I've also attached the results from 0.11.1 and 0.12.2 as html files.

**Comment by boutinb** [comment]
Hi @luisbm1634 , the file was not sent. The best way to do it, is to make a zip file, and to drag & drop it in this issue with GutHub.

**Comment by luisbm1634** [comment]
Hi Bruno,

I mistakenly just attached the file to my email response rather than uploading via GitHub. They should now be available.

-Luis

[2x2x2_ANCOVA.zip](https://github.com/jasp-stats/jasp-issues/files/4814279/2x2x2_ANCOVA.zip)

**Comment by boutinb** [comment]
Hoi @JohnnyDoorn Can you have a look to the data?
