### ISSUE TITLE
Descriptives in two-way ANOVAs - Show "total" means and SDs

### ISSUE THREAD

**Issue by FelipeMAffonso** [jasp-stats/jasp-issues#799]
* Enhancement: Descriptives in two-way ANOVAs - Show "total" means and SDs
* Purpose: To show means of main effects on higher-order ANOVA models.
* Use-case: Suppose I have A (a1, a2) and B (b1, b2) factors and I run a two-way ANOVA. The descriptives show me only the crossed table (a1 and a2 for b1, a2 and a2 for b2, or the reverse of this), but it does not show me the mean and SD of a1 and a2, and b1 and b2 (for all Bs and all As, respectively).

When I am writing a report of an ANOVA result that involves main effects, it's useful to have these results handy. SPSS does this (it has a "total" row for each factor). Can JASP please add a "display factor totals" check so I can see such totals, or even add they for every descriptive table?

Otherwise, I need to keep running/rerunning the ANOVA removing the factors. And if I use "descriptives" it's more time consuming.

Thank you!

**Comment by tomtomme** [comment]
I would solve this nowadays via the green + button, that duplicates my analysis. Then I would remove the second factor. Works pretty fast for me. Does this help?
