### ISSUE TITLE
unexpected termination in SEM

### ISSUE THREAD

**Issue by DocGavin** [jasp-stats/jasp-issues#803]
Hi I don't understand what went wrong here. 

Error in lavaan::lavTestLRT(semContainer[['semResultsList']]$object$semResults): lavaan ERROR: model did not converge

Stack trace

this is the data command file 
[cn-sdq sem.txt](https://github.com/jasp-stats/jasp-issues/files/4777878/cn-sdq.sem.txt)
this is the data i am using
[CN_SDQ2510-19Intervention&Control.xlsx](https://github.com/jasp-stats/jasp-issues/files/4777883/CN_SDQ2510-19Intervention.Control.xlsx)

**Comment by boutinb** [comment]
@vankesteren Can you have a look?

**Comment by DocGavin** [comment]
Hi I tried a different model and got the same kind of error

This analysis terminated unexpectedly.

Error in lavaan::lavTestLRT(semContainer[['semResultsList']]$object$semResults): lavaan ERROR: model did not converge

Stack trace

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports


I created manifest variables in SPSS and imported them into JASP

Model was

# CNI1
CN1 =~ ENN1 + EMN1 + RN1 + AN1
# SDQ1
SDQ1 =~ Pro1 + Hyper1 + Emot1 + Cond1 + Peer1 + SDQ_tot1
#sem cn1 to sdq1
AN1 =~ Emot1
RN1 =~ Hyper1 + Cond1 + Peer1 + Pro1
ENN1 =~SDQ_tot1

Unfortunately I have to resort to lavaan in R which I hate having to do
cheers
Prof. Gavin T L Brown, PhD
Associate Dean Postgraduate Research (ADPG)
Director Quantitative Data Analysis and Research Unit
Faculty of Education & Social Work
The University of Auckland
Tel: +64 9 3737599 ext. 48602
I am working virtually and if I send you an email outside your reasonable work hours, please note that I am doing so because it works for me in managing my work / life balance. I do not expect that you will read, respond or take action outside of your normal working hours.
[EdUHK_logo]Honorary Professor, Dept. of Curriculum & Instruction, Education University of Hong Kong
[umu-logo-crest only small] Affiliated Professor, Dept. of Applied Educational Sciences, University of Umea, Sweden
[frontiers_logo]Frontiers in Education Chief Section Editor: Assessment, Testing, and Applied Measurement
[routledge_logo]Routledge author: https://www.routledge.com/authors/i14875-gavin-brown

**Comment by vankesteren** [comment]
Hi @DocGavin, 

did it work in R in the end?

**Comment by DocGavin** [comment]
Goede dag Erik-Jan
I got the model to run in R using R-Studio but the same model in JASP throws an error
Model Syntax
# no SDQ total
CNSDQ.T1 <-  '
# CNI1
ENN1 =~ lambda_1_1*CN2t1 + lambda_1_2*CN1t1 + lambda_1_3*CN3t1 + lambda_1_4*CN4t1 + lambda_1_5*CN5t1 + lambda_1_6*CN7t1
EMN1 =~ lambda_2_1*CN12t1 + lambda_2_2*CN6t1 + lambda_2_3*CN14t1
RN1 =~ lambda_3_1*CN18t1 + lambda_3_2*CN8t1 + lambda_3_3*CN11t1
AN1 =~ lambda_4_1*CN21t1 + lambda_4_2*CN9t1 + lambda_4_3*CN10t1 + lambda_4_4*CN19t1

# SDQ
FPro1   =~ lambda_1_1*SDQ20t1 + lambda_1_2*SDQ1t1 + lambda_1_3*SDQ4t1 + lambda_1_4*SDQ9t1 + lambda_1_5*SDQ17t1
FHyper1 =~ lambda_2_1*SDQ2t1 + lambda_2_2*SDQ10t1 + lambda_2_3*SDQ15t1 + lambda_2_4*SDQ21t1 + lambda_2_5*SDQ25t1
FEmot1  =~ lambda_3_1*SDQ24t1 + lambda_3_2*SDQ3t1 + lambda_3_3*SDQ8t1 + lambda_3_4*SDQ13t1 + lambda_3_5*SDQ16t1
FCond1  =~ lambda_4_1*SDQ5t1 + lambda_4_2*SDQ7t1 + lambda_4_3*SDQ12t1 + lambda_4_4*SDQ18t1 + lambda_4_5*SDQ22t1
FPeer1  =~ lambda_5_1*SDQ14t1 + lambda_5_2*SDQ6t1 + lambda_5_3*SDQ11t1 + lambda_5_4*SDQ19t1 + lambda_5_5*SDQ23t1
SDQ =~ FPro1 + FHyper1 + FEmot1 + FCond1 + FPeer1

#SEM
AN1 =~ FEmot1
RN1 =~ FHyper1 + FCond1 + FPeer1 + FPro1
ENN1 ~~0*FPro1+0*FHyper1+0*FEmot1+0*FCond1+0*FPeer1
EMN1 ~~0*FPro1+0*FHyper1+0*FEmot1+0*FCond1+0*FPeer1
RN1 ~~0*FPro1+0*FHyper1+0*FEmot1+0*FCond1+0*FPeer1
AN1 ~~0*FPro1+0*FHyper1+0*FEmot1+0*FCond1+0*FPeer1
'
Lavaan analysis input
cnsdqt1_fit<-cfa(CNSDQ.T1, data=cn_sdq_614,estimator="MLR", check.gradient = FALSE)
There were 12 warnings (use warnings() to see them)
summary (cnsdqt1_fit, standardized=TRUE)
lavaan 0.6-6 ended normally after 951 iterations

JASP error

This analysis terminated unexpectedly.

Error in lavaan::lavTestLRT(semContainer[['semResultsList']]$object$semResults): lavaan ERROR: model did not converge

Stack trace

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

So yes it seems to work in lavaan but not jasp
Hope this helps

Prof. Gavin T L Brown, PhD
Associate Dean Postgraduate Research (ADPG)
Director Quantitative Data Analysis and Research Unit
Faculty of Education & Social Work
The University of Auckland
Tel: +64 9 3737599 ext. 48602
I am working virtually and if I send you an email outside your reasonable work hours, please note that I am doing so because it works for me in managing my work / life balance. I do not expect that you will read, respond or take action outside of your normal working hours.
[EdUHK_logo]Honorary Professor, Dept. of Curriculum & Instruction, Education University of Hong Kong
[umu-logo-crest only small] Affiliated Professor, Dept. of Applied Educational Sciences, University of Umea, Sweden
[frontiers_logo]Frontiers in Education Chief Section Editor: Assessment, Testing, and Applied Measurement
[routledge_logo]Routledge author: https://www.routledge.com/authors/i14875-gavin-brown

**Comment by juliuspf** [comment]
@DocGavin, sorry for the very late response. Could you try if the issue persists with the latest version of JASP?

**Comment by DocGavin** [comment]
Ok. thanks for your efforts here. I ran this code today successfully for a hierarchical CFA.
# hierachical CFA

# Factors
Factor1 =~ lambda_1_1*IDE1 + lambda_1_2*IED2 + lambda_1_3*IDE3
Factor2 =~ lambda_2_1*ITG1 + lambda_2_2*ITG2 + lambda_2_3*ITG3
Factor3 =~ lambda_3_1*ISL1 + lambda_3_2*ISL2 + lambda_3_3*ISL3
Factor4 =~ lambda_4_1*IV1 + lambda_4_2*IV2 + lambda_4_3*IV3
Factor5 =~ lambda_5_1*IrB1 + lambda_5_2*IrB2 + lambda_5_3*IrB3
Factor6 =~ lambda_6_1*IrI1 + lambda_6_2*IrI2 + lambda_6_3*IrI3
Factor7 =~ lambda_7_1*IrA1 + lambda_7_2*IrA2 + lambda_7_3*IrA3
Factor8 =~ lambda_8_1*ScA1 + lambda_8_2*ScA2 + lambda_8_3*ScA3
Factor9 =~ lambda_9_1*StA1 + lambda_9_2*StA2 + lambda_9_3*StA3

# Second-order factor
Improve =~ gamma_1_1*Factor1 + gamma_1_2*Factor2 + gamma_1_3*Factor3 + gamma_1_4*Factor4
Irrel =~ gamma_1_1*Factor5 + gamma_1_2*Factor6 + gamma_1_3*Factor7
 
I will go back and test the example code over the weekend.

**Comment by DocGavin** [comment]
I think you guys have actually solved this 
i'm getting different results (sometime does not converge) but it is running as it should
