### ISSUE TITLE
JASP crashed

### ISSUE THREAD

**Issue by pyoka** [jasp-stats/jasp-issues#807]
* JASP version: 0.12.2
* OS name and version: Windows 10 (10.0)

* Analysis: 
* Bug description:
* Expected behaviour:

#### Steps to reproduce:

-----------------------------------------------------------------------

### Debug information:
**Engine # 0** process  is *running* and it's state is *idle*.
**Engine # 1** process  is *running* and it's state is *idle*.
**Engine # 2** process  is *running* and it's state is *idle*.
**Engine # 3** process *does not exist (anymore)* and it's state is *initializing*.

[Commit used](https://github.com/jasp-stats/jasp-desktop/commit/9bc9fb7d416745d6507714374619adfa3922db7e)

**Comment by boutinb** [comment]
Hallo @pyoka, could you give a clear reproduction path of your problem: does the crash occur when you just open JASP, or open JASP with a file, or when starting some analysis?

**Comment by JorisGoosen** [comment]
And could you perhaps add the logs? 
If you turn on logging in `file menu -> preferences -> advanced -> logging`.
There is also a button there that takes you straight to the logfiles.
