### ISSUE TITLE
Contingency coefficients

### ISSUE THREAD

**Issue by NikitaKhromov-Borisov** [jasp-stats/jasp-issues#811]
* JASP version: 0.12.2
 Win
* OS name and version: Win10
* Analysis: Contingency tables. 
-- 
* Bug description: sometimes phi coefficient is not calculated. See attached file. The report appears: Value could not be calculated - At least one row or column contains all zeros, whereas there are no such row or column 
* Expected behaviour: it should be calculated. Moreover, any parameter, as well as p-values, should be presented with at least TWO significant digits.
[FTO_HGLU56.zip](https://github.com/jasp-stats/jasp-issues/files/4801130/FTO_HGLU56.zip)

**Comment by vandenman** [comment]
Thanks for reporting the issue!

In the table, there is a footnote that explains why the value cannot be computed -- but the reason in the footnote is indeed incorrect. The (absolute value of the) phi coefficient can only be computed for 2x2 coefficient tables, at least in our current implementation. In your data set, `FTO` has 3 outcomes (0, 1, 2) and `HGLU56` has 2 outcomes (0, 1) so you have a 3 by 2 table of counts. 

If you do add a filter like so:
![image](https://user-images.githubusercontent.com/21319932/108340888-61590d00-71d9-11eb-963f-8a3157d7e7f4.png)

then you do get values in the table (although I'm not sure you'd want to ignore one outcome like that).

![image](https://user-images.githubusercontent.com/21319932/108340973-77ff6400-71d9-11eb-98a8-263bb8d077d4.png)

I'll adjust the footnote to display a more appropriate message.



Concerning:
> Moreover, any parameter, as well as p-values, should be presented with at least TWO significant digits.

You can customize this behavior by going to the menu in the top left, `Preferences`->`Results`->`Table options`

![image](https://user-images.githubusercontent.com/21319932/108341096-9a917d00-71d9-11eb-8584-baa2393ff999.png)

Note that JASP rounds to a particular number of digits, not to a number of significant digits.
