### ISSUE TITLE
credible estimates

### ISSUE THREAD

**Issue by NikitaKhromov-Borisov** [jasp-stats/jasp-issues#812]
* Enhancement: calculate and present Bayesian credible intervals, not frequentist confidence intervals. 
* Purpose: to have full Bayesian methodology, not it hybrid with the frequentist one. 
* Use-case:

**Is your feature request related to a problem? Please describe.**
 

**Describe the solution you'd like**
 

**Describe alternatives you've considered**
 

**Additional context**

**Comment by boutinb** [comment]
@EJWagenmakers could you answer this request?

**Comment by EJWagenmakers** [comment]
There are some analyses where the credible interval information is not as prominently displayed as we'd like. This will be handled in the revamp of the Bayesian procedures that we have planned -- should be done within a year or so.
