### ISSUE TITLE
Different CFA results with different JASP versions

### ISSUE THREAD

**Issue by ghost** [jasp-stats/jasp-issues#813]
Hello,
My lab was trying to run a CFA using the lavaan SEM capabilities in JASP, but we noticed something strange. We saw that, using the same exact data, syntax, and setting, we received noticeably different results when using two different versions of JASP. Additionally, we were unable to obtain Mardia’s coefficient using 0.12.2, with a message on the output stating that “Not all used variables are numeric. Mardia's coefficients not available.” I am not sure if any of this is because of missing data? The data was run using a Macbook Pro (macOS Mojave version 10.14.6) and on both JASP 0.10.2 and JASP 0.12.2. Please let me know what other information you may need in order to best advise. Thank you

**Comment by EJWagenmakers** [comment]
Thanks for reporting this.
@vankesteren : this may relate to another report about missing values, the one we got over email. Would be good to sort this out.
E.J.

**Comment by vankesteren** [comment]
It seems this happened in the rewrite of SEM @JohnnyDoorn? In any case, @jdraptis I'm working on a new version of the SEM analysis, this will be done relatively soon and include a fix for this! 

In the meantime, could you elaborate a little on the differences between the JASP versions? And do you have a lot of missing data?

**Comment by JohnnyDoorn** [comment]
Hi @jdraptis ,

Could you share the jasp file with us? That way we can take a closer look at this and verify it in R as well.

Kind regards,
Johnny
