### ISSUE TITLE
Audit Module: check the frequency of last digits

### ISSUE THREAD

**Issue by FelipeMAffonso** [jasp-stats/jasp-issues#815]
* Enhancement: in addition to Benford's law, it would be useful to check the frequency of last digits.
* Purpose: Improve fraud detection.
* Use-case: Example: http://datacolada.org/77

Thanks!

**Comment by koenderks** [comment]
@FelipeMAffonso If you want, you can preview the new feature by downloading the JASP nightly built from https://static.jasp-stats.org/Nightlies/ (the latest).

**Comment by FelipeMAffonso** [comment]
Hi @koenderks I had some trouble trying to use this feature. 

I generated the following dataset:


55.34
41.24
66.64
32.54
5.4
44454.4
68452.4
4554.4
9.4
774564.4
785453.4
878.4
3.7
3.8

The leading digit looks good:

![image](https://user-images.githubusercontent.com/57021043/87089266-2c78e680-c204-11ea-9c96-d9e18395780a.png)

But the last just doesn't seem right!

![image](https://user-images.githubusercontent.com/57021043/87089353-503c2c80-c204-11ea-8548-f0d9328bc9ce.png)

I can't understand where these numbers came from. I tried to make sense of them through the data, but I couldn't.

What I was actually wanting to be able to do would be to select the following:

First digit (ok)
First and second digit (ok, works)
Last DECIMAL (I was expecting to see a huge frequency of 4 (12 out of the 14 numbers), one 7, and one 8. The last decimal is important because in many situations one expects that these decimals are uniformly distributed.

But other interesting options would be:

Last digit that are NOT decimals (confounds with first digit if the number is <10.
First decimal
Second decimal...

and so on.

So for every "position" of the number

![image](https://user-images.githubusercontent.com/57021043/87089743-e708e900-c204-11ea-84ae-567a9f12b47a.png)

We could then draw the distribution of it. 

thanks!!

**Comment by FelipeMAffonso** [comment]
Of course, the categorization below assumes fixed positions. But it would be nice to have "first, second, ..., last", but these should be split by whether it's before or after the decimal point. To detect fraud, it's nice to see the last digit (after the decimal point) and see whether the distribution is uniform
