### ISSUE TITLE
It is impossible to refer to a to-be-create variable when using he r-version of the column-creator. 

### ISSUE THREAD

**Issue by MaxvanderVelde** [jasp-stats/jasp-issues#816]
JASP-Version: 0.12.2.0

* Enhancement: Allow the column creator(r-version) to use the to be created variable.
* Purpose: Increase ease of use and 
* Use-case:
In the example below, the to be created variable is named “New”. When I attempt to specify this variable as “New<-2*day1”, where day1 is a variable of the scale-measurement level, I get a warning message that states that a computed column cannot use itself. Given the way variable/column/vector creation works in R, this possibility seems intuitive and I would like to see this possibility added.  

![image](https://user-images.githubusercontent.com/67456660/85830745-628e8300-b78d-11ea-8fb1-60cb5441653a.png)

**Comment by AlexanderLyNL** [comment]
Ah yes, the assignment to the column name is automatic. If you change the code to 

`2*day1`

then that should do it. Please close this thread if this works out for you. 

Cheers,
Alexander

**Comment by MaxvanderVelde** [comment]
The main point of the request was to add the option to also compute it my specifying the to-be created variable. This would also be helpful in specifying if/else/else statements (making it more clear what is actually happening).

**Comment by AlexanderLyNL** [comment]
I have the following use-case in mind. You want to double a variable named `contNormal` which is positive or negative, but eventually you only want to retain the positive variables, and set the negative values to zero. To do so:

```
interimVar <- 2*contNormal
interimVar[interimVar > 0] <- 0
interimVar
```

The last statement in the R code is what gets assigned. I'm happy to provide the R code for other use-cases, if you describe them here.

**Comment by MaxvanderVelde** [comment]
Thank you, the example is clear!
