### ISSUE TITLE
The drag and drop column creator is awkward when computing variables made up from more than 2 existing variables.

### ISSUE THREAD

**Issue by MaxvanderVelde** [jasp-stats/jasp-issues#817]
* JASP version: 0.12.2.0
* OS name and version: Windows 10

* Bug description: 
When using multiple(more than 2) variables to create a new variable through the drag and drop version of the column-creator, brackets are created automatically and uncontrollably leading to confusing and, sometimes, incorrect notations for the to be conducted transformation. In the picture below I attempted to sum a few variable of the scale level of measurement, leading to seemingly randomly placed brackets. 
![image](https://user-images.githubusercontent.com/67456660/85831525-b8175f80-b78e-11ea-9215-02f2455c287e.png)

This becomes more problematic when conduct more than simple addition. Here I attempt to add the product of day1 and day2 to the product of day3 and day2 and the product of day3 and day1, leading to the following output. 
![image](https://user-images.githubusercontent.com/67456660/85831473-a7ff8000-b78e-11ea-9510-9bf30c274f19.png)

As you can see, the program does not allow(or it does not show that it is possible to) specific combinations of additions of products. How would I be allowed to add d1*d2 to the product of d3 and d2 and the product of d3 and d1? For me it is unclear whether I can, and if so, how to do so.

**Comment by AlexanderLyNL** [comment]
One way to do this is by selecting `*` to construct a product, then select `+` to construct the sum. In the `...` of the sum, you can add more than just one variable. Perhaps we should be clearer about this. To provide a brief overview, you can add into the `...` the following:
- variables `var1`
- just the operation, thus, just `...+...`
- variables and operations, such as, `var1 + var2,` which you can into `...` as a whole

Here's an example:

<img width="1360" alt="Screen Shot 2020-06-26 at 13 07 59" src="https://user-images.githubusercontent.com/10271675/85850960-1acc2380-b7ae-11ea-9695-4f9c508854a7.png">

Hence, in principle you can create the whole formula first, and then add the variables into the `...` afterwards. 

Please let me know if this works out for you. 

Cheers,
Alexander

**Comment by MaxvanderVelde** [comment]
I would indeed suggest adding some additional information somewhere in JASP(maybe under the "i" ?). Thank you!
