### ISSUE TITLE
It’s impossible to conduct transformations on variables that are not of the scale type through the non-r version of the column creator, making it difficult to create columns containing interactions and/or dummies.

### ISSUE THREAD

**Issue by MaxvanderVelde** [jasp-stats/jasp-issues#818]
* Enhancement: Allow transformation of categorical variables through the column creator
* Purpose: Allows to create dummies/interaction terms outside of analyses
* Use-case:
Often, either out of direct interest to the currently conducted study or to check assumptions(e.g. ancova) interactions terms are created and tested for significance. Furthermore, to provide a better “picture” of the data being used, they can be plotted. Sadly, it is impossible to create variables using a grouping variable, making the creation of an interaction term including such a variable impossible. Though it is possible to add interaction terms in most of the analyses, plotting and investigating single interactions appears to be impossible. It also makes it quite difficult to create things like dummies, since those are also often computed from non-scale-level variables. The existent solution is simply changing the measurement level of the variables, but this might prove to be counter-intuitive and counterproductive in a teaching environment. 
![image](https://user-images.githubusercontent.com/67456660/85831959-789d4300-b78f-11ea-9a3a-838ed9ac9947.png)

**Comment by JorisGoosen** [comment]
If you create a computed column with R-code, does that not give you ample opportunities to transform the data as you see fit?

As in, a scalar column "V1" can be converted easily to a two-level ordinal by the R code `ifelse(V1 < 0.5, "small", "big")` or something like that.

**Comment by AlexanderLyNL** [comment]
I think that there are multiple issues described in the first post: (1) the creation of dummy variables, which can be solved as described by what Joris suggested, and (2) interaction terms. 

I'm not sure if the screenshot refers to (2), but to visually check for a possible interaction, between day1 and music, I'd recommend going to Descriptives and split by music. 

Perhaps I'm missing the point here. If so, please provide us with a use-case with a jasp file, then I'll give a description on how I'd tackle this within JASP.
