### ISSUE TITLE
Making including/excluding the intercept in an analysis less easy

### ISSUE THREAD

**Issue by MaxvanderVelde** [jasp-stats/jasp-issues#819]
* Enhancement: Relocate the possibility to include/exclude the intercept in analyses 
* Purpose: To not confuse beginning statisticians 
* Use-case:
As we discussed, it might not be a good to idea to make it this easy to exclude the intercept through analyses, as it might confuse beginners. Given that it’s use is quite limited, the option seems to stand out a bit to much, given the fact that it often drastically changes the results (coefficients, R2 ect.) as shown in the pictures below. 

With intercept:
![image](https://user-images.githubusercontent.com/67456660/85832357-36283600-b790-11ea-9594-c3d24a7e8cd7.png)

Without intercept:
![image](https://user-images.githubusercontent.com/67456660/85832374-404a3480-b790-11ea-8f41-97493595d868.png)
[

](url)

**Comment by AlexanderLyNL** [comment]
Would it be acceptable if this option is under the "Component" and "Model Terms" block instead?

**Comment by Kucharssim** [comment]
> Would it be acceptable if this option is under the "Component" and "Model Terms" block instead?

@MaxvanderVelde @AlexanderLyNL I just tried this, moving the checkbox below the model terms section would look like this
![Screenshot 2020-06-26 at 13 28 24](https://user-images.githubusercontent.com/7093546/85852537-15bca380-b7b1-11ea-812a-5d4f96663d06.png)

In my view it is already an improvement, as it does not hit you in the eye right when you expand the section. I can bring this change while I also deal with https://github.com/jasp-stats/jasp-issues/issues/820. By the way, I would do the same change in the logistic regression as well. Does that sound good?

**Comment by MaxvanderVelde** [comment]
Sounds good to me!

**Comment by Kucharssim** [comment]
Great!

Sorry - I am reopening the issue so that I don't forget to put it inside JASP. I will close it once we are sure it's in.
