### ISSUE TITLE
Casewise diagnostics differ between JASP(Version 0.12.2.0) and SPSS (version:25.0.0.1 ) 

### ISSUE THREAD

**Issue by MaxvanderVelde** [jasp-stats/jasp-issues#820]
* JASP version: 0.12.2.0
* SPSS version: 25.0.0.1
* OS name and version: Windows 10
* Analysis: Casewise diagnostics for linear regression

* Bug description: 
The Casewise diagnostics presented by the two programs differ(other cases and values for the standardized residuals), while predicted values are equal.

JASP-Version:
![image](https://user-images.githubusercontent.com/67456660/85833014-586e8380-b791-11ea-98ed-c66654de567e.png)

SPSS-Version:
![image](https://user-images.githubusercontent.com/67456660/85833023-5c9aa100-b791-11ea-9472-c9f90f39135f.png)

* Expected behaviour:
I would expect the results to be the same

#### Steps to reproduce:
Ask for casewise diagnostics when conducting a linear regression analysis 

Sadly it seems impossible to add the JASP file?

**Comment by Kucharssim** [comment]
As far as I can see the difference is between the standardized residuals, right?

This is probably because SPSS reports standardized residuals, JASP reports studentized residuals (which is more appropriate since the variance of the errors is unknown). We should explain it in the helpfile though.

**Comment by MaxvanderVelde** [comment]
That explains it, thank you!

**Comment by AlexanderLyNL** [comment]
@MaxvanderVelde to add a JASP file to a thread you have to compress it into a zip file first before dragging it into the comment box.

**Comment by Kucharssim** [comment]
Sorry - I am reopening the issue so that I don't forget to put it inside JASP. I will close it once we are sure it's in.
