### ISSUE TITLE
Network analysis manual colors not affecting variable names

### ISSUE THREAD

**Issue by skollgrim** [jasp-stats/jasp-issues#821]
* JASP version: 0.12.2

* OS name and version: Windows 10
* Analysis: When using network analysis and enabling the network plot. The variable names (to the right of the nodes) should have a small dot indicating which group is what color. 
* Bug description: The dot which color should indicate the group is the same for all the variables variables when having manual color selected, but works as intended when not having manual color selected.
* Expected behaviour: The color of the dot next to the variable names should match how the groups are color coded.

#### Steps to reproduce:
1. Run network analysis with the same file as featured in your video "How to Perform a Network Analysis in JASP"
[https://www.youtube.com/watch?v=KacSF0TzoPg](url)
2. I've included an image of the bug and an image of how it works like it is supposed to when not selecting manual colors as well as the JASP file.
[Data and images.zip](https://github.com/jasp-stats/jasp-issues/files/4836253/Data.and.images.zip)

**Comment by vandenman** [comment]
Thanks for reporting this error!

I do believe it was reported before (https://github.com/jasp-stats/jasp-issues/issues/702#issuecomment-624862487)

Could you see if the issue persists with the latest nightly version of JASP? Available from http://static.jasp-stats.org/Nightlies/

**Comment by skollgrim** [comment]
Running the latest windows 64 bit stable zip nightly version does indeed solve the issue I reported, great stuff.

Another pet peeve I also have in the graphical options is the inability to select multiple variables I want to assign to a color or to a group, as it stands now I have to manually select every variable.

**Comment by vandenman** [comment]
> Running the latest windows 64 bit stable zip nightly version does indeed solve the issue I reported, great stuff.

Happy to hear that it works!

> Another pet peeve I also have in the graphical options is the inability to select multiple variables I want to assign to a color or to a group, as it stands now I have to manually select every variable.

I agree that it is a bit inconvenient. Perhaps @boutinb can think of a way to make that easier?

**Comment by boutinb** [comment]
I have made an apart issue (#827) for the assignment of a color to all selected variables.

This issue can be then closed.
