### ISSUE TITLE
Swedish letters not being outputed properly in Coefficient table

### ISSUE THREAD

**Issue by skollgrim** [jasp-stats/jasp-issues#822]
* JASP version: 0.12.2

* OS name and version: Windows 10
* Analysis: When doing a linear regression with variables with Swedish letters (Ä, Ö, Å) JASP should be able to output the letters.
* Bug description: The output table specifically for _coefficients_ has problems writing the variables with the Swedish letters, JASP can correctly output the letters in other tables but in this specific table it seems to mess up.

* Expected behaviour: JASP should be able to write the letters regardless of which table it is.

* With the image and the data file it should be fairly easy to understand the error and reproduce it.
[data and image.zip](https://github.com/jasp-stats/jasp-issues/files/4836403/data.and.image.zip)

* EDIT, when attempting today (with version 0.13) to import from a from a .csv containing Swedish letters, it did not recognize the letters at all straight from the first screen (data view)

**Comment by tomtomme** [comment]
Tested with 0.18.2 and all worked fine.
@skollgrim 
feel free to reopen if not fixed on your side.
