### ISSUE TITLE
Blurred font 

### ISSUE THREAD

**Issue by purushottamb** [jasp-stats/jasp-issues#823]
Hi,
Please help me with this issue. 
Since the latest update, the JASP interface on my screen has turned to blurred fonts.
Please find attached screenshot. It is really difficult to develop models. The strain on the eyes.
The previous version worked well. Now I can't find an earlier version on the website.
My Dell XPS display resolution is 3200 x 1800.
![2020-06-26 (3)](https://user-images.githubusercontent.com/38065814/85850420-0b000f80-b7ad-11ea-9f95-bcc40c0fb33b.png)

**Comment by boutinb** [comment]
When did you download this version?

**Comment by purushottamb** [comment]
probably a month ago.

**Comment by boutinb** [comment]
We have changed the version on Windows some weeks ago, that should solve this issue.

**Comment by purushottamb** [comment]
oh okay. 
I will check with the new install and let you know.

**Comment by purushottamb** [comment]
New Install worked well. 
This version has a clear font.
Thank you :)
