### ISSUE TITLE
Network plot resizing back to default size when changing it's options.

### ISSUE THREAD

**Issue by skollgrim** [jasp-stats/jasp-issues#824]
* JASP version: 0.12.2

* OS name and version: Windows 10
* Analysis: A minor annoyance, but I feel it's worth bringing it up.
* Bug description:  When in network analysis and you are using the network plot, making changes to the size of the network plot will not stay if you change it's options as it will output in the default size again.
* Expected behaviour: Be able to change the network plot options while still keeping the same size.

**Comment by JorisGoosen** [comment]
Aah yeah, this is an annoying thing indeed.

**Comment by boutinb** [comment]
@JorisGoosen Did you have a look to this issue? If not it has to be postponed to 0.15

**Comment by JorisGoosen** [comment]
Did not have a look but probably the dependencies aren't right and the plot is being rendered again or something like that.
But this seems like this could easily be postponed to 0.15 anyway.

**Comment by JorisGoosen** [comment]
@vandenman maybe this fits in with the ploteditingstuff youve been working on?

**Comment by JorisGoosen** [comment]
I've seen some hacky solutions for this by people adding invisible items to forms to store plotsizes in, maybe this could be generalized?

**Comment by vandenman** [comment]
So @JorisGoosen I could build in a hack for this particular plot, but the problem is indeed more general. Ideally, when refreshing any analysis the resized size of a figure should be used if it exists. In addition, we should add an option to reset the size of a figure back to its defaults (whatever was specified in the R analysis). The same mechanism might also be useful for plot editing.

**Comment by vandenman** [comment]
I've made an internal issue for this and I think it's high on our (at least on my) to-do list. I'm not sure when this will be finished, however.

**Comment by JorisGoosen** [comment]
Well, I think this would make our graph-editing edition a lot nicer if it is in there.
