### ISSUE TITLE
model plot not properly working 

### ISSUE THREAD

**Issue by syakinad** [jasp-stats/jasp-issues#825]
* JASP version: 0.12.2.0

* OS name and version: windows
* Analysis: mediation and visual modelling plot
* Bug description: his analysis terminated unexpectedly. 

Error in png(tmpFile): unable to start png() device

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.medPathPlot(modelContainer, options, ready)

.suppressGrDevice(semPlot::semPaths(object = po, layout = rbind(deps_l, medi_l, pred_l, conf_l), intercepts = FALSE, reorder = FALSE, whatLabels = ifelse(options$plotpars, 'par', 'name'), edge.color = 'black', color = list(lat = '#EAEAEA', man = '#EAEAEA', int = '#FFFFFF'), border.width = 1.5, edge.label.cex = 0.9, lty = 2, title = FALSE, sizeMan = round(8 * exp(-n_totl/80) + 1), legend = options$plotlegend, legend.mode = 'names', legend.cex = 0.6, nodeNames = decodeColNames(po@Vars$name), nCharNodes = 3))

png(tmpFile)
* Expected behaviour:terminate unexpectedly

#### Steps to reproduce:
1. Go to model plot
2. Click on parameter estimates
3. Scroll down to '

**Comment by boutinb** [comment]
@syakinad Please give an exact description (step by step) of what you are doing to get this error. If possible send also the data or the JASP file (in a zip format).

**Comment by Kucharssim** [comment]
Thank you for the report. As it turns out, there is a similar issue: https://github.com/jasp-stats/jasp-issues/issues/1194. Recently, we made a fix to this bug, so the it should be working properly in the next release version of JASP.

Please reopen the issue if it reoccurs in the future.
