### ISSUE TITLE
Program does not start on Elementary OS

### ISSUE THREAD

**Issue by asdeden** [jasp-stats/jasp-issues#826]
* JASP version: 0.12.2 installed via flatpak

* OS name and version: elementary OS 5.1.5 Hera
* Analysis: 
* Bug description: Program does not start.
* Expected behaviour:

The error code is below:

Setting special options for software rendering (aka safe graphics).
Making new argument list for Application startup: org.jaspstats.JASP --disable-gpu
Starting JASP

(process:2): Gtk-WARNING **: 15:12:55.698: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: 15:12:55.700: Failed to load module "pantheon-filechooser-module"
Gtk-Message: 15:12:55.726: Failed to load module "canberra-gtk-module"
Gtk-Message: 15:12:55.726: Failed to load module "canberra-gtk-module"
QIBusPlatformInputContext: invalid portal bus.
QApplication: invalid style override passed, ignoring it.
    Available styles: Breeze, Windows, Fusion
Desktop:	new LanguageInfo created: Language: '' qmFolder: '' and qmFilenames: ''
Desktop:	new LanguageInfo created: Language: 'English' qmFolder: '/app/bin/Resources/Translations' and qmFilenames: ''
Desktop:	new LanguageInfo created: Language: '' qmFolder: '' and qmFilenames: ''
Desktop:	findQmlFiles(qmlocation = /app/bin/Resources/Translations) called
Desktop:	Checking qm file: /app/bin/Resources/Translations/jasp_nl.qm
Desktop:	Language (30) not registered in LanguageModel, adding it now
Desktop:	new LanguageInfo created: Language: 'Dutch' qmFolder: '/app/bin/Resources/Translations' and qmFilenames: '/app/bin/Resources/Translations/jasp_nl.qm'
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid

Thank you very much.

**Comment by asdeden** [comment]
Dear Goosen,

Thank you for your reply. 

There is "Nederlands" instead of "Dutch" in "Language & Region" settings of Elementary OS. 
I both installed missing language and set my system language to "Dutch" by selecting "Nederlands". It still does not work. Could it be due to this name differece in the settings?

Terminal returned same error:
flatpak run org.jaspstats.JASP
Setting special options for software rendering (aka safe graphics).
Making new argument list for Application startup: org.jaspstats.JASP --disable-gpu
Starting JASP

(process:2): Gtk-WARNING **: 14:24:03.233: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: 14:24:03.235: Failed to load module "pantheon-filechooser-module"
Gtk-Message: 14:24:03.273: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:24:03.274: Failed to load module "canberra-gtk-module"
QIBusPlatformInputContext: invalid portal bus.
QApplication: invalid style override passed, ignoring it.
    Available styles: Breeze, Windows, Fusion
Desktop:	new LanguageInfo created: Language: '' qmFolder: '' and qmFilenames: ''
Desktop:	new LanguageInfo created: Language: 'English' qmFolder: '/app/bin/Resources/Translations' and qmFilenames: ''
Desktop:	new LanguageInfo created: Language: '' qmFolder: '' and qmFilenames: ''
Desktop:	findQmlFiles(qmlocation = /app/bin/Resources/Translations) called
Desktop:	Checking qm file: /app/bin/Resources/Translations/jasp_nl.qm
Desktop:	Language (30) not registered in LanguageModel, adding it now
Desktop:	new LanguageInfo created: Language: 'Dutch' qmFolder: '/app/bin/Resources/Translations' and qmFilenames: '/app/bin/Resources/Translations/jasp_nl.qm'
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid

**Comment by JorisGoosen** [comment]
Well, It shouldn't be necessary to set system language to dutch/nederlands. But on some systems there is a difference between a "locale" and a "language" so maybe you are still missing the "dutch locale".

It might be named "region" or something on your OS. 

But otherwise I can install elementary os somewhere and check it out. But Im not sure when I have time for that.

**Comment by JorisGoosen** [comment]
Hmm, I just installed Elementary and it already installed the dutch stuff for me. And, perhaps not so surprising, jasp worked.

After removing the dutch languagepacks and restarting it still works.

Could you run `locale -a` in a terminal and post the output here?

**Comment by asdeden** [comment]
Dear Goosen,

After getting driver problems with several other linux distros (Mint, Manjaro and MX Linux), I sadly switched back to Windows 10. My computer has AMD CPU and GPU. I will test Linux again in future, if new linux kernels provide better support for AMD hardware.

Thank you for your support and assistance.

**Comment by JorisGoosen** [comment]
Ah yes I know that pain.

My previous laptop had the same problem. I would have hoped that with the new opensource amd drivers these kind of problems would be gone. Ah well.
