### ISSUE TITLE
When a Variables List has an extra component, give the possibility to set this component to all selected variables

### ISSUE THREAD

**Issue by boutinb** [jasp-stats/jasp-issues#827]
This feature comes from a comment in #821
* Enhancement:
A Variables List may have extra component: a checkbox or a dropdown for example. It would be user-friendly to be able to select some variables, and by setting the value of one extra component of one selected variable, to set this value to all components to all selected variables.
* Purpose:
To set in one click all selected components instead of clicking them one by one.
* Use-case:
See #821 

**Is your feature request related to a problem? Please describe.**
See #821

**Comment by tomtomme** [comment]
I did refresh the analysis file from 821 and the legend looked fine.
So I guess this can be closed.
