### ISSUE TITLE
Failed Correlation Analysis

### ISSUE THREAD

**Issue by andreariccieu** [jasp-stats/jasp-issues#829]
This is the bug
I have a separate request (since you have the file) : *if possible* please suggest me if there is a **turnaround** to execute a PCA on these data . Many thanks!

* JASP version: 0.12.2

* OS name and version: MAC OSX 10.15.5
* Analysis: Correlation
* Bug description: 
Error in names(result) <- statsNames: 'names' attribute [5] must be the same length as the vector [3]

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.corrMainResults(jaspResults, dataset, options, ready)

.corrComputeResults(jaspResults, dataset, options, ready)

.corr.test(x = data[, 1], y = data[, 2], z = condData, method = 'pearson', alternative = alt, conf.level = options$confidenceIntervalsInterval)

* Expected behaviour:

#### Steps to reproduce: 
[AsiaPacific-Table 1.csv.zip](https://github.com/jasp-stats/jasp-issues/files/4847122/AsiaPacific-Table.1.csv.zip)

]

Select all DEL.(country name)
Execute correlations

**Comment by boutinb** [comment]
@vandenman I can reproduce the error even in 0.13 beta

**Comment by Kucharssim** [comment]
I think I might know where is the issue

**Comment by andreariccieu** [comment]
thanks for trying hard guys !

**Comment by TimKDJ** [comment]
Thanks for bringing this to our attention, it will be fixed in version 0.13
