### ISSUE TITLE
Engine crashed error

### ISSUE THREAD

**Issue by BLueBLack053** [jasp-stats/jasp-issues#830]
* JASP version: 0.12.2

* OS name and version: Windows 10
* Analysis: SEM (and any other analysis)
* Bug description: "The engine crashed while trying to run this analysis"
* Expected behaviour: 

#### Steps to reproduce:
1. Open ANY DATA
2. Click on ANY ANALYSIS
3. Just I can see "The engine crashed while trying to run this analysis" error message on Results Screen

![20200630_172346](https://user-images.githubusercontent.com/67629510/86107482-dbc70680-bafc-11ea-8bb8-82fde9330dca.jpg)

**Comment by JorisGoosen** [comment]
Sorry to hear the engine keeps crashing for you...

We are working on releasing a new version and a demo version can be found here: https://static.jasp-stats.org/Nightlies/WindowsZip/JASP-nightly-stable-1742c19cf71223c23a8cf5901a2da0206d0ad047.zip

Maybe you could try that one out and see if the problem is solved there?

If the engine keeps crashing it would be good to upload the logs. They can be found in preferences -> advanced.

**Comment by BLueBLack053** [comment]
i did download demo version and i removed JASP already installed with install program

i copied and pasted files from folder of demo version to folder that is originally JASP folder(in program files)

but engine keeps crashing, so i upload the logs
[JASP 2020-07-01 09_38_42 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/4855011/JASP.2020-07-01.09_38_42.Desktop.log)

The logs except Desktop.log(logs of Engine 1~3) is empty file.

Also, i have additional question
Is there basic specifications of computer to run JASP ?
Please tell for me to check specifications of my computer

**Comment by JorisGoosen** [comment]
Aah, it wasn't necessary to copy those files to program files, you could have extracted that folder anywhere and it would've worked. Well, in your case only partially apparently.

So yeah, it seems that the engines crash immediately on starting...

Could you try something else?
Download http://www.dependencywalker.com/ and with it "open" `JASPEngine.exe`.
Then when that is finished loading could you save the log as a `*.dwi` and attach that here?

**Comment by BLueBLack053** [comment]
Actually, can this file work normally, even though i have windows 10?
That link said we can run 'dependency walker 2.1' with windows XP, and there aren't any words about windows 10

first of all, i upload the very logs(*.dwi).
Is this logs enough to check my problem?

In this site, I cannot upload file with *dwi form
So i upload zip file
Please check my logs  X(
[JASPEngine.zip](https://github.com/jasp-stats/jasp-issues/files/4857141/JASPEngine.zip)

Sincerely thanks to your advice

**Comment by JorisGoosen** [comment]
Yes of course! 
The site is just not updated very often I think :p

I will have a look at the log later today, when I have time to get Windows booted.
Thank you for responding so quickly.

**Comment by JorisGoosen** [comment]
Ok, so it seems that JASPEngine.exe can find all required dlls, that is good.

But, could you maybe restart JASP and then send me the 5 logfiles?
Because right now the actual first log you send me does not include the startup.

**Comment by BLueBLack053** [comment]
Like this?

i just restart JASP, and before opening save data, i immediately load logs and send them to you

[JASP 2020-07-02 00_21_12 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/4858728/JASP.2020-07-02.00_21_12.Engine.1.log)
[JASP 2020-07-02 00_21_12 Engine 2.log](https://github.com/jasp-stats/jasp-issues/files/4858729/JASP.2020-07-02.00_21_12.Engine.2.log)
[JASP 2020-07-02 00_21_12 Engine 3.log](https://github.com/jasp-stats/jasp-issues/files/4858730/JASP.2020-07-02.00_21_12.Engine.3.log)
[JASP 2020-07-02 00_21_12 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/4858732/JASP.2020-07-02.00_21_12.Desktop.log)
[JASP 2020-07-02 00_21_12 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/4858733/JASP.2020-07-02.00_21_12.Engine.0.log)

**Comment by boutinb** [comment]
I see that you have a korean language on your computer. I am not sure if it the cause of your problem, but in case, can you change the language setting of your PC to english, or do you have access to a non-korean PC?

**Comment by BLueBLack053** [comment]
Oh, yeah
i change the language setting of my PC to english, and restart JASP and upload logs again
[JASP 2020-07-02 00_48_09 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/4858916/JASP.2020-07-02.00_48_09.Desktop.log)
[JASP 2020-07-02 00_48_09 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/4858917/JASP.2020-07-02.00_48_09.Engine.0.log)
[JASP 2020-07-02 00_48_09 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/4858918/JASP.2020-07-02.00_48_09.Engine.1.log)
[JASP 2020-07-02 00_48_09 Engine 2.log](https://github.com/jasp-stats/jasp-issues/files/4858919/JASP.2020-07-02.00_48_09.Engine.2.log)
[JASP 2020-07-02 00_48_09 Engine 3.log](https://github.com/jasp-stats/jasp-issues/files/4858920/JASP.2020-07-02.00_48_09.Engine.3.log)

**Comment by JorisGoosen** [comment]
Could you check the region settings?

I think what I see in the log is that it tries to set it to English (United States) like you see in for instance this tutorial: https://www.isunshare.com/windows-10/change-system-locale-in-windows-10.html

Is that what you see as well?

**Comment by BLueBLack053** [comment]
Umm, yeah

i understand "change the language setting of your PC to english" means i need to set the language to English (United States), which boutinb said.

And now, i follow your link(@JorisGoosen) and change my region settings of my computer too

And this is JASP log again

[JASP 2020-07-02 01_15_34 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/4859064/JASP.2020-07-02.01_15_34.Desktop.log)
[JASP 2020-07-02 01_15_34 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/4859065/JASP.2020-07-02.01_15_34.Engine.0.log)
[JASP 2020-07-02 01_15_34 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/4859066/JASP.2020-07-02.01_15_34.Engine.1.log)
[JASP 2020-07-02 01_15_34 Engine 2.log](https://github.com/jasp-stats/jasp-issues/files/4859067/JASP.2020-07-02.01_15_34.Engine.2.log)
[JASP 2020-07-02 01_15_34 Engine 3.log](https://github.com/jasp-stats/jasp-issues/files/4859068/JASP.2020-07-02.01_15_34.Engine.3.log)

**Comment by BLueBLack053** [comment]
Oh, my!

Now i can run my JASP normally!

i think someone can run JASP in the region settings "English(United Kingdom)" of his of her computer !

**Comment by BLueBLack053** [comment]
> Could you check the region settings?
> 
> I think what I see in the log is that it tries to set it to English (United States) like you see in for instance this tutorial: https://www.isunshare.com/windows-10/change-system-locale-in-windows-10.html
> 
> Is that what you see as well?

I'm sorry to plus new question

i got "unable to start png() device" message in path diagram when i try to run SEM...

Please can you answer to me? or i need to write new issue?

**Comment by JorisGoosen** [comment]
Aah!

So the region is related to it somehow. Good to know!

Ill change the other issue into your Sem question.

**Comment by JorisGoosen** [comment]
In the next version you will be able to use your normal account.
