### ISSUE TITLE
JASP mixing up columns from csv datafile

### ISSUE THREAD

**Issue by cmgreene** [jasp-stats/jasp-issues#831]
* JASP version: 0.12.2
* OS name and version: MacOS Catalina version 10.15.5
* Analysis: All
* Bug description: This is a bit odd, so bear with me. I have a largeish data file (~3700 cases, 120 variables) in csv format. I've been working with this file in JASP for several days with no issues (apart from very, very slow estimation of correlations, which I believe has been reported elsewhere). Today, I suddenly started getting errors for all my saved analyses (correlations, regressions, ANOVAS etc.) and realised that all of my scale variables had been recoded as nominal, even though I hadn't changed anything in the source datafile. When I scrolled down through the JASP file, I realised that 1) the JASP file now contains fewer cases than the CSV file (2329 vs. 3746), and 2) JASP had mixed up the columns, so that values from variable X were appearing in the column for variable Y. 

I've attached screenshots illustrating this for the variable age; as you can see, in the csv file (in Excel) the values are all numeric, but in JASP some text responses from another column have been transposed into the age variable. I tried closing JASP and reopening the file, but the issue persists. I also tried making changes to the csv file and saving; if I alter one or two values, JASP updates that value OK (but with the same issues as before). If I try to update a whole column, this just causes JASP to crash with no warning. 

![CSV screenshot](https://user-images.githubusercontent.com/67635411/86118807-48281280-bac9-11ea-965a-11449002598a.png)
![JASP Screenshot](https://user-images.githubusercontent.com/67635411/86118815-4a8a6c80-bac9-11ea-96ea-51790d4b98a4.png)

I'm happy to email my datafile it that will help (I don't know what email address to send it to) but I don't want to upload it publicly as it contains identifiable information. 

I'm aware that I can just start all over again with a new JASP file, but then I will lose several days worth of saved analyses which I will have to run again, which I'm reluctant to do if the same issue is likely to recur. 

Thanks!

**Comment by cmgreene** [comment]
Update: I tried saving the csv file under a new name and opening a fresh JASP file, but the same issues occurred. It's worth noting that I can open this file without any issues in SPSS and other programs - the correct number of cases are present and the variables are in the correct columns. The issue only occurs in JASP.

**Comment by JorisGoosen** [comment]
This certainly sounds odd!

I could have a look as to what is going wrong. You can reach me at "j.c.goosen at uva.nl" for the csv. 

I do already see something that could be going wrong here though. It seems there are textfields in the data. It might be that these contain for instance comma's. And seeing how CSV stands for Comma Separated Value this might be causing the problem. Some software tries to limit these problems by adding quotes around whatever textvalue is going into a csv, but this might actually also go wrong in certaing scenarios.

However, you state that it *can* be loaded correctly in other software, like SPSS. So it must be formatted in a way that some other program could read it.

**Comment by JorisGoosen** [comment]
Have you tried this out in 0.13.1 ?
And without any response from you I will not be able to debug this problem.

**Comment by JorisGoosen** [comment]
I got a response from @cmgreene in the mail stating:

> Sorry for my delayed reply, I completely missed your first email! It obviously slipped through the cracks on a busy day. Thanks very much for getting back to me. 
> I'm attaching the .jasp and .csv files. when I reopened this file today, it updated and while there are still issues they are with different variables. From my earlier screenshot, you'll have seen that the data in the 'age' column was incorrect. Now that column is fine, but the 'education' variable has been altered in the JASP file relative to the csv file. You'll also see that most of the saved analyses now have empty fields; apparently the relevant variables were removed when the file updated.

> As you can see, the csv file is fine, and it worked with spss, r and other programs, so the issue does seem to be specific to jasp. Also, the file was working perfectly for at least a week before it suddenly developed these glitches out of nowhere. You're right that there are some variables containing commas, but those are represented as text (which is fine for my purposes) and they weren't the variables presenting problems - those were (or should be) entirely numerical.

> I was actually able to 'rescue' my data by saving it all as a new csv file and reopening in a new jasp window, so it's not the end of the world, but I lost about a week's work as I had to redo all my analyses from scratch. I've been loving jasp, but this is the kind of issue that would make me reluctant to start a big project with it again if I couldn't trust that my data and analyses would stay where I put them!

Sadly enough the attachment got lost somewhere along the way and Ive requested it again, in the original format.

**Comment by EJWagenmakers** [comment]
Hmm. So what can we do to prevent such mishaps in the future? Going to the file history and using the older version of JASP ought to be enough to recover all analyses of course, but perhaps there is a better solution -- let's discuss on Slack.

**Comment by JorisGoosen** [comment]
I'm afraid I don't have enough information to know what is going on. Did @cmgreene use a new version of JASP? Or just reload the same file in the same JASP?

**Comment by cmgreene** [comment]
I hadn't changed anything - same version of jasp, same csv file, just one
day I opened it up and got error messages for all my analyses and found
that the data had been corrupted. I just reopened it with jasp version
0.13.1, but the same issue is present.

Ciara Greene, BA PhD PGDip FPsyS
Associate Professor
School of Psychology
University College Dublin
Belfield
Dublin 4
Ireland
Tel: +353 (0)1 7168334


  ucdattentionmemory.com

**Comment by JorisGoosen** [comment]
I should mention here that I did get the csv file back then and should definitely look into this.

**Comment by JorisGoosen** [comment]
So I've looked into the files that @cmgreene uploaded half a year ago and I can only surmise that what could've happened is that maybe the datafile was still linked to the JASP-file and auto-synching was on.
Then when Ciara was editing the original csv-file it might have triggered JASP to reload the csv while maybe a comma or quote was missing, extra or something.

This because I see entries like: 
![image](https://user-images.githubusercontent.com/29062713/104928076-81ab6700-59a2-11eb-8703-661a9cc14df2.png)

Where it looks a lot like a part of the csv was interpreted as being part of the string in that column. Instead of it being several entries. And I'm guessing that once that initial mistake was loaded into jasp-file the file was then quite broken indeed..

I'm afraid I cannot think of another scenario.

Of course I wonder if my scenario is possible but because it took me this long to get back to this issue I can imagine that Ciara also can't remember the exact scenario back then.
My suggestion for avoiding these kind of problems would be to turn "Preferences -> Data -> Synchronize automatically on data file save" off. That way at least you can be sure that the data won't magically change.

We will be working on supporting data editing inside JASP in the near future and hopefully we can turn the synchronization off by default then.
