### ISSUE TITLE
Error when performing Multi group SEM

### ISSUE THREAD

**Issue by krutcher7069** [jasp-stats/jasp-issues#834]
* JASP version: 0.12.2.0

* OS name and version: Windows
* Analysis: Multi group SEM
* Bug description: 
![image](https://user-images.githubusercontent.com/67669189/86195617-8251ec80-bb7b-11ea-89b3-66ec52b66751.png)
I was running a multi group SEM. I had 2 latent variables, with 1 variable predicting another. My grouping variable has 2 levels: high and low. Everything was fine until I asked the program for R-squared. The red box immediately popped up. I wish I could attach a JASP file here. I tried doing that but it didn't seem to work (I even turned my JASP file into a zip file).

* Expected behaviour: Please take care of the bug

**Comment by JorisGoosen** [comment]
@krutcher7069 we would like to fix this bug of course. But could you perhaps try to attach the file again?
This uhm, does usually work. As in, it has never not worked for me.

**Comment by krutcher7069** [comment]
I have been trying to generate the R-squareds, but nothing seems to work.
It really is wonderful that you are willing to help with this problem.
Thank you very much!

**Comment by AlexanderLyNL** [comment]
Could you please add the jasp file as a zip to this thread, by going to https://github.com/jasp-stats/jasp-issues/issues/834? Otherwise, we can't see what's happening.

**Comment by krutcher7069** [comment]
I'm sorry. I have added the jaspp file as a zip.

**Comment by AlexanderLyNL** [comment]
Unfortunately, it doesn't work by mail. Could you please add the jasp file to the thread instead?

**Comment by krutcher7069** [comment]
I think it works now. 

Thank you for your patience.


[Need help (Thank you).zip](https://github.com/jasp-stats/jasp-issues/files/4890515/Need.help.Thank.you.zip)

**Comment by juliuspf** [comment]
@krutcher7069, I am very sorry for the late response. The file you sent works in the latest version of JASP, so I will close this issue now :)
