### ISSUE TITLE
JASP is not producing results tables

### ISSUE THREAD

**Issue by LeighAnnVaughn** [jasp-stats/jasp-issues#837]
* JASP version: 0.13.0.0 (this also happened with 0.12.0.0)

* OS name and version: Windows
* Analysis: all
* Bug description: In earlier versions of JASP and in the instructional videos, clicking on the type of analysis that you want to run automatically brings up a table that gets populated with your variables and results. The current and previous versions of JASP (indicated above) show no tables at any point.  
* Expected behaviour: I have a computer with JASP version 0.11.1.0, and this version of JASP works fine. 

#### Steps to reproduce:
1. Go to '...' open JASP, open any data file
2. Click on '....' any analysis
3. Scroll down to '....' anything you want to include in the analysis
4. See error: the error is that JASP produces no tables at all

**Comment by Liesbeth-Tip** [comment]
Same is happening with me, no output.

**Comment by JorisGoosen** [comment]
Sorry to hear it and too bad we didn't fix the error in two versions.

Let's see if we can do something about it. 

Could you both try to run an analysis in JASP after turning on "log to file" in preferences -> advanced. And then attach the "Desktop" logfile here?

Besides that, do you know which GPU is in your computer?

**Comment by LeighAnnVaughn** [comment]
Hi, Joris.
Thanks for your reply. I have attached the log files from the one minute of work I attempted to do on JASP, in which I opened two data files. Today, in addition to JASP producing no tables, it also crashed while trying to run the drag and drop filter. I had not tried to use that filter. Each time I opened a file, JASP automatically tried to use the filter and then crashed.

My computer's GPU is Intel(R) UHD Graphics 630.

Best wishes,
Leigh Ann

******************************
Leigh Ann Vaughn
Professor
Department of Psychology
1119 Williams Hall
Ithaca College
Ithaca, NY 14850-7290
(607) 274-7353
http://faculty.ithaca.edu/lvaughn/
******************************


________________________________

**Comment by JorisGoosen** [comment]
Thank you for the response Leigh Ann, but sadly enough GitHub does not copy the attachments from email-responses to issues.
Would you be so kind as to attach the log here in the issue: https://github.com/jasp-stats/jasp-issues/issues/837

**Comment by LeighAnnVaughn** [comment]
Thanks for letting me know. I trust that the following files attached correctly.

[JASP 2020-07-07 07_17_00 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/4884809/JASP.2020-07-07.07_17_00.Engine.1.log)
[JASP 2020-07-07 07_17_00 Engine 2.log](https://github.com/jasp-stats/jasp-issues/files/4884810/JASP.2020-07-07.07_17_00.Engine.2.log)
[JASP 2020-07-07 07_17_00 Engine 3.log](https://github.com/jasp-stats/jasp-issues/files/4884811/JASP.2020-07-07.07_17_00.Engine.3.log)
[JASP 2020-07-07 07_18_13 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/4884812/JASP.2020-07-07.07_18_13.Desktop.log)
[JASP 2020-07-07 07_17_00 Engine 1 - Copy.log](https://github.com/jasp-stats/jasp-issues/files/4884813/JASP.2020-07-07.07_17_00.Engine.1.-.Copy.log)
[JASP 2020-07-07 07_18_13 Engine 0 - Copy.log](https://github.com/jasp-stats/jasp-issues/files/4884814/JASP.2020-07-07.07_18_13.Engine.0.-.Copy.log)
[JASP 2020-07-07 07_18_13 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/4884815/JASP.2020-07-07.07_18_13.Engine.0.log)
[JASP 2020-07-07 07_17_00 Engine 2 - Copy.log](https://github.com/jasp-stats/jasp-issues/files/4884817/JASP.2020-07-07.07_17_00.Engine.2.-.Copy.log)
[JASP 2020-07-07 07_18_13 Engine 3.log](https://github.com/jasp-stats/jasp-issues/files/4884818/JASP.2020-07-07.07_18_13.Engine.3.log)
[JASP 2020-07-07 07_17_00 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/4884821/JASP.2020-07-07.07_17_00.Desktop.log)
[JASP 2020-07-07 07_17_00 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/4884822/JASP.2020-07-07.07_17_00.Engine.0.log)

**Comment by JorisGoosen** [comment]
The files got through and were quite informative.

In fact, it seems that something in the naming of the columns of your data let the engine (where we run the code for analyses and filters) crash somehow. I think.

Now, I see in the logfile the names of the columns because you imported them from spss/stata/sas and that importcode describes what it does. The actual data is not included of course.

I don't know if it is possible for you to share the data-file with me? If not I can work around it by making a dummy file with the columnnames but that would be somewhat more work than just importing a readymade file. But if this is not possible I fully understand and will just have to make something up and see if I can reproduce  this myself.

@Liesbeth-Tip your problem sounds similar. Perhaps you could also upload your logfiles?

**Comment by JorisGoosen** [comment]
And in case you want to mail it you can reach me at "j.c.goosen at uva.nl".

**Comment by JorisGoosen** [comment]
It seems I cannot reproduce this problem with a dummy dataset based on just the columnnames.

It would be incredibly helpful if I could have the data you used to figure out what is going wrong here.

**Comment by LeighAnnVaughn** [comment]
Thanks, Joris. I'll email you a data file directly.

******************************
Leigh Ann Vaughn
Professor
Department of Psychology
1119 Williams Hall
Ithaca College
Ithaca, NY 14850-7290
(607) 274-7353
http://faculty.ithaca.edu/lvaughn/
******************************

________________________________

**Comment by JorisGoosen** [comment]
Aah, ok so the problem is caused by the fact that the column between `debtimer_Click_Count` and `af1r` has no name in JASP.
It also seems to have no information or labels in it.

I will be making JASP a little bit more resilient with regard to this kind of data, but in the meantime you could work with the data if you remove that column from the sourcedata.

**Comment by JorisGoosen** [comment]
Ow, the column "transformed_variables" somehow doesn't seem to get a name, never mind my workaround in that case. I will just have to fix it here.

**Comment by JorisGoosen** [comment]
Removing that column should still work though, as the problem seems to be that it contains no data whatsoever.

**Comment by LeighAnnVaughn** [comment]
Hi, Joris.
Thank you! How fascinating that this was the cause of the problem. It is easy for me to take out that empty column, and JASP works fine when I do.

Best wishes,
Leigh Ann

******************************
Leigh Ann Vaughn
Professor
Department of Psychology
1119 Williams Hall
Ithaca College
Ithaca, NY 14850-7290
(607) 274-7353
http://faculty.ithaca.edu/lvaughn/
******************************

________________________________
