### ISSUE TITLE
Changing type of column while ANOVA, ANCOVA, CFA is active leads to crash

### ISSUE THREAD

**Issue by jdebeer2005** [jasp-stats/jasp-issues#839]
* JASP version:0.13

* OS name and version:win 10
* Analysis: trying to change variable type from nominal to scale and JASP closes - Repeatedly
* Bug description:trying to change variable type from nominal to scale and JASP closes - Repeatedly
* Expected behaviour:  Change variabel type smoothly
[Raw Data from Chris Lord.zip](https://github.com/jasp-stats/jasp-issues/files/4870825/Raw.Data.from.Chris.Lord.zip)
[Raw Data from Chris Lord.zip](https://github.com/jasp-stats/jasp-issues/files/4870828/Raw.Data.from.Chris.Lord.zip)

**Comment by jdebeer2005** [comment]
JASP team -this is really a bad feature.  If the data is not recognized as scalar and put in a nominal, and we cannot change, that is a bad deal.  Essentially I am locked out of my analysis.

**Comment by EJWagenmakers** [comment]
I can confirm that changing "FillWt" from ordinal to continuous indeed makes JASP crash. Nothing appears to be wrong with FillWt (Descriptives returns a mean etc., no missing values). This is strange; let's check the scale transformations in general.
@jdebeer2005 : thanks for reporting this and adding the .jasp file. We'll fix this asap (together with another few mishaps).
E.J.

**Comment by jdebeer2005** [comment]
Thanks, I had to un-install V132, and re-install v12

**Comment by AlexanderLyNL** [comment]
This seems to be a Windows thing. It doesn't crash on mac. @FBartos could you check? Also could you check if this occurs on the nightly or zipped version?

**Comment by FBartos** [comment]
I tried both the release and zipped nightly version and I can load and change the variable types:
![image](https://user-images.githubusercontent.com/38475991/86498509-63737600-bd86-11ea-8fdc-498ef00d0932.png)
but it crashes when I open the zipped .jasp, and change the variable afterward.

I did some more experimentation and it seems to crash using these steps:
1) load the .csv dataset
2) open ANOVA, set "PickUp" as dependent variable and "Prcker" as Fixed factor
3) go to variables overview, and change FilWt to scale

**Comment by djdekker** [comment]
Here is another data set with a similar (or the same?) problem in JASP 0.13:

1. load the .csv dataset
2. open ANOVA (no need to set Dependent Variable or Fixed Factors)
3. go to variables overview and change "teacher" to Nominal  =>  CRASH

[ANOVA_teachers.csv.zip](https://github.com/jasp-stats/jasp-issues/files/4873016/ANOVA_teachers.csv.zip)

**Comment by FBartos** [comment]
I did some more testing and it's not dependent on the dataset (it can be reproduced with the debug dataset as well).

From the main ribbon, I found that the following analyses crash if they are opened while the variable type is being changed:

- ANOVA
- ANCOVA
- Confirmatory Factor Analysis

**Comment by AlexanderLyNL** [comment]
Thanks for testing this out, this is really helpful. I can reproduce this error on mac now. I wonder if it's related to some qml edits we did recently. @FBartos it's weekend, don't forget to relax.

**Comment by JorisGoosen** [comment]
Aah yes, this crashes everywhere...

**Comment by jdebeer2005** [comment]
Team, JASP still crashes when changing from scale to nominal values on the data set I sent in.  I reloaded a fresh copy of 0.13 on to Windows 10, started to run a mixed effects model and wanted to change parada from scale to nominal, and JASP stopped.
08:02 Jul 7, 2020, west Coast US time

JDB

**Comment by AlexanderLyNL** [comment]
Hi JDB,

It's correct that it's not fixed in the version you downloaded, but it's fixed in our development plan. Once we fix up some other smaller issues, we will release a new version. 

Cheers,
Alexander

**Comment by jdebeer2005** [comment]
Ah Ha, Sorry, I thought when it was closed it was fixed.  I can wait.

Thanks

JDB
