### ISSUE TITLE
Matching groups of data

### ISSUE THREAD

**Issue by Pokroy** [jasp-stats/jasp-issues#84]
## Environment (for enhancement requests)
* Enhancement: one to one match of data samples in order to match the baseline characteristics of two data groups as closely as possible
*Purpose: When the items in the various experimental groups differ on one or more variables, but need to be matched for all other factors that can affect the outcome measure, selecting the best-matching items from larger sets of candidate items is necessary. A program to match the data on a one-to-one basis readily solves this problem. See the reference: Match: a program to assist in matching the conditions of factorial experiments. Behavior Research Methods, 2007.

**Comment by tomtomme** [comment]
Just adding the link to the paper: https://link.springer.com/content/pdf/10.3758/BF03192992.pdf
And assigning johnny and JT since this seems related to ANOVA (factorial designs in general) and Quality Control modules

**Comment by tomtomme** [comment]
@Pokroy 
I just realized that this is a part duplicate of https://github.com/jasp-stats/jasp-issues/issues/73
And probably a complete duplicate of https://github.com/jasp-stats/jasp-issues/issues/2052
Do you agree?
Then we could close this one and discuss over there.
