### ISSUE TITLE
JASP keeps crashing on MacOS (intel iris GPU) even in safe graphics mode

### ISSUE THREAD

**Issue by tegedik** [jasp-stats/jasp-issues#843]
* JASP version: 0.13

* OS name and version: MacOS Catalina  10.15.5
* Analysis: any analysis, even scrolling in the program
* Bug description: JASP crashes unexpectedly
* Expected behaviour:

#### Steps to reproduce:

I know this is an ongoing issue for macbooks with Intel Iris GPU, but even safe graphics mode does not work anymore (at least for me). I also disable animations, but JASP keeps crashing frequently and unexpectedly. Is there any other way to keep these crashes at minimum?

**Comment by JorisGoosen** [comment]
Hey tegedik, sorry to hear JASP is crashing for you so badly.

We sadly don't really know what causes it. No that we've released 0.13 I was thinking of upgrading some of the libraries that we use. Maybe one of those causes this problem.

I can send you a link with a testversion once we have one and then you can help us out by telling us if it stops crashing, or at the very least crashes less..

Sorry I cannot help you out more with this problem now. It is a rather frustrating bug for sure...

**Comment by tegedik** [comment]
Thank you, I will be waiting for a test version. I guess this bug affects a small group of users and is not as pressing as other issues, but I really liked to use JASP. It is a great software and gets better every day (thanks!).

**Comment by JorisGoosen** [comment]
Well it is pressing, it is just that the only way I can think of hopefully fixing this implies upgrading many things so we wanted to wait for this 0.13 release. I will upload the testversion somewhere today and then let's see if we can make it a lot better today...

**Comment by JorisGoosen** [comment]
@tegedik would you like to give http://static.jasp-stats.org/Nightlies/MacOS/JASP-nightly-qt5.15-022ce5da27692d754dfa14d69f9d74bb28b5e57c.dmg a go?

It isn't signed or notarized so Apple will complain, or suggest you throw it in the trashcan... But if you choose "open" from the contextmenu twice it will actually allow you to open it.

**Comment by JorisGoosen** [comment]
Ah, and another version of JASP, but if the first one does not crash anymore there is no point in trying this one: http://static.jasp-stats.org/Nightlies/MacOS/JASP-nightly-noQuartz-2c2b3a6466f2afcdf449f02ec113cb1d98ceb56a.dmg

**Comment by AlexanderLyNL** [comment]
> @tegedik would you like to give http://static.jasp-stats.org/Nightlies/MacOS/JASP-nightly-qt5.15-022ce5da27692d754dfa14d69f9d74bb28b5e57c.dmg a go?
> 
> It isn't signed or notarized so Apple will complain, or suggest you throw it in the trashcan... But if you choose "open" from the contextmenu twice it will actually allow you to open it.

This works well for me and it feels much more stable on my macOS 10.13.6 (High Sierra). I'm not sure how easy it is to port the Windows development to Qt 5.15 as well. Or we can just wait until Frans and Bruno are back to help out with that.

**Comment by JorisGoosen** [comment]
Windows is easy, in fact it is already done and standing ready on the nightlies. Transitioning flatpak will be harder. But if you both get way less crashes then before this is a very good sign and I will move it into stable.

**Comment by tegedik** [comment]
Thank you @JorisGoosen, I tried both versions. The version ("qt5.15") in the first link (https://github.com/jasp-stats/jasp-issues/issues/843#issuecomment-654871944) worked really well for me. I ran several analyses and JASP did not crash (I find a bug in the mixed models module, but I will post another report for that). 

Unfortunately, the second version ("noQuartz", https://github.com/jasp-stats/jasp-issues/issues/843#issuecomment-654884519) did not work at all. I got the error message: "The engine crashed while trying to run this analysis..." and can't do any analysis.

I will continue using the version in the first link.

**Comment by AlexanderLyNL** [comment]
Thanks for testing this for us! 

Is the bug you found in Bayesian (G)LMM? Or in classical? This is expected, and there's no need to report this, because you're on pre-Catalina. If the bug is in classical (G)LMM, then we would appreciate a bug report.

**Comment by tegedik** [comment]
It is both on Bayesian and classical GLMM. A very strange bug. I will post a full request, but shortly: when there is a missing value on the binary outcome (even a single NA), the analysis with binomial family and logit link function throws this error: "Generalized linear mixed model with binomial family and logit link function requres [sic] that the dependent variable contains only 0 and 1."

**Comment by JorisGoosen** [comment]
So Im afraid I cannot help with the bug you found. But I will be replacing the installers on the website with new ones that use qt 5.15, you will need the preCatalina version. This might solve some of the problems in MM.

**Comment by AlexanderLyNL** [comment]
That will solve the Bayesian LMM problem, but not the problem that the error message is not informative enough. Thanks for also reporting the bad error message. @FBartos could you please have a look at how the missing values are dealt with in (Bayesian) GLMM and LMM.

**Comment by FBartos** [comment]
Hi @tegedik ,

thanks for reporting this. Yes, you are right. I fear that the variable checking procedures do not consider and omit NAs values from the dependent variables yet. I will work on fixing this issue.

**Comment by AlexanderLyNL** [comment]
Hi @tegedik, 

Frantisek made the issue for you, so you don't need to report the bug anymore, unless you find something else of course. Thanks again for testing this for us. I close this issue now. Please reopen, if the issue reappears.

Cheers,
Alexander

**Comment by tegedik** [comment]
Thanks a lot @JorisGoosen , @AlexanderLyNL  and @FBartos . Surely you are a great team.

**Comment by JorisGoosen** [comment]
Thank you very much @tegedik!
And [here](static.jasp-stats.org/JASP-0.13.0.0-preCatalina.dmg) you can find the new installer for mac that should hopefully not crash and is also meant for pre-Catalina systems like the one you are using.
