### ISSUE TITLE
Ordinal CFA Invariance Question

### ISSUE THREAD

**Issue by psych919** [jasp-stats/jasp-issues#844]
I am attempting to run a CFA with ordinal data including invariance analyses. The assignment box only allows continuous variables to be entered, although it is possible to select estimators that account for ordinal data (WLS, DWLS). Would the use of an estimator thus allow for you to run the CFA appropriately if your data is ordinal (even though the data type has to be categorized as scale to move into the assignment box)? Thank you for any guidance that you can provide!

**Comment by EJWagenmakers** [comment]
@vankesteren

**Comment by juliuspf** [comment]
This should be possible by now :)
