### ISSUE TITLE
Windows Installation

### ISSUE THREAD

**Issue by mocherry23** [jasp-stats/jasp-issues#847]
* JASP version: JASP-0.13.0.0

* OS name and version: Windows 10 Enterprise Version 1803, 64-Bit

None of the installation options for Windows works. I have tried:
The 64-bit Windows installer.
The 32-bit installer.
The pre-installed 64-bit or 32-bit versions.

Installation proceed without any problems. When trying to run the program nothing happens.
???

Thanks and best
Matthias

**Comment by JorisGoosen** [comment]
Hello Matthias,

Could you download https://www.dependencywalker.com/ and use it to open "C:\Program Files\JASP\JASP.exe" ?
And then attach the dwi log here?

Then we can have a look if there is something going wrong loading dlls.

**Comment by mocherry23** [comment]
Dear Joris, version 012.2 runs o.K.Attached is the dwi I get when trying to run the latest Version. Zipped as otherwise too large! ThanksMatthias Gesendet von Mail für Windows 10 Von: Joris GoosenGesendet: Montag, 6. Juli 2020 12:28An: jasp-stats/jasp-issuesCc: mocherry23; AuthorBetreff: Re: [jasp-stats/jasp-issues] Windows Installation (#847) Hello Matthias,Could you download https://www.dependencywalker.com/ and use it to open "C:\Program Files\JASP\JASP.exe" ?And then attach the dwi log here?Then we can have a look if there is something going wrong loading dlls.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by JorisGoosen** [comment]
Hey Matthias, 

Could you actually go to the github website and this issue at https://github.com/jasp-stats/jasp-issues/issues/847 and upload the file there? They do not take the attachments from email...

**Comment by mocherry23** [comment]
[JASP.zip](https://github.com/jasp-stats/jasp-issues/files/4884712/JASP.zip)

**Comment by JorisGoosen** [comment]
So it seems that that all loads properly.

Could you try starting JASP from the commandline like so: `"C:\Program Files (x86)\JASP\JASP" --logToFile` and then see if you have any logfiles in `C:\Users\**YOUR USERNAME HERE**\AppData\Roaming\JASP\JASP\Logs`?

If you already have 0.12.2 installed you could also just enable logging there.

And, is your computer set up running in a german locale by any chance?

**Comment by JorisGoosen** [comment]
The relevant part from a comment in #863:
The logs here would have to be made by starting the 0.13 version.
What you could do is download the [zipped installer](http://static.jasp-stats.org/JASP-0.13.0.0-64bit.zip), unzip it and double-click JASP.exe.

 This will generate (hopefully) some logs that will tell me at what exact point JASP well, stops starting... The thing with "locales" is probably related to that issue.
