### ISSUE TITLE
Model Constraints in Bain ANOVA

### ISSUE THREAD

**Issue by knamesnik** [jasp-stats/jasp-issues#848]
* JASP version: 13

* OS name and version: Windows 10
* Analysis: Bain ANOVA
* Bug description: I am updating our instructions for students how to enter the hypotheses in the Model Constraints box in the newest version of JASP. In the past a period was used to separate variable and level (e.g. group.blu) whereas in the newest version the period is no longer needed (e.g. groupblu). When I was running some of our example analyses, I noticed that when typing the hypotheses SOMETIMES not all letters would appear. 
In the first analysis: no problem. In the analyses that followed, with either the same or a different variable, I would have about half the letters that would create a space or double space in the model constraints box. 
This is what I am trying to type:
methodebasis_EI-methodebasis_C=methodespeciaal_EI-methodespeciaal_C
methodespeciaal_DI-methodespeciaal_C>methodebasis_DI-methodebasis_C
methodebasis_EI-methodespeciaal_EI=methodebasis_C-methodespeciaal_C
This what I get:
![image](https://user-images.githubusercontent.com/38688445/86581070-dbf15700-bf7f-11ea-9795-228059503bfb.png)

My colleague tried it too, and got the same problem. The strange thing is: the analysis seems to run...

* Expected behaviour:
Normally I see what I type and is not half the text blank. 

#### Steps to reproduce:
1. Go to Bain > ANOVA
2. Click on hoofd_toename as the dependent variable (or any of the other scale variables)
Use methode or groep as the factor and try to enter a model constraint. The first time it works. After that the letters seem to disappear (I even tried to type the entire alphabet, but it also concerns > and < and =)
3. -

[Rekenvaardigheid voor Bain2.zip](https://github.com/jasp-stats/jasp-issues/files/4878177/Rekenvaardigheid.voor.Bain2.zip)

**Comment by tomtomme** [comment]
@knamesnik 
I tested this with 0.18.3 and it worked fine. 
If not fixed on your site, feel free to reopen!
