### ISSUE TITLE
A Histogram of a 7 likertskala ist mixed

### ISSUE THREAD

**Issue by KaNa-67** [jasp-stats/jasp-issues#849]
* JASP version: 0.13

* OS name and version: Windows 8.1
* Analysis: 
* Bug description: The ratings in the histogram schould be from 1 to 7. In 2 cases it ist 2,3,4,5,6,7,1 and 2,3,5,6,7,1,4 in the other 3 ist works properly. I could´t find an excuse in the exeldata.
![Histogramfehler](https://user-images.githubusercontent.com/67901688/86582526-0c39f500-bf82-11ea-9fbf-e2d8ea04e56e.jpg)

* Expected behaviour: Ratings schould bei from 1 to 7 in properly order 1,2,3,4,5,6,7

**Comment by EJWagenmakers** [comment]
That's strange -- could you send us (part of) the (anonimized) data, so we can confirm and investigate?
Cheers,
E.J.

**Comment by djdekker** [comment]
I remember having seen this same issue with ordinal data and bar charts. The "fix" was to switch the column type from ordinal to scale and back to ordinal. I could not succesfully reproduce the issue afterwards.

**Comment by AlejandroPeru** [comment]
La solución seria que revises el label de los datos
