### ISSUE TITLE
JASP 0.13 cannot be placed in the ribbon at the bottom of the screen

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-issues#850]
On my windows laptop, dragging the JASP icon to the ribbon below (to have it nest between the programs that I want to have available immediately) does not work. Similarly, if I have a JASP file open, no icon is placed on the ribbon; so when I open another program and it visually blocks JASP, there is no hint that JASP is active -- for all other programs on my computer, the icon on the ribbon provides this information.

![image](https://user-images.githubusercontent.com/8603015/86591527-0e0bb480-bf92-11ea-8ad8-e2c3dfaa41c6.png)

**Comment by EJWagenmakers** [comment]
Update: when JASP is active there is an icon on the ribbon. The reason I did not notice if at first is that it is not the JASP logo, but just a blank sheet of paper. 
![image](https://user-images.githubusercontent.com/8603015/86592467-d56cda80-bf93-11ea-8343-c0f7fb114ea7.png)

**Comment by JorisGoosen** [comment]
Does it still have the "blank page" icon after rebooting?

**Comment by EJWagenmakers** [comment]
Restart fixed it!
