### ISSUE TITLE
Reliability analysis does not work for 30 and more items

### ISSUE THREAD

**Issue by jachymDvorak** [jasp-stats/jasp-issues#853]
* JASP version: 0.13

* OS name and version: Windows 10 Pro 64 bit
* Analysis: Single-test Reliability analysis
* Bug description: When I add more than 30 items to reliabiity analysis (I have 36), I get the following error: Error: $ operator is invalid for atomic vectors
* Expected behaviour: analyze all 36 items 

#### Steps to reproduce:
1. Go to 'single test reliability analysis"
2. Add at least 30 items (all ordinal, values range from 1 to 5, no NAs)
3. See error

[data.xlsx](https://github.com/jasp-stats/jasp-issues/files/4880180/data.xlsx)

**Comment by antboxg** [comment]
Hi, I have errors too (other data, in v0.12 is OK):

![192412](https://user-images.githubusercontent.com/67921129/86621384-635dbb00-bfbe-11ea-8328-131444703617.png)
or 
![192840](https://user-images.githubusercontent.com/67921129/86621760-09112a00-bfbf-11ea-9271-7c8827a0e464.png)

JASP 013, Win 10Pro 64bit

**Comment by juliuspf** [comment]
Thanks. This problem is related to non-invertible matrices. Since your data example does not result in all non-invertible bootstrap matrices, it can be solved by updating the R-package to the latest commit, @JorisGoosen? However, the issue of non-invertible matrices is part of another problem we are looking into

**Comment by JorisGoosen** [comment]
@juliuspf what do you mean by that? The user is on windows with the release version of 0.13 so that should be this: https://github.com/jasp-stats/jasp-required-files/tree/Windows/R/library/Bayesrel

Or are you talking about some other package?

**Comment by juliuspf** [comment]
Sorry. Well I fixed the problem for this particular type of data (data that results in some bootstrapped covariance matrices being non-invertible, but not all) in the R-package Bayesrel; once a new version of JASP uses the 0.6.5.2 version of Bayesrel, this issue can be closed
