### ISSUE TITLE
Flexplot's added variable plots are not showing up

### ISSUE THREAD

**Issue by dustinfife** [jasp-stats/jasp-issues#854]
* JASP version: .13
* OS name and version: Mac OSX Catalina 10.15.4
* Analysis: Linear modeling
* Bug description: Added variable plots return an empty plot
* Expected behaviour: Added variable plots should return a plot

#### Steps to reproduce:
1. Go to Visual Modeling
2. Click on Linear Modeling
3. Select a DV and 2+ IVs
4.Check Results Display->Added variable plot

I have fixed this issue with [this flexplot commit](https://github.com/dustinfife/flexplot/commit/b36b94d585478b352815e8fb1c53d84c21908a5a). Can you include in the next release of JASP?

Also, I'm still updating my JASP module by changing the library where R installs the package. Any update on fixing the "Install developer module" feature?

**Comment by JorisGoosen** [comment]
I will add the new version of flexplot to our repositories.

What exactly do you mean by "fixing the install developer module" feature? Was there an issue related to this? 
I will be focussing on fixing bugs in 0.13 for a while and then I will continue working on modules. I am not aware of any particular bug in the install developer module feature though, so if you would like me to fix something this is the time to point it out to me ^^

**Comment by JorisGoosen** [comment]
Ok, so flexplot has been updated @dustinfife if you want me to have a look at whatever it is that is going wrong with devmodule you should make an issue for it.
