### ISSUE TITLE
Error in Reliability

### ISSUE THREAD

**Issue by JorisGoosen** [jasp-stats/jasp-issues#855]
Originally posted by @antboxg in https://github.com/jasp-stats/jasp-issues/issues/853#issuecomment-654371108

Hi, I have errors too (other data, in v0.12 is OK):

![192412](https://user-images.githubusercontent.com/67921129/86621384-635dbb00-bfbe-11ea-8328-131444703617.png)
or 
![192840](https://user-images.githubusercontent.com/67921129/86621760-09112a00-bfbf-11ea-9271-7c8827a0e464.png)

JASP 013, Win 10Pro 64bit

**Comment by JorisGoosen** [comment]
@Antboxg could you add a jasp-file that shows this error?
Aka, save the file you are working on when you see this error and attach that here (possibly zipped if github complains).

**Comment by antboxg** [comment]
I'm uploading files...

[errors.zip](https://github.com/jasp-stats/jasp-issues/files/4883259/errors.zip)

**Comment by juliuspf** [comment]
Thank you. The first screenshot is expected behaviour so far. The second one is part of a larger issue of non-invertible matrices that we are looking into.
