### ISSUE TITLE
Difference in (CFA) RMSEA values with MPLUS 8.1!

### ISSUE THREAD

**Issue by jjcosta1** [jasp-stats/jasp-issues#858]
* JASP version: 0.12.2

* OS name and version: Mac OS Mojave 10.14.6
* Analysis: CFA indice RMSEA very different from MPLUS 8.1
* Bug description:
In AFC, how is it possible that the JASP and Mplus programs present for the same data and the same factorial structure (18 items distributed over 6 factors, all categorical variables, in a sample of 399 subjects) so different adjustment index values ? The differences are very large, especially for the RMSEA, but they also vary for the other indicators.

I present the values, according to the estimator, to get an idea of ​​what I'm talking about (program name, estimator, indices values):

MPLUS 8.1
wlsmv: rmsea = 0.187; cfi = 0.79; tli = 0.76; srmr = 0.13
wls: rmsea= 0.201; cfi = 0.93; tli = 0.92; srmr = 0.33
wlsm: rmsea = 0.261; cfi = 0.33; tli = 0.81; srmr = 0.13
uls: rmsea = 0.187; cfi = 0.79; tli = 0.76; srmr = 0.13

JASP emulate mplus, error calculation robust
dwls: rmsea= 0.07; cfi = 0.93; tli = 0.91; srmr = 0.08
wls: rmsea= 0.06; cfi = 0.74; tli = 0.67; srmr = 0.15
wlsm doesn't have
uls: rmsea = 0.03; cfi = 0.98; tli = 0.97; srmr = 0.08

Note: JASP has the option to assume that the factors are not correlated, in which case the rmsea (for dwls) changes to .21. Could it be that for MPLUS the factors are not correlated and that is why the value is so high? 

* Expected behaviour: Same or similar values of RMSEA in CFA?
I don't know if this a bug or not but it is very important to understand the value discrepancies because in the cut-off values are involved in adjustment values.

I would like to thank you for sharing with us the JASP program and for all the work involved.

**Comment by JorisGoosen** [comment]
So I cannot answer this question I am afraid but I have assigned someone to this issue who can. He is on a vacation though, so it might take a while before he gets back to you.

**Comment by jjcosta1** [comment]
Hi 

Thanks for the quick answer. 

I'm very interested in this situation. 

Thnk you, 

jjmc 

A 2020-07-07 15:33, Joris Goosen escreveu:

> So I cannot answer this question I am afraid but I have assigned someone to this issue who can. He is on a vacation though, so it might take a while before he gets back to you. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

 

Links:
------
[1]
https://github.com/jasp-stats/jasp-issues/issues/858#issuecomment-654906158
[2]

**Comment by vankesteren** [comment]
Hi @jjcosta1 

this is strange. just to check: did you make the variables categorical (ordered, ![image](https://user-images.githubusercontent.com/11596858/86801027-e68d1880-c073-11ea-962b-ae8cd8b6a5f2.png)) in the JASP interface?

Erik-Jan

**Comment by jjcosta1** [comment]
Dear Erik-Jan 

When I make the variables ordinal, I'm unable to put them in the factors
window. 

Is it normal? To assign each variable to each factor I must put the in
scale format. 

Thanks, 

jjmc 

A 2020-07-07 16:04, Erik-Jan van Kesteren escreveu:

> Hi @jjcosta1 [1] 
> 
> this is strange. just to check: did you make the variables categorical (ordered, [2]) in the JASP interface? 
> 
> Erik-Jan 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [3], or unsubscribe [4].

 

Links:
------
[1] https://github.com/jjcosta1
[2]
https://user-images.githubusercontent.com/11596858/86801027-e68d1880-c073-11ea-962b-ae8cd8b6a5f2.png
[3]
https://github.com/jasp-stats/jasp-issues/issues/858#issuecomment-654927223
[4]

**Comment by jjcosta1** [comment]
Hi 

I've tried to do CFA with ordinal variables but JASP (0.13) does not
allow to put items inside the factors boxes if they are described as
categorical. 

As you know, this feature is presented as a JASP 0.13 version in _New
Features and improvements as_ 

 	* SEM module
 	* Allow ordinal variables in CFA

Yours sincerely, 

jjmc 

A 2020-07-08 10:10, José Costa escreveu:

> Dear Erik-Jan 
> 
> When I make the variables ordinal, I'm unable to put them in the factors window. 
> 
> Is it normal? To assign each variable to each factor I must put the in scale format. 
> 
> Thanks, 
> 
> jjmc 
> 
> A 2020-07-07 16:04, Erik-Jan van Kesteren escreveu:
> 
>> Hi @jjcosta1 [1] 
>> 
>> this is strange. just to check: did you make the variables categorical (ordered, [2]) in the JASP interface? 
>> 
>> Erik-Jan 
>> 
>> --
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub [3], or unsubscribe [4].

 

Links:
------
[1] https://github.com/jjcosta1
[2]
https://user-images.githubusercontent.com/11596858/86801027-e68d1880-c073-11ea-962b-ae8cd8b6a5f2.png
[3]
https://github.com/jasp-stats/jasp-issues/issues/858#issuecomment-654927223
[4]

**Comment by vankesteren** [comment]
Hi @jjcosta,

this is a mistake in the release notes. CFA will soon allow ordinal variables, but does not yet. This is immediately the reason for the difference between JASP and MPLUS. We will fix the release notes, thank you for reporting this!

**Comment by jjcosta1** [comment]
Hi 

Thank you for your help. Keep up the good work, 

jjmc 

A 2020-07-08 13:19, Erik-Jan van Kesteren escreveu:

> Hi @JJCosta [1], 
> 
> this is a mistake in the release notes. CFA will soon allow ordinal variables, but does not yet. This is immediately the reason for the difference between JASP and MPLUS. We will fix the release notes, thank you for reporting this! 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].

 

Links:
------
[1] https://github.com/JJCosta
[2]
https://github.com/jasp-stats/jasp-issues/issues/858#issuecomment-655483968
[3]

**Comment by jjcosta1** [comment]
Hi 

I would like to know when do you intend allow ordinal variables in CFA.
It is a very important issue to my work and I would appreciate your
consideration in this issue. 

Thank you for all your work, 

jjmc 

A 2020-07-08 13:32, José Costa escreveu:

> Hi 
> 
> Thank you for your help. Keep up the good work, 
> 
> jjmc 
> 
> A 2020-07-08 13:19, Erik-Jan van Kesteren escreveu:
> 
>> Hi @JJCosta [1], 
>> 
>> this is a mistake in the release notes. CFA will soon allow ordinal variables, but does not yet. This is immediately the reason for the difference between JASP and MPLUS. We will fix the release notes, thank you for reporting this! 
>> 
>> --
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].

 

Links:
------
[1] https://github.com/JJCosta
[2]
https://github.com/jasp-stats/jasp-issues/issues/858#issuecomment-655483968
[3]
