### ISSUE TITLE
HTML "Export Results" | Descriptive Plot missing

### ISSUE THREAD

**Issue by JasperRobinson** [jasp-stats/jasp-issues#859]
* JASP version:
0.11.1

* OS name and version: macOS 10.15.5

* Bug description: The HTML file created with "Export Results" is almost always missing the rendered Descriptive plot. There's a box where it should be, but the graph is missing. 

It usually appears but you have to keep exporting the results until it works. 

[2 - AE Phase 2 NOFEED-wide.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/4884007/2.-.AE.Phase.2.NOFEED-wide.jasp.zip)

**Comment by JorisGoosen** [comment]
Have you tried our new release? 0.13? 

Maybe the problem has been fixed already.

**Comment by JasperRobinson** [comment]
Thank you Joris—I didn't realise that I was out of date!

All good now in 0.13 for me—The "Descriptive Plot" *did* appear in the first "Export Data" .html file. I didn't need to repeat the export to get it to appear. :-)

**Comment by JorisGoosen** [comment]
Aah you didn't see a "download new version" button in the welcome page?
Anywway, good it works now!
