### ISSUE TITLE
Easier entry of "Repeated Measures Cells" | saved templates? Consistent keyboard entry key?

### ISSUE THREAD

**Issue by JasperRobinson** [jasp-stats/jasp-issues#860]
* Enhancement: 
1. Improve specification of "Repeated Measures Cells" (rows that specify levels of a within-subject variable).

2. Allow creation of analysis templates/allow Jasp to point to different data sets. 

* Purpose:
Massively speed up analysis and reduce errors. 

1. I almost always perform the same analysis on multiple data files, which have a common structure. 
2. E.g., at the moment, I'm running one-way ANOVAs, the variable has 12 levels ("Repeated Measures Cells"). Specifying them is awkward: there are 3 in Jasp to start with. I can tab to jump to and rename. After that, I need to use a mouse or a funny combination of tab and enter to rename. This takes a long time and it's easy to make mistakes. 
3. All of these processes need to be repeated for each new analysis—even though the structure of the analyses is identical. 

* Use-case:
For me, specifying "Repeated Measures Cells" is the most time consuming & error prone part of data analysis. 

**Describe the solution you'd like**

—Would it be possible to have a field to enter the number of levels (here, 12) and have Jasp create that number of "Repeated Measures Cells"? Or an "+" button to click until there are 12 rows? Perhaps they could be sequential numbers by default, which would probably work most of the time. 

—Could moving down each row be controlled just by tapping the Tab key? 

—Would it be possible to save the first analysis as a template and, after that, apply it to new data files? Or, re-save the Jasp analysis file with a new name and direct it to a different data file?

**Describe alternatives you've considered**

I've tried different key strokes but nothing seems to work efficiently for adding and naming "Repeated Measures Cells". 

I've tried: 1. duplicating the Jasp analysis file and 2. pasting the next data set into the .csv file that the first Jasp analysis file uses. This works but it's a scary because you lose contact with the actual data sets and re-opening the first Jasp file will perform the analysis on the most recent data set. So unless, you know that you will never add notes

**Comment by EJWagenmakers** [comment]
Yes, we should give this some attention. @JohnnyDoorn ?

**Comment by JohnnyDoorn** [comment]
Hi @JasperRobinson,

Thank you for your input! Yes, I have noticed that the widget can be a bit tricky sometimes, also due to it being relatively small. I have noticed that in 0.13 it is a bit easier to move around with Tab - which version are you currently using? I think additional changes in the QML, like the ones you're suggesting, would be interesting for @boutinb.

As for the making a template: you can do this by going to "sync data" and then selecting a different file from your computer (it does not have to have the same filename). Then you can save the .jasp file under a comprehensive name so they do not get mixed up. 

Kind regards,
Johnny

**Comment by JasperRobinson** [comment]
Thanks for this useful advice Johnny, 

I was using V 0.11 but have retested this morning with 0.13—here's what I found running some similar within-subjects parametric ANOVAs: [That reminds me: it would be great if Jasp checked for updates]

1. Inputing new Repeated Measures Cells is unchanged. So, tabbing to the first 2 pre-installed row works nicely—i.e., each tab press jumps to the next row for editing or accepting with the pre-installed "Level 1 or 2". After Level 2 tabbing jumps to a "RM Factor 2"—as though you want a second within-subject variable. To add level, 3 onwards you need to: 

 1. Mouse to the next level; 
 2. rename it. 
 3. Return, which creates the next level but sends you to the "Repeated Measures Cell" field (not ready for this yet!). 
 4. Mouse or ⇧ tab to get back to the "Repeated Measures" field.  
 5. Tab which allows you to rename the new level. 

2. I tried the "sync data" 3 times with different .csv files, renaming first, not renaming, etc and Jasp crashed every time. :-(

Best wishes, Jasper 
[yes-it is difficult for me to search for .jasp files on my machine with this name!]

**Comment by tomtomme** [comment]
@JasperRobinson 
We now have R-Syntax that you can copy over to another open JASP-instance. This should work nicely as a template to repeat an analysis. 
Feel free to reopen, if you disagree!
