### ISSUE TITLE
Jasp cannot be installed without admin privileges

### ISSUE THREAD

**Issue by donovaly** [jasp-stats/jasp-issues#861]
I wanted to try out JASP on my PC at work. This is impossible because JASP's installer requires admin privileges, which one of course doesn't have (my colleagues at the University also don't have admin privileges). Admins are also lazy and dependent on your organization, you must first explain why a program is important for your work, then the IT guys must check if giving a new program admin privileges might be harmful to the system etc.

But there is no need for this hassling. I had a look and JASP technically needs no admin privileges. This would only be necessary if one must modify the HKLM registry part. Since JASP doesn't install hardware drives a modification of HKLM is not necessary.
Besides this, since several users share usually the same PC, admins also don't ant to install all programs being available for all users. 

Conclusion: JASP could increase it userbase easily by enabling to install it as normal Windows user.
Proposal: do it like the KDE applications do: 
- when the installer is executed as normal user, the installation path is the default Windows one for local installations as shown in this screenshot of the KDE application LabPlot:
![labplot-master-446-windows-msvc2019_64-cl_e8qgLcy4xU](https://user-images.githubusercontent.com/1828501/86774534-ecc0cc00-c056-11ea-88af-9333f145a359.png)
- when the installer is executed by an admin, he gets the additional installer page where he can decide whether to install for all users or only for himself:
![labplot-master-446-windows-msvc2019_64-cl_AvVA1xUuXS](https://user-images.githubusercontent.com/1828501/86774513-e92d4500-c056-11ea-8ce0-70021432bc35.png)

Implementing this would allow a lot of people to use JASP.  All major installer engines (like NSIS, WIX etc.) provide options to enable this feature. I could have a look how this is done for the JASP installer if you like. Who is JASP's installer guy?

(I built this feature into installers for some programs (e.g. FreeCAD or LyX) and got the positive feedback that this helps to use these programs at work.)

**Comment by EJWagenmakers** [comment]
Did you see that we offer a preinstalled zip file, which allows you to install JASP without admin privileges?

**Comment by JorisGoosen** [comment]
@donovaly if you would like to help us out with this that could be great. I have set up the WIX code but basically have stopped paying attention to it as it seems to do all we want.

For most users the zipped version of JASP is good enough.
But if you want to have a go at it you can find the wix stuff here: https://github.com/jasp-stats/jasp-desktop/tree/stable/Tools/wix
And to build the installer we run https://github.com/jasp-stats/jasp-desktop/blob/stable/Tools/autobuild.cmd

A basic document describing how to set up the source structure for this all to function (should you feel inclined to build) can be found here: https://github.com/jasp-stats/jasp-desktop/blob/stable/Docs/development/jasp-building-guide.md
Although it is a bit outdated and is a candidate for replacement/revising to be honest.

**Comment by donovaly** [comment]
> @donovaly if you would like to help us out with this that could be great. I have set up the WIX code...

OK. I am an NSIS guy but think I can do this with WIX nevertheless. I am now in vacation and will have a look when I am back. So give me about 2 weeks.

**Comment by JorisGoosen** [comment]
> OK. I am an NSIS guy but think I can do this with WIX nevertheless. I am now in vacation and will have a look when I am back. So give me about 2 weeks.

Any help would certainly be appreciated and if you get stuck on something let us know.
Enjoy your vacation!

**Comment by donovaly** [comment]
Here is the installer ready to be tested:
https://github.com/donovaly/JASPInstProj/releases/tag/0.1

I decided not to improve the existing installer but to re-use the installer I wrote for the FreeCAD project.
Why?
* The FreeCAD installer is a bit more complex and it has been proven stable for over a year now (for sure more than 100k installations)
* I can provide more features the current installer is missing, I listed them here: https://github.com/donovaly/JASPInstProj/releases/tag/0.1

So please give it a try:
https://github.com/donovaly/JASPInstProj/releases/download/0.1/JASP-0131-Installer-1.exe
and report back what you think about it.

Note: don't wonder that on some Windows machines when executing the installer you will get a warning, that executing a .exe file
can be harmful. Just say "install anyway". There is nothing one can do against this since Microsoft alone know their internal heuristic when to issue this. The installer has a valid signature but the experience with FreeCAD shows that it collects info how many users use the installer already, then it keeps silent (big brother like).

**Comment by JorisGoosen** [comment]
Hey @donovaly, first of all I appreciate the effort you've put into this!

But we actually used NSIS before and the whole reason we stopped using that is because having an exe as an installer leads to errors such as "installing can be harmful". Also, with an MSI the whole install process and all files are integrated neatly with Windows. 

And we can sign it properly so that the installer mentions "Universiteit van Amsterdam" as being the author. Which should inspire trust because well, we are that university.

What advantage would using this installer have over our current MSI? Because the MSI works fine, except for the installing as admin part.

**Comment by JorisGoosen** [comment]
Aah, well it seems to be about 100M smaller, which is a nice thing. I will test out your installer on a VM later today.

**Comment by donovaly** [comment]
> What advantage would using this installer have over our current MSI?

As I wrote
 >> I can provide more features the current installer is missing, I listed them here: https://github.com/donovaly/JASPInstProj/releases/tag/0.1

> an exe as an installer leads to errors such as "installing can be harmful".

This was the only reason? You cannot influence what Windows does and will do in the future. maybe in future you need to specially sign *.msi files etc. We had the same issue with FreeCAD and found out that Microsoft "learns" that it is a harmless installer. After some days nobody got the "can be harmful" message. Besides this, it is of course the case that installing anything can be dangerous, also if it is a *.msi package.

> we can sign it properly so that the installer mentions "Universiteit van Amsterdam" as being the author.

The same is with NSIS. As you can see i signed the installer that the "JASP Team" is the author. You can change this easily.
(I wonder that ist is the University because I see that there are contributions from non-university members. I see in JASP's about dialog the university as copyright holder but in the citation rule the JASP team. Maybe you can clarify this.)

**Comment by JorisGoosen** [comment]
> > What advantage would using this installer have over our current MSI?
> 
> As I wrote:
> 
> > > I can provide more features the current installer is missing, I listed them here: https://github.com/donovaly/JASPInstProj/releases/tag/0.1

Ok, the translations are nice, but Im sure those could also just be part of the MSI. The other options for installing silently are also supported by windows-installer/msi. In fact, that is all basic functionality that is provided by MSI.

> 
> > an exe as an installer leads to errors such as "installing can be harmful".
> 
> This was the only reason? You cannot influence what Windows does and will do in the future. maybe in future you need to specially sign *.msi files etc. We had the same issue with FreeCAD and found out that Microsoft "learns" that it is a harmless installer. After some days nobody got the "can be harmful" message. Besides this, it is of course the case that installing anything can be dangerous, also if it is a *.msi package.

No it isn't the only reason. In fact, we already sign the msi with an official key which is why it says "Universiteit van Amsterdam" during install. The other reason is that MSI is the official way of installing software on microsoft windows computers, it also does not need to run arbitrary executable code and is fully transactional. Which means that if something goes wrong the previous state is restored. And because MSI registers all components and registry keys in an internal database all of this info is stored properly.
Or at least as good as something can be on Windows.

Of course installing something with an msi could still be installing malicious software. And if you get some DLL-hooks into the msi maybe you could get the installer to do some of that as well. But at least with WIX there is no need to write imperative code, their declarative model is hard to get into but once it works it works fine.

> 
> > we can sign it properly so that the installer mentions "Universiteit van Amsterdam" as being the author.
> 
> The same is with NSIS. As you can see i signed the installer that the "JASP Team" is the author. You can change this easily.
> (I wonder that ist is the University because I see that there are contributions from non-university members. I see in JASP's about dialog the university as copyright holder but in the citation rule the JASP team. Maybe you can clarify this.)

Well almost the entire core team of JASP is employed by that university. There are of course contributions of others but we actually publish the software.

**Comment by donovaly** [comment]
Dear Joris,

It seems you don't like other installer frameworks. I mean of course the other installers around follow the instillation guidelines of Windows too. So there are no DLL hooks and of course they use the correct registry folders

> In fact, we already sign the msi with an official key which is why it says "Universiteit van Amsterdam" during install. 

Fine. This can be done with NSIS as well. As you see, I signed my installer (using a key I created) while the installer is created. You can easily replace the .cer and .pvk file with your official one.
Note that when using an officially signed key, then Windows will also not declare the installer as potentially harmful. That is the main benefit of an officially signed installer.

My proposal is the same installer as used for the Project FreeCAD and it works well, so this is why I proposed this for you too. And again, it is just a proposal and also a demonstrator that no admin permissions are necessary.
If you like staying with WIX, do so, but please allow users like me who are not admin at work to install JASP. My installer shows that this is possible since there is no technical need to install as admin and some IT guys also don't like that because then every user of a PC is confronted with the program. For example my work PC is used by 3 users and the other 2 colleagues would be confronted with a program they don't need.

> There are of course contributions of others but we actually publish the software.

That is fine but then the university is not the copyright holder. Therefore "Jasp Team" is correct for the copyright while the university is correct as publisher. Therefore the registry offers the copyright and publisher fields.

> in fact, that is all basic functionality that is provided by MSI.

But why don't you provide it then the features of my installer also for the WIX installer?
Feel free to take my installer as inspiration. The whole installer and its translation is GPLed, so you can take them.

**Comment by JorisGoosen** [comment]
Hey Uwe,

Well, it is just that we used to use NSIS and the arguments I reiterated to you are the ones that convinced me to switch to wix/msi. I especially like the fact that when the setup gets killed the previous state is restored. That is a big advantage in case anything goes wrong. Ive seen very messy install-folders resulting from things like that. Im not trying to bash NSIS or your work but Im just trying to get clear if the advantages of using your modified version of the freeCAD installer weigh up to the disadvantage of losing the rollback functionality of an MSI and the builtin registry of components etc in Windows that it gives.

I do think it is a good plan to support a non-admin installer, for sure! It is just that we had the zip for that and nobody asked for that in the installer yet. Or I wasn't aware of it.

I also did specifically ask if you could add it to the wix-installer and it is of course fine if you don't want to do that. I appreciate the effort you've put into it.

**Comment by donovaly** [comment]
> I do think it is a good plan to support a non-admin installer, for sure!
> It is just that we had the zip for that

Then you misunderstood the concept of "installation". Extracting a ZIP does no installation.
What does installing for the current user do?:
- it registers the program to the user registry that you can start if from the start menu
- it registers the file extensions ".jasp" to the user registry so that the user can double-click on a .jasp file and JASP will be opened
- it adds the program to the list of installed programs (as you can see when using my installer Windows explicitly wants this. In the list of installed programs you see if a program is installed for all users or only for you
- as most programs, JASP adds files to the `C:\Users\<username>\AppData\Roaming\JASP`. According to the Windows policy these files must be removed when a program is no longer at the PC. So the uninstaller has to take care of thes, besides deleting the set registry settings

So installation for the current user is nothing special. It justs registers JASP to the registry branch HKCU, this an explicit design feature of Windows. So there is no need to force average users not to be able to use JASP like admin users. Not everybody is a computer expert, most are just users. So forcing them to register e.g. the .jasp extension manually is not sensible since Windows allows you to treat them the same ad admin users.

> I also did specifically ask if you could add it to the wix-installer

I started with this, but then I realized, that your WIX isntaller is not translated, does not check is JASP is currentl runnnign etc. Since my spare time is limited, I took my existing insaller and rewrote it for JASP. So jsut 3 hours of work and I got all features I missed.

However, WIX allows of course the installation for the current user only. Have e.g. look here:
http://windows-installer-xml-wix-toolset.687559.n2.nabble.com/per-user-per-app-WiX-installation-td7600513.html
Alternatively you can check what registry permission the user has that starts the installer, if it is HKCU, you change the installation forlder to LocalAppDataFolder instead of ProgramFilesFolder.
I am just not familiar with WIX yet. to tell you out of the box what you must do.

**Comment by JorisGoosen** [comment]
> > I do think it is a good plan to support a non-admin installer, for sure!
> > It is just that we had the zip for that
> 
> Then you misunderstood the concept of "installation". Extracting a ZIP does no installation.
> So what does installing for the current user actually do?:
> 
>     * it registers the program to the user registry that you can start if from the start menu
> 
>     * it registers the file extensions ".jasp" to the user registry so that the user can double-click on a .jasp file and JASP will be opened
> 
>     * it adds the program to the list of installed programs (as you can see when using my installer Windows explicitly wants this. In the list of installed programs you see if a program is installed for all users or only for you
> 
>     * as most programs, JASP adds files to the `C:\Users\<username>\AppData\Roaming\JASP`. According to the Windows policy these files must be removed when a program is no longer at the PC. So the uninstaller has to take care of this, besides deleting the set registry settings

And you are certainly right about that, this would be quite an improvement over the zip.

> 
> 
> So installation for the current user is nothing special. It just registers JASP to the registry branch HKCU, this an explicit design feature of Windows. So there is no need to force average users not to be able to use JASP like admin users. Not everybody is a computer expert, most are just users. So forcing them to register e.g. the .jasp extension manually is not sensible since Windows allows you to treat them the same ad admin users.

Again, I'm not disagreeing with you on the need for this. The question just never arose and I also only have limited time.

> 
> > I also did specifically ask if you could add it to the wix-installer
> 
> I started with this, but then I realized, that your WIX installer is not translated, does not check is JASP is not currently running etc. Since my spare time is limited, I took my existing installer and rewrote it for JASP. So just 3 hours of work and I got all features I missed.
> 
> However, WIX allows of course the installation for the current user only. Have e.g. look here:
> http://windows-installer-xml-wix-toolset.687559.n2.nabble.com/per-user-per-app-WiX-installation-td7600513.html
> Alternatively you can check what registry permission the user has that starts the installer, if it is HKCU, you change the installation folder to LocalAppDataFolder instead of ProgramFilesFolder.
> I am just not familiar with WIX yet. to tell you out of the box what you must do.

I can certainly work out how to do these things by myself if need be. I am just working on the actual application at the moment and trying to add support for other much needed functionality. I would regard the installing as user and closing a running JASP as nice-to-haves that should be added but can be worked around for now.

And I thought, if you feel like looking into that is great, but otherwise I'll get around to it at some point.

**Comment by JorisGoosen** [comment]
Aah and a point about the installer not being translated, this was not very useful up until this point because JASP was also not translated. This is in fact one of our current projects.

**Comment by boutinb** [comment]
@JorisGoosen Should this issue be postponed to 0.15?

**Comment by JorisGoosen** [comment]
I don't think this will be too much work and it would be nice if we support this sooner rather than later.

**Comment by JorisGoosen** [comment]
This turned out to be quite some work but it seems to work now.

In case @donovaly would like to help us out a bit by testing one of the new nightlies at: https://static.jasp-stats.org/Nightlies/
They are building now, so should be uploaded in roughly ~20m.

**Comment by donovaly** [comment]
> In case @donovaly would like to help us out a bit by testing

I tested it using the latest 64bit MSI nightly but I get a smartScreen warning:

![rHDIuWra63](https://user-images.githubusercontent.com/1828501/92543488-e5cb5b00-f24b-11ea-83a4-0eda259b475d.png)

(I thought you denied my NSIS proposal just because of the unavoidable SmartScreen warning.)
Here the point is, that since the publisher of the installer is unknown SmartScreen will always warn.

However I still cannot install JASP without admin permissions :-(
Could you therefore please reopen the issue until one can install without admin permits to assure that other affected users find it when searching the issues?

**Comment by JorisGoosen** [comment]
Thank you Uwe for testing, the smartscreen makes sense. Because we need to have a special department of the university sign the installer, which is a bit overkill for a nightly. As in, I literally have to mail a guy which is annoying but the only way to get it signed by the uni...

You did manage to get to the installer by ignoring the warning and you chose "Advanced",  "per-user" and didn't select the "C++ runtime ? 
Because the C++ runtime redistributable wants to install to C:\Windows which is of course not allowed as a user..

**Comment by JorisGoosen** [comment]
And if that is how you started it, maybe you could run the msi through `msiexec /i jasp-***.msi /lv jasp.log`  and then attach that log here?

**Comment by JorisGoosen** [comment]
And to be sure we are talking about the same installer, could you try it with: https://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-stable-dfe5e3d0db607d0f8102744de0af0e894bc96144.msi

**Comment by donovaly** [comment]
> And to be sure we are talking about the same installer, could you try it with: https://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-stable-dfe5e3d0db607d0f8102744de0af0e894bc96144.msi

I took this now for the test. It works, many thanks!

However, there are 2 issues:

1. the default setting should be the other way round: Only if you want to install JASP for all users you must press the Advanced button.
I mean the vast majority of users are not admins. Why should they bother the other users of the PC with their special programs. If all users in an organization should get JASP, the admin will do this and he of course has admin permissions.

(I always wonder why programs love to be installed for all users by default. For example at work I see therefore programs for billing, for surveys etc. despite I am not a marketing or sales guy, but a development engineer. On the other hand my sales colleagues see programs I use but they don't need.)

2. There is no explanation about the components - in this case the users don't know what the C++ runtime is and why they should or should not install. Therefore please add this info as component description.
To see what I mean, here is a screenshot of the installer for LibreOffice:
![msiexec_553oKVaQty](https://user-images.githubusercontent.com/1828501/92666971-ff7fa780-f30a-11ea-8f04-540b45f01593.png)
In this example you see the description of the component "Report Builder"

**Comment by JorisGoosen** [comment]
> > And to be sure we are talking about the same installer, could you try it with: https://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-stable-dfe5e3d0db607d0f8102744de0af0e894bc96144.msi
> 
> I took this now for the test. It works, many thanks!

Ah great!
So we are getting somewhere :)

> However, there are 2 issues:
> 
>     1. the default setting should be the other way round: Only if you want to install JASP for all users you must press the Advanced button.
>        I mean the vast majority of users are not admins. Why should they bother the other users of the PC with their special programs. If all users in an organization should get JASP, the admin will do this and he of course has admin permissions.

I'm not sure if this is true actually, but maybe this is a question of perspective. As in, by far most pc's I've used were mine and with admin rights. 

On the other hand, it wouldn't make much of a difference to single-user systems anyway if it was installed per-user or per-machine. Only problem with that is that for some(/many?) systems the c++ redistributable needs to be installed and that has to go in `C:\Windows` so you would need admin rights anyway. 

And JASP is a fairly large install, so if it *is* a multiuser system the installs accumulate GBs quickly...

I would have preferred the whole "accept license and advanced or default"-dialog wasn't there to be honest.
But despite my preference for working with WIX to get a nice MSI I do have to admit that WIX is very painful.
And I am already happy that this works, so I'm quite tempted to leave it like this.

> (I always wonder why programs love to be installed for all users by default. For example at work I see therefore programs for billing, for surveys etc. despite I am not a marketing or sales guy, but a development engineer. On the other hand my sales colleagues see programs I use but they don't need.)

Aah yeah, IT... I guess they just install an image or something with everything for everyone in it. Less hassle.

> 
>     1. There is no explanation about the components - in this case the users don't know what the C++ runtime is and why they should or should not install. Therefore please add this info as component description.

Yeah, that is a good one!
I will add this.

**Comment by JorisGoosen** [comment]
So it turns out to be another substantial change...

I really wish Microsoft had made it a bit easier to comply with "Windows Installer" but once https://github.com/jasp-stats/jasp-issues/issues/971 has been implemented things will be well.
For now I'm afraid I'll have to leave it like this.
