### ISSUE TITLE
 too many open devices???

### ISSUE THREAD

**Issue by mocherry23** [jasp-stats/jasp-issues#863]
* JASP version: 0.12.2

* OS name and version: Windows 10, 64-bit
* Analysis: 
* Bug description: when working with large data tables I get the error "too many open devices" for many of the options

Best
Matthias

**Comment by JorisGoosen** [comment]
The errormessage refers to plot-devices in R.

Is it possible to share the jasp-file where this occurs? Or describe a bit what you are doing?

For instance: are you changing options for an analysis that will output plots with a large dataset?

I also assume that once this message pops up the best thing to do is save your work and restart JASP because it seems somehow the devices R uses to plot are not being closed properly.

**Comment by mocherry23** [comment]
Dear Joris,

in the attachment you find the data file I have been using (jasp.txt) and the log-files and error messages I get when starting Jasp from the command line as you have suggested.
Mind, this is with version 0.12.2. Insatllation the latest version does not work at all (ref. other issue I have opened).
When using all the variables (except V1) and performing a standard correlation analysis, Jasp does the calculations and produces the tables. However, activating the Scatter Plot option results in : too many open devices.
I am not sure what you mean with "german locale " but as I am in Germany, I guess this is true. How do I check? Would this be a problem?
[jasp.txt](https://github.com/jasp-stats/jasp-issues/files/4888988/jasp.txt)
[jasp_Logs.zip](https://github.com/jasp-stats/jasp-issues/files/4888989/jasp_Logs.zip)

Thanks and best
Matthias

**Comment by JorisGoosen** [comment]
Ah, well, the logs of JASP starting are for your issue at https://github.com/jasp-stats/jasp-issues/issues/847 and they would have to be made by starting the 0.13 version. What you could do is download the [zipped installer](http://static.jasp-stats.org/JASP-0.13.0.0-64bit.zip), unzip it and double-click JASP.exe. This will generate (hopefully) some logs that will tell me at what exact point JASP well, stops starting... The thing with "locales" is probably related to that issue.

For this issue on the other hand using 0.12.2 is fine, as that is where you have the problem. So for this issue what you could do is, start 0.12.2, run your analyses and stuff. Until you get the "too many devices opened" error. And then you attach those logs here.

**Comment by mocherry23** [comment]
Dear Joris,

thanks for your patience.
I now have downloaded and unpacked version 0.13.0.0 as per your suggestion. Then I tried to run it from the command line. The resulting logs are attached. The problem remains: nothing happens.

Thanks and best
matthias
[logs with jasp o.12.0.0.zip](https://github.com/jasp-stats/jasp-issues/files/4890870/logs.with.jasp.o.12.0.0.zip)

**Comment by JorisGoosen** [comment]
Hey Matthias, 

No problem, and these logs are the right ones indeed!
JASP seems to stop at an unexpected place for me...

I am installing a german version of windows in a VM now to see if I can then reproduce it here...

**Comment by JorisGoosen** [comment]
Ok, so actually, for me in a fresh german windows install 0.13 works fine...

Could you try this test version of JASP 0.13 with qt 5.15 out?
http://static.jasp-stats.org/Nightlies/WindowsZip/JASP-nightly-qt5.15-c2fc3a8ccbc98a40939c05a600e0fbbc64784dd0.zip

**Comment by JorisGoosen** [comment]
And if it also doesn't work, please upload the logs, thanks!

**Comment by mocherry23** [comment]
Dear Joris,

so, this versions does not work either: It produces an error message: "vcruntime140.1.dll not found ..."
When staring from the command line no log files are produced at all.

**Comment by JorisGoosen** [comment]
Aah yes, because it is a zip it does not include the visual studio distributable: https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by mocherry23** [comment]
Dear Joris,

o.K. after installing this, the program runs.
When more than 30 variables are in the analysis, neither scatter plots nor heatmaps are produced though. Do you think that is a problem of my system only.
Also, do you plan to include the possibility to export graphs as .svg files?

Thanks so far, I will certainly try other modules and capabilities. So far, I really like waht I am seeing.
Best
Matthias

**Comment by JorisGoosen** [comment]
Hmm, well. I don't know if that is supposed to happen or not.
If you feel it is weird, maybe you can open a new issue for it? Also describing in which analysis and also make sure to mention you got a slightly experimental version from me.

I am actually surprised we aren't supporting export to svg yet. And in fact, it seems nobody has requested it yet. I will make an issue for it because it should actually not be that hard to implement.

Enjoy using JASP!
