### ISSUE TITLE
Descriptives allowing frequency tables for continous variables again?

### ISSUE THREAD

**Issue by AlexanderLyNL** [jasp-stats/jasp-issues#864]
Use-case provided by JASP lecturer: For an `age` variable (scale/continuous) you cannot extract from a histogram the number of 23-years old participants. This can be changing the type of `age`, or by allowing frequency tables for continuous variables. 

-1.a One problem is that the frequency tables can get uninformative and overwhelming when you have both continuous and discrete variables. For instance, you're interested in `hair colour`, `age`, but you also want to see the mean of `contNormal` in the main table. The frequency table of `contNormal` might clutter the frequency table for `hair colour` and for the use-case also for `age`, even though it's continuous. 
-1.b One work around to get the main table for `contNormal`, `age` and `hair colour`, but only a frequency table for `hair colour` and `age` would be to Copy analysis, remove `contNormal` from the copy and select frequency table. 
-2. One of our users deemed it non-sensible to have a frequency table for continuous variables anyways. I can't remember the details of the discussion. I don't have a workaround for this.

**Comment by tomtomme** [comment]
Nowadays we allow freq tables for any var up to 200 lines
