### ISSUE TITLE
This analysis terminated unexpectedly. 

### ISSUE THREAD

**Issue by mupeker** [jasp-stats/jasp-issues#865]
* JASP version:13

* OS name and version:W10
* Analysis: reliabilty
* Bug description:
Error: $ operator is invalid for atomic vectors

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.frequentistReliabilityMainResults(jaspResults, dataset, options)

**Comment by JorisGoosen** [comment]
Thank you for reporting this error, we are working on it in a private issue at https://github.com/jasp-stats/INTERNAL-jasp/issues/974 and another public issue here: https://github.com/jasp-stats/jasp-issues/issues/855
