### ISSUE TITLE
Major inconsistency between frequentist and bayesian non parametric paired t-test

### ISSUE THREAD

**Issue by ArCourtin** [jasp-stats/jasp-issues#868]
* JASP version:0.13

* OS name and version: Windows 10
* Analysis: (bayesian) paired t-test
* Bug description: The W value returned by the Bayesian and parametric paired t-test are inconsistent. BF and p-values interpretation lead to drastic differences of decision on H0 rejection.
* Expected behaviour: I'm unusure wether the W statistic are supposed to be exactly equal between the 2 tests but I assume they should not differ to such extent

#### Steps to reproduce:
1. Go to "T-tests>Paired samples t-test" and "T-tests>Paired samples t-test"
2. Tick the "Wilcoxon signed rank" box in the "Test" menus
3. Compare W statistics obtained for the same dataset. 
![image](https://user-images.githubusercontent.com/53186412/86930997-e5252400-c137-11ea-9eaa-ed8ea662f66e.png)

**Comment by EJWagenmakers** [comment]
@JohnnyDoorn

**Comment by ArCourtin** [comment]
The inconsistency in W is also present in JASP v0.12.2 but the corresponding BF and p-value seemed to be in agreement.
Same dataset in JASP V0.12.2:
![image](https://user-images.githubusercontent.com/53186412/87001716-560c2080-c1b8-11ea-88db-48a70eec90ab.png)
