### ISSUE TITLE
analysis terminated unexpectedly

### ISSUE THREAD

**Issue by MarCordero** [jasp-stats/jasp-issues#869]
* JASP version: 0.12.2.0
 Windows 10 Pro
* Analysis: Repeated Measures ANOVA
* Bug description: 
This analysis terminated unexpectedly. 

Error in if (xr[2] - xr[1] > 1000) {: missing value where TRUE/FALSE needed

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.BANOVAdescriptives(rmAnovaContainer, longData, options, list(noVariables = FALSE), 'RM-ANOVA', ready)

.BANOVAdescriptivesPlots(descriptivesContainer, dataset, options, errors, analysisType)

JASPgraphs::getPrettyAxisBreaks(ci.pos)

getPrettyAxisBreaks.numeric(ci.pos)

* Expected behaviour: I was trying to analyse a Repeated Measures ANOVA on a dataset of size 24 Kb. I set the variables and between factors and I wanted to see the descriptives plots as well. So right after I checked the box of 'Display error bars', this message appeared on the screen.

#### Steps to reproduce:
1. Open a dataset
2. Click on 'Repeated measures ANOVA' 
3. Add 2 conditions in 'Repeated measures factors' (I named the factor "Condition") and add 2 different variables to 'Repeated Measures Cells' (I also had my subjects' column in "Between Subject factors")
4. Scroll down to ''Descriptives plots" and add the subjects to the "Horizontal axis" and the factor (in my case, Condition) in the "Separate lines"
5. Check box "Display error bars" under the section Display (with the confidence interval of 95%)
6. See error

**Comment by JorisGoosen** [comment]
Does this happen with every dataset?
Or, if it is possible to share this data you could perhaps attach it here at the issue? (Zipped)

**Comment by JorisGoosen** [comment]
Or actually, maybe you could try the new release? 0.13?

**Comment by MarCordero** [comment]
Thank you @JorisGoosen for your quick response. I have seen that the problem is due to the format of some cells... Here I attach you one of the files 
[dataset.zip](https://github.com/jasp-stats/jasp-issues/files/4892666/dataset.zip)

The .csv files I have obtained from Matlab after I pre-analysed the data there. I opened the .csv file to check it and for some reason, the values in some of the cells are not processed as having decimals but as being "a thousand", so the dot is removed and then the data results are different. For instance, 25,338 is converted into 25.338. I tried to open with UTF-8 and English UK language and there were fewer cells with this problem. I manually corrected those bad ones and saved it. But when I then reopened the modified file, in LibreOffice (since Excel was not reading the columns properly), the data in the previsualization seemed fine but the problem persisted when the file was opened. Do you know how to deal with this? 
Thank you in advance!

**Comment by JorisGoosen** [comment]
If I look in the csv file I see a large set of numbers, all having decimals as denoted by the dot.
JASP will never interpret a dot as thousands, always as the denoter of decimals. And because some locales use commas to denote decimals we convert those commas to dots before doing further processing.

But it seems the problem here is that you have the data specified in Matlab and it isn't exported properly, or did I misunderstand?

**Comment by MarCordero** [comment]
I see... Yes, maybe Matlab exported the data wrongly but it is very hard to do it since I am using a specific plugin for analysing my data. I was checking when was NaN appearing and actually the error is caused due to the fact that I do not have between-subject conditions so there are no possible values there to compare. And the dot error is exclusively seen in Excel or LibreOffice, but you are right that there is no such trouble in JASP. Sorry for this and thank you for your time and help!

**Comment by JorisGoosen** [comment]
No problem and good luck with your data!
