### ISSUE TITLE
JASP maxes out at 17,745 observations

### ISSUE THREAD

**Issue by jdebeer2005** [jasp-stats/jasp-issues#871]
* JASP version: 0.13
win 10
* OS name and version:
* Analysis: JASP will not run a complete contingency report, maxes out at 17,745 ob
* Bug description:
* Expected behaviour:  I expect it to report 23,000 plus obs

#### Steps to reproduce:
1. Go to '...' jaxp file
2. Click on '....'  contingency
[2020-Mar-May_JDB.zip](https://github.com/jasp-stats/jasp-issues/files/4893949/2020-Mar-May_JDB.zip)

**Comment by jdebeer2005** [comment]
Please ignore, my fault, I that blocked some variables and observations.

very sorry.

**Comment by JorisGoosen** [comment]
No problem
