### ISSUE TITLE
Save image as SVG

### ISSUE THREAD

**Issue by JorisGoosen** [jasp-stats/jasp-issues#873]
As suggested/requested in https://github.com/jasp-stats/jasp-issues/issues/863 

It would indeed be nice to support this. Especially given the fact that we already support rendering all plots to svg anyway.
Those few remaining issues with that will have to be solved.

**Comment by EJWagenmakers** [comment]
Yes, and Richard M. tells me that svg plays well with Word too, so it would be nice to have.

**Comment by vandenman** [comment]
@JorisGoosen 

>  Those few remaining issues with that will have to be solved.

This makes it seem a little bit easier than it was ;)


I've got this working on [this branch](https://github.com/vandenman/jasp-desktop/tree/svg_device) without the issues we had before. Now you can both save an image as `svg` and images shown in JASP are by default `svg` files. 

Before I open a PR, are we sure that we want that all plots are `svg` files by default?

If yes, I may need to do additional work to ensure that copied figures look ok when pasted into word.

**Comment by JorisGoosen** [comment]
Well, I don't think we need to change the default to svg, I think @TimKDJ will kill me if I suggest that now :p
But we could just add it as an option right?
For "Save plot as"

Would still be nice to check if it looks good in word, but how could they mess up rendering an svg?
