### ISSUE TITLE
[Request] SPRITE Procedure for Audit/Data Generation

### ISSUE THREAD

**Issue by FelipeMAffonso** [jasp-stats/jasp-issues#874]
* Enhancement: add the SPRITE procedure to JASP. 
* Purpose: SPRITE is a tool that generates data/histograms based on parameters such as means, SDs, and ranges.
* Use-case: With this tool:

1) One could check for irregularities/data plausibility when no raw data is available. One could check the potential distributions that are generated by SPRITE and see the plausibility
2) One could generate data for fixed parameters.

The code exists for R, Python, etc., so I think it should be easy to implement.

"Recovering data from summary statistics: Sample Parameter Reconstruction via Iterative TEchniques (SPRITE)"

https://peerj.com/preprints/26968v1/

A quick explanation is provided here: https://twitter.com/jamesheathers/status/1001811174210535425?lang=en

You can see it operating via shiny apps here: https://steamtraen.shinyapps.io/rsprite/

Here is an updated version https://twitter.com/sTeamTraen/status/1280600285707227137 and the link to see it working: https://steamtraen.shinyapps.io/rsprite/

**Comment by koenderks** [comment]
Isn't this possible using the 'Discovering Distributions module" @Kucharssim?

**Comment by AlexanderLyNL** [comment]
Perhaps Felipe can describe use-cases and Simon can show how to do this with the Discover statistics module. We can then track possible overlap and possiblities for extensions.

**Comment by FelipeMAffonso** [comment]
If the "Discovering Distributions" is the "Show Distribution" using certain parameters, then not. At least I couldn't do it.

I believe that behind this module similar operations are made, but what we can do with it is different.

So, here is the tool: https://steamtraen.shinyapps.io/rsprite/

If we put these parameters (range, sample size, mean, SD, decimal places, etc), you can generate several histograms (in other words, you can generate several sets of raw data that leads to those parameters). 

There are two purposes on doing this.

First, it provides a visual aid for checking the plausibility of distributions based on summary statistics. This is a fraud detection tool. By looking at the possible distributions (something which is hard to do with numbers alone), one can get a better grasp of what is the raw data underlying the summary statistics. 

Second, it can generate raw data with certain distributions, which can be useful when studying statistics.

I believe the preprint (https://peerj.com/preprints/26968v1/) does a much better job than I do explaining it on page 8 and 9. I'll paste some of the relevant parts here.

Wansink, Just, Payne, & Klinger (2012) “Attractive Names Sustain Increased Vegetable Intake in Schools”. Wansink et al. (2012) investigated the effect of changing the names of vegetable dishes served to elementary school students.It was hypothesized and confirmed that labeling vegetables with attractive names (e.g., “X-ray Vision Carrots”) increased the consumption of vegetables, compared to when the vegetables were labeled with neutral or no names. The paper contains two studies, the first of which is summarized in Table 1 below. Although all of the mean/SD pairs in this table are unusual, the number of carrots taken in the control group stands out in particular. The mean/SD of 19.4/19.9 seems to imply that some children within the sample were taking a very large number of carrots without any intervention, so we decided to use SPRITE to explore the possible distributions of the number of carrots taken by each student

Recreating this distribution without an upper bound restriction is potentially misleading, as the number of possible outcomes are enormous, and can produce highly unrealistic distributions. Instead, we can attempt to establish a minimum possible upper bound by running SPRITE with a range of maximum values (e.g. 30 to 80), and investigating the resulting distributions. Thus, we ran SPRITE under the reported parameters (mean=19.4, SD=19.9, N=45) at a series of ranges (0 to 30, 0 to 31, 0 to 32, etc.) and observed the difference between the reported SD and the intended SD (i.e. 19.9). At lower ranges, the sample does not contain a sufficient range to satisfy the SD. The lowest upper bound of the range at which a solution becomes possible is 41. However, a range of 0 to 41 produces an unrealistic distribution, as it requires a large number of duplicate values at the upper bound (i.e. values are overwhelmingly either 0 or 41). As seen in Figure 6 below, the gradual relaxation of the upper limit lowers the amount of upper-bound and lower-bound values included in the distribution. While it might be expected that a large number of students will select 0 carrots, it is surprising to see how many carrots a number of students have to take to get the values to work.

**Comment by Kucharssim** [comment]
To summarise, the idea of SPRITE is to check whether we can recreate a plausible looking data set from summary statistics (i.e., sample data that have some fixed summary stats), in "discover distributions" we generate data by fixing the underlying parameters of the distribution (e.g., population mean), which results in sampling variability of the summary statistics. To me, these are very different ideas and applications.

Not sure what to do with this. I don't think SPRITE belongs to Distributions module, but I would also say it does not belong to AUDIT either (I am not sure whether @koenderks agrees). I think it could be made into a separate module for checking integrity of research reports and also include things like statcheck, but these tools are usually already available online by the very people who created them, so I am not sure what additional value we would get by implementing them in JASP. Any thoughts on this?

**Comment by AlexanderLyNL** [comment]
I'm not yet convinced that this needs to be high on our priority list. Perhaps I'm missing a convincing use-case. The rSprite webapp seems to be based on fitting a multinomial onto some summary stats, but I'm not sure how informative this is for me.

**Comment by FelipeMAffonso** [comment]
Hmm. I agree. Nevermind! I think there are more important things to be prioritized.
