### ISSUE TITLE
JASP won't start on macOS big sur

### ISSUE THREAD

**Issue by kampfq** [jasp-stats/jasp-issues#876]
* JASP version: 0.13

* OS name and version: macOS 11 Beta 2
* Analysis: -
* Bug description: JASP does not start, crashes immediatly.

**Comment by JorisGoosen** [comment]
I don't think it will have very high prio to get JASP to work on a beta version of macOS but it is good to be prepared for trouble. It seems like the new version will be quite an upgrade so Im not surprised things aren't working as expected...

**Comment by JorisGoosen** [comment]
It works on big sur
