### ISSUE TITLE
JASP file does not render on OSF

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-issues#878]
This JASP file, created with 0.13, does not render on the OSF: https://osf.io/mskxz/
(I can download it and open it fine; also, other jasp files do display -- for instance, from the same directory, https://osf.io/u6zvk/ does work. I am not sure whether this problem holds for all of 0.13, or is somehow specific to this particular file.

**Comment by JorisGoosen** [comment]
Sure, but could you attach the original file?

**Comment by JorisGoosen** [comment]
Hmm, I dont know what you did but if I download your file, refresh it and save it on my own OSF I get the functioning report: https://osf.io/xq4nd/ So I will close this issue.

**Comment by EJWagenmakers** [comment]
OK maar ik kan de werkende file niet zien, want daarvoor heb ik access nodig. Die heb ik aangevraagd. Je kunt me deze file ook mailen -- dan overschrijf ik de oude.
Misschien komt het omdat de eerdere versie gemaakt was onder de Mac, terwijl ik hem heb geedit met Windows? Het is zo langzamerhand het enige wat ik kan bedenken.

**Comment by JorisGoosen** [comment]
Misschien heb je hem gesaved terwijl ie nog aan het rekenen was? Dat kan ook soms dingen verstoren.
Ik neem aan dat je ondertussen wel bij de file kan. Maar anders zie hier.
[MensErgerJeNietCombined.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/4924764/MensErgerJeNietCombined.jasp.zip)

Het zou op zich ook goed zijn om te testen of zelf de file laden van je eigen osf, refreshen met Ctrl+R en saven op de osf het probleem ook verhelpt.

**Comment by EJWagenmakers** [comment]
"Het zou op zich ook goed zijn om te testen of zelf de file laden van je eigen osf, refreshen met Ctrl+R en saven op de osf het probleem ook verhelpt."

Ja, dat verhelpt het probleem! Dank
E.J.
