### ISSUE TITLE
Linear Regression Plot

### ISSUE THREAD

**Issue by gtobin26** [jasp-stats/jasp-issues#879]
* Enhancement:  Create a plot for a simple single XY dependent/independent relationship
* Purpose:  To provide a regression plot showing the individual data points, the line of best fit, the confidence lines for the predicted line of best fit, and the confidence limits of the prediction of Y from X.  Unless I have missed it, JASP has no option to plot this type of graph yet has excellent plots for items like residuals.
* Use-case:  It is still uncommon for many investigators to show a plot of anything more than the individual points and line of best fit, yet an indictation of uncertainty for both the slope and the prediction of Y from X is almost essential and is best shown graphically.  

**Describe the solution you'd like**
 Add an additional plot option to the regression menu with the ability to set the level of confidence for both the slope and prediction.  The axes ranges should be manually adjustable.

**Additional context**

![image](https://user-images.githubusercontent.com/45859576/87316231-69ebb580-c51d-11ea-89b2-6dd52e21541f.png)

**Comment by EJWagenmakers** [comment]
Thanks for the suggestion. I'll add this one to our list of figures that we want to include in a future release (no promises when this will happen, but it is on our radar now)

**Comment by gtobin26** [comment]
That’s great.  I understand that you have other priorities.  When you come to do it, if you need some worked examples with intermediate stages to check the program, let me know.  I have lots from perfect fits to scatter plots.

Thanks for considering the option.

Graham
