### ISSUE TITLE
Bug in Bayesian t-Test Sequential Analysis Graph

### ISSUE THREAD

**Issue by mopodendo** [jasp-stats/jasp-issues#88]
## Template for bug reports

* JASP version: 0.8.1.2 + 0.8.2
* OS name and version: Win 10
* Analysis: Bayesian One Sample t-Test
I noticed a bug when displaying the sequential Bayesian t-Test in the two latest versions. I get another (seemingly correct) chart with Version 0.8.1.1
I have attached pictures with the same analyses of the same data with version 0.8.1.1 and version 0.8.2. Notice the huge drop at the beginning of the graph in the second picture.
![grafik](https://user-images.githubusercontent.com/31739931/30174150-6101e7b6-93fa-11e7-942e-576de4da1cd7.png)
![grafik](https://user-images.githubusercontent.com/31739931/30174159-68955b2a-93fa-11e7-8b66-8500b230a01f.png)

**Comment by juliuspfadt** [comment]
@mopodendo sorry for the late response. Could you check if this is fixed in the latest JASP version?
