### ISSUE TITLE
Mediation with a Categorical Outcome

### ISSUE THREAD

**Issue by 16665k00** [jasp-stats/jasp-issues#880]
Will it be possible to update the mediation analysis so as to allow for categorical outcome variables? (e.g., correct/incorrect, yes/no, and so on).

**Comment by vankesteren** [comment]
Yes, this would be really nice to have!

**Comment by vankesteren** [comment]
I just checked -- this is already available for binary outcomes. You have to set your outcome variable to "ordinal" (![image](https://user-images.githubusercontent.com/11596858/88159221-4b687700-cc0d-11ea-9612-13baf78e6d1b.png)). The model plot will not be available, but the mediation model parameter estimates will be. 

We should also change this in the help file, as it currently states the following, which is quite misleading:
>For binary endogenous variables, recode your variable into a dummy continous variable with 0 for the first category and 1 for the second category. The linearity assumption still holds, however, i.e., SEM does not perform logistic regression.

**Comment by 16665k00** [comment]
Thanks! I have just tried this, and received the following error message: "FIML missing value handling only available when all endogenous variables are of scale type. Ordinal endogenous variables in the model: VariableNameHere"

However, if I change the outcome category to a scale value (and the outcomes themselves to 1 and 0), then it works...

**Comment by vankesteren** [comment]
yes, you need to switch to "listwise deletion" under advanced > missing value handling

**Comment by 16665k00** [comment]
It works! But note - rather than "listwise deletion" it actually reads "Exclude cases listwise".

Many thanks!
