### ISSUE TITLE
Not able to open Jasp on Mac 

### ISSUE THREAD

**Issue by anne992** [jasp-stats/jasp-issues#885]
I got a big issue  .

There is a Problem with the Installation for Jasp with my Macbook. I have been trying the Installation for weeks now. And even a Apple Employee does not know the Problem. They have instaled the right Software and I did every step which is on the Jasp website for trouble with Jasp under Mac OS .Could you please help me?I need it for the the University and I feel like that I already did every single step that is possible to do

Thank you very much

**Comment by eminSerin** [comment]
Please provide more detailed information about the version of your OS (e.g., Catalina 10.15.5) and JASP (e.g., 0.13) you are trying to install.

**Comment by EJWagenmakers** [comment]
It may be the fact that you have a Mac with Intel Iris GPU? We have solved this issue in the upcoming release, which is imminent. @Joris, what do you suggest -- try a nightly? 
If that still does not work for you, we will indeed need more information.

**Comment by JorisGoosen** [comment]
The problem with Intel Iris GPU was only *after* installing.

@eminSerin is right, we would need to know which version of MacOS @anne992 is using and it would also be good if she was trying the latest installer (0.13.1).

**Comment by anne992** [comment]
Hey Guys thanks für those quick  answers . I have installed evers single Version of jasp which is listed on the homepage. I could not Open one of them Even the latest Version. My Mac OS Version is High sierra 10.13.6 . Thats the latest version that was instaled by an Apple emplyoee to help me out with Jasp


________________________________
Von: Joris Goosen <notifications@github.com>
Gesendet: Friday, July 17, 2020 11:45:29 AM
An: jasp-stats/jasp-issues <jasp-issues@noreply.github.com>
Cc: anne992 <anne16es@hotmail.de>; Mention <mention@noreply.github.com>
Betreff: Re: [jasp-stats/jasp-issues] Not able to open Jasp on Mac (#885)


The problem with Intel Iris GPU was only after installing.

@eminSerin<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FeminSerin&data=02%7C01%7C%7C08571a5c60ee4ef733b308d82a36248d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637305759304652113&sdata=9Ie6MajfgZEtv%2BKgiGdYXiE4QiOhjbvgXk9klhFI%2FfM%3D&reserved=0> is right, we would need to know which version of MacOS @anne992<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fanne992&data=02%7C01%7C%7C08571a5c60ee4ef733b308d82a36248d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637305759304652113&sdata=KMdGdQuzkLO4d5a5ZnVyIpJxHJlbBDfUZdgIDPcJ0Cg%3D&reserved=0> is using and it would also be good if she was trying the latest installer (0.13.1).

**Comment by eminSerin** [comment]
That's very weird. What's the error you have? Could you post the screenshot of the error warning? High Sierra is not the latest version of MacOS, but it's not very old either, thus it should okay for JASP. If you could share the error warning, you could find the solution faster.

**Comment by anne992** [comment]
There is no Error warning. After the Installation the jasp Programm ask me if i want to open it.And when i press Yes there is nothing hapend. Like i do have the JASP symbol on my mac but when i double click it to open it,  there is nothing open up.

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Emin Serin <notifications@github.com>
Gesendet: Friday, July 17, 2020 12:19:10 PM
An: jasp-stats/jasp-issues <jasp-issues@noreply.github.com>
Cc: anne992 <anne16es@hotmail.de>; Mention <mention@noreply.github.com>
Betreff: Re: [jasp-stats/jasp-issues] Not able to open Jasp on Mac (#885)


That's very weird. What's the error you have? Could you post the screenshot of the error warning? High Sierra is not the latest version of MacOS, but it's not very old either, thus it should okay for JASP. If you could share the error warning, you could find the solution faster.

**Comment by JorisGoosen** [comment]
I think @AlexanderLyNL is still working on High Sierra as well, or maybe he upgraded?

@anne992 what I have noticed on some older macos' is that you have to right-click the JASP icon and choose "open". Then for some reason it didnt do anything and then the second time you do it it would work.

But I thought we had fixed that.

If you've tried that and it still doesn't work I would ask you to do the following:
1. Open a terminal
2. Enter: `/Applications/JASP.app/Contents/MacOS/JASP`

And then send us the entire output from the terminal, if it doesn't work still..

**Comment by AlexanderLyNL** [comment]
@anne992 Just to double check, did you downloaded the version mentioned with the smaller font?

http://static.jasp-stats.org/JASP-0.13.1.0-preCatalina.dmg

- Once downloaded, I open the dmg and move it to the Applications folder
- To open it the first time, I go to Applications folder, right click on JASP and press Open
- For me the first time it doesn't really open, but the second time I only need to double click to logo to open JASP

**Comment by anne992** [comment]
Thank you guys i will try it out

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: AlexanderLyNL <notifications@github.com>
Gesendet: Friday, July 17, 2020 3:14:11 PM
An: jasp-stats/jasp-issues <jasp-issues@noreply.github.com>
Cc: anne992 <anne16es@hotmail.de>; Mention <mention@noreply.github.com>
Betreff: Re: [jasp-stats/jasp-issues] Not able to open Jasp on Mac (#885)


@anne992<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fanne992&data=02%7C01%7C%7Cc25d8e1a34a54eba59fd08d82a534c02%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637305884521447222&sdata=%2Bwscv9tuQ7a0PsDbnU3ieshd1zTLT%2FU%2Fwfxmtd8tM%2BA%3D&reserved=0> Just to double check, did you downloaded the version mentioned with the smaller font?

http://static.jasp-stats.org/JASP-0.13.1.0-preCatalina.dmg<https://eur04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fstatic.jasp-stats.org%2FJASP-0.13.1.0-preCatalina.dmg&data=02%7C01%7C%7Cc25d8e1a34a54eba59fd08d82a534c02%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637305884521457217&sdata=K%2FVVpBW8Yzi8pCXo2gvJYJuDQDV7rHTJIDuGPds0mYY%3D&reserved=0>

  *   Once downloaded, I open the dmg and move it to the Applications folder
  *   To open it the first time, I go to Applications folder, right click on JASP and press Open
  *   For me the first time it doesn't really open, but the second time I only need to double click to logo to open JASP

**Comment by anne992** [comment]
@joris Goosen do you might tellin me how to open an terminal on Mac
Or anyone please

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: anne bola <anne16es@hotmail.de>
Gesendet: Monday, July 20, 2020 1:09:45 PM
An: jasp-stats/jasp-issues <reply@reply.github.com>; jasp-stats/jasp-issues <jasp-issues@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Betreff: Re: [jasp-stats/jasp-issues] Not able to open Jasp on Mac (#885)

Thank you guys i will try it out

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: AlexanderLyNL <notifications@github.com>
Gesendet: Friday, July 17, 2020 3:14:11 PM
An: jasp-stats/jasp-issues <jasp-issues@noreply.github.com>
Cc: anne992 <anne16es@hotmail.de>; Mention <mention@noreply.github.com>
Betreff: Re: [jasp-stats/jasp-issues] Not able to open Jasp on Mac (#885)


@anne992<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fanne992&data=02%7C01%7C%7Cc25d8e1a34a54eba59fd08d82a534c02%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637305884521447222&sdata=%2Bwscv9tuQ7a0PsDbnU3ieshd1zTLT%2FU%2Fwfxmtd8tM%2BA%3D&reserved=0> Just to double check, did you downloaded the version mentioned with the smaller font?

http://static.jasp-stats.org/JASP-0.13.1.0-preCatalina.dmg<https://eur04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fstatic.jasp-stats.org%2FJASP-0.13.1.0-preCatalina.dmg&data=02%7C01%7C%7Cc25d8e1a34a54eba59fd08d82a534c02%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637305884521457217&sdata=K%2FVVpBW8Yzi8pCXo2gvJYJuDQDV7rHTJIDuGPds0mYY%3D&reserved=0>

  *   Once downloaded, I open the dmg and move it to the Applications folder
  *   To open it the first time, I go to Applications folder, right click on JASP and press Open
  *   For me the first time it doesn't really open, but the second time I only need to double click to logo to open JASP

**Comment by JorisGoosen** [comment]
See any of the [following search results](https://www.google.com/search?q=open+terminal+mac).
