### ISSUE TITLE
CFA Model Plot with Standardized Parameters

### ISSUE THREAD

**Issue by eminSerin** [jasp-stats/jasp-issues#886]
* JASP version: 0.13

* OS name and version: MacOS Mojave 10.14.6
* Analysis: Confirmatory Factor Analysis
* Bug description: I am not sure if it's a bug. JASP always provides CFA model plots with unstandardized parameters regardless of whether or not standardization is selected. 
* Expected behaviour: When you select standardization in the "Advanced" menu, the parameters in the CFA model plot should be standardized.

**Comment by vankesteren** [comment]
Oh yes, this seems like a bug. I'll look into it!

**Comment by vankesteren** [comment]
Ah yes, this was not implemented. I've now added an extra button in the plot to show the standardized parameters:
![image](https://user-images.githubusercontent.com/11596858/88768811-e61c0500-d17b-11ea-8eb6-86aec12fd122.png)

Expect this in a release of JASP soon!
