### ISSUE TITLE
Reliability: Average interitem correlation 95%CI, do not include point estimate!

### ISSUE THREAD

**Issue by Marian-Popa** [jasp-stats/jasp-issues#888]
* JASP version:
0.13.1
* OS name and version:
Windows 10
* Analysis: 
Reliability
* Bug description:
In Reliability Statistics table, the point estimate for Average interitem correlation is .21 and the 95%CI are reported as .87 - .84
At the same time, in the Cronbach's alpha column 95%CI values are not displayed. I assume there are the two limits displayed wrong on the column Average interitem correlation
* Expected behaviour:
95%CI (if computable) should include the point estimate
Cronbach's alpha should have 95%CI

[data_Reliability.zip](https://github.com/jasp-stats/jasp-issues/files/4936836/data_Reliability.zip)

Best regards,
Marian

**Comment by juliuspf** [comment]
Thank you. This is my bad, two columns are switched. alpha and the average correlation. I am restructuring the module to get rid of this, and simplify the order of things.
