### ISSUE TITLE
Plots on linux are only saved as png

### ISSUE THREAD

**Issue by JorisGoosen** [jasp-stats/jasp-issues#889]
Flatpak version 0.13.1 on Arch Linux.

If I try to save any plot as anything it always saves as png.
So if I select pdf it gives it the extension pdf but it saves a png anyway...

**Comment by JorisGoosen** [comment]
I was looking at #884 when I noticed this.

**Comment by vandenman** [comment]
Same on Ubuntu. I don't have this problem on development though.

**Comment by JorisGoosen** [comment]
Yeah, I think I caused it through some code I added in https://github.com/jasp-stats/jasp-desktop/commit/88572e1437463a548219bfb325a0e137d5b69074

Im guessing the type-selection in the linux widget doesn't go right.
I still need to check it with "non-native filedialogs" though, maybe the Qt one behaves better.

**Comment by JorisGoosen** [comment]
Yeah, pretty weird. So the flatpak "native filedialog" messes things up.
If you select the non-native one things work as expected.

It seems our code doesn't expect the data it gets back from that "native" filedialog portal..
