### ISSUE TITLE
Report crucial information in factor analysis

### ISSUE THREAD

**Issue by moritzkoerber** [jasp-stats/jasp-issues#89]
There is important information missing how the analysis proceeds. What is the method of extraction (maximum likelihood, principle axis factoring, something else)? And what are the parameters chosen for this method? How many iterations were done? How were missing values treated?

**Comment by alexgeavis** [comment]
Is there an update on this? Having same issue. Thanks

**Comment by vankesteren** [comment]
Hi all,

the method that JASP uses to perform EFA currently is `minres`. In the next version of JASP, EFA will include other extraction methods for EFA too! For more information on minres and other available extraction methods, see [the `psych::fa` documentation](https://www.rdocumentation.org/packages/psych/versions/1.8.12/topics/fa#l_details).

Missing values by default are treated by pairwise deletion to create the correlation matrix which acts as the basis of the factor analysis.

**Comment by moritzkoerber** [comment]
Thank you, that is all of the information that I've needed!
