### ISSUE TITLE
ROC and cut-off procedures

### ISSUE THREAD

**Issue by Simon4819** [jasp-stats/jasp-issues#890]
I can use JASP to get ROC, AUC, sensitivity and specificity.
But I cannot get around to getting Pairwise Values for the Coordinates of the ROC so that I can determine cut-off value for the variable in question. I am using the latest JASP version.
Can you help?
Regards,
 Dr Simon Sandett Namnyak

* Enhancement:
* Purpose:
* Use-case:

**Is your feature request related to a problem? Please describe.**
 I can use JASP to get ROC, AUC, sensitivity and specificity.
 But I cannot get around to getting Pairwise Values for the Coordinates of the ROC so that I can determine cut-off value for the variable in question. I am using the latest JASP version.
Can you help?
 Regards,
 Dr Simon Sandett Namnyak

**Describe the solution you'd like**
 ROC program to provide Pairwise Coordinates of the ROC Curve, with sensitivity and 1-specificity tabulated accordingly

**Describe alternatives you've considered** None
 None

**Additional context**
None

**Comment by vankesteren** [comment]
How would you like to see this? Is an ROC curve plot enough?
