### ISSUE TITLE
I cant run t o Mann-Whitney tests when mean (and variance) in a condition is equal to 0

### ISSUE THREAD

**Issue by ismaelgutier** [jasp-stats/jasp-issues#892]
* Enhancement: I would like to propose the running of t tests or Mann-Whitney tests when I have a condition of 60 items with all 0 on it and its variance is 0. 
* Purpose: I need to compare a condition (of 60 items) with a given mean (e.g., 34) with other condition with a mean of 0 as sum of its items (variance = 0).
* Use-case: I cannot compare two conditions when one of them has as mean 0 (variance too). 

**Is your feature request related to a problem? Please describe.**
 I am not sure if it is related to a problem but i can get results when i run the same tests on SPSS.

**Describe the solution you'd like**
 It could be possible to allow t tests and related parametrics to take some conditions with 0 in its values (all of them) and its mean as valid.

**Describe alternatives you've considered**
 

**Additional context**
 Here i add some screenshots, the "problem" appears as NaNª:

![image](https://user-images.githubusercontent.com/68556299/87962701-eb13f100-cab7-11ea-9e5e-ffa8b8d6755f.png)
![image](https://user-images.githubusercontent.com/68556299/87964037-ebad8700-cab9-11ea-956e-7f8a2481b911.png)

It's all i want to request. I like JASP so much but i would appreciate that it could help me 100%.
Thank you!

**Comment by EJWagenmakers** [comment]
If you want to compare to a condition with variance zero, aren't you looking for a one-sample t-test instead?

**Comment by AlexanderLyNL** [comment]
One sample version solves the problem. Please reopen if something's still unclear.

**Comment by ismaelgutier** [comment]
> If you want to compare to a condition with variance zero, aren't you looking for a one-sample t-test instead?
> One sample version solves the problem. Please reopen if something's still unclear.

That solved the problem, I ended up performing my analyses on R-Studio.

Thank you both very much
