### ISSUE TITLE
Same working directory for "R in JASP" as for JASP proper

### ISSUE THREAD

**Issue by PeterKlaren** [jasp-stats/jasp-issues#895]
* Enhancement: Set the working directory for "R in JASP" as the same as that of JASP proper.
* Purpose: Ease of use of "R in JASP", would be great for learners of JASP to replicate JASP's analyses using R scripts.
* Use-case:

**Is your feature request related to a problem? Please describe.**
No problem.

**Describe the solution you'd like**
Upon starting "R in JASP" the getwd() function returns the directory of the currently loaded dataset.

**Describe alternatives you've considered**
 
Manually typing in the current working directory. It's a bit of a hassle.

**Additional context**

![getwd](https://user-images.githubusercontent.com/43278770/88101517-618b1e80-cb9e-11ea-8e3a-0a220a04efb9.JPG)

Note the different working directories.

**Comment by JorisGoosen** [comment]
What do you think @EJWagenmakers, @TimKDJ or @AlexanderLyNL ?
Would that be a logical place?

The pro of the current random temp folder is that nothing messy happens in the users documents-folder but the con is that well, as @PeterKlaren stated, you have to type in a whole directory or path to get somewhere useful.

Maybe it would be good to set the working directory to Documents/home?

**Comment by TimKDJ** [comment]
The proposed solution by @PeterKlaren sounds sensible to me.
Not entirely sure where it should point to for OSF datafiles though.

**Comment by JorisGoosen** [comment]
Then we could have users home directory.

**Comment by AlexanderLyNL** [comment]
Agree

**Comment by tomtomme** [comment]
@JorisGoosen 
Seems not yet implemented. Getwd still shows tmp folder
