### ISSUE TITLE
Komogorov-Smirnof Test

### ISSUE THREAD

**Issue by brodykade** [jasp-stats/jasp-issues#9]
There is already a frequency tab full of useful stats options, however, I really need the KS test option and believe it would be an easier statistic to patch in.

Thank you for all the work, and I like the software.  I've spent the last few weeks on Rstat, and this is refreshing.  Just need that damn KS test.  

Brody

**Comment by JohnnyDoorn** [comment]
KS is available in the distributions module (since that test requires a fully specified distribution to compare). Shaprio Wilk is now available in the descriptives module, and in various other tests.

**Comment by TemIsreal** [comment]
The KS test under distributions only takes one variable at a time
