### ISSUE TITLE
Please give us the ability to customize X axis bin size, min, and max (and more)

### ISSUE THREAD

**Issue by JimWeinrich** [jasp-stats/jasp-issues#90]
## Template for enhancement requests
* Enhancement: Allow users to customize presentation parameters for X axis (and Y axis)

* Purpose: If a variable could in theory have values from 1 to 10, but in a particular data set only actually takes values of 7, 8, 9, and 10, there seems to be no way to tell JASP to have the X axis run from 1 to 10. JASP instead (intelligently) notices that there are no values from 1 to 6, and only graphs bars for the values that actually occur in the data set.

It would be nice if this range adjustment could apply across the board (if desired), so that (see sample data set below) JASP could produce distribution plots that run from 1 to 10 (say) for all variables, even if some of them only run from 7 to 10, or 1 to 3, or 2 to 9, or whatever. This would make comparisons across variables easier and more insight-producing.

JASP also makes assumptions about what bin size should apply to the X axis, and it would be nice to be able to tell JASP to make a different choice. In the data set pasted below, for example, with "Descriptive statistics" and "Display distribution plots" the bin sizes are chosen to be 0.5, 1.0, or 2.0, with no way to standardize or adjust them. (Apologies if there is a way to do so that I haven't discovered.)

I'm sure you are aware of this behavior. I sympathize. If I were you, I would despair of when to make such options available to users, because the customization that users might desire is ENDLESS, and for the moment at least one might want to concentrate on the actual statistics, not the presentation of summary data. Color and shape options for the data points? Thick or thin lines? Those can wait (grin). So I'm confining my feature request to an aspect that really is important statistically, and thank you for a great product (no matter how long I have to wait for this feature to be added).

Sample data set:

var1,var2,var3,var4,var5,var6,var7,var8
4.1,9.1,10.1,8.1,7.1,1.1,4.1,7.1
5.1,8.1,10.1,10.1,7.1,1.1,10.1,6.1
9.1,5.1,8.1,8.1,8.1,9.1,9.1,5.1
4.1,4.1,9.1,8.1,5.1,1.1,8.1,4.1
5.1,7.1,10.1,10.1,8.1,10.1,7.1,5.1
3.1,3.1,10.1,8.1,7.1,3.1,8.1,8.1
10.1,10.1,10.1,10.1,10.1,7.1,10.1,9.1
10.1,7.1,9.1,9.1,6.1,6.1,8.1,5.1
6.1,6.1,8.1,7.1,7.1,7.1,7.1,5.1
1.1,4.1,7.1,6.1,7.1,2.1,3.1,7.1
3.1,4.1,8.1,6.1,4.1,2.1,9.1,4.1
8.1,8.1,9.1,8.1,6.1,9.1,10.1,5.1
8.1,9.1,9.1,7.1,5.1,8.1,8.1,5.1
2.1,1.1,10.1,8.1,9.1,2.1,10.1,10.1
6.1,7.1,9.1,7.1,7.1,8.1,7.1,7.1
4.1,3.1,9.1,8.1,6.1,6.1,9.1,3.1
8.1,7.1,9.1,5.1,7.1,9.1,9.1,5.1
4.1,6.1,10.1,9.1,8.1,2.1,9.1,9.1
7.1,10.1,10.1,10.1,8.1,9.1,8.1,1.1
7.1,9.1,10.1,9.1,6.1,6.1,7.1,7.1

**Comment by Ema51** [comment]
It would be really useful to be able to adjust dimension and dpi with precision before saving the pictures. Because I found really difficult to adjust the images after copying from JASP without losing quality or making a mess with the x and y axis written part

**Comment by EJWagenmakers** [comment]
We currently offer tiff, eps, and pdf format. For each figure, instead of selecting "copy" after opening the small triangle on top of the figure of interest, you can select "save as" to access these options. I'm closing this, feel free to re-open if I've misunderstood your point.
Cheers,
E.J.

**Comment by EJWagenmakers** [comment]
Oh yes, and about the title: we are working on a comprehensive graph-editing solution that will deal with this! We are very much aware of the need to do this and we're on our way.

**Comment by meaadk** [comment]
Hello, 
what happened to the editing of the y axis range? how can i control it and change the range (min and max). 
thank you

**Comment by vandenman** [comment]
This will be available in the upcoming release.

**Comment by kshitizkz** [comment]
Changing the y axis range would be VERY useful. 

Also, although I figured out a hack (very new to JASP), it would be very useful if we could plot multiple box plots in a single figure. Right now it plots each box-plot in a single image.

**Comment by vandenman** [comment]
@kshitizkz if you want multiple box plots in a single figure and your data is in long format (i.e., one column with data and another column that indicates the category) then you could do something like this:

![image](https://user-images.githubusercontent.com/21319932/128362562-593eae0b-ae4d-42bc-b8ac-0401ba53aff5.png)

**Comment by AugustOlsson** [comment]
@vandenman 

If its tricky to include customizable y-axis, just changing the script so that when one plots data by separate plots the same y-axis scale is used for both plots would be extremly good (e.g. when one has 3 independent variables, e.g. in a mixed anova).

As it is now, I get different axis for the different y-axis of the two "separate plots" which is very unfortunate. This was however not the case about 2 years ago (before the steps were added to the y-axis), then at least the start and end of the y-axis of both plots plotted simultainously was the same, which in my opinion is more worth than have a fine-graded y-axis scale. 

Best,
August

**Comment by vandenman** [comment]
Hi @AugustOlsson, the next version of JASP should allow you to customize the axes:
![image](https://user-images.githubusercontent.com/21319932/132499344-1e47c18e-fe23-4373-bf54-adae73eaebb4.png)

It's also on our to-do list to add a checkbox that ensures that the y-axes are the same by default.
