### ISSUE TITLE
Selecting a custom spreadsheet editor not working

### ISSUE THREAD

**Issue by skollgrim** [jasp-stats/jasp-issues#901]
* JASP version: 0.13.1

* OS name and version: Windows 10
* Bug description: Having selected to use a custom spreadsheet editor and pointing it to excel it still decides to use the default, which in my case is SPSS.

**Comment by boutinb** [comment]
Hallo @skollgrim, what is the type of the file you want to edit? Is it a specific SPSS type file (like .sav)?

**Comment by skollgrim** [comment]
> 
> 
> Hallo @skollgrim, what is the type of the file you want to edit? Is it a specific SPSS type file (like .sav)?

Yes it was and I guess that solves the problem and we can close this.
