### ISSUE TITLE
STANDARD DEVIATION IN RELIABILITY ANALYSIS

### ISSUE THREAD

**Issue by josecrocha** [jasp-stats/jasp-issues#902]
* JASP version: 0.11.1

* OS name and version: MACOS SIERRA
* Analysis: 
* Bug description:
There is an error on SD calculation when asking for Reliability Analysis->Scale Statistics->Standard Deviation, the result is not correct.

* Expected behaviour:

**Comment by AlejandroPeru** [comment]
Ahora estamos en la 0.13.1

**Comment by JorisGoosen** [comment]
No hablo espanol, English please.

**Comment by JorisGoosen** [comment]
@josecrocha have you tried 0.13.1?

**Comment by EJWagenmakers** [comment]
It is too bad GitHub does not do automatic translations, like in gmail. For our non-English users, I think that using Google translate is the best option.

**Comment by josecrocha** [comment]
> Ahora estamos en la 0.13.1

When you use MacOS Sierra, this is the most updated version. Nevertheless, you may look if the problems persists in earlier versions.

**Comment by juliuspf** [comment]
@josecrocha Could this be the same issue? https://github.com/jasp-stats/jasp-issues/issues/540

**Comment by josecrocha** [comment]
> @josecrocha Could this be the same issue? #540

It may be... I will update my Sierra machine to test it... Thanks!

**Comment by juliuspf** [comment]
Well, did you reverse scale an item? If that is indeed the same issue, unfortunately only the the new version of JASP fixes your problem
