### ISSUE TITLE
Polychoric/tetrachoric factor analysis

### ISSUE THREAD

**Issue by ivmcphail** [jasp-stats/jasp-issues#903]
Hi JASP team,

First, let me thank you for all the great new features that have been recently added to JASP! I have recently used the factor analysis module for a project and the ease of analysis and the figures that it automatically produces were very welcome and amazing!

In other research projects, I have used polychoric and tetrachoric factor analysis in R. It is really nice that R allows this kind of functionality and allows one to use polychor/tetrachoric approaches to not only explore factor solutions but also to do analyses like parallel analysis. I recommend that the JASP team considers adding in the poly/tetrachoric approach to the Factor Analysis module. 

The specific R packages that provide these polychor/tetrachoric EFA are the 'psych' package or the 'EFAUtilities' package. 

A recent study also provided some R code for a function that allows for a category probability proportions-based polychoric/tetrachoric parallel analysis; I include the reference below. I have found that using this approach to parallel analysis, especially with low base rates in dichotomous items (i.e., category proportions that vary greatly from .50), produces much more accurate and reasonable estimates for the number of factors to include.

Lubbe, D. (2019). Parallel analysis with categorical variables: Impact of category probability proportions on dimensionality assessment accuracy. Psychological methods, 24(3), 339.

Many thanks,

Ian

**Comment by brianmsm** [comment]
I'd also like to have this feature in JASP. 
For EFA with psych, is possible to use `polychoric` function within function for `parallel` or `fa` procedures.
For CFA with lavaan, you can include this with `ordered` argument within `cfa` or `sem` function. For example:
```
cfa(model = model_example, 
data = example, 
ordered = c("Item01", "Item02"),
 estimator = "WLSMV")
```

**Comment by boutinb** [comment]
@Kucharssim Is it something you could implement?

**Comment by raoelg** [comment]
> @Kucharssim Is it something you could implement?

Actually, if in the current JASP interface ordinal factors would be allowed as variables (instead of only continuous ones as is now the case), then the lavaan package apparently already automatically uses polychoric correlations to do the factor analysis. I understand from the literature that this in combination with DWLS is most popular for Likert scales based confirmatory factor analysis. So it might be just a matter of allowing ordinal factors in the interface.

**Comment by boutinb** [comment]
@Kucharssim Can you check if when you allow the ordinal factors, that the analysis works as expected?

**Comment by helenum** [comment]
Hi there. Was the poly/tetrachoric correlations added to the Factor Analysis module?
Many thanks

**Comment by Kucharssim** [comment]
Hello @helenum,

it is possible to use ordinal variables in CFA. I see that this is not the case for EFA yet. I will take a look.

**Comment by Kucharssim** [comment]
Actually, @juliuspf already made a PR that implements this feature, and it is scheduled for the 0.16.3 release. https://github.com/jasp-stats/jaspFactor/pull/93

**Comment by juliuspf** [comment]
Also for EFA by courtesy of https://github.com/francotisocco in here https://github.com/jasp-stats/jaspFactor/pull/75
