### ISSUE TITLE
Imputing Missing Data functionality

### ISSUE THREAD

**Issue by ivmcphail** [jasp-stats/jasp-issues#904]
Hi again JASP Team,

I wanted to make a second feature request. I have been working with R and SPSS to do analyses with multiply imputed datasets as a means of dealing with missing data. Having the option of (a) creating multiple imputed datasets in JASP and (b) conducting analyses on multiple imputed datasets in JASP may be an interesting addition. 

Within R, one of the main packages for multiple imputation is 'mice'. I have been using mice recently and with my R coding skills not being very good, working in this package has been quite difficult and frustrating. 

Best,

Ian

**Comment by EJWagenmakers** [comment]
This is under active development, so I'll close this issue :-) Good suggestion! :-)

**Comment by ivmcphail** [comment]
Fantastic to hear this! A big thanks to the JASP team for taking on what must be a huge task to include imputation functionality. Can't wait!

**Comment by rjgagno** [comment]
Would love to hear any updates on this, I am hoping to begin using JASP in my intro courses instead of SPSS, but this a function that I would love to have before jumping in

**Comment by EJWagenmakers** [comment]
We hope to have it added this academic year.

**Comment by rjgagno** [comment]
Wonderful!
