### ISSUE TITLE
Moderated Mediation

### ISSUE THREAD

**Issue by sushiman** [jasp-stats/jasp-issues#905]
<Hi all,
I was wondering whether and if JASP will eventually include a moderated mediation analysis section with included path diagram. The PROCESS macro implements this statistical term quite well, however, I believe JASP would be able to improve on this. 

What are your thoughts?

**Comment by vankesteren** [comment]
It is currently not an explicit separate analysis, but you could include an interaction term in the mediation analysis (depending on which moderation effects you want to include). For example, for this model:
![image](https://user-images.githubusercontent.com/11596858/88547727-64fb2b80-d01e-11ea-81cc-be3dbf997e7b.png)

you can include `W` and a new computed variable `W*X` as a predictor, and you will be running a moderated mediation analysis (with path diagram)

**Comment by tomtomme** [comment]
This can be closed

PROCESS is now available in beta: 
https://github.com/jasp-stats/jasp-desktop/releases/tag/v0.18.2.beta
 
or via our nightly builds: 
https://static.jasp-stats.org/Nightlies/

final 0.18.2 will be out soonTM.
