### ISSUE TITLE
Jasp 0.13.1.0: results do not display

### ISSUE THREAD

**Issue by HGZM2020** [jasp-stats/jasp-issues#906]
Hi, I am new user and have the Results are not displayed in version 0.13.1.0 running in Windows 7 / 64 bits. Please, could you help me? I don't know how to turn safe graphics on.

* JASP version: 0.13.1.0

* OS name and version: Windows 7 / 64 bits
* Analysis: Results are not displayed
* Bug description: Results are not displayed, but it is possible to copy the output panel.
* Expected behaviour: Results shown in the output panel

#### Steps to reproduce:
1. Go to any analysis
2. Click on analysis
3. Scroll to output panel
4. See error Results are not displayed.

**Comment by JorisGoosen** [comment]
Could you attach a screenshot of JASP I am curious to see what exactly you mean.

**Comment by HGZM2020** [comment]
Thank you. I active Safe Graphics Mode (in Preferences/Interface)  and now it is working. First, it didn't work, but I resarted the laptop and now it is working.

**Comment by JorisGoosen** [comment]
Good to hear!
