### ISSUE TITLE
JASP 0.13.1.0: JASP file keeps crashing

### ISSUE THREAD

**Issue by adrianwroblewski** [jasp-stats/jasp-issues#907]
* JASP version: 0.13.1.0

* OS name and version: Windows 10
* Analysis: JASP keeps crashing when trying to open file (210MB large)
* Bug description: JASP file cannot be opened after trying to save changes. JASP tries to open it and is closed immediately without any note.

**Comment by JorisGoosen** [comment]
Could you describe the file? Is it for instance an csv of spss file?
What kind of data does it contain?
Have you opened your system monitor (Ctrl + Shift + Esc) to check it perhaps your systems RAM is full?

Do you think there is a possibility you could share this file?
