### ISSUE TITLE
Bug in display of Contingency Tables

### ISSUE THREAD

**Issue by djdekker** [jasp-stats/jasp-issues#908]
* JASP version: 0.13.1
* OS name and version: macOS 10.15.6 Catalina
* Analysis: Contingency Tables & Bayesian Contingency Tables
* Bug description: table is still shown (but with wrong variable) after removing variable from analysis
* Expected behaviour: table should be removed when removing variable from analysis

#### Steps to reproduce:

1. open contingency_display_bug.jasp (attached as a .zip file)
2. go to Frequencies > Contingency Tables
3. remove the *first* variable (called 'School') from the 'Rows' box
4. the output pane is not updated correctly: the contingency table for the remaining variable is now shown twice
<img width="1158" alt="contingency_display_bug" src="https://user-images.githubusercontent.com/5346286/88549444-983eba00-d020-11ea-9d71-a9468452f1d9.png">

5. put the variable 'School' back in the 'Rows' box
6. the contingency tables in the output pane are not updated at all
<img width="1158" alt="contingency_display_bug_2" src="https://user-images.githubusercontent.com/5346286/88549466-9c6ad780-d020-11ea-93c8-34753728c1f4.png">

[contingency_display_bug.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/4982352/contingency_display_bug.jasp.zip)

**Comment by djdekker** [comment]
There are still problems with the display of contingency tables in 0.15 (nightly build of April 24, 2021; commit 2cf137b5667f952f140a03ef324e8e820e737ade).

The contingency tables are updated incorrectly when variables are removed and/or added back in:

https://user-images.githubusercontent.com/5346286/115990276-9bbc9d00-a5c2-11eb-8561-261f92b8e741.mp4

[test.csv](https://github.com/jasp-stats/jasp-issues/files/6371744/test.csv)

**Comment by boutinb** [comment]
@TimKDJ Heb je tijd om naar die issue te kijken?

**Comment by TimKDJ** [comment]
It appears I worked on this last year, but then sort of... stopped.
I'll get back on it. It'd be great if you could test it once I finish https://github.com/jasp-stats/jaspFrequencies/pull/8 and it gets merged.

**Comment by djdekker** [comment]
Sure, I'd be happy to test.
