### ISSUE TITLE
Calculating signal detection theory (SDT) measures requires whitelisting qnorm

### ISSUE THREAD

**Issue by singmann** [jasp-stats/jasp-issues#909]
A popular framework for analysing accuracy data in psychology is signal detection theory (SDT). It allows transforming the proportion of hits ("yes" responses to signal items) and false alarms ("yes" responses to noise items) into measures of discriminability and response biases. Popular measures are `d'` and `c`, where for example [`d'` is defined as](https://en.wikipedia.org/wiki/Sensitivity_index) d' = Z(hit rate) - Z(false alarm rate), where Z is the inverse of the cumulative distribution function of the Gaussian distribution. This function is available in `R` as `qnorm`. However, `qnorm` is not whitelisted in `JASP` when calculating new variables:
![image](https://user-images.githubusercontent.com/1902102/88556579-75fd6a00-d029-11ea-8add-bad552a8140f.png)

Can `qnorm` be whitelisted? 

I guess other distribution functions for the normal distribution (i.e., `dnorm` and `pnorm`) could then also be whitelisted. And maybe even the distribution functions for other distributions (see `?Distributions`). But I am not sure how much need there is. With `qnorm` alone, basic SDT analysis should be possible in `JASP`.

**Comment by JorisGoosen** [comment]
We have added some special cases of the distributions to JASP:
```R
normalDist   <- function(mean, sd)          { return( rnorm(   n=.dataSetRowCount(), mean=mean, sd=sd))             }
expDist      <- function(rate)              { return( rexp(    n=.dataSetRowCount(), rate=rate))                    }
betaDist     <- function(alpha, beta)       { return( rbeta(   n=.dataSetRowCount(), shape1=alpha, shape2=beta))    }
gammaDist    <- function(shape, scale)      { return( rgamma(  n=.dataSetRowCount(), shape=shape, scale=scale))     }
unifDist     <- function(min, max)          { return( runif(   n=.dataSetRowCount(), min=min, max=max))             }
tDist        <- function(df, ncp)           { return( rt(      n=.dataSetRowCount(), df=df, ncp=ncp))               }
chiSqDist    <- function(df, ncp)           { return( rchisq(  n=.dataSetRowCount(), df=df, ncp=ncp))               }
binomDist    <- function(trials, prob)      { return( rbinom(  n=.dataSetRowCount(), size=trials, prob=prob))       }
poisDist     <- function(lambda)            { return( rpois(   n=.dataSetRowCount(), lambda=lambda))                }
geomDist     <- function(prob)              { return( rgeom(   n=.dataSetRowCount(), prob=prob))                    }
fDist        <- function(df1, df2, ncp)     { return( rf(      n=.dataSetRowCount(), df1=df1, df2=df2, ncp=ncp))    }
negBinomDist <- function(targetTrial, prob) { return( rnbinom( n=.dataSetRowCount(), size=targetTrial, prob=prob))  }
logNormDist  <- function(meanLog, sdLog)    { return( rlnorm(  n=.dataSetRowCount(), meanlog=meanLog, sdlog=sdLog)) }
weibullDist  <- function(shape, scale)      { return( rweibull(n=.dataSetRowCount(), shape=shape, scale=scale))     }
```
I'll add the ones you requested to the whitelist now though.

**Comment by JorisGoosen** [comment]
I'm adding these:
```R
"dbeta",		"pbeta",		"qbeta",		"rbeta",
"dbinom",		"pbinom",		"qbinom",		"rbinom",
"dcauchy",		"pcauchy",		"qcauchy",		"rcauchy",
"dchisq",		"pchisq",		"qchisq",		"rchisq",
"dexp",			"pexp",			"qexp",			"rexp",
"df",			"pf",			"qf",			"rf",
"dgamma",		"pgamma",		"qgamma",		"rgamma",
"dgeom",		"pgeom",		"qgeom",		"rgeom",
"dhyper",		"phyper",		"qhyper",		"rhyper",
"dlnorm",		"plnorm",		"qlnorm",		"rlnorm",
"dmultinom",	"pmultinom",	"qmultinom",	"rmultinom",
"dnbinom",		"pnbinom",		"qnbinom",		"rnbinom",
"dnorm",		"pnorm",		"qnorm",		"rnorm",
"dpois",		"ppois",		"qpois",		"rpois",
"dt",			"pt",			"qt",			"rt",
"dunif",		"punif",		"qunif",		"runif",
"dweibull",		"pweibull",		"qweibull",		"rweibull",
"dsignrank",	"psignrank",	"qsignrank",	"rsignrank",



"pbirthday",
"ptukey",
"dwilcox"
```

**Comment by singmann** [comment]
Great thanks. Do you have a rough estimate when the next JASP version with this fix will be available to download?

**Comment by JorisGoosen** [comment]
Well a proper release, I don't know. But the [nightlies](https://static.jasp-stats.org/Nightlies/) already contain it.

**Comment by singmann** [comment]
Thanks a lot. It is working great!

**Comment by JorisGoosen** [comment]
Enjoy!
