### ISSUE TITLE
JASP crashed

### ISSUE THREAD

**Issue by cumtbfengjunda** [jasp-stats/jasp-issues#912]
* JASP version: 0.13.1
* OS name and version: Windows 10 (10.0)

* Analysis: 
* Bug description:
* Expected behaviour:

#### Steps to reproduce:

-----------------------------------------------------------------------

### Debug information:
**Engine # 0** process  is *running* and it's state is *initializing*.
**Engine # 1** process  is *running* and it's state is *initializing*.
**Engine # 2** process  is *running* and it's state is *initializing*.
**Engine # 3** process *does not exist (anymore)* and it's state is *initializing*.

[Commit used](https://github.com/jasp-stats/jasp-desktop/commit/d2d5d378a3ccb371eb6ea357352966b510c516a6)

**Comment by boutinb** [comment]
Sorry for the late answer... But could you be a bit more explicit: what do you do exactly? Do you double-click the JASP icon, and it crashes immediately, or is it when you load a file?
