### ISSUE TITLE
Add Odds Ratio (OR) calculation at the contingency tables procedure

### ISSUE THREAD

**Issue by vicenteinefo** [jasp-stats/jasp-issues#913]
* Enhancement: In the contingency tables procedure, why JASP calculates OR as log OR instead of the "normal" OR? 
It would be possible to add the "normal" OR calculation?
It also, would be useful to add the possibility of determine the level of the confidence interval manually.
* Purpose: To add a more user-friendly OR measure 
* Use-case: The Log Odds Ratio is a bit confusing, isn't it?

![Captura de pantalla 2020-07-29 a las 17 47 20](https://user-images.githubusercontent.com/29978768/88822324-fe177700-d1c3-11ea-8c9b-bb49f2439f08.png)

**Comment by EJWagenmakers** [comment]
Maybe a really good project for some of our new students, @vandenman

**Comment by vandenman** [comment]
fixed in development by https://github.com/jasp-stats/jaspFrequencies/pull/14
