### ISSUE TITLE
Column order option does not work

### ISSUE THREAD

**Issue by vicenteinefo** [jasp-stats/jasp-issues#914]
* JASP version: 0.13.1

* OS name and version: MacOS 10.15.6
* Analysis: Contingency tables
* Bug description: Ascending and descending column order option does not work, the data of the table does not change the order
* Expected behaviour: the order of the column should be modified

#### Steps to reproduce:
1. Open the attached file
2. Scroll down to Options section
3. Click on Ascending or Descending order option
4. Observe that the data of the Contingency table is not updated

[Chi cuadrado asociación ejemplo 1.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/4999799/Chi.cuadrado.asociacion.ejemplo.1.jasp.zip)

**Comment by boutinb** [comment]
@TimKDJ This is a problem in ContingencyTables: the columnOrder option is passed to the analysis, but apparently the handling (line 636/674: ss.matrix <- ss.matrix[ , ncol(ss.matrix):1] does not do what it should do.

**Comment by boutinb** [comment]
@vandenman Maybe if you are back from your holidays, you can take this issue over.
