### ISSUE TITLE
JASP Crashed and New Column Could not be created 

### ISSUE THREAD

**Issue by RossRobinson2** [jasp-stats/jasp-issues#916]
* JASP version:

* OS name and version:  Windows
* Analysis: Completing descriptive Statistics 
* Bug description: Error message stated something wrong with the internal engine and crashed. I now cannot reload previous saved files too. 

* Expected behaviour:

**Comment by AlexanderLyNL** [comment]
Could you please fill out the bug report template more fully? Otherwise we can't help you further. Which version of Windows? Which JASP version? etc. To speed up the process, it would be good to add the jasp file as a zip to this thread.
