### ISSUE TITLE
JASP crashes with request for marginal means on significant 2-way ANOVA 

### ISSUE THREAD

**Issue by ataylor92110** [jasp-stats/jasp-issues#919]
* JASP version:0.11

* OS name and version: Windows
* Analysis: Repeated Measures ANOVA requested marginal means for interaction effect
* Bug description: System crashes but gives me this error message:
This analysis terminated unexpectedly.
Error in if (is.finite(value)) {: argument is of length zero
Stack trace
analysis(dataset = dataset, options = options, perform = perform, callback = the.callback, state = oldState)
.rmAnovaMarginalMeansTable(dataset, options, perform, status, fullModel)
.clean(r$lsmean[index])
* Expected behaviour:

#### Steps to reproduce:
[F19 wild prepostt3myths.zip](https://github.com/jasp-stats/jasp-issues/files/5004199/F19.wild.prepostt3myths.zip)

1. Go to 'Repeated Measures ANOVA Accuracy Self-Esteem Increases Achievement'

**Comment by ataylor92110** [comment]
OH, I didn't complete that. You want to click on Additional Options
Scroll down to Marginal Means and click on estmFMF * GPAhilo

**Comment by AlexanderLyNL** [comment]
Could you please check whether this bug is still in the newest version? You can find JASP 0.13.1 on our download page: https://jasp-stats.org/download/

**Comment by ataylor92110** [comment]
That fixed it. Thank you.

Annette

Annette Kujawski Taylor, Ph.D.
Professor, "Retired," Psychological Sciences
University of San Diego
taylor@sandiego.edu

**Comment by AlexanderLyNL** [comment]
Thanks for the confirmation.
