### ISSUE TITLE
Hierarchical Clustering

### ISSUE THREAD

**Issue by LauriJC** [jasp-stats/jasp-issues#921]
* Enhancement: Under Linkage, it would be very helpful to have Ward as an option.  In my field, Ward is seen as the optimal linkage because it not only averages distance between all members of the clusters but also adjusts for covariances.
* Purpose:  Cluster analysis in Machine Learning - Hierarchical clustering
* Use-case: Not sure what this is here but provided information about for use

**Is your feature request related to a problem? Please describe.**
 It sort of is related to a problem in the sense that I cannot teach with JASP for cluster without the Ward option.  I was so excited that you added clustering and then disappointed that hierarchical did not have Ward option when R does. 

**Describe the solution you'd like**
 Just Ward added as a linkage option. 

**Describe alternatives you've considered**
 Using R and SPSS

**Additional context**

**Comment by koenderks** [comment]
Thanks, very useful and easy to implement. Consider it done via https://github.com/jasp-stats/jasp-desktop/pull/4222. I've added methods `ward.D`, `ward.D2`, `mcquitty`, and `median`.  Will be in the next version of JASP.

**Comment by LauriJC** [comment]
Awesome!
