### ISSUE TITLE
JASP for Mac Won't Open

### ISSUE THREAD

**Issue by madtownpeters** [jasp-stats/jasp-issues#923]
* JASP version:0.13.1 but I've also tried to download multiple versions - none will open

* OS name and version: Mc High Sierra 10.13.6
* Bug description: JASP will not open. When I click on the application, I get an error that says JASP quit unexpectedly.

**Comment by FransMeerhoff** [comment]
Dear @madtownpeters ,

Sorry to hear that you have this problem.

If you are sure that you have downloaded the http://static.jasp-stats.org/JASP-0.13.1.0-preCatalina.dmg version and overwrite the last installation can you check the following from a terminal:

>cd /Applications/JASP.app/Contents/MacOS
>./JASP

Some info in now shown on the screen.
Can you copy that info and add it to this issue?
(If you do not know how open a terminal press on the search button from Mac and type 'terminal.app')

We hope that this info gives us some more info what is going on.

Kind regards
Frans Meerhoff

@boutinb Are you still running High Sierra and did you test the latest preCatalina version?
