### ISSUE TITLE
JASP crashed

### ISSUE THREAD

**Issue by jopwonya** [jasp-stats/jasp-issues#924]
* JASP version: 0.13.1
* OS name and version: Windows 10 (10.0)

* Analysis: 
* Bug description:
* Expected behaviour:

#### Steps to reproduce:

-----------------------------------------------------------------------

### Debug information:
**Engine # 0** process  is *running* and it's state is *idle*.
**Engine # 1** process  is *running* and it's state is *idle*.
**Engine # 2** process  is *running* and it's state is *idle*.
**Engine # 3** process  is *running* and it's state is *idle*.

[Commit used](https://github.com/jasp-stats/jasp-desktop/commit/d2d5d378a3ccb371eb6ea357352966b510c516a6)

**Comment by Tudan90** [comment]
I keep getting this message when trying selecting my data in the contingency tables tab. How can this be resolved?
![Capture](https://user-images.githubusercontent.com/69343875/89630575-7a324e80-d897-11ea-868f-304d46d55361.JPG)

**Comment by boutinb** [comment]
Can you send us your JASP file, and a precise description of what you do before it crashes?
Use GitHub to send the JASP file (you have first to transform it as a zip file).
