### ISSUE TITLE
Serial Mediation

### ISSUE THREAD

**Issue by amsa1234** [jasp-stats/jasp-issues#925]
Hi, thanks for the terrific work that you do. Right now, the mediation feature appears to allow for the use of multiple mediators. However, multiple mediation can be parallel or serial. I believe that, at present, the JASP mediations with multiple mediators are all parallel mediation. Is it possible to set up the mediation so that we can have serial mediation as well (i.e., A -> M1 -> M2 -> B, where A is the treatment/condition, M1 and M2 are mediators, and B is the outcome).

**Comment by boutinb** [comment]
@AlexanderLyNL Do you know who can answer this question?

**Comment by AlexanderLyNL** [comment]
I think that Van Kesteren can best answer this. At the same time, I think that this can be done manually with duplicate analysis and gradually add terms in the subsequent analysis.

**Comment by vankesteren** [comment]
You can do this in the SEM module. The lavaan code from the mediation analysis can give you a head-start!
