### ISSUE TITLE
reloading jasp data file from csv does not work in version 0.13

### ISSUE THREAD

**Issue by BRauchbauer** [jasp-stats/jasp-issues#926]
* JASP version: 0.13

* OS name and version: Windows 10
* Analysis: 
* Bug description: data editing in .csv file does not transfer to jasp file
* Expected behaviour:

**Comment by AlexanderLyNL** [comment]
We have no idea how to solve this without the jasp and csv file. You can add them as a zip to this thread, 

https://github.com/jasp-stats/jasp-issues/issues/926

if you'd like us to look into this.

**Comment by BRauchbauer** [comment]
attached is a jasp file and the corresponding csv file
the jasp version is 0.13.1 which I recently updated

thanks!

Am Fr., 7. Aug. 2020 um 11:43 Uhr schrieb AlexanderLyNL <
notifications@github.com>:

**Comment by boutinb** [comment]
@BRauchbauer, what do you do exactly: you load first a csv file in JASP, change one cell of this csv file, and you do not see this change in JASP?

**Comment by BRauchbauer** [comment]
Exactly. I click on the data in jasp to change it - Csv file opens, I add a data column and save csv file - jasp doesn’t update

**Comment by boutinb** [comment]
Which spreadsheet editor do you use to edit your csv file? Can you try also notepad to change just one value?
