### ISSUE TITLE
Jasp crashed: Many more empty cells than valid cells

### ISSUE THREAD

**Issue by Tudan90** [jasp-stats/jasp-issues#927]
* JASP version:

* OS name and version: Windows
* Analysis: Contigency tables
* Bug description: jasp crash
![Capture](https://user-images.githubusercontent.com/69343875/89630848-d5fcd780-d897-11ea-959a-3c351d833ba6.JPG)

* Expected behaviour:

**Comment by AlexanderLyNL** [comment]
We have no idea how to solve this without the jasp. You can add them as a zip to this thread, 

https://github.com/jasp-stats/jasp-issues/issues/927

if you'd like us to look into this.

**Comment by AlexanderLyNL** [comment]
Also please complete the issues template to provide us with the information to study this issue.

**Comment by Tudan90** [comment]
> We have no idea how to solve this without the jasp. You can add them as a zip to this thread,
> #927
> if you'd like us to look into this.

I am not sure I can follow. Do you need the Jasp version I am using? If yes it is 0.11.1.0

**Comment by Tudan90** [comment]
> Also please complete the issues template to provide us with the information to study this issue.

If you mean these points: 

Expected behaviour:
Steps to reproduce:
Go to '...'
Click on '....'
Scroll down to '....'
See error

I have absolutely no clue what is expected. Sorry, but you would need to talk me through this...

**Comment by AlexanderLyNL** [comment]
So you're using version JASP 0.11.1. Could you please try the same thing with the newest version of JASP? See

https://jasp-stats.org/download/

If JASP crashes for certain analyses, then it would be good to save the jasp file, add that jasp file to a zip and then send it to us, by adding it to the thread.

**Comment by Tudan90** [comment]
![Capture](https://user-images.githubusercontent.com/69343875/89636850-2cbadf00-d8a1-11ea-8e78-d98b11c5716c.JPG)
That's the message that came up now. I did not even select the data yet...

**Comment by Tudan90** [comment]
[Decoded Quick & Arch- Preservation comparisons only.zip](https://github.com/jasp-stats/jasp-issues/files/5040865/Decoded.Quick.Arch-.Preservation.comparisons.only.zip)

I am doing a study on skeletal preservation (Quantiative 0%-100% (scale data), and Quantitative 1-3-> poor to good) and try to test it against grave location (inside/outside of the church) and whether the presence of grave goods (presence/absence) had an impact on it. I hope that helps?

As I have got to go now I am not able to get back to you until tomorrow. Thank you so much for your patience and help!

**Comment by AlexanderLyNL** [comment]
Okay what I see is that the data contains many many more columns and rows, which are viewed as missing data. This might be confusing for jasp.

- On my mac 10.13.6, the contingency table analysis in jasp 0.13.1 doesn't crash immediately
- Could you tell me how you recorded the data? Did you use some kind of program for this? 
- @koenderks would you be able to check this on Windows and see what kind of behaviour you get

**Comment by koenderks** [comment]
@AlexanderLyNL On my computer I am able to open the .jasp file and select contingency tables without causing a crash

![image](https://user-images.githubusercontent.com/25059399/89638711-8d034e00-d8ac-11ea-9490-969dae436a43.png)

**Comment by Tudan90** [comment]
I have tried it again now and it works absolutely fine. Thank you for your help!

**Comment by Tudan90** [comment]
> Okay what I see is that the data contains many many more columns and rows, which are viewed as missing data. This might be confusing for jasp.
> 
> On my mac 10.13.6, the contingency table analysis in jasp 0.13.1 doesn't crash immediately
> Could you tell me how you recorded the data? Did you use some kind of program for this?
> @koenderks would you be able to check this on Windows and see what kind of behaviour you get

I recorded the data on Microsoft Excel. I am not sure why it shows all these additional columns/rows. I used to have some more variables in the columns, but as it kept crashing I split my original datasheet into separate ones based on the topic I want to analyse and deleted those. The datasheet used to be formatted as a table and I have noticed that this caused some problems from time to time, especially when inserting/deleting data... As I had problems when inserting/deleting data there I converted it back to a range to be able to make those changes. Not sure if that would still cause problems for Jasp?

**Comment by JorisGoosen** [comment]
It is quite possible that sometime during all these transformations excel outputted data in a format JASP didn't get.

Now however you seem to be able to load the data properly so I guess this issue can be closed.
