### ISSUE TITLE
mgm estimator bug 

### ISSUE THREAD

**Issue by gimagarotto** [jasp-stats/jasp-issues#928]
* JASP version: 0.12.2.0

* OS name and version: Windows 10
* Analysis: Network analysis 
* Bug description: Error in if (options[['estimator']] = 'mgm' && options[['mgmVariableType']] ≠ : missing value where TRUE/FALSE needed

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.networkAnalysisPlotContainer(mainContainer, network, options)

.networkAnalysisNetworkPlot(plotContainer, network, options)
* Expected behaviour:

#### Steps to reproduce:
1. Go to 'Network analysis'
2. Click on 'mgm estimator'
3.. See error

Can you help me?

**Comment by vandenman** [comment]
Thanks for reporting the error!

Unfortunately, I can't replicate this error with the latest JASP version (0.13.1). Could you check if the error persists with the latest version? You can get it from https://jasp-stats.org/download/

If the error persists, could you perhaps share the data so I can reproduce the error?
