### ISSUE TITLE
Feature request: Internal Update option

### ISSUE THREAD

**Issue by AndrewDWilson** [jasp-stats/jasp-issues#93]
As a fairly uncomplicated user, I would love the option to simply 'update' JASP rather than install the latest and uninstall the earlier versions. I mostly just want to be able to use whatever the latest features are and I'm generally not too worried about version issues.

**Comment by tomtomme** [comment]
This would be a great feature, yes. My students often work with outdated JASP versions and just expect of any app to update itself. Uninstalling and redownloading any app is completely foreign to them.

**Comment by tomtomme** [comment]
will this be available through the new MSIX installer on windows? And how will MacOS handle this?

**Comment by boutinb** [comment]
@RensDofferhoff ?

**Comment by RensDofferhoff** [comment]
The windows store has auto update & notification capabilities. 
So if all goes well this should be resolved for windows users choosing the store install.
Lets see how it goes in the upcoming version before making it the recommended install path.

I imagine that if we publish on the apple store the same is true for mac users. But publishing there will be a pain.

**Comment by tomtomme** [comment]
closing, since duplicate of #2136
Lets discuss there how the transition goes.
