### ISSUE TITLE
Error loading developer module (missing description.json file)

### ISSUE THREAD

**Issue by dustinfife** [jasp-stats/jasp-issues#930]
* JASP version:
* OS name and version: Mac 10.15.4
* Analysis: NA
* Bug description: After specifying the correct folder in developer mode (preferences->advanced). I click on "Install Developer Module," then get this error:

<img width="429" alt="Screen Shot 2020-08-07 at 12 38 47 PM" src="https://user-images.githubusercontent.com/7094676/89668626-123a3300-d8ac-11ea-84fd-f61948178022.png">

* Expected behaviour: The module should update with the changes. 

#### Steps to reproduce:
1. Go to menu->preferences->advanced->click "developer mode (beta)"
2. Select development folder: choose the right folder
3. Click + to add a module -> install developer module. 

I'd upload the log files, but I don't remember where they're located

**Comment by boutinb** [comment]
@dustinfife Your module (https://github.com/jasp-stats/VisualModeling) was already updated: the description.json is now a description.qml.  It is better to clone this repository and to update this one. I will add then your changes to the main repository.  It is a bit awkward now, but over 1 month (after 0.14) this repository will be directly a submodule of the main (jasp-desktop) repository and all changes will be automatically in JASP.

**Comment by JorisGoosen** [comment]
And @dustinfife the log files can always be found through Preferences->Advanced->Browse/Open logfiles

**Comment by dustinfife** [comment]
Sorry, let me clarify. I know it was updated universally for JASP users, but I'm developing some new features. I want to test these features on my local version of JASP. It used to be that I could do so by clicking "install developer module," but not anymore. 

Currently, I'm bypassing that by doing the following:

1. Reinstalling flexplot in R.
2. Copying the build files from R's local library over to JASP's (/Applications/JASP.app/Contents/Frameworks/R.framework/Versions/3.6/Resources)
3. Close jasp
4. Open jasp and test features. 

I figured out how to write bash scripts the other day, so this whole process isn't as time-consuming as it was, but it would be nice to be able to do that all within JASP.

**Comment by dustinfife** [comment]
Thanks, @JorisGoosen. I was able to see the log files. In there it says,

"00:00:53.106: Trying to find 'description.json' in folder: '/Users/fife/Documents/R Packages/flexplot'
00:00:53.108: Trying to find 'description.json' in folder: '/Users/fife/Documents/R Packages/flexplot/build'
00:00:53.109: Trying to find 'description.json' in folder: '/Users/fife/Documents/R Packages/flexplot/build/js'"

My description.json file is in the flexplot/inst folder. Should it be in the root flexplot folder?

**Comment by JorisGoosen** [comment]
Well, as @boutinb mentioned, we changed the way the description for a module is read. 
As you can see in this commit from may: https://github.com/jasp-stats/VisualModeling/commit/958c3c04daa62b472d6adc4bd40f18bf8fbe5ecf#diff-ad3d79da558ecb11e5d3e206e0cca3e0 `description.json` has been replaced by `Description.qml`.

Description.qml ought to be in the 'inst' folder.
The code is still looking for 'description.json' in certain cases but this is deprecated and will be removed.

I would suggest you fork https://github.com/jasp-stats/VisualModeling and work there from the current commit in `master`.

**Comment by JorisGoosen** [comment]
Then you can make your changes there and test them as a developer module and when it is done we can move the code to `stable`.
