### ISSUE TITLE
Export indivdual tables to .doc/.docx

### ISSUE THREAD

**Issue by saurabhr** [jasp-stats/jasp-issues#931]
please!

**Comment by AlexanderLyNL** [comment]
Hi @saurabhr,

This is feature we implemented in JASP some time ago. Perhaps even at the start. The following gif shows how

https://jasp-stats.org/wp-content/uploads/2017/10/tableCopy.gif

@mellevdlinde we should make people aware of this again. 

Cheers,
Alexander
