### ISSUE TITLE
Labels not being displayed anymore in spreadsheet

### ISSUE THREAD

**Issue by djdekker** [jasp-stats/jasp-issues#933]
* JASP version: 0.13.1
* OS name and version: macOS 11.0 Big Sur (public beta)
* Analysis: N/A (spreadsheet)
* Bug description: labels are not shown anymore in spreadsheet after changing variable type ordinal -> scale -> ordinal
* Expected behaviour: for ordinal variables, labels are always shown in the spreadsheet

Steps to reproduce:
1. Open test.jasp.
2. Change the variable type of v1 from ordinal to scale and see the labels disappear as they should.
3. Change the variable type of v1 back to ordinal.
4. The labels are not displayed in the spreadsheet anymore (but they can be shown by clicking on the variable name).

![test](https://user-images.githubusercontent.com/5346286/89716516-ddaea000-d9ad-11ea-8d90-16ef1e96e05d.png)

[test.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/5045873/test.jasp.zip)

**Comment by AlexanderLyNL** [comment]
Thanks for the report! Another very useful find!

@JorisGoosen I can replicate this on macOS 10.13.6 High Sierra.
- The ordinal information is retained after switching from ordinal-scale-ordinal, but I suspect only partially 
- After switching from ordinal-scale-ordinal, and reversing order of all factors leads to label information being destroyed
- After switching from ordinal-scale-ordinal, and changing the order of one factor level leads to hard crash
