### ISSUE TITLE
Clarify wording in explanation on Benford's Law (Audit/JfA module)

### ISSUE THREAD

**Issue by JoKeyser** [jasp-stats/jasp-issues#934]
* JASP version: 13.1
* Analysis: Audit -> Benford's Law
* Bug description: 
Sorry if this is a bit nitpicky.
During translation work, I stumbled across the explanatory text in Benford's Law (in `stable`, see e.g. [here](https://github.com/jasp-stats/jasp-desktop/blob/stable/JASP-Engine/JASP/po/R-JASP.pot#L811)), emphasis mine:
> Benford's law states that in many naturally occurring collections of ***numbers***, the leading significant ***number*** is likely to be small. The goal of this procedure is to determine to which extent the first leading ***numbers*** in the ***population*** follow Benford's law, and to test this relation with <b>%1$s</b> confidence.

At first reading, I got confused which use of "number" refers to the *digit*, or observations in the data/population.

* Expected behaviour: Clearer formulation, here my suggestion:

"Benford's law states that in many naturally occurring collections of ***numerical observations***, the leading significant ***digit*** is likely to be small. The goal of this procedure is to determine to which extent the first leading ***digits*** in the ***data set*** follow Benford's law, and to test this relation with <b>%1$s</b> confidence."

If others agree, I'm happy to send a pull request, if you point me to the correct file where to change this - I would assume https://github.com/jasp-stats/jasp-desktop/blob/stable/JASP-Engine/JASP/po/R-JASP.pot?

**Comment by AlexanderLyNL** [comment]
Hi Johannes, 

Thanks for pointing this out. This is very useful. @koenderks could you look into this?

Cheers,
Alexander

**Comment by koenderks** [comment]
Thanks for the suggestion, I agree that this is more clearly formulated. I will make these adjustments on the R side. @FransMeerhoff  can you give a little suggestion on the best course of action from there? I believe these changes will then automatically show up in the next versions of the .po files, correct?

**Comment by FransMeerhoff** [comment]
@koenderks 
If you take care of the R-side, I'll make a PR with Dutch translation to check. OK for time being?

**Comment by AlexanderLyNL** [comment]
Fixed
