### ISSUE TITLE
JASP crashed

### ISSUE THREAD

**Issue by harveyalone** [jasp-stats/jasp-issues#936]
* JASP version: 0.13.1
* OS name and version: Windows 10 (10.0)

* Analysis: 
* Bug description:
* Expected behaviour:

#### Steps to reproduce:

-----------------------------------------------------------------------

### Debug information:
**Engine # 0** process *does not exist (anymore)* and it's state is *initializing*.
**Engine # 1** process *does not exist (anymore)* and it's state is *initializing*.
**Engine # 2** process *does not exist (anymore)* and it's state is *initializing*.
**Engine # 3** process *does not exist (anymore)* and it's state is *initializing*.

[Commit used](https://github.com/jasp-stats/jasp-desktop/commit/d2d5d378a3ccb371eb6ea357352966b510c516a6)

**Comment by boutinb** [comment]
What do you do exactly? Do you start JASP by clicking its icon, and it crashes immediately?
