### ISSUE TITLE
Bayesian Linear Mixed Models with Poisson distributions

### ISSUE THREAD

**Issue by jubera** [jasp-stats/jasp-issues#937]
* Enhancement: Bayesian Linear Mixed Models with Poisson distributions
* Purpose:
* Use-case: 

**Describe the solution you'd like**
Implementation

**Comment by EJWagenmakers** [comment]
If you go to "Mixed Models" on the JASP ribbon, you'll find the Bayesian Generalized LMMs in there, and this includes the Poisson case.
E.J.

**Comment by jubera** [comment]
That's wonderful news! thanks a lot. I'm sorry that I did not see it before by myself, but I did only check in Bayes Linear Mixed Models
