### ISSUE TITLE
Large dataset: Crash when changing variable type

### ISSUE THREAD

**Issue by djdekker** [jasp-stats/jasp-issues#938]
* JASP version: 0.14 (nightly build of August 14th, 075f70b4e3b7cd994b0efe9bf78da79cc6468b83)
* OS name and version: macOS 11.0 Big Sur (Public beta)
* Analysis: N/A (spreadsheet)
* Bug description: JASP crashes when changing variable type in a large dataset
* Expected behaviour: JASP should not crash

**Steps to reproduce**
1. Open the attached dataset, which contains 85,938 cases.
2. In the spreadsheet, change the variable type of Order ID from Scale to Nominal.
3. JASP crashes immediately.

The dataset contains the first 85,938 cases of the (even larger) "100000 Sales Records" dataset available from [E for Excel](http://eforexcel.com/wp/downloads-18-sample-csv-files-data-sets-for-testing-sales/), with which the same crash occurs. I removed cases to make the dataset smaller. I found that the crash does not occur when the dataset contains the first 85,157 cases.

JASP 0.10.2 shows the same behaviour as JASP 0.14:
85,157 cases => no crash upon changing variable type
85,938 cases => crash upon changing variable type
&nbsp;

[85938 Sales Records.csv.zip](https://github.com/jasp-stats/jasp-issues/files/5078300/85938.Sales.Records.csv.zip)

**Comment by boutinb** [comment]
@JorisGoosen Do you think you can still fix this for 0.14? If it can't be fix next week, it must be postponed to 0.15

**Comment by JorisGoosen** [comment]
I would have to look at the issue with the data etc, next week I can do that. And know more.
