### ISSUE TITLE
Wilcoxon signed ranks show p < .001 and statistic of 0

### ISSUE THREAD

**Issue by shariellen** [jasp-stats/jasp-issues#940]
* JASP version:  0.13.1

* OS name and version:  Windows 8.1 enterprise
* Analysis: Paired samples t test
* Bug description:  Running Wilcoxon on 10 pairs (N = 32).  All  p values reporting p < .001.  Value of statistic is 17, 8.5, 8.5, 8, 7 and Five Zeros.  How can a Wilcoxon of  p < .001 be equal to zero?  I also ran the student t test and those look correct, same p < .001 but values from 6.5 to 11.5.  How can something have a t = 10.2 and wilcoxon = 0
* Expected behaviour:  non-zero results with p < .001 

#### Steps to reproduce:
1. Go to 'paired samples t test'
2. Click on 'student, wilcoxon, m1 not equal m2, excluded per dependent v.'
Push pairs in by number:  QnPre and QnQost (there are 10 pairs)
3. Scroll down to --stats and p appear on right
4. See error:  pairs 1, 6, 8, 9 and 10 show 0 as the statistic
zip file attached
[shariellen github wilcoxon bug.zip](https://github.com/jasp-stats/jasp-issues/files/5084067/shariellen.github.wilcoxon.bug.zip)

**Comment by JohnnyDoorn** [comment]
Thanks for reporting this on GitHub as well!
From my reply on twitter: This is normal behavior, as the test-value of the signed rank statistic is equal to n*(n+1)*0.5. So any deviation from this value (lower or higher) will go towards evidence against H0, so the p-values you report seem to make sense.

You can try this in R:
wilcox.test(-(1:10)) # all negative differences, will give V = 0, p-value = 0.001953
wilcox.test(1:10) # all positive differences, will give V = 55, p-value = 0.001953

I will close this for now, please reopen if you have more questions!
Kind regards
Johnny
