### ISSUE TITLE
Chart text not displaying on linux

### ISSUE THREAD

**Issue by ndpegram** [jasp-stats/jasp-issues#943]
* JASP version: 0.13.1
* OS name and version: Ubuntu 20.04.1 LTS
* Analysis: Bug in chart creation. Possible font issue.
* Bug description: Chart type displaying as tofu (empty square boxes).
* Expected behaviour: Labels displayed in readable type.

1. Open the Presidents' Height sample file.
1. Create the Height Ratio boxplot as per the instructions under "Filtering a Continuous Column" in the tutorial at https://jasp-stats.org/2018/06/27/how-to-filter-your-data-in-jasp/
1. All text is displayed as tofu on Linux, but doing the same on Windows displays the outlier value as expected.

Interestingly, the type in the Bayesian analysis which is pre-existing in the data file displays as expected.

![image](https://user-images.githubusercontent.com/3038811/90591053-adb89580-e214-11ea-9fbd-ca9e889fb0c4.png)

**Comment by JoKeyser** [comment]
@ndpegram, have you tried to refresh the fonts, as described at https://jasp-stats.org/linux-installation-guide/ "Font problem in plots"?
"To solve this problem you can simply execute the following in a terminal:"
```
flatpak run --command=fc-cache org.jaspstats.JASP -f -v
```

**Comment by ndpegram** [comment]
That's it exactly. Thanks I'd missed that.
