### ISSUE TITLE
Effect sizes for post-hoc interactions not printing

### ISSUE THREAD

**Issue by mjkofler** [jasp-stats/jasp-issues#949]
* JASP version: 0.13.1

* OS name and version: macOS Catalina 10.15.6
* Analysis: Repeated measures ANOVA (Classical)
* Bug description: under the Post Hocs Tests menu, clicking "Effect Size" used to print Cohen's d effect size for each post hoc contrast. in 0.13.1 it still does this for main effects but not for interactions (other columns print as expected, i.e., mean difference, SE, t, p)
* Expected behaviour: Cohen's d effect sizes included in table for interaction contrast when that option is checked

#### Steps to reproduce:
1. Go to '...' ANOVA > Classical Repeated Measures ANOVA
2. Click on '....' under Post Hoc Tests menu, click check box for "Effect size". Add main and interaction terms to the post hoc selection box
3. Scroll down to '....' Post Hoc Comparisons - Between * RM Factor 1
4. See error: Missing column for cohen's d effect sizes

**Comment by mjkofler** [comment]
Issue remains in version 0.14

**Comment by JohnnyDoorn** [comment]
Hi @mjkofler 

Unfortunately we do not print effect sizes for interaction effects, since it does not seem very straightforward how to calculate this. I am aware of this, and want to start working on this in the next year (we are currently undertaking research project about ANOVA's and effect sizes that will hopefully provide more insight).

Kind regards
Johnny

**Comment by mjkofler** [comment]
Thanks for the quick reply! Cohen’s d ESs were printed for interaction effects (between x repeated measure) in earlier versions of JASP. The group x time interaction is the critical test in RCTs, so the omission of corresponding effect sizes for these tests in more recent JASP versions was notable. Thanks!

**Comment by JohnnyDoorn** [comment]
We used a rough simple measure, which was the t statistic, divided by the square root of n. In the end I did not feel comfortable with that, so removed it, pending a better method. So if you want, you can apply this yourself, if you already need an effect size (albeit a rough one).

**Comment by mjkofler** [comment]
Great might be the enemy of good in this case? Would it be possible to add it back for cases where the repeated measure has 2 levels, in which case the effect sizes would be straightforward, as paired samples T-tests just run separately for each of the between-subjects groups (which is already implemented when running paired samples T-tests, but saves a lot of time versus having to ‘select cases’ a bunch of times to get that test for each group separately)?

**Comment by juliuspf** [comment]
Due to some tricky wording this wasn't closed through https://github.com/jasp-stats/jaspAnova/pull/90, but it should have been
