### ISSUE TITLE
Correlation variables WITH variables

### ISSUE THREAD

**Issue by Marian-Popa** [jasp-stats/jasp-issues#95]
## Template for enhancement requests
 
* Enhancement: 
Option to correlate one/more variables WITH other one/more variables.
* Purpose:
It covers the situation where we are not interested in the correlation matrix, but only the correlation of certain variables WITH other variables.
SPSS has this option only through syntax, although in an old version it was included in the correlation dialog box.

Best regards,
Marian

**Comment by tomtomme** [comment]
@Marian-Popa 
Now available:
Regression => Correlation => Additional Options => Display pairwise 

This is not exactly but almost what you requested.
Does this suffice?

**Comment by Marian-Popa** [comment]
Hi,

Yes, it is good solution.

Best regards,
Marian
