### ISSUE TITLE
Fit of path analysis

### ISSUE THREAD

**Issue by Manuel-Sp1211** [jasp-stats/jasp-issues#950]
* JASP version: 0.13.1

* OS name and version: Catalina 10.15.6
* Analysis: SEM - Medition analysis
* Bug description: Path analysis with observed variables do not provide fit indices (CFI, RMSEA, etc.) How can I get this indices to report in a paper?
* Expected behaviour:

**Comment by vankesteren** [comment]
Hi Manuel, mediation analysis indeed does not have this option currently. For now, you can copy-paste the syntax generated by the mediation analysis into the SEM analysis for obtaining these metrics. To get the syntax, go to options  and tick "lavaan syntax".
