### ISSUE TITLE
"INSTALLPATH" not used for all the binaries

### ISSUE THREAD

**Issue by CdeMills** [jasp-stats/jasp-issues#951]
* JASP version: 0.11

* OS name and version: CentOS-8 x86_64

* Analysis: Some of the binaries may be installed elsewhere than /usr/bin by tweaking JASP.pri. I would like to keep all programs under /usr/bin managed by "dnf"

* Bug description: "jasp" is still installed as /usr/bin/jasp

* Expected behaviour: jasp should be installed as "$INSTALLPATH"/jasp

#### Steps to reproduce:
1. edit JASP.pri, set INSTALLPATH to INSTALLPATH = /usr/local/bin
2. mkdir build; cd build; qmake-qt5 ../JASP.pro; make
3. make -n install => 
test -d /usr/bin || mkdir -p /usr/bin
/usr/bin/qmake-qt5 -install qinstall -exe ../jasp /usr/bin/jasp
strip /usr/bin/jasp

the file build/JASP-Desktop/Makefile uses INSTALL_ROOT as prefix. This INSTALL_ROOT is not defined anywhere in the whole set of files from the checked out sources.
Any hint ?
Regards

Pascal

**Comment by boutinb** [comment]
@JorisGoosen Could you answer this request?

**Comment by JorisGoosen** [comment]
INSTALL_ROOT seems to be a Qt specific feature as this SO tells me: https://stackoverflow.com/questions/8360609/how-to-make-use-of-the-install-root-that-resides-in-generated-makefiles/13736063

@CdeMills can I ask why you are trying to install JASP 0.11 though? 
Have you tried newer versions?

It does seems that INSTALLPATH is not used correctly by our qmake files indeed.
I've made a quick change at https://github.com/jasp-stats/jasp-desktop/commit/2815e2a06cb1a6ec8434f6d720f4483fd84e8316
(In the branch INSTALLPATH) 

Maybe you can try this out and maybe tweak it further? I'm not in a position to test this properly soon I'm afraid but I can certainly give you more assistance in fixing this.
