### ISSUE TITLE
Problem starting JASP

### ISSUE THREAD

**Issue by LeonieBorne** [jasp-stats/jasp-issues#955]
* JASP version: 0.13.1 (same problem if I try version 0.11.0 or 0.12.1)

* OS name and version: Ubuntu 20.04 (but I had the same problem with Ubuntu 18.04)
* Analysis: I try to launch JASP as normal.
* Bug description: 

When I launch JASP, the following window opens:

![jasp-bug](https://user-images.githubusercontent.com/19991748/91794602-cedea480-ec5e-11ea-9433-9dad0a78576b.png)

This is the error message I get in the terminal:

```
$ flatpak run org.jaspstats.JASP
Making new argument list for Application startup: org.jaspstats.JASP
Starting JASP
Gtk-Message: 14:20:39.421: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:20:39.421: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
Desktop:	new LanguageInfo created: Language: '' qmFolder: '' and qmFilenames: ''
Desktop:	new LanguageInfo created: Language: 'English' qmFolder: '/app/bin/Resources/Translations' and qmFilenames: ''
Desktop:	new LanguageInfo created: Language: '' qmFolder: '' and qmFilenames: ''
Desktop:	findQmlFiles(qmlocation = /app/bin/Resources/Translations) called
Desktop:	Checking qm file: /app/bin/Resources/Translations/jasp_nl.qm
Desktop:	Language (30) not registered in LanguageModel, adding it now
Desktop:	new LanguageInfo created: Language: 'Dutch' qmFolder: '/app/bin/Resources/Translations' and qmFilenames: '/app/bin/Resources/Translations/jasp_nl.qm'
qrc:/components/JASP/Widgets/ModulesMenu.qml:69:4: QML Column: Binding loop detected for property "width"
R_HOME: /app/lib64/R/
R_HOME: /app/lib64/R/
R_HOME: /app/lib64/R/
R_HOME: /app/lib64/R/
```
Do you have any idea where the problem might come from?
Thanks in advance!

**Comment by boutinb** [comment]
@JorisGoosen or @vandenman, do you have any idea about this problem?

**Comment by JorisGoosen** [comment]
I've seen this before here: https://forum.cogsci.nl/discussion/6361/jasp-gui
The solution is turning on safe graphics through starting JASP like:  `flatpak run org.jaspstats.JASP --safeGraphics` from a terminal.

@LeonieBorne what kind of videocard do you have?

**Comment by LeonieBorne** [comment]
It works, thank you very much @JorisGoosen!
Here is my graphic card information:

```
$ lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation Iris Plus Graphics G7 (rev 07)
```

**Comment by JorisGoosen** [comment]
Aah thank you for that and happy to hear it works :)
