### ISSUE TITLE
Syntax Mode

### ISSUE THREAD

**Issue by g30diaz** [jasp-stats/jasp-issues#960]
* Enhancement:
* Purpose:
* Use-case:

**Is your feature request related to a problem? Please describe.**
 

**Describe the solution you'd like**
 

**Describe alternatives you've considered**
 

**Additional context**

**Comment by EJWagenmakers** [comment]
High priority, under development, & making good progress!

**Comment by g30diaz** [comment]
Great to hear this! Thank you!

George Diaz

"Finishing is better than starting, patience is better than pride."
