### ISSUE TITLE
Exploratory Factor crashes

### ISSUE THREAD

**Issue by robkoper** [jasp-stats/jasp-issues#961]
* JASP version: 0.13.1

* OS name and version: OSX Catalina 10.15.5
* Analysis: 
Exploratory Factor Analysis
* Bug description:
I read a csv file with likert scale items (1-7). It reads it as ordinal data (I had to change it manually to scale variables).
Running Factor Analysis results with a certain number of variables to the message below:

_**The following problem(s) occurred while running the analysis:
Data not valid: too many missing values in variable(s) (1.t)houtoven-bezit, (1.t)houtoven-gemaakt, (1.t)houtoven-consumentenrapporten, (1.t)houtoven-vergelijken, (1.t)houtoven-verschillende, (1.t)houtoven-voorkeur, (1.e)houtoven-vrienden en familie, (1.e)houtoven-noodzakelijk, (1.e)houtoven-uitziet, (2.e)merkkleding-uitziet, (2.e)merkkleding-samenstelling, (3.t)sieraad-bezit, (3.t)sieraad-gemaakt, (1.e)houtoven-samenstelling, (2.t)merkkleding-bezit, (2.t)merkkleding-gemaakt, (2.t)merkkleding-consumentenrapporten, (2.t)merkkleding-vergelijken, (2.t)merkkleding-verschillende .**_

However, there are NO missing values in any of these. This error occurs when adding more than a certain number of variables for the factor analysis. It doesn't matter which variables are added, when adding random one by one, at a certain moment this error occurs. 

I will add the dataset (only the first set of variables are set to scale type.

[Archive.zip](https://github.com/jasp-stats/jasp-issues/files/5174710/Archive.zip)

**Comment by djdekker** [comment]
Your data set contains only 15 cases and you're trying to carry out EFA with more than 15 variables.

I have been using JASP for EFA's with dozens of variables. JASP handles that easily, as long as the data set contains enough cases.

**Comment by robkoper** [comment]
Ah, thanks, didn’t know this constraint!
Rob

**Comment by vandenman** [comment]
Sorry for taking so long to reply.

It's indeed true that you can't use more variables than there are observations in the data set. However, the error message about missing values is rather inaccurate. 

The changes in the PR linked above hopefully make the error message a bit more informative (on the left is the old error message, on the right the new one):
![image](https://user-images.githubusercontent.com/21319932/94784241-2a22c480-03ce-11eb-8f14-24a9b537f5a0.png)

**Comment by robkoper** [comment]
Yes, this will help, thanks!
Rob
