### ISSUE TITLE
Repeated-measure Anova contrasts

### ISSUE THREAD

**Issue by Girouxma** [jasp-stats/jasp-issues#966]
* JASP version: 0.13.1
* OS name and version: Windows 10 professional
* Analysis: Repeated measure Anova, contrasts
* Bug description: When I compare results from repeated measure Anova with Statistica and with JASP, I get the same results but, when it comes to specific contrasts they are different ! The SE is different (example : 0.81 for Statistica and 1.35 for JASP) so the t and the p value are not the same either (Statistica : t = -4.78, p=0.002; JASP : t=-2.87, p=0.009). It doesn't occur for this example only but for all datasets and contrasts I have tested.

ANOVA with Statistica : 
![ANOVA](https://user-images.githubusercontent.com/70891307/92379713-30dc5580-f108-11ea-867b-1966458bac6a.png)

Contraste with Statistica :
![Contrastes](https://user-images.githubusercontent.com/70891307/92379709-30dc5580-f108-11ea-944f-8a8a487cac0c.png)

ANOVA + Contrastes with JASP :
![image](https://user-images.githubusercontent.com/70891307/92379757-3f2a7180-f108-11ea-9eb5-52d65e03c9ea.png)

* Expected behaviour:
Is it possible to fix this problem ? I know it is possible to use different sum of square for error and some are better than others. Could you fix the way the contrasts are calculated so that it is consistent with other softwares like statistica ?

You can find the CSV file with the data and the JASP file there : 
[Bush Tucker Food.zip](https://github.com/jasp-stats/jasp-issues/files/5182663/Bush.Tucker.Food.zip)

**Comment by JohnnyDoorn** [comment]
Hi @Girouxma ,

The difference here is whether you pool the standard error or not. The classic RM ANOVA model assumes that these are pooled, and so it makes sense to use the pooled errors in the follow up analyses. For some cases, we do provide the option deviate from this and not use the pooled standard errors (see the tick boxes in contrast and posthoc tests), for instance when the equal variances assumption does not hold. I have been thinking about how to approach this best, as using pooled SE or not is not a trivial decision. I believe that when we offer the full analysis without pooling SE, we have to change the RM ANOVA model that it is all based on, so this change requires a bit more rewriting. 
See below for an illustration in R:
```
library(afex)
library(emmeans)
dat <- read.csv("~/Downloads/BushFood.csv")

t.test(dat$Stick.Insect, dat$Kangaroo.Testicle, paired = TRUE) # gives result of statistica, t = 4.7753

longdat <- data.frame(group = rep(colnames(dat)[2:5], each = 8),
                      y = unlist(dat[, 2:5]),
                      id = rep(1:8, 4))
afexMod <- afex::aov_ez(id = "id", dv = "y", within = "group", data = longdat) # fit rm anova model
pairs(emmeans(afexMod, specs = "group"))  # compute marginal means, then compare pairwise
                                          # gives result of JASP, t = -2.868 
```

Kind regards
Johnny
