### ISSUE TITLE
Posterior and prior plot and BF for Bayes Linear Mixed

### ISSUE THREAD

**Issue by kornbrot** [jasp-stats/jasp-issues#968]
Output only shows effect and SE. Bayes plots would be very informative
* Enhancement: Please provide output in same format as for Bayes t-tests and Bayes ANOVA
* Purpose: clearer interpretation of results
* Use-case: clear results presentation
**Is your feature request related to a problem?  NO
**Describe the solution you'd like**
Outptut as Posterior and prior plot and BF 
**Describe alternatives you've considered**
R but currently won't compile Rstan on  Mac Catalina so is unusable

**Comment by tomtomme** [comment]
This is tracked here: https://github.com/jasp-stats/jasp-issues/issues/845
