### ISSUE TITLE
A wish: Confirmatory Factor Analysis

### ISSUE THREAD

**Issue by mozny** [jasp-stats/jasp-issues#97]
* Enhancement: Confirmatory Factor Analysis
* Purpose: It is used to test whether measures of a construct are consistent with a researcher's understanding of the nature of that construct (or factor). As such, the objective of confirmatory factor analysis is to test whether the data fit a hypothesized measurement model. This hypothesized model is based on theory and/or previous analytic research.
In confirmatory factor analysis, the researcher first develops a hypothesis about what factors he believes are underlying the measures he has used
Details e.g. here:
https://en.wikipedia.org/wiki/Confirmatory_factor_analysis

**Comment by vankesteren** [comment]
As of JASP 0.10, we have CFA!
