### ISSUE TITLE
Add description to features in WIX installer

### ISSUE THREAD

**Issue by JorisGoosen** [jasp-stats/jasp-issues#971]
In the issue at https://github.com/jasp-stats/jasp-issues/issues/861 I used the WIX_Advanced UI to add a selection for per-user and per-machine installs. This works.

However, the feature selection dialog doesn't support description and the very reasonable request was made to add this. I agree and I want to but to do so requires me to rewrite that particular dialog and smash it in there.

This is a bit much as we want to start testing for a release soon.
So I want to postpone it a bit and include the following:

- Add description to features
- Remove the superfluous "license agreement" dialog (and just start with the per-user and per-machine choice)
- Make sure it installs to `C:\Program files\` for 64bit as opposed to `C:\Program Files (x86)\`

**Comment by JorisGoosen** [comment]
Maybe I should just adapt the libreoffice wxs/installer because it is an msi and does basically what we want.

**Comment by tomtomme** [comment]
@JorisGoosen 
Isn't this solved now by the move to MSIX?

**Comment by JorisGoosen** [comment]
yes
