### ISSUE TITLE
spreadsheet editor wont open

### ISSUE THREAD

**Issue by jaspishurtingmybrain** [jasp-stats/jasp-issues#972]
* JASP version: 0.13.1

* OS name and version:  MacOS Mojave 10.14.6
* Analysis: 
* Bug description:  spreadsheet editor won't open when trying to edit data.  opens new window of Jasp instead of opening excel 
* Expected behaviour: double click a cell and excel opens in order to edit data
#### Steps to reproduce:
1. double click a cell
2.instead of excel or preferred spreadsheet editor opening a new window of Jsp opens instead

**Comment by boutinb** [comment]
Hi @jaspishurtingmybrain , what are your Spreadsheet Editor settings in Preferences/Data?

**Comment by JorisGoosen** [comment]
Maybe JASP has been set as the default editor for csv/sav/??? files?
