### ISSUE TITLE
JASP not syncing after changes in csv (win7) - encoding related

### ISSUE THREAD

**Issue by varhelyiklara** [jasp-stats/jasp-issues#975]
* JASP version: 0.13.1
* OS name and version: Windows 7 (64bit)
* Spreadsheet editor: Microsoft Excel 2016
* Analysis: synchronizing data

* Bug description: 
JASP opens the CSV file (saved from Excel) without problem. But when we try to edit the data (double click on it in JASP - it opens the data in Excel - we make the changes needed - save in Excel - sync in JASP), JASP does not synchronize it. It just says: Synchronizing data...  and nothing happens.

We tried 1) the automatic synchronization. 2) forcing sync typing CTRL-Y. 3) forcing sync thought Sync data / Current and 4) Sync Data / Browse. 5) saving the CSV with another name, and Opening it in JASP, but we can't see the changes in the data.

If we change the preferred spreadsheet editor to Wordpad, and do all the step listed above, the error remains.

Sometimes, when the change is minor in the data (e.g. changing only one value) the sync works just fine, but with "major" changes like sorting data, it never synchronize it.

I know that Win7 is quite old, but I'm teaching statistics in JASP and some of my students still has this operation system, and this bug makes learning statistics and JASP quite hard for them.

Thank you in advance for looking into this problem!
Klara

**Comment by varhelyiklara** [comment]
I want to give an update on the situation.

It turned out that the error in synchronization is present not only in Windows 7 but in Windows 10 as well. Several of my students has reported the same bug from different operation systems.

Now, we have a strong guess that the cause of the problem is the use of accented characters. In our language (Hungarian) we use a lot of accented characters, like á é ö ü ó ő ú ű í. In the 0.13.1 version of JASP I notices that these characters appear correctly in the results tables (in v0.12 they did not work), but it seems they still cause a lot of problems in JASP.

**Comment by boutinb** [comment]
@varhelyiklara Could you send me a csv file where you get this problem?

**Comment by varhelyiklara** [comment]
[stathelp_JASPBev_bsciadatok_02_NYERS.zip](https://github.com/jasp-stats/jasp-issues/files/5249100/stathelp_JASPBev_bsciadatok_02_NYERS.zip)

Thank you for looking into this!

There are two parts of this error
1) the bigger issue is the error of sync 2) the smaller one is that JASP did not displays accented characters in variable names correctly in the data interface and in the results.

Out of my students, 6 persons use Win7 - all of them experienced both problems.
The students who use Win10 - approx. 20% experienced the error in display but none of them met the problem of sync.

Furthermore the students with Win7 use different types of Excels (Excel 2013 and Excel2016) and they said that they do not have the option to save file into CSV UTF-8 instead tried all other versions of CSV available in their Excel but none of them worked.

**Comment by varhelyiklara** [comment]
One more update:
In my previous message, I wrote that only win7 systems are affected. Since then some of my students with win10 also reported the bug in sync.

(I'm so sorry for the inconsistencies in my updates, my students were trying out JASP in these two weeks and it continuously changes what I know about this issue as they write to me about the problems they encountered using JASP)

**Comment by boutinb** [comment]
Hi @varhelyiklara I have already one explanation about the problem with the accented characters: Excel has the bad habit to transform files written with UTF8 encoding to an ANSI encoding. So when you save the file, you have to be careful to choose Save As with the right format. Depending of the Excel version, you have CSV (UTF8), which is fine. On my PC, I have only Text format (Unicode), that transforms the file first in a tab separated file, and that works also.
Could you try that already?

**Comment by boutinb** [comment]
Hi @varhelyiklara Did you try the UTF8 setting in Excel?

**Comment by varhelyiklara** [comment]
Hi @boutinb 
Thank you for asking about the progress. Sorry for the delay, I myself did not experience this bug so I had to ask my students about it and it took some time to collect the answers from them.
I think you are right and the source of the problem is the encoding used by Excel. Those, who have and Excel with the ability to save CSV with UTF-8 encoding, did not experience the bug. I asked the others to use Text format, as you suggested, and while the working format was quite diverse, everyone found a solution to the problem.
Thank you for your help!

**Comment by boutinb** [comment]
Hi @varhelyiklara 
Nice to hear that it solves your problems. But maybe we could do something to at least warn the users when the data file is not in UTF-8 encoding, and that some characters cannot be read.
I will have a look.

**Comment by varhelyiklara** [comment]
Thank you! Although it is worth warning users about the possibly strange appearance of accented characters, we did not find the problem so severe (I think, those whose native language contains special characters, have long been accustomed to such inconveniences). 
It would be more important to point out that these accented characters can cause problems during synchronization.

**Comment by JorisGoosen** [comment]
This issue would also help people in more "exotic" locales. For instance, a chinese csv encoded in the local codepage looks like a big mess and breaks stuff.

[ChineseCodepageCSVSample.zip](https://github.com/jasp-stats/jasp-issues/files/5830119/ChineseCodepageCSVSample.zip)

So if it *is possible* to detect the csv is not in utf-8 (or utf16/32 because the code seems prepared for that) then it would be even better to do the conversion to utf-8 ourselves.
Or at least give a warning, because more things can break than just synching.

**Comment by JorisGoosen** [comment]
Also related to: https://github.com/jasp-stats/jasp-issues/issues/232

**Comment by JorisGoosen** [comment]
I've tested it and this problem will be fixed in 0.15
