### ISSUE TITLE
Jasp data import from Calc

### ISSUE THREAD

**Issue by lucy-faure** [jasp-stats/jasp-issues#976]
JASP version: 0.13.1.0
* OS name and version: Windows 10 company

![Photo des colonnes problématiques sur Jasp](https://user-images.githubusercontent.com/71496592/93613420-22781e80-f9d1-11ea-9530-927fefaf177b.PNG)

Bug description:

Hello, I've created an online questionnaire using a Jalios questionnaire module. In it, I have questions for which the participant may have put several answers. I have extracted the data table of the results in cvs format. I believe that all the fields are separated by tabs. When I open it in Calc, multiple answers to the same question are grouped together in the same cell. When I try to open the database on Jasp, I have all the participants' answers overlapping in the cells where there are multiple answers. It's unreadable. However, in the csv spreadsheet, everything appears normally.

I've tried saving the file with a new name, but it doesn't change anything. I tried to save it with an odt format but I only see the first answer given by the participants in the cells where there are several as soon as I put the file on Jasp.

**Comment by boutinb** [comment]
JASP is not suited to display a cell with a lot of text inside. But the question is why you would do that? This cell cannot be used like that in an analyse anyway: it must be first parsed. For example the question 'Quels outils..' could be transposed to have as many columns as possible answer, and just a boolean yes/no as result. This transformation of your data must be first done before using JASP.

**Comment by lucy-faure** [comment]
Indeed, that's also what I thought when I thought about it at length. Thank you for taking the time to answer me !
