### ISSUE TITLE
Jasp doesn't run

### ISSUE THREAD

**Issue by VRossier** [jasp-stats/jasp-issues#977]
Hello, 

I've got a problem with Jasp. 
I use a PC with Windows 7, 64 bits. I downloaded the 64 bit version of Jasp 0.13.1 and installed it. 

When I try to make it run, my PC seems to try during 2 ou 3 seconds (the mouse curser turns around) then nothing happens. There isn't even any window that opens. 

I tried to uninstall and install again many times, and to restart my PC, but nothing works. 

Do you have any idea about where this problem come from ? 

Thank you so much for your help.
Best regards

Virginie

**Comment by boutinb** [comment]
Hello Virginie,
That is really annoying...
Would it be possible to start a Command Prompt (Type cmd in the Search field), and type the following:
`"c:\Program Files\JASP\JASP.exe" > log.txt`
Then send me the log.txt file (in zip format)?

**Comment by VRossier** [comment]
Hello, 
Thank you for your answer. 
I tried to type this command in cmd and it's doing exactly the same : my mouse curser turns and nothing happen. 
I tried to type this command with an other programm to see what should happen and it works with this other programm : it opens directly after the command. 

I've got a new information to add : I tried every version of Jasp form the most recent to the ancient one. The version 0.9.2.0-64-bit and the previous ones work but not the more recent ones. 

Thank you for your help. 

Virginie

**Comment by JorisGoosen** [comment]
@VRossier could you instead of the previous advice by my esteemed colleague try to start JASP as following: `C:\Program Files\JASP\JASP.exe --logToFile`

Then you can find some logfiles in (supposing your username is "VRossier") `C:\Users\VRossier\AppData\Roaming\JASP\JASP\Logs`

If you could zip all of those and attach them here that would be incredibly helpful.

**Comment by VRossier** [comment]
Hello, 

Thank you for the advice. I tried it. 

The first proposition gave me this message : **"C:\Program" n'est pas reconnu en tant que commande interne ou externe, un programme exécutable ou un fichier de commandes**
_C:\Program" is not recognized as an internal or external command, executable program or command file._


The second try gave me this message : **Le chemin d'accès spécifié est introuvable**

Sorry for the french and the "DeepL traduction" ;)
_The specified path cannot be found._

Virginie

**Comment by JorisGoosen** [comment]
Aah, yeah that is my fault, excusez moi! (Also for my french ;))

If you could open the command-prompt and try out:
`"C:\Program Files\JASP\JASP.exe" --logToFile`
And If that fails:
`"C:\Program Files (x86)\JASP\JASP.exe" --logToFile`

**Comment by boutinb** [comment]
Hi @VRossier ,
What is your username on your PC? Is there a space or an accent like é or è?

**Comment by VRossier** [comment]
Good evening,

There is no space nore accent in my username (FitsyTosh).

I tried to the last command but each time I had the _"Le chemin d'accès spécifié est introuvable."_ message.

**Comment by JorisGoosen** [comment]
Well, it is too bad that JASP won't start the way we are specifying it.
I guess we should first make sure we are in the right directory.

Where did you install JASP?
We are guessing it is either in "C:\Program Files\JASP" or "C:\Program Files (x86)\JASP" but it would be good to be sure.

Once we know which directory it is in we can test something else.

Suppose your JASP is installed in "C:\Program Files\JASP", then perhaps you could try the following in CMD-prompt:
```
cd C:\Program Files\JASP
JASP.exe --logToFile --safeGraphics
```

**Comment by VRossier** [comment]
Jasp is installed in C:\Program Files\JASP\JASP.exe on my computer.

When I do the last command you wrote, after having written the first line and pressed enter, instead of 
_C:\users\Fitsy_
it is written 
_C:\Program Files\JASP_

But then I write _JASP.exe --logToFile --safeGraphics_ and it doesn't do anything.

**Comment by boutinb** [comment]
Do you see some log files in C:\Users\FitsyTosh\AppData\Roaming\JASP\JASP\Logs
or in C:\Users\Fitsy\AppData\Roaming\JASP\JASP\Logs

**Comment by VRossier** [comment]
No, when I put this file name in my computer, it say that "Window doesn't manage to find "C:\Users\Fitsy\AppData\Roaming\JASP\JASP\Logs"

But I found a .txt file in an other document book and it says : 
_Setting special options for software rendering (aka safe graphics).
Making new argument list for Application startup: c:\Program Files\JASP\JASP.exe --disable-gpu
Starting JASP_

**Comment by JorisGoosen** [comment]
What is this file called?

**Comment by VRossier** [comment]
It is called just log.txt and it is located in _C:\Users\Fitsy_ directly.

**Comment by JorisGoosen** [comment]
Aah yeah, that is the file that you made with Bruno's advice from: https://github.com/jasp-stats/jasp-issues/issues/977#issuecomment-696770490

And apparently it is running in safe graphics mode already, and crashes very quickly...

Hmm, maybe you could try out the beta-version of the new release we are working on: https://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-stable-711c3bb44e548d6bcefb93e8aabd7db9e45117a1.msi

**Comment by VRossier** [comment]
Thank you. But it doesn't work neither. 

I probably could make it with the 0.9.2.0 version but the point is: I will have to teach some psychologist students to do statistics with Jasp and I fear two different things : 
- The differences that there could be between what I show them with my computer and what they have on their own computers with the newest version. 
- The fact that some students may not be able to use the last version, just like me.

Is there lot of differences between the two versions ? Graphically and in the content ? 

Thank you for your answer !

Virginie

**Comment by JorisGoosen** [comment]
Hmm, this is too bad. I think it would be good to figure out what could be going wrong on your system because it seems there is something so wrong JASP cannot even give us useful info about it. For this we can make a special version that tells us way more, that way we can see at what point it breaks on your computer.

I would honestly counsel against using the 0.9.2 version. Not only have we completely rewritten the entire interface, most analyses have in fact also been updated, expanded and sometimes rewritten. Also many bugs have been fixed since, also some statistical ones. 

On the other hand, it will of course be better than nothing.

Much better than nothing would be making sure it also works on your computer of course!

**Comment by JorisGoosen** [comment]
So I've made a new version of our development JASP: http://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-stable-f0250e8611db1cce9fdb0bebd0147717ef35c5ab.msi

If you, @VRossier, could install this one and start it like: `"c:\Program Files\JASP\JASP.exe" > log_extra.txt`
And then attach that "log_extra.txt" file here we can see if we can pinpoint the problem.

**Comment by VRossier** [comment]
Hello, 

Thank you for having made this new version.
Here is the log-extra.txt file in attachment.

Virginie
[log_extra.txt](https://github.com/jasp-stats/jasp-issues/files/5292239/log_extra.txt)

**Comment by JorisGoosen** [comment]
Hello Virginie, thank you for testing it!

I've made another version that logs even more: https://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-stable-8573ce8ba8db807294e901bd7957bbd9148d4b9d.msi

If you could run that again as: 
`"c:\Program Files\JASP\JASP.exe" > log_extra.txt`

And, if this time some log files have appeared in either `C:\Users\FitsyTosh\AppData\Roaming\JASP\JASP\Logs`
or in `C:\Users\Fitsy\AppData\Roaming\JASP\JASP\Logs` it would be nice if these could be attached as well. But I am afraid that won't be the case.

**Comment by VRossier** [comment]
Hello, 

Here is the new file _log extra.txt_

Ps : I don't have any file named "AppData". These files .txt appear directly in c:\Users\Fitsy


[log_extra.txt](https://github.com/jasp-stats/jasp-issues/files/5299656/log_extra.txt)

**Comment by JorisGoosen** [comment]
Aah, and this is with the newly installed version?

Hmm...

The "AppData" folder is hidden by default, if you go to the "View" tab in explorer you can select "Hidden Items" like so:
![image](https://user-images.githubusercontent.com/29062713/94578775-65ab7a80-0278-11eb-953d-bd414b5811f8.png)

**Comment by VRossier** [comment]
Yes, it's with the last version. 

I found this folder : "C:\Users\Fitsy\AppData\Roaming" but there isn't any Jasp folder in it...
Does the problem come from there ?

**Comment by JorisGoosen** [comment]
No it seems JASP crashes before it even starts making those logs..

But that is pinpointing the problem a bit, I'll see if I can make an even more specific version of JASP.

**Comment by JorisGoosen** [comment]
Hello @VRossier

I've created another version that should make it clear at which part JASP breaks during startup: http://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-stable-195c688b1c157b562b56cd032235612e42a62238.msi

Would you be so kind as to try it out?
Narrowing down where the problem occurs would still be quite helpful of course and I hope we haven't bored you to death yet with all these attempts...

Me and @boutinb were also thinking that maybe he could contact you through Zoom or something to see if maybe we are missing something?

**Comment by VRossier** [comment]
No, on the contrary, thank you to take so much time trying to solve the problem !

So I installed the new version and it's the same : it doesn't start. I did the same command in cmd than last time and it seems that you could have more information this time in the log file...

I attach it here. 
[log_extra.txt](https://github.com/jasp-stats/jasp-issues/files/5318918/log_extra.txt)

**Comment by JorisGoosen** [comment]
Thank you for running it again!
And at least now I know for sure where it crashes, although that still doesn't help us..

We'll get to the bottom of it eventually though!

Could you download http://www.dependencywalker.com/depends22_x64.zip 
And run the dependency walker on `JASP.exe` ? 
It should give you a lot of computer-mumbo-jumbo and if you could save that to a `*.dwi` file and attach that here we can see if maybe JASP is loading the wrong DLL at some point.

**Comment by VRossier** [comment]
Hello, 
I hope I did right because I never used this kind of programm before. I attach here the .dwi file. 
Good luck ! ;)
[JASP.zip](https://github.com/jasp-stats/jasp-issues/files/5334136/JASP.zip)

**Comment by JorisGoosen** [comment]
Well, you did it perfectly alright!

This is exactly what I wanted, only problem is is that it doesn't seem to explain what went wrong. So the problem might lie somewhere else still...

I'll confer with @boutinb on what else could be the problem.

**Comment by boutinb** [comment]
@VRossier One thing that could cause your problem, is that you are using Windows 7. Windows 7 is not supported anymore by Microsoft since January this year, and so do not send minor upgrade to fix bugs or security issues. So we will also not support Windows 7 anymore.
This crash might be related to a missing fix in Windows self.
Can you upgrade to Windows 10?

**Comment by JorisGoosen** [comment]
I would like to add to this point that it is, in general, a good point to move away from windows 7 to windows 10.
Especially now that it isn't even supported by Microsoft anymore, it will just make it that much more likely that you will run into other problems (other software, bugs, malware and the likes).

**Comment by VRossier** [comment]
Thank you for your last advices. I thought that it could be linked to the oldness of my computer but I still had hope that I could keep it some few years more because it still works for everything else.

I will see to change for Windows 10 and see if it solves the problem. 

In the meanwhile, do you think that I can use the basic online version or is there lot of differences between it and the "installed on computer" version of Jasp 0.13.1 ?

Thank you again for having tried so strong :+1: 

Virginie

**Comment by boutinb** [comment]
We want to ask RollApp to update their JASP version. It is now on 0.9, quite old.
What you can try also is to install JASP 0.12 or 0.11 from our site. Maybe they can still run on Windows 7.
But I would really try to upgrade to Windows 10: as said Joris, you will get surely other problems soon, because some applications won't be able to run anymore. And maybe more important, Microsoft does not send security fixes for Windows 7, making your PC quite vulnerable.

**Comment by JorisGoosen** [comment]
@boutinb Virginie already tried those versions, they don't work.

I will soon try to update JASP so that we can get it on RollApp so that should be an option again after this release.

**Comment by VRossier** [comment]
Hello, 

It's me again. :)
So, I turned into Windows 10 and... yes it finaly works with Jasp's last version ! At least, I will know what to advice to my future students if they are in my case !!! And now, you know that this bug was effectively caused by the Windows version. 

The sad point is that my computer became really slower (I suppose that Windows 10 is heavier than Windows 7) and I think I will finaly be forced to change it. 

Anyway, thank you again for all you tried to help me. 

Best regards, 

Virginie

**Comment by JorisGoosen** [comment]
Glad to hear you can at least use JASP now!

An advice if you do not want to change your computer, you can also install Linux on it.
It can be much lighter than windows and JASP runs on it as well ;)

In any case, you're welcome!

Best regards,
Joris
