### ISSUE TITLE
Bayesian correlation matrix: Issue of Bayesian correlation matrix plot

### ISSUE THREAD

**Issue by Golden-Retriever-1** [jasp-stats/jasp-issues#978]
* JASP version: 0.13.1

* OS name and version: macOS Catalina 10.15.6
* Analysis: 
* Bug description: Regression --> Bayesian correlation 
* Expected behaviour: Getting results in the area of plots --> correlation matrix, densities for variables, posteriors under H1

#### Steps to reproduce:
1. Go to 'Bayesian correlation'
2. Click on 'Additional options --> Select all' & 'Plots --> Select all'
3. Scroll down to 'Bayesian correlation matrix plot'
4. See error "too many open devices"

Comment on the data: I have analysed 9 items (scale) of 10 participants. There are no missing values.
![image](https://user-images.githubusercontent.com/60108165/93663349-97963300-fa67-11ea-8691-cd1080c05464.png)

**Comment by boutinb** [comment]
Could you send us the JASP file or the data (in a zipped format)?

**Comment by boutinb** [comment]
If you want to send safely the data, send it directly to me: b.boutinATuva.nl

**Comment by Golden-Retriever-1** [comment]
Is the data file for sure required to solve the issue? It is not even a huge data file – there is nothing special about the data which is why I do not like to forward it. I am never keen on giving anyone my research data. Sorry, but this is just a general caution regarding data security.

**Comment by vandenman** [comment]
@Golden-Retriever-1 there is no need to share the data if the issue is not specific to the data (i.e., you can reproduce it with other data sets). However, very often a jasp file provides us with more information than what is posted in an issue. For example, I could not replicate the issue on Ubuntu 18.04. Maybe the issue is specific to macOS?

It's perfectly fine if you don't want to share the data. However, if you could reproduce the issue with our [debug data set](https://github.com/jasp-stats/jasp-desktop/blob/stable/Resources/Data%20Sets/debug.csv) that'd be great.

**Comment by Golden-Retriever-1** [comment]
Thank you very much. This is of interest: Does JASP provide the possibility to generate and retrieve a log-file which I could forward to you?

**Comment by vandenman** [comment]
In the menu, go to `Preferences` -> `Advanced` -> `Logging options`.

![image](https://user-images.githubusercontent.com/21319932/93915686-ae0ee980-fd08-11ea-800a-313afcd5b6f8.png)

If you open the log directory there will be one log for the desktop and one for each engine you have running (usually 4 if I remember correctly):

![image](https://user-images.githubusercontent.com/21319932/93915945-0fcf5380-fd09-11ea-84dc-227fff5092c0.png)

The log files are just .txt files so you can open them with any text editor. They may contain column names of the data set so if you're very keen on not sharing those you may want to edit the file before sending it.
