### ISSUE TITLE
Feature request: Bayesian correlation matrix – nice to add: a tabular Bayesian correlation matrix

### ISSUE THREAD

**Issue by Golden-Retriever-1** [jasp-stats/jasp-issues#979]
* Enhancement: Adding a tabular Bayesian correlation matrix to the analyses options
* Purpose: Showing a tabular correlation matrix of Bayesian correlations to the users as the users knows the tabular format from their statistics lectures, text books, etc.
* Use-case: Several in data analysis. Tabular correlation matrices give the user a very good overview over pairs of correlations.

**Is your feature request related to a problem? Please describe.**
 It eases data analysis and data exploration when using Bayesian correlation matrices in general. It is a well-known format and is currently not available for Bayesian correlations.

**Describe the solution you'd like**
 The variables on the rows and columns of a correlation matrix as usual. Inside the cells several parameters can be displayed per correlation matrix such as Pearson's r  with the BF below, and the lower and upper 95% interval below. I am sure it is easy to find a way to display a Bayesian tabular correlation matrix.

**Describe alternatives you've considered**
 There is currently no alternative in JASP to display a Bayesian correlation matrix. The plain and bare tabular format which is no matrix is good but does not support visual analyses. The format of the correlation matrix as value-based result is missing.

**Additional context**

**Comment by boutinb** [comment]
@EJWagenmakers What do you think?

**Comment by Golden-Retriever-1** [comment]
Dear all,

I am glad about your answer. I have to add this just for formality reasons. Can I be sure that the research data remain confidential? 

Kind regards,
Daniela
__________________________________________________________
 
Dr. rer. nat. Daniela Schmid | Human Factors scientist and psychologist | Germany
daniela.schmid64@icloud.com

**Comment by EJWagenmakers** [comment]
1. Yes we do not collect any data (see also our FAQ online)
2. "The variables on the rows and columns of a correlation matrix as usual. Inside the cells several parameters can be displayed per correlation matrix such as Pearson's r with the BF below, and the lower and upper 95% interval below. I am sure it is easy to find a way to display a Bayesian tabular correlation matrix." -> this is exactly what we have now. See screenshot. Please re-open if I did not understand your request properly.

![image](https://user-images.githubusercontent.com/8603015/93904983-bbbd7280-fcfa-11ea-940d-b69e296b93e9.png)

**Comment by Golden-Retriever-1** [comment]
Dear all,

This is not what I was asking for.

I was asking for a correlation matrix as used to in factor analyses and PCA:

Item 1 Item 2 Item 3 Item 4
Item 2
Item 3
Item 4

Kind regards,
Daniela
