### ISSUE TITLE
Delete key and keyboard navigation

### ISSUE THREAD

**Issue by lindeloev** [jasp-stats/jasp-issues#98]
I find myself repeatedly trying to delete selected results using the delete key. Similarly, I also press delete to remove selected variables in an analysis. As a user experience, JASP feels slightly unfinished or unresponsive when this doesn't work. It's not a major problem but it would be a nice polish.

Keyboard navigation works great for the selection of variables, but it would be nice if the "move variable to..." arrow was highlighted when it's selected via the TAB key. Currently, only mouse-over highlights it on Ubuntu 16.04 (JASP 8.3).

Congratulations on releasing 8.3! I'm impressed with the fast-paced development.

**Comment by tomtomme** [comment]
This works now: "move variable to..." arrow highlight when selected the TAB key
And instead of delete key you can use SPACE to move variables.

So this issue could be closed.
