### ISSUE TITLE
Error in the three-way Bayesian repeated measures ANOVA: undefined columns selected

### ISSUE THREAD

**Issue by mengsili** [jasp-stats/jasp-issues#982]
* JASP version: 0.13.1.0-64bit for Windows

* OS name and version: WIN10
* Analysis: Three-way Bayesian repeated measures ANOVA
* Bug description: 
I was doing a 4 x 4 x 3 three-way Bayesian repeated-measures ANOVA. The Bayes factors could be calculated normally, but when I tried to add the descriptive results or the post-hoc tests, the following error showed up.
![image](https://user-images.githubusercontent.com/69629203/93687017-5144d200-fa6f-11ea-8755-be6913020dfc.png)

I noticed there was one similar issue reported one year ago.
#506 (comment)
* Expected behaviour: results of descriptives or the post-hoc tests should appear. 

#### Steps to reproduce:
1. Go to 'Bayesian Repeated Measures ANOVA'
2. Specify three Repeated Measures Factors "IT" (4 levels: IT1, IT2, IT3, IT4), Region (4 levels: F, C, P, O), & Hemisphere (L, M, R)
3. Insert the variables respectively into 'Repeated Measures Cells'. It should already be in order.
4. Click on "descriptives" or post-hoc tests. 
5. See error

[FN400.zip](https://github.com/jasp-stats/jasp-issues/files/5250484/FN400.zip)

**Comment by bentoovey** [comment]
I had this same error and signed up to reply here. I don't have a code fix, but it seems to be related to the length of your factor names/level names that you write in the cells. 

For example, if i set my 2x2 factor names as "t" and "c" instead of "task" and "category", then the descriptive output fails. With longer names ("tas" and "cat", for example), the descriptives are output correctly.

**Comment by JohnnyDoorn** [comment]
Hi @Lumossssss and  @bentoovey ,

Yes, unfortunately we are still working on a functional way to internally handle factor level names in a way that makes everything work. This means that some names for levels will cause crashes. In the meantime, I can recommend bentoovey's advice, and make the level names a bit longer. Our apologies for this confusion.

Kind regards
Johnny

**Comment by Lumossssss** [comment]
@JohnnyDoorn @bentoovey 
Thanks Johnny & bentoovey. I will try renaming the factors.

**Comment by tomtomme** [comment]
I downloaded the file and renamed the factors to at least 3 characters. This still does not solve the problem with 0.18.3. There is no crash, but the progress bar does not move - the computation never finishes.

**Comment by JohnnyDoorn** [comment]
Hmm yes this seems to be a different issue, and I can replicate it (it happens with both short and long level names). There are also not so many data points, or model terms, so I am not sure what is going on here.. @boutinb or @vandenman do you have an idea?
