### ISSUE TITLE
Confidence Level Not Showing for Cronbach's Alpha

### ISSUE THREAD

**Issue by sharmajee499** [jasp-stats/jasp-issues#983]
* JASP version: 0.13.1

* OS name and version: Windows 10 
* Analysis: Reliability Analysis
* Bug description: The reliability Analysis part is not showing the Confidence Level for Cronbach's Alpha part. 
* Expected behaviour: To show the confidence level for cronbach alpha.
![issue_JASP](https://user-images.githubusercontent.com/33268514/93693156-985bb300-fac1-11ea-9c5e-639178615e89.jpg)

**Comment by juliuspf** [comment]
Duplicate of https://github.com/jasp-stats/jasp-issues/issues/888

**Comment by juliuspf** [comment]
The latest nightlies fix this issue (https://static.jasp-stats.org/Nightlies/). For the official release, you have to wait for 0.14 unfortunately :(

**Comment by sharmajee499** [comment]
Thank you so much
