### ISSUE TITLE
EFA and CFA not allowing variables to be added

### ISSUE THREAD

**Issue by audraq** [jasp-stats/jasp-issues#984]
* JASP version: 0.13.1

* OS name and version: Catalina 10.15.4
* Analysis: EFA and CFA
* Bug description: After successfully uploading data, the EFA and CFA sections do not allow me to add variables. I cannot drag them over or use the arrow button (it is greyed out).
[CleanedSatisFromR-updated 9-21-20.csv.zip](https://github.com/jasp-stats/jasp-issues/files/5254828/CleanedSatisFromR-updated.9-21-20.csv.zip)
 I have used this same data before using this program. Also, other analyses allow me to add the variables (such as Reliability)
* Expected behaviour: In the past I have had no problem dragging and dropping variables over, or using the arrow button to add variables. 
--->

**Comment by boutinb** [comment]
This is quite strange... I cannot reproduce it even with your data... Just to be sure: only scale data are allowed to be added.
Can you send me a screenshot of how it looks like?

**Comment by audraq** [comment]
Hi Bruno!
It does seem to be that the problem is with ordinal variables. I was able to add the continuous variables. Not sure if this captures it, but screen shots are included below. Thanks in advance for any assistance you can offer!

[A screenshot of a cell phone  Description automatically generated][A screenshot of a cell phone  Description automatically generated]

**Comment by boutinb** [comment]
Hi @audraq I don't see the screenshot. But as I said, only scale data cab be added in the Variables list, no ordinal. The type of the columns is guessed by JASP when you load the csv file. But you can still change this type on clicking on the type icon at the top of the column in the data panel:
<img width="357" alt="Screen Shot 2020-09-24 at 08 36 02" src="https://user-images.githubusercontent.com/503332/94109305-106b0580-fe41-11ea-9261-a10ba1126991.png">

**Comment by audraq** [comment]
Hi Bruno – Okay that worked! But it’s strange because I’ve used this same data many months ago doing the same thing and didn’t have to change the variables like that. Did something change? Regardless, thank you so very much for the assistance!! Greatly appreciate it.

**Comment by boutinb** [comment]
JASP makes just a guess about the types of the columns. If the values of one column are all integers, and have only 2 different values, then its type is set to nominal, if it has less than 10 different values (this threshold can be changed in preferences/data  by setting the 'Import threshold between Categorical or Scale' checkbox) then it is considered to be ordinal, otherwise it is a scale.
But as you saw, you can always change this type afterwards.

**Comment by audraq** [comment]
Hi again, Bruno- really sorry to bug you again, but I am so confused why I’m having another problem that didn’t happen last time I used JASP for this same analysis. When I try to use “Maximum Likelihood” as the estimation method, I get the following error: “Estimation failed. Internal error message: L-BFGS-B needs infinite values of ‘fn’ … see screenshot below. I had no problems using this same estimation method several months ago.
[cid:image001.png@01D69333.3CD6E5E0]

**Comment by boutinb** [comment]
Hi @audraq Can you use the GitHub Website to answer and to send files. If not, I cannot see the file.
