### ISSUE TITLE
Feature request: Bayesian correlation matrix – nice to add: a tabular Bayesian correlation matrix with specific example

### ISSUE THREAD

**Issue by Golden-Retriever-1** [jasp-stats/jasp-issues#986]
Adding a tabular Bayesian correlation matrix to the analyses options as used to from factor analyses and PCAs
* Enhancement: Visual analyses of a simple Bayesian correlation matrix made possible
* Purpose: Showing a tabular correlation matrix of Bayesian correlations to the users as the users knows the tabular format from their statistics lectures, text books, etc.
* Use-case:Several in data analysis. Tabular correlation matrices give the user a very good overview over pairs of correlations. 

Example
         Item 1  Item 2  Item 3  Item 4  Item 5  Item 6  Item 7  Item 8  Item 9
Item 1
Item 2
Item 3
Item 4
Item 5
Item 6
Item 7
Item 8
Item 9

**Is your feature request related to a problem? Please describe.**
 It eases data analysis and data exploration when using Bayesian correlation matrices in general. It is a well-known format and is currently not available for Bayesian correlations. 

**Describe the solution you'd like**
 The variables on the rows and columns of a correlation matrix as usual. Inside the cells several parameters can be displayed per correlation matrix such as Pearson's r with the BF below, and the lower and upper 95% interval below. I am sure it is easy to find a way to display a Bayesian tabular correlation matrix. 
Example
         Item 1  Item 2  Item 3  Item 4  Item 5  Item 6  Item 7  Item 8  Item 9
Item 1 
Item 2
Item 3
Item 4
Item 5               correlations in here
Item 6
Item 7
Item 8
Item 9

**Describe alternatives you've considered**
 There is currently no alternative in JASP to display a Bayesian correlation matrix for only this purpose. The plain and bare tabular format which is no matrix is good but does not support visual analyses. The format of the correlation matrix as value-based result is missing. 

**Additional context**

**Comment by boutinb** [comment]
@vandenman what do you think about this request?

**Comment by vandenman** [comment]
@Golden-Retriever-1 I'm not sure how this is different from the current Bayesian correlation, could you provide another example?

Currently, we provide these two views of the correlation matrix:

![image](https://user-images.githubusercontent.com/21319932/94924230-700a8600-04bd-11eb-9e54-1d46e637e07b.png)

![image](https://user-images.githubusercontent.com/21319932/94924282-831d5600-04bd-11eb-8044-d396e4700507.png)

Would you like the Bayes factors to be removed from the top screenshot?

**Comment by Golden-Retriever-1** [comment]
It provides the standard layout format from textbooks and aggregates the information of one correlation in a lovely cell!

**Comment by vandenman** [comment]
something like this?

![image](https://user-images.githubusercontent.com/21319932/94936387-75240100-04ce-11eb-90e0-01a727877d47.png)

you can obtain something like that by unticking `Report Bayes factors`:

![image](https://user-images.githubusercontent.com/21319932/94937104-6e49be00-04cf-11eb-8ef3-bf1233a20d1e.png)

**Comment by Golden-Retriever-1** [comment]
It would be helpful to join the information for visual analysis, as eg correlation above, Bayes factor below in the format below.

Eg 

.60
3.567

**Comment by vandenman** [comment]
So how is your request different from this table?

![image](https://user-images.githubusercontent.com/21319932/94924230-700a8600-04bd-11eb-9e54-1d46e637e07b.png)

**Comment by Golden-Retriever-1** [comment]
Yes, it is. It keeps the structure for visual analyses that most know from their textbooks. In one cell, there is way to display more than one information by applying a structural approach. I am sure a key can help to read the table when adding more than the 2 suggested values.

**Comment by vandenman** [comment]
I'm afraid I don't understand what you mean, could you provide a screenshot or word/ excel table of how you'd the output to be arranged?

**Comment by Golden-Retriever-1** [comment]
Simply keeping the layout of the usual visual representation and aggregating the different values one above each other in the places of the table:

Instead of .70 as Pearson’s r 

You could write .70 as Pearson’s r above the value for the BF10 while keeping the visual structure which really most of the users are used to from their statistical textbooks. The current layout is user-unfriendly.

**Comment by AlexanderLyNL** [comment]
I think that what's requested is something that is implemented already. The last tweak seems to a bit of nuance difference and perhaps a difference in opinion regarding what's user-friendly. The current implementation allows users to only display the summary statistic without the Bayes factor, or only the Bayes factor, or both. I think it's reasonable to consider this issue solved.

**Comment by Golden-Retriever-1** [comment]
Your resistance to keeping unusual formats with a wide difference to textbooks! Enjoy.

**Comment by AlexanderLyNL** [comment]
I don’t see it as a matter of resistance, and I'm happy with the feedback. From what I gathered we’ve implemented exactly what you requested. A table with Pearson’s r above the Bayes factor can be requested as shown in

https://github.com/jasp-stats/jasp-issues/issues/986#issuecomment-703445379

**Comment by Golden-Retriever-1** [comment]
﻿I just really wonder about not using the usual textbook format which is why especially beginners and learners might have difficulties in reading the current outputs! No all are really proficient which all different types of aggregating data which is why I suggested it. I extra draw a sketch of it. The most easy programming solution is often not the best visual representation of tabular data.

It could look like this:

**Comment by vandenman** [comment]
@Golden-Retriever-1 could you use the GitHub website to show us what you have in mind? Your last post doesn't show any images in case you attached any:
![image](https://user-images.githubusercontent.com/21319932/95077517-e9031b00-0713-11eb-87a9-fbf32f0b097c.png)


We prefer not to use any unusual format and would be happy to implement your request if it's reasonable, but we are having a really hard time understanding what your feature request is about.

**Comment by Golden-Retriever-1** [comment]
Okay, I have answered via email maybe the picture file was not added.

**Comment by Golden-Retriever-1** [comment]
What about this link? I can later on upload the file to Github.

https://1drv.ms/u/s!AjVtS8ZiRDYiokhxlNn2QMIZGQ9n

**Comment by vandenman** [comment]
Thanks, that image came through. I'm also pasting it here for future reference:

![image](https://user-images.githubusercontent.com/21319932/95078271-27e5a080-0715-11eb-9934-dca664050a4e.png)

**Comment by Golden-Retriever-1** [comment]
Here is the complete scan via link. I am currently on mobile which is why I cannot access github at this time:

https://1drv.ms/u/s!AjVtS8ZiRDYiokwZ5Hw3rX1mLkiu

**Comment by tomtomme** [comment]
@Golden-Retriever-1 
As far as I can see, there is only one difference between JASP and your sketch. The legend or key as you call it is outside of the table in your sketch, instead of integrated into the table as in JASP. 
The JASP behaviour duplicates the legend multiple times. This could be considered a drawback. 

However, general advice for plots also say, that you always should include the legend / key within a plot, as near as possible to the data. This increases readability, because the eye does not have to jump such a large distance between legend and plot. This general advice is certainly applicable to tables as well. 
If you do not like the duplication of the legend/key, you can activate the pairwise table.

Thus I, as a stats teacher, would vote against an external legend / key, even if some textbooks show this differently.
