### ISSUE TITLE
JASP Plots looking strange

### ISSUE THREAD

**Issue by romanogino** [jasp-stats/jasp-issues#987]
* JASP version: 0.13.1

* OS name and version: Windows 10
* Analysis:  Very good software!!
* Bug description: Open file, then go to Descriptive/ activate variable and then Plot/ See errors in the letters are overlapping, the pie chart is not centered. Finally, when I tried to send my file here, this web page did not recognize the file type.
[PLEASE DELETE..txt](https://github.com/jasp-stats/jasp-issues/files/5264873/PLEASE.DELETE.txt)

* Expected behaviour:

**Comment by vandenman** [comment]
Hi @romanogino and thanks for the report! Unfortunately, GitHub only accepts zip files as attachments. You can upload images though (e.g., screenshots). Does your problem look somewhat like this?

![image](https://user-images.githubusercontent.com/21319932/93978952-0089ed80-fd7d-11ea-95e1-19d19226c79a.png)

**Comment by romanogino** [comment]
![2020-09-23_085413](https://user-images.githubusercontent.com/1270242/94022351-a0924780-fd7a-11ea-8027-a145a7b95978.jpg)
![2020-09-23_085447](https://user-images.githubusercontent.com/1270242/94022368-a6882880-fd7a-11ea-98aa-e56af1b2d56f.jpg)

The file is not mine, so I can not upload it, but there are two screen captured. I am using Likert scale, with spanish languague. I could send by email the file.

Best regards.

r.

**Comment by vandenman** [comment]
A solution for the first issue is resizing the figure. If you hover over the figure there a small triangle should appear in the bottom right. If you click it you can resize the figure.

For the second figure, I'm afraid that the only thing you can do right now to make the figure legible is to shortening or abbreviate the names of the categories.

Let me know if that solves the problem.

**Comment by romanogino** [comment]
Thanks for the advice. I will do it. I just reported the issue.
Best regards.
r.
