### ISSUE TITLE
First factor not showing up in meta-analysis

### ISSUE THREAD

**Issue by meterfiller** [jasp-stats/jasp-issues#989]
* JASP version: 0.13.1

* OS name and version: Windows 10, all updates as of Sept 29, 2020
* Analysis: Meta-Analysis
* Bug description: When I put a factor variable (with n=4 factors, for example) into my meta-analysis, it shows the coefficients for only n-1 factors. So for example when my factor has 4 levels, it shows me factor 2,3,4, but not 1. 
* Expected behaviour: When I've used JASP for meta with earlier versions (last time was 0.11), it showed the coefficients for all of my factors. I don't think anything has changes, and if I open an old analysis in JASP 0.13.1 it shows all the factors, but as soon as I start messing with the analysis, the first factor disappears again. 

#### JASP file and screenshot:
The JASP file is here: https://mega.nz/file/1RlzzCSA#yJ9P4DoWBRPLoFRRFW0mPgHKweL3QXoDkLI1XnHYyi8

Screenshot:
![Clipboard01](https://user-images.githubusercontent.com/15251706/94533506-ca170b80-0271-11eb-9de3-382aa767b716.jpg)

**Comment by boutinb** [comment]
@sophieberkhout Can you have a look also to this issue?

**Comment by raoelg** [comment]
Hi John,

You have turned off the intercept in the model, but this feature is purely intended to allow users to restrict the intercept to be zero. Your 'prompt' predictor has two levels ('work' and 'non-work') and is turned into a dummy variable in which the 'work' class is coded with a 1 and the rest with zero. Could that be the issue?

**Comment by dismukealex** [comment]
I'm having the same issue, but I have the intercept option turned on. My coefficients table just shows the intercept and then every category other than the first one. I can't figure out how to get it to include the first category of the factor in the table. help :(

**Comment by sophieberkhout** [comment]
Hi @dismukealex,

As Raoul said before, the factor variable is turned into dummy variables as is standard for regression models. The number of dummy variables is always the number of categories minus one, where the intercept is the coefficient for the reference category (the one category left out). You can read more about this here: https://www.metafor-project.org/doku.php/tips:models_with_or_without_intercept
