### ISSUE TITLE
Bayesian Generalised Linear Model (GZLM), for dependent data that include a binary outcome

### ISSUE THREAD

**Issue by MAALKAN** [jasp-stats/jasp-issues#994]
* Enhancement: Generalised Linear (GZLM) for binary logistic events/trials data.
* Purpose: Analysing binary data (with a fixed number of trials) where the DV is not normally distributed
* Use-case:  PhD Thesis

**Is your feature request related to a problem? Please describe.**
 
Yes. Instead of using a chi-square, SPSS gives the option to compute a GLZm for events/trials data.  I would like to use this feature in JASP because of the ability to also compute effect sizes and bayes factor for null results. In my case, I have a dependent variable which measures success (retrieving objects with the possibilty of getting none of the two discrete trials correct, one corrrect or both correct). 

**Describe the solution you'd like**
I would like to see this feature added so that the full analyses including effect sizes and BF can be generated using JASP. 

**Describe alternatives you've considered**
I have considered using a chi-sq or non-parametric alternative to a t-test but the most appropriate test for the data is  a GLZM binary logistic model.

**Additional context**
This particular test is increasingly used within biological statistics so would prove useful for more disciplines than just my own (developmental psychopathology)

**Comment by boutinb** [comment]
@EJWagenmakers What do you think about this request?

**Comment by EJWagenmakers** [comment]
We do have Bayesian GLMMs in JASP (under mixed models), just not with Bayes factors. This is definitely something we would like to add! 
E.J.

**Comment by tomtomme** [comment]
@MAALKAN 
It sounds like you were asking for Bayesian Logistic Regression, and this is implemented now, even with BFs!
Feel free to reopen, if I misunderstood!

If you wanted BFs in GLMMs, like suggested by EJ, this is tracked here: https://github.com/jasp-stats/jasp-issues/issues/845
