### ISSUE TITLE
Facilitate creating a bug report from JASP

### ISSUE THREAD

**Issue by ElJefito** [jasp-stats/jasp-issues#997]
Note: this whole report was automatically created by JASP when I went to close it after doing a (successful) analysis. If it's useful, great; otherwise please delete it.

* JASP version: 0.13.1
* OS name and version: Windows 10 (10.0)

* Analysis: 
* Bug description:
* Expected behaviour:

#### Steps to reproduce:

-----------------------------------------------------------------------

### Debug information:
**Engine # 0** process *crashed* and it's state is *initializing*.
**Engine # 1** process *crashed* and it's state is *initializing*.
**Engine # 2** process *crashed* and it's state is *idle*.
**Engine # 3** process *crashed* and it's state is *idle*.

[Commit used](https://github.com/jasp-stats/jasp-desktop/commit/d2d5d378a3ccb371eb6ea357352966b510c516a6)

**Comment by boutinb** [comment]
Hi @ElJefito Can you give more information about this crash. Ca you reproduce it? And if yes, what is the exact reproduction path? You can also set the 'Log to file' on (in Preferences/Advanced) and send us the generated log files.

**Comment by ElJefito** [comment]
Hello — please note that I did not originate the message. JASP did. JASP created the message automatically.

I just assumed that there must be something in the message that would be meaningful to a JASP systems person.

From memory, I had been using the Reliability (frequentist) module and it crashed, probably when I had asked JASP to save my work.

The issue is related to #999. I have had quite a bit of trouble running the Reliability module, especially when dealing with a dataset having more than 80 items. It has not been unusual for JASP to hang. When it does so I simply close JASP and that’s when the JASP system message will appear automatically.

----------------------------------------
Lertap5 <http://www.lertap5.com/> Support Desk
Fremantle, Western Australia
----------------------------------------
(Same time zone as Hong Kong)

**Comment by JorisGoosen** [comment]
@ElJefito I am the author of the code that generates this message, Ive noticed that a lot of people seem to find the "report button" a bit confusing, as in, they do not notice that they should enter a bit of info for us.

Do you think something like:
![image](https://user-images.githubusercontent.com/29062713/95333705-67df8b80-08ad-11eb-861c-8a058d1a52f4.png)
Would be clearer?

Is it for you?

**Comment by ElJefito** [comment]
Good morning Joris and JASP staff,

The sample error-reporting message you’ve sent is good, at least in my opinion.

My experience with Windows macOS is that when a crash of some sort appears there will be a message saying something like:

“Something has gone wrong. Click on the Send button to forward the system’s record of the crash to our developers, or click Cancel otherwise. (Note: if you elect to send the report, no personal information about you will be included.)”

And at times there will be the option to see what the crash report looks like. I sometimes have a look, and it’s a lot of gibberish, stuff that I can seldom understand.

It’s this sort of experience which has led me to assume that JASP is doing the same thing, that is, that JASP knows what I was doing at the time, and all I should do is simply forward the JASP message without having to look at it, just as I do when Windows or macOS crashes.

So, what it amounts to, from my point of view, is that I’m wrong. I should pay more attention when JASP has a crash or error message, and I will do that from here on. I’d like to help if I can as I see lots of good in JASP and the work you’re doing.

Now: JASP 0.14 is about ready? I ask because the message you send with sample error message has 0.14 at the top.

Regards from Western Australia where it’s now time for a second cup of morning coffee.

Larry Nelson
----------------------------------------
Lertap5 <http://www.lertap5.com/> Support Desk
Fremantle, Western Australia
----------------------------------------
(Same time zone as Hong Kong)

**Comment by JorisGoosen** [comment]
Hello Larry,

It is about time for my second cup as well, thanks for your feedback.

It seems that your behavior is entirely normal because we have seen many issues posted like that, but then without the thoughtful note at the top that you left. Which means you already paid more attention to it than most do.

And still it was unclear, so I think that expecting other users who are paying less attention to understand the weird format of markdown and knowing where to put info is a bit much. 

So I'll just let JASP ask directly to the user what they were doing, then add it directly in the generated report, that way pressing "Submit new issue" will be all that is necessary.

**Comment by tomtomme** [comment]
@ElJefito 
What do you think of the current "crash report behaviour" of JASP?
It sends you to the github-issue tracker I think. And then you need to register first, if you do not have an account.
